### ISSUE TITLE
Support language-specific API generation tools

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1007]
We should have the option to specify the language your project is written in, and then we will build an API reference for your language appropriately.

## Implementation

I imagine having a *Programming Language* option on project import, similar to the spoken language option already there. Then we would run the specific API tooling for that language, like Javadoc, JSDoc, GoDoc, PHPDoc, etc.

Hopefully we would add some RTD-skinning, and integration between the generated API doc, and the hand-written prose documentation.

**Comment by destroyerofbuilds** [comment]
I would like to see something like `EnvironmentBase` extended to support different build environments similar to how `Base` supports different build tools.

In my particular case I'm extending ReadTheDocs to support building documentation for Node-based projects, and I need to install Node and `npm` within the build directories, and add the binaries to the build user's `PATH`. Once that's complete I can use a custom builder that builds documentation using tools like `JSDoc`.

The work-around I'm putting together will involve hooking into `setup_environment` to run a Heroku buildpack for setting up a Node environment, in place of the Python and pip steps. Once that's complete, the build process should continue on to using the custom builder.

**Comment by agjohnson** [comment]
Part of this work is happening now, at https://github.com/rtfd/sphinx-autoapi

The second half of this work will be implementing the necessary bits that integrate with Read the Docs -- any sort of configuration that needs to pass through, etc.

**Comment by ericholscher** [comment]
Closing this, as it will be an AutoAPI feature, not something inside RTD itself.
