### ISSUE TITLE
Document recommended deployment scheme

### ISSUE THREAD

**Issue by vmalloc** [rtfd/readthedocs.org#1012]
I recently tried to install rtd in a local deployment, and couldn't find how to complete the deployment. Namely - how does rtd expect workers to be deployed? What is the celery broker that should be set up, and where? Are there more background-related elements needed (cron jobs?) etc.

It would be nice to have a small section in the installation docs describing the entire recommended deployment scheme.

**Comment by ericholscher** [comment]
If you would like to support docs around local installs, we would welcome the contribution. As it stands, we don't have time to officially support it.
