### ISSUE TITLE
Not creating rtd-builds directory after successful build

### ISSUE THREAD

**Issue by deejay1** [rtfd/readthedocs.org#1022]
After the build is completed without any errors no rtd-builds directory is being created with the completed files, the build ends only in:

> [11/Nov/2014 18:38:44] INFO [projects.utils:81] Running: '/srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/envs/latest/bin/sphinx-build -T  -b epub -D language=en . _build/epub ' [/srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/checkouts/latest/docs]
> [11/Nov/2014 18:38:45] INFO [projects.utils:81] Running: 'mv -f /srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/checkouts/latest/docs/_build/epub/foo-workshop.epub /srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/artifacts/latest/sphinx_epub/foo-bar-workshop.epub' [/srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/checkouts/latest]
> [11/Nov/2014 18:38:45] INFO [vcs_support.utils:92] Lock (foo-bar-workshop): Releasing
> [11/Nov/2014 18:38:46] INFO [projects.tasks:112] (Build) [foo-bar-workshop:] Build finished

So it results in a 404 error "/srv/rtd_app/readthedocs.org/user_builds/foo-bar-workshop/rtd-builds/latest/index.html" does not exist

Tried the master and staging branches. Any hints?

**Comment by shield007** [comment]
I'm also seeing this issue.

**Comment by domdinicola** [comment]
Me too... any update on this?

**Comment by gepoch** [comment]
Hey guys! Just dropping a note for anyone stuck on this. I ran into this same issue, but found a workaround.

Not sure how you're getting celery deployed , but you need to have the right redis queues configured in order for it to work properly.

When you start celery, specify the redis queues that it uses with -Q My systemd config for my celery worker is:

    [Unit]
    Description=ReadTheDocs Celery Worker
    Requires=redis.service
    Wants=readthedocs-gunicorn.service
    After=redis.service readthedocs-gunicorn.service

    [Service]
    User=rtd
    WorkingDirectory=/opt/readthedocs/readthedocs
    SyslogIdentifier=readthedocs
    PIDFile=/opt/readthedocs/celery.pid

    ExecStart=/usr/bin/python manage.py celery worker -Q celery,web -c 4 --pidfile=/opt/readthedocs/celery.pid

Hope that helps!

**Comment by domdinicola** [comment]
Ciao guys!

Have a look at your FILE_SYNCER setting!
I used to extend postgresql settings so:
FILE_SYNCER = 'privacy.backends.syncers.DoubleRemotePuller'

If is setted to 'privacy.backends.syncers.LocalSyncer' the folder should have been successfully created.

Please let me know!

**Comment by espdev** [comment]
@gepoch thank you! Recently I have updated my local RTD server and Celery broke. Thank you for your comment. I have changed run configuration for Celery and it works fine for me.

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
