### ISSUE TITLE
Intermittent failures during builds

### ISSUE THREAD

**Issue by hach-que** [rtfd/readthedocs.org#1028]
I keep getting build failures randomly when my documentation is built:

e.g. https://readthedocs.org/builds/protobuild/1864981/

There's no errors in the logs (other than "No setup.py, skipping install"), and the outcome is Failed (Status Code: 999).

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.

**Comment by ppikula** [comment]
Hi @ericholscher, we  started to observe this kind of intermittent failures.

recent fail: https://readthedocs.org/builds/mongooseim/3256523/

**Comment by ericholscher** [comment]
I believe this is a Django 1.8 upgrade issue, I have deployed something
that might fix it, and am monitoring the servers now.

On Wed, Aug 19, 2015 at 5:21 AM, Paweł Pikuła <notifications@github.com>
wrote:

> Hi @ericholscher <https://github.com/ericholscher>, we started to observe
> this kind of intermittent failures.
>
> recent fail: https://readthedocs.org/builds/mongooseim/3256523/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1028#issuecomment-132571523>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
