### ISSUE TITLE
Outdated setuptools

### ISSUE THREAD

**Issue by uppfinnarn** [rtfd/readthedocs.org#1029]
Looks like documentation is built with setuptools 1.1 installed, which fails to install some packages which require newer versions.

Updating is as simple as running `easy_install -U setuptools`, but from what I can see, I can't do it only for my own project - if that's an option, I must have missed it.

**Comment by zonca** [comment]
I have the same issue, is there a workaround?

**Comment by uppfinnarn** [comment]
Could we have some response to this? This currently breaks a large chunk of my project's documentation, as a module that imports a library that rtfd fails to install just plain disappears from the documentation.

**Comment by ericholscher** [comment]
Are you able to specify the version of setuptools in your pip requirements?
If not, you can send a pull request fixing it, the line is here:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L328

On Wed, Feb 4, 2015 at 4:39 AM, uppfinnarn <notifications@github.com> wrote:

> Could we have some response to this? This currently breaks a large chunk
> of my project's documentation, as a module that imports a library that rtfd
> fails to install just plain disappears from the documentation.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1029#issuecomment-72847808>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by uppfinnarn** [comment]
Looks like I can specify the version in my requirements.txt, even when using setup.py for the actual project.

I'd say setuptools should still be updated though, or even installed without a version pin, as it's one of the few packages (along with pip itself) that you'd typically want to run the latest version of at all times.

**Comment by stuaxo** [comment]
Is there any way to contact someone from RTD to get this upgrade ?

**Comment by ericholscher** [comment]
If this is still an issue, please send a pull request. https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L337 is the code -- closing this issue.

**Comment by bhanuvrat** [comment]
@ericholscher yes its still happening to me https://readthedocs.org/builds/vyked/3098727/

**Comment by gregmuellegger** [comment]
@bhanuvrat I assume you get the error `Unknown distribution option: 'install_requires'` because you are using distutils. Please use setuptools instead as recommended by the Python Packaging Authority: https://packaging.python.org/en/latest/current.html#packaging-tool-recommendations

**Comment by stuaxo** [comment]
install_requires works on versions of setuptools for a while now.   

distutils comes with the standard library.

I think distribute, introduced install_requires, it has since been merged into setuptools for a while now.
