### ISSUE TITLE
How to use subdirectories instead of subdomains?

### ISSUE THREAD

**Issue by rahul286** [rtfd/readthedocs.org#1031]
*__Note:__ This question is about self-hosted setup!*

I see if I install this on example.com then for project `foo` and `bar` documentation URL will be `foo.example.com` and `bar.example.com` respectively. 

Can I instead use subdirectory style URL like `example.com/foo` and `example.com/bar`?

If yes, please guide.

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
