### ISSUE TITLE
Markdown docblock reference generator?

### ISSUE THREAD

**Issue by gintsmurans** [rtfd/readthedocs.org#1033]
It would be great to have some sort of docblock generator support that also supports markdown. As github is supported as main vcs, it would only make sense to support markdown (e.g. README.md) files which actually is possible using mkdocs, but I would also like to generate documentation from docblocks, not write the same thing in seperate files.

**Comment by ericholscher** [comment]
We now support markdown in both Sphinx & Mkdocs.
