### ISSUE TITLE
Install cairo on server?

### ISSUE THREAD

**Issue by stuaxo** [rtfd/readthedocs.org#1037]
Shoebot renders graphics using cairo, I'd like it to generate graphics that go into the doc, would it be possible to have cairo on the server ?

**Comment by ericholscher** [comment]
We are just upgrading our build server deployments, so we could do this now. Do you know the ubuntu packages off hand?

**Comment by stuaxo** [comment]
I had a look for libraries that don't work straight from pip (basically Gtk python apps - Shoebot, Gramps, Novacut):  ... and a couple of things like pyaudio, and aubio.    

AFAICT these packages predate pip/virtualenv, which is why they need persuading to work with them :)

Virtualenvs can link to the system versions of these either with --system-site-packages, symlinking or using something like 'vext' (my own project that allows only certain packages access to system modules).

Packages:
```
aubio-tools
gir1.2-freedesktop
gir1.2-pango-1.0
libaubio-dev
libaubio-doc
libcairo2-dev
libgirepository
libgirepository1.0-dev
libglib2.0-dev
libgtkspell-3-0
libjpeg-dev 
libpango
libpangocairo
python3-bsddb3
python-cairo 
python-cairo-dev
python-dev
python-gi 
python-gi-cairo
python-gobject
python-gobject
python-gobject-dev
python-gtk2 
python-gtksourceview2 
python-gtkspell
python-pyaudio
python-pyicu
python-rsvg
```

Apps that might want to use gstreamer in some way (can certainly imagine thumbnailing in docs for instance):
```
sudo apt-get install python-gi python3-gi \
    gstreamer1.0-tools \
    gir1.2-gstreamer-1.0 \
    gir1.2-gst-plugins-base-1.0 \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-libav
```

This list is reflects stuff I've been using so far, should be enough to get shoebot stuff working and Gtk related libs (using pango etc).


My next project will be doing stuff with GL, so maybe in a few years I'll be back, asking for GL2PS or similar, lets see..

**Comment by stuaxo** [comment]
But yeah - for my immediate problem - I need cairo

**Comment by stuaxo** [comment]
Heh could have asked for that better, but if there is a chance of cairo, would be great :)

**Comment by ericholscher** [comment]
I've added a PR for `libcairo2-dev` to our docker images: https://github.com/rtfd/readthedocs-docker-images/pull/7/files

**Comment by stuaxo** [comment]
Fantastic, if I ever finish my next ubertool that uses some of those other libs I'll be back here.

**Comment by stuaxo** [comment]
Just to confirm: our docs generator using cairo works now this is merged, thanks :)
