### ISSUE TITLE
margin-bottom missing for centered images

### ISSUE THREAD

**Issue by pluskid** [rtfd/readthedocs.org#1040]
Hi for Sphinx documents, adding an images looks fine
```
.. image:: foo.png
```

However, if you specify the size of the image or centering it for example:
```
.. image:: foo.png
   :align: center
   :width: 400px
```
then it will be wrapped in a div, making the bottom-margin disappearing. It will then be too close to the text following the image.

Is there any simple way to add one extra css file on top of the theme so that we could do some simple fine tuning?

**Comment by ericholscher** [comment]
This is an issue on the RTD theme: https://github.com/snide/sphinx_rtd_theme -- Closing it here.

Sphinx does support adding extra CSS with add_stylesheet.
