### ISSUE TITLE
IOError: [Errno 28] No space left on device

### ISSUE THREAD

**Issue by kmike** [rtfd/readthedocs.org#1044]
It seems there is no space left on some of the machines; see e.g. https://readthedocs.org/builds/splash/1891095/

**Comment by ddeboer** [comment]
We’re now getting this error too: https://readthedocs.org/builds/foshttpcachebundle/2881905/.

**Comment by BertrandBordage** [comment]
Same here :(
https://readthedocs.org/projects/django-cachalot/builds/3634119/

**Comment by SteveDoyle2** [comment]
Same for mine

https://readthedocs.org/projects/pynastran-git/builds/3638738/

**Comment by agjohnson** [comment]
We're going to scale out some builder boxes, seems we're racking up repository storage rather quickly these days.

**Comment by BertrandBordage** [comment]
I could build successfully since, the issue is fixed for me. :)

**Comment by agjohnson** [comment]
Yeah, this may be intermittent, we've also cleaned out some build artifacts as well
