### ISSUE TITLE
readthedocs docs virtualenv dependencies are hardcoded

### ISSUE THREAD

**Issue by hahnicity** [rtfd/readthedocs.org#1048]
In projects/tasks.py the dependencies for building sphinx docs for a project are hardcoded to

```
'sphinx==1.2.2 virtualenv==1.10.1 setuptools==1.1 docutils==0.11 readthedocs-sphinx-ext==0.4.4 mkdocs==0.11.1 mock==1.0.1 pillow==2.6.1'
```

I have run into issues with this building docs for projects that required other packages like `sphinxcontrib-httpdomain` to build. Overall there should at least be an EXTRA_PACKAGES option we can set in settings to install additional packages so we don't have to make a code change.

**Comment by ericholscher** [comment]
You can override these settings in your requirements.
