### ISSUE TITLE
PyYAML installation fails

### ISSUE THREAD

**Issue by p3trus** [rtfd/readthedocs.org#1051]
Not shure if it's a real Problem but the build output shows a failing PyYAML installation.

    Installing collected packages: sphinx, virtualenv, setuptools, docutils, readthedocs-sphinx-ext, mkdocs, mock, pillow, Jinja2, Pygments, Markdown, PyYAML, watchdog, ghp-import, markupsafe, argh, pathtools
      Running setup.py install for mkdocs
        
        warning: no previously-included files matching '__pycache__' found under directory '*'
        warning: no previously-included files matching '*.py[co]' found under directory '*'
        Installing mkdocs script to /home/docs/checkouts/readthedocs.org/user_builds/slave/envs/feature-sr7230/bin
      Running setup.py install for PyYAML
        checking if libyaml is compilable
        x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
        build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
         #include <yaml.h>
                          ^
        compilation terminated.

**Comment by bravo-kernel** [comment]
Same here and it seems my markdown.yml is not found or used.

https://github.com/alt3/cakebox/tree/dev/docs

**Comment by adamdubiel** [comment]
Same here, the only non-standard thing i do is using [sphinx_bootstrap_theme](http://ryan-roemer.github.io/sphinx-bootstrap-theme/). Same setup works well on internal RTD instance.

**Comment by bravo-kernel** [comment]
FWIW placing my markdown.yml in the root folder (and thus not in the docs subdir) does work.

**Comment by ericholscher** [comment]
Not much we can do about Yaml sadly. Closing this.
