### ISSUE TITLE
"stable" version won't go away

### ISSUE THREAD

**Issue by mboersma** [rtfd/readthedocs.org#1052]
Every time you visit the "versions" admin page, a build called "stable" is selected by default. And whenever you do a manual doc build by clicking "build version", the "stable" version is added again, even if you've toggled it off. I can't see a way to get rid of it, it is a zombie that won't die.

When the "stable" version resurrects itself, it also resets the visibility you had set for it, so "private" becomes "public."

**Comment by mboersma** [comment]
This is still a problem today. "stable" is not something we ever wanted, but it keeps inserting itself without being selected. I would love a fix for this--it's become basically impossible to build our docsets without an unwanted "stable" version being linked to, which has confused several of our users.

**Comment by mboersma** [comment]
Specifically, in our software "latest" and "v1.2.2" are releases that correspond directly to Docker Hub tags. Someone reading the `v1.2.2` docs expects to install several Docker images with `:v1.2.2` as their tag. This is a useful concordance.

`stable` has no such correlation, and has led users to think that a `:stable` tag exists for our software images on Docker Hub, which it does not. 

I just wish RTFD would not continually override my preference of toggling `stable` off and "private." Next build, it's on again, and "public."

**Comment by ericholscher** [comment]
I don't have time to work on this right now, but it should be pretty easy to fix. I will look at it next week, but if you want to try and take a stab, the code is here: https://github.com/rtfd/readthedocs.org/blob/4bf9c60220f5c4a70d7820aa3f086f80778a19a4/readthedocs/restapi/views/model_views.py#L101-L127

**Comment by mboersma** [comment]
@ericholscher thank you, I'll take a look at that and make a PR.

**Comment by rmzelle** [comment]
@mboersma, I have the opposite problem: I can't find a way to build the "stable" version. Did you do anything special to get it? (see https://github.com/rtfd/readthedocs.org/pull/1046#issuecomment-73639262 )

**Comment by gregmuellegger** [comment]
@mboersma I tried to reproduce the issue desperately. However I wasn't able to recreate it locally. I created a project, added a version, made the build, set the stable version to inactive and private, pushed a new version, checked the stable version but it was still inactive and private.

Is the problem still occuring for you? Can you give a link to project on readthedocs.org so that I might get more information form there?

**Comment by mboersma** [comment]
@gregmuellegger the project where we've had "stable" keep rising from the dead is https://readthedocs.org/projects/deis/. It stays set to "private" but "Active" gets turned on again.

**Comment by mboersma** [comment]
I haven't seen this in a few weeks, which is notable. I'll close this and reopen it if it recurs.

**Comment by gregmuellegger** [comment]
Awesome! Thanks for the feedback. So the work on this end helped. That's good to know.
