### ISSUE TITLE
Add variable path for setup.py 

### ISSUE THREAD

**Issue by hahnicity** [rtfd/readthedocs.org#1053]
Some projects may not have their setup.py located in their base checkout directory. Currently, RTD doesn't account for this and if a setup.py is not found in the checkout dir it will not run. This can have consequences for doc quality as source docs or other docs depending on a module in the virtualenv cannot be created

**Comment by ericholscher** [comment]
There are lots of workarounds for this in other bugs. #373 is one. Closing this.
