### ISSUE TITLE
Makefile honoring

### ISSUE THREAD

**Issue by matejak** [rtfd/readthedocs.org#1054]
How to handle cases when a project uses its own functionality to generate its documentation (mainly images)?
One way is to have it installed and then use Python code in `matplotlib` plot directives.
However, an alternative way is to write recipes of how to generate `.png` and `.pdf` files to the sphinx-generated `Makefile` and then just include those image files in the documentation. Scripts for image generation (that would be involved in the recipes) could be either scripts installed by `setup.py install` or Python scripts placed somewhere in the `doc` directory or subdirectories.
This way is cleaner in a way:

* Images and text are processed separately.
* Images are recalculated only when it is absolutely necessary.
* Especially images can benefit from a centralized generation (so their size is declared on one place etc.).

However, it seems that I am out of luck with this approach since RTD skips the `Makefile` and it just searches for the `conf.py` and calls `sphinx-build` by itself. Or is there a possibility to generate images on RTD in a smart way (i.e. not using the plot directive which involves repeating  boilerplate code all over again)?

**Comment by ericholscher** [comment]
We will not be adding support for makefiles. Generally the doc builds should be repeatable, and running random make scripts before building them is not something we will be supporting. To systematize it, we need to carefully call Sphinx with a number of options, and allowing a set of makefile commands to call it another way would break stuff on our side.

**Comment by matejak** [comment]
Not so fast, please.
I understand that you want to have control over sphinx-build invocation, but that's not necessarily related. And I don't see any relation to builds being repeatable.
Since you already allow installing the package to a virtualenv, the only thing necessary could be trying to run e.g. `make data` in the `doc` folder (details would become part of the RTD "API").
This is not so bad, is it?

The rule to make data could look like

```make
data: build/out1.png ...

build/out1.png: _static/src1.mat
    my-gen-script.py _static/src1.mat -o build/out1.png
    
...
```
where the `my-gen-script.py` is installed during `setup.py install`.

As an example, my `imreg_dft` project's manually uploaded documentation (http://pythonhosted.org/imreg_dft/) uses this to generate an image to the title page and also outputs of a command-line utility invocation. As a result, the documentation is 100% up-to-date with the source code, which is cool. I don't think that it can be done any other way (maybe except writing Sphinx extensions, which is not so easy to do).

If you are curious, you can [clone](https://github.com/matejak/imreg_dft) the latest revision and try the `make data` invocation in the `doc` dir (the package has to be installed beforehand).
