### ISSUE TITLE
Python-3 projects depending on matplotlib & plot-directive fail indeterministically

### ISSUE THREAD

**Issue by ankostis** [rtfd/readthedocs.org#1056]
If a python-3 project needs matplotlib's plot-directive extension, fails on install because the native-library `freetype2` is not installed:

Notice that `freetype` is indeed installed, so python2 projects are not affected by this bug 
(see ie build: https://readthedocs.org/builds/xray/1889182/ collected by #1021)

The error produced is the following:

### Setup Output
    ...
    
    requirements
    -----
    ...
    BUILDING MATPLOTLIB
                matplotlib: yes [1.4.2]
                    python: yes [3.4.0 (default, Apr 11 2014, 13:05:11)  [GCC
                            4.8.2]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [not found. pip may install it below.]
                       six: yes [six was not found.]
                  dateutil: yes [dateutil was not found. It is required for date
                            axis support. pip/easy_install may attempt to
                            install it after matplotlib.]
                      pytz: yes [pytz was not found. pip will attempt to install
                            it after matplotlib.]
                   tornado: yes [tornado was not found. It is required for the
                            WebAgg backend. pip/easy_install may attempt to
                            install it after matplotlib.]
                 pyparsing: yes [pyparsing was not found. It is required for
                            mathtext support. pip/easy_install may attempt to
                            install it after matplotlib.]
                     pycxx: yes [Official versions of PyCXX are not compatible
                            with matplotlib on Python 3.x, since they lack
                            support for the buffer object.  Using local copy]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]    
        OPTIONAL LATEX DEPENDENCIES
                    dvipng: yes [version 1.14]
               ghostscript: yes [version 9.10]
                     latex: yes [version 3.1415926]
                   pdftops: no
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype

**Comment by gregmuellegger** [comment]
@ankostis I'm wading through old tickets and discovered that this was never responded to yet. Sorry for this! We updated the matplotlib on the server and some of its configuration lately so I'm wondering if that issue still exists for you and needs further investigation by readthedocs?

**Comment by ankostis** [comment]
Sorry, v cannot provide confirmation any more.
Have switched to using Python-2 for working with matplotlib in rtd.

Feel free to close it.
