### ISSUE TITLE
"edit on github" not working for the 'stable' branch

### ISSUE THREAD

**Issue by jarondl** [rtfd/readthedocs.org#1062]
Hi.
The "edit on github" link does not work for the stable documentation version, as it tries to open the non- existent `stable` branch on github.

As I understand it, both  `latest` and `stable` are references, latest to master, and stable to the latest tagged version ( see https://docs.readthedocs.org/en/latest/versions.html ). However it seems that only `latest` has special logic to deal with the edit on github feature
https://github.com/rtfd/readthedocs.org/blob/e67465175d981d19bdd98e911d02c85e7009edff/readthedocs/builds/utils.py#L40
So the solution would be to apply the same logic, and have `stable` point to the latest tagged version.

**Comment by Klortho** [comment]
Ping. It would be really nice if this could be addressed.

**Comment by dnrce** [comment]
This would be nice to have, but might require some creativity. I looked into it but I don't see that `stable` is mapped to a tag in the database -- the closest available field is `identifier` which is the SHA (for git, at least). This might be good enough.

However, there's another issue: GitHub doesn't provide edit functionality for tags/shas. So, what's an appropriate link target for "edit"?
