### ISSUE TITLE
difference: RTD hosted theme and RTD local theme

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1064]
The RTD local theme (import sphinx_rtd_theme) is different from the hosted theme (on_rtd = os.environ.get('READTHEDOCS', None) == 'True')
Specifically, :class:`term` is red text on white background. The hosted theme generates black text on white background. The red text is more effective and differentiable.

Is there a setting in the "on_rtd=os.environ.get" string that implements the default local RTD theme on the host?

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
