### ISSUE TITLE
Build log says "failed" but logs say PDF file successfully created

### ISSUE THREAD

**Issue by gerv** [rtfd/readthedocs.org#1065]
We are getting (PDF) builds marked as failed, but the build log seems to suggest that the PDF was successfully created.

https://readthedocs.org/builds/bugzilla/1921250/

This finishes with:
Output written on Bugzilla.pdf (180 pages, 626340 bytes).
but still the build page:
https://readthedocs.org/builds/bugzilla/
lists the build as failed. :-(

Issue #979 may be related.

Gerv

**Comment by hwine** [comment]
Gerv - I have a similar issue (different character) for the [releng PDF](https://readthedocs.org/builds/moz-releng-docs/2057496/) -- how did you fix the issue for the hosted version?
Hal

**Comment by gerv** [comment]
I believe we solved it by removing the character from the PDF :-| It was only in an example, so it was easy to change. Sorry not to give a more useful answer.

**Comment by gregmuellegger** [comment]
@hwine is this still an issue for you?

**Comment by hwine** [comment]
It would be great if alternate character sets were supported, but sufficient if PDF failures are at least reported. At the time I commented, I thought I also opened an issue about non-html formatting failures, but I can't find that at the moment.
Like @gerv, I also modified my source to remove the unsupported characters.

**Comment by ericholscher** [comment]
This is now fixed with #1524 :)

**Comment by vonhatduc** [comment]
we can use https://saypdf.com to convert scan pdf to word
