### ISSUE TITLE
Hook for GitLab

### ISSUE THREAD

**Issue by alexjironkin** [rtfd/readthedocs.org#1068]
Hi,

I was trying to get RTD to play nicely with GitLab and found a little problem in that if the project is marked as private/internal RTD needs authentication details in order to clone it.

So is there any plans to make RTD integrate with GitLab repos a little better? I think there are a lot of people that currently host either internal GitLab servers or projects on GitLab.com that would be very excited about ability to use RTD for their documentation!

**Comment by markshao** [comment]
Is there any plan to make RTD well integrated with the Gitlab ? Currently we are using Gitlab internally and need to push the docs to the internal RTD server when something update on the Gitlab automatically.

**Comment by weiwongfaye** [comment]
+1

**Comment by mkaag** [comment]
+1

**Comment by agjohnson** [comment]
We'd like to be able to support public repos hosted at gitlab. We're focusing on github and bitbucket integrations for now, among many other things. Gitlab is off our radar for the immediate future. We'd be glad to point anyone willing to work on this in the right direction.

@markshao @alexjironkin if these are internal RTD installs, can you not clone via ssh to your internal gitlab installs? If you have the option of ssh pull from gitlab, installing a private key that can auth on the gitlab instance should get you access to your code. The post commit RTD endpoint can then be used to trigger a build.

**Comment by deanet** [comment]
+1

**Comment by destroyerofbuilds** [comment]
:+1:

**Comment by carukc** [comment]
+1

**Comment by warsaw** [comment]
Another +1 for gitlab.com integration!

**Comment by dissipate** [comment]
We need gitlab integration as well. +1

**Comment by bigz94** [comment]
+1 for a clean gitlab integration

**Comment by agjohnson** [comment]
We're happy to point anyone that wants to help with this in the right direction. This is low on our priorities at the moment though.

Otherwise, interest is noted, no more reason to add any more noise to this ticket.

**Comment by takotuesday** [comment]
@agjohnson would the place to start be adding gitlab to oauth and then work from there?

**Comment by agjohnson** [comment]
@takotuesday It depends on the level of integration.

To just accept a webhook and update a project on push, there needs to be an endpoint for github to push to, similar to:
https://github.com/rtfd/readthedocs.org/blob/1511716c9c984e7a53521c0fcc91e50f49e1473c/readthedocs/core/views.py#L197-L274

Ideally, integration would set this up automatically, but this requires oauth support for gitlab in [django-allauth][django-allauth]. With oauth, we can enable webhooks automatically:
https://github.com/rtfd/readthedocs.org/blob/1511716c9c984e7a53521c0fcc91e50f49e1473c/readthedocs/projects/signals.py

For full integration, we'd need oauth at gitlab, webhook creation, and models in our database to reflect what we get back from gitlab's api:
https://github.com/rtfd/readthedocs.org/blob/1511716c9c984e7a53521c0fcc91e50f49e1473c/readthedocs/oauth/models.py

[django-allauth]: https://github.com/pennersr/django-allauth

**Comment by destroyerofbuilds** [comment]
To everyone who has previously commented on the desire to have GitLab integration with ReadTheDocs, @agjohnson has setup a [GitLab Milestone](https://github.com/rtfd/readthedocs.org/milestones/Gitlab) to track all issues related to adding GitLab support.

We would appreciate your help in developing merge requests to close out the issues, and/or [reviewing merge requests](https://github.com/rtfd/readthedocs.org/pull/1448) related to the GitLab milestone.

**Comment by alexjironkin** [comment]
Hi, I am going to find some time to test this on our Gitlab server and feedback as much as I can. I saw there is #1448, would it be better if I pull down that revision before the merge and test it out, or you would like to merge first?

Also, you may not want this polluting your current development, maybe gilab branch would be good place to merge this code, then others might find it easier to pull the latest Gitlab integration code. Only a thought.

**Comment by agjohnson** [comment]
@alexjironkin We won't merge PRs into master until they are ready for production. Feel free to target the PR branch.

**Comment by ericholscher** [comment]
We have merged a hook for GitLab. #1442

**Comment by alexjironkin** [comment]
Should Gitlab appear as an option for importing project together with BitBucket and Github? Otherwise, how do I link to gitlab repo? Do I have to manually import git repo then setup hook on gitlab for this? In that case where should the hook go in RTD project?

**Comment by agjohnson** [comment]
No, that integration is not currently active, #1870 was the PR with work to add this, but it has rotted a bit by now.

Yes, manual import and manual set up of a gitlab webhook -- i'm not a user so can't walk you through that process. Docs here would be a good addition.
