### ISSUE TITLE
Use django-copyright to avoid outdated copyright notice like Copyright 2010-2013. 

### ISSUE THREAD

**Issue by philippeowagner** [rtfd/readthedocs.org#1073]
[django-copyright](https://github.com/arteria/django-copyright/)
![screen shot 2014-12-08 at 23 52 36](https://cloud.githubusercontent.com/assets/113043/5349006/828c93cc-7f35-11e4-89b0-c65c9d6a1772.png)

**Comment by ericholscher** [comment]
Happily accept a PR adding this. Not a big priority now though :)
