### ISSUE TITLE
Finish moderate() view

### ISSUE THREAD

**Issue by jMyles** [rtfd/readthedocs.org#1078]

**Comment by stsewd** [comment]
Is this necessary/useful right now or is in the plans of rtd?

/cc @humitos

**Comment by stsewd** [comment]
If I'm right this is part of the comments app, and as explained here https://github.com/rtfd/readthedocs.org/issues/2879#issuecomment-365825197, I thinks this issue has no relevance now.

**Comment by RichardLitt** [comment]
I agree.
