### ISSUE TITLE
comments_moderation view requires styling

### ISSUE THREAD

**Issue by jMyles** [rtfd/readthedocs.org#1079]
The dashboard for comments moderation requires styling.

**Comment by humitos** [comment]
@jMyles hi, what page are you talking about?

As far as I know there are no comments on RTD.

**Comment by jMyles** [comment]
Hey @humitos - awesome to meet you at PyCon! :-)

This is a project we were working on back in 2014; I think it is basically dead-ended right now and can be closed.

**Comment by humitos** [comment]
@jMyles oh... you are YOU. Everything is clearer now I can match your name/picture with your face :)

Nice to meet you!

I've been taking a look at old issues and there are a couple that can be closed. I will probably bothering your inbox with more of this ones.
