### ISSUE TITLE
differences between local version and hosted version of RTD

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1081]
Previously opened an issue with differences for ":class:".
     https://github.com/rtfd/readthedocs.org/issues/1064
A second difference is ".. list-table::".
Locally, list-table allows line breaks within a cell, for wrapping a long string.
Is there a local version of RTD that has the identical behavior of the hosted/server version?

**Comment by agjohnson** [comment]
Duplicate of #1150. Closing.
