### ISSUE TITLE
Sync Versions Exception: Client Error 403

### ISSUE THREAD

**Issue by Vitexus** [rtfd/readthedocs.org#1082]
Hallo i have problem on fresh installatiion:

***./manage.py update_repos vaultier***

sendto(12, "POST /api/v2/project/1/sync_versions/ HTTP/1.1\r\nHost: docs.rclick.cz\r\nContent-Length: 4282\r\nAccept-Encoding: gzip, deflate\r\naccept: application/json\r\nUser-Agent: python-requests/2.3.0 CPython/2.7.3 Linux/2.6.32-5-xen-amd64\r\ncontent-type: application/json\r\nAuthorization: Basic YXBpOk1hbWJ1Z3NvbWVmMA==\r\n\r\n{\"repo\": \"http://git/rclick/vaultier.git\", \"branches\": [{\"identifier\": \"origin/262_news\", \"verbose_name\": \"262_news\"}, {\"identifier\": \"origin/bugfix_debian_postinstal\", \"verbose_name\": \"bugfix_debian_postinstal\"}, {\"identifier\": \"origin/feature-131-disable-hotkeys-when-loader-is-visible\", \"verbose_name\": \"feature-131-disable-hotkeys-when-loader-is-visible\"}, {\"identifier\": \"origin/feature-176-lostkey-api\", \"verbose_name\": \"feature-176-lostkey-api\"}, {\"identifier\": \"origin/feature-182-bck\", \"verbose_name\": \"feature-182-bck\"}, {\"identifier\": \"origin/feature-196\", \"verbose_name\": \"feature-196\"}, {\"identifier\": \"origin/feature-214\", \"verbose_name\": \"feature-214\"}, {\"identifier\": \"origin/feature-239\", \"verbose_name\": \"feature-239\"}, {\"identifier\": \"origin/feature-338\", \"verbose_name\": \"feature-338\"}, {\"identifier\": \"origin/feature-genericacl\", \"verbose_name\": \"feature-genericacl\"}, {\"identifier\": \"origin/feature-mptt\", \"verbose_name\": \"feature-mptt\"}, {\"identifier\": \"origin/feature-redesign\", \"verbose_name\": \"feature-redesign\"}, {\"identifier\": \"origin/feature-redesign-254\", \"verbose_name\": \"feature-redesign-254\"}, {\"identifier\": \"origin/feature-redesign-258\", \"verbose_name\": \"feature-redesign-258\"}, {\"identifier\": \"origin/feature-redesign-259\", \"verbose_name\": \"feature-redesign-259\"}, {\"identifier\": \"origin/feature-reversion\", \"verbose_name\": \"feature-reversion\"}, {\"identifier\": \"origin/feature-reversion-wireframes-and-api\", \"verbose_name\": \"feature-reversion-wireframes-and-api\"}, {\"identifier\": \"origin/feature-testing-example\", \"verbose_name\": \"feature-testing-example\"}, {\"identifier\": \"origin/feature-tree\", \"verbose_name\": \"feature-tree\"}, {\"identifier\": \"origin/feature-v1.0\", \"verbose_name\": \"feature-v1.0\"}, {\"identifier\": \"origin/feature-v1.0-332\", \"verbose_name\": \"feature-v1.0-332\"}, {\"identifier\": \"origin/feature-v1.0-348-v2\", \"verbose_name\": \"feature-v1.0-348-v2\"}, {\"identifier\": \"origin/feature-v1.0-361\", \"verbose_name\": \"feature-v1.0-361\"}, {\"identifier\": \"origin/feature-v1.0-362\", \"verbose_name\": \"feature-v1.0-362\"}, {\"identifier\": \"origin/feature-v1.0-frontend-tree\", \"verbose_name\": \"feature-v1.0-frontend-tree\"}, {\"identifier\": \"origin/issue_#305\", \"verbose_name\": \"issue_#305\"}, {\"identifier\": \"origin/master\", \"verbose_name\": \"master\"}, {\"identifier\": \"origin/release\", \"verbose_name\": \"release\"}, {\"identifier\": \"origin/stable\", \"verbose_name\": \"stable\"}, {\"identifier\": \"origin/v1.0\", \"verbose_name\": \"v1.0\"}], \"tags\": [{\"identifier\": \"2292662dbf51eca5a7a0c555aebc1dbb40e7e904\", \"verbose_name\": \"v0.1.0-alpha1\"}, {\"identifier\": \"92b9d9195f6ffe706650a706d49a9df8756698d1\", \"verbose_name\": \"v0.2.0-alpha1\"}, {\"identifier\": \"69a704a75623d9c9efa0e7e98cab4b03621ef4f6\", \"verbose_name\": \"v0.6.0\"}, {\"identifier\": \"fe7baf8ac33935391761ae1d9a4640fc1c01dc45\", \"verbose_name\": \"v0.6.1\"}, {\"identifier\": \"568176dcaa7b90b33684ac6c0d0095cb7720fc2b\", \"verbose_name\": \"v0.6.2\"}, {\"identifier\": \"2fa8e04b2171e818b89d3bea1443c42e7d240965\", \"verbose_name\": \"v0.6.3\"}, {\"identifier\": \"13f1462c413709a1be0a02ffbd4b79a985ec3e2d\", \"verbose_name\": \"v0.6.4\"}, {\"identifier\": \"34ec5d1a6ddc2b8f178d5d35cfa229d76ba09c8a\", \"verbose_name\": \"v0.6.5\"}, {\"identifier\": \"0009c63245177b3f15d62de45362c27aaffb6bb4\", \"verbose_name\": \"v0.7.1-stable.1\"}, {\"identifier\": \"17c129194251300be0e9d8496a7ce16890a5397f\", \"verbose_name\": \"v0.7.2-rc.1\"}, {\"identifier\": \"1690fcfb627ae1c7dd3ad171d5ff406a9580f31d\", \"verbose_name\": \"v0.7.2-stable.1\"}, {\"identifier\": \"1891699ac317dbc4e3d085d2c693160fb0ee9449\", \"verbose_name\": \"v0.7.3-rc.1\"}, {\"identifier\": \"9335cbad01f5e0ea375c9ad087f8c7335e0517af\", \"verbose_name\": \"v0.7.3-stable.1\"}, {\"identifier\": \"896a1b506961ff52741f74c2bc851a399fd614e4\", \"verbose_name\": \"v0.7.3-stable.2\"}, {\"identifier\": \"887da07f29bb2f621bdff1d31e456e937a41c433\", \"verbose_name\": \"v0.7.4-rc.1\"}, {\"identifier\": \"c3e80afa9e98b7d543320e3b3c0850587ced8129\", \"verbose_name\": \"v0.7.4-rc.2\"}, {\"identifier\": \"d83cf3760f874a532044e5b37212c237f64fdf69\", \"verbose_name\": \"v0.7.4-rc.3\"}, {\"identifier\": \"9c778d3d736b16fe0c49f59d6730f1f747c12f41\", \"verbose_name\": \"v0.7.4-rc.4\"}, {\"identifier\": \"e0127f0371d93150c3468856e0cb1fd916f0f03b\", \"verbose_name\": \"v0.7.4-rc.5\"}, {\"identifier\": \"49edff3acdc79b91b8110d488488608af4b47ba0\", \"verbose_name\": \"v0.7.4-stable.1\"}]}", 4587, 0, NULL, 0) = 4587

gives me 

recvfrom(12, "HTTP/1.1 403 FORBIDDEN\r\nServer: nginx/1.2.1\r\nDate: Fri, 12 Dec 2014 16:04:05 GMT\r\nContent-Type: application/json\r\nTransfer-Encoding: chunked\r\nConnection: keep-alive\r\nVary: Accept, Accept-Language, Cookie\r\nContent-Language: en\r\nAllow: POST, OPTIONS\r\n\r\n0\r\n\r\n", 8192, 0, NULL, NULL) = 256

Sync Versions Exception: Client Error 403: http://docs.rclick.cz/api/v2/project/1/sync_versions/

Any idea why ?

**Comment by MonamiB** [comment]
Hi, 
Were you able to resolve this? I am facing the same problem. More here - https://github.com/rtfd/readthedocs.org/issues/1206

So all the POST, GET, and PUT calls are throwing errors.
    [26/Mar/2015 05:11:29] "POST /api/v2/project/1/sync_versions/ HTTP/1.1" 403 38
Sync Versions Exception: Client Error 403: http://localhost:8000/api/v2/project/1/sync_versions/

    [26/Mar/2015 05:11:29] "GET /api/v2/project/1/ HTTP/1.1" 403 38

    [26/Mar/2015 05:11:29] "PUT /api/v1/build/2/ HTTP/1.1" 401 0
    [26/Mar/2015 05:11:29] ERROR [projects.tasks:555] Unable to post a new build

**Comment by Vitexus** [comment]
No. Finally i copy generated docs by hand :(

**Comment by ericholscher** [comment]
If you would like to support docs around local installs, we would welcome the contribution. As it stands, we don't have time to officially support it.

**Comment by MonamiB** [comment]
Eric, I would be happy to document my learnings from the attempted local
installation and some workarounds to the issues faced. Glad to collaborate
as well. Please let me know how to proceed.

Thanks!
Monami

On Wed, May 27, 2015 at 6:35 AM, Eric Holscher <notifications@github.com>
wrote:

> If you would like to support docs around local installs, we would welcome
> the contribution. As it stands, we don't have time to officially support it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1082#issuecomment-105707406>
> .
>



-- 
Thanks!

*Monami Bhattacharya*
Seller Platform - Documentation

**Comment by ericholscher** [comment]
We have a tree in the docs with some basic information, feel free to add
your information here, and send a pull request:

https://github.com/rtfd/readthedocs.org/tree/master/docs/custom_installs

On Tue, May 26, 2015 at 10:45 PM, MonamiB <notifications@github.com> wrote:

> Eric, I would be happy to document my learnings from the attempted local
> installation and some workarounds to the issues faced. Glad to collaborate
> as well. Please let me know how to proceed.
>
> Thanks!
> Monami
>
> On Wed, May 27, 2015 at 6:35 AM, Eric Holscher <notifications@github.com>
> wrote:
>
> > If you would like to support docs around local installs, we would welcome
> > the contribution. As it stands, we don't have time to officially support
> it.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/rtfd/readthedocs.org/issues/1082#issuecomment-105707406
> >
> > .
> >
>
>
>
> --
> Thanks!
>
> *Monami Bhattacharya*
> Seller Platform - Documentation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1082#issuecomment-105764562>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by thedillonb** [comment]
@Vitexus @MonamiB check to make sure your `SLUMBER_*` settings are correct and that the username and password are valid. This exact issue was just happening to me until I noticed that the default `SLUMBER_USERNAME` 'test' did not exist in the system.
