### ISSUE TITLE
DocumentCommentManager needs method "visible()"

### ISSUE THREAD

**Issue by jMyles** [rtfd/readthedocs.org#1084]
``` python
def visible(self, inquiring_user=None, node=None):
'''
Returns all comments that are visible, pursuant to their project's 
moderation settings, including those that are otherwise not visible
but for inquiring_user's authority.

Can be restricted to node.
'''
```

**Comment by Tikam02** [comment]
I think it's already done and someone has commented it in models.py
![screenshot from 2018-02-15 22-02-45](https://user-images.githubusercontent.com/10548085/36268271-0d65bf8a-129c-11e8-9294-a1e50926066c.png)

**Comment by stsewd** [comment]
This is part of the comments app, as mention here https://github.com/rtfd/readthedocs.org/issues/2879#issuecomment-365825197, this issue has no relevance and must be closed.

Note: [Here](https://github.com/rtfd/readthedocs.org/milestone/2) are some more related issues to the comment app, probably need them to be closed too.

**Comment by stsewd** [comment]
Closing this since the comments app was removed #3802
