### ISSUE TITLE
http and https links displayed as raw text instead of link

### ISSUE THREAD

**Issue by femtotrader** [rtfd/readthedocs.org#1091]
Hello,

http:// and https:// links in Markdown file are considered as raw text on ReadTheDocs but as link on GitHub.

see
http://pandas-datareaders.readthedocs.org/en/latest/todo/
and compare to:
https://github.com/femtotrader/pandas_datareaders/blob/master/docs/todo.md

Kind regards

**Comment by ericholscher** [comment]
This is a Mkdocs question, not a Read the Docs one.
