### ISSUE TITLE
unordered list depth problem

### ISSUE THREAD

**Issue by femtotrader** [rtfd/readthedocs.org#1093]
Hello,

it seems that there is a problem with unordered list depth.

compare
http://pandas-datareaders.readthedocs.org/en/latest/todo/
with
https://github.com/femtotrader/pandas_datareaders/blob/master/docs/todo.md

I was expecting same results.

Any idea ?

**Comment by ericholscher** [comment]
This is a Mkdocs question, not a Read the Docs one.
