### ISSUE TITLE
Access to checked-out version in conf.py

### ISSUE THREAD

**Issue by holtgrewe** [rtfd/readthedocs.org#1096]
Is it possible to access the current version (e.g. "latest", "master", or "develop") in the `conf.py` file?

I would like to generate links to API documentation at `http://example.com/docs/${version}` and make the `${version}` part correspond to the version as on the readthedocs server.

**Comment by rrahn** [comment]
:+1:

**Comment by gregmuellegger** [comment]
We could make the version available as a environment variable. Let's put this on the list, but it's not high in priority for us. @holtgrewe @rrahn would you be interested in working on this in a Pull Request? I'm happy to guide you through any of this if you need help.

**Comment by rrahn** [comment]
Hey thank you for your response.
@esiragusa and me can work on this. 
Can you give us a starting point to look at? We could then create a pull request.

**Comment by gregmuellegger** [comment]
This would be a good place to set the actual environment variable: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/environments.py#L92

You can get to the `Version` model instance for the current build there with `self.build_env.version`. It is an instance of https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/builds/models.py#L30
The `slug` attribute on the version is the bit that will be used in the URL, so you probably want to set an environment variable like `environment['VERSION_SLUG'] = self.build_env.version.slug`.

If you look into the `__init__` method of `BuildCommand` you see that `self.build_env` might be `None`. Please make sure to test for this case.

**Comment by stsewd** [comment]
This issue was already solved on #1570 (merged)

**Comment by rrahn** [comment]
@stsewd can you close the issue. I am afraid I can't as I am not the original author. The others probably will not respond.

**Comment by stsewd** [comment]
@rrahn I can't neither, let's wait to someone with permissions to do it.

**Comment by holtgrewe** [comment]
Thanks!
