### ISSUE TITLE
Unable to delete stale build

### ISSUE THREAD

**Issue by aik099** [rtfd/readthedocs.org#1102]
The https://readthedocs.org/builds/phpunit-mink/2014493/ build appears to be stale. I try to delete it according to instructions on http://read-the-docs.readthedocs.org/en/latest/builds.html page, but the url I've constructed http://readthedocs.org/wipe/phpunit-mink/2014493/ returns 404 page.

**Comment by mboersma** [comment]
+1 for this. We have numerous stale doc builds that are still accessible on the internet, and RTFD's instructions for how to delete them do not work. We've wasted time helping users who have somehow bookmarked or found these obsolete docsets, only to discover they're reading unsupported, dead docs.

This is the same issue I reported first in #1001.

**Comment by ericholscher** [comment]
There is a current branch open to add Wipe to the dashboard, which will fix this issue very soon.
