### ISSUE TITLE
Decorated function shows wrong signature

### ISSUE THREAD

**Issue by aroberge** [rtfd/readthedocs.org#1107]
I have some Python functions that are modified by a decorator which attempts to preserve the signature.  When I create the documentation locally with Sphinx, the signature is indeed preserved.

However, when ReadtheDocs creates the documentation, the signature is transformed into a generic ``*args, **kwargs`` form which is not very useful; granted, one can view the source but it would be better if the signature was preserved.  Examples can be seen at: 
http://easygui-qt.readthedocs.org/en/latest/api.html

**Comment by ericholscher** [comment]
Sounds like this was resolved.
