### ISSUE TITLE
clean_canonical_url is chopping off important subpath

### ISSUE THREAD

**Issue by mmerickel** [rtfd/readthedocs.org#1108]
The pyramid project[1] is using a `canonical_url` of `http://docs.pylonsproject.org/projects/pyramid/`. It appears as if `readthedocs.projects.models.Project.clean_canonical_url`[2] is chopping off `/projects/pyramid`.

For example, I see

```
<link rel="canonical" href="http://docs.pylonsproject.org/en/latest/quick_tour.html" />
```

instead of

```
<link rel="canonical" href="http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tour.html" />
```

[1] https://readthedocs.org/projects/pyramid/
[2] https://github.com/rtfd/readthedocs.org/blob/10496ffbf2b5190e8a66047c649c402db7fdf8f9/readthedocs/projects/models.py#L382

**Comment by ericholscher** [comment]
Believe this just got fixed.

**Comment by mmerickel** [comment]
Just re-built the docs and they look correct. Thanks again.
