### ISSUE TITLE
Support for multiple requirements files

### ISSUE THREAD

**Issue by zaro0508** [rtfd/readthedocs.org#1112]
My project is here: https://readthedocs.org/projects/jenkins-job-builder/

My project has two requirements files (requirements.txt and test-requirements.txt).   I enable the "use virtualenv" setting and  set requirements file to "-rrequirements.txt -rtest-requirements.txt".  When the build runs I get the following error: Could not open requirements file: [Errno 2] No such file or directory: '-rrequirements.txt' 

I've tried a few other combinations to set both requirements files but none work.  Does rtfd support multiple requirements files or am I just not setting it correctly?

**Comment by ericholscher** [comment]
You can include other requirements files within a single. For example:
https://github.com/rtfd/readthedocs.org/blob/master/deploy_requirements.txt#L1

On Fri, Jan 2, 2015 at 12:52 PM, Zaro <notifications@github.com> wrote:

> My project is here: https://readthedocs.org/projects/jenkins-job-builder/
>
> My project has two requirements files (requirements.txt and
> test-requirements.txt). I enable the "use virtualenv" setting and set
> requirements file to "-rrequirements.txt -rtest-requirements.txt". When the
> build runs I get the following error: Could not open requirements file:
> [Errno 2] No such file or directory: '-rrequirements.txt'
>
> I've tried a few other combinations to set both requirements files but
> none work. Does rtfd support multiple requirements files or am I just not
> setting it correctly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1112>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by zaro0508** [comment]
I keep them separate because I want to deploy my app without requiring the test dependencies. If i use the '-r' flag as you suggested a pip install would also install the test-requirements.

**Comment by ericholscher** [comment]
We will only support 1 requirements file. Feel free to make a custom one just for us that points at multiple others.

**Comment by KeyWeeUsr** [comment]
The file was moved [here](https://github.com/rtfd/readthedocs.org/blob/master/requirements/deploy.txt#L1)

**Comment by dtantsur** [comment]
> We will only support 1 requirements file. Feel free to make a custom one just for us that points at multiple others.

That's a really bad decision. You're excluding essentially any serious projects using autodoc, which have to install both requirements.txt (for autodoc) and test-requirements.txt (for sphinx plugins). For example, you're excluding any OpenStack project (following OpenStack guidelines https://governance.openstack.org/tc/reference/project-testing-interface.html#pti-documentation).

**Comment by fungi** [comment]
Note that the documentation portion of OpenStack's PTI selected doc/requirements.txt expressly to maintain compatibility with RTD. If there is still something missing which prevents use of RTD by projects following the PTI recommendations then we can probably get those recommendations updated.

**Comment by dtantsur** [comment]
@fungi autodoc requires installing the complete requirements. Which, given the decision made in this bug, requires copying everything from requirements.txt to doc/requirements.txt and then keeping both in sync. And if we consider people building docs locally, then we need the 3rd file just for RTD, and then keep it in sync with the 2 previously created... This is just a nightmare compared to potential change to support a list of files instead of one.

**Comment by ericholscher** [comment]
You can reference requirements files from each other: https://stackoverflow.com/questions/11704287/split-requirements-files-in-pip

**Comment by KeyWeeUsr** [comment]
> You can reference requirements files from each other: https://stackoverflow.com/questions/11704287/split-requirements-files-in-pip

While this is true via using `include PATH` inside the requirements.txt, it does not allow installing packages from the multiple requirements.txt *one after another*. For example:

**req1.txt**:
```
Pillow
```

**req2.txt**:
```
some-package-that-depends-on-Pillow-already-installed  # fail
```
