### ISSUE TITLE
Can't install pip_requirements.txt

### ISSUE THREAD

**Issue by sujaymansingh** [rtfd/readthedocs.org#1113]
Cloned with tag 1.0
```
$ pip --version
pip 6.0.6 from /opt/env/readthedocs/local/lib/python2.7/site-packages (python 2.7)
```

I get this at the end of my attempt to `pip install -r pip_requirements.txt`
```
...
Collecting python-dateutil<2.0,>=2.1 (from github2->-r /opt/readthedocs/pip_requirements.txt (line 15))
  Could not find a version that satisfies the requirement python-dateutil<2.0,>=2.1 (from github2->-r /opt/readthedocs/pip_requirements.txt (line 15)) (from versions: 1.4, 1.4.1, 1.5, 2.1, 2.2, 2.3, 2.4.0)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external to allow).
  No distributions matching the version for python-dateutil<2.0,>=2.1 (from github2->-r /opt/readthedocs/pip_requirements.txt (line 15))
```

**Comment by sujaymansingh** [comment]
Actually it worked when I cloned using `master` rather than `1.0`.
Is `1.0` not to be used?
If you want, I can close this if `1.0` is not a valid release.

**Comment by ericholscher** [comment]
1.0 is old and broken. We should remove it.

**Comment by 62mkv** [comment]
> We should remove it.

But it's not removed ! 

And actually, the same problem also prevents building other "versions", like "stable", "0.2.2" and "0.2.1" 

That's quite embarassing for a newcomer..
