### ISSUE TITLE
Wrong canonical URL for genindex

### ISSUE THREAD

**Issue by nijel** [rtfd/readthedocs.org#1114]
Currently http://docs.weblate.org/en/latest/genindex.html contains canonical link:

```
<link rel="canonical" href="http://docs.weblate.org/en/latest/gen" />
```

but this page does not exist...

**Comment by nijel** [comment]
The problem is in removing index.html from the URL:

https://github.com/rtfd/readthedocs.org/blob/0843f4a36ba513fbc4148c144fad6f4f6796aec6/readthedocs/templates/sphinx/layout.html#L14

**Comment by ericholscher** [comment]
Confirmed this is still an issue. Can be fixed with a PR checking for this case in the linked above code.
