### ISSUE TITLE
[Suggestion] Use a link to the doc rather than the project for the badge

### ISSUE THREAD

**Issue by stof** [rtfd/readthedocs.org#1115]
The Markdown snippet provided for the badge currently uses a link to the project page on ReadTheDocs. I think it might be more useful for people seeing the badge on the package if the link was actually pointing to the rendered doc. They are more likely to be interested in the documentation of the package rather than the config used to build it.
What do you think about this ?

**Comment by aik099** [comment]
The badge alternative text says `Documentation Status` so this was meant to display the status I guess. 

But for documentation status doesn't really mean much because it's unlikely somebody will break the documentation :)

**Comment by destroyerofbuilds** [comment]
:+1: 

I would like, given that the badge says `docs: latest`, that clicking on the badge would take me to the build artifacts associated with the `latest` label in ReadTheDocs.

The same would go for `docs: stable`, which would point to documentation associated with the latest tagged version.

**Comment by nedbat** [comment]
I agree: the badge should link to the docs themselves.  No one but me is going to want to see the project page.

**Comment by gregmuellegger** [comment]
I'm a :+1: as well. However we need a decision by @ericholscher or @agjohnson here.

**Comment by agjohnson** [comment]
I think this makes sense, it is in line with our thoughts on redesigning what "failing" builds mean in the context of authorship and in consuming documentation. This was implemented as an author feature, but really should be a reader feature.

**Comment by gregmuellegger** [comment]
This is fixed now, we link now from the badge to the docs instead of the project page. However existing badges in REAMDE files etc need to be updated by hand ofcourse.
