### ISSUE TITLE
Issue 666 has returned - underscore to hyphen in project name results in 404

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#1116]
The beast has returned. Example.
http://pylons.readthedocs.org/projects/pyramid-cookbook/en/latest/

This issue just started happening again within the last week, I would guess.

**Comment by ericholscher** [comment]
Bah, sorry about that. Should be resolving itself now.

On Tue, Jan 6, 2015 at 10:57 PM, Steve Piercy <notifications@github.com>
wrote:

> The beast has returned. Example.
> http://pylons.readthedocs.org/projects/pyramid-cookbook/en/latest/
>
> This issue just started happening again within the last week, I would
> guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1116>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by stevepiercy** [comment]
Thank you! Looks like all the other projects with underscores are rendering again, too.
