### ISSUE TITLE
github list is not up to date

### ISSUE THREAD

**Issue by jcw** [rtfd/readthedocs.org#1117]
While checking out RTD, I wanted to try it out on a project of mine. But even after requesting a refresh, my projects are not all listed. Some old ones are in the list, but some new ones, including a new organisation, aren't. Is there a way to _properly_ force an update of my github repository list on rtd.org?

**Comment by shangguokan** [comment]
+1 i don't know why even for these repos removed on github, RTD keep them

**Comment by gregmuellegger** [comment]
That's no good. We need to investigate here.

**Comment by ericholscher** [comment]
I believe this is fixed now.

**Comment by jcw** [comment]
The jcw/buzz repository I created two weeks ago is not showing up in my RTD list.
No big deal for me, but it looks like this is not yet 100% fixed - or perhaps just lagging?

**Comment by KeithWoods** [comment]
Just chiming in here. I don't see all the organisations I have against my github account nor all the projects. I removed and added my github users and now see more projects, but not the other organisations.

**Comment by agjohnson** [comment]
@KeithWoods et al -- is this an organization that requires the application to be authorized? We don't do anything special with organizations here. We do however filter out private repositories, so that might be why some are missing?
