### ISSUE TITLE
Build from github fails (too) silently

### ISSUE THREAD

**Issue by ycopin** [rtfd/readthedocs.org#1119]
I imported a small sphinx-based project (https://readthedocs.org/builds/spectrogrism/) from a github public repository (https://github.com/ycopin/spectrogrism), but I just can't pass the build. It fails with a very simple but not very helpful message:

```
Etat: Finished
Résultat Failed
Version : latest
Type: html
Commit: 1ade93ea54ee4b2cd029d0b693415c18c723d279
Build Standard Output

Sortie de configuration

checkout
-----

Erreur standard d'environnement

checkout
-----
```

I tried all sorts of tweak in the configuration. I assume it's a but in my own configuration, but could the error message be a bit more informative on the reason of the failures?

**Comment by ericholscher** [comment]
This is a weird edge case where it wasn't able to find your conf.py file
because there was a bunch of other conf.py files in your _build dir, which
wasn't getting cleaned because it was in your git ignore. I blew away the
build dir and it seems to be happier now.

On Tue, Jan 13, 2015 at 12:13 AM, Yannick Copin <notifications@github.com>
wrote:

> I imported a small sphinx-based project (
> https://readthedocs.org/builds/spectrogrism/) from a github public
> repository (https://github.com/ycopin/spectrogrism), but I just can't
> pass the build. It fails with a very simple but not very helpful message:
>
> Etat: Finished
> Résultat Failed
> Version : latest
> Type: html
> Commit: 1ade93ea54ee4b2cd029d0b693415c18c723d279
> Build Standard Output
>
> Sortie de configuration
>
> checkout
> -----
>
> Erreur standard d'environnement
>
> checkout
> -----
>
> I tried all sorts of tweak in the configuration. I assume it's a but in my
> own configuration, but could the error message be a bit more informative on
> the reason of the failures?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1119>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by ycopin** [comment]
Thanks, the build is now passing... but I don't quite understand the situation. AFAIK:

1. I'm surprised by the presence of the  `_build` dir, which has not been committed to git
2. there's no `conf.py` line in the `.gitignore`
3. the HTML build still fails with:

```
WARNING: autodoc: failed to import module u'spectrogrism'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spectrogrism/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 335, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spectrogrism/envs/latest/local/lib/python2.7/site-packages/spectrogrism.py", line 32, in <module>
    import numpy as N
ImportError: No module named numpy
```

This results ultimately in an incomplete documentation (e.g. http://spectrogrism.readthedocs.org/en/latest/#code-documentation is empty).  A simple "make html" works fine here.

Thanks for your support, and just let me know if you consider this is too much a "specific" issue.

**Comment by ycopin** [comment]
Following the [FAQ](http://docs.readthedocs.org/en/latest/faq.html#my-project-isn-t-building-with-autodoc), I now use `virtualenv` and added a `requirements.txt` with `numpy` and `matplotlib`. However, even though the build is successful, the autodoc failed because of a missing `numpy` installation. In `Setup Output/requirements`:

```
Downloading/unpacking numpy (from -r requirements.txt (line 1))
  Running setup.py (path:/var/build/user_builds/spectrogrism/envs/latest/build/numpy/setup.py) egg_info for package numpy
    Running from numpy source directory.
    
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
```

**Comment by ycopin** [comment]
Sorry about the last comment: this was already addressed in the [FAQ](http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules). Everything is working fine now, without any need for `virtualenv` and requirements.
