### ISSUE TITLE
No email notification sent for build failures only affecting PDF format

### ISSUE THREAD

**Issue by hwine** [rtfd/readthedocs.org#1121]
I am configured to receive build failure notification for [a project](https://readthedocs.org/dashboard/moz-releng-docs/notifications/). However, I only receive the email if there is a failure in the HTML build.
Not receiving notfication of PDF build failures led, in part, to issue #1120, where we went from 6 months before the failed builds were noticed.

**Comment by agjohnson** [comment]
Ah yes, this comes from tracking the builds of HTML and pdf as separate objects without a link between the two. We'll have to move the notification to a spot that knows of both HTML abs pdf build objects, which is currently only where the  builds are triggered.

**Comment by agjohnson** [comment]
As part of a build refactor, we aren't performing a goofy magic pdf build anymore on build trigger, so failures should be per build and you should get notified on pdf failures.

**Comment by hwine** [comment]
:100:
