### ISSUE TITLE
I can add, but not delete, subprojects I don't own

### ISSUE THREAD

**Issue by philipstarkey** [rtfd/readthedocs.org#1122]
I (stupidly) attempted to add a subproject before I had created it. It so happens that the project (apparently) already existed, and it added it despite me not owning it. When I try to delete the subproject, it says "Sorry, this page does not exist yet".

To confirm, I added another subproject (of a colleague of mine) called bprofile. Same deal. I can add, but not delete the subproject.

Details:
Site: readthedocs.org
Project: labscriptsuite
subprojects: labscript, bprofile

Based on what I've read, the system should not have allowed me to add a project I don't own.
Also, I would suggest allowing the ability to remove a subprojects from a project, even if you don't own the subproject, so that I can clean my project up (I really don't want these random projects to be subprojects of my project!)

**Comment by RomanKharin** [comment]
Same issue,
Site: readthedocs.org
Project: pyfpdf
subprojects: wiki (that i wanna remove from subprojects)
