### ISSUE TITLE
Differences between RTD and Online rST (OrST)

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1123]
I have a question about formatting of csv-table and list-table.

Here is a csv-table on Online rST:   [link to OrST-1] (http://rst.ninjs.org/?n=5523984685b576e5f5b14f727b33c354&theme=nature)

However the lines do not wrap on RTD. Here is how they look on RTD: [link to RTD](http://nutrients.readthedocs.org/en/latest/$_02-core-08-relationships.html)

Here is a list-table on OrST:   [link to OrST-2](http://rst.ninjs.org/?n=41ad85ecb2220029fb6aba7e435cb8ab&theme=nature).

Again, the lines do not wrap on RST.

Is there a setting where RTD will format these tables as formatted on OrST?

I am using sphinx_rtd_theme.

**Comment by agjohnson** [comment]
Your links don't work for me, it sounds like you are referring to tables scrolling and not wrapping.

This is a design decision that I agree with, I don't think squashing content works for all cases. There are no settings for this, it is all done on the client side. You can override this behavior with local static includes in your project docs.

Reopen this ticket on the theme repo if you feel this is a bug.
