### ISSUE TITLE
Differences between RTD-Windows-client and RTD-server

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1124]
I have a question about frames - meaning that the navigation section is stationary when scrolling down in the detail section.

On Windows (sphinx_rtd_theme) frames are enabled for:
1. Definition List
2. Glossary (implemented as a Definition List)
3. Bibliography
4. Bullet-list
5. Table of Contents (i.e. an .rst with toctree:: and :maxdepth: 4 - creating a long list)

However, frames do not work on a page with mixed elements (combinations of 1 and 4).

On RTD-server frames do not work for any configuration.

On Sphinx, frames are enabled for all elements and element combinations. See  [link to Sphinx](http://sphinx-doc.org/index.html)

Is there an RTD setting that will:
1. Enable frames on the RTD-server as they are implemented on RTD-Windows-client?
2. Enable frames for all elements as on Sphinx?

**Comment by agjohnson** [comment]
I don't quite follow what the issue is here, but it sounds like an issue with CSS or the browser being used. More info could help here, if you want to include a screenshot of the difference and some more info about your setup/browser.

To answer your question, no, there are no settings that control this.

**Comment by gigster99** [comment]
IMHO this not a CSS issue. It definitely is not a browser issue.
The best way learn about the issue and to see differences is to compare the RTD documentation site to the Sphinx site.
When scrolling down a long page, Sphinx menus (on the right) are stationary (some folks call this a 'frame' even though the code to implement frames is no longer implemented in modern browsers). 
When you scroll down a Web implementation of RTD (using the RTD theme) the menus are not in a 'frame' and scroll off the screen with other content above the long content being viewed.
However, when you scroll down a long page using the RTD theme under Windows, the page is treated like a frame and menus (on the left) are stationary. In other words, the menus are not synchronized with the content on the display page; menus are stationary when scrolling down a long page.
Can you use the same code that implements 'frames' on Windows on the RTD web site?
/g

**Comment by agjohnson** [comment]
Okay, this makes more sense -- what browser is this occurring on? Also, a link to your project would be helpful.

This is indeed a CSS issue, likely with the way that the nav menu is positioned on whatever browser you are using. Not sure if this is the case, but CSS positioning will stop the nav from scrolling if the window height is larger than the nav list. It doesn't sound like this is the case though.

No windows machines immediately available, we can test this more this week.

**Comment by gigster99** [comment]
Here is our project:
http://nutrients.readthedocs.org/en/latest/index.html
Just to be clear - we like how the RTD CSS works under Windows and would like the same behavior on RTD web.
No snarking intended here - we'd just like to get the same behavior as we see on the Sphinx web site.
We spoke with the Sphinx folks about their template - the report is that they added a bit of javascript to implement the frames. But we don't see any javascript on RTD Windows. The desirable RTD scrolling under Windows works the same for Internet Explorer, Safari, Chrome and Firefox.
