### ISSUE TITLE
CSS change for :class:

### ISSUE THREAD

**Issue by gigster99** [rtfd/readthedocs.org#1125]
Am using sphinx_rtd_theme on Windows.
When using directive :class: the variable is displayed with red text and white background.
However, on RTD-server (using sphinx_rtd_theme), the text is black.
What steps should I follow to make the :class: directive on RTD-server display red text and white background?
A work-around is to create a new directive that formats like :class: but uses red text and white background. But I'm not sure whether that would work on RTD-server.
I have used :raw: and inline HTML CSS code to test whether the color red displays on RTD-server (it does), but hope to avoid this extra effort if there is a more straightforward alternative.

**Comment by agjohnson** [comment]
You can include arbitrary static files and CSS in with your documentation. Sphinx knows to search in the `_static` path.

Bugs with our theme are tracked seperately. You can submit a patch against the theme at https://github.com/snide/sphinx_rtd_theme
