### ISSUE TITLE
Absolute import

### ISSUE THREAD

**Issue by domdinicola** [rtfd/readthedocs.org#1126]
In order to be compliant to standard and to improve the extensibility, don't you think absolute import would improve this?

**Comment by agjohnson** [comment]
Could you elaborate? I'm not sure I follow this issue.

**Comment by domdinicola** [comment]
the import should be using absolute namespace
eg. instead of "from api.base import x" use "from readthedocs.api.base import x"

**Comment by ericholscher** [comment]
The main reason this is done is so that the apps can be reused outside of the codebase. It's something we might fix, but closing this since it won't happen for a long time probably :)
