### ISSUE TITLE
Build says "passed" but batch says "unkown version"; what to do?

### ISSUE THREAD

**Issue by erikb85** [rtfd/readthedocs.org#1127]
Hi,

my [project](https://github.com/DFE/MONK/)  doesn't show any errors, but the batch ([![Documentation Status](https://readthedocs.org/projects/monk-tf/badge/?version=latest)](https://readthedocs.org/projects/monk-tf/badge/?version=latest)) still is not happy. Can't find anything in the [docs](https://docs.readthedocs.org/en/latest/versions.html) or the [FAQ](https://docs.readthedocs.org/en/latest/faq.html). What to do?

**Comment by ericholscher** [comment]
It seems to look okay on our side: https://readthedocs.org/projects/monk-tf/
-- I'm guessing this is GitHub caching the image.

On Tue, Jan 20, 2015 at 6:14 AM, Erik Bernoth <notifications@github.com>
wrote:

> Hi,
>
> my project <https://github.com/DFE/MONK/> doesn't show any errors, but
> the batch ([image: Documentation Status]
> <https://readthedocs.org/projects/monk-tf/?badge=latest>) still is not
> happy. Can't find anything in the docs
> <https://docs.readthedocs.org/en/latest/versions.html> or the FAQ
> <https://docs.readthedocs.org/en/latest/faq.html>. What to do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1127>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by erikb85** [comment]
yeah might be. Getting the green batch in the RTD Profile as well. Then I
simply look again tomorrow if it has changed. Thanks

**Comment by erikb85** [comment]
The other badges all updated by now, but as you might still see above the docs link didn't update (although loading the batch directly in the browser shows a green "latest"). Maybe there might be a [nearly hidden problem with how the HTTP response explains its caching desires](https://github.com/github/markup/issues/224#issuecomment-37663375). I'm not sure if you set the batch response headers yourself or if you use an external service for this. But maybe someone can have a look at that other issue and see if an improvement could be implemented.

**Comment by gregmuellegger** [comment]
Hm, seems like the referenced project is removed. For the badge URL we perform a redirect to the shields.io service. The 302 does not contain any caching information.

I guess we could add this to be ~5 Minutes or so.

**Comment by gregmuellegger** [comment]
Oh and we cache the badges up to 30 minutes in the Django level of things, since https://github.com/rtfd/readthedocs.org/commit/bf8931082f29ca1f6f3825b0d3bdc99edbcf537f

**Comment by ericholscher** [comment]
Believe this should be fixed, as it was an issue with our caching.
