### ISSUE TITLE
PDF generation is not built, with no errors

### ISSUE THREAD

**Issue by mickaelandrieu** [rtfd/readthedocs.org#1135]
Hi,

look at https://readthedocs.org/dashboard/blogbee-docs/, I don't know how to make the PDF to be generated.

The HTML build is ok, but no download is suggested and no PDF generation is done.

edit: this is not available with mkdocs.

Did you plan to add this feature ?

**Comment by agjohnson** [comment]
We're working on a solution that would give a lot of sphinx's power to markdown. But to answer your question, no, I don't think mkdocs is targeting PDF output.

**Comment by mickaelandrieu** [comment]
Hi @agjohnson, thanks.

Did you have a roadmap for kind of "markdown support" into sphinx ?

Regards,
