### ISSUE TITLE
accesskey for next, previous links

### ISSUE THREAD

**Issue by mblakele** [rtfd/readthedocs.org#1136]
It would be nice to have an `accesskey="n"` and `accesskey="p"` attribute on the next and previous links in the page footer and pagination widgets. This should improve accessibility without breaking any current behavior.

**Comment by agjohnson** [comment]
This should be an easy first but, it's low on our list though. Happy to provide guidance to anyone looking to address this.

**Comment by gregmuellegger** [comment]
I assume that's fixed as with snide/sphinx_rtd_theme#187 so closing it here.
