### ISSUE TITLE
Building successfully requires an _static directory

### ISSUE THREAD

**Issue by pydanny** [rtfd/readthedocs.org#1137]
I had to add a boilerplate text file in order to get our docs to build. Not a big deal, just letting you know!

Reference: https://github.com/eventbrite/eventbrite-sdk-python/commit/b3e76a80a2282171683ed722133f2eb3c379e81c

**Comment by gregmuellegger** [comment]
We'll consider this while building our new build system. Thanks for the report!

**Comment by stsewd** [comment]
I believe this issue is already solved, the `_static` directory is created if isn't found.

**Comment by agjohnson** [comment]
Closing for now, it sounds like this is solved.
