### ISSUE TITLE
Build failed: No space left on device

### ISSUE THREAD

**Issue by mstimberg** [rtfd/readthedocs.org#1140]
I'm not sure whether this is the right place to report this kind of problem, but our builds are currently failing with `[Errno 28] No space left on device`: https://readthedocs.org/builds/brian2/2268241/

Thanks

**Comment by ericholscher** [comment]
Sorry about that. We built a cleanup script last time this happened, but it
stopped working properly. Should be fixed now.

On Mon, Feb 2, 2015 at 4:48 AM, Marcel Stimberg <notifications@github.com>
wrote:

> I'm not sure whether this is the right place to report this kind of
> problem, but our builds are currently failing with [Errno 28] No space
> left on device: https://readthedocs.org/builds/brian2/2268241/
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1140>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by mstimberg** [comment]
Many thanks for the quick fix, it builds fine now.
