### ISSUE TITLE
Support for private bitbucket repo.

### ISSUE THREAD

**Issue by makailol** [rtfd/readthedocs.org#1144]
Hi,

Is it possible to use private instance of RTD with private bitbucket repo?
Also is there some option to use RTD without bitbucket or github repo ?

Thanks,
Makailol

**Comment by gigster99** [comment]
+1

**Comment by agjohnson** [comment]
We aren't looking to support private repositories with readthedocs.org, we only offer hosting for open source projects. Github and Bitbucket private repository support is built into readthedocs.com however.

There isn't a way currently to use RTD without a VCS backing, but we've thought about bringing the feature back. This would likely be a manual zip/tarball upload.

**Comment by gigster99** [comment]
Would you help me with this statement: "Bitbucket private repository support is built into readthedocs.com however."
We have a bitbucket repository. When it was in private status, RTD would not accept a repository URL in this format: https://_name_@bitbucket.org/_name_/sphinx_1.git. When we switched to a public repository and used this URL: https://bitbucket.org/_name_/sphinx_1.git the build was successful. Is there a method where we can build an RTD instance from a bitbucket access level is set to "This is a private repository"?

**Comment by agjohnson** [comment]
We don't support private repositories on readthedocs.org. We believe the value of RTD comes from projects being open source. You're welcome to host anything for free, as long as its liberally licensed.

Readthedocs.com is a separate product, focusing on companies that require private hosting. It has support for private repositories on github and bitbucket.

**Comment by gigster99** [comment]
Got it - missed the .com part of readthedocs. Glad to see the .com service is up and running - we'll use it.

**Comment by KylePiira** [comment]
For anyone who may come across this ticket, I was able to solve this problem by creating a public github repo dedicated to hosting the docs of my project while keeping the repo containing the proprietary code private. It's not ideal but considering RTD.org does not plan to support private repos and RTD.com charges very large fees it seems to be a good enough solution.

**Comment by pedrojuk** [comment]
Readthedocs.com does seem very expensive.  We would definitely use for our small-scale but commercial project if it were 1/5 of the price.  For now we will be forced to use @KylePiira 's approach.

**Comment by agjohnson** [comment]
For anyone considering working around our restriction of private repositories to host your commercial documentation, please consider at least donating money through a gold subscription for you project. It's entirely unfair to offload your commercial hosting on to volunteer labor without supporting our efforts in some fashion.

We don't offer a small paid plan on our commercial hosting as we tend to offer a lot of custom guidance to customers. If you're okay with a plan with no email support or a smaller amount of pageviews, feel free to contact us at hello@readthedocs.com and we can perhaps put together a small plan to get you started.
