### ISSUE TITLE
Custom mkdocs.yml with pages section doesn't work

### ISSUE THREAD

**Issue by michalwski** [rtfd/readthedocs.org#1145]
I'm wondering what can be wrong with our custom [mkdocs.yml](https://github.com/esl/MongooseIM/blob/manual-mkdocs-yml/mkdocs.yml) file. It looks like the build of the branch succeeded (https://readthedocs.org/builds/mongooseim/2288071/) but when I go the version http://mongooseim.readthedocs.org/en/manual-mkdocs-yml/ I got error 404.

I tried custom mkdocs.yml file without pages section and it worked correctly.

**Comment by ericholscher** [comment]
This is probably because you don't have an index.md file. We have code to move the README file into the index, but it might not work in that case which would be a bug on our side. I'll look into it today.

**Comment by michalwski** [comment]
@ericholscher any update on this issue?

**Comment by michalwski** [comment]
It's been a while since I opened the issue. Any progress or should I do a workaround on my own?

**Comment by d0ugal** [comment]
@michalwski we have recently updated MkDocs to the most recent version and I believe this should be resolved. Can you retest? You may need to trigger a build. Happy to reopen if it is still an issue.
