### ISSUE TITLE
GitHub application permissions seem excessive

### ISSUE THREAD

**Issue by chrisdembia** [rtfd/readthedocs.org#1149]
I hooked up my readthedocs account with GitHub, and the permissions that readthedocs requires seem excessive:

![image](https://cloud.githubusercontent.com/assets/846001/6093740/1d8390be-aec1-11e4-9134-524e5dae042d.png)

Why does readthedocs need any write permissions?

**Comment by agjohnson** [comment]
I believe this is a separate setting in Github that determines which of your orgs we have permission to query. The settings above that should list that we only have read access to organizations -- we are only requesting `read:org` oauth scope from github.

**Comment by destroyerofbuilds** [comment]
@chrisdembia, looks like pydy/pydy#112 has been resolved. Is anything further required here?

**Comment by agjohnson** [comment]
This can be closed for now, feel free to reopen if the github oatuh scope lists more than `read:org` here
