### ISSUE TITLE
confusing/misleading error message when two conf.py files exist

### ISSUE THREAD

**Issue by monkeypants** [rtfd/readthedocs.org#1151]
This is not a bug, just a very minor feature-tweek request.

I have two conf.py files in my repo (/conf.py and /tmp/conf.py). RTFD was unable to build my docs until I specified "conf.py" as the conf location in the advanced admin tab, rather than letting RTFD locate/choose the conf.py file for me. OK, fair enough, me having two conf.py files is a bit silly.

When the automatic locate/chose feature was failing, the error message in the logs was "unable to find conf.py". I was flumoxed for a while because it was right there, in the root of the repo. If the error said "I can find two conf.py files but don't know which one to use", it would have been much quicker for me to understand and fix the problem.

**Comment by agjohnson** [comment]
Our error reporting is lacking in general, we hope to improve this with a slight build refactor. I agree that the message should be more clear. It's low on our lists at the moment, but it'd be great to have a patch for this.

**Comment by ericholscher** [comment]
This should be fixed with #1524
