### ISSUE TITLE
autodoc_member_order does not support bysource

### ISSUE THREAD

**Issue by lwcolton** [rtfd/readthedocs.org#1162]
When I set 

autodoc_member_order = "bysource"

in my conf.py, it does not work when readthedocs.org builds my documentation.  However, when I use sphinx to build my documentation locally, it does work.

http://sphinx-doc.org/ext/autodoc.html#confval-autodoc_member_order

**Comment by ericholscher** [comment]
This is a Sphinx question, not a Read the Docs one.

**Comment by geertj** [comment]
Is readthedocs using an older version of Sphinx? I get the same issue.

Also the OP mentioned that he is able to build locally, and so am I. So I fail to see the logic of referring to Sphinx.

**Comment by lwcolton** [comment]
+1 definitely a read the docs problem and not something that can be
deferred to sphinx

**Comment by d0ugal** [comment]
ReadTheDocs is using Sphinx 1.3.1. The latest appears to be the latest version on PyPI. The Sphinx website states 1.3.2 tho which is odd.

https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L5

**Comment by gregmuellegger** [comment]
There is no 1.3.2 release so far, also the github page does not list one: https://github.com/sphinx-doc/sphinx/releases So I assume 1.3.2 is the current development version and not yet released.

@geertj @lwcolton are you using any development version of Sphinx locally? Can you see any oddities or warnings in the build log for your builds on RTD?

**Comment by geertj** [comment]
@gregmuellegger I have done some more investigation.

Version 1.3.1 supports ``'bysource'`` perfectly so that is not the issue.

After a lot of troubleshooting, it is working for me now. Unfortunately I have no idea which change made it work. Repo is at github.com/geertj/gruvi

**Comment by gregmuellegger** [comment]
Cool, glad to hear that it works now for you.

**Comment by rmk135** [comment]
Hey everybody,

I had the same problem and happy to share the solution with you, folks:

- if you want order 'bysource' to work well for your project, you do have to add your package to sys.path in your conf.py

... Hope it will help anyone
