### ISSUE TITLE
More extensive documentation on several configuration issues

### ISSUE THREAD

**Issue by mapa17** [rtfd/readthedocs.org#1165]
Hello,

I am searching for a more extensive documentation (i.e. compared to https://docs.readthedocs.org/en/latest/install.html )how to install and configure readthedocs.

I have followed the instruction on how to install rtd, setup a git server as the source of private and local repositories. I am able to build the readme files, but have several open issues that i am not able to solve following the documentation.

* Using the search function (besides installing elasticsearch and starting the server, what has to be done, do i have to index the generated html files?)
* In the left menu part of the documentation I can see the different MD files, but when viewing a single of them no sub menu points are generated for the headers in the readme.
* Using the official/online verison of rtd, it is possible to export pages to pdf, and other formats, using a small menu on the lower left side of the page. This menu is not present in my local installation, how can I enable it?

I know this is not the best form and place to post this collection of questions, but the IRC server freenode.net is not reachable, and it think it would be exaggerating to create a separate issue for each question.

**Comment by ericholscher** [comment]
If you would like to support docs around local installs, we would welcome the contribution. As it stands, we don't have time to officially support it.
