### ISSUE TITLE
Building big project takes half an hour?

### ISSUE THREAD

**Issue by bobmulder** [rtfd/readthedocs.org#1166]
I got the following message:

`Whoa! The build queue is 132 tasks long, new builds may take a while.`

But, building is currently taking half an hour. Is that normal?

**Comment by agjohnson** [comment]
Yes, build processing is periodically a bottleneck. We've rolled out more builders and have plans to speed things up a bit, but this is normal behavior during a queue back up

**Comment by bobmulder** [comment]
Thanks ;) What helped is setting up the webhooks again in GitHub. Sometimes the webhook is sent but  the build keeps `building` without passing or failing ;) Good luck ;)
