### ISSUE TITLE
Forgot email and password

### ISSUE THREAD

**Issue by k4ml** [rtfd/readthedocs.org#1167]
I know my username exists:-

http://readthedocs.org/api/v1/project/django-practical-guide/?format=json
http://readthedocs.org/api/v1/project/asas-django/?format=json
http://readthedocs.org/api/v1/user/?username=k4ml&format=json

Above are all my projects. I just can't remember anymore what email I used to register before. Is that any way I can get back my account ?

**Comment by ericholscher** [comment]
Sorry this got missed. You can reset your password here: https://readthedocs.org/accounts/password/reset/

**Comment by k4ml** [comment]
Thanks Eric. The problem is I can't remember the email address used for this account.
