### ISSUE TITLE
Read the docs notice shows on top of sidebar items

### ISSUE THREAD

**Issue by hach-que** [rtfd/readthedocs.org#1168]
See:

![image](http://i.imgur.com/mvzrdUM.png)

Also visible on http://protobuild.readthedocs.org/en/latest/getting_started.html.

**Comment by kmike** [comment]
+1. Firefox 36.0.4, OS X.

**Comment by agjohnson** [comment]
This is an old styling issue, and the theme was updated to resolve this issue, so should be resolved.
