### ISSUE TITLE
Better support for changing a project's VCS

### ISSUE THREAD

**Issue by steko** [rtfd/readthedocs.org#1170]
I recently moved my totalopenstation project from Mercurial to git, but RTD keeps looking for the `default` pathspec instead of `master`, and basically builds the same version again and again on every push.

Builds pass ([most recent here](https://readthedocs.org/builds/totalopenstation/2371817/)), but the _checkout_ section shows this error:

```
error: pathspec 'default' did not match any file(s) known to git.
```

Ideally there should be a way to explicitly set the pathspec, or some other mechanism to ensure builds don't get stuck in limbo.

Thanks

**Comment by lazka** [comment]
Same problem here: https://readthedocs.org/builds/quodlibet/2448497/

Not quite sure what to do..

**Comment by steko** [comment]
I worked around the problem by deleting and recreating the project, but that's not necessarily a viable option.

PS kudos for quodlibet, it's awesome software.

**Comment by lazka** [comment]
Thanks for the tip. Just when I wanted to delete/recreate I saw the "Default branch:" setting under "Advanced Settings". Setting that to "master" seems to work.

**Comment by steko** [comment]
It did not work for me, I should have mentioned this in the issue report.

**Comment by gregmuellegger** [comment]
I think changing the default branch should do the trick as lazka pointed it out. But it's strange that it didn't work for the totalopenstation project.

I'm re-targeting the ticket to better support changing the VCS type of a project. Maybe testing that changing the default branch works might be enough with some help text on the VCS type field that you should consider changing the default branch when changing the VCS type.

**Comment by agjohnson** [comment]
This ticket has gone a bit stale, so I'm just going to close this as an edge case users don't encounter a lot. It seems it's possible to switch VCS backends, you might just need to wipe your environment in between changes.
