### ISSUE TITLE
errors in hyperlinks in getting_started.html

### ISSUE THREAD

**Issue by vinceskahan** [rtfd/readthedocs.org#1171]
In https://read-the-docs.readthedocs.org/en/latest/getting_started.html#in-rst there are two links to the beginners template that use the text "this template" that point to missing pages.

I'm guessing the link you are trying to reference http://docs.writethedocs.org/en/latest/writing/beginners-guide-to-docs.html perhaps (?)

**Comment by agjohnson** [comment]
Indeed, looks like this was patched. Thanks for the report!
