### ISSUE TITLE
Markdown Downloadable PDF

### ISSUE THREAD

**Issue by alijaya** [rtfd/readthedocs.org#1174]
Hmmm... Is it only me or if I use Markdown, I can't download the pdf version of it?

**Comment by agjohnson** [comment]
Correct, mkdocs output is limited. We hope to have a solution to markdown pdf builds soon.

**Comment by alijaya** [comment]
Do you have any workaround with this?

**Comment by agjohnson** [comment]
We do not, this would be an issue to bring up with mkdocs
