### ISSUE TITLE
Project version slugging need to respect slashes

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1176]
Project versions with slashes don't match the regex for reverse path resolution:

    NoReverseMatch: Reverse for 'project_version_detail' with arguments '(u'cffi', u'the_drow/ensured-that-enums-cannot-be-declared-wi-1410868467138')' and keyword arguments '{}' not found. 1 pattern(s) tried: ['dashboard/(?P<project_slug>[-\\w]+)/version/(?P<version_slug>[-\\w.]+)/$']

Version slugging or url pattern matching should respect extra characters

**Comment by funsim** [comment]
Im hitting this issue as well.

**Comment by arigo** [comment]
Can you at least ignore such branch names and let the page go through?  I'm quite annoyed because I cannot access this versions page to create a "release-0.9" version, at https://readthedocs.org/dashboard/cffi/versions/ ...

**Comment by arigo** [comment]
To work around the blocker, I removed the whole project, and set up a different project going to a different repo.  For now I manually copy just the doc changes to this new repo, with no strange branch name.

**Comment by gregmuellegger** [comment]
I started working on this in #1362

**Comment by gregmuellegger** [comment]
This was fixed with the merge of #1362

**Comment by arigo** [comment]
I don't know if it is the same issue, but I still get the "ascii whale" picture with "Fail.  Check back in a bit!" if I log in (arigo) and try to go to the page https://readthedocs.org/projects/pypy/versions/ .  If you want to look inside the logs, I tried to reload several times in the seconds before I posted this.

**Comment by gregmuellegger** [comment]
It is a slightly different one. But just so slightly. I fixed it in #1396 (and checked in a local installation with the pypy project that it fixes the issue). The problem were uppercase letters in the branch name, in your case it was `SomeChar-charclass`. The issue should be finally resolved when the PR gets deployed.

**Comment by gregmuellegger** [comment]
@arigo is this fixed for you now?

**Comment by arigo** [comment]
Yes, thanks!
