### ISSUE TITLE
Broken search when using a newer version of Sphinx

### ISSUE THREAD

**Issue by vitaut** [rtfd/readthedocs.org#1178]
For the [AMPL/MP](https://github.com/ampl/mp) project I need to use the latest version of Sphinx because of the issues with C++ support in version 1.2.2 installed on https://readthedocs.org/. To this end I use the following requirements file:

```
-e git+https://github.com/sphinx-doc/sphinx.git@04e3e761d7d23545aedf633fa8b395399de6255f#egg=sphinx
```

[The docs](http://mp.readthedocs.org/en/latest/) are built fine and show the correct Sphinx version (1.3b3+), but search is broken because the old version of [`searchindex.js`](http://mp.readthedocs.org/en/latest/searchindex.js) is used. Note that `envversion` is 42, while in the Sphinx version I'm using it should be 46.

**Comment by vitaut** [comment]
So, I managed to workaround this by adding a `setup.py` script that uninstalls old version of Sphinx. However, this looks rather hackish. Is there a better was to use a specific version of Sphinx on readthedocs.org?

**Comment by ericholscher** [comment]
Believe this has been fixed. We're on Sphinx 1.3 with working search.
