### ISSUE TITLE
Build is stuck oscillating between Installing and Building

### ISSUE THREAD

**Issue by vitaut** [rtfd/readthedocs.org#1179]
The build https://readthedocs.org/builds/mp/2390885/ started 2.5 hours ago, but it doesn't show any progress, only the status changes between Installing and Building all the time. Usually the build takes a minute.

**Comment by vitaut** [comment]
There is a week's worth of stalling builds now:
![screenshot from 2015-03-12 11 20 52](https://cloud.githubusercontent.com/assets/576385/6624930/f33320d8-c8a9-11e4-905b-9f1694d1ec21.png)

Is there a way to at least cancel them?

**Comment by ericholscher** [comment]
They time out after 10 minutes on the build server, and must not be getting
cleaned up in the database. Guessing there is a loop or something happening
in your build code, does it work locally?

On Thu, Mar 12, 2015 at 11:22 AM, Victor Zverovich <notifications@github.com
> wrote:

> There is a week's worth of stalling builds now:
> [image: screenshot from 2015-03-12 11 20 52]
> <https://cloud.githubusercontent.com/assets/576385/6624930/f33320d8-c8a9-11e4-905b-9f1694d1ec21.png>
>
> Is there a way to at least cancel them?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1179#issuecomment-78555771>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by vitaut** [comment]
There is no loop in the code, but the [commit that got stuck](https://github.com/ampl/mp/commit/6197e9f97f7142498e2cf7adaf7bcd27dc9bb633) tried to uninstall Sphinx to replace it with a new version as a workaround for #1178.

**Comment by ericholscher** [comment]
It seems to be timing out on setup.py install -- guessing because it has a
large dependency chain, and that is making it hit the build time limit on
our side.

On Thu, Mar 12, 2015 at 11:37 AM, Victor Zverovich <notifications@github.com
> wrote:

> There is no loop in the code, but the commit that got stuck
> <https://github.com/ampl/mp/commit/6197e9f97f7142498e2cf7adaf7bcd27dc9bb633>
> tried to uninstall Sphinx to replace it with a new version as a workaround
> for #1178 <https://github.com/rtfd/readthedocs.org/issues/1178>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1179#issuecomment-78560626>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by vitaut** [comment]
So could you cancel these builds and, perhaps, make the builds that hit time limit fail in the future instead of being stuck?

**Comment by vitaut** [comment]
Tried removing `setup.py` but still no luck:

```
Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 2338, in <module>
    main()
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 824, in main
    symlink=options.symlink)
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 984, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 1276, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/home/docs/checkouts/readthedocs.org/user_builds/mp/envs/latest/bin/python'
```

**Comment by ericholscher** [comment]
Closing this, as it was likely a transient build issue, and new versions of these docs seem to be building properly.
