### ISSUE TITLE
Versions page crashes if the project has a branch named with a hash

### ISSUE THREAD

**Issue by amercader** [rtfd/readthedocs.org#1181]
If the project you are managing has a branch with a `#` character on its name, the version page will crash if you are logged in and you are not able to manage them:

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```
This happens both in https://readthedocs.org/projects/*/versions/ and https://readthedocs.org/dashboard/*/versions/

Maybe related to #1176

**Comment by agjohnson** [comment]
This is the same issue as #1176, closing this as a duplicate
