### ISSUE TITLE
RTD not sorting files/folders in alphabetical order

### ISSUE THREAD

**Issue by karai17** [rtfd/readthedocs.org#1183]
The order in which RTD sorts the navigation is seemingly random, as can be seen [here](http://dominatrix.readthedocs.org/en/latest/). Is there a way to override the default sort method to be alphabetical?

**Comment by karai17** [comment]
My submitting my own `mkdocs.yml` file I was able to define my own navigation order. I still think that if no YAML file is provided, RTD should try to default to alphabetical.

**Comment by agjohnson** [comment]
We only do what mkdocs does by default. Consider raising this issue with mkdocs perhaps? Closing this here for now.
