### ISSUE TITLE
Files not in subfolders appear to not have proper navigation

### ISSUE THREAD

**Issue by karai17** [rtfd/readthedocs.org#1184]
All of my markdown files contain h1 tags via `#`. As you can see in the pictures below, my "Syntax" file which is not in a subdirectory does not have expanded navigation, whereas "Inline Elements" and any other file within a subdirectory seem to work just fine.

![](http://puu.sh/gyhgU/981bc637c3.png)

![](http://puu.sh/gyhlm/b3200f988f.png)

**Comment by agjohnson** [comment]
This also looks like it could be a mkdocs issue. Can you reproduce locally on mkdocs build?

**Comment by agjohnson** [comment]
Assuming this is a mkdocs bug, not rtd. Reopen if neccessary.
