### ISSUE TITLE
Allow users to change theme

### ISSUE THREAD

**Issue by karai17** [rtfd/readthedocs.org#1191]
I would like to try other themes provided by mkdocs but it seems like no matter what I change the theme to, I am forced to use the RTD theme. :(

**Comment by marscher** [comment]
you can override this in your sphinx conf.py

**Comment by karai17** [comment]
I am not using sphinx, I am using the other one.

**Comment by d0ugal** [comment]
This is a duplicate of #978

**Comment by ericholscher** [comment]
Closing as dupe.
