### ISSUE TITLE
Support mkdocs CSS autolinking feature

### ISSUE THREAD

**Issue by LPGhatguy** [rtfd/readthedocs.org#1192]
When mkdocs discovers a css file in the `docs` folder of your project, it'll automatically link it into every document in the tree. RTD doesn't do this.

A fix for me (since I'm using autogenerated documentation) is to generate a style linking directive at the top of every file I create. This isn't optimal though, since I have to compute relative links myself here and only here, since RTD translates relative links to be relative to the root of the site elsewhere.

**Comment by d0ugal** [comment]
#1313 is a duplicate of this, but contains more info so closing this in factor of it.
