### ISSUE TITLE
Lua Syntax Highlighting

### ISSUE THREAD

**Issue by LPGhatguy** [rtfd/readthedocs.org#1193]
Lua is a popular language, it should have syntax highlighting support in the RTD theme!

**Comment by kmike** [comment]
There is Lua support - see e.g. http://splash.readthedocs.org/en/latest/scripting-tutorial.html. 
Use 
```
.. code-block:: lua

    function foo()
    end
```

**Comment by LPGhatguy** [comment]
The code generated by markdown via mkdocs does not appear to have Lua syntax highlighting as far as I can tell.

It generates
```html
<code class="lua hljs">
function foo()
end
</code>
```

Output for this code block with the theme appears to be: http://i.imgur.com/eI2qoxT.png

**Comment by agjohnson** [comment]
This is likely more of a mkdocs issue, feel free to file a bug report there:
https://github.com/mkdocs/mkdocs/issues
