### ISSUE TITLE
Downloads page using https prefixed links, even if not using https

### ISSUE THREAD

**Issue by mrshoki** [rtfd/readthedocs.org#1194]
Hi, 

I am running RTD inside a container, and I currently don't have and want HTTPS activated. Unfortunately after building html, epub and zip html archive, the build download page lists  all the links with https prefixed and so links from the download page are broken.

Here is the rendered html:

```html
<div class="module-list-wrapper">
	<ul>
		<li class="module-item col-span">
			<a class="module-item-title" href="https://docs.myproject.org/projects/test-project/downloads/pdf/latest/">
			latest PDF
			</a>
		</li>
		<li class="module-item col-span">
			<a class="module-item-title" href="https://docs.myproject.org/projects/test-project/downloads/htmlzip/latest/">
			latest HTMLZip
			</a>
		</li>
		<li class="module-item col-span">
			<a class="module-item-title" href="https://docs.myproject.org/projects/test-project/downloads/epub/latest/">
			latest Epub
			</a>
		</li>
	</ul>
</div>
```

Looking at the code I don't see anywhere where this is added. Project model should return a relative path (`//<PRODUCTION_DOMAIN><path>`).

Any idea how I can change this behavior ?

Thanks,

**Comment by agjohnson** [comment]
The relevant code can be found at:
https://github.com/rtfd/readthedocs.org/commit/0425016d3c1931da7d07b7a0a27c953755ba3d52#L369-L380

But this is returning links without schemes, so there might be something else going on in your setup. If you have luck, a test case might be helpful here.

**Comment by ericholscher** [comment]
CLosing this, as we don't have enough information to debug it.
