### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by afelicioni** [rtfd/readthedocs.org#1199]
Just spotted by looking on https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/locale/it/LC_MESSAGES/django.po#L621 and following lines, where github points to `https://pip.pypa.io/en/latest/user_guide.html#requirements-files` the Transifex counterpart is using `http://www.pip-installer.org/en/latest/cookbook.html#requirements-files`

Meanwhile is fine to use in translations the legacy one?

**Comment by gregmuellegger** [comment]
Yes I can confirm that it's still that way. We probably need to `tx push` the files more oftenly. We should do it by hand for this time, but need a more automated way in the long run.

@ericholscher could you please push the current state of translation strings from master to transifex?

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/rtfd/readthedocs.org/issues/2844 and https://github.com/rtfd/readthedocs.org/issues/3329
