### ISSUE TITLE
ImproperlyConfigured: The SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by orotau** [rtfd/readthedocs.org#1200]
Getting the error message 'ImproperlyConfigured: The SECRET_KEY setting must not be empty' when trying to build documentation on readthedocs.org

**Comment by orotau** [comment]
I am *guessing* that this line https://github.com/stephenmcd/mezzanine/blob/master/docs/conf.py#L26
is being used and it links through to https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/project_template/settings.py
There is no SECRET_KEY setting. I put in a dummy secret key https://github.com/orotau/mezzanine/blob/master/mezzanine/project_template/settings.py#L346 and the docs compiled.
I would imagine that this is fixable within readthedocs.org

**Comment by agjohnson** [comment]
This is outside the scope of what we want to touch with third party code. If you have settings or build dependencies that would cause a failing build, they should be properly handled in your project or sphinx configuration.

**Comment by orotau** [comment]
ok thanks. Today, someone fixed this within the Mezzanine project. Not sure if the timing is related or coincidental... rtd is a great project btw!
