### ISSUE TITLE
Sphinx has changed the default theme

### ISSUE THREAD

**Issue by jcrmatos** [rtfd/readthedocs.org#1202]
Hello,

Sphinx has changed the default theme to 'alabaster' and the old 'default' is now called 'classic'.
Please allow RTD to accept both old 'default' and new 'classic' theme names.
Right now it does not build and returns the error
ThemeError: no theme named 'classic' found (missing theme.conf?)

Thanks,
JM

**Comment by dnephin** [comment]
Just hit this as well.  I think a sphinx upgrade would fix it.

**Comment by shabda** [comment]
I hit this as well. Please check https://readthedocs.org/builds/pysaml-test/2512830/ if you want to see a failed build.

**Comment by kejbaly2** [comment]
Looking for a workaround. Anyone got one to spare?

**Comment by kejbaly2** [comment]
Never mind; found your commit above :) Works for me! Thanks!

**Comment by svetlyak40wt** [comment]
Workaround is bad but better then nothing.

**Comment by gregmuellegger** [comment]
I think this should be fixed as readthedocs is using Sphinx 1.3.1 since this commit: 0ac37e2902d8e65864c60a38fedfdd114dec957f
Please comment here or open a new issue if this is still a valid issue for you.
