### ISSUE TITLE
Changing localhost to public IP

### ISSUE THREAD

**Issue by MonamiB** [rtfd/readthedocs.org#1203]
I am testing RTD to build our API docs implementation, so running a local installation of RTD in a virtualenv within a debian VM. The ./manage.py runserver command runs the RTD server successfully.
 
    Validating models...

    0 errors found
    March 25, 2015 - 03:11:57
    Django version 1.6.10, using settings 'settings.sqlite'
    Starting development server at http://127.0.0.1:8000/

To access the RTD admin console from my laptop browser (outside the VM) I would like to change the localhost to the public IP. For that, I changed the IP references in:
* /etc/hosts
* settings/sqlite.py (section Internal_ips, and a few other occurrences)

But, it continues to build the server at http://127.0.0.1:8000/

Where else should I be configuring this? What else should I be configuring?

**Comment by vinuthomas** [comment]
Try ./manage.py runserver 0.0.0.0:8000

**Comment by MonamiB** [comment]
Thanks! This works! Using it with a twist now :)

    ./manage.py runserver [VM IP ADDRESS]:8000
