### ISSUE TITLE
The "not latest" banner does not show if branch naming strategy changes

### ISSUE THREAD

**Issue by bmbouter** [rtfd/readthedocs.org#1207]
We changed our branch names from pulp-2.1, pulp-2.2, etc pulp-2.3, etc to 2.4-release 2.5-release, etc. I expect that the pulp-2.\* pages would show the "You are not using the most up to date version of the library. XXX is the newest version." but they don't.

Specifically on this page I expect it on this page: http://pulp-puppet-dev-guide.readthedocs.org/en/pulp-2.3/

I do see it on the 2.4-release page:  http://pulp-puppet-dev-guide.readthedocs.org/en/2.4-release/

This banner is produced through a javascript call on the page [here](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/readthedocs-doc-embed.js#L235). That call is made to the API handler [here](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/api/base.py#L141).

From some discussion on IRC it was suggested the issue is that distutils is getting the comparison wrong.

I feel that using the VCS tag is wrong for a version comparison given that sphinx explicitly sets this in conf.py.  http://sphinx-doc.org/config.html#confval-version

To implement a fix, when a RTD builder is built it should store the version in a way that the API handler can look at it without having to actually import conf.py.

**Comment by gregmuellegger** [comment]
Using the version number from `conf.py` seems like a good idea. But I'm not sure if that holds up in all situations. Maybe we can get some expert input on this from @agjohnson or @ericholscher here.

**Comment by bmbouter** [comment]
When I filed this issue I talked with @ericholscher. He indicated it would be difficult to do this in practice. Nevertheless, I maintain that RTD should use the version from `conf.py`. RTD is built around Sphinx and should not ignore the Sphinx version defined in `conf.py` in favor of its own. Not only is it theoretically wrong, but it makes the banners show up on the "latest" version in some cases which is wrong in practice.

**Comment by humitos** [comment]
I think we can divide this issue in two parts:

1. changing the style name version in the project

I would say that this is not more possible since the only supported way is semantic versioning (PEP440): http://docs.readthedocs.io/en/latest/versions.html?highlight=version#how-we-envision-versions-working

So, I think this is not a problem anymore.

```
>>> import unicodedata
>>> from packaging.version import Version
>>> version_name = '2.5-release'
>>> Version(unicodedata.normalize('NFKD', unicode(version_name)).encode('ascii', 'ignore'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/humitos/.pyenv/versions/rtd/lib/python2.7/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion("Invalid version: '{0}'".format(version))
packaging.version.InvalidVersion: Invalid version: '2.5-release'
>>> 
```

This is part of the code in RTD at https://github.com/humitos/readthedocs.org/blob/a0a29e8bbb454d9296b91492d31ecbee396fe1fa/readthedocs/projects/version_handling.py#L109-L115

2. read the version from `conf.py`

I'm not sure if we want this, but it's something that has to be decided by @agjohnson or @ericholscher I suppose.

**Comment by agjohnson** [comment]
I'm -1 on reading from conf.py. Every single `conf.py` has a version and release which is likely not maintained in 95% of cases. We tie to VCS concepts wherever possible, so I don't think it makes sense to treat conf.py as canonical for this information. I've rather wanted to automate this through our conf.py template, rather then respect the version/release setting in conf.py.

I think we have some overlapping tickets on how we actually want to support "latest version", so I'm going to close this.
