### ISSUE TITLE
using rtd on a local maschine with a webserver

### ISSUE THREAD

**Issue by mbedr** [rtfd/readthedocs.org#1213]
Hey there,

I want to use RTD on a webserver in a virtual maschine, with Ubuntu 14.04 as my operating system, for the documentation of my git repo. I should be local in my network for my team.
I've got some problems when I want to switch between two different versions on my RTD website. I can't make this change because the little window / feature doesn't open. It's the feature where I can make a pdf or change between the languages and so on.
The search-engine doesn't work either.

**Comment by agjohnson** [comment]
Check your host parameters for the API host, the built documentation references this. Also, you'll need to install elastic search. Closing this because there isn't any specific issue to address here. Feel free to reopen if you have a specific issue you would like to resolve.
