### ISSUE TITLE
How can i use Sphinx v1.3

### ISSUE THREAD

**Issue by shangguokan** [rtfd/readthedocs.org#1214]
conf.py
If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.3'

build message
Sphinx version error:
This project needs at least Sphinx v1.3 and therefore cannot be built with this version.

I need to use some new features of Sphinx v1.3, for exemple: option 'caption' of code-block
Some body know how can i build with v1.3 replace the v1.2.2 current?

**Comment by agjohnson** [comment]
We haven't rolled out support for 1.3.1 yet, parts of our theme are broken because of changes in 1.3. We expect a release in the next few weeks.

**Comment by agjohnson** [comment]
Just an update here -- Sphinx 1.3.1 support has been released, including support for captions.

**Comment by shangguokan** [comment]
Thanks cool!
