### ISSUE TITLE
mkdocs + Mathjax

### ISSUE THREAD

**Issue by tsdev** [rtfd/readthedocs.org#1217]
I am writing a documentation using `mkdocs`, I tried to install `mathjax` for rendering euations, however the math doesn't get rendered:
http://spinw.readthedocs.org/en/latest/doc/
I included a conf.py file in the main folder of my docs with the following string:
`mathjax_path = '//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML'`
On my local `mkdocs` server math gets rendered (at least for the `$$...$$` noation).
Is there anything else I have to do to make math rendered on readthedocs.org?
Thanks!

**Comment by d0ugal** [comment]
`mathjax_path` isn't a MkDocs configuration option. I am not a mathjax users, but you can see a MkDocs user got it working with these settings: https://github.com/mkdocs/mkdocs/issues/356#issuecomment-96358772

**Comment by ericholscher** [comment]
Closing this, as it's a mkdocs issue, not a Read the Docs one.
