### ISSUE TITLE
PDFs for Django haven't updated since October

### ISSUE THREAD

**Issue by timgraham** [rtfd/readthedocs.org#1219]
The PDF for 1.8 is missing: https://media.readthedocs.org/pdf/django/1.8.x/django.pdf and the other PDFs haven't updated since October 2014:
* https://media.readthedocs.org/pdf/django/1.7.x/django.pdf
* https://media.readthedocs.org/pdf/django/latest/django.pdf

We had [the same issue for 1.7](https://code.djangoproject.com/ticket/22519#comment:2). Not sure if the root cause is the same or different.

**Comment by ericholscher** [comment]
This should be fixed (again). Sorry about that. There 1.8 PDF is up, and I
will rebuild 1.7 so it updates as well.

On Thu, Apr 9, 2015 at 6:31 AM, Tim Graham <notifications@github.com> wrote:

> The PDF for 1.8 is missing:
> https://media.readthedocs.org/pdf/django/1.8.x/django.pdf and the other
> PDFs haven't updated since October 2014:
>
>    - https://media.readthedocs.org/pdf/django/1.7.x/django.pdf
>    - https://media.readthedocs.org/pdf/django/latest/django.pdf
>
> We had the same issue for 1.7
> <https://code.djangoproject.com/ticket/22519#comment:2>. Not sure if the
> root cause is the same or different.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1219>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by agjohnson** [comment]
I believe this was fixed with: https://github.com/rtfd/readthedocs.org/commit/acf7557e700d0f39a4b8bf57666ea16aa0eb88d5
