### ISSUE TITLE
Translation projects are not found

### ISSUE THREAD

**Issue by tobias47n9e** [rtfd/readthedocs.org#1220]
When I try to add a translation to a RTD project under `Admin -> Translations` I get the error:

> Project https://github.com/tobias47n9e/innsbruck-stereographic/tree/master/docs_int/de was not found

I tried around with other URLs to see if I made a mistake, but at this point I think that the web-form has a bug.

The RTD-project is here: https://readthedocs.org/dashboard/innsbruck-stereographic

**Comment by agjohnson** [comment]
This isn't a bug, but it could definitely be done better. The form isn't clear about what it's asking for.

To link a translation, enter the project name as it exists in read the docs -- ie. 'innsbruck-stereographic'

**Comment by tobias47n9e** [comment]
Thank you. That turned out to be rather easy. I now also figured out how to assign different relative directories to different `conf.py` files. Going multilingual is not as hard as I thought it would be.
