### ISSUE TITLE
Broken Search

### ISSUE THREAD

**Issue by jimmyjames** [rtfd/readthedocs.org#1222]
Search just hangs - any simple search on readthedocs just hangs: http://docs.readthedocs.org/en/latest/search.html?q=version&check_keywords=yes&area=default#

This is also happening in my docs project (docs.smartthings.com).

**Comment by d0ugal** [comment]
I'm seeing this too, it appears to be broken on all the sites I've tried. I think it is related to a JavaScript error, I'm seeing this error:

    Uncaught TypeError: Cannot read property 'waypoint' of null

That happens here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static/core/js/readthedocs-doc-embed.js#L242

**Comment by jimmyjames** [comment]
Yes, I see a recent commit merged in changes that should avoid that error, but looks like RTD hasn't been rebuilt with that change?

**Comment by d0ugal** [comment]
Possibly, I'm not sure. I had a look at the recent changes and I couldn't see anything obviously related but I don't know the code well at all.

**Comment by jimmyjames** [comment]
It looks like this commit would fix it: https://github.com/rtfd/readthedocs.org/commit/2cc53f31eed576106856080e57a3752fd8e0a50f

Specifically, the change to readthedocs-doc-embed.js. I don't know how RTD is built, so not sure why we're still seeing this issue. Broken search for this many days, on RTD itself and most sites using it... is not good!

**Comment by d0ugal** [comment]
If that does indeed fix it, I'd guess a deploy is needed. Given that PyCon.us just happened, I expect much of the team have been busy.

**Comment by agjohnson** [comment]
Yes, we're a bit behind after PyCon, sorry for not chiming in on this sooner. A fix is deployed for search, I'm working on a more permanent change this morning.

**Comment by d0ugal** [comment]
Much appreciated, thanks very much!

**Comment by agjohnson** [comment]
Calling this resolved, the underlying cause was the above changeset merged with https://github.com/rtfd/readthedocs.org/commit/8313d3108c101798593268228506003bf40e2aa5

**Comment by rened** [comment]
@agjohnson just for clarification, should search work again already or does the fix still need to be deployed? currently, http://docs.readthedocs.org/en/latest/search.html?q=version&check_keywords=yes&area=default# does not seem to work yet. thanks!

**Comment by d0ugal** [comment]
@rened That link works for me. Perhaps a caching issue?

**Comment by rened** [comment]
ha, you are right - didn't occur to me that that could be an issue. thx!
