### ISSUE TITLE
Websocket to localhost?

### ISSUE THREAD

**Issue by tisdall** [rtfd/readthedocs.org#1223]
When reviewing a build status I saw a shield icon in my address bar in Chrome.  It said that "This page is trying to load scripts from unauthenticated sources".  I looked in the javascript console and saw this:  

> Mixed Content: The page at 'https://readthedocs.org/builds/project/123/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://localhost:8088/websocket'. This request has been blocked; this endpoint must be available over WSS.

WebSocket on localhost???  I thought maybe the server was hacked or something but I then found it in the repo here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/builds/build_detail.html#L91  It's been in there for 3 years!  It looks like someone started working on implementing something and forgot about it.  Maybe this should be moved to a branch, tagged with a TODO comment, or stripped out.

**Comment by agjohnson** [comment]
Eeeks, yup, that's a whole bunch of test code that shouldn't be there. I'll just remove it.

**Comment by agjohnson** [comment]
Good catch, thanks for the report!
