### ISSUE TITLE
Survey: Docutils needs your help, how can we improve?

### ISSUE THREAD

**Issue by tony** [rtfd/readthedocs.org#1228]
Hi readthedocs contributors,

I'm helping out with the Docutils project, one of the most important, yet underrated python packages out there! For those who don't know, the Documentation Utilities are working underneath the hood of readthedocs to help sphinx build great documentation.

Docutils has its' own great documentation both on it's website and in the internals of it's code. You just have to look deep:

- http://docutils.sourceforge.net/docutils/statemachine.py
- http://docutils.sourceforge.net/docutils/parsers/rst/__init__.py

If any of you would like to help participate in the docutils project, you can check out the Docutils-develop list at http://docutils.sourceforge.net/docs/user/mailing-lists.html. Readthedocs.org and the documentation community relies heavily on docutils, perhaps some of you could join the conversation.

Since docutils is on SourceForge and most of open source activity is underway here, I'd like to get more understanding as to why docutils is so underrepresented.

**Users:** What do you think docutils could do to make things easier for users to understand reST and use docutils? Have you ever seen docutils' internals documentation? Documentation on the website? What is your experience, how could it be improved?

**Developers:** Are you interested in contributing to docutils? Have you tried? How was your experience? If not, what has prevented you? What could be improved?

**Comment by Juanlu001** [comment]
Hello @tony, thanks for bringing this up. I agree with you that docutils is both important and underrepresented, and I have considered these same questions in the past so let me give you my two cents.

As a **user** I find the docutils web documentation extremely difficult to navigate. 100 % of the times I rely on Google to find a specific topic. Putting aside the aesthetics, it's ironic that the package that powers RTD and Sphinx has such a bad user experience regarding its own documentation.

As a **developer** the one thing that discourages me from contributing is having to go through SourceForge. Last time I checked they were using subversion but I am not sure this is still true.

Hope you manage to bring docutils to the place it deserves, good luck!

**Comment by ericholscher** [comment]
Closing this, as it's not actually a bug. But good luck with docutils!

**Comment by tony** [comment]
Thanks for letting us have it open!
