### ISSUE TITLE
How to test new MkDocs versions with RTD

### ISSUE THREAD

**Issue by d0ugal** [rtfd/readthedocs.org#1231]
MkDocs releases can be troublesome (for example #1230 had to be rolled back) for ReadTheDocs. At the moment it is a bit of a black box, I don't know of a way I can explicitly test on Read The Docs and/or be notified of MkDocs specific errors.

I tried setting http://mkdocs.readthedocs.org/en/latest/ to build the documentation with a virtualenv, so it would then use a development MkDocs to build itself, this could be really useful for us. However, it looks like you then install MkDocs over the top afterwards?

If there is a reasonable way for me to set things up locally and test it that way, I could do this too but last time I tried to do this I got a bit stuck.

Is there something else I can be doing?

**Comment by ericholscher** [comment]
Any reason you can't run it locally? Pip requirements should take
precedence over versions that we install, so using the virtualenv on
RTD.org should also work.

On Wed, Apr 22, 2015 at 12:01 AM, Dougal Matthews <notifications@github.com>
wrote:

> MkDocs releases can be troublesome (for example #1230
> <https://github.com/rtfd/readthedocs.org/pull/1230> had to be rolled
> back) for ReadTheDocs. At the moment it is a bit of a black box, I don't
> know of a way I can explicitly test on Read The Docs and/or be notified of
> MkDocs specific errors.
>
> I tried setting http://mkdocs.readthedocs.org/en/latest/ to build the
> documentation with a virtualenv, so it would then use a development MkDocs
> to build itself, this could be really useful for us. However, it looks like
> you then install MkDocs over the top afterwards?
>
> If there is a reasonable way for me to set things up locally and test it
> that way, I could do this too but last time I tried to do this I got a bit
> stuck.
>
> Is there something else I can be doing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1231>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Or
http://ericholscher.com

**Comment by d0ugal** [comment]
This is what I tried, maybe I did something wrong. It was about 6 months ago that I did try this. I'll try again and report back.

**Comment by d0ugal** [comment]
So, I finally managed to find time for this. It worked first time, so I've no idea what I got wrong.
