### ISSUE TITLE
repo field in Project too small

### ISSUE THREAD

**Issue by sujaymansingh** [rtfd/readthedocs.org#1234]
Could the `repo` field in `Project` be extended from 100 chars to 255 please?
https://github.com/rtfd/readthedocs.org/blob/4937ebc40629de1987a23a7b189adda855e15284/readthedocs/projects/models.py#L64-L65

At the moment, if I want to use a private instance against a private github repo, I have to specify a token in the repo name (http://bash-shell.net/blog/2014/apr/19/private-read-docs-private-github-repo/)

This means the repo name is `https://<long-token-here>:x-oauth-basic@github.com/owner/repo` which often goes over 100 chars.

**Comment by destroyerofbuilds** [comment]
:+1:

**Comment by ericholscher** [comment]
Should be fixed.
