### ISSUE TITLE
Image relative paths aren't working correctly

### ISSUE THREAD

**Issue by mickmuzac** [rtfd/readthedocs.org#1237]
I've scoured the documentation for both RTD and Mkdocs looking for relevant information, but I've been unsuccessful so far. Locally, `mkdocs build` and `mkdocs serve` run without errors and serve everything correctly, including images.

On the live RTD page, image URLs contain an extra up directory `../` resulting in the image not being found. I could potentially fix this by moving the images to a parent directory, but then that will break the images on Github and on my local machine.

Here are the docs and the corresponding Markdown source:
http://sandboxdocs.readthedocs.org/en/latest/User%20Guide/terrain/index.html
https://github.com/adlnet/SandboxDocs/blob/master/docs/User%20Guide/terrain.md

The image at the top has this generated image tag:

`<img alt="" src="../.././images/terrain/terrain.htmlcd_Image0.png">`

from Markdown that looks like this:

`![](./images/terrain/terrain.htmlcd_Image0.png)`

This seems to be a bug. The **ONLY** reason the image seems like it's being properly loaded is because I copied my entire image directory up to its parent directory.

**Comment by d0ugal** [comment]
This is probably because ReadTheDocs are on an old version of MkDocs. I am fairly sure this has been fixed downstream.

There are some compatibility issues with upgrading that I am working on.

**Comment by ericholscher** [comment]
Closing this as a mkdocs issue. It should be fixed with an upgrade happening soon.

**Comment by mickmuzac** [comment]
Is there anywhere I can go to get news about this pending update?

**Comment by d0ugal** [comment]
You can follow along in my downstream issue. https://github.com/mkdocs/mkdocs/issues/554
