### ISSUE TITLE
Internet Explorer downloads epub files as zip files

### ISSUE THREAD

**Issue by timgraham** [rtfd/readthedocs.org#1239]
Example URL: http://media.readthedocs.org/epub/django/1.8.x/django.epub

Some Googling indicates this can be fixed by serving the files with the appropriate content type. For example, if using .htaccess: `AddType application/epub+zip .epub`

**Comment by ericholscher** [comment]
I went ahead and fixed this live. I will leave it open so we can fix it in
our deployment scripts as well, so it lives on into the future.

On Wed, Apr 29, 2015 at 4:08 AM, Tim Graham <notifications@github.com>
wrote:

> Some Googling indicates this can be fixed by serving the files with the
> appropriate content type. For example, if using .htaccess: AddType
> application/epub+zip .epub
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1239>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
This is now fixed on our deployment scripts.
