### ISSUE TITLE
Table of contents hides tree structure

### ISSUE THREAD

**Issue by SamB** [rtfd/readthedocs.org#1243]
For example, I'm looking at <http://deb-o-matic.readthedocs.org/en/0.20/>, and towards the bottom it seems like half the entries in the ToC are labeled "Parameters", with no indication that they're for subsections of the other half.

I've heard of a thing called "indentation"; might that not be useful here?

**Comment by ericholscher** [comment]
Thanks for the pointer to "indentation" -- The TOC Tree is generated based
on the headers of the items that are placed in it. Having the proper
structure will make it nest properly, with indentation and all.

On Thu, Apr 30, 2015 at 1:18 PM, Samuel Bronson <notifications@github.com>
wrote:

> For example, I'm looking at http://deb-o-matic.readthedocs.org/en/0.20/,
> and towards the bottom it seems like half the entries in the ToC are
> labeled "Parameters", with no indication that they're for subsections of
> the other half.
>
> I've heard of a thing called "indentation"; might that not be useful here?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1243>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
