### ISSUE TITLE
pip requirement django-pagination no longer exists in Git

### ISSUE THREAD

**Issue by Spedge** [rtfd/readthedocs.org#1244]
lo folks,

In pip_requirements.txt, there's a line for https://github.com/ericflo/django-pagination.git@e5f669036c which doesn't exist.

I'd fix it, but I don't know how critically important it is, or what it's used for.

Sorry :/

**Comment by Spedge** [comment]
And while we're at it, git+https://git@github.com/jMyles/bamboo_boy#egg=bamboo_boy probably isn't meant to be git@ either.

**Comment by destroyerofbuilds** [comment]
@Spedge, please see #1245

**Comment by agjohnson** [comment]
Addressing on the pagination module here, I believe this is just an outdated URI format. It should be in the form of: ```git+git://github.com/ericflo/django-pagination.git@e5f669036c```

**Comment by Spedge** [comment]
I don't see any commit in the pagination project with that id...

**Comment by destroyerofbuilds** [comment]
@Spedge, that's because `e5f669036c` is on the ericflo/django-pagination#dev branch.

Please see: https://github.com/ericflo/django-pagination/commit/e5f669036c

@agjohnson, why the form `git+git`?

Also, @Spedge, what error are you encountering with this requirement? I myself haven't run into any issues installing this dependency.

**Comment by Spedge** [comment]
There's no error - it just skips the dependency and doesn't include it, which perhaps isn't the desired behaviour. IMO either it should work, or we leave it out - save confusing folks.

**Comment by agjohnson** [comment]
@destroyerofbuilds `git+git://...` uri resolves correctly for me, the `http://...` uri throws a 404 when attempting a pip install.

**Comment by agjohnson** [comment]
Also, this dependency can not be left out, it is a requirement of RTD.

**Comment by destroyerofbuilds** [comment]
The installation using an unmodified version of `requirements/pip.txt` successfully installs django-pagination:

```bash
Downloading/unpacking django-pagination-dev from git+https://github.com/ericflo/django-pagination.git@e5f669036c (from -r requirements/pip.txt (line 78))
  Cloning https://github.com/ericflo/django-pagination.git (to e5f669036c) to ./venv/build/django-pagination-dev
  Could not find a tag or branch 'e5f669036c', assuming commit.
  Running setup.py (path:/.../venv/build/django-pagination-dev/setup.py) egg_info for package django-pagination-dev
```

@agjohnson, sorry. Meant to ask why `git+git://` over `git+https://`. The form `git+https://` seems to work for me, and seems to match the other GitHub requirements in `pip.txt`.

@Spedge, what version of ReadTheDocs are you using, and can you paste your installation output here?

**Comment by agjohnson** [comment]
@destroyerofbuilds ah gotcha, yeah `git+https://` would work just fine here

**Comment by ericholscher** [comment]
Closing this, as it doesn't seem to be an issue for me. If it is an issue, please send a pull request that fixes it.
