### ISSUE TITLE
bamboo_boy Pip URL Is Invalid SSH URL

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1245]
Splitting out an observation made by @Spedge regarding the following PIP requirement:

```
git+https://git@github.com/jMyles/bamboo_boy#egg=bamboo_boy
```

Because the URL contains an SSH scheme reference, `git@`, pip attempts to install over SSH. This fails for those that don't have SSH key access to the `bamboo_boy` project.

Using the #master branch of `readthedocs.org`, the requirements for this project can't be installed.

**Comment by destroyerofbuilds** [comment]
Also, it seems Travis-CI is not catching this issue. Could an SSH key, with access to `bamboo_boy`, be uploaded to the Travis-CI page for `readthedocs.org`?

**Comment by destroyerofbuilds** [comment]
Looks like this issue was introduced as part of bf2237baa0afb6d85b87c56f806b9aafdda564fc

Please let me know if you would like me to make a pull request to resolve the URL.

**Comment by agjohnson** [comment]
Good catch, yeah a PR updating to the correct HTTP url would be great

**Comment by Spedge** [comment]
I did, in the end, submit a PR even though @destroyerofbuilds did the legwork - mostly because I wanted to go through the process of doing one (creating a branch, doing a PR) when it was around a very simple change :)

Hope you don't mind too much @destroyerofbuilds ...

**Comment by destroyerofbuilds** [comment]
@Spedge, no problem.

Thanks for tackling this one!

**Comment by agjohnson** [comment]
Thanks @destroyerofbuilds & @Spedge! The PR was merged earlier, feel free to reopen if this is an issue still
