### ISSUE TITLE
Build error since last night

### ISSUE THREAD

**Issue by ronf** [rtfd/readthedocs.org#1255]
I'm new to ReadTheDocs and finally got my documentation ("asyncssh") building in it last night. However, when I tried it again today, the build is failing even though I haven't really changed anything, and it doesn't appear to be related to anything in my repo. The build error is:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 244, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/application.py", line 126, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 249, in <module>
    from recommonmark.parser import CommonMarkParser
  File "/home/docs/checkouts/readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/recommonmark/parser.py", line 37, in <module>
    class CommonMarkParser(object, parsers.Parser):
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Parser

Anyone know what might be going on?

**Comment by ericholscher** [comment]
Should be fixed, sorry about that.

On Tue, May 5, 2015 at 8:14 PM, Ron Frederick <notifications@github.com>
wrote:

> I'm new to ReadTheDocs and finally got my documentation ("asyncssh")
> building in it last night. However, when I tried it again today, the build
> is failing even though I haven't really changed anything, and it doesn't
> appear to be related to anything in my repo. The build error is:
>
> Traceback (most recent call last):
> File "/home/docs/checkouts/
> readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/cmdline.py",
> line 244, in main
> opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
> File "/home/docs/checkouts/
> readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/application.py",
> line 126, in *init*
> confoverrides or {}, self.tags)
> File "/home/docs/checkouts/
> readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/config.py",
> line 277, in *init*
> execfile_(filename, config)
> File "/home/docs/checkouts/
> readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/sphinx/util/pycompat.py",
> line 128, in execfile_
> exec_(code, _globals)
> File "conf.py", line 249, in
> from recommonmark.parser import CommonMarkParser
> File "/home/docs/checkouts/
> readthedocs.org/user_builds/asyncssh/envs/develop/local/lib/python3.4/site-packages/recommonmark/parser.py",
> line 37, in
> class CommonMarkParser(object, parsers.Parser):
> TypeError: Cannot create a consistent method resolution
> order (MRO) for bases object, Parser
>
> Anyone know what might be going on?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1255>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ronf** [comment]
Thanks so much for the quick response! It's working for me again.
