### ISSUE TITLE
features/* in docs/index.rst does not resolve

### ISSUE THREAD

**Issue by Spedge** [rtfd/readthedocs.org#1256]
lo,

I've spotted that the documentation under docs/features is not added to the page, even though the features/* rule is under the Features "_feature-docs" toctree.

Not sure when this was introduced as we only have the latest version of the docs :/

**Comment by agjohnson** [comment]
Could you include a link to the project?

**Comment by Spedge** [comment]
https://github.com/rtfd/readthedocs.org/blob/master/docs/index.rst

If you open it in raw, you'll see in the toctree

**Comment by ericholscher** [comment]
Believe this is working again.

**Comment by Spedge** [comment]
Yep, I can confirm this is working again. Not sure what's changed to make it work though :)
