### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by tisdall** [rtfd/readthedocs.org#1257]
When viewing http://docs.pylonsproject.org/projects/colander/en/latest/api.html the JS console says:

    XMLHttpRequest cannot load https://readthedocs.org/bookmarks/exists/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.pylonsproject.org' is therefore not allowed access.

This seems to be related to https://media.readthedocs.org/javascript/readthedocs-doc-embed.js:

            // ask the server if a bookmark exists for this page so we can show the proper icon
            $.ajax({
                    type: 'POST',
                    url: API_HOST + "/bookmarks/exists/",
                    crossDomain: true,
                    xhrFields: {
                      withCredentials: true,
                    },
                    data: JSON.stringify(data),
                    success: function (data) {
                      $(".bookmark-active").show();
                    },
                    error: function(data) {
                      $(".bookmark-inactive").show();
                    },
                    dataType: 'json'
            });

The relevant code is here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static/core/js/readthedocs-doc-embed.js#L150-165

**Comment by agjohnson** [comment]
The bookmarks feature is something that we need to move into the API and clean up, the implementation is just a first draft at this point. This would be a good area for contribution until we get to changing it.

**Comment by ericholscher** [comment]
We have removed bookmarks for now, so this should be fixed.
