### ISSUE TITLE
Affix for Menu doesn't work anymore

### ISSUE THREAD

**Issue by frontendphil** [rtfd/readthedocs.org#1258]
With the latest updates we experience an error with the sticky menu. When you scroll down the menu scrolls out of view. 

Also: just putting the ads right over the themed part of the sidebar looks plain ugly :) Cant you somehow stick that to the rtfd banner on the bottom?

![screen shot 2015-05-06 at 17 36 43](https://cloud.githubusercontent.com/assets/187786/7496772/80c275ba-f416-11e4-8b2c-b253b7f2846b.png)

**Comment by agjohnson** [comment]
Is this a fork or a customization of the rtd theme? Also, what is the actual project being built here?

**Comment by frontendphil** [comment]
It's a cutomization of the rtd theme. The project is called "effektif" or "effektif-de" respectively.

**Comment by gregmuellegger** [comment]
+1 on sticking it to the banner. It's also an issue on the unmodified rtd theme:
![screen6](https://cloud.githubusercontent.com/assets/88278/8522126/4407e056-23eb-11e5-80ae-5532a53a8c4c.png)

**Comment by ericholscher** [comment]
This is an issue with the theme, please open it at https://github.com/snide/sphinx_rtd_theme/ if it's still an issue.
