### ISSUE TITLE
Build failure after sphinx 1.3.1 upgrade

### ISSUE THREAD

**Issue by yxiong** [rtfd/readthedocs.org#1259]
I recently had a [build failure](https://readthedocs.org/builds/xy-python-utils/2715127/) which I believe is caused by the sphinx 1.3.1 upgrade (see #1250 and #1187), because the timeframe correlates, and I did not make any changes to my `docs` folder. Could you kindly look into this and let us know if there is something I could do from my side to fix the issue? Thanks!

    Traceback (most recent call last):
    ......
      File "/home/docs/checkouts/readthedocs.org/user_builds/xy-python-utils/envs/latest/local/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg/sphinx/environment.py", line 350, in find_files
        self.srcdir, config.source_suffix, exclude_matchers=matchers))
      File "/home/docs/checkouts/readthedocs.org/user_builds/xy-python-utils/envs/latest/local/lib/python2.7/site-packages/Sphinx-1.2.3-py2.7.egg/sphinx/util/__init__.py", line 94, in get_matching_docs
        suffixpattern = '*' + suffix
    TypeError: cannot concatenate 'str' and 'list' objects

**Comment by amercader** [comment]
We are having the same issue on our builds:

https://readthedocs.org/builds/ckan/2714358/

Also happy to help

**Comment by ericholscher** [comment]
Sorry, this was us depending on Sphinx 1.3+ -- should be fixed now.

On Thu, May 7, 2015 at 7:31 AM, Adrià Mercader <notifications@github.com>
wrote:

> We are having the same issue on our builds:
>
> https://readthedocs.org/builds/ckan/2714358/
>
> Also happy to help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1259#issuecomment-99888534>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by yxiong** [comment]
Yep, I just verified that the docs build was fixed for my repo. Thanks!

**Comment by amercader** [comment]
Thanks!
