### ISSUE TITLE
Generated link in left menu doesn't work in own domain (CName config) host.

### ISSUE THREAD

**Issue by aeng** [rtfd/readthedocs.org#1260]
Click on left menu regenerate links on the menu. 
http://zanata.readthedocs.org/ works fine, but when navigating through own domain http://docs.zanata.org/ (cname config), after first click, all the other links are broken.

**Comment by onewheelskyward** [comment]
This seems to be working now, does it look good from your end?

**Comment by aeng** [comment]
@onewheelskyward thats because I'm using the workaround, 

# workaround for issue: https://github.com/rtfd/readthedocs.org/issues/1260
use_directory_urls: false
