### ISSUE TITLE
Syntax error for Sphinx v1.1.3

### ISSUE THREAD

**Issue by dragoonis** [rtfd/readthedocs.org#1262]
Sphinx v1.1.3
Usage: /home/docs/checkouts/readthedocs.org/user_builds/ppi/envs/2.1/bin/sphinx-build [options] sourcedir outdir [filenames...]

So this build worked: https://readthedocs.org/builds/ppi/2719814/

Then all of a sudden this build and all future builds started failing:  https://readthedocs.org/builds/ppi/2720001/

**Comment by ericholscher** [comment]
Sorry, this was us depending on Sphinx 1.3+ -- should be fixed now.

On Thu, May 7, 2015 at 7:26 AM, Paul Dragoonis <notifications@github.com>
wrote:

> Sphinx v1.1.3
> Usage: /home/docs/checkouts/
> readthedocs.org/user_builds/ppi/envs/2.1/bin/sphinx-build [options]
> sourcedir outdir [filenames...]
>
> So this build worked: https://readthedocs.org/builds/ppi/2719814/
>
> Then all of a sudden this build and all future builds started failing:
> https://readthedocs.org/builds/ppi/2720001/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1262>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by dragoonis** [comment]
@ericholscher i am re-building now - I pinged you on IRC earlier but didn't hear from you.

**Comment by dragoonis** [comment]
@ericholscher I re-triggered the build - same issue: https://readthedocs.org/builds/ppi/2720572/

**Comment by ericholscher** [comment]
Ah, I believe we still require Sphinx 1.2+ -- We are passing arguments that
only exist in Sphinx 1.2. Is there a reason you're staying with such an old
version?

On Thu, May 7, 2015 at 8:56 AM, Paul Dragoonis <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher> I re-triggered the build
> - same issue: https://readthedocs.org/builds/ppi/2720572/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1262#issuecomment-99921247>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by dragoonis** [comment]
@ericholscher nope - if you can point out to me where i'm referencing old sphinx arguments, I can update my end.

**Comment by ericholscher** [comment]
Yep: https://github.com/ppi/docs/blob/2.0/requirements.txt

On Thu, May 7, 2015 at 9:04 AM, Paul Dragoonis <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher> nope - if you can point
> out to me where i'm referencing old sphinx arguments, I can update my end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1262#issuecomment-99922973>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by dragoonis** [comment]
@ericholscher what should I change it to? 1.2.0, 1.2.*  ?

**Comment by ericholscher** [comment]
1.3.1 is best, or just remove the dependency, and just say "Sphinx" which
will use the latest available.

On Thu, May 7, 2015 at 9:07 AM, Paul Dragoonis <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher> what should I change it
> to? 1.2.0, 1.2.* ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1262#issuecomment-99923826>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by dragoonis** [comment]
@ericholscher i hard coded it to 1.3.1 and it passed wonderfully, thank you!

One more thing now is, what's with all these crazy errors? https://readthedocs.org/builds/ppi/2720692/

**Comment by dragoonis** [comment]
@ericholscher all passing anyway - thanks for your help.
