### ISSUE TITLE
"sphinx-build not found" error in a Py3k venv

### ISSUE THREAD

**Issue by NYKevin** [rtfd/readthedocs.org#1263]
Possible duplicate of #994, but I'm not sure because I'm seeing weird Py3k errors.  Also, the latest branch is building successfully, but another branch is failing.

See e.g. https://readthedocs.org/builds/nbtparse/2722836/

Under build standard error:

    /bin/sh: 1: /home/docs/checkouts/readthedocs.org/user_builds/nbtparse/envs/version-0.5.0/bin/sphinx-build: not found

Under environment standard error:

```
Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/lib/python3.4/base64.py", line 9, in <module>
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/home/docs/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

If the branch+project name is too long, I'm stumped.  Making my tags any shorter would make the repository potentially confusing for human users, since I use a mixture of tags, branches, and bookmarks.  Worse, tag and branch names are (mostly) permanent in the Mercurial data model.  Any advice?

**Comment by paternal** [comment]
Same problem here. Compilation of most of my projects stopped working without any change to the repository. And here either, neither project name nor branche name seems to be too long. Examples of failed compilation : [pdfautonup](https://readthedocs.org/builds/dummypdf/2730457/) [dummypdf](https://readthedocs.org/builds/pdfautonup/2730460/).

**Comment by estin** [comment]
seems like some problems in virtualenv version or or PATH environ variable (some hooks?)

```
venv
-----

Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/lib/python3.4/base64.py", line 9, in <module>
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/home/docs/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. Either you are trying to run from the p
```

virtualenv running under python2.7, but have some imports from python3.4 in this traceback

Sorry for my poor English

**Comment by ericholscher** [comment]
This appears to be a bug with Python or Virtualenv. When we run ``virtualenv-2.7 -p python3 venv`` it breaks with that error.

**Comment by ericholscher** [comment]
I talked with @dstufft about work arounds, but there doesn't appear to be much we can do currently.

**Comment by dstufft** [comment]
One option is to install virtualenv into Python 3 and run ``python3 -m virtualenv`` instead of ``virtualenv -p python3``

**Comment by NYKevin** [comment]
>When we run `virtualenv-2.7 -p python3 venv` it breaks with that error. 

In my experience, trying to use the 2.7 version of Virtualenv to create a 3.x venv doesn't tend to work very well, at least on Ubuntu.

**Comment by makmanalp** [comment]
I'll also put in a +1, I'd be happy to test out any workarounds.

**Comment by zmwangx** [comment]
My experience with creating a py3k virtualenv with virtualenv 2.7 is the opposite; never had a problem, if I recall correctly. I'm on OS X though.

```
> virtualenv-2.7 --version
1.11.6
```

**Comment by makmanalp** [comment]
The odd thing is while I was fiddling with settings I had gotten it to work at some point: 

- http://atlas-core.readthedocs.org/en/latest/
- https://readthedocs.org/builds/atlas-core/2742932/

So I'm confused as to how that ever happened. Here's a recent failure: https://readthedocs.org/builds/atlas-core/2742978/

**Comment by zmwangx** [comment]
@ericholscher By the way, since you already have py3k installed anyway, why can't you just invoke `virtualenv-3.4` to create a py3k virtualenv?

**Comment by makmanalp** [comment]
OK, so funny discovery, I thought I figured out that it works when a github push triggers the build, but not manually! Check it out:

https://readthedocs.org/builds/atlas-core/2743001/

But then I triggered it manually again and it works again!

https://readthedocs.org/builds/atlas-core/2743009/

**Comment by NYKevin** [comment]
Hm... bug seems to be transient.  A manual trigger worked for me, too.

**Comment by cjw296** [comment]
Same thing for me: github push fails, manual trigger works. Any eta on a fix?

**Comment by takluyver** [comment]
So long as virtualenv is installed on Python 3, #1316 should fix it (using @dstufft's suggestion - thanks!)
