### ISSUE TITLE
Problems with build of my project from pypi

### ISSUE THREAD

**Issue by ziky5** [rtfd/readthedocs.org#1265]
I'm sorry for opening this as an issue, as it is more a question, but I don't where else to ask.

I have created a doc at https://readthedocs.org/projects/probe-spherical-pic-docs/, the docs are hosted at https://bitbucket.org/ziky2/probe-spherical-pic-docs. Everything works well until I decided to include  a auto-generated documentation from one of my packages hosted at pypi (probe-data-process). This project depends on several other packages (Numpy, Scipy, ...), so according to FAQ I have created Mock objects for all of them in conf.py to make my package importable. So far so good.

The problem arose when I tried to build docs at readthedocs. I specified my two projects in pip requirement file and those packages has few dependencies in their setup.py (again Numpy, Scipy, ...). The server on the readthedocs tried to install these libraries faild (matplotlib and bokeh, I think). So, is there a way how to tell that I don't want to install dependencies (`--no-deps` option for `pip install`)? I tried to use requirement file but I wasn't successful.

As I was hopeless I commented out dependencies in my setup.py files and build it. It went well and I finally built my documentation on readthedocs. But now, I'm not able to build it again, server always say:
```
Requirement already satisfied (use --upgrade to upgrade): probe-data-process in /var/build/user_builds/probe-spherical-pic-docs/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): probe-plotting in /var/build/user_builds/probe-spherical-pic-docs/envs/latest/lib/python2.7/site-packages (from -r requirements.txt (line 2))
```

How to reinstall my packages on the server?

How to install my packages without dependecies specified in the setup.py file?

I'll be really grateful for any response or help, as I'm clearly doing something wrong.

Thanks.

**Comment by ericholscher** [comment]
Hmm, this is tricky. I don't know the best way around it. I believe you can specify pip options to install in the requirements file? We can't really add ``--no-deps`` on our side for all users.

**Comment by gregmuellegger** [comment]
@ziky5 You should be able to cleanup the virtualenv on the build server for your project by clicking the *Wipe* button in the versions page of your project. Then you can trigger a new build on the *Builds* page.
