### ISSUE TITLE
github-style code fences (triple backticks) with language don't render correctly

### ISSUE THREAD

**Issue by maxogden** [rtfd/readthedocs.org#1267]
this renders as expected:

![screen shot 2015-05-12 at 10 17 08 am](https://cloud.githubusercontent.com/assets/39759/7593609/414fe826-f890-11e4-8022-9fa40c49fe9c.png)

but this renders incorrectly:

![screen shot 2015-05-12 at 10 20 00 am](https://cloud.githubusercontent.com/assets/39759/7593637/79686eb8-f890-11e4-8ec5-861d3ae57264.png)

![screen shot 2015-05-12 at 10 20 23 am](https://cloud.githubusercontent.com/assets/39759/7593643/8577e5bc-f890-11e4-85f0-a9e12fafcaaa.png)

example: https://raw.githubusercontent.com/maxogden/dat/29359bb9408765dabf429187d7292bd02cf79e0b/beta-cli-api.md
wonky render: http://datproject.readthedocs.org/en/latest/getting-started/

**Comment by onewheelskyward** [comment]
I'm going to test this out, but is there any chance that ```bash syntax is github-flavored markdown?

**Comment by maxogden** [comment]
@onewheelskyward thanks! according to https://help.github.com/articles/github-flavored-markdown/ the triple backticks (with or without the language) aren't part vanilla markdown

**Comment by agjohnson** [comment]
Correct, mkdocs only supports vanilla markdown

**Comment by maxogden** [comment]
@agjohnson how come it supports \`\`\` but not e.g. \`\`\`js? seems weird to support one but not the other (since neither is vanilla markdown)

**Comment by agjohnson** [comment]
Agreed, it's a symptom of the spec being ill-defined. It's these cases I remind folks that Sphinx has already addressed this issue :)

I believe mkdocs uses the code fencing additions from the python Markdown module, not sure why they didn't implement the full github flavored markdown additions:
https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html

Eventually, RTD will support commonmark, which will address extensions in a proper way, but this still won't support the github flavor additions:
http://spec.commonmark.org/0.19/#fenced-code-blocks
