### ISSUE TITLE
Transfer ownership of "pythondotorg" project

### ISSUE THREAD

**Issue by berkerpeksag** [rtfd/readthedocs.org#1272]
Hi,

I would like to serve [python.org's development documentation](https://github.com/python/pythondotorg/tree/master/docs) on Read the Docs, but someone else already registered a fork of the project on Read the Docs:  https://readthedocs.org/projects/pythondotorg/

I emailed them about the subject almost a week ago, but didn't get any reply.

Is it possible to move the "pythondotorg" project to my account(my username on Read the Docs is [berkerpeksag](https://readthedocs.org/profiles/berkerpeksag/))? I'm obviously not the owner of the [python/pythondotorg](https://github.com/python/pythondotorg) repository itself, but I'm a [contributor](https://github.com/python/pythondotorg/graphs/contributors) to the project and also a CPython core developer.

Thanks!

**Comment by ericholscher** [comment]
Went ahead and added you as an admin.
