### ISSUE TITLE
Useless scrollbar in Firefox 37

### ISSUE THREAD

**Issue by untitaker** [rtfd/readthedocs.org#1276]
![2015-05-19-183004_310x784_scrot](https://cloud.githubusercontent.com/assets/837573/7708327/23293396-fe55-11e4-8ae3-b38b9501d62a.png)

I've tried disabling HTTPS Everywhere and AdBlock, neither do anything.

**Comment by onewheelskyward** [comment]
What OS are you running?

**Comment by untitaker** [comment]
Archlinux

**Comment by onewheelskyward** [comment]
Confirmed in Arch 5.01, Firefox 38.

**Comment by untitaker** [comment]
Use `overflow:auto`, it works.

**Comment by agjohnson** [comment]
I've noticed this completely intermittently on OSX in chrome and safari as well -- i'll get a patch in to the theme shortly

**Comment by agjohnson** [comment]
This is an issue with the theme, I've moved it there: snide/sphinx_rtd_theme#200
