### ISSUE TITLE
ToC tree doesn't work with Markdown?

### ISSUE THREAD

**Issue by olasitarska** [rtfd/readthedocs.org#1277]
Hi everyone!

So I tried to publish my first docs on RTD last night, and it almost worked perfectly :) My docs are written in Markdown, so I downloaded MkDocs, changed locally theme to RTD theme. Then I made corrections to my docs so all the headers have the right level, which made [my ToC](http://cl.ly/image/3w2m211L2M3x) looks locally as I wanted them to look. 

[Today I pushed everything to RTD](http://djangae.readthedocs.org/en/latest/), but the ToC only renders the main chapter names, not subchapters :( 

I looked into RTD docs, I found [this](http://docs.readthedocs.org/en/latest/theme.html#how-the-table-of-contents-builds), but it only applies to Sphinx. I looked into RTD code, but couldn't find anything that could be helpful to debug this. 

So, my question is:
- Does RTD support tree-like TOC for Markdown and I'm just doing something wrong?
- If not, Is there a way I can improve RTD to add support for that? I'd be happy to work on a PR if you point me in the right direction :)

Sorry if this problem has been raised somewhere here, I couldn't find it. Huge thanks for your awesome work on this, y'all rock! :tada:

**Comment by d0ugal** [comment]
I suspect this is related to ReadTheDocs running an old version of MkDocs. I am working on updating it this week after I roll a new MkDocs release with a ton of fixes.

**Comment by olasitarska** [comment]
Yay! Thanks @d0ugal.

**Comment by d0ugal** [comment]
FWIW, I have started tracking this downstream as I get some confused users that I want to point somewhere :) https://github.com/mkdocs/mkdocs/issues/554

**Comment by d0ugal** [comment]
@olasitarska Read the docs is now running the latest MkDocs. Can you check if it has been resolved for you? You may need to trigger a new build.

**Comment by olasitarska** [comment]
Works beautifully, thanks @d0ugal! :sparkles:

**Comment by sahilTakiar** [comment]
Hey everyone, I'm having some trouble with this also. How exactly does one specify the `toctree` in the `mkdocs.yml` file? What is the exact syntax? I can only find documentation on adding it to an `.rst` file.

**Comment by d0ugal** [comment]
@sahilTakiar There is an example in MkDocs itself. Is this what you are after? https://github.com/mkdocs/mkdocs/blob/master/mkdocs.yml#L8-L19

**Comment by sahilTakiar** [comment]
Hey @d0ugal that works when I run `mkdocs serve` locally, but when I try to build using readthedocs the Table of Contents defaults to all the `.md` files present: http://gobblin-sahiltakiar.readthedocs.org/en/latest/

It seems readthedocs requires using Python's `toctree` to set the table of contents, but the readthedocs documentation only has direction on how to use `toctree` in `.rst` files, but not in `.md` files, which is what I am trying to do. Any idea what the syntax should be? The example you showed me adds the `toc` Markdown extension, I added that to my `mkdocs.yml` file but it didn't change anything.

**Comment by d0ugal** [comment]
I am not aware of anything specific required by readthedocs. MkDocs builds fine that I can see: http://mkdocs.readthedocs.org/en/stable/

**Comment by sahilTakiar** [comment]
Hey @d0ugal thanks for the help! I got it to work by moving the `mkdocs.yml` to the root of the GitHub project.
