### ISSUE TITLE
No build for latest tagged release from GitHub in many hours

### ISSUE THREAD

**Issue by posita** [rtfd/readthedocs.org#1278]
I maintain [`dimgx`](https://github.com/posita/py-dimgx). RTD webhooks are enabled on the repository. At Wed May 20 14:17:51 2015 -0700, I [tagged and pushed the 0.2.0 release](https://github.com/posita/py-dimgx/releases/tag/v0.2.0). So far (~~about 7 hours later as of this filing~~ after over 24 hours), neither an updated `stable` nor the `v0.2.0` tag shows up as available to RTD:

https://readthedocs.org/builds/dimgx/
https://readthedocs.org/dashboard/dimgx/versions/

Possibly related to #1017?

**Comment by ericholscher** [comment]
did you try rebuilding the project?

**Comment by ericholscher** [comment]
I believe there was a bug in our tag updated code that is now fixed. I rebuilt your project and its working properly again. Sorry about that!

**Comment by posita** [comment]
I had tried rebuilding in the past, but not this particular occasion. It didn't seem to help when I did it. It looks like your code change triggered a rebuild on the new tag. Thank you! :bow:
