### ISSUE TITLE
With Index.html rendered documentation is not found

### ISSUE THREAD

**Issue by kdambekalns** [rtfd/readthedocs.org#1279]
We have our documentation in rST with the start being `Index.rst`. This renders without problems and generates `Index.html`. Now, when going to `…/en/latest/` all there is is a 404. Obviously the nginx only looks for `index.html` when no filename is given.

I tried using redirects, but that doesn't seem to work - and it would be cumbersome to add for subdirectories, versions, …

Is there a way to configure this, so that `Index.html` is used as index document on readthedocs.org?

**Comment by thomashempel** [comment]
Have you tried

    location / {
        Index.html;
    }

**Comment by brgmn** [comment]
index index.html Index.html;

**Comment by kdambekalns** [comment]
Well, yes, obviously. But how do I do this *on readthedocs.org*?

**Comment by thomashempel** [comment]
Ohhhhh... No idea. Was confused tbh

**Comment by onewheelskyward** [comment]
Can you point me to your Read the Docs page?

**Comment by ericholscher** [comment]
Any reason not to just rename it to index.rst?

On Thu, May 21, 2015 at 8:15 AM, Andrew Kreps <notifications@github.com>
wrote:

> Can you point me to your Read the Docs page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1279#issuecomment-104315048>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by kdambekalns** [comment]
@onewheelskyward Sure, it's http://neos.readthedocs.org/en/latest/ - which doesn't work. But http://neos.readthedocs.org/en/latest/Index.html does.

@ericholscher That is what we will do - unless we can keep the file naming convention we have been using for the last years… If I had the "power" to do so, I'd rather add one more string to my nginx config, than rename a number of files across a few branches. :)

**Comment by kdambekalns** [comment]
Is there any chance this will be solved on the side of RTD any time soon (say, days)? If not, I'll just rename or try some other way of having index.html generated.

Note: I am not intending to sound pushy, just want to know if holding back with a "workaround" makes sense… Thanks!

**Comment by ericholscher** [comment]
Correct. We have over 20,000 projects, and this is the first time this is an issue. ``index.html`` is the standard for this, and I don't see us changing it.

**Comment by kdambekalns** [comment]
Oh well, ok then. Would have been a one-line change to the nginx config, but I get your point. Still sad we have to deviate from our CamelCaps convention for filenames. Thanks for the clear statement, though.
