### ISSUE TITLE
multi languages supports with mo files on single project 

### ISSUE THREAD

**Issue by shangguokan** [rtfd/readthedocs.org#1280]
hello, i got one problem
for example
i want to add French and Chinese to my actual English project: **example.readthedocs.org/en/latest/**
and i do not want to create some projects likes example_fr and example_zh (because i have to fork many projects on github, i want to keep all translation all in a centralized repository)
So i follow these steps here: http://sphinx-doc.org/intl.html, so i got mo file of translation in locale:
```
├── locale
│   ├── fr
│   │   └── LC_MESSAGES
│   │       ├── Behavioral
│   │       ├── Creational
│   │       ├── More
│   │       ├── README.mo
│   │       ├── README.po
│   │       └── Structural
│   └── zh_CN
│       └── LC_MESSAGES
......
```

and i add these parameters in my conf.py
```
language = ['en', 'fr', 'zh_CN']
locale_dirs = ['locale/']  
gettext_compact = False
```

and then i found RTD can not recognize 3 languages at one time, it cound only generate/show/support one language, for example:
if i chose English in admin page it generate English version and the project turn to **example.readthedocs.org/en/latest/**
```
Running Sphinx v1.3.1
making output directory...
loading translations [en]... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 39 source files that are out of date
```
if i chose French in admin page it generate French version and the projet turn to **example.readthedocs.org/fr/latest/**
```
Running Sphinx v1.3.1
making output directory...
loading translations [fr]... done
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 39 source files that are out of date
```
what should i do to make RTD generate these threes language in one build (``loading translations [en, fr, zh-CN]``) and active languages picker in UI?

**Comment by frontendphil** [comment]
The version we came up with can be seen at: https://github.com/effektif/user-docs/tree/master/docs. We keep everything in one repo and have different conf.py files for the different languages. 

* German: https://github.com/effektif/user-docs/blob/master/docs/de/conf.py
* English: https://github.com/effektif/user-docs/blob/master/docs/en/conf.py

**Comment by shangguokan** [comment]
I think i understand how you did on your project, keep each translation and each conf.py in one repo, and use "Manually Import" form same repo same branch to create different project "effektif" and "effektif-de",and in admin page, choose different language, then create connection between them.

but i think if it is possible to just create only one project "effektif" on RTD, when it buiding, it can 
``loading translations [en, de]``

if it is not possible, i'll took your solution, it's great. thanks for your help.
