### ISSUE TITLE
"502 Bad Gateway" when deleting a project

### ISSUE THREAD

**Issue by edmorley** [rtfd/readthedocs.org#1285]
We recently changed github repo names, so had to create new projects and delete the old ones.

When deleting the two projects, for both I got a "502 Bad Gateway" error after confirming the "are you sure" (the page URLs at the point of error were https://readthedocs.org/dashboard/treeherder-service/delete/ and https://readthedocs.org/dashboard/treeherder-ui/delete/ ). The project did end up deleted, but it was slightly confusing UX.

**Comment by edmorley** [comment]
Actually, those two projects didn't delete properly - I can still access the doc pages.
Could you remove them for me? :-)

**Comment by ericholscher** [comment]
These files should be deleted. The 502 is probably the slowness of deleting all the build records, and there isn't much we can do, other than queue the deletion.
