### ISSUE TITLE
Support Javascript API documentation using jsdoc

### ISSUE THREAD

**Issue by kewisch** [rtfd/readthedocs.org#1291]
Unfortunately its not (yet) possible to use readthedocs for API documentation on Javascript projects using jsdoc tags. I tried [jsdoc-rst-template](https://www.npmjs.com/package/jsdoc-rst-template) to convert from jsdoc -> rst and import that into readthedocs, but this did not work for my project (due to missing features in that template). I've also looked into a few other projects, but it seems there is nothing acceptable at the moment.

I asked on IRC, and agj told me a good direction would be to parse the JS to AST and pull information from that. I mentioned [jsdoc3](https://github.com/jsdoc3/jsdoc), which has an "explain" action that does exactly this parsing, applies some transformations to understand the jsdoc tags and outputs JSON data. We agreed that this could be used to add jsdoc support to rtd. 

Here is an excerpt, which I created using `jsdoc --explain lib/ical/binary.js` in my working directory:

```json
[
 {
        "comment": "/**\n   * @classdesc\n   * Represents the BINARY value type, which contains extra methods for\n   * encoding and decoding.\n   *\n   * @class\n   * @alias ICAL.Binary\n   * @param {String} aValue     The binary data for this value\n   */",
        "meta": {
            "range": [
                587,
                641
            ],
            "filename": "binary.js",
            "lineno": 22,
            "path": "/Users/kewisch/mozilla/github/ical.js/lib/ical",
            "code": {
                "id": "astnode100000009",
                "name": "Binary",
                "type": "FunctionDeclaration",
                "paramnames": [
                    "aValue"
                ]
            },
            "vars": {
                "this.value": "ICAL.Binary#value"
            }
        },
        "classdesc": "Represents the BINARY value type, which contains extra methods for\nencoding and decoding.",
        "kind": "class",
        "alias": "ICAL.Binary",
        "params": [
            {
                "type": {
                    "names": [
                        "String"
                    ]
                },
                "description": "The binary data for this value",
                "name": "aValue"
            }
        ],
        "name": "Binary",
        "longname": "ICAL.Binary",
        "memberof": "ICAL",
        "scope": "static"
    }, 
    ...
]

**Comment by ericholscher** [comment]
:+1: This looks like a good first step of javascript integration.

**Comment by agjohnson** [comment]
Will continue tracking this integration with the AutoAPI at rtfd/sphinx-autoapi#7

**Comment by agjohnson** [comment]
Closing this issue here, as this relates to the autoapi
