### ISSUE TITLE
Auto-hiding the sidebar

### ISSUE THREAD

**Issue by gkiar** [rtfd/readthedocs.org#1292]
I am trying to configure RTD in such a way that the sidebar/sitemap is automatically hidden when a page is loaded, regardless of the page width (if you make your browser very narrow this happens anyways). Is there a theme option to make this happen?

**Comment by ericholscher** [comment]
This is an issue with the theme: https://github.com/snide/sphinx_rtd_theme/ -- Any changes and issues should go there.

**Comment by gkiar** [comment]
Ah, sorry about that. Thanks!
