### ISSUE TITLE
need to be able to fully wipe virtualenv directory (or use pip -U for requirements.txt)

### ISSUE THREAD

**Issue by zzzeek** [rtfd/readthedocs.org#1293]
I build sqlalchemy's docs with a custom theme and extension package that is available here: https://pypi.python.org/pypi/zzzeeksphinx

I need this to work such that I can update this package and have its changes be used, *without* the need for me to go to five different tags of the SQLAlchemy project and bump requirements.txt.

For a long time, i was able to do this by just putting the github link in requirements.txt:

    git+https://bitbucket.org/zzzeek/zzzeeksphinx.git@HEAD#egg=zzzeeksphinx

But at this point, even if I do the documented "wipe" procedure by pressing the button at https://readthedocs.org/wipe/sqlalchemy/rel_1_0/ (which btw provides *no* confirmation of any kind that anything actually happened, plus can we please get this button in the admin page itself?)  the build does *not* seem to rebuild anything, as we see at https://readthedocs.org/builds/sqlalchemy/2865623/:

	requirements
	-----

	Requirement already satisfied (use --upgrade to upgrade): changelog>=0.3.4 in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from -r doc/build/requirements.txt (line 1))
	Requirement already satisfied (use --upgrade to upgrade): sphinx-paramlinks>=0.2.2 in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from -r doc/build/requirements.txt (line 2))
	Requirement already satisfied (use --upgrade to upgrade): zzzeeksphinx>=1.0.16 in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from -r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): pyscss in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): mako in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): six in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from pyscss->zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): enum34 in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from pyscss->zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): pathlib in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from pyscss->zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Requirement already satisfied (use --upgrade to upgrade): MarkupSafe>=0.9.2 in /var/build/user_builds/sqlalchemy/envs/rel_1_0/lib/python2.7/site-packages (from mako->zzzeeksphinx>=1.0.16->-r doc/build/requirements.txt (line 3))
	Cleaning up...

that's not what a "wiped" environment looks like.   

can we get some clarification / documentation / features / fixes / etc. whatever so that I can please get my workspace to reinstall entirely?  I think this used to work and it seems to have stopped.

**Comment by gregmuellegger** [comment]
I tried locally and a wipe is removing virtualenv for the build. Maybe it's something on the build server that is going wrong there. We'll investigate this.

**Comment by ericholscher** [comment]
The wipe command in the Versions page should fix this now.
