### ISSUE TITLE
Contents are not updated when using mkdocs (md)

### ISSUE THREAD

**Issue by sils1297** [rtfd/readthedocs.org#1294]
# Steps to reproduce:

Visit http://coala.readthedocs.org/en/latest/
Compare the content listing with http://coala.readthedocs.org/en/latest/Getting_Involved/MAC_Hints/

# Actual results:

On the initial landing page the third navigation entry from the bottom is "Writing Commit Messages". On all other pages it is "Writing Good Commits". (Writing commit messages was the old page that doesn't exist anymore in the repository.)

# Expected results:

The entry should be "Writing Good Commits" in all cases.

**Comment by d0ugal** [comment]
Odd. Can you see any errors for the build on https://readthedocs.org/?

**Comment by sils1297** [comment]
This is our latest build: https://readthedocs.org/builds/coala/2870604/

I do get some errors because readthedocs tries to install my python project with python 2 but none related to documentation creation. (I tried to turn that off without success.)

If you can't access that build info, here's the output: http://pastebin.com/SRUrysrv

**Comment by sils1297** [comment]
oh this part might be the interesting one:

```
html
-----

Building documentation to directory: _build/html
Directory _build/html contains stale files. Use --clean to remove them.
```

**Comment by d0ugal** [comment]
@sils1297 Yeah, quite possibly.

**Comment by sils1297** [comment]
@d0ugal let me know if you need anything else.

**Comment by d0ugal** [comment]
ReadTheDocs probably needs to be updated to pass in `--clean`. I am working on updating ReadTheDocs to use the new release of MkDocs, so if it isn't done before I get there I'll add that.

**Comment by ericholscher** [comment]
Do we just need to add --clear to our call?

**Comment by d0ugal** [comment]
Possibly yes, I wasn't sure how to try and reproduce this.

**Comment by d0ugal** [comment]
it certainly won't do any harm.

**Comment by d0ugal** [comment]
@sils1297 are you able to retest?

**Comment by sils1297** [comment]
@d0ugal I think this is fixed, I can't really reproduce it anymore since it related to the index/readme issue. It would be more work for me to do a reproduction as I had to rename the file again and add it with other contents and so on.

**Comment by d0ugal** [comment]
Hah, okay. I guess we can just assume it is good for now then. Thanks!
