### ISSUE TITLE
Python3.4 project is trying to import python2.7 libraries

### ISSUE THREAD

**Issue by rakeshvar** [rtfd/readthedocs.org#1295]
Hi, 

[This](https://readthedocs.org/builds/theanet/2866398/) is the build I am referring to. Specifically, 

```bash
venv
-----
Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/virtualenv.py", line 8, in <module>
    import base64
  File "/usr/lib/python3.4/base64.py", line 9, in <module>
    import re
  File "/usr/lib/python3.4/re.py", line 324, in <module>
    import copyreg
  File "/home/docs/lib/python2.7/site-packages/copyreg/__init__.py", line 7, in <module>
    raise ImportError('This package should not be accessible on Python 3. '
ImportError: This package should not be accessible on Python 3. 
Either you are trying to run from the python-future src folder or your installation of python-future is corrupted.
```

My project is in Python3.4. 

I **checked** the *'Install your project inside a virtualenv using setup.py install'* option and 
specified the Interpreter as **CPython 3.x**. 
*'Give the virtual environment access to the global site-packages dir'* is left **unchecked**.

Why is it trying to call 2.7? This happens only sometimes. Sometimes it goes through alright. Like it did the very [next time](https://readthedocs.org/builds/theanet/2866414/).

Thanks.

**Comment by ericholscher** [comment]
This should now be fixed.
