### ISSUE TITLE
Does Transifex integration work with an mkdocs based project?

### ISSUE THREAD

**Issue by carukc** [rtfd/readthedocs.org#1298]
Hello,  I've been having trouble getting the Transifex integration working.  I've setup two versions of the project.  One with .md files and the other with .rst.  For some reason nether will push to Transifex.

According to the instructions I need to 'tx push' the source language and 'tx pull' the target languages.  Neither seem to work.  I assume that I do this from the user_builds/my-project directory.

The docs did not mention 'tx init'  but looking at the documentation for tx it looks like I need to run this in the 'my-project/checkouts/latest/docs' directory .  Despite this I do not seem to be able to push anything to my Transifex account.

Ideally I would like to use Markdown but the priority is to automate the translation using Transifex so if I must use .rst files then I will.

Can anyone help me understand how to get Transifex integration working?

Thanks
Chris

**Comment by d0ugal** [comment]
No, there is no support for Transifex in MkDocs. This will only work in ReadTheDocs adds something on top to enable it, which I am unaware of.

**Comment by carukc** [comment]
Thanks.  I'll concentrate on getting ReadtheDocs working with Sphynx based content.

I don't suppose you kow how to properly use the tx commands do you?  Tx push returns without errors on my project but does not do anything.  I've 'tx init'ed in the user_builds/my-project directory and attempted to 'tx set' using the location of my project on Transifex but it's not working.

**Comment by d0ugal** [comment]
No idea, sorry. It is something I want to add in MkDocs eventually, but I've not gotten there yet.

**Comment by carukc** [comment]
It would be great to see this in MkDocs.... I started with it and found it to be MUCH easier to work with than ReadTheDocs but unfortunately, in this case I need translations.

**Comment by d0ugal** [comment]
Noted. I can't promise we will have it soon, but we do want it.
