### ISSUE TITLE
Noticeable delay when loading a markdown based project

### ISSUE THREAD

**Issue by carukc** [rtfd/readthedocs.org#1299]
Hello,  

I noticed while trying to get Transifex integration working that the markdown version of the project exhibits a noticeable delay when loading pages.  It almost seems like ReadTheDocs is recompiling the md files on each load.  

Is this normal?

Thanks
Chris

**Comment by ericholscher** [comment]
Not sure I follow? We don't support translation of mkdocs-based projects. We do support them with Sphinx however.

**Comment by carukc** [comment]
Hello Eric,  

Yea... it's been a voyage of discover for me.  I started with Markdown because it's a simpler markup but soon realized that it was better to stick with Sphinx.

How exactly does the transifex integration work with RTD?  I've figured out that I need to run tx init first (in the docs directory) to create the .rc and config files but after that tx push does not seem to send anything to transifex.  The project names are the same, I've tried tx set --auto-remote with the URL of my project, but get a "ValueError: No JSON object could be decoded" error... so far, no joy.

What am I missing?

Chris

**Comment by d0ugal** [comment]
Could it be that MkDocs assets are not stored on the CDN?

**Comment by carukc** [comment]
Hi.  Good thought, but in this case both are hosted locally... It's not a big gap... Sphinx based docs seem to load in less than a second while MkDocs content takes 3-4 seconds.  It's almost as if RTD is recompiling the MD file when a page is viewed

**Comment by carukc** [comment]
I've moved my question re Transifex to a separate post:
 https://github.com/rtfd/readthedocs.org/issues/1303

It seems off topic for this thread.

**Comment by ericholscher** [comment]
I've never seen this as an issue, so I'm closing it. If there is a specific issue that we've diagnosed, feel free to re-open, but this ticket is unactionable as it currently stands.
