### ISSUE TITLE
Apache RTD Installation virtual host?

### ISSUE THREAD

**Issue by marksie1988** [rtfd/readthedocs.org#1301]
Is it possible to install Read the docs on a server that has apache using a virtual host? if so please could this be added to the documentation for install? 

Im new to your product and want to install it on my server. 

Regards,
Steve

**Comment by agjohnson** [comment]
There shouldn't be a problem running RTD and apache httpd. However, the community only supports development installs of read the docs, and the production stack uses nginx, so we don't have an answer for this. Feel free to contribute a documentation patch for this.

Closing for now.
