### ISSUE TITLE
Broken symbolic link breaks search and the version box

### ISSUE THREAD

**Issue by carukc** [rtfd/readthedocs.org#1302]
I've found an issue with the layout of files in the clone that I've just grabbed.

In /media/javascript there is a symbolic link that points: 
  readthedocs-doc-embed.js -> ../static/core/js/readthedocs-doc-embed.js

that file is actually in:
   ../../readthedocs/core/static/core/js/readthedocs-doc-embed.js

From within the media directory ($HOME/media/javascript)

  ln -s ../../readthedocs/core/static/core/js/readthedocs-doc-embed.js

fixes the version box and gets the search box working.  I will post as an issue (if it hasn't already).

I hope that this helps
Chris

**Comment by agjohnson** [comment]
You need to perform static asset collection, files shouldn't be linked to the source files in /media/static. I haven't outlined the changed to the static asset generation yet, documentation will come shortly for that.

For now, see django static asset collection.
