### ISSUE TITLE
Allow subproject slug to be custom

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1304]
Not everything needs to live within ``/projects/`` on the parent project.

**Comment by gregmuellegger** [comment]
Can you elaborate a bit on this so that someone who is interested could start working on it based on the information in this ticket?

**Comment by ericholscher** [comment]
Fixed this with an alias for subprojects.

**Comment by Luthaf** [comment]
The alias do not seems the work. I added `chemfiles-python` as a subproject for `chemfiles`, with the `python` alias. 

The proposed URL in the admin view is http://chemfiles.readthedocs.org/projects/python/, which leads to a 404 error. The http://chemfiles.readthedocs.org/projects/chemfiles-python/ URL leads to the documentation.

**Comment by agjohnson** [comment]
@Luthaf this is a new issue, please open a separate ticket
