### ISSUE TITLE
latest badge got red

### ISSUE THREAD

**Issue by sils1297** [rtfd/readthedocs.org#1307]
Hi,

for some reason the docs|latest badge just decided to go red. Here: https://github.com/coala-analyzer/coala

However if I look here: https://readthedocs.org/projects/coala/ it's still green and I also can't find any errors nor an explanation.

May that be a bug even? If not at least a usability bug?

**Comment by d0ugal** [comment]
It is green for me. GitHub caches these for a while, so expect it to take some time to update. I can't see how it would be a RTD bug.

**Comment by onewheelskyward** [comment]
It's green on the reported affected project as well as my own.  Looks like this one was just transient.
