### ISSUE TITLE
Python 3 development headers missing (again)

### ISSUE THREAD

**Issue by nre** [rtfd/readthedocs.org#1311]
Python 3.x build https://readthedocs.org/builds/doxhooks/2897156/ fails because Python.h is missing (during the installation of pillow, which prevents the installation of Sphinx, etc).

This problem has been fixed before in #801.

**Comment by ericholscher** [comment]
Gah, sorry. This is an issue with our new build server salt configs. Will
fix.

On Mon, Jun 1, 2015 at 9:21 AM, Nick Evans <notifications@github.com> wrote:

> Python 3.x build https://readthedocs.org/builds/doxhooks/2897156/ fails
> because Python.h is missing (during the installation of pillow, which
> prevents the installation of Sphinx, etc).
>
> This problem has been fixed before in #801
> <https://github.com/rtfd/readthedocs.org/issues/801>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1311>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by agjohnson** [comment]
This should be resolved. Feel free to reopen if you hit the issue again.
