### ISSUE TITLE
MkDocs extra css/js not working

### ISSUE THREAD

**Issue by d0ugal** [rtfd/readthedocs.org#1313]
Example: http://tvheadend.readthedocs.org/en/stable/
extra_css: https://github.com/ProfYaffle/tvheadend-documentation/blob/master/mkdocs.yml#L12

This works locally but not on RTD. There may be some bad logic here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/mkdocs.py#L55-L77

MkDocs will automatically add all CSS in the docs dir if the user doesn't set a extra_css/js config option. However, RTD manually adds these settings so to MkDocs it appears that the user is explicitly including some and not others.

However, even including it manually as above it isn't working. It is likely that the solution to this is a large refactor of how MkDocs integration works and us making it easier in MkDocs itself for you to do that.

**Comment by d0ugal** [comment]
Turns out manually specifying the `extra_css` does work - I think we just didn't wait long enough. However, the automatic discovery of css and js is still broken by RTD pre-processing.

**Comment by stsewd** [comment]
> However, the automatic discovery of css and js is still broken by RTD pre-processing.

We only extend these settings, we don't override them. We don't discover them automatically or at least we don't do that anymore.

Let me know if this is still a problem to reopen this issue.
