### ISSUE TITLE
Versions in the project page seems down

### ISSUE THREAD

**Issue by ugocupcic** [rtfd/readthedocs.org#1322]
Hi,

I can't seem to be able to reach the versions page in any of my projects on rtd. This is what I see on https://readthedocs.org/projects/sr-ronex/versions:

![image](https://cloud.githubusercontent.com/assets/557182/7978268/d82079cc-0a93-11e5-8359-21442eece4a3.png)

**Comment by ugocupcic** [comment]
I'm wondering whether this is related to my doc failing to build. I get the following error when trying to build a simple new project (https://readthedocs.org/builds/sr-ronex/2913551/): 

```
checkout
-----

Top-level Build Failure: Server Error 500: https://readthedocs.org/api/v2/version/1615369/
```

The project I'm trying to build can be seen here: https://github.com/shadow-robot/sr-ronex/tree/F%23185_rtd/docs

**Comment by gregmuellegger** [comment]
We had a problem on the versions page which was related to the branch names in the project's repository. We fixed that a few days ago and it might also have fixed the problem for you.

@ugocupcic is this problem still valid for you?

**Comment by ugocupcic** [comment]
@gregmuellegger yes it's still failing for me: https://readthedocs.org/projects/sr-ronex/versions/ is still returning the fail check back in a bit error. Might be due to our `#` in the branch name?

**Comment by gregmuellegger** [comment]
Probably that is the problem yes. If I try the same project in my local installation, then the `#` is escaped as expected. A migration should have fixed the invalid slugs. Maybe there are still some strange slugs left in the DB.

@agjohnson @ericholscher Could one of you look into the server's database to see if there is any version slug left with invalid characters? Namely a version with a `#` in the `sr-ronex` project?

**Comment by ugocupcic** [comment]
@gregmuellegger it's not only in sr-ronex, I get the same on:
- https://readthedocs.org/projects/shadow-robot/versions/
- https://readthedocs.org/projects/shadow-robot-ethercat-driver/versions/

(we use the same convention for our branch names: F#123_feature - where 123 links to the github issue. It's used in waffle.io to automatically update some TODO lists)

Cheers,

**Comment by ericholscher** [comment]
This problem with version slugging has been fixed.

**Comment by chaudum** [comment]
probably related: #1822
