### ISSUE TITLE
documentation doesn't build

### ISSUE THREAD

**Issue by sils1297** [rtfd/readthedocs.org#1326]
Hi,

our docs just stopped working: https://readthedocs.org/builds/coala/2922630/ (doc-builder section)

We didn't change anything in our configuration so I'm wondering if there was a change on your side or you have further insight?

**Comment by sils1297** [comment]
Hey, this issue seems to be related to python3, when changing environment back to python2 it seems to build again (although executing our setup.py fails and I still don't see why or how I can't deactivate that this is executed in the first place).

**Comment by d0ugal** [comment]
Interesting. The error is odd, it looks like it is an issue creating the virtualenv or something like that.

**Comment by sils1297** [comment]
Ok although it's showing that the build succeeds I get an 404 on that branch. Here's the build:

https://readthedocs.org/builds/coala/2939819/

And here's the docs (or rather: should be):

http://coala.readthedocs.org/en/wip-sils-docfix/

I'm now even getting this for our main documentation :/. I'd appreciate any help for a workaround. It's not like I have configured anything big (or could have).

**Comment by sils1297** [comment]
it says

`INFO    -  Building documentation to directory: /var/build/user_builds/coala/checkouts/wip-sils-docfix/_build/html `

I don't know how this is mapped but maybe this info helps you more.

**Comment by sils1297** [comment]
Hey, it's only the index page that is not found, i.e.:
http://coala.readthedocs.org/en/wip-sils-docfix/

yields an E404 for me right now. http://coala.readthedocs.org/en/wip-sils-docfix/README/ works.

http://coala.readthedocs.org/en/latest/ works again but I had E404 before. All this feels very very weird and might be related to https://github.com/rtfd/readthedocs.org/issues/1294 .

**Comment by d0ugal** [comment]
There are a ton of errors in the build output. They all seem to be related to Coala being Python 3 only. I don't know if this is causing the issue?

**Comment by d0ugal** [comment]
I removed the MkDocs label, as despite you are using MkDocs I can't see how it could be the issue here.

**Comment by sils1297** [comment]
> There are a ton of errors in the build output. They all seem to be related to Coala being Python 3 only. I don't know if this is causing the issue?

A while ago it worked fine in a python 2 environment, that means the build failed but the documentation did build! I actually don't see why readthedocs needs to install coala to build it's documentation.

> I removed the MkDocs label, as despite you are using MkDocs I can't see how it could be the issue here.

Actually I'm getting the 404 locally too after upgrading mkdocs:

![screenshot from 2015-06-10 09-13-43](https://cloud.githubusercontent.com/assets/5716520/8076882/16f541e8-0f51-11e5-9148-27d1f868f0e2.png)

Note that this is the very same mkdocs.yml file that worked for quite a while quite nicely. (Last change was on may 8th a documentation addition and that still worked.) I noticed the deprecation message which lead me to update my yml to the new syntax - the warning goes away but I still get the E404:

![screenshot from 2015-06-10 09-18-39](https://cloud.githubusercontent.com/assets/5716520/8076942/9e67e054-0f51-11e5-863d-5345871aaacf.png)

(This is the wip/sils/docfix branch upstream if you care for the actual code.)

**Comment by sils1297** [comment]
> There are a ton of errors in the build output. They all seem to be related to Coala being Python 3 only. I don't know if this is causing the issue?

> Hey, this issue seems to be related to python3, when changing environment back to python2 it seems to build again (although executing our setup.py fails and I still don't see why or how I can't deactivate that this is executed in the first place).

https://readthedocs.org/builds/coala/2922630/ was python3
https://readthedocs.org/builds/coala/2941394/ is python2

I found a workaround. The E404 seems to be related to me being reluctant to name the Home page index.md (I wanted README.md because this is shown on github the right way). I renamed it back to index which makes our documentation accessible again.`

**Comment by d0ugal** [comment]
ReadTheDocs is supposed to make it work with either a `README.md` or `index.md` file, I can't see why that wouldn't be working now. MkDocs itself has always required an `index.md` - if it worked otherwise that is a bug or a feature that pre-dates my involvement and wasn't documented :)

**Comment by sils1297** [comment]
For reference this is what fixed it for us: https://github.com/coala-analyzer/coala/commit/2f5dfa66f266b31081ebeb40e5430fe4d59c9f9a

I'd be glad to be able to revert that commit.

**Comment by d0ugal** [comment]
Keep an eye on https://github.com/mkdocs/mkdocs/issues/608

**Comment by sils1297** [comment]
Thanks. Then there is still the issue that it should work on readthedocs, please let me know if I can help you somehow investigating.

**Comment by d0ugal** [comment]
Ah, I guess it is because ReadTheDocs creates the index file here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L89-L103 but nothing updates the mkdocs.yml to use the new file. If you only care about building on RTD you should be able to leave it as index.md in the config and revert the file rename.

**Comment by sils1297** [comment]
That sounds like an ugly thing to do and likely for future compatability break so I'll stay with index.md for now. Also docs should be buildable locally, which is true now.

Actually I'm not anymore getting the E404 on all branches but issue #1294 occurrs again, i.e. it shows some old home page which doesn't exist since quite some time in the repository. So what we're observing here is likely several overlapping symptoms.

**Comment by sils1297** [comment]
@d0ugal maybe it's easier if we speak on IRC or similar? You don't seem to be on freenode#readthedocs, can you join https://gitter.im/coala-analyzer/coala by chance?

**Comment by ericholscher** [comment]
Closing this issue, and I don't think it is a RTD issue, and hasn't been updated in a few months.
