### ISSUE TITLE
Feature request: RTD config file in repo

### ISSUE THREAD

**Issue by takluyver** [rtfd/readthedocs.org#1336]
I know this would be a big change; I'm opening an issue to discuss whether it's something RTD should do, and how it might work. :-)

The web interface is a helpful guide when setting up a first project, when you don't know what the options are. But when you're setting up several, mostly using the same settings, it's relatively tedious to click or tab through the options.

Other sites that do things from VCS repos (I'm thinking of CI services like Travis and Appveyor) look for a specially named config file in the repo root to control their options. It would be nice to be able to configure RTD by putting a `readthedocs.(toml|yml|ini)` file into my repo and then just pressing one button one the website. It also means that other people can suggest changes to the config by making pull requests.

Obviously the web interface shouldn't go away, so there's a question of how the two configs interact. Appveyor [also offers both interfaces](http://www.appveyor.com/docs/build-configuration#configuring-build), and uses the simple rule that if there's an appveyor.yml file in the repo, the settings in the web interface are completely ignored. This seems like a good approach: more advanced users who prefer the config file can ignore the web interface.

CC @Carreau , who suggested this to me.

**Comment by Carreau** [comment]
If there was an API endpoint to enable it would be even more awesome, you could have a readthedoc CLI interface, and "just" do `$ readthedoc init` in a repo to create the `.readthedocs` file and enable github web-hook.

**Comment by d0ugal** [comment]
Yup, this seems like a good idea to me. After getting used to file based config a for other projects (mostly CI related) I find it a much nicer experience.

**Comment by ericholscher** [comment]
These are both things that I have basic working versions of, but need more
testing to roll out. We've been trying to dig ourselves out of a number of
holes in the project before being able to get to bigger stuff like this,
but it's on the short term roadmap.

I will hopefully have something demo-able and tryable in this regard in the
next couple weeks, and would love feedback/testing once I do.

On Thu, Jun 11, 2015 at 12:07 PM, Dougal Matthews <notifications@github.com>
wrote:

> Yup, this seems like a good idea to me. After getting used to file based
> config a for other projects (mostly CI related) I find it a much nicer
> experience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1336#issuecomment-111243357>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by takluyver** [comment]
Awesome, we'll be happy to test when you're ready.

**Comment by d0ugal** [comment]
Likewise, happy to test and review etc.

**Comment by Carreau** [comment]
+1

**Comment by shoyer** [comment]
Indeed, this would great. In particular, the configuration steps required to build docs based on the scientific python stack are somewhat non-obvious. Being able to point someone to a config file for the advanced settings rather than talking them through the web interface would be much easier.

**Comment by takluyver** [comment]
@ericholscher is this any closer to being ready for us to test?

I'd also like to see a way to put more flexible installation steps in the config file as an alternative to the specific options for `setup.py` and `requirements.txt`. I'm thinking of a list of commands to run before building the docs, similar to the 'install' section in a Travis config file.

**Comment by Carreau** [comment]
If there is any way to enable that as a beta for some repositories that would be great !

**Comment by ericholscher** [comment]
This is the same as #752 -- closing as dupe.
