### ISSUE TITLE
autosummary files are not included

### ISSUE THREAD

**Issue by chfw** [rtfd/readthedocs.org#1339]
Hi all,

I am not sure what have happened with read the docs web site. My [api page]( http://pyexcel.readthedocs.org/en/latest/api.html) should read like [this](pythonhosted.org/pyexcel/api.html) is empty on rtdc. It was fine before version [v0.1.3]( http://pyexcel.readthedocs.org/en/v0.1.3/api.html). 

I referred to latest [build log](https://readthedocs.org/builds/pyexcel/2951139/), and found these:

/var/build/user_builds/pyexcel/checkouts/latest/doc/source/generated/pyexcel.Book.rst:: WARNING: document isn't included in any toctree
/var/build/user_builds/pyexcel/checkouts/latest/doc/source/generated/pyexcel.Book.number_of_sheets.rst:: WARNING: document isn't included in any toctree
/var/build/user_builds/pyexcel/checkouts/latest/doc/source/generated/pyexcel.Book.save_as.rst:: WARNING: document isn't included in any toctree
/var/build/user_builds/pyexcel/checkouts/latest/doc/source/generated/pyexcel.Book.save_to.rst:: WARNING: document isn't included in any toctree
/var/build/user_builds/pyexcel/checkouts/latest/doc/source/generated/pyexcel.Book.save_to_database.rst:: WARNING: document isn't included in any toctree

Can someone tell me how to fix it? When I do documentation locally, I dont have such problem at all.

Cheers,

chfw

**Comment by agjohnson** [comment]
What version of sphinx are you using locally? <1.3?

**Comment by chfw** [comment]
Local version is 1.2.3 and rtd used 1.2.2. When I install sphinx v1.3.0+, I can reproduce it locally as well. So is it too early to adopt sphinx 1.3.0+ for readthedocs?

**Comment by agjohnson** [comment]
Not at all, we are running 1.3.1 on readthedocs. You are hitting the issue described here: #1290, which is a bug in sphinx.

Closing this ticket as a dulpicate, we'll be sure to adopt the latest sphinx when a release is made.
