### ISSUE TITLE
Cannot delete subproject

### ISSUE THREAD

**Issue by gossi** [rtfd/readthedocs.org#1341]
Hi,

I have added a subproject to test, what this is about. Now I can't delete it anymore.

This url: `https://readthedocs.org/dashboard/<prj>/subprojects/delete/<subprj>/` does not exist.

**Comment by gregmuellegger** [comment]
That seems odd. Which project is this on? Could you please give the link that you are actually trying to click and get a 404 back for?

**Comment by gossi** [comment]
This is the link that gives me a 404: https://readthedocs.org/dashboard/fvf/subprojects/delete/manual/

**Comment by gregmuellegger** [comment]
Thanks, I will have a look at this.

**Comment by gossi** [comment]
Thanks. Since I'm not an admin of the "manual" project. Could you delete it for me?

**Comment by gregmuellegger** [comment]
The changes are not deployed yet. You will be able to remove the the subproject without beeing an admin of it once it's in production. Will probably happen early in the week.

**Comment by jflory7** [comment]
Hi, it doesn't seem like it's possible to delete sub-projects anymore? I am looking at this page but see no method of deleting a sub-project. I tried using the above URL but had no luck.

![Cannot delete sub-project](https://user-images.githubusercontent.com/4721034/35124536-6e707e20-fc74-11e7-88dd-c6711362964c.png)

**Comment by stsewd** [comment]
@jflory7 you need to click on the "coordinate_to_admin..." link

**Comment by jflory7** [comment]
@stsewd Oh, I feel dumb now. I guess I was misclicking by a few pixels – I was redirected to back to the project page the first two times I tried it.

So I guess this isn't a bug then, but maybe better UI/UX would be helpful – an "Edit" button would be really clear.

**Comment by RichardLitt** [comment]
@jflory7 Want to open an issue for that? :)

**Comment by jflory7** [comment]
@RichardLitt Done, see #3538. 🙂

**Comment by RichardLitt** [comment]
Thanks. :)
