### ISSUE TITLE
Git project import in RTD not creating "media/json/<project>/<version>" directory

### ISSUE THREAD

**Issue by mchong** [rtfd/readthedocs.org#1347]
I'm running my own instance of RTD locally.  From tracing through the RTD code, it looks like the import of git projects should create the directory: `readthedocs.org/media/json/<project>/<version>`

But it doesn't create the `media/json/<project>/<version>` directory for my project imports.  This is causing my searches using elasticsearch on the projects to return zero results.  Any ideas what could be causing this?

I noticed that the `json` directory itself doesn't get created under the `media` directory.

**Comment by gregmuellegger** [comment]
Can you point at the code bits that you expect the creation of the directories should happen during git imports? That would make investigating a lot easier. Cheers! :)

**Comment by mchong** [comment]
I believe it's here: 
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L691

**Comment by ericholscher** [comment]
Closing this, as it is an old local install issue.
