### ISSUE TITLE
https://readthedocs.org/projects/pyramid-cubicweb/versions/ fails

### ISSUE THREAD

**Issue by cdevienne** [rtfd/readthedocs.org#1352]
Hi,

I cannot access the https://readthedocs.org/projects/pyramid-cubicweb/versions/ page anymore.
I may be related to the last tags that were pushed: "0.3.1" and "debian/0.3.1-1"

**Comment by gregmuellegger** [comment]
It works fine for me, but that's probably because I only see the public page of your project.
What do you get as an error? Do you see a HTTP 500 page?

**Comment by ericholscher** [comment]
I believe this is an instance of #1176

On Thu, Jun 18, 2015 at 9:06 AM, Gregor Müllegger <notifications@github.com>
wrote:

> It works fine for me, but that's probably because I only see the public
> page of your project.
> What do you get as an error? Do you see a HTTP 500 page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1352#issuecomment-113149810>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by cdevienne** [comment]
I get a HTTP 500 page indeed.

The slash is likely to be the cause. And it is on a tag I don't need to publish.
Ignoring it in a first time would be a short term solution for my case.

**Comment by gregmuellegger** [comment]
Yep the reason is part of #1176 (the slash in the tag name). I'm working on a fix for this in #1362

**Comment by cdevienne** [comment]
Thanks for looking into it!

**Comment by gregmuellegger** [comment]
A fix for this go merged. Is the problem solved for you now?

**Comment by cdevienne** [comment]
It is, thanks a lot !
