### ISSUE TITLE
The embeded help link in versions page is broken

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1353]
Nothing happens when you click on the **(Help)** link:
![screen](https://cloud.githubusercontent.com/assets/88278/8229495/abfed878-15b7-11e5-9d09-6be01ffdbf60.png)

**Comment by gregmuellegger** [comment]
The markup for the link looks like this:

```
<div id="help_container">
  <a href="#" class="quiet readthedocs-help-embed">(Help)</a>
</div>
```

So I assumed that there is some reference to `help_container` or `readthedocs-help-embed` in the Javascript, but there isn't. So it seems that this help has no chance to work.

Is there something missing that was once in place? I found only this reference: https://github.com/rtfd/readthedocs.org/commit/a36a1dc6fd71930f419046b70b3db9b8e5c6a12e#diff-77fa4d857406100554a8766dc8f0c871R28 but it seems that this code has been deleted at some point.

**Comment by ericholscher** [comment]
This should be removed for now. We need to improve the performance of our Embed API before it makes sense to re-enable this.
