### ISSUE TITLE
All headings and subheadings at the same level in TOC!

### ISSUE THREAD

**Issue by fniessen** [rtfd/readthedocs.org#1355]
I have the simplest repo one can have, with one `docs/index.md` file. See https://github.com/fniessen/repo.

There, I have 2 level-1 headings, and 2 subheadings. They are correctly formatted in the HTML. However, the TOC puts them all at the same level. See http://screencast.com/t/PBmwpwEzp.

PS- Thanks A LOT for this wonderful piece of art!

**Comment by d0ugal** [comment]
This is by design and how I would expect the TOC to be rendered by MkDocs. The ReadTheDocs theme only recently added styling to fold subheadings in the table of contents. This needs to be implemented in MkDocs still. https://github.com/mkdocs/mkdocs/issues/588

**Comment by fniessen** [comment]
FYI, I'm not asking for folding (which I do not particularly like BTW, but YMMV). I was just expecting an indentation to the right.

**Comment by d0ugal** [comment]
Sure, well, the goal of the MkDocs ReadTheDocs theme is to match the Sphinx ReadTheDocs theme as closely as we can when features matchup etc.

Going another route would be a fork in the theme which you are welcome to try doing.
