### ISSUE TITLE
Missing `python-dev|python-devel`

### ISSUE THREAD

**Issue by jirikuncar** [rtfd/readthedocs.org#1356]
We are getting failed build in https://readthedocs.org/builds/invenio/2978500/ with following error:

`SystemError: Cannot compile 'Python.h'. Perhaps you need to install python-dev|python-devel.`

**Comment by cdeil** [comment]
Same error here with Python 3 (scroll to the very bottom of the page):
https://readthedocs.org/builds/ctapipe/3001244/

**Comment by ericholscher** [comment]
These should now be installed on the build servers, closing this.
