### ISSUE TITLE
Include more information on build in built documentation

### ISSUE THREAD

**Issue by anarcat** [rtfd/readthedocs.org#1357]
it would be nice to have, in the footer (or the bottom-left popup), the version the docs were built from. i think two fields would be nice:

1. "git commit: <7hex>", for example, "git commit: 2048019" or "git commit: ga38aef4"
2. "git version: <output of git describe>", for example "git version: 2.0.1" or "git version: 2.0.1-31-ga38aef4"

where they would be put i don't mind so much... 

this would help me figure out if i hit "force-reload" correctly to see new changes propagated to rtd.org :)

**Comment by agjohnson** [comment]
Also, piggybacking on this, we should include the build id with the commit data as well, to tell if the doc build is current. It wouldn't have to display anywhere necessarily, but a link back to the project build instance would be handy.

**Comment by anarcat** [comment]
agreed

**Comment by ericholscher** [comment]
This is now included in the footer, and is fixed.

**Comment by anarcat** [comment]
that's great! unfortunately, it doesn't seem like it puts the release number in there - how about a little bit of `git describe` magic? :)
