### ISSUE TITLE
inconsistent badge color

### ISSUE THREAD

**Issue by xuchen** [rtfd/readthedocs.org#1358]
![screen shot 2015-06-18 at 11 27 04 am](https://cloud.githubusercontent.com/assets/543547/8238875/345d0fb0-15ad-11e5-8716-f79896ad70e7.png)

It shows a passed build but the badge is still dark red:

https://readthedocs.org/projects/parsetron/badge/?version=latest

![https://readthedocs.org/projects/parsetron/badge/?version=latest]
(https://readthedocs.org/projects/parsetron/badge/?version=latest)

However, if I remove the version selector, it shows green:

https://readthedocs.org/projects/parsetron/badge/
![https://readthedocs.org/projects/parsetron/badge/]
(https://readthedocs.org/projects/parsetron/badge/)

Also, I can't get a correct CNAME setting after following the docs. If I do ``dig parsetron.kitt.ai``::

    ;; ANSWER SECTION:
    parsetron.kitt.ai.	84738	IN	CNAME	PARSETRON.READTHEDOCS.ORG.
    PARSETRON.READTHEDOCS.ORG. 300	IN	A	162.209.114.75

But if I access parsetron.kitt.ai, there's a 404 Maze Found Error from readthedocs.org

A little help please?? Thanks a million!!

**Comment by xuchen** [comment]
After one hour I can see the red badge turned green. So maybe this is just a timing issue. However the CNAME setting is still not working.

**Comment by agjohnson** [comment]
The response is cached, so this was likely the cause for the delay.

For the separate CNAME issue, check your project settings, there is a settings for the domain you need to change.

**Comment by xuchen** [comment]
I can only see "Project homepage" and "Canonical URL" as possibly relevant in project settings. Is it where I should change? I did change these two places anyways. Is there some other place that I missed? Thanks!
