### ISSUE TITLE
Almost 11 hours and still running?

### ISSUE THREAD

**Issue by Gabriel-p** [rtfd/readthedocs.org#1361]
I updated my repo yesterday night, it's been 11 hours and the build still shows as 'Active': https://readthedocs.org/builds/asteca/2982095/

It builds with no issues in my system. Is RTD down or is there a problem with my code?

**Comment by gregmuellegger** [comment]
Another affected build: https://readthedocs.org/builds/isuma-media-players/2979685/
Maybe the builder workers are down.

**Comment by daanemanz** [comment]
Here's another one - been stuck for 16h30m as of now https://readthedocs.org/builds/locationkit/2981339/

**Comment by ericholscher** [comment]
This was an issue with one of our builders. It should be resolved now.

On Fri, Jun 19, 2015 at 10:35 AM, Daniel van den Berg <
notifications@github.com> wrote:

> Here's another one - been stuck for 16h30m as of now
> https://readthedocs.org/builds/locationkit/2981339/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1361#issuecomment-113532681>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by daanemanz** [comment]
Confirmed - builds have passed by now. Thanks!

**Comment by Gabriel-p** [comment]
My build is still running :(

@gregmuellegger should I just wait? There's no way for me to abort the build, as far as I can see.

**Comment by agjohnson** [comment]
@Gabriel-p can you just rebuild? The stale state might stick around if the task was lost in the queue.

**Comment by Gabriel-p** [comment]
I didn't know you could just hit the 'Build version:' button to force a re-build.

I just did and everything passed. Thank you!
