### ISSUE TITLE
upper case in dig redirect in CNAME setting?

### ISSUE THREAD

**Issue by xuchen** [rtfd/readthedocs.org#1366]
Apologies first: I have to open this issue again. I've been having the 404 Maze Found Error when accessing http://parsetron.kitt.ai, but the dig record shows the correct path:

```
;; ANSWER SECTION:
parsetron.kitt.ai.	86138	IN	CNAME	PARSETRON.READTHEDOCS.ORG.
PARSETRON.readthedocs.org. 38	IN	A	162.209.114.75
```

I believe all settings are correct. One thing worth notice is that the domain names are all in capital case here. And [middleware.py](https://github.com/rtfd/readthedocs.org/blob/68ed2f0c56feeaf476785bbaaad925c4ad195edd/readthedocs/core/middleware.py) doesn't seem to do case switching. Could this be the problem?

P.S., according to the [CNAME docs](docs.readthedocs.org/en/latest/alternate_domains.html), there's nothing to set on the Project->Settings side. All I need to do is to provide a CNAME record on the domain provider side. Please correct me if I'm wrong.

Thanks!

**Comment by ericholscher** [comment]
Why is it in all caps? The DNS record should be in lowercase, and I imagine
it will work. We've never hit this before, but I guess we could patch it to
not be case sensitive to be more robust.

On Mon, Jun 22, 2015 at 3:07 PM, xuchen <notifications@github.com> wrote:

> Apologies first: I have to open this issue again. I've been having the 404
> Maze Found Error when accessing http://parsetron.kitt.ai, but the dig
> record shows the correct path:
>
> ;; ANSWER SECTION:parsetron.kitt.ai.  86138   IN  CNAME   PARSETRON.READTHEDOCS.ORG.PARSETRON.readthedocs.org. 38   IN  A   162.209.114.75
>
> I believe all settings are correct. One thing worth notice is that the
> domain names are all in capital case here. And middleware.py
> <https://github.com/rtfd/readthedocs.org/blob/68ed2f0c56feeaf476785bbaaad925c4ad195edd/readthedocs/core/middleware.py>
> doesn't seem to do case switching. Could this be the problem?
>
> P.S., according to the CNAME docs
> <http://docs.readthedocs.org/en/latest/alternate_domains.html>, there's
> nothing to set on the Project->Settings side. All I need to do is to
> provide a CNAME record on the domain provider side. Please correct me if
> I'm wrong.
>
> Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1366>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by xuchen** [comment]
I simply *cannot* change the case. My domain provider automatically does upper casing even though I input lowercase.

All other working CNAME settings I poked around about had lowercases. Thus I suspect this IS the issue. Could you please patch it on your side? Should be a small effort. Thanks!

**Comment by ericholscher** [comment]
Might take us a bit to get to this, but if you submit a patch it will make it happen faster :)

**Comment by xuchen** [comment]
OK! Pull request submitted! When do you estimate deployment will happen?

**Comment by xuchen** [comment]
Thanks for fixing it!
