### ISSUE TITLE
User/Group Permissions & Inline Editing

### ISSUE THREAD

**Issue by jspizziri** [rtfd/readthedocs.org#1367]
Support/Feature request.

Is it possible to have different user/group permissions for different portions of the website?

Also, is it possible to edit the source documents inline? Or is there a package that could be installed to do so?

**Comment by agjohnson** [comment]
Advanced permissions for teams is part of readthedocs.com, the feature is more applicable to companies with projects than it is to open sources projects.

And no, I don't believe there are any packages available to enable inline editing of documents, whether you mean editing rST or the HTML output. The closest you can likely get is editing the source documents in Github.
