### ISSUE TITLE
broken pip requirements 

### ISSUE THREAD

**Issue by fmoor** [rtfd/readthedocs.org#1369]
it seems that the bzr==2.5b4 requirement in requirements/pip.txt is not valid. I commented it out and ran:
pip install bzr=2.6

http://read-the-docs.readthedocs.org/en/latest/install.html?highlight=install?highlight=install

this was on windows 7, python 2.7.10, pip 6.1.1

**Comment by gregmuellegger** [comment]
Hi, thanks for the report. I was able to reproduce locally in a fresh virtualenv:

```
gregor@myra ~ % mkvirtualenv --python=/usr/bin/python2.7 tmp
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in tmp/bin/python2.7
Also creating executable in tmp/bin/python
Installing setuptools, pip, wheel...done.

(tmp) gregor@myra ~ % pip install bzr==2.5b4
Collecting bzr==2.5b4
  Could not find a version that satisfies the requirement bzr==2.5b4 (from versions: 2.6.0)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external bzr to allow).
No matching distribution found for bzr==2.5b4

1 (tmp) gregor@myra ~ % pip install bzr==2.5b4 --allow-external bzr                                                                                                                                                                                                                       :(
Collecting bzr==2.5b4
  Could not find a version that satisfies the requirement bzr==2.5b4 (from versions: 2.6.0)
  Some insecure and unverifiable files were ignored (use --allow-unverified bzr to allow).
No matching distribution found for bzr==2.5b4

1 (tmp) gregor@myra ~ % pip install bzr==2.5b4 --allow-external bzr --allow-unverified bzr                                                                                                                                                                                                :(
Collecting bzr==2.5b4
  bzr is potentially insecure and unverifiable.
  Using cached https://launchpad.net/bzr/2.5/2.5b4/+download/bzr-2.5b4.tar.gz
Building wheels for collected packages: bzr
  Running setup.py bdist_wheel for bzr
  Stored in directory: /home/gregor/.cache/pip/wheels/0b/20/62/53308ef6b5481e7df83bcc08eb5f1eb7c54518fbcf1509aaf7
Successfully built bzr
Installing collected packages: bzr
Successfully installed bzr-2.5b4
pip install bzr==2.5b4 --allow-external bzr --allow-unverified bzr  17.88s user 0.67s system 74% cpu 24.779 total
```

It only works when running `--allow-unverified` which is not really ideal.

**Comment by gregmuellegger** [comment]
Actually this is expected as these flags were listed in the `requirements/pip.txt` file. However IMO we should get rid of them. I created #1377 for this.

**Comment by fmoor** [comment]
Thanks. I redid the tutorial on a different computer and didn't get the 
same error again. I must have been doing something wrong...



On 06/25/2015 03:07 AM, Gregor Müllegger wrote:
>
> Hi, thanks for the report. I was able to reproduce locally in a fresh 
> virtualenv:
>
> |gregor@myra ~ % mkvirtualenv --python=/usr/bin/python2.7 tmp
> Running virtualenv with interpreter /usr/bin/python2.7
> New python executable in tmp/bin/python2.7
> Also creating executable in tmp/bin/python
> Installing setuptools, pip, wheel...done.
>
> (tmp) gregor@myra ~ % pip install bzr==2.5b4
> Collecting bzr==2.5b4
>    Could not find a version that satisfies the requirement bzr==2.5b4 (from versions: 2.6.0)
>    Some externally hosted files were ignored as access to them may be unreliable (use --allow-external bzr to allow).
> No matching distribution found for bzr==2.5b4
>
> 1 (tmp) gregor@myra ~ % pip install bzr==2.5b4 --allow-external bzr                                                                                                                                                                                                                       :(
> Collecting bzr==2.5b4
>    Could not find a version that satisfies the requirement bzr==2.5b4 (from versions: 2.6.0)
>    Some insecure and unverifiable files were ignored (use --allow-unverified bzr to allow).
> No matching distribution found for bzr==2.5b4
>
> 1 (tmp) gregor@myra ~ % pip install bzr==2.5b4 --allow-external bzr --allow-unverified bzr                                                                                                                                                                                                :(
> Collecting bzr==2.5b4
>    bzr is potentially insecure and unverifiable.
>    Using cached https://launchpad.net/bzr/2.5/2.5b4/+download/bzr-2.5b4.tar.gz
> Building wheels for collected packages: bzr
>    Running setup.py bdist_wheel for bzr
>    Stored in directory: /home/gregor/.cache/pip/wheels/0b/20/62/53308ef6b5481e7df83bcc08eb5f1eb7c54518fbcf1509aaf7
> Successfully built bzr
> Installing collected packages: bzr
> Successfully installed bzr-2.5b4
> pip install bzr==2.5b4 --allow-external bzr --allow-unverified bzr  17.88s user 0.67s system 74% cpu 24.779 total
> |
>
> It only works when running |--allow-unverified| which is not really ideal.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rtfd/readthedocs.org/issues/1369#issuecomment-115197169>.
>

**Comment by gregmuellegger** [comment]
Cool ok. I will close the issue here then. We can track the update of bzr in the #1377 then.
