### ISSUE TITLE
jinja2 exception - unexpected '}'

### ISSUE THREAD

**Issue by michalwski** [rtfd/readthedocs.org#1373]
We didn't change anything in the documentation nor the mkdocs config file but the documentation is not built anymore. Here is the link to a failed build:

https://readthedocs.org/builds/mongooseim/3000853/

and the repo is cloned from here:

https://github.com/esl/MongooseIM

**Comment by d0ugal** [comment]
This is an issue that was resolved in MkDocs 0.14, I need to update ReadTheDocs.

You can work around it by adding this to your config. Basically, it is trying to discover extra templates in your documentation if we set the setting as blank it wont do that.

    extra_templates:

0.14 turned this off by default, as although it was useful having it enabled caused some issues.

**Comment by michalwski** [comment]
Thanks for the advice. This worked for me:
```
extra_templates: []
```

**Comment by d0ugal** [comment]
@michalwski Great. You should be able to remove that hack when #1374 lands.
