### ISSUE TITLE
Build is failing: Top-level Build Failure: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by darklow** [rtfd/readthedocs.org#1378]
Haven't change anything except few `index.rst` text updates and build is now failing.
Few notes:
* `make html` locally is working fine.
* Also tried enabling virtualenv in Admin but it didn't helped.
* Just tried building a version (v.0.1.12) that was working a week ago find and now it also fails.

Error itself also isn't very explanatory:
```
checkout
-----
Top-level Build Failure: 'NoneType' object has no attribute 'replace'
```

I also noticed some errors while compiling:
```
checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/check_libyaml.c -o build/temp.linux-x86_64-2.7/check_libyaml.o
    build/temp.linux-x86_64-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
```

Error and build log:
https://readthedocs.org/builds/django-suit/3010778/

Only a week ago same exact version/commit was working fine:
https://readthedocs.org/builds/django-suit/2957166/

Any ideas?
Thank you

**Comment by Progi1984** [comment]
The same for me : https://readthedocs.org/builds/phppowerpoint/3010900/

**Comment by ericholscher** [comment]
Hmm, this looks like a bug on our side. I'll check it out.

On Fri, Jun 26, 2015 at 4:59 AM, Progi1984 <notifications@github.com> wrote:

> The same for me : https://readthedocs.org/builds/phppowerpoint/3010900/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1378#issuecomment-115655802>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
