### ISSUE TITLE
Upgrade to Celery 3.1

### ISSUE THREAD

**Issue by takotuesday** [rtfd/readthedocs.org#1379]
Celery now has built in support for Django so the use of djcelery would no longer be needed. Upgrading rtd to this version would enable rtd to use the Celery API directly and no longer tie the use of the celery command to manage.py.

**Comment by gregmuellegger** [comment]
That surely would be good as `djcelery` will fade away in the long run I guess. Do you know of any pitfalls that we might encounter when transitioning?

Is that something you are interested in working on? We would really appreciate any pull requests in that regard. I think it's not high in priority on our end to make the change as long as everything works. But I'm happy to review any pull requests in that regard.

**Comment by gregmuellegger** [comment]
We are upgrading to celery 3.1 in the process of #1420 
However we won't make go djcelery go away in that. That's still and open issue.

**Comment by czpython** [comment]
@gregmuellegger @ericholscher Can this be closed given that #1420 has been merged?

**Comment by humitos** [comment]
Closing because #3237
