### ISSUE TITLE
Theme should differentiate python code from parsed-literal

### ISSUE THREAD

**Issue by aebrahim** [rtfd/readthedocs.org#1388]
IPython notebooks are a great way to write docs and convert them to rst. However, the theme makes the code and its output (which is given as a parsed-literal in the rst file) look identical, which makes things a little bit confusing.

This is what an example [notebook] (https://github.com/opencobra/cobrapy/blob/0.3.2/documentation_builder/getting_started.ipynb) looks like: 
![image](https://cloud.githubusercontent.com/assets/1380168/8421442/84e59b3a-1e83-11e5-8b43-b263d94f8f07.png)

This is how readthedocs [renders it](https://cobrapy.readthedocs.org/en/0.3.2/getting_started.html)
![image](https://cloud.githubusercontent.com/assets/1380168/8421453/98c4b956-1e83-11e5-96c8-5cca21960cb9.png)

If the border or background color were changed slightly on the parsed-literal, this would make this way of writing documentation a lot easier.

**Comment by ericholscher** [comment]
This is an issue with the theme, please file it there. https://github.com/snide/sphinx_rtd_theme

**Comment by aebrahim** [comment]
My bad, will do.
