### ISSUE TITLE
Files Copied to rtd_build_path Twice

### ISSUE THREAD

**Issue by ghost** [rtfd/readthedocs.org#1391]
The [move_files](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L661) task in `tasks.py` is called in both `build_docs` and `finish_builds`. Both of which are called by `update_docs`.

This causes the files to be copied twice by the selected syncer.

**Comment by gregmuellegger** [comment]
I reviewed the code just a little and it seems that we indeed could remove the call to `move_files` in `build_docs´. However I haven't actually tested it. Let's get the opinion of someone else as well.

Good catch! Would be cool to reduce the amount of work done there.

**Comment by ericholscher** [comment]
This is done so that the HTML gets updated quickly, before the final syncing of all the files at the end of the build. If we aren't, we should be setting html=False on the second sync, but the idea is to get HTML to the users quickly, and then fill in the remaining assets at the end of the build.

**Comment by destroyerofbuilds** [comment]
@ericholscher, I see what you mean. It seems that `HTML=True` in both cases, so the HTML assets are copied twice.

The quickest solution is to set `HTML=False` on the call to `move_files` in `finish_build`.

**Comment by ericholscher** [comment]
Agreed. Feel free to send a PR that makes this change, along with a comment explaining it (perhaps pointing to this issue)

**Comment by saisrivathsa** [comment]
I have gone through the current files and I don't think this issue persists. The `move_files` task was called twice with `html=True` when the issue was created.

**Comment by stsewd** [comment]
Yeah, this issue isn't valid anymore.

https://github.com/rtfd/readthedocs.org/blob/dfbc8142e70d2ddd893ecabba765690319b5f5aa/readthedocs/projects/tasks.py#L749-L764
