### ISSUE TITLE
Remove Commented Out Code in Tasks File

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1393]
Just a thought, but could the commented-out code found in `projects/tasks.py` be deleted so that it doesn't show up when grepping the code?

**Comment by ericholscher** [comment]
Sure. Feel free to send over a PR.

**Comment by destroyerofbuilds** [comment]
Seems I was on old code. Commented out code was removed by @gregmuellegger as part of 9292f676f0c7219300a06d19b3bbc08990e40056
