### ISSUE TITLE
Build Error: cannot import name UserString

### ISSUE THREAD

**Issue by bendk** [rtfd/readthedocs.org#1395]
Builds for the amara package are failing with this error:

```
Could not import extension readthedocs_ext.readthedocs (exception: cannot import name UserString)
```

Here's an example:
https://readthedocs.org/builds/amara/3036398/

**Comment by ericholscher** [comment]
UserString isn't defined in our project at all. Do your docs build locally?

**Comment by bendk** [comment]
I thought they did, but now that I check they don't anymore.

After testing it a bunch, I realize the issue has to do with six.moves.  I'm not sure why, but somehow one of our dependencies changes that.  It seems like it has to do with raven and/or haystack, but I'm not sure which.  At this point, I guess it's more on us than you and we should close this ticket.

**Comment by bendk** [comment]
FWIW this hack seems to fix things:

https://github.com/pculture/unisubs/commit/48d509e61f980d790ccb9e24615ba6f07a8fbc20
