### ISSUE TITLE
Database Migration Fails for MariaDB Backend

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1398]
The database migration step fails when running the migration against a MariaDB database.

**Comment by gregmuellegger** [comment]
readthedocs.org only runs on Postgres and there is no plan to support other database backends as this would add quite some testing overhead. However see my comment in #1397 regarding the patch for this.

**Comment by gregmuellegger** [comment]
I'm closing this as this will be addressed in Django 1.8 with #1420 Also see my latest comment in #1397
