### ISSUE TITLE
Add support for automake

### ISSUE THREAD

**Issue by geertj** [rtfd/readthedocs.org#1401]
My project has a dependency on the Python module "pyuv".

The setup script for this module downloads libuv, which requires automake and autoconf. The build process fails because it cannot find automake.

Note: autoconf is needed too, so if that's not present, than this is a request to add autoconf as well.

**Comment by agjohnson** [comment]
Unless libuv is used directly in doc generation, you should mock out dependencies like this as per the documentation at:
http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by agjohnson** [comment]
@geertj does this solve your problem?

**Comment by ericholscher** [comment]
Closing this for lack of feedback.
