### ISSUE TITLE
ExtractionError: Can't extract file(s) to egg cache

### ISSUE THREAD

**Issue by IvanMalison** [rtfd/readthedocs.org#1402]
ExtractionError: Can't extract file(s) to egg cache

The following error occurred while trying to extract file(s) to the Python egg
cache:

  [Errno 13] Permission denied: '/root/.python-eggs'

I'm getting this consistently in my builds.

It seems like the solution should be to set the PYTHON_EGG_CACHE environment variable but I dont see an easy way to do this

**Comment by gregmuellegger** [comment]
This might be related to #1394.

**Comment by agjohnson** [comment]
@IvanMalison Is this for a Python 3 project?

**Comment by agjohnson** [comment]
I have deployed a fix the our build servers, check to see if this is still an issue.

**Comment by gregmuellegger** [comment]
Closing this as I assume it was fixed. @IvanMalison feel free to open a new ticket if it's still an issue for you.

**Comment by IvanMalison** [comment]
Yep. Things look good!
