### ISSUE TITLE
Only show V button on "View Docs" if there are >1 version

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1411]
We show the Dropdown for projects with 1 version, which makes no sense. Only show it if there are > 1 version.

**Comment by ericholscher** [comment]
Also consider moving search to the bottom.

**Comment by stsewd** [comment]
Do you mean this? I think we already got it.

## More than one version

![screenshot-2017-12-27 welcome to the zulip documentation zulip 1 7 1 git documentation 2](https://user-images.githubusercontent.com/4975310/34396427-c123b53a-eb38-11e7-9976-3197974629dd.png)

## Single version

![screenshot-2017-12-27 welcome to the zulip documentation zulip 1 7 1 git documentation 3](https://user-images.githubusercontent.com/4975310/34396429-c59ec15e-eb38-11e7-8ce3-07a4535028b1.png)

**Comment by agjohnson** [comment]
No, i think this describes the "View Docs" button on the version list page. I think this is resolved -- either we're doing the above logic already, or i probably removed the dropdown completely
