### ISSUE TITLE
RFE: Custom documentation build

### ISSUE THREAD

**Issue by sils1297** [rtfd/readthedocs.org#1412]
Hi,

wouldn't it be easy for you and cool for the users to be able to just build a webpage with arbitrary commands and you serve it? I'd love to use pandoc with a few custom tweaks here and there, building the commands is easy.

**Comment by agjohnson** [comment]
Would we be executing the commands? Or would we be accepting arbitrary HTML? I think either way this is outside the scope of what we want to do. We support Sphinx, and don't have much interest in being a naive web hosting provider.

**Comment by sils1297** [comment]
Well, how about pandoc support then? Preferably with the mddia preprocessing script for generating flow charts and stuff.

I'd really love be able to use pandocs gorgeous and powerful markdown for building docs.

**Comment by agjohnson** [comment]
We want to support Markdown as a secondary format, but where we support rST + Sphinx, we don't see much benefit in supporting Markdown mashups to make Markdown behave more like rST. At least not with our development time.

We already have mkdocs as an option, and we have Markdown in Sphinx support in the pipeline, I don't think we'll fragment our efforts any more on Markdown. We might accept a patch for this if anyone is willing to go through the design process with us and get a proper backend for pandoc however.

We're happy to guide anyone on this if they are willing to own it.

**Comment by ericholscher** [comment]
Closing this, as we won't be supporting custom build commands any time soon.
