### ISSUE TITLE
Websockets not working on /live page

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1414]
I was testing the [live](https://readthedocs.org/live/) page to verify behavior of the ReadTheDocs project, but noticed in dev-tools that the live updating was not working.

I received the following in dev-tools:

```
Mixed Content: The page at 'https://readthedocs.org/live/' was loaded over HTTPS, but attempted to connect to the insecure WebSocket endpoint 'ws://websocket.readthedocs.org:8088/websocket'. This request has been blocked; this endpoint must be available over WSS.(anonymous function) @ 

Uncaught SecurityError: Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.
```

**Comment by agjohnson** [comment]
This is a half baked feature, use of websockets was experimental here

**Comment by gregmuellegger** [comment]
@agjohnson What's the resolution here, shall we remove the related code?

**Comment by ericholscher** [comment]
+1 on removing it.

On Mon, Jul 13, 2015 at 2:17 AM, Gregor Müllegger <notifications@github.com>
wrote:

> @agjohnson <https://github.com/agjohnson> What's the resolution here,
> shall we remove the related code?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1414#issuecomment-120864373>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
This has been removed.
