### ISSUE TITLE
NGINX_X_ACCEL_REDIRECT No Longer Used

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1415]
Seems `NGINX_X_ACCEL_REDIRECT` option in the setting files is no longer used. Looks to have been refactored out after pull request [366](https://github.com/rtfd/readthedocs.org/pull/366).

**Comment by alexbarcelo** [comment]
I have just found this, which is closed, but the `dev.py` settings file is still using that parameter, which is no longer used...?

Or I am missing something?

**Comment by RichardLitt** [comment]
Looks like there may be some extra work to do. Want to help us with a pull request, @alexbarcelo?

**Comment by RichardLitt** [comment]
Thanks @alexbarcelo!
