### ISSUE TITLE
Tastyapi Client no longer used

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1416]
I was trying to find where the `IMPORT_EXTERNAL_DATA` setting was used, but the only file that uses that setting `tastyapi/client.py` does not seem to be used any longer.

It looks like the other use of `tastyapi/client.py` was removed in bf1a3d2c49150f3b6d4362625375457cb7817fa2

**Comment by gregmuellegger** [comment]
I addressed this in #1458

**Comment by destroyerofbuilds** [comment]
Closed by #1458
