### ISSUE TITLE
Bad gateway errors

### ISSUE THREAD

**Issue by claesenm** [rtfd/readthedocs.org#1419]
I'm getting a lot of bad gateway errors when accessing one of my project's pages: https://readthedocs.org/projects/optunity/

The error (picture attached)
![badgateway](https://cloud.githubusercontent.com/assets/5254910/8598353/80637f8a-265a-11e5-8ee0-60ee49d25d6a.png)
:
502 Bad Gateway

nginx/1.4.6 (Ubuntu)

The builds are also taking very long, one is triggered for 19 min so far. I'm not sure if the problem is on my side or RTD...

**Comment by ericholscher** [comment]
Yea, this was an issue on our side. It should be resolved now, you might
need to re-trigger your build.

On Thu, Jul 9, 2015 at 7:47 AM, Marc Claesen <notifications@github.com>
wrote:

> I'm getting a lot of bad gateway errors when accessing one of my project's
> pages: https://readthedocs.org/projects/optunity/
>
> The builds are also taking very long, one is triggered for 19 min so far.
> I'm not sure if the problem is on my side or RTD...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1419>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by claesenm** [comment]
Working perfectly now, thanks!
