### ISSUE TITLE
On GitHub: View / Edit points to wrong url

### ISSUE THREAD

**Issue by HelloZeroNet** [rtfd/readthedocs.org#1422]
The View / Edit links are broken on the panel that appears when clicking on bottom left arrow.

Example:
http://zeronet.readthedocs.org/en/latest/faq/
 - Points to: https://github.com/HelloZeroNet/Documentation/blob/master/docs/Frequently%20asked%20questions.md
 - It shoud: https://github.com/HelloZeroNet/Documentation/blob/master/docs/faq.md

**Comment by ericholscher** [comment]
CLosing as a dupe of #1483
