### ISSUE TITLE
Link to PDF in RTD popup menu shows even though PDF build is turned off

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#1425]
See https://github.com/rtfd/readthedocs.org/pull/1344#issuecomment-120510729

The link is in the RTD popup menu
![RTD popup menu](http://i.imgur.com/9E5C1Sl.png)

An example is in [Pyramid docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/).

**Comment by gregmuellegger** [comment]
I've added PR #1431 for this. Thanks for the report :sunglasses:

**Comment by stevepiercy** [comment]
Thank you!
