### ISSUE TITLE
too-old setuptools (likely due to too-old virtualenv)

### ISSUE THREAD

**Issue by rbtcollins** [rtfd/readthedocs.org#1426]
Virtualenv bundles pip, wheel and setuptools. The Python packaging ecosystem is moving quite rapidly at the moment, and the version of virtualenv used to build the docs is sufficiently old that the bundled setuptools cannot handle the new version of mock (which needs setuptools 17.1).

Options:
1. upgrade your virtualenv to 13.1.0
2. add a call to pip install -U pip wheel setuptools between making the virtualenv and installing projects

**Comment by ericholscher** [comment]
I believe you should be able to specify this in your requirements file also. Which seems like a good idea if you require a specific, newer version. I'll look into upgrading our versions as well though.

**Comment by ericholscher** [comment]
Ah, I see, it's the bundled verisons in venv. I will update that.
