### ISSUE TITLE
setuptools being downgraded

### ISSUE THREAD

**Issue by rbtcollins** [rtfd/readthedocs.org#1428]
This is a follow-on to #1426. With the newer virtualenv the requirements.txt processing does manage to complete, but the install target fails due to very old setuptools (1.1!) - the doc_builder target appears to be downgrading it to 1.1 in the middle. :(.
```
doc_builder
-----

Collecting sphinx==1.3.1
...
Collecting virtualenv==1.10.1
Collecting setuptools==1.1
...
  Found existing installation: setuptools 18.0.1
    Uninstalling setuptools-18.0.1:
      Successfully uninstalled setuptools-18.0.1
Successfully installed Jinja2-2.7.3 Markdown-2.6.2 PyYAML-3.11 Pygments-2.0.2 alabaster-0.7.6 babel-1.3 backports.ssl-match-hostname-3.4.0.2 certifi-2015.4.28 click-4.0 commonmark-0.5.4 docutils-0.11 livereload-2.4.0 markupsafe-0.23 mkdocs-0.14.0 mock-1.0.1 nilsimsa-0.3.7 pillow-2.6.1 pytz-2015.4 readthedocs-sphinx-ext-0.5.4 recommonmark-0.1.1 requests-2.7.0 setuptools-1.1 six-1.9.0 snowballstemmer-1.2.0 sphinx-1.3.1 sphinx-rtd-theme-0.1.8 tornado-4.2 virtualenv-1.10.1
```

This is from https://readthedocs.org/builds/mock/3074098/

**Comment by rbtcollins** [comment]
And https://github.com/rtfd/readthedocs.org/blob/b4c6c7bcd750bd0751c7a151b485b22df932a435/readthedocs/projects/tasks.py#L335 seems to be the culprit. I don't know why setuptools 1.1 is being pinned - but its really rather old. In fact - https://github.com/rtfd/readthedocs.org/commit/d5d71c0d1e326a38ab607d2e688982e439b3c35e is where it was introduced.

Would a PR to bump that to 18 be acceptable?

**Comment by gregmuellegger** [comment]
I created #1429 as a fix. I want to get it reviewed before we can deploy it. If you need a very quick workaround you can pin the setuptools/virtualenv versions you need in your repo's `requirements.txt`.

**Comment by ericholscher** [comment]
Should be deployed.

On Mon, Jul 13, 2015 at 12:45 AM, Gregor Müllegger <notifications@github.com
> wrote:

> I created #1429 <https://github.com/rtfd/readthedocs.org/pull/1429> as a
> fix. I want to get it reviewed before we can deploy it. If you need a very
> quick workaround you can pin the setuptools/virtualenv versions you need in
> your repo's requirements.txt.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1428#issuecomment-120840262>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
