### ISSUE TITLE
Add custom styling for CSRF error

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1430]
In #1268 we found that the CSRF error sometimes happens when some headers are blocked. We cannot really avoid that, but we could make the styling more appealing so that users don't see the Django default error page for this.

To override the styling the csrf failure view, this can be used: https://docs.djangoproject.com/en/1.8/ref/settings/#csrf-failure-view

**Comment by agjohnson** [comment]
Yes, i've been meaning to get something in for this for a while.

**Comment by agjohnson** [comment]
I have some thoughts here, as we are talking about error pages at several levels. I'll mock up what I have in mind maybe this weekend.
