### ISSUE TITLE
Consider Using django-gulp

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1434]
Please consider employing [django-gulp](https://pypi.python.org/pypi/django-gulp/2.0.0).

`django-gulp` intercedes at the beginning of `runserver` and `collectstatic`, running `gulp` prior to the normal actions of those Django commands.

`django-gulp` would allow the `browserify` task to run, building the contents of the `static-src` directory at runtime, instead of needing to commit build artifacts to the repository.

**Comment by agjohnson** [comment]
This is a deployment decision for now. We may replace this step with precompilation before deployment at some point, but we will not be compiling assets on each server with this.

**Comment by destroyerofbuilds** [comment]
@agjohnson, though you are correct that deployment should be a consideration, I argue that your duplication of code in the code base is not only bad practice (submitting build artifacts to a source code repository), but is detrimental to people that wish to contribute (because they have to know how to run `npm install` followed by `gulp`, and then remember to not only add their changed file, but the build artifact as well. None of which is documented by ReadTheDocs).

Regardless of how you decide to deploy ReadTheDocs in production, you should consider the following:
1. Remove build artifacts from this repository.
2. Eliminate the gulp build step from the developer workflow to mitigate human error.

**Comment by agjohnson** [comment]
Yes, I meant to write documentation on front end development, it's written somewhere, but apparently not here. I'll make a ticket and take ownership on actually getting that into our docs now.

We know the limitations around checking in bundles, but it's less error prone than assuming contributors need to instantiate our full front end stack to just make simple changes. This is an intermediate design decision that we've made to start modernizing some outdated code while still easing development. The next step might be getting closer to what you describe.

No matter what the option, it still requires node, npm dependencies, and bower dependencies. When we revisit front end dependencies, and either break some stuff out or create a workflow that requires developers to have the full front end stack installed, we'll likely consider using something like django-gulp, or going back to django-compressor more likely, to make this implicit.
