### ISSUE TITLE
Search has problems with special chars ", : . " in the search string

### ISSUE THREAD

**Issue by KSSonline** [rtfd/readthedocs.org#1435]
We are having a lot of strings like "php::class" or "TYPO3.Neos:Headline" which are therefore common search strings. We figured out, that as soon as a special char like ":" is in the search string, the search won't find anything at all. If you remove the chars by hand, then you find what you are searching for.

Example of current search:
Open: http://neos.readthedocs.org/en/stable/Appendixes/CommandReference.html#typo3-neos-domain-activate
Search for: typo3.neos:domain:activate
Search result: Your search did not match any documents. [...]

Expected Search Result:
Search finished, found 9 page(s) matching the search query.

Neos Command Reference
...e was automatically generated from code on 2015-06-05 Package *TYPO3.NEOS* -------------------- ``typo3.neos:domain:activate`` ****************************** **Activate a domain record** Arguments ^^^^^^^^^ ``--host-pattern`` The... 

Possible solution:
Strip out the special chars of the provided search string before passing it to the elastic search

**Comment by dogweather** [comment]
Came here to report this as well. Here's an example:

![screenshot 2015-08-01 20 22 16](https://cloud.githubusercontent.com/assets/150670/9024597/bd8e7d1c-388c-11e5-9d7a-34de419a7e00.png)

![screenshot 2015-08-01 20 22 09](https://cloud.githubusercontent.com/assets/150670/9024598/caf1011e-388c-11e5-9f33-c1579a9c0e07.png)

**Comment by gregmuellegger** [comment]
I guess a solid resolution to this is quite tricky. I don't have a good strategy for this in mind.
I'm deferring this to @ericholscher and @agjohnson. They are quite experienced with the search system and might have a solution in mind.

**Comment by ericholscher** [comment]
I believe this is actually a Sphinx issue, where it is indexing these objects. Read the Docs search should be stripping them out: https://readthedocs.org/projects/neos/search/?q=typo3.neos%3Adomain%3Aactivate -- the main issue is that we need to integrate the RTD Elastic Search-based search into the main Sphinx search page via the API.
