### ISSUE TITLE
Allow change of project slug

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1440]
We should make it possible to change the slug of a project. There are valid
reasons for it.

This was reported by @nanuxbe in #327. She wrote:

> BitBucket is one example of a name change leading to a slug change.
> I can see the need of keeping the slug stable as for search engine and external links but this is also the reason why changing the slug can be important as urls are very important to search-engines. Here's my current situation and why I'm interested in the topic:
> I recently had to rename a project because the project's name was a slur word in some language which I was not aware of at time of creation.
> Now that the project had been renamed I really don't want that project's read-the-docs pop up as search results for that slur word but in keeping the slug, this is likely to happen.
> Also, now that the project has been renamed, people with a new interest in the project might instinctively check https://slug-of-new-name.readthedocs.org
> 
> I don't have any insight with RTD name change statistics, but I would guess that people don't change the name of a project that often and that, when they do, they have a good reason to do it and don't want the old name to still be associated with the project (think of name change due to copyright infringement too), which is likely to happen if the project still has its old name as RTD slug.
> Now I realize this probably doesn't happen often and should probably not be treated as a high-priority issue but I thought it was still worth raising the question.
> 
> Maybe making the slug change optional when someone renames a project would be an acceptable solution. Let the user decide if they want to keep that url stable or if they want to change it?

**Comment by Progi1984** [comment]
I have exactly the problem.

My project : https://github.com/PHPOffice/PHPPowerPoint/ has been renamed to https://github.com/PHPOffice/PHPPresentation

I want the same with docs but impossible. Have you a solution ?

**Comment by Progi1984** [comment]
Some news ?

**Comment by IanLee1521** [comment]
@Progi1984 I just did this "rename" for pep8 -> pycodestyle today by making a new project with the new name. I need to figure out how to tell people about it now, but at least I have the new url available and I can start publicizing that one instead.

**Comment by dojutsu-user** [comment]
Is this issue still open.
I am interested in sending a PR on this.

**Comment by humitos** [comment]
@dojutsu-user yes, this issue is marked as `Accepted`. Feel free to start working on it and sending a PR. Thanks!

**Comment by stsewd** [comment]
There are still some design decisions here, we were talking about this. And isn't clear how this would affect the commercial site, where we use slugs in a different way.

**Comment by humitos** [comment]
For now, this will keep being handled by specific requests and the user won't be able to change the slug by themselves until we make some decisions about it.

**Comment by dojutsu-user** [comment]
@humitos 
I think this issue can be closed.

**Comment by humitos** [comment]
Closing. More info at https://github.com/rtfd/readthedocs.org/pull/5403
