### ISSUE TITLE
Add GitLab Provider from django-allauth

### ISSUE THREAD

**Issue by takotuesday** [rtfd/readthedocs.org#1441]
Add GitLab as an option to Social Accounts so that users can connect rtd accounts to thier GitLab repositories. There seems to be the demand and use cases, as discussed in #1068. 

Once this [issue](https://github.com/pennersr/django-allauth/issues/964) is resolved,  integrate the gitlab provider into rtd.

**Comment by saily** [comment]
Hi, the gitlab provider is implemented, it just needs to be merged, see: https://github.com/pennersr/django-allauth/pull/1231

**Comment by destroyerofbuilds** [comment]
@saily++

**Comment by saily** [comment]
merged, let's wait for a new release and then update our version pins in `requirements.txt`.

**Comment by agjohnson** [comment]
Commit is pinned with work in #1850, which should also include the commits required here. #1893 addresses bumping to the next release.
