### ISSUE TITLE
Add GitLab Web Hook End-Point

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1442]
Need to add an end-point to Read the Docs to received on-push events from a GitLab installation.

The GitLab end-point would be similar to Read the Docs' existing [GitHub support](https://github.com/rtfd/readthedocs.org/blob/1511716c9c984e7a53521c0fcc91e50f49e1473c/readthedocs/core/views.py#L197-L274) with only minor changes needed to support the slightly different response sent by a GitLab web hook POST.

POST body sent as a result of a push event is documented [here](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/web_hooks/web_hooks.md).

**Comment by destroyerofbuilds** [comment]
I would like to assign this to myself.

**Comment by destroyerofbuilds** [comment]
I just realized, there is test code for the GitHub end-point in `test_post_commit_hooks.py`. No Bitbucket tests though.

Should I add tests for GitLab? If so, how would I go about doing that since it seems the file is setup for only testing GitHub?

**Comment by agjohnson** [comment]
Yes, we should have tests for integrations, including the missing ones for bitbucket. I'll open a separate issue for that.
