### ISSUE TITLE
Setup GitLab Web Hook on Project Import

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1443]
When a GitLab project is imported into Read the Docs, the imported project's GitLab project needs to be automatically setup with a Read the Docs web hook.

Support already exists for [GitHub and Bitbucket](https://github.com/rtfd/readthedocs.org/blob/1511716c9c984e7a53521c0fcc91e50f49e1473c/readthedocs/projects/signals.py#L26)

This enhancement must wait until #1442 has been completed, and a Read the Docs service has been upstreamed to GitLab's Community Edition code base.

**Comment by BuddhaOhneHals** [comment]
Will be fixed with #1870 
A Read the Docs service within GitLab is not needed.
