### ISSUE TITLE
Add Read the Docs Service to GitLab

### ISSUE THREAD

**Issue by destroyerofbuilds** [rtfd/readthedocs.org#1444]
Needs to add a new Read the Docs service to GitLab. The service is a web hook service that would be setup on a GitLab project as a result of #1443 

Tracking here to keep beside all the other GitLab issues, and because I don't have an account on GitLab.com.

**Comment by agjohnson** [comment]
We'll set this up under a RTD owned account once the webhook exists.

**Comment by destroyerofbuilds** [comment]
@agjohnson , would you mind adding this to the GitLab milestone?

Also, I think the actual service will need to be added through the commit of a new [GitLab Service Project](https://gitlab.com/gitlab-org/gitlab-ce/tree/master/app/models/project_services).

**Comment by agjohnson** [comment]
This was added last week. We have an application on GitLab similar to how we have an application with GitHub
