### ISSUE TITLE
RTD template and Mac OS X scroll behaviour

### ISSUE THREAD

**Issue by tfeldmann** [rtfd/readthedocs.org#1445]
The RTD sphinx template has problems with the Mac OS X Safari scroll behaviour. If you scroll past the top and the page bounces back the navigation is partly hidden (see the attached video).
![rqmhq0idyg](https://cloud.githubusercontent.com/assets/385566/8746905/4b0c7de8-2c8e-11e5-83cf-cc2cf06e6ceb.gif)

**Comment by agjohnson** [comment]
This is a bug with sphinx_rtd_theme, it should be addressed there. Feel free to open a ticket.

I've noted the issue in Safari as well but should try to get a fix in for the 0.1.9 release there.

**Comment by tfeldmann** [comment]
Thank you. I opened an issue in sphinx_rtd_theme.

**Comment by agjohnson** [comment]
@tfeldmann thanks! i'll take a look at it shortly
