### ISSUE TITLE
Local VM Install only build docs with 127.0.0.1 address

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1447]
I have a local VM installation of ReadTheDocs.  

Documentation builds successfully when ReadTheDocs is launched from "./manage.py runserver" and the builds are kicked off from a browser on the local machine.

However, the build process does not seem to start when ReadTheDocs is launched from "./manage.py runserver [VM IP ADDRESS]:8000" and the browser is on a non-local machine.  The build state remains as "Triggered" for always and forever more.

The git repos are not local to the VM but are on a machine on the WAN.

Would anyone have any idea?

**Comment by agjohnson** [comment]
This isn't something we can really help with, if you are deviating from our supported development installation. My only guess would be that you don't have celery configured correctly, it should be always eager resolution on tasks.

**Comment by Balooga** [comment]
I'll check thanks.

Somewhat related/unrelated question.  Your commercial offering of ReadTheDocs; will this support the configuration I described above?  Having all servers and repos internal to a company WAN?

**Comment by takotuesday** [comment]
@Balooga can you elaborate a bit more on your vm set up? Are you using sqlite? Which settings .py file are you using?

**Comment by agjohnson** [comment]
@Balooga It won't be available after our initial launch, but we do plan to have an installable instance available for companies sometime in the future

**Comment by Balooga** [comment]
The latest git version of ReadTheDocs running on top of Centos SCL & Python 2.7.

It's a vanilla install using the instructions from https://read-the-docs.readthedocs.org/en/latest/install.html, apart from a "local_settings.py" file containing ALLOW_PRIVATE_REPOS = True

**Comment by Balooga** [comment]
After clicking "Build Version:", the output of "./manage.py runserver apollocreed.isg.directv.com:8000" ends as follows;

[17/Jul/2015 16:54:11] INFO [requests.packages.urllib3.connectionpool:180] Starting new HTTP connection (1): localhost
[17/Jul/2015 16:54:11] "POST /build/24 HTTP/1.1" 302 0
[17/Jul/2015 16:54:11] "GET /builds/edm-v/ HTTP/1.1" 200 10856

**Comment by takotuesday** [comment]
what do you have the SLUMBER_API_HOST set to? I would take a look at your settings, if SLUMBER vars are not configured correctly than you may experience hanging builds.

**Comment by Balooga** [comment]
Thank you!  I modified the value of SLUMBER_API_HOST to the address of the VM, and now everything works.
