### ISSUE TITLE
Account inactive

### ISSUE THREAD

**Issue by titusz** [rtfd/readthedocs.org#1451]
When I try to login at https://readthedocs.org/accounts/login/ I always get the error: `This account is currently inactive`. I did a successful password reset but I still get the same error at login.

I tried to get help via irc but got no response. My username is **`titusz`**. It would be great if some of the admins could checkout why the account is `inactive` and maybe hit the `active` flag in the admin interface.

And by the way: Thanks for this great project.

**Comment by ericholscher** [comment]
I've marked your account active. Sorry this took a while to get to.

**Comment by titusz** [comment]
There is absolutely no need apologize. I very much appreciate you volunteered to fix this. **Thank you very much!**
