### ISSUE TITLE
Latest PDF links to stale file, despite build succeeding

### ISSUE THREAD

**Issue by jnmclarty** [rtfd/readthedocs.org#1452]
My pdfs appear to be building fine, however after 12h, it's still serving up a pdf from a few builds ago.  I just forced a new build, and it seems to have built fine, but the pdf from the 18th is still being served.

Project is here: http://trump.readthedocs.org/en/latest/

As soon as it serves a PDF from the 19th, I believe it'll be working.

I'm wondering if it has t odo with the RTD web-server caching, and not so much read the docs.  Maybe time will solve? If so, how long to expect?

See also #1120 and #1121

**Comment by jnmclarty** [comment]
Ok, so pressing the "latest" link, will direct you to:

https://cdnmedia.readthedocs.org/pdf/trump/latest/trump.pdf

...but, my hunche was right, it is a web-server caching kind-of problem, because if I hit:

http://media.readthedocs.org/pdf/trump/latest/trump.pdf

I get the correct latest build.  Maybe this stuff gets refreshed nightly or periodically?

**Comment by ericholscher** [comment]
Ah, this is likely a bug in our server settings. I'll try and get it
addressed today.

On Sun, Jul 19, 2015 at 1:33 PM, Jeffrey McLarty <notifications@github.com>
wrote:

> Ok, so pressing the "latest" link, will direct you to:
>
> https://cdnmedia.readthedocs.org/pdf/trump/latest/trump.pdf
>
> ...but, my hunche was right, it is a web-server caching kind-of problem,
> because if I hit:
>
> http://media.readthedocs.org/pdf/trump/latest/trump.pdf
>
> I get the correct latest build. Maybe this stuff gets refreshed nightly or
> periodically?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1452#issuecomment-122701764>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
This was an issue with our CDN which is now fixed.
