### ISSUE TITLE
Move readme to index rather than copy

### ISSUE THREAD

**Issue by JakeGinnivan** [rtfd/readthedocs.org#1453]
Hey,

I am just getting started using readthedocs and am wondering why the change (see https://github.com/rtfd/readthedocs.org/commit/b1a037066b39b428471604674ed7b2ce68382496) to copy instead of move? I now get both the HOME and README pages when I really just want HOME.

**Comment by ericholscher** [comment]
Hmm, not sure. I believe there was an issue with moving them, but I don't remember what it was. We can likely support that.

**Comment by JakeGinnivan** [comment]
Suppose you will now find out the other way what the issue is :) Thanks, it is a minor thing but I like being able to browse both the docs folder on github and readthedocs. Having the index called readme makes that nicer
