### ISSUE TITLE
Choosing search index summary

### ISSUE THREAD

**Issue by AbdealiJK** [rtfd/readthedocs.org#1454]
Currently at coala we use the following home page - http://coala.readthedocs.org/en/latest/

Due to this, the default summary provided by google is:
```
.o88Oo._ d8P .ooOO8bo._ 88 '*Y8bo. __ YA '*Y8b __ ,dPYb, YA 68o68**8Oo.
IP'`Yb "8D *"' "Y8o I8 8I Y8 'YB .8D I8 8P '8 d8' 8D I8 8' 8 d8888b d AY ,gggo, ...
```

Is there a way to make search indexes ignore the ascii art ? It'd be nice to be able to choose which section should be indexed by search engines

**Comment by gregmuellegger** [comment]
I'm not 100% sure, but I think google is using the `<meta name="description" content="...">` as the summary in the search result if available. You can use the ReST `meta` directive to set it:

```
.. meta:
    :description: Coala is more than just ASCII art
```

See here for the docs http://docutils.sourceforge.net/docs/ref/rst/directives.html#meta (It's currently offline but will hopefully come back later today)

**Comment by AbdealiJK** [comment]
We use mkdocs, and according to mkdocs the equivalent way of adding metadata is:

http://pythonhosted.org/Markdown/extensions/meta_data.html

I'll try this and get back to you :) Thanks

**Comment by AbdealiJK** [comment]
According to the `mkdocs` docs - http://www.mkdocs.org/user-guide/configuration/
What I needed was `site_description` in mkdocs.yml

Thanks !
