### ISSUE TITLE
Review current code base regarding i18n

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1455]
As suggested in #1157 we should walk through the code base and make sure that all relevant strings in Python files, JavaScript files and templates are marked as translatable.

**Comment by stsewd** [comment]
Related #3561

**Comment by stsewd** [comment]
We can close this in favor of https://github.com/rtfd/readthedocs.org/issues/3561 and https://github.com/rtfd/readthedocs.org/issues/2607 and related ones.
