### ISSUE TITLE
ASP.NET documentation is using RTFD!

### ISSUE THREAD

**Issue by weitzhandler** [rtfd/readthedocs.org#1456]
I'm sure you noticed the official ASP.NET documentation team is using your repo to represent their documentation, pointing to it from Visual Studio and the project templates ReadMe file!

Anyway, I thought it would be worth putting it on the "Featured Projects" on RTD homepage.

**Comment by destroyerofbuilds** [comment]
http://docs.asp.net/en/latest/

**Comment by weitzhandler** [comment]
@destroyerofbuilds haha oops forgot to include link...
tx

**Comment by gregmuellegger** [comment]
:tada: That's super cool! Thanks for letting us know. We'll hope any major vendor realizes that this the platform to go to :) There are many more features in the pipe to make it even more attractive for companies to host their docs here.

Stay tuned.
