### ISSUE TITLE
Help with access to Django Filter

### ISSUE THREAD

**Issue by carltongibson** [rtfd/readthedocs.org#1460]
Hi. 

I'm maintaining [Django Filter](https://github.com/alex/django-filter). I need to manage the [RTD project for it](https://readthedocs.org/projects/django-filter/). 

Unfortunately, neither I, nor Alex Gaynor — who originally created Django Filter — know [the RTD user who owns the project on RTD](https://readthedocs.org/profiles/jamespacileo/).

My RTD username is `[carltongibson](https://readthedocs.org/profiles/carltongibson/)`. Could you help me by adding me to the Django Filter project on RTD? 

Thanks!

**Comment by gregmuellegger** [comment]
Seems legitimate. Carlton has permissions on the alex/django-filter repository.
@ericholscher @agjohnson could you make this happen?

**Comment by carltongibson** [comment]
Thanks @gregmuellegger — we can @mention a few people if you need someone known to vouch.

**Comment by ericholscher** [comment]
Should have access now.

**Comment by carltongibson** [comment]
Awesome thanks!
