### ISSUE TITLE
Add Version Compare information to the RTD Footer Response

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1463]
We want to unify the API calls for `/api/v1/<project>/highest/<version>` and `/api/v2/footer_html` in order to reduce the number of API calls.

**Comment by gregmuellegger** [comment]
@ericholscher I have a few questions regarding this task.

1. The version comparison call is part of API v1. Shall this be moved into API v2? Do we need to stay backwards compatible?
2. The API calls are made from the `readthedocs/core/static-src/core/js/readthedocs-doc-embed.js` file. I noticed that the API is also called from the `media/javascript/rtd.js` file. Is this file still relevant?

**Comment by ericholscher** [comment]
We should just move the logic into the footer response. I don't believe we
need to maintain backwards compat, I don't think. It might make sense to
keep the logic seperate, and have an API endpoint for it, but to embed it
in the footer response on doc page load to decrease server requests, but
keep it available.

I believe rtd.js is old -- likely around for docs that haven't been rebuilt
in a long time.

On Tue, Jul 21, 2015 at 6:41 AM, Gregor Müllegger <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher> I have a few questions
> regarding this task.
>
>    1. The version comparison call is part of API v1. Shall this be moved
>    into API v2? Do we need to stay backwards compatible?
>    2. The API calls are made from the
>    readthedocs/core/static-src/core/js/readthedocs-doc-embed.js file. I
>    noticed that the API is also called from the media/javascript/rtd.js
>    file. Is this file still relevant?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1463#issuecomment-123308650>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by gregmuellegger** [comment]
> The API calls are made from the readthedocs/core/static-src/core/js/readthedocs-doc-embed.js file. I noticed that the API is also called from the media/javascript/rtd.js file. Is this file still relevant?

@ericholscher What's your take on this?

**Comment by gregmuellegger** [comment]
Sorry ignore my comment. Your take on the rtd.js was hidden in the github UI because it thought it was part of the quoted email text...
