### ISSUE TITLE
Build fails without explanation when claiming to pass

### ISSUE THREAD

**Issue by carljm** [rtfd/readthedocs.org#1464]
The RTD-hosted docs at http://susydocs.oddbird.net/en/latest/ are not being styled. They are using the default theme. Latest Firefox and Chrome both show two console errors related to RTD CSS assets:

```
The stylesheet https://media.readthedocs.org/css/readthedocs-doc-embed.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
```

```
The stylesheet https://media.readthedocs.org/css/sphinx_rtd_theme.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
```

(I note that another random project with working styling, http://django-model-utils.readthedocs.org/en/latest/, is using slightly different links for these CSS files -- at `cdnmedia.readthedocs.org` instead of `media.readthedocs.org`.)

I thought maybe a new build would fix the problem, but builds seem to be failing in a very strange way for the Susy project. The dashboard claims the build passes, but the actual docs never update. And looking at the build output shows several errors -- a "Build Standard Error" and an "Environment Standard Error" are both listed without explanation. Local Sphinx builds work fine for this repo.

A full sample build log is at https://readthedocs.org/builds/susy/3123972/ for anyone with admin access who can see that.

Any clue greatly appreciated.

**Comment by ericholscher** [comment]
This was a short lived deployment bug that should now be resolved.

On Tue, Jul 21, 2015 at 9:15 AM, Carl Meyer <notifications@github.com>
wrote:

> The RTD-hosted docs at http://susydocs.oddbird.net/en/latest/ are not
> being styled. They are using the default theme. Latest Firefox and Chrome
> both show two console errors related to RTD CSS assets:
>
> The stylesheet https://media.readthedocs.org/css/readthedocs-doc-embed.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
>
> The stylesheet https://media.readthedocs.org/css/sphinx_rtd_theme.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
>
> (I note that another random project with working styling,
> http://django-model-utils.readthedocs.org/en/latest/, is using slightly
> different links for these CSS files -- at cdnmedia.readthedocs.org
> instead of media.readthedocs.org.)
>
> I thought maybe a new build would fix the problem, but builds seem to be
> failing in a very strange way for the Susy project. The dashboard claims
> the build passes, but the actual docs never update. And looking at the
> build output shows several errors -- a "Build Standard Error" and an
> "Environment Standard Error" are both listed without explanation. Local
> Sphinx builds work fine for this repo.
>
> A full sample build log is at https://readthedocs.org/builds/susy/3123972/
> for anyone with admin access who can see that.
>
> Any clue greatly appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1464>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by carljm** [comment]
Thanks @ericholscher! The lack-of-styling issue does seem to be resolved. Unfortunately the builds still aren't working. I triggered another one, with the same mysterious "Build Standard Error" and "Environment Standard Error" results in the build output (and no changes reflected in the live docs), even though the build claims to be "Passed" in the builds list: https://readthedocs.org/builds/susy/3125279/

**Comment by carljm** [comment]
For a litmus test of whether a new build has actually been deployed, see the two CSS code blocks at https://github.com/ericam/susy/blob/master/docs/install.rst#bower are missing at http://susydocs.oddbird.net/en/latest/install/#bower

I pushed a fix to the syntax for those code blocks this morning, and they render correctly locally. I've manually triggered several builds since then which claim to be `Passed`, but the built output hasn't changed.

**Comment by modulec** [comment]
I've just installed the new instance from latest commit. From what I see 
this folder 

/home/docs/checkouts/readthedocs.org/user_builds/[project-name]/rtd-builds/
is never created even though builds are passing in status output.

Perhaps you your styles issue is related to this. Will try to find any additional informations.

**Comment by carljm** [comment]
@modulec Thanks for looking into it! To be clear, the styles issue seems to be unrelated (an RTD deployment issue), and is now fixed. The only remaining issue is that builds are claiming to pass but not actually updating the docs.

**Comment by agjohnson** [comment]
@carljm @modulec The missing stylesheet was an unrelated issue to build output not showing up on our web servers. The web syncing queue was backed up, causing built html to not show up on the web servers.

**Comment by ericholscher** [comment]
This was an issue with our doc syncing queues being backed up. I believe it
should be resolved now as well.

On Tue, Jul 21, 2015 at 11:54 AM, Carl Meyer <notifications@github.com>
wrote:

> @modulec <https://github.com/modulec> Thanks for looking into it! To be
> clear, the styles issue seems to be unrelated (an RTD deployment issue),
> and is now fixed. The only remaining issue is that builds are claiming to
> pass but not actually updating the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1464#issuecomment-123441413>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by carljm** [comment]
Just pushed a new commit, and the build did indeed update the markup. But now the styling is gone again, with this error in FF console: 

```
The stylesheet https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
```

It's now using the `cdnmedia` url instead of the `media` url it was using before, but now that URL isn't sending the correct mime type either. It seems styling is now broken on other projects too, e.g. http://django-model-utils.readthedocs.org/en/latest/

**Comment by ericholscher** [comment]
Yea, that was likely a bad CDN cache. I've cleared that cache as well, so
hopefully it should be actually fixed now. We had 1 web server that didn't
get the proper patch applied, which likely caused a few bad CDN cached
files.

On Tue, Jul 21, 2015 at 12:05 PM, Carl Meyer <notifications@github.com>
wrote:

> Just pushed a new commit, and the build did indeed update the markup. But
> now the styling is gone again, with this error in FF console:
>
> The stylesheet https://cdnmedia.readthedocs.org/css/sphinx_rtd_theme.css was not loaded because its MIME type, "application/octet-stream", is not "text/css".
>
> It's now using the cdnmedia url instead of the media url it was using
> before, but now that URL isn't sending the correct mime type either. It
> seems styling is now broken on other projects too, e.g.
> http://django-model-utils.readthedocs.org/en/latest/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1464#issuecomment-123445579>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by carljm** [comment]
Confirmed that everything is working well now!

Much much gratitude to everyone who works on RTD. You all are awesome!
