### ISSUE TITLE
build passes but documentation is not published

### ISSUE THREAD

**Issue by jmcanterafonseca** [rtfd/readthedocs.org#1468]
Hello,

The build in question is: 

https://readthedocs.org/builds/fiware-cloto/3126899/

It passes but 

https://fiware-cloto.readthedocs.org 

displays an NGINX not found page 

However documentation has been generated as .zip in the downloads page 

https://readthedocs.org/projects/fiware-cloto/downloads/

Any help would be appreciated

thanks

**Comment by ericholscher** [comment]
You don't have an index.html file, which is what the HTTP server will
default to serving.

On Tue, Jul 21, 2015 at 3:25 PM, Jose M. Cantera <notifications@github.com>
wrote:

> Hello,
>
> The build in question is:
>
> https://readthedocs.org/builds/fiware-cloto/3126899/
>
> It passes but
>
> https://fiware-cloto.readthedocs.org
>
> displays an NGINX not found page
>
> However documentation has been generated as .zip in the downloads page
>
> https://readthedocs.org/projects/fiware-cloto/downloads/
>
> Any help would be appreciated
>
> thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1468>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by ericholscher** [comment]
Upon further inspection, it looks like we had a README.html as an available
index file. We've added README/index.html, which will support README files
for the dirhtml sphinx backend, which I believe is what was breaking here.

On Tue, Jul 21, 2015 at 3:30 PM, Eric Holscher <eric@ericholscher.com>
wrote:

> You don't have an index.html file, which is what the HTTP server will
> default to serving.
>
> On Tue, Jul 21, 2015 at 3:25 PM, Jose M. Cantera <notifications@github.com
> > wrote:
>
>> Hello,
>>
>> The build in question is:
>>
>> https://readthedocs.org/builds/fiware-cloto/3126899/
>>
>> It passes but
>>
>> https://fiware-cloto.readthedocs.org
>>
>> displays an NGINX not found page
>>
>> However documentation has been generated as .zip in the downloads page
>>
>> https://readthedocs.org/projects/fiware-cloto/downloads/
>>
>> Any help would be appreciated
>>
>> thanks
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rtfd/readthedocs.org/issues/1468>.
>>
>
>
>
> --
> Eric Holscher
> Maker of the internet residing in Portland, Oregon
> http://ericholscher.com
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by jmcanterafonseca** [comment]
@ericholscher many thanks for the prompt response! 

Now the README and the table of contents is being generated perfectly but the links point to nowhere. 

http://fiware-cloto.readthedocs.org/en/develop/

I've been reading the config.py documentation but no idea what could be wrong 

Could you help with that?

thanks

**Comment by ericholscher** [comment]
I'm going to close this, and say that we require an ``index.html`` file to exist, and remove the README setting in our nginx config.
