### ISSUE TITLE
Respond to linting errors and enable CI linting

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1471]
With #1450, we will be getting back to performing linting on contributed code. Because we haven't been linting code for a while, there are a lot of outstanding issues that need to be resolved before we can start using linting as a metric for code quality.

The ultimate goal of this ticket is to ensure that we can run automated linting via Travis, against all applications except `projects/` and `builds/`. Any pull requests that address linting errors should reference this ticket for tracking.

When contributing linting clean up pull requests, keep pull requests reasonably small, don't address multiple applications needlessly. Grouping cleanup efforts across applications like this will more likely create conflicts that will slow down clean up efforts.

Linting will be run from Tox, clean up efforts only need to address the problems in those errors. See http://docs.readthedocs.org/en/latest/tests.html for more information on our test suite.

refs #1424

**Comment by gregmuellegger** [comment]
See #1522

**Comment by gregmuellegger** [comment]
Was fixed with the merge of #1522.
