### ISSUE TITLE
Clean up linting errors in projects

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1472]
Once #1471 has addressed linting errors in lesser applications, clean up the `projects/` path.

refs #1424

**Comment by gregmuellegger** [comment]
See #1522

**Comment by gregmuellegger** [comment]
Was fixed with the merge of #1522

**Comment by agjohnson** [comment]
This doesn't seem to be resolved. We are still ignoring `projects/` path in `prospector.yaml` and I get a lot of failures in that path.

**Comment by gregmuellegger** [comment]
Ohoh, you are right. Sorry for the sloppiness.
