### ISSUE TITLE
Clean up docstrings to PEP257 specs and enable CI linting with pep257

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1474]
Once #1471 addresses initial linting errors, we will continue linting clean up by targetting errors produced by pep257 linting. Similar to #1471, address docstring cleanup efforts in small chunks, which will be easier to merge into other work and will not create broad changes that are difficult to merge. This will encourage the clean up effort to be quick, and will not block other work.

Work addressing clean up efforts can reference this ticket.

Applications that may cause linting errors due to pep257 failures:
- [ ] api
- [ ] betterversion
- [ ] bookmarks
- [ ] builds
- [ ] comments
- [ ] core
- [ ] djangome
- [ ] doc_builder
- [ ] donate
- [ ] gold
- [ ] oauth
- [ ] privacy
- [ ] profiles
- [ ] projects
- [ ] redirects
- [ ] restapi
- [ ] rtd_tests
- [ ] search
- [ ] settings
- [ ] tastyapi
- [ ] templates
- [ ] vcs_support

refs #1424

**Comment by gregmuellegger** [comment]
It's no longer blocked and open for everyone who wants to tackle this.

**Comment by rixx** [comment]
@agjohnson, @gregmuellegger do you have an overview over which parts of this are still open (and maybe update the issue check list)? I see that `core` and `api` have been done in #2245 already.

**Comment by alexwlchan** [comment]
If it weren’t obvious from the flurry of PRs, I’m planning to work on this.

I’ll try not to have too many PRs open at once, so I don’t spam the repo. :-)

**Comment by agjohnson** [comment]
@alexwlchan this is great, thanks for the help cleaning up! i'll keep up with the cleanup efforts so that things don't go stale. So far, things are looking good -- small PRs is a good way to not clobber some of the other work.
