### ISSUE TITLE
Document code style guidelines

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1475]
As discussed in #1424, we will want to decide on and document style guidelines for Python, JavaScript, and CSS. This ticket will be a place we can discuss changes before putting together any pull requests.

**Comment by tBaxter** [comment]
Would Python simply be "Follow PEP-8"?

**Comment by agjohnson** [comment]
No, there is a large variance in how strict projects are with regards to style issues raised by pylint and things like docstring formatting guidelines with pep257.

**Comment by agjohnson** [comment]
We've formalized some of this in the start of autolinting, so I think we can close this. JavaScript will be a different thing, but perhaps same tooling.
