### ISSUE TITLE
Missing "Edit on GitHub" link in markdown-based projects

### ISSUE THREAD

**Issue by tormi** [rtfd/readthedocs.org#1478]
"Edit on GitHub" link is missing in markdown-based docs, see http://infohaldus.readthedocs.org/et/latest/ for example ([source](https://github.com/kinnisvara/infohaldus/)).

**Comment by d0ugal** [comment]
This needs to be added in MkDocs itself. https://github.com/mkdocs/mkdocs/issues/269

**Comment by tormi** [comment]
Thanks.
