### ISSUE TITLE
Documentation version selection broken with Mkdocs

### ISSUE THREAD

**Issue by shravantc** [rtfd/readthedocs.org#1480]
If we switch versions from the options to release-3.7.0-1 on http://gluster.readthedocs.org/en/latest/
the resultant URL gets appended with "None" as in http://gluster.readthedocs.org/en/release-3.7.0-1/None/

also from any page, we cannot view the different versions of the documents, what I observed is the URL fired is mis matching the directory.

![image](https://cloud.githubusercontent.com/assets/10970993/8822127/d4c729ac-3080-11e5-9b3c-bbd2d1c36148.png)

**Comment by d0ugal** [comment]
For some reason it is adding a None to the end of the url. I am not sure why. I guess there is an issue getting the current path?

**Comment by d0ugal** [comment]
Yeah, so this line isn't working for some reason: https://github.com/mkdocs/mkdocs/blob/master/mkdocs/themes/readthedocs/base.html#L29

**Comment by d0ugal** [comment]
and actually, page title isn't the right thing to put there. We should be putting the URL. You can see it being used incorrectly when you change the version here: http://gluster.readthedocs.org/en/latest/Quick-Start-Guide/Terminologies/

**Comment by jhamman** [comment]
I'm getting the same behavior on this site: http://vic.readthedocs.org/en/master/.

All the links under `Versions` and `On GitHub` send you to a url with the word "None" at the end.

**Comment by gregmuellegger** [comment]
@d0ugal I tried using https://github.com/mkdocs/mkdocs/commit/74031a084d776f45ad43568e334da2b89133986b of mkdocs, but it still appended `None` on the version select links. Is there anything that we need to adjust on the RTD end?

**Comment by d0ugal** [comment]
@gregmuellegger Yeah, I think so. I just made the data available, I don't really know how it works on your end, but it looked like you were using the Title incorrectly as the URL so I added that.

**Comment by d0ugal** [comment]
I was planning to come and figure it out, but hadn't found the time yet :)

**Comment by gregmuellegger** [comment]
I tried to install the mkdocs master in the venv that is used for the rtd build, but the change didn't pick up. The base.html in the filesystem contains the change ... but the build doesn't seem to use it.

@d0ugal could there be any other path in RTD that is loading the mkdocs theme templates from except from the mkdocs package in the venv?

**Comment by jhamman** [comment]
@d0ugal and @gregmuellegger - 

Can either of you give us an update on where this issue is at? We have live docs on RTD that are not working because of this bug.  If there is something I can do to help move this forward, let me know.

**Comment by gregmuellegger** [comment]
I further worked on a fix and finally came up with a robust solution. However for this to work mkdocs needs to merge mkdocs/mkdocs#721 first AND make a new release afterwards. Then we can merge #1634 and finally fix this issue.

@d0ugal could you make this happen soonish? That would be :trophy:

**Comment by gregmuellegger** [comment]
Blocked by mkdocs/mkdocs#721
Blocked by #1634

**Comment by jhamman** [comment]
Just giving this a bump since it seems like the fixes are not blocked anymore.

**Comment by d0ugal** [comment]
It is still blocked (mostly by me), MkDocs needs a release. I am super swamped until the end of the month and don't want to do a release I won't be able to support.

**Comment by dnrce** [comment]
MkDocs 0.15.0 was released today. Is this now unblocked?
