### ISSUE TITLE
svg files trigger 404 if external domain is used (CNAME)

### ISSUE THREAD

**Issue by deyhle** [rtfd/readthedocs.org#1481]
I have a svg image in my docs, which works fine on readthedocs directly:

http://entrecode.readthedocs.org/en/latest/img/statediagram.svg

However, using a CNAME redirection, the request fails and triggers a 404:

http://rtdtest.entrecode.de/en/latest/img/statediagram.svg

The DNS entry is correct:

```
rtdtest.entrecode.de	canonical name = entrecode.readthedocs.org.
Name:	entrecode.readthedocs.org
Address: 162.209.114.75
```

So it is probably an issue with the server configuration at readthedocs.org.

**Comment by ericholscher** [comment]
This was fixed with a PR a few weeks ago.
