### ISSUE TITLE
Edit on GitHub link is broken for Markdown files in Sphinx projects

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1483]
Here is an example: http://docs.readthedocs.org/en/latest/changelog.html

The changelog source is in `changelog.md` but the link goes to `https://github.com/rtfd/readthedocs.org/blob/master/docs/changelog.rst`.

**Comment by ericholscher** [comment]
This is a Sphinx bug. I pushed a patch into Sphinx that fixes it, and gives us the proper source_suffix in the template context, we just need to make sure we are respecting it. 

https://github.com/sphinx-doc/sphinx/pull/1876

**Comment by gregmuellegger** [comment]
I reviewed the code and I think we are passing `source_suffix` through from the build to the API to the function that builds the github URL. So we should be good, but we now need to wait for a new Sphinx release :(

**Comment by gregmuellegger** [comment]
Blocked by next Sphinx release ">1.3.1"

**Comment by ericholscher** [comment]
This is fixed in the code base & waiting on a Sphinx release: https://github.com/sphinx-doc/sphinx/issues/2278

**Comment by aidz92** [comment]
i don't think this is fixed, I still get relocated to the .rst version of the file and the OP's issue has not been resolved as per the example [link](http://docs.readthedocs.org/en/latest/changelog.html)
