### ISSUE TITLE
Search is not working 

### ISSUE THREAD

**Issue by jmcanterafonseca** [rtfd/readthedocs.org#1487]
hello,

If I try to search for something under my project http://fiware-orion.readthedocs.org nothing is found regardless the word I enter. Should I do anything to enable search for my project?

thanks

**Comment by gregmuellegger** [comment]
I think the search should work out of the box. So it's not your fault :) We need to investigate this.

**Comment by jmcanterafonseca** [comment]
hello guys,

Any idea on how to fix this?

thanks!

2015-07-27 10:02 GMT+02:00 Gregor Müllegger <notifications@github.com>:

**Comment by gregmuellegger** [comment]
@ericholscher @agjohnson any ideas?

**Comment by jmcanterafonseca** [comment]
hello guys, @ericholscher @gregmuellegger @agjohnson 

any idea or recommendation on how to solve the issue? 

thanks!

**Comment by ericholscher** [comment]
Believe this is a bug with our mkdocs integration. It seems the json builder is breaking when using the theme option. We should have a patch for it soon.

**Comment by deejay1** [comment]
Don't know if it's related but when I try to build an mkdocs site on my installation of rtd (commit f54d78b372845e9236377cbe38a9a401b84d34d7) I get:

```
[13/Aug/2015 13:20:04] DEBUG [readthedocs.search.utils:134] (Search Index) Parsing sections for /data/rtd/media/json/rtfd-tests/latest/tst/foo/index.json
[13/Aug/2015 13:20:04] ERROR [celery.worker.job:282] Task readthedocs.projects.tasks.update_search[0ab34218-5daf-4fd3-a4c7-d4b5c6bdefbf] raised unexpected: KeyError('url',)
Traceback (most recent call last):
  File "/srv/rtd_app/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/srv/rtd_app/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/rtd_app/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 595, in update_search
    page_list = process_mkdocs_json(version, build_dir=False)
  File "/srv/rtd_app/checkouts/readthedocs.org/readthedocs/search/utils.py", line 28, in process_mkdocs_json
    relative_path = parse_path_from_file(documentation_type='mkdocs', file_path=filename)
  File "/srv/rtd_app/checkouts/readthedocs.org/readthedocs/search/utils.py", line 62, in parse_path_from_file
    path = page_json['url']
KeyError: 'url'
```

Sample repo is here https://github.com/deejay1/rtfd_test

**Comment by jmcanterafonseca** [comment]
hello,

is there any news about this issue? or any way we can contribute to get it fixed?

thanks

**Comment by wzrdtales** [comment]
I'm also waiting for this...

**Comment by deejay1** [comment]
What's the current branch I could test and/or deploy from?

**Comment by justonestep** [comment]
Any news about this? Got the same issue.

**Comment by agjohnson** [comment]
No news on this, we haven't focused on the mkdocs integration recently. Anyone willing to look into this is free to take this on.

**Comment by ghostoy** [comment]
Any updates recently? Search is extremely important for our doc.

**Comment by sahilTakiar** [comment]
Would love to see this fixed too

**Comment by carukc** [comment]
We are seeing this problem and the popup menu at the bottom left is missing when building mkdocs... perhaps related.  If anyone is working on this perhaps we can assist?  We do not know much about the code yet but learn quickly ;)

**Comment by weitzman** [comment]
Possible workaround in #1088

**Comment by nitinsurana** [comment]
Search is still not working :(  http://solarium.readthedocs.io/en/latest/

**Comment by fosskers** [comment]
Search "works", but it doesn't track changes in our `latest` branch. It always gives results with a URL structure we used a lot time ago. 

See https://github.com/locationtech/geotrellis/issues/1967.

**Comment by ccharles** [comment]
I'm surprised to discover how long this bug has been active. Has search on readthedocs.io truly been broken for over 18 months (and counting)? I am seeing the problem on https://projectile.readthedocs.io/.

What is preventing this from being resolved, and how can I help fix it?

**Comment by fosskers** [comment]
The solution for us was to port all our docs to RST.

**Comment by Daniel085** [comment]
Guys, I am still having this issue: http://voicebase.readthedocs.io/en/v2-beta/search.html?q=hello&check_keywords=yes&area=default Is there a solution other than converting all our documentation prior to using readthedocs?

**Comment by fosskers** [comment]
@Daniel085 Using pandoc (linked above), the conversion process is at most an afternoon's worth of work.

**Comment by Daniel085** [comment]
@fosskers I understand the workaround, but markdown is a supported feature: http://docs.readthedocs.io/en/latest/getting_started.html?highlight=markdown

Not being able to click search results containing any markdown documents seems like a serious bug.

**Comment by Screwtapello** [comment]
Reading through the various links to other issues, so far as I can tell, this is what's going on:

- Sphinx and mkdocs both support "client-side" searching, where and index of terms is generated at build-time, stored as JSON, and the search functionality is JS that runs inside the user's browser, downloads the JSON blob and renders the results.
- mkdocs also supports rendering the generated index in a standard format that can be indexed server-side (at least, judging by #1088), which can be faster since the client doesn't have to download a whole index every time.
- when RTFD builds docs in mkdocs format, it [injects JavaScript](https://github.com/rtfd/readthedocs.org/blob/499a74076f0debae09acc1d4c4eeeab03f8f557e/readthedocs/core/static-src/core/js/doc-embed/mkdocs.js) that modifies the search field to submit requests to https://readthedocs.org/search/ instead of using the client-side searching.
- Unfortunately, server-side searching doesn't seem to actually be set up or working in any way.
- As a user of RTFD, you can work around this problem by [injecting your own JavaScript](https://github.com/nodemcu/nodemcu-firmware/commit/7dd89dd15ef993c9740ba4d4361e6be8edd1284b) that points the search field back to client-side searching.

I'm not sure why RTFD rewrites the search field for mkdocs documentation. After all, Sphinx-based documentation still uses client-side searching.

**Comment by abaumann** [comment]
With the exception of actually hosting docs I'd say search is one of the most important aspects of a documentation site, so +100 for fixing this, but thanks so much for that workaround!

**Comment by stsewd** [comment]
All projects listed here have a working search, is this still an issue for anyone?

**Comment by Daniel085** [comment]
This seems to be resolved fo us at least!

**Comment by ericholscher** [comment]
👍

**Comment by senesis** [comment]
Search is not working for https://climaf.readthedocs.io/en/latest/index.html 
Do I need to hack as described above ?

**Comment by ericholscher** [comment]
@senesis It looks like you have a really old version of jQuery in your built docs. I believe this is causing the issue.

**Comment by ericholscher** [comment]
Yea, you're running your doc builds with `Sphinx v1.2.3`, which I'm guessing is the issue.

**Comment by ericholscher** [comment]
I'll also see if we can make our search code work with older jquery, which should hopefully fix it.

**Comment by ericholscher** [comment]
Looks like we broke our fallback in our latest search code. https://github.com/rtfd/readthedocs.org/pull/5285 will fix it.

**Comment by senesis** [comment]
Thanks ! I will also consider upgrading the Sphinx version I use
