### ISSUE TITLE
Links to the individual subdocuments in the TOC are not working

### ISSUE THREAD

**Issue by jmcanterafonseca** [rtfd/readthedocs.org#1488]
hello,

In this project http://fiware-cloto.readthedocs.org/en/develop/ linked to 
https://github.com/jmcanterafonseca/fiware-cloto none of the links in the TOC are working. Any idea?

Thanks in advance

**Comment by gregmuellegger** [comment]
Hm, the branch name is not included in the link URL ... So the doc is linking to
http://fiware-cloto.readthedocs.org/en/doc/admin_guide/ instead of
http://fiware-cloto.readthedocs.org/en/develop/doc/admin_guide/

We need to investigate here.

**Comment by gregmuellegger** [comment]
When beeing on a deep link, then the TOC is working. https://fiware-cloto.readthedocs.org/en/develop/doc/architecture/

I think the issue could be related to the Sphinx-HTMLDir Builder. The README.rst that lives in the top-level of the project will be served when accessing `/en/develop` but it's actual path in the filesystem is `README/index.html`. So it links one directory up to get the actual doc pages, e.g. `../doc/architecture/`.

@ericholscher Any ideas on this?

@jmcanterafonseca A quickfix for this might be to not use the HTMLDir builder for now. I know that's not ideal but I'm not sure when we get around to fix the issue.
An alternative fix could be to have a `index.rst` besides the `README.rst` which includes the readme `.. include:: README.rst`, but I'm not 100% sure that this will solve the problem. Might be worth a try anyways.

**Comment by ericholscher** [comment]
Ah, that was me trying to be clever, but I can remove the README/index.html
as an 'index page' in nginx.

On Mon, Jul 27, 2015 at 1:35 AM, Gregor Müllegger <notifications@github.com>
wrote:

> When beeing on a deep link, then the TOC is working.
> https://fiware-cloto.readthedocs.org/en/develop/doc/architecture/
>
> I think the issue could be related to the Sphinx-HTMLDir Builder. The
> README.rst that lives in the top-level of the project will be served when
> accessing /en/develop but it's actual path in the filesystem is
> README/index.html. So it links one directory up to get the actual doc
> pages, e.g. ../doc/architecture/.
>
> @ericholscher <https://github.com/ericholscher> Any ideas on this?
>
> @jmcanterafonseca <https://github.com/jmcanterafonseca> A quickfix for
> this might be to not use the HTMLDir builder for now. I know that's not
> ideal but I'm not sure when we get around to fix the issue.
> An alternative fix could be to have a index.rst besides the README.rst
> which includes the readme .. include:: README.rst, but I'm not 100% sure
> that this will solve the problem. Might be worth a try anyways.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1488#issuecomment-125126894>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by jmcanterafonseca** [comment]
@ericholscher with the index.rst addition (including README.rst) now it
worked!

thanks!

2015-07-27 18:45 GMT+02:00 Eric Holscher <notifications@github.com>:

**Comment by gregmuellegger** [comment]
@jmcanterafonseca cool! glad to hear :)
@ericholscher what action do we need to take to fix that?

**Comment by ericholscher** [comment]
Closing this, as I have removed the README/index.rst hack -- it isn't a good way to move forward, and you should just serve a root-level index.html file.
