### ISSUE TITLE
Can not upgrade Ipython version

### ISSUE THREAD

**Issue by paugier** [rtfd/readthedocs.org#1489]
Hello,

I try to use readthedocs for a documentation (http://fluidlab.readthedocs.org/en/latest/) which contains some ipython notebooks which need to be converted to rst. With Ipython 1.2.1, the notebooks can not be converted and I got the error:

    NBFormatError: Unsupported JSON nbformat version 4 (supported version: 3)
 
I would have to upgrade to a more recent version of Ipython but I do not see how to do it. I even tried to activate the environment and to run:

    pip install --upgrade --no-deps --ignore-installed ipython[notebook]

but it does not work and gives

    Collecting ipython[notebook]
      Using cached ipython-3.2.1-py2-none-any.whl
    Installing collected packages: ipython
    Successfully installed ipython-1.2.1

I do not really understand this but it seems to be a bug with pip, virtualenv and ipython.

The very simple and clean solution would just be to have a recent version of Ipython in the base Python of readthedocs. Would it be possible ?

Another solution is to just remove this old Ipython from the base Python of readthedocs. Then it would not be a problem to install any versions of Ipython in the virtualenv of the projects.

**Comment by gregmuellegger** [comment]
Hi, could you give us an idea about what the project is called on RTD you have troubles with? Cheers :)
:balloon:

**Comment by paugier** [comment]
Yes, I'm trying RTD with this project:

http://fluidlab.readthedocs.org/en/latest/

**Comment by gregmuellegger** [comment]
Seems like we have `ipython` installed on the servers, but it shouldn't interfere with the builds ... I cannot find any reference to `ipython` in the readthedocs.org code base.

@paugier I don't know the `ipython[notebook]` notation. Is there something special about the brackets? I cannot find a reference on what this does at first try. Could you quickly describe it?

**Comment by paugier** [comment]
Yes python 1.2.1 is installed on the servers. And if a project use a virtualenv with the option "Give the virtual environment access to the global site-packages dir." (for example to get numpy, scipy, matplotlib...), it does not seem possible to upgrade Ipython to a more recent version in the virtualenv.

So the issue is really about the version of Ipython installed on the servers and the fact that it seems difficult (impossible?) to upgrade ipython with a virtualenv made with the option --system-site-packages.

The notation with brackets `ipython[notebook]` or  `ipython[all]` is not very common but is used by Ipython to precise which Ipython dependencies should be installed. See  https://ipython.org/ipython-doc/3/install/install.html#dependencies-for-the-ipython-html-notebook. I do not think it is related to the problem.

**Comment by paugier** [comment]
To be clear, `ipython nbconvert` is called in the file conf.py of the project and not in the readthedocs.org code base.

I know it is not common to do this but it seems to me that using Ipython notebooks converted to rst during the build is quite convenient.

**Comment by paugier** [comment]
Why this issue is still tagged "Needed: more information" ? Which information should I give ?

**Comment by hannorein** [comment]
I just saw this issue (I filed a similar one an hour ago). I also want to use `ipython nbconvert` to convert my ipython examples to rst and then include them in the documentation. I can't seem to figure out how to do this on the build servers.

**Comment by gregmuellegger** [comment]
@paugier could you provide us with a link to the project you are having problems with?

**Comment by gregmuellegger** [comment]
Related: #1498

**Comment by hannorein** [comment]
Thank you! Very much appreciated!

**Comment by gregmuellegger** [comment]
Related: #1511

**Comment by hannorein** [comment]
Now might be a good time for the update:

http://blog.jupyter.org/2015/08/12/first-release-of-jupyter/

**Comment by ericholscher** [comment]
I have upgraded the ipython install to 4.0, and as @gregmuellegger mentioned in #1511, you can install it in your own requirements file if needed.

**Comment by hannorein** [comment]
Thanks a lot! Everything works now!
