### ISSUE TITLE
modernizr is being requested relative to the page, not the site

### ISSUE THREAD

**Issue by slaneyrw** [rtfd/readthedocs.org#1497]
I have noticed this on my local sphinx build, but also on some RTD hosted ( ie docs.asp.net ).

The layout.html page has a link...

    <script src="_static/js/modernizr.min.js"></script>

This link is relative to the current page, so if you are creating folders in your documentation then the path to the modernizr file will move as well.

Example:

http://docs.asp.net/en/latest/getting-started/installing-on-windows.html
404: http://docs.asp.net/en/latest/getting-started/_static/js/modernizr.min.js

Is there a config setting that we can use to make this link absolute ?

**Comment by slaneyrw** [comment]
I changed my local sphinx template to use

    <script src="{{ pathto('_static/js/modernizr.min.js', 1) }}"></script>

It appears to work in my *limited* testing.

**Comment by gregmuellegger** [comment]
Seems valid and is already fixed in the sphinx_rtd_theme repository. We should update the theme in RTD to fix this issue. I've created #1500 for this.

**Comment by gregmuellegger** [comment]
That's fixed an will be live with the next deploy
