### ISSUE TITLE
Use sphinx_rtd_theme directly instead of vendoring it

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1501]
Are there any reasons why the sphinx rtd theme is copied into the RTD code base instead of referenced as dependency?

There were bugs like #1497 that would not have been raised if the theme would have been up to date.

**Comment by ericholscher** [comment]
ha, read my mind :)

**Comment by agjohnson** [comment]
I have a refactor that i'd like in v0.1.9 of the theme which will allow us to use it as a bower dependency

**Comment by gregmuellegger** [comment]
@agjohnson Whats the planned ETA for this? Why not integrating as a python dependency?

**Comment by agjohnson** [comment]
Our two options here:

* Bring it in as a python dependency and import the global declaration in our bundled javascript for built docs.
* Treat it as a javascript dependency as part of the bundling process and bundle the theme javascript into our bundles

I still lean towards the latter, as it's more consistent with how we treat the rest of our javascript dependencies. It's one less spurious script include as well, as it would be bundled in, if that's important. I think the only argument for the python package method is that we're already installing the theme on RTD. This should change though, as I can't think of any reason why the theme should exist outside version virtualenvs.

I'm going to try for this week, it's at the top of my list. I had to bump it from my list last week as my focus wasn't on rtd.org.

**Comment by agjohnson** [comment]
PR for this is #1645
