### ISSUE TITLE
Track modified date of all files

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1505]
This refs the work in #1390 -- we are slowly learning more about each of the files that we're hosting, so we should be tracking the modified date as well.

This will allow interesting features, like "freshness" UI around each page or section.

**Comment by agjohnson** [comment]
Marking this low priority for now, until we have a feature to show freshness. Without this piece, tracking modified date doesn't add much value.

**Comment by ericholscher** [comment]
This is actually implemented in the new search code for search invalidation. So I'm gonna close this one as done. 👍
