### ISSUE TITLE
./manage.py migrate

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1508]
Just noticed that "./manage.py migrate" no longer works.

In https://docs.readthedocs.org/en/latest/install.html, the instructions state to;

    cd readthedocs
    ./manage.py migrate

However "manage.py" is in the "readthedocs.org" folder, not the "readthedocs.org/readthedocs" folder.

And running "./manage.py migrate" in "readthedocs.org" returns the following;

```
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/core/management/__init__.py", line 312, in execute
    django.setup()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/opt/rh/python27/root/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/tastypie/models.py", line 32, in <module>
    from tastypie.compat import AUTH_USER_MODEL
  File "/users/lcrook/rtd/lib/python2.7/site-packages/tastypie/compat.py", line 14, in <module>
    User = get_user_model()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 150, in get_user_model
    return django_apps.get_model(settings.AUTH_USER_MODEL)
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/apps/registry.py", line 199, in get_model
    self.check_models_ready()
  File "/users/lcrook/rtd/lib/python2.7/site-packages/django/apps/registry.py", line 131, in check_models_ready
    raise AppRegistryNotReady("Models aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Models aren't loaded yet.
```

**Comment by destroyerofbuilds** [comment]
I'm encountering the same issue while upgrading to 1075845fc69191cc19a26beb30a84fdfaff8a20e from the previous master branch commit.

I attempted to run the steps listed under _Deployment Note_ from pull request #1420 

I'm still looking into this issue.

**Comment by gregmuellegger** [comment]
Can you please try to remove all the `.pyc` files and `__pycache__` directories if there are any. I usually use this command:
`find . -name \*.pyc -delete ; find . -name __pycache__ -delete`

We had a bigger restructure merged into master which touched nearly every python file. So if the cached ones are stale, you might end up in that situation.

**Comment by destroyerofbuilds** [comment]
In a clean checkout of my copy of readthedocs at the 1.8 migration, I ran the following:

```bash
pip install -U -r requirements/deploy.txt
```

```bash
~ $ python readthedocs/manage.py migrate contenttypes
ReadTheDocs: WARNING [py.warnings:9] /app/.setup/python/lib/python2.7/site-packages/haystack/utils/__init__.py:11: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils import importlib

ReadTheDocs: WARNING [py.warnings:10] /app/.setup/python/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
  from django.contrib.contenttypes import generic

ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:5: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  ProjectManager = import_by_path(getattr(settings, 'PROJECT_MANAGER', 'privacy.backend.ProjectManager'))

ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:6: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  VersionManager = import_by_path(getattr(settings, 'VERSION_MANAGER', 'privacy.backend.VersionManager'))

ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:7: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  RelatedProjectManager = import_by_path(getattr(settings, 'RELATED_PROJECT_MANAGER', 'privacy.backend.RelatedProjectManager'))

ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:10: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  AdminPermission = import_by_path(getattr(settings, 'ADMIN_PERMISSION', 'privacy.backend.AdminPermission'))

ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:13: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
  Syncer = import_by_path(getattr(settings, 'FILE_SYNCER', 'privacy.backends.syncers.LocalSyncer'))

System check identified some issues:

WARNINGS:
gold.GoldUser.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
ReadTheDocs: WARNING [py.warnings:8] /app/.setup/python/lib/python2.7/site-packages/south/db/postgresql_psycopg2.py:4: RemovedInDjango19Warning: The django.db.backends.util module has been renamed. Use django.db.backends.utils instead.
  from django.db.backends.util import truncate_name

There is no South database module 'south.db.postgresql_psycopg2' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.
```

I'm not sure what the reference is to `South`.

Also, even after executing the other two migration steps, the actual application still crashes for the same reason.

**Comment by ericholscher** [comment]
You have to uninstall south.

On Mon, Aug 3, 2015 at 11:51 AM, Hutson Betts <notifications@github.com>
wrote:

> In a clean checkout of my copy of readthedocs at the 1.8 migration, I ran
> the following:
>
> pip install -U -r requirements/deploy.txt
>
> ~ $ python readthedocs/manage.py migrate contenttypes
> ReadTheDocs: WARNING [py.warnings:9] /app/.setup/python/lib/python2.7/site-packages/haystack/utils/__init__.py:11: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
>   from django.utils import importlib
>
> ReadTheDocs: WARNING [py.warnings:10] /app/.setup/python/lib/python2.7/site-packages/south/modelsinspector.py:20: RemovedInDjango19Warning: django.contrib.contenttypes.generic is deprecated and will be removed in Django 1.9. Its contents have been moved to the fields, forms, and admin submodules of django.contrib.contenttypes.
>   from django.contrib.contenttypes import generic
>
> ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:5: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
>   ProjectManager = import_by_path(getattr(settings, 'PROJECT_MANAGER', 'privacy.backend.ProjectManager'))
>
> ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:6: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
>   VersionManager = import_by_path(getattr(settings, 'VERSION_MANAGER', 'privacy.backend.VersionManager'))
>
> ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:7: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
>   RelatedProjectManager = import_by_path(getattr(settings, 'RELATED_PROJECT_MANAGER', 'privacy.backend.RelatedProjectManager'))
>
> ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:10: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
>   AdminPermission = import_by_path(getattr(settings, 'ADMIN_PERMISSION', 'privacy.backend.AdminPermission'))
>
> ReadTheDocs: WARNING [py.warnings:43] /app/readthedocs/privacy/loader.py:13: RemovedInDjango19Warning: import_by_path() has been deprecated. Use import_string() instead.
>   Syncer = import_by_path(getattr(settings, 'FILE_SYNCER', 'privacy.backends.syncers.LocalSyncer'))
>
> System check identified some issues:
>
> WARNINGS:
> gold.GoldUser.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
>         HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
> ReadTheDocs: WARNING [py.warnings:8] /app/.setup/python/lib/python2.7/site-packages/south/db/postgresql_psycopg2.py:4: RemovedInDjango19Warning: The django.db.backends.util module has been renamed. Use django.db.backends.utils instead.
>   from django.db.backends.util import truncate_name
>
> There is no South database module 'south.db.postgresql_psycopg2' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.
>
> I'm not sure what the reference is to South.
>
> Also, even after executing the other two migration steps, the actual
> application still crashes for the same reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1508#issuecomment-127368723>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by destroyerofbuilds** [comment]
@ericholscher this seems to have been an issue with deploying readthedocs using the Heroku Python buildpack (which was installing over an existing virtual environment, thereby, leaving South around).

I managed to wipe the Heroku cache, and run through the installation mostly successfully.

While running `python readthedocs/manage.py migrate contenttypes` and I got `django.db.utils.ProgrammingError: relation "django_content_type" already exists`.

However, despite that, I was able to successfully start readthedocs up after the migration.

**Comment by gregmuellegger** [comment]
@destroyerofbuilds Were you able to apply the migrations somehow? Maybe try: `python manage.py migrate contenttypes --fake-initial`

**Comment by destroyerofbuilds** [comment]
@gregmuellegger so, though it seemed like I applied the migrations correctly, despite that error, I decided to pursue the issue a little further.

Eventually I came to the same conclusion as you, about using `--fake-initial`, for the `contenttypes` migration.

Using the following steps I'm able to apply the migrations without any errors or warnings:

* `python readthedocs/manage.py migrate contenttypes --fake-initial`
* `python readthedocs/manage.py migrate projects 0002 --fake`
* `python readthedocs/manage.py migrate --fake-initial`

**Comment by gregmuellegger** [comment]
@destroyerofbuilds Thanks for the investigation. I've updated the deployment notes in #1420 
Closing this as it seems that we solved all the problems.

**Comment by Balooga** [comment]
FYI; https://docs.readthedocs.org/en/latest/install.html states to run "./manage.py migrate" from the "readthedocs" directory.  But this should be run from within "readthedocs.org".

**Comment by gregmuellegger** [comment]
@Balooga Thanks! I created #1566 for this.
