### ISSUE TITLE
Bug in core.views.queue_info, is it used anymore?

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1515]
The code in `core.views.queue_info` contains this:

```python
            for obj in reserved['build']:
                kwrags = eval(obj['kwargs'])
                reserved_pks.append(str(kwargs['pk']))
```
So it has a typo in `kwrags`. That means the third line of the example won't pick up the correct variable. It might still succeed without a `NameError` as it might be already initialized by another for loop above in the same function.

See https://github.com/rtfd/readthedocs.org/blob/291d7d61e626c1dfb998d9e5d4e5b734a44a7024/readthedocs/core/views.py#L102

I didn't fix it straight away as it seems that the `queue_info` URL is not used anywhere in the project? Do we still have a use for it?
```
$ grep -r queue_info .
./readthedocs/core/views.py:def queue_info(request):
./readthedocs/urls.py:    url(r'^queue_info/$', 'readthedocs.core.views.queue_info', name='queue_info'),
```

**Comment by ericholscher** [comment]
It was mainly used for debugging celery, but we now have real monitoring
for it, so it can likely be deleted.

On Fri, Jul 31, 2015 at 4:26 AM, Gregor Müllegger <notifications@github.com>
wrote:

> The code in core.views.queue_info contains this:
>
>             for obj in reserved['build']:
>                 kwrags = eval(obj['kwargs'])
>                 reserved_pks.append(str(kwargs['pk']))
>
> So it has a typo in kwrags. That means the third line of the example
> won't pick up the correct variable. It might still succeed without a
> NameError as it might be already initialized by another for loop above in
> the same function.
>
> See
> https://github.com/rtfd/readthedocs.org/blob/291d7d61e626c1dfb998d9e5d4e5b734a44a7024/readthedocs/core/views.py#L102
>
> I didn't fix it straight away as it seems that the queue_info URL is not
> used anywhere in the project? Do we still have a use for it?
>
> $ grep -r queue_info .
> ./readthedocs/core/views.py:def queue_info(request):
> ./readthedocs/urls.py:    url(r'^queue_info/$', 'readthedocs.core.views.queue_info', name='queue_info'),
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1515>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com
