### ISSUE TITLE
Build process missing layout.html

### ISSUE THREAD

**Issue by miohtama** [rtfd/readthedocs.org#152]
Plone's developer documentation is using a custom layout.html template with Sphinx 1.1.2. This adds some documentation specific links to the source code. For some reason these changes are not picked up

* Footer block has some injected HTML

* Head block has some injected <script> Javascript

How "native" Sphinx build HTML looks like:

http://opensourcehacker.com/wp-content/uploads/docs/

How readthedocs.org HTML looks like:

 http://collective-docs.readthedocs.org/en/latest/index.html

I am still new to readthedocs.org - is there something special that needs to be done for custom layout.html or is it supported at all? (XSS injections and stuff)

**Comment by gregmuellegger** [comment]
@ericholscher What's the current status of this?

**Comment by ericholscher** [comment]
It's still an issue, where we use it for our customizations.

On Tue, Jul 21, 2015 at 4:43 AM, Gregor Müllegger <notifications@github.com>
wrote:

> @ericholscher <https://github.com/ericholscher> What's the current status
> of this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/152#issuecomment-123278037>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by kennethreitz** [comment]
This has been driving me crazy all month. Relieved to find this page and find our I'm not doing anything wrong. 

An easy solution is give a project the option to disable RTD's html meddling for a given project.

**Comment by agjohnson** [comment]
We are working to remove some of this with our sphinx extension, namely #1946 and rtfd/readthedocs-sphinx-ext#13

**Comment by kennethreitz** [comment]
I almost moved my docs off RTD, but was able to workaround this limitation by adding my custom css/js as a sidebar on all pages.

**Comment by agjohnson** [comment]
@kennethreitz if you just need to add custom javascript/css, another method is to include files via the Sphinx application API in your `conf.py`:

```python
def setup(app):
    app.add_javascript('foo.js')
    app.add_stylesheet('foo.css')
```

More:
http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_javascript

Soon we shouldn't need a `layout.html` override however.

**Comment by kennethreitz** [comment]
@agjohnson ah, fantastic. Thanks! :)

**Comment by agjohnson** [comment]
Good news everyone!

We have just merged and deployed changes to RTD and our Sphinx extension that move RTD specific overrides into our Sphinx extension, without the need to override `layout.html` anymore. We're instead monkey patching the template rendering, injected our necessary changes there.

This might cause some different breakage, but we will deal with those changes as they come up. Feel free to open any new issues that might stem from this tomfoolery.

**Comment by macrocosme** [comment]
This may not be exactly the fix requested, but by overriding the ``sidebartitle`` block from rtd ``layout.html``, I managed to change the link to something other than the ``master_doc``. 

So, in my own ``_layout/layout.html``, I override it with the following: 

```
{% block sidebartitle %}

      {% if logo and theme_logo_only %}
        <!-- a href="{{ pathto(master_doc) }}" -->
        <a href="http://www.home.org/">
      {% else %}
        <a href="http://www.home.org/" class="icon icon-home"> {{ project }}
      {% endif %}

      {% if logo %}
        {# Not strictly valid HTML, but it's the only way to display/scale it properly, without weird scripting or heaps of work #}
        <img src="{{ pathto('_static/' + logo, 1) }}" class="logo" />
      {% endif %}
      </a>

      {% if theme_display_version %}
        {%- set nav_version = version %}
        {% if READTHEDOCS and current_version %}
          {%- set nav_version = current_version %}
        {% endif %}
        {% if nav_version %}
          <div class="version">
            {{ nav_version }}
          </div>
        {% endif %}
      {% endif %}

      {% include "searchbox.html" %}

{% endblock %}
```
