### ISSUE TITLE
Social Network Login Failure

### ISSUE THREAD

**Issue by kermit666** [rtfd/readthedocs.org#1520]
When clicking on connect GitHub on the [social accounts page](https://readthedocs.org/accounts/social/connections/?) I get a message:

> An error occurred while attempting to login via your social network account.

There's a `?` in the url. Could that be a hint? Is it missing some request arguments? If I omit it, the bug persists.

Cheers!

**Comment by aventurella** [comment]
I am having the same issue.

**Comment by kermit666** [comment]
As a workaround, I managed to manually import a GitHub repository by entering the repo url and adding Read The Docs as a service to notify of new commits in the repo's settings on GitHub. Explained [here](https://read-the-docs.readthedocs.org/en/latest/webhooks.html).

**Comment by aventurella** [comment]
This is the Error in the URL:
```
The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application
```

**Comment by aventurella** [comment]
More info.. It looks like it has to do with how `allauth`  is doing it's job:

https://github.com/pennersr/django-allauth/blob/8efc7e5ebb3326d467248de3350853407e3fc73b/allauth/account/app_settings.py#L42-L44

```python
@property
    def DEFAULT_HTTP_PROTOCOL(self):
        return self._setting("DEFAULT_HTTP_PROTOCOL", "http")
```

where `self._setting` is:

```python
def _setting(self, name, dflt):
        from django.conf import settings
        getter = getattr(settings,
                         'ALLAUTH_SETTING_GETTER',
                         lambda name, dflt: getattr(settings, name, dflt))
        return getter(self.prefix + name, dflt)
```

So my guess now is all the production app at `https://readthedocs.org` has to do to fix this issue is to set `DEFAULT_HTTP_PROTOCOL` in the django app's settings.

**Comment by gregmuellegger** [comment]
I was able to reproduce it locally with the `django-sslserver` and a custom GitHub app. #1530 should be fixing it.

**Comment by kermit666** [comment]
That was fast. Thanks, folks!
