### ISSUE TITLE
Removing project that to not exist on github

### ISSUE THREAD

**Issue by urosjarc** [rtfd/readthedocs.org#1538]
Hy I want to ask if there is possibility to remove/rename project that do not exist on github.
The case is that i want for my project to have the same name as this project... https://readthedocs.org/projects/mylinux/ but this project do not exist at all...

I tried to contact the owner but no luck...

So is there a possibility to rename/delete old project(s) that do not exist on github or any other hosted site?

**Comment by gregmuellegger** [comment]
We ofcourse cannot auto-remove any projects that lack a github repository. However as for this specific case I agree that we might be able to remove the repository as the GIT repo went away and the project has zero successful builds:

https://readthedocs.org/builds/mylinux/

But I'm deferring this to the product managers @agjohnson and @ericholscher to make the final decision.

**Comment by urosjarc** [comment]
Great to hear some response, anything done in this case will be much appreciate it.

**Comment by ericholscher** [comment]
I have deleted the `mylinux` project -- The larger issue here is being tracked with #1408 if you want to follow along with that.

**Comment by yassineS** [comment]
Hi, I removed the project (http://cosmos-hms.readthedocs.org/en/latest/) from the dashboard as well as the 'hook' on the github side. However the docs are still available on the link. Can you please take down?

**Comment by agjohnson** [comment]
@yassineS this issue is closed, please open a new ticket with your issue so that we can track it
