### ISSUE TITLE
Inactive account

### ISSUE THREAD

**Issue by gtorodelvalle** [rtfd/readthedocs.org#1541]
Hi guys, I just reset my password and when I try to log in I get a "This account is inactive". How can I get it set as active? :)
I saw this issue you solved in the past: https://github.com/rtfd/readthedocs.org/issues/1451 Just in case it helps :)
My username in readthedocs.org is gtorodelvalle
Thank you very much in advance for your help.

**Comment by ericholscher** [comment]
Should be good to go.

**Comment by gtorodelvalle** [comment]
Indeed... :) Thank you very much!

**Comment by qiuwch** [comment]
Hi, I have exactly the same issue. My username is qiuwch. What should I do to active the account?

**Comment by ajinkyawadekar** [comment]
hey the same issue, my username is a.wadekar.

**Comment by RichardLitt** [comment]
Thanks @ajinkyawadekar - can you open a new issue for this, please?
