### ISSUE TITLE
MkDocs theme integration broken by a recent change

### ISSUE THREAD

**Issue by d0ugal** [rtfd/readthedocs.org#1542]
The popup thing used to be docked in the left side, now it off floating on the right again.

**Comment by d0ugal** [comment]
See for example here: http://mkdocs.readthedocs.org/en/latest/

(I had somebody else test it, and it worked as first due to caches, so make sure you hard refresh)

**Comment by gregmuellegger** [comment]
@d0ugal can you remember when it last worked?

**Comment by d0ugal** [comment]
I'd guess it worked around a week ago and perhaps more recently too.

**Comment by gregmuellegger** [comment]
Ok, found the problem. The JS refactor in #1463 did the harm (I'm responsible on that :cry:)
Will be fixed with the merge of #1545

**Comment by d0ugal** [comment]
Awesome, thanks! It's good to see that refactor, the code was somewhat hacky to make it work with a Sphinx documentation. Good work :)
