### ISSUE TITLE
need some header files for install, installed code needed for docs build

### ISSUE THREAD

**Issue by ThomasWaldmann** [rtfd/readthedocs.org#1546]
Hi, I just wanted to migrate https://borgbackup.github.io/ project's docs to rtfd.

But I ran into issue I could not solve.

To build the usage docs, I need working code installed as the interactive help output (borg init --help for example) is used to generate part of the docs.

To build / install borg, I need some header files and libraries not present on rtfd, see there for debian/ubuntu:
https://borgbackup.github.io/borgbackup/installation.html#debian-ubuntu-installation-from-git

Currently, at least libacl1-dev seems missing.

See build log there:
https://readthedocs.org/builds/borgbackup/3205340/

**Comment by gregmuellegger** [comment]
Unfortunatelly we cannot support arbitrary header files and compiling from source. Maybe you can work around the problem by mocking out the C libraries that you depend on. See the FAQ for more info on that: http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by ericholscher** [comment]
Closing this, as we aren't able to support this.

**Comment by ThomasWaldmann** [comment]
yes, I understand. thanks for the hint, i'll try if we can install without or with mocking that lib.
