### ISSUE TITLE
Customise the PDF layout

### ISSUE THREAD

**Issue by pditommaso** [rtfd/readthedocs.org#1547]
Is there any way to modify or provide a custom layout to the PDF generated by ReadTheDocs ?

In particular I would need to change the text formatting in the source code blocks.

**Comment by gregmuellegger** [comment]
The PDF is created by compiling the `rst` files into LaTeX files and then converting those into a PDF. So you can adjust the Sphinx latex options in order to customize the outcome, see here: http://sphinx-doc.org/config.html#latex-options

**Comment by pditommaso** [comment]
Thanks, for your quick reply. However in that link I'm unable to find any way to manage the style of Literal code blocks. Any clue about that ?

**Comment by gregmuellegger** [comment]
I'm afraid that will require LaTeX knowledge to change the style. I'm not good with that, but I think it would go into the `latex_elements` in the `preamble` section. Also examine the files emitted when you run "make latex" for your Sphinx project. These will be the source file used to convert into PDF. You will see the markup that wraps the code block. Based on that you will probably be googling around a lot about LaTeX :( sorry that I can't help more on that end.

**Comment by pditommaso** [comment]
Thanks for the tip. I will try to investigate that.
