### ISSUE TITLE
wrong link for "Edit on GitHub" of README.rst (if index.rst does not exist)

### ISSUE THREAD

**Issue by wdv4758h** [rtfd/readthedocs.org#1550]
Currently, `doc_builder/base.py` will rename `README.rst` to `index.rst` if repo does not have `index.rst`. And this make the generated index.html finding `index.rst` as source. Then, it cause 404 when user click "Edit on GitHub". (repo only have `README.rst`)

**Comment by gregmuellegger** [comment]
Example: http://python-best-practices.readthedocs.org/en/latest/

**Comment by ericholscher** [comment]
I believe our servers will now serve README.html as an index file, so we can probably stop transforming the files and be good.

**Comment by gregmuellegger** [comment]
@ericholscher I tried this in #1585, but it seems to be more complicated. See there for comments.
