### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Swader** [rtfd/readthedocs.org#1551]
I have a `requirements.txt` file in the appropriate advanced settings input field, and it's in my repo [here](https://github.com/sitepoint-editors/samplesphinx-php/blob/master/requirements.txt), but it's not getting executed. To be precise, I'm trying to get sphinxcontrib-phpdomain to install but no dice, it's like it never runs - the build error log just tells me it can't fine the sphinxcontrib-phpdomain module.

Everything works fine locally, and the req file is an export of my local pip freeze.

Any ideas?

**Comment by Swader** [comment]
Never mind, realized the errors are actually in another section, and the file wasn't being fully executed. Suggestion: style the build fail screen a bit better.

**Comment by gregmuellegger** [comment]
@Swader Glad that it is resolved for you. We are reworking the build page and will hopefully have visible improvements on the build logs in a few weeks. I'm absolutely with you that the build page can be confusing sometimes.
