### ISSUE TITLE
orphaned project 'testfixtures'

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#1552]
Hi All,

When I try and register my 'testfixtures' project, I get told a project already exists, but I can't find it anywhere.

My suspicion is that it was created in the very eary days of rtd and is somewhat broken.

Would someone be able to delete the remnants so I can re-register the project?

thanks,

Chris

**Comment by ericholscher** [comment]
https://readthedocs.org/projects/testfixtures/ is the project. It's owned
by "chrisw": https://readthedocs.org/profiles/chrisw/

I'm guessing that is an old account that you created. I can delete the
project if that's easiest?

On Tue, Aug 11, 2015 at 1:55 AM, Chris Withers <notifications@github.com>
wrote:

> Hi All,
>
> When I try and register my 'testfixtures' project, I get told a project
> already exists, but I can't find it anywhere.
>
> My suspicion is that it was created in the very eary days of rtd and is
> somewhat broken.
>
> Would someone be able to delete the remnants so I can re-register the
> project?
>
> thanks,
>
> Chris
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1552>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by agjohnson** [comment]
Was this resolved?

**Comment by cjw296** [comment]
Yep, I recovered the password for 'chrisw' and deleted the project there.
