### ISSUE TITLE
Uninformative error when branch name contains a dot

### ISSUE THREAD

**Issue by takluyver** [rtfd/readthedocs.org#1553]
We were just experimenting with some docs stuff, and @minrk created a branch name with a dot (`.`) in it. Builds on this branch all failed, and the only error message in the logs was "top level build failure". It took us a while to work out that the branch name was the problem.

I don't think it's especially important to allow branch names with dots, but it would be nice to at least get an error that pointed us to the branch name.

**Comment by agjohnson** [comment]
Agreed, this could be an edge case bug that wasn't covered with some changes to branch name slugging.

**Comment by gregmuellegger** [comment]
Hm, I tried locally with the pypy project and built their `release-2.6.x` branch which worked.
@takluyver could you provide us with the branch you have problems with?

**Comment by takluyver** [comment]
I think it was a docs project @minrk had set up with his fork of the ipython/ipython GH repo to experiment. He might have more details.

**Comment by minrk** [comment]
The branch name was 'conf.py-hacks' Pushing the same commit to a new branch 'target' resulted in a successful build.

**Comment by gregmuellegger** [comment]
I investigated on this and found that the problem is not related to the dot in the branch name but the substring `conf.py`. I proposed a fix in #1629.

**Comment by minrk** [comment]
Thanks, @gregmuellegger!
