### ISSUE TITLE
Possible to create multiple projects from single repo?

### ISSUE THREAD

**Issue by Swader** [rtfd/readthedocs.org#1554]
I have some Gettext translations all in a single repo, under /docs in my project. I can create a separate config file for every language, so that every language setup is essentially a translation of the original project, but is there a way to add multiple RTD projects via a single repository? I need this in order to not have to make a separate github repo for every one of the included languages - they have abstracted common parts and work fantastically in this single-repo setup, allowing all my users to update any language they see fit without leaving the repo. If I had to separate out all those languages into separate repos just to make new RTD projects and declare them as transactions, that'd be too much of a dealbreaker.

I saw some people did [this](https://github.com/effektif/user-docs/tree/master/docs/de), but I'm unclear on how they implemented it in RTD.

**Comment by ericholscher** [comment]
You can point RTD to the specific conf.py file for Sphinx in the Advanced
Settings of the project Admin. This will use that specific conf.py,
allowing multiple projects that live in a repo.

We are hoping to add support for multiple translations within 1 project at
some point, but it's a low priority since it already works currently,
though it's a bit more effort.

On Tue, Aug 11, 2015 at 3:57 PM, Bruno Škvorc <notifications@github.com>
wrote:

> I have some Gettext translations all in a single repo, under /docs in my
> project. I can create a separate config file for every language, so that
> every language setup is essentially a translation of the original project,
> but is there a way to add multiple RTD projects via a single repository? I
> need this in order to not have to make a separate github repo for every one
> of the included languages - they have abstracted common parts and work
> fantastically in this single-repo setup, allowing all my users to update
> any language they see fit without leaving the repo. If I had to separate
> out all those languages into separate repos just to make new RTD projects
> and declare them as transactions, that'd be too much of a dealbreaker.
>
> I saw some people did this
> <https://github.com/effektif/user-docs/tree/master/docs/de>, but I'm
> unclear on how they implemented it in RTD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1554>.
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by Swader** [comment]
> You can point RTD to the specific conf.py file for Sphinx in the Advanced
Settings of the project Admin. This will use that specific conf.py,
allowing multiple projects that live in a repo.

That was the original idea, yes, but as I can only set up one project from a single repo, I don't get the change to set up several projects, each pointing to its own `conf.py`. Or am I missing something.

**Comment by gregmuellegger** [comment]
@Swader I think you can create a new project that uses the same repository url. You will have two distinct projects on RTD with different names that use the same repository.

**Comment by Swader** [comment]
Ah, correct. So that worked and I have everything running smoothly on my local machine.

My builds on RTD are failing, though - any help would be much appreciated.

It keeps looking for the master file in the location of the custom `conf.py` file, specific to the language. How do I make it look for the sources two folders above the current file's location? I tried appending paths, to no avail. See [here](https://github.com/sitepoint/rtdsphinx-php).

Full build error [here](https://readthedocs.org/builds/rtdsphinx-php/3255152/).

**Comment by Swader** [comment]
Resolved via #1573 and in [this project](https://github.com/sitepoint/rtdsphinx-php)
