### ISSUE TITLE
"./manage.py migrate" no longer prompts for a Django superuser account

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1562]
Most likely something on my end.  But following the rtd install from scratch per https://docs.readthedocs.org/en/latest/install.html, "./manage.py migrate" no longer prompts for a superuser password.

**Comment by nathanaelhuffman** [comment]
I'm experiencing the same, so it may not be on your end.

**Comment by Balooga** [comment]
I created a superuser manually using "./manage.py createsuperuser", which seems to do the trick.

**Comment by gregmuellegger** [comment]
Thanks for the report! The docs will be fixed with #1566 
The `./manage.py createsuperuser` is the recommend way to create a new superuser.
