### ISSUE TITLE
Check visitor stats?

### ISSUE THREAD

**Issue by Gabriel-p** [rtfd/readthedocs.org#1564]
Not sure if this qualifies as an 'issue', perhaps more a question about the site.

I might me missing something obvious here, but I searched around and I've found no way to check the visitors stats for a RTD project. Is this correct?

If there is no built in stats page for a project, can a tracking block (e.g: Google Analytics) be added? If so, are there any instructions on how to do this?

Cheers.

**Comment by gregmuellegger** [comment]
You can set a google analytics code in your admin panel. Go to the dashboard of your project, then select "Admin" and then "advanced settings" in the sidebar on the left. You will see a field called "Analytics-Code" at the very bottom of the page:

![screen1](https://cloud.githubusercontent.com/assets/88278/9301875/23249322-44d2-11e5-8efd-c014fdb74aa6.png)

Hope this helps :)

**Comment by Gabriel-p** [comment]
Don't know how I missed that, mainly because I had *already set up the tracking code*. Sorry and thank you!
