### ISSUE TITLE
Add Domain objects

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#1571]
The goal here is to make our usage of domains more explicit. This includes CNAME's, and our tracking or domain usage of people on our site. 

To do:

* [x] Model Domain objects
* [ ] Migrate Canonical URL on project to Domain object
* [ ] Build admin panel (API-based)
* [ ] Create objects in middleware on domain usage

**Comment by gregmuellegger** [comment]
Related #1575

**Comment by ericholscher** [comment]
Closing as we now have a PR.
