### ISSUE TITLE
Intermittent "Top-level Build Failure: __init__() takes exactly 2 arguments (1 given)"

### ISSUE THREAD

**Issue by edmorley** [rtfd/readthedocs.org#1572]
Only occurs intermittently, eg:
https://readthedocs.org/builds/treeherder/3256061/
https://readthedocs.org/builds/treeherder/3223958/
https://readthedocs.org/builds/treeherder/3223481/
https://readthedocs.org/builds/treeherder/3219551/
https://readthedocs.org/builds/treeherder/3210710/

If a new build is manually triggered it then succeeds.

Any ideas? :-)

**Comment by Swader** [comment]
+1 happens often for me too lately

**Comment by jstoiko** [comment]
same here https://readthedocs.org/builds/ramses/3257411/

**Comment by ericholscher** [comment]
Yea, this appears to be a random Django 1.8 failure that I haven't quite
tracked down yet. I am looking into it.

On Wed, Aug 19, 2015 at 8:06 AM, Jonathan Stoikovitch <
notifications@github.com> wrote:

> same here https://readthedocs.org/builds/ramses/3257411/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1572#issuecomment-132632672>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by jstoiko** [comment]
ramses does not use django

**Comment by ericholscher** [comment]
It's an error on our side, and seems to have started when we upgraded to Django 1.8 a couple weeks ago, I mean.

**Comment by jstoiko** [comment]
I see. time to switch to pyramid maybe :)

**Comment by gregmuellegger** [comment]
@ericholscher expressed that he has deployed a fix as described in #1028 
Seems to be fixed for Treeherder: https://readthedocs.org/projects/treeherder/builds/
