### ISSUE TITLE
Paths to the generated documentation in "Downloads" (pdf, epub, zip) is "locahost" on a local RTD installation

### ISSUE THREAD

**Issue by Balooga** [rtfd/readthedocs.org#1578]
I just noticed that the path to the pdf, epub & zip'ed HTML documentation in the "Downloads" section of a project is "localhost" on a *local* installation of RTD, and not the server name specified in "SLUMBER_API_HOST"

**Comment by agjohnson** [comment]
Check your production domain setting, `SLUMBER_API_HOST` only sets the host for API calls.

**Comment by Balooga** [comment]
That did the trick. Thank you.
