### ISSUE TITLE
api request: list of the latest updated documents

### ISSUE THREAD

**Issue by lucamorelli** [rtfd/readthedocs.org#1586]
I would like to poll periodically and ask for updated or new documents in a project. How can I do this?

**Comment by gregmuellegger** [comment]
Just to be clear, you want to get a list of the latest updated `.rst` documents?

One possibility to do so would be to check the source code repository for the latest updates in the docs directory. If this is feasible depends of course on your usecase. There is currently no way to achieve that with our REST API

What do is the usecase you have in mind for this?

**Comment by lucamorelli** [comment]
thanks, in the end I solved this way. I check for all the changed rst files in the commit
