### ISSUE TITLE
Dead "fundraising-wrapup" link on homepage (maze found)

### ISSUE THREAD

**Issue by tbielawa** [rtfd/readthedocs.org#1590]
In the **Thanks for supporting us!** call-out on the RTD homepage there is a link in this sentence:

* Please read our [blog post](https://blog.readthedocs.com/fundraising-wrapup/) outlining our plan going forward. 

Which points to ``https://blog.readthedocs.com/fundraising-wrapup/``

However, visiting the link brings one to a non-existent page (maze found)

**Comment by ericholscher** [comment]
-> curl -I https://blog.readthedocs.com/fundraising-wrapup/
HTTP/1.1 200 OK

Works for me?

**Comment by tbielawa** [comment]
That is so weird, sorry for the false alarm. Must be on my end of things.

I tried with google chrome when I reported the bug. I tried in Firefox after seeing your response and everything worked fine (same w/ chrome incognito mode).
