### ISSUE TITLE
Can't login even after password reset

### ISSUE THREAD

**Issue by jarvisschultz** [rtfd/readthedocs.org#1591]
I've successfully reset my password many times. I've tried logging in with both my email and username. I've tried pasting the username that was included in the password reset email. I've looked at my user metadata: http://readthedocs.org/api/v1/user/?username=jarvisschultz&format=json and I can't see anything weird. However, every time I login I get

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```
and the page title is `Server Error | Read the Docs`. Username is `jarvisschultz`.

Any ideas?

**Comment by agjohnson** [comment]
This was a server error with our session storage, it should be resolved now.

**Comment by jarvisschultz** [comment]
Definitely fixed... Thanks!
