### ISSUE TITLE
With build queue nonresponsive, changes to documentation should not be possible

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1592]
Audit the scenario brought up in #1589.

If the build queue is non-responsive, pushing a commit via webhook should not alter built documentation in any way. Make sure this isn't the case.

**Comment by humitos** [comment]
What are the steps to audit this? Is it possible to test this locally or we need access to the server?

Is it enought to kill celery in a local instance and hit a webhook? or should I kill redis and test the webhook? Would it be that enough?

Is this issue still valid? It's from 2015 with `Priority: High` so... it doesn't seem to be too high :P

**Comment by agjohnson** [comment]
You should be able to test this locally. The underlying issue describes the cause as:

* Build queue goes down or is unreachable
* Push a webhook to the project
* Something removes the documentation or more likely the symlink
* Build never happens

Let's investigate the symlink step, this seems to be the culprit. It's getting triggered on project save.

**Comment by stsewd** [comment]
I can't replicate, I did this:

- Shutdown celery
- Trigger a manual webhook
- There is a build (triggered state)
- The docs are still showing and symlinks look good

I also tried shutting down celery in the middle of the build.

**Comment by agjohnson** [comment]
We can probably close this then. We hit this in production once, but haven't since.
