### ISSUE TITLE
error by the branch name with Unicode chars 

### ISSUE THREAD

**Issue by sih4sing5hong5** [rtfd/readthedocs.org#1594]
I used `文件` as the branch name and got the error message.
```
'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
```
I created another branch `docs` with the same commit and worked.

I really setted the interpreter with Cpython 3 in advanced settings.

This issue is like #1553  ?

Here is [my repository](https://github.com/sih4sing5hong5/tai5-uan5_gian5-gi2_kang1-ku7).

**Comment by agjohnson** [comment]
It is similar, though we already started discussing the implications of utf8 slugs in #1410. Closing this as a duplicate, feel free to chime in on or watch that ticket.

**Comment by sih4sing5hong5** [comment]
Thanks.
