### ISSUE TITLE
Upgrade to Pip 7.0.2 or later

### ISSUE THREAD

**Issue by Ichimonji10** [rtfd/readthedocs.org#1595]
For quite some time, pip has allowed the use of requirements specifiers, like so:

    SomeProject
    SomeProject == 1.3
    SomeProject >=1.2,<.2.0
    SomeProject[foo, bar]
    SomeProject~=1.4.2

Pip 6.0 and later also allow the use of environment markers, like so:

    SomeProject ==5.4 ; python_version < '2.7'
    SomeProject; sys.platform == 'win32'

Unfortunately, pip 7.0.0 and 7.0.1 suffer from a bug (pypa/pip#2839) that breaks environment markers containing the `python_version` token. For pip 7.0.0 and 7.0.1, the following is legal instead:

    "SomeProject ==5.4 ; python_version < '2.7'"

Note the extra quotes. Pip 7.0.2 fixes this issue, but no attempt at backward compatibility is made.

rtfd uses pip 7.0.1. As a result, rtfd is incompatible with any Python project that uses requirements specifiers with the `python_version` environment marker. In my case, it means that documentation for NailGun cannot be built because its [`requirements-dev.txt`](https://github.com/SatelliteQE/nailgun/blob/master/requirements-dev.txt) file contains the following:

    # For `make test`
    mock
    unittest2 ; python_version < '3.4'

Please update to pip 7.0.2 or later.

**Comment by Ichimonji10** [comment]
I've manually tested the proposed solution for this issue. In short, it goes like this:

```sh
git clone https://github.com/SatelliteQE/nailgun.git
cd nailgun
python3 -mvirtualenv env
source env/bin/activate
pip install pip==7.0.1
pip install -r requirements-dev.txt  # fails
pip install pip==7.0.2
pip install -r requirements-dev.txt  # succeeds
```

**Comment by ericholscher** [comment]
Pip should be set at 7.1.0 in our requirements now: https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L2

**Comment by Ichimonji10** [comment]
:+1:
