### ISSUE TITLE
Docs not building after push to repo

### ISSUE THREAD

**Issue by Gabriel-p** [rtfd/readthedocs.org#1598]
I noticed this yesterday for my repo: https://github.com/asteca/ASteCA-Docs

After a push, the documentation wouldn't update automatically (I have RTD set up as a Service in the Github repo).

I had to manually build it and even so only the HTML version was built, when I have the `Create a PDF version of your documentation with each build.` option checked.

I just made another push (few minutes ago) and still nothing.

**Comment by Gabriel-p** [comment]
Weird, I just notices that the PDF *is* being produced even if no notice of "Passed" is given in the builds page.

Still not making the builds automatically though, I have to force them manually.

**Comment by agjohnson** [comment]
The build system no longer creates magic pdf builds, they are encapsulated under the main build object.

Not sure on the webhook, we'd have to look more into that.

**Comment by Gabriel-p** [comment]
Thanks for clarifying the PDF building issue. I'll try a new commit push in a couple of hours to see if this problem is fixed and report back here.

**Comment by Gabriel-p** [comment]
Just pushed a commit (~10 min ago: https://github.com/asteca/ASteCA-Docs) and there's no new build: https://readthedocs.org/projects/asteca/builds/

**Comment by Gabriel-p** [comment]
2 hrs since pushed commit, still no build.

**Comment by Gabriel-p** [comment]
+8 hrs now, still nothing. @agjohnson should I just build it manually?

**Comment by agjohnson** [comment]
If it isn't triggered immediately, the webhook failed. My guess is your repository name doesn't match the github repo URL (it's case sensitive).

**Comment by Gabriel-p** [comment]
Yep, that was it. I didn't notice it was case sensitive and some time ago I had changed  the name of the repo from `asteca` to `ASteCA`.

Closing the issue, thank you for your help @agjohnson!
