### ISSUE TITLE
Remove duplication of get_downloads

### ISSUE THREAD

**Issue by takotuesday** [rtfd/readthedocs.org#1600]
These seem to be duplicate implementations:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/builds/models.py#L167

and 

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L422

It appears that the only implementation of get_downloads used, is within the Version class:
https://github.com/rtfd/readthedocs.org/search?utf8=%E2%9C%93&q=get_downloads

Is this legacy code that could be refactored?

**Comment by gregmuellegger** [comment]
The `Project.get_downloads` is still used here: https://github.com/rtfd/readthedocs.org/blob/457823dfe84e7fdcc3a5274be7132224379bdae1/readthedocs/api/base.py#L52

So I think we cannot remove one of the implementations.
