### ISSUE TITLE
Remove unused variable media_url_prefix

### ISSUE THREAD

**Issue by takotuesday** [rtfd/readthedocs.org#1605]
This code appears to no longer be in use. If you look at the template being rendered, `media_url_prefix` is never used.

https://github.com/rtfd/readthedocs.org/commit/35a942b71c047c2518f96bea9a2f9bdc0aa921d6#diff-4fcca638684a1c1611b72a6dd6f1119aR34

**Comment by gregmuellegger** [comment]
I can confirm that the variable is not used. Proposed the refactor in #1630
