### ISSUE TITLE
the website generated is still alive after remove the project on rtd

### ISSUE THREAD

**Issue by mickaelandrieu** [rtfd/readthedocs.org#1606]
Hi,

http://blogbee-docs.readthedocs.org/en/latest/ should be down :/  this cause a duplicate content issues on http://blogbee.backbee.com.

Can someone in charge of the platform can take a look ? 

Thank you

**Comment by gregmuellegger** [comment]
This is problem that we hope to resolve in #1408. We'll delete the artifacts from our servers manually for now to fix the problem for you.

@agjohnson @ericholscher Can you delete the left over artifacts from the webservers?
The related project was deleted: https://readthedocs.org/projects/blogbee-docs/

**Comment by mickaelandrieu** [comment]
thank you @gregmuellegger :+1:

**Comment by ericholscher** [comment]
Deleted.
