### ISSUE TITLE
Docs Information Pop Up not working

### ISSUE THREAD

**Issue by ffleandro** [rtfd/readthedocs.org#1608]
I've installed readthedocs on my own private server, configured it and i'm correctly building a repo, with several versions, just one language, and exporting to pdf.

Howver, when i'm viewing the builded html, the pop up that can be viewed on the lower left corner is always minimized. I click on it, but it doesn't show.

Is there any configuration needed to make this feature work or it should work out of the box?

**Comment by alasdairdc** [comment]
Its due to broken symlinks to javascript files.

**Comment by ffleandro** [comment]
Thanks for your response @alasdairdc .
Which symlinks do I have to correct/create?

**Comment by iconoeugen** [comment]
The correction I have done is:

```
mkdir ./media/static
ln -s ../../readthedocs/core/static/core ./media/static/core
ln -s ../../readthedocs/static/vendor ./media/static/vendor
```

I would expect this to be added to the git repo, but at the same time the `media/static` path is included in the `.gitignore`

I think the problem of this collision between missing links under a path that is explicitly ignored must be clarified before I push a pull request.

**Comment by alasdairdc** [comment]
From memory its 3 javascript file for Sphinx and a couple for MkDocs.  Inspect element while on the page and you'll notice the 404s for the files.  Just delete the broken links and recreate them with the correct paths.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

And I think the solution pointed in https://github.com/rtfd/readthedocs.org/issues/1608#issuecomment-141774500 is the correct.
