### ISSUE TITLE
CNAME for a project imported from Github

### ISSUE THREAD

**Issue by claus022015** [rtfd/readthedocs.org#1613]
Hi!

I`m a newbie in readthedocs.org and i`m trying to setup a CNAME for a sub project.
The main project is this : 
http://nutrition-database-modernization.readthedocs.org/en/latest/

I`ve followed the tutorial, added a canonical name to the subproject , but i`m getting " Server not found " error.

Here is what i see in page source :

  
  
  <link rel="canonical" href="http://docs.nutrition-database-modernization.org/en/latest/" />

Could you please give me some advice on this issue?
What am i failing to do?

Thanks in advance!

**Comment by agjohnson** [comment]
What's the hostname you are trying to point to RTD? It seems that isn't set up correctly.

**Comment by claus022015** [comment]
I'm trying to point it to  
  <link rel="canonical" href="http://docs.nutrition-database-modernization.org/en/latest/" />

I have also tried to point my own hostname www.afdsi.org , but again it returns a Server Not Found error.

Should i modify the DNS on my own server, and point www.afdsi.org to docs.afdsi.org ?

**Comment by claus022015** [comment]
Trying to point to this: 
link rel="canonical" href="http://docs.nutrition-database-modernization.org/en/latest/

previous comment didnt show the URL path

**Comment by agjohnson** [comment]
Yes, you'll need to point the subdomains you want to use at you:
http://docs.readthedocs.org/en/latest/alternate_domains.html?highlight=domain#cname-support

**Comment by claus022015** [comment]
Thank you for taking the time to clarify this.
