### ISSUE TITLE
list of branches isn't updated

### ISSUE THREAD

**Issue by mlubin** [rtfd/readthedocs.org#1617]
For JuMP (http://jump.readthedocs.org/en/latest/), I recently pushed a branch called ``release-0.10``, but it's not showing up on the list at https://readthedocs.org/dashboard/jump/versions/ so that I can enable docs for this branch. I've rebuilt the docs a number of times and pushed commits using webhooks, but doesn't seem to update the list of branches. Any ideas?

Thanks!

**Comment by agjohnson** [comment]
This might be another bug with our version parsing, I get a 500 error on your version page.

**Comment by agjohnson** [comment]
Dug into this a little more, it's a utf8 character in the version name apparently. We don't do a good job of handling utf8 names yet. This is a duplicate of #1410, moving conversation there.

**Comment by mlubin** [comment]
So is there anything I can do in the meantime? I deleted the branch with unicode characters but the list of branches is still stuck.

**Comment by mlubin** [comment]
Sorry to bother, but is there anything we can do on our side to get the list of branches working again? We no longer have a branch with UTF-8 characters.

**Comment by agjohnson** [comment]
There are likely stale branches that need to be removed on our end, we can try to clean those out soon.

**Comment by mlubin** [comment]
Any way we could get a fix for our repo soon? This issue is preventing us from maintaining separate release and development docs.

**Comment by buhtz** [comment]
I still don't see this fixed. The list of branches is not updated and there also is no button to trigger this.
