### ISSUE TITLE
Add sumome analytics support

### ISSUE THREAD

**Issue by ugocupcic** [rtfd/readthedocs.org#1620]
Hi,

I was wondering how hard it would be to add support for [sumome](http://sumome.com)? 

The idea is to inject the line below - it should be close to what google analytics require:

```html
<script src="//load.sumome.com/" data-sumo-site-id="YOUR-TOKEN" async="async"/>
```

Cheers,

Ugo

**Comment by agjohnson** [comment]
This could be handled by including the script with template modifications. I think this is outside the scope of RTD otherwise.
