### ISSUE TITLE
Issue in building and installing on Windows

### ISSUE THREAD

**Issue by TheBlueSky** [rtfd/readthedocs.org#1625]
Hello everyone,

Is building and running on Windows supported?

I followed the [installation steps](https://read-the-docs.readthedocs.org/en/latest/install.html), or rather the equivalent Windows version, and made sure all my tools are installed with their supported vertions; e.g., Python 2.7, pip, virtualenv, and Visual C++ Compiler for Python 2.7.

However, when I run `pip install -r requirements.txt` I receive a compilation error; "hiredis" references some *nix specific header that isn't available on Windows.

Is this a known issue and is there any way around it?

**Comment by agjohnson** [comment]
This error means the redis development headers are not found. I'm not familiar with windows though, so not sure what the equivalent procedure would be here.

Anyways, no, windows is not supported. If you are able to install dependencies, we make heavy use of symlinking on built documentation. This would require significant changes to our infrastructure to support. Happy to discuss what that means if you are willing it take on supporting this, but we won't be supporting this ourselves.
