### ISSUE TITLE
New build failure in epub.py

### ISSUE THREAD

**Issue by arq5x** [rtfd/readthedocs.org#1627]
Hello,

I have been able to cleanly build the documentation for bedtools for a couple of years now. Last week, however, and a very minor update to the docs, I am consistently getting the following build error:

      File "/home/docs/checkouts/readthedocs.org/user_builds/bedtools/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/epub.py", line 210, in esc
    name = name.replace('&', '&amp;')
AttributeError: 'NoneType' object has no attribute 'replace'

Full log: https://readthedocs.org/projects/bedtools/builds/3302623/

This appears to be an error that is unrelated to the docs themselves, but rather something in the RTD build process, though I may be wrong.  Could you provide any guidance as to what might be causing this error? I should not that a local build is successful. What `name` might epub.py be looking for that is missing?

**Comment by gregmuellegger** [comment]
I think this is a Sphinx error, I reported a ticket in sphinx-doc/sphinx#2027

To make your docs build again right now, you can comment out the line `html_title=None` in your `conf.py`. That should fix the issue.
