### ISSUE TITLE
Search results for mkdocs do not use CNAME

### ISSUE THREAD

**Issue by itayher** [rtfd/readthedocs.org#1628]
When ever I search for a phrase in the documentation, the results links are coming back with wrong URL. It seems that they don't consider multi level. Also the URL comes with readthedocs.org domain and not the our domain. Is this a bug or we missing configuration?

**Comment by gregmuellegger** [comment]
Seems to work ok for the pip project: https://pip.pypa.io/en/stable/search.html?q=setuptools&check_keywords=yes&area=default
Can you provide us with a link to a malfunctioning search?

**Comment by itayher** [comment]
Yes, I see it is working for you.
In http://docs.backand.com search for ORM, the result looks different (doesn't use the highlight cool feature) and if you click on the link to the page you see it is broken.
Thanks for the help

**Comment by gregmuellegger** [comment]
Ok thanks for the example. I assume the reason is that there is no specific theme for a mkdocs based documentation. However it should ofcourse take the configured CNAME into account. We'll need to have a look there.

**Comment by gregmuellegger** [comment]
I think we can't address this issue currently in a proper way as readthedocs.org does not know anything about configured CNAMEs. I created #1632 as a new issue in order to propose some way to configure the "main" domain that should be used to link to a project's documentation.

**Comment by itayher** [comment]
How can I setup the search to return results with highlighted text and not in the way it is now.
Regarding the CNAME, the URL is broken not just because of the domain name but also it doesn't include folder structure (try to replace the result domain with docs.backand.com and still remain broken).

**Comment by gregmuellegger** [comment]
Thanks for pointing out the broken links! I missed that in the first look through. I've opened #1633 to track it separately.

Regarding the highlighting: the text is actually highlighted, but only by making it italic:
![screen1](https://cloud.githubusercontent.com/assets/88278/9720007/415a3b1c-558a-11e5-886e-77c87ea587bb.png)
You can see the word *ORM* being in italic.

Actually while writing this, I realized that you mean the highlighting of the words when following the link from the search to the docs, right? For example, the following link should highlight the word "database", correct? http://backand-docs.readthedocs.org/en/latest/?highlight=database

**Comment by itayher** [comment]
Yes, database was supposed to be highlight

**Comment by gregmuellegger** [comment]
That feature did not exist so far for mkdocs projects. I created #1640 to suggest an implementation of this.

**Comment by gregmuellegger** [comment]
Seems like there have been three main points in this ticket that we did split out into:

- #1632 
- #1633 
- #1640 

I'm closing this ticket as we have the other three open to track the individual progress.

@itayher I hope this addresses all of your issues. Respond here if I have forgotten something.
