### ISSUE TITLE
Make "canonical domain" configurable

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1632]
It was raised in #1628 that the search results page (or any other link to the docs) does not use the configured CNAME, but is using the subdomain *.readthedocs.org

Here is an example:
https://readthedocs.org//search/?q=ORM&check_keywords=yes&area=default&project=backand-docs&version=latest&type=file
Or the project dashboard links to the subdomain, not to the CNAME `docs.backand.com`

I would consider this sub-optimal UX and would assume as a user that I can host the docs in a canonical location. I want to avoid the same content at different URLs.

However we currently have no way to link to the full CNAME domain as we do not have the information in the database. The users are setting up the CNAMEs outside of readthedocs.org. I propose that we should make the main docs domain that a project wants to use configurable.

**Comment by agjohnson** [comment]
I think #1575 gets us at least part of the way there on this, though I don't think it establishes an idea of "primary cname"

**Comment by gregmuellegger** [comment]
Seems like there is a `canonical` field on the `Domain` model. So it might fight our need perfectly here :)

**Comment by gregmuellegger** [comment]
Blocked by #1575

**Comment by gregmuellegger** [comment]
#1575 got merged.

**Comment by ericholscher** [comment]
We don't link out to CNAME's from the RTD site anywhere, generally. People have often misconfigured their CNAME's which leads to the whole of RTD being broken for a user. I could be convinced, but if people are coming to a project from RTD, it makes sense to send them to our domain hosting for the project. If we wanted to "truly" support CNAME's, we could force redirect the slug.rtd.org domains to a CNAME, but again this feels like more complexity without much user benefit. 

I think having all of the domains be the same is something project owners might care about, but as a user I don't care what domain I look at to view docs. Linking to known good URL's that we control seems like a better user experience in general.

**Comment by ericholscher** [comment]
Believe this is now fixed, as seen here: http://readthedocs.org/projects/writethedocs-www/ and in the initial URL in the bug.
