### ISSUE TITLE
Build PDF from MkDocs markdown

### ISSUE THREAD

**Issue by jkmacc-LANL** [rtfd/readthedocs.org#1635]
The RTD docs imply that a PDF would be built for the supported doc formats, which include markdown from MkDocs.  My project uses MkDocs and markdown.  No PDF is being built, however.  Rather, it's an old blank one from when I was tweaking the project settings. I've tried wiping the build directory, but that didn't work.

[RTD Project page](https://pysac-seismic.readthedocs.org/en/latest/index.html)
[PDF link](https://readthedocs.org/projects/pysac-seismic/downloads/pdf/latest/)

 Does RTD actually support PDF building for markdown docs?

**Comment by agjohnson** [comment]
No. This needs to be part of Mkdocs first.
