### ISSUE TITLE
Fix or abandon reindex_elasticsearch

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/readthedocs.org#1641]
Currently the managment command `reindex_elasticsearch` [located here](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/management/commands/reindex_elasticsearch.py) is broken in at least two ways:

1. We give a [filter argument to the version's manager public method](https://github.com/rtfd/readthedocs.org/blob/adf227ae3810b0820d0ff548651dcd223f4f2388/readthedocs/core/management/commands/reindex_elasticsearch.py#L31). But that does not do any filtering. Therefore only selecting one project that should be updated will result in all projects to be reindexed.
2. We do not distinguish between mkdocs/sphinx projects. The used `parse_json.process_all_json_files` will only work correctly for Sphinx based projects.

We should either remove the command completely as long as it no longer used/needed. Or fix the issues outlined above.

**Comment by ericholscher** [comment]
This is the only way we have to reindex our search cluster, so it's definitely something we need to keep around.
