### ISSUE TITLE
Tries to install my code, even though I did not ask for it

### ISSUE THREAD

**Issue by Kwpolska** [rtfd/readthedocs.org#1649]
Builds for projects `pkgbuilder` and `cheqlist` fail. ReadTheDocs is attempting to do this:

    python /home/docs/checkouts/readthedocs.org/user_builds/pkgbuilder/envs/stable/bin/pip install --exists-action=w -r/home/docs/checkouts/readthedocs.org/user_builds/pkgbuilder/checkouts/stable/requirements.txt

However, I do not have the “use virtualenv” option checked, and I did not set any requirements path. I do not use autodoc, and therefore do not need this.

**Comment by gregmuellegger** [comment]
Here is the line that gets fancy when no requirements.txt file is specified explicitly: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L283

It is in line with our goals to reduce the number of projects that depend on a virtualenv or any other installation prior to building the docs, so would love to resolve this ticket soon. However we are deep in the work for creating a build system that will be configured with a `readthedocs.yml` file in the repository. Until then we want to avoid adding more configuration options in the admin.

Unfortunatelly too many projects depend on the auto-installed requirements that you experienced to be able to turn it off right now. We'll do the switch with the new build system. Stay tuned.

**Comment by gregmuellegger** [comment]
Blocked until `rtd-build` is in production.

**Comment by ericholscher** [comment]
You should be able to turn this off by unsetting the "install in virtualenv" in the advanced options. It's the first option on that page.

**Comment by ericholscher** [comment]
This should be fixed, I believe. The `install project` option will trigger it.
