### ISSUE TITLE
Don't email on version locked build errors

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1654]
Version locked exceptions should not bubble up as an exception we notify on in the project build task.

**Comment by Kemp-J** [comment]
Is this being looked at at all? I'm getting a "failed" email on every commit currently because of these errors. The system retries and inevitably succeeds the next time.

Alternatively, is there a workaround for users?

**Comment by willsheffler** [comment]
Also having this issue.

**Comment by humitos** [comment]
Closed by #2900
