### ISSUE TITLE
No option for completely removing testing docs

### ISSUE THREAD

**Issue by aperezalbela** [rtfd/readthedocs.org#1656]
Hi, I need to delete two test docs but I can't find the option in the UI. Could you please remove them completely? Their names are: "ScrapinghubTest" and "ScrapinghubTests". They are really messing with our official docs in search engines.

Thanks in advance.

cc: @gregmuellegger

**Comment by ericholscher** [comment]
They should be removed when they are deleted from the site. We had an issue with things not being deleted properly for a time, so they might have gotten caught there. What are the URL's?

**Comment by aperezalbela** [comment]
URL's are:

- http://scrapinghubtest.readthedocs.org
- http://scrapinghubtests.readthedocs.org

Thanks in advance.

**Comment by ericholscher** [comment]
Those projects still exist on the site. Delete them in the "Admin" section
of the project, at the bottom of the Settings tab.

On Wed, Sep 16, 2015 at 12:54 PM, Andrés Pérez-Albela H. <
notifications@github.com> wrote:

> URL's are:
>
>    - http://scrapinghubtest.readthedocs.org
>    - http://scrapinghubtests.readthedocs.org
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1656#issuecomment-140868559>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by aperezalbela** [comment]
Hey @ericholscher, thanks for your prompt reply. I've deleted both of them but the docs still appear at:

- http://scrapinghubtest.readthedocs.org
- http://scrapinghubtests.readthedocs.org

**Comment by ericholscher** [comment]
Hmm, we must have not fixed this. I have removed them by hand for now.

**Comment by aperezalbela** [comment]
@ericholscher thank you very much.

**Comment by ahnitz** [comment]
Is this still an issue? I've tried to delete an account and the pages still seems to be up (maybe they take a while?). Specifally, here. 

* http://pycbc.readthedocs.org/
