### ISSUE TITLE
Debian Stable, 8.1 jessie, installation problems

### ISSUE THREAD

**Issue by ppKrauss** [rtfd/readthedocs.org#1657]
Using http://docs.readthedocs.org/en/latest/install.html

The exception comments are about UBUNTU (installs on Stable Debian are different), so I ignore it... But some `django` errors occurs, and at end, 
<pre>
peter@localhost:~$ pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
(....)
  Cloning https://github.com/django-tastypie/django-tastypie.git (to 1e1aff3dd4dcd21669e9c68bd7681253b286b856) to /tmp/pip-build-7PTC2Q/django-tastypie
  Could not find a tag or branch '1e1aff3dd4dcd21669e9c68bd7681253b286b856', assuming commit.
(....)
Collecting django-filter from git+https://github.com/alex/django-filter.git#egg=django-filter (from -r requirements/pip.txt (line 52))
  Cloning https://github.com/alex/django-filter.git to /tmp/pip-build-7PTC2Q/django-filter
Collecting django-pagination-dev from git+https://github.com/ericflo/django-pagination.git@e5f669036c#egg=django_pagination-dev (from -r requirements/pip.txt (line 53))
  Cloning https://github.com/ericflo/django-pagination.git (to e5f669036c) to /tmp/pip-build-7PTC2Q/django-pagination-dev
  Could not find a tag or branch 'e5f669036c', assuming commit.
Collecting django-taggit-dev from git+https://github.com/alex/django-taggit.git#egg=django_taggit-dev (from -r requirements/pip.txt (line 54))
(...)
  building 'lxml.etree' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/src
  creating build/temp.linux-x86_64-2.7/src/lxml
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-7PTC2Q/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
  In file included from src/lxml/lxml.etree.c:346:0:
  /tmp/pip-build-7PTC2Q/lxml/src/lxml/includes/etree_defs.h:9:31: fatal error: libxml/xmlversion.h: No such file or directory
   #include "libxml/xmlversion.h"
                                 ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for lxml
  Running setup.py bdist_wheel for redis

(...)
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
  Running setup.py install for django-tastypie
  Running setup.py install for lxml
    Complete output from command /home/peter/rtd/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-7PTC2Q/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zCTxLP-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/peter/rtd/include/site/python2.7/lxml:
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'bugtrack_url'
      warnings.warn(msg)
    Building lxml version 3.3.5.
    Building without Cython.
    ERROR: /bin/sh: 1: xslt-config: not found
    
    ** make sure the development packages of libxml2 and libxslt are installed **
    
    Using build configuration of libxslt
    running install
    running build
    running build_py
    copying src/lxml/includes/lxml-version.h -> build/lib.linux-x86_64-2.7/lxml/includes
    running build_ext
    building 'lxml.etree' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/tmp/pip-build-7PTC2Q/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    In file included from src/lxml/lxml.etree.c:346:0:
    /tmp/pip-build-7PTC2Q/lxml/src/lxml/includes/etree_defs.h:9:31: fatal error: libxml/xmlversion.h: No such file or directory
     #include "libxml/xmlversion.h"
                                   ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/peter/rtd/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-7PTC2Q/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zCTxLP-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/peter/rtd/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-7PTC2Q/lxml
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(rtd)peter@localhost:~/rtd/checkouts/readthedocs.org$ 
</pre>

**Comment by gregmuellegger** [comment]
You need the `libxml-dev` package.

**Comment by ppKrauss** [comment]
Thanks (!), now my `apt-get install libxml2-dev` is ok... How to restart the installation? need some "purge" process before, or is only repeat `pip install -r requirements.txt`?

**Comment by agjohnson** [comment]
These installation steps are all covered in our documentation, please refer to the steps there.

**Comment by ppKrauss** [comment]
(first occurence of) `pip install -r requirements.txt` is at [install.html](http://docs.readthedocs.org/en/latest/install.html)

> Next, install the dependencies using pip (included with virtualenv):
> cd readthedocs.org
> pip install -r requirements.txt

**Comment by agjohnson** [comment]
Closing this due to activity. The core team doesn't have the capacity to support external installations, and these issues seem to be mostly covered in our documentation anyways.
