### ISSUE TITLE
Handle logged out users on build detail page

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1659]
Currently, due to some possibly aggressive permission checking on the build detail page, logged out users get a spinner, but API update requests receive a 403 response. Either logged out users should be able to query public projects, or this should back down to the static build detail page.

**Comment by humitos** [comment]
@agjohnson I wasn't able to reproduce this issue. As an anonymous user I have access to see a build page while it's building and receiving the updates and also when it has finished.

If that's what the issue talks about, I would close it.

**Comment by agjohnson** [comment]
This might be an old issue. I think we can close and reinvestigate if the issue isn't reproducible.
