### ISSUE TITLE
version "None" on multiple branches?

### ISSUE THREAD

**Issue by knickels** [rtfd/readthedocs.org#1660]
I'm having problems setting up multiple versions of my docs.
I have two tags (V2.0.0 and v4.0.0) and two branches (forked after v4.0.0) called "master" and "v4.1.0".
So I *think* that I have four "versions" of the docs - /en/v2.0.0 /en/v4.0.0 /en/v.1.0 also known as /en/stable, and finally /en/master also known as /en/latest.

BTW, the RTD site is [http://player-stage-manual.readthedocs.org](http://player-stage-manual.readthedocs.org)

The versions menu in the lower left points to http://player-stage-manual.readthedocs.org/en/latest/None, http://player-stage-manual.readthedocs.org/en/stable/None, etc... (which don't exist).  But the URLs that seem to work are simply /en/lastest or /en/stable (without the None).  

Can anyone help me fix my setup?

**Comment by ericholscher** [comment]
This will be fixed by #1634 -- It's blocked on Mkdocs.
