### ISSUE TITLE
String together Edit on Github link URL in RTD

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1661]
This is currently done in the theme, and is only performing a simple concat of the pieces. This should either be handled in a more robust way with snide/sphinx_rtd_theme#249, or we should build the link inside conf.py overrides. The only spot `conf_py_path` is even used in the theme is in the 'Edit on Github' link.

**Comment by humitos** [comment]
@agjohnson can you explain a little bit more this issue? is this still a problem?

**Comment by agjohnson** [comment]
Nope, i'll close this, i can't make sense of this one. I think the theme is a better place to handle this anyways?
