### ISSUE TITLE
Theme incorporated as submodule not found during build 

### ISSUE THREAD

**Issue by willdoran** [rtfd/readthedocs.org#1666]
Hi,

I'm trying to build an instance of my docs where the theme - based on sphinx_rtd_theme - is included and referenced as a submodule.

Locally, the build works once the submodule init has been run but on RTD I get a theme not found error. 

I've researched through RTD issues and noted that in the past there were some issues with submodules but that RTD does run git submodule update --init --recursive.

I've wired the theme into conf.py, setting 
html_theme
and
html_theme_path

The latter is set to point to a _theme dir within the same directory as conf.py, the _theme dir contains the submodule.

Could you point me in the right direction to resolve this?

Thanks!

**Comment by gregmuellegger** [comment]
Yes we unfortunatelly had problems with submodules lately which are not yet resolved. Could you please tell us which project you have problems with, so that we can have a look at the build logs?

**Comment by gregmuellegger** [comment]
Related: #1618

**Comment by humitos** [comment]
@willdoran is this still and issue?

I'm closing this one by now. Feel free to reopen and add more information to the report so we can reproduce it. Thanks!
