### ISSUE TITLE
support for documentation of a git repo hosted on Visual Sudio Online

### ISSUE THREAD

**Issue by fleed** [rtfd/readthedocs.org#1669]
Is there the possibility to create the documentation out of a private git repository hosted on Visual Studio Online?

**Comment by agjohnson** [comment]
Is Visual Studio Online only for private repositories? It supports git, so theoretically should be relatively easy to support.

The community site, that is readthedocs.org, only offers hosting for public documentation/repositories. It would be possible to support these repositories at readthedocs.com though.

**Comment by fleed** [comment]
Thanks. Actually, I would like to host them by myself using a docker container.
But also hosting them at readthedocs.com might be a good solution.

**Comment by agjohnson** [comment]
Roger. If you have standard access to the private repos through ssh keys, then yes, it should mostly work -- webhooks won't work without specific support for Visual Studio Online.

**Comment by advancedrei** [comment]
I would love support for it if you could put it on the roadmap. The webhooks are documented here: https://www.visualstudio.com/docs/integrate/get-started/service-hooks/events. You could also build an extension for the Visual Studio marketplace. https://www.visualstudio.com/docs/integrate/extensions/overview

Thanks!

**Comment by agjohnson** [comment]
Supporting VSO is a non-trivial amount of work, and there doesn't look to be much support in this thread for implementation. We partially support it currently, but it takes manual setup on both our community site and our commercial hosting. Perhaps we can add some documentation on this instead.
