### ISSUE TITLE
Build failing for project with matplotlib dependencies (I believe I have read every solution - HALP! 🙏) 

### ISSUE THREAD

**Issue by drvinceknight** [rtfd/readthedocs.org#1671]
On a library that makes use of matplotlib (and also numpy) we only just noticed a failed build. In fact the docs stopped building in mid August :cry: but the first failing commit didn't really have anything in it that changed the docs.

You can see the issue here: https://github.com/Axelrod-Python/Axelrod/issues/318 which has more information.

I have tried:

- pointing at a dummy requirements file: https://read-the-docs.readthedocs.org/en/latest/faq.html#my-project-isn-t-building-with-autodoc
- using various versions of mocking the dependencies out of the library: http://blog.rtwilson.com/how-to-make-your-sphinx-documentation-compile-with-readthedocs-when-youre-using-numpy-and-scipy/ and https://read-the-docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
- I have read https://github.com/rtfd/readthedocs.org/issues/1056 and https://github.com/rtfd/readthedocs.org/issues/217 but they do not offer any help (I found those by searching for https://github.com/rtfd/readthedocs.org/issues?utf8=%E2%9C%93&q=Builds+fail+when+using+matplotlib after reading your contributions guidelines).

I have tried a large number of changes without any luck (a co contributor and I spent pretty much all afternoon committing and reverting every single thing we could find/think off).

Ultimately I would be happy if it were possible to build the documentation without building the library at all (I think that I need to disable autodoc for that which I have also tried)...

Here is the conf.py file for the repo (on branch `318` which is being built by rtd): https://github.com/Axelrod-Python/Axelrod/blob/318/docs/conf.py

Any explanation and/or pointers would be appreciated.

**Comment by drvinceknight** [comment]
I have also tried the solutions helpfully suggested at #1624.

**Comment by capcarr** [comment]
I noticed that your `setup.py` file includes matplotlib in the `install_requires` keyword. This will probably break the installation process, but have you tried building the docs without this?

**Comment by meatballs** [comment]
The last successful build (3259753) was on August 20th at commit 67491390f6edb9e91cec2e3d04e66712924fa7bb

I've now created a 'docstest' branch at that commit and triggered build 3342236. It fails with the same error we've seen since August 20th.

**Comment by meatballs** [comment]
@capcarr thanks for the suggestion. I just tried it on build #3342348, but it made no difference.

**Comment by capcarr** [comment]
@meatballs Even when specifying an empty requirements file on RTD?

**Comment by meatballs** [comment]
Aha! I removed ```install_requires``` and then used the advanced options to use virtualenv and an empty requirements.txt created in the docs folder. It built!!

**Comment by meatballs** [comment]
Is this related to commit d36ebae04b2b3b34f8ea7bc5fb35435314f53ac6 which is dated August 20th - the last time our docs built?

I can see it contains a change to ```tasks.py``` (line 312) that seems relevant here.

**Comment by gregmuellegger** [comment]
I'm not sure if the mentioned commit is source of the problems you have experienced. But cool that you were able to resolve the issue. The real problem here is that we cannot support installing custom versions of matplotlib (all the nasty compiling involved .. :disappointed:) so a build will fail if matplotlib is mentioned in a requirements file or in the `install_requires` option.
