### ISSUE TITLE
What's causing "TypeError make_toctree at ... is not JSON serializable"?

### ISSUE THREAD

**Issue by reece** [rtfd/readthedocs.org#1676]
In several projects on Read the Docs (including my own), I see variations on this error message: "TypeError make_toctree at ... is not JSON serializable".

Examples are:
https://readthedocs.org/projects/hgvs/builds/3334927/
https://readthedocs.org/projects/pyhatch/builds/3270548/
https://readthedocs.org/projects/xymath/builds/3300272/

Docs build fine locally. 

Any suggestions about how to debug this or suspicions about the cause?

(Also asked at http://stackoverflow.com/questions/32727325/)

**Comment by ericholscher** [comment]
We generate JSON output from Sphinx, using the Json Builder: http://sphinx-doc.org/builders.html#sphinx.builders.html.JSONHTMLBuilder -- Guessing that is what is happening.

**Comment by ericholscher** [comment]
We used to not fail builds because of this, however. We should be running it at the end of the build, but it is important because it's how we generate our search indexes.

**Comment by reece** [comment]
Thanks, Eric. Is there something for me (and other packages) to do to fix or debug this? I don't even know where to start given that it only happens at RTD.

Since this doesn't happen for everyone, but does happen for unrelated projects, perhaps there's a common config option that is tickling this bug?

**Comment by ericholscher** [comment]
You can do `make json` locally to run it.

**Comment by reece** [comment]
Indeed. And I can reproduce it. Investigating...

**Comment by reece** [comment]
What I know so far:
* triggered by building json with sphinxcontrib.fulltoc; building json wo/fulltoc and html w/fulltoc work fine
* the problem is that fulltoc creates a dict entry in context to override the toctree here:   
https://github.com/dreamhost/sphinxcontrib-fulltoc/blob/master/sphinxcontrib/fulltoc.py#L46
Serialization of that entry is failing.

I just found https://github.com/dreamhost/sphinxcontrib-fulltoc/issues/10.
This is unrelated to rtd, so I'll take it up there.
