### ISSUE TITLE
Version menu links are generated with a None suffix

### ISSUE THREAD

**Issue by jmcanterafonseca** [rtfd/readthedocs.org#1679]
See http://fiware-orion.readthedocs.org . 

If you go to the drop down menu which allows to choose a documentation version and select a version, the URL points to http://fiware-orion.readthedocs.org/en/0.24.0/None/ 

Obviously the 'None' prefix is incorrect and breaks the navigation.

**Comment by ericholscher** [comment]
This is a dupe of #1634 -- we're waiting on a mkdocs release.
