### ISSUE TITLE
Custom domains feature not working

### ISSUE THREAD

**Issue by Flavien** [rtfd/readthedocs.org#1687]
My domain is managed by Cloudflare. I have setup a managed CNAME from docs.openchain.org to openchain.readthedocs.org, and setup a domain on readthedocs.org:

![image](https://cloud.githubusercontent.com/assets/296540/10067265/ad2794ae-62a3-11e5-821f-981cc82d46a5.png)

When I access https://docs.openchain.org/, I get the usual error: This page does not exist yet.

**Comment by ericholscher** [comment]
This will be fixed once #1681 is merged.

**Comment by Flavien** [comment]
This works now, but the canonical URL in the page source is set to the "openchain.readthedocs.org" domain, and I can't change it to the actual vanity domain.

**Comment by ericholscher** [comment]
Looking at your docs now, this looks fixed.
