### ISSUE TITLE
Badges don't work with "protected" projects

### ISSUE THREAD

**Issue by sergiopasra** [rtfd/readthedocs.org#1690]
I was wandering why my project's badge was yellow when it was green in the dashboard. After a few days I noticed that

```
curl -I https://readthedocs.org/projects/numina/badge/?version=latest
```

Returned 

https://img.shields.io/badge/docs-unknown%20version-yellow.svg?style=flat

when my project was protected and 

https://img.shields.io/badge/docs-latest-brightgreen.svg?style=flat

when my project was public.

So, I don't know if this is the intended behavior, but if it is,  I think it should be documented.

Thanks!

**Comment by stsewd** [comment]
Hi, I wasn't able to reproduce this on my local instance or on the .org site. Is this still an issue for you?

**Comment by RichardLitt** [comment]
I am going to close this as being stale. @sergiopasra feel free to reopen if you still have this issue! Thanks for the follow up, too, @stsewd.

**Comment by bochen87** [comment]
@stsewd @RichardLitt I also have this issue with our badge
https://enway-gmbh-cleansquare-ros.readthedocs-hosted.com/en/latest/?badge=latest

**Comment by stsewd** [comment]
@bochen87 that's a project from rtd.com, this issue tracker is for rtd.org version, you can contact support there or provide a project in rtd.org with the same problem.
