### ISSUE TITLE
Theme path woes

### ISSUE THREAD

**Issue by mahmoud** [rtfd/readthedocs.org#1692]
Hey all, ran into this issue when I noticed [my docs builds][builds_link] started failing a couple days ago. I hadn't changed much in my conf.py so [I diffed the generated conf.pys][diff] from the `cat conf.py` step. The successful build is on the left. Looks like the default theme path isn't getting set anymore or something. I might be off-base on the debugging, but I figured I'd report it anyways.

[builds_link]: https://readthedocs.org/projects/boltons/builds/
[diff]: https://www.diffchecker.com/sl1lqpgc

**Comment by mahmoud** [comment]
I've tried a [a few things][history], but no luck. A bit of googling shows it [happening elsewhere lately][elsewhere], too?

[history]: https://github.com/mahmoud/boltons/commits/master/docs/conf.py
[elsewhere]: https://readthedocs.org/projects/laf-fabric/builds/3346738/

**Comment by ericholscher** [comment]
I believe this should be fixed now. I believe it was an issue with Sphinx < 1.3.

**Comment by ericholscher** [comment]
A rebuild of your docs looks good. Closing this. Sorry about that, we switched to using an installed theme, and Sphinx 1.3+ installs it automatically, but not on < 1.3.

**Comment by mahmoud** [comment]
Ah, it happens. Thank you for looking into it and resolving it within the day. :)
