### ISSUE TITLE
Subdomain redirects don't work if PRODUCTION_DOMAIN has more than 2 url parts

### ISSUE THREAD

**Issue by clarkperkins** [rtfd/readthedocs.org#1697]
If `settings.PRODUCTION_DOMAIN` has more than 2 parts in the url (i.e. `dev.readthedocs.org` instead of just `readthedocs.org`), subdomain redirects from `/` to `/en/latest/` don't work properly.  This is due to the fact that the `SubdomainMiddleware` has a hardcoded `3` for the number of url parts of the incoming domain.

**Comment by agjohnson** [comment]
Thanks for the report and fix!
