### ISSUE TITLE
Build failed on-line but works in local

### ISSUE THREAD

**Issue by fmarco76** [rtfd/readthedocs.org#1699]
Hi,

I have a problem to build my documentation. All the build fails with the following error
```
Using real prefix '/usr'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/csgf/envs/latest/bin/python
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/docs/lib/python2.7/site-packages/virtualenv.py", line 2363, in <module>
    main()
  File "/home/docs/lib/python2.7/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/home/docs/lib/python2.7/site-packages/virtualenv.py", line 994, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/home/docs/lib/python2.7/site-packages/virtualenv.py", line 1288, in install_python
    shutil.copyfile(executable, py_executable)
  File "/usr/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 26] Text file busy: '/home/docs/checkouts/readthedocs.org/user_builds/csgf/envs/latest/bin/python'
```

I have tried to build locally and it works. Additionally, I have put my repo back to last successful build but I still get the error so I am not sure it is related with my code.

Do you have any hint/idea on the reasons of the error.

The documentation is: https://readthedocs.org/projects/csgf/builds/

Cheers,
Marco

**Comment by agjohnson** [comment]
So, what is happening here is that your build processes are taking too long, or are consuming a lot of resources, and the processes are going into a sometimes zombie state, sticking around on the server. This keeps the python script open and will raise this error on subsequent builds.

You could try inspecting your documentation for cases that could be looping or running rampant and see if removing such pieces helps.

**Comment by fmarco76** [comment]
You are right about the problem. There was a loop in the code and I have fixed it. What it is not clear to me is how to kill the zombies. Any way to stop them?

**Comment by fmarco76** [comment]
I solved the problem. Wipe did not work but I have to de-activate the version and then clean it. When I put it back the building process was working properly.
Thanks

**Comment by agjohnson** [comment]
Great! I'll get on the servers and clean up any lingering issues this morning.
