### ISSUE TITLE
Protected translation linking is incorrect in built documentation

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#1703]
The issue here is that when a translation is marked as protected, the version is still listed as a possible translation. It shouldn't be returned as a translation in this case. The original issue notes projects that don't exist anymore, but this behavior still exists.

This is also yet another issue that is resolved by removing project privacy levels, so perhaps we resolve this issue in #2663 

~I see that https://docs.readthedocs.org/en/latest/index.html has links to IT and JP versions hosted at https://docs.readthedocs.org/it/latest/index.html and https://docs.readthedocs.org/jp/latest/index.html respectfully.~

~But those two pages don't backlink to RTD. Why?~

~Also, there are much more languages in https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/locale - why they are not available?~

**Comment by agjohnson** [comment]
What do you mean when you say that the translations don't backlink to RTD?

The `locale` path you linked to are the translations for the application, not our docs -- they should be available as language selectors on the dashboard pages. There is a `locale` path in our docs path as well, my guess is that the languages there aren't complete enough to link to as translations? It's something worth looking into for sure though.

**Comment by techtonik** [comment]
> What do you mean when you say that the translations don't backlink to RTD?

1. Open https://docs.readthedocs.org/en/latest/index.html
2. Go to Italian translation
3. Try to find a link back to English version

**Comment by agjohnson** [comment]
I have an `en` translation link that links to the english translation

**Comment by techtonik** [comment]
@agjohnson are you sure you're on italian page?

**Comment by agjohnson** [comment]
Indeed. Currently on `http://docs.readthedocs.org/it/latest/` and have an `en` translation link on the flyout pointing to `http://docs.readthedocs.org/en/latest/`

**Comment by agjohnson** [comment]
Oh, mystery solved. You aren't logged in, and are receiving a 404 on the footer GET request?

**Comment by techtonik** [comment]
@agjohnson I am logged into https://readthedocs.org but maybe not into https://docs.readthedocs.org This is how a flayout looks from `it` URL.

![image](https://cloud.githubusercontent.com/assets/515889/10347212/8c808ed4-6d3b-11e5-8ff5-ab8c661cd88d.png)

And this is how it looks from `en` URL.

![image](https://cloud.githubusercontent.com/assets/515889/10347269/c0e3e388-6d3b-11e5-80dc-72fd0daf21a0.png)

**Comment by agjohnson** [comment]
Yup, that's what I get when I'm logged out. I just realized the I'm an admin user though, so the privacy filtering is most likely different there.

Not sure what exactly we want to do here. Immediately, `readthedocs-it` shouldn't be protected. If a translation is marked as protected, it probably shouldn't be returned as part of the translations -- that is, it shouldn't be listed on `docs.readthedocs.org/en/latest/` as a translation. If you land on a protected translation page, it probably should be linking back to the main translation, as that version isn't protected.

**Comment by techtonik** [comment]
If translation is protected, it should not appear in listing of languages.

**Comment by stsewd** [comment]
Those translations aren't on the docs project anymore, is this issue still relevant?

**Comment by techtonik** [comment]
@stsewd if you find the commit that fixes this - that would be the best.

**Comment by agjohnson** [comment]
Issue is still relevant, the translations are indeed gone though. None of the RTD docs translations are thoroughly translated :(

**Comment by stsewd** [comment]
We have a guide for translations https://docs.readthedocs.io/en/latest/guides/manage-translations.html

**Comment by humitos** [comment]
Since the middle/long term solution is to remove privacy levels, this issue doesn't make sense anymore and won't be fixed. Moving to #2663 as @stsewd mentioned.

I'm closing it here.
