### ISSUE TITLE
404 Error?

### ISSUE THREAD

**Issue by Meow-J** [rtfd/readthedocs.org#1704]
I don't know when it started, but the pages were fine yesterday. 

I have two pages that have the same problem:
- http://mcforge-cn.readthedocs.org/
- http://learnopengl-cn.readthedocs.org/

The projects are
- https://readthedocs.org/projects/learnopengl-cn/
- https://readthedocs.org/projects/mcforge-cn/

I rebuilt the projects a few times, and all of them are succeeded, but the pages still have 404 error.

**Comment by Meow-J** [comment]
All right, I found the solution. I need to specify a index page

**Comment by gep13** [comment]
@Meow-J thanks for this! Just ran into this myself, and got it working based on your suggestion!
