### ISSUE TITLE
Error viewing the documentation after a successful compilation

### ISSUE THREAD

**Issue by frbattid** [rtfd/readthedocs.org#1706]
Hi,

This is the link to the documentation (404 not found):
http://fiware-cosmos.readthedocs.org/en/latest/

This is the compilation result:
![fiware_cosmos_compilation](https://cloud.githubusercontent.com/assets/3865056/10159177/19fe3e56-6697-11e5-8996-d8ce843ecec3.png)

This is the github repo of the project:
https://github.com/telefonicaid/fiware-cosmos

`mkdocs.yml` at `develop` branch:
https://github.com/telefonicaid/fiware-cosmos/blob/develop/mkdocs.yml

Thanks for the support!

**Comment by ericholscher** [comment]
http://fiware-cosmos.readthedocs.org/en/develop/ seems to be working for me. You likely just need to merge into your master?

**Comment by frbattid** [comment]
Yeah, it works! Despite the link to the documentation was about the latest version instead of the develop one, I tried both and no one was working for me. Anyway, it is working, so perfect. I'll close the issue. Thanks!
