### ISSUE TITLE
Project not building (Killed)

### ISSUE THREAD

**Issue by skirpichev** [rtfd/readthedocs.org#1712]
I noticed [my docs builds](https://readthedocs.org/projects/omg/builds/) started failing recently (latest ok build was [this](https://readthedocs.org/projects/omg/builds/3357698/), it's 2 days ago).

Now if I rerun my master's build (see [the log](https://readthedocs.org/projects/omg/builds/3364937/)), it shows:
```
preparing documents... done
assembling single document... install tutorial/index [...] modules/polys/wester Killed
```
Sometimes it's killed in some different place of this stage (e.g. [here](https://readthedocs.org/projects/omg/builds/3365129/)).  Few times, after writting output for some modules (e.g. modules/polys/internals [here](https://readthedocs.org/projects/omg/builds/3365084/)).

Everything builds fine locally (with sphinx v1.3.1 too).  Also documentation wasn't changed on my side, this seems to be a readthedocs.org regression.

**Comment by ericholscher** [comment]
We have just deployed a new build system that limits build time & memory. I'm guessing your build used over 500M of RAM, and was thus killed. We are just rolling this out, and trying to tune it, but we are hoping to impose reasonable build limits on projects, so that our build servers are not overwhelmed. We might raise those limits a bit for now, which would hopefully allow your build to complete.

**Comment by skirpichev** [comment]
Ok, I understand.

I tried to run build this with `ulimit -v 512000`, this indeed breaks build.  ~800Mb is enough (for html-only build - 600Mb is fine), not sure if that's ok on your side.

Anyway, I suppose this limit should be documented somewhere.  Or I miss something?

**Comment by zzzeek** [comment]
> We are just rolling this out, and trying to tune it, but we are hoping to impose reasonable build limits on projects, so that our build servers are not overwhelmed. We might raise those limits a bit for now, which would hopefully allow your build to complete. 

SQLAlchemy's builds are huge.   Do I need to start moving my docs back to my own servers?

**Comment by skirpichev** [comment]
> SQLAlchemy's builds are huge.

How much?

**Comment by zzzeek** [comment]
> How much?

the memory use is largely OS dependent and I don't have access to run "top" on RTD's servers.  timewise they can take many minutes on a less powerful server.

**Comment by skirpichev** [comment]
On Thu, Oct 01, 2015 at 08:41:10AM -0700, mike bayer wrote:
>      How much?
> 
>    the memory use is largely OS dependent

Sure, but not too much (e.g. by order of magnitude), if you are using
something similar to rtd (x86_64 linux) locally.

**Comment by zzzeek** [comment]
i run on OSX here I'd have to spin up a VM and check.

**Comment by ericholscher** [comment]
We've bumped the build limit to 1GB of memory and 20 minutes for now. This
should hopefully fix these issues, and might be a better default.

On Thu, Oct 1, 2015 at 9:17 AM, Sergey B Kirpichev <notifications@github.com
> wrote:

> On Thu, Oct 01, 2015 at 08:41:10AM -0700, mike bayer wrote:
> > How much?
> >
> > the memory use is largely OS dependent
>
> Sure, but not too much (e.g. by order of magnitude), if you are using
> something similar to rtd (x86_64 linux) locally.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1712#issuecomment-144776475>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by skirpichev** [comment]
Works for me (except from being undocumented).

Thank you very much!

**Comment by skirpichev** [comment]
@agjohnson, there is no documentation issue?

**Comment by agjohnson** [comment]
This would be a separate issue from the original issue. I've opened a new ticket #1720
