### ISSUE TITLE
Regression: pandas and traits used to be available; aren't any longer?

### ISSUE THREAD

**Issue by bpteague** [rtfd/readthedocs.org#1713]
My project, `cytoflow`, depends heavily on the scientific python ecosystem.  It is currently set to `setup.py install` to a virtualenv with the global `site-packages` available in the virtualenv.

Up until yesterday, two of the packages that my package depends on (`pandas` and `traits`) were available in the build environment.  (See, for example, https://readthedocs.org/projects/cytoflow/builds/3361883/).

Yesterday, something changed.  The build tries to collect the same packages (see for example https://readthedocs.org/projects/cytoflow/builds/3362450/), but now it's trying to build them them and failing (both rely heavily on compiled extensions).

I've tried mocking out the two in `conf.py`, but traits in particular doesn't respond well to that treatment.

More generally, is there some way to figure out precisely what the build environment is?  Which packages are available in the global packages directory and which `pip install` is going to try to get and build?

**Comment by ericholscher** [comment]
We just rolled out a new build system, and are catching up with all the dependencies. We will get this resolved by the end of the day. Sorry about that!

**Comment by agjohnson** [comment]
I pushed out a fix for this last night, installing python pandas packages at the system level on the new build images. Can you confirm this solves this issue?

**Comment by bpteague** [comment]
Fixed.  Thanks!
