### ISSUE TITLE
Regression: New failures for previously built docs

### ISSUE THREAD

**Issue by reece** [rtfd/readthedocs.org#1714]
I have been getting new failures in RTD runs. While debugging, I noticed that recently built docs no longer build. For example:

* https://readthedocs.org/projects/hgvs/builds/3323656/ -- succeeded 14 days ago (with errors for make json as discussed in another ticket)

* https://readthedocs.org/projects/hgvs/builds/3365717/ -- fails today for the same code above

It appears to me that perhaps mercurial used to be installed but is no longer available. Correct?

**Comment by agjohnson** [comment]
Confrimed, seems the new builder backends didn't pick up the correct dependencies here. I'll update the build images to include this today.

**Comment by reece** [comment]
Now builds previously failing changeset. Looks fixed to me. Thanks! Closing.

**Comment by agjohnson** [comment]
Great! Sorry, I was working on this on a train ride and didn't have time to update this ticket after. Glad it works though
