### ISSUE TITLE
Improve the documentation about domain and translation

### ISSUE THREAD

**Issue by Grummfy** [rtfd/readthedocs.org#1715]
Hello,
I find the documentation http://docs.readthedocs.org/en/latest/alternate_domains.html and http://docs.readthedocs.org/en/latest/localization.html not verry clear in the case of translation.

For me the following questions are not clear (and because I don't know how to do it I can't make pull request to fix the doc) :
* How I choose the default language to print?
* How can I make all the translation inside the same domain and having multiple project?

thanks

**Comment by agjohnson** [comment]
+1 We've made some changes to translations and domain configuration that we should definitely clarify.
