### ISSUE TITLE
all builds failing, repeatedly, for 12 hours:  "killed"

### ISSUE THREAD

**Issue by zzzeek** [rtfd/readthedocs.org#1716]
All of SQLAlchemy's builds are being "killed":

        ...
	None:None: WARNING: py:meth reference target not found: Text.columns
	None:None: WARNING: py:class reference target not found: sqlalchemy.schema.SchemaVisitor
	None:None: WARNING: py:class reference target not found: RootTransaction
	None:None: WARNING: py:meth reference target not found: Operators.collate
	None:None: WARNING: py:class reference target not found: AttributeImpl
	None:None: WARNING: py:func reference target not found: as_declarative
	None:None: WARNING: more than one target found for cross-reference u'in_': sqlalchemy.orm.interfaces.PropComparator.in_, sqlalchemy.orm.properties.RelationshipProperty.Comparator.in_, sqlalchemy.orm.properties.ColumnProperty.Comparator.in_, sqlalchemy.sql.expression.ColumnElement.in_, sqlalchemy.schema.Column.in_, sqlalchemy.sql.operators.ColumnOperators.in_, sqlalchemy.orm.attributes.QueryableAttribute.in_
	None:None: WARNING: py:func reference target not found: as_declarative
	None:None: WARNING: py:func reference target not found: orm.local
	None:None: WARNING: py:meth reference target not found: Compiler.process
	None:None: WARNING: py:mod reference target not found: dogpile_caching

	writing... Killed

https://readthedocs.org/projects/sqlalchemy/builds/3367056/
https://readthedocs.org/projects/sqlalchemy/builds/3367053/
https://readthedocs.org/projects/sqlalchemy/builds/3365790/

etc.

failures began at least 12 hours ago

I've "wiped" the builds, no luck.  

this is an urgent issue and I will be pinging on IRC to find RTD administrators to help.

**Comment by skirpichev** [comment]
See #1712

**Comment by zzzeek** [comment]
thank you, new memory limits mentioned in #1712 have resolved (for now!).
