### ISSUE TITLE
Canonical URL cannot be set to use HTTPS instead of HTTP

### ISSUE THREAD

**Issue by Flavien** [rtfd/readthedocs.org#1717]
I can see that from the latest update, the canonical URL is built from the canonical domain.

The issue is that there is no way to have the canonical URL to use HTTPS. Can we have this option?

**Comment by Flavien** [comment]
How is that progressing? We are losing out on SEO because of this.

**Comment by kakulukia** [comment]
I just found out that the link cannot be set to https .. is anyone looking into this?

**Comment by stsewd** [comment]
@kakulukia  sorry if I don't understand this, what link is this?

**Comment by kakulukia** [comment]
It’s the automatically inserted canonical link defaulting to the servers domain and or the project domain marked as canonical and if I remember it correctly it’s living inside readthedocs-include.html.tmpl 
I will recheck an Post the full path at home.

**Comment by kakulukia** [comment]
here is the problematic template
.venv/lib/python2.7/site-packages/readthedocs_ext/_templates/readthedocs-insert.html.tmpl
Its used in the default template and is always filled with an http url. Even if i enter https:// in the domains config page it gets stripped away. :/

**Comment by LeeEvans1234** [comment]
Thank you I hope to get these issues fixed so things can work for the better good cause the hub I'm trying to create is for all with minds to see and knowloge to help each other no matter how great or small the need it's like the creation story it's just there

**Comment by RichardLitt** [comment]
Thanks for the comment, @LeeEvans1234. In the future, although thanks are appreciated, try to keep comments relevant to the thread that they're in.

**Comment by kakulukia** [comment]
too bad i deleted the problematic template line yesterday so i cant test the new/found checkbox that easily :/

**Comment by stsewd** [comment]
Cannonilas urls are https, rtd run on https for *.readthedocs.io and custom domains.
