### ISSUE TITLE
Connection timeout when cloning git repo from github

### ISSUE THREAD

**Issue by gesanderson** [rtfd/readthedocs.org#1719]
Our builds have been failing since yesterday. Following error appears during pip install of requirements:

``` 
Collecting git+git://github.com/xivo-pbx/sphinx-git.git@tagtitles (from -r requirements.txt (line 1))
  Cloning git://github.com/xivo-pbx/sphinx-git.git (to tagtitles) to /tmp/pip-i9XAvV-build
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out

  Complete output from command git clone -q git://github.com/xivo-pbx/sphinx-git.git /tmp/pip-i9XAvV-build:
  
  ----------------------------------------
Command "git clone -q git://github.com/xivo-pbx/sphinx-git.git /tmp/pip-i9XAvV-build" failed with error code 128 in None
```

Link to our requirements.txt : https://github.com/xivo-pbx/xivo-doc/blob/master/requirements.txt

**Comment by agjohnson** [comment]
I believe this is a duplicate of #1718, which I've deployed a fix for. Can you confirm this resolves your issue?

**Comment by gesanderson** [comment]
Great ! I checked this morning and everything seems to be back to normal. Thank you so much for your great work on RTD :)
