### ISSUE TITLE
Unable to import renamed GitHub repository

### ISSUE THREAD

**Issue by sloria** [rtfd/readthedocs.org#1723]
I renamed my repos and want to rebuild the RTD project for it. I renamed the repo on GitHub and deleted the old project from RTD. However, when I go to import the newly-named repo, it does not show up, even after I click "Sync your GitHub projects" (the old repo still shows up, though).

This is the repo in question: https://github.com/marshmallow-code/apispec

**Comment by sloria** [comment]
I was able to do a "Manual import" of the repo, which works fine.

**Comment by agjohnson** [comment]
This sounds related to #1670, which will be resolved by #1695 when that is merged in shortly. Closing this as a duplicate
