### ISSUE TITLE
Unable to take down a build

### ISSUE THREAD

**Issue by yassineS** [rtfd/readthedocs.org#1724]
Hi, I removed the project (http://cosmos-hms.readthedocs.org/en/latest/) from the dashboard as well as the 'hook' on the github side. However the docs are still available on the link. Can you please take down?

**Comment by agjohnson** [comment]
Not sure if you solved the issue or if another admin cleared these out without updating this ticket -- seems to be removed now though. Feel free to reopen if this isn't resolved

**Comment by egafni** [comment]
I'm having the same problem at a different url :(
http://cosmos-wfm.readthedocs.org/

Would really appreciate it if you could take that url down as well
