### ISSUE TITLE
Remove project translation does not work 

### ISSUE THREAD

**Issue by mipapo** [rtfd/readthedocs.org#1725]
I accidentally added a wrong "translation" to a project. There is a delete button but if I click it:
https://readthedocs.org/dashboard/runalyze-docs/translations/delete/docs-de/
I get the error "This page does     /           ]   not exist yet.   "

**Comment by stsewd** [comment]
Are you still having this issue? I just checked on my local instance and I can delete translations.

**Comment by mipapo** [comment]
I'm not sure anymore - I don't use rtd anymore. I will close this issue

**Comment by humitos** [comment]
@mipapo thanks for the update.

Can you give us feedback on why you move out Read the Docs if you don't mind? Thanks!
