### ISSUE TITLE
Pillow issue when installing without external libraries

### ISSUE THREAD

**Issue by docapotamus** [rtfd/readthedocs.org#1729]
`ValueError: --enable-jpeg requested but jpeg not found, aborting.`

This issue has started my builds failing after upgrading to Pillow 3>.

The docs state that libjpeg and zlib need to be present. http://pillow.readthedocs.org/en/3.0.x/releasenotes/3.0.0.html#libjpeg-and-zlib-are-required-by-default.

I can not work out how to apply `--disable-libjpeg` and `--disable-zlib` myself.

Is something that can be fixed your end or is there something I need to do in my admin panel?

Thanks in advance.

**Comment by agjohnson** [comment]
Seems these dependencies are missing from the new build instances? I'll get these updates in today

**Comment by docapotamus** [comment]
Thanks @agjohnson

**Comment by agjohnson** [comment]
Confirmed it was the missing `libjpeg-dev` dependency. I'm deploying new images now, try this again in a couple hours.

**Comment by docapotamus** [comment]
@agjohnson looks to be working now. Thank you very much for your help.
