### ISSUE TITLE
Search does not link back to the project for mkdocs

### ISSUE THREAD

**Issue by janmeier** [rtfd/readthedocs.org#1733]
Original issue https://github.com/sequelize/sequelize/issues/4611

Search in itself is working fine, so I didn't want to post in the other mkdocs search related issues here - sorry if I just couldn't find the right issue.

The problem is that the search page e.g. `https://readthedocs.org//search/?q=create&check_keywords=yes&area=default&project=sequelize&version=latest&type=file` is linking to `https://readthedocs.org/en/latest/api/model/?highlight=create`, not `https://sequelize.readthedocs.org/en/latest/api/model/?highlight=create`

This happens both when searches are initiated from sequelize.readthedocs.org and from docs.sequelizejs.com

**Comment by agjohnson** [comment]
This may be related to some of the other mkdocs + search bugs we have open. We did make some recent changes to domain handling however. I'd start by double checking the domain settings for the project. I assume this is a problem with the search result page and domain resolution though.

**Comment by janmeier** [comment]
Thanks for the response - domain settings look alright to me

**Comment by agjohnson** [comment]
We deployed a new method of domain resolution a while back, it looks like this is resolved. Feel free to reopen if you are noticing issues still.
