### ISSUE TITLE
Problem with canonical domain 

### ISSUE THREAD

**Issue by mipapo** [rtfd/readthedocs.org#1734]
Maybe a support case.
I'm not sure if it's related with #1687
I have two projects. First I added to the first one (runalyze-admin-docs) the canonical domain admindocs.runalyze.com and to the second (runalyze-docs) docs.runalyze.com.
After that we decided to change the urls (runalyze-admin-docs -> docs.runalyze.com & runalyze-docs -> help.runalyze.com)

But after changing the dns records I still see on help.runalyze.com the runalze-docs and not runalyze-admin-docs.
CNAME configuration seems be right. 

When I open http://runalyze-admin-docs.readthedocs.org/ I get sometimes "502 Bad Gateway" error messages. After I try to reload the page I'm redirected to http://runalyze-admin-docs.readthedocs.org/en/latest/ (like it always should be)

Used browser:  Chrome 45.0.2454.101 on Linux

**Comment by ericholscher** [comment]
The 502 was an error with our redirect code that should now be fixed.

**Comment by ericholscher** [comment]
You might need to check the Domain (Under Project > Admin > Domains) and make sure it's pointed at the right one.

**Comment by mipapo** [comment]
The Domain section looks fine in both of the projects. The only difference is, that the domain in runalyze-docs is light gray and the domain in runalyze-admin-docs is black. 
![auswahl_066](https://cloud.githubusercontent.com/assets/2135076/10386617/ded28952-6e59-11e5-804f-b145999dfc31.png)
![auswahl_065](https://cloud.githubusercontent.com/assets/2135076/10386616/ded26ba2-6e59-11e5-9bfc-f71278133b75.png)

Just another questions: It seesm I can't spend money on https://gratipay.com/~readthedocs/ ?

**Comment by mipapo** [comment]
Seems to work now. Have you changed something?

**Comment by ericholscher** [comment]
Yea, we deployed new code to deal with this. Closing.
