### ISSUE TITLE
rtfd doesn't find index.md

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1738]
I have created a develop branch which contains a "docs" [1] directory (https://gitlab.com/saigkill/hoe-manns/tree/develop/docs). 
As you can see it contains two markdown files and one of them is called "index.md". But if i'm build the develop version of the docs i'm getting an error: http://hoe-manns.readthedocs.org/en/develop/

Why it doesn't find it?

[1] as proposed there: https://docs.readthedocs.org/en/latest/getting_started.html#in-restructuredtext

**Comment by ericholscher** [comment]
Seems to work for me?

**Comment by ericholscher** [comment]
```
-> curl -I http://hoe-manns.readthedocs.org/en/develop/
HTTP/1.1 200 OK
```

**Comment by saigkill** [comment]
Oh it looks you're right. Maybe it takes some time.
Thanks for answering. :-)
