### ISSUE TITLE
cmdclass ignored in setup.py

### ISSUE THREAD

**Issue by anarcat** [rtfd/readthedocs.org#1740]
i went through great lengths (https://github.com/borgbackup/borg/pull/262) to change our toolchain to use `setup.py` to build our docs so that we could move our documentation to readthedocs.org. unfortunately, it seems that this construct:

```python
class build_foo(Command):
     # [...]

build.sub_commands.append(('build_foo', None))

setup(cmdclass={'build_foo': build_foo})
```

is ignored by readthedocs. it seems that, at some point, RTD stopped processing those `cmdclass` items properly. Compare [this build](https://readthedocs.org/projects/borgbackup-anarcat/builds/3382963/) and [this one](https://readthedocs.org/projects/borgbackup-anarcat/builds/3382964/). The first one calls `build_ext`, while the second doesn't.

The `setup.py` file changed between the two calls but i can't figure out what made it fail, here's the version where it was actually calling the `cmdclass` bits:

http://paste.ubuntu.com/12714683

(that commit actually got rewritten, so it's gone from the history).

Here's a setup.py that doesn't call the cmdclass: https://github.com/borgbackup/borg/blob/824f9c72a2c6d7e09f5ddba7747d7d963b5bebdd/setup.py

I can't figure that out... so thanks for any input.

**Comment by agjohnson** [comment]
Does reverting to the previous commit still build properly? This issue may be attributed to the new build backends that we just rolled out, but it would be best to rule out anything inside your `setup.py` as I don't have time to delve much deeper into your issue currently.

Another option which may help you is to avoid the installation step as much as possible, and only install the packages you need to run your documentation compilation on RTD. This involves mocking out dependencies that are unused:
http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by anarcat** [comment]
well, at this point i totally hacked around the issue by overriding the `build_py` command to call my custom commands, which works, but is really wonky.

i just read the mocking stuff layer on, i am not sure it can help at this point: i am already skipping the includes as much as i can by checking the environment...

**Comment by ericholscher** [comment]
Closing this, as we're just doing a standard `python setup.py install`, and nothing special during package install.
