### ISSUE TITLE
Subprojects not available on custom domain

### ISSUE THREAD

**Issue by klings** [rtfd/readthedocs.org#1741]
I've set up http://nwebsec.readthedocs.org with a custom domain http://docs.nwebsec.com, this works as expected.

I've added two subprojects:
* http://nwebsecsessionsecurity.readthedocs.org
* http://nwebsecazurestartuptasks.readthedocs.org

The documentation builds ok and is available on those links, and also as subprojects under the NWebsec RTD address:
* http://nwebsec.readthedocs.org/projects/SessionSecurity/en/latest/
* http://nwebsec.readthedocs.org/projects/AzureStartupTasks/en/latest/

But they won't show up as projects under the custom domain? (Links from "View Docs" on project pages)
* http://docs.nwebsec.com/projects/SessionSecurity/en/latest/
* http://docs.nwebsec.com/projects/AzureStartupTasks/en/latest/

The canonical tags look ok, referring to the addresses under the custom domain.

Any help would be much appreciated.

**Comment by ericholscher** [comment]
I went ahead and forced symlinks properly here, and it should be working now. It would have resolved itself with another rebuild of the docs, but should be working now.

**Comment by klings** [comment]
Thanks for the help, it works now! For the record, I built all three projects to see if that would resolve the problem.
