### ISSUE TITLE
Etag + md5 question

### ISSUE THREAD

**Issue by Carreau** [rtfd/readthedocs.org#1743]
I'm playing with python3 conversion, and came across the following : 

I see that [here](https://github.com/rtfd/readthedocs.org/blob/f829ef0ebf93447318c93ff9ad45dfe7ed22ce98/readthedocs/projects/views/public.py#L117) the Etag is set to a `md5.new(url)` object. Shouldn't it be the `md5.new(url).hexdigest()` ? Or does django do some magic ?

Thanks.

**Comment by ericholscher** [comment]
Perhaps -- It would be great to get a test for this showing it failing, and a patch that fixes it.

**Comment by berkerpeksag** [comment]
Actually, it should use the `hashlib` module. `md5` has been deprecated since Python 2.5. However, it seems like the else branch in `_badge_return` is unused. `_badge_return` used by the `project_badge` view which passes `redirect=True` by default. I will open a pull request to simply it.
