### ISSUE TITLE
Document translation usage

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#1746]
https://docs.readthedocs.org/en/latest/localization.html

This current scheme looks weird - if you need multiple languages, you need for **each langauge**:

  1. Create Sphinx repository
  2. Create RTFD project
  3. Set appropriate language in RTFD project to set URL like `/en/latest`

And the phrase `You must commit the .mo files for Read the Docs to translate your documentation.` is the most puzzling. Why commit .mo files into separate repositories if it is possible to just define proper location in a single one?

Also, where to commit those `.mo` files and what are they is not clear.

**Comment by agjohnson** [comment]
I answered your question on where to commit in #1747 

You don't need a repo for each language, all of your translations can live in one repo. We need to set up separate projects for each translations though, which is the one thing I would like to see changed. 

Seems translations needs some more documentation at very least.

**Comment by techtonik** [comment]
The answer was:

> These files should be in the path specified in your Sphinx conf locale_dirs.

The format of this `local_dirs` is unclear.
