### ISSUE TITLE
Where to commit .mo files?

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#1747]
https://docs.readthedocs.org/en/latest/localization.html#single-project-in-another-language

This tells to commit `.mo` files. Where to commit them?

**Comment by agjohnson** [comment]
You commit the `.mo` files in your repo with your docs. These files should be in the path specified in your Sphinx conf `locale_dirs`.

**Comment by agjohnson** [comment]
Closing as duplicate of #1746
