### ISSUE TITLE
HTML docs including some - but not all - docstring automodule documentation

### ISSUE THREAD

**Issue by jagophile** [rtfd/readthedocs.org#1749]
My project (pyatomdb) has several .rst files due to having several modules. The documentation is built using sphinx, which uses automodule to pull out the various commands and their docstrings.

Offline this works fine (using sphinx-build). On readthedocs, this works fine for the PDF generation, but the html version is generating these for only 1 module (pyatomdb.atomdb), and ignoring the rest. It builds without errors, produces basic webpages for these modules, but doesn't produce any automodule output.

This is very confusing as the PDF versions are fine, online and offline.

Any assistance welcome...

**Comment by shoyer** [comment]
I'm pretty sure this is https://github.com/sphinx-doc/sphinx/issues/1822

You will need to add `sphinx==1.2.3` as a dependency to your doc build to fix this, at least until sphinx issues a bug fix release.

**Comment by jagophile** [comment]
Thank you shoyer - putting that in the requirements.txt solved everything.

**Comment by jagophile** [comment]
Sorry, for reopening this, I am now thoroughly confused. After running this with the suggested fix I initially had everything documented. But now it has vanished again. I am building with sphinx==1.2.3 in the requirements file and it seems to be running through fine (no errors at all) but it is still producing nothing from the docstrings of all but 1 module for the HTML output. But it works absolutely fine locally using sphinx.

**Comment by agjohnson** [comment]
@jagophile not finding your project on RTD, can you include a link to your project?

My guess is somehow you aren't using 1.2.3 anymore, or 1.3.1 is being given priority.

**Comment by jagophile** [comment]
Hi,
My project is atomdb.readthedocs.org.
Looking at it today, it seems to be working again. Is there a time delay between rebuilding and the docs appearing online? Or maybe my browser had cached the "wrong" pages and I wasn't reloading. Anyway, everything seems to be working as of this moment - sorry for the confusion.

**Comment by agjohnson** [comment]
Only in the case of a queue backup, perhaps. I'll close, but feel free to reopen if you notice this again.
