### ISSUE TITLE
proposed layout for rtfd repositories with translations

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#1750]
The current state of things is confusing. `gettext` LC_MESSAGES is confusing. Undefined `.pot/.pot/.mo` locations is not friendly. `gettext` is especially scary to non-technical translators.

I propose:
1. Fixed layout for all files involved in the process
2. No legacy artifacts unless really-really needed
3. rtfd.org support for building and rendering .mo files

The layout in repository:

```
locale/pot/    - the root for .pot files generated with `make gettext`
locale/de/     - the root for .po translated files in `de` language
```

`.mo` files are excluded and regenerated by rtfd.org during build
phase. URLs /de/ are automatically generated based on contents
of locale/<lang> dir.

Does that sound good?

**Comment by agjohnson** [comment]
Not sure about `.mo` file generation issue, this may be possible. I'm -1 on dictating a scheme for translation file layout though. This probably comes down to educating how to use translations and Sphinx, it isn't something we can enforce.

**Comment by techtonik** [comment]
@agjohnson it is not about changing the default mechanism (whatever it is). It is about proposing an alternative simplified workflow. The proposed scheme is just what I want to use. I am against any hardcoded schemes myself, but it should start with something actionable.

**Comment by techtonik** [comment]
What question do you need to answer for that design decision?

**Comment by agjohnson** [comment]
I think we're against dictating how any of these tools should be used. We have a number of docs on how to manage translations for your projects, including one under `guides/` that targets users making translations for their projects. This is probably a better place to help guide users.

**Comment by techtonik** [comment]
`rtfd` translations are here for the `f` sake. =)
