### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1751]
I have just one question again. My official documentation of a project
now lies inside a docs directory under my projectroot.
If i now would like to add a new translation for that project, i have to
create a new project in rtd. But can i use the same git repository for that?

Let me say:

$projectroot/docs/
$projectroot/docs/stuff-en.*
$projectroot/docs/$projectname-german
$projectroot/docs/$projectname-german/stuff-de.*
$projectroot/docs/$projectname-russian
$projectroot/docs/$projectname-russian/stuff-ru.*

Or need i for the translations a own git repository?

**Comment by agjohnson** [comment]
There shouldn't be any problems with that. You can check out what we have laid out in our `docs/` path for this. It involves a locale path in `conf.py`, with the `.po` and `.mo` files checked into those paths.

https://github.com/rtfd/readthedocs.org/tree/master/docs
