### ISSUE TITLE
rtd doesn't build pdf

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1753]
In this project http://hoe-packaging.readthedocs.org/en/latest rtd renders the index.md correctly. But for the targets html, pdf and epub it says:

Please create a /home/docs/checkouts/readthedocs.org/user_builds/hoe-packaging/checkouts/latest/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/hoe-packaging/checkouts/latest/README.rst file with your own content.

As document type i've set in the settings "Mkdocs". Do i need rst files for rendering to the other targets?

**Comment by saigkill** [comment]
Any ideas?

**Comment by agjohnson** [comment]
Correct, mkdocs does not support PDF output: http://docs.readthedocs.org/en/latest/builds.html?highlight=pdf#mkdocs

**Comment by ericholscher** [comment]
Dupe of #1635
