### ISSUE TITLE
Documentation inconsistent about where conf.py is searched

### ISSUE THREAD

**Issue by phile314** [rtfd/readthedocs.org#1754]
In "Build Process->How we build documentation->Sphinx", it is said that conf.py is only searched in the top-level directory, the "/doc" and "/docs" directory.
<pre>
We will look inside a doc or docs directory first, and then default to the top-level of your documentation.
</pre>

"FAQ->Where do I need to put my docs for RTD to find it?" says: 
<pre>
Read the Docs will crawl your project looking for a conf.py. Where it finds the conf.py, it will run sphinx-build in that directory. So as long as you only have one set of sphinx documentation in your project, it should Just Work.
</pre>

Actual behaviour seems to match the FAQ entry. I think the documentation in the "Build Process" should be updated.

**Comment by agjohnson** [comment]
Correct, the behavior described in the FAQ is the current behavior.
