### ISSUE TITLE
Include Lato Italic font

### ISSUE THREAD

**Issue by jonls** [rtfd/readthedocs.org#1755]
I was wondering if it is possible to get the Lato Italic fonts included on the generated documentation. I noticed that this has been discussed previously in issue #824 but Lato Italic does not seem to be included still. My documentation pages reference [this CSS file](https://media.readthedocs.org/css/sphinx_rtd_theme.css) which appears to only include Lato Regular and Lato Bold.

**Comment by agjohnson** [comment]
This should be moved to the theme at http://github.com/snide/sphinx_rtd_theme
