### ISSUE TITLE
Error Failed to import project

### ISSUE THREAD

**Issue by Serhioromano** [rtfd/readthedocs.org#1757]
I set up everything like it is in docs and on screencast. I use Bitbacket. I push my docs that are built locally no problems to bitbuket. It is public repo I can see source as public user. I set up Service hook as well, but even if I trigger build manually it always gives me this error 

![2015-10-14_15-04-53](https://cloud.githubusercontent.com/assets/650741/10479244/f85c9c4e-7284-11e5-8b31-5c6f4ce27fa4.png)

I read FAQ but I am not sure i understand if suggestion 

>  If you see `ImportError` messages for custom Python modules, you should enable the virtualenv feature in the Admin page of your project, which will install your project into a virtualenv, and allow you to specify a `requirements.txt` file for your project.

is correct for my case. And anyway there is not link to read about  `requirements.txt` configuration and how to configure it.

**Comment by agjohnson** [comment]
The suggestion won't help, as there is no `ImportError` thrown. This is failing on the initial checkout of your repository, which usually signifies a problem with the URL used for the project repo.

What's your project name?

**Comment by Serhioromano** [comment]
> What's your project name?

You mean in `package.json`?

ula-docs

**Comment by agjohnson** [comment]
No, you're RTD project name.

**Comment by Serhioromano** [comment]
Pardon? RTD?

**Comment by agjohnson** [comment]
Your Read the Docs project name, I can't help any further without looking at the project configuration.

**Comment by Serhioromano** [comment]
Unfortunately this issue was critical for me and I could not wait, so I use other solution now, but I wanted you to know for future customers.

**Comment by leoheck** [comment]
I am with the same problem. @Serhioromano, you didn't show your project configuration for @agjohnson help us. And, what you did to solve the problem? @agjohnson, _which file you need to see_ to help me? I am new with RTD.

**Comment by reece** [comment]
I had this problem and the cause was a typo in the repo url. It appears that "Failed to import project" is returned for failed repo pulls. Makes sense in retrospect, but a more straightforward error message would help.

**Comment by Serhioromano** [comment]
@leoheck 
> I am with the same problem. @Serhioromano, you didn't show your project configuration for @agjohnson help us

I had no longer that file by the time I was asked for it.

@leoheck 
> And, what you did to solve the problem?

I am using Mkdocs instead. Completely different solution.

**Comment by agjohnson** [comment]
@reece I need to know the name of, or link to, your project on RTD, to be able to see your configuration

**Comment by reece** [comment]
@agjohnson I should have been clearer. I had the same error as the OP, but discovered that the cause was my own typo in the URL. When I fixed the typo, everything worked fine.

In my case at least, the only outstanding issue that "Failure to import project" is not as transparent as, say, "Could not clone or update repo from https://...".

While you're at it, you might offer a help message that suggests trying on the command line and including a copy-pastable command line (e.g., "git clone https://...").

**Comment by leoheck** [comment]
Very good guys! Now you solved my problem. Thank you. I put my docs folder somewhere inide a repo and I though that I should all the path in link. I was wrong. Thank you.

**Comment by agjohnson** [comment]
@reece sorry, the above was meant to be in reply to @leoheck 

agreed the messages could be clearer for this case though. i'll leave this open in case anyone wants to grab this.
