### ISSUE TITLE
doesn't display output of last failed command 

### ISSUE THREAD

**Issue by sih4sing5hong5** [rtfd/readthedocs.org#1759]
I got `Error 'ascii' codec can't encode characters in position 103-104: ordinal not in range(128)` in my [bulid](https://readthedocs.org/projects/tai5-uan5-gian5-gi2-tsu1-liau7-khoo3/builds/3401135/).

But there were only two successful commands.

**Comment by agjohnson** [comment]
This should be displayed on a build command, this implies the error was thrown as a point were the exception wasn't caught and handled for display purposes.

**Comment by humitos** [comment]
The building link doesn't work anymore. @agjohnson is this still a problem? I think that many work was done from 2015 to nowadays regarding handling exceptions and how errors are displayed.

**Comment by agjohnson** [comment]
Agreed, not much we can do here if the build is now removed as well. We can reopen if anyone else notices this issue.
