### ISSUE TITLE
Support: organization members cannot access RTD project for their repo

### ISSUE THREAD

**Issue by aschampion** [rtfd/readthedocs.org#1763]
The owner of the [catmaid RTD project](https://readthedocs.org/projects/catmaid/), [unidesigner2000](https://readthedocs.org/profiles/unidesigner2000/) (@unidesigner on GH), is unable to access his RTD account because he cannot remember his login details or the email with which he registered in 2012. This project points to a stale branch on https://github.com/acardona/CATMAID, which has been moved to an organization at https://github.com/catmaid/CATMAID.

The current project maintainers and organization/repo owners, @tomka and myself, would like to begin using RTD again, but are unable to do so since no one can access the RTD project.

Would it be possible to either:
- Grant the organization/repo owners permissions on the RTD project (our RTD account names are the same and are linked to our GH accounts)
- Send unidesigner2000 a password reset and hope it is directed to an email address he has access to

Thanks!

**Comment by unidesigner** [comment]
I found the password. This issue can be closed. Sorry for the hassle.
