### ISSUE TITLE
"Wipe build" appears to not clean out all build artifacts

### ISSUE THREAD

**Issue by shoyer** [rtfd/readthedocs.org#1770]
In my attempt to sort out #1726, I created a new version of my project on ReadTheDocs, pointing to the same GitHub repo. I configured the project identically via the RTD admin panel.

To my surprise, I found that my test branch now builds differently -- it can successfully install a newer version of pandas than provided by global site-packages. Compare the output on the last steps of these builds:
https://readthedocs.org/projects/xray/builds/3410081/, `pandas: 0.13.1`
https://readthedocs.org/projects/xray-tmp/builds/3409819/, `pandas: 0.17.0` (this is my temporary project)

I have been faithfully wiped my build environment on this branch, and even created entirely new branches on my original project, but still it doesn't work like the new project. My only hypothesis here is that there must be some build artifacts or hidden settings that are shared across versions. Maybe RTD is caching wheel for dependencies across project versions? I'm really stumped here and would appreciate some guidance.

Thanks,
Stephan

**Comment by cheerfulstoic** [comment]
I think I'm having this issue as well.  I'm getting errors about `hidden_code_block` (which used to work, but that's another issue).  I removed all references to `hidden_code_block` from my repo and wiped many times but I keep getting the errors:

https://readthedocs.org/projects/neo4jrb/builds/3413246/

**Comment by shoyer** [comment]
Any updates here? I love ReadTheDocs, but the inability to document new releases (due to this issue) is starting to cause a significant pain point for our users.

**Comment by adler-j** [comment]
Also reporting in on this issue. Example: https://readthedocs.org/projects/odl/builds/3548135/

Wipe does not clean out all the expected files.

Is there any way to force ReadTheDocs to do as we do locally?

`make clean`
`make html` etc

**Comment by stsewd** [comment]
Hi, are you still having this issue? The build links don't work and your last builds seems successful.

**Comment by shoyer** [comment]
We switched to using conda (instead of pip) for our builds, which resolved the issue for us.

**Comment by RichardLitt** [comment]
Thanks for letting us know! Reopen this if it happens again.
