### ISSUE TITLE
ablog feeds not being published

### ISSUE THREAD

**Issue by mr-c** [rtfd/readthedocs.org#1771]
Hello,

When I build locally the feeds are created and links are inserted into the header as expected. When RTD builds the atom feeds are not created and manually changing the URL doesn't work.

Source: https://github.com/mr-c/blog
URL: http://mrc.commonwl.org

**Comment by agjohnson** [comment]
I would check your ablog version is correct in your requirements, and that there are no errors on your build output page. What's your project name? I'd need to see the output to offer any other suggestions.

**Comment by mr-c** [comment]
Thanks @agjohnson, I upgraded my requirements.txt from `ablog` to `ablog>=0.8.0`; no change

https://readthedocs.org/projects/mrc-snippets/builds/3418068/

My project name is `mrc-snippets`

**Comment by agjohnson** [comment]
Your build looks as I'd expect. We aren't doing anything different to handle ablog projects, so this is likely an ablog configuration issue. I'd suggest looking into what is actually determining whether the feed is generated in ablog

**Comment by mr-c** [comment]
@agjohnson Thank you for taking a look.

**Comment by agjohnson** [comment]
No problem, feel free to reopen this if it is indeed a difference set up by RTD.
