### ISSUE TITLE
[mkdocs] version links contain /None/ at the end

### ISSUE THREAD

**Issue by michalwski** [rtfd/readthedocs.org#1772]
I'm wondering why the specific version link (as found in the left-bottom corner here: http://mongooseim.readthedocs.org/en/latest/) contain `/None/` at the end. It leads to a non-existent page, f.e http://mongooseim.readthedocs.org/en/1.6.0/None/). What should I do to avoid this `/None/` suffix?

**Comment by agjohnson** [comment]
Hrm, this looks to be something up with the template or with page name detection. Anyone willing to look into this further, we have a vendorized theme at https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/templates/mkdocs/readthedocs

**Comment by agjohnson** [comment]
This looks to possibly be resolved in #1634 actually. Closing this as a duplicate.
