### ISSUE TITLE
Project import doesn't open import form with FF on OSX

### ISSUE THREAD

**Issue by hackebrot** [rtfd/readthedocs.org#1773]
Hi there!

I am trying to import a new project to rtfd at [Import a Repository](https://readthedocs.org/dashboard/import/). For some reason pressing named button doesn't seem to do anything. I am not getting any errors or success messages.

This would be the project I'd like to import https://github.com/hackebrot/pytest-cookies and my account is _hackebrot_. Any help is greatly appreciated. :bow:

_Thank your for your great work! I :heart: readthedocs_

**Comment by agjohnson** [comment]
Which button are you referring to? If it's what I think it is, the old javascript and css might be cached still, and just requires a refresh. If that's not it, are you receiving any javascript errors on your console when clicking the import button?

**Comment by hackebrot** [comment]
Talking about the **+** button on the very right.

![screen shot 2015-10-19 at 23 07 10](https://cloud.githubusercontent.com/assets/6024445/10591427/69b17a88-76b6-11e5-888f-263d53cc7a32.png)

Refreshing didn't seem to help and the javascript console doesn't report any errors apparently.

![screen shot 2015-10-19 at 23 14 13](https://cloud.githubusercontent.com/assets/6024445/10591574/260b4628-76b7-11e5-8d1a-d370c201cab2.png)

**Comment by agjohnson** [comment]
Ah okay, that wasn't what I thought it was then. This looks like Firefox on OSX, I've confirmed the same behavior there. This looks like a bug with the JS that submits the form.

**Comment by hackebrot** [comment]
Yeah sorry about missing out my specs. OS X 10.10.5 Firefox 41.0.2 :no_mouth:

**Comment by hackebrot** [comment]
Works just fine on Safari 9.0

**Comment by agronholm** [comment]
Firefox 42 on Ubuntu 15.10. No errors in console but pressing the button does nothing.

**Comment by str4d** [comment]
Same issue with FIrefox 47 on WIndows 7.

**Comment by str4d** [comment]
Works fine on Chrome 51.0.2704.103 m on the same Windows 7 machine.

**Comment by waveform80** [comment]
Same issue with Firefox 48 on Ubuntu 16.04 (no errors in console, the javascript event seems to be in place, but clicking the button does nothing); seems happy under Chrome 52 on the same platform.

**Comment by hackebrot** [comment]
Thank you for fixing this! 😄 👍
