### ISSUE TITLE
Silent build failure

### ISSUE THREAD

**Issue by bdarnell** [rtfd/readthedocs.org#1774]
This build didn't work: https://readthedocs.org/projects/tornado/builds/3409409/

RTD considered it a successful build, but most of the pages using autodoc came out blank due to the import errors (which are my fault). Is it possible to get the build to fail when errors like this occur so I'll get notified instead of a partial build?

**Comment by agjohnson** [comment]
We consider a build successful based on the exit code of Sphinx, which returns as normal in your case. Perhaps you wanted to enable Sphinx option `-W` to enable failure on warnings?

**Comment by bdarnell** [comment]
Yes, I think I want the `-W` option. Can that be set in RTD? There's also another warning which looks harmless and shouldn't abort the build:
```
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/user_builds/tornado/checkouts/latest/docs/_static' does not exist
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
```

**Comment by agjohnson** [comment]
Not currently, though this would be a good option that we could add to our project configuration YAML file that will be implemented with http://github.com/rtfd/readthedocs-build. More immediately, you might have luck forcing this option in your conf.py.

To get rid of the warnings above, you'll need to set a blank `html_static_path = []`. Our override of the option defaults this option to `['_static', ...]` -- not sure if there is some historical reason for that there.

**Comment by bdarnell** [comment]
I don't think `-W` can be set in the config file; it's only on the command line (as far as I can tell from the docs). 

I actually do run `sphinx-build -W` in my CI build, so I thought I was covered without this option in RTD, but my virtualenv wasn't quite set up in the same way (I ran `setup.py install` in my CI, but I didn't have the equivalent option checked in RTD until this issue happened). 

Anyway, the problem is solved now so I'll close this issue, but consider this a feature request to add the ability to set `-W`.

**Comment by agjohnson** [comment]
Yeah, looking briefly I don't see any options for configuring this in `conf.py`. I've created rtfd/readthedocs-build#7 to track this feature addition
