### ISSUE TITLE
WARNING: html_static_path entry ... does not exist

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#1776]
I noticed a 404.
http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/

This issue cropped up recently for at least 5 other Pylons Project project's documentation.
http://docs.pylonsproject.org/projects/pyramid_tm/en/latest/
http://docs.pylonsproject.org/projects/pyramid-jinja2/en/latest/
http://docs.pylonsproject.org/projects/pyramid-debugtoolbar/en/latest/
http://docs.pylonsproject.org/projects/pyramid-zcml/en/latest/
http://docs.pylonsproject.org/projects/pyramid-cookbook/en/latest/

All was working fine a few weeks ago and there had been no changes to these repos that could have caused a build to fail. After much Googling, flailing, and random guessing, I just gave up. Every build ends up with a false positive like the following.
https://readthedocs.org/projects/pyramid_tutorials/builds/3413804/

```
copying static files... WARNING: html_static_path entry u'/home/docs/checkouts/readthedocs.org/user_builds/pyramid-tutorials/checkouts/latest/_static' does not exist
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
```

Any insight would be greatly appreciated.

**Comment by tseaver** [comment]
FWIW, the following does render:

  http://pyramid-tm.readthedocs.org/en/latest/

**Comment by agjohnson** [comment]
This might be related to some recent refactoring of domains and subprojects, have you made any changes to domains recently? It might be worth double checking those, or testing the new domain admin interface.

**Comment by agjohnson** [comment]
Also, to remove the warnings, try setting `html_static_path = []` in your conf.py. We default this to include the `_static` path if it's not set.

**Comment by stevepiercy** [comment]
Thanks for the tips, @agjohnson.

I am aware of no changes in the Domains section of the Admin interface. Is there another Admin UI?
https://readthedocs.org/dashboard/pyramid_tutorials/domains/

I tried adding http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/ as the canonical domain name at the above, but got an error message:

> Domain with this Domain already exists.

In our project's [conf.py](https://github.com/Pylons/pyramid_tutorials/blob/master/conf.py#L115) we have
```
    canonical_url='http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/'
```
I wonder if that has anything to do with it?

> Also, to remove the warnings, try setting `html_static_path = []` in your conf.py. We default this to include the `_static` path if it's not set.

That was one of my [earlier attempts](https://github.com/Pylons/pyramid_tutorials/commit/75ec4fb651a639c12fd8f4fa4568a4af30b8b661) which failed, too. :disappointed:

**Comment by agjohnson** [comment]
Calling @ericholscher in on this, he's had the most experience with domains and subprojects lately.

**Comment by stevepiercy** [comment]
Another data point, the [Pyramid docs](http://docs.pylonsproject.org/projects/pyramid/en/latest/) build just fine. Pyramid is our "gold standard" for the ideal setup and configuration regarding Sphinx and RTD. That might give y'all something that works for comparison. Thanks for looking into this.

**Comment by ericholscher** [comment]
This is an issue with our handling of underscores in project slugs. The work I did likely reverted a hacky bit we were doing transforming them. _'s are illegal in subdomains, so we don't allow them anymore, but we need to migrate old projects to fix their slugs. I will plan on doing this today, and it will fix this issue. 

The main thing that needs to happen is redirects. We are already doing these redirects on subproject & subdomain URL's, we just need to add them to the actual project pages on RTD.org, and it should be seamless.

**Comment by stevepiercy** [comment]
Thanks, @ericholscher, looks like those 6 projects are back. Closing this issue as resolved.

In this scenario, it was actually a Good Thing™ that the 404 occurred without a redirect. I might not have noticed with a redirect, depending on implementation.

**Comment by chigaki** [comment]
chmod 777 /home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static

**Comment by ale5000-git** [comment]
I get this `copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist`.

How can be avoided?

**Comment by Ewan82** [comment]
I have the same issue as @ale5000-git , is there a work around here?

**Comment by niuzhenguo** [comment]
I got the same issue here http://mogan.readthedocs.io/projects/api-ref/en/latest/v1/index.html

**Comment by ale5000-git** [comment]
@stevepiercy: Could you please reopen the issue?

**Comment by stevepiercy** [comment]
@ale5000-git It's up to the maintainers. Ping @agjohnson for triage, or open a new issue, referencing this one.
