### ISSUE TITLE
Issue deleting docs

### ISSUE THREAD

**Issue by vedtopkar** [rtfd/readthedocs.org#1777]
Hi there,

I know that you are working on functionality to delete docs from the admin panel, but I need to have these docs: https://guideseq.readthedocs.org/en/latest/ taken down, as it is confusing our users.

Thanks!
Ved

**Comment by vedtopkar** [comment]
Would like to bump this up. Sorry for the inconvenience, would really like this taken down as soon as possible. Thanks!

**Comment by stsewd** [comment]
Hi, this functionality is now implemented, if you are the project owner you can delete your project/docs here https://readthedocs.org/dashboard/guidesec/edit/ (at the bottom)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
