### ISSUE TITLE
Project alias gives 404

### ISSUE THREAD

**Issue by Luthaf** [rtfd/readthedocs.org#1781]
I have a main project, [chemfiles](http://readthedocs.org/projects/chemfiles/). I also have another project called chemfiles-python.

When I add chemfiles-python as a subproject for chemfiles, **with the python alias**, the proposed URL in the admin view is http://chemfiles.readthedocs.org/projects/python/, which leads to a 404 error. 

The http://chemfiles.readthedocs.org/projects/chemfiles-python/ URL leads to the documentation.

What was expected: the `http://chemfiles.readthedocs.org/projects/python/` URL should work.

**Comment by agjohnson** [comment]
The above URL works for me as expected. Perhaps the project was being rebuilt when you attempted the alias?

**Comment by Luthaf** [comment]
OK, so this one works now, but http://chemfiles.readthedocs.org/projects/fortran/en/latest/ and http://chemfiles.readthedocs.org/projects/julia/en/latest/ do not ... (The corresponding http://chemfiles.readthedocs.org/projects/chemfiles-fortran/en/latest/ and http://chemfiles.readthedocs.org/projects/chemfiles-julia/en/latest/ do).

I just clicked on "Compile a new version" to rebuild the latest version of the doc, and I still get this error. Is there any post-processing delay here ?

**Comment by Luthaf** [comment]
Some more investigation: the http://chemfiles.readthedocs.org/projects/fortran/ link leads to a 404, but adding `/en/latest/` leads to the correct place (i.e. using http://chemfiles.readthedocs.org/projects/fortran/en/latest/)

So it might be missing a redirection to `/<lang>/<version>`

**Comment by agjohnson** [comment]
Closing this, these projects seem to lead to 404s now.
