### ISSUE TITLE
Readthedocs just renders index.rst

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1782]
I have inside a repository a directory "docs" with two rst files in it: https://gitlab.com/saigkill/hoe-manns/tree/develop/docs.
If i'm building the docs from that develop branch it builds the docs at http://hoe-manns.readthedocs.org/en/develop. 
But there is only the index.rst available, but not the behind-the-scene.rst.

But where's the trap? Have i missed anything? As builder i'm using the default Sphinx builder,

**Comment by agjohnson** [comment]
The file is built:
http://hoe-manns.readthedocs.org/en/develop/behind-the-scene.html

But seems you aren't linking the file at all, you'll need to mention the file in a `toctree` directive in `index.rst`.

Closing as this isn't a RTD issue.
