### ISSUE TITLE
Project Disabled

### ISSUE THREAD

**Issue by naellis89** [rtfd/readthedocs.org#1786]
My project was disabled for excessive resource use.  This is an error, I wasn't trying to do anything bad, I was just debugging an issue with the builds causing them to hang.  This required building a lot, and more than a few building processes hanging for long periods of time (> 1 hour).  The issue is resolved, and I will no longer be using nearly as many resources.  Please re-enable my project.

https://readthedocs.org/projects/invoca-developer-portal/

**Comment by ericholscher** [comment]
Should be fixed.
