### ISSUE TITLE
Trouble deleting docs

### ISSUE THREAD

**Issue by nicksagona** [rtfd/readthedocs.org#1787]
Hello, I've seen similar issues posted regarding the deleted of old document projects. I'm having an issue with an old project (that I've deleted) still showing up under the CNAME pointer (instead of pointing to the new project)

The project that needs to be permanently deleted is:
http://pop-php-framework-documentation.readthedocs.org/en/latest/

Thanks.

**Comment by ericholscher** [comment]
This is a 404.
