### ISSUE TITLE
Automatic linking

### ISSUE THREAD

**Issue by saigkill** [rtfd/readthedocs.org#1789]
I'm having a md file there: https://gitlab.com/saigkill/hoe-manns/blob/master/docs/index.md. I'm creating the link with that code:

A deeper insight is possible there: [Behind the scene](behind-the-scene).

After building the master branch (http://hoe-manns.readthedocs.org/en/master/home/) rftd creates a link to: http://hoe-manns.readthedocs.org/en/master/behind-the-scene, and it works.

For the develop branch i'm converted it to rst. That builds http://hoe-manns.readthedocs.org/en/develop/.
That build creates also a link to: http://hoe-manns.readthedocs.org/en/develop/behind-the-scene, but after clickin on it, it doesn't work. But it's available under: http://hoe-manns.readthedocs.org/en/develop/behind-the-scene.html.

Is it possible to tell rtd that it builds a http://hoe-manns.readthedocs.org/en/master/behind-the-scene or it searches http://hoe-manns.readthedocs.org/en/develop/behind-the-scene.html too by accessing via Web Interface?

**Comment by agjohnson** [comment]
It looks like your linking syntax is incorrect. You are telling sphinx to link to `behind_the_scene`, so it is. You should look either use the `:doc:` reference if you are referencing another document, or one of the various methods to link to section headings.

More info here: http://sphinx-doc.org/markup/inline.html#cross-referencing-syntax

Closing this, as this isn't an issue with read the docs.
