### ISSUE TITLE
Can not modify settings of my projects

### ISSUE THREAD

**Issue by seisman** [rtfd/readthedocs.org#1791]
I created two projects one year ago, but now I can not see them in my dashboard. My dashboard looks like this:
![selection_003](https://cloud.githubusercontent.com/assets/3974108/10727680/a335f472-7c16-11e5-85f8-d38d87972842.png)

Howerer, when I try `Import a Project`, it tells me that `The repository has already been imported.`
![selection_001](https://cloud.githubusercontent.com/assets/3974108/10727444/f1530174-7c14-11e5-9724-5264f5ce5ade.png)
![selection_002](https://cloud.githubusercontent.com/assets/3974108/10727445/f175ce5c-7c14-11e5-9080-f1b728b80068.png)

It seems that these two projects does not belong be me anymore. Can you help me get them back to my dashboard? Or just delete them so that I can import them?

The two projects are: 
1. http://gmt5-docs.rtfd.org/
2. http://htwm.rtfd.org

**Comment by agjohnson** [comment]
These projects are under (I'm assuming) one of your accounts: https://readthedocs.org/profiles/SeisMan/

Do you still have access to that account?

**Comment by seisman** [comment]
Yes, I have access to this account. I didn't realize that I have two accounts. 

Is it possible to delete one of the two accounts? I can't find the 'delete account' option on admin panel.

**Comment by ericholscher** [comment]
Sadly not. #1408 covers this.
