### ISSUE TITLE
password 'reset it' doesn't work

### ISSUE THREAD

**Issue by revesansparole** [rtfd/readthedocs.org#1792]
Username: revesansparole

I tried to reset my password on page: https://readthedocs.org/accounts/password/reset/
Never received confirmation email. Can't find it even in my spam box.

sorry for the inconvenience, how can I solve it?

Thanks

**Comment by mriffle** [comment]
Can confirm, this is also happening on my account.

**Comment by revesansparole** [comment]
Seems to be working this morning, thanks
