### ISSUE TITLE
Virtualenv cannot install freetype and png

### ISSUE THREAD

**Issue by dschult** [rtfd/readthedocs.org#1795]
It looks like my virtualenv on readthedocs is not able to load matplotlib.
The [build errors](https://readthedocs.org/projects/dschult-networkx/builds/) show an error getting freetype and png.

The same requirements.txt file works in the networkx project but doesn't seem to work in this dschult-networkx project. Do I have an advanced setting wrong? Am I getting the wrong environment?

**Comment by agjohnson** [comment]
You can try installing using system level packages instead, this should use the prebuilt libraries.

**Comment by dschult** [comment]
How do I do that? On my own machine I can use a ```--system-site-packages``` virtual environment. Is there an "advanced setting" for that on readthedocs?
Thanks!

**Comment by dschult** [comment]
Found it....  sorry for thr trouble and Thanks Very Much for the great software and platform!!
