### ISSUE TITLE
[Question] Can you add Support for Gitter Sidecar

### ISSUE THREAD

**Issue by gep13** [rtfd/readthedocs.org#1797]
I don't know if you saw this or not, but Gitter have just announced Sidecar

https://sidecar.gitter.im/

Would it be possible to add support for this into readthedocs, so that I could show the Gitter sidecar on my documentation site?

I am seen this already added into two main sites that I contribute to:

https://chocolatey.org/
http://cakebuild.net/

and I think it is a great addition.

**Comment by agjohnson** [comment]
I'd like to see more integration points like this, but this is outside the focus of the core team's roadmap for the foreseeable future. I could see implementing a base for service integrations some point soon-ish, though.

We likely won't have time to pick this up any time soon, marking this community support if anyone would like to support this. We're happy to give anyone direction on this if so.

**Comment by gep13** [comment]
Thanks for getting back to me!

Yip, totally understand.  I just thought it would be a nice touch.  I am a complete noob at RTD's, only just started using it in the last week, (loving it so far), so wouldn't know where to get started in terms of adding this in, but happy to help where/when I can.

**Comment by drasko** [comment]
+1 for Gitter Sidecar. It's awesome to have people instant access to your project's community chat.

**Comment by agjohnson** [comment]
Closing this due to lack of interest. I don't think this is an integration we'd focus core development on. Feel free to ask for assignment if you're interested in developing this.
