### ISSUE TITLE
There was an error with your request: CSRF Failed: CSRF token missing or incorrect.

### ISSUE THREAD

**Issue by evert** [rtfd/readthedocs.org#1809]
Getting the following error when trying to add a new project:

    There was an error with your request: CSRF Failed: CSRF token missing or incorrect.

This happens when I'm 'refreshing my accounts'. None of my repositories are found. I have quite a few =)

This is with Firefox 42 on Kubuntu 15.10.

**Comment by agjohnson** [comment]
This is most likely caused by #1805

**Comment by averagehat** [comment]
Is there a workaround?

**Comment by markotom** [comment]
This error is somehow frustrating, but thanks in advance for your great work!

**Comment by neuromusic** [comment]
I'm having the same issue

**Comment by averagehat** [comment]
In case anyone misses it, you can still import projects using the "import manually" button.

**Comment by LulzAugusto** [comment]
Same issue here. 

@agjohnson the PR went to production?

**Comment by agjohnson** [comment]
there is no PR on this bug, i have not had time to address this.

**Comment by orome** [comment]
Same issue here.

In the meantime, is manual the only way to proceed?

**Comment by agjohnson** [comment]
@orome for now, yes, manual should still work. i haven't had any spare time recently to address some of these outstanding bugs. I'm poking at some now tough.

And yes, the github import is what allows us  to establish the required webhook. That will need to be added in the Github project admin for now as well.

**Comment by orome** [comment]
@agjohnson — Cool. So at least its a one-time only (per repo) initialization thing, correct?

**Comment by agjohnson** [comment]
Yup. Though I just deployed a hotfix for this, changes are at #1841. I don't get the CSRF warning anymore.

**Comment by orome** [comment]
@agjohnson — Hmmm. Builds are not triggering for me. I need to do them manually. Any ideas why?
