### ISSUE TITLE
Build failed with mysterious error messages 

### ISSUE THREAD

**Issue by talhaham** [rtfd/readthedocs.org#1811]
As part of the FIWARE project, I try to publish our MD docs in read the docs.
The build fails with error messages that I do not understand.

my repo:  https://github.com/ishkin/Proton
my mkdocs file:  https://github.com/ishkin/Proton/blob/master/mkdocs.yml
my failed build: https://readthedocs.org/projects/proactive-technology-online/builds/3467156/

Any clue?

Thanks!
Tali

**Comment by talhaham** [comment]
Here are the build error messages:

python /home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/bin/mkdocs build --clean --site-dir _build/html --theme readthedocs

/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:86: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:100: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:125: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:145: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:176: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py:194: Warning: Click detected the use of the unicode_literals __future__ import.  This is heavily discouraged because it can introduce subtle bugs in your code.  You should instead use explicit u"" literals for your unicode strings.  For more information see http://click.pocoo.org/python3/
  @common_options
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/checkouts/latest/_build/html 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/cli.py", line 134, in build_command
    ), clean_site_dir=clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/build.py", line 296, in build
    utils.copy_media_files(config['docs_dir'], config['site_dir'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 121, in copy_media_files
    for (source_dir, dirnames, filenames) in os.walk(from_dir):
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/lib/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/lib/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/home/docs/checkouts/readthedocs.org/user_builds/proactive-technology-online/envs/latest/lib/python2.7/posixpath.py", line 80, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 16: ordinal not in range(128)

**Comment by agjohnson** [comment]
Seems to be a MkDocs issue handling unicode characters. Are you getting this problem locally using the latest mkdocs release? If so, probably worth opening this issue against mkdocs.

**Comment by talhaham** [comment]
I'm not following you. I just activate the build in readthedocs (click the button). Above the button, the selected build version is latest

**Comment by agjohnson** [comment]
Assuming you have the latest mkdocs release installed on your system, you should be able to generate you docs. I would assume you hit the same problem as above, as this seems to be an issue with mkdocs parsing the configuration file or something.

**Comment by talhaham** [comment]
Do I need to have something installed on my system?
I thought I just need to activate the build through the readthedocs site,
that has link to the git repository that has the mkdocs.yml file. Are you
sure I need to install something? What and where?
Thanks

**Comment by agjohnson** [comment]
You should read these docs: http://mkdocs.readthedocs.org/en/stable/

**Comment by talhaham** [comment]
Thank you for the link.
I guess I don't understand the basic. 
I already have my documentation in md format, with mkdocs.yml in the github repository. 
What I need to generate? Should I put the generated in my github as well?
I was under the assumption that after I have my docs and yml, the read the docs on line build does the building. Am I wrong?

**Comment by agjohnson** [comment]
mkdocs is the building backend in your case. you can test that locally.

**Comment by talhaham** [comment]
The problem was that some of the files in the github sub tree had spaces in their file name
