### ISSUE TITLE
Invalid symlinks under the media folder

### ISSUE THREAD

**Issue by selimt** [rtfd/readthedocs.org#1813]
Hi, I am installing a readthedocs server into one of our local VMs running CentOS 7.1 and I ran into a problem with the themes. I followed the instructions here:

http://read-the-docs.readthedocs.org/en/latest/install.html

And when I tried building the test projects, I noticed that the sphinx_rtd_theme was not being used. Then I discovered that some symlinks under the media folder are pointing to invalid targets:

/opt/rtd/checkouts/readthedocs.org/media:
fonts -> static/core/font/

/opt/rtd/checkouts/readthedocs.org/media/css
badge_only.css -> ../static/core/css/badge_only.css
sphinx_rtd_theme.css -> ../static/core/css/theme.css

/opt/rtd/checkouts/readthedocs.org/media/font
fontawesome_webfont.eot -> ../static/core/font/fontawesome-webfont.eot
fontawesome_webfont.svg -> ../static/core/font/fontawesome-webfont.svg
fontawesome_webfont.ttf -> ../static/core/font/fontawesome-webfont.ttf
fontawesome_webfont.woff -> ../static/core/font/fontawesome-webfont.woff

There is no "static" folder under media. I  have the following:
css
font
fonts
htmlzip
humans.txt
images
javascript
json
lib
readthedocsbranding.ai
readthedocsbranding.jpg
robots.txt

Did I miss a step during installation?

Thanks.
-Selim

**Comment by agjohnson** [comment]
Yes, you need to run static collection to grab the files in the `static/` path.

**Comment by selimt** [comment]
Yes, that fixed it! I couldn't find this step in the install instructions. Could you please make sure it gets added there?

Thanks
-Selim

**Comment by agjohnson** [comment]
I'd be glad to have this contribution, our docs are under `/docs/` in this repository.
