### ISSUE TITLE
Creating a Supervisord for RTD

### ISSUE THREAD

**Issue by jetheurer** [rtfd/readthedocs.org#1815]
I can access RTD if I use `./checkouts/readthedocs.org/manage.py runserver 0.0.0.0:8000`  However, if I reboot the server, I'll need to run this command again.  How can I have RTD start on boot-up?

Bigger picture, I'd like to use the VMs ip address when accessing this page because URLs like http://my_libarary.ip_address:8000

**Comment by agjohnson** [comment]
Gunicorn or another server works. This is an infrastructure decision that isn't related to RTD though, closing as it isn't an issue with RTD.

**Comment by REWStevenBarre** [comment]
As someone who knows nothing about running a python web app (I use apache/php) can you point me to where I can find some info about howto use Gunicorn with RTD?
