### ISSUE TITLE
Container id can exceed length allowed for hostnames

### ISSUE THREAD

**Issue by romgar** [rtfd/readthedocs.org#1818]
I want to generate for the first time some documentation for my project https://github.com/romgar/django-dirtyfields.
I have used `sphinx` to generate this documentation locally and it works as expected, but after configuring my readthedocs account to build it on every push, I have this error:
```Build exited due to unknown error: unable to sethostname "version-initialise_proper_documentation-of-django-dirtyfields-1764795": invalid argument``` (https://readthedocs.org/projects/django-dirtyfields/builds/3484477/)

I have probably missed something, but can't manage to find the problem. Anybody has some ideas ?

**Comment by agjohnson** [comment]
Looks like this is a problem with our slugging and what docker expects for container names.

**Comment by romgar** [comment]
It seems that the branch name length is the problem. I have tried others branches with a shorter name, and everything runs fine !
