### ISSUE TITLE
Version URLs lead to a different RTFD project of mine

### ISSUE THREAD

**Issue by nicolaiarocci** [rtfd/readthedocs.org#1819]
I have this documentation at https://cerberus.readthedocs.org/en/latest/. If I go to the flyout and try to navigate to either versions, they all link to another project I have on rtfd (eve.readthedocs.org). On my project Overview page the links are fine (cerberus.readthedocs.org) and I [cannot try to reset them](https://read-the-docs.readthedocs.org/en/latest/faq.html#how-do-i-change-my-slug-the-url-your-docs-are-served-at) anyway.

I tried creating a new test project (c3.readthedocs.org) from the same github repo, and there the version links are fine. So I could probably delete the previous project and create a new one with the same name to get back my working links, but I find this to be a really weird behaviour and I thought I would report it. Also I was wondering if there is a way to apply a fix without having to delete and re-create the project (I also have a custom domain associated with it, and the test project can't use it so I'm a little hesitant since I'm not 100% sure it will all work out well).

**Comment by tterrag1098** [comment]
This may be the same as (or related to) my issue.

https://readthedocs.org/projects/mcforge-cn/ is a unique project from a third party, however clicking the "latest" build on the main page of my project (mcforge) takes me to http://mcforge-cn.readthedocs.org/en/latest/
which contains my latest code.

What could be causing this strange linkage of different projects is beyond me, but it is a very serious issues as people being linked to our docs aren't getting the most recent version.

**Comment by nicolaiarocci** [comment]
I solved by deleting the project on the readthedocs site and re-importing the repo from github.
