### ISSUE TITLE
nbconvert.preprocessors.ExecutePreprocessor() causes NoSuchKernel exception

### ISSUE THREAD

**Issue by mgeier** [rtfd/readthedocs.org#1827]
I gather (from the successfully closed issues #1511, #1498 and #1489) that IPython and nbconvert are installed in a quite recent version on readthedocs.org, which is great!

However, when I try to use `nbconvert.preprocessors.ExecutePreprocessor()` (which should use a plain old IPython kernel), I get a `NoSuchKernel` exception.

This is one of my failed build attempts: http://readthedocs.org/projects/sfs/builds/3498275/

I have `ipython[nbconvert,nbformat]` in my `requirements.txt`and I have both "Install your project inside a virtualenv using setup.py install" and "Give the virtual environment access to the global site-packages dir" switched on. And I've kept the default CPython 2.x, if that matters.

What am I doing wrong?
Do I have to install further packages?

**Comment by mgeier** [comment]
OK, I think I know now what's the problem:
I was running Python 2.x on readthedocs, but the notebook I was converting was using IPython 3.

Strangely, the `NoSuchKernel` exception didn't provide any details, in retrospect I would have expected something like `NoSuchKernel: 'python3'`.

Anyway, is there a way to install packages for Python 3 if Python 2.x is selected in the readthedocs settings?
Or vice versa?

For now I'm OK with manually making sure that I use only one and the same version, but probably there is a non-complicated general solution for that?

**Comment by agjohnson** [comment]
No, i don't believe that is a possibility, at least not with our configuration. We don't make any distinction during installation whether your requirements are for py2/3. We would also need to possibly create a python3 virtualenv on top of the py2 virtualenv. Are you able to just use a py3 virtualenv?

**Comment by mgeier** [comment]
Yes, thanks, I'm totally fine with using Python 3 for both the virtualenv and the notebooks.

I just wanted to ask if there is probably a *simple* solution which I didn't know of.

I'm closing this ...
