### ISSUE TITLE
Spam on readthedocs.org

### ISSUE THREAD

**Issue by mame98** [rtfd/readthedocs.org#1828]
Today I noticed a lot of 'projects' on the startpage without any documentations build, but only offering links to websites where you can watch movies for free...
I am not sure if this is the right way of reporting, but I had no better idea...

I made a few screenshots:

## Example 'Project'
![spam_rtd2](https://cloud.githubusercontent.com/assets/6823756/11310871/8e035166-8fcc-11e5-844d-c69e793cea38.PNG)
## Recent Page
![spam_rtd](https://cloud.githubusercontent.com/assets/6823756/11310965/215d7284-8fcd-11e5-9ac8-a205a6b6682a.PNG)
## jogonda's Profile
![spam_rtd3](https://cloud.githubusercontent.com/assets/6823756/11311000/56108a70-8fcd-11e5-94a7-7db0cfd356f7.PNG)

Everything was created by an account called 'jogonda' (https://readthedocs.org/profiles/jogonda/). On this account are many projects, but only one with documentation (which looks like a demo site..). The rest are, more than 100 (I think) 'empty' projects, only containing links to probably illegal website, offering free movies...

**Comment by agjohnson** [comment]
This is why we can't have nice things :(

Thanks for the report! Looks like we'll have to play cleanup.

**Comment by mame98** [comment]
No problem :) good luck with the cleanup!

**Comment by mame98** [comment]
Sadly I found another user who is publishing links to free movies...
![spam_rtd](https://cloud.githubusercontent.com/assets/6823756/11318512/9171ec7a-9055-11e5-8828-73e85374e9b1.png)

**Comment by agjohnson** [comment]
@mame98 thanks once again for the heads up! :bow:

The absolute last thing we need to waste our development time on is fighting referral spam, it's quite depressing. I've done a deep cleanup for now, it's just going to come back though ;_;

Seems we need a flagging system at very least

**Comment by mame98** [comment]
Yes, a flagging System should be good...
I would also suggest, that projects which have no available documentation, should not be visible for public... So it would be much more difficult to create spam...

**Comment by agjohnson** [comment]
We're already considering some changes there. Requiring builds won't work for very long, unfortunately, as some projects were already targeting existing repositories. 

Developing flagging is a waste of our development time, as there are many *useful* features that we would rather be allocating our time towards.

We will likely just remove the project listing on the homepage. None of these pages are indexed by Google mind you, so it's not like there is much incentive to spamming referral spam anyways. *shrug*

I'll close this issue for now, feel free drop by our IRC channel -- `#readthedocs` on freenode -- if you come across any others, or feel free to open a new issue.
