### ISSUE TITLE
github webhook is failing, not enough information to debug

### ISSUE THREAD

**Issue by reece** [rtfd/readthedocs.org#1831]
I'm a member of the GA4GH team. We are trying to setup RTD to build our docs at https://ga4gh-schemas.readthedocs.org/en/latest/. 

I first used my personal github repo, reece/schemas, to set this up. That worked fine.

I then attempted to transition the RTD project to watch the official repo, ga4gh/schemas. When I do that, I can force build the project (under the RTD build tab) and I can trigger it with curl, but the new webhook on the ga4gh/schemas repo does NOT trigger a build and the github "test service" button does not work.

I've tried the migration twice with extra care regarding spelling. Both attempts failed.

Do you you have any tips for debugging webhook failures (other than curl)?

**Comment by reece** [comment]
Maybe this will help debugging at RTD:

At apx Mon Nov 23 06:27:00 UTC 2015, I triggered a build using the github "test service button" with the project configured against reece/schemas. That worked fine.
I reconfigured the project github URL for ga4gh/schemas and added a webhook by 06:29, and attempted several tests. All failed.

My hope in providing this is for you to be able to extract github webhook attempts for this time period.

**Comment by agjohnson** [comment]
@reece This sounds like the lookup on the Github webhook is failing. Can you check that the repo url set up in the RTD project matches the Github https url exactly -- that is, matches case/etc as well.

**Comment by reece** [comment]
Hi Anthony-

I think I figured out what happened.

The main problem was that we had a mistaken branch, "f242434e", on master.
That meant that the github service test created a payload with that branch
name. We weren't building docs on that branch, of course. The nice folks at
github fetched this http reply from RTD:

"(URL Build) Not Building: github.com/ga4gh/schemas [f242434e]"


They also said that reporting webhook replies was on the wishlist.

I'll close the ticket.  Thanks for your help.

-Reece
