### ISSUE TITLE
Cannot change documentation type

### ISSUE THREAD

**Issue by SamMarkowitz** [rtfd/readthedocs.org#1832]
Attempting to change documentation type from Sphinx to Mkdocs does not work. Leads to the fail whale:

```
         .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

**Comment by pmacosta** [comment]
I get the fail whale whenever I try to submit any change in the "Settings" and "Advanced Settings" tabs of the "Admin" page.

**Comment by rmk135** [comment]
+1 about @pmacosta story, #1834 is the same from my side (might be a duplicate)

**Comment by agjohnson** [comment]
I believe the underlying cause of this is the same as #1835. I've deploy a fix, can you confirm this resolves your issue?

**Comment by pmacosta** [comment]
Yes! Changing settings now works again for me and I was able to build the
documentation. Thanks!!!

**Comment by SamMarkowitz** [comment]
Works for me too. Thanks.
