### ISSUE TITLE
Can't submit settings changes

### ISSUE THREAD

**Issue by rmk135** [rtfd/readthedocs.org#1834]
Hey there,

I faced a problem, that I can't save settings changes on https://readthedocs.org/ 
Here is my lib's account on rtd - https://readthedocs.org/projects/dependency-injector/

Steps to reproduce:
1. Go to https://readthedocs.org/dashboard/dependency-injector/edit/
2. Press "submit" button

Expected results:
1. Get settings page with updated values

Actual results:
1. Get page with message: "Fail.  Check back in a bit!"
2. Settings values are not updated

Can someone take a look?

Thanks

**Comment by agjohnson** [comment]
Think this might be related to #1835 and resolved by deployed hotfix with changes at #1839. Can you confirm?

**Comment by rmk135** [comment]
Hey @agjohnson,

I've just tried and it works well now!

Thanks a lot,
Roman
