### ISSUE TITLE
Can not import new project

### ISSUE THREAD

**Issue by revesansparole** [rtfd/readthedocs.org#1835]
I've been trying for the past few days to import a new repository but it's not working.

Can not refresh my packages similar to #1809
Trying to use the "manual import" button but got the fail whale (like  #1832).
Tried to clean my browser (firefox) but nothing changed.

Anything I need to do?

**Comment by Fizzadar** [comment]
I'm also getting the fail whale when importing new projects.

**Comment by borsna** [comment]
I have the same problem, manual import does not work.

**Comment by steffenbrem** [comment]
I also cannot import a new project, tried a lot of different repositories, none are working. Always getting the message: `Fail.  Check back in a bit!`.

**Comment by rmk135** [comment]
+1

**Comment by agjohnson** [comment]
Sorry, I think this was due to some users not having profiles. I've deployed a potential hotfix, with changes at #1839. Can anyone confirm?

**Comment by Fizzadar** [comment]
@agjohnson now working for me :)!

**Comment by agjohnson** [comment]
Marking this as closed, feel free to reopen if that change didn't resolve the issue.

**Comment by revesansparole** [comment]
It is working fine now, thank you
