### ISSUE TITLE
Renamed repo, can't add new project

### ISSUE THREAD

**Issue by vsoch** [rtfd/readthedocs.org#1836]
We recently renamed our organization, and although I've checked that read the docs is authorized (both from my highest level of settings and the individual repo settings) I get the "fail whale" every time I try to add a link to the repo. I thought it might have something to do with readthe docs caching the old repo path, and then github saving the old redirect link, so the error is because it thinks I'm trying to create docs for something that already exists. Help would be greatly appreciated - we can host our own docs, but the automatic generation is much preferred! Repo is here

      https://github.com/expfactory/expfactory-python

and it used to be called

      https://github.com/psiturk/psiturk-python

**Comment by agjohnson** [comment]
This might be related to #1834, does the deployed fix resolve this issue as well?

**Comment by vsoch** [comment]
Success! Yes the organization had one user with pending join, and so I removed the invitation (and perhaps it was just the fix above) but everything is [up and running](http://expfactory.readthedocs.org/en/latest/)! Huge thanks for your help!

**Comment by agjohnson** [comment]
Great, glad that worked!
