### ISSUE TITLE
RTD theme templating

### ISSUE THREAD

**Issue by ivankravets** [rtfd/readthedocs.org#1837]
![screen shot 2015-11-27 at 01 17 09](https://cloud.githubusercontent.com/assets/1760209/11431621/a7a30d96-94a4-11e5-950a-f15ed798c4b8.png)
How to enable templating for RTD theme on the RTD server? It works locally for me. Here is source code https://github.com/platformio/platformio/commit/bf9c9b8985a9f54d322a3938d19aa5c3590fd985

P.S: I found this doc http://docs.readthedocs.org/en/latest/custom_installs/customization.html and the answer https://github.com/rtfd/readthedocs.org/issues/1721 that is doesn't work.

Thanks in advance!

**Comment by ivankravets** [comment]
Resolved in other way...

**Comment by mhils** [comment]
We have the same issue - any pointers how you fixed this? :smiley:
