### ISSUE TITLE
Project page shows "Python" instead of "Fire Framework"

### ISSUE THREAD

**Issue by jayjaybillings** [rtfd/readthedocs.org#1838]
The project page for one of my projects still shows "Python." I'm not sure how a change this. It should say "Fire Framework."

http://fire-framework.readthedocs.org/en/latest/

Any suggestions are greatly appreciated. This was the only issue tracker I could find, so I figured it was the right place.

**Comment by agjohnson** [comment]
I believe this is due to the theme setting the default of `Python` in the template, where it expects the conf.py to have a project name. It seems your conf.py doesn't set `project`, `version`, `copyright`, etc.

**Comment by jayjaybillings** [comment]
Okay. I'll try that. Thanks!

Is the a good conf.py example out there? I couldn't find the conf.py for RTD; only setup.py in the repo.

Jay
________________________________
From: Anthony
Sent: Sunday, November 29, 2015 4:45 AM
To: "rtfd/readthedocs.org"
CC: "Billings, Jay Jay"
Subject: Re: [readthedocs.org] Project page shows "Python" instead of "Fire Framework" (#1838)



I believe this is due to the theme setting the default of Python in the template, where it expects the conf.py to have a project name. It seems your conf.py doesn't set project, version, copyright, etc.

-

**Comment by agjohnson** [comment]
The `sphinx-quickstart` command[1] will output a full `conf.py` based on the input that you give it. You don't need all of the options there, but would be a good place to work from.

Feel free to reopen if this doesn't help

1: http://sphinx-doc.org/invocation.html#invocation-of-sphinx-quickstart
