### ISSUE TITLE
delete SQLAlchemy rel_0_6 and rel_0_5 HTML totally

### ISSUE THREAD

**Issue by zzzeek** [rtfd/readthedocs.org#1842]
Hi -

I don't see any way to do this, there's a "clear" button that I pressed and seems to do nothing.  The rel_0_6 and rel_0_5 builds are showing up in Google results and deeply confusing people, unfortunately the "canonical" URL function, even though I've rebuilt these docs and it shows up, is not sufficient because the file organization has changed and google does not honor a canonical URL that itself turns up a 404.

Can I please have everything underneath:

http://docs.sqlalchemy.org/en/rel_0_6/

and

http://docs.sqlalchemy.org/en/rel_0_5/

be *completely gone*? that is, 404, not found, no content here, google please stop indexing these pages.  Or otherwise how should I do that.   Thanks.

**Comment by zzzeek** [comment]
e.g., a redirect.  which would also be an awesome feature.

**Comment by ericholscher** [comment]
These now 404.

**Comment by zzzeek** [comment]
okey doke thanks!
