### ISSUE TITLE
[Question] Localization with Mkdocs backend

### ISSUE THREAD

**Issue by flaporte** [rtfd/readthedocs.org#1844]
As a preamble of the [Localization page](http://docs.readthedocs.org/en/latest/localization.html) it's written :  

> This feature only applies to Sphinx documentation. We are working to bring it to our other documentation backends.

I wanted to know if bringing it to Mkdocs is targeted for a specific milestone or should not be expected shortly.

**Comment by agjohnson** [comment]
This is probably a better question for mkdocs, we would only support what mkdocs supports.
