### ISSUE TITLE
[Question] Bringing in historical documentation

### ISSUE THREAD

**Issue by gep13** [rtfd/readthedocs.org#1845]
Apologies if this is covered somewhere in your documentation, but I couldn't see it.

We, the Chocolatey Team, are currently deciding whether to bring the documentation for Chocolatey into Read the Docs.  We currently using the GitHub wiki for our documentation, but we are starting to run into some limitations, and we are looking to start using something like your service to make that happen.  Before doing that, we have some questions...

We have two GitHub wiki's that contain documentation of historical versions of Chocolatey.  Is it possible to bring this historical documentation into the docs folder of our main repository, and respectively associate a version number to it?  I understand that the RTD version numbers can be inferred from tags, but the tags that we would use have already been assigned to the repository, and therefore can't be changed.  Is there a mechanism to create the RTD version in another way?

Since we are already using the GitHub wiki, are were planning on using your markdown support to build our documentation.  Is all GitHub flavored markdown supported in RTD?

Thanks in advance!

**Comment by agjohnson** [comment]
We rely on VCS tags/branches for versioning, so you historical documentation for each version would need to be updated on those tags/branches.

Markdown support in Sphinx use the Commonmark spec, so no flavors of Mardown are supported.

**Comment by gep13** [comment]
@agjohnson thanks for getting back to me!

Are you aware of any projects that use branches to control their documentation?  Was hoping to see a sample of what that looks like.

Just want to decide best course of action before jumping in.

Thanks!

**Comment by agjohnson** [comment]
Many projects do, as this is the benefit of automating documentation release with RTD. A few off the top of my head:

* http://django.readthedocs.org/en/latest/
* http://fabric.readthedocs.org/en/latest/
* http://julia.readthedocs.org/en/release-0.4/

**Comment by gep13** [comment]
@agjohnson can a RTD site target docs from multiple repositories, or is it a 1-to-1 relationship

**Comment by agjohnson** [comment]
If you would like to combine several repositories in a single documentation project, you can with git submodules, though the issue there is that versioning becomes more difficult in the main repository.

**Comment by gep13** [comment]
@agjohnson thanks again for getting back to me.  I "think" we have a plan on how to proceed now.  Just a case of getting it done! :smile:

**Comment by ferventcoder** [comment]
@agjohnson submodules? That's rock solid. I had that question initially :)

**Comment by ferventcoder** [comment]
@agjohnson I don't think we'd approach it, it's just good to know it's an option.
