### ISSUE TITLE
Original owner of project on RTD can't make me admin

### ISSUE THREAD

**Issue by bkabrda** [rtfd/readthedocs.org#1847]
Hi, I became new maintainer of flexmock (original repo at [1], the new official repo is my fork at [2]) and I'd like to start building docs for it on RTD. The project is already at RTD [3], [4] but the original author (@has207) claims he never created that nor has he registered for RTD. He can sign in now, but seems to not be able to do anything with [4]. Interestingly enough, I was able to trigger manual rebuild on [4] yesterday even though I have no rights to that project.
Could you please transfer the project to me? The original author confirmed that my fork is now the official one in [5]; I believe if you need his confirmation, he can confirm it here again. Thanks!

[1] https://github.com/has207/flexmock
[2] https://github.com/bkabrda/flexmock
[3] http://flexmock.readthedocs.org
[4] https://readthedocs.org/projects/flexmock/
[5] https://github.com/has207/flexmock/commit/0a11b51dc3f5d471a828801e9ecbd971963c7fa0

**Comment by agjohnson** [comment]
If @has207 has access to the account `has207` on RTD, which it looks like he does, he is listed as the project owner for that project. He can perform maintenance on the project -- including adding you as an owner.

If you still have problems adding a user, we'll need to verify the transfer with the user/email in RTD -- both users should follow up with support@readthedocs.org.

And for triggering manual rebuilds, anyone can trigger a rebuild of another projects, all the projects on the community site are public.

**Comment by bkabrda** [comment]
It seems that the original maintainer succeeded adding me as another maintainer now, so I'm closing this. Thanks.
