### ISSUE TITLE
readthedocs.org build taking ~two days

### ISSUE THREAD

**Issue by connor4312** [rtfd/readthedocs.org#1851]
It's been about two days since I triggered a build of our (relatively small) documentation, and it's still pending. We're fairly new to Read the Docs -- are these wait times normal?

![](http://peet.io/i/15-12-qWqfCOUUqEZfrFiFgqlfBKdvs.png)

Build IDs are #3540076 and #3540091. Standard Sphinx project. The only plugin is Mathjax. The docs themselves are [here](https://github.com/WatchBeam/interactive-reference)

**Comment by ericholscher** [comment]
Go ahead and re-build the project. Our builders time out after 10 minutes, so there was likely a bug that stopped them from properly updating the status on the servers.

**Comment by marcelstoer** [comment]
Just ran into this myself with https://readthedocs.org/projects/nodemcu/builds/3539907/. Was a bit surprised to find no option to cancel or delete those triggered zombie builds.
Re-building works fine, though.

**Comment by connor4312** [comment]
Thanks, a rebuild worked. It'd be super awesome if there was a way to cancel triggered and in-progress builds, like you can on CIs such as Travis :)
