### ISSUE TITLE
Title version mismatch

### ISSUE THREAD

**Issue by radarhere** [rtfd/readthedocs.org#1852]
Hi. I don't think a similar issue exists here, my apologies if it does.

As described in python-pillow/Pillow#1494, the `title` tag for https://pillow.readthedocs.org/en/3.0.x/ lists the Pillow version as 2.6.1, where one would expect it to be 3.0.0.
- https://github.com/python-pillow/Pillow/blob/3.0.x/docs/conf.py#L126-L128 shows that `html_title` is not defined.
- https://github.com/python-pillow/Pillow/blob/3.0.x/docs/conf.py#L62 shows that `release` is the Pillow version
- https://github.com/python-pillow/Pillow/blob/3.0.x/PIL/__init__.py#L15 shows that the Pillow version is 3.0.0

Any thoughts? Thanks very much.

**Comment by ericholscher** [comment]
This is a Sphinx issue, not a Read the Docs issue.

**Comment by radarhere** [comment]
Okay, thanks for your response.

**Comment by ialexryan** [comment]
Sorry, wait a second. Two days after @ericholscher said it was Sphinx's fault, @lehmannro [said it was RTD's fault](https://github.com/sphinx-doc/sphinx/issues/2281#issuecomment-177477841).

Whose fault actually is it? The bug is still out there - [here's a live example](https://flask-restful.readthedocs.io/en/0.3.5).

![image](https://cloud.githubusercontent.com/assets/2292782/23352192/9ace710c-fc7a-11e6-949b-2bd4aaff4b23.png)

**Comment by ericholscher** [comment]
The version is taken from the sphinx `conf.py` file, which is where that number came from.

**Comment by humitos** [comment]
@ialexryan the live example you linked shows a complete different page for me.

![captura de pantalla_2017-03-03_17-53-45](https://cloud.githubusercontent.com/assets/244656/23572021/62b12378-003a-11e7-8090-4cba7fc7176e.png)

**Comment by ialexryan** [comment]
@humitos sorry, should have clarified - that navigation link only shows up at viewport widths of 875 pixels or less. The erroneous title is also visible in the tab bar.

@ericholscher would it be possible for the project to have all up-to-date text content without having been built in years? (Sorry if that's a noob question, I haven't used RTD myself and I don't have control of this repo, just a user trying to get to the bottom of the issue.)

**Comment by humitos** [comment]
> @humitos sorry, should have clarified - that navigation link only shows up at viewport widths of 875 pixels or less. The erroneous title is also visible in the tab bar.

Oh, I see, and I was able to reproduce your issue (also the title of the web is wrong)

> @ericholscher would it be possible for the project to have all up-to-date text content without having been built in years? (Sorry if that's a noob question, I haven't used RTD myself and I don't have control of this repo, just a user trying to get to the bottom of the issue.)

Didn't get this. How are you going to have fresh content without re-build? Each build correspond to a specific commit and branch. If a new commit happens there that updates the docs, a new build is done to update the docs.

I'm lost with your question.

**Comment by humitos** [comment]
@ialexryan the name of the branch is `0.3.5` but you haven't changed the code for that: https://github.com/flask-restful/flask-restful/blob/0.3.5/docs/conf.py#L56 it says `0.2` and `0.2.1`. That's the problem here.
