### ISSUE TITLE
Bump to Sphinx 1.4.1

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1853]
Sphinx 1.3.4 is out, upgrade to this release.

Edit: target 1.4.1 release instead. testing will be required here.

**Comment by stevepiercy** [comment]
Sphinx 1.3.4 was released today. It fixes this bug:
https://github.com/sphinx-doc/sphinx/issues/2189

**Comment by agjohnson** [comment]
This is still open, though we've already targeted 1.3.5. Repurposing this ticket to target 1.4.1 instead.

**Comment by davidchall** [comment]
It'd be great if you bumped to 1.4.2 instead. It fixes https://github.com/sphinx-doc/sphinx/issues/2304 which is affecting me.

(The latest version is 1.4.5)

**Comment by agjohnson** [comment]
@davidchall you can specify a specific version of sphinx if you need to

**Comment by davidchall** [comment]
@agjohnson How do I do this? Through the requirements.txt file?

**Comment by mozbhearsum** [comment]
@davidchall Looks like you can set the version with "needs_sphinx" in conf.py.

**Comment by mozbhearsum** [comment]
My bad, pinning in requirements.txt is the right solution.

**Comment by agjohnson** [comment]
Closing this, we've bumped to support 1.5.3
