### ISSUE TITLE
Syntax error using metaclass

### ISSUE THREAD

**Issue by cemsbr** [rtfd/readthedocs.org#1855]
It runs successfully in my environment with sphinx-1.3.3, but in readthedocs I get:
```
    class Runnable(metaclass=ABCMeta):
                            ^
SyntaxError: invalid syntax
```
The project is https://github.com/cemsbr/aioshell

**Comment by agjohnson** [comment]
Looks like you're running your py3 code in a py2 virtualenv. Try setting the correct version in the project admin.

**Comment by cemsbr** [comment]
Thanks, it works now with CPython 3.x in advanced settings.

**Comment by d6tdev** [comment]
This helped! Just to clarify, to change this setting, in the main project page, select admin | advanced | interpreter.
