### ISSUE TITLE
readthedocs+recommonmark still does not get code highlighting

### ISSUE THREAD

**Issue by kozo2** [rtfd/readthedocs.org#1859]
This is already issued in #1485
but readthedocs+recommonmark still does not get code highlighting.

Please compare
http://markdown-code-highlight.readthedocs.org/en/latest/markdown.html
with
http://readthedocs-sphinx-markdown-issue.readthedocs.org/en/latest/rst.html

The code repo is
https://github.com/kozo2/readthedocs-sphinx-markdown-issue

**Comment by marcelstoer** [comment]
Or look at it's own dog food code at https://recommonmark.readthedocs.org/en/latest/#getting-started

**Comment by agjohnson** [comment]
Yeah, that looks like it should work, seems there is a regression somewhere.

**Comment by pardahlman** [comment]
I've noticed this, too. Issue #1485 is closed but the example links @kozo2 posted in this issue are rendered without syntax highlight. Any news for this issue?

**Comment by tigerhawkvok** [comment]
On this bug, it's good to note that the collapsable navigation doesn't show up for the markdown, either -- which is to say, 

```
# Foo
## Bar
```

Doesn't nest "Foo" under "Bar", but shows them as siblings.

**Comment by agjohnson** [comment]
@tigerhawkvok your issue is not related to this issue, nor can I reproduce it. I assume this is because you are using mkdocs, and not Sphinx + recommonmark.

**Comment by stsewd** [comment]
I tested this on my local instance with the latest rtd-theme, it works as expected

![screenshot-2018-5-17 rst header test test documentation](https://user-images.githubusercontent.com/4975310/40202863-00894cfc-59e9-11e8-9ce2-7d5adb50ecbd.png)

![screenshot-2018-5-17 2nd level rst header test test documentation](https://user-images.githubusercontent.com/4975310/40202865-01f095d2-59e9-11e8-87f4-65814efcc91f.png)

Feel free to reopen this issue if I misunderstand something.
