### ISSUE TITLE
Activate inactive account, please

### ISSUE THREAD

**Issue by cmc333333** [rtfd/readthedocs.org#1860]
Hello! Please re-activate the inactive `cmc333333` account when you have a moment. Thank you

**Comment by cmc333333** [comment]
Bump

**Comment by cmc333333** [comment]
Pretty please re-activate this account

**Comment by cmc333333** [comment]
@ericholscher - it looks like you've handled inactive accounts in the past. Would you mind fixing for me?

**Comment by ericholscher** [comment]
Should be fixed.
