### ISSUE TITLE
Increment Pygements release to support Python 3.5 syntax

### ISSUE THREAD

**Issue by aaugustin** [rtfd/readthedocs.org#1865]
Hello,

Read the Docs offers the option to build docs with Python 2.x or 3.x, which is great.

Python 3.5 introduced some new syntax, namely the ``await`` and ``async`` keywords. Since Read the Docs runs Python 3.4, code samples that use this syntax cannot be parsed and thus aren't syntax-highlighted. See the first block on [this page](http://aiohttp.readthedocs.org/en/v0.19.0/web.html) for example.

Have you considered making it possible to pick a specific Python version, perhaps among 2.7, 3.4, 3.5? Alternatively, do you have a rough idea of when you'll upgrade the platform to 3.5?

Thanks!

**Comment by aaugustin** [comment]
I appear to have incorrectly assumed that it was related to the version of Python running Sphinx.

Apparently the next release of Pygments (for which there's no ETA) should solve the problem.

https://bitbucket.org/birkenfeld/pygments-main/issues/1154/please-make-next-release

**Comment by agjohnson** [comment]
Regarding the Python version selection: we haven't yet, though the ability to use arbitrary versions of Python might be a good future feature.

The real issue seems to be a pending Pygments release, we'll pin the next release to come out.

**Comment by aaugustin** [comment]
Pygments 2.1 was releaseed mid-January, unblocking this issue.

**Comment by aaugustin** [comment]
Is it just a matter of bumping Pygments to 2.1.3 in `requirements/pip.txt`?

**Comment by agjohnson** [comment]
You'll need to update the requirements in:
https://github.com/rtfd/readthedocs.org/blob/42ab9d198494d5cf9fe320ac217d837bf480c73f/readthedocs/doc_builder/python_environments.py

**Comment by aaugustin** [comment]
I just submitted a PR with this change, I hope this helps. Thanks!
