### ISSUE TITLE
Links to documentation version end in a "does not exist yet" error page

### ISSUE THREAD

**Issue by fgalan** [rtfd/readthedocs.org#1868]
Regarding the following project at RTD: http://fiware-orion.readthedocs.org/en/0.24.0/, the  different versions are shown at the bottom left corner, e.g. 0.26.1, 0.26.0, 0.25.0, etc.

However, when we click on any of those, we end in a  "SORRY - This page does not exist yet" error page.

The problem could be due to the link associated to the version includes a "/None" in the URL, e.g:

http://fiware-orion.readthedocs.org/en/0.26.0/None/

We have checked that without "/None" the page at http://fiware-orion.readthedocs.org/en/0.26.0 works.

Is this an already known issue? How to solve it? Thanks!

**Comment by agjohnson** [comment]
This is supposed to be resolved by #1634. A mkdocs release is required though. Closing this, feel free to subscribe to the PR.

**Comment by fgalan** [comment]
PR #1634 has been recently merged, but the problem at http://fiware-orion.readthedocs.org/en/0.24.0 stills. Maybe some time has to pass between the code is fixed by that PR and that code is intalled in production at readthedocs.org?

**Comment by agjohnson** [comment]
Correct, I don't believe this was deployed yet, should be out this week.
