### ISSUE TITLE
Alternate domain returning wrong project

### ISSUE THREAD

**Issue by borntyping** [rtfd/readthedocs.org#1872]
I have a domain [`docs.borntyping.co.uk`](http://docs.borntyping.co.uk/en/latest/scripts/) pointing at the [`borntyping-maintenance`](http://borntyping-maintenance.readthedocs.org/en/latest/) project, but it's returning an unrelated project named [`maintenance`](http://maintenance.readthedocs.org/en/latest/) instead.

I'm guessing this is due to the similarity of the two project slugs, but I can't find anything in the code that would cause this.

**Comment by ericholscher** [comment]
Believe this is fixed. There were some stale symlinks causing this. Let us know if it happens again.

**Comment by borntyping** [comment]
Thanks!
