### ISSUE TITLE
Reset link not working

### ISSUE THREAD

**Issue by camil-sumodhee** [rtfd/readthedocs.org#1873]
Hi,
I tried to reset my password using the following link:
https://readthedocs.org/accounts/password/reset/

But I've never received the email (not even in spam).
I tried a few times on several days, but I'm still unlucky.
It looks like this issue is similar to issue [#1792](https://github.com/rtfd/readthedocs.org/issues/1792)

Any idea on how to recover?

Thank you in advance.

C.

**Comment by agjohnson** [comment]
Is this still an issue? We haven't had any problems with our outbound email, maybe this is a straight forward content filtering issue.

**Comment by camil-sumodhee** [comment]
Hi agjohnson. Indeed it's still an issue. Tried today 2016-01-04 at 13:30 and 13:45 (GMT+1) without success. We're using Google Apps email accounts. No content filtering and nothing in spam either. Could you please check the outbound mail again? Thanks in advance.

**Comment by agjohnson** [comment]
Not sure this is related, but I deployed a fix for a similar problem today. If you are still not receiving mail after this change, I would guess that this is a problem with your mail provider dropping the email from us. Feel free to reopen if we can change anything to allow for delivery.
