### ISSUE TITLE
Apply for Gratipay 2.0 Team

### ISSUE THREAD

**Issue by mattbk** [rtfd/readthedocs.org#1876]
From https://github.com/rtfd/readthedocs.org/issues/1734#issuecomment-146760532

> Just another questions: It seesm I can't spend money on https://gratipay.com/~readthedocs/ ?

I know you guys were receiving some money under the previous version of Gratipay, would you be interested in [applying for a Gratipay 2.0 Team](https://gratipay.com/new)? The link up at https://readthedocs.org/ won't let anyone donate.

([Here's why Gratipay 2.0 happened.](https://medium.com/gratipay-blog/gratipay-2-0-2453d3c53077#.mvjanvezx))

**Comment by agjohnson** [comment]
Yeah, we should remove mention of gratipay completely, we don't use it at all and process donations directly through stripe now.

**Comment by mattbk** [comment]
Full disclosure, I work on some of the user support for Gratipay. It looks like you still would have people donating to you if you applied for a team; the existing tips from back in April (before the terms of service changed) would be automatically migrated.

**Comment by ericholscher** [comment]
We aren't using gratipay anymore. My PR on #1764 fixes this.
