### ISSUE TITLE
No TeX files were found

### ISSUE THREAD

**Issue by chfw** [rtfd/readthedocs.org#1877]
How do I get rid of 'No TeX files were found' warning? https://readthedocs.org/projects/pyexcel/builds/3589272/

Cheers

**Comment by agjohnson** [comment]
Have you disabled the latex/pdf output?

**Comment by chfw** [comment]
Indeed, it's gone after latex had been commented out. Thanks for your help

**Comment by pfalcon** [comment]
> Have you disabled the latex/pdf output?

I did not. Why would I? How this should be done? How to still build PDF docs, because again, why would I want to disable PDF, if it's second most used format?

Our project has suddenly stopped building docs successfully ~ 6 months ago with this error. Google for `readthedocs "No TeX files were found"`, there're gazillion of project which are hit by this issue (so the only relevant link I found is this ticket). What happens here?

**Comment by agjohnson** [comment]
@pfalcon There are a number of causes that can cause this -- from misconfiguration of sphinx, to failing on the latex output pass. I can't help you without information on your project though, and either way, the original issue here has been closed. Please open a new ticket to address your issue.

**Comment by pfalcon** [comment]
> from misconfiguration of sphinx

I guess in our case, it falls under this category, we added support for generating multiple versions of docs (based on conditions), and named output index accordingly, but latex config still referred to default 'index' name.

I guess, what I really wanted to say here is that if readthedocs works, it works, and if not, it's rather hard to diagnose it, starting from a simple things like output commands shown truncated on build page, e.g. http://readthedocs.org/projects/micropython/builds/3607404/ , and there's no easy way to see the full command. Not sure it's worth opening a new ticket though, just hope someone will google this up if hitting similar issue, and will get the hint that they should err on their side and RTFM.

**Comment by UnixedIT** [comment]
the sames error! ,
please check this project:

https://bit.ly/39OVE7Q

 thank you.
