### ISSUE TITLE
ReadTheDocs not updating, even after fresh rebuild

### ISSUE THREAD

**Issue by mkli90** [rtfd/readthedocs.org#1878]
Hi guys, why could it be, that read the docs is not correctly showing the content of my project? When using "make html" on my machine and inspecting the generated files everything seems fine. I've uploaded the newly built html's to my github and rebuilt in readthedocs, but it still misses all the content: http://pss.readthedocs.org Here's the code: https://github.com/mkli90/pss/blob/master/docs/build/html/pss.html

**Comment by agjohnson** [comment]
This is a problem of your local environment having the correct C dependencies, while our build servers do not. You should read up on how to mock out python C dependencies that don't exist on our build servers. See our docs at http://docs.readthedocs.org

**Comment by mkli90** [comment]
Awesome! Thanks! Working perfectly

**Comment by lobachevzky** [comment]
@macskay I have the same problem. Could you describe the solution that is working perfectly for you?

**Comment by RichardLitt** [comment]
@lobachevzky This is a fairly old issue, and I'm not sure that your issue would still be the same. Could you please open a new issue for your problem?
