### ISSUE TITLE
Cannot import project from BitBucket

### ISSUE THREAD

**Issue by fraca7** [rtfd/readthedocs.org#1879]
When I click on "Connect to BitBucket", it asks me for a username and e-mail. First, it's not clear if I should give my username on BB or RTD, but that's moot since they're the same. If I submit, it complains that the username is already used (duh, it's mine). Looks like "connect to BitBucket" actually logs me out of RTD. What am I missing ?

**Comment by agjohnson** [comment]
Are the email addresses for your RTD account and your Bitbucket account different? Are they both verified addresses? Any details here would help track this down.

I'm not sure exactly why `django-allauth` does this, but during account connection, it assumes the account should be a new acccount for some reason, deauths the session, and provides a signup for. This is obviously not what we intended. This might be a configuration bug, I'll see about testing it with #1850

**Comment by fraca7** [comment]
The email address for RTD is a secondary address on BitBucket. Both verified. I tried using both of my verified addresses on BB, same result. The user name is the same for RTD and BB. Not much more I can gather unfortunately; if you need me to try out something I'll be happy to oblige.

**Comment by agjohnson** [comment]
That's helpful, my guess without looking at the allauth code is that the secondary address isn't tested, thus a new account for RTD is requested. I don't know why this email or username check would be required, it should just connect the account.

**Comment by agjohnson** [comment]
It looks like my guess was not correct, I haven't had any luck replicating the issue yet. This likely isn't a Bitbucket specific issue, and is most likely a `django-allauth` configuration issue or bug.

Merging this into #1875, feel free to follow there.
