### ISSUE TITLE
Cannot import with self-signed certificate

### ISSUE THREAD

**Issue by halfdan** [rtfd/readthedocs.org#1880]
I am trying to add a project hosted at a private Gitlab instance: https://gitlab.cs.uni-tuebingen.de/eva2/eva2

This is a university project and there's no way to get a proper SSL certificate for it. I am getting build errors `Error: Failed to import project` which I suspect come from using a self-signed certificate on that domain. Can we please add `-c http.sslVerify=false` to all git commands or just globally set `http.sslVerify` to `false`?

**Comment by agjohnson** [comment]
No, I can't say I'd support this change. SSL verification is a security feature we'd rather keep around. I'm not sure if there is a better answer, other than convincing your university to use proper SSL certificates, or hosting your code someplace that does.
