### ISSUE TITLE
Random repeated failures with missing .requirements

### ISSUE THREAD

**Issue by rougier** [rtfd/readthedocs.org#1882]
I've setup a ```.requirements``` for dependencies in my project but the build process complains about missing file. From time to time it works but I cannot find the reason (I did not remove the file from my projects):

```
Could not open requirements file: [Errno 2] No such file or directory: '.requirements'
```

One failed build: https://readthedocs.org/projects/glumpy/builds/3595136/

**Comment by ericholscher** [comment]
Looks like this has been passing for the last ~20 builds, guessing it has been resolved?

**Comment by rougier** [comment]
Yes but I did not change anything. Weird.
I'm closing the issue, I'll reopen it if necessary.
