### ISSUE TITLE
CSRF check failed from a 404 page

### ISSUE THREAD

**Issue by brunifrancesco** [rtfd/readthedocs.org#1883]
If I try to change the lang from the 404 page I got a CSRF token fail validation (and a 403 status code).
The classic Django yellow page appears with no further details.

Try to change lang [here](http://docs.readthedocs.org/en/latest/contribute.htmldddd), for example.
Cheers,

FB

**Comment by agjohnson** [comment]
Two issues here, styling the django csrf error page, which is a duplicate of #1430, and the underlying cause of the missing csrf token.

**Comment by humitos** [comment]
I think this has already solved. Trying to change the lang from the page you linked I end at http://docs.readthedocs.io/i18n/setlang/ and I see the Maze.

I'm closing this issue. Feel free to reopen it if you consider.
