### ISSUE TITLE
Refactor abstraction with buildenv and pythonenv, including env variables

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1891]
Because the docker command call doesn't do env vars, we need to prefix these to the bash call, which is hacky. It is also prone to breakage, as we aren't scrubbing the env vars we're adding on, so characters can current escape the bash call. If we can implement through a newer version of docker's api, this is best. Otherwise, the buildenv should be made aware of the pythonenv -- that is, reverse the relationship now -- and pythonenv should expose a `get_environment_vars` method that returns vars to add to the environment. This would be on instantiation, and the vars would be appended to the vars passed into the docker container creation call instead, where they should be safer. `BuildCommand` should also provide a `get_environment_vars` method for centralizing all of the additions to the env vars that we should be adding in local and docker build command instances.

**Comment by ericholscher** [comment]
Believe we fixed this.
