### ISSUE TITLE
conda support not activated, virtualenv is used

### ISSUE THREAD

**Issue by pitrou** [rtfd/readthedocs.org#1894]
I tried to use conda support as explained in the docs, but virtualenv is still being used. My test build is at https://readthedocs.org/projects/-pitrou-llvmlite/builds/3609496/.

The changeset it points to is the following: https://github.com/numba/llvmlite/commit/e99dbc88e488f18e3b6133677f8635dea677aabd

**Comment by ericholscher** [comment]
Hmm, it looks like the second build on a server picks up conda correctly. I'll investigate.

**Comment by ericholscher** [comment]
Believe this should be resolved. Let me know if it isn't working for you.
