### ISSUE TITLE
Example of using custom javascript with Sphinx deployed on ReadTheDocs

### ISSUE THREAD

**Issue by bamos** [rtfd/readthedocs.org#1903]
Hi, I asked the following on IRC yesterday but didn't get a response. I'm re-posting here since the IRC channel isn't very active.

---

Is there an example of using a custom js import with readthedocs?

 I can successfully include custom js in my local Sphinx build by adding a js file in html_static_path and then including it in a theme that imports it in`extrahead`, but my custom javascript isn't included when depolyed on readthedocs.

For CSS, I found https://blog.deimos.fr/2014/10/02/sphinxdoc-and-readthedocs-theme-tricks-2/. However, by looking at the layout at https://github.com/snide/sphinx_rtd_theme/blob/8c880a64fa0f08785ffc560708628fc3108a2f3d/sphinx_rtd_theme/layout.html,  there doesn't appear to be an equivalent 'extra_js_files' I can add to the context.

**Comment by ericholscher** [comment]
http://sphinx-doc.org/latest/extdev/appapi.html#sphinx.application.Sphinx.add_javascript

**Comment by bamos** [comment]
Thanks! `Sphinx.add_javascript` works well.
