### ISSUE TITLE
Best practice for constructing image links

### ISSUE THREAD

**Issue by michaelmcandrew** [rtfd/readthedocs.org#1904]
I can't find any documentation on the right way / best practice for referencing images on rtd (with markdown). I have a manual that i have 'imported' https://github.com/civicrm/civicrm-user-guide and I am cleaning up the image links.

Currently all images are in docs/img. what is the best way to reference an image from for example docs/advanced-configuration/logging.md?

I am presuming that ../../img/image.png would be best (esp. if we are doing stuff like having multiple versions and languages on the same domain) but wanted to check in case there is some rtd magic that I can / should take advantage of.

Thanks!

**Comment by agjohnson** [comment]
This sounds like a queation for mkdocs, we don't do anything special here. I'm not familiar enough with mkdocs to answer, but seems like relative paths should be fine.

Closing this as this isn't an issue with RTD.

**Comment by michaelmcandrew** [comment]
Thanks @agjohnson,
Do you think this could / should be documented in https://docs.readthedocs.org/en/latest/index.html? I couldn't find anything there, or in mkdocs on the subject. Might be obivous to some but would also avoid some head scratching if a recommended way to do it is explicitly documented.

**Comment by agjohnson** [comment]
I don't think it needs to end up in our docs, where it will most certainly rot. Mkdocs would again be the best location for this information if anything, we do nothing with special with paths here.

**Comment by michaelmcandrew** [comment]
OK - will leave it there then, I think.
