### ISSUE TITLE
Possible bug: Sphinx's conf.py ignored

### ISSUE THREAD

**Issue by chiffa** [rtfd/readthedocs.org#1908]
I am trying to build the documentation for [my project](https://github.com/chiffa/BioFlow) on the RTFD. Building the documentation works fine on my machine, however when I try to build the documentation on the [readthedocs.org](https://readthedocs.org/projects/bioflow/builds/3621046/), the build fails due to the attempt to install C python modules. 

Following the [RTFD FAQ](http://read-the-docs.readthedocs.org/en/latest/faq.html) I mock my modules within the Sphinx's `conf.py` file. However it seems that RTFD tries to install the project without first executing `conf.py` and because of that the dependencies installation fail, along with the build. I know `conf.py` is not executed because it will print `sys.path` modifications when executed and/or imported.

I tried to explicitely point out the location of the conf.py file, along with letting RTFD discover it itself, but it seems that the problem persists. I was not able to find any mention of that problem online and the contradiction of that behavior to what is indicated in FAQ seems to indicate that this behavior might be a bug

**Comment by agjohnson** [comment]
Mocking only avoids dependencies that are not installed during Sphinx execution. You still need to specify a pruned list of dependencies to RTD, otherwise we'll just continue trying to install those packages. Many projects use a separate requirements file with docs-specific packages here.

**Comment by chiffa** [comment]
Is this a behavior that has changed recently? I remember getting the pipeline above to work about 10 months ago.

**Comment by agjohnson** [comment]
It has not. We can't inspect your conf.py until your dependencies are installed, so this has always been the case.

**Comment by chiffa** [comment]
Ok. Once I added the "on_rtd" into the setup.py to adjust the dependencies that actually need to be installed, it works. Would you mind adding this step into the documentation?

**Comment by agjohnson** [comment]
Feel free to submit additions to the docs, they are open source.
