### ISSUE TITLE
ImportError: cannot import name import_by_path

### ISSUE THREAD

**Issue by ashwillwink** [rtfd/readthedocs.org#1909]
I'm getting the foll error when running locally. Not sure of the issue any suggestions?

Running Sphinx v1.3.3

Exception occurred:
  File "C:\Python27\lib\site-packages\readthedocs-1.0-py2.7.egg\readthedocs\privacy\loader.py", line 1, in <module>
    from django.utils.module_loading import import_by_path
ImportError: cannot import name import_by_path
The full traceback has been saved in c:\users\agumma~1\appdata\local\temp\sphinx-err-tg80oq.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by isankadn** [comment]
Its deprecated from Django 1.10!
https://github.com/djangonauts/django-pgjson/issues/45
