### ISSUE TITLE
can't get rid of a bad version

### ISSUE THREAD

**Issue by hlship** [rtfd/readthedocs.org#1910]
At some point in the past, a tag, 1.0.4, was added.

This version number now appears on https://readthedocs.org/dashboard/ioavisopretty/versions/, even though I've subsequently deleted the tag from my local, and GitHub repositories.

Because it is semantically ahead of the actual latest version number (0.1.21), it is magically linked at the stable release.  I have not way that I can find to fix this.  I've had to remove my stable build entirely.

RTD should have the ability to see that it has a tag that no longer exists in the repo OR at least, a mechanism to delete local tags, so that I can clean things up, and have a stable build link again.

**Comment by ericholscher** [comment]
I've deleted this from the DB -- if it still exists on our checkouts, it will likely be re-created though.
