### ISSUE TITLE
Our site is not building

### ISSUE THREAD

**Issue by lkettle** [rtfd/readthedocs.org#1913]
Hello, our project ( Hashkat ) documentation is hosted on Github

http://docs.hashkat.org/en/latest/
https://github.com/hashkat/hashkat

Recently our documentation build broke when we attempted to add a new tab and reorganize the tab order (in the sidebar)

this is the build that did not happen:
hashkat/hashkat@5457592

The commits to the main github site appear to have gone fine, it is just the read the docs part We are reluctant to revert on Github because there have been several commits (tho not to documentation) .

Could you please tell us what we did wrong and how we can fix it?

Thank you.

Linda Kettle
linda.kettle@uoit.net
416-833-3676

**Comment by agjohnson** [comment]
Closing as duplicate.
