### ISSUE TITLE
builds have started being killed

### ISSUE THREAD

**Issue by minrk** [rtfd/readthedocs.org#1915]
I've noticed that my pyzmq builds have started being killed, but don't see any info for what I might be able to do about it.

From the logs, it seems to happen during the `byte-compiling` stage of installation. PyZMQ is pretty small, but requires Cython and C compilation. Builds don't take super long, so I'm trying to figure out what could be causing it, but I can't do much debugging.

Last good build: 3619724: Jan. 7, 2016. 7:12 a.m, took 141 seconds
First killed build: 3616964: Jan. 8, 2016. 6:29 a.m, killed after 108 seconds

The code differences [are negligible](https://github.com/zeromq/pyzmq/compare/3ceac86b79eef1d0a76ed23c7b177aee0a187997...ee143ca21e037add4c1cc74c509b0d36911ccbb8).

Every build since then on multiple pyzmq repos is killed at a similar stage of installation.

I've tried switching to conda builds with readthedocs.yml, but those builds also get killed during installation with no feedback about why.

**Comment by agjohnson** [comment]
I believe the return code of `137` is a state where the docker container has run out of memory, but it wasn't detected as being OOM killed. Normally, if a process consumes too much memory, it is OOM killed and reported as killed by docker. This might be an edge case we're missing, or have to infer from the return code.

Has there been recent changes with pyzmq that could increase memory usage?

**Comment by minrk** [comment]
Aha, yes indeed. I added a test that apparently requires a large amount of memory *to compile*, which is something I've definitely never seen before. Sorry for the noise.
