### ISSUE TITLE
Redirect to canonical domain from readthedocs.org URL?

### ISSUE THREAD

**Issue by shoyer** [rtfd/readthedocs.org#1916]
I recently added a subdomain for accessing my project's docs (xarray.pydata.org) and set it as the canonical domain. However, the old URL (xray.readthedocs.org) still works, and does not redirect to this new URL. It is possible to change this so that visitors to my old domain get redirected to the canonical domain automatically? The canonical domain does fix this issue for search engines, but I would like to more clearly signal the new URL to users (which also corresponds to a new project name).

**Comment by ericholscher** [comment]
We serve all documentation from nginx directly, so we can't handle redirects on pages that exist and are served directly. The site should generate links to the proper domain, and google will index it.

**Comment by shoyer** [comment]
OK, fair enough. It's something worth considering in the future if the tech stack changes to make it doable.

**Comment by ericholscher** [comment]
Closing this, since it isn't really fixable in the near future.

**Comment by ericholscher** [comment]
Actually, we can incorporate it into our `base` redirector at least. PR: #3388
