### ISSUE TITLE
Allow execution of commands prior to building documentation

### ISSUE THREAD

**Issue by maplesond** [rtfd/readthedocs.org#1922]
I have a readthedocs project inside an autotools software project which is currently hosted on github.  I use the github webhooks to automatically update the documentation when a commit is appended to a particular branch.  

In order to have one place where I need to specify the project version (in my configure.ac file), I need to enter variables into the sphinx conf.py.in file.  These get resolved when I run autoreconf and configure on my project, producing a conf.py file, containing all the correct values.

Is there someway I can run autoreconf and configure, prior to readthedocs building the project?

My current workaround is to keep the latest copy of conf.py in my git repository, which is a bit messy.

**Comment by agjohnson** [comment]
So far, we have been against allowing arbitrary commands to be executed, as we aren't sure we can provide enough support for hostile uses of arbitrary command execution. Leaving this open for now, we'll need to definitively decide if this feature is worth it or not for the community site.

**Comment by agjohnson** [comment]
So we haven't come to any conclusions here, and so far have been against prescribing arbitrary command execution. However, you can accomplish this effectively by using a Sphinx extension point in your conf.py and calling arbitrary commands there.

We haven't added arbitrary command execution to our v2 config file, so I'll say that it's probably not something we'd support directly. For that, I suppose I'll close this issue and perhaps we can reconsider for a v3
