### ISSUE TITLE
Browser cache is not invalidated on new builds

### ISSUE THREAD

**Issue by Korijn** [rtfd/readthedocs.org#1925]
After triggering a new build, we noticed that `/` and `/index.html` differed. Turns out this was due to browser cache (hard refresh solved the inconsistency). The browser cache should be invalidated upon a new build for files that have changed, I guess.

**Comment by agjohnson** [comment]
I don't think there is any way for us to reasonably enforce this on the client side. Closing this as I don't think there is any steps we want to take here, if anyone has any ideas on how to reasonably do this, we can reopen.
