### ISSUE TITLE
Canonical link leads to a wrong domain

### ISSUE THREAD

**Issue by odinserj** [rtfd/readthedocs.org#1928]
Hi there!

Canonical link for my documentation leads to a strange domain I've never set. When I open `http://docs.hangfire.io/en/latest/configuration/` page in my browser to see the source code, I'm getting the following results:

```html
<link rel="canonical" href="http://hangfirechinese.readthedocs.org/en/latest/configuration/" />
```

I've googled a bit and found that there is the `hangfirechineese` project that isn't even linked in translation or subprojects in my project's options. And the other project that is not under my control (I'm supposing that this is a translation) affected my project.

* http://readthedocs.org/projects/hangfire/ (mine)
* http://readthedocs.org/projects/hangfirechinese/ (not mine)

Expected behavior is to have `docs.hangfire.io` domain in the canonical link, or even `hangfire.readthedocs.org` unless I've specified something else. Please tell me what should I do to resolve this, as this breaks my site search crawler.

**Comment by ericholscher** [comment]
This should be fixed. It looks like there was an old issue from when we let projects specify projects they don't own as translations.

**Comment by odinserj** [comment]
I've rebuilt the docs, and the issue is gone. Thank you!
