### ISSUE TITLE
Readthedocs.org lost my project

### ISSUE THREAD

**Issue by satishmaha** [rtfd/readthedocs.org#1937]
I linked my GitHub, and setup my project (as evidenced by the successful build here: http://json-query-documentation.rtfd.org/).

However, after logging into readthedocs.org a day later, it seems to have lost my project as well as the GitHub linking. Can someone please look into this?

**Comment by ericholscher** [comment]
It looks to be owned by the user `satish` -- is that not the username you're logging in with?

**Comment by satishmaha** [comment]
Oh wow, I must have signed up twice. You are correct, my apologies. This can be closed.
