### ISSUE TITLE
Buggy, unusable website interface

### ISSUE THREAD

**Issue by catb0t** [rtfd/readthedocs.org#1938]
This is a bug report / support question about http://readthedocs.org, not necessarily its backend.

---

Approximately every page-load of the website, I'm logged out and asked to re-enter my password despite checking the "keep me logged in" tickbox. My browser accepts and stores cookies normally, and its cache is functional.

Additionally, after connecting my RTD account to my git account and clicking "Import a Repository", the list of my git repos in full (about 20 repositories) appears for a second, then vanishes and displays "No remote repositories found, try refreshing your accounts." 

When I click the "refresh" icon at the top of that page, I get "There was an error with your request: Authentication credentials were not provided." despite being logged in, having verified my email and connected to git.

If I click the "refresh" icon once more, I get "Successfully logged in as catb0t" above the other authentication error. If I then reload the page, I'm asked to login again. 

If I log in and then click "Manually Import", I'm asked to log in again, then taken to the "Manual Import" page. If I submit the Manual Import request, I'm asked to log in again and the "Manual Import" page is displayed once again, with no change. This results in an endless loop.

This is reproducible for me by just browsing various parts of the site; this is Chrome 47.0.2526.111 on Linux 64 bit.

**Comment by agjohnson** [comment]
This could be a problem due to our session middleware, which helps prevent session fixation attacks. Does the problem exist for you in a Chrome incognito session? If not, what plugins are you using? Anything that provides tracking protection or might alter the browser user agent?

**Comment by catb0t** [comment]
@agjohnson It doesn't seem to happen in Incognito, which is interesting because I tried disabling some addons and it had no effect. You can close this, since it's an addon of mine, I just have to figure out which.

**Comment by agjohnson** [comment]
Let me know what you find, it would be helpful to figure out if there is an addon that we need to account for. Our session middleware likely has some edge cases that we could handle better.

**Comment by catb0t** [comment]
@agjohnson I was trying to figure out exactly which addon it was by enabling some in Incognito and it seems like it might be AdBlock Plus (the one with 200 million dl's). However, now I can't get it to load without "There was an error with your request: Authentication credentials were not provided." even after disabling adblock and my other addons and restarting the session. I'll look at this more in the morning because it's baffling.

**Comment by agjohnson** [comment]
@catb0t i never followed up on this, any more info here? We might have to look into adblock plus, if there is any specific configuration you've changed locally, that information would also help.

**Comment by agjohnson** [comment]
Assuming this can be closed, if there is any additional information here, feel free to reopen.

**Comment by catb0t** [comment]
@agjohnson  interestingly, it seems to be working fine now. I don't know what the issue was, but it's no longer present for me.

**Comment by joncison** [comment]
I had the same issue (readthedocs not showing my GitHub repos) and this problem disappeared when using Google Chrome "incognito".
