### ISSUE TITLE
Build Error Screen Too Narrow

### ISSUE THREAD

**Issue by lkettle** [rtfd/readthedocs.org#1940]
I'm unable to read the errors in the build because the display box is narrower than the type displayed.

![error screen](https://cloud.githubusercontent.com/assets/14791604/12379406/1c0fca9c-bd28-11e5-983f-da9f194116d4.png)

Like - which file is missing?

Can you amend your display so I can do more self help?

**Comment by agjohnson** [comment]
Not sure of the best option here. For immediate relief, highlighting the text will scroll the line.

**Comment by lkettle** [comment]
ok good to know.

On Wed, Jan 20, 2016 at 12:13 PM, Anthony <notifications@github.com> wrote:

> Not sure of the best option here. For immediate relief, highlighting the
> text will scroll the line.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/1940#issuecomment-173278049>
> .
>



-- 
Linda Kettle

**Comment by stsewd** [comment]
I think what is suggested here #2921 is the best option. Probably we can closes this issue in favor of the other one.

**Comment by humitos** [comment]
Agree with @stsewd. Closing
