### ISSUE TITLE
Installing documentation with 'requirements.txt' brings error 'RequirementParseError: Missing distribution spec <!DOCTYPE html>'

### ISSUE THREAD

**Issue by oliversauter** [rtfd/readthedocs.org#1943]
When importing a documentation from a github repo with the "[requirements.txt](https://github.com/WorldBrain/h/blob/master/docs/requirements.txt)" file containing: 
'sphinxcontrib-httpdomain'

...it brings up the following error: https://readthedocs.org/projects/worldbrain-bookmarks/builds/3647690/

The original project I forked it from, hypothes.is, has the same file structure and content of the  "[requirements.txt](https://github.com/hypothesis/h/blob/master/docs/requirements.txt)"
For them, their documentation running perfectly on your platform.

How can we overcome this problem?
Thanks for the help.

**Comment by ericholscher** [comment]
It requires a local file, relative to the root of your repository, not a URL.

**Comment by oliversauter** [comment]
thanks!
