### ISSUE TITLE
manage.py update_repo fails with unable to execute gcc:      

### ISSUE THREAD

**Issue by telefax** [rtfd/readthedocs.org#1944]
I'm running CentOS 7 with python2.7 and thought I had installed every possible dependency needed for readthedocs.
However, I cannot run update_repo without gcc fails. Doesn't matter which repo I try to update.

# which gcc
/usr/bin/gcc

# gcc -v
gcc version 4.8.5 20150623 (Red Hat 4.8.5-4) (GCC) 

How could I troubleshoot this?
Thanks

Log:

# ./manage.py update_repos pip

Installing collected packages: pillow, requests, nilsimsa, readthedocs-sphinx-ext, commonmark, recommonmark
  Running setup.py install for pillow
    Complete output from command /home/kral/readthedocs.org/user_builds/pip/envs/latest/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-sg4tPn/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DlRZbK-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kral/readthedocs.org/user_builds/pip/envs/latest/include/site/python2.7/pillow:
    Single threaded build, not installing mp_compile: 1 processes
    running install
    running build
    running build_py
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.yaml'
    warning: no files found matching '*.bdf' under directory 'Images'
    warning: no files found matching '*.fli' under directory 'Images'
    warning: no files found matching '*.gif' under directory 'Images'
    warning: no files found matching '*.icns' under directory 'Images'
    warning: no files found matching '*.ico' under directory 'Images'
    warning: no files found matching '*.jpg' under directory 'Images'
    warning: no files found matching '*.pbm' under directory 'Images'
    warning: no files found matching '*.pil' under directory 'Images'
    warning: no files found matching '*.png' under directory 'Images'
    warning: no files found matching '*.ppm' under directory 'Images'
    warning: no files found matching '*.psd' under directory 'Images'
    warning: no files found matching '*.tar' under directory 'Images'
    warning: no files found matching '*.webp' under directory 'Images'
    warning: no files found matching '*.xpm' under directory 'Images'
    warning: no files found matching 'README' under directory 'Sane'
    warning: no files found matching 'README' under directory 'Scripts'
    warning: no files found matching '*.icm' under directory 'Tests'
    warning: no files found matching '*.txt' under directory 'Tk'
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext
    building 'PIL._imaging' extension
gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ -DHAVE_LIBTIFF -I/usr/include/freetype2 -I/tmp/pip-build-sg4tPn/pillow/libImaging -I/home/kral/readthedocs.org/user_builds/pip/envs/latest/include -I/usr/local/include -I/usr/include -I/usr/include/python2.7 -c _imaging.c -o build/temp.linux-x86_64-2.7/_imaging.o
    unable to execute gcc: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/kral/readthedocs.org/user_builds/pip/envs/latest/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-sg4tPn/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-DlRZbK-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kral/readthedocs.org/user_builds/pip/envs/latest/include/site/python2.7/pillow" failed with error code 1 in /tmp/pip-build-sg4tPn/pillow

[18/Jan/2016 15:07:44] INFO [readthedocs.doc_builder.environments:284] (Build) [pip:latest] Build finished

**Comment by ericholscher** [comment]
We don't support Read the Docs on Centos via our open source project. We do provide commercial support, if you're interested more information is here: http://docs.readthedocs.org/en/latest/support.html#commercial-support
