### ISSUE TITLE
Support HTTPS for rtfd.org short URLs?

### ISSUE THREAD

**Issue by pdehaan** [rtfd/readthedocs.org#1952]
Currently if I go to the following link, it doesn't work in Firefox or Chrome, saying that the connection is not secure:

https://loadsv2.rtfd.org/

I can use HTTP and the redirect works, but doesn't redirect to the HTTPS site.

**Workaround:** Don't use short URLs and specify the full HTTPS URL everywhere: https://loadsv2.readthedocs.org/ (plus it's only 6-7 chars longer).

**Comment by marcelstoer** [comment]
Or use http://j.mp/1S13EXq which is even shorter than the rtfd.org address (albeit less memorable).

**Comment by agjohnson** [comment]
Yes, this has been raised before. The `rtfd.org` domain doesn't have a wildcard cert as it's not in the budget. `readthedocs.org` is the correct domain to use.
