### ISSUE TITLE
Versions do not seem to be working for doc.picklesdoc.com

### ISSUE THREAD

**Issue by dirkrombauts** [rtfd/readthedocs.org#1953]
Hi,

I'm trying to use the Versions feature on http://docs.picklesdoc.com/. The build process pickles up the versions from the tags and shows them in the popup thing on the bottom left hand side of the pages, but when I click on the version links I am sent into virtual nirvana.

I realize that this is probably not enough information for you to tell me what I'm doing wrong. What information do you need?

Thank you for you time!

**Comment by agjohnson** [comment]
This is a known issue with Mkdocs. There is a PR open for a fix somewhere, but it was blocked on a Mkdocs release. Closing this as a duplicate.
