### ISSUE TITLE
Errors with importing and building

### ISSUE THREAD

**Issue by chief93** [rtfd/readthedocs.org#1954]
Hello
I registered today at `rtfd`. When I tried to import my repo from `github`, I saw that screen:
![e1](https://cloud.githubusercontent.com/assets/2089568/12532605/cfd07fb6-c220-11e5-9bcf-0e1991160b12.png)
Not clear documentation for import process =\ I changed name to `QuarkDocs`, and then it was created. Then, I tried to build documentation, but got `nginx` `404` standart http error on created docs  URL http://quarkdocs.readthedocs.org/en/latest/ Other languages got me `rtfd` not found error

Building process was finished with no erros, that says `rtfd` build log. I tried to build few times with same result.

**Comment by agjohnson** [comment]
It would be helpful to hear your thoughts on what we could do better here.

The error above, though not translated, describes the error state aptly -- another user had a project with the same name as yours. Projects are hosted as subdomains on the domain `readthedocs.org`, and so two cannot exist in the same namespace.

The error with not finding your documentation is because you didn't configure your documentation correctly with Mkdocs. The docs you are trying to serve are found here:

http://quarkdocs.readthedocs.org/en/latest/README/

**Comment by chief93** [comment]
Yes, this second user was me, because after registering, I clicked on Import and `rtfd` redirected me at  OAuth github dialog. After that, I was redirected back, BUT my `rtfd` session was inactive, so github authorized other wrong created account

**Comment by pvital** [comment]
@agjohnson I also had the same error (404 - not found) with my project, and you are correct. I don't have any configuration file to rtfd and my docs directory has a README.md but none index.md file. 

However, the official rtfd documentation in  http://docs.readthedocs.org/en/latest/builds.html#mkdocs says "Then Mkdocs will build any files with an .md extension. If you have a README.md, it will be transformed into an index.md automatically.". My understanding is that an official index page will be *automatically* available in my readthedocs page and will not be necessary access the README directly.

**Comment by agjohnson** [comment]
@pvital ah yes, that might be a matter of old documentation. We did have this feature, but it was difficult to ensure and was eventually removed

**Comment by agjohnson** [comment]
@chief93 you should have the project under your original account then. though you might now have two rtd accounts due to an additional oauth signup

**Comment by chief93** [comment]
@agjohnson my original account is that, I can't access wrong created account. And this is your failure, because my session was terminated unexpextedly after few minutes! If you can't resolve this issue, please remove wrong created account and wrong imported repositories, I will try to import in that right account.

**Comment by stsewd** [comment]
@chief93 I'm not sure if still have this issue, but I really don't understand the steps you made to have 2 accounts.

> I was redirected back, BUT my rtfd session was inactive, so github authorized other wrong created account.

What another account? (GitHub? rtd?)

Although, the original report (404 page) was already documented (rtd doesn't rename the README file to index anymore).

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, we can move the conversation about the index file on https://github.com/rtfd/readthedocs.org/pull/3635 https://github.com/rtfd/readthedocs.org/issues/1960 https://github.com/rtfd/readthedocs.org/issues/1800
