### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by par2** [rtfd/readthedocs.org#1956]
I have a build that sometimes times out trying to build my docs.  It seems to consistently timeout trying to build `pandas` which is listed in my requirements file.  It there a reason why the builds fail on rtds, while the same build passes on travis in less time?

**Comment by agjohnson** [comment]
if this is an intermittent failure, it's likely because we have to rotate our cached repository files aggressively.

If your question is how to reduce build time, look into mocking out pandas if you don't directly need it for your build.

**Comment by par2** [comment]
The issue resolved itself without me changing anything.  I suspect your first supposition is correct.

**Comment by agjohnson** [comment]
Closing this, if it's still an issue, feel free to reopen.

**Comment by par2** [comment]
I've had some issues with my builds timing out half the time.  I've managed to get by with rebuilding.  However, after my latest commits, I'm unable to build.  I don't understand the issue as I have not changed anything build related.  I've only added more content to my existing docs, yet I'm timing out.  Is there something that can be done server side to help?

**Comment by agjohnson** [comment]
You should look into mocking out pandas and removing that from your list of installed requirements. The wheel build step is taking a long time to complete. Alternatively, if you need pandas to generate your documentation, look into conda.

**Comment by par2** [comment]
Yes, I would prefer to use miniconda as I do need pandas to generate the docs.  Can you point me to how I can set miniconda up on RTDs? 

UPDATE: I suppose [this](http://read-the-docs.readthedocs.io/en/latest/conda.html) is the current documentation for setting up conda.  I will try this.

**Comment by par2** [comment]
Experimenting with the yamls, I was able to reduce the build time from 900 secs to as [low as 66 secs](https://readthedocs.org/projects/lamana/builds/4019595/), though I'm uncertain what is happening on the backend.  For those interested, here are yaml files for my package which requires `pandas`, `matplotlib`:

```
# readthedocs.yml
conda:
    file: docs/environment.yml

python:                                 # specify python on the os
	version: 3

# docs/environment.yml
name: project_docs
dependencies:
- matplotlib                           # needed for my sphinx conf.py
- pandas                               # speeds up build 
- pip                                  # misc. sphinx dependencies
  - nbsphinx==0.2.2
  - ipykernel==4.2.2
  - numpydoc==0.5
```
