### ISSUE TITLE
Upgrade to pip 8

### ISSUE THREAD

**Issue by erikrose** [rtfd/readthedocs.org#1958]
pip 8 introduces a new [hash-checking mode](https://pip.readthedocs.org/en/stable/reference/pip_install/#hash-checking-mode) which makes backward-incompatible changes to the requirements file syntax. It would be great if readthedocs would support pip 8 so projects using RTD can also use this feature. Perhaps all that is necessary is to upgrade to pip 8 and/or virtualenv 14.0.1 at https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L2-L3. (virtualenv embeds pip.)

**Comment by agjohnson** [comment]
This should be fine, we'll want to test the new version of course. A PR for this should be easy enough and would kick start our testing.

**Comment by jezdez** [comment]
As requested a PR to update to pip 8. Let me know if you think this needs more work.

**Comment by Osmose** [comment]
Any guesses on when this will be up on the site? No rush, just curious. :D
