### ISSUE TITLE
Cannot build a Japanese PDF

### ISSUE THREAD

**Issue by hitsumabushi** [rtfd/readthedocs.org#1959]
# Problem

A document containing Japanese cannot build PDF properly.
# Example

https://readthedocs.org/projects/ja-sample/ ( [souce repo](https://github.com/hitsumabushi/read_the_docs_example_ja) )

You can find differences between HTML and PDF.
PDF doesn't contain any Japanese words. (Author name, Section name, and sentences)
Seeing [a build log](https://readthedocs.org/projects/ja-sample/builds/3672977/), you can find errors in the step of `pdflatex`.
(I pasted a log to https://gist.github.com/hitsumabushi/7487f403ecd1b8435984.)

---

I think this is because of using `pdflatex` command directory.
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/sphinx.py#L279-L283

``` python
        pdflatex_cmds = [
            ['pdflatex',
                '-interaction=nonstopmode',
                tex_file]
            for tex_file in tex_files]
```

In Sphinx's Makefile, (I don't know why,) use `platex` command for Japanese documents.
https://github.com/sphinx-doc/sphinx/blob/master/sphinx/texinputs/Makefile#L24-L32

```
all-pdf-ja:
    for f in *.pdf *.png *.gif *.jpg *.jpeg; do extractbb $$f; done
    for f in *.tex; do platex -kanji=utf8 $(LATEXOPTS) $$f; done
    for f in *.tex; do platex -kanji=utf8 $(LATEXOPTS) $$f; done
    for f in *.tex; do platex -kanji=utf8 $(LATEXOPTS) $$f; done
    -for f in *.idx; do mendex -U -f -d "`basename $$f .idx`.dic" -s python.ist $$f; done
    for f in *.tex; do platex -kanji=utf8 $(LATEXOPTS) $$f; done
    for f in *.tex; do platex -kanji=utf8 $(LATEXOPTS) $$f; done
    for f in *.dvi; do dvipdfmx $$f; done
```

Could you change the command or create options for building document contains Japanese?

**Comment by agjohnson** [comment]
The actual changes for this might be fairly minimal, but it would require some thorough testing. If `platex` can be dropped in for `pdflatex`, it should be possible to selectively execute `platex` instead, based on the project's language setting.

Marking this as a community enhancement, as this is slightly off our radar currently. We're happy to guide anyone that can take this on however.

**Comment by stsewd** [comment]
I'm closing this issue in favor of https://github.com/rtfd/readthedocs.org/issues/1556, where we are considering platex too. @hitsumabushi would be great if you could help up us with some feedback on the other issue.
