### ISSUE TITLE
README.html not serving over placeholder documentation

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1960]
Seems we aren't clearing out built documentation on syncing, which is a problem if users want to host README.html. In this case, it seems the files sync, but there is no index.html to overwrite the placeholder index.html, and so it still serves.

**Comment by stsewd** [comment]
We don't convert README files to index files anymore, so I'm not sure if this is still relevant (or maybe I misunderstood the issue)
