### ISSUE TITLE
Python 3.5 support with conda build

### ISSUE THREAD

**Issue by ostrokach** [rtfd/readthedocs.org#1962]
Right now Python 3.5 packages fail to install at line:

```
conda install --yes --name update_docs sphinx==1.3.1 Pygments==2.0.2 docutils==0.12 mock==1.0.1 pillow==3.0.0 sphinx_rtd_theme==0.1.7 alabaster>=0.7,<0.8,!=0.7.5
```

because there is a conflict between `mock==1.0.1` and `python 3.5*`:

```
Hint: the following packages conflict with each other:
  - mock ==1.0.1
  - python 3.5*
```

Can the dependencies be loosened up to just:

    conda install --yes --name update_docs sphinx Pygments docutils mock pillow sphinx_rtd_theme alabaster

Example for a failed build: https://readthedocs.org/projects/elaspic/builds/3676155/.

**Comment by ericholscher** [comment]
I think it makes sense to at least unspecify the version requirement on `mock`. Feel free to send a PR to fix this.

**Comment by ostrokach** [comment]
I unspecified the version requirement on `mock`. 
However this still feels fragile, since another package may get mismatched with another Python version.

Maybe it would be better if installing `sphinx`, `Pygments`, `mock`, etc. was delegated to the owner of the package, through their `environment.yml` file?

Or at least include the custom channels from the users `environment.yml` file when installing `sphinx` and friends, so that the user could compile their own versions of `mock`, for example, and have it installed from their channel on anaconda.org?

**Comment by ericholscher** [comment]
This seems to work for now. I don't know the best way to handle Conda's incredibly strict versioning requirements, as we do have to install our own dependencies for builds (mainly just our own plugins and extensions)

**Comment by agjohnson** [comment]
Closing this as this seems to be resolved. Feel free to reopen if not.
