### ISSUE TITLE
move to sphinx 1.3.5

### ISSUE THREAD

**Issue by wm75** [rtfd/readthedocs.org#1966]
sphinx 1.3.4 introduced this bug: https://github.com/sphinx-doc/sphinx/issues/2247
, which breaks builds of projects using definition lists containing regular expression like strings.

This was considered a high priority bug by the sphinx devs and was fixed with version 1.3.5.
Please move to the new version so that I can again build my docs.

**Comment by kmarsteller** [comment]
Is this as simple as a one-character fix to change the sphinx version in requirements/pip.txt?

**Comment by ericholscher** [comment]
You can specify a specific Sphinx version in your requirements file, and we'll install it over our default.

**Comment by agjohnson** [comment]
Reopening this as we should test and change our dependencies for sphinx still. Anyone that requires the latest release should use an override though.

**Comment by wm75** [comment]
Thanks for reopening this.

While adding a working sphinx version to your requirements file is a workaround (thanks for pointing it out), I'd like to stress that this is a bug in just one specific version of sphinx so affected docs would build with any sphinx **except** 1.3.4.
Just conceptually I find it the wrong approach to tell people to adjust their repos because you are building their docs with buggy software. The right solution, IMO, is still to move on to v1.3.5 or, alternatively, go back to 1.3.3.

**Comment by kmarsteller** [comment]
Perhaps I'm misunderstanding the work-around mentioned above, but I have had a requirements.txt in my docs directory since I started using readthedocs, and I have had the path to it set in my Admin->Advanced Settings.  In that docs/requirements.txt file, among other items, I have `Sphinx==1.3.1`, but my docs are still getting built with 1.3.4?  Looking back at past builds, it seems that the requirements.txt has not been respected all along, and my build just happened to work?  Sorry if this is the wrong place to discuss this; if it is, we can move this discussion elsewhere.

**Comment by agjohnson** [comment]
@wm75 we just can't flip a switch and deploy it -- vetting and all that. 1.3.5 is our next target and it will be pinned as soon as we can verify the new release.

**Comment by wm75** [comment]
Sure, no problem waiting. The requirements file works for me for the time being.

**Comment by kmarsteller** [comment]
Is anyone else seeing this behavior?:

I am using the requirements.txt file to pin Sphinx == 1.3.1:
[my requirements.txt](https://github.com/OpenMDAO/OpenMDAO/blob/master/openmdao/docs/requirements.txt
)

Sometimes my builds seem to respect that and use 1.3.1 (and pass):
[passing build](https://readthedocs.org/projects/openmdao/builds/3713502/)

Other times, (in this case, the very next build) the requirements.txt seems to be ignored, and the build uses 1.3.4 (and hence, fails):
[failing build, hours later](https://readthedocs.org/projects/openmdao/builds/3717889/)

I'm not changing anything docs-related in the code between builds.  Anyone have any ideas?
Thanks.

**Comment by ericholscher** [comment]
This is weird, on the failing build it says its installing:

`  Using cached Sphinx-1.3.4-py2.py3-none-any.whl`

But then on the list of installed packages, it's:

`sphinx-1.3.1`

Seems like this is a bug with pip perhaps. We haven't deployed the upgraded pip 8, so maybe that will help fix it.
