### ISSUE TITLE
Document static collection step

### ISSUE THREAD

**Issue by bjackson1** [rtfd/readthedocs.org#1967]
Hi,

I've followed the documented process here http://read-the-docs.readthedocs.org/en/latest/install.html to create a local installation.  Most things seem OK, but the theme content seems to be missing.

> [31/Jan/2016 02:09:14] INFO [readthedocs.core.views:496] Serving index.html for test1
> [31/Jan/2016 02:09:14]"GET /docs/test1/en/latest/ HTTP/1.1" 200 7494
> [31/Jan/2016 02:09:15]"GET /media/css/sphinx_rtd_theme.css HTTP/1.1" 404 1845
> [31/Jan/2016 02:09:15]"GET /media/javascript/jquery/jquery-2.0.3.min.js HTTP/1.1" 404 1884
> [31/Jan/2016 02:09:15]"GET /media/css/readthedocs-doc-embed.css HTTP/1.1" 200 1660
> [31/Jan/2016 02:09:15]"GET /media/javascript/jquery/jquery-migrate-1.2.1.min.js HTTP/1.1" 404 1908
> [31/Jan/2016 02:09:15]"GET /media/javascript/doctools.js HTTP/1.1" 200 6686
> [31/Jan/2016 02:09:15]"GET /media/javascript/underscore.js HTTP/1.1" 404 1845
> [31/Jan/2016 02:09:15]"GET /media/javascript/readthedocs-doc-embed.js HTTP/1.1" 404 1878
> [31/Jan/2016 02:09:15] INFO [readthedocs.core.views:496] Serving _static/js/modernizr.min.js for test1
> [31/Jan/2016 02:09:15]"GET /docs/test1/en/latest/_static/js/modernizr.min.js HTTP/1.1" 200 15414

It primarily seems to relate to files that are symlinked to a non-existent 'rtd/checkouts/readthedocs.org/media/static' directory.  I'd expect to see a 'static' directory in here https://github.com/rtfd/readthedocs.org/tree/master/media.

I'm not sure if this is an error, or whether the content of this directory is expected to be sourced from elsewhere...

Any help appreciated...
Thanks

**Comment by agjohnson** [comment]
Seems you still need to run django's collect static command.

**Comment by dan-blanchard** [comment]
`./manage.py collectstatic` is not in instructions and probably should be.

**Comment by agjohnson** [comment]
Retriaging this ticket to address documentation updates

**Comment by ericholscher** [comment]
This was fixed in #2026
