### ISSUE TITLE
Feature Request: Run sphinx-apidoc automatically?

### ISSUE THREAD

**Issue by WJCode** [rtfd/readthedocs.org#1972]
We generate our API documentation using a simple `sphinx-apidoc -o docs/API/ ../`.
However, this command would need to be run each time a new module etc. is added. I think it would be a great addition to readthedocs.org if there was an option to run this command automatically.

For example, in our [latest docs](http://coaladocs.readthedocs.org/), we already have an entry in our RST/sphinx toctree that points to the `API/modules` generated by `sphinx-apidoc`.

**Comment by agjohnson** [comment]
Closing this, it is a duplicate of #1139

**Comment by WJCode** [comment]
Oops. Thanks!
