### ISSUE TITLE
'article' documentclass doesn't have blue titlepage

### ISSUE THREAD

**Issue by samwilson** [rtfd/readthedocs.org#1974]
When using the `article` documentclass (as the 5th argument to the `latex_documents` config variable), the title, author, and date lines are not rendered in the same blue sans-serif font as subsequent headers in the document body.

For example:
https://media.readthedocs.org/pdf/assetmanager/latest/assetmanager.pdf

Does anyone know how I might fix this?

**Comment by agjohnson** [comment]
This would probably be more appropriate for the Sphinx issue tracker, we aren't doing anything special to PDF output here.

**Comment by samwilson** [comment]
Have raised it there. Thanks!
