### ISSUE TITLE
Build failed on Windows: "environment can only contain strings"

### ISSUE THREAD

**Issue by vverzellesi** [rtfd/readthedocs.org#1975]
Hi,

I am trying to locally install Read the Docs on Windows. I'm able to run the application and manually import a project.
However, the project is never built. I get an error saying that "environment can only contain strings".

Is Read the Docs really not supported on Windows? Is there any way I can locally run it?

Thanks

**Comment by mukulmishra** [comment]
No thanks.
I don’t need to install git.

**Comment by vverzellesi** [comment]
@ericholscher

**Comment by agjohnson** [comment]
@vverzellesi we don't officially support windows, I'm not sure what work it should take to make it work. The above error doesn't give enough information, I'm not quite sure where that error is coming from.

**Comment by matheusmmo** [comment]
@agjohnson, @vverzellesi  I have the same problem here. For what looks like the file that is causing the error is the https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/vcs_support/base.py#L53.

I tried to set "env=None", the build process starts and in the log gets "Cloning master" (or something like this).

And them my server crashs.

If anyone from the community could help, I'd be glad.

**Comment by ericholscher** [comment]
We offer commercial support, where we would be able to help you with this. You can find more information here: https://readthedocs.com/services/#open-source-support

**Comment by agjohnson** [comment]
Without the actual error or, preferably, stack trace, we can't help diagnose this. But the issue still stands that we can't help support windows very effectively. If anyone can supply the actual error here, it would be helpful.
