### ISSUE TITLE
Chinese docs cannot output PDF

### ISSUE THREAD

**Issue by ups216** [rtfd/readthedocs.org#1983]
I'm trying to write some docs in Chinese but PDFs are not generated correctly, all Chinese text are not shown in PDFs.

example: http://mydocs2016.readthedocs.org/

**Comment by lextm** [comment]
It is more an issue with sphinx. When it generates the LaTex source file, Chinese related TeX modules are not properly added. Will have to report to sphinx.

A blog post claims that it can be solved by editing `conf.py`,

http://seisman.info/chinese-support-for-sphinx.html

**Comment by agjohnson** [comment]
@lextm thanks for the fix, if anyone can confirm, that would be great to document here.

Eventually, I plan on reworking our extension to handle theming our PDF output as well. We might be able to automatically perform this fix based on documentation language if so.

**Comment by stsewd** [comment]
The solution posted is 404 :/. Anyway, closing as duplicated of https://github.com/rtfd/readthedocs.org/issues/1959
