### ISSUE TITLE
PayPal integration possibility

### ISSUE THREAD

**Issue by lextm** [rtfd/readthedocs.org#1984]
Would there be a PayPal option on reathedocs.org besides credit cards?

**Comment by agjohnson** [comment]
At the moment, we don't have plans for implementing Paypal alongside Stripe for donations/subscriptions. This could change in the future, but for now, Stripe gives us a good amount of control of the subscription process, and we'd have to rework all of that for Paypal's model

**Comment by lextm** [comment]
@agjohnson then what about donation via PayPal if that's easier to achieve?
