### ISSUE TITLE
Length of title can prevent version builds

### ISSUE THREAD

**Issue by nedbat** [rtfd/readthedocs.org#1987]
When I try to build the "dogwood" version of "Open edX Building and Running a Course" (https://readthedocs.org/projects/open-edx-building-and-running-a-course/builds/3719787/) it fails with:
```
Build exited due to unknown error: [8] System error: invalid argument
```
I forget what clue lead me to this conclusion, but the problem seems to be code in rtfd that creates a DNS host name from a title and version string.  If this string exceeds 64 characters, it fails.

**Comment by agjohnson** [comment]
We'll address this issue at #1818
