### ISSUE TITLE
Git backend transforming tags/branches incorrectly

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1989]
I had thought that the refactor to version slugs had unified our slugging for VCS versions, but it seems the Git backend is still performing transforms on these names. Is there a reason for this?

For instance, a repository with a tag of "release/foobar" becomes just "foobar" at:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/vcs_support/backends/git.py#L113

Shouldn't the `VersionSlugField` be handling this now?

**Comment by humitos** [comment]
@agjohnson following you example, what should be the correct slug generated, `release-foobar`?

**Comment by agjohnson** [comment]
I think that's fine. The bigger question is why this isn't already happening I suppose. The logic should exist already

**Comment by humitos** [comment]
There are more discussion in the PR, but the thing is that we were transforming the `slug` _and_ the `verbose_name` and we need to transform the `slug` only.

`verbose_name` is used for the "Edit on Github" link for example and GH wants the full name in the URL, even with the `/` on it (`release/foobar`)
