### ISSUE TITLE
http://diamond.readthedocs.org/ returning 404

### ISSUE THREAD

**Issue by jaingaurav** [rtfd/readthedocs.org#1992]
Hi, I manage the diamond project and it seems that for some reason we're getting a 404 for our docs: http://diamond.readthedocs.org/.

I tried deleting and re-creating the project without any luck. Is there any way someone can help?

Thanks

**Comment by loweryaustin** [comment]
Maybe the index.html file is missing or named incorrectly like in this situation?
https://github.com/rtfd/readthedocs.org/issues/737

**Comment by jaingaurav** [comment]
@loweryaustin: Seems like your inital hunch was correct. I think this was likely due to the mkdocs version bump. Trying to fix up my config accordingly

**Comment by jaingaurav** [comment]
Okay seems that mkdocs didn't like that index.md was a symbolic link. Must be a changed behaviour or regression. Thanks for the help, the docs are fixed now.
