### ISSUE TITLE
Please delete Apache Usergrid pages

### ISSUE THREAD

**Issue by snoopdave** [rtfd/readthedocs.org#1993]
We no longer use ReadTheDocs and the docs here are old, out of date and no longer correct. 

Please delete our pages from this site and (if possible).

Our ReadTheDocs page is: http://usergrid.readthedocs.org

Our new and up-to-date docs pages are here: http://usergrid.apache.org/docs/

**Comment by snoopdave** [comment]
I took care of this myself and added a page that links to the official Usergrid docs.

**Comment by agjohnson** [comment]
You can also add a redirect in RTD to external pages.

**Comment by snoopdave** [comment]
Actually, I was not able to delete all of the pages.  I published an empty site to my project, with only a "Our docs have moved" page but still all of the Usergrid subpages exist. They are very old and out of date, really not good to have in search results.

Please delete them.

Thanks!
