### ISSUE TITLE
Please delete OpenStack Designate Docs pages

### ISSUE THREAD

**Issue by grahamhayes** [rtfd/readthedocs.org#1994]
We no longer use ReadTheDocs and the docs here are old, out of date and no longer correct.

Please delete our pages from this site and (if possible).

Our ReadTheDocs page is: http://designate.readthedocs.org

Our new and up-to-date docs pages are here: http://docs.openstack.org/developer/designate

**Comment by kiall** [comment]
FYI I used to be the owner of this project on RTD, but I deleted it a long time ago. To my knowledge, there is currently no "designate" RTD project.

Additionally, http://python-designateclient.readthedocs.org/en/latest/ also needs purging.

**Comment by agjohnson** [comment]
@grahamhayes @kiall is the owner of both projects[1], and will need to be the one to delete them. 

1: https://readthedocs.org/profiles/kiall/

**Comment by humitos** [comment]
Hi people! All the projects linked on the comments give 404, so it seems this issue can be closed. Please, feel free to reopen if you consider. Thanks!
