### ISSUE TITLE
Stable version not detected correctly

### ISSUE THREAD

**Issue by arteymix** [rtfd/readthedocs.org#1996]
It seems like the stable branch is obtained from the latest tag in the `master` trunk rather than the latest tag in the repository.

I disabled the stable build and I manually publish the latest tag myself.

Here's a more explicit example: http://docs.valum-framework.org/en/stable/

**Comment by agjohnson** [comment]
Can you expand on this? I'm not sure I see the issue here.

We obtain git tags by invoking `show-ref`, so whether or not the commit was tagged in master shouldn't matter.

**Comment by arteymix** [comment]
The latest stable version is `v0.2.12`, but it's stuck at `v0.2.6` since then.

I will trigger another build just to make sure.

**Comment by arteymix** [comment]
Yeah, it's still stuck at `v0.2.6`.

**Comment by agjohnson** [comment]
Thanks, I understand the issue now, though still can't answer why our stable is pointing to your most recent master commits

**Comment by arteymix** [comment]
It seems to believe I have a branch named `stable`. I did at some point, but I remove it. It looks like a cache issue to me.

**Comment by agjohnson** [comment]
Oh, this makes more sense then. If you had a branch named stable, our stable pointer won't automatically update. I've updated your version to automatically update, and rebuilt your stable version. Seems to point to the correct commit now.

**Comment by arteymix** [comment]
I can confirm it works!

Maybe `--prune` is missing when you fetch the latest commits?

**Comment by agjohnson** [comment]
We do a prune, but we aren't removing the database objects that represent branches/tags that get removed. This is likely so that versions aren't magically removed, though with an overhaul of the versions page, we should expose some of this state and provide a manual override.

Closing this issue as it seems resolved.

**Comment by arteymix** [comment]
Sounds good to me!
