### ISSUE TITLE
Update docs to describe PDF generation more

### ISSUE THREAD

**Issue by gerv** [rtfd/readthedocs.org#1997]
Steps to reproduce:
- Download http://readthedocs.org/projects/bugzilla/downloads/pdf/latest/
- Note that the TOC only has a single level
- View http://git.mozilla.org/?p=bugzilla/bugzilla.git;a=blob;f=docs/en/rst/conf.py
- Note that pdf_toc_depth = 5
- Be surprised.

Gerv

**Comment by agjohnson** [comment]
I'm actually not surprised :)

RTD explicitly uses the LaTeX builder, which would avoid `rst2pdf` completely. You can do this with the LaTeX builder as well though:
http://stackoverflow.com/questions/20073309/how-to-set-sphinx-and-latexpdf-toc-depth

**Comment by gerv** [comment]
OK. Can I change this bug into a request that you document this fact? As far as I can see, the only docs on RTD's PDF generation is this paragraph:
http://docs.readthedocs.org/en/latest/features.html#pdf-generation

Thanks :-)

**Comment by agjohnson** [comment]
Sure thing, i've re-triaged the ticket. We should describe these steps more, not to mention add some more support docs on common issues with pdf generation.

**Comment by gerv** [comment]
Sorry to use you for tech support, but I've followed the instructions in your link and done this:
http://git.mozilla.org/?p=bugzilla/bugzilla.git;a=blob;f=docs/en/rst/conf.py#l220

and yet I still get only one level of TOC:
 http://readthedocs.org/projects/bugzilla/downloads/pdf/latest/

Where have I gone wrong?

**Comment by agjohnson** [comment]
That I don't know, this is getting into an area that I've only experimented with. I have never attempted to override the latex TOC. You might have more luck with someone from the Sphinx community that knows more about latex.

**Comment by gerv** [comment]
Any suggestions on who to ask or where to ask? :-)

**Comment by humitos** [comment]
> Sure thing, i've re-triaged the ticket. We should describe these steps more, not to mention add some more support docs on common issues with pdf generation.

@agjohnson I'm not following you here, the sphinx documentation about latex isn't enough? http://www.sphinx-doc.org/en/stable/latex.html

It doesn't mention specifically the `'preamble': '\setcounter{tocdepth}{1}'` but that's something that I'm not sure it should go in RTD documentation.

**Comment by agjohnson** [comment]
I think we can probably leave this out of our docs, yeah. Sphinx would be a better spot. I should add this to my list of blog posts too, actually -- I've experimented a little here. This this can be closed for now
