### ISSUE TITLE
Update Google Analytics code

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#1998]
We are currently pushing the old `ga.js` legacy tracker, we should update this to use the new GA tracker code.

**Comment by humitos** [comment]
@agjohnson can you explain this one a little more?

**Comment by jessetan** [comment]
@humitos Google Analytics has functionality that is not available if using the legacy `ga.js`, but requires the newer `analytics.js` with a different API.
Information about upgrading: https://developers.google.com/analytics/devguides/collection/upgrade/

**Comment by stsewd** [comment]
This issue was solved on #3495 (already merged).
