### ISSUE TITLE
The whl installation stops suddenly

### ISSUE THREAD

**Issue by kozo2** [rtfd/readthedocs.org#2000]
I don't know why this whl installation was killed.
I would like to ask your advice on
http://readthedocs.org/projects/ecell4/builds/3736390/

**Comment by agjohnson** [comment]
The exit code implies there was an uncaught out of memory condition during installation. The wheel being installed is 138M, so I assume that has something to do with the error.

**Comment by agjohnson** [comment]
Looks like the changes in https://github.com/ecell/ecell4/commit/f8ec641e0af1a3d26b8ac697fbf9c000be2f1691 may have resolved this issue. Closing it here, but feel free to reopen if the fix didn't resolve your problem fully.

**Comment by kozo2** [comment]
Could you reopen this issue?
https://github.com/ecell/ecell4/commit/f8ec641e0af1a3d26b8ac697fbf9c000be2f1691
is reduced one (some features are disabled).
I tried the 100MB over whl again, and it has still failed.
https://github.com/ecell/ecell4/commit/f7817187837cdfbbfb9c512eefec9db1c9fec1a7
https://readthedocs.org/projects/ecell4/builds/3767552/

Could you support 100MB over whl?

**Comment by kozo2** [comment]
I reopened this issue in https://github.com/rtfd/readthedocs.org/issues/2033

**Comment by agjohnson** [comment]
Best to reopen it here. Not sure what is best to do, as this is pretty far out of our normal usage. Do you even need the module to generate your docs, or is it an installation dependency? You can mock out installation dependencies in your `conf.py` if that's the case:
http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by humitos** [comment]
It seems that most of the latest build are succeed. So, I'm closing this issue. Please, feel free to reopen if you consider. Thanks!
