### ISSUE TITLE
On premise read the docs without github or bitbucket.

### ISSUE THREAD

**Issue by fatagun** [rtfd/readthedocs.org#2001]
Hello,

I wanted to ask you and find out if we can deploy read-the-docs locally and use it for documenting our software projects. However we are not using Github or bitbucket. We are only interested in documenting the projects along with the versioning feature of it.

Can you please let me know if we can do this with the on premise install?

Thanks.

**Comment by ericholscher** [comment]
Replied in email.

**Comment by joaobentes** [comment]
I'd like also to know how can I have an installation on premise. Could you share this email with me?

**Comment by fatagun** [comment]
Well they are selling it.

**Comment by ericholscher** [comment]
Yea, I'd recommend https://readthedocs.com if you need private repos. We are trying to reduce our investment in even paid private installs, because they aren't really a good way to make money.
