### ISSUE TITLE
Docs not getting updated

### ISSUE THREAD

**Issue by SeanHayes** [rtfd/readthedocs.org#2003]
I submitted a question on SO:
http://stackoverflow.com/questions/35415494/when-do-docs-get-updated-on-readthedocs-org

Project name: django-tastypie
URL: http://readthedocs.org/projects/django-tastypie/
Action taken: pushed to master in Git
Expected result: latest docs should get built, new tags should show up
Actual result: latest docs aren't updated, new tags don't show, or only show up after a number of days

Also, I have push access on GitHub, but I'm not able to access the project on RTD. Do I have to contact our project owner, or is this something the RTD admins can help with?

**Comment by agjohnson** [comment]
It sounds like the webhook is missing from the project. The owner of the RTD project shouldn't need to do anything special. As long as the URL in the RTD project matches the GitHub http url, it should update.

**Comment by SeanHayes** [comment]
Thanks, I'll look into it!
