### ISSUE TITLE
Query: is self-hosting part of the design plan?

### ISSUE THREAD

**Issue by kwill** [rtfd/readthedocs.org#2005]
We are considering how to host Python documentation on our intranet. This would include private Python modules, and clones of public modules (limited to the specific version(s) we use).

Is self-hosting RTD part of the current or long term design plan? In an ideal world, this would mean that we could `sudo apt install python-readthedocs` on an intranet server, and configure which local repos we generate docs from.

Right now it looks like this should be possible with the current codebase (just requires a bit more effort than `sudo apt` ;) ), but I want to find out how sustainable and supported this approach (self-hosting) is before committing to it. Thanks for a great service!

**Comment by toogy** [comment]
Self-hosting RTD is already supported, isn't it?

**Comment by agjohnson** [comment]
Yeah, RTD is open source, you're free to host on your own. We provide paid support for external installations, and we started readthedocs.com to provide the same service you're describing.

Self hosting will require knowledge of hosting django, celery, as well as a database and message queue such as redis.

**Comment by kwill** [comment]
This is now answered fully by http://docs.readthedocs.io/en/latest/custom_installs/index.html

It *is* part of the design plan, but support *is not* provided by the development team (which is perfectly understandable, Linus doesn't provide me with personal support for my kernel installation).

> Read the Docs is open source, which means you can run your own version of it. There are many reasons to do this, the main one being if you want a private instance. If you have to keep everything behind a firewall or VPN, this is for you.
>
> > Warning
> >
> > Read the Docs developers do not support custom installs of our software. These documents are maintained by the community, and might not be up to date.

**Comment by kwill** [comment]
Also http://docs.readthedocs.io/en/latest/open-source-philosophy.html
