### ISSUE TITLE
Downloadable docs are updated, some online HTML is not

### ISSUE THREAD

**Issue by xesscorp** [rtfd/readthedocs.org#2008]
## Details

If this issue is for a specific project or build, include the following:

* Project: https://kifield.readthedocs.org/en/latest/
* Build #: latest

I updated the docs on my github project and rebuilt on readthedocs (both automatically and manually) with no reported errors. But the online documentation (in particular, the usage page) is not updated to the latest version. However, the downloadable versions of the documentation (pdf, html and epub) do include the most current documentation. I've also rebuilt the docs locally with the makefile and those are correct.

I'm not sure what else to do to make the online version show the latest documentation.

**Comment by agjohnson** [comment]
The commit at the bottom of the page matches the content. Perhaps this was transient? We had some intermittent issues with doc serving from one of our web servers in the last week.

**Comment by xesscorp** [comment]
Yes, it seems OK now. Sorry for the bother. Thanks for looking at it!

**Comment by agjohnson** [comment]
No problem, thanks for reporting! Feel free to reopen if you are noticing this issue again.

**Comment by acecross** [comment]
I'm having a similar issue with my Project: https://readthedocs.org/projects/impro/
Downloadable versions are build correctly, but the online version isn't updated.
Especially weird: 
https://impro.readthedocs.io/en/latest/impro.analysis.html?highlight=analysis#module-impro.analysis 
gives me the updated html while: 
https://impro.readthedocs.io/en/latest/impro.analysis.html#module-impro.analysis
doesn't. The second link has a slight difference in the html header:
<link rel="next" title="impro.data package" href="impro.data.html" />
<link rel="prev" title="Welcome to impro’s documentation!" href="index.html" />

**Comment by stsewd** [comment]
@acecross it may be cache/cdn, try cleaning your browser cache, or wait some minutes in case it's the cdn.

**Comment by acecross** [comment]
@stsewd Thanks for your support. It works fine right now. Probably was the browser cache.
