### ISSUE TITLE
'Domain with this Domain already exists' Error

### ISSUE THREAD

**Issue by emqplus** [rtfd/readthedocs.org#2009]
## Details

Thanks for the awesome project, I am moving the wiki of my project from github to RTD. I try to configure a 'docs.emqtt.io' domain for 'emqttd_docs' project, but the Admin always report 'Domain with this Domain already exists' Error.
- Project: emqttd_docs

**Comment by agjohnson** [comment]
Yeah, that's an awful error message. It's supposed to imply that the domain has already been configured for another project.

**Comment by erylee** [comment]
@agjohnson, I searched 'emqtt' on readthedocs.org and the result: https://readthedocs.org/search/?q=emqtt&version=latest&type=project&language=en. 

We could still find the project 'docs.emqtt.io' that has been removed a few days before. How to delete this project permanently?

**Comment by Auroch** [comment]
I misconfigured my domains for the project (https://readthedocs.org/projects/cahier-de-notes/). I added auroch.be and bollingh.eu, but in fact I really needed docs.auroch.be & docs.bollingh.eu. So I removed the two domains and when I try to add the two correct versions, I get the message: "Domaine with this domain already exist", but they are already removed from my admin page, so I can't do anything by myself. Could you help me please?

**Comment by mvantellingen** [comment]
Hitting the same issue when I try to add www.python-zeep.org to http://docs.python-zeep.org/
I might have added the www.python-zeep.org to a project which I then removed again during some experimenting.

**Comment by erylee** [comment]
@agjohnson, could we resolve this issue manually?

**Comment by agjohnson** [comment]
@erylee sure, if you own the project already using the domain

**Comment by Auroch** [comment]
OK and how ?
Because m'y issue is I already own m'y project. I've deleted the previous
entry to my own domain.com and it prompt the error when I try to add
doc.domain.com.

**Comment by stsewd** [comment]
Is anyone still having this problem?

**Comment by stsewd** [comment]
So, this works as Anthony mentions, if another project add a custom domain, that can't be used by another project (different user even). So, if someone has this problem, please feel free to open a new issue so the team can manually remove the other domain, also you need to verify that you really own the domain.
