### ISSUE TITLE
allow users to pick if package should be installed with pip

### ISSUE THREAD

**Issue by minrk** [rtfd/readthedocs.org#2011]
## Details

There is a system-wide config for whether "install this package" should mean `pip install .` or `setup.py install`. It would be useful for packages to be able to specify, at least in the `setup.py install` case that's on the official deployment, that `pip install .` should be used for their package.

**Comment by agjohnson** [comment]
This might be worth exploring as part of our push to move configuration into a top-level `readthedoc.yaml` configuration file.
