### ISSUE TITLE
broken short path links on docs.deis.io

### ISSUE THREAD

**Issue by bacongobbler** [rtfd/readthedocs.org#2012]
## Details

* Project: deis

[Short path links](http://docs.deis.io/en/latest/installing_deis/quick-start) return a 404 OK, but [the full path works](http://docs.deis.io/en/latest/installing_deis/quick-start.html). As far as I know we haven't touched anything on our end. Is there something we can do to fix this?

Thank you! :cherry_blossom:

**Comment by agjohnson** [comment]
Assuming you meant the second link to be:
http://docs.deis.io/en/latest/installing_deis/quick-start.html

In that case, you're describing the difference between HTML and HTML directory Sphinx builders:
http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.StandaloneHTMLBuilder
http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.DirectoryHTMLBuilder

RTD subclasses these, there is an option in your project settings to handle this. Might this have changed?

**Comment by bacongobbler** [comment]
Thanks! It wasn't immediately apparent to me that "Sphinx HTML" and "Sphinx DirHTML" are two different build types.
