### ISSUE TITLE
Dependency issue for autodoc

### ISSUE THREAD

**Issue by ajing** [rtfd/readthedocs.org#2014]
## Details

If this issue is for a specific project or build, include the following:

* Project: ChemTreeMap
* Build #: 3763463

My project need to install rdkit for full installation, but rdkit doesn't support pip install. I want to have autodoc to generate the beautiful documentation for API. It works great on my computer, but it doesn't work on readthedoc. Is there any way to get around this?

**Comment by agjohnson** [comment]
Do you need `rdkit` for your documentation generation, or is it just a dependency for installation? If it is just an installation dependency, mock out the dependencies:
http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

This also requires specifically not installing all of your dependencies -- either with a limited `requirements.txt` or not installing via `setup.py`.

**Comment by ajing** [comment]
Thanks!

For adding mock library, do I need to put mock in requirements.txt or setup.py? requirements.txt should be under the root of the repository, right?

**Comment by ajing** [comment]
For mock, could I mock multiple levels of classes?

As I have to import rdkit.Chem, how could I do that with the example?

```python
class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
            return Mock()

MOCK_MODULES = ['rdkit', 'rdkit.Chem']
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

This doesn't seem to work.

**Comment by ajing** [comment]
OK, I think I get it work. Thanks!
