### ISSUE TITLE
Read The Docs TOC Footer Not Loading and Throwing Errors

### ISSUE THREAD

**Issue by sahilTakiar** [rtfd/readthedocs.org#2015]
## Details

If this issue is for a specific project or build, include the following: 

* Project: http://gobblin.readthedocs.org/en/readthedocs/
* Build #: latest

When loading the project page, the Chrome Inspect tool throws an error saying: `Failed to load resource: the server responded with a status of 404 (NOT FOUND) https://readthedocs.org//api/v2/footer_html/?callback=jQuery211025191313796…2Fcheckouts%2Freadthedocs%2Fgobblin-docs&source_suffix=.md&_=1456430887845 `

and `Error loading Read the Docs footer $.ajax.error @ readthedocs-doc-embed.js:1`

I notice that the Read the Docs tab on the bottom left of the screen (at the bottom of the main TOC) is not loading. I'm guessing these are related, but any idea why this is happening? Is this a bug? Has anyone else seen this issue?

<img width="319" alt="screen shot 2016-02-25 at 12 11 20 pm" src="https://cloud.githubusercontent.com/assets/1282583/13332876/eb7d73ca-dbb8-11e5-9c54-7851873c9871.png">

**Comment by sahilTakiar** [comment]
For reference my `mkdocs.yml` file is here: https://github.com/linkedin/gobblin/blob/readTheDocs/mkdocs.yml

The docs are checked into the following branch of this GitHub Project: https://github.com/linkedin/gobblin/tree/readTheDocs and are under the folder `gobblin-docs`

The ReadTheDocs Admin Page is here: https://readthedocs.org/projects/gobblin/
The ReadTheDocs Home Page is here: http://gobblin.readthedocs.org/en/readthedocs/

**Comment by agjohnson** [comment]
For some reason, the URL requested includes an incorrect version slug of: `&version=readTheDocs`. It should be the version slug, ie:`&version=readthedocs`. This seems like whatever Mkdocs is using here is incorrect.

**Comment by agjohnson** [comment]
Seems this is where it is wrong:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/mkdocs.py#L101

**Comment by sahilTakiar** [comment]
Thanks a ton for the investigation @agjohnson 

Should I go ahead and open an Issue on the Mkdocs GitHub?

If the change is as simple as `'version': self.version.verbose_name,` to `'version': self.version.slug,` I can create the PR too

**Comment by agjohnson** [comment]
A PR would be :100: I believe that change should be enough. I don't use Mkdocs and haven't tested this however.

**Comment by sahilTakiar** [comment]
I checked http://gobblin.readthedocs.org/en/readthedocs/ and this is working now thanks everyone!
