### ISSUE TITLE
ImportError 

### ISSUE THREAD

**Issue by mcocdawc** [rtfd/readthedocs.org#2016]
At first thanks for your great project!

Since several weeks I tried to get my functions imported and documented with autodoc, 
but it does not work, since I always get an ImportError. Could you help me?
I try to give you all the background information about what I did:

## Steps
* Local compilation of the documentation with different sphinx versions on computers I had access to, works without any problem. (my sphinx version is v.1.3.5)
* Since my project is relying on python 3.x, I set the virtual env tick in your ``advanced settings`` together with specifying python 3.x as interpreter.
* I set the tick ``use system packages``, since I use C compiled modules but only default ones like numpy. (``REQUIRES=['numpy', 'pandas', 'copy', 'math', 'collections', 'os', 'sys', 'io']``)
* I wrote a ``requirements.txt`` and tried several combinations of ``pip installing`` modules. My current version includes numpy, pandas, chemcoord.
* You can install my module via pip. 

## Details

* Project: https://github.com/mcocdawc/chemcoord
* Build #: 3759282  (and any previous ones)
* ProjectURL: http://chemcoord.readthedocs.org/en/latest/

**Comment by agjohnson** [comment]
If you don't need the dependencies directly for you docs, that is, if they are only dependencies for installation, then you should mock out those modules in your `conf.py` and not install them.

http://docs.readthedocs.org/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by mcocdawc** [comment]
Thank you very much for your answer.

I tried to include the following snippet into my conf.py file in the beginning.
```python
from unittest.mock import MagicMock
class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return Mock()

MOCK_MODULES = ['numpy',
                'pandas'
                ]

sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```
If I compile the doc locally with `make html` it raises now a `RecursionError`.

**Comment by mcocdawc** [comment]
After some fiddling around I found a solution but stumbled over a new problem. Since this could be a bug and is definitely different to this issue I opened a new one (#2075).
