### ISSUE TITLE
Dutch translations

### ISSUE THREAD

**Issue by roelofr** [rtfd/readthedocs.org#2018]
## Details

I would love to help bring a Dutch version of ReadTheDocs online, but no such language category is available in Transifex. Could you perhaps make one?

Thank you.

**Comment by agjohnson** [comment]
That would be great! I'll update when one of us has made the change.

**Comment by roelofr** [comment]
Can I get a follow up on this, since there are still no translations available.

**Comment by agjohnson** [comment]
Following up, albeit late: we've had Dutch translations for a while now: https://www.transifex.com/readthedocs/readthedocs/language/nl/
