### ISSUE TITLE
Remove unsupported options from Mkdocs project footer

### ISSUE THREAD

**Issue by sahilTakiar** [rtfd/readthedocs.org#2024]
## Details

If this issue is for a specific project or build, include the following:
- Project: http://readthedocs.org/projects/gobblin/
- Build #: latest
- Version: readthedocs
- Documentation: http://gobblin.readthedocs.org/en/readthedocs/

It seems the ReadTheDocs footer is now generated for our project, thanks everyone for the help in https://github.com/rtfd/readthedocs.org/issues/2015 and https://github.com/rtfd/readthedocs.org/pull/2017

Still having a few issues though with the ReadTheDocs footer that is auto-generated:
- The "Downloads" for PDF, HTML, and ePub don't seem to work
  - I did some digging and MkDocs doesn't seem to support these, which is fine, but how do I remove them from the footer so none of our users get confused?
- The "On GitHub" links don't seem to work either, is there I way to manually set them?
  - The "View" links to here https://github.com/linkedin/gobblin/blob/readTheDocs/home/docs/checkouts/readthedocs.org/user_builds/gobblin/checkouts/readthedocs/gobblin-docs/index.md
  - The "Edit" links to here https://github.com/linkedin/gobblin/edit/readTheDocs/home/docs/checkouts/readthedocs.org/user_builds/gobblin/checkouts/readthedocs/gobblin-docs/index.md
  - Neither of these links exist

**Comment by agjohnson** [comment]
There is no way to currently set these, it should be handled server side. The footer should be altered for mkdocs projects, so I'll triage this as a bug there. We should remove these download options.

The issue with github links is a known issue

**Comment by sahilTakiar** [comment]
Thanks @agjohnson for the explanation. I went ahead and opened on issue on the MkDocs GitHub Repo: https://github.com/mkdocs/mkdocs/issues/849

**Comment by agjohnson** [comment]
These changes are strictly in Read the Docs, we need to alter how we are passing the flyout content to mkdocs projects

**Comment by stsewd** [comment]
Related to https://github.com/rtfd/readthedocs.org/pull/4041

**Comment by stsewd** [comment]
I don't see the download options for mkdocs projects anymore, only htmlzip (if this option is activated). For the another issue, it's kind of solved, more info in #1820
