### ISSUE TITLE
Delete Usergrid content from ReadTheDocs

### ISSUE THREAD

**Issue by snoopdave** [rtfd/readthedocs.org#2029]
We no longer use ReadTheDocs and the docs here are old, out of date and no longer correct.

Please delete our pages from this site and (if possible).

Our ReadTheDocs page is: http://usergrid.readthedocs.org
Our new and up-to-date docs pages are here: http://usergrid.apache.org/docs/

I was able to create a page that points to our new docs site, but all of our content still appears to be on RTD and are showing up in Google results, confusing our users with old and incorrect information. 

Please help us clear this up.

**Comment by ericholscher** [comment]
Sure, I can delete it. Curious why you've moved to hosting it yourself?

**Comment by snoopdave** [comment]
We are an Apache project and want to host on Apache infrastructure.

**Comment by agjohnson** [comment]
404s for me, closing.
