### ISSUE TITLE
Allow normal users to use API, and clean up API docs

### ISSUE THREAD

**Issue by peterbe** [rtfd/readthedocs.org#203]
The docs say this snippet should work:
http://readthedocs.org/docs/read-the-docs/en/latest/api.html?highlight=user#example-of-adding-a-user-to-a-project

First of all, with the latest slumber, the way to do authentication is to use:
```
api = slumber.API("http://slumber.in/api/v1/", auth=("demo", "demo"))
```

I keep getting 401 Unauthorized errors when trying to PUT. I tried regular curl on the command line too with http://username:pwd@readthedocs.... and that's also giving me 401 errors.

**Comment by gregmuellegger** [comment]
Closing this as we have the **Maintainers** tab in the projet's admin panel now.
