### ISSUE TITLE
spaces in code blocks in PDF improperly rendered

### ISSUE THREAD

**Issue by AvdN** [rtfd/readthedocs.org#2030]
## Details

If you have properly indented code or YAML as in my case and try to copy and paste this
from the generated PDF, the result is unusuable as spaces are not rendered properly
in the PDF. In the image you see the text highlighted and both spaces before the dashes,
as well as between key and value in the mapping should be highlighted so that copy is enabled.

![missing_spaces](https://cloud.githubusercontent.com/assets/1210650/13397995/a7e0b068-defc-11e5-827e-94f481be574f.png)

**Comment by agjohnson** [comment]
You didn't provide a link to your project, so I can only guess. If this isn't an issue with tab/spaces, it might be a bug in Sphinx's rendering of this. Best to move this issue there. Feel free to reopen if you feel there is more to the issue and it is a problem with RTD.

**Comment by AvdN** [comment]
This is a generic RST->PDF problem. The spaces are not rendered, instead offsets are used even in the code sections, where spaces would make more sense.
