### ISSUE TITLE
Safer automation for LaTeX compilation

### ISSUE THREAD

**Issue by elfring** [rtfd/readthedocs.org#2037]
[The program "pdflatex"](https://tug.org/applications/pdftex/ "Information about pdfTeX") is called several times in [the script for the documentation generation](https://github.com/rtfd/readthedocs.org/blob/f5eb95d5a4ebb3ee2a8a68015b1d94dd4eaa00f9/readthedocs/doc_builder/backends/sphinx.py#L278 "Run conversions for LaTeX to PDF").
How do you think about to process LaTeX input files by [a higher-level software build system](https://ctan.org/topic/compilation "Doc­u­ment com­pi­la­tion pro­cess for LaTeX")?

**Comment by agjohnson** [comment]
What would this afford us? It seems to complicate the build steps

**Comment by elfring** [comment]
Do you know all software components on which [TeX source files](https://en.wikipedia.org/wiki/TeX "Description for usage of TeX") might [depend on](https://ctan.org/pkg/texdepend "Finding dependencies in LaTeX files") for your documentation generation?

**Comment by agjohnson** [comment]
This sounds like a Sphinx question. I'm not sure there is anything actionable here. Closing for now.
