### ISSUE TITLE
Difference between project search page results and in doc search results

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2039]
There should be some overlap here, but in a project that defaults back to the sphinx search due to missing results, searching on the RTD project page results results. There is a difference in the query here, but the in doc page should be returning _more_ results.

**Comment by ericholscher** [comment]
@agjohnson do you have an example of this anywhere to test against?

**Comment by agjohnson** [comment]
I'll keep an eye out, we should probably explicitly QA docs for a bit to test this. It might not be and issue or it might have been a transient issue.
