### ISSUE TITLE
Clean up pyflakes errors on star import

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2040]
Disregarded for now in: https://github.com/rtfd/readthedocs.org/commit/cb5461939eb8de1f5e1396acf3479febf0eda712

**Comment by berkerpeksag** [comment]
The only file that uses `from ... import *` is `readthedocs/core/utils/tasks/__init__.py`. It should be an easy fix so I'm marking this as 'Good First Bug'.

**Comment by kamyarrasta** [comment]
I suppose this should be closed by 5f8d596

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by kamyarrasta** [comment]
sure!
