### ISSUE TITLE
Unable to import organization repo

### ISSUE THREAD

**Issue by davidchall** [rtfd/readthedocs.org#2044]
I would like to import the topasmc/topas-docs repo into ReadTheDocs. When I go to the import page, I can only see my personal repos (none of the organization repos). This is a public repo, and I checked that I am publicly a member of the organization.

Do I need to somehow register with RTD the fact that I am a member of this organization?

**Update:** I found that I could import the project using the "manual import" option. But does this mean that anyone could have added this repo to their account? Or it does authentication via the manual import? It would be nice if this function had some more documentation, since I found this confusing.

**Comment by agjohnson** [comment]
Not sure why the repo doesn't show for you. The organization could have privacy settings that require authorization of 3rd party applications perhaps?

Manual import will work on any public repository, GitHub integration just takes care of adding repo webhooks back to RTD.

**Comment by davidchall** [comment]
Thanks for your response. I suppose it doesn't matter too much now that we have it working.

**Comment by lafrech** [comment]
For the record, I was in the same situation: RTD only seeing my own repos on GitHub. By default, it doesn't have access to orgnizations' repos.

To request/grant RTD access to an organization, follow the steps in https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/.

See https://help.github.com/articles/about-oauth-app-access-restrictions/ for more context.
