### ISSUE TITLE
all builds failed "Server Error 500: https://readthedocs.org//api/v2/command/"

### ISSUE THREAD

**Issue by ups216** [rtfd/readthedocs.org#2046]
all builds were working yesterday and started failing today, I have 2 projects under 2 different accounts, both failed. 

error message

Server Error 500: https://readthedocs.org//api/v2/command/

**Comment by agjohnson** [comment]
This is known issue, there is a duplicate ticket with similar issues. It seems a load based issue with our api endpoints. Closing this here.

**Comment by ups216** [comment]
@agjohnson it happened again today. looks like this issue happens during the weekend? is there any scheduled job somewhere affecting the site?

**Comment by ups216** [comment]
it's working again now

**Comment by agjohnson** [comment]
Nope, the issue is completely intermittent, more dependent on load. I've made some changes to our infrastructure today, am seeing if that has any effect on this.

Tracking the issue at #2002
