### ISSUE TITLE
Take ownership of our project on RTD

### ISSUE THREAD

**Issue by patrys** [rtfd/readthedocs.org#2048]
Our project (https://readthedocs.org/projects/saleor/) was initially added by someone who is not a contributor and someone we cannot get in contact with. We'd like to take ownership of the project and get control over its page on RTD.

I am the maintainer of Saleor on behalf of Mirumee Software: https://github.com/mirumee/saleor

Thanks for your work on RTD!

**Comment by ericholscher** [comment]
What is your RTD account now?

**Comment by patrys** [comment]
It's [`patrys`](https://readthedocs.org/profiles/patrys/).

**Comment by ericholscher** [comment]
Should be setup now.
