### ISSUE TITLE
Install cloned project with conda build?

### ISSUE THREAD

**Issue by dotsdl** [rtfd/readthedocs.org#2053]
I'm using [conda](http://docs.readthedocs.org/en/latest/conda.html) to build the necessary environment for building the docs for my package [datreant.data](https://readthedocs.org/projects/datreantdata/). However, the reason I needed conda in the first place was to get autodoc to properly build the docs on import of the module, for which the module must first be installed. It's not clear to me that the package is being installed *a la* `python setup.py install` after being cloned from GitHub. [Here is a recent build](https://readthedocs.org/projects/datreantdata/builds/3802786/) for reference.

Without conda the way to make this happen was to check the box labeled "Install your project inside a virtualenv using setup.py install". But with conda, this doesn't appear to have any effect. Is there a known solution to this issue?

**Comment by ericholscher** [comment]
How would we conda install your project? Just `conda install setup.py`?

**Comment by dotsdl** [comment]
To my knowledge conda can only pull from conda repositories; it cannot install from source. If you want to install a python project from source you would typically do either `python setup.py install` or `pip install .` when in the package source directory. If the conda environment is already active, then using `pip` should put it into the same environment.

**Comment by ericholscher** [comment]
Do you have the proper setting in your YAML? http://docs.readthedocs.org/en/latest/yaml-config.html#python-setup-py-install

**Comment by dotsdl** [comment]
Ah cool: using the [`python setup.py install`](http://docs.readthedocs.org/en/latest/yaml-config.html#python-setup-py-install) option works well for this.
