### ISSUE TITLE
Add conda channels to RTD yaml

### ISSUE THREAD

**Issue by jrkerns** [rtfd/readthedocs.org#2055]
As best I can tell, the RTD yaml will make a conda env from your conda yaml using the default channels. It would be nice to have the ability to prepend channels to the conda env before getting the packages, as some custom packages are not in the default channels. Something like this in the RTD yaml:

     conda:
         file: environment.yml
         channels: 
             - mycustomchannel1
             - mycustomchannel2

**Comment by willingc** [comment]
@jkerns Not sure it this fits your use case but we do use channels in the Project Jupyter docs. We use a `readthedocs.yml` in the root of our repo and an `environment.yml` in our `docs`. An example can be found in https://github.com/jupyter/nbconvert. We specify the channels in the `environment.yml`.

**Comment by jrkerns** [comment]
It does fit! I couldn't find any full docs about the conda env file to know if I could add channels, but it appears so. Thanks @willingc.

**Comment by willingc** [comment]
@jrkerns Glad it helped.
