### ISSUE TITLE
Builds using conda are broken due to pygments

### ISSUE THREAD

**Issue by dean0x7d** [rtfd/readthedocs.org#2059]
The conda requirements were recently updated with 'pygments==2.1.3' (#2050) but the latest version available in the main conda channel is 2.1.1. Now all conda builds fail with the message:
```
Error: No packages found in current linux-64 channels matching: pygments ==2.1.3
```
See the full build log here: https://readthedocs.org/projects/pybinding/builds/3806323/

**Comment by ericholscher** [comment]
Sorry about that. Just deployed a fix.
