### ISSUE TITLE
virtualenv is not installed for python3

### ISSUE THREAD

**Issue by suanmeiguo** [rtfd/readthedocs.org#2062]
## Details

When installed the repo under python2 (which is in default for most of OS), and then add a python3 project (set the python interpreter to CPython3.x), build will fail with following error:

```
/usr/bin/python3: No module named virtualenv
```

Because the app is trying to run the command `python3 -mvirtualenv --no-site-packages`.

**Comment by agjohnson** [comment]
What is this in reference to? Is this a local installation? This requires Python 3 and virtualenv for for Python 3 installed on your host OS, it's nothing RTD attempts to automate.

**Comment by suanmeiguo** [comment]
You're right. It would be nice to clarify this in the document.

**Comment by agjohnson** [comment]
Seems it's missing, feel free to contribute an addition to the page.
