### ISSUE TITLE
custom domain setting lost

### ISSUE THREAD

**Issue by pkra** [rtfd/readthedocs.org#2063]
## Details

Project: https://readthedocs.org/projects/mathjax/

## Description

A few hours ago, a user alerted us that our subdomain docs.mathjax.org had stopped working. Not sure if it's relevant but docs.mathjax.org was still redirecting to http://docs.mathjax.org/en/latest/ which in turn gave a readthedocs 404 page.

I admit I don't remember whether the setup of a subdomain has changed since we set this up years ago. But following the documentation, I noticed that the admin settings for the custom domain were empty. 

After I added it, things are back to normal.

As we haven't triggered a build in a few weeks and things were working ok yesterday, I'm a little confused how this happened. 

The only problem I still see is a warning on the project page 

```
This repository doesn't have a valid webhook set up. That means it won't be rebuilt on commits to the repository
. 
You can resync your webhook to fix this.
```

However, resyncing the webhook does not prevent the error message from showing up while GitHub is showing a working webhook.

Things are ok now but since I don't understand how it happened, I wonder if there's a problem lurking somewhere.

If you happen to have some advice, I'd greatly appreciate it.

Thanks again for providing such a great tool!

**Comment by ericholscher** [comment]
The site seems to be working for me. Is this still an issue?

We just recently deployed some changes to how we handle Nginx & CNAME routing, so there might have been a short window when it was breaking. Also, if the version privacy level was set to `Private`, that would have stopped it from displaying.

**Comment by pkra** [comment]
> The site seems to be working for me. Is this still an issue?

As I wrote, everything went back to normal after I added the domain again in the admin settings.

What I don't understand is how it got lost. Was there ever another way to configure a custom domain? If not, then the setting was simply lost yesterday. (Maybe that's a bug but you'll know better than me.)

> We just recently deployed some changes to how we handle Nginx & CNAME routing, so there might have been a short window when it was breaking. 

Interesting. All I can say is that the chronologically first report was [22h ago](https://github.com/mathjax/MathJax-website/issues/55) and it was still an issue 11h ago (just before I filed this issue :wink: ).

>  Also, if the version privacy level was set to Private, that would have stopped it from displaying.

I think I can rule that out as a cause since the settings haven't been touched in over 6 months.

**Comment by pkra** [comment]
Feel free to close. I primarily filed this in case this was caused by a bug that might affect other repositories. Thanks again for a great service!

**Comment by ericholscher** [comment]
Aye, thanks for the report. We've had some logic in middleware to automatically create Domain objects for the past few months, and so your project must have somehow gotten missed by that code. We just recently depreciated the auto-creation as well, so it must have been the switch over to using Domain objects, and for some reason the old Domain porting code missed it.

**Comment by pkra** [comment]
Thanks for the background, @ericholscher, and thanks again for readthedocs!

**Comment by rmzelle** [comment]
I'm seeing the same error:

```
This repository doesn't have a valid webhook set up. That means it won't be rebuilt on commits to the repository.
You can resync your webhook to fix this. 
```

But when I look at https://readthedocs.org/dashboard/citation-style-language/domains/, it still shows docs.citationstyles.org as an existing domain. I haven't tried resyncing the webhook yet.
