### ISSUE TITLE
sphinx build fails with Unicode encode/decode error (and insufficient context from build)

### ISSUE THREAD

**Issue by jenisys** [rtfd/readthedocs.org#2068]
## Details

I have problems with the RTD builds of my project.
* Project: python-behave
* Build #: 3813119 (and earlier, version: latest)

Error: 
```'ascii' codec can't encode character u'\ufffc' in position 80: ordinal not in range(128)```

Note that my normal sphinx-builds show no problem at all.
Wiping the "latest" and "stable" versions on "readthedocs.org" did not help.

It would be much easier if you would provide more details (like a stack trace) to identify the problem location (at least for the project admin).

**Comment by ericholscher** [comment]
It seems you somehow added an invisible ASCII code into the `conf_py_file` (`\ufffc`) variable when you set it on your project. This caused us to generate an invalid path to your conf.py which contained unexpected Ascii. 

Should be fixed now.

**Comment by jenisys** [comment]
Thanks.
