### ISSUE TITLE
SQLAlchemy bulids failing due to "killed" 90% of the time now

### ISSUE THREAD

**Issue by zzzeek** [rtfd/readthedocs.org#2069]
SQLAlchemy almost can't build at all on RTD anymore, due to the "killed" issue which if I understand correctly is strictly due to a build taking up too much resources (im not sure if these are time resources, memory, or what).

https://readthedocs.org/projects/sqlalchemy/builds/

I often have to put out fires with my SQLA RTD builds because of things like upgrades or template changes on the RTD side, but because I have a pretty custom build I know those are "my fault" and as yet they haven't been enough reason for me to move back to self-hosted.  But if RTD is no longer able to support large documentation due to straight up resource overload, then please let me know so I can get on with moving off of RTD, rather than having failures come up all the time.

**Comment by ericholscher** [comment]
I bumped SQLa to have 2GB of memory and a 2 hour build time limit. Hopefully this should be enough.

**Comment by zzzeek** [comment]
they seem to be building now thanks!
