### ISSUE TITLE
Remove "Edit on Github" from header & Commit SHA Revision from Footer on readthedocs.org built docs

### ISSUE THREAD

**Issue by brianjking** [rtfd/readthedocs.org#2073]
## Details

Hello,

When using http://readthedocs.org with the ReadTheDocs theme is it possible to remove the following elements? If so, how? I couldn't find anything in the documentation about this, if I overlooked it, please point me in the right direction.

- Edit on Github link in header
- In footer there's a "Revision #######" after the copyright message. Is there a way to remove this?

Thanks!

* Project: _Not specific to any project nor build._
* Build #: _Not specific to any project nor build._

**Comment by agjohnson** [comment]
Yes, with template overrides in your `_template` path. The Sphinx docs have some more on this if you are unfamiliar.

**Comment by brianjking** [comment]
Thanks @agjohnson. I checked out http://www.sphinx-doc.org/en/stable/templating.html as well as a few other issues as well as StackExchange and I'm stumped.

If you can help specifically with the "Edit on Github" piece I'd greatly appreciate it, if not, I understand and you can go ahead and close the issue.

Thanks for everything. :+1:

**Comment by brianjking** [comment]
@agjohnson Seems this is discussed in #681 and #743, however, it's not working based on my understanding of the issue. I also added in the suggested details from https://github.com/snide/sphinx_rtd_theme/issues/205 to no avail. 

It looks like the lines are actually not related to layout.html, but actually `breadcrumbs.html` as seen in https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/breadcrumbs.html#L16-L19.

Are you saying to override this I should grab the full breadcrumbs.html, add this to my repo in a `_templates` folder, then it should work?

Thanks!

**Comment by brianjking** [comment]
I ended up figuring this out myself and updated my StackOverflow question about this with the answer.

http://stackoverflow.com/questions/36019670/removing-the-edit-on-github-link-when-using-read-the-docs-sphinx-with-readthed
