### ISSUE TITLE
Issue using conda environment

### ISSUE THREAD

**Issue by tritemio** [rtfd/readthedocs.org#2074]
## Summary

I tried the using conda environment with [fretbursts](https://github.com/tritemio/FRETBursts) to see if I can get rid of the mocking layer.

However, building the docs fails on RTD unless I reintroduce the mocking for scipy.

## Details

* Project: http://readthedocs.org/projects/fretbursts/
* Build #: 
   - Not Working: http://readthedocs.org/projects/fretbursts/builds/3813468/
   - Working: http://readthedocs.org/projects/fretbursts/builds/3813474/

Commit between "Working" and "Not Working":
https://github.com/tritemio/FRETBursts/commit/d9e642167e51756e581443b99dbc9f8573cb3271

**Comment by ericholscher** [comment]
This looks like an error on a C module, `libgfortran.so.1`, not on anything we can install with Python or Conda. We likely don't have a Fortran compiler on our build servers, and aren't planning to include one.

**Comment by tritemio** [comment]
@ericholscher, this is plain scipy. Are you saying that scipy cannot be installed on RTD? Conda packages are precompiled and should include all these binaries AFAIK.

**Comment by ericholscher** [comment]
Well, the install of the conda scipy seemed to work fine. I'm not sure why this particular library is missing. This seems more like a conda issue, or something in the way we're using it, which I'm not really able to debug.

**Comment by tritemio** [comment]
@ericholscher, yes seems a missing library on RTD that is required by scipy's conda package.

**Comment by Korijn** [comment]
Related: https://github.com/conda/conda/issues/444

**Comment by jakirkham** [comment]
Yeah, this is definitely a conda issue. I believe they relinked some stuff to `libgfortran.so.3` (no idea how they are doing versioning with this stuff), but some packages are still linked to `libgfortran.so.1`. This issue is related. ( https://github.com/conda/conda/issues/2177 ) Though it couldn't hurt to open a new one with `conda`.

**Comment by agjohnson** [comment]
Closing the issue here, as this doesn't seem to be an issue with RTD. Feel free to reopen if there is anything actionable here.

**Comment by Korijn** [comment]
Something "actionable": is the pre-installed conda pinned to a specific version on RTD or do you always run `conda update conda`? Conda 4.x came out recently and it fixed a large number of important bugs related to package resolution.

**Comment by agjohnson** [comment]
Is this an issue of an out-dated conda? This doesn't seem to be an issue of a wrong conda version, as the conda ticket above notes that it was a packaging issue.

**Comment by jakirkham** [comment]
I don't think so. That is an orthogonal issue I believe. I have placed it in this issue ( https://github.com/rtfd/readthedocs.org/issues/2076 ) and cc'd the two of you on the ticket.
