### ISSUE TITLE
Strange behaviour while circle importing

### ISSUE THREAD

**Issue by mcocdawc** [rtfd/readthedocs.org#2075]
Hello, 

I have a big class `Cartesian` in a module `xyz_functions` and a big class `Zmat` in a module `zmat_functions`.

Since `Cartesian` and `Zmat` have to be transformed into each other, they have a method 
`to_zmat` and `to_xyz`. For this reason I have a line `from . import zmat_functions` in my `xyz_functions` module and a `from . import xyz_functions` in my `zmat_functions` module.

Local compilation of the documentation with different sphinx versions on computers I had access to, works without any problem. (my sphinx version is v.1.3.5)

Compilation on readthedocs only works if I comment at least one of the circle imports out.
For this reason I tagged one version as v1.0.0 with outcommented `from . import zmat_functions` in my `xyz_functions` module. 

I have now a `rtd_test` branch and a tag `v1.0.0` with the only difference that in `v1.0.0` one of the circle imports is outcommented. As you can see in
- http://chemcoord.readthedocs.org/en/v1.0.0/xyz_functions.html
- http://chemcoord.readthedocs.org/en/rtd_test/xyz_functions.html

This causes an `ImportError` in `rtd_test`.
## Details
- Project: https://github.com/mcocdawc/chemcoord
- Build: 3822047

**Comment by agjohnson** [comment]
> Compilation on readthedocs only works if I comment at least one of the circle imports out.

What do you mean by "only works"? I see passing builds, is there output missing somewhere? This seems to be an authoring issue, not a bug with RTD.

**Comment by mcocdawc** [comment]
If you look for example at the documentation part under ``rtd_test`` you can see, that it has problems with Importing:
http://chemcoord.readthedocs.org/en/rtd_test/xyz_functions.html

And if you look at the output of Build 3825573 (which is the last one of ``rtd_test``) it also complains about an ImportError.
