### ISSUE TITLE
I install the readthedocs in win7. But something goes wrong.

### ISSUE THREAD

**Issue by mazhenhit** [rtfd/readthedocs.org#2081]
## Details

I build a project named template:
- Project: template
- Build #: 
  python: can't open file 'D:\rtd\checkouts\readthedocs.org\user_builds\template\envs\stable\bin\pip': [Errno 2] No such file or directory

I do not know why?

**Comment by agjohnson** [comment]
Was the virtualenv established in `D:\rtd\checkouts\readthedocs.org\user_builds\template\envs\stable\bin\pip`?

**Comment by mazhenhit** [comment]
python 2.7.11
pip install virtualenv
virtualenv rtd
cd rtd
Scripts\activate
mkdir checkouts
cd checkouts
git clone https://github.com/rtfd/readthedocs.org.git
cd readthedocs.org
pip install -r requirements.txt
python manage.py migrate
python manage.py createsuperuser
python manage.py loaddata test_data
python manage.py runserver

then I open 127.0.0.1 and login
create the project template (git@github.com:readthedocs/template.git)
but a ERROR:
 python: can't open file 'D:\rtd\checkouts\readthedocs.org\user_builds\template\envs\stable\bin\pip': [Errno 2] No such file or directory

**Comment by idizh** [comment]
Looks like I have the same problem https://github.com/rtfd/readthedocs.org/issues/2434
But as I understand it depends on OS Windows, virtualenv stores files in Scripts folder instead of bin.

**Comment by skral** [comment]
readthedocs doesn't seem to support building on Windows. In order to get to build docs successfully on a Windows 7 machine I had to change code in a couple of places. Look at the compare [here](https://github.com/skral/readthedocs.org/compare/master...skral:build_html_on_windows?diff=split&name=build_html_on_windows). I didn't take the time to make it nice but might help someone else.

**Comment by travcunn** [comment]
Do we want to officially support Windows 7 here?

**Comment by stsewd** [comment]
RTD doesn't support Windows right now (it depends on symlinks for generating the docs)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

And also as mention above, rtd doesn't support building docs on Windows.
