### ISSUE TITLE
How can I assign a label to an issue, as instructed by your docs?

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2083]
## Details

The RTD docs say to label issues, but when I look at the Issues list, there are no checkboxes to select issues so I can label them. 

http://docs.readthedocs.org/en/latest/contribute.html

**Comment by willingc** [comment]
@barbara-sfx To label issues, a contributor would need to have that privilege on the repo to add labels. 

The linked document talks about labeling by someone triaging issues. Usually a contributor becomes a triager after working with an open source project for a while. If you would like to help triage issues, I would just let the maintainers know that you are interested.

**Comment by agjohnson** [comment]
@barbara-sfx Thanks for your interest, @willingc is correct. We can't give access to triage without giving out commit bit to users. Hopefully, some day GitHub will address this. Until then, feel free to chime in on any support issues or requests, we're glad to have the help!

We're still formalizing how we can direct new users and users interested in contributing, we'll try to improve those docs more to offer some guidance.
