### ISSUE TITLE
take over funcsigs project?

### ISSUE THREAD

**Issue by rbtcollins** [rtfd/readthedocs.org#2084]
Myself and @harlowja recently took over maintenance of funcsigs (https://pypi.python.org/pypi/funcsigs) when Aaron lost interest/moved on. I'm just working through the backlog of PR's before doing our first release, and I realised that we can't update the rtfd docs since it points at Aaron's github repo.

Ideally we'd get it pointing at the new home @testing-cabal/funcsigs, and with one of me / harlowja owning it but failing that, disabling it so that folk don't see old documentation in google would be good.

You can see on the PyPI record page - "Package Index Owner: Joshua.Harlow, lifeless, Aaron.Iles" that we're owners now. (I haven't removed Aaron in case he chooses to come back, but its coming up on three years :) so I'm not holding my breath).

**Comment by rbtcollins** [comment]
ping ?

**Comment by harlowja** [comment]
I'm fine with helping maintaince just fyi.

I've got a couple readthedocs sites, and they've always worked well for me.

**Comment by agjohnson** [comment]
If you have any contact with Aaron, the projects can be transferred to your RTD account if he has access to his account still. As long as we have permission, we can also make that change.

**Comment by rbtcollins** [comment]
We can try again, but we spent nearly a year getting enough contact to get the pypi record moved over in the first place, so I don't hold much hope.

**Comment by humitos** [comment]
We have a policy regarding abandoned projects now that maybe interesting for you, http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by agjohnson** [comment]
Closing this due to activity, feel free to kick off the process noted in our docs for abandoned projects if you'd like assistance.
