### ISSUE TITLE
Can't download doc over HTTP

### ISSUE THREAD

**Issue by nojhamster** [rtfd/readthedocs.org#2089]
## Details

Download links (PDF/HTML/EPUB) lead to a "_Fail.  Check back in a bit!_" when trying to access them in HTTP. Since the navigation is in HTTP by default when coming from the project page, I guess it's not the intended behaviour.

**Comment by agjohnson** [comment]
Both the links on the dashboard and the links from doc pages download the generated docs okay for me. Is this still a problem for you? Both requests should redirect to HTTPS pages, but I don't think that would be an issue.

**Comment by nojhamster** [comment]
My bad, the browser won't follow the redirection of HTTP links from the doc pages, but requesting the same links from the command line works. It seems that the problem comes from my side, maybe some issue with our corporate proxy. Thanks !

**Comment by agjohnson** [comment]
Interesting. Well feel free to include more information if you have any. It might be an issue on your side, but something we can address on our side. Chances are you aren't the only one noticing the problem.
