### ISSUE TITLE
Allow to build documenation of projects in subdirectories

### ISSUE THREAD

**Issue by whimboo** [rtfd/readthedocs.org#2097]
## Details

If a project is part of a larger repository and located in a sub directory, the generation of the documentation will fail because the "setup.py install" command cannot be executed. As it looks like RTD only checks the top folder but not the folder where the project is located in. 

So you can specify the path to a requirements.txt file in the advanced config: `testing/puppeteer/firefox/requirements.txt`. That works fine and is processed. But there is no way to configure the path to the setup.py file.
- Project: https://readthedocs.org/projects/firefox-puppeteer/

As a workaround we may be able to put a separate requirements.txt file for specifically RTD, but I feel that should not be necessary.

**Comment by sydvicious** [comment]
Since the packages that the requirements.txt file needs have to be in pypi, and my package, dom/media/text/external (external-media-tests) is not in pypi, a special requirements file is not going to work.

**Comment by agjohnson** [comment]
This would be a great addition to our focus on a `readthedocs.yaml` configuration file. It's a bit too edge case to support as a UI option, we're moving these sort of features into a configuration format at https://github.com/rtfd/readthedocs-build

This will require some changes here of course, once it is added. The core team might not have enough time for this, but feel free to take this on, we're happy to provide any guidance!

**Comment by ChrisCummins** [comment]
I would love this feature, without it users can't use autodoc for projects in subdirectories.

I would make the case that this would *simplify* the UI. The two options we have at the moment are:

<img width="618" alt="screen shot 2016-10-26 at 17 14 16" src="https://cloud.githubusercontent.com/assets/1636663/19734522/c275cb7e-9b9f-11e6-87ee-c3767e3235bc.png">

The way I read those are:

1. Tick this box to run `python ./setup.py install`
1. Type a path in this box to run `pip install -r <path>`.

Why not have two textboxes?

1. Type a path in this box to run `cd $(dirname <path1>) && python $(basename <path1>) install`
1. Type a path in this box to run `pip install -r <path2>`

I would be happy to implement this, although acknowledging that I've no knowledge of how any of readthedocs works, and am simply happy such a service exists, even if it doesn't work for my use case :)

**Comment by stsewd** [comment]
@agjohnson I think we can close this in favor of https://github.com/rtfd/readthedocs.org/issues/4354

**Comment by stsewd** [comment]
Yep, it's the same as #4354
