### ISSUE TITLE
Ordering of Markdown files

### ISSUE THREAD

**Issue by mattcoker** [rtfd/readthedocs.org#2098]
I've been digging through the existing documentation, and have yet to find an answer to this question. How can I force an order for Markdown files for a project?

For example, I have 3 files in my documents, and would like for them to be in the following order:

- index.md
- dependencies.md
- build-process.md

However, the default is descending alphabetical order, giving me the following:

- index.md
- build-process.md
- dependencies.md

I know index.md is reserved and identified as the project documentation "home page", but it appears that after the index page, everything is in alphabetical order.

**Comment by barbara-sfx** [comment]
I can't believe I actually know the answer to something!

I just got rtd running yesterday, after I installed and read the mkdocs documentation. My pages showed up in the order I put them in my mkdocs.yml file:

site_name: Product Docs
docs_dir: ProductDocs/docs
pages:
- Home: index.md
- Why question: why-question.md
- Quick Start: quick-start.md

**Comment by mattcoker** [comment]
@barbara-sfx Thanks for the speedy response! I thought mkdocs was a totally separate project from Read The Docs. So RTD will automatically see the `mkdocs.yml` file and handle it appropriately?

**Comment by barbara-sfx** [comment]
Yes. I thought they were totally separate as well, but RTD works with mkdocs and sphinx, which I will also be trying. http://docs.readthedocs.org/en/latest/builds.html

**Comment by mattcoker** [comment]
Excellent, tried it myself and it works great! The mkdocs.yml file even supports the `repo_url` value. Thanks!

**Comment by mattcoker** [comment]
Closing because solution was found.
