### ISSUE TITLE
Project name is immutable

### ISSUE THREAD

**Issue by EntilZha** [rtfd/readthedocs.org#2099]
## Details
I (very) recently renamed a project (https://github.com/EntilZha/PyFunctional). I updated relevant details on readthedocs for http://scalafunctional.readthedocs.org/en/v0.6.0/

However, the short urls http://scalafunctional.readthedocs.org and http://scalafunctional.rtfd.org haven't changed. Optimally, I would like to force them to redirect to the new name urls http://pyfunctional.readthedocs.org and http://pyfunctional.rtfd.org which don't exist right now. I looked through the settings, and there doesn't seem to be a way to set these up. Some direction would be great.

**Comment by agjohnson** [comment]
Your project name is currently immutable. If we did support immutable project names, we wouldn't handle redirects. If you change a project name, you lose that namespace completely.

**Comment by berkerpeksag** [comment]
This looks like a duplicate of #1440.
