### ISSUE TITLE
Take ownership of our project on RTD

### ISSUE THREAD

**Issue by robertwb** [rtfd/readthedocs.org#2100]
Cython was added by https://readthedocs.org/profiles/mirror/. I have no idea who this person is, but as lead of the Cython project would like to take ownership of this project. (Both my github and readthedocs username is robertwb.)

**Comment by agjohnson** [comment]
I believe `mirror` is an internal user we use. I can transfer ownership to your user if that is indeed the case.

**Comment by robertwb** [comment]
Yes, that'd be great if you could transfer it to me.

**Comment by robertwb** [comment]
Ping?

**Comment by robertwb** [comment]
Anything I can do to help this along?

**Comment by agjohnson** [comment]
Lost track of this. It is indeed an internal mirror, I can transfer this to you. I'll follow up on email.

**Comment by agjohnson** [comment]
Transferred! Thanks for your patience! Closing this here, feel free to reopen if that didn't solve the issue.
