### ISSUE TITLE
Audit of GET requests, pattern for GET requests and CSRF

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2106]
Ensure there are no legacy actions being handled via GET, and for those that we require via GET, create a decorator that wraps CSRF middleware to protect GET requests as well. This does not exist in Django, however we can create a decorator that overrides the middleware `_accept` to also process a GET request.

Refs #2105

**Comment by humitos** [comment]
I think we can close this issue.

When doing some research to remove django strict sessions, I checked all the endpoints, forms and more places to request a CSRF when POST.

None of the GET requests produce write-actions.

Related to https://github.com/rtfd/readthedocs-corporate-ops/pull/127#issuecomment-449119717 and #5009

**Comment by stsewd** [comment]
I think we can close this one too.
