### ISSUE TITLE
Manual configuration of Github web-hook build trigger gives 403  CSRF verification failed.

### ISSUE THREAD

**Issue by julian1** [rtfd/readthedocs.org#2109]
The full Gitbug service integration asks for a lot of privileges - including the email lists of my employer organisation, even if the repo I want to serve is under my personal Gibhub account.  

Instead, I have tried to configure the webhook update manually from Github.

Using the cli, works great, and the docs are correctly rebuilt,

```
curl -v -v  -X POST https://readthedocs.org/build/mcp-profile-docs
```

Configuring Github to hit the same url fails with a 302 redirect to https://readthedocs.org/projects/mcp-profile-docs/builds/

Configuring Github with the redirected url https://readthedocs.org/projects/mcp-profile-docs/builds/ gives a 403

```
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>

  <p>You are seeing this message because this HTTPS site requires a &#39;Referer header&#39; to be sent by your Web browser, but none was sent. This header is required for security reasons, to ensure that your browser is not being hijacked by third parties.</p>
  <p>If you have configured your browser to disable &#39;Referer&#39; headers, please re-enable them, at least for this site, or for HTTPS connections, or for &#39;same-origin&#39; requests.</p>

</div>
```

**Comment by agjohnson** [comment]
You can use the GitHub endpoint at `https://readthedocs.org/github` -- this should be in our docs, feel free to contribute the change if not.

**Comment by posita** [comment]
Manual Github webhooks are documented here:

http://docs.readthedocs.io/en/latest/webhooks.html#github

**Comment by agjohnson** [comment]
We also have a more recent management page for this, found under "Integrations" on the project dashboard. I'd suggest looking at that and the docs on webhooks if you're still hitting issues here.
