### ISSUE TITLE
"Single version" feature broken (yields 404)

### ISSUE THREAD

**Issue by gwillem** [rtfd/readthedocs.org#2110]
First of all, thanks for building and sharing such a brilliant service!

The advanced settings page says:

> [ ] A single version site has no translations and only your "latest" version, served at the root of the domain. Use this with caution, only turn it on if you will never have multiple versions of your docs.

But when enabled, the [root of my domain](http://hypernode-docs.readthedocs.org/) gives a 404. It does serve the index at [/en/latest/](http://hypernode-docs.readthedocs.org/en/latest/) but this seem to contradict the "single version" characteristics (I would expect there would not be `latest` in the URI).

[Example build](https://readthedocs.org/projects/hypernode-docs/builds/3874785/)

**Comment by barbara-sfx** [comment]
Your site looks fine to me.

**Comment by gwillem** [comment]
... because I had disabled `single version` to convince my colleagues of RTD :)
 
For your convenience, I have re-enabled it and yes, the [frontpage gives a 404](http://hypernode-docs.readthedocs.org/) again.

**Comment by akakeronos** [comment]
Hi,
I have the same issue. When I import manually a repository to hook it with RTD it works fine and I have the welcome page showing the nice setup.
It states create

**Comment by gwillem** [comment]
@akakeronos it doesn't sound like you have the same issue. I was reporting a (likely) regression in the "single page" feature of RTD.

**Comment by agjohnson** [comment]
@gwillem I see at least one issue here. I believe we have some changes in the pipeline that address this. Hang tight for now, we're shooting for next week on deployment.

@akakeronos you are noticing something different, you should create an `index.rst` or `README.rst`/`README.md` file, as Sphinx isn't finding any to serve as the root document

**Comment by martindsouza** [comment]
If ti's any help I'm having the same issue: Build passed, but getting `404`s

Build example: https://readthedocs.org/projects/oos-utils/builds/3893521/
404: http://oos-utils.readthedocs.org/en/master/

**Comment by agjohnson** [comment]
@gwillem I believe our latest deploy should have resolved your issue, though looks like your project is gone now

@martindsouza your issue isn't related to single version projects, could you open a new issue to track this?

Going to close this issue for now, but feel free to reopen if the latest operations changes we made didn't have any effect on this issue with single versions.

**Comment by gwillem** [comment]
Thanks for the fix! I still want to move my project over there but am stuck in corporate bureaucracy. Not giving up yet ;)
