### ISSUE TITLE
Delete docs

### ISSUE THREAD

**Issue by jtiret** [rtfd/readthedocs.org#2111]
Hello there,

I need to have the following doc deleted:
http://hipay-tpp-gateway-api.readthedocs.org/en/latest/

It's confusing for our customers. What do you need me to do in order have this documentation deleted?

Thanks in advance!

**Comment by gwillem** [comment]
Log in, go the admin tab, on the bottom of the page is a `delete` link

**Comment by jtiret** [comment]
Hi, I don't have an "admin" tab. Maybe it's because I'm not registered as "owner" of the project. Actually, the owner is a person who is no longer in our our company. However, **I'm owner of the related GitHub organization and repository**. Can I do something?

**Comment by mukulmishra** [comment]
Guys I don’t understand actually.
Why the heck I am getting your message.
I already have unsubscribed from github.

**Comment by agjohnson** [comment]
@mukulmishra you are subscribed to the RTD github project, please unsubscribe there.

@jtiret Because your docs are an open source project, there is nothing permitting other users from forking or hosting your docs here. You'll need to be in touch with the user about transfer of ownership/etc, we can help facilitate this if need be. Ownership of the github project doesn't imply ownership here, and so we can't take down a project without infringing on other user's ability to clone open source documentation.

**Comment by jtiret** [comment]
Hi @agjohnson, thanks for your reply. I'll try to get in touch with the person who has the ownership then. In order to facilitate the transfer, is there any link I can provide the owner with that would bring him directly on the ownership transfer page?

**Comment by jtiret** [comment]
Hi @agjohnson! I have followed your advice and have taken contact with the author for him to delete the doc, which no longer exists: http://hipay-tpp-gateway-api.readthedocs.org/en/latest/

**The problem is that a PDF version still exist in cache and is references on Google**, is it possible to delete it please (as the web version doesn't exist anymore)? Here is the link of that version: https://media.readthedocs.org/pdf/hipay-tpp-gateway-api/latest/hipay-tpp-gateway-api.pdf

Thanks in advance for your help!

**Comment by gwillem** [comment]
Same here, [this PDF](https://media.readthedocs.org/pdf/hypernode-docs/latest/hypernode-docs.pdf) still exists while the corresponding repository doesn't.

Thanks for cleaning up!

**Comment by jtiret** [comment]
Hi @agjohnson! Is there anyway to delete this PDF (as well as @gwillem's): https://media.readthedocs.org/pdf/hipay-tpp-gateway-api/latest/hipay-tpp-gateway-api.pdf 
Thanks in advance

**Comment by sjezewski** [comment]
+1

I also have a tag/version that I need to delete, and although I am and admin, I don't see any place on the admin interface to delete a tag/version or build.

**Comment by humitos** [comment]
Thank you all! I'm closing this issue since all the links mentioned in the comments are 404 now. So it seems that all is fixed/deleted.
