### ISSUE TITLE
Pages don't always load (load balancer issues?)

### ISSUE THREAD

**Issue by marten** [rtfd/readthedocs.org#2112]
Looking at http://zooniverse-aggregation.readthedocs.org/en/latest/. Refreshing this page will sometimes result in a full page load, sometimes the CSS won't load, sometimes the page itself will be a 404 message... Seems like there is load balancing being done but not all endpoints behind the balancer have this repository.

Any ideas would be welcome.

**Comment by agjohnson** [comment]
Yikes, a number of issues there. We have some changes coming hopefully next week to reduce the likelihood of some of these issues. I'll see about manually cleaning things up on the build servers before then.

**Comment by edublancas** [comment]
Does this happen to new builds/projects only? I'm having the same issues http://sklearn-evaluation.readthedocs.io/en/latest/

**Comment by marten** [comment]
It's still happening for us, at least. But only for our latest project, older ones are unaffected

**Comment by ericholscher** [comment]
We have since deployed changes that require each web server to handle their own syncing. This fixes the majority of the cases where this issue was triggered, so I'm going to mark this one as closed.
