### ISSUE TITLE
Hosting private RTD instance

### ISSUE THREAD

**Issue by cgswong** [rtfd/readthedocs.org#2113]
We are trying to host a private RTD instance (following instructions on RTD site) and have gotten an instance up, and sample docs built, but are unable to access the docs themselves as whenever the page redirects to `<project>.<domain>/en/latest` we get a 404. Everything else appears to work.

Any thoughts on what could be wrong here? We've tried fronting with nginx but that didn't do anything differently. # @

**Comment by gwillem** [comment]
If the docs are built but do not show up through http, it is a webserver configuration issue. Which has nothing to do with RTD, so you are better off asking at http://serverfault.com

**Comment by cgswong** [comment]
@gwillem Thanks for the reply. You are correct in that I was doing something silly in my web server config.
