### ISSUE TITLE
readthedocs not reading my mkdocs.yml

### ISSUE THREAD

**Issue by hartsantler** [rtfd/readthedocs.org#2120]
## Details
my documentation works locally when i build it with `mkdocs`, and i have mkdocs.yml in my root.  but when i push a new change, and readthedocs rebuilds it, it fails to find my index.md and generate the home page.  The other pages work, but you have to go to them directly because the TOC was not generated properly.
https://github.com/secureosv/pythia/blob/master/mkdocs.yml

If this issue is for a specific project or build, include the following:

* Project: http://pythia.readthedocs.org
* Build #:

**Comment by barbara-sfx** [comment]
I have no idea why this might be a problem, but in my YML file there is no blank line between docs_dir and the pages: line, and my docs are building correctly.

**Comment by agjohnson** [comment]
@hartsantler your docs were built with Sphinx, not mkdocs
