### ISSUE TITLE
Update to git repo not being reflected in latest build

### ISSUE THREAD

**Issue by sydvicious** [rtfd/readthedocs.org#2122]
## Details

If this issue is for a specific project or build, include the following:
- Project: https://readthedocs.org/projects/firefox-puppeteer/
- Build #: 3887613

There are (many) newer commits on master on https://github.com/mozilla/gecko-dev.git. However, this build always pulls revision b5709cdb58616cd9b39cd0555ca7182949f95785, which is from March 23.

I have tried wiping the builds, and it is not helping. Any ideas as to how to fix this are welcome.

**Comment by mgeier** [comment]
Did you try to "wipe" the version on RTD (see "Versions" tab) and then re-build?

**Comment by garrettr** [comment]
Chiming in to say that I had the same problem on https://securedrop-support.readthedocs.org/en/latest, and "wiping" the "latest" version on RTD, then re-building, resolved the issue for me.

**Comment by barbara-sfx** [comment]
I've been having a similar problem (docs not being updated on push), but on readthedocs.com, where this is no Wipe option. I'm thinking that Wiping might help my problem as well. Is that a forthcoming feature?

**Comment by sydvicious** [comment]
I tried wiping multiple times. Another admin was able to get it build eventually.

**Comment by humitos** [comment]
@sydvicious I saw that latest builds for your project are working properly. Is the issue fixed? Can we close it? It's the same for @garrettr project.

**Comment by sydvicious** [comment]
I no longer work with that project. Feel free to close this issue.
