### ISSUE TITLE
Incorrect webhook URL set for Bitbucket project

### ISSUE THREAD

**Issue by Kemp-J** [rtfd/readthedocs.org#2125]
I imported a Bitbucket project from a linked account and it stated that the webhook was activated. However, my next push didn't trigger a build. It appears that the webhook URL in Bitbucket was set to https://readthedocs.org/bitbucket rather than the https://readthedocs.org/build/[project] that my documentation overview page tells me it should be. Editing the webhook to use the correct URL works as expected.

**Comment by agjohnson** [comment]
`/build/<project>` is a generic post commit that we don't necessarily recommend. Bitbucket webhooks are meant to hit `/bitbucket`. The webhook should work, it's likely you have a version disabled or something.

**Comment by csadorf** [comment]
Even with the correct url https://readthedocs.org/bitbucket , I'm consistently running into a timeout.

![screen shot 2016-07-25 at 4 44 33 pm](https://cloud.githubusercontent.com/assets/1441208/17116763/2a645fe6-5287-11e6-9404-b201003a2cde.png)

**Comment by ganey** [comment]
I'm also consistently getting timeouts or 404's with the URL of https://readthedocs.org/bitbucket

Response body says 'Invalid Request'


It's been this way for a month now, I've given up on the bitbucket webhook working.

**Comment by joserc87** [comment]
I get exactly the same here: an 'Invalid Request' 404. Luckily that workaround with the /build URL works like a charm, so I'm guessing this is not very high priority. If you need the JSON or HTTP headers that cause the 'Invalid Request' let us know though.

**Comment by agjohnson** [comment]
We implemented a new webhook path in the last couple of months. If you are still having trouble with this, try to remove the existing webhook and resync your project webhook. There is an unexposed form to resync this at `http://readthedocs.org/dashboard/<project_slug>/resync_webhook/`

**Comment by agjohnson** [comment]
Further, we recently implemented an entire webhook management dashboard page for projects. If anyone his something similar, just reconnect the webhook from the "Integrations" project dashboard page. Our documentation has more information on managing webhooks.

Closing here due to inactivity.
