### ISSUE TITLE
! LaTeX Error: Undefined color model `HTML'.

### ISSUE THREAD

**Issue by mgeier** [rtfd/readthedocs.org#2127]
This problem occurs e.g. here: https://readthedocs.org/projects/nbsphinx/builds/3896683/

I'm using this in my LaTeX code:

```latex
\definecolor{nbsphinxin}{HTML}{303F9F}
```

This is supposed to work (and works locally) with the `xcolor` package, it will not work with the `color` package.

AFAIK, `xcolor.sty` is available on RTD. Am I right?
So the Sphinx style file `sphinx.sty` should load the `xcolor` package ...

Is there a way to see the generated `.tex` file to check if it looks OK?

**Comment by mgeier** [comment]
This problem is still persisting (that's a recent error page: https://readthedocs.org/projects/nbsphinx/builds/3926118/), could somebody please have a quick look?

**Comment by agjohnson** [comment]
The ubuntu package `latex-xcolor` is in fact installed. Is there another missing package perhaps? It might also be possible that the package is outdated -- ubuntu 14.04 has version `2.11-1.1`. Any idea how old this is, or how it compares to the version you have?

**Comment by mgeier** [comment]
Thanks for checking this out!

It looks like in later Ubuntu (and also Debian) versions, `latex-xcolor` has become a virtual package provided by `texlive-latex-recommended`, but this may not be relevant to the problem.

I don't think it's too old, the problem rather seems to be that `xcolor.sty` isn't found. In `sphinx.sty` this is used to check:

```latex
\IfFileExists{xcolor.sty}{
    \RequirePackage{xcolor}
}{
    \RequirePackage{color}
}
```

I tried to look it up with `kpsewhich` on the RTD server, but there seem to be some problems currently (see https://readthedocs.org/projects/nbsphinx/builds/3966262/ and https://readthedocs.org/projects/nbsphinx/builds/3966421/).

Can you try this on the server?

    kpsewhich xcolor.sty

**Comment by mgeier** [comment]
OK, now RTD seems to work again ...

I tried checking for `xcolor.sty` and it is found with `kpsewhich` at `/usr/share/texmf/tex/latex/xcolor/xcolor.sty` (see https://readthedocs.org/projects/nbsphinx/builds/3969533/).

All looks well, but `pdflatex` still uses `color.sty` instead of `xcolor.sty` ...

I have no clue what's going wrong here ... any ideas?

**Comment by mgeier** [comment]
Now I found the reason!

The selection of `xcolor.sty` vs. `color.sty` was added to Sphinx in version 1.4, I didn't realize this was such a recent feature.

Upgrading to `sphinx>=1.4` in `requirements.txt` solves this issue.

I'm closing this ...
