### ISSUE TITLE
Fix webhook mapping to use a regex

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#2128]
Currently we do some crazy hacking of URL's that is error prone. We should fix the project<->repo mapping to use a regex so that it's more dependable.

**Comment by humitos** [comment]
Not sure if this issue is still valid or not.

If it is, can you explain a little more and point some code lines to take a look?

**Comment by ericholscher** [comment]
Not sure, believe we fixed this though! :)
