### ISSUE TITLE
"Edit on GitHub" links broken for markdown files in a mixed rST/markdown project

### ISSUE THREAD

**Issue by timabbott** [rtfd/readthedocs.org#2130]
## Details

The Zulip project docs use a mix or .rst and .md files for our documentation, and everything works great except that the "Edit on GitHub" links for a file named e.g. "foo.md" point to a nonexistent "foo.rst" file on GitHub and thus are broken.

* Project: zulip

I'm seeing the same problem with the files written in markdown in project using a mix of markdown and rST (the "edit on GitHub" links go to e.g. foo.rst when the page was generated from e.g. foo.md):
See e.g. http://zulip.readthedocs.org/en/latest/integration-guide.html

**Comment by mgeier** [comment]
This is a duplicate of #1871, which was closed although it's not working yet.

**Comment by brainwane** [comment]
@timabbott ok to close this now that we got it working by upgrading our Sphinx past 1.3.6?

**Comment by timabbott** [comment]
Yes, for us this was resolved by upgrading to Sphinx 1.3.6.
