### ISSUE TITLE
Webhook build by branch

### ISSUE THREAD

**Issue by zxiiro** [rtfd/readthedocs.org#2138]
## Details

I'm trying to setup a custom webhook following the instructions from [0] and want to make a hook that triggers builds for specific branches. I don't see any documentation on how to make rtd using a custom webhook to build a specific branch. Is this possible using custom webhooks?

[0] https://read-the-docs.readthedocs.org/en/latest/webhooks.html

**Comment by agjohnson** [comment]
Looking into implementing this, it seems our webhook is in fact accepting a version already:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/views/hooks.py#L292-L296

A POST with `version_slug` *should* build a particular version, but I haven't tested this. Can you confirm?

**Comment by zxiiro** [comment]
I was able to build my project with the following command:

    curl -X POST --data "version_slug=stable-boron" https://readthedocs.org/build/opendaylight

We should update the webhooks documentation to mention the version_slug parameter. I'll see if I can find out where to update it and submit a patch.

**Comment by zxiiro** [comment]
Submitted PR #2599
