### ISSUE TITLE
Unify usage of settings

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2140]
There are a number of place that we are using `getattr(settings, <setting>, <default>)`, with varying defaults for the same setting. We should either:
- Trust the base configuration as canonical and stop trying to redefine settings defaults everywhere
- Use a secondary module to import settings into and set defaults in a common area
- Break out defaults for use in various calls to `getattr` -- though this duplicates the default in base config, unless we remove settings there

Raised in #1829

## Resolution

All settings that we use should be implemented with a default in `settings.base`. `getattr` usage for settings will be phased out and can be refactored.

**Comment by humitos** [comment]
I think that using `gettattr` with a default value all over the code is not a good idea. I'd prefer to have a `settings/default.py` or similar (even in the `settings/base.py`) where all the default settings live.

Otherwise it's need to jump into specific files to see what is the default value for a setting and there is no way to see them all together.

**Comment by ericholscher** [comment]
+1. We should move all the defaults into `base.py`, and remove our usage of `getattr`.

**Comment by ericholscher** [comment]
(This feels like cleanup, which I thought we were de-prioritizing though)

**Comment by agjohnson** [comment]
I'd avoid a settings.default given our already complex setting hierarchy. I think settings.base is the correct place for defaults.

+1 on making this our pattern going forward, and +1 on making refactoring this a non-priority cleanup task.

**Comment by davidfischer** [comment]
We have decided to drop `getattr` and define settings in the base.

**Comment by saadmk11** [comment]
Working on it. I'll open a PR soon.
