### ISSUE TITLE
contextlib2 "latest" not building after switch from Mercurial to Git

### ISSUE THREAD

**Issue by ncoghlan** [rtfd/readthedocs.org#2143]
I'm currently migrating contextlib2 development from Mercurial-on-BitBucket to git-on-GitHub, and am having trouble getting the "latest" docs to build correctly: they seem to keep building the old, pre-migration docs, even after I use "Wipe" on the build environment.

A new "master" version builds correctly, so I'm wondering if there may be a problem with the switch from "default" as the main branch in Mercurial to "master" in git.

* Project: contextlib2
* Build #: 3915890

**Comment by willingc** [comment]
@ncoghlan Did you try setting in "Advanced Project settings" the "Default branch" to "master" and save?
<img width="715" alt="screen shot 2016-04-18 at 11 25 30 pm" src="https://cloud.githubusercontent.com/assets/2680980/14629649/f728630a-05bc-11e6-984b-b5911eedbb53.png">

Then see if the rebuild works for latest.

Hopefully that should work. FYI - I forked your repo and everything built fine. I did notice a difference between my test deploy and your current settings.

<img width="759" alt="screen shot 2016-04-18 at 11 29 11 pm" src="https://cloud.githubusercontent.com/assets/2680980/14629757/b35fabf0-05bd-11e6-9f45-573161d240a3.png">

<img width="733" alt="screen shot 2016-04-18 at 11 30 06 pm" src="https://cloud.githubusercontent.com/assets/2680980/14629778/d8b57998-05bd-11e6-992c-ce2dcafb4447.png">

**Comment by ncoghlan** [comment]
Ahah, indeed, that got it. I was looking for a field that actually said "default", and missed that there was an empty "Default branch" field" in the Advance Settings.

Thanks!

**Comment by willingc** [comment]
@ncoghlan Glad it worked for you :sunflower:
