### ISSUE TITLE
TLS certificate for cdnmedia.readthedocs.org has expired

### ISSUE THREAD

**Issue by hobarrera** [rtfd/readthedocs.org#2145]
TLS certificate for cdnmedia.readthedocs.org has expired

```
cdnmedia.readthedocs.org uses an invalid security certificate.
The certificate expired on 2016-04-15 20:59. The current time is 2016-04-18 03:04.
```

**Comment by ericholscher** [comment]
This should be fixed. We aren't actively using this domain any more, so it got missed in our SSL updates. Guessing this doc needs to be rebuilt to point at a different media endpoint.

**Comment by hobarrera** [comment]
FWIW, I can across a couple of broken docs due to this issue. The latest I can recall is [icalendar](https://icalendar.readthedocs.org/).
