### ISSUE TITLE
Command line script to search the site

### ISSUE THREAD

**Issue by therealssj** [rtfd/readthedocs.org#2146]
## Details

Is there some sort of command line script to search the site for docs and download them in required format?

**Comment by agjohnson** [comment]
Not yet, but that sounds like a great addition :)

**Comment by therealssj** [comment]
As a little summer project we created a basic cli.
Please check it out  [here](https://github.com/MUSoC/rtfd-cli)

Any comments are much appreciated.

**Comment by humitos** [comment]
Is this issue still valid? I mean, it seems that @therealssj already created a cli and looks good.

Is RTD interested on creating _another_ tool for this?

**Comment by agjohnson** [comment]
Nope. If we ever want a cli tool, we can extend the project above.
