### ISSUE TITLE
Not using requested Sphinx version

### ISSUE THREAD

**Issue by jluttine** [rtfd/readthedocs.org#2149]
My build seems to be running Sphinx v1.3.5 although in my requirements file I specify `sphinx>=1.4.0`. How can I force newer Sphinx version? Building my docs needs Sphinx 1.4.0 or newer. Thanks for any help!

In the build logs, I can see the following line:
```
Requirement already satisfied (use --upgrade to upgrade): sphinx>=1.4.0 in /home/docs/checkouts/readthedocs.org/user_builds/bayespy/envs/latest/lib/python3.4/site-packages (from -r doc/requirements_rtd.txt (line 1))
```

But still the doc building begins with:
```
Running Sphinx v1.3.5
```

## Details

* Project: bayespy
* Build #: 3923030

https://readthedocs.org/projects/bayespy/builds/3923030/

**Comment by jluttine** [comment]
Any workaround ideas for this? I still haven't figured out any working setting.

**Comment by jluttine** [comment]
I tried specifying `sphinx>=1.4.0` in both the requirements file *and* `setup.py`, and it seems like it does install the latest `1.4.1` but for some reason it still keeps using `1.3.5` when building the docs:
https://readthedocs.org/projects/bayespy/builds/3969160/

**Comment by jluttine** [comment]
I'm not sure what exactly fixed this issue but it seems to work now. I wiped my environments and put the requirement to setup.py and chose to install my package to the virtual environment in the settings.

**Comment by ssbarnea** [comment]
This bugs should be reopened, RTD fails to install correct version of sphinx, even if the project specifies it.

See https://readthedocs.org/projects/jira/builds/6905467/

**Comment by stsewd** [comment]
Resolved on https://github.com/rtfd/readthedocs.org/issues/3734#issuecomment-373941644
