### ISSUE TITLE
Bare project URL not redirecting to the latest documents

### ISSUE THREAD

**Issue by gbraad** [rtfd/readthedocs.org#2151]
## Details

We have a project called `steth` and had a `stable` and `latest` option. Now, the latest actually results in output. We removed the `stable` and only have a `latest` option. The document passes the build, and we can open:
- http://steth.readthedocs.org/en/latest

but the bare url `http://steth.readthedocs.org/` does not seem to redirect to `/en/latest`. How can we make this work?
- Project: steth
- Build #: 3925601

**Comment by agjohnson** [comment]
Seems the project is set to be a single-version project? Check to make it isn't in your project admin.

**Comment by funkyfuture** [comment]
i have more or less the same issue [here](inxs.readthedocs.io). the `latest` version is configured as default in the settings.

**Comment by stsewd** [comment]
@gbraad was the issue solved? I see you now use your docs with the `single-version` option.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
