### ISSUE TITLE
Tables don't scale

### ISSUE THREAD

**Issue by dotnetjunkie** [rtfd/readthedocs.org#2161]
When building tables using RST, the table isn't automatically kept 100% with its table cells auto-scaling. Instead, all the content of the cell is placed on the same line, causing the table to become horizontal scrollable. This might make sense in some environments with small displays, but it even happens when viewing content on a 4k screen.

This seems to be javascript behavior; when javascript is disabled, the tables get formatted correctly. Also, when removing the 'wy-table-responsive' class from the table's surrounding <div> block, tables get formatted correctly as well. Tables also get formatted correctly in the PDF.

I experienced this problem while writing documentation for the simpleinjector.readthedocs.org project, but you can also see this behavior with other projects, such as [the table on this project's page](https://autofac.readthedocs.org/en/latest/glossary.html).

This problem makes it practically impossible to use tables in the documentation, which is a severe limitation for our project. Sometimes, tables are the only way to properly format parts of the text.

Can this be fixed, or otherwise, are there ways for me around this limitation, or is it possible for me to tune the output of tables for my project only?

**Comment by agjohnson** [comment]
For now, I'd use a custom stylesheet: https://github.com/snide/sphinx_rtd_theme/issues/117#issuecomment-153083280

This was a design decision for the theme around table wrapping, though I agree that the experience around wide tables on large displays is generally poor.

**Comment by stsewd** [comment]
Closing in favor of https://github.com/rtfd/sphinx_rtd_theme/issues/117
