### ISSUE TITLE
Exception on task update_docs is causing task to hang indefinitely on fresh installs

### ISSUE THREAD

**Issue by Drachenfels** [rtfd/readthedocs.org#2164]
## Details

I followed basic installation procedure (http://read-the-docs.readthedocs.org/en/latest/install.html) + used readthedocs fork to test if local instance of readthedocs is generating documentation correctly (https://github.com/Drachenfels/Test-Fork). To my despair it did not. Took me few dark and sad hours to figure out why.

I learnt that on default config (default redis, default readthedocs) one variable in the config did not match my local box (SLUMBER_API_HOST was pointing to localhost:8000 not localhost:9000). It was causing task 'update_docs' to go boom.

However there was nothing in logs, no error mentioned, no information that it was cancelled, nothing. However task was stuck in state 'Triggering'.

If you need more details:

http://stackoverflow.com/questions/36866593/readthedocs-local-instance-building-documentation-never-concludes

I do not know much more about issue. But I know it would be very helpful to do one of the following.

a) update documentation that tasks tend to fail silently
b) update task(s?) to log to error.log when they fail on execution

Of course it might be that this specific behaviour is related to fact that tasks are run 'Eagerly'. Not sure.

How to reproduce error.

Start new installation of readthedocs, keep everything on default settings but run server on port 9000 (./manage.py runserver 9000), next try to build any documentation.

**Comment by martinpengellyphillips** [comment]
Setting `SLUMBER_API_HOST` fixed the hung 'Triggering' state builds for me also whilst running the development server with `python manage.py runserver domain:port`.

**Comment by humitos** [comment]
@Drachenfels I setup my RTD local instance a couple days ago by following the official instructions and I didn't have bug issues: http://read-the-docs.readthedocs.io/en/latest/install.html

Would you like to check again?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
