### ISSUE TITLE
How do you create bookmarks?

### ISSUE THREAD

**Issue by carukc** [rtfd/readthedocs.org#2173]
The last time I built readthedocs I seem to recall that there was a way to create bookmarks. 

I've just finished building again but cannot locate the bookmark command.
Is this something that has been removed or do I need to enable something before I can create bookmarks?

I'm using commonmark (which is working quite well) and the standard doc template.

Many Thanks
Chris

**Comment by humitos** [comment]
Hi @carukc! Can you provide more information about this? I don't know what you mean by "create bookmarks", I don't know this feature.

**Comment by humitos** [comment]
This feature won't be available anymore and will be completely removed on #3659.

Please, reopen if you consider.
