### ISSUE TITLE
Preserve protocol on .org -> .io domain redirect

### ISSUE THREAD

**Issue by dcarley** [rtfd/readthedocs.org#2175]
The redirect from the old `readthedocs.org` to the new `readthedocs.io` domain should preserve the protocol of the original request.

We always reference the HTTPS URL of our project, but the redirect currently sends people back to HTTP:
```
➜  paas-team-manual git:(master) ✗ curl -s -D- https://government-paas-team-manual.readthedocs.org/ | grep Location
Location: http://government-paas-team-manual.readthedocs.io/
```

For context, this is the email I received about the change of domains:

> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
> …
> Projects will automatically be redirected, and this redirect will remain in place for the foreseeable future. Still, you should plan on updating links to your documentation after the new domain goes live.
> …

**Comment by ericholscher** [comment]
Hmm -- I tested this and it was working previously. I'll look into it.

**Comment by ericholscher** [comment]
Should be fixed now -- sorry about that!

**Comment by dcarley** [comment]
Thanks 👍
