### ISSUE TITLE
could not locate conda-env

### ISSUE THREAD

**Issue by joaander** [rtfd/readthedocs.org#2179]
## Details

If this issue is for a specific project or build, include the following:

* Project: hoomd-blue
* Build # 3956594: 

Also:

* Project: gsd
* Build # 3956602 

I am attempting to configure a new project using conda to supply the environment. I am getting the error: Error: Could not locate 'conda-env' in the first step of the build process:

```
conda env create --name 2.0 --file /home/docs/checkouts/readthedocs.org/user_builds/hoomd-blue/checkouts/2.0/environment.yml
```

To check the status of the system, I also requested a build of the latest docs on another established project: gsd. This project gives the same error, where it previously was able to build fine.

I suspect a system configuration error. It appears that conda is not installed on the VM my jobs are being directed to.

**Comment by willingc** [comment]
Also getting ``could not locate conda-env`` messages this morning. I wonder if it is related to the ``io`` suffix change or just a temporary blip. Build #3956628 is one example. @ericholscher and team, I'm happy to help if I can. It's been working well for months. I appreciate having conda :smile:

![screen shot 2016-04-29 at 9 47 51 am](https://cloud.githubusercontent.com/assets/2680980/14923021/93c074c0-0def-11e6-986b-28bb9833581d.png)

**Comment by agjohnson** [comment]
Yeah, as we reprovisioned our build servers, this caused our build images to update. We're looking into what changed here.

**Comment by ericholscher** [comment]
I'm guessing this is an issue with conda 4.0.5. I rebuilt out docker containers and conda is now broken:

```
docs@5969f47b0ae7:/$ conda --version
conda 4.0.5
docs@5969f47b0ae7:/$ conda env
Error: Could not locate 'conda-env'
```

**Comment by ericholscher** [comment]
I have to say that conda is the most frustrating package I've ever had to install on Linux:

```
docs@5969f47b0ae7:/$ conda update conda
Error: package 'conda' is not installed in /usr
```

**Comment by ericholscher** [comment]
I've hotfixed https://github.com/rtfd/readthedocs-docker-images/pull/11 on the builders for now -- can folks confirm its working?

**Comment by joaander** [comment]
Yes, it is working for me now.

**Comment by willingc** [comment]
@ericholscher @agjohnson Thanks! Just got a chance to check, all is well 🏄 🐚 🌴

**Comment by agjohnson** [comment]
Giddyup. Thanks for the report!
