### ISSUE TITLE
Private versions no longer viewable?

### ISSUE THREAD

**Issue by zmeggyesi** [rtfd/readthedocs.org#2181]
## Details

Since the change to readthedocs.io, I no longer seem to be able to open versions of my project marked private: the Maze page is displayed, with a conspicuous login link, even though I'm logged in on readthedocs.org

Public and Protected versions seem to work fine, only private versions are inaccessible.

If this issue is for a specific project or build, include the following:
- Project: N/A, multiple
- Build #: N/A

**Comment by moth3r** [comment]
the same for me

**Comment by jputrino** [comment]
Same here.
This is also the case if the project is set to be private but a specific version is set to protected.
Project: sdk-docs-dev
Build #4270874 / version development
I couldn't view the above build even though the privacy level for the development version is set to protected.

**Comment by raphaelquast** [comment]
same here... I can't access my versions once they are set to private

**Comment by dafeder** [comment]
Same here. What's going on?

**Comment by FaustinCarter** [comment]
Since this still hasn't been fixed, I'll add that I am also having this problem.

**Comment by humitos** [comment]
Hi all! I don't know the problem behind this but what I can tell is that it probably won't be fixed since there is a plan of removing the `Private` privacy level: https://github.com/rtfd/readthedocs.org/issues/2663

**Comment by stsewd** [comment]
@zmeggyesi are you still having this issue?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
