### ISSUE TITLE
Include git header files

### ISSUE THREAD

**Issue by delfick** [rtfd/readthedocs.org#2183]
Hello,

I have a project that needs to be installed in the rtd virtualenv so that I can scrape it for information to add to the documentation

(http://harpoon.readthedocs.io/en/latest/docs/configuration.html#Image)

This project includes git support and I've recently moved from using dulwich to pygit2.

The problem with this is that pygit2 requires the libgit header files to compile (https://readthedocs.org/projects/harpoon/builds/3961730/).

Seeing as git is such a common thing, can we please add it's header files to rtd?

Thanks

Stephen.

**Comment by humitos** [comment]
@delfick not sure, but I think the quick answer is "No, they won't add the git headers file" as they explain in the FAQ: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

I will close this issue as invalid. Feel free to re-open it if you consider.
