### ISSUE TITLE
Project name "autobahn" blocked

### ISSUE THREAD

**Issue by oberstet** [rtfd/readthedocs.org#2184]
I am maintainer of a Python open-source project called "Autobahn": https://github.com/crossbario/autobahn-python

We would like to publish the docs for this project under https://readthedocs.org/projects/autobahn/ on RTD. The reason is, that we believe users might be confused if we host under a different name. Autobahn has quite some user base.

However, this is currently blocked, as the name is already taken. But there is no contents at all published. The GitHub repo linked is also completely empty: https://github.com/gitu/autobahn

We also host this http://txaio.readthedocs.io/en/latest/, and as a stop-gap-solution, I've published the Autobahn docs here: https://autobahn-python.readthedocs.io/en/latest/

I have contacted the user (https://github.com/gitu) via the email displayed here https://www.easywhois.com/?domain=schr.ag, and kindly asked if he would be willing to release the "autobahn" name on RTD, so we can move there.

I will wait for an response for a couple of days and report back here ..

**Comment by oberstet** [comment]
I have received a kind reply via email by Florian. Florian is the user that originally registered the `autobahn` name at RTD stating that

* he is fine with handing over the `autobahn` RTD name to us
* but he can't do technically, because he has lost access to the mail he used while originally registering

@agjohnson IOW, could the RTD team release the `autobahn` name maybe? That would be awesome!

I am attaching the (german) email reply here for the record :

```


Heya Tobias

Kannst du gerne haben, ich habe aber keine Ahnung was ich damals für eine
Email Addresse verwendet hatte, daher kann ich den rtfd name nicht
freigeben.

Wenn du willst kannst du rtfd direkt kontaktieren damit die das schliessen
können.

Gruss
Flo

On Mon, May 2, 2016 at 6:25 AM Tobias Oberstein <tobias.oberstein@gmail.com>
wrote:

> Hallo Florian,
>
> sorry dass ich Dich "unaufgefordert" direkt anschreibe.
>
> Ich vermute Du hast auf RTD folgendes geclaimed:
>
> https://readthedocs.org/projects/autobahn/
>
> was auf
>
> https://github.com/gitu/autobahn
>
> verweist?
>
> Falls ja, verwendest Du das noch? (beides ist ja leer)
>
> Denn, ich bin Maintainer von
>
> https://github.com/crossbario/autobahn-python
>
> und wir würden gerne unsere Docs unter "autobahn" auf RTD hosten.
>
> Geht aber nicht .. da der Name eben belegt ist.
>
> Autobahn ist in relativ breiter Verwendung, und es wäre schön, wenn
> Nutzer nicht verwirrt würden, durch ein Hosting unter einem anderen Namen.
>
> Wäre also super / nett wenn Du den Namen freigeben könntest. Bitte gib
> mir in jedem Falle Bescheid - egal wie Du Dich entscheidest.
>
> Danke und Viele Grüsse,
> Tobias
>
>
>
```

**Comment by oberstet** [comment]
@agjohnson Any news on that? Florian is fine with releasing the "autobahn" project name, but cannot do it himself. Could you or a RTD admin "force remove" the https://readthedocs.org/projects/autobahn/ project (which is empty)?

**Comment by ericholscher** [comment]
I've removed the `autobahn`, since it had no valid builds and 0 activity on it.

**Comment by oberstet** [comment]
@ericholscher awesome, thanks! we've moved our docs from `autobahn-python` to `autobahn` now (http://autobahn.readthedocs.io/en/latest/)
