### ISSUE TITLE
Two identical build processes launched

### ISSUE THREAD

**Issue by jluttine** [rtfd/readthedocs.org#2190]
I'm wondering why RTD launches two identical build processes for my project whenever I push to develop branch. GitHub has only one hook, so I don't quite understand what's happening.

It also seems that it might mess my environment. It is almost random whether the builds fail or succeed. Usually the other fails and the other succeeds, but it might be that the failing build process messes the environment because both processes are touching it at the same time. Not sure though. Anyway, I need to constantly wipe my environment manually and rebuild the branch in order to fix this.
## Details

You can see that there are two build processes launched at the same time (unless I've manually launched only one process):

https://readthedocs.org/projects/bayespy/builds/

**Comment by humitos** [comment]
There are a similar report on #3255, maybe you find something useful there (webook & integration together).

**Comment by stsewd** [comment]
Also similar to #2775 and #3043

**Comment by humitos** [comment]
Do we know why this is happening?

**Comment by stsewd** [comment]
I wasn't able to reproduce this on my local instance (manually activating the webhooks and from github). This issue is still around (see https://github.com/rtfd/readthedocs.org/issues/2775#issuecomment-359963181)

**Comment by stsewd** [comment]
@jluttine can you try this #3255 (comment)?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, there are other issues reporting the same problem
