### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Locbit** [rtfd/readthedocs.org#2193]
## Details

Hello,

I am new to read the docs, but I love the tool!

My question is, can I build index.rst file the invokes JSON that has be retrieved from an API.

**Comment by agjohnson** [comment]
Sure, sphinx is highly extendable. Depending on what you need to do, there might be an extension for your use case. Closing this as this isn't an RTD issue, and the core team doesn't have the resources to provide guidance like this.
