### ISSUE TITLE
Deleted tag seems to control 'stable' version forever

### ISSUE THREAD

**Issue by gvanrossum** [rtfd/readthedocs.org#2195]
Long ago we accidentally pushed a tag 'v1.3.1' to our GitHub repo. Then we deleted the tag again, but ReadTheDocs decided that that tag should be the stable version -- all our other tags are lower (the latest is 'v0.4.0').

We can't seem to fix this on our end -- the tag is no longer in our GitHub repo but I've found no way to remove it from ReadTheDocs (honestly I can't figure out the right git flag to recommend).
- Project: mypy

CC: @ddfisher, @JukkaL.

**Comment by ericholscher** [comment]
Ack -- I believe we don't clean tags properly because we expect them to exist forever. I've updated the repo properly, and it should be working again. Sorry about that!

**Comment by gvanrossum** [comment]
Thanks for the quick response. Alas, "stable" is still locked to f6c71c57aeee0faeeb8c885d266eefd0b74cc72d. :-(

I am still pretty confused by the admin UI -- I think I don't have the right model for how docs actually get built and I have no idea whether to use Build, Edit, Wipe or whatever, and in what order. :-(

**Comment by groolot** [comment]
I experience the same issue.

My context was multiple branches and tags, rebase and moved branches.

A complete project deleting and reinstallation did not do anything at all, even if my original repository is clean.

**Comment by gvanrossum** [comment]
This is still broken! Help!!!

**Comment by ericholscher** [comment]
I just tried fixing this again, and it appears to have stuck this time, stable now points at `v0.4.1 b1cd80ce`. 

@groolot what is your project name?

**Comment by gvanrossum** [comment]
Thanks!

**Comment by xor-xor** [comment]
@ericholscher - I have a similar problem with our `ralph-cli` project.

Our GitHub repo (and RTD docs) went through some major reorganization (new, different project, but under the same name, which is quite important to us), and now I have a lot of stale versions, which are impossible to delete/refresh from RTD's Admin panel.

At this moment, I'd like to keep only the `latest` version (pointing to the tip of the `develop` branch") and `v0.1.0` version (pointing to `04bc43c28778d986401df3b533bdf4a297d8e72c`, **not** `415580dc`, which doesn't exist anymore and blocks `v0.1.0`) - all other versions/tags/branches etc. can be safely deleted. 

Could you help me with that..? Thanks in advance!

**Comment by gvanrossum** [comment]
@ericholscher @agjohnson @pydanny The mypy docs "stable" version is again stuck on the tag v1.3.1 which was removed from our repo. In previous comments of this issue we received confirmation that this was fixed, but either it wasn't, or the problem has somehow come back (maybe you are using a different old copy of the repo)? Please can you fix this again?

**Comment by ericholscher** [comment]
Sorry about that. I'm traveling today, but I'll look at it first thing tomorrow.

**Comment by ericholscher** [comment]
Should be fixed -- that old v`v1.3.1` version showed up again and was breaking the stable updating.

**Comment by gvanrossum** [comment]
Thanks? How the heck does this tag keep getting resurrected?

**Comment by ericholscher** [comment]
I'm also curious about that -- I thought I deleted all the checkouts in the past, but impossible things happen all the time in the software universe :) I blame git.
