### ISSUE TITLE
Spam page

### ISSUE THREAD

**Issue by jseabold** [rtfd/readthedocs.org#2199]
AFAICT, this project is just mirroring the tornado project and adding some non-sensical Chinese and ads then serving the docs here. It shows up higher than the tornado docs on google for me.

* Project: 
http://tornadokevinlee.readthedocs.io/en/latest/
https://github.com/kevinleegithup/tornado/commits/master

**Comment by agjohnson** [comment]
This is a duplicate issue of #1981, closing here.
