### ISSUE TITLE
RTD build stuck in Triggered state

### ISSUE THREAD

**Issue by nhitchins** [rtfd/readthedocs.org#2201]
Attempting to build latest docs but build process appears to be stuck in "Triggered" state for the last few hours.

* Project: eagle.io
* Build #: 3986464

**Comment by nhitchins** [comment]
Still no luck...any ideas?

**Comment by zzzeek** [comment]
SQLAlchemy has this issue for over a week now apparently there are several dozen builds all stuck in "triggered"

**Comment by zzzeek** [comment]
nevermind for SQLAlchemy though this issue should be fixed in RTD overall.   Unfortunately the SQLA project can't tolerate continued documentation build outages so I've had to switch to my own host.

**Comment by agjohnson** [comment]
this should now be resolved, both projects were on a separate build queue for projects that cause resource contention on our build servers. i've swapped both back to the production task queue as it seems we made a operations change at some point

**Comment by nhitchins** [comment]
Working! much appreciated.
