### ISSUE TITLE
conflict with redirect from readthedocs.org to readthedocs.io

### ISSUE THREAD

**Issue by joschirr** [rtfd/readthedocs.org#2203]
The subdomain
guidelines.readthedocs.org
is used by the project
https://readthedocs.org/projects/guidelines/
with original homepage
guidelines.openaire.eu

while 
guidelines.readthedocs.io
is related to
https://github.com/readthedocs/guidelines/blob/master/index.rst

**Comment by ericholscher** [comment]
Woops! Sorry about that -- we were using the guidelines domain as a test for our deployment over to .io, and forgot to switch it back. Should be working properly now!
