### ISSUE TITLE
Build timeout for extremely large doc set

### ISSUE THREAD

**Issue by jputrino** [rtfd/readthedocs.org#2204]
## Details

Hi gang, 

I have a gigantic REST API doc set that is hitting the build time limit (and probably the space limit as well) and failing. Does anyone have any suggestions for a workaround? I'm only going to have to build this doc set once, as it's not part of an actively developed project; we just need to be able to consult it for support purposes. 

If this issue is for a specific project or build, include the following:
- Project: [linerate-api](https://readthedocs.org/projects/linerate-api/)
- Build #: [3989765](https://readthedocs.org/projects/linerate-api/builds/3989765/); Build #[3992486](https://readthedocs.org/projects/linerate-api/builds/3992486/)

Thanks!

**Comment by jboecker** [comment]
In the default RTD theme, you can click the green version tag in the bottom left corner to show links to downloadable HTML, PDF and ePub versions.

As far as I know these are generated by default for everything that they host.

**Comment by agjohnson** [comment]
Project looks to be removed, so can't provide much guidance. We can look into bumping up the allowed limits if nothing else.

**Comment by jputrino** [comment]
@agjohnson - thanks for looking, my apologies for not updating this thread earlier. I hid the project because I didn't want to confuse our customers. I tried building it locally with sphinx and it took a few hours, so I think I'm just not going to be able to use read the docs for this project (sob!).

**Comment by agjohnson** [comment]
Yeah, that's a long time to be blocking the community queue. We can provide more resources on our base plans on readthedocs.com, so especially if this is a commercial project, I'd consider a plan there.
