### ISSUE TITLE
Dead link in documentation

### ISSUE THREAD

**Issue by gunthercox** [rtfd/readthedocs.org#2205]
In the latest documentation there appears to be a dead link (https://github.com/rtfd/readthedocs.org/blob/master/docs/getting_started.rst).

The section reads:

> Now, edit your index.rst and add some information about your project. Include as much detail as you like (refer to the reStructuredText syntax or **this template** if you need help). Build them to see how they look:

The broken link is in the text:
this template --> http://docs.writethedocs.org/en/latest/writing/beginners-guide-to-docs/#id1

**Comment by ericholscher** [comment]
Should be fixed -- thanks!
