### ISSUE TITLE
FeatureRequest: Add offline support for pages

### ISSUE THREAD

**Issue by mtycholaz** [rtfd/readthedocs.org#2206]
As a developer, my commute is on buses, trains, and waiting inbetween with no wifi. It'd be awesome to have an offline mode for the site so I can still read/reference material.

**Comment by jboecker** [comment]
In the default RTD theme, you can click the green version tag in the bottom left corner to show links to downloadable HTML, PDF and ePub versions.

As far as I know these are generated by default for everything that they host.

**Comment by agjohnson** [comment]
Downloaded files above are generated for all sphinx projects by default, though some projects disable them, and mkdocs projects do not build them at all. An offline website mode would require re-architecting our output, and isn't likely going to be a feature we would develop/accept for our hosted version.

Sounds like downloads is what you want anyways though, closing this issue.
