### ISSUE TITLE
Latest build index page is not updated

### ISSUE THREAD

**Issue by cjermain** [rtfd/readthedocs.org#2218]
## Details
- Project URL: https://github.com/ralph-group/pymeasure
- Build URL (if applicable): http://pymeasure.readthedocs.io/en/latest/
- Read the Docs username (if applicable): cjermain
## Excepted Result

I'm looking to update the latest version of the docs. I merged into the master and a new build commenced for commit 7a1dd2ad. I expected this new version to be available on RTD after it successfully reports "Build Complete", as it has been in all previous commits.
## Actual Result

The index page served on RTD is for a previous commit (39c9c833). Links are broken to pages in this old version. Manually entering an appropriate URL for a new page yields that page with the correct revision number (7a1dd2ad) -- for example http://pymeasure.readthedocs.io/en/latest/tutorial/graphical.html. Wiping the latest version and rebuilding does not appear to fix it.

RTD appears to be serving the wrong index page, but the correct sub-pages.

**Comment by lkev** [comment]
Also having this issue.

http://wt-fdd.readthedocs.io/en/latest/ (d9541dde) is the current and correct build of the docs.

However, when I click on one of the links here, and then click on the homepage, it brings me to
http://wt-fdd.readthedocs.io/en/latest/index.html (18f60694).

**Comment by cjermain** [comment]
The docs look fine at this point -- it still seems to be a cache issue. While the problem is temporarily not an issue for me, it would be nice to solve this since it affects other users.

**Comment by lkev** [comment]
Yep, mine are now fixed. Must be a cache issue. It'd be nice to only show the older rev of the docs until the new ones are fully up so there's no confusion.

**Comment by cjermain** [comment]
Agreed, good idea.

**Comment by tgoodlet** [comment]
Wow thought I was losing my mind...

I have the same problem.
correct version: http://switchy.readthedocs.io/en/latest/index.html
old version: http://switchy.readthedocs.io/en/latest/

@cjermain you might want to update the issue name to *Latest build index page is not updated*.

**Comment by humitos** [comment]
This issue seems stale and like a temporary error in 2016. So, I'm going to close it but feel free to reopen it if you consider or open a new one.
