### ISSUE TITLE
Multiple of my newly added GitHub repositories are hanging in state 'Cloning'

### ISSUE THREAD

**Issue by Paebbels** [rtfd/readthedocs.org#2221]
Multiple of my newly added GitHub repositories are hanging in state 'Cloning'.
This state was entered 7 hours ago.
- Project URL:
  - https://readthedocs.org/projects/rc3e-client
  - https://readthedocs.org/projects/rc3e-server
  - https://readthedocs.org/projects/rc3e-node
  - https://readthedocs.org/projects/rc3e
  - https://readthedocs.org/projects/rc2f
- Read the Docs username (if applicable): Paebbels

**Comment by blaisep** [comment]
Hi @Paebbels , I'm seeing this also in my internally-hosted RTD server. Repos older than 5 days seem to be OK. Let me know if you want to compare notes offline.

**Comment by Paebbels** [comment]
Hello,

the repository is now older than 6 days. I tried a new build run, but it's still cloning. Is there any chance to kill the old tasks?

Regards
    Patrick

**Comment by benjaoming** [comment]
Not sure why I have access to build these projects :)

But when I do, I get `Invalid "requirements_file": path requirements.txt does not exist` so perhaps the issue has changed?
