### ISSUE TITLE
Links to PDFs at readthedocs.io fail; readthedocs.org works

### ISSUE THREAD

**Issue by willingc** [rtfd/readthedocs.org#2224]
## Details
- Project URL: https://github.com/jupyterhub/jupyterhub/pull/585
- Build URL (if applicable):
- Read the Docs username (if applicable): 
## Excepted Result

_I expected a link to a PDF for the JupyterHub docs to work when including readthedocs.io in the link. Example: https://media.readthedocs.io/pdf/jupyterhub/latest/jupyterhub.pdf_
## Actual Result

_The link to the PDF using readthedocs.io resulted in "Sorry. This page does not exist yet."_

When using the former readthedocs.org link, the PDF is located.  Example: https://media.readthedocs.org/pdf/jupyterhub/latest/jupyterhub.pdf

**Comment by ericholscher** [comment]
Where did you get the media.rtd.io link from?

**Comment by willingc** [comment]
By clicking on the Download PDF link (see images). This is no longer an issue so I'm going to close.
<img width="410" alt="screenshot 2017-12-08 14 09 01" src="https://user-images.githubusercontent.com/2680980/33783228-824e34be-dc21-11e7-9f5c-f435e5f68c24.png">

**Comment by ericholscher** [comment]
Great, thanks! Was likely an old bug that we fixed at some point :)
