### ISSUE TITLE
Cloning stuck (USERTrust certificate not supported?)

### ISSUE THREAD

**Issue by phineas42** [rtfd/readthedocs.org#2226]
## Details
- Project URL: https://readthedocs.org/projects/public-docs
- Repository URL: https://code.oscer.ou.edu/phineas/docs.git
## Expected Result

git clone over https. 
## Actual Result

Stuck at "Cloning" (Same symptom as #2047)
## Notes

The repo server does not log any access, leading me to suspect an SSL issue between read-the-docs and my repo. The certificate chain is identical to the one in #1885 . Was the resolution in #1885 to trust the chain, or to make an exception for the site?

**Comment by phineas42** [comment]
The following intermediate certificate is what was missing on my systems:
[InCommon SHA2/RSA Production (SHA384) Intermediate Cert (PEM format)](http://www.incommon.org/cert/repository/sha384%20Intermediate%20cert.txt)

**Comment by agjohnson** [comment]
We took no action to resolve this. We don't want to make custom exceptions for SSL, as this isn't going to be manageable. If the cert chain is included in Ubuntu, we can support it. If you can confirm the cert chain works on 16.04, this might be a matter of running 16.04 on our builders -- which is coming soonish.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also see https://github.com/rtfd/readthedocs.org/issues/2226#issuecomment-228490809
