### ISSUE TITLE
should readthedocs.io be on the public suffix list?

### ISSUE THREAD

**Issue by dkg** [rtfd/readthedocs.org#2233]
I see that the hosted documentation for projects is now under readthedocs.io instead of readthedocs.org.  presumably this is for domain separation, so that bad project documentation can't use same-origin policy to mess around with the readthedocs domain itself.

however, there is still a possibility of cross-project contamination, since foo.readthedocs.io is considered same-origin as bar.readthedocs.io by most browsers.

One way to avoid this cross-project contamination would be to submit readthedocs.io to the public suffix list via a pull-request over at https://github.com/publicsuffix/list.  You'll note that https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat contains github.io and githubusercontent.com, presumably for the same reason.

I'm happy to open this PR myself if you want me to, but i wanted to verify that this is something that the readthedocs folks actually want to happen.

**Comment by davidfischer** [comment]
I realize it is two years later but this sounds like a good idea to me. I don't know if you're still around to do this but I'd appreciate if you did open that PR. If not, I'll go ahead and do it in a week or two.

**Comment by stsewd** [comment]
@davidfischer I checked and there isn't a PR for rtd yet, so feel free to do it :)

**Comment by dkg** [comment]
I've made https://github.com/publicsuffix/list/pull/722 .  In order for this to follow through, someone with access to the DNS zone needs to create the following TXT record, as documented in the [PSL Guidelines](https://github.com/publicsuffix/list/wiki/Guidelines):

    $ dig TXT _psl.readthedocs.io
    https://github.com/publicsuffix/list/pull/722

**Comment by davidfischer** [comment]
The TXT record is setup.

**Comment by stsewd** [comment]
The PR was already merged https://github.com/publicsuffix/list/pull/722, closing.

thanks @dkg!
