### ISSUE TITLE
Need Step By Step for Creating New/Importing

### ISSUE THREAD

**Issue by BruceEckel** [rtfd/readthedocs.org#2242]
At the bottom of http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs
There are two subheads:
### Importing existing docs

These each need links to step-by-step instructions on how to do this.

**Comment by stsewd** [comment]
Mmm, I don't see this feature on the site right now

> We provide a simple editor and two sample pages whenever a new project is created.

(On the creating new docs section)

**Comment by humitos** [comment]
I think the whole "What's available" needs some love: http://docs.readthedocs.io/en/latest/install.html#what-s-available

**Comment by stsewd** [comment]
This was solved on #3498. @humitos did you mind to close this?

**Comment by humitos** [comment]
@BruceEckel let us know if this is clearer now!
