### ISSUE TITLE
xlrd project has been hijacked

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#2250]
## Details

* Hijacked URL: https://readthedocs.org/profiles/kmonsoor/ and https://readthedocs.org/projects/python-xlrd/
* Project URL: https://github.com/python-excel/xlrd
* Read the Docs username (if applicable): kmonsoor / chris@python.org

## Excpeted Result

I'd like to be able to build the sphinx docs for the xlrd project, of which I'm the primary maintainer.

## Actual Result

"kmansoor" has somehow added this project to rtd. It won't work as it needs settings changed before I start converting the docs for xlrd to be sphinx. Accidental or deliberate hijacking, it's preventing me from using rtd to build docs for the xlrd project, and I have no way of contacting "kmonsoor".

Please can you delete that project so that I can add it with my chris@withers.org account and get on with things?

**Comment by cjw296** [comment]
Okay, so the author of https://readthedocs.org/profiles/kmonsoor/ has removed that project, but turns out https://readthedocs.org/projects/xlrd/ is the real problem. I've tweeted and emailed the owner of that one, but no response yet...

**Comment by agjohnson** [comment]
If you have no luck contacting the maintainer, we can help facilitate this. Let me know here if you haven't had a response in several days and I can try to connect you over the email for the user.

**Comment by cjw296** [comment]
@agjohnson - well, I've heard from @dmr and he seems amenable: https://twitter.com/daniel_aus_wa/status/738768832202952704
...but no response as to when "back home" might be. Is there anything we can do to expedite?

**Comment by dmr** [comment]
hijacked sounds pretty hard, I tried to build xlrd docs for some there but gave up.

@cjw296 @agjohnson I need your read the docs username to add you as a maintainer for the readthedocs project.

**Comment by cjw296** [comment]
Many thanks to @dmr, I've not got things set up, but now every build I do gets stuck on "Triggered":

https://readthedocs.org/projects/xlrd/builds/

Could this be related to re-creating the project or is something else going on?

**Comment by cjw296** [comment]
Looks like others are having build problems too, so will close and followup there.

Thanks again to @dmr for sorting this so quickly!
