### ISSUE TITLE
Search feature is broken

### ISSUE THREAD

**Issue by rationalism** [rtfd/readthedocs.org#2252]
On the page http://cider.readthedocs.io/en/latest/, which has documentation for the Emacs mode CIDER, searching for the term "debugging" in the "Search docs" box returns zero results:

![screenshot of search results](https://cloud.githubusercontent.com/assets/813306/15777605/9138fa44-2945-11e6-8162-1aa14557a6cd.png)

However, the docs for CIDER have a large section dedicated to debugging:

![screenshot of docs](https://cloud.githubusercontent.com/assets/813306/15777641/c91698e0-2945-11e6-8947-970c98e7e7cd.png)

There should be at least one search result for "debugging", since the word "debugging" is a section header as well as a header in the documentation HTML.

**Comment by agjohnson** [comment]
You look to be using mkdocs, which doesn't provide search currently. See #1088, closing this as duplicate.
