### ISSUE TITLE
Latest repeatedly builds stale code

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#2254]
## Details
- Project URL: https://github.com/pypa/setuptools
- Build URL (if applicable):
- Read the Docs username (if applicable): jaraco

Per pypa/setuptools#604, I'm migrating the project to RTD as PyPI is dropping support for doc hosting. I've gotten access to the setuptools project, which was formerly configured for Mercurial (Bitbucket), which may be implicated in this issue.

After moving from Mercurial to Git, the project failed to build because it was missing dependencies, so [I pushed this commit](/pypa/setuptools/commit/ffddefca6a) and reconfigured the project in RTD to use for docs/requirements.txt. The build failed, so I retried a couple of times manually building latest.
## Excepted (erm, Expected) Result

As seen in the UI, latest should build the VCS default branch. In this case, it's a git repo and 'master' is configured as the default branch in Github. Therefore, it should build the aforementioned commit, which is in master.

![screen shot 2016-06-03 at 14 04 37](https://cloud.githubusercontent.com/assets/308610/15788204/56376fa8-2994-11e6-942e-e2afcb3b220f.png)
## Actual Result

Instead, the build failed:

![screen shot 2016-06-03 at 14 07 46](https://cloud.githubusercontent.com/assets/308610/15788259/9bb295bc-2994-11e6-8354-4eda68ab6778.png)

I retried several times, but repeatedly got the same error.

**Comment by jaraco** [comment]
it seems that after waiting a few minutes and triggering another latest build, it now got the latest commit:

![screen shot 2016-06-03 at 14 09 40](https://cloud.githubusercontent.com/assets/308610/15788297/d98147d0-2994-11e6-95ba-a4a0621c0887.png)

So while I thought maybe it was an issue with having been a Mercurial project, because I saw `default` here:

![screen shot 2016-06-03 at 14 11 51](https://cloud.githubusercontent.com/assets/308610/15788352/2fc64b40-2995-11e6-9a36-0a122b794e53.png)

Apparently the issue is only a lag between when commits are pushed and when they can be pulled. Is that by design?

**Comment by jaraco** [comment]
It's happening again, now with https://github.com/pypa/setuptools/commit/8fea56035d22fc46e8237fa8f6b1b548fd0105d5. I'll keep repeatedly building until I get a different response and see if I can assess how long the stale builds continue.

**Comment by jaraco** [comment]
Oh, this is interesting. It seems one build went back to a commit even older than the one that finally built before:

![screen shot 2016-06-03 at 14 21 09](https://cloud.githubusercontent.com/assets/308610/15788650/87766e96-2996-11e6-967d-4f22917ed4ce.png)

**Comment by jaraco** [comment]
And again

![screen shot 2016-06-03 at 14 22 47](https://cloud.githubusercontent.com/assets/308610/15788675/adb24e04-2996-11e6-8db5-b0a230538ea9.png)

How weird.

**Comment by jaraco** [comment]
More than 6 minutes and RTD is still building pypa/setuptools@f12843c13

**Comment by jaraco** [comment]
15 minutes and it's still building one of two older commits. I'm going to take a break from this effort for now.

**Comment by jaraco** [comment]
Hours later, problem still exists.
![screen shot 2016-06-03 at 21 03 41](https://cloud.githubusercontent.com/assets/308610/15796619/b8f9412c-29ce-11e6-8c52-b6a026c80788.png)

**Comment by jaraco** [comment]
I set the branch to the default, `master`, and that triggered a build, which grabbed the latest tip:
<img width="857" alt="screen shot 2016-06-03 at 21 09 47" src="https://cloud.githubusercontent.com/assets/308610/15796663/b1f6aa9e-29cf-11e6-9f24-5baaa040efa8.png">

**Comment by agjohnson** [comment]
I'll take a look into this, it seems I might need to go in an clean out the old project commit history.

**Comment by agjohnson** [comment]
It seems the last build did in fact complete successfully without having to alter the out of date versions:
http://readthedocs.org/projects/setuptools/builds/4068321/

Does this seem resolved?

**Comment by jaraco** [comment]
Yes, sort-of. It seems that setting the branch manually seems to have worked around the issue.

**Comment by agjohnson** [comment]
I suspect this is a matter of stale version/commit info. If it stops working, I can wipe the existing version and commit info from the project.

**Comment by jaraco** [comment]
I'll remove the branch override and see if the issue re-emerges, in which case it's worth trying a wipe to see if the project can be restored to a state that behaves as expected.

**Comment by hldh214** [comment]
![Uploading err1.png…]()

Server Error

**Comment by Grummfy** [comment]
seems same as #2255

**Comment by stsewd** [comment]
@jaraco I think this is related to #3913

**Comment by agjohnson** [comment]
Closing as a duplicate, and due to lack of activity.
