### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by wshafer** [rtfd/readthedocs.org#2256]
## Details

* Project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): N/A

## Excepted Result

Site comes up

## Actual Result

Looks like one of your servers is dead.  Every other request to readthedocs.org is pulling up a "502 Bad Gateway"

**Comment by cjw296** [comment]
Yep, getting this here too:

https://readthedocs.org/projects/xlrd/builds/

**Comment by Grummfy** [comment]
same as 2257 & 2255

**Comment by agjohnson** [comment]
Closing as duplicate
