### ISSUE TITLE
Build stuck in Triggered state

### ISSUE THREAD

**Issue by eerimoq** [rtfd/readthedocs.org#2257]
## Details

* Project URL: simba-os
* Build URL (if applicable): https://readthedocs.org/projects/simba-os/builds/4070274/
* Read the Docs username (if applicable): eerimoq

## Excepted Result

The documentation is generated.

## Actual Result

The build is stuck in Triggered state, and has been like that for the last couple of days.

Thanks for a useful site! I appreciate your work.

**Comment by Grummfy** [comment]
same as 2256 & 2255

**Comment by agjohnson** [comment]
Closing as duplicate
