### ISSUE TITLE
Read the docs public api documentation incorrect

### ISSUE THREAD

**Issue by therealssj** [rtfd/readthedocs.org#2264]
## Expected Result
http://read-the-docs.readthedocs.io/en/latest/api.html#get--api-v1-build-
Many examples on the page above, like the `build` end point, don't work or more like they don't exist.
Even the file search endpoint 
`http://readthedocs.org/api/v1/file/search/?format=json&q=`
returns an error.  

## Actual Result
A working api which returned the expected results.

Has the api been modified and the docs left un changed?

**Comment by berkerpeksag** [comment]
I think this can be closed as a duplicate of #1610.

**Comment by berkerpeksag** [comment]
Closing as a duplicate of #1610.
