### ISSUE TITLE
Custom domains stopped working

### ISSUE THREAD

**Issue by andrewshadura** [rtfd/readthedocs.org#2266]
Project URL: http://kallithea.readthedocs.org

We have a proxy set up according to the docco, at http://docs.kallithea-scm.org/. When opening that URL, however, the RTFD server responds with `Location: http://kallithea.readthedocs.io/en/0.3.1/`. If I try http://docs.kallithea-scm.org/en/latest/contributing.html, which previously worked, the server responds with Maze Found.

**Comment by adamchainz** [comment]
Everyting moved to `.io` as per https://blog.readthedocs.com/securing-subdomains/ , you shoudl just start proxying the `.io` domain rather than the `.org` one

**Comment by andrewshadura** [comment]
We use a custom domain, we don't use any of the RTFD domains.

**Comment by andrewshadura** [comment]
None of http://read-the-docs.readthedocs.io/en/latest/alternate_domains.html work these days. I tried to stop proxying in favour having CNAME pointing to RTFD, but it was useless as old links broke. Now even proxying is broken too.

**Comment by adamchainz** [comment]
Do you have CNAME pointing to `.io` or `.org` ?

**Comment by andrewshadura** [comment]
We currently do not have a CNAME. I proxy requests to whatever `kallithea.readthedocs.io` resolves to, which is `162.242.198.235` at the moment.

**Comment by agjohnson** [comment]
@andrewshadura can you confirm you are sending us a host header in your proxy request?

**Comment by stsewd** [comment]
Are you still having this issue? All the links provided work properly.

**Comment by andrewshadura** [comment]
I had to remove RTD CNAME and use our own proxy. The `Host` header was in the requests, yes.

Unless anything was specifically done to fix this issue, it should still be valid.

**Comment by agjohnson** [comment]
I'm not sure there is anything we can do to help. Even if proxying was configured still, there isn't much visibility we have on our side to provide guidance. I know that this isn't a bug however, as proxying works without issue for other projects with custom domains.

Feel free to provide more information with sample requests and responses that would help us. Closing for now.
