### ISSUE TITLE
Problems about GitHub account connecting

### ISSUE THREAD

**Issue by LasmGratel** [rtfd/readthedocs.org#2268]
## Details

I have a dispose user:LasmGratel
And I have a new user:Lasm_Gratel
But I forgot the **password and the email** for LasmGratel
So I **disconnected** the connection **in GitHub only**
But in rtfd site, it **still** says "_The social account is already connected to a different account._"
**Can you help me on this(Stop the connection in rtfd site) and solve this problem?**
(Sorry for my bad English)
- Read the Docs username: Lasm_Gratel, LasmGratel

**Comment by ericholscher** [comment]
This was a bug that we had for a long time, but has been fixed for a number of months. If you login with GitHub (https://readthedocs.org/accounts/github/login/?process=login) it will bring you to your account connected with that GitHub account, which you can then unlink (https://readthedocs.org/accounts/social/connections/) to fix this.
