### ISSUE TITLE
404 redirect to root

### ISSUE THREAD

**Issue by nhitchins** [rtfd/readthedocs.org#2272]
Trying to eliminate any 404 pages a user may ever encounter and simply redirect to root.
Looking at the redirect documentation, I cant find an easy way to this.

Is it possible to redirect any 404 encountered at /en/latest/* back to /en/latest/

Or alternatively use a custom 404 page?

**Comment by agjohnson** [comment]
No not at this time, we raised how we might handle an overridden 404 page in #353 though. I don't think we'll enable something like a redirect on 404, closing this issue here as a duplicate.
