### ISSUE TITLE
Documentation version randomly changes for the same compilation

### ISSUE THREAD

**Issue by bonigarcia** [rtfd/readthedocs.org#2273]
## Details

* Project URL: https://github.com/Kurento/doc-kurento-readthedocs
* Build URL: http://doc-kurento.readthedocs.io/

## Expected Result

The stable build of our project currently is version 6.5.0. This can be easily seen in the upper left part of our documentation:

![image](https://cloud.githubusercontent.com/assets/5413013/16299154/17369ab8-3939-11e6-943e-ab823eefb7f3.png)

## Actual Result

For some unknown reason, the version of our documentation changes from one request to another. In order to reproduce the problem, just refresh the browser (Ctrl-R) several times. From time to time, the version of the documentation changes to the previous one (6.4.0).

![image](https://cloud.githubusercontent.com/assets/5413013/16299259/a1eca6a2-3939-11e6-911d-8ae6146ba060.png)

I don't know if this can be related with the "cloning stuck issue" (I'm guessing here). Our project experiences the same problem than reported in this open [issue](https://github.com/rtfd/readthedocs.org/issues/2047).

**Comment by agjohnson** [comment]
The cloning issue is separate, there is an open issue for fixing logging on errors there.

I can't reproduce this now, I'm sure this was an intermittent issue with one of the web servers.
