### ISSUE TITLE
Consistent timeout error when building docs

### ISSUE THREAD

**Issue by hoonhout** [rtfd/readthedocs.org#2274]
## Details
- Project URL: https://readthedocs.org/projects/xbeach/
- Build URL (if applicable): any build fails, for example https://readthedocs.org/projects/xbeach/builds/4130313/
- Read the Docs username (if applicable): hoonhout
- GitHub repository: https://github.com/openearth/xbeach-docs

I try to build Sphinx documentation from the GitHub repository. The GitHub repository only holds the documentation files, no source code is needed for the build and is not included in the repository. The documentation is quite elaborate with many figures, mathematical equations and references.

The build consistently fails with a timeout error after 900 seconds. When I build the documentation locally it builds in about 10 minutes. I suppose that cloning the repository and rendering PDF and EPUB files in addition takes the build beyond the time limit of 15 minutes. Since the building involves RST files only, I'm not sure if I can speed it up. Would it be possible to increase the time limit for this project?
## Expected Result

I try to build the Sphinx documentation from a GitHub repository, including the HTML website at http://xbeach.readthedocs.io/, the PDF file and the EPUB file.
## Actual Result

I consistently get a timeout error after 900 seconds about halfway building the PDF file. The generation of the HTML files and publication on http://xbeach.readthedocs.io/ work fine.

**Comment by agjohnson** [comment]
This looks like the project is hitting our time limit for builds, based either on the documentation that is generated or the reference documentation. I'll see about bumping up the time limit.

These docs look great, by the way :100:

**Comment by hoonhout** [comment]
Hi Anthony,

Awesome, thanks.
The docs are a community effort :-) I’ll pass on the message!

Bas

**Comment by humitos** [comment]
Related to #2614

**Comment by hoonhout** [comment]
In the past year we circumvented above-mentioned issue by switching off PDF and EPUB output and run the Sphinx locally instead. This is quite inconvenient and error prone. Therefore, we are still really interested in having especially the PDF output online. The documentation is as lean and mean as we can get it. We only update it a few times a year (!). I don't see any optimisation possibilities, except:

1. Bumping up the time limit, as suggested above, or
2. Switching off JSON and Single Page HTML output in favor of PDF output, as described in #2614 

We would appreciate if one of these two options can still be considered.

As we are a non-profit, open-source organisation ourselves we don't have steady funding for a permanent RTD subscription. If one can provide me with an estimate of the costs involved with realising option 2, I will try to raise a one time donation to cover these.

Bas

**Comment by stsewd** [comment]
You can disable the `single page html` build with the yaml file https://docs.readthedocs.io/en/latest/yaml-config.html#formats. For the JSON build, we can't do that, since rtd uses to provide the search feature. But we have a _beta_feature to output the json artifacts in the normal html build step https://github.com/rtfd/readthedocs.org/pull/4229 (only selected projects has this feature at the moment)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also please see https://github.com/rtfd/readthedocs.org/issues/2274#issuecomment-397729907. BTW, now all previous projects built the json artifacts in the html step, and your latest builds are passing.
