### ISSUE TITLE
Support passing configuration file name to mkdocs

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2275]
mkdocs has the `-f` or `--config-file` option, this could support multiple configuration files, for translations/etc.

**Comment by Surgo** [comment]
Thank you. +1

**Comment by KrzysztofMadejski** [comment]
+1
Now it's not possible to build MkDocs documentation if th configurations file doesn't lie in `doc` or `docs` subdirectory. It would be nice to allow setting the path to the `mkdocs.yml` file instead of `Python configuration file:` (`Advanced Settings`) if MkDocs builder is used.

**Comment by stsewd** [comment]
This was already implemented in https://github.com/rtfd/readthedocs.org/pull/4486

**Comment by Surgo** [comment]
Wow thank you so much :)
