### ISSUE TITLE
"View Docs" takes users to the wrong project.

### ISSUE THREAD

**Issue by d0ugal** [rtfd/readthedocs.org#2279]
## Details

* Project URL: http://readthedocs.org/projects/mkdocs/
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): d0ugal, but not related

## Expected Result

Go to http://readthedocs.org/projects/mkdocs/. Click on "View Docs" (the big green button). Expect to go to http://mkdocs.readthedocs.io/en/stable/

## Actual Result

Instead be taken to http://mikasa-demo.readthedocs.io/en/stable/

**Comment by willingc** [comment]
@d0ugal The link appears to now work as expected. Would you mind taking a look and closing if it works correctly for you now? Thanks!

**Comment by d0ugal** [comment]
Yup, thanks. Any idea what resolved it?

**Comment by willingc** [comment]
@d0ugal I'm not sure. I was just helping the RTD folks triage some issues.

Is there any particular reason that `stable` version is set to `origin/859`?

<img width="1062" alt="screen shot 2016-07-09 at 7 04 12 am" src="https://cloud.githubusercontent.com/assets/2680980/16708320/da680fbe-45a3-11e6-84d8-8c05223cc736.png">
