### ISSUE TITLE
Import a Repository desperately needs a search box

### ISSUE THREAD

**Issue by calston** [rtfd/readthedocs.org#2282]
## Details

* Project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

I'd like to import a repository by searching for it.

## Actual Result

I'm presented with a pagination of several thousand repos and can't find the one I want

**Comment by edunham** [comment]
@calston, thank you for reporting this! I've tagged it as "design decision needed" so that a project leader can weigh in on how they would recommend implementing such a search feature.

**Comment by barbara-sfx** [comment]
+1

A faster way to page through the results would also help, since (I think) they are alphabetical but IIRC you can only go forward or back 1 page at a time.

**Comment by agjohnson** [comment]
Going to merge this ticket with #1899, feel free to move the conversation that way
