### ISSUE TITLE
readthedocs down

### ISSUE THREAD

**Issue by rajasimon** [rtfd/readthedocs.org#2293]
I tried so many readthedocs site and all are down now. It simply showing "Service Unavailable"

**Comment by akutz** [comment]
Now it seems as if my projects aren't being sync'd with Github, even though RTD is back online. Any word/note on that?

**Comment by agjohnson** [comment]
This was a problem with our database that took me a few bleary-eyed hours this morning to resolve. Service was restored sometime around 5am PDT. Closing this.

@akutz feel free to open a separate issue with information on your project if this is still an issue.
