### ISSUE TITLE
Incorrect webhook message and icon for rtd.com (not .org)

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2297]
## Details
- Read the Docs username (if applicable): brsnyder

I imported a private repo -- product-docs-private -- as a project. Eric Holscher is a collaborator.
## Expected Result

I wanted it to build.
## Actual Result

I see the message "webhook created" etc., but in fact, for rtd.com, you have to manually go and add a separate webhook. So either that webhook should be added automatically, or the import should end with a message telling me to go add it, along with all the settings I need to use.

After adding it manually, builds are working but the webhook shows an error icon, although some OK icons are also there. 

![image](https://cloud.githubusercontent.com/assets/17709550/16786999/c2593f18-484d-11e6-87f0-10d3e0a50063.png)

**Comment by stsewd** [comment]
I'm not sure if I understand the issue. Is this a problem on https://readthedocs.com? If so, you can contact to support for that.
