### ISSUE TITLE
Extraneous session tracking

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2298]
We're currently tracking sessions on documentation page views somewhere. We should only require sessions on dashboard pages. Likely this has something to do with the ad display or the footer calls.

**Comment by travcunn** [comment]
If this has to do with the API calls to retrieve the footer, `FooterNoSessionMiddleware` middleware isn't doing it's job: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/middleware.py#L202

**Comment by ericholscher** [comment]
Looks like we aren't setting this cookie, Rackspace our load balancer is:

`Set-Cookie: X-Mapping-fjhppofk=F369C23A072E7240473DC7A44CD7D010; path=/`

It gets turned off when I turn off **Session Persistence** in the settings.

**Comment by ericholscher** [comment]
Believe this should be fixed:

```
-> curl -i 'https://readthedocs.org/api/v2/footer_html/?project=docs&version=latest'
HTTP/1.1 200 OK
Server: nginx/1.10.3 (Ubuntu)
Date: Fri, 10 Nov 2017 20:39:52 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept, Accept-Language
Content-Language: en
Allow: OPTIONS, GET
X-Frame-Options: DENY
X-Deity: web02
```
