### ISSUE TITLE
Task for update_docs can timeout apparently

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2299]
Stack trace:

```
Jul 13 18:43:51 build02 readthedocs/celery.worker.job[11229]: ERROR Task update_docs[12609cdb-ee39-45f2-b3a6-616a1a920c3c] raised unexpected: TimeLimitExceeded(3600,) [celery.worker.job:282]
Traceback (most recent call last):
  File "/home/docs/local/lib/python2.7/site-packages/billiard/pool.py", line 641, in on_hard_timeout
    raise TimeLimitExceeded(job._timeout)
TimeLimitExceeded: TimeLimitExceeded(3600,)
Jul 13 18:43:51 build02 readthedocs/celery.worker.job[11229]: ERROR Hard time limit (3600s) exceeded for update_docs[12609cdb-ee39-45f2-b3a6-616a1a920c3c] [celery.worker.job:368]
```

This should instead report a failure on the build, not just die. When the celery process is killed, the lock stays around, user is not notified of failure, and the build stays in "Building" state.

**Comment by ericholscher** [comment]
This is a celery setting that we have set.

**Comment by ericholscher** [comment]
We can remove it or raise it if we don't think this is an issue now that we have the Docker time-limiting in place.

**Comment by agjohnson** [comment]
Yeah, the reason for termination is clear. We'll want to do this as an argument to calling the task, as the value of Docker time limit changes with projects.
