### ISSUE TITLE
Delete stale branches

### ISSUE THREAD

**Issue by berkerpeksag** [rtfd/readthedocs.org#2320]
Most of the stale branches at https://github.com/rtfd/readthedocs.org/branches/stale?page=2 have already been merged so they can safely be removed now.

**Comment by ericholscher** [comment]
+1

**Comment by stsewd** [comment]
Can I do this? With merged branches at least :). I really like to see the project clean :grin:

**Comment by humitos** [comment]
@stsewd I suppose that merged branches are safe to remove.

**Comment by stsewd** [comment]
I just delete all merged branches, what a relief! `git fetch --prune`

**Comment by stsewd** [comment]
There are a lot of branches from closed PRs too

**Comment by ericholscher** [comment]
Closing this now, thanks stablebot!
