### ISSUE TITLE
Successfully installing this on a VM or private server

### ISSUE THREAD

**Issue by magicalbanana** [rtfd/readthedocs.org#2322]
## Details

Has anyone ever installed this successfully on a VM or private server that gets the docs from a private git server as well?

I tried doing this but the builds are stuck at **triggered**.

Any help would be much appreciated.

**Comment by berkerpeksag** [comment]
Could you give us a little bit more information? How did you setup the instance? Did you install all dependencies like Celery, Redis, Elasticsearch etc? Did you set up a webhook? How did you trigger the build?

**Comment by zabeloliver** [comment]
Hi, 

i had the same problem. do you use a proxy? that was my problem because of a wrong proxy setting, localhost was tried to be reach through the proxy, so no internal api-calls succeded.

try to call the needed urls by hand whether you could reach them.

**Comment by magicalbanana** [comment]
@zabeloliver it wasn't the proxy, it was the SLUMBER credentials. Not sure what docs I was reading but definitely that part could be written more clearer.

**Comment by splashx** [comment]
@zabeloliver any reference on how to set this up behind proxy? I'm having issues that doing the import doesn't work. After manually hacking the first import to work, the building doesn't work. Then after rolling back the hack, the building works but new imports won't go through. 
It would be good to have a clear step on how to set this up behind proxy.

**Comment by splashx** [comment]
@agjohnson up
