### ISSUE TITLE
Build environment creation failed (even after wiping)

### ISSUE THREAD

**Issue by tjanez** [rtfd/readthedocs.org#2329]
## Details

* Project URL: https://readthedocs.org/projects/resolwe/
* Build URL (if applicable): https://readthedocs.org/projects/resolwe/builds/4225846/
* Read the Docs username (if applicable): tjanez

## Expected Result

Build would start.

## Actual Result

Build fails with:

```
Error

Build environment creation failed
```

## Note

I tried cleaning up the build environment by performing a wipe.

**Comment by DhavalKapil** [comment]
It seems all builds are failing.

I am facing the same issue. Even builds that succeeded earlier:

http://readthedocs.org/projects/elasticsearch-lua/builds/4225879/

**Comment by endyul** [comment]
i am facing the same issue.

[This Build #4070017](https://readthedocs.org/projects/ltp/builds/4070017/) has been building for 1 month, and still not finish

Any new building task will fail with this error msg:

	Build environment creation failed

**Comment by faustin315** [comment]
I'm having the same problem. I even tried the demo project that they offer and it isn't building either. Same error: ``Build environment creation failed.``

**Comment by ericholscher** [comment]
This should be resolved. It was a misconfiguration of a docker image that got updated last night and broke in the middle of the night.

If folks want to ensure better availability in European time zones, we could use more contributors from Europe. You can find more information here: http://docs.readthedocs.org/en/latest/contribute.html

**Comment by cdeil** [comment]
I had the same issue with two projects a few hours ago.
Now I restarted the build and it worked.

I think this issue is resolved.

@ericholscher - Thank you!

**Comment by willingc** [comment]
All is well now. Thanks @ericholscher and team 🐳

**Comment by berkerpeksag** [comment]
Per https://github.com/rtfd/readthedocs.org/issues/2329#issuecomment-234594091, closing this as fixed. Thanks for the report!
