### ISSUE TITLE
pip installs alpha versions of dependencies

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#2339]
## Details
- Project URL: https://github.com/Pylons/zodburi
- Build URL (if applicable): http://docs.pylonsproject.org/projects/zodburi/en/latest/
- Read the Docs username (if applicable): stevepiercy
## Expected Result

When installing dependencies, I expect that only the latest stable version with a distribution, not an alpha version, gets installed.

I expected pip to install, in this case, ZEO 4.2.1.
## Actual Result

The version of pip used by RTD installed ZEO 5.0.0a1.
http://readthedocs.org/projects/zodburi/builds/4246953/
## Workaround

I pinned ZEO to 4.2.1 in my `rtd.txt`:

``` text
ZEO==4.2.1
-e .[docs]
```

And now RTD will download the correct version of the dependency, instead of the alpha version.
http://readthedocs.org/projects/zodburi/builds/4247026/

However this is not a good workaround because it will prevent the latest release of ZEO to get installed when it is ultimately released.

**Comment by humitos** [comment]
This is not something related to RTD but by the command `python setup.py install --force` that it's executed by RTD and how it decides which version of the packages has to install.

`pip` for example has this option to allow pre releases.

    --pre                       Include pre-release and development versions. By default, pip only finds stable versions.

So, we should re-search for the proper argument for `setup.py` to _avoid_ installing pre-release.

Anyway, I'm not sure how is the global opinion on this.

**Comment by stsewd** [comment]
`setup.py install` uses easy_install behind the scenes and I didn't find an option for that https://setuptools.readthedocs.io/en/latest/easy_install.html#command-line-options. I think that is the behavior of setuptools. Also, I find this https://stackoverflow.com/questions/48642708/specify-dependency-range-in-setuptools-setup-py#comment84718849_48642708

**Comment by stevepiercy** [comment]
For a short while, we used `Sphinx >= 1.3.5, != 1.7.3` when there was a bug introduced:
https://github.com/sphinx-doc/sphinx/issues/4889

**Comment by stsewd** [comment]
I'm not sure if rtd can do anything about this, seems like a setuptools issue :/

**Comment by stevepiercy** [comment]
Yeah it is. I'll close this issue.
