### ISSUE TITLE
build timeout

### ISSUE THREAD

**Issue by arsenovic** [rtfd/readthedocs.org#2343]
## Details
- Project URL: https://github.com/scikit-rf/scikit-rf
- Build URL (if applicable):https://readthedocs.org/projects/scikit-rf/builds/4252709/
- Read the Docs username (if applicable): arsenovic
## Expected Result

the build to work
## Actual Result

the build times out

the build doesnt appear to be failing for any reason other than the timeout. is there a way to increase this limit?

**Comment by arsenovic** [comment]
should i post this somewhere else?

**Comment by arsenovic** [comment]
now the builds just hang, and say building. i have tried to `wipe` them, but to no avail. 

https://github.com/scikit-rf/scikit-rf/issues/81

**Comment by agjohnson** [comment]
I believe we solved this yesterday. #2573 also helps this by trying to reduce the number of unreported build exceptions. Closing this here, but feel free to reopen if this is still an issue.
