### ISSUE TITLE
Build hanging for 1.5+ hrs

### ISSUE THREAD

**Issue by ian-s-mcb** [rtfd/readthedocs.org#2345]
## Details

* Project URL: https://github.com/ian-s-mcb/saass
* Build URL (if applicable): https://readthedocs.org/projects/saass/builds/4255819/
* Read the Docs username (if applicable): ian-s-mcb

## Expected Result

Build to succeed, or at the very least, fail with an error message.

## Actual Result

Build has been cloning for 1hr and 53min. Tried wiping the version to stop the build, but it didn't make an observable difference.

**Comment by ian-s-mcb** [comment]
Deleting and recreating the doc on readthedocs.org did the trick. Not sure how the build went on for so long. It ended up running for ~18hrs without any way to stop it.

**Comment by agjohnson** [comment]
This sounds like it was an uncaught exception that killed the build. This periodically happens, and the build state is not reported back.

**Comment by ian-s-mcb** [comment]
@agjohnson Thank you for clarifying.
