### ISSUE TITLE
Support for gerrit in RTD

### ISSUE THREAD

**Issue by rameshthoomu** [rtfd/readthedocs.org#2346]
## Details

I have my markdown files placed in Gerrit tool and I want to build documentation using readthedocs. Is there any option available to build documentation from Gerrit?

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by ericholscher** [comment]
We only support mainstream version control systems. Isn't gerrit a review tool, not a VCS tool?
