### ISSUE TITLE
RTD building old "stable" docs instead of "latest" when auto-triggered from recent push

### ISSUE THREAD

**Issue by chummels** [rtfd/readthedocs.org#2351]
## Details
- Project URL: https://bitbucket.org/trident-project/trident
- Build URL (if applicable): https://readthedocs.org/projects/trident/builds/4264796/
- Read the Docs username (if applicable): chummels
## Expected Result

The "latest" docs to be built when triggered by updates to the BitBucket repository. 
## Actual Result

The "stable" branch of the docs are built when triggered by updates to the BitBucket repository.
## Additional Information

I am not sure if it is related, but in the last few weeks, I have been experiencing some weird behavior with bitbucket's webhooks for automatically triggering RTD builds.  When I push a change to the BitBucket repository, it triggers a webhook to be sent to: https://readthedocs.org/build/trident , but it times out.  It subsequently auto-sends two more webhooks to RTD, each of them timing out too.  

When I look at what builds are occurring on the RTD side of things, there are three separate builds that have been started by these webhooks, each for the "stable" (i.e. old) branch, not the "latest" tip.  After they each build successfully, I receive an email from RTD informing me that my build failed (link to a "failing" build at: https://readthedocs.org/projects/trident/builds/4264796/ ).  After that, I am able to manually trigger a build of the "latest" docs, so RTD knows about the new code, it's just not auto-building it.  I'm not sure how to resolve this issue, but it appears to be a bug somewhere, either on RTD or on BitBucket.  Any suggestions are welcome.  Thank you!

**Comment by humitos** [comment]
Maybe it's related to #2563

**Comment by stsewd** [comment]
@chummels are you still having this issue? Your latest builds are building successfully. I also noted that you migrate the project to GitHub, was because of this issue?

**Comment by chummels** [comment]
We moved to github for a number of reasons, but these problems with rtd were not the main cause.  That said, it appears that the issue is now resolved with the move to github.
