### ISSUE TITLE
Project Search API

### ISSUE THREAD

**Issue by Kapeli** [rtfd/readthedocs.org#2355]
Is there any API to search for projects by name? If not, could this be added? 

Alternatively, is it ok if I cache the list of projects (as returned by https://read-the-docs.readthedocs.io/en/latest/api.html#projects) on my servers and implement my own search?

This is related to: https://github.com/rtfd/readthedocs.org/issues/662#issuecomment-141514217.

**Comment by berkerpeksag** [comment]
If I read https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/views/search_views.py correctly, it's not possible to search for projects by name. You'll need to provide both `q` and `project` (project slug) parameters. Perhaps we can make `project_search` to search for project name or slug.

(Note that API v1 is being replaced by API v2.)

**Comment by humitos** [comment]
@Kapeli you can search project by name using this endpoint:

    http "https://readthedocs.org/api/v2/search/project/?q=turtle"

I'm closing this issue since I think it's solved. Please, re open if you consider.
