### ISSUE TITLE
rtd.com building a version, but not creating docs

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2358]
## Details

* Project URL:  (private, RTD folks can see it at https://readthedocs.com/projects/signalfx-product-docs/)
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

Upon successful build of branch (version), docs should be available at https://signalfx-product-docs.readthedocs-hosted.com/en/analytics-improvements/

## Actual Result

Build successful, but no docs

<img width="924" alt="screen shot 2016-08-09 at 1 44 36 pm" src="https://cloud.githubusercontent.com/assets/17709550/17527141/25f9e824-5e38-11e6-8d2f-6f39a13a5d40.png">

<img width="591" alt="screen shot 2016-08-09 at 1 44 44 pm" src="https://cloud.githubusercontent.com/assets/17709550/17527142/25fac46a-5e38-11e6-97bd-d4abe1636fd3.png">

**Comment by agjohnson** [comment]
Closing this, it should be resolved.
