### ISSUE TITLE
GitHub service issue: The social account is already connected to a different account. 

### ISSUE THREAD

**Issue by foxbunny** [rtfd/readthedocs.org#2360]
## Details

I am using [this profile](https://readthedocs.org/profiles/outernet/) to log in. In the past, I would log in with this account, then connect to my foxbunny GH account to retrieve the list of projects. This time, however, RTD seems to have decided that 'foxbunny' is a [separate profile](https://readthedocs.org/profiles/foxbunny/) which I cannot log into since I never actually signed up to create it in the first place. Disconnecting the connection from the GitHub side did not help.
## Expected Result

Expected the outernet profile to be able to connect to foxbunny GH account.
## Actual Result

The foxbunny GH account is taken over by a foxbunny profile that cannot be logged into using any of the emails that are connected to the GH account.

**Comment by acouch** [comment]
I'm having the same issue.

**Comment by ericholscher** [comment]
This was a bug that we had for a long time, but has been fixed for a number of months. If you login with GitHub (https://readthedocs.org/accounts/github/login/?process=login) it will bring you to your account connected with that GitHub account, which you can then unlink (https://readthedocs.org/accounts/social/connections/) to fix this.

**Comment by 1a1a11a** [comment]
The disconnect button not working, it does nothing just return to the same page.

**Comment by 1a1a11a** [comment]
Solved by deleting account. Thank you!
