### ISSUE TITLE
How to install on a private server with elastic search enabled

### ISSUE THREAD

**Issue by magicalbanana** [rtfd/readthedocs.org#2361]
## Details
Does anyone know or have configured RTD on a private server that is much as like as readthedocs.org? It would be great if someone can share their configuration that has elastic search enabled and postgers as a backend database.

**Comment by ericholscher** [comment]
Going to close this, as we don't support internal installs (http://docs.readthedocs.io/en/latest/open-source-philosophy.html#unsupported)
