### ISSUE TITLE
Unable to add subproject

### ISSUE THREAD

**Issue by mspanc** [rtfd/readthedocs.org#2365]
## Details
- Project URL: docs.radiokit.org
- Build URL (if applicable):
- Read the Docs username (if applicable): radiokit
## Expected Result

I am trying to add `radiokit-depot` as a subproject to `radiokit` with alias `depot`. It should be added.
## Actual Result

It shows error message `Project radiokit-depot does not exist` despite project being visible in my project list.

**Comment by stsewd** [comment]
Are you still having this issue? I think this problem is (was?) because the slug is `depot-docs`, no `radiokit-depot` as the name, probably that value is sent. I going  to see the code later.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
