### ISSUE TITLE
Feature request: Add gitlab as connected service on readthedocs.org 

### ISSUE THREAD

**Issue by rtvisser** [rtfd/readthedocs.org#2374]
I'm using gitlab.com to host my repro's and would like to use readthedocs.org, unfortunately this is only available for github and bitbucket at the moment. I would like to avoid creating a repro on github specifically for this.

As Bitbucket and Gitlab are getting closer in terms of popularity, it makes broader sense to add this intergration to readthedocs.org (https://www.google.com/trends/explore?date=all&q=bitbucket,gitlab). Also, based on the issues and merge requests, it seems that the gitlab integration is available.

**Comment by ericholscher** [comment]
You can use gitlab repos on Read the Docs via the normal git-based cloning mechanism. We also have a gitlab webhook I believe, which should keep your docs up to date.

**Comment by agjohnson** [comment]
This is being addressed in #1870 -- so no webhook support yet. Closing this as a duplicate.

**Comment by rtvisser** [comment]
Thank you, I wasn't sure if there were separate issues for the hosted version of RTD, great work on RTD btw and looking forward to the integration.

**Comment by ericholscher** [comment]
We have a webhook for it here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/views/hooks.py#L176
