### ISSUE TITLE
Can't register at www.readthedocs.io

### ISSUE THREAD

**Issue by cypromis** [rtfd/readthedocs.org#2375]
I have tried with multiple email addresses (gmail based, my mail server based and exchange bases) to register on readthedocs.io and I never get a confirmation email so I can never log in. Asking for a password change works but since the account is probably never set to active this has no real productive result. Anybody who could help with that, I find that a major problem .....

**Comment by ericholscher** [comment]
What URL did you register at?

**Comment by ericholscher** [comment]
Also what is the account name?

**Comment by ericholscher** [comment]
Also, you should be able to login without confirming your email address -- what exactly is the error you're getting?

**Comment by cypromis** [comment]
https://www.readthedocs.io/accounts/signup/
cypromis, cyprolizard is what I tried. 
cypromis looks like it registered but login in here: https://www.readthedocs.io/accounts/login/ just gets me back to the login page with an attribute and asks me to log in: https://www.readthedocs.io/accounts/login/?next=/dashboard/

I never get any dashboard or anything, just the login fields again.

**Comment by ericholscher** [comment]
Bleh, this is a bug. You should be registering at readthedocs.org -- for some reason that URL isn't redirecting properly. (the same URL at `https://readthedocs.io` will redirect)

**Comment by ericholscher** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NFYhsc3p&#x2F;145-fix-www-readthedocs-io-links-working"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Fix www.readthedocs.io links working</a>

**Comment by ericholscher** [comment]
This should now be fixed.
