### ISSUE TITLE
Send doc build status to GitHub Commit Status API

### ISSUE THREAD

**Issue by jodal** [rtfd/readthedocs.org#238]
It would be lovely if ReadTheDocs would use GitHub's new [Commit Status API](https://github.com/blog/1227-commit-status-api) to annotate commits that triggered doc builds with the doc build result, in much the same way as Travis CI does for the test suites.

**Comment by humitos** [comment]
I think this is duplicated of https://github.com/rtfd/readthedocs.org/issues/1340

**Comment by agjohnson** [comment]
Yup, it is. Closing this issue.
