### ISSUE TITLE
python library install error due to missing c lib fails the compilation (even if mocked)

### ISSUE THREAD

**Issue by osallou** [rtfd/readthedocs.org#2384]
## Details
- Project URL: https://readthedocs.org/projects/biomaj/
- Build URL (if applicable): https://readthedocs.org/projects/biomaj/builds/4334338/
- Read the Docs username (if applicable): osallou
## Expected Result

module should install or fail silently. As library is mocked, compilation will not fail at missing library.

_A description of what you wanted to happen_

Installation should have silently failed and compilation started.
## Actual Result

_A description of what actually happened_

While installing the python dependencies via requirements.txt, pycurl fails and compilation stops in error state due to a missing C library. The problem is the whole doc compilation fails because the library cannot install, even if it is not necessary for the doc generation.

```
Collecting pycurl (from -r requirements.txt (line 4))
   Downloading pycurl-7.43.0.tar.gz (182kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
     ....
     __main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
```

**Comment by ericholscher** [comment]
This is because your project is attempting to install the library, which fails. The mocking only works in the Sphinx run. You need to specify a set of installed packages that don't depend on C libraries.

**Comment by osallou** [comment]
So i need a specific requirements file for rtd

Le jeu. 25 août 2016 17:37, Eric Holscher <notifications@github.com> a
écrit :

**Comment by humitos** [comment]
> So i need a specific requirements file for rtd

Yes.

@osallou I will close this issue as invalid. Please feel free to re-open if you consider.
