### ISSUE TITLE
How to configure specific user for gitlab

### ISSUE THREAD

**Issue by deusyss** [rtfd/readthedocs.org#2385]
## Details

Hi,

I'm actually installing a readthedocs server in my office, without any LDAP connection. The VCS is gitlab. All works well, except one small things. When i manually ask to compil documentation, the RTD server, in its terminal, ask me username and password.

I'd like to put them in local_settings.py to simplify the process, because actually, only the RTD admin can compil documentation and add project.

Thanks for your help
## Expected Result

Default username/password are defined, in local_settings.py per example, and are used each time someone clicked on "compil"
## Actual Result

When someone clicked on "compil", the RTD server, in its terminal ask and wait for a username and a password for gitlab.

**Comment by agjohnson** [comment]
Closing this, as there hasn't been any activity from the community here and the core team doesn't have the resources to support third party private installs like this.
