### ISSUE TITLE
Stuck on Installing

### ISSUE THREAD

**Issue by desilinguist** [rtfd/readthedocs.org#2388]
## Details

* Project URL: https://readthedocs.org/projects/rsmtool/
* Build URL (if applicable): https://readthedocs.org/projects/rsmtool/builds/4339964/
* Read the Docs username (if applicable): desilinguist

## Expected Result

The build should have passed since it only takes a few minutes.

## Actual Result

The build seems to be stuck on the installing phrase. On a related note, the status for another branch says "Passed" but there's nothing in the actual docs for that branch. I get the 404 error.

**Comment by desilinguist** [comment]
What's interesting is that I just triggered another build for a different branch and that seems to be building. However, the build for `latest` that I referred to above is still just stuck on "Installing ...".

**Comment by desilinguist** [comment]
2 hours and 17 minutes and still stuck on installing.

**Comment by willingc** [comment]
@desilinguist I'm not sure what the original issue was. It does look as if latest is building now (https://readthedocs.org/projects/rsmtool/builds/4340048/) in 2 seconds. I recommend closing this issue as resolved and reopening if it occurs again. Thanks.

**Comment by desilinguist** [comment]
@willingc so there's no way to remove that build which is still stuck on installing. Is it taking up resources or should I just ignore it?

**Comment by willingc** [comment]
@desilinguist It's safe to ignore it.

**Comment by desilinguist** [comment]
Sounds good. Thanks!
