### ISSUE TITLE
Paginated import UI is unusably slow

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#2392]
I recently linked my Github account to RTD. I'm a member of 8 or so organizations and have hundreds of repos properly in my account.

The UI, apparently introduced in #1695, has several issues.
## Pagination

Although in principle pagination is a good idea, it has several pitfalls.

First, it hides most of the content I want to reach. I can't Ctrl+F to find the project I want if it's not visible. So I'm forced to click through and Ctrl+F for each. The pagination has made my life harder not easier.

Second, the pagination extends beyond a single view. Unless one sets the zoom to a very small size, the page doesn't fit on the page, so one has to page and scroll, a poor user experience.

Third, the pagination buttons are displayed only at the bottom, so after the page loads, one must scroll to the bottom to find the buttons, and then scroll to the top to see the off-view items.
## Performance and Responsiveness

On my account, using Firefox 48.0.1, a page takes 3-4 sec to load. Each click of the pagination takes 3-4 seconds. It takes 10 or so clicks of the Next button, each with this delay, to get to the page that I currently am interested in.

Furthermore, during this delay, there's no indication that anything is happening. If delays of more than a second are to be expected, the UI should present some form of "working" message or UI element to signal to the user to be patient.
## Unable to Filter on Own Projects

It's possible to filter on organizations, but one's own account isn't listed in the filters, so it's not possible to filter for projects in one's own account. One must trudge through the list of repositories, most of which are ancillary projects for which I've never contributed but am only affiliated through the organization, to find the target project in my own account.
# Recommendation

I recommend updating the UI following conventions similar to those employed by the Travis-CI project. First, present all of the personal repositories in a single list. Let the browser's Find feature quickly help the user locate the desired project. Second, only show the organizational repositories if one selects an organization to view. Third, if the list is still considered too big to display, provide a UI element to filter repositories; don't paginate ever.

**Comment by jaraco** [comment]
I've since encountered additional issues.

## Add button does nothing

I click the Add button and nothing happens. I see nothing in the debug console or network traffic. It's as if there's no event bound to the button.

## Return Navigation Resets Page

If one clicks on a repository in the list, that takes them to the repository. If then one clicks the back button to return, the pagination is lost and one returns to the first page.

**Comment by jaraco** [comment]
> each click of the pagination takes 3-4 seconds.

It's gotten worse, pushing 5 seconds.

![image](https://cloud.githubusercontent.com/assets/308610/21365640/2908655a-c6c4-11e6-89ef-580d1d49e3b1.png)

**Comment by pounard** [comment]
I agree, this UI is unusable, at least a search box would be the bare minimum.

**Comment by jaraco** [comment]
This ticket appears to be largely duplicative of #1899.
