### ISSUE TITLE
Branch missing from my project

### ISSUE THREAD

**Issue by nedbat** [rtfd/readthedocs.org#2394]
## Details
- Project URL: https://readthedocs.org/projects/edx-platform-api/versions/
- Build URL (if applicable):
- Read the Docs username (if applicable): edx
## Expected Result

We have a relatively new branch, "open-release/eucalyptus.master" that we want to use as a version.
## Actual Result

That branch is not among the choices on the versions page.

**Comment by ericholscher** [comment]
Is this still an issue? I believe we have some bugs in our version syncing, but guessing this was resolved at some point.
