### ISSUE TITLE
Conda builds fail repeatedly on a branch but build passes if a new doc project is created

### ISSUE THREAD

**Issue by willingc** [rtfd/readthedocs.org#2397]
## Details

* Project URL: 
    - http://readthedocs.org/projects/testnbc/
    - https://readthedocs.org/projects/test-nbconvert/
* Build URL (if applicable): 
    - http://readthedocs.org/projects/testnbc/builds/4358566/
    - https://readthedocs.org/projects/test-nbconvert/builds/4358594/
* Read the Docs username (if applicable): willingc

These projects are built from my repo [willingc/nbconvert](https://github.com/willingc/nbconvert) using branch `doc-channel`.

## Expected Result

I expected that the build on test-nbconvert would pass after wiping the build for the doc-channel branch. I created a new documentation project testnbc that built the doc-channel branch cleanly the first time.

## Actual Result

The build on test-nbconvert would fail for the doc-channel branch even after wiping the version and enabling/disabling the version.

If I had to guess the old conda builds are not being cleared out on test-nbconvert when the version is wiped or disabled/reenabled.

@ericholscher @agjohnson please let me know if you wish for me to try any troubleshooting steps.

cc Jupyter folks @takluyver, @minrk, @Carreau, @michaelpacer

**Comment by ericholscher** [comment]
Some quick googling points to this issue which has a similar odd error: https://github.com/conda-forge/conda-forge.github.io/issues/171

`/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: ncurses-5.9-` seems to be the error, which looks like a conda issue?

**Comment by ericholscher** [comment]
This looks like a dupe of https://github.com/rtfd/readthedocs.org/issues/1902

**Comment by ericholscher** [comment]
Looks like its the length of the project name that is causing the issue, I believe.

**Comment by willingc** [comment]
@ericholscher Could be related to #1902. Though may have some other element as well since the failures were not always doing so with the `/opt/conda/envs/_build_placehold_placehold_placehold_placehold_placehold_placeho' too short in: ncurses-5.9-` errors.

**Comment by willingc** [comment]
I did a bunch of testing last night. The length of the "branch" name seems to be part of the problem.

I'm going to close this issue until I can reliably reproduce the issue and conda-build 2 lands as referenced in #1902.
