### ISSUE TITLE
F score on securityheaders.io

### ISSUE THREAD

**Issue by ThomasWaldmann** [rtfd/readthedocs.org#2400]
See there:

https://securityheaders.io/?q=borgbackup.readthedocs.io&followRedirects=on

It also affects the score given to projects by https://bestpractices.coreinfrastructure.org/ - one of the criteria is like:

```
(Future criterion) It is SUGGESTED that the project website, repository (if
accessible via the web), and download site (if separate) include key
hardening headers with nonpermissive values. [hardened_site]

Note that GitHub is known to meet this.
Sites such as https://securityheaders.io/ can quickly check this.

The key hardening headers are:
Content Security Policy (CSP),
HTTP Strict Transport Security (HSTS),
X-Content-Type-Options (as "nosniff"),
X-Frame-Options,
and X-XSS-Protection.

X-Content-Type-Options was not set to "nosniff".
```

The last line refers to readthedocs.io site.

**Comment by PeterJCLaw** [comment]
Given that the pages on readthedocs.io are (as I understand it) essentially read-only, and users shouldn't ever be submitting credentials to them (all project admin is done via readthedocs.org); what set of security headers is really desirable there?

**Comment by ericholscher** [comment]
Yep -- going to close this, as I don't believe it's really applicable to what we're doing with the site. If there is a specific issue you'd like to highlight, feel free to reopen, and we can discuss adding a specific header and why it would be valuable to our users.
