### ISSUE TITLE
Add persistent messaging

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2403]
## Problem

Currently, we rely on a mix of on-site messaging through ephemeral messages provided by django messages, and through email notifications. We don't currently have a good pattern for messaging/reminding users about required actions -- ie: your project's webhook is not set up correctly, we're having trouble cloning your repo, your builds have been failing, etc.
## Solution

Implement persistent messaging, with messages that can be dismissed by the user. Messages will also track some context as to avoid duplication -- we shouldn't spam a user with on-site messages when builds repeatedly fail.

Tracking what messages have been sent to users will also allow for more troubleshooting, with the ability to determine what users have seen.
## Implementation

To make a generic implementation that handles both email (text/html + subject) and on-site (html), none of the existing solutions for persistent messaging would work well without additional modelling and features.

There are several pieces to this implementation: a class to model the specific messages we're sending -- along with in-code templates for the messages -- backend classes for actually performing the send functions, and modeling to track the messages that have been sent.

More specifically:
- A `MessageSource` class would be created as a base class for specific message text -- storing text and html versions, or perhaps html only with a generic transform for html -> text
- A `Backend` class will specify how to send the message to the user, lightly wrapping email send and session messaging mechanisms
- Backends will be configurable in settings, allowing for custom implementations
- Message objects would be defined in code as constants, specifying the following attributes:
  - Foreign key to User
  - Subject
  - Text
  - Level -- similar/reuse django message levels
  - Unique slug -- this is for deduplication
  - Read -- boolean for dismissing
  - Create/modified/expiration dates
- Messages that haven't been read or expired would be added as messages through middleware, using the standard django message mechanism

**Comment by ericholscher** [comment]
Seems like a good approach. I'd be curious if something like this already exists for Django.

A quick look found:

* https://github.com/samluescher/django-persistent-messages
* https://pypi.python.org/pypi/django-monitio

Though it might be more trouble trying to integrate an existing option than to build our own, it would likely be worth looking into the existing ones.

**Comment by ericholscher** [comment]
Ha, well maybe not monito: https://github.com/mpasternak/django-monitio#do-not-use-this-project :)

**Comment by agjohnson** [comment]
Already found those, among others, but none would work quite how I wanted. `django-persistent-messages` is 6 years unmaintained and the closest project seemed to be https://github.com/AliLozano/django-messages-extends

However, I did start to implement my plan above and might just scale back this implementation. It seems there will be a number of cases where the on-site html and email html will diverge because the site gives a user context -- the email messaging will need to be more verbose perhaps. I'll rethink and update the details above.

**Comment by agjohnson** [comment]
#2406 and a few others implement this. Closing.
