### ISSUE TITLE
Ignored first requirement (Cython>=0.23) from .txt

### ISSUE THREAD

**Issue by KeyWeeUsr** [rtfd/readthedocs.org#2404]
## Details

* [Project URL](https://github.com/KeyWeeUsr/KrySA)
* Read the Docs username same as GitHub
* [Requirements.txt](https://github.com/KeyWeeUsr/KrySA/blob/master/docs/docs-requirements.txt)

Cython is required for Kivy, which I require for building docs, but for some reason is Cython ignored in my project, yet in [other](https://readthedocs.org/projects/kivy/builds/4390124/) projects Cython is fully available. Conclusion - something is wrong with my project, dunno what, last change in setup.py was a few days before the latest successful build.

Kivy is downloaded via url `https://github.com/kivy/kivy/zipball/master` right after Cython requirement, but the building worked before, so I don't think it has something with how I download Kivy.

## Expected Result

* [Build URL](https://readthedocs.org/projects/krysa/builds/4358435/)(passed)

## Actual Result

* [Build URL](https://readthedocs.org/projects/krysa/builds/4378797/)(failed)

When I changed requirements, sometimes it didn't install more than one package. And it built twice - one build was close to a commit on readthedocs.org, the another one was manually triggered a minute ago. I don't understand it at all.

**Comment by KeyWeeUsr** [comment]
In Travis the build requires `Cython` to be installed before `Kivy` (logically as it's dependency) too, I solved it with separating it into two calls - Cython first, the rest later, so probably it'll work with solution from #1112

**Comment by rafaelmendes** [comment]
Hi there, 

Did you find a solution for this? I am facing the exact same problem and I dont know how to work around it...

**Comment by KeyWeeUsr** [comment]
@rafaelmendes With using Travis CI, yes. Unfortunately, I found a reference related to my problem somewhere here in the issues stating that there will be only a single command `pip install -r requirements.txt` and my problem is basically that the `setup.py` of my requirement handles multiple platforms and imports Cython and a file from the git clone of the package during the installation to check some config.

Therefore I need to have Cython and that other requirement installed *before* I install *my* package which isn't possible unless there's a behavior such as:

**requirements_files**: /path/requirements.txt,/something/requirements.txt,...

where for each path an individual `pip install -r <file>` launches in the order of the paths, which I believe currently isn't available and most likely even intended, sadly.
