### ISSUE TITLE
Subversion download failing; reason unclear

### ISSUE THREAD

**Issue by briantoby** [rtfd/readthedocs.org#2409]
## Details
- Project: https://readthedocs.org/projects/gsas-ii/ 
- docs at: http://gsas-ii.readthedocs.io
- from account: briantoby
## Expected Result

_A build would be initiated_
## Actual Result

_Build fails with message_

```
   Error

   Failed to import project: Failed to get code from 'https://subversion.xray.aps.anl.gov/pyGSAS/trunk/' (svn checkout): 1

```

The server was down earlier, but I am now able to see it via a web browser and the `svn ls` command works as well, so I am unsure of the problem. Is there any way to get the actual svn error message?

**Comment by briantoby** [comment]
I should add that there is no hurry to fix this. I am fine with keeping the current version of the docs for the foreseeable future.

**Comment by humitos** [comment]
@briantoby is this still happening to you? wasn't it a temporary error in the svn repository?

What did it changed in the last build that it ends properly?

**Comment by agjohnson** [comment]
This issue has been resolved, so I'll close this out. The error here was that there was a missing certificate from our servers that was causing the svn pull to fail.
