### ISSUE TITLE
Need to delete stale pdf

### ISSUE THREAD

**Issue by tghastly** [rtfd/readthedocs.org#2410]
## Details
- Build URL (if applicable): https://media.readthedocs.org/pdf/pynq/latest/pynq.pdf
- Read the Docs username (if applicable): tghastly

I have deleted the project from my account and now want to delete the pdf called  'pynq.pdf', referenced above

Is there a way for a user to do this or must I request admin assistance for such a deletion as in the case of the earlier issue 1011?

Thanks!

**Comment by ericholscher** [comment]
Seems there is a project with this name: https://readthedocs.org/projects/pynq/
