### ISSUE TITLE
Add Case Insensitive Url Matching Option

### ISSUE THREAD

**Issue by rtpHarry** [rtfd/readthedocs.org#2414]
## Details
- Project URL: http://docs.orchardproject.net/

Our project has come over from a Windows based IIS / Asp.net based website. Windows hosting has case-insensitive urls. This means that Google and various external sites have got links coming in to our project which have different casing to the actual file on the server. 

It would be nice to offer an admin toggle to make the urls for the documentation case-insensitive so that these errors don't crop up. At the moment we have to wait until one is found and then set up a manual page redirection in the admin panel.

Worse still, when the wrongly-cased url is accessed it gets itself stuck in an infinite redirect loop.
## Expected Result

Visiting this page:

http://docs.orchardproject.net/en/latest/Documentation/Working-with-orchard-in-WebMatrix/

Would automatically redirect me to the url with the same filename but different casing:

http://docs.orchardproject.net/en/latest/Documentation/Working-with-Orchard-in-WebMatrix/
## Actual Result

Visiting this page:

http://docs.orchardproject.net/en/latest/Documentation/Working-with-orchard-in-WebMatrix/

Sends the browser into an infinite redirect loop before aborting with a "this page has redirected too many times" error.

**Comment by ericholscher** [comment]
Don't believe this is something we can really do in a good way. You can create a new redirect for yourself in this regard, but automatically redirects to files is outside of our scope I think, and hard to do in a general case.
