### ISSUE TITLE
Builds failing for the past few hours

### ISSUE THREAD

**Issue by RbtShelton** [rtfd/readthedocs.org#2415]
## Details
- Project URL: https://github.com/pjlao307/testrepo.git
- Build URL (if applicable): http://techdocs.readthedocs.io/
- Read the Docs username (if applicable): RbtShelton
## Expected Result

_A description of what you wanted to happen_

Build the project.
## Actual Result

_A description of what actually happened_

Up until about 3 hours ago (Build #4410637 completed at 9/15/2016 at 5:27pm system time), things seemed to be working flawlessly.  For the last hour, I've been trying to build, but getting one of three failures....

1 - Display of the "Triggered" message and spinning wheel keeps on turning, but it does not proceed into the build. 

2 - "Build Failed" message accompanied by "Server Error 502: https://readthedocs.org/api/v1/version/2215463/

3 - "Build failed" message accompanied by "[Errno 30] Read-only file system: '/home/docs/checkouts/readthedocs.org/user_builds/techdocs'"

I have not been able to resolve either one.  Can you help?  

Best

**Comment by humitos** [comment]
@RbtShelton is this still happening to you? I would relate this to an upgrade in the RTD servers or something like that.

I can see that the last builds were working properly for you.

**Comment by RbtShelton** [comment]
Thanks for the follow-up, Manuel.

As you indicate, I had subsequent builds that were successful.

Recently, we’ve been migrating away from read-the-docs to another platform that comes closer to our needs, so I can’t tell you whether or not the problem still occurs.   But as I said, I had more recent successes than I did the earlier issues.

Robert

**Comment by humitos** [comment]
@RbtShelton OK, I'm closing this one. Please feel free to re-open if you consider.
