### ISSUE TITLE
HTTPS redirect for readthedocs.io projects

### ISSUE THREAD

**Issue by sambrightman** [rtfd/readthedocs.org#2417]
## Details
- Project URL: http://pydocstyle.readthedocs.io

Just an example, I guess the applies to all projects. The main page (http://readthedocs.io) redirects to https://readthedocs.org though.
## Expected Result

Redirect to https://pydocstyle.readthedocs.io
## Actual Result

Stays on plain HTTP.

**Comment by agjohnson** [comment]
Duplicate of #3282
