### ISSUE TITLE
sphinx.ext.imgmath not found

### ISSUE THREAD

**Issue by xoorath** [rtfd/readthedocs.org#2418]
## Details

* Project URL:  https://readthedocs.org/projects/xo-math
* Build URL (if applicable): https://readthedocs.org/projects/xo-math/builds/4419629/
* Read the Docs username (if applicable): xoorath

## Expected Result

sphinx.ext.imgmath should be supported the same way it is when following the setup instructions locally for RTD. No additional installation or setup is required to get imgmath to work on OSX. I would expect that this should be the same on RTD unless a workaround is documented.

## Actual Result

Imgmath is not found and causes throws an exception. If there is a workaround for having RTD find imgmath, then I could not find this information during setup.

```
Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
```

**Comment by xoorath** [comment]
I found the solution in someone elses project, although I must say I went through one heck of a time finding this solution.

I needed to add:

\<documentation root>/**conf.py** 
    `needs_sphinx = '1.4.3'`

\<documentation root>/**requirements.txt**
    `Sphinx>=1.4.3`

requirements.txt was a new file in my case, that line is all I need in there. 

From the error messages it wasn't clear that A) RTD uses an old sphinx version and B) how to update sphinx. OR to have new RTD projects default to the latest packages since that's what they'll be getting if they follow the setup guide. 

I'd suggest adding to the setup guide a note on the sphinx version and how to update it.

**Comment by Gabriel-p** [comment]
I've been dealing with this error for months now. I can't believe this hasn't been added to the RTD's site somewhere, it's a pretty big deal.

Thanks for sharing the solution @xoorath!

**Comment by isomorphisms** [comment]
I needed to comment out the offending module.

```
# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
#    'sphinx.ext.pngmath', # imgmath is not supported on readthedocs.
    'sphinx.ext.ifconfig',
]
```

where `# sphinx.ext.pngmath` was added by me.

**Comment by RichardLitt** [comment]
Thanks. Please open new issues, as this one is quite old. :)
