### ISSUE TITLE
Add "lang" attribute to html

### ISSUE THREAD

**Issue by Artoria2e5** [rtfd/readthedocs.org#2419]
## Details
- Project URL: https://pypinyin.readthedocs.io
- Build URL (if applicable): (persists)
- Read the Docs username (if applicable): (irrelevant)
## Expected Result

A project with a language specified should end up with appropriate `lang` attribute in `<html>` or `<body>` to label the whole page as of a certain language.
## Actual Result

Nothing seen for `en`, neither for `zh_CN`.

**Comment by humitos** [comment]
@Artoria2e5 I think that is more related to your Sphinx setting (https://github.com/mozillazg/python-pinyin/blob/master/docs/conf.py#L63) or/and the sphinx theme you are using than RTD itself.

**Comment by ericholscher** [comment]
Yep, this is something that you would want to fix in Sphinx. We're passing a language into it, and the template should be using that to produce the result you'd like.
