### ISSUE TITLE
Relative Links No Redirection

### ISSUE THREAD

**Issue by sjezewski** [rtfd/readthedocs.org#2422]
## Details
- Project URL: http://pachyderm.readthedocs.io/
- Build URL (if applicable): n/a
- Read the Docs username (if applicable): n/a
## Expected Result

I would expect

`http://pachyderm.readthedocs.io/getting_started/getting_started.html`

To redirect to the proper default language / version:

`http://pachyderm.readthedocs.io/en/latest/getting_started/getting_started.html`
## Actual Result

a 404

I've found the `Redirects` section under the admin panel, but I don't see a way to do this for all assets on the site.

E.g. A 'prefix redirect' allows me to do:

`faq.html -> /$lang/$version/faq.html`

But I want to do this for all pages by default. Is there a way to do this?

**Comment by humitos** [comment]
@sjezewski I'm not following you correctly. Why the redirect you suggested is not enough?

**Comment by sjezewski** [comment]
I think its possible to do it that way, but unwieldy.

If I have ~500 unique pages on my site, it's kind of a pain to enter 500 new redirect rules to accommodate each page. And harder to keep that list up to date w all the pages (as I add or delete documents from the site).

**Comment by humitos** [comment]
It's not the same, but it's related to #2904

**Comment by stsewd** [comment]
This is a new feature and needs a design decision. Related to https://github.com/rtfd/readthedocs.org/issues/2968 and https://github.com/rtfd/readthedocs.org/issues/3465

**Comment by stsewd** [comment]
Although, I think this can be done with our new $rest keyword, see https://docs.readthedocs.io/en/latest/user-defined-redirects.html#exact-redirects

**Comment by stsewd** [comment]
Ok, I can confirm I was able to make this redirect with this.

![screenshot_2018-08-31 edit redirects read the docs](https://user-images.githubusercontent.com/4975310/44931761-5ddf1c00-ad28-11e8-85f3-8f6842bc7b98.png)

I'm closing this issue, as this can be done with the above redirect, feel free to reopen if you consider

**Comment by humitos** [comment]
I think the redirect needed here is `/$rest -> /en/latest/`
