### ISSUE TITLE
Build from custom Makefile

### ISSUE THREAD

**Issue by ddeboer** [rtfd/readthedocs.org#2423]
## Details
- Project URL: http://docs.zotonic.com/
- Build URL (if applicable): https://github.com/zotonic/zotonic/blob/master/.travis.yml#L18
## Expected Result

When a Makefile is available, run `make html` instead of the `sphinx ...` command. This allows us to customise the build, for instance by generating some .rst files based on source files.
## Actual Result

The `sphinx ...` build command cannot be overridden.

**Comment by agjohnson** [comment]
The best way to address this would be to extend Sphinx. Allowing a makefile breaks our usage of Sphinx, so not really a possibility.

A Sphinx extension has all the capabilities of a makefile though, and should be more flexible as it has context of the sphinx application.
