### ISSUE TITLE
search for the word "url" on nbsphinx fails

### ISSUE THREAD

**Issue by michaelpacer** [rtfd/readthedocs.org#2426]
## Details
- Project URL: https://github.com/sphinx-doc/sphinx
- Build URL (if applicable):
- Read the Docs username (if applicable): 
## Expected Result

_A description of what you wanted to happen_

When searching for the term "url" using readthedocs search on the nbsphinx-docs website, it should return a search for the term "url" in the docs.
## Actual Result

_A description of what actually happened_

When searching for the term "url" using readthedocs search on the nbsphinx-docs website, it gets replaced with html with an emphasis tag. You get a 400 Bad Request message.

See https://github.com/sphinx-doc/sphinx/issues/2974 (which referred me here).

**Comment by ericholscher** [comment]
I can't reproduce this. I'll need more information to attempt to fix it, can you show me what URL this is happening?

**Comment by michaelpacer** [comment]
It seems to be fixed now.
