### ISSUE TITLE
Impossible to build notebooks with Scipy requirements via nbsphinx on readthedocs.io

### ISSUE THREAD

**Issue by timstaley** [rtfd/readthedocs.org#2429]
* Project URL (simple test case): https://github.com/timstaley/nbsphinx-rtd-test
* Build URL: http://readthedocs.org/projects/nbsphinx-rtd-test/builds/4452250/
* Read the Docs username: timstaley

Hi there,
I'm trying to use [nbsphinx](http://nbsphinx.readthedocs.io/) to display some ipython notebooks on RTFD, but have run into an issue when the package install requires Scipy. Using Scipy on RTD requires the 'system-site-packages' option to be switched on, but this seems to result in the virtualenv getting an old version of setuptools, which seems to cause the Pygments parser problems when it's called as part of NBSphinx.

I also submitted this as [an issue](https://github.com/spatialaudio/nbsphinx/issues/64) to the NBSphinx project, but wanted to ask if the RTD team has any suggestions - seeing as I've got a simple test-build set up it should be easy to verify, and the build runs fine locally. 

Many thanks!

**Comment by mgeier** [comment]
Is there a reason why `setuptools` version 3.3 is installed on RTD (for Python 2)?
It seems to be extremely old ...

Installing `setuptools>=18.5` should solve this issue.

**Comment by timstaley** [comment]
The virtualenv is definitely getting a recent version of setuptools:
```Successfully installed Jinja2-2.8 ... setuptools-21.2.1  ...```
(From the build log)
it's just the system version that's ancient.
