### ISSUE TITLE
List of redirects doesn't say which URLs are being redirected (if exact redirects)

### ISSUE THREAD

**Issue by ttmc** [rtfd/readthedocs.org#2431]
## Details
- Project URL: https://readthedocs.org/projects/bigchaindb/
- List of project redirects (URL): https://readthedocs.org/dashboard/bigchaindb/redirects/
## Expected Result

When I make a bunch of redirects, I would expect the list of exact redirects to say the URL being redirected (and maybe where). Maybe the list would be simple but I'd be able to click on each item to see the details (such as the URL which get redirected and where).
## Actual Result

The actual list of redirects doesn't say anything about each one, other than it's an "Exact Redirect" (as seen in the image below). Also, I can't click on a redirect to find out more information about it.

What if I want to remove one (but only one) redirect? How can I pick the one to remove?

<hr>

![list_of_redirects](https://cloud.githubusercontent.com/assets/1210951/18984645/06cac79a-86f4-11e6-9d5b-7854c4959615.png)

**Comment by ttmc** [comment]
:tada:

**Comment by RichardLitt** [comment]
Thank you, @ttmc! :D
