### ISSUE TITLE
Build is failing during running pip

### ISSUE THREAD

**Issue by idizh** [rtfd/readthedocs.org#2434]
## Details

I have deployed RedaThedDocs on my local PC, during building it throws errors.

> python: can't open file 'C:...\readthedocs.org\user_builds\test\envs\latest\bin\pip': [Errno 2] No such file or directory

I can't understand why it calls pip from bin directory while it doesn't exists
Environment was installed, configured like in installation guide,  path and tags without white spaces.

**Comment by idizh** [comment]
I found this one [http://stackoverflow.com/questions/13206990/virtualenv-env-not-creating-bin-directory-in-windows-7](url)

> Some paths within the virtualenv are slightly different on Windows: scripts and executables on Windows go in ENV\Scripts\ instead of ENV/bin/ and libraries go in ENV\Lib\ rather than ENV/lib/.

But why ReadTheDocs Build engine calls pip from bin, not from Scripts folder?

**Comment by agjohnson** [comment]
Closing this, I don't think we'll get around to solving this. The core team doesn't support Windows as a platform, mostly due to problems with symlinking.
