### ISSUE TITLE
Our subdomain connects to someone else's docs

### ISSUE THREAD

**Issue by ttmc** [rtfd/readthedocs.org#2437]
## Details
- Project URL: https://bigchaindb.readthedocs.io/en/latest/ 
- Read the Docs username: bigchaindb_admin
## Expected Result

Our current docs can be seen at https://bigchaindb.readthedocs.io/en/latest/ 

We wanted to have the same docs at docs.bigchaindb.com i.e. an alternate domain (a subsomain of our bigchaindb.com domain), so we followed the instructions at:

https://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-support

1) We registered the bigchaindb.com domain name with gandi.net some time ago. You can see our main website at that domain:  https://www.bigchaindb.com/ 
2) The nameservers are at CloudFlare, and (as instructed) we added a CNAME there, so that `docs.bigchaindb.com` points to `readthedocs.io`. Here's what `dig docs.bigchaindb.com` returns:

``` text
$ dig docs.bigchaindb.com

; <<>> DiG 9.9.5-3ubuntu0.9-Ubuntu <<>> docs.bigchaindb.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 62092
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;docs.bigchaindb.com.       IN  A

;; ANSWER SECTION:
docs.bigchaindb.com.    300 IN  CNAME   readthedocs.io.
readthedocs.io.     300 IN  A   162.242.198.235
```

3) We logged into readthedocs.org as `bigchaindb_admin`, went to the BigchainDB project - Admin - Domains, and added a new domain: bigchaindb.com. A screenshot is shown below.

![project-bigchaindb-admin-domains](https://cloud.githubusercontent.com/assets/1210951/19112981/e7acf5be-8b07-11e6-82b5-d724bce2d808.png)
## Actual Result

We waited a while and then visited http://docs.bigchaindb.com in our web browser.

Our web browser changed the address to http://docs.mio-lang.org/zh_CN/latest/ 

Those are not our docs. (They appear to be a translation of ReadTheDocs docs into another language.) What is going on?

Changing the checkbox beside "This Domain is the primary one where the documentation is served from." did not fix this problem.

**Comment by barbara-sfx** [comment]
Our domain is set to docs.signalfx.com, so maybe yours should be docs.bigchaindb.com

**Comment by ttmc** [comment]
Oh wow, that worked! Thanks @barbara-sfx 

TODO: The documentation at 

https://read-the-docs.readthedocs.io/en/latest/alternate_domains.html#cname-support 

should be more clear about what one should fill in as the "Domain" in the ReadTheDocs admin. (docs.bigchaindb.com is a subdomain, not a domain.)

**Comment by humitos** [comment]
@ttmc would you like to make a PR by explaining this in a better way?
