### ISSUE TITLE
Exclude page from search engines

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2439]
## Details
- Project URL: docs.signalfx.com
- Build URL (if applicable):
- Read the Docs username (if applicable): 

We have a few docs in our doc set that people get to only by clicking a specific link we give them. We'd like to exclude those docs from our local search results as well as from google etc. Is there a way to do this? 

Thanks -- Barbara

**Comment by humitos** [comment]
Maybe related to #2430 which talks about `robots.txt`

**Comment by humitos** [comment]
Closing as duplicated.
