### ISSUE TITLE
Build webhook

### ISSUE THREAD

**Issue by NikitaEgorov** [rtfd/readthedocs.org#2441]
How i could call build specific version from git webhook?

I found only one URL

```
 url((r'^build/'
         r'(?P<project_id_or_slug>{project_slug})'.format(**pattern_opts)),
        hooks.generic_build,
        name='generic_build'),
```

How i specify branch name (version)

**Comment by agjohnson** [comment]
We get this data from the github json that is pushed with the webhook. You shouldn't be pushing to this unless you're github. It sounds like you want the generic webhook:
http://docs.readthedocs.io/en/latest/webhooks.html#others
