### ISSUE TITLE
Ethical Advertising & Acceptable Ads

### ISSUE THREAD

**Issue by sahal2080** [rtfd/readthedocs.org#2443]
As a proponent of community-led standardization I encourage the the project maintainers to take a look at [Acceptable Ads](https://acceptableads.com/en/). More awesome if you join its [committee](https://acceptableads.com/en/committee/apply)!

Either way, thanks for an awesome project that many benefit from everyday.

**Comment by ericholscher** [comment]
We're not really an ad network, and are serving our ads from first party servers. I believe this means that they shouldn't be blocked, since they aren't really ads in the traditional sense that these tools don't like. I'm going to close this for now, but thanks for the idea, and kind words :)
