### ISSUE TITLE
Question: How to redirect from old branch to new branch documentation at ReadTheDocs?

### ISSUE THREAD

**Issue by fgalan** [rtfd/readthedocs.org#2444]
(This issue comes from http://stackoverflow.com/questions/39882805/how-to-redirect-from-old-branch-to-new-branch-documentation-at-readthedocs, so I haven't just copy-pasted instead of using the suggested issue template. I hope this would be also acceptable).

We are rendering ReadTheDocs (RTD) documentation for a software project hosted at github (in particular, [this one](https://github.com/telefonicaid/fiware-orion)).

Recently we have changed our main branch due to internal policies. In the past we used "develop" as main branch. Now, we are unsing "master" as default branch. The "develop" branch is still in our repository, but it is not receiving new contributions (at the end, it will be deleted).

The problem is that all the links to documentation (that we have been distributing among our users during years) like this one https://fiware-orion.readthedocs.io/en/develop/user/walkthrough_apiv2/index.html will point to an obsolete piece of documentation, as now the right one is https://fiware-orion.readthedocs.io/en/master/user/walkthrough_apiv2/index.html

Does RTD have some functionality (redirect, alias, etc.) that could solve this problem? As far as I checked, RTD supports several redirection types ("Prefix redirect", "Page redirect", etc.) but after looking them all it seems they cannot do this kind of redirection (or I haven't understood how the work to do it :). I mean redirecting

```
https://fiware-orion.readthedocs.io/$lang/develop/path/to/something.html
```

to

```
https://fiware-orion.readthedocs.io/$lang/master/path/to/something.html
```

Any idea about how to solve this problem or feasible workarounds will be highly appreciated.

**Comment by barbara-sfx** [comment]
I think this answers your question. I believe you would use 

From /develop/  To /master/  

http://docs.readthedocs.io/en/latest/user-defined-redirects.html#prefix-redirects

**Comment by fgalan** [comment]
Thank you very much for the answers.

I'm trying to configure such /develop/ to /master/ redirect using the prefix redirect functionality you mention. However, I'm not able to configure the destination so the outcome is

> Outcome: /develop/faq.html -> /$lang/$version/faq.html

and not the one that I'd need:

> Outcome: /develop/faq.html -> /master/faq.html

See attached screenshot:

![2016-10-13 12_03_50-edit redirects _ read the docs](https://cloud.githubusercontent.com/assets/1534240/19345076/252c1cb8-913d-11e6-8d26-a7b01b941472.png)

**Comment by fgalan** [comment]
Another attemp, this time adding `$lang`. Outcome now shows:

> Outcome: /$lang/develop/faq.html -> /$lang/$version/faq.html

but what I need would be:

> Outcome: /$lang/develop/faq.html -> /$lang/master/faq.html

Screenshot:

![2016-10-13 12_05_54-edit redirects _ read the docs](https://cloud.githubusercontent.com/assets/1534240/19345148/6de546dc-913d-11e6-8951-4cf8bcd32b75.png)

**Comment by shimizukawa** [comment]
+1 to redirecting old-branch to new-branch

**Comment by tk0miya** [comment]
+1

**Comment by barbara-sfx** [comment]
@fgalan  I think you want to go into the Versions setting and change develop (which is what I imagine is there now) to master. In our case, $version = latest

![image](https://user-images.githubusercontent.com/17709550/37712525-8c9d2c44-2cea-11e8-9807-3464f7130a95.png)

**Comment by fgalan** [comment]
A long time has passed since I needed this (October 2016). I'm not sure, but I don't remember that Versions settings that time. Has it been introduced recently (in the Octuber 2016 to now timeframe)?

**Comment by barbara-sfx** [comment]
Well, it's there now, so either it was there and you didn't know it, or it has in fact been added since then. I don't know which.

**Comment by wohali** [comment]
We also want the ability to specify redirects of the form `/$lang/#.#.#` to `/$lang/#.#.#`, or even `/$lang/#.#.#` -> `/$lang/stable`, so that people looking for obsolete versions of the documentation get auto-redirected to the current or a specified supported old version.

**Comment by barbara-sfx** [comment]
@wohali  My guess is that is what prefix redirect is supposed to do, but I just reported that it only has From and not To, so I'm actually not sure how it is supposed to work.

![image](https://user-images.githubusercontent.com/17709550/43913600-5f59e454-9bba-11e8-8d01-85b4129d4ca7.png)

**Comment by stsewd** [comment]
@barbara-sfx please see https://docs.readthedocs.io/en/latest/user-defined-redirects.html

**Comment by barbara-sfx** [comment]
Ah, looks like prefix redirect ONLY redirects to latest version (per response from support, which led me to this doc):

https://docs.readthedocs.io/en/latest/user-defined-redirects.html

I responded: Thanks, that helps. But it would be even better if I could specify where I wanted to redirect to. e.g. Maybe I have /rev4/ and want to redirect to /rev5/ . Can you add this as a feature request?

**Comment by barbara-sfx** [comment]
Thanks, that helps. But it would be even better if I could specify where I wanted to redirect to. e.g. Maybe I have /rev4/ and want to redirect to /rev5/ . Can you add this as a feature request?

-- Barbara

P.S. I also suggest you add a link to that document on the redirects page.

**Comment by humitos** [comment]
I think this is a bug on our side.

First of all, our UX says that a Prefix Redirect will match the _Absolute path_, but taking a look at the code it only consider the `path` as everything that comes _after_ the language and version:

https://github.com/rtfd/readthedocs.org/blob/5d8becd51bc9272511ebd86262a3be5e00c7e851/readthedocs/redirects/models.py#L128

So, for example, if the URL is `/en/2.0/guides/somepage.html` the `path` used to the prefix match is only the `/guides/somepage.html`.

This transformation is done at this function:

https://github.com/rtfd/readthedocs.org/blob/5d8becd51bc9272511ebd86262a3be5e00c7e851/readthedocs/redirects/utils.py#L56-L66

Example:

```
In [25]: path = '/en/2.0/guides/something.html'

In [26]: language, version_slug, path = language_and_version_from_path(path)

In [27]: path
Out[27]: '/guides/something.html'
```

I hope to propose a solution for this soon. Marking as a bug.

**Comment by humitos** [comment]
Hi all! This was deployed yesterday and should be working properly. You may want to create the redirects you weren't able to do it.

Please, if you find any other issue open a new one :)
