### ISSUE TITLE
Help setting up doc for psutil project

### ISSUE THREAD

**Issue by giampaolo** [rtfd/readthedocs.org#2447]
## Details

* Project URL: http://psutil.readthedocs.io/en/latest/
* Read the Docs username (if applicable): giampaolo

Hello, I want to move psutil doc from pythonhosted.org to RTD because pythonhosted.org recently disabled automated uploads:
https://mail.python.org/pipermail/python-dev/2016-October/146611.html

psutil doc originally started on RTD, but I later moved it on pythonhosted.org.
Now psutil url seems to be active:
http://psutil.readthedocs.io/en/latest/
...but I see no way to "edit" it, nor it is listed in "my projects".
I also tried to create a new psutil project on RTD but it says the name it's already taken.

Any advice?

Thanks a lot in advance.

**Comment by giampaolo** [comment]
Bump?

**Comment by agjohnson** [comment]
the `psutil` slug is taken already, here is the project page:
http://readthedocs.org/projects/psutil/

The author is here:
https://readthedocs.org/profiles/grodola/

I assume this is an old profile of yours?

**Comment by giampaolo** [comment]
Oh I see, it's 2 different accounts (yeah grodola is mine). 
Thanks a lot, I will delete the old one then.
