### ISSUE TITLE
Installing package using conda

### ISSUE THREAD

**Issue by bennyrowland** [rtfd/readthedocs.org#2450]
## Details
- Project URL: pylcmodel.rtfd.io
- Build URL (if applicable): https://readthedocs.org/projects/pylcmodel/builds/4497752/
- Read the Docs username (if applicable): bennyrowland@mac.com
## Expected Result

I have some code that requires Python 3.5 to import successfully, so trying to use the conda environment to install the right version of Python. I import the package inside my conf.py to access the current version and also want the package to be installed so that I can use autodoc. However it seems like there is no point in the build where my package is installed, only the dependencies get installed, then sphinx is run. Is there a way to have the package be importable from conf.py using the conda environment?

**Comment by philngo** [comment]
I had a similar issue after switching to a conda build and solved it by adding this setting to my `readthedocs.yml` file.

```
python:
   setup_py_install: true
```
That will run the `python setup.py install --force` command after updating your conda environment.

See http://docs.readthedocs.io/en/latest/yaml-config.html#python-setup-py-install

**Comment by bennyrowland** [comment]
Solved my problem too. Thanks @philngo.
