### ISSUE TITLE
Search results from our domain link to hosted URL

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2456]
## Details
- Project URL: http://docs.signalfx.com
- Build URL (if applicable):
- Read the Docs username (if applicable): 

Step: Search for something, then click  on one of the search results.
## Expected Result

You go to a page http://docs.signalfx.com/whatever
## Actual Result

You go to a page https://signalfx-product-docs.readthedocs-hosted.com/whatever

**Comment by humitos** [comment]
This seems to be already fixed.

Steps I followed:

1. Go to https://docs.signalfx.com/en/latest/
2. Search for "project"
3. Click on the first result
4. I ended at https://docs.signalfx.com/en/latest/admin-guide/custom-prioritized-filters.html?highlight=project

I'm closing this one. Please re-open if you consider.
