### ISSUE TITLE
Recognize search phrases/multiple words as AND, not OR

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#2457]
## Details

I'm not sure if this is an issue or a feature request.
- Project URL: docs.signalfx.com
- Build URL (if applicable):
- Read the Docs username (if applicable): 

Step:
Search for "metric proxy" (including the quotes)
## Actual Result

All docs containing _either or both words_ are returned. We have the word "metric" on many many pages, so these results really don't help.
## Expected Result

Ideal: Only pages containing the exact phrase "metric proxy" are returned.
Better than now but not ideal: Only pages with both words are returned

In general, if a search phrase has multiple words, without quotes, I think this should be interpreted as a boolean AND, so only pages containing _both words_ should be returned.

**Comment by austin-plixer** [comment]
Our company is looking for this feature request as well. It would be very helpful to our readers to search a phrase. 

Even if that meant wrapping the search string with quotes as a workaround, it would greatly improve the search feature.

**Comment by ericholscher** [comment]
I'd like to get this as one of the next steps in our Summer of Code project. Having the ability to search with quotes and other common "google style" search queries would be a really good improvement for our search.

**Comment by ericholscher** [comment]
So, this feature should:

* Allow searching of exact terms ("run the tests" and not return results that just mention `tests`)
* It should search in a case insensitive manner ("Run the Tests" should return `run the tests`)

**Comment by barbara-sfx** [comment]
Can linking to a heading above the search term rather than just the top of the doc also be part of the summer of code? (Your link to projects above is 404 so I can't see what's already there.)

**Comment by safwanrahman** [comment]
@barbara-sfx The project has been made public. You will be able to access it now.

**Comment by safwanrahman** [comment]
@barbara-sfx The project has been made public. You will be able to access it now.

**Comment by barbara-sfx** [comment]
Thanks @safwanrahman.  How would I create a feature request for you guys to prioritize and determine if/when you might address it? Ideally, clicking on a search result would go to the actual matching sentence. I said heading (in my comment above) because I thought that would be more do-able. But navigating to the actual sentence or paragraph is actually what I would expect to see when I click a search result.

**Comment by safwanrahman** [comment]
It has been fixed by #4292 
Thanks a lot @barbara-sfx for the issue!
Wishing for the best to get it deployed.

**Comment by safwanrahman** [comment]
@austin-plixer It has been fixed in the `search_upgrade` branch. We hope to get it deployed within couple of weeks.
