### ISSUE TITLE
"False Build Failure Alarm" when using sphinxcontrib.youtube

### ISSUE THREAD

**Issue by ricyik** [rtfd/readthedocs.org#2461]
## Info
- Build URL (if applicable):
  http://readthedocs.org/projects/pythonic-cs1-build-a-mobile-app/builds/4518302/
## Expected Result

Build pass, and we can see a Youtube Video as in this page:
http://pythonic-cs1-build-a-mobile-app.readthedocs.io/en/latest/you-can-build-an-app-to-impact-the-world.html
## Actual Result

Build failed, but we can actually see the Youtube Video as in this page:
http://pythonic-cs1-build-a-mobile-app.readthedocs.io/en/latest/you-can-build-an-app-to-impact-the-world.html
## A description of what actually happened

The build runs successfully in my local machine and as described above. And **even in readthedocs.org the generated HTML is fine**, but just leaving a build failure. Can you help taking a look? Thanks.

**Comment by agjohnson** [comment]
This looks like it's most certainly a bug with the youtube extension. Can you replicate the issue by executing the same build command locally? It might take set up of our extension locally as well.

**Comment by ricyik** [comment]
Hi Anthony. Local build works.
Actually RTD also produces a visually good output, but just leaving us a build failure. Thanks.

**Comment by ericholscher** [comment]
Looks like this is passing now, going to close it as I assume it's resolved.
