### ISSUE TITLE
The social account is already connected to a different account.

### ISSUE THREAD

**Issue by lambdalisue** [rtfd/readthedocs.org#2462]
I'm not really sure if this is a right place to ask this kind of support request but my GitHub account could not be connected to my ReadTheDocs account somehow.
## Details
1. Login into my GitHub account with 2-step authentication (an account which I used here)
2. Go to https://readthedocs.org/accounts/social/connections/
3. Click "Connect to GitHub"
4. "The social account is already connected to a different account." is appeared.

I could connect to my BitBucket account by the way.
- Read the Docs username (if applicable): [lambdalisue](https://readthedocs.org/profiles/lambdalisue/)

So could anyone could check the database or give me a right place to ask?

**Comment by agjohnson** [comment]
Do you have another user connected already? This could also be related to a bug with signup where users where given a secondary dummy account when signing up with GitHub.

**Comment by lambdalisue** [comment]
> Do you have another user connected already? This could also be related to a bug with signup where users where given a secondary dummy account when signing up with GitHub.

I'm sorry but I could not remember... I use Read the Docs about several years so I may accidentally connect to another user but currently I only know the account I showed.

**Comment by akuzminsky** [comment]
The error message should be more descriptive.
"The social account (*GitHub account*) is already connected to a different account (*ReadTheDocs account*)".

I got same error message. I have a couple of readthedocs accounts and it turns out my github account was already connected to another readthedocs account. Good luck finding which one if you don't remember.

**Comment by lambdalisue** [comment]
So no way to remove the existing connection which I have no idea?

**Comment by akuzminsky** [comment]
that part I don't know. Fortunately I knew all my RTD accounts

**Comment by 1a1a11a** [comment]
I don't have a second account signed up, but I also got this error, anyway to resolve this?

**Comment by daledali** [comment]
?

**Comment by mhuruuk** [comment]
lambdalisue, вы решили проблему? 

Что делать?
