### ISSUE TITLE
`This page does not exist yet` error After `Passing` build

### ISSUE THREAD

**Issue by jwogrady** [rtfd/readthedocs.org#2472]
## Details

http://status26.readthedocs.io/en/latest/ shows "This page does not exist yet." after passing build as described in issues #1868 and #2356 which were previously closed.
## Expected Result

Expected to be able to view the content.
## Actual Result

I push the commit.  The build reported passing, but I got the error when viewing the page.  
Tried to resolve by....
-  clearing restarting browser.
-  manually rebuilding in the admin interface.
  Searching for fixes in the issues lead me to believe this is a recurring bug, but since I can't find an instance in open status I decided it would be best to create a new issue.

**Comment by ericholscher** [comment]
Do you not have an `index.rst` that is able to be displayed at the root?

**Comment by jwogrady** [comment]
This is the repo was trying to build.

https://github.com/status26/docs

Do I need an index.rst file?

**Comment by stsewd** [comment]
@jwogrady Yes, you need to create a index.{md,rts} file. Here you can see your docs http://status26.readthedocs.io/en/latest/README/

**Comment by stsewd** [comment]
I think this was a doc problem, and the docs were updated on https://github.com/rtfd/readthedocs.org/pull/3498/commits/d907524ddec69c2530324d9c6cc7011830a209d8 (merged)

**Comment by humitos** [comment]
Updated docs at http://docs.readthedocs.io/en/latest/builds.html
