### ISSUE TITLE
python -mvirtualenv --no-site-packages --no-download /opt/rtd/checkouts/readthedocs/user_builds

### ISSUE THREAD

**Issue by qqbuby** [rtfd/readthedocs.org#2474]
When I build the RTD, it has the `--no-download` option.

What's it ?

How can I disable it ?

Thanks.

**Comment by agjohnson** [comment]
Here's the code:
https://github.com/rtfd/readthedocs.org/blob/499a74076f0debae09acc1d4c4eeeab03f8f557e/readthedocs/doc_builder/python_environments.py#L98

Closing this as it isn't an issue.
