### ISSUE TITLE
DNS seems to have lost our site?

### ISSUE THREAD

**Issue by timabbott** [rtfd/readthedocs.org#2477]
## Details

* Project URL: http://zulip.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): zulip

## Expected Result

Documentation working!

## Actual Result

DNS errors:

"This site can’t be reached

zulip.readthedocs.io’s server DNS address could not be found."

**Comment by agjohnson** [comment]
Not sure what the issue would be, but it seems limited to your end. I get the correct IP resolution:

```
% dig +short zulip.readthedocs.io
162.242.198.235
```

**Comment by timabbott** [comment]
It seems to have fixed itself, but we got reports from several users in multiple countries about the issue, so I'm pretty confident it was actually down.

**Comment by agjohnson** [comment]
We didn't notice any downtime on our side, and there were no changes to DNS recently. This was most certainly upstream from us -- perhaps related to this week's DNS outage?
