### ISSUE TITLE
Password Reset

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [rtfd/readthedocs.org#2479]
## Details
- Project URL: [Password Reset](https://readthedocs.org/accounts/password/reset/done/)
- Build URL (if applicable):
- Read the Docs username (if applicable): _cannot remember it, I just have my mail address which has to be associated to an existing account because when I try to create a new account I am told that this mail address is already being used_
## Expected Result

I have attempted to reset my RTD password multiple times, but have actually received no mail after waiting more than 15 minutes.
## Actual Result

At each attempt a web page displays this message:

> We have sent you an e-mail. Please contact us if you do not receive it within a few minutes.

Yet No mail. Besides, how do I contact you? This ought to be explained, at least by providing a link.

**Comment by agjohnson** [comment]
Support is done on a community basis, an issue here is the best way to contact someone from the community. If you prefer another method of contacting the core team, happy to talk more about a support contract.

I see emails to your servers soft bouncing for whatever reason. Getting this response:
```
499 Unable to connect to MX servers
```

**Comment by DimitriPapadopoulos** [comment]
Strange. There are no known issues on our own MX servers as far as I know, I keep getting mail from other senders. Also:
* I eventually received RTD mails sent to my `dimitri.papadopoulos@` address hours later, so at least they hadn't been rejected as spam. Unfortunately the reset link was not valid anymore - if I recall correctly the reason was that subsequent password resets had been requested. Yet I still haven't seen the "last" mail that should have contained a valid link.
* I ended up creating a new account associated to `dimitri.papadopoulos-orfanos@` and it worked, including a password reset. Mails sent this address have been sent through rapidly.
* I suspect the problem is not on my side.

I'll try a single last password reset of the account associated to the `dimitri.papadopoulos@` mail address.

**Comment by DimitriPapadopoulos** [comment]
Made a new request a few minutes ago, around 2016-10-28 18:50 UTC.

![Password Reset](https://cloud.githubusercontent.com/assets/3234522/19818582/acb03420-9d50-11e6-840d-8c607cfce099.png)

**Comment by DimitriPapadopoulos** [comment]
I received the mail with the reset link shortly after. The link worked and I was able to reset the password. I now have access to the `DimitriPapadopoulos` account.

**Comment by DimitriPapadopoulos** [comment]
Still, I'm wondering why it failed before. Why the soft bounces, and specifically on the `dimitri.papadopoulos@` (ends up into the same mail box as `dimitri.papadopoulos-orfanos@`).
