### ISSUE TITLE
only getting a placeholder index page but no other content

### ISSUE THREAD

**Issue by mikkokotila** [rtfd/readthedocs.org#2480]
## Details
- https://github.com/botlabio/deny-hosting-IP
- http://deny-hosting-ip.readthedocs.io/en/latest/
## Expected Result

To see the the README.md content I have created in Github on the built rtd page. 

I'm doing everything 100% within readthedocs.org and I have authorized Github and have an active websync. 
## Actual Result

I'm only getting a placeholder auto generated index page instead: 

http://deny-hosting-ip.readthedocs.io/en/latest/

**Comment by humitos** [comment]
@mikkokotila the repository you linked has not a valid Sphinx project for Read the Docs. Please, check out the Read The Docs user's guide: http://docs.readthedocs.io/en/latest/getting_started.html
