### ISSUE TITLE
Permalinks to a specific section arrive at the page, but not at the specific section

### ISSUE THREAD

**Issue by zspitz** [rtfd/readthedocs.org#2485]
## Details

* Project URL: http://docs.xlwings.org/en/stable/api.html#xlwings.App.pid

This behavior occurs in other projects as well:

http://pydash.readthedocs.io/en/stable/api.html#pydash.arrays.append
http://pydash.readthedocs.io/en/stable/api.html#module-pydash.collections
http://pyaero.readthedocs.io/en/latest/#features

Tested on Chrome 54.0.2840.71, and Firefox 48.0.2

## Expected Result

The viewport should be scrolled to the hashtagged section

## Actual Result

The page seems to first arrive at the requested section, but then self-refreshes and is reloaded at the top.

**Comment by humitos** [comment]
All the examples you pointed worked perfect for me using Chrome 56.0.2924.87 and Firefox 51.0.1

It doesn't seem to be an issue in the RTD code.

**Comment by zspitz** [comment]
@humitos Just want to confirm that it probably isn't a problem with the RTD code, as this is an issue I've been seeing on multiple sites.
