### ISSUE TITLE
Support, latex in Read the Docs

### ISSUE THREAD

**Issue by ugoproto** [rtfd/readthedocs.org#2487]
## Details

* Project URL: http://ugo-py-doc.readthedocs.io/en/latest/manuals/Python%20for%20Education/
* Build URL (if applicable):
* Read the Docs username (if applicable): ugolbt@gmail.com

## Expected Result

*A description of what you wanted to happen*

In the link above, I have a document with math equations. It's LaTeX. In my markdown editor, I bracket the math between $ z = \frac{x}{y} $. I get a math equation.

Try the above equation in the editor: https://stackedit.io/editor

## Actual Result

*A description of what actually happened*

But Read the Docs does not render math equations or LaTeX. You see the raw $ expression $.

How can we turn the LaTeX option on; if it exists?

Cheers

**Comment by ugoproto** [comment]
I fixed it.

**Comment by QiayuanLiao** [comment]
how to fix it?

**Comment by davidfischer** [comment]
It's unclear precisely how this was fixed since that project no longer exists but I suspect he fixed it along these lines: http://www.sphinx-doc.org/en/stable/ext/math.html
