### ISSUE TITLE
Broken/unpegged django-filter dependency

### ISSUE THREAD

**Issue by atcase** [rtfd/readthedocs.org#2490]
## Details

* Project URL: https://github.com/rtfd/readthedocs.org
* Build URL (if applicable): https://travis-ci.org/rtfd/readthedocs.org/builds/173218817

## Expected Result

Whilst trying to run an instance of readthedocs locally, I ran into exceptions identical to those on the referenced CI build. Specifically `TypeError: 'VersionSlugFilter' object is not iterable`. This occurs on a fresh build, following instructions on http://docs.readthedocs.io/en/latest/install.html and attempting to view / build any of the projects imported by `python manage.py loaddata test_data`.

## Actual Result / Workaround

I noticed that in requirements/pip.txt django-filter is not pegged to any specific version or commit. Adding a reference to a recent release commit resolved the issue on my local installation.

`git+https://github.com/alex/django-filter.git@47042b9#egg=django-filter`

**Comment by zeigerpuppy** [comment]
I am also having this issue on a fresh install (Debian).
I tried adding the reference you mentioned to pip.txt and re-running:

```
pip install -r requirements.txt
python manage.py makemigrations
python manage.py migrate
python manage.py collectstatic
```

That process seemed to go fine but the error remains whenever I try to build or browse to a built project.

```
 'VersionSlugFilter' object is not iterable
```

**Comment by agjohnson** [comment]
Closing this, #2499 fixes the issues here.
