### ISSUE TITLE
RTD not loading new versions from branches

### ISSUE THREAD

**Issue by robredpath** [rtfd/readthedocs.org#2491]
## Details

* Project URL: http://openreferral.readthedocs.io/en/latest/
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): robredpath

## Expected Result

I've created a new branch in my docs repo - https://github.com/openreferral/specification/tree/inline-docs . I pushed about 12 hours ago, and the new branch hasn't appeared as a version in RTD, which I was expecting to happen automatically. 

## Actual Result

The 'versions' page in RTD admin shows 4 versions:
![screen shot 2016-11-08 at 08 18 09](https://cloud.githubusercontent.com/assets/641009/20091671/f1f72a32-a58b-11e6-8f67-068a43e33c2a.png) ,

which doesn't reflect the current branches: 

![screen shot 2016-11-08 at 08 18 43](https://cloud.githubusercontent.com/assets/641009/20091692/02123ea2-a58c-11e6-9749-7e852405f636.png)

UPDATE 2016-11-08 17:45 UTC: Branches have now appeared; I'm not sure if that's due to this issue being opened. My immediate problem is fixed, but my expected result of seeing new branches fairly quickly and actual result of it taking 24h are still different.

**Comment by stsewd** [comment]
See related comment here https://github.com/rtfd/readthedocs.org/issues/1822#issuecomment-285510144.

I'm not sure about this use case, but I think is unnecessary to have to build the last docs in order to get the new branch, (probably this one is going to be build too). Having a webhook to do this seems reasonable to me. I going to see the code if this is _easily_ possible.

**Comment by stsewd** [comment]
If we want to add this feature, we need to pass all the tags or branches (we can get this data from the cloned repo), Or we can implement a `patch` endpoint for only add branches.

Should we implement all the crud for versions? When a branch or tag is created or deleted on the repo, we have to update this on the project.

Or... we could call the build process when a new branch is created, this will resync all the versions.

**Comment by stsewd** [comment]
I think this can be also solved with https://github.com/rtfd/readthedocs.org/issues/1375

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
