### ISSUE TITLE
Searching a public site

### ISSUE THREAD

**Issue by ugoproto** [rtfd/readthedocs.org#2492]
## Details

* Project URL: https://readthedocs.org/projects/ugo-py-doc/
* Build URL (if applicable):
* Read the Docs username (if applicable): ugoproto

## Expected Result

*A description of what you wanted to happen*

I would like my site to be searchable. It's the main reason why I created the docs. To be able to search and retrieve info because the webpages are indexed.

## Actual Result

*A description of what actually happened*

Among the 3 projects I created

http://ugodoc.readthedocs.io/en/latest/
http://ugo-py-doc.readthedocs.io/en/latest/
http://ugo-r-doc.readthedocs.io/en/latest/

only the first one is searchable.  _r_ and _py_ have the same settings though? They don't return search results. They are 'public'.

**Comment by agjohnson** [comment]
These sites are using mkdocs. There are a few issues open around mkdocs search. Closing this as a duplicate.
