### ISSUE TITLE
Inactive version URLs produce "permission denied" instead of 404 and redirecting

### ISSUE THREAD

**Issue by toomanybrians** [rtfd/readthedocs.org#2494]
## Details

* Project URL: https://github.com/missionpinball/mpf-docs
* RTD URL: http://docs.missionpinball.org

## Expected Result

We used to have a "dev" and "stable" builds in RTD, but those were too confusing for our users (we host user docs for non-technical users, not library docs). So we decided to use the "latest" version instead. No prob, we enabled that version and disabled the dev and stable versions.

I want it so that old URLs forward to new URLs, e.g. 
http://docs.missionpinball.org/en/dev/versions/roadmap.html -> http://docs.missionpinball.org/en/latest/versions/roadmap.html

## Actual Result

This page http://docs.missionpinball.org/en/dev/versions/roadmap.html produces a "Permissions Denied" page, which I think is not a 404 so that means that none of the redirection options work? I've tried every possible combination of redirects, but I can't get this to work. So is there a way to across the board forward those old versions to the latest version?

**Comment by humitos** [comment]
@toomanybrians going to http://docs.missionpinball.org/en/dev/versions/roadmap.html I get a 404 instead of "Permissions Denied"

Can you share how are your redirect options you have tried?

**Comment by humitos** [comment]
Stale issue. Closing.

Feel free to re-open if you consider. Thanks!
