### ISSUE TITLE
Git clone failures are not detailed enough

### ISSUE THREAD

**Issue by benjaoming** [rtfd/readthedocs.org#2496]
## Details

* Project URL: https://readthedocs.org/projects/ka-lite/builds/
* Build URL (if applicable): https://readthedocs.org/projects/ka-lite/builds/4661619/
* Read the Docs username (if applicable): benjaoming

## Expected Result

I have long been baffled by why our builds have stopped working all by themselves. The output of the build failure is almost entirely useless.. all I can say is that cloning doesn't work on RTD, but of course works fine on my local machine :)

## Actual Result

I've tried developing a RTD locally and found that the actual problem IS within our repo because of a wild `.gitmodules` which someone has put in the repo, and now RTD has started using submodules.

So the actual problem IMO is that error messages don't indicate the actual issue.

I'm PR'ing this now!

**Comment by agjohnson** [comment]
Closing this here. I opened another issue, #2512, as i think we missed some review feedback on the PR. A more complete fix will require altering our exception handling anyways, so there is a larger chunk of work there.
