### ISSUE TITLE
Update django-filter to 1.0

### ISSUE THREAD

**Issue by benjaoming** [rtfd/readthedocs.org#2498]
## Details

Sorry for deleting the issue template: This is about technical debt :) It may not be immediately critical, but the advice from the author of django-filter is that it's worth it.

django-filter 1.0 has changes that are backwards incompatible. The release notes are here:

http://django-filter.readthedocs.io/en/latest/migration.html

It means, amongst other this, that all where  `Filter` object instances are iterated on, we have to [add the `.qs` method](http://django-filter.readthedocs.io/en/latest/migration.html#queryset-methods-are-no-longer-proxied).

**Comment by rpkilby** [comment]
Hi @benjaoming - I'm partly to blame for the API breakage 😅. Feel free to ping me if you have any questions about the changes.

**Comment by benjaoming** [comment]
@rpkilby - thanks! it's a major version bump and with a nice migration guide so it's all in good order I guess :) I've opened the issue, hoping that someone who knows the codebase well is going to do the refactor.. I'm shying away here.

**Comment by rpkilby** [comment]
Hi @benjaoming - went ahead and took a stab at it (see #2501). Not familiar with the RTD source, so I may have missed something.
