### ISSUE TITLE
favourites

### ISSUE THREAD

**Issue by sehmaschine** [rtfd/readthedocs.org#25]
I find myself searching for the same docs over and over again.
IMO, it´d be nice to have something like "favourites", letting people flag the docs the usually read. on the index-page, there could be an additional block (if I´m logged in) showing the docs I´ve marked.

**Comment by ericholscher** [comment]
This was merged, and is deployed. It's limited to only working on non-CNAME sites, but calling this done until we solve that problem at a more general level.
