### ISSUE TITLE
Insecure asset loaded in production

### ISSUE THREAD

**Issue by benjaoming** [rtfd/readthedocs.org#2500]
## Details

> Loading mixed (insecure) display content “http://i2.wp.com/media.readthedocs.org/images/silhouette.png” on a secure page[Learn More]

The default Gravatar URL should be:

    https://media.readthedocs.org/images/silhouette.png

This means adding this somewhere in production settings:

    GRAVATAR_DEFAULT_IMAGE = 'https://media.readthedocs.org/images/silhouette.png'

Currently, users are redirected to `http://i2.wp.com/media.readthedocs.org/images/silhouette.png` which will display a connection warning in nice browsers :)

**Comment by agjohnson** [comment]
Not sure where that url is coming from, we already override this setting to our media assets. Our gravatar setting is not pointing to `https` URL currently though.

What URL are you noticing this issue?

**Comment by benjaoming** [comment]
@agjohnson If you login on readthedocs.org and you don't have a gravatar, the replacement image is set for an insecure URL. It doesn't happen with the dev settings, they're fine (and the dev server isn't running on HTTPS anyways).

**Comment by humitos** [comment]
This is already fixed, I'm seeing the proper silhouette over HTTPS. Closing.
