### ISSUE TITLE
Please change my username

### ISSUE THREAD

**Issue by jeremytedwards** [rtfd/readthedocs.org#2502]
## Details

* Project URL: 
https://readthedocs.org/profiles/pinmanm2020/

* Read the Docs username (if applicable): 
pinmanm2020

## Expected Result
Please change user name from: 
pinmanm2020
to 
pinman2020
(no second 'm')

## Actual Result

username is currently pinmanm2020

**Comment by Shashi456** [comment]
Is there any way i can go about doing this?

**Comment by humitos** [comment]
After https://github.com/rtfd/readthedocs.org/pull/3175 got merged, it's possible to remove your account and create a new one. I think it's fully tested yet, but you can help us on this process.

**Comment by agjohnson** [comment]
Closing this as this doesn't require admin intervention anymore. You can change users by creating the new user, assigning ownership of your projects to the new user, and finally deleting your old user.
