### ISSUE TITLE
Fix up error messages that happen outside build environment

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2512]
The UI behind these error messages is sloppy, and the messages are overly verbose. #2497 introduces an improvement to the amount of error we're reporting, but the error message should be shortened. Mercurial needs a similar error message.

Refs #2497

**Comment by humitos** [comment]
@agjohnson I think this is already done by https://github.com/rtfd/readthedocs.org/pull/3310 and we could close it.
