### ISSUE TITLE
PDF/ePub Build appears to succeed but 404 when trying to view

### ISSUE THREAD

**Issue by 0xHiteshPatel** [rtfd/readthedocs.org#2514]
## Details

* Project URL: http://readthedocs.org/projects/appsvcs-integration-iapp/
* Build URL (if applicable): http://readthedocs.org/projects/appsvcs-integration-iapp/builds/4678173/
* Read the Docs username (if applicable): 0xHiteshPatel

## Expected Result

PDF/ePub files generated and viewable

## Actual Result

Build of both PDF/ePub appears to succeed but trying to access either results in 404 error.  This only happens on this version/branch from GitHub.  The develop/latest version works without issue.  No changes in conf.py between branches.

Working version: http://readthedocs.org/projects/appsvcs-integration-iapp/downloads/pdf/develop/
Working build: http://readthedocs.org/projects/appsvcs-integration-iapp/builds/4677669/

**Comment by agjohnson** [comment]
This looks to be aggressive rewriting of URLs that match `/projects/.*`, which is a problem with our production stack. I'll attach this report to the fix there, which will hopefully go live this week.

**Comment by 0xHiteshPatel** [comment]
Great.  Thanks!

**Comment by ericholscher** [comment]
This is fixed.
