### ISSUE TITLE
keras using theano backend

### ISSUE THREAD

**Issue by stephenhky** [rtfd/readthedocs.org#2516]
## Details

* Project URL: https://github.com/stephenhky/PyShortTextCategorization
* Build URL (if applicable):
* Read the Docs username (if applicable): stephenhky

## Expected Result

I am generating documentation from the docstring in my code. I used virtualenv and allowed readthedocs to install online package directly.

## Actual Result

It has to be noted that the package 'keras' allow both 'theano' and 'tensorflow' backends.

I used the package 'keras', which I assume to be in 'theano' backend. It has been doing theano backend for my first few runs. However, at one point, 'tensorflow' was assumed to be the backend, but then error comes out. As a result, any modules that import 'keras' do not have documention produced.

I wonder how to control the backend. I have no problem compiling it on my own laptop.

**Comment by humitos** [comment]
@stephenhky 

* are you able to build your documentation in your own laptop? is the result as you expect?
* what are the RTD builds that worked as you expected? (links)
* what are the RTD builds that didn't work as you expected? (links)

**Comment by stephenhky** [comment]
Thanks for the reply.

Currently, I temporarily makes the readthedocs show the documentation (I made it to something else because of this bug). And for one of the pages, it shows like this: http://shorttext.readthedocs.io/en/latest/codes.html
However, it is expected to be like this: http://pythonhosted.org/shorttext/codes.html

I am able to build the documentation on my own laptop.

**Comment by stephenhky** [comment]
Sorry that I have to revert the links above because users are reading the documents generated by readthedocs.

**Comment by ericholscher** [comment]
The issue is that we can't import `tensorflow` in the Python environment. http://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc is likely the cause of your issue. You might need to mock it, as documented here: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
