### ISSUE TITLE
pandoc swallows <audio> tags

### ISSUE THREAD

**Issue by mgeier** [rtfd/readthedocs.org#2521]
HTML5 `<audio>` tags are apparently filtered out when using the version of `pandoc` installed on readthedocs.org, while `<video>` tags are fine, see e.g. http://nbsphinx.readthedocs.io/en/0.2.10/markdown-cells.html#HTML-Elements-(HTML-only).

When using `conda` to build (using the `conda-forge` channel BTW), everything is fine.

**Comment by humitos** [comment]
@mgeier did this comment fixed your issue? https://github.com/spatialaudio/nbsphinx/issues/69#issuecomment-262350287, can I close this one?

**Comment by mgeier** [comment]
@humitos Thanks for following up on this!

The mentioned comment is unrelated and didn't fix it, but in the meantime there seems to have been a long-awaited upgrade of packages on RTD, and with the currently installed version of `pandoc` it works!

Thanks!
