### ISSUE TITLE
Default site shows instead if docs

### ISSUE THREAD

**Issue by mspanc** [rtfd/readthedocs.org#2522]
## Details

* Project URL: http://docs.radiokit.org/projects/toolkit-js/en/latest/
* Build URL (if applicable) : https://readthedocs.org/projects/radiokit-toolkit-js/builds/4692360/
* Read the Docs username (if applicable): radiokit

## Expected Result

The Docs built from my source should show up 

## Actual Result

Default docs installation instructions are showing up

**Comment by sanscore** [comment]
You need a `conf.py` file. If you have already have one, then you haven't committed it to your bitbucket repo. If you don't have one, then try (re-)running `sphinx-quickstart` in your `docs/` directory.

**Comment by mspanc** [comment]
Thanks, I have deleted it accidentally
