### ISSUE TITLE
SingleHtmlBuilder is broken w/ patch

### ISSUE THREAD

**Issue by sanscore** [rtfd/readthedocs.org#2526]
## Details

I am trying to produce a project with as i would with Sphinx's `make singlehtml`, however with my internal build of RTD.org, the effect is the same as `make html`. I found the issue in [backends/spinx.py](https://github.com/rtfd/readthedocs.org/blame/master/readthedocs/doc_builder/backends/sphinx.py#L165) which was created by this commit: https://github.com/rtfd/readthedocs.org/commit/ed12559ab3ee3e867387c8cbe75d6471a8db79b3

In the previous commit, an `__init__` method was added to the `HtmlBuilder` and the `HtmlDirBuilder` builders, however the `SingleHtmlBuilder` was unmodified. Since `SingleHtmlBuilder` inherits from `HtmlBuilder , `HtmlBuilder.__init__` is executed and sets the `singlehtml_builder_instance.sphinx_build` to `readthedocs` or `readthedocs-comments`. Which makes it impossible to get the correct value of `shpinx_builder` from the class; `SingleHtmlBuilder.sphinx_buidler == 'readthedocssinglehtml'`.

The fix, found below, is to add a `__init__` method to `SingleHtmlBuilder` and set `self.sphinx_builder` appropriately.

* Project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

1. Set a project's `Documentation type:` to `Sphinx Single Page Html`. 
1. Build docs. 
1. Expect to see a single page of documentation.

## Actual Result

1. Actual result is the normal `Sphinx Html` page is built.

## Patch
```diff
---
 readthedocs/doc_builder/backends/sphinx.py | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/readthedocs/doc_builder/backends/sphinx.py b/readthedocs/doc_builder/backends/sphinx.py
index 3bd95b8..780034b 100644
--- a/readthedocs/doc_builder/backends/sphinx.py
+++ b/readthedocs/doc_builder/backends/sphinx.py
@@ -183,7 +183,10 @@ class HtmlDirBuilder(HtmlBuilder):

 class SingleHtmlBuilder(HtmlBuilder):
     type = 'sphinx_singlehtml'
-    sphinx_builder = 'readthedocssinglehtml'
+
+    def __init__(self, *args, **kwargs):
+        super(SingleHtmlBuilder, self).__init__(*args, **kwargs)
+        self.sphinx_builder = 'readthedocssinglehtml'


 class SearchBuilder(BaseSphinx):
--
```

**Comment by berkerpeksag** [comment]
Closing this as fixed since #2527 has already been merged.
