### ISSUE TITLE
404 / Maze found / RTD demo on all sites

### ISSUE THREAD

**Issue by monotek** [rtfd/readthedocs.org#2529]
## Details

* Project URL: https://zammad.readthedocs.org
* Build URL (if applicable): http://zammad.readthedocs.io/en/latest/
* Read the Docs username (if applicable): monotek

## Expected Result

* Zammad docs are shown

## Actual Result

* Empty / RTD demo site is shown
* 404 @ menulinks like https://zammad.readthedocs.io/en/latest/install-elasticsearch.html

**Comment by monotek** [comment]
Seems to be a proble with .gitmodules and sphinx template

**Comment by polyzen** [comment]
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/404.html
