### ISSUE TITLE
Reset password for account faunadb

### ISSUE THREAD

**Issue by marrony** [rtfd/readthedocs.org#2531]
## Details

* Project URL: http://faunadb.readthedocs.io/en/latest/index.html
* Build URL (if applicable):
* Read the Docs username (if applicable): faunadb

## Expected Result

We of [Fauna, Inc.](http://fauna.com) would like to get access to the account of the username above mentioned. We are trying to reset the password however we're not sure what email has been registered. This account has been created by a former employee that don't work with us anymore.

## Actual Result

No email has been sent

**Comment by agjohnson** [comment]
A fix for this has been deployed, messages should be delivered as expected.
