### ISSUE TITLE
Option to add a comments/feedback form to each documentation page

### ISSUE THREAD

**Issue by brechtm** [rtfd/readthedocs.org#2533]
A feedback form at the bottom of each page could help improve documentation. An example of this is the [PHP documentation](http://php.net/manual/en/language.variables.basics.php).

Notes can  be used to:
- signal that a particular part is not clear
- suggest improvements
- provide additional information

Some ideas and remarks:
- notes could be flagged to indicate their type (comment, suggestion, extra-info)
- notes can be public (viewable by everyone) or private (viewable only by the project owner)
- public notes can be up/downvoted
- all notes can be forced to be private by the project owner
- notes could be attached to specific paragraphs, so that readers can view only those relevant to what (s)he is reading
- how to handle this across documentation for several project versions?

The [sphinxcontrib-disqus](https://robpol86.github.io/sphinxcontrib-disqus/) extension offers something similar, but this can be improved upon.

**Comment by humitos** [comment]
Since #3618, I'd say that this is not longer going to be implemented by RTD core team. I'm closing this here, but feel free to reopen if you consider.
