### ISSUE TITLE
Build stuck in installing for 2 weeks 2 days. 

### ISSUE THREAD

**Issue by Einstein42** [rtfd/readthedocs.org#2535]
## Details

* Project URL: https://readthedocs.org/projects/ud-polyglot/
* Build URL (if applicable): https://readthedocs.org/projects/ud-polyglot/builds/4664726/
* Read the Docs username (if applicable): einstein.42

## Expected Result

Completed build of documents

## Actual Result

Completed, docs will build but not update for new versions. 
Above build url, stuck in 'installing' for 2 weeks 2 days.

**Comment by humitos** [comment]
Related to #2407

**Comment by humitos** [comment]
I'm marking this as `Operations` since we need access to the servers log to see what happened and try to attack the main reason.

**Comment by ericholscher** [comment]
This is a bug that we have, when a process gets killed uncleanly, the build state never gets re-updated. It is a known issue, so I'm going to close this specific issue, and hopefully we'll fix it soon.
