### ISSUE TITLE
KeyError: 'caption' in docutils/nodes.py

### ISSUE THREAD

**Issue by goulu** [rtfd/readthedocs.org#2537]
## Details

* Project URL: https://readthedocs.org/projects/goulib/
* Build URL : https://readthedocs.org/projects/goulib/builds/4737525/
* Read the Docs username : Goulu

## Expected Result

* Doc builds correctly in local with Py 3.5 + Sphinx 1.4.6

## Actual Result
(... many messages...)
```
writing... 
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/goulib/envs/latest/local/lib/python3.4/site-packages/docutils/nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: 'caption'
```

## Solution ?
* same or similar error was fixed very simply in Sphinx 1.4.2 according to https://github.com/sphinx-doc/sphinx/issues/2465

**Comment by humitos** [comment]
I'm not sure if it's a valid report error for RTD, maybe RTD could upgrade the default sphinx version to a newer one but I think it will need a lot of testing.

**Comment by humitos** [comment]
Closing because Sphinx was updated to 1.5.3 in https://github.com/rtfd/readthedocs.org/pull/2676
