### ISSUE TITLE
Upgrade pip to >=8.2 for extra name handling bug fix

### ISSUE THREAD

**Issue by snarfed** [rtfd/readthedocs.org#2538]
first off, thanks for the `extra_requirements` config feature, it's really useful!

i recently hit a problem with it that took a bit to debug. i had an extra named `appengine-sdk`, and readthedocs would try to install it, but fail with _oauth-dropins 1.6 does not provide the extra 'appengine-sdk'_. [example build.](https://readthedocs.org/projects/oauth-dropins/builds/4722454/)

turns out that pip up to 8.1.2 had a bug (pypa/pip#3810) that made it not support extras with capitals or non-alphanumerics like dashes in their names. when i renamed my extra `appenginesdk`, it worked. [example build.](https://readthedocs.org/projects/oauth-dropins/builds/4739176/)

looks like [your requirements.txt](https://github.com/rtfd/readthedocs.org/blob/master/requirements/pip.txt#L2) currently pegs pip at 8.1.1. mind upgrading that to 8.2 or later for this fix? thanks in advance!

## Details

* Project URL: https://oauth-dropins.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/oauth-dropins/builds/4722454/
* Read the Docs username (if applicable): snarfed

## Expected Result

install the appengine-sdk extra successfully.

## Actual Result

failed with _oauth-dropins 1.6 does not provide the extra 'appengine-sdk'_ due to pypa/pip#3810.

**Comment by snarfed** [comment]
thanks! ...except it looks like the pip bug was still in 8.1.2, and the fix didn't land until 8.2 or later.

**Comment by humitos** [comment]
pip was already updated and your build is passing now by installing the correct package version name `appengine-sdk-1.9.50.post0`. I'm closing this issue.

Please, feel free to reopen if you consider.
