### ISSUE TITLE
Build stalled in python3

### ISSUE THREAD

**Issue by jonDel** [rtfd/readthedocs.org#2542]
## Details

* Project URL: https://readthedocs.org/projects/serenata-toolbox/
* Build URL : https://readthedocs.org/projects/serenata-toolbox/builds/4739105/
* Read the Docs username: jonDel

## Expected Result
Documentation build complete.

## Actual Result
The build get stuck for some reason in the second command which I think has nothing to do with my particular build (seems like readthedocs related packages installation):
`` python /home/docs/checkouts/readthedocs.org/user_builds/serenata-toolbox/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/serenata-toolbox/.cache/pip sphinx==1.3.5 Pygments==2.1.3 setuptools==20.1.1 docutils==0.12 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext sphinx-rtd-theme==0.1.9 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.1.1 ``

It only occurs when it is configured to run my setup.py install, which is odd, since it never gets to the point of installing my dependencies.

It is even stranger that the command related seems to be completed successfully, and nevertheless it never went to the execution of the next command.
![screenshot from 2016-12-02 11-39-16](https://cloud.githubusercontent.com/assets/6098364/20837922/6004ae46-b88d-11e6-94f4-e8426813cce1.png)
![screenshot from 2016-12-02 11-39-09](https://cloud.githubusercontent.com/assets/6098364/20837921/6003c2b0-b88d-11e6-8937-8bbae11fa55e.png)

**Comment by ericholscher** [comment]
Looks like this has been resolved, as the recent builds have happened properly. Let me know if this is still an issue.
