### ISSUE TITLE
Password reset e-mail not showing up

### ISSUE THREAD

**Issue by klings** [rtfd/readthedocs.org#2544]
## Details

* Project URL: https://readthedocs.org/projects/nwebsec/
* Build URL (if applicable):
* Read the Docs username (if applicable): klings

## Expected Result

I've forgotten my password, so tried to reset it. Expected a reset e-mail (I have found an old one, so I know the e-mail is correct).

## Actual Result

No e-mail. I've tried several times the last two days.

**Comment by klings** [comment]
For the record, my registered e-mail is a gmail account. I doubt there's anything wrong on that end. Your reset procedure claims that a reset e-mail has been sent, but no e-mail arrives. I've checked Junk/spam etc. Is the "reset password" procedure working correctly? Searching through my inbox, I've received mail from you in the past, including a password reset back in the days. So this must be my registered account.

**Comment by ajdapretnar** [comment]
+1

I seems to have two accounts and when I tried to connect to the other (which is linked to my Github account), the mail never showed up...

**Comment by ajdapretnar** [comment]
p.s. It might even be possible ''some stole my e-mail". That is Readthedocs says the mail is already registered with a different account, but I don't remember signing up nor does my gmail have any registration mail from Readthedocs. So now I'm stuck. I can't connect to my Github or retrieve my forgotten password. 😢

**Comment by markcmiller86** [comment]
+1

I dunno if its related but I added github two-factor authentication since origin RTD login. My email is also a gmail account.

**Comment by dusktreader** [comment]
+1
username:dusktreader
email is a gmail account

**Comment by rfleschenberg** [comment]
Same problem. Not a gmail account here. No 2FA. I run my own mailserver for my registered e-mail address (rene@fleschenberg.net), so I have access to its logs. I was not able to find any delivery attempts from RTD in the logs so far.

**Comment by david4096** [comment]
+1

**Comment by dusktreader** [comment]
+1 again. Would really like to get docs for my new project up

**Comment by agjohnson** [comment]
I've deployed a potential fix for this. If you were having troubles before, please retry.

**Comment by dusktreader** [comment]
@agjohnson Thank you! That worked

**Comment by agjohnson** [comment]
Closing this, as I'm already noticing more mail going through. Feel free to reopen if this doesn't seem resolved.

**Comment by rmihael** [comment]
I'm having this trouble with account p.dmitriev@nimble.com. That is Gmail account with no 2FA. Other emails are coming smoothly.
