### ISSUE TITLE
Build + install fails 

### ISSUE THREAD

**Issue by pulse1989** [rtfd/readthedocs.org#2546]
## Details

* Project URL: none - the build doesnt get this far
* Build URL (if applicable): -
* Read the Docs username (if applicable): -

## Expected Result

*A description of what you wanted to happen*: the build succeeds and i can use the software

## Actual Result

build fails with the following:

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/libxml2 -I/tmp/pip-build-0SpYBG/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w
    x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1)
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 4

    ----------------------------------------
Command "/opt/rtd/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-0SpYBG/lxml/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-IK8pZl-record/install-record.txt --single-version-externally-managed --compile --install-headers /opt/rtd/include/site/python2.7/lxml" failed with error code 1 in /tmp/pip-build-0SpYBG/lxml/

not too sure where i am going wrong. I've followed instructions on here:

http://docs.readthedocs.io/en/latest/custom_installs/local_rtd_vm.html and made sure all dependencies were installed. 

currently running on ubuntu 16.04 LTS

Thanks

**Comment by ericholscher** [comment]
As noted, we don't support local installs, as we don't have enough time: http://docs.readthedocs.io/en/latest/open-source-philosophy.html#unsupported -- closing this as it won't get looked at.
