### ISSUE TITLE
old version of setuptools being used

### ISSUE THREAD

**Issue by steven-murray** [rtfd/readthedocs.org#2547]
## Details

* Project URL: hmf.readthedocs.org
* Build URL (if applicable): https://readthedocs.org/projects/hmf/builds/4775749/
* Read the Docs username (if applicable): steven_murray

## Expected Result

I need to use sphinx >= 1.5 (so I can use nbsphinx properly in my project). However, on using sphinx>=1.5 in my requirements file, it gives the error you can see at the URL. In short:

```
Exception occurred:
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
VersionConflict: (setuptools 3.3 (/usr/lib/python2.7/dist-packages), Requirement.parse('setuptools>=18.5'))
```

Note that I have already tried adding `setuptools>=19` to the requirements. I'm not sure why such an old version is being used? Or where it is being found? 

Any advice? Thanks!

**Comment by warsaw** [comment]
Note that RTD really needs to update to setuptools 31.0.1, which was just released.  This version has fixes for namespace packages, and without this new version packages such as my [flufl.i18n doesn't build](https://readthedocs.org/projects/flufli18n/builds/).

**Comment by Kwpolska** [comment]
The ancient setuptools version used by RTD also does not support environment markers, useful for things like `argparse ; python_version < '2.7'`.

**Comment by mrocklin** [comment]
This also affects me.  Is there any workaround available today?  Would installing within a conda environment help to bypass this?

**Comment by humitos** [comment]
can't you just add `setuptools==34.3.0` to your requirements file?

**Comment by Kwpolska** [comment]
`pip` will still be using the old `setuptools` and tooling for the rest of the install, so no.

**Comment by mrocklin** [comment]
Would many things break if we were to update the version of setuptools?  Can anyone on this issue speak to the short-term feasibility or challenges of doing this?

**Comment by ericholscher** [comment]
This should have been upgraded: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py#L107

**Comment by mrocklin** [comment]
Ah indeed, and roughly six days ago my builds started running again : https://readthedocs.org/projects/distributed/builds/

Thank you @kdeldycke
