### ISSUE TITLE
Update sphinx from 1.3.5 to 1.5

### ISSUE THREAD

**Issue by NikitaEgorov** [rtfd/readthedocs.org#2548]
## Details

* Project URL: local
* Build URL (if applicable): local
* Read the Docs username (if applicable): local

## Expected Result
Need new Sphinx 1.5 version

**Comment by jakirkham** [comment]
This would be really great. Are there any obstacles to doing this?

**Comment by agjohnson** [comment]
This change needs to be QAed with `Sphinx==1.5.2` with a pass over a number of projects to test for any newly introduced changes.

**Comment by thijstriemstra** [comment]
Can we help? We have about 4/5 projects that run fine with Sphinx 1.5.2 on rtd (after having to manually install it).

**Comment by agjohnson** [comment]
@thijstriemstra Did you run in to any issues with the upgrade? I'm mostly concerned about support for our theme and other pieces where our sphinx extension might need to be upgraded.

If anyone wants to contribute here, forking some popular projects and testing a force of `1.5.2`, or even just accumulating information on projects running `>1.5` now would help.

**Comment by ericholscher** [comment]
This was deployed a couple days ago.

**Comment by thijstriemstra** [comment]
@ericholscher what version exactly?

**Comment by ericholscher** [comment]
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py#L105
