### ISSUE TITLE
autodoc always showing special members

### ISSUE THREAD

**Issue by nbastin** [rtfd/readthedocs.org#2550]
## Details

* Project URL: http://geni-lib.readthedocs.io/en/latest/index.html
* Build URL (if applicable):
* Read the Docs username (if applicable): barnstorm

## Expected Result

No special members in doc output

## Actual Result

The last few builds, regardless of settings (have tried setting autodoc defaults to no-special-members in conf.py, also setting it on individual pages), if you have undoc-members set, special python methods will also always be included, cluttering up the docs with entries for things like `__getitem__` and `__delattr__`, etc.

You can see an example at:

http://geni-lib.readthedocs.io/en/latest/api/geniaggregate/vts.html

**Comment by nbastin** [comment]
Actually I think the problem might be more directly related to setting inherited-members, since apparently `object` and `Exception` have documented special members in the python doc, and it follows the inheritance tree all the way down.  Still, we don't have special-members set, so I don't know why these show up at all (documented or not).

**Comment by ericholscher** [comment]
This sounds like an issue with Sphinx, not Read the Docs specifically. The actual functionality of the builds is based on how Sphinx works, and likely this is a bug that should be filed on their tracker.

**Comment by fterbo** [comment]
This is an issue with the specific setup of sphinx at RTD, it seems, as I do not have this problem making sphinx builds locally.
