### ISSUE TITLE
None of RTD is loading.. at all.

### ISSUE THREAD

**Issue by josefdlange** [rtfd/readthedocs.org#2554]
**I know this is going to be a shitty issue report but I don't have a lot to go on here**

## Details
Any RTD subdomain, root domain, etc.

## Expected Result

Docs load

## Actual Result

Docs do not load...

## cURL output
```
$ curl -vvv https://readthedocs.org
* Rebuilt URL to: https://readthedocs.org/
*   Trying 162.209.114.75...
* TCP_NODELAY set
* Connected to readthedocs.org (162.209.114.75) port 443 (#0)
* Unknown SSL protocol error in connection to readthedocs.org:-9805
* Curl_http_done: called premature == 1
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to readthedocs.org:-9805
```

I don't think it's just me experiencing this -- literally all of the rest of the Internet is loading fine for me. Let me know if there's anything else I can do to help here.

**Comment by josefdlange** [comment]
Aaaaand as soon as I put together the nice report it all comes back. I'll leave it to you guys to close the issue, as I think there should probably be record and details regarding an outage...

**Comment by agjohnson** [comment]
Thanks! I can only assume a network blip. Things all look normal in that time frame.
