### ISSUE TITLE
enumerate render error: second line for item sticks to next item; leaves some space

### ISSUE THREAD

**Issue by SimJoSt** [rtfd/readthedocs.org#2557]
I noticed on the current changelogs of Gluon (https://gluon.readthedocs.io/en/v2016.2.2/releases/v2016.2.2.html#bugfixes), that the list/enumerate is not rendered correctly.
Some of the list items have a second line without being the next item. Instead of being rendered directly underneath the item they belong to, with a little space they seem to stick to the top of the next item.

**Comment by ericholscher** [comment]
Thanks for reporting this. This is a theme issue, not an issue with Read the Docs. You can open issues with the theme here: https://github.com/snide/sphinx_rtd_theme/

**Comment by SimJoSt** [comment]
Thank you!
I did that here: https://github.com/rtfd/sphinx_rtd_theme/issues/408
