### ISSUE TITLE
all vesions except 'latest' disappeared

### ISSUE THREAD

**Issue by kmike** [rtfd/readthedocs.org#2562]
## Details

* Project URL: http://scrapy.readthedocs.io/ (we're using custom domain: https://doc.scrapy.org/)

## Expected Result

There used to be documentation version selector. 

## Actual Result

Now the version selector is gone (the UI element is still present, but there are no versions available). Also, docs other than 'latest' are not available at all, links to these docs are broken. 

Versions still have checkboxes checked near them in readthedocs project options; I don't think we changed anything recently.

**Comment by ericholscher** [comment]
Scape is set to a `single_version` project, which removes the other versions that are associated with it.

**Comment by kmike** [comment]
Thanks for the quick answer! It fixed it. Maybe someone checked this checkbox occasionally. Sorry for noise!
