### ISSUE TITLE
wipe does not wipe

### ISSUE THREAD

**Issue by schollii** [rtfd/readthedocs.org#2565]
## Details

* Project URL: https://readthedocs.org/projects/pypubsub/
* Build URL (if applicable): https://readthedocs.org/projects/pypubsub/builds/4836271/
* Read the Docs username (if applicable): schoenborno

## Expected Result

1. After I click on Wipe for stable version, clicking on Stable link should produce a 404 or empty or such.
2. After I click on Build for Stable version, and it passes, clicking on Stable link should show docs for latest release. The build hash is correct (points to the correct commit in github). 

## Actual Result

1. The docs that I wiped are still there. 
2. Clicking on Stable shows old docs.

**Comment by humitos** [comment]
@schollii as documentation says at http://docs.readthedocs.io/en/latest/builds.html#deleting-a-stale-or-broken-build-environment, the _Wipe_ button don't delete your documentation but your build environment configurations.

**Comment by schollii** [comment]
Thanks @humitos for the info that addresses item 1 of this issue. 
If you have any status on item 2, please let me know.

**Comment by humitos** [comment]
I'm closing this issue because item 1 was clarified and item 2 is duplicated by #2563
