### ISSUE TITLE
Elasticsearch [Can't specify parent if no parent field has been configured]

### ISSUE THREAD

**Issue by qhoekman** [rtfd/readthedocs.org#2571]
## Details

* Project URL:  local
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

I was expecting some search rules when the query has runned against a Elasticsearch 1.3.7 instance.
But it seems that he project isn't indexed, because there isn't a _parent field definition. 

## Actual Result

When the query has runned against the Elasticsearch instance it returns the following:

readthedocs_1    | [05/Jan/2017 04:52:08] ERROR [celery.worker.job:282] Task readthedocs.projects.tasks.update_search[3b3ae9a6-63c2-400b-b609-680da4791ef6] raised unexpected: RequestError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]", {u'status': 400, u'error': u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]"})
readthedocs_1    | Traceback (most recent call last):
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
readthedocs_1    |     R = retval = fun(*args, **kwargs)
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
readthedocs_1    |     return self.run(*args, **kwargs)
readthedocs_1    |   File "/app/readthedocs/projects/tasks.py", line 561, in update_search
readthedocs_1    |     delete=delete_non_commit_files,
readthedocs_1    |   File "/app/readthedocs/restapi/utils.py", line 144, in index_search_request
readthedocs_1    |     page_obj.bulk_index(index_list, parent=project.slug)
readthedocs_1    |   File "/app/readthedocs/search/indexes.py", line 140, in bulk_index
readthedocs_1    |     bulk_index(self.es, docs, chunk_size=chunk_size)
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 182, in bulk
readthedocs_1    |     for ok, item in streaming_bulk(client, actions, **kwargs):
readthedocs_1    |   File "/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 124, in streaming_bulk
readthedocs_1    |     raise e
readthedocs_1    | RequestError: TransportError(400, u"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")

This is when I'm using my own project, but when I'm using the Pip project for experimentation it runs flawlessly. Only the project is still nog indexed, I hope that I'm doing something wrong, because it was working in the past. I also tried different versions beside 1.3.7 for Elasticsearch, but the same result for <2.11.

My setup is based on the floross/docker-readthedocs docker setup for reproduce purposes.

**Comment by qhoekman** [comment]
I just fixed the issue by doing the following.or see https://webcache.googleusercontent.com/search?q=cache:EOq3LW42s7UJ:haiku.readthedocs.org/en/latest/rtfd.html

from readthedocs.settings.dev import *
from readthedocs.search.indexes import Index, PageIndex, ProjectIndex, SectionIndex

import os
environ = os.environ

ES_HOSTS = ['localhost:9200']
REDIS = {
    'host': 'localhost',
    'port': 6379,
    'db': 0,
}
BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
DEBUG = True
CELERY_ALWAYS_EAGER = False

# Create the index.
index = Index()
index_name = index.timestamped_index()
index.create_index(index_name)
index.update_aliases(index_name)
# Update mapping
proj = ProjectIndex()
proj.put_mapping()
page = PageIndex()
page.put_mapping()
sec = SectionIndex()
sec.put_mapping()

Execute the script as:
/opt/rtd/checkouts/readthedocs.org$ DJANGO_SETTINGS_MODULE=readthedocs.settings.dev python search.py

**Comment by tweep** [comment]
I ran into similar issues, below is what what helped me: 

First issue: `Custom Analyzer [default_icu] failed to find tokenizer under name [icu_tokenizer]`

1) stopped elasticsearch 

` sudo systemctl stop   elasticsearch.service`

2) Removed + reinstalled ICU plugin 
( I tried version 2.4.1 but that's incompatible) 

`sudo  /usr/share/elasticsearch/bin/plugin  -remove  elasticsearch/elasticsearch-analysis-icu/2.3.0
`sudo  /usr/share/elasticsearch/bin/plugin  -install   elasticsearch/elasticsearch-analysis-icu/2.3.0

` sudo systemctl start   elasticsearch.service`

3) check if it works in the logs 

`tail -f  /var/log/elasticsearch/elasticsearch.log`


Second issue : `"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]")`
This is reported in the RTD logs ... I guess I have done something wrong during the very first indexing, so i remove the index and recreate it ...

1) remove the old indexes + alias 

` curl -X DELETE "localhost:9200/readthedocs"`
` curl -X DELETE "localhost:9200/readthedocs-20181030105541"`

2) re-provision indexes + mappings 

`python3 manage.py provision_elasticsearch`
`python3 manage.py reindex_elasticsearch`

Now everything works :-)
