### ISSUE TITLE
Github connected to another account

### ISSUE THREAD

**Issue by xrisk** [rtfd/readthedocs.org#2576]
When trying to connect my account to Github, I get "The social account is already connected to a different account.". To the best of my knowledge, I do _not_ have any other read the docs account. I also went to Github's settings and removed the read the docs authorized application from there, but that did not fix anything.

My read the docs username is xrisk

**Comment by ericholscher** [comment]
This was a bug that we had for a long time, but has been fixed for a number of months. If you login with GitHub (https://readthedocs.org/accounts/github/login/?process=login) it will bring you to your account connected with that GitHub account, which you can then unlink (https://readthedocs.org/accounts/social/connections/) to fix this.

**Comment by cmungall** [comment]
For anyone else arriving at this issue:

I had the same problem, but the "Disconnect" button didn't work on my already connected account. I tried again after resetting my password, after this it worked. Not sure if this correlation not causation and it was a momentary glitch. HTH.
