### ISSUE TITLE
Dead project: predicsis-sdk

### ISSUE THREAD

**Issue by jeanbaptistepriez** [rtfd/readthedocs.org#2579]
## Details

Hello and happy new year,

When we are looking for "predicsis" using readthedocs.org, the engine returns a dead project

* Project URL: https://readthedocs.org/projects/predicsis-sdk/
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

This project is dead so it should not be there.

## Actual Result

Using the search engine: 
![capture d ecran 2017-01-06 a 10 55 05](https://cloud.githubusercontent.com/assets/17195729/21714319/a2e5fddc-d3fe-11e6-9cdf-3bb852092948.png)

And when we click on the first link
![capture d ecran 2017-01-06 a 10 55 15](https://cloud.githubusercontent.com/assets/17195729/21714320/a5fb68f4-d3fe-11e6-8575-ecc4fc916891.png)

(This page should not exist anymore)

**Comment by ericholscher** [comment]
Guessing this is a bug in our search index got removing deleted projects. Thanks for the report.

**Comment by ericholscher** [comment]
This should now be fixed.
