### ISSUE TITLE
Properly implement headers/subheaders in TOC for PDF

### ISSUE THREAD

**Issue by rogersachan** [rtfd/readthedocs.org#2580]
## Details

* Project URL: https://docs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/docs/
* Read the Docs username (if applicable): 

## Expected Result

Subheaders rendered in TOC

## Actual Result

Did not render

## Images of Proof

![ddd](https://cloud.githubusercontent.com/assets/7173984/21736936/6e9a1c36-d442-11e6-9962-f63e416555ac.PNG)

![dddd](https://cloud.githubusercontent.com/assets/7173984/21736946/8484b7d6-d442-11e6-8668-dd0d30d0a040.PNG)

**Comment by humitos** [comment]
@rogersachan not sure to understand what you said, would you like to have the `User Documentation`, `About Read the Docs`, `Feature Documentation`, `Developer Documentation`, etc in the PDF? Is that what you mean?

**Comment by rogersachan** [comment]
@humitos That is what I mean.

**Comment by ericholscher** [comment]
This is an issue with Sphinx, not with Read the Docs. You'd need to open a bug with the sphinx project here: https://github.com/sphinx-doc/sphinx
