### ISSUE TITLE
Show syntax error with Python 3.6

### ISSUE THREAD

**Issue by Infernion** [rtfd/readthedocs.org#2581]
## Details
I'm using Python 3.6 f-string and variable annotations. 

* Project URL: https://annots.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/annots/builds/4872722/
* Read the Docs username (if applicable): infernion

## Expected Result

*Docs should be build*

## Actual Result

*Syntax error*

**Comment by pcattori** [comment]
Same thing happening to me:

- Project URL: https://maps.readthedocs.io
- Build URL: https://readthedocs.org/projects/maps/builds/4933774/
- Read the Docs username: pcattori

**Comment by dirn** [comment]
As mentioned in #1990, RTD currently only supports Python 3.4 for CPython 3.x projects. Any syntax (e.g., `async`/`await`, f-strings) or modules (e.g., `typing`) introduced since then will cause autodoc to fail.

**Comment by ericholscher** [comment]
We have a beta builder that has 3.6, which you can sign up for here: https://docs.google.com/forms/d/e/1FAIpQLSfFufPgFiPFNjGTr0c8ErNY92h_S4QmF1EVrsMOGD4VofWDdg/viewform?c=0&w=1

**Comment by achimnol** [comment]
I have sent the beta application via the above form twice during last a few days, but haven't gotten any reply yet.
Is the beta participation program still active?

**Comment by chrizzFTD** [comment]
I've submitted the beta application twice since early April this year but didn't get an answer; was hoping the feature would start running in production because of that, but it has not. I've moved to github pages in the meantime.

I got one project running on that beta (application submitted in February) and it runs great!

**Comment by chrizzFTD** [comment]
@achimnol have you tried the alternative mentioned in [issue 2584](https://github.com/rtfd/readthedocs.org/issues/2584) using conda? I've tried it and it works properly; setup is a bit more verbose but completely worth it! On that issue they reference the [poliastro project](https://github.com/poliastro/poliastro/blob/master/.travis.yml) as an example.

**Comment by numberoverzero** [comment]
@ericholscher I've submitted that form a few times for the bloop project but my builds are still failing: https://readthedocs.org/projects/bloop/builds/5995227/

Anything else I can do to opt into the program?  I really don't want to resort to conda for this.

**Comment by mathiasbrito** [comment]
Any news on this issue? Also requested access to the Beta and did not get it. My project is all python 3.6 and I get syntax errors with type annotation.

**Comment by ericholscher** [comment]
We have a PR open that will let users configure this themselves: https://github.com/rtfd/readthedocs.org/pull/3339 -- it has one outstanding issue, and then should be merged in the next week or so.

**Comment by liiight** [comment]
so if i want to use use python 3.6 ill have to dockerize my project? I'm sorry if I misunderstood how that PR solves the 3.6 issue...

**Comment by dirn** [comment]
RTD runs the builders in Docker containers. The PR provides more control over which image is used.

**Comment by liiight** [comment]
I see. Thanks for the explanation, looking forward for the implemented solution

**Comment by goranvrbaski** [comment]
When can we expect this solution to be implemented?

**Comment by ericholscher** [comment]
http://docs.readthedocs.io/en/latest/yaml-config.html#build-image

**Comment by ericholscher** [comment]
It's a new feature, so please let us know if it isn't working for some case.

**Comment by gasparka** [comment]
I ran into https://github.com/pypa/pip/issues/4216 while installing 'sphinxcontrib.fulltoc' as extra requirement... updating the pip should fix this.

Otherwise it works, thanks :)

**Comment by liiight** [comment]
Well, the build runs now and it doesn't fail but for some reason I don't see autodoc stuff (even though it looks fine locally when i `make html` via sphinx).
I'm not sure if it's a config issue on my part (probably) or a real issue.

docs: http://notifiers.readthedocs.io/en/latest/API.html 
source: https://github.com/liiight/notifiers/blob/develop/source/API.rst

I'd appreciate the help and I apoligize in advance if I'm hijacking the issue. This is my first RTD project...

**Comment by gasparka** [comment]
@liiight i use ``pip_install: true`` and autodoc works.

**Comment by liiight** [comment]
Thanks @gasparka! That did the trick! python 3.6 works great here too 😄

**Comment by RichardLitt** [comment]
That's two confirmations. I am going to call this as closed. If anyone has an issue, let's reopen. Thanks everyone!
