### ISSUE TITLE
Document that RTD uses `rel` branch for production

### ISSUE THREAD

**Issue by zabeloliver** [rtfd/readthedocs.org#2583]
Hi, i'd like to add a new builder for doxygen documentation (but native, not with breath). Since there are a lot of branches like real/relcorp which a far ahead of master, i'd like to know, which branch to choose for development.

Thanks in advance!
Oli

**Comment by ericholscher** [comment]
Thanks for your interest. We likely wouldn't include a doxygen builder in code, but we'd be happy to make it easy to implement as a third party builder, with a good API in RTD. We'd also be happy to list the extension in our docs! :)

The main site is deployed from `rel`, which shouldn't be ahead of `master`.

**Comment by alyjak** [comment]
Note that there are a few sphinx extensions for integrating doxygen content, notably https://github.com/michaeljones/breathe, you might want to check that out before starting from scratch.

**Comment by humitos** [comment]
Should I close this issue? The original question was answered (regarding to the branch) :grin: 

Do you want to continue the discussion about how to it here? If so, we should change the title of the issue since it will be confusing.

**Comment by ericholscher** [comment]
We should probably document how we do deployments and that the `rel` branch is in production.
