### ISSUE TITLE
{% if meta is defined and 'github_url' in meta %}

### ISSUE THREAD

**Issue by tliron** [rtfd/readthedocs.org#2590]
## Details

* Project URL: http://ronin.readthedocs.io/en/latest/ronin.html
* Build URL (if applicable): https://readthedocs.org/projects/ronin/builds/4900779/
* Read the Docs username (if applicable): tliron

## Expected Result

I wanted the documentation to build!

## Actual Result

I keep getting this exception:
```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ronin/envs/latest/local/lib/python2.7/site-packages/sphinx_rtd_theme/breadcrumbs.html", line 9, in top-level template code
    {% if meta is defined and 'github_url' in meta %}
TypeError: argument of type 'NoneType' is not iterable
```
I tried many different things to fix this, including manually adding `.. meta:: :github_url: ...` to all my pages and disabling my Sphinx theme entirely.

Searching for this error, I found a few other projects on ReadTheDocs that had this error at some point and then ... solved it. But even looking through their commits I can't find out any change that seems relevant to this issue.

**Comment by humitos** [comment]
@tliron it seems to be a bug in `sphinx_rtd_theme` that was solved at https://github.com/snide/sphinx_rtd_theme/pull/302

Can you try that latest code? (check this issue https://github.com/snide/sphinx_rtd_theme/issues/361)

**Comment by tliron** [comment]
Passed for the first time. :)
