### ISSUE TITLE
Support query args in redirects

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2595]
A redirect should be able to pass on query args. Currently, a redirect hit with query args 404s.

**Comment by sxn** [comment]
Hi! Mind if I give it a shot? :)

**Comment by humitos** [comment]
@agjohnson can you provide an example when you are receiving 404?

I just checked this URL: http://tox.readthedocs.io/?say=hello&di=hola and I was redirected to http://tox.readthedocs.io/en/latest/

On the other hand, in my example, would you like to be redirected to http://tox.readthedocs.io/en/latest/?say=hello&di=hola ?

**Comment by humitos** [comment]
Closing because it's done in the private repository. Thanks!
