### ISSUE TITLE
Search results are dropping the .html extension 

### ISSUE THREAD

**Issue by julie-sullivan** [rtfd/readthedocs.org#2596]
## Details

* Project URL: http://intermine.readthedocs.io/

## Expected Result

1. Do a keyword search, e.g. using the string "portal".
2. Get four results back
3. All four links in search results work correctly, including the one titled "linking in to your mine":

http://intermine.readthedocs.io/en/latest/webapp/linking-in/index.html?highlight=portal

## Actual Result

1. Do a keyword search, e.g. using the string "portal".
2. Get four results back
3. Three links in the search results work correctly, except for the one titled "linking in to your mine":

http://intermine.readthedocs.io/en/latest/webapp/linking-in/index?highlight=portal

* If you append `.html`, that URL works
* If you build the docs locally, all URLs are always correct. The `.html` is not dropped.

**Comment by humitos** [comment]
Related to #2914

**Comment by stsewd** [comment]
Everything works correctly on https://readthedocs.org/projects/intermine/search/?q=portal

The resulted URL is http://intermine.readthedocs.io/en/latest/webapp/linking-in/?highlight=portal
(without the `index` part).

Searching on the site http://intermine.readthedocs.io/en/latest/search/?q=portal&check_keywords=yes&area=default

The resulted URL is wrong http://intermine.readthedocs.io/en/latest/webapp/linking-in/index?highlight=portal

Maybe something wrong with the js of the theme you use?

**Comment by stsewd** [comment]
I can't replicate this on my local instance, I don't have elastic search set up, but the search works on your project, so, I think there is an overlapping with elastic search.

**Comment by humitos** [comment]
I was able to replicate this issue just by going to

https://intermine.readthedocs.io/en/latest/search/?q=portal&check_keywords=yes&area=default

and the first link displayed is this one: https://intermine.readthedocs.io/en/latest/webapp/linking-in/index?highlight=portal and should be this one https://intermine.readthedocs.io/en/latest/webapp/linking-in/index.html?highlight=portal (note the `.html` on it)

This is a bug that will probably be fixed when all the work already done around search has been deployed.

**Comment by humitos** [comment]
We can revisit it one some time after deploying new changes for ES. Hopefully, `stale` bot will remind us :)

**Comment by stsewd** [comment]
This issue looks like https://github.com/rtfd/readthedocs.org/issues/5254, I'm not able to replicate it anymore. I guess we don't use the resolver anymore in the new search.

**Comment by humitos** [comment]
I'm closing this one since we can't replicate it anymore. Feel free to reopen if you still have this issue.

**Comment by julie-sullivan** [comment]
thank you!! Yes, it seems to be working now. :)
