### ISSUE TITLE
Build failed because of old buggy versions of setuptools and virtualenv

### ISSUE THREAD

**Issue by paugier** [rtfd/readthedocs.org#2597]
## Details

* Project URL: http://fluidimage.readthedocs.io
* Build URL: https://readthedocs.org/projects/fluidimage/builds/4912706/
* Read the Docs username: paugier

## Expected Result

Build the doc (with `virtualenv --system-site-packages`) .

## Actual Result

Build failed with error:

```
pkg_resources.VersionConflict: (setuptools 3.3 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=18.5'))
```

See also https://github.com/rtfd/readthedocs.org/issues/2547

I've already encountered such problems locally with `virtualenv --system-site-packages`. setuptools 18.5 is installed in the virtualenv but `import setuptools` loads the old system setuptools package /usr/lib/python3/dist-packages because of a path problem (bug virtualenv). The problem is solved after updating `virtualenv`, `setuptools` and `pip`:

```bash
sudo pip3 install pip -U
sudo pip3 install setuptools -U
sudo pip3 install virtualenv -U
```

**Comment by paugier** [comment]
The build for another documentation also failed with the same error:

## Details

* Project URL: http://fluidlab.readthedocs.io
* Build URL: https://readthedocs.org/projects/fluidlab/builds/4940488/
* Read the Docs username: paugier

I see:
```
Successfully installed Jinja2-2.9.4 Markdown-2.6.7 MarkupSafe-0.23 PyYAML-3.12 Pygments-2.1.3 alabaster-0.7.9 babel-2.3.4 backports-abc-0.5 click-6.7 commonmark-0.5.4 docutils-0.12 livereload-2.5.1 mkdocs-0.15.0 mkdocs-bootstrap-0.1.1 mkdocs-bootswatch-0.4.0 mock-1.0.1 nilsimsa-0.3.8 pillow-2.6.1 pytz-2016.10 readthedocs-sphinx-ext-0.5.4 recommonmark-0.1.1 requests-2.13.0 setuptools-21.2.1 six-1.10.0 snowballstemmer-1.2.1 sphinx-1.3.5 sphinx-rtd-theme-0.1.9 tornado-4.4.2
```

but finally get the error:
```
Exception occurred:
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 632, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (setuptools 3.3 (/usr/lib/python3/dist-packages), Requirement.parse('setuptools>=18.5'))
```

**Comment by ericholscher** [comment]
We've now upgraded our version of setuptools. I believe this should be fixed.
