### ISSUE TITLE
No privacy policy

### ISSUE THREAD

**Issue by DXGLdotinfo** [rtfd/readthedocs.org#2602]
## Details

* Project URL: https://readthedocs.org
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): N/A

## Expected Result

There should be a "footer" link to a privacy policy, as the site uses Google Analytics which requires one

## Actual Result

There is no privacy policy - a policy is required per the terms at https://www.google.com/analytics/terms/us.html
This issue affects hosted docs too.

**Comment by ericholscher** [comment]
Good call. We've had this on our list for a long while, and should get it set up.

**Comment by JohannesKreuzer** [comment]
Hi,
what is the state on this issue?
When will the privacy policy available?

**Comment by davidfischer** [comment]
I'm going to commit on getting a privacy policy in place by May 25, 2018. Read the Docs has contacted our lawyers about this and we are currently waiting to hear back but if they continue to lag I'll get one in place and then we can iterate on it.
