### ISSUE TITLE
[Feature request] Importing projects: filter by "not in an organization"

### ISSUE THREAD

**Issue by amueller** [rtfd/readthedocs.org#2605]
I'd like to be able to add a project that is not in an organization.
I'm in the conda-forge organization, which has a repository for every python package. As far as I can tell, I need to manually page past all of them to reach my repositories.

Thanks

**Comment by WoLpH** [comment]
Yes... 2nd that. I have over 300 repositories linked to my account and this is _very_ annoying right now.
Although I suppose a (quick-)search would be a better solution regardless, this feature is essential to this filter.

**Comment by agjohnson** [comment]
We already have some issues open to address this, so i'll close this here.

Ref #1899
