### ISSUE TITLE
Filter by User

### ISSUE THREAD

**Issue by jakirkham** [rtfd/readthedocs.org#2606]
When adding a new project, there is a nice set of filters for organizations. It's pretty handy to be able to cut 100s or 1000s of repos to 10s easily this way. One thing that would make things a little nicer still would be adding a user filter too. That way, I can quickly add my own repos without having to sift through all repos or importing them manually.

**Comment by agjohnson** [comment]
We have some plans to update this page, so I'll close this here.

Ref #1899

**Comment by jakirkham** [comment]
Thanks. Sorry to duplicate.
