### ISSUE TITLE
Duplicates in "import project"

### ISSUE THREAD

**Issue by WoLpH** [rtfd/readthedocs.org#2612]
The screenshot says it all I suppose. It looks like it's related to case sensitivity because most (all?) of my repositories are duplicated.

![image](https://cloud.githubusercontent.com/assets/270571/22314933/12de1772-e364-11e6-8823-b271deeb7b4e.png)

**Comment by agjohnson** [comment]
Not sure if this is something we'll code against -- these are all separate repositories as far as GitHub tells us. If anyone has a good idea of how to fix this, feel free to reopen this issue. I'll close this for now.

We do have plans to update this page with a fuzzy search mechanism, but that doesn't necessarily fix this issue -- it does however hopefully make sorting through a list of doubled repositories quicker.

**Comment by WoLpH** [comment]
Why not? It's as simple as a case sensitive unique constraint isn't it? As far as I am aware Github doesn't allow mulitiple users with multiple case variations (or at the very least, they shouldn't).
