### ISSUE TITLE
Build celery task timeout doesn't report an error

### ISSUE THREAD

**Issue by cdeil** [rtfd/readthedocs.org#2614]
## Details

* Project URL: https://github.com/gammapy/gammapy
* Build URL: https://readthedocs.org/projects/gammapy/builds/4945075/

## Expected Result

I expected build status of "succeeded".
(see below why)

## Actual Result

The build status is "failed", and there's a red message at the top:
> Error
> An unexpected error occurred

However, the HTML version of the docs from that build was published at
http://docs.gammapy.org/en/latest/

I did search the logs for mentions of "error" by expanding every build command log at  https://readthedocs.org/projects/gammapy/builds/4945075/ and didn't find any error.

**Comment by agjohnson** [comment]
My guess is this failed with the task being killed due to timeout. We try to force the docker container to timeout first and surface an error, but this seems to not catch the task failure.

**Comment by cdeil** [comment]
@agjohnson - Thanks for looking at this!

So for this same project, this issue keeps re-occurring, it wasn't a one-time fluke.
Here's another build that fails even though all commands are shown to have return code 0:
https://readthedocs.org/projects/gammapy/builds/4950936/

**Comment by agjohnson** [comment]
This isn't related to the build command exit code, but rather the actual celery task that encapsulates all the build commands is being killed because of a timeout at the celery level. This should instead throw an exception, and was previously, but it seems something has regressed.

**Comment by skirpichev** [comment]
> the actual celery task that encapsulates all the build commands is being killed because of a timeout at the celery level.

Was something changed recently on your side, i.e. these timeouts were different before?

**Comment by cdeil** [comment]
> Was something changed recently on your side, i.e. these timeouts were different before?

This was a question to @agjohnson , not me, right?

---

So just now I got this for a different project:
http://readthedocs.org/projects/astropy-regions/builds/5035649/
after this commit:
https://github.com/astropy/regions/commit/5addcb9a6aab57279d15f006078e9ebdfe0bbd3f

It's really frustrating to just get an error without any indication if there's something I can do to fix it.
I'll try to wipe that project now and start a fresh build, see if that helps.

**Comment by skirpichev** [comment]
> This was a question to @agjohnson , not me, right?

Sure.

> So just now I got this for a different project:

BTW, [same error](http://readthedocs.org/projects/diofant/builds/5034192/) now appear in my project, randomly.

**Comment by cdeil** [comment]
Still the same error after wiping:
https://readthedocs.org/projects/astropy-regions/builds/5035681/

Maybe it's a new general issue with conda builds on RTD?
I'll give up for today and try again tomorrow.

**Comment by skirpichev** [comment]
> Maybe it's a new general issue with conda builds on RTD?

My project doesn't use conda.

**Comment by agjohnson** [comment]
These errors were due to a build server going readonly on it's filesystem. The server is back to normal now.

@skirpichev I'm not sure what would have changed. This likely requires us to explicitly catch a timeout event from celery, if that's possible. Currently we're just padding the timeout with an additional percentage to account for vcs checkout

**Comment by ericholscher** [comment]
This bug should now be fixed and deployed, in that we're properly timing out builds at 15 minutes with docker. We've also recently fixed bugs with conda. If there is a specific conda bug, we should track that in a new issue.
