### ISSUE TITLE
Replace extension pattern with updated version

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2618]
We have two extension patterns utilized currently. These extension points are required so that we can add additional functionality or altered querysets on readthedocs.com.

The modern version is in `readthedocs.core.utils.extend`, and an example of this extension is `readthedocs.core.symlink.PublicSymlink`. There are a number of classes using arbitrary settings to allow for override in `readthedocs.privacy.backend`. Unifying these two implementations would clean things up and consolidate our settings.

Ref #2611

**Comment by ChamanAgrawal** [comment]
Can you please elaborate the issue

**Comment by rixx** [comment]
`readthedocs.privacy.backend` already uses `SettingsOverrideObject` with `VersionManager`/`VersionQuerySet` - what else do you see as requiring changes?

**Comment by agjohnson** [comment]
The old pattern is used in these spots:

* https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/privacy/loader.py
* https://github.com/rtfd/readthedocs.org/blob/c84cd7362a5c43eb95c2316fef9b6df4c592b3b4/readthedocs/oauth/services/__init__.py
* https://github.com/rtfd/readthedocs.org/blob/c84cd7362a5c43eb95c2316fef9b6df4c592b3b4/readthedocs/projects/backends/views.py
