### ISSUE TITLE
PDF creation build failure for Gujarati language

### ISSUE THREAD

**Issue by cyberorg** [rtfd/readthedocs.org#2620]
## Details
Building pdf fails with many of these kind of errors:
! Package inputenc Error: Unicode char \u8:ત not set up for use with LaTeX.

Building epub and html completes successfully.

* Project URL: https://readthedocs.org/projects/mss-doc-gu
* Build URL (if applicable): https://readthedocs.org/projects/mss-doc-gu/builds/4954188/
* Read the Docs username (if applicable): cyberorg

## Expected Result
PDF build should complete successfully 

## Actual Result
PDF build failure

**Comment by humitos** [comment]
@cyberorg where you able to build the PDF in your own computer? I just downloaded the code and was able to build the HTML but I had a different problem with the PDF:

```
******** ERROR !! PLEASE UPDATE titlesec.sty !!********
******** THIS VERSION SWALLOWS SECTION NUMBERS.********.
```

**Comment by cyberorg** [comment]
Yes, using this in conf.py

latex_elements = {
    'preamble': '''

\usepackage{fontspec}
\setsansfont{FreeSans}
\setromanfont{FreeSerif}
\setmonofont{FreeMono}
''',
}
and then running the following:

make -e SPHINXOPTS="-D language='gu'" latex
cd build/latex/
xelatex *.tex

This creates the pdf.

**Comment by humitos** [comment]
I see. That seems to be a very custom way to generate your PDF file which is not setup in RTD. You could try to do some _magic_ in your `conf.py` that RTD will execute by you and try different options.

**Comment by cyberorg** [comment]
Using xelatex instead of pdflatex seems to be the only way to generate pdfs of "non-english" language, I am sure this affects every Indian languages(there are 15 official ones) and all other languages using unicode characters.

Is there way to add that magic of using xelatex in place of pdflatex to conf.py?
