### ISSUE TITLE
Can't delete translation when there are 2 translations for the same language

### ISSUE THREAD

**Issue by atodorov** [rtfd/readthedocs.org#2621]
## Details

Hi guys,
when I reach the following URL I get an error:

https://readthedocs.org/dashboard/mutation-testing-patterns/translations/delete/mutation/

Under my project I made the mistake to add 2 project which translate the
original content into Chinese. Now I can't delete one of them.

* Project URL: http://mutation-testing-patterns.readthedocs.io/en/latest/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable):  atodorov

## Expected Result

translation is deleted

## Actual Result

internal server error as it seems

**Comment by agjohnson** [comment]
This is likely due to a recent change to translations deletion.

**Comment by ChamanAgrawal** [comment]
Hey can you tell me where the translation deletion code is?

**Comment by ericholscher** [comment]
@ChamanAgrawal https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/views/private.py#L564-L592

**Comment by rixx** [comment]
@ChamanAgrawal Does that mean you're working on the issue?

**Comment by stsewd** [comment]
Hi, I just test this case on my local instance and I was able to delete successfully the translation. Are you still having this issue?

**Comment by atodorov** [comment]
I am still having this issue with the link in the first comment.

**Comment by stsewd** [comment]
@atodorov can you attach a screenshot of your translations panel? Just in case I didn't understand the issue, thanks!

**Comment by atodorov** [comment]
![rtd](https://user-images.githubusercontent.com/1002300/36024720-45f3b472-0d99-11e8-9404-1caaa6f94b5c.png)

**Comment by stsewd** [comment]
@atodorov sorry for the late replay, I was able to reproduce this issue, but haven't found a way of delete the translation, this is because a circular dependency (Project A is added as translation of project B, and project B is added as translation of project A). The current solution (_almost solution_) is to delete one project, or someone with access to the server database to remove the relationship.

**Comment by atodorov** [comment]
@stsewd thanks for the update. The translation I was trying to delete, the one that fails, is a project made by somebody else and configured as translation to my own project. Thus I don't have control over it and I can't get in touch with the original author to ask them to delete the relation. In this case I'm not going to pursue the matter further. Feel free to close this issue.

**Comment by stsewd** [comment]
@atodorov for the record, neither user can delete the translation. Current solution is deleting one of the projects and making a new one (same name can be used).

I think we can keep it open to fix the circular dependency. Sorry for the problem.

**Comment by stsewd** [comment]
@atodorov this was part of a security bug (was already solved), now users can only add projects where they are owners as translation. And the circular project was also resolved. I'm not sure if now you can delete the project.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
