### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by boscorelly** [rtfd/readthedocs.org#2622]
Hi,

i can't install on a "fresh" install of CentOS (it is also hosting my centreon system).
`Command "/home/docs/rtd/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5s95zS/lxml/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-oquiI0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/rtd/include/site/python2.6/lxml" failed with error code 1 in /tmp/pip-build-5s95zS/lxml/
`
Executed as user docs and as root.

**Comment by ericholscher** [comment]
We don't support custom installs of the project. You can read more about why here: http://docs.readthedocs.io/en/latest/open-source-philosophy.html#official-support -- thanks for your interest in the project!

**Comment by boscorelly** [comment]
what a fucking joke....

**Comment by ericholscher** [comment]
The joke is asking for us to provide you free support. We'll happily provide paid support of custom installs, but as the page above mentions, we have limited time and choose to prioritize our open source users.

**Comment by boscorelly** [comment]
You have a guide.
I follow the guide.
It is not working.
Not my fault.
