### ISSUE TITLE
html: build view broken on mac firefox

### ISSUE THREAD

**Issue by joernhees** [rtfd/readthedocs.org#2624]
https://readthedocs.org/projects/rdflib/builds/4959564/

looks like this for me:
![screen shot 2017-01-30 at 14 35 55](https://cloud.githubusercontent.com/assets/464192/22425113/d64b39a4-e6f9-11e6-96e2-401053f0bb94.png)

if i disable the `margin-bottom: 16px` in `div.build-command div.build-command-run > span` it's fixed:
![screen shot 2017-01-30 at 14 36 30](https://cloud.githubusercontent.com/assets/464192/22425144/fe82a9ca-e6f9-11e6-82c4-ccc5cf3e29e6.png)

**Comment by agjohnson** [comment]
This is a duplicate issue of #2261, closing.
