### ISSUE TITLE
docutils is updated to version > 0.12 because of pip install -U flag - fails documentation build

### ISSUE THREAD

**Issue by cpaulik** [rtfd/readthedocs.org#2625]
## Details
RTD needs docutils 0.12 but during the build the following command is executed:

`python /home/docs/checkouts/readthedocs.org/user_builds/ascat/conda/docs/bin/pip install -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/ascat/.cache/pip mkdocs==0.15.0 git+https://github.com/rtfd/readthedocs-sphinx-ext.git@0.6-alpha#egg=readthedocs-sphinx-ext commonmark==0.5.4 recommonmark==0.1.1`

This updates docutils to 0.13.1

```
Collecting docutils>=0.11 (from recommonmark==0.1.1)
  Downloading docutils-0.13.1-py2-none-any.whl (537kB)
```

* Project URL: 
* Build URL (if applicable): https://readthedocs.org/projects/ascat/builds/4959791/
* Read the Docs username (if applicable): 

## Expected Result

RTD should build

## Actual Result

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/ascat/conda/docs/lib/python2.7/site-packages/docutils/writers/_html_base.py", line 671, in depart_document
    assert not self.context, 'len(context) = %s' % len(self.context)
AssertionError: len(context) = 3
```

See also https://github.com/sphinx-doc/sphinx/issues/3212

**Comment by ericholscher** [comment]
What is the suggested fix here? It seems like you need to specify a newer version of Sphin which fixes this issue?

**Comment by cpaulik** [comment]
I worked around it for now by putting "sphinx>1.5" in my RTD `environment.yml` file. 

My first guess would be that the whole thing would work if pip install is called without the `-U` flag.
