### ISSUE TITLE
master_doc is ignored when serving build HTML via readthedocs.io

### ISSUE THREAD

**Issue by nichtich** [rtfd/readthedocs.org#2628]
## Details

* Project URL: https://readthedocs.org/projects/pod-pandoc/
* Build URL (if applicable): http://pod-pandoc.readthedocs.io/
* Read the Docs username (if applicable): 

The file `conf.py` sets `master_doc` to `Pod-Pandoc`. Sphinx uses `Pod-Pandoc.rst` as master document and generates `Pod-Pandoc.html` but the webserver at readthedocs.io seems to ignore this setting and still looks for `index.html`.

## Expected Result

* http://pod-pandoc.readthedocs.io/en/latest/ should redirect to 
  http://pod-pandoc.readthedocs.io/en/latest/Pod-Pandoc.html

## Actual Result

* http://pod-pandoc.readthedocs.io/en/latest/ results in a 404 page (or shows the dummy index page created to prevent 404)

## Requirement

If `master_doc` is not set to `index` then create a redirect from the directory index to master file (in this case: `Pod-Pandoc.html`).

**Comment by ericholscher** [comment]
We can't reconfigue nginx to use a different index file. I don't know a reasonable way to implement this, so you should probably just create an index.rst thats a symlink or some other workaround.

**Comment by nichtich** [comment]
Thanks for the quick feedback. I created a plugin to add an `index.html` that redirects to the real master document.
