### ISSUE TITLE
Remove Django filters

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2635]
We aren't using Django Filters project anymore, this dependency should be removed. This will require some updates to the code where it is expected.

**Comment by ericholscher** [comment]
I believe it's used in REST Framework, but the in page filters aren't being used. It broke our pagination on Builds in #2633, so it might also be breaking other stuff, and is unnecessary complexity.

**Comment by vardhan26** [comment]
I would like to fix this bug but I am new and do not know how to start. how can I fix this?

**Comment by humitos** [comment]
@vardhan26 I started _today_ to take a look at the code, but what I would do is something like:

1. read this http://docs.readthedocs.io/en/latest/contribute.html
1. install readthedocs project in my computer following http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs
1. remove django-filter (`pip uninstall django-filter`)
1. run tests (`python manage.py test`)
1. see what fails
1. try to fix them
1. runserver (`python manage.py runserver`)
1. try to build different projects again (`python manage.py update_repos pip`)
1. create a PR
1. be happy to be a contributor :)

**Comment by ChamanAgrawal** [comment]
hey @agjohnson  do i have to debug all the 174 errors and 25 failures and then send PR or I can debug few and contribute ?

**Comment by rixx** [comment]
@vardhan26, @humitos, @ChamanAgrawal: are you working on this issue atm?

**Comment by humitos** [comment]
@rixx No, I'm not. Would you like to?

I would like to _fix_ my previous command to run the tests: `tox -e py27`, since they are using `tox` in RTD :)

**Comment by rixx** [comment]
@agjohnson 

I found the following uses of `django_filters`:

- `build.filters` defines some filtersets
- `core.urls` uses views from `django_filters.views` in `deprecated_urls`; I assume those are to be deleted?
- `projects.filters` and `builds.filters` define lots of filters that are used as `filter_class` in `restapi.views.model_views`, and are passed as `context` sometimes in `projects.views.public`

I'd appreciate guidance as to what to do with those, especially those used in `restapi.views.model_filters` and `projects.views.public`.

**Comment by JLorne** [comment]
Sorry to write a comment in a closed issue, but I don't know where to put it.

We are using readthedocs as our documentation build system and we are using the REST API to monitoring the build status of the different versions of our repositories. Now that you removed django-filter, do you have another way to use the REST API without having to parse all builds from the beginning of time?

**Comment by davidfischer** [comment]
@JLorne while going through some of these issues I found this. It is now possible to filter builds by project. For example, you can do something like https://readthedocs.org/api/v2/build/?project__slug=pip (that's a double underscore). Hopefully this meets your needs.

APIv2 is also now [documented](https://docs.readthedocs.io/en/latest/api/v2.html). Since the RTD team is going through some initial design on a v3 API, I'd love to understand your use case a bit better so we can better meet it.

**Comment by JLorne** [comment]
Thank you @davidfischer for the filterable v2 API.
We are using it to monitor documentation build status for our 160 internal repositories and display build fail on TV. But we need to keep track of the build status of some versions in addition of the latest. I add a custom API that add build API with some query parameters:
- api/build?slug=pip&version=v9.0.3 => returns all pip v9.0.3 builds ordered by dates (latest first)

**Comment by davidfischer** [comment]
Currently only the `slug` is used for filtering. For performance reasons, we wanted to make sure that things you can filter on are indexed in the database. I don't believe the version parameter in https://readthedocs.org/api/v2/build/?project__slug=pip&version=v9.0.3 does anything.
