### ISSUE TITLE
Docs fail to build with python 3.6 (python3.6 not found)

### ISSUE THREAD

**Issue by nelson-liu** [rtfd/readthedocs.org#2639]
## Details

* Project URL: http://deep-qa.readthedocs.io/en/latest/
* Build URL (if applicable):https://readthedocs.org/projects/deep-qa/builds/5022575/
* Read the Docs username (if applicable): nfliu

## Expected Result

The docs build properly.

## Actual Result

The build failed. Pardon if this is a trivial issue, but it seems like it has to do with `python3.6` -- I don't recall this being the default the last time I ran a build (my default is CPython 3.x, and I specifically recall having to add the `typing` module to my requirements to support the python 3.4 that RTD used to run). Not sure if this is on my side or on RTD's...thoughts?

**Comment by agjohnson** [comment]
This might be related to a release I just put out. My guess is the correct python version is not being selected based on the build image.

**Comment by dmed256** [comment]
Not sure if it's related, but I started to get a similar error today:

![error](https://cloud.githubusercontent.com/assets/1812355/22910286/8ee26b7a-f21e-11e6-8c07-b523f1c77bc6.png)

Thanks for looking into it!

**Comment by agjohnson** [comment]
@dmed256 thanks, yes that's also related

**Comment by agjohnson** [comment]
@dmed256 I believe I've resolved the issue that caused the `python3.3` error. I'm rebuilding your docs now, but seems to work okay

**Comment by dmed256** [comment]
@agjohnson Thanks a lot for the fast fix + rebuild :)

**Comment by agjohnson** [comment]
@nelson-liu I think what happened was a build was triggered in the middle of the deploy, and the build image name failed a lookup, defaulting to python 3.6. You are now using `python3.4` as expected. This probably points to us also having to wipe all virtualenvs, as something about how we are trying to recreate virtualenvs causes a problem here.

**Comment by nelson-liu** [comment]
ah i see, thanks for the quick resolution @agjohnson ! feel free to close if you're satisfied this has been resolved (not sure if there's work left to be done).

**Comment by agjohnson** [comment]
Looks like your build passed. I'll close this issue to deal with the virtualenv implementation separately.

**Comment by michaelpacer** [comment]
Not sure if this is the same issue, but our docs are failing for reasons seemingly related to some current merges?

![image](https://cloud.githubusercontent.com/assets/2482408/22954285/6aa57944-f2ca-11e6-9293-0771df83d791.png)

NB: They were failing before that too, but that was an unrelated issue that should be addressed shortly.

**Comment by agjohnson** [comment]
@michaelpacer https://github.com/jupyter/nbconvert/blob/master/readthedocs.yml#L4

I can pin your project to the new build image to ensure 3.5 support, you are currently limited to 3.4 until we make the switch the new 2.0 build image later this week:
http://blog.readthedocs.com/build-image-upgrade/

**Comment by michaelpacer** [comment]
Thanks a tonne! 

Just curious, why hadn't this been an issue until recently (where it seems like it was expecting 3.3 before)?

**Comment by agjohnson** [comment]
I think readthedocs-build was parsing 3.5 as a valid pointer, but RTD was ultimately using just `python2` or `python3`. The updates I just pushed out were to support minor version specification as well
