### ISSUE TITLE
Documentation build failing due to timeout

### ISSUE THREAD

**Issue by martingalloar** [rtfd/readthedocs.org#2641]
## Details

* Project URL: http://readthedocs.org/projects/pysap/
* Build URL (if applicable): http://readthedocs.org/projects/pysap/builds/5021915/
* Read the Docs username (if applicable): 

After enabling `nbsphinx` on the documentation builds started to fail. Documentation uses `nbsphinx` and a few Jupyther notebooks to build graphical representations of different network protocols packets using `scapy`.

It seems that the build is reaching the timeout limit, as builds are all in the order of 900 seconds. Travis builds the docs in around 200 secs (e.g. https://travis-ci.org/CoreSecurity/pysap/jobs/201282386) so I'm wondering if there's a way to either speed up the build process or push the limit a little bit further.

## Expected Result

Build succeded

## Actual Result

Build failed with `An unexpected error occurred` error.

**Comment by humitos** [comment]
@martingalloar time limit in RTD is 10 minutes. I'm closing this one as duplicated of #2591 which has more discussion on the topic.

Not really sure what is the position for this of the core maintainers, since I'm sure they can't support a task running _forever_ or for a lot time.
