### ISSUE TITLE
Be able to ignore files/patterns

### ISSUE THREAD

**Issue by zappen999** [rtfd/readthedocs.org#2644]
I've searched, but i cannot seem to find a way of ignoring directorys/files when building the docs. It would be nice to have a `.rtdignore` in the project root that works in the same way as .gitignore.

My usecase:
![](https://i.gyazo.com/653a27f8c6b65914d71b83113118f2e4.png)
## Details
* Project URL: Local setup

## Expected Result
* Add a .rtdignore file to the project root with patterns to ignore.
* RTD now ignores these files when building.

Is there any way of doing this at the moment?

Thanks

**Comment by agjohnson** [comment]
I'm not sure of the use case here. It seems like you should rather be reconfiguring Sphinx to get the directory structure you want?

**Comment by zappen999** [comment]
Thanks for the response. Yes that seems reasonable, I've now tried adding a pattern to `docs/conf.py` like this, without success:
```py
exclude_patterns = [
    '/**/.github/*
]
```
I'm using markdown, should i configure mkdocs instead?

**Comment by agjohnson** [comment]
Not unless you need mkdoc features, mkdocs is not well supported.

**Comment by humitos** [comment]
@zappen999 why not just change your folder structure as @agjohnson said? I mean, using a `docs/` directory at the root of your project. That is the simplest and common way of solve this, isn't it?

**Comment by zappen999** [comment]
@humitos The problem is that i have both `docs/` and `.github/`, and it takes in both directories. If someone could point me to the correct config file to specify the pattern I'd be very thankful.

**Comment by humitos** [comment]
@zappen999 ok, it's not easy to help you since we don't have access to the repo to see how it's configured or so.

I would say that you have set up your root directory for building the documentation instead of the `docs/` folder and that's the issue.

**Comment by ericholscher** [comment]
This is an issue with mkdocs, not with anything in particular we're doing. Going to close this. If you need support, the mkdocs project is the proper place to ask for it.
