### ISSUE TITLE
Please transfer the project "afew"

### ISSUE THREAD

**Issue by teythoon** [rtfd/readthedocs.org#2645]
## Details

* Project URL: https://readthedocs.org/projects/afew/
* Read the Docs username (if applicable): teythoon

## Expected Result

I recently transferred my project "afew" here on github to the newly founded group https://github.com/afewmail.  Would you please be so kind to transfer the rtfd project "afew" to @flokli (also flokli on rtfd)?

**Comment by agjohnson** [comment]
You don't seem to be the owner of the project, so we would not transfer ownership. You can contact the project owner and see about transferring ownership. If you are unable to find contact information for the owner, or the owner is unresponsive, we can help facilitate a conversation. Closing this for now.

**Comment by flokli** [comment]
@agjohnson Did you mean the github project, or the afew project?

**Comment by agjohnson** [comment]
We have no control over github projects, if you'd like to be a (co)owner of the Read the Docs project, you'll have to be in touch with the current owner.

**Comment by flokli** [comment]
@agjohnson: Understood. @teythoon is currently not the owner of the RTD project? The seems to be weird, as he maintained the project for a long time. Is there a way to contact the owner, or you can point him at this issue?

**Comment by teythoon** [comment]
@agjohnson I'm confused.  I have just right now logged in to rtfd.org using my username "teythoon", clicked on projects, and there is "afew", with the url https://readthedocs.org/projects/afew/, and there is one person listed under "owners", and that's me.

**Comment by agjohnson** [comment]
Oops, sorry for the confusion, you are correct. You can accomplish this by adding the user as a maintainer, under the project admin dashboard.

**Comment by teythoon** [comment]
Ok, did that.  I actually saw that option, but it was not clear to me that it can be used to transfer ownership.  Can it?
