### ISSUE TITLE
Sporadic "Page Does Not Yet Exist" error message 

### ISSUE THREAD

**Issue by Kgespada** [rtfd/readthedocs.org#2650]
## Details

* Project URL: http://opendcre.readthedocs.io
* Read the Docs username: Kgespada 

## Expected Result

Load any page in the project. (Refreshing the main landing page is a good way to see this issue)

## Actual Result

Very frequently - but not consistently - redirected to the "page does not yet exist" image.

![screenshot from 2017-02-17 13-52-07](https://cloud.githubusercontent.com/assets/1463192/23078848/5a2718d4-f518-11e6-9595-c1e733a29435.png)

As far as I can tell the documentation is all present and available, but very frequently an error message is displayed instead of the desired information.

**Comment by jdtech3** [comment]
Reloaded your docs' landing page for about 10 times. No error... Unreliable servers?

**Comment by Kgespada** [comment]
That's very strange - I usually only need to refresh it about two or three times before I see the error. This is the case for the rest of my team as well.

**Comment by Kgespada** [comment]
So after opening a new project and pointing it at the same repo, it looks like that functionally resolved the problem for us. I think I might leave the old project up in case anyone wants to look into what's happening with it - but since we more or less have a working solution now, this issue could also probably be closed.

**Comment by humitos** [comment]
I wasn't able to reproduce the issue and @Kgespada said the issue could be closed. Closing.
