### ISSUE TITLE
Build fails with RecursionError

### ISSUE THREAD

**Issue by javh** [rtfd/readthedocs.org#2653]
## Details

* Project URL:  http://changeo.readthedocs.io
* Build URL: https://readthedocs.org/projects/changeo/builds/5050686/
* Read the Docs username: javh

## Expected Result

Expected builds for both `latest` and the `version-0.3.3---makedb-expansion` tag to pass without error. 

## Actual Result

Builds for `latest` were passing on February 15, 2017, but have failed consistently after that date. I attempted to validate by wiping all builds and building the `version-0.3.3---makedb-expansion` tag, which had previously built successfully, but it failed as well with the same error. The following error occurred:

```
Exception occurred:
  File "conf.py", line 28, in __getattr__
    def __getattr__(cls, name):  return Mock()
RecursionError: maximum recursion depth exceeded while calling a Python object
```

I also testing another project that had built successfully prior to last week (tag version-0.5.2---windows-install-fix):
* Project URL:  http://presto.readthedocs.io
* Build URL: https://readthedocs.org/projects/presto/builds/5050858/

And received the same error.

* The full traceback for `changeo` has been saved in /tmp/sphinx-err-91k1y4ql.log.
* The full traceback for `presto` has been saved in /tmp/sphinx-err-f4ximys9.log.

**Comment by humitos** [comment]
@javh you have a problem in your `conf.py` snippet. You are returning `Mock` instead of `MagicMock`

**Comment by javh** [comment]
Doh! Thanks, @humitos... Looks like you fixed the FAQ I stole the snippet from too.
