### ISSUE TITLE
Obscure error message: An unexpected error occurred

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#2655]
## Details

* Project URL: https://readthedocs.org/projects/pysynphot/
* Build URL (if applicable):
   * https://readthedocs.org/projects/pysynphot/builds/5054720/ (Sphinx 1.3)
   * https://readthedocs.org/projects/pysynphot/builds/5054832/ (Sphinx 1.5)
* Read the Docs username (if applicable): 

## Expected Result

Successful build.

## Actual Result

Error: An unexpected error occurred. Build took 577 seconds. But perhaps the rendered HTML was published anyway?!

```
...
copying static files... WARNING: html_static_path entry
    '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static'
    does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warning.
Copying readthedocs-dynamic-include.js_t... done
Copying readthedocs-data.js_t... done
Copying searchtools.js_t... done

Command time: 343s     Return: 0 
```

**Comment by guillochon** [comment]
I'm seeing exactly the same issue: https://readthedocs.org/projects/mosfit/builds/5088291/

**Comment by ericholscher** [comment]
Believe this is a timeout because the build is taking more than 10 minutes. This is a bug that was just fixed, and it should now be given 15 minutes for building. If it still takes that long, it should now give a proper exception around what has happened.

**Comment by humitos** [comment]
Closing. Both project are building successfully.

Please, feel free to reopen if you consider.
