### ISSUE TITLE
Missing automodule content possibly due to a different version of sphinx

### ISSUE THREAD

**Issue by yusufm** [rtfd/readthedocs.org#2660]
## Details

* Project URL:  http://mobly.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): yusufm

## Expected Result

Documentation of module created via sphinx automodule. When doing a "make html" locally, we see the different modules correctly documented. 

We are using Sphinx 1.5.2 & Alabaster 0.7.9.

The source files for the page are identical between local and readthedocs versions.

## Actual Result

Missing content when drilling down to individual modules. 

See: http://mobly.readthedocs.io/en/latest/mobly.html#mobly-asserts-module

On readthedocs we see its building with an older version:

Sphinx 1.3.5 & Alabaster 0.7.9.

Is it possible to have readthedocs build with a newer version of sphinx? Possibly by providing a pip requirements file that has the correct version specified?

**Comment by humitos** [comment]
> Is it possible to have readthedocs build with a newer version of sphinx? Possibly by providing a pip requirements file that has the correct version specified?

@yusufm yes, you can provide a `rtd_requirements.txt` on your project's page. Please, try that and let me know if this fixes that issue so we can close it.

**Comment by yusufm** [comment]
Does this have to be in the project root, or in the docs folder?

**Comment by humitos** [comment]
you can configure that in your RTD project's page as you wish.

![captura de pantalla_2017-02-23_18-10-37](https://cloud.githubusercontent.com/assets/244656/23283354/6b1bc02e-f9f3-11e6-9976-e9aa248cdb4a.png)

**Comment by yusufm** [comment]
Its using the right version of sphinx, but still no content. Is it because its not finding the module files?

**Comment by humitos** [comment]
Check the last build message: http://readthedocs.org/projects/mobly/builds/5067247/

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/mobly/envs/latest/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named 'mobly'
```

You will need to install `mobly` in the venv or mock it, maybe.

**Comment by yusufm** [comment]
I added mobly to the requirements file and it now works.

However, thats getting the code from the pip release, not from the source in github. What is the right way to setup the project so that when readthedocs builds the docs, it uses the module code from github?

**Comment by humitos** [comment]
Take a look at this guide: https://pip.pypa.io/en/latest/user_guide/#requirements-files

I'm closing this issue since it's not a problem on RTD but in your repo/project configurations.
