### ISSUE TITLE
Outdated RTD documentation

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#2662]
I'm not 100% sure but it seems that the build process is done inside a docker container, which is defined at https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile and there are more libraries installed that the ones listed at http://docs.readthedocs.io/en/latest/builds.html#packages-installed-in-the-build-environment

**Comment by humitos** [comment]
Also, here http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules it says that `libevent` can cause a problem, but it's listed here http://docs.readthedocs.io/en/latest/builds.html#packages-installed-in-the-build-environment and it's in the Dockerfile: https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile#L19

**Comment by agjohnson** [comment]
We haven't yet decided to just support Docker, but if we did, that would simplify requirements for development set up. Our images can be pulled down and this document is not required. There is probably a better example for missing development headers, there are a number of mathematical packages that are trouble for us.

**Comment by agjohnson** [comment]
Also, i wonder if we can automate this list somehow, or document it in docker-images. The list of libraries is going to rot in our documentation.

**Comment by stsewd** [comment]
The list of libraries was updated recently (and now we have a list for each image, which makes easier to update), we only need to update the `libevent` example as mention here https://github.com/rtfd/readthedocs.org/issues/2662#issuecomment-282170505

**Comment by stsewd** [comment]
@anubhavsinha98 sure!

**Comment by anubhavsinha98** [comment]
So basically I researched on the issue and I founded that I have to add a documentation related to Docker, but I was not able to understand clearly so can you help to understad this issue @stsewd ?

**Comment by stsewd** [comment]
You need to remove `libevent` example from here https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules and maybe add a link to the available libs https://docs.readthedocs.io/en/latest/builds.html#the-build-environment

**Comment by paternal** [comment]
> Also, i wonder if we can automate this list somehow, or document it in docker-images. The list of libraries is going to rot in our documentation.

If you are referring to the list of installed libraries, I wrote a package for this purpose: [sphinxcontrib-packages](http://packages.rtfd.io). It automatically lists:
- [Python versions](https://packages.readthedocs.io/en/latest/pyversions/)
- Python libraries : [Python2](https://packages.readthedocs.io/en/latest/python/python2/) and [Python3](https://packages.readthedocs.io/en/latest/python/python3/)
- [Binaries](https://packages.readthedocs.io/en/latest/bin/)
- [C libraries](https://packages.readthedocs.io/en/latest/c/)
- [debian packages](https://packages.readthedocs.io/en/latest/deb/)
- [LaTeX classes and packages](https://packages.readthedocs.io/en/latest/latex/)

**Comment by paternal** [comment]
> That's cool, but it only works if the docs are built inside the docker images, right?

That's right. It lists the packages installed on the (physical/virtual/docker) system used to generate the documentation:
- you build the [packages](http://packages.rtfd.io) documentation at home: it lists the packages installed on your computer (not really interesting);
- the documentation is built on http://rtfd.io: it lists the packages installed on the system used to build the documentation.

Indeed, it looks like it is not exactly what you need…

**Comment by dojutsu-user** [comment]
@stsewd 

> maybe add a link to the available libs https://docs.readthedocs.io/en/latest/builds.html#the-build-environment

Where the link is to be added, in this section: https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules ?

I am interested in submitting a PR for this issue.
