### ISSUE TITLE
Embed API Javascript example not working

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#2667]
At http://docs.readthedocs.io/en/latest/embed.html#javascript there is a real example that doesn't work because it's not able to load the css and js file because it's using `http://localhost:5555/` urls.

What are the correct ones?

**Comment by humitos** [comment]
On the _NOTE_ it says that they are already loaded but I'm getting a 404 on http://docs.readthedocs.io/static/css/public.css

**Comment by agjohnson** [comment]
The embed stuff is half baked. We should consolidate this until we have something that is production ready.

**Comment by stsewd** [comment]
I think the urls are:

- `{host}/media/css/readthedocs-doc-embed.css`
- `{host}/media/javascript/readthedocs-doc-embed.js`

And on rtd:

- `https://media.readthedocs.org/javascript/readthedocs-doc-embed.js`
- `https://media.readthedocs.org/css/readthedocs-doc-embed.css`

But doesn't look like this is implemented.

**Comment by stsewd** [comment]
I guess we can remove that documentation till we have something working, the embed endpoint was removed https://github.com/rtfd/readthedocs.org/issues/4768.

Actually, it should just be updated, but we need to modify the ext:

The embebed logic comes from https://github.com/rtfd/readthedocs-ext/blob/af0f42aa1227551b0849605d9935d102f130ce8b/readthedocsext/embed/views.py#L35 

and it's mounted on the v1 endpoint https://github.com/rtfd/readthedocs.org/blob/b170de972be8dfe99318ab7533a72c8bf6ec32a1/readthedocs/urls.py#L117-L121

But the sphinx-ext is fetching from the v2 endpoint (that got removed bs it wasn't working).
https://github.com/rtfd/readthedocs-sphinx-ext/blob/5b3afcd9f28264b0e13ca7bb11ebe624c1674fdd/readthedocs_ext/embed.py#L10

The v1 endpoint works https://readthedocs.org/api/v1/embed/?project=requests&doc=index&section=User%20Guide

**Comment by stsewd** [comment]
Should we update the sphinx-ext? or should we mount the embed api on the v2 endpoint?

**Comment by ericholscher** [comment]
Yea, we should remove this from the docs, and just expose the REST API & JS framework for now.
