### ISSUE TITLE
build failing - debug help

### ISSUE THREAD

**Issue by fozy81** [rtfd/readthedocs.org#2669]
## Details

* Project URL: https://github.com/hoodiehq/hoodie
* Build URL (if applicable): http://readthedocs.org/projects/hoodie/builds/5075127/
* Read the Docs username (if applicable): jan & gr2m - I'm not the admin on this repo

## Expected Result

Successful build

## Actual Result

Build failed 'BadZipfile: Truncated file header'

**Comment by humitos** [comment]
I think it was a temporal error trying to download a package.

Now, it's failing because a `TypeError` exception: http://readthedocs.org/projects/hoodie/builds/5077085/. Not sure why.

**Comment by fozy81** [comment]
@humitos thanks for looking at this. Hopefully, its again something temporal.

**Comment by gr2m** [comment]
Hey I’m one of the maintainers. I’ve set the `conf.py` path now. We now get a different error:
https://readthedocs.org/projects/hoodie/builds/5077665/

**Comment by humitos** [comment]
@gr2m is this issue fixed? I see that last builds are passing

**Comment by fozy81** [comment]
@humitos @gr2m  Yes, fixed thank you. I used the  `sphinx-quickstart` command to create a new conf.py and makefile. Useful debug strategy was to point readthedocs account to github branch with updated conf.py and makefile to test it was working.
