### ISSUE TITLE
Improving the Search 

### ISSUE THREAD

**Issue by abinabrahamanchery** [rtfd/readthedocs.org#2678]
## Details

* Project URL: https://readthedocs.org/search/?q=

* Read the Docs username (if applicable): Abin

## Expected Result

There Should be a Search option based on the alphabets so someone new can freely rome around and browse the projects randomly (Something like http://tools.kali.org/tools-listing but based on the Alphabetical order)  

## Actual Result

There is a pretty good search option on the topic

**Comment by humitos** [comment]
@abinabrahamanchery isn't this the page that you are looking for? https://readthedocs.org/projects/

**Comment by abinabrahamanchery** [comment]
@humitos no i was talking about the search page https://readthedocs.org/search/

If you include an option to select the project based on a Alphabet that will be great ..!!!

check out the Search page by yourself its totally Empty and there is a search button saying "Go Crazy" (which is very creative ) but instead of going to a random search if you modify the search page or put some more creativity into that it will be awesome

**Comment by agjohnson** [comment]
We've decided not to incorporate a feature like this. In the future I think we might be able to offer better search on our homepage for projects, but in reality, this is not the normal path for users to find documentation on our site.

Closing this as an off roadmap feature.
