### ISSUE TITLE
Unknown error, a timeout?

### ISSUE THREAD

**Issue by guillochon** [rtfd/readthedocs.org#2680]
## Details

* Project URL: https://github.com/guillochon/MOSFiT
* Build URL (if applicable): https://readthedocs.org/projects/mosfit/builds/5095067/
* Read the Docs username (if applicable): guillochon

## Expected Result

A successful document build.

## Actual Result

The build fails with an unhelpful message "An unexpected error occurred." The commands that do run seem to do so successfully, and the build emits the error 10 minutes after a build is triggered, suggesting a timeout. I have no idea how to proceed.

Also: It seems like a bug for this to be marked as an "unexpected error," it clearly seems to be a timeout.

**Comment by humitos** [comment]
It seems you are trying to compile a C library to build your documentation. So, it fails with this error:

    mpi.h: No such file or directory

https://readthedocs.org/projects/mosfit/builds/5095916/

I suggest you to use a specific requirements for RTD different to the one for your project and put there only what is needed to build the documentation.

In case you _really need_ a C library to build your docs, use the mocking approach: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

Please, try that and let me know if that fixes your issue.

**Comment by guillochon** [comment]
Hi @humitos, so that build in particular was after enabling the "Give the virtual environment access to the global site-packages dir." That obviously didn't work. Most of my attempts have had that option unchecked. So I don't think that's the issue.

**Comment by guillochon** [comment]
Figured this out: The requirements in my requirements.txt file were taking longer than 10 minutes to install.

However, RTD *should* emit a more useful error message! Took forever to figure this out with the useless message that RTD spat out.

**Comment by humitos** [comment]
Thanks!

I'm closing this issue since the problem solved.

> However, RTD should emit a more useful error message! Took forever to figure this out with the useless message that RTD spat out.

Feel free to open another issue to track this and express your ideas on how it should be and we can continue the discussion there.
