### ISSUE TITLE
Copy of our project on RTD causing confusion to users

### ISSUE THREAD

**Issue by nigelbabu** [rtfd/readthedocs.org#2686]
## Details

* Project URL: http://gluster.readthedocs.org
* Build URL (if applicable):
* Read the Docs username (if applicable): nigelbabu

## Expected Result

A user has setup glusterfs.readthedocs.org, which is an outdated copy of our repo at https://github.com/gluster/glusterdocs. This docs are not up-to-date (understandably since it doesn't have access to hooks)

## Actual Result

The copy is removed leading to a 404 or redirected to gluster.readthedocs.org.

**Comment by humitos** [comment]
@nigelbabu Hi, I'm not sure to understand what is the problem here and what you want to do. Can you clarify it a bit?

Do you want to remove this documentation http://glusterfs.readthedocs.org? do you own that project? who does?

**Comment by agjohnson** [comment]
Our policy on this is that we won't remove a user's project directly. If you'd like to have this resolved, you should be in touch with the project owner.

**Comment by nigelbabu** [comment]
@humitos We host http://github.com/gluster/glusterdocs at http://gluster.readthedocs.io. Someone is hosting a copy of our docs at http://glusterfs.readthedocs.io. The problem is without the right hooks, the glusterfs.readthedocs.org site isn't updated. So users visit oudated docs causing confusion.

I'd love to have http://glusterfs.readthedocs.io/ removed if possible. If you can get me in touch with the project's owner and I could ask them, that would be great too. It isn't someone we at the gluster project are familiar with.

**Comment by agjohnson** [comment]
@nigelbabu we can try to facilitate this next week. You'd probably also have luck checking their GitHub profile.

**Comment by nigelbabu** [comment]
@agjohnson Thank you. I've tried, can't find a github username matching the RTD username.

**Comment by Paebbels** [comment]
@nigelbabu You should note that both (yours and the outdated) docs are build from the same GitHub repository. The outdated version is not build from a fork of your repository.

@agjohnson Isn't there a rule that a GitHub URL can only be used once in ReadTheDocs? Other projects like Landscape or Travis show an error if you add an already existing GitHub URL to the project.

Moreover, if ReadTheDocs uses OpenID (#2698), both accounts could be linked and avoid duplication. Building docs by users, who aren't part an authorized GitHub team.

**Comment by nigelbabu** [comment]
@Paebbels I'm well aware that it's not a fork.

@agjohnson Any luck with this one? i know there's plenty of requests you folks have to deal with.

**Comment by humitos** [comment]
@nigelbabu we have a new policy on this that you can check out at http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by nigelbabu** [comment]
@humitos We solved this slightly differently by using our own domain and pointing that as the canonical address. This has helped stemmed the tide of problems we used to have.

It appears that at some point the RTD team has removed https://glusterfs.readthedocs.io. Much thanks to solving one of our problems for the last year! Thank you for the near-thankless job you do :)
