### ISSUE TITLE
Clean up HTML for `donate` app

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#2691]
More information here: https://github.com/rtfd/readthedocs.org/pull/2503#pullrequestreview-9281664

**Comment by Riyuzakii** [comment]
@ericholscher, i am a first timer and i would like to contribute. could explain the issue a bit and direct me to the files that need to be changed.

**Comment by ericholscher** [comment]
The first step would be to clean up the HTML as suggested in that pull request. It uses `<strong>` where it should be doing it with CSS.

**Comment by Riyuzakii** [comment]
@ericholscher , @agjohnson can you direct me to the files that need to be changed.

**Comment by agjohnson** [comment]
@Riyuzakii all the files that need to be changed are in the review feedback. I'd prefer to remove HTML styling and instead add css rules in https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static/core/css/theme.css

If you clean up the Knockout implementation, you'll be playing with this file:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/donate/static-src/donate/js/donate.js

Sorry I don't have time for more direct guidance. Feel free to raise any questions you run into here and we'll try to point you in the right direction.

**Comment by krsion** [comment]
Has anyone resolved this issue? I'd like to contribute.

**Comment by hanumanthan** [comment]
@agjohnson For replacing the strong tag into css, I looked at static/core/css/theme.css and the css seems to be minified version. Also I could find few style in the html elements in promo_detail.html.

Am I missing something here. Also could you please let me know on how to test my changes as http://127.0.0.1:8000/sustainability/report/live/ - gives me no such promos - which means I need to create promos. How do I create one

**Comment by monvilafer** [comment]
Hi everyone, has anyone solved this issue?
If not, can I work on it?

**Comment by Tikam02** [comment]
@agjohnson clean-up the css/theme.css. check it once so that i can PR it.
![screenshot from 2018-02-13 23-17-21](https://user-images.githubusercontent.com/10548085/36164984-17376920-1114-11e8-9b9e-99d08e265e8c.png)

**Comment by davidfischer** [comment]
To be 100% honest, I think this issue can be closed. The donate app has been moved out of this repository.

**Comment by Tikam02** [comment]
@ericholscher  actually i saw the whole code for js/css/html , sorry to say that but it's not formatted properly can i clean-up the codes.for better understanding.

**Comment by stsewd** [comment]
@Tikam02 you can check this PR for reference #2699 (was closed due inactivity)

**Comment by agjohnson** [comment]
Closing, this isn't valid anymore as the source has moved.
