### ISSUE TITLE
Conda environment is not being built

### ISSUE THREAD

**Issue by molpopgen** [rtfd/readthedocs.org#2700]
## Details

* Project URL: http://githib.com/molpopgen/fwdpy 
* Build URL (if applicable): https://readthedocs.org/projects/fwdpy/builds/5117276/
* Read the Docs username (if applicable): molpopgen

## Expected Result

Conda environment to be build

## Actual Result

Conda environment not built

**Comment by willsheffler** [comment]
same problem:
https://readthedocs.org/projects/rif/builds/5117259/

**Comment by humitos** [comment]
I'm closing this because it's duplicated of #2651
