### ISSUE TITLE
Moving from Sphinx 1.3.1 to 1.5.3 breaks LaTeX compilation of links rendered as code

### ISSUE THREAD

**Issue by stefano-maggiolo** [rtfd/readthedocs.org#2706]
## Details

* Project URL: http://readthedocs.org/projects/cms/
* Build URL (if applicable): http://readthedocs.org/projects/cms/builds/5112454/

That build was the first failing. The triggering commit is https://github.com/cms-dev/cms/commit/3e9bca76fcb31e0b54bd200af38eb320bc1924d3

The errors is in the LaTeX compilation are repetitions of this:
```
! Argument of \T1\. has an extra }.
<inserted text> 
                \par 
l.492 ...dev/cms/tree/v1.3.dev0/config/}{config/}}
                                                  . You want to copy them to...

Runaway argument?
! Paragraph ended before \T1\. was complete.
<to be read again> 
                   \par 
l.492 ...dev/cms/tree/v1.3.dev0/config/}{config/}}
                                                  . You want to copy them to...

```

which seems to be completely unrelated to the commit. More like a different definition of \code{} or \href{}{}?

On my machine with a stock LaTeX installation in Ubuntu 14.04 it compiles without trouble.

**Comment by humitos** [comment]
@stefano-maggiolo not sure if it's already deployed, but I know that the default Sphinx version changed a couple of days ago. Are you using your own `requirements.txt` to pin your own versions?

Looking at the diff from a passing and a failing build I found that this could be useful

```
** (sphinx) defining (legacy) text style macros without \sphinx prefix
** if clashes with packages, set latex_keep_old_macro_names=False in conf.py
```

In case you want to take a look at the whole diff, here it is: http://linkode.org/mV1lx5pLbr1boSNm3zRAX6

**Comment by stefano-maggiolo** [comment]
Progress: I can reproduce the error locally bu installing sphinx 1.5.3. Now debugging.

**Comment by stefano-maggiolo** [comment]
Ok, the failure reason is just that LaTeX doesn't like mixing \sphinxcode and \href (not sure why, and this is probably a bug to fix).

The reason it happens only to us is that I believe to have that output you need to write an extension, and we have extensions that do exactly that (create a link to some URL and render the text as code).

So for us the easy workaround is to style those differently, but I'm going to rename and leave the bug open in case it is interesting to fix.

**Comment by stefano-maggiolo** [comment]
Oh and thanks @humitos for pointing out that it was likely to be a problem in version mismatch, it was very helpful!

**Comment by humitos** [comment]
@stefano-maggiolo I'm not sure if this is a bug on RTD (you should explain it better), on Sphinx (you should report it in the Sphinx repo) or on your own `.rst` code (you should fix it by yourself :) ). Thanks for your feedback!

**Comment by stefano-maggiolo** [comment]
Yeah, it should probably be against Sphinx - sorry I am a bit confuse on the boundaries of the two projects :)
