### ISSUE TITLE
Support Conda Forge by default

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#2713]
It sounds like we should be supporting `conda-forge` by default, as it will have updated versions of packages we release to PyPI much sooner than the default conda install.

Sounds like we just need to add `conda config --add channels conda-forge` to our initial install via docker or in our calling of conda.

Would love contributions or guidance here on what the best path forward is.

**Comment by ericholscher** [comment]
Lots of conversation in #2378 about this.

**Comment by jakirkham** [comment]
Would recommend making sure `conda-forge` has higher channel priority that `defaults`. This is how things are built at `conda-forge`. So environments should be able to reproduce known working environments in `conda-forge` (to the extent one specifies them).

ref: https://conda.io/docs/channels.html#after-conda-4-1-0

**Comment by humitos** [comment]
@jakirkham so, what Eric said is the correct way of doing this since we are using 4.3.11 and 

> The command conda config --add channels new_channel adds the new channel to the top of the channel list, making it the highest priority

I propose a PR at https://github.com/rtfd/readthedocs-docker-images/pull/34 but I'm not sure that is the way we should take. More thoughts there.

**Comment by humitos** [comment]
The PR got merged. Closing this one as fixed.
