### ISSUE TITLE
IE Compatibility mode

### ISSUE THREAD

**Issue by NikitaEgorov** [rtfd/readthedocs.org#2716]
## Details

* Project URL: local
* Build URL (if applicable): local
* Read the Docs username (if applicable): local

## Expected Result
IE work with compatibility mode

Add
``<meta http-equiv="X-UA-Compatible" content="IE=Edge" />``

to base.html

**Comment by humitos** [comment]
I know nothing about IE, but I think you should provide more information about what is this issue about, what's the problem, what's the solution and more detail.

**Comment by humitos** [comment]
Stale issue. Closing.
