### ISSUE TITLE
navigation_depth has no effect

### ISSUE THREAD

**Issue by goerz** [rtfd/readthedocs.org#2718]
## Details

* Project URL: https://github.com/mabuchilab/QNET
* Doc URL:  http://qnet.readthedocs.io/en/latest/
* Build URL: http://readthedocs.org/projects/qnet/builds/

## Description

It appears the `navigation_depth` setting has no effect on the RTD website. In
`conf.py`, I have

    html_theme_options = {
        'collapse_navigation': True,
        'display_version': True,
        'navigation_depth': 4,
    }

This works correctly when generating the documentation locally (`make doc` in a
checkout of the project), using `sphinx_rtd_theme`. However, on the online
version of the docs, the navigation depth remains at 2, which is insufficient.
How do I get a deeper navigation in the sidebar?

**Comment by humitos** [comment]
@goerz what version of `sphinx_rtd_theme` are you using locally?

In RTD it seems you are using `0.1.7` which I think doesn't support `navigation_depth`. Consider upgrading it in your requirements and let me know if that is the reason.

**Comment by humitos** [comment]
A good place to take a look is the RTD documentation itself, that seems to have at least `3`. Maybe you can steal some configurations from there -> https://docs.readthedocs.io/en/latest/team.html#members

**Comment by goerz** [comment]
I'm using version 0.2.4 locally. Is it supposed to work by upgrading whatever older version of the theme  RTD is using through `environment.yml`? I've added the following to `environment.yml`

    - ...
    - pip:
        - ...
        - sphinx_rtd_theme==0.2.4

In the RTD build logs, it says "requirement already fulfilled". It still
complains about ["unsupported theme options"](http://readthedocs.org/projects/qnet/builds/5159327/)

And why is RTD not using the most current version of their own theme on their
server? I really wish they'd just let me create a clean conda environment and
issue the same `make doc` I'm using locally, and then just host the resulting
HTML file.

**Comment by goerz** [comment]
Oh, I think I get why it's not working: After installing the latest version of the theme from `environment.yml`, it then downgrades it again in the next step of the build process. So how do I get around that? Do I have to fork the theme under a different name just so I can put that name in `conf.py`?

Sorry I'm annoyed...

**Comment by stsewd** [comment]
Closing in favor of https://github.com/rtfd/readthedocs.org/issues/3829
