### ISSUE TITLE
"Edit on Github" leads to 404

### ISSUE THREAD

**Issue by goerz** [rtfd/readthedocs.org#2719]
## Details

* Project URL: https://github.com/mabuchilab/QNET
* Doc URL: http://qnet.readthedocs.io/en/latest/
* Build URL: http://readthedocs.org/projects/qnet/builds/

## Description

Several pages of my documentation are autogenerated with `apidoc`, e.g. http://qnet.readthedocs.io/en/latest/API/qnet.algebra.abstract_algebra.html These pages still have an "Edit on Github" link at the top. However, since there is no corresponding ReST file in the repository, the link produces a 404 error.

Is there any way to disable the "Edit on Github" link completely? I think the option `html_show_sourcelink = False` in `conf.py` does this when I compile the documentation locally, but it appears to be ignored on the RTD server.

**Comment by polyzen** [comment]
Duplicate of #1820?

**Comment by goerz** [comment]
Sort of, except that in #1820 the problem is with mixed-up hashes on Github, whereas my issue is for pages where a corresponding ReST file just doesn't exist. But yeah, the two issues are closely related. This can probably be closed, and I'll just add a brief comment on #1820.

In any case, there really should be an option to disable these links.

**Comment by goerz** [comment]
As you point out, this is definitely a duplicate of https://github.com/rtfd/sphinx_rtd_theme/issues/324 Closing here.
