### ISSUE TITLE
Support latest Pygments (for improved Haskell syntax, and more)

### ISSUE THREAD

**Issue by declension** [rtfd/readthedocs.org#2720]
### Change Requested
The use of `Pygments==2.2.0` (or newer, potentially) to highlight code.

### Background
As part of a [syntax highlighting problem noted on Haskell-Servant](https://github.com/haskell-servant/servant/issues/359), @teh pushed a [PR for Pygments](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/685/two-haskell-fixes/diff) that was merged a while ago. 

I've submitted [a Pygments dependency bump in the Servant codebase](https://github.com/haskell-servant/servant/compare/master...declension:359-upgrade-pygments) which works locally, but as we use https://readthedocs.org for actually hosting, it won't help solve the real problem unless Pygments is upgraded here too...

**Comment by humitos** [comment]
Currently, RTD uses `pygments==2.0.2`. Not sure, but I think that upgrading it to `2.2.0` won't be a big deal. Anyway, in the meanwhile, you could use that particular version in your `requirements.txt` file for read the docs.

**Comment by declension** [comment]
@humitos thanks - [we have now](https://github.com/haskell-servant/servant/pull/709/files) actually, and it seems to be working well (see [latest haskell-servant docs](https://haskell-servant.readthedocs.io/en/latest/tutorial/ApiType.html) vs previous [0.10 version](https://haskell-servant.readthedocs.io/en/v0.10/tutorial/ApiType.html)).

So I guess this is a lower priority for now but still might be nice to have (and FWIW I'll report back if I notice anything weird)
