### ISSUE TITLE
Clean up web servers and build servers on project delete

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2722]
Our position thus far:

* RTD is a library, we should preserve documentation
* We won't actively delete documentation for users, and don't automatically clean up projects

I'm undecided on whether we need to change this position, but we do need clean up operations on files to automate removal for the following cases:

* Built documentation needs to be removed for a project
* Project is spam (probably most important currently)
* Customer is no longer a paying customer

If there is no objection to changing our policy on documentation retention, I think the default behavior should be a full clean up on our web and build servers. If we still want to keep these projects around, we could at least offer this clean up through limited interfaces (user triggered removal, admin removal, etc)

cc @ericholscher

**Comment by ericholscher** [comment]
I'd like to archive things to some kind of archive before we wholesale delete things. Perhaps we could upload time dates snapshots to archive.org, or have an S3 or Cloud Files bucket that holds archived or deleted files at some point in time.

I believe we currently do actively delete files from deleted projects, though.

**Comment by agjohnson** [comment]
If we are, there were a number of cases where files weren't removed from either. I handled the last round of spam clean up from the repl.

**Comment by ericholscher** [comment]
It depends on how you delete the projects. I believe it fires on the Version delete: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/builds/models.py#L158-L163

**Comment by humitos** [comment]
This is already implemented. Deleting a project removes all the artifacts.

> Perhaps we could upload time dates snapshots to archive.org, or have an S3 or Cloud Files bucket that holds archived or deleted files at some point in time.

Opened a new issue for this at #4602

Closing here.
