### ISSUE TITLE
can't use readthedocs with gitlab.com

### ISSUE THREAD

**Issue by chaica** [rtfd/readthedocs.org#2723]
## Details

* Project URL: https://gitlab.com/chaica/discountbot
* Build URL (if applicable): https://gitlab.com/chaica/discountbot
* Read the Docs username (if applicable): chaica

## Expected Result
checkout the repo and build the documentation

*A description of what you wanted to happen*
checkout the repo and build the documentation

## Actual Result
Error message:
Failed to import project: Failed to get code from 'https://gitlab.com/chaica/discountbot' (git clone): 128 git clone error output: fatal: could not read Username for 'https://gitlab.com': No such device or address 

*A description of what actually happened*
Error message:
Failed to import project: Failed to get code from 'https://gitlab.com/chaica/discountbot' (git clone): 128 git clone error output: fatal: could not read Username for 'https://gitlab.com': No such device or address 

Let me know if you need more information,
Carl

**Comment by ericholscher** [comment]
This happens to be locally too:

```
-> git clone https://gitlab.com/chaica/discountbot
Cloning into 'discountbot'...
Username for 'https://gitlab.com'
```

**Comment by humitos** [comment]
It seems it's not a public repository. Check out https://gitlab.com/chaica/discountbot in the browser.

**Comment by chaica** [comment]
yes, it was private before but I have been changing the visibility. Anyway it does not come from readthedocs.
