### ISSUE TITLE
Unable to build private project with gold subscription 

### ISSUE THREAD

**Issue by alexkiro** [rtfd/readthedocs.org#2724]
### Steps

* Import new private project
* Go to settings -> Gold
* Adopt the project.
* Go to builds page and trigger a new build

The cloning step fails with:

```
Failed to import project: Failed to get code from 'https://github.com/SpamExperts/xxxx' (git clone): 128 git clone error output: fatal: could not read Username for 'https://github.com': No such device or address
```

**Comment by ericholscher** [comment]
This is not what Gold projects are for. They support Read the Docs -- if you want private projects you can use http://readthedocs.com -- Do we have it documented somewhere that Gold lets you do private projects on readthedocs.org?

**Comment by humitos** [comment]
I did a quick look into our docs and I don't find anything saying that Gold subscription supports private repos.

Private repos are mentioned in a section that says that it works for .com, http://docs.readthedocs.io/en/latest/business/index.html

I'm closing this issue.
