### ISSUE TITLE
Random build failures in readthedocs.org

### ISSUE THREAD

**Issue by Peque** [rtfd/readthedocs.org#2730]
Documentation builds fail randomly. See for example these build failures (from two different projects):

- https://readthedocs.org/projects/osbrain/builds/5161834/
- https://readthedocs.org/projects/markdownreveal/builds/5161988/

Rebuilding them leads to failure/success at random again.

**Comment by Peque** [comment]
This is probably not related to #2773, as I am still finding this issue as of today:

https://readthedocs.org/projects/osbrain/builds/5629372/

**Comment by humitos** [comment]
Hi @Peque! A lot of changes were done in the last months regarding this issue and the builds of `osbrain` are passing. It should be fixed now. I'm closing this issue but feel free to reopen if you consider.
