### ISSUE TITLE
Gold subscription not credited on "Sustainability" page

### ISSUE THREAD

**Issue by LiaungYip** [rtfd/readthedocs.org#2733]
I appreciate the service that Read The Docs provides, so I signed up and [subscribed](https://readthedocs.org/accounts/gold/) to donate $5/month.

I had expected that Gold subscribers would have their name and Gravatar to appear on the [sustainability](https://readthedocs.org/sustainability/) page, along with the [one-time donors](https://readthedocs.org/sustainability/contribute/?). My name and Gravatar do not appear here.

Is this intentional?

**Comment by agjohnson** [comment]
Correct, the donation page is strictly for those that have donated. We could perhaps also display the subscription status of anyone that is giving monthly here though. This sounds like a good addition.

**Comment by agjohnson** [comment]
This issue is probably pretty far off of our roadmap, so i'm going to close it as something we likely won't fix
