### ISSUE TITLE
Project name already registered to a fork

### ISSUE THREAD

**Issue by esteve** [rtfd/readthedocs.org#2737]
## Details

* Project URL: http://ros2-java.readthedocs.io/en/latest/
* Read the Docs username (if applicable): esteve

## Expected Result

http://ros2-java.readthedocs.io/en/latest/ should point to https://github.com/ros2-java/ros2_java or https://github.com/esteve/ros2_java

## Actual Result

http://ros2-java.readthedocs.io/en/latest/ points to a fork of ros2_java named ros2alfred-java

I believe ros2-java as a project name on readthedocs is already registered to another user, so I'd like to claim it for ros2_java, if it's possible.

To prove I'm the author of ros2_java, here's a couple of links.

Announcement I made for ros2_java:
https://groups.google.com/d/msg/ros-sig-ng-ros/y6m51E53Nyo/LTNUs9wADwAJ

Reference to ros2_java at ROSCon 2016 (page 34):
http://roscon.ros.org/2016/presentations/ROSCon%202016%20-%20ROS%202%20Update.pdf

Moreover, I'm a member of the ROS 2.0 organization on GitHub:
https://github.com/orgs/ros2/people
https://github.com/esteve

Thanks!

**Comment by esteve** [comment]
BTW, I contacted the owner of the fork by email before submitting this issue, but I haven't received a response so far.

**Comment by humitos** [comment]
We have a policy to handle these cases now: http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by agjohnson** [comment]
Our abandoned project policy would be the correct place to start here. Closing this issue.
