### ISSUE TITLE
Build terminates with Unexpected error

### ISSUE THREAD

**Issue by piogor** [rtfd/readthedocs.org#2739]
## Details

* Project URL: https://readthedocs.org/projects/tango-controls/
* Build URL (if applicable): https://readthedocs.org/projects/tango-controls/builds/5182699/
* Read the Docs username (if applicable):  piotr.goryl

## Expected Result

*Documentation to be build*

## Actual Result

*Built process stops with* **An unexpected error occurred** after less then minutes. It seems to happen during or just after installation process. I have tried different settings: using original RTD environment and Sphinx 1.4.8 from source/requirements.txt

Some previous builds reported **Failed** but at least HTML was built.

Thanks in advance!
Piotr

**Comment by piogor** [comment]
It was my mistake - merging documentation from other source I have included conf.py in subtree and this cause a trouble.

**Comment by humitos** [comment]
I love when people fixes their own issues :)
