### ISSUE TITLE
Build of "cyphon" project timing out

### ISSUE THREAD

**Issue by lhadjchikh** [rtfd/readthedocs.org#2740]
## Details

I'm having trouble getting my build to pass due to timeout errors. The project has a ton of reST substitutions in the rst_epilog that are taking a long time to process (sorry about that!). The farthest any build has gotten is the `localmedia` step.

Would it be possible to increase the timeout setting for the project?

* Project Name: cyphon
* Project URL: https://github.com/dunbarcyber/cyphon
* Build URL: https://readthedocs.org/projects/cyphon/builds/5181218/
* Read the Docs username: lhadjchikh

## Expected Result

Build completed

## Actual Result

Build exited due to time out

Thanks for your time!

**Comment by humitos** [comment]
@agjohnson the build process is taking 895 seconds and it's killed but I don't understand why the try/except we added the other day didn't worked here: https://github.com/rtfd/readthedocs.org/blob/rel/readthedocs/projects/tasks.py#L182

**Comment by agjohnson** [comment]
This looks to be instead Docker terminating the container due to memory consumption. We try to catch this on container failure -- Docker's API should return with OOM as the reason for termination. We should be backing down to detect exit code `137` as docker killing the process due to memory comsumption, I'm not sure why this isn't caught though.

**Comment by lhadjchikh** [comment]
FYI, all my other builds timed out at the about the same time (~890 seconds, e.g., https://readthedocs.org/projects/cyphon/builds/5191073/), but #5181218 is the only build that didn't return the time out error message. It was also the only build that generated output for the localmedia stage. Not sure if that helps at all, but thought I'd mention it. I only used #5181218 as an example because it looked like it had progressed the farthest, but the absence of an error message has so far been a one-time occurrence.

**Comment by lhadjchikh** [comment]
As an aside, I noticed that search results are returning URLs containing ".txt.html" instead of just ".html". E.g.: 
http://cyphon.readthedocs.io/en/latest/modules/aggregator.filters.admin.txt.html?highlight=filters

Is that because the build isn't making it to the index stage, or do I have something wrong with my configuration?

Would it be possible to increase the timeout setting for the project to see if that resolves the problem with the build timing out (and possibly the issue with search results)? It's still not making it past the JSON build: https://readthedocs.org/projects/cyphon/builds/5229620/

If there's anything I can do on my end to help resolve this, please let me know. Thanks again for your time!

**Comment by lhadjchikh** [comment]
@agjohnson Search results are now working after the bug fix you mentioned in [#2814](https://github.com/rtfd/readthedocs.org/issues/2814). Thank you!! Unfortunately, our builds are still timing out  due to all reST substitutions in the `rst_epilog`. Would it be possible to increase the timeout for [cyphon](https://github.com/dunbarcyber/cyphon) to give the builds longer to complete? Local builds are working fine, it's just the ones on RTD that are failing due to the 15 min timeout. Thanks for your help!

**Comment by humitos** [comment]
hi @lhadjchikh! I just triggered a new build for your project using `latest` and I found that the problem of the memory is when building `readthedocssinglehtmllocalmedia`. I recommend you to disable these formats using https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html#reduce-formats-you-re-building

Please, let me know if doing that solves your problem of memory/

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, I also believe that https://github.com/rtfd/readthedocs.org/issues/2740#issuecomment-413361659 should fix this.

**Comment by humitos** [comment]
@lhadjchikh hey! I added your project to a special build queue that will have more resources available. Let me know if you find that it did or did not work.

**Comment by humitos** [comment]
After building this again in a dedicated queue after increasing its building time and it failed again. Build took 2392 seconds, which it's a lot of time!

I'd like to make this project to build under Read the Docs. Would you mind following what I said in my previous comment? That seems to be the proper solution, since the HTML build step succeed in my tests.

**Comment by lhadjchikh** [comment]
Hi @humitos, thanks for your persistence! And sorry to not get back to this sooner! @chasebrewsky is maintaining this project now, but I submitted a PR ([#679](https://github.com/dunbarcyber/cyphon/pull/679)) to try to get it to build without additional formats. I'll let you know if we have any luck. Thanks again for your help!

**Comment by humitos** [comment]
@lhadjchikh thanks!

I want this project to build in our platform ;)
