### ISSUE TITLE
‘stable’ is built from master instead of tag

### ISSUE THREAD

**Issue by vfaronov** [rtfd/readthedocs.org#2744]
## Details

* Project URL: http://httpolice.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/httpolice/builds/5195878/
* Read the Docs username (if applicable): vfaronov

## Expected Result

The ‘stable’ version on Read the Docs should be built from the latest version tag that is not pre-release. Currently, this is [0.5.2](https://github.com/vfaronov/httpolice/releases/tag/0.5.2) (commit [869d924](https://github.com/vfaronov/httpolice/commit/869d924174e3005ff2f8ef37437e17a67eeddcb6)).

## Actual Result

Instead, Read the Docs builds the ‘stable’ version from commit [7fd0dfc](https://github.com/vfaronov/httpolice/commit/7fd0dfcb85878ae9b41cb3a5285aa90ed4211d7b), which is the current `master` branch, and is not tagged:

![rtd-wrong-stable](https://cloud.githubusercontent.com/assets/300211/24310512/45aa436a-10e1-11e7-8346-5ca068cd7aa5.png)

This can also be seen on the http://httpolice.readthedocs.io/en/stable/ page itself: the title says “0.6.0.dev1”, not “0.5.2” as it should.

I have tried wiping and rebuilding ‘stable’, same result.

**Comment by humitos** [comment]
It seems to be a bug for me. Your stable version (`0.5.2`) and your dev version (`0.6.0.dev1`) follow the PEP440 (https://www.python.org/dev/peps/pep-0440/#developmental-releases) which is the one used for this.

Besides, I didn't find anything strange in your tag names or something that call my attention.

We should take a look at the code and check why it's failing. A good point to start it's the test case suite for sync versions at: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/rtd_tests/tests/test_sync_versions.py#L121

So, the first step for me would be to add a test case with the naming that you have and see if it pass.

**Comment by ericholscher** [comment]
This should now be fixed. We will prefer tags over branches.
