### ISSUE TITLE
getting fail whale when importing new project

### ISSUE THREAD

**Issue by anarcat** [rtfd/readthedocs.org#2746]
## Details

* Project URL: https://readthedocs.org/projects/charybdis/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): anarcat

I added the [Charybdis](https://github.com/charybdis-ircd/charybdis/) project to Readthedocs.org, through the [import manually](https://readthedocs.org/dashboard/import/manual/) button in the [import dashboard](https://readthedocs.org/dashboard/import/).

## Expected Result

I expected the repository to be added and to start building my docs.

## Actual Result

Instead, i got this:

![An ASCII whale says "Fail.  Check back in a bit!"](https://cloud.githubusercontent.com/assets/796623/24359159/7c6c7b4c-12d1-11e7-8ef1-b86272c01f75.png)

The [repository *was* created](https://readthedocs.org/projects/charybdis/), however, which is really not obvious from the error message.

It has a warning that says:

> This repository doesn't have a valid webhook set up. That means it won't be rebuilt on commits to the repository.
> You can [resync your webhook](https://readthedocs.org/dashboard/charybdis/resync_webhook/) to fix this. 

That link gives me more ASCII art (`You sure? O_o`) and goes back to a similar fail whale at [this page](https://readthedocs.org/dashboard/charybdis/resync_webhook/).

Now, I do not have admin or commit access to that project, mind you, so it's possible that this is just the error I should expect when adding such a project. But it seems to me the user experience could be a little better.

Furthermore, I have also experienced the *same* issue with a repository I *do* own, [anarcat/charybdis](https://github.com/anarcat/charybdis/), in the [anarcat-charybdis](https://readthedocs.org/dashboard/anarcat-charybdis/) project. It had the same failures and I ended up ignoring them and running the builds by hand, which worked fine. Eventually, the warning about syncing webhooks went away and things went back to normal there. When I reported this on IRC, I was told the issue couldn't be reproduced (which was probably accurate at the time) and to open an issue if the problem happened again (which it just did).

Thanks!

**Comment by anarcat** [comment]
another note: triggering a manual build failed to accomplish anything. [that build](https://readthedocs.org/projects/charybdis/builds/5205676/) is stuck at the "Triggered" state. after a 10 minutes wait, i tried to trigger a [second build](https://readthedocs.org/projects/charybdis/builds/5205746/) which is now in the "Cloning" state.

this may be an old issue: i was able to dig out https://github.com/rtfd/readthedocs.org/issues/1835 that looks a bit similar, at least regarding the error message (the fail whale).

**Comment by stsewd** [comment]
Hi, have you experienced this problem again?

**Comment by anarcat** [comment]
not recently, i guess we can close this, sorry.

**Comment by stsewd** [comment]
Feel free to reopen if you have this problem again, thank for reporting.

**Comment by RichardLitt** [comment]
@anarcat Nothing to be sorry for. :) Thanks again.

**Comment by Teecloudy** [comment]
Hi i'm having the same problem, im trying to import a .rst file from github into readthedocs manually but im receiving the error message:

This repository doesn't have a valid webhook set up, commits won't trigger new builds for this project. 

Please help me on how i can import my github file to be viewed in readthedocs.

**Comment by RichardLitt** [comment]
@Teecloudy That sounds like a different problem, related to [your webhook](https://docs.readthedocs.io/en/latest/getting_started.html?highlight=webhook#manually-import-your-docs). I would read the documentation on that a bit more; if you are still struggling, open a new ticket so we can help you there, as this one is closed. Thanks!
