### ISSUE TITLE
Error loading footer for branch build

### ISSUE THREAD

**Issue by ajantiss** [rtfd/readthedocs.org#2757]
We are currently trying to build documentation based  on a git branch named 2017.03+lts.1 which seems to be PEP 440 valid (https://www.python.org/dev/peps/pep-0440/#id41)

Unfortunately once fetched from gitlab, the `+` is replaced by `-` in branch name and so becomes invalid.
As a result the black version selection pane is **not** displayed as you can figure here : 

https://documentation.xivo.solutions/en/2017.03-lts.1/

An error is displayed in JS console:

```
readthedocs-doc-embed.js:1             Error loading Read the Docs footer
```

Our main issue is that we need to maintain version for long term and we want to use git branch for this purpose, nevertheless as we are delivering also incremental version, built on tags, every three weeks (2017.04, 2017.05...) we want to have a way for the user to find quickly which version is related to the LTS one. Do you have any idea to achieve it by circumvent this display issue ?

**Comment by stsewd** [comment]
This works for me on my local instance

![screenshot-2018-1-1 versions read the docs 1](https://user-images.githubusercontent.com/4975310/34472229-1f7ac5b0-ef2b-11e7-9021-0e80789b1385.png)

![screenshot-2018-1-1 welcome to the jungle tag-test 2017 03 lts 1 documentation](https://user-images.githubusercontent.com/4975310/34472230-20d53210-ef2b-11e7-9d83-a51656dd524a.png)

Sorry if I don't understand the issue.

**Comment by swzang** [comment]
How to solved this problem?

**Comment by RichardLitt** [comment]
@humitos I'm not sure why you labelled this as a good first issue. Since you did, can you help explain (perhaps to @swzang) how to solve this?

**Comment by humitos** [comment]
I probably made a mistake. I'm removing that tag.

Also, @ajantiss can you provide the Project URL, Build URL and username of the project? The link you pasted here gives 404.

**Comment by RichardLitt** [comment]
Thanks @humitos! I agree with that decision - this is a bit of a tricky one. :)

**Comment by ajantiss** [comment]
@humitos, indeed we removed completely the source branch, as we were just trying to find a way to handle multiple LTS documentation branch in a single project.

Finally we created two readthedocs project, one for ongoing development (and so flagged as next-lts) and one for each LTS with simple tag version (just numbers) no fancy PEP 440 characters.

If you want to reproduce the issue, you just need to create a branch like 

>  2017.03+lts.1

 and let it build by readthedocs, I think **+** char is the root cause of my past problem

**Comment by ajantiss** [comment]
Ok sorry, I think it has been fixed, or I made something wrong at that time, I confirm @humitos that works perfectly fine after creating branch with such name !

You can close this ticket, it became irrelevant

**Comment by humitos** [comment]
Thanks for the update @ajantiss. Glad it worked!
