### ISSUE TITLE
building project does not generate new pdf with changes in it

### ISSUE THREAD

**Issue by Yaseenh** [rtfd/readthedocs.org#2758]
## Details

so i have set up a test project on github as well as on read the docs. when i make a change e.g index.rst , and i build it in read the docs then click view docs, it shows the changes perfectly however under downloads, when viewing the pdf version it does not show any changes or the updated version. It only shows the first built version. 

Any help?

**Comment by dpdani** [comment]
Same. I'm fairly new to Sphinx/RTD so I'm not sure about what's going on.
When I download the [latest pdf build](https://media.readthedocs.org/pdf/tbb/latest/tbb.pdf) it's still the original blank one, 5 pages long.
Nevertheless, in the build output for command `pdflatex`, it clearly says the recently built one is 7 pages long.
Build number: #5291065

**Comment by humitos** [comment]
@Yaseenh @dpdani can you provide more details?

* project url
* rtd url
* build url
* what you see and what you expected to see in which specific versions

**Comment by dpdani** [comment]
@humitos
This is the project URL: http://tbb.readthedocs.io/en/latest/
Since the day after I posted the comment, though, the PDF builds fine and correctly updates when I push new code into the GitHub repo.

**Comment by humitos** [comment]
Great! So, I'm closing this issue. Please, feel free to re-open if you consider.

**Comment by adamjstewart** [comment]
It seems to me like there is a 1-day delay in updating the PDF for a project. Is this correct? My HTML pages update very quickly, but my PDF generally lags behind by a day. It would be nice if the RtD docs mentioned this delay.

**Comment by humitos** [comment]
@adamjstewart would you mind opening a new issue to address your problem by filling the template and mentioning that it could be related to this one so we can address that problem there? Thanks!
