### ISSUE TITLE
Build started failing about 21:00 UTC

### ISSUE THREAD

**Issue by keiranmraine** [rtfd/readthedocs.org#2766]
## Details

* Project URL: http://cgpjbrowsetoolkit.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/cgpjbrowsetoolkit/builds/5225458/

## Expected Result

Build to completion

## Actual Result

All builds ceased to build.  All appearing to fail after second step with 'Error An unexpected error occurred', before the reading of conf.py.

No fundamental changes had been made between pass and fail generations.  Local build with sphynx all good.

Tried
* Wipe of builds
* Resyncing web-hooks
* Deleting read the docs site and rebuilding

**Comment by ericholscher** [comment]
This looks like a unicode bug in our latest deploy (we should really upgrade to python 3 :frown:) -- it should now be fixed.
