### ISSUE TITLE
one of the request gives 404 

### ISSUE THREAD

**Issue by wojdyr** [rtfd/readthedocs.org#2781]
Just to let you know:
fontawesome request gives 404
for example on http://docs.readthedocs.io/en/latest/index.html

(I noticed it accidentally when I was checking why RTD is slow to load)

![screenshot_2017-04-05_11-24-15](https://cloud.githubusercontent.com/assets/491873/24702027/dd6165dc-19f4-11e7-8e9a-cf2fe20d6cfd.png)

**Comment by wojdyr** [comment]
I get more details when I open RTD in Chrome:

> Access to Font at 'https://media.readthedocs.org/fonts/fontawesome-webfont.woff2?v=4.6.3' from origin 'http://docs.readthedocs.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://docs.readthedocs.io' is therefore not allowed access. The response had HTTP status code 404.

**Comment by jessetan** [comment]
This looks like it's fixed by #372

**Comment by RichardLitt** [comment]
Then let's close this. Reopen as necessary.
