### ISSUE TITLE
Padding problems with line numbers (linenos)

### ISSUE THREAD

**Issue by rmk135** [rtfd/readthedocs.org#2783]
## Details

* Project URL: http://python-dependency-injector.ets-labs.org/providers/factory.html
* Build URL (if applicable): https://readthedocs.org/projects/python-dependency-injector/builds/5214381/
* Read the Docs username (if applicable): rmk

## Expected Result

I see line numbers on the same vertical position as corresponding lines of code.

## Actual Result

I see line numbers on the different vertical position as corresponding lines of code.

**Comment by kevinsteves** [comment]
I am seeing the line number/line misalignment as well.

Pygments (2.2.0)
Sphinx (1.5.5)
sphinx-autobuild (0.5.2)
sphinx-rtd-theme (0.2.4)

.. literalinclude:: _static/uid-login.xml
   :language: xml
   :linenos:

.. literalinclude:: _static/uid-logout.xml
   :language: xml
   :linenos:

**Comment by humitos** [comment]
I see the issue: the line number in the original file doesn't match with the rendered in the documentation.

1. Does it happen only with the RDT theme or with the Sphinx default also?
1. Does it work properly if you build it locally?

**Comment by rmk135** [comment]
Hey @humitos,

1. Yes, it happens only with ``sphinx_rtd_theme``.
2. No, problem is still in place when I build locally.

**Comment by humitos** [comment]
I'm moving this issue to the `sphinx_rtd_theme` repository since it's more related to that than with RTD itself. See https://github.com/rtfd/sphinx_rtd_theme/issues/415

**Comment by rmk135** [comment]
Got it! Thanks!
