### ISSUE TITLE
ImportError: No module named 'pip'

### ISSUE THREAD

**Issue by hans-permana** [rtfd/readthedocs.org#2784]
## Details

* Project URL: https://readthedocs.org/projects/cablab/
* Build URL (if applicable): https://readthedocs.org/projects/cablab/builds/5260056/
* Read the Docs username (if applicable):  bcdev

## Expected Result

I want the RTD build to be successful

## Actual Result

It failed at the step where it is trying to do a pip install on some modules, with error message `ImportError: No module named 'pip'`

**Comment by humitos** [comment]
It seems this is already fixed. I saw that the latest builds from your project are passing properly. I'm closing this one. Please, feel free to re-open in case you consider. Thanks!
