### ISSUE TITLE
exception: No module named javasphinx

### ISSUE THREAD

**Issue by radkin** [rtfd/readthedocs.org#2789]
_this might be an issue for https://github.com/bronto/javasphinx_ if so, apologies.

A functional (for python) readthedocs django server up and running builds runs javasphinx builds and it shows the following on the "sphinx-build" step:

```bash
Running Sphinx v1.5.3
making output directory...

Traceback (most recent call last):
  File "/home/foo/read1/readthedocs.org/user_builds/sample-demo/envs/latest/lib/python2.7/site-packages/sphinx/cmdline.py", line 295, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/foo/read1/readthedocs.org/user_builds/sample-demo/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 199, in __init__
    self.setup_extension(extension)
  File "/home/foo/read1/readthedocs.org/user_builds/sample-demo/envs/latest/lib/python2.7/site-packages/sphinx/application.py", line 516, in setup_extension
    err)
ExtensionError: Could not import extension javasphinx (exception: No module named javasphinx)

Extension error:
Could not import extension javasphinx (exception: No module named javasphinx)
```

- running javasphinx on the command-line works fine
- python is able to find the javasphinx module when run on the command-line with an import statement in the CLI
- virtualenv shows the following
Python 2.7.5

- pip shows these
javasphinx (0.9.15)
readthedocs-sphinx-ext (0.5.4)
sphinx-autobuild (0.6.0)
sphinx-rtd-theme (0.2.4)
sphinxcontrib-httpdomain (1.4.0)

- java 
openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

- conf.py for the project shows the following
extensions = ['javasphinx']

**Comment by humitos** [comment]
Is this a private RTD instance? If not, what is the project name/page on RTD and its repository?

I think you need to provide more details to be able to reproduce your issue.

**Comment by radkin** [comment]
It is a private instance, yes. I'll provide any additional information you want, please just let me know what is useful.

Here are some builds with the error I found with a google search for "exception: No module named javasphinx"

https://readthedocs.org/projects/javasphinx/builds/3450929/
http://cx.bretaza.com-oracle.readthedocs.io/projects/most-report/builds/3206363/

The first one looks like it could lead us to the answer, but I don't have a "paper trail" or "breadcrumbs" that lead to a ticket, issue, etc. that lets us know how it was sorted out.

**Comment by humitos** [comment]
Those builds you linked are not installing `javasphinx` in the repository, that's why they don't find it.

https://pypi.python.org/pypi/javasphinx/0.9.15

**Comment by radkin** [comment]
we added a requirements.txt to the docs directory and it works fine. Thanks!
