### ISSUE TITLE
html_logo not displayed

### ISSUE THREAD

**Issue by Chilipp** [rtfd/readthedocs.org#2791]
## Details

* Project URL: http://readthedocs.org/projects/psyplot/

## Expected Result

Display the [logo](http://psyplot.readthedocs.io/en/latest/_static/psyplot.png) in the upper left corner like, for example, [here](https://borgbackup.readthedocs.io/en/stable/). 

## Actual Result

The logo is not shown. However, when I build the documentation locally on my laptop with

```bash
git clone https://github.com/Chilipp/psyplot.git  # takes a while
cd psyplot/docs
conda env create
source activate psyplot_docs
pip install sphinx-rtd-theme==0.2.4
make html
```

this logo is shown (see the results in [html.zip](https://github.com/rtfd/readthedocs.org/files/912844/html.zip))

**Comment by Blendify** [comment]
```
if not on_rtd:  # only import and set the theme if we're building docs locally
    import sphinx_rtd_theme
    html_theme = 'sphinx_rtd_theme'
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

    # Add any paths that contain custom static files (such as style sheets)
    # here, relative to this directory. They are copied after the builtin
    # static files, so a file named "default.css" will overwrite the builtin
    # "default.css".
html_static_path = ['_static']
```

This is not needed anymore, and maybe this is what is causing the issue?

**Comment by Chilipp** [comment]
Hi! Thanks a lot @Blendify for your help! 

I tried it first by [removing the indent](https://github.com/Chilipp/psyplot/commit/6565a7bc1d5d20f7e2819f723118e070ea137bc8) (i.e. removing ``if not on_rtd``) and also by [removing the entire section](https://github.com/Chilipp/psyplot/commit/db371c1583c827c9c87acb95ba444bc3cb4c5a70). Both did not help as you can see in the [docs](http://psyplot.readthedocs.io/en/dev/) and the corresponding builds [#1](https://readthedocs.org/projects/psyplot/builds/5323523/) and [#2](https://readthedocs.org/projects/psyplot/builds/5323573/)

Also this part is more or less the same as in the [conf.py](https://github.com/borgbackup/borg/blob/master/docs/conf.py) of the working [borg](https://borgbackup.readthedocs.io/en/stable/) documentation.

Any other idea?

**Comment by Chilipp** [comment]
For whatever reason the icon is shown now, so this issue can be closed
