### ISSUE TITLE
HTML zip does not match latest build

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#2803]
# Details

* Project URL: https://readthedocs.org/projects/ginga/
* Build URL (if applicable): https://readthedocs.org/projects/ginga/builds/5307171/
* Read the Docs username (if applicable): pllim

c/c @ejeschke

## Expected Result

https://readthedocs.org/projects/ginga/downloads/htmlzip/latest/ should reflect the documents in http://ginga.readthedocs.io/en/latest/ .

## Actual Result

I downloaded the ZIP file of what is supposed to be latest HTML. However, the downloaded version seems to have an older layout. For example, http://ginga.readthedocs.io/en/latest/manual/plugins_global/thumbs.html is now its own separate page but the ZIP version gives me `file:///.../ginga-latest/index.html#thumbs` instead.

I cannot see how I can re-trigger the build of ZIP version. I only see PDF and ePUB checkboxes in the admin settings.

**Comment by pllim** [comment]
Hmm. So maybe it matches after all, but somehow the documentation is "collapsed into single level"?

**Comment by stsewd** [comment]
@pllim are you still having this issue?

**Comment by pllim** [comment]
Ah, I think we decided to just "live with it". Thanks for following up.
