### ISSUE TITLE
Previous doxygen builds aren't wiped clean

### ISSUE THREAD

**Issue by kratsg** [rtfd/readthedocs.org#2805]
## Details

* Project URL: https://github.com/UCATLAS/xAODAnaHelpers
* Build URL (if applicable): https://readthedocs.org/projects/xaodanahelpers/builds/5316172/
* Read the Docs username (if applicable): kratsg

## Expected Result

I wanted the build to run successfully.

## Actual Result

The build did not run successfully because it complained about a missing file that doesn't actually exist (it was removed). Running this locally shows no issues.

**Comment by humitos** [comment]
Last build is passing properly. Did you change something?

Otherwise we can close this issue.

**Comment by kratsg** [comment]
@humitos not at all. What's confusing is a build right before it failed: https://readthedocs.org/projects/xaodanahelpers/builds/5331537/ . I'm still somewhat worried this isn't fully resolved?

**Comment by humitos** [comment]
I don't know, really.

As you said, two different build with the same git hash and one failed and the other one succeed:
1. https://readthedocs.org/projects/xaodanahelpers/builds/5349203/
2. https://readthedocs.org/projects/xaodanahelpers/builds/5349204/

Besides, I don't understand why two build are triggered at the same time for the same git hash

**Comment by kratsg** [comment]
Just to ping again -- https://readthedocs.org/projects/xaodanahelpers/builds/ -- I'm still seeing spurious failing builds when they should succeed. It's pretty confusing and crazy now.

**Comment by kratsg** [comment]
Figured it out, and this seems like a strange bug. Look at this build: https://readthedocs.org/projects/xaodanahelpers/builds/5421726/

The first `sphinx-build` command is run with `-E` to not use a saved environment and it runs successfully. The second `sphinx-build` command is run *without* `-E` and will use a saved environment, and that's why it crashes. Can we get `-E` on the second build command here?

**Comment by stsewd** [comment]
@kratsg are you still having this issue? Your latest builds (+4 months) are passing. Also, I'm not sure if it is worth to add the `-E` flag :thinking:, we are also _deprecating_ the json builder step in favor of generating the json artifacts in the html build step

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Comment by kratsg** [comment]
Thanks -- this is not an issue anymore -- especially now that I can manually clean up builds from the rtd website.
