### ISSUE TITLE
Extra padding in "literalinclude" directive

### ISSUE THREAD

**Issue by argaen** [rtfd/readthedocs.org#2807]
First of all sorry if this is not the correct repo to post this.

## Details

* Project URL: http://aiocache.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/aiocache/builds/5324336/ (happens in any build)
* Read the Docs username (if applicable): argaen

## Expected Result

the code snippets should appear without the extra bottom padding. Only happens when using the `literalinclude` directive. For example in the two big code snippets in http://aiocache.readthedocs.io/en/latest/configuration.html.

## Actual Result

Extra padding added coming I don't know from where:

![screenshot from 2017-04-23 12-28-21](https://cloud.githubusercontent.com/assets/3578154/25312703/617e9f2c-2820-11e7-85c4-060d29c1115e.png)

**Comment by humitos** [comment]
Hi! The correct repository probably would be https://github.com/rtfd/sphinx_rtd_theme

I'm CC @Blendify who has been working a lot on the theme. He may know if this is a known issue or is something new.

**Comment by Blendify** [comment]
I think #2802  will fix this

**Comment by argaen** [comment]
I just installed latest version of `sphinx_rtd_theme` and same happens in my local machine =/

**Comment by klas-genestack** [comment]
I think this should be closed and all the description moved to rtfd/sphinx_rtd_theme#417

**Comment by argaen** [comment]
Moved!
