### ISSUE TITLE
Building suddenly failed...

### ISSUE THREAD

**Issue by qnzhou** [rtfd/readthedocs.org#2808]
## Details

* Project URL: https://github.com/qnzhou/PyMesh
* Build URL (if applicable): https://readthedocs.org/projects/pymesh/builds/5323255/
* Read the Docs username (if applicable): 

## Expected Result

My doc has been building fine for a long time.  However, It seems the RTD suddenly changes the build steps for my project.  It simply fails to build after a commit with nothing to do with doc.

## Actual Result

It seems the building script is looking for `docs/requirements.txt`.  Is it possible to know the exact steps of the doc building process?  [Existing doc](http://docs.readthedocs.io/en/latest/builds.html) seems to suggest `requirements.txt` is optionals (and I don't see where `docs` comes from).

**Comment by humitos** [comment]
What's your setting here in your RTD project?

![captura de pantalla_2017-04-24_15-04-20](https://cloud.githubusercontent.com/assets/244656/25356313/5618b4ee-28ff-11e7-9ca1-eb0881e40b2e.png)

On the other hand, you have a `doc/requirements.txt` file in your repo at: https://github.com/qnzhou/PyMesh/blob/master/doc/requirements.txt and it's blank. Probably has nothing to do, but anyway, I don't understand what's that useful for :)

**Comment by qnzhou** [comment]
I did not set the requirements file.

![image](https://cloud.githubusercontent.com/assets/3606672/25357788/fe959e5e-28f3-11e7-81a5-0429878b2665.png)

The empty `doc/requirements.txt` was not used, and should be deleted.  Another observation is that suddenly RTD switch to python3.5 instead of python2.7 used before for my build.

**Comment by TagnumElite** [comment]
Is it all right that the command running the `-r docs/requirements.txt` is `-rdocs/requirements.txt`...

**Comment by agjohnson** [comment]
The original issue looks cleared up, but looking into recent builds, your project has a broken git submodule configuration:

```
Build failed with unhandled exception: No option 'path' in section: u'submodule "pybind11"'
```

Closing this as not an issue with RTD, but feel free to reopen if you come across something we're doing wrong.

**Comment by qnzhou** [comment]
Thanks @agjohnson !  I was wondering why the recent build fails.  Where did you find the error info?  I cannot find this error message from the logs.
