### ISSUE TITLE
Inactive account

### ISSUE THREAD

**Issue by colomet** [rtfd/readthedocs.org#2810]
## Details
What can i do if the account is inactive?

## Expected Result
to login in the site

## Actual Result
i can not login after to write the username and pasword.
![captura de pantalla 2017-05-01 a las 2 52 21](https://cloud.githubusercontent.com/assets/3929177/25569518/50e2124e-2e19-11e7-9332-81efc4c74e32.png)

**Comment by humitos** [comment]
Hi. Can you fill the details, please?

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable):

**Comment by colomet** [comment]
colomet
colomet@hotmail.com

**Comment by humitos** [comment]
Hi @colomet! I re-activate your account.

I'm closing this issue. Let me know if you have any problem with it.
