### ISSUE TITLE
.readthedocs.yml not honoring python version

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#2811]
## Details

* Project URL: https://github.com/yougov/velociraptor/tree/bd866b85e1350c9c7c6cba9817d9cbd2808e2016
* Build URL (if applicable): https://readthedocs.org/projects/velociraptor/builds/5360888/
* Read the Docs username (if applicable): jaraco

## Expected Result

The build should have been attempted under Python 3.

## Actual Result

Build was attempted under Python 2.

**Comment by jaraco** [comment]
Changing the config in the UI to Python 3 [resulted in a Python 3 build](https://readthedocs.org/projects/velociraptor/builds/5360894/).

**Comment by humitos** [comment]
Are you still having this issue? I just imported your repo into my local instance and built the latest and stable version from https://github.com/yougov/velociraptor

Python3 was used by default.

**Comment by jaraco** [comment]
I just changed the UI config back to Python 2 and ran a build - https://readthedocs.org/projects/velociraptor/builds/6462644/. It does appear to have run under Python 3, so this issue does appear to have been solved.
