### ISSUE TITLE
Error "expected string" for None in YAML config

### ISSUE THREAD

**Issue by jaraco** [rtfd/readthedocs.org#2813]
In the [docs for yaml config](http://docs.readthedocs.io/en/latest/yaml-config.html#requirements-file), it says that the default for a `requirements_file` is **None**. I assumed **None** meant a Python None or a null value, so I used the YAML syntax of `null` for the value, but that triggered [this build failure](https://readthedocs.org/projects/velociraptor/builds/5360892/).

It's unclear from the docs how one might specify the default value for a setting. Here's what I recommend:

- [ ] Docs for YAML config should specify defaults and example values in YAML syntax (i.e. `null` for null value).
- [ ] RTD should allow for null values (YAML `null` or Python `None`) in config where appropriate.
- [ ] RTD should use native types in YAML config and not encoded values (i.e. literal `None` string in YAML).

But most essentially, it should be possible to specify the default value for a given setting. I don't believe that's possible given the current implementation (though admittedly, I haven't looked at the implementation itself).

**Comment by stsewd** [comment]
I'm solving this issue on the rtd-build repo https://github.com/rtfd/readthedocs-build/pull/38
