### ISSUE TITLE
Malformed URLs in search results

### ISSUE THREAD

**Issue by lhadjchikh** [rtfd/readthedocs.org#2814]
## Details

I'm having trouble getting search results to work properly on the Cyphon project.

Project Name: cyphon
Project URL: https://github.com/dunbarcyber/cyphon
Build URL: https://readthedocs.org/projects/cyphon/builds/5366489/
Read the Docs username: lhadjchikh

## Expected Result

Search results should list valid links to pages in the documentation.

## Actual Result

Search results list links that don't exist. For example, [this search](http://cyphon.readthedocs.io/en/latest/search.html?q=filters&check_keywords=yes&area=default 
) yields[ this result](http://cyphon.readthedocs.io/en/latest/modules/alerts.filters.txt.html?highlight=filters#module-alerts.filters).

I don't see this issue on my local build, so I'm guessing this may be due to the build on RTD timing out before the `makeindex` step. Would it be possible to increase the timeout setting for the project to see if that fixes the issue?

Thanks for your help!

**Comment by agjohnson** [comment]
Correct. This is a duplicate issue around a bug related to us upgrading to Sphinx 1.5. Closing this here, I'm working to address the bug.

**Comment by lhadjchikh** [comment]
Awesome, thank you!
