### ISSUE TITLE
Unable to have the readthedocs theme active

### ISSUE THREAD

**Issue by albancGIT** [rtfd/readthedocs.org#2815]
Hello,

## Details

* Project URL: https://gitlab.com/mindflow/current/
* Build URL (if applicable): http://mindflow.readthedocs.io/fr/latest/
* Read the Docs username (if applicable): albanc

## Expected Result

I just want to have the documentation display the awesome official readthedocs theme

## Actual Result

I have been trying various configurations during a whole day before opening this issue, without any success.

I have created a sphinx based documentation which displays nicely localy using the official RTD theme. But when I upload it to readthedocs.org (thru gitlab pulling), the documentation builds properly, but the RTD theme will never show up. It seems like there is no theme applied on the documentation.

_I have tried switching the html_theme to 'default' as suggested in your doc, without success. I have also tried html_theme = 'sphinx_rtd_theme' and I have tried regenerating a fresh conf.py using sphinx-quickstart. Same result always applies._

Here is the conf.py : https://gitlab.com/mindflow/current/blob/master/docs/source/conf.py

The only specific stuff I can see in my conf.py is the following directive : 

> source_encoding = 'iso-8859-15' 

But I assume the docs wouldn't build without it, as my accented caracters would raise many errors. Anyway it does build, but the default RTD theme won't show up. Either I am missing something trivial, or there is some bug on the server side.

Could you give a hint ? Thanks

**Comment by humitos** [comment]
I tested it locally by downloading the repo, installing all the common RTD packages and running `make html` and I can see the RTD theme properly. Marking as a bug.

**Comment by albancGIT** [comment]
Hello,

It looks like the issue has been solved. Thanks a lot for your investigations humitos.
