### ISSUE TITLE
After project delete the docs are still available 

### ISSUE THREAD

**Issue by saimaz** [rtfd/readthedocs.org#2817]
## Details
After project delete the docs are still available. I removed project months ago and the hosted docs page are still available. How can I remove it? 

* Project URL: http://ongr-handbook.readthedocs.io/en/latest/
* Read the Docs username (if applicable): saimaz

## Expected Result
When the project is deleted also do not see the docs website as well.

## Actual Result
The docs are still hosted after project removal.

**Comment by humitos** [comment]
Hi @saimaz! The project you mentioned seems it's not deleted. Check http://readthedocs.org/projects/ongr-handbook/

I don't remember exactly, but reading this http://docs.readthedocs.io/en/latest/faq.html#how-do-i-change-my-slug-the-url-your-docs-are-served-at it seems that it may delete the docs.

On the other hand, there is some positions about this in https://github.com/rtfd/readthedocs.org/issues/2722

**Comment by saimaz** [comment]
Thank you. Didn't notice that someone forked a repo and created a project in the readthedocs.
