### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by joke2k** [rtfd/readthedocs.org#2818]
* Project URL: https://github.com/joke2k/faker
* Read the Docs username: joke2k
* RTD URL: https://readthedocs.org/projects/faker/

Can you change the ownership to me, please?

Thank you

**Comment by humitos** [comment]
Hi @joke2k. RTD can't just change the owner of a project.

You should contact `fcurella`, who owns `faker` on RTD first to change the ownership or delete and then you re create the project under your name.

Related: https://github.com/rtfd/readthedocs.org/issues/2645#issuecomment-280151954

**Comment by stsewd** [comment]
It seems that you are already on the list of owners now.

**Comment by humitos** [comment]
For the record, we have a policy now http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by reox** [comment]
I have a similar problem here. Someone already created the repository on RTD, thus I can not create a webhook nor trigger the build manually.
How can I contact the owner of the project? If I go to the profile page, there is no information on how to contact the person...

**Comment by stsewd** [comment]
@reox I have made a suggestion for future implementation of this feature here https://github.com/rtfd/readthedocs.org/issues/3382#issuecomment-365815824, would be awesome to have some feedback from your, since you are the one who need this.

**Comment by reox** [comment]
Something like this seems fine - but there is the potential to abuse this feature. Can you couple this with the existence of a webhook? For example in my case there is no chance that the current author has the webhook enabled, as it requires logging in to github and edit the preferences of the repository. If I'm able to proof that I can set up the webhook, I might also be the owner of the repository.
Or maybe there should be some activation process for new repositories: When the repo is linked to RTD, the owner on github should be informed if he wants to allow this. If there is no response in a time internal, the github repo might be abanoned and is "free" to own on RTD.

**Comment by humitos** [comment]
@reox can you open a new issue with your problem by filling the template? (project, username and which project you are requesting).

We can help you by contacting the owner and maybe the owner can add you as an owner also. But please, fill a new issue refering to this one.

Also, I'm closing this one since the original author didn't reply for a long time.
