### ISSUE TITLE
Read The Docs Dead URL 

### ISSUE THREAD

**Issue by cairnsd** [rtfd/readthedocs.org#2829]
## Details

Dead links at "Read the Docs" on the live docs site when you search for "Docker" as a Keyword the first retur
![dead docker links](https://cloud.githubusercontent.com/assets/1311665/25855619/9cf8167a-34cb-11e7-988b-d70fec19a1d4.PNG)
ned link is : "[Generating a Machine Image](http://docs.usharesoft.com/projects/appcenter-user-guide/en/latest/pages/templating/appliance-generate.rst.html?highlight=docker)" which is a dead link.

In fact all the Docker search links are dead.

* Project URL: http://docs.usharesoft.com/projects/appcenter-user-guide/en/latest/search.html?q=docker&check_keywords=yes&area=default
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result
Live Docker documentation links

*A description of what you wanted to happen*
Live links

## Actual Result
dead links

*A description of what actually happened*

**Comment by begriffs** [comment]
We're having a similar problem on the Citus docs - https://github.com/citusdata/citus_docs/issues/513

For more context we recently changed some urls, reorganizing content into new sections, and it appears that the full text search database hasn't flushed out the old locations.

Is there a way to erase and rebuild the text search database?

**Comment by ericholscher** [comment]
Hmm. The URL that was broken previously now all work for me? (http://docs.usharesoft.com/projects/appcenter-user-guide/en/latest/search.html?q=docker&check_keywords=yes&area=default)

The MX one in the citus docs still breaks, I'll poke a bit more.

**Comment by ericholscher** [comment]
I've resolved the immediate issue, but need to look into it more. I believe it's an issue with the search index (JSON) syncing to the webs being delayed, and using old data, which then marks that file as including the recent commit, so commit N+1 of where a file is removed might still keep it in the index.

**Comment by ericholscher** [comment]
This has been fixed.
