### ISSUE TITLE
Old release does not build anymore

### ISSUE THREAD

**Issue by stevendavis** [rtfd/readthedocs.org#2833]
## Details

* Project URL: https://github.com/CFSAN-Biostatistics/snp-pipeline
* Build URL (if applicable): https://readthedocs.org/projects/snp-pipeline/builds/
* Read the Docs username (if applicable): stevendavis

## Expected Result

I have a project on GitHub with a single master branch and multiple tagged releases. The project does not have release branches.  The documentation is hosted on Read The Docs. Six months ago I released version 0.7.0 and the documentation was built successfully. After releasing version 0.8.0, I realized it would be a good idea to publicly expose the docs for the old 0.7.0 release for users who are not ready to upgrade.

## Actual Result

When I tried to build the old docs from the admin page, they don't build anymore.  It looks like RTD is now using a newer version of Sphinx.  My old conf.py contains the mathjax sphinx extension, which results in a build failure with the new Sphinx version.

What is right way to resolve this?  Do I need to restructure my project with release branches, or is there another way -- perhaps there is a way to tell RTD which sphinx version to use for the rebuild.

**Comment by humitos** [comment]
hI @stevendavis, RTD has updated its Sphinx version that is used by default so that's probably the reason of the failing. You should use a `requirements.txt` if you want to pin the versions used for RTD to build your documentation.

http://docs.readthedocs.io/en/latest/yaml-config.html?highlight=requirements#requirements-file

The other solution is to update the configuration of your docs to be compatible with the new version used, `1.5.3`

**Comment by stevendavis** [comment]
@humitos thank you for the prompt reply.  I've created a new 0.7 branch with the contents of the 0.7.0 release and changed the conf.py to make it compatible with Sphinx 1.5.3.  However, RTD does not seem to know about the existence of the branch.  How do I make RTD build the docs for the newly created branch?

**Comment by stevendavis** [comment]
Update.  Got it working like this: GitHub > Settings > Integrations & Services > Click "Test service"

**Comment by stevendavis** [comment]
Closing
