### ISSUE TITLE
Docs compilation started to fail when created a requirements.txt file

### ISSUE THREAD

**Issue by DominiqueMakowski** [rtfd/readthedocs.org#2836]
## Details

* Project URL: http://neurokit.readthedocs.io/en/latest/
* Build URL (if applicable): http://readthedocs.org/projects/neurokit/builds/
* Read the Docs username (if applicable): DominiqueMakowski

Docs compilation started to fail when created a requirements.txt file

## Problem
I had my documentation up and running (see [here](http://neurokit.readthedocs.io/en/latest/documentation.html)) until I created a [requirements.txt](https://github.com/neuropsychology/NeuroKit.py/blob/master/requirements.txt) file. I created this file to be used by travis and codecov for testing purposes. This file is only called within the [.travis.yml](https://github.com/neuropsychology/NeuroKit.py/blob/master/.travis.yml) file.

However, this makes my docs [build to fail](http://readthedocs.org/projects/neurokit/builds/5402802/). It says that the problem lies within another package (`bioread`) where it throwns the following error `ImportError: No module named numpy`. However, it worked nicely before this requirements.txt file. 

I tried to go to advance settings, tick the "compile in a virtual env" box, and provided the requirements.txt file. But it didn't solve the problem.

Is there a way to ignore this requirements.txt file upon documentation building?

Thanks!

## Procedure to reproduce the problem
Build the docs

## Error logs / results
```python
Collecting numpy (from -r requirements.txt (line 1))
  Using cached numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pandas (from -r requirements.txt (line 2))
  Using cached pandas-0.20.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scipy (from -r requirements.txt (line 3))
  Using cached scipy-0.19.0-cp27-cp27mu-manylinux1_x86_64.whl
Collecting sklearn (from -r requirements.txt (line 4))
  Using cached sklearn-0.0.tar.gz
Collecting matplotlib (from -r requirements.txt (line 5))
  Using cached matplotlib-2.0.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting mne (from -r requirements.txt (line 6))
  Using cached mne-0.14.tar.gz
Collecting bioread (from -r requirements.txt (line 7))
  Using cached bioread-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ygKJm_/bioread/setup.py", line 13, in <module>
        metadata = get_locals(os.path.join('bioread', '_metadata.py'))
      File "/tmp/pip-build-ygKJm_/bioread/setup.py", line 10, in get_locals
        exec(open(filename, 'r').read(), {}, l)
      File "<string>", line 13, in <module>
      File "bioread/__init__.py", line 13, in <module>
        from bioread import reader
      File "bioread/reader.py", line 18, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ygKJm_/bioread/
```

**Comment by DominiqueMakowski** [comment]
I still can't find a way to fix it...! 😢

**Comment by humitos** [comment]
Two things here:

1. the problem is not extrictly related to RTD, since trying to install those two packages by one it's not possible:

```
(rtd-2836) [00:46] humitos: ~> pip install numpy bioread
Collecting numpy
  Downloading numpy-1.12.1-cp27-cp27mu-manylinux1_x86_64.whl (16.5MB)
    100% |████████████████████████████████| 16.5MB 97kB/s 
Collecting bioread
  Downloading bioread-1.0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-LFv5FD/bioread/setup.py", line 13, in <module>
        metadata = get_locals(os.path.join('bioread', '_metadata.py'))
      File "/tmp/pip-build-LFv5FD/bioread/setup.py", line 10, in get_locals
        exec(open(filename, 'r').read(), {}, l)
      File "<string>", line 13, in <module>
      File "bioread/__init__.py", line 13, in <module>
        from bioread import reader
      File "bioread/reader.py", line 18, in <module>
        import numpy as np
    ImportError: No module named numpy
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LFv5FD/bioread/
(rtd-2836) [00:47] humitos: ~> 
```

2. RTD automatically detects the `requirements.txt` and installs the dependencies from it. If you want to ignore it, you can create an empty `requeriments_rtd.txt` and point it from the project settings from the admin page.

**Comment by DominiqueMakowski** [comment]
Thanks for your reply!

1. The thing is that if I don't use the requirements.txt (the dependencies are then in the setup.py), it works. How is it that it works without requirements and with, it creates problem within the loading of a particular package (moreover, the error is `no module named numpy` just after numpy's importation...)

2. I've tried it, created an empty requirements_rtd.txt and pointed toward it in RTD's settings. It throws another error that looks like within the loading of again another package : 

```python
...
Processing neurokit-0.1.4-py2.7.egg
Removing /home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/lib/python2.7/site-packages/neurokit-0.1.4-py2.7.egg
Copying neurokit-0.1.4-py2.7.egg to /home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/lib/python2.7/site-packages
neurokit 0.1.4 is already the active version in easy-install.pth

Installed /home/docs/checkouts/readthedocs.org/user_builds/neurokit/envs/latest/lib/python2.7/site-packages/neurokit-0.1.4-py2.7.egg
Processing dependencies for neurokit==0.1.4
Searching for cvxopt
Reading https://pypi.python.org/simple/cvxopt/
Downloading https://pypi.python.org/packages/ef/90/38ccadcf77c8002ffd607fe1c14c67a4bf1041c990e8ba7aa4b8a2287350/cvxopt-1.1.9.tar.gz#md5=a56e7b23d76c2b5aaf3bea2a7c245ea7
Best match: cvxopt 1.1.9
Processing cvxopt-1.1.9.tar.gz
Writing /tmp/easy_install-SjE6Dy/cvxopt-1.1.9/setup.cfg
Running cvxopt-1.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-SjE6Dy/cvxopt-1.1.9/egg-dist-tmp-5Zaa5J
src/C/sparse.c: In function ‘sparse_concat’:
src/C/sparse.c:368:30: warning: variable ‘blk_ncols’ set but not used [-Wunused-but-set-variable]
         int_t blk_nrows = 0, blk_ncols = 0;
                              ^
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
collect2: error: ld returned 1 exit status
UPDATING build/lib.linux-x86_64-2.7/cvxopt/_version.py
set build/lib.linux-x86_64-2.7/cvxopt/_version.py to '1.1.9'
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

Any suggestions?

**Comment by humitos** [comment]
It's trying to install the dependencies from `setup.py` because you have marked the option `Install your project inside a virtualenv using setup.py install` from the "Advance settings" page.

Do you _really_ need to install your project, and its dependencies, to build the documentation? If the answer is "yes" I would recommend you to check out the `conda` environments since you have compiled libraries dependencies.

Anyway, these problems you are have here are not related to RTD itself but with your project.

**Comment by DominiqueMakowski** [comment]
Thanks, it works when I switched off the installation. Can't remember why I did it in the first place... anyway, thanks!!!
