### ISSUE TITLE
Conda packages not being added in build

### ISSUE THREAD

**Issue by snowman2** [rtfd/readthedocs.org#2837]
## Details

* Project URL: https://readthedocs.org/projects/gazar
* Build URL (if applicable): https://readthedocs.org/projects/gazar/builds/5408878
* Read the Docs username (if applicable): snowman2

## Expected Result

The install was supposed to use the conda_env.yml to update the environment.

## Actual Result

The packages are missing and are being installed by pip and it is failing.

**Comment by snowman2** [comment]
Same issue here:

https://readthedocs.org/projects/pangaea/builds/5409294/

**Comment by snowman2** [comment]
https://readthedocs.org/projects/gsshapy

Same issue here:
https://readthedocs.org/projects/gsshapy/builds/5398986/
Was working here:
https://readthedocs.org/projects/gsshapy/builds/5392453/

**Comment by snowman2** [comment]
Looks like the build is fixed.

**Comment by snowman2** [comment]
Same problem is back again:

http://readthedocs.org/projects/gsshapy/builds/5498086/

**Comment by snowman2** [comment]
Looks like an issue pip installing GDAL. However, I install GDAL with conda ...

**Comment by humitos** [comment]
I see the problem. I don't understand why it's happening. As you mentioned before, there are some builds that run exactly the same commands and they worked, but there are others that do not.

I just check by running those commands by hand locally and it worked properly. I'm not sure how to research this issue. Do you have a clue where it could be problem?

On the other hand, what has changed between your builds that failed, then passed and now failed again?

**Comment by snowman2** [comment]
I am not sure what the problem could be. I didn't change anything about the installation, so I don't know. 

- One idea is that the conda environment yml file uses the `conda-forge` channel. There are differences between the `defaults` channel version of GDAL and the `conda-forge` version. 
- Another idea is that it errors and says it needs gcc to compile GDAL. Do you have gcc installed on the build machines?

Thanks!

**Comment by humitos** [comment]
@snowman2 many things has changed regarding the building process and I see your lastest builds (between nine-six month ago) were working properly.

I'm closing this issue here, but feel free to re-open if you consider. Thanks!


> Another idea is that it errors and says it needs gcc to compile GDAL. Do you have gcc installed on the build machines?

Yes.

```
docs@9c125177efbd:~$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
