### ISSUE TITLE
Fix up use of %-style log formatting

### ISSUE THREAD

**Issue by alexwlchan** [rtfd/readthedocs.org#2838]
There are a bunch of logging calls that look like this:

```python
log.info("Lock (%s): Releasing" % self.name)
```

Better practice is to pass the substitutions as extra arguments to the log function:

```python
log.info("Lock (%s): Releasing", self.name)
```

so the string substitution is only performed if the message is actually logged.

I'll tackle this after I've finished the PEP 257 cleanup (#1474). Two parts:

- [ ] Fix any outstanding logs
- [ ] Enable linting to prevent it creeping back in later

**Comment by agjohnson** [comment]
Another great place to clean up some cruft. We currently have no standard for logging, so our log messages are all over the place. Perhaps that is cleanup for another day though. I think that plan above is a good first step.

**Comment by agjohnson** [comment]
I believe this is can be closed as these issues were dealt with during our linting upgrade at pycon.
