### ISSUE TITLE
Update translations, improve workflow to keep updated

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2844]
Translations seem to go out of date very easily, we should have process around keeping this updated and generating support for translations.

Perhaps this is a fabric task or part of something larger, like release automation.

The documentation on translation could also be updated probably.

**Comment by stsewd** [comment]
Related to https://github.com/rtfd/readthedocs.org/issues/3329

**Comment by agjohnson** [comment]
#3329 is unrelated. It describes a feature that allows for Transifex integration for users.

Some of this is updated in #4645, there is invoke tasks for helping. Closing this in favor of #4463
