### ISSUE TITLE
Update docs on docker setup

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2845]
* Mention DOCKER_VERSION == 1.19 requirement
* Permissions on build path

**Comment by humitos** [comment]
I had to downgrade `docker-py` to `1.2.3` also.

**Comment by humitos** [comment]
I'm closing this one in favor of this comment https://github.com/rtfd/readthedocs.org/pull/2692#issuecomment-353792766 and this PR: https://github.com/rtfd/readthedocs.org/pull/3243
