### ISSUE TITLE
Unexpected error when building docs

### ISSUE THREAD

**Issue by vmalloc** [rtfd/readthedocs.org#2849]
## Details

* Project URL: slash.readthedocs.org
* Build URL (if applicable): https://readthedocs.org/projects/slash/builds/5429646/
* Read the Docs username (if applicable): vmalloc

**Comment by molpopgen** [comment]
Seeing this too.  Haven't changed any of my settings that were working a week ago.

* fwdpy11/readthedocs.org
* https://readthedocs.org/projects/fwdpy11/builds/5431466/
* molpopgen

**Comment by molpopgen** [comment]
It seems that my builds are alternating between the unexpected error and this:

```
AttributeError: 'NoneType' object has no attribute 'replace'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/fwdpy11/conda/dev/lib/python3.5/site-packages/docutils/transforms/universal.py", line 290, in apply
    txtnode.parent.replace(txtnode, nodes.Text(newtext))
AttributeError: 'NoneType' object has no attribute 'replace'
```

The above occurred in this build: https://readthedocs.org/projects/fwdpy11/builds/5431637/

**Comment by vmalloc** [comment]
It seems to consistently fail now... Anyone?

**Comment by agjohnson** [comment]
This was related to a server issue that I cleared up today. Feel free to reopen or open a new issue if you are still experiencing this issue.
