### ISSUE TITLE
build docs in python 3 - how to specify a python version for the newly created virtualenv?

### ISSUE THREAD

**Issue by samzn** [rtfd/readthedocs.org#2850]
I'm building documentation for a project written in python 3 (using a local instance/installation of read the docs); using the "install your project inside a virtualenv using setup.py install" option in advanced settings.    

I know I can specify which Python interpreter  is used to create the virtual environment (2 vs 3).

Is there a way to specify which python interpreter version is used in the newly created virtualenv itself (I feel like this is the more useful thing)?

**Comment by humitos** [comment]
I'm not sure if I understand your question, but If you create the virtualenv with Python3, then it will use Python3.

**Comment by samzn** [comment]
not always; for me the python 3 kernel would still (on default) create a python 2 virtualenv, and I found someone with a similar problem here [https://superuser.com/questions/1039369/how-to-create-a-python3-virtual-environment-as-of-2016](url)

**Comment by agjohnson** [comment]
Feel free to provide more information around this case, but otherwise I'm not sure there is anything we can do here unless we can recreate the issue. We've had no problem with python version specific virtualenvs, so this might be a local environment issue.

Closing for now.
