### ISSUE TITLE
Build error: No space left on device

### ISSUE THREAD

**Issue by ppwwyyxx** [rtfd/readthedocs.org#2853]
## Details

* Project URL: https://github.com/ppwwyyxx/tensorpack/
* Build URL (if applicable):https://readthedocs.org/projects/tensorpack/builds/5443371/
* Read the Docs username (if applicable): ppwwyyxx

## Actual Result
```
Error

Failed to import project: Failed to get code from 'https://github.com/ppwwyyxx/tensorpack.git' (git fetch): 128 Stderr: error: file write error (No space left on device) fatal: unable to write sha1 file fatal: unpack-objects failed
```

**Comment by abompard** [comment]
I'm getting this one too.

**Comment by geerlingguy** [comment]
Same here: https://readthedocs.org/projects/drupal-vm/builds/5446465/

```
Error

Failed to import project: Failed to get code from 'https://github.com/geerlingguy/drupal-vm'
(git fetch): 128 Stderr: error: unable to create temporary file: No space left on device fatal:
failed to write object fatal: unpack-objects failed
```

**Comment by humitos** [comment]
Thanks for report this issue. It was something temporal and it was already fixed. It should be working now. Please let us know if the issue persists.
