### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by Simont3** [rtfd/readthedocs.org#2854]
## Details

* Project URL: https://readthedocs.org/projects/awftp/
* Build URL: https://readthedocs.org/projects/awftp/builds/5443784/
* Read the Docs username (if applicable): simont3

## Actual Result

Error

Failed to import project: Failed to get code from 'https://gitlab.com/simont3/awftp.git' (git fetch): 128 Stderr: error: unable to create temporary file: No space left on device fatal: failed to write object fatal: unpack-objects failed

**Comment by abompard** [comment]
Duplicate of #2853?

**Comment by geerlingguy** [comment]
Agreed, we should consolidate the error reporting to that issue.

**Comment by humitos** [comment]
Thanks for report this issue. It was something temporal and it was already fixed. It should be working now. Please let us know if the issue persists.
