### ISSUE TITLE
"stable" not updating after deleting a tag

### ISSUE THREAD

**Issue by aseering** [rtfd/readthedocs.org#2858]
## Details

* Project URL: https://bitbucket.org/nutonian/eureqa_api/
* Build URL (if applicable): http://eureqa-api.readthedocs.io/
* Read the Docs username (if applicable): aseering

## What I did:

I deleted the tag "v1.68" from our repository.  It was a typo (off-by-one); that version doesn't exist yet, we meant to add the previous version.

## Expected Result

"v1.68" should be removed as a tag from our ReadTheDocs account.  "stable" should be re-pointed at v1.67.

## Actual Result

"v1.68" is still shown in ReadTheDocs, and (because it would be the newest version if it existed) "stable" points to it.  I have tried marking "v1.68" as Inactive, but "stable" continues to build that revision.

I'm guessing y'all have a local checkout that's not correctly syncing the tag deletion.  Is there a way we can force ReadTheDocs to blow away and re-check-out its copy of our repository?

**Comment by humitos** [comment]
Looking at the code, it should be removing the branches that doesn't exist anymore in the repository. If it's not enough, maybe, forcing to WIPE the environment should help.

The related code is at https://github.com/rtfd/readthedocs.org/blob/9bcb5fb2fe491ff68ac1466618344ce2347404e2/readthedocs/restapi/views/model_views.py#L163

and

https://github.com/rtfd/readthedocs.org/blob/9bcb5fb2fe491ff68ac1466618344ce2347404e2/readthedocs/restapi/utils.py#L56-L77

that code seems to do what you need.

Can you confirm that this is still a bug on RTD?

**Comment by aseering** [comment]
I can confirm that the nonexistent-tag bug still exists.

`stable` no longer points to that tag because this bug is old enough that we have pushed a tag with a larger version number, which it now correctly points to.

You can see the docs here:
http://eureqa-api.nutonian.com/en/v1.68/

And you can see the repository tags on a dropdown on this page (or just check out the repository):
https://bitbucket.org/nutonian/eureqa_api/src

Note that the tag `v1.68.0` does exist in both places.  However, `v1.68` does not exist in git; only in ReadTheDocs.

I've tried `WIPE`in the environment.  Didn't help.

**Comment by humitos** [comment]
It seems that we are not deleting `Version` anymore and this chunk of code is broken: https://github.com/rtfd/readthedocs.org/issues/3887#issuecomment-378029743 has more information about this issue.

**Comment by andy-maier** [comment]
I also experience this issue on the python-zhmcclient project, and would like to register interest in its resolution.

**Comment by Phlya** [comment]
I have a strange problem: among my tags in the project one contained a Cyrillic symbol which seemed to break the build. I removed that tag, and even re-created the project on readthedocs, but it is still listed in `git show-ref --tags` during the build, while if I do it from my computer it is not there anymore (or look at tags in the repo online).

**Comment by stsewd** [comment]
@Phlya did you try wiping the environment? This can be done in the `Versions` section, `edit` button

**Comment by Phlya** [comment]
Yes, that helped - sorry, forgot to mention when I figured it out.

**Comment by stsewd** [comment]
I see only two possible fixes here:

- It was because of https://github.com/rtfd/readthedocs.org/pull/3913
- https://github.com/rtfd/readthedocs.org/issues/4450

Also related to https://github.com/rtfd/readthedocs.org/issues/4259

Closing in favor of the other issues, but I think this is already solved. Let us know if you still have this problem
