### ISSUE TITLE
`stable` tag in the repo interfers with stable version in RTD

### ISSUE THREAD

**Issue by standage** [rtfd/readthedocs.org#2860]
## Details

* Project URL: https://github.com/dib-lab/khmer
* Build URL (if applicable): https://readthedocs.org/projects/khmer/builds/5455699/
* Read the Docs username (if applicable): danielstandage

## Expected Result

The `stable` build should build the latest release `v2.1`.

## Actual Result

The `stable` build is trying to build the previous stable release `v2.0`.

**Comment by standage** [comment]
It turns out that we had a tag named `stable` that was intended to be temporary but ended up sticking around for a while. I deleted the tag, and now `stable` on RTD tries to build the latest unstable master.

**Comment by humitos** [comment]
Hi @standage! Thanks for your report. I changed the title of the issue and marked it as a bug.

We have been working on how the stable branch is matched in the last weeks. Could you confirm that this is still happening?

**Comment by stsewd** [comment]
This bug is better documented in https://github.com/rtfd/readthedocs.org/issues/3887 and there is a PR https://github.com/rtfd/readthedocs.org/pull/3913. So, closing this in favor of the other issue.
