### ISSUE TITLE
Unimplemented ModerationActionManger model in comments app

### ISSUE THREAD

**Issue by smcoll** [rtfd/readthedocs.org#2879]
`readthedocs.comments.models.ModerationActionManager` is unimplemented, and contains a single `current_approvals` method which doesn't return anything.  This is probably a cleanup issue.

**Comment by stsewd** [comment]
The whole comments app needs to be removed? I don't know where is used on the site right now.

**Comment by shreyateeza** [comment]
@smcoll I too have the same query as @stsewd . Please explain. I am new here and would like to work on this issue.

**Comment by shreyateeza** [comment]
@humitos Please throw some light on this issue.

**Comment by RichardLitt** [comment]
@ericholscher or @agjohnson may know more. :)

**Comment by ericholscher** [comment]
The `comments` app was a dead end, and should probably be deleted. It was our attempt at doing comments on the site, but we never got it working well enough to ship it at scale.

**Comment by shreyateeza** [comment]
@ericholscher, you mean this needs to be deleted. Right?

**Comment by RichardLitt** [comment]
@shreyateeza Sounds like it to me.

**Comment by humitos** [comment]
Yeah, please. If you have some time to work on this, remove the whole app. People is using `sphinx-disqus` for comments, which is not great, but this doesn't work as Eric said. We can recover this code in the future in case we want to continue this work.

In the meanwhile, if we remove it, the code won't interfers in our lives :)

**Comment by shreyateeza** [comment]
Will do it @humitos. Please assign this issue to me. :)

**Comment by humitos** [comment]
I can't assign the issue, sorry.

Yes, remove the folder and make the necessary changes to keep the code working :)
