### ISSUE TITLE
Remove the pullers from readthedocs/privacy/backends/syncers.py

### ISSUE THREAD

**Issue by lordmauve** [rtfd/readthedocs.org#2885]
In readthedocs/privacy/backends/syncers.py there are two puller classes. These don't appear to be referenced anywhere in the codebase:

```
$ ack Puller
readthedocs/privacy/backends/syncers.py
79:class DoubleRemotePuller(object):
117:class RemotePuller(object):
$
```

These appear to be rotten - in particular the docstrings and logging seem to be wrong. DoubleRemotePuller appears to have bugs - it loops over `for server in app_servers` but doesn't use the `server` in its actual rsync command. Neither class has tests.

I would suggest deleting these classes.

**Comment by lordmauve** [comment]
Ah - I misread the code, it does use `server`.

However it does specify `--delete` to rsync, while specifying the same `target`, which appears odd - I would imagine that could cause syncs from each server to clobber each other's files.

**Comment by humitos** [comment]
Those `Pullers` are used as `FILE_SYNCER` setting and loaded at this file `readthedocs.org/readthedocs/builds/syncers.py`

The pullers are only used for production so, and the ops/settings code for production is under a private repo, but they are used. So, they can't be deleted.

> However it does specify --delete to rsync, while specifying the same target, which appears odd - I would imagine that could cause syncs from each server to clobber each other's files.

I don't understand why it could cause problems. Can you elaborate it a bit more? Thanks!

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
