### ISSUE TITLE
"An unexpected error occurred" when two builds are triggered

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#2901]
Triggering the build twice almost at the same time in my local instance makes the second build (the one that receives the LockTimeout exception) to show `An unexpected error occurred` instead of `Version locked, retrying in 5 minutes`

![captura de pantalla_2017-05-23_20-14-23](https://cloud.githubusercontent.com/assets/244656/26380342/7152183e-3ff4-11e7-8796-bded1d15b545.png)

Also, the first one also fails with the same error but most of the commands where executed:

![captura de pantalla_2017-05-23_20-15-06](https://cloud.githubusercontent.com/assets/244656/26380360/8b000656-3ff4-11e7-8e90-23300214d412.png)

(when running just one build it works properly)

**Comment by geerlingguy** [comment]
I seem to be running into this today as well: https://readthedocs.org/projects/drupal-vm/builds/5463920/

<img width="832" alt="screen shot 2017-05-23 at 11 40 45 pm" src="https://cloud.githubusercontent.com/assets/481677/26385965/42f15f28-4011-11e7-8535-11e7755e2e23.png">

**Comment by dlech** [comment]
This is currently a problem for me too with https://readthedocs.org/projects/grx/

Except I am also getting "Version locked, retrying in 5 minutes.", so I am being spammed every 5 minutes with error emails (currently 222 unread messages in my inbox this morning!)

**Comment by RichardLitt** [comment]
Related to 3180.

**Comment by edmorley** [comment]
We're seeing this too:
https://readthedocs.org/projects/treeherder/builds/6211065/

**Comment by humitos** [comment]
I'm closing this one since the original problem was solved. I'm getting the version locked error which is the correct. Please feel free to open other issue if you have a similar problem. Thanks.
