### ISSUE TITLE
Why do I get stable back on the list when I manually disabled it

### ISSUE THREAD

**Issue by cprogrammer1994** [rtfd/readthedocs.org#2906]
## Details

I disabled "stable" however when I build my project I get the "stable" version back.
The base url [moderngl.readthedocs.io](https://moderngl.readthedocs.io) gets redirected to stable however I set it to redirect to the "latest". My settings only work for a couple of minutes.

- tried to make "stable" private
- tried to disable "stable" (multiple times)

![image](https://cloud.githubusercontent.com/assets/11232402/26389853/3bdbac34-405c-11e7-8cd2-161588865169.png)

* Project URL: https://moderngl.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/moderngl/builds/5464362/
* Read the Docs username (if applicable): cprogrammer1994

## Expected Result

I don't want the "stable" version at all.
The moderngl.readthedocs.io should redirect to the latest.

## Actual Result

**sometimes** (probably after I push changes to master then I build the docs) a version stable appears and moderngl.readthedocs.io gets redirected to stable.

**Comment by humitos** [comment]
_I think_ that there is no way to disable `stable` version (there is a PR that will probably enable this, but it's a work in progress and needs review #2908)

On the other hand, when I go to moderngl.readthedocs.io it redirects me to https://moderngl.readthedocs.io/en/latest/, which I understand that it's what you want.

**Comment by humitos** [comment]
I'm closing this one because #2908
