### ISSUE TITLE
Search terms sometimes provide a 404 link

### ISSUE THREAD

**Issue by ChaosMTA** [rtfd/readthedocs.org#2914]
## Details

* Project URL: docs.owlgaming.net
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

Go to this link: https://docs.owlgaming.net/search.html?q=scam&check_keywords=yes&area=default

Clicking the first result should load the page with the highlighted text

## Actual Result

Now if you click on the first result, it will result in a 404 error because the URL becomes `filename.rst.html` when it should be `filename.html`

**Comment by humitos** [comment]
Closing because is duplicated of #2829
