### ISSUE TITLE
Sustainability banners often don't show

### ISSUE THREAD

**Issue by lordmauve** [rtfd/readthedocs.org#2920]
## Details

* Project URL:  \<various\>.readthedocs.io

## Expected Result

Banner adverts appear for non-gold user.

## Actual Result

Banner adverts show with broken image.

![broken-banner](https://cloud.githubusercontent.com/assets/617224/26691585/39296016-46ed-11e7-9e62-da517f2d0f29.png)

This happens in a new incognito window so appears not to be extension related. However I am behind a corporate proxy.

This what appears in the Network pane in Developer Tools:

![network-inspector](https://cloud.githubusercontent.com/assets/617224/26691586/393e4936-46ed-11e7-96e7-2b167515ace0.png)

The first request is plain HTTP, redirecting to HTTPS.

**Comment by agjohnson** [comment]
Is there any further information here? Brand of corporate firewall or something might help track this down.

**Comment by ericholscher** [comment]
Guessing this is an ad blocker issue or similar.
