### ISSUE TITLE
reStructuredText hyperlinks to source files (C, configurations, …) working on GitHub and Read the Docs

### ISSUE THREAD

**Issue by jeras** [rtfd/readthedocs.org#2926]
## Details

* Project URL: https://github.com/jeras/readthedocs-source-links
* Build URL (if applicable): http://read-the-docs-issue-with-source-links-demo.readthedocs.io/en/latest/
* Read the Docs username (if applicable): RedPitaya

## Expected Result

I would like to create a reStructuredText document providing a hyperlink to a C source file or a OS configuration file hosted on GitHub in the same repo as the documentation. The link would have to work both on GitHub (pointing to a file in the same repo) and Read the Docs (preferably pointing to GitHub).

For example:
```
Source file link `main.c </src/main.c>`_.
```
This file works as expected on GitHub, but it points nowhere on Read the Docs.

Absolute links would work properly, but are not practical since they would have to be modified one by one if the repo address is changed or if another branch is used.
```
Source file link `main.c <https://github.com/Me/MyRepo/blob/master/src/main.c>`_.
```

Something useful is mentioned on [StackOverflow](https://stackoverflow.com/questions/20059953/linking-to-source-code-file-in-sphinx/20061845#20061845) using :source:, but I do not know how to get it to work on Read the Docs. And based on my tests it would not work on GitHub.

**Comment by krzychb** [comment]
Maybe this will help: http://esp-idf.readthedocs.io/en/latest/contribute/documenting-code.html#linking-examples.

If you look on the code required to implement it, actually is amazingly short - https://github.com/espressif/esp-idf/blob/master/docs/link-roles.py

**Comment by jeras** [comment]
Thanks, I was able to use the suggested option.

Would you perhaps know, how to modify the displayed text to use a a **fixed width font**, or simply the **literal** style.

**Comment by stsewd** [comment]
Something like this? http://www.sphinx-doc.org/en/stable/markup/inline.html#role-download

**Comment by slcasner** [comment]
> If you look on the code required to implement it, actually is amazingly short - https://github.com/espressif/esp-idf/blob/master/docs/link-roles.py

Now moved here:
https://github.com/espressif/esp-idf/blob/master/docs/idf_extensions/link_roles.py

**Comment by pagrubel** [comment]
> > If you look on the code required to implement it, actually is amazingly short - https://github.com/espressif/esp-idf/blob/master/docs/link-roles.py
> 
> Now moved here: https://github.com/espressif/esp-idf/blob/master/docs/idf_extensions/link_roles.py

Good example of a link that does not work

**Comment by krzychb** [comment]
Good point @pagrubel 😄 

To keep the links live and avoid the issue you mentioned, `link_roles.py` script is generating links to specific GitHub commits like this:

- Source: https://github.com/espressif/esp-docs/blob/51b839ab109a9060f4955b6a481c79b4c21a0678/src/esp_docs/esp_extensions/link_roles.py
- Documentation: https://github.com/espressif/esp-docs/blob/51b839ab109a9060f4955b6a481c79b4c21a0678/docs/writing-documention.md#linking-files
