### ISSUE TITLE
Build successful but "Maze found" page shown instead

### ISSUE THREAD

**Issue by borkmann** [rtfd/readthedocs.org#2934]
## Details

After triggering a build on 'latest' branch, the doc page doesn't show up ("Maze found" page shown) even though the build passed successful. Trying out a different branch from the project also builds fine, but this time the doc page for that branch works. Looks like an issue in the backend?

* Project URL: http://cilium.readthedocs.io/en/latest/

## Expected Result

Doc page shows up after successful build.

## Actual Result

"Maze found" page shown instead.

**Comment by ericholscher** [comment]
This was an error on the deploy, it should be fixed on a rebuild.

**Comment by borkmann** [comment]
Thanks, seems to work again.
