### ISSUE TITLE
Hundred emails on support: documentation  for PlatformIO is broken

### ISSUE THREAD

**Issue by ivankravets** [rtfd/readthedocs.org#2937]
http://docs.platformio.org

P.S: Should we host it on the own server?

**Comment by ivankravets** [comment]
The new repo-trigger helped. How to avoid similar issues?

**Comment by agjohnson** [comment]
Following up on your email, pageviews aren't a problem -- we serve more than 1 million per day. I'm not sure why your project would have went into an unbuilt state however. This would have to have been a version being wiped manually.

**Comment by ivankravets** [comment]
A lot of projects were affected that day. The only one solution was to "re-build" docs via new commit. 

This project ( https://esp-idf.readthedocs.io ) also had the same symptoms. 

> This would have to have been a version being wiped manually.

I never touch your "Admin" system. Just only commits...

If you don't see a problem in the logs, we can close this issue. Thanks!

**Comment by agjohnson** [comment]
This might be due to a bug with our symlinking after builds. Ping this issue if this comes back, but I'll close this for now.
