### ISSUE TITLE
markdown table not rendering properly

### ISSUE THREAD

**Issue by cedewey** [rtfd/readthedocs.org#2941]
## Details

* Project URL: https://gitlab.com/drutopia/documentation/blob/master/development.md
* Build URL (if applicable): http://docs.drutopia.org/en/latest/development.html

## Expected Result and Actual Result

A table should display. It renders properly in GitLab, but not on the Read the Docs page. I've double checked the syntax and I think it's fine, though I have that feeling I must be missing something.

Also, love the project - nice work!

**Comment by agjohnson** [comment]
Recommonmark doesn't support GHFM tables, or any tables for that matter. While the commonmark spec is still being decided on, we've considered "experimental table" support for recommonmark, that uses the most likely table syntax to pass into the commonmark spec.

Anyways, feel free to subscribe to the issues on recommonmark around this issue, this isn't an issue with RTD.
