### ISSUE TITLE
Translation symlinks on subprojects

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2947]
Something seems buggy when symlinking translations as subprojects. For example, given the following project structure:

* Parent project `Foo`
* `Foo` subproject `bar` with language == `en`
* `bar` translation `bar-fr` with language == `fr`

.. I would expect:

* `foo.readthedocs.io/projects/bar/en/latest/` serves `bar`
* `foo.readthedocs.io/projects/bar/fr/latest/` serves `bar-fr`

Currently, `bar-fr` is disregarded.

Design decisions to make here:
- [ ] Are translations subprojects or translations?

**Comment by ericholscher** [comment]
Is there an example of this issue? It seems like it should be working.

**Comment by ericholscher** [comment]
When I added the subproject, the symlink wasn't properly created, but when I re-saved the subproject, it properly created the symlink.

**Comment by ericholscher** [comment]
https://github.com/rtfd/readthedocs.org/pull/2948
