### ISSUE TITLE
Error cloning public git repository referenced in requirements.txt

### ISSUE THREAD

**Issue by chuck1** [rtfd/readthedocs.org#2959]
## Details

* Project URL: https://github.com/chuck1/ws_sheets_server/tree/dev
* Build URL (if applicable): https://readthedocs.org/projects/ws-sheets-server/builds/5586161/

## Expected Result

When RTD gets to

    -e git+git@github.com:chuck1/ws_storage.git@7b8960e628922d2336f1beda6407e447d9fc92d6#egg=ws_storage

in requirements.txt, it should clone the repo and install from source. The requirements file was created automatically by `pip3 freeze`.

## Actual Result

RTD fails to clone the repo. This is a public repository and it does indeed exist.

```
Obtaining ws_storage from git+git@github.com:chuck1/ws_storage.git@7b8960e628922d2336f1beda6407e447d9fc92d6#egg=ws_storage (from -r /home/docs/checkouts/readthedocs.org/user_builds/ws-sheets-server/checkouts/dev/requirements.txt (line 13))
  Cloning git@github.com:chuck1/ws_storage.git (to 7b8960e628922d2336f1beda6407e447d9fc92d6) to /home/docs/checkouts/readthedocs.org/user_builds/ws-sheets-server/envs/dev/src/ws-storage
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.
```

**Comment by humitos** [comment]
Hi @chuck1! It seems the problem was already solved. Looked like the repositories permission were wrong for some reason.

I'm closing this issue. Please, feel free to reopen if you consider. Thanks
