### ISSUE TITLE
Anpr build failing without clear error

### ISSUE THREAD

**Issue by mccalv** [rtfd/readthedocs.org#2962]
## Details

* Project URL: http://anpr.readthedocs.io
* Build URL (if applicable):latest
* Read the Docs username (if applicable): mccalv

## Expected Result

*Build is failing and there isn't an indication on what is going wrong. This documentation is quite relevant for our project, please it would be great if you can have a look into this.

**Comment by agjohnson** [comment]
This looks to be a regression. The error we're receiving on our side is the the conf.py file is not being found, though it exists in your path. You can specify the path to the conf.py in your RTD project configuration, under the 'Advanced' configuration options for the project.

The failure here was supposed to be surfaced to the user -- ie "You are missing a conf.py file". Also, we should be able to find this file. I suspect something got dislodged with recent refactoring. I'll open up several issues for this.

**Comment by rasky** [comment]
If it matters, there were 3 `conf.py` in that repo (you can try at commit 2196e3d)

**Comment by stsewd** [comment]
@mccalv is this issue still a problem? I can see your last builds are successful https://readthedocs.org/projects/anpr/builds/

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

And the latest builds are successful
