### ISSUE TITLE
The API for notifications might be wrong

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2965]
This doesn't seem correct. Ensure that the API does resolve both `Webhook` and `Emailhook` objects from the `Notification` abstract model.

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/urls.py#L27

**Comment by stsewd** [comment]
The notification viewset represents the `EmailHook` model only

https://github.com/rtfd/readthedocs.org/blob/076539117f9b2db7a76e9e8456332b0ef725abe3/readthedocs/restapi/views/model_views.py#L236-L242

For the webhooks notifications, there are other specific urls

https://github.com/rtfd/readthedocs.org/blob/076539117f9b2db7a76e9e8456332b0ef725abe3/readthedocs/restapi/urls.py#L69-L86

**Comment by stsewd** [comment]
So, it seems correct to me (from the point of view of the logic at least)
