### ISSUE TITLE
Allow user-provided docker images for the build environment

### ISSUE THREAD

**Issue by cpascual** [rtfd/readthedocs.org#2966]
Given that rtfd already uses [docker for its build environment](http://docs.readthedocs.io/en/latest/development/buildenvironments.html), I propose that users are allowed to provide their own customized images for building their project.

This would allow the users to install any dependencies needed for building their docs with much more flexibility than just using pip or even conda (for example, I am having [problems which conda does not solve](https://github.com/taurus-org/taurus/issues/408#issuecomment-310458330)). 

Consider the following example. A user creates an account in dockerhub and creates a public docker image called `someuser/someimage:sometag` using the following Dockerfile:

```
FROM readthedocs/build
USER root
RUN apt-get -y update
RUN apt-get -y install foo bar
USER docs 
CMD ["/bin/bash"]
```

then she configures the readthedocs.yml as follows:
```
docker-image:
    someuser/someimage:sometag
```

... and the build is done on her customized build environment.

Note that by basing the customized image on the official rtfd one (which you already have locally cached), the traffic generated when downloading a custom image would be limited to only the custom layers (and you could enforce limits if necessary).

Does this make any sense?
Cheers!

**Comment by agjohnson** [comment]
Thanks for the suggestion!

This is something that I don't think we want to support, as it would be an operations nightmare for us. Our build servers are already over capacity. Arbitrary docker images will worsen this and open us up to a number of cases of broken user experience, user configuration problems bringing build infrastructure down, etc. If you have a very special build process, we hope to address this case with allowing upload from an existing CI service. This would mean one build during the CI pass, we get shipped the built docs and manipulate them for hosting, and things work as expected from there.

**Comment by cpascual** [comment]
> we hope to address this case with allowing upload from an existing CI

That would indeed be awesome (much better for us, since we are already building the docs in Travis anyway).

Any hint of how long may that take?
