### ISSUE TITLE
Scheduled tasks for cleaning up messages

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2967]
Clean up all them message_extends messages stored in the database.

**Comment by humitos** [comment]
@agjohnson can you provide more info here?

It seems that `message_extends` app is still used. So, I suppose that what we want is a migration that remove _old persistent_ messages, right? Let's say older than 2 weeks?

**Comment by humitos** [comment]
Oh, I didn't read the "scheduled task" part. So, instead a migration we want a celery task for this. I think it makes more sense :)

**Comment by humitos** [comment]
This is done at #3604. Closing.
