### ISSUE TITLE
recent builds seem to fail

### ISSUE THREAD

**Issue by nathandunn** [rtfd/readthedocs.org#2976]
## Details

* Project URL: 
http://genomearchitect.readthedocs.io/

* Build URL (if applicable):
http://genomearchitect.readthedocs.io/en/latest/
http://genomearchitect.readthedocs.io/en/stable/
http://genomearchitect.readthedocs.io/en/2.1.0/

* Read the Docs username (if applicable): 
nathandunn / ndunn@me.com

## Expected Result

*A description of what you wanted to happen*
I expected to see the same readthedoc page that I'm used to.

## Actual Result

*A description of what actually happened*
I see an old-school HTML page (no formatting at all) and 404s for a few different files including:

 http://genomearchitect.readthedocs.io/en/latest/images/githubForkTarget.png 404 (Not Found)
(index):1622 GET http://genomearchitect.readthedocs.io/en/latest/images/githubPullRequest.png 404 (Not Found)
(index):1628 GET http://genomearchitect.readthedocs.io/en/latest/images/githubTestProgress.png 404 (Not Found)
(index):1629 GET http://genomearchitect.readthedocs.io/en/latest/images/githubTestStatus.png 404 (Not Found)
(index):1448 GET http://genomearchitect.readthedocs.io/en/latest/images/githubForkButton.png 404 (Not Found)
jquery-2.0.3.min.js:5 GET https://readthedocs.org/api/v2/footer_html/?callback=jQuery20305199388140382901_1498578986138&theme=sphinx_rtd_theme&format=jsonp&_=1498578986139 
send @ jquery-2.0.3.min.js:5
ajax @ jquery-2.0.3.min.js:5
n @ readthedocs-doc-embed.js:1
(anonymous) @ readthedocs-doc-embed.js:1
f @ jquery-2.0.3.min.js:3
fireWith @ jquery-2.0.3.min.js:3
ready @ jquery-2.0.3.min.js:1
ge @ jquery-2.0.3.min.js:1
readthedocs-doc-embed.js:1 Error loading Read the Docs footer
error @ readthedocs-doc-embed.js:1
f @ jquery-2.0.3.min.js:3
fireWith @ jquery-2.0.3.min.js:3
n @ jquery-2.0.3.min.js:5
n @ jquery-2.0.3.min.js:5
dispatch @ jquery-2.0.3.min.js:3
y.handle @ jquery-2.0.3.min.js:3

**Comment by geerlingguy** [comment]
I'm getting 'Build failed' with errors on every build starting this evening...

Project: `drupal-vm`
Example failed build: https://readthedocs.org/projects/drupal-vm/builds/5618109/

Failure message:

```
Error

An unexpected error occurred
```

**Comment by nathandunn** [comment]
I can build locally (successfully) using sphinx 1.6.3 . .  anything else I should test?  

Also, my build is "successful":  

https://readthedocs.org/projects/genomearchitect/builds/5618554/

I'll try to re-run with those build command and see where I get.

**Comment by nathandunn** [comment]
I think it might be related to #2015.  I'm getting 404s on this:

https://readthedocs.org/api/v2/footer_html/?callback=jQuery20309366837078921149_1498643245478&theme=sphinx_rtd_theme&format=jsonp&_=1498643245479

Also images are not being stored properly:

http://genomearchitect.readthedocs.io/en/latest/images/githubForkButton.png

**Comment by nathandunn** [comment]
Either you fixed it or I did (unlikely).  

I did change my settings to use the virtual setup.py and made sure I was using CPython2.    I doubt that was it, though. 

Thanks!
