### ISSUE TITLE
Builds continuously fail with unexpected error

### ISSUE THREAD

**Issue by marcelstoer** [rtfd/readthedocs.org#2982]
## Details

* Project URL: https://nodemcu.readthedocs.io
* Build URL (if applicable):latest, master, dev ... all
* Read the Docs username (if applicable): marcelstoer

## Expected Result

GitHub commit hook triggers build and I never hear anything, has been like this for months more or less.

## Actual Result

For the last couple of days all builds seem to have failed for unknown (to me) reasons.

https://readthedocs.org/projects/nodemcu/builds/5626630/

> An unexpected error occurred

...are they _ever_ expected 😉 

The three listed build tasks there don't indicate any problem. Output suggests all is well.

**Comment by marcelstoer** [comment]
BUT the builds actually do succeed (as suspected) and the pages _are_ updated.

**Comment by trpedersen** [comment]
I have the same problem; builds are reporting as failed, but the updated docs are being installed. It seems something fails after the 'Installing' step.

Example build URL: https://readthedocs.org/projects/uhack-guide/builds/5635512/
Project: https://readthedocs.org/projects/uhack-guide/

**Comment by trpedersen** [comment]
I tried creating a new project (from the same source repo in Bitbucket), to no avail - builds still report 'unexpected error' but the HTML is built successfully.

Eg: https://readthedocs.org/projects/uhack-guide-2017/builds/

**Comment by hugsy** [comment]
Same is happening to me: RTFD stopped generating correctly the docs 14 days ago, without me changing anything to it. Since then all builds fail, but no error message to help debug (and no error when trying locally - on Py2 or Py3).

Project: https://readthedocs.org/projects/gef/builds/

![rtd](https://user-images.githubusercontent.com/590234/28099340-ca48120c-6670-11e7-8980-f381f61cb791.png)

**Comment by TrentBrown** [comment]
Brand new RTD user here. Having what appears to be a very similar issue: I get an "An unexpected error occurred" when my Markdown files are processed, and yet my site renders just fine.

![screen shot 2017-07-16 at 4 11 19 pm](https://user-images.githubusercontent.com/7009/28252107-99bd40c4-6a41-11e7-8ec6-f577822611d5.png)

![screen shot 2017-07-16 at 4 11 42 pm](https://user-images.githubusercontent.com/7009/28252109-ad9e67f8-6a41-11e7-9faa-8b1bc1e4ad0c.png)

![screen shot 2017-07-16 at 4 11 58 pm](https://user-images.githubusercontent.com/7009/28252112-b4123402-6a41-11e7-8e39-57303182e986.png)

![screen shot 2017-07-16 at 4 12 09 pm](https://user-images.githubusercontent.com/7009/28252115-b9294cbe-6a41-11e7-8a76-79eb7aa3c9b3.png)

**Comment by willingc** [comment]
Recent PRs merged #3009 and #2979 appear to have resolved this issue. I recommend closing this issue.
