### ISSUE TITLE
Builds for the past three days seem to fail

### ISSUE THREAD

**Issue by monicacecilia** [rtfd/readthedocs.org#2984]
## Details

* Project URL: 
http://go-ontology.readthedocs.io/

* Build URL (if applicable):
Latest build today: https://readthedocs.org/projects/go-ontology/builds/5627360/
Also at: http://go-ontology.readthedocs.io/en/latest/

* Read the Docs username (if applicable): 
monicacecilia

## Expected Result

I hoped to see the usual display for all documentation. That is, the web page with black / blue / white backgrounds, browsable content with index table on the left, etc. For an example, see this other project of ours (screenshot): 

<img width="400" alt="screen shot 2017-06-29 at 4 55 30 pm" src="https://user-images.githubusercontent.com/1714621/27715418-d33ab07e-5ceb-11e7-83ab-18bc58e2489d.png">

## Actual Result

Instead, all I I see is an old-timey HTML page (without formatting) and with broken links for a number of files, for example these URLs:
http://go-ontology.readthedocs.io/en/latest/DailyWorkflow.html#commit
http://go-ontology.readthedocs.io/en/latest/Configs.html

Examples: 
<img width="400" alt="screen shot 2017-06-29 at 4 56 21 pm" src="https://user-images.githubusercontent.com/1714621/27715434-f3e804de-5ceb-11e7-88f7-2255dd16be6f.png">

<img width="400" alt="screen shot 2017-06-29 at 4 56 37 pm" src="https://user-images.githubusercontent.com/1714621/27715436-f7ac8446-5ceb-11e7-8157-0e2e0cdebdf7.png">

**Comment by marcelstoer** [comment]
Your build says it completed successfully yet it didn't. So this is the exact opposite of #2982.

**Comment by cmungall** [comment]
@marcelstoer - I'm not quite following. I don't see any failed builds here: https://readthedocs.org/projects/go-ontology/builds/

**Comment by monicacecilia** [comment]
@cmungall I may be the source of confusion: the builds have the label saying they are "passing", but something must be broke and thus I wrote in the issue that builds 'seem to fail', for lack of better description. 

Even if builds are 'passing', the documentation display is still wrong. And I'm out of options to update from the Admin panel. I'm also a little surprised that it has been 6 days and we have not heard back from RTD friends; I am hoping it's because #2981 is probably still taking most of their attention.

**Comment by cmungall** [comment]
Unfortunately it's been another 3 weeks, and http://go-ontology.readthedocs.io/ is still not building as expected

**Comment by monicacecilia** [comment]
I burned http://go-ontology.readthedocs.io/ and created http://ontologydocs.readthedocs.io/en/latest/ instead. Error persists and it is not building as expected.  Also getting the sense that I am sending messages to the void here? :(

**Comment by marcelstoer** [comment]
http://ontologydocs.readthedocs.io/en/latest/ makes a request to 

https://readthedocs.org/api/v2/footer_html/?callback=jQuery2030396509873724028_1501870083137&theme=sphinx_rtd_theme&format=jsonp&_=1501870083138

which fails with HTTP 404. I guess that's why loading the rest of the page i.e. all CSS artifacts is then aborted and you get the "unstylish" look.

@agjohnson is that an obvious problem you've seen before?

**Comment by cmungall** [comment]
not sure if this helps, but it looks like there is a giant blank spot in the head section of the HTML

```

<head>
--
  | <meta charset="utf-8">
  |  
  | <meta name="viewport" content="width=device-width, initial-scale=1.0">
  |  
  | <title>go-ontology 0.5 documentation</title>
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  |  
  | <link rel="index" title="Index"
  | href="genindex.html"/>
  | <link rel="search" title="Search" href="search.html"/>
  | <link rel="top" title="None" href="index.html#document-index"/>
  |  
  |  
  | <script src="_static/js/modernizr.min.js"></script>
  |  
  | </head>

```

**Comment by marcelstoer** [comment]
Oh, that'd be a more logical explanation why CSS artifacts are not loaded 🙁

**Comment by monicacecilia** [comment]
Thanks for your help @marcelstoer and @cmungall.

I changed the theme from 'default' to 'alabaster' in my configuration, and that blank space at the top went away. 

```
<head>
--
  | <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  |  
  | <title>GO Ontology 0.5 documentation</title>
  |  
  | <link rel="stylesheet" href="_static/alabaster.css" type="text/css" />
  | <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  |  
  | <script type="text/javascript">
  | var DOCUMENTATION_OPTIONS = {
  | URL_ROOT:    './',
  | VERSION:     '0.5',
  | COLLAPSE_INDEX: false,
  | FILE_SUFFIX: '.html',
  | HAS_SOURCE:  true,
  | SOURCELINK_SUFFIX: '.txt'
  | };
  | </script>
  | <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-2.0.3.min.js"></script>
  | <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-migrate-1.2.1.min.js"></script>
  | <script type="text/javascript" src="https://media.readthedocs.org/javascript/underscore.js"></script>
  | <script type="text/javascript" src="https://media.readthedocs.org/javascript/doctools.js"></script>
  | <script type="text/javascript" src="https://media.readthedocs.org/javascript/readthedocs-doc-embed.js"></script>
  | <link rel="index" title="Index" href="genindex.html" />
  | <link rel="search" title="Search" href="search.html" />
  |  
  | <link rel="stylesheet" href="_static/custom.css" type="text/css" />
  |  
  |  
  | <meta name="viewport" content="width=device-width, initial-scale=0.9, maximum-scale=0.9" />
  |  
  | </head>

```

Improvements to styling on the documentation pages are visible at http://ontologydocs.readthedocs.io/en/latest/

The reason behind that 404 with the default theme may remain a mystery.

**Comment by stsewd** [comment]
@monicacecilia  Hi, I can see that your docs look good now, are you still having this issue?

**Comment by stsewd** [comment]
@monicacecilia thanks for the update!
