### ISSUE TITLE
Error: An unexpected error occurred

### ISSUE THREAD

**Issue by tannerjfco** [rtfd/readthedocs.org#2985]
## Details

* Project URL: https://readthedocs.org/projects/ddev/
* Build URL (if applicable): https://readthedocs.org/projects/ddev/builds/5627279/ and many, many, many others before it. 
* Read the Docs username (if applicable): drud

We were initially getting build failures over a configuration issue. I believed to have resolved the configuration, but there's no way to tell with the error message provided. The build linked above is from a Version I added against a branch, which is rolled back to our last known good commit for readthedocs, so it should succeed. It fails, and at this point I don't seem to have any way to successfully build my docs.

## Expected Result

Either:

- The build succeeds
- The build fails, and provides me a useful error message that tells me something about the error and ideally how to resolve it.

## Actual Result

The build failed with the following: "Error: an unexpected error occurred". This error message gives me nothing to work with. I can't imagine its all that useful to a developer reading reports like this either. Searching the web for this issue is also useless, since every previous report is either a case that readthedocs devs identified as some problem that's reported as solved, or some user magically figuring out their issue was some configuration issue not relevant to my project.

**Comment by smsullivan** [comment]
Hitting this issue as well, but I just checked my latest public build and the updated docs are actually showing up correctly. So even though it is telling me I have a failed build (with the "unexpected error occurred" message), the docs are actually building and showing up. 

- Project URL: https://docs.readthedocs.io/en/latest/builds.html
- Build URL:  https://readthedocs.org/projects/lqmtoolset/builds/5630262/

**Comment by marcelstoer** [comment]
Dup of #2982

**Comment by mepi0011** [comment]
Get the same on my project.

[https://readthedocs.org/projects/openhabdoc/builds/5634911/](url)

**Comment by trpedersen** [comment]
I have the same problem; builds are reporting as failed, but the updated docs are being installed. It seems something fails after the 'Installing' step.

Example build URL: https://readthedocs.org/projects/uhack-guide/builds/5635512/
Project: https://readthedocs.org/projects/uhack-guide/

**Comment by MaslovaEV** [comment]
I have been facing this issue since the past week(( so the documentation on my project can not be updated...

**Comment by weitzman** [comment]
Sale here. Builds are showing new HTML but reporting as failed:

Example Build URL: https://readthedocs.org/projects/drush/builds/5646326/

**Comment by trpedersen** [comment]
I tried creating a new project (from the same source repo in Bitbucket), to no avail - builds still report 'unexpected error' but the HTML is built successfully.

Eg: https://readthedocs.org/projects/uhack-guide-2017/builds/

**Comment by byjg** [comment]
Mine project failed and the HTML document is not created. http://yaj.readthedocs.io/en/latest/

**Comment by MaslovaEV** [comment]
My project docs are failed with an undefined error https://readthedocs.org/projects/stream-juggler/builds/5651727/

**Comment by agjohnson** [comment]
I believe this is a problem with unicode that was introduced with either changes for py2/3 compatibility or recent changes to our file syncing code.

**Comment by agjohnson** [comment]
Yup, underlying it is an issue with YAML and unicode. Fix at #2998

**Comment by byjg** [comment]
Build still failing:

```
Build #5673116
latest (dbb7515474cb300bb884d318c084d12d9e41543b)
Build failed
Erro

An unexpected error occurred
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/yaj/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/yaj/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/yaj/.cache/pip sphinx==1.5.3 Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext<0.6 sphinx-rtd-theme<0.3 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0
python /home/docs/checkouts/readthedocs.org/user_builds/yaj/envs/latest/bin/mkdocs build --clean --site-dir _build/html --theme readthedocs

```

**Comment by martindevans** [comment]
I also have this problem.

Build: [https://readthedocs.org/projects/dissonance/builds/5688334/](https://readthedocs.org/projects/dissonance/builds/5688334/)
Docs: [https://dissonance.readthedocs.io/en/latest/](https://dissonance.readthedocs.io/en/latest/)

As others have said, the build reports a failure but the live version of the docs appears to be up to date.

**Comment by ethernomad** [comment]
https://readthedocs.org/projects/link-blockchain/builds/5713802/
```
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/link-blockchain/envs/latest
```
```
 New python executable in /home/docs/checkouts/readthedocs.org/user_builds/link-blockchain/envs/latest/bin/python2.7
Also creating executable in /home/docs/checkouts/readthedocs.org/user_builds/link-blockchain/envs/latest/bin/python
Installing setuptools, pip, wheel...done.
```

**Comment by smsullivan** [comment]
The issue seems to be resolved. My project started building successfully a day ago (7/20/2017) and it seems many of the projects here are building successfully as well now.

**Comment by hyt-hz** [comment]
same problem here, it only says "An unexpected error occurred", don't know what to do:

https://readthedocs.org/projects/ivr/builds/5749015/

**Comment by azhipaigor** [comment]
Same problem: "An unexpected error occurred"
Build: https://readthedocs.org/projects/diadocsdk-1c/builds/5852205/

**Comment by lwm** [comment]
Also seeing this one https://readthedocs.org/projects/stack/builds/5876544/.

**Comment by lwm** [comment]
Coming back to this, I see that we're both (the OP and I) complaining about this bad error message. Maybe I should just do something about fixing this myself instead of moaning :) Can any core dev seeing this perhaps point me in the right direction and I'd definitely take a stab at exposing the real error messages.

**Comment by agjohnson** [comment]
I addressed this a bit in #3073. A hotfix is out, folks can test their builds again to be sure.

**Comment by ericholscher** [comment]
This should be fixed, as this error was previously a generic one we threw, but now have fixed.

**Comment by lwm** [comment]
Thank you all!
