### ISSUE TITLE
Please change my username

### ISSUE THREAD

**Issue by td2014** [rtfd/readthedocs.org#2987]
## Details

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): anthonyd2004

## Expected Result

*A description of what you wanted to happen*
Please change my username:  
(from) anthonyd2004 
(to) td2014
## Actual Result

*A description of what actually happened*
Thanks.

**Comment by AwesomeTech10** [comment]
I thought this was possible from the user settings.

**Comment by td2014** [comment]
@AwesomeTech10  I've not been able to find that option - perhaps I'm looking the wrong spot, but it seems like everything else can be changed except the username of the account.  Thanks.

**Comment by safwanrahman** [comment]
@td2014 You can completely delete your account and create a new one
https://readthedocs.org/accounts/delete/
