### ISSUE TITLE
Conda environment fail due to to gcc link error

### ISSUE THREAD

**Issue by alen12345** [rtfd/readthedocs.org#2988]
## Details

* Project URL: https://github.com/alen12345/nonlinearHyperElasticity/tree/development
* Build URL (if applicable): https://readthedocs.org/projects/nonlinearhyperelasticity/builds/5636820/
* Read the Docs username (if applicable): alen12345

## Expected Result

I would except the conda environment to install correctly. This is my readthedocs.yml file: 
https://github.com/alen12345/nonlinearHyperElasticity/blob/development/readthedocs.yml

and here the environment.yml:
https://github.com/alen12345/nonlinearHyperElasticity/blob/development/environment.yml

## Actual Result

The build of the conda env fails with the following error message related to *gcc*:
`LinkError: post-link script failed for package defaults::gcc-4.8.5-7
running your command again with `-v` will provide additional information`

**Comment by brews** [comment]
Related?: https://github.com/ContinuumIO/anaconda-issues/issues/1392

**Comment by humitos** [comment]
Hi @alen12345! Are you still having this issue? It seems the project was deleted or something, right?

**Comment by alen12345** [comment]
Hello @humitos ! I am moving servers right now :) just give me a couple of days to relaunch the setup and report back an updated situation!

Thanks in advance for your kind interest!

**Comment by alen12345** [comment]
@humitos sorry for the very late reply! The project is back to public, and everything is passing smoothly now!!!

Thanks again for your interest"
