### ISSUE TITLE
Markdown Docs Builds seem to fail.

### ISSUE THREAD

**Issue by AwesomeTech10** [rtfd/readthedocs.org#2989]
## Details
For some reason, trying to do markdown builds fail. The site they should be uploaded to is https://nano-docs.readthedocs.io/en/latest/ which says "This is an auto generated index file" It should say 
"Nano Documentation
This is the official documentation for [Nano and ReIN], the makers of NeXT Gen Tech.
Contribute to the docs at BitBucket." But it doesn't. 

* Project URL:  rein.netau.net | nano-docs.readthedocs.io
* Build URL (if applicable): nano-docs.readthedocs.io (I don't know what the build URL is)
* Read the Docs username (if applicable): ReIN

## Expected Result

 It should say 
"Nano Documentation
This is the official documentation for [Nano and ReIN], the makers of NeXT Gen Tech.
Contribute to the docs at BitBucket." But it says 
Welcome to Read the Docs
This is an autogenerated index file.

Please create a /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/checkouts/latest/docs/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/checkouts/latest/docs/README.rst file with your own content.

If you want to use another markup, choose a different builder in your settings.

It also uses Sphinx when it should be using Mkdocs
## Actual Result

It says Welcome to Read the Docs
This is an autogenerated index file.

Please create a /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/checkouts/latest/docs/index.rst or /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/checkouts/latest/docs/README.rst file with your own content.

If you want to use another markup, choose a different builder in your settings.

It uses Sphinx when it should be using Mkdocs (Markdown)

## What the Build Did
Step 1: 
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest

New python executable in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/python2.7
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/python2.7)
Installing setuptools, pip, wheel...done.

Step 2: 
python /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/.cache/pip sphinx==1.5.3 Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mkdocs==0.15.0 mock==1.0.1 pillow==2.6.1 readthedocs-sphinx-ext<0.6 sphinx-rtd-theme<0.3 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0

Requirement already up-to-date: sphinx==1.5.3 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: Pygments==2.2.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: setuptools==28.8.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: docutils==0.13.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: mkdocs==0.15.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: mock==1.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: pillow==2.6.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: readthedocs-sphinx-ext<0.6 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: sphinx-rtd-theme<0.3 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: alabaster!=0.7.5,<0.8,>=0.7 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: commonmark==0.5.4 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: recommonmark==0.4.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: six>=1.5 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: requests>=2.0.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: babel!=2.0,>=1.3 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: Jinja2>=2.3 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Requirement already up-to-date: tornado>=4.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: click>=4.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: livereload>=2.3.2 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: mkdocs-bootstrap>=0.1.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: mkdocs-bootswatch>=0.1.0 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: PyYAML>=3.10 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: Markdown>=2.3.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from mkdocs==0.15.0)
Requirement already up-to-date: nilsimsa>=0.3.7 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from readthedocs-sphinx-ext<0.6)
Requirement already up-to-date: idna<2.6,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: urllib3<1.22,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: pytz>=0a in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from babel!=2.0,>=1.3->sphinx==1.5.3)
Requirement already up-to-date: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from Jinja2>=2.3->sphinx==1.5.3)
Requirement already up-to-date: singledispatch in /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/lib/python2.7/site-packages (from tornado>=4.1->mkdocs==0.15.0)
Requirement already up-to-date: backports-abc>=0.4 in /home/docs/checkouts/readthedocs.org/user_builds/

Step 3 (The step that fails):
python /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/mkdocs build --clean --site-dir _build/html --theme readthedocs

INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/docs/checkouts/readthedocs.org/user_builds/nano-docs/checkouts/latest/_build/html 
ERROR   -  Error building page index.md 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/__main__.py", line 137, in build_command
    ), clean_site_dir=clean)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 289, in build
    build_pages(config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 249, in build_pages
    dump_json)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 169, in _build_page
    site_navigation=site_navigation
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 35, in convert_markdown
    extension_configs=config['mdx_configs']
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/mkdocs/utils/__init__.py", line 337, in convert_markdown
    extension_configs=extension_configs or {}
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/docs/checkouts/readthedocs.org/user_builds/nano-docs/envs/latest/local/lib/python2.7/site-packages/markdown/__init__.py", line 264, in build_extension
    module = importlib.import_module(module_name_old_style)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: Failed loading extension 'pymdownx.superfences' from 'pymdownx.superfences', 'markdown.extensions.pymdownx.superfences' or 'mdx_pymdownx.superfences'
Command time: 1s Return: 1

I hope this helps!

-AwesomeTech10

**Comment by marcelstoer** [comment]
Possibly related to #2985 and thus also to #2982.

**Comment by agjohnson** [comment]
This is failing on a missing extension. Seems you need to install this as a dependency.

```
ImportError: Failed loading extension 'pymdownx.superfences' from 'pymdownx.superfences', 'markdown.extensions.pymdownx.superfences' or 'mdx_pymdownx.superfences'
Command time: 1s Return: 1
```
