### ISSUE TITLE
Project import sync UI doesn't update on failure

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#2993]
Something is up with the promise for updating the UI for syncing remote repositories. If the request returns a 500 response, the UI syncing element is still never updated and remains in a waiting state.

Raised with #2992

**Comment by agjohnson** [comment]
Closing as duplicate of #3273

**Comment by j-gooding** [comment]
This still an issue and not fixed in the current release.

**Comment by stsewd** [comment]
@j-gooding can you please open a new issue with more information about the problem you are facing?
