### ISSUE TITLE
Google Analytics verification for Google Webmaster Central

### ISSUE THREAD

**Issue by cheerfulstoic** [rtfd/readthedocs.org#3002]
## Details

* Project URL: http://neo4jrb.readthedocs.io/
* Build URL (if applicable): 
* Read the Docs username (if applicable): cheerfulstoic

## Hopefully informative history / explanation

I'd like to be able to link to my RTD documentation on a YouTube video that I made because there is some information in the video which is out of date.  In order to link to a website from a YouTube video, you apparently need to be able to prove that you are the webmaster.  There are various ways to do that, but they only one that I figured would work since my docs are generated via `rst` files is through Google Analytics verification.  I was able to add my GA code into my RTD admin page and after a day or so it started working (which is awesome, by the way.  That by itself is wonderful to have).  But when I try to verify the site via Google's Webmaster Central it won't verify.  On the page to verify it says the following:

```
* You must be using the asynchronous tracking code .
* Your tracking code should be in the <head> section of your page.
* You must have the "edit" permission for the Analytics web property.
```

I have the "edit" permission in Analytics, so I'm guessing perhaps one of the first two things isn't true.  I looked at the source of the docs page and I don't see anything about Google Analytics / `ga` in the source, so maybe the tracking is done via server side events?  Any insight help would be welcome.

Thanks for readthedocs, BTW!

**Comment by ItsPugle** [comment]
I don't know too much about how ReadTheDocs works with Analytics, but I'd think that your issue may lay with the `analytics.js` script not being in the `<head>` section of the site.

The asynchronous tracking code, as far as I know of, is a `UA-XXXXXXXX-X` format, `X` being a random number, so if your tracking code is in that format, that shouldn't be the issue. [Google Developers on Website Analytics](https://developers.google.com/analytics/devguides/collection/analyticsjs/) explains it all in more depth, but I'm not sure if that helps.

First attempt at helping with RTD.... Probably failed.
![I tried](https://media.giphy.com/media/tZpGRRMUoXgeQ/giphy.gif)

**Comment by ericholscher** [comment]
You're welcome to include GA in your own HTML with the normal Sphinx way of doing it. We also have a setting in the project `Admin > Advanced Settings` that outputs it on the page, along with ours.

**Comment by cheerfulstoic** [comment]
Thanks to both of you ;)

I set the "Analytics code" under the "Advanced Settings", but I didn't see it on the page.  But I'll try the Sphinx way of doing it (I hadn't thought of that).  Thanks!

**Comment by cheerfulstoic** [comment]
FYI for anybody coming along, I was able to get the GA code into the header by editing the `docs/_templates/layout.html` file.  See here:

https://github.com/neo4jrb/neo4j/blob/8.1.x/docs/_templates/layout.html
