### ISSUE TITLE
Deleting a project

### ISSUE THREAD

**Issue by ItsPugle** [rtfd/readthedocs.org#3007]
## Details

* Project URL: http://itspugle-demo.readthedocs.io/en/latest/
* Build URL (if applicable): Non-Applicaable
* Read the Docs username (if applicable): ItsPugle

Hey, rtfd Team,

I was just wondering how I was to go through with deleting this demo/test project?

Thanks,
ItsPugle

**Comment by willingc** [comment]
Hi @ItsPugle,

From the Project Page of your project, you should select the **Admin** tab. Under **Settings**, scroll to the bottom of the page and there will be a **Delete** link. Confirm and it will be deleted.

**Comment by willingc** [comment]
@agjohnson This issue can be closed as resolved.

**Comment by ItsPugle** [comment]
My golly, I should have seen that button! Hidden next to the submit button, you need to be a detective to see it ;)

I'll go through and close this :) Thanks for your help!
