### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by pbvarga1** [rtfd/readthedocs.org#3010]
## Details

* Project URL: https://github.com/planetarypy/pdsspect
* Build URL (if applicable): https://readthedocs.org/projects/pdsspect/builds/5718808/
* Read the Docs username (if applicable): pbvarga1

## Expected Result

*A description of what you wanted to happen*
Docs to build successfully or to fail with an error that clearly points to how I can fix the error

## Actual Result

*A description of what actually happened*
For the last couple weeks, my docs have been failing with this error:
```
libgcc_s.so.1 must be installed for pthread_cancel to work
Aborted
```
I can't figure out how to fix the problem from my end, seems like a linux configuration issue. Let me know if there is something I have to change! Thanks!

**Comment by willingc** [comment]
I'm assuming that you simply wish for the docs to build and that the docs do not necessarily depend on having a running installation of your package.

The suggestions that I made in this other issue may help you here: https://github.com/rtfd/readthedocs.org/issues/3013#issuecomment-317297733

Feel free to ask follow up questions.

**Comment by pbvarga1** [comment]
Not installing the package allows for the build to succeed but then the autodocs does not work correctly (the pages exist but there are no docs). Can I make autodocs work without an installation of my package?

**Comment by willingc** [comment]
Nope, autodocs will need to be installed. I've opened a PR on your repo that adds support for building successfully with conda.
