### ISSUE TITLE
local rtfd sphinx cannot support chinese search well

### ISSUE THREAD

**Issue by chilibreaker** [rtfd/readthedocs.org#3011]
## Details
Dear all,
         I have installed rtfd + sphinx locally but the chinese search function on sphinx do not work well.I use jieba Chinese text segmentation for the sphinx searching,but cannot search chinese sentence.
        And I find the sphinx chinese search function on projects from official website https://readthedocs.org/ work very well.I can search whole chinese sentence on those projects.
        I want to ask which Chinese text segmentation is used by official rtfd?

Really appreciate your help.Thanks.

**Comment by willingc** [comment]
Hi @chilibreaker,

The localization files are found here: https://github.com/rtfd/readthedocs.org/tree/master/readthedocs/locale/zh_CN

Search uses elasticsearch:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/search/views.py#L24

I hope this helps.

**Comment by chilibreaker** [comment]
Hi @willingc 
          Problem solved .
Thanks a lot~

**Comment by willingc** [comment]
@agjohnson @ericholscher This can be closed 👍

**Comment by kkpattern** [comment]
@chilibreaker Hi, can you tell me how you solved this problem? I set html_search_language to zh in conf.py but still have no Chinese search support.

**Comment by stsewd** [comment]
Closing this as the original issue was solved https://github.com/rtfd/readthedocs.org/issues/3011#issuecomment-318275371

@chilibreaker can you tell us how you solve the issue? Thanks!
