### ISSUE TITLE
PIL requirement cannot be satisfied during build

### ISSUE THREAD

**Issue by yarden** [rtfd/readthedocs.org#3013]
## Details

* Project URL:  http://miso.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/miso/builds/5723576/
* Read the Docs username (if applicable): yardenkatz

## Expected Result

Trying to build documentation as html.

## Actual Result

Documentation build failed because PIL requirement couldn't be satisfied:

```
python /home/docs/checkouts/readthedocs.org/user_builds/miso/envs/fastmiso/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/miso/.cache/pip -rdocs/REQUIREMENTS
Collecting PIL>=1.1.5 (from -r docs/REQUIREMENTS (line 1))
  Could not find a version that satisfies the requirement PIL>=1.1.5 (from -r docs/REQUIREMENTS (line 1)) (from versions: )
No matching distribution found for PIL>=1.1.5 (from -r docs/REQUIREMENTS (line 1))
```

I tried to remove all ":scale:" commands from documentation in the hope that it would then not require PIL at all, but that didn't work. I'd like to avoid having PIL as a requirement for my project because it's not at all used in the code.

Thank you.

**Comment by willingc** [comment]
Hi @yarden,

PIL is a fairly old package that doesn't have pip support (as far as I am aware). I would recommend using Pillow which is a maintained fork of PIL. https://pillow.readthedocs.io/en/latest/index.html

`Pillow>=4.0`

**Comment by yarden** [comment]
Hi @willingc - Thank you for your response. To clarify, I am not using PIL at all in my package; it's not part of the required packages in my ``setup.py``. Apparently, PIL is used by readthedocs to build the virtual environment in order to satisfy a requirement of docutils (that's my understanding based on [this](http://docs.readthedocs.io/en/latest/faq.html#image-scaling-doesn-t-work-in-my-documentation)). I don't want to include ``Pillow>=4.0`` in my project requirements because I am not using this package at all.

**Comment by willingc** [comment]
Hi @yarden, I looks like there's a file in your repo's doc directory (https://github.com/yarden/MISO/blob/fastmiso/docs/REQUIREMENTS) that has PIL included. I would try to remove this file since it looks as if this is being added to the build.

**Comment by yarden** [comment]
Thanks very much @willingc - not sure how that got in there. I removed the PIL requirement though now I get another error related to build that I cannot reproduce in normal installation of my packages (https://readthedocs.org/projects/miso/builds/5728937/) and that also seems to be related to the build environment of readthedocs: ``"ImportError: No module named numpy.distutils.core"``. Is there a way to get readthedocs to build only the documentation, without attempting to install the whole package? IIRC that's how it used to work. I use Travis CI and other services to automatically build the package and here my goal is mainly to build the documentation. Thanks very much.

**Comment by willingc** [comment]
Hi @yarden, I would recommend something similar to what we do in [JupyterHub's documentation](jupyterhub.readthedocs.io):

- At the repo root, add a `readthedocs.yml` file that tells RTD builder where to look for an `environment.yml` file for conda  or a `requirements.txt` if you prefer pip. Personally I find conda a bit simpler for building docs.
- In the docs, directory at the same level as the Makefile, add an `environment.yml` file which lists the dependencies that you need for only the docs (sphinx, theme,...).

Hope this helps. Feel free to ping with additional questions.

[jupyterhub's readthedocs.yml](https://github.com/jupyterhub/jupyterhub/blob/master/readthedocs.yml)

[jupyterhub's environment.yml](https://github.com/jupyterhub/jupyterhub/blob/master/docs/environment.yml)

To build docs, locally use the `environment.yml` to build a conda environment, activate the environment and run `make html`.

**Comment by yarden** [comment]
Hi @willingc - thank you so much for these pointers! That completely addresses all of the issues I had with the build. Thanks again!

**Comment by willingc** [comment]
Great! Glad it helped @yarden.
