### ISSUE TITLE
DMCA typo

### ISSUE THREAD

**Issue by ajhoekst** [rtfd/readthedocs.org#3015]
## Details
Apostrophe should not be used

* Project URL: docs/DMCA/index.rts

## Expected Result

Page should say "...which we appreciate for its focus..."

## Actual Result

Page currently says "...which we appreciate for it's focus..."

**Comment by stsewd** [comment]
This was fixed on #3017, already merged.

**Comment by RichardLitt** [comment]
Closing this, then. Thanks @ajhoekst!
