### ISSUE TITLE
Unable to find LAPACK/BLAS

### ISSUE THREAD

**Issue by stephenhky** [rtfd/readthedocs.org#3016]
## Details

* Project URL: https://github.com/stephenhky/PyShortTextCategorization
* Build URL (if applicable): docs/conf.py
* Read the Docs username (if applicable): 

## Expected Result

It should compile the document successfully.

## Actual Result

It cannot be built. According to readthedocs.org panel, it said:

`
running install
running bdist_egg
running egg_info
writing requirements to shorttext.egg-info/requires.txt
writing shorttext.egg-info/PKG-INFO
writing top-level names to shorttext.egg-info/top_level.txt
writing dependency_links to shorttext.egg-info/dependency_links.txt
reading manifest file 'shorttext.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'shorttext.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/shorttext
copying build/lib.linux-x86_64-2.7/shorttext/__init__.py -> build/bdist.linux-x86_64/egg/shorttext
creating build/bdist.linux-x86_64/egg/shorttext/classifiers
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/bow
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/maxent
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/maxent/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/maxent
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/maxent/MaxEntClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/maxent
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/topic/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/topic/TopicVectorDistanceClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/topic/SkLearnClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/bow/topic/LatentTopicModeling.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/embed
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/sumvec/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/sumvec/SumEmbedVecClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/sumvec/frameworks.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/sumvec/VarNNSumEmbedVecClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec
creating build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/nnlib/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/nnlib/frameworks.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib
copying build/lib.linux-x86_64-2.7/shorttext/classifiers/embed/nnlib/VarNNEmbedVecClassification.py -> build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib
copying build/lib.linux-x86_64-2.7/shorttext/smartload.py -> build/bdist.linux-x86_64/egg/shorttext
creating build/bdist.linux-x86_64/egg/shorttext/data
copying build/lib.linux-x86_64-2.7/shorttext/data/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/data
copying build/lib.linux-x86_64-2.7/shorttext/data/shorttext_exampledata.csv -> build/bdist.linux-x86_64/egg/shorttext/data
copying build/lib.linux-x86_64-2.7/shorttext/data/data_retrieval.py -> build/bdist.linux-x86_64/egg/shorttext/data
creating build/bdist.linux-x86_64/egg/shorttext/generators
copying build/lib.linux-x86_64-2.7/shorttext/generators/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/generators
creating build/bdist.linux-x86_64/egg/shorttext/generators/bow
copying build/lib.linux-x86_64-2.7/shorttext/generators/bow/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/generators/bow
copying build/lib.linux-x86_64-2.7/shorttext/generators/bow/AutoEncodingTopicModeling.py -> build/bdist.linux-x86_64/egg/shorttext/generators/bow
copying build/lib.linux-x86_64-2.7/shorttext/generators/bow/LatentTopicModeling.py -> build/bdist.linux-x86_64/egg/shorttext/generators/bow
copying build/lib.linux-x86_64-2.7/shorttext/generators/bow/GensimTopicModeling.py -> build/bdist.linux-x86_64/egg/shorttext/generators/bow
creating build/bdist.linux-x86_64/egg/shorttext/stack
copying build/lib.linux-x86_64-2.7/shorttext/stack/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/stack
copying build/lib.linux-x86_64-2.7/shorttext/stack/stacking.py -> build/bdist.linux-x86_64/egg/shorttext/stack
creating build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/__init__.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/compactmodel_io.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/gensim_corpora.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/wordembed.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/kerasmodel_io.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/stopwordset.pkl -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/deprecation.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/textpreprocessing.py -> build/bdist.linux-x86_64/egg/shorttext/utils
copying build/lib.linux-x86_64-2.7/shorttext/utils/classification_exceptions.py -> build/bdist.linux-x86_64/egg/shorttext/utils
byte-compiling build/bdist.linux-x86_64/egg/shorttext/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/maxent/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/maxent/MaxEntClassification.py to MaxEntClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic/TopicVectorDistanceClassification.py to TopicVectorDistanceClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic/SkLearnClassification.py to SkLearnClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/bow/topic/LatentTopicModeling.py to LatentTopicModeling.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec/SumEmbedVecClassification.py to SumEmbedVecClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec/frameworks.py to frameworks.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/sumvec/VarNNSumEmbedVecClassification.py to VarNNSumEmbedVecClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib/frameworks.py to frameworks.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/classifiers/embed/nnlib/VarNNEmbedVecClassification.py to VarNNEmbedVecClassification.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/smartload.py to smartload.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/data/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/data/data_retrieval.py to data_retrieval.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/generators/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/generators/bow/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/generators/bow/AutoEncodingTopicModeling.py to AutoEncodingTopicModeling.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/generators/bow/LatentTopicModeling.py to LatentTopicModeling.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/generators/bow/GensimTopicModeling.py to GensimTopicModeling.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/stack/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/stack/stacking.py to stacking.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/compactmodel_io.py to compactmodel_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/gensim_corpora.py to gensim_corpora.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/wordembed.py to wordembed.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/kerasmodel_io.py to kerasmodel_io.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/deprecation.py to deprecation.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/textpreprocessing.py to textpreprocessing.pyc
byte-compiling build/bdist.linux-x86_64/egg/shorttext/utils/classification_exceptions.py to classification_exceptions.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/ShortTextCategorizerConsole -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/switch_kerasbackend -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/ShortTextWord2VecSimilarity -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/ShortTextCategorizerConsole to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/switch_kerasbackend to 755
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/ShortTextWord2VecSimilarity to 755
copying shorttext.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shorttext.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shorttext.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shorttext.egg-info/not-zip-safe -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shorttext.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying shorttext.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
creating 'dist/shorttext-0.4.0-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing shorttext-0.4.0-py2.7.egg
removing '/home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/lib/python2.7/site-packages/shorttext-0.4.0-py2.7.egg' (and everything under it)
creating /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/lib/python2.7/site-packages/shorttext-0.4.0-py2.7.egg
Extracting shorttext-0.4.0-py2.7.egg to /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/lib/python2.7/site-packages
shorttext 0.4.0 is already the active version in easy-install.pth
Installing ShortTextCategorizerConsole script to /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/bin
Installing switch_kerasbackend script to /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/bin
Installing ShortTextWord2VecSimilarity script to /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/bin

Installed /home/docs/checkouts/readthedocs.org/user_builds/shorttext/envs/latest/lib/python2.7/site-packages/shorttext-0.4.0-py2.7.egg
Processing dependencies for shorttext==0.4.0
Searching for scipy>=0.18.1
Reading https://pypi.python.org/simple/scipy/
Downloading https://pypi.python.org/packages/52/67/d9ef9b5058d4a9e3f0ae641ec151790622cbeb37f157de5773358e2bf3da/scipy-0.19.1.tar.gz#md5=6b4d91b62f1926282b127194a06b72b3
Best match: scipy 0.19.1
Processing scipy-0.19.1.tar.gz
Writing /tmp/easy_install-gsUxmC/scipy-0.19.1/setup.cfg
Running scipy-0.19.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-gsUxmC/scipy-0.19.1/egg-dist-tmp-Mc_VSN
/tmp/easy_install-gsUxmC/scipy-0.19.1/setup.py:323: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
  warnings.warn("Unrecognized setuptools command, proceeding with "
/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1542: UserWarning: 
    Atlas (http://math-atlas.sourceforge.net/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [atlas]) or by setting
    the ATLAS environment variable.
  warnings.warn(AtlasNotFoundError.__doc__)
/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1553: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) libraries not found.
    Directories to search for the libraries can be specified in the
    numpy/distutils/site.cfg file (section [lapack]) or by setting
    the LAPACK environment variable.
  warnings.warn(LapackNotFoundError.__doc__)
/usr/lib/python2.7/dist-packages/numpy/distutils/system_info.py:1556: UserWarning: 
    Lapack (http://www.netlib.org/lapack/) sources not found.
    Directories to search for the sources can be specified in the
    numpy/distutils/site.cfg file (section [lapack_src]) or by setting
    the LAPACK_SRC environment variable.
  warnings.warn(LapackSrcNotFoundError.__doc__)
Running from scipy source directory.
non-existing path in 'scipy/integrate': 'quadpack.h'
error: no lapack/blas resources found
Command time: 3s Return: 1
`

However, I have no control how to install lapack/blas on readthedocs.org

**Comment by humitos** [comment]
Hi @stephenhky! The FAQ section has a solution for this http://docs.readthedocs.io/en/latest/faq.html?#i-get-import-errors-on-libraries-that-depend-on-c-modules

Hope it helps.
