### ISSUE TITLE
sanskrit-data build failing with unclear error 

### ISSUE THREAD

**Issue by vvasuki** [rtfd/readthedocs.org#3021]
## Details

* Project URL: https://readthedocs.org/projects/sanskrit-data
* Build URL (if applicable): https://readthedocs.org/projects/sanskrit-data/builds/5771077/
* Read the Docs username (if applicable): vishvasv

On my computer, I can run `make html` and see the docs generated just fine. But on readthedocs, I see a strange error (please see url above). I am new to sphynx and readthedocs, and would appreciate pointers to slack/ gitter chat or other such support avenues.

**Comment by humitos** [comment]
Hi @vvasuki! It seems that you were able to solve your issue. I'm closing this one. Please feel free to reopen it if you consider. Thanks
