### ISSUE TITLE
Markup bug in the emails

### ISSUE THREAD

**Issue by bzick** [rtfd/readthedocs.org#3022]
## Details

Click to recover password

## Expected Result

No bugs

## Actual Result

Has a bug:
![Markup bug](https://user-images.githubusercontent.com/22669894/29493018-50c7b87c-85d0-11e7-98e2-ef3b0e2d3650.png)

**Comment by ItsPugle** [comment]
Just so you're aware, I've put a block over your key to protect your account. I've also added some relevant labels. Thanks for the report!

**Comment by ericholscher** [comment]
This should be fixed. 🎆
