### ISSUE TITLE
Why is pip install called with --ignore-installed

### ISSUE THREAD

**Issue by cpaulik** [rtfd/readthedocs.org#3025]
This makes it hard to prepare an environment with conda and have pip packages with C dependencies in the requirements.txt

## Details

* Project URL: https://github.com/TUW-GEO/gldas
* Build URL (if applicable): https://readthedocs.org/projects/gldas/builds/5774270/
* Read the Docs username (if applicable): cpaulik

## Expected Result

pygrib should not be installed with pip since it is already installed via conda

## Actual Result

pygrib installation failed because of missing system libraries for compiling the c code.

**Comment by cpaulik** [comment]
I worked around it by using `python setup.py install` instead.

**Comment by goerz** [comment]
Using `setup_py_install: true` and `pip_install: false` in `readthedocs.yml` works, but it requires that the conda environment file lists *all* dependency packages that should be installed through pip. As an example:

~~~
name: py36
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - anaconda
  - pytest-cov
  - pytest-xdist
  - coverage
  - pip:
      - better-apidoc
      - trajectorydata
      - sphinx-autobuild
      - git+https://github.com/mabuchilab/QNET.git@develop#egg=QNET-2.0.0-dev
~~~

**Comment by agjohnson** [comment]
This seems it can be closed. Our yaml config might soon have more options to configure these steps, but currently this case is a bit of an edge case.
