### ISSUE TITLE
Support `--upgrade` flag for `pip` installs

### ISSUE THREAD

**Issue by wmayner** [rtfd/readthedocs.org#3027]
## Details

I'm using my own fork of `sphinx_rtd_theme`, but since the upstream version has already been installed by the time the project-specific requirements are installed, my fork is ignored because `pip` thinks that `sphinx_rtd_theme` is up-to-date.

This could be fixed by:
1. Keeping my fork's version higher than the upstream;
2. Giving it a different name;
3. Putting my fork directly in the project repository via *e.g.* `git subtree`;
4. Passing the `--upgrade` flag to the project-specific `pip install`.

(1) seems like a hack; (2) is also a hack; (3) is inelegant, since the theme already has a nice way of being required as a dependency, and subtrees are a pain anyway. So (4) seems like the best option, unless it would lead to problems on the RTD side.

Happy to submit a PR if this seems like a reasonable idea (pointing me to the relevant sections of the code would be helpful—I think it's [`readthedocs/doc_builder/python_environments.py`](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py)?)

* Project URL: https://pyphi.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/pyphi/builds/5775564/
* Read the Docs username (if applicable): wmayner

**Comment by stsewd** [comment]
I think this was already solved here #3201

**Comment by stsewd** [comment]
This issue was already solved on #3201 (merged) as a continuation of #3077
