### ISSUE TITLE
Build success, but no functions be listed

### ISSUE THREAD

**Issue by zsdonghao** [rtfd/readthedocs.org#3029]
## Details

* Project URL: http://tensorlayer.readthedocs.io/en/latest/modules/iterate.html
* Build URL (if applicable): https://github.com/zsdonghao/tensorlayer
* Read the Docs username (if applicable): zsdh123

## Expected Result

All functions should be able to list on the website.

## Actual Result

In the pass few days, when I change something, the RTD can still be built, but the functions cannot be listed on the website. If I change it back, functions can be listed...

Sometime, the functions will come back automatically if I click build more...

here is my commits: https://github.com/zsdonghao/tensorlayer/commits/master

Many thanks in advance ~

**Comment by humitos** [comment]
Hi @zsdonghao! The latest build of your docs seems to be working properly, right?

If yes, can you close this issue? If not, can you provide more info? Thanks!

**Comment by zsdonghao** [comment]
@humitos yeah, it works again without any modification , i have no idea about the reason ~~ 

Thanks,
