### ISSUE TITLE
Following the tutorial results in a failed build

### ISSUE THREAD

**Issue by egel-lang** [rtfd/readthedocs.org#3030]
## Details

I followed the video tutorial, pip installed sphinx, ran sphinx-quickstart, uploaded to github, installed the github hook on readthedocs. The result is a failed build.

* Project URL: http://egel.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/egel/builds/5783020/
* Read the Docs username (if applicable): egel-lang

## Expected Result

A vanilla website.

## Actual Result

Failed build.

**Comment by stsewd** [comment]
I just seen your latest builds are successful, were you able to solve the problem?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
