### ISSUE TITLE
Lino build is getting killed

### ISSUE THREAD

**Issue by lsaffre** [rtfd/readthedocs.org#3031]
## Details

* Project URL: https://readthedocs.org/projects/lino/
* Build URL (if applicable): https://readthedocs.org/projects/lino/builds/5783388/
* Read the Docs username (if applicable): lsaffre

Some weeks ago my builds of the Lino docs started to fail without a real error message, just the word "Killed". I publish the same doctree at http://www.lino-framework.org/ and on my machine that build takes a few minutes. Is there anything I can do to get it passing on RTD?

**Comment by stsewd** [comment]
Well, the original problem seems that was resolved, (I believe it was because of memory limits), now your builds seem to fail because of this dependency https://pypi.python.org/pypi/requests-mock

**Comment by lsaffre** [comment]
Yes, the memory limit is fixed. That other problem is of course mine and not yours.
