### ISSUE TITLE
Viewing xlrd project's docs shows maze page

### ISSUE THREAD

**Issue by chunkytrunk** [rtfd/readthedocs.org#3034]
## Details

* Project URL: https://github.com/python-excel/xlrd
* Build URL (if applicable): ?
* Read the Docs username (if applicable): n/a

## Expected Result

http://xlrd.readthedocs.io/en/latest/ should show the documentation for xlrd

## Actual Result

Shows a maze page.

@cjw296 sent me here since there seemed no problem on the project's side.

**Comment by cjw296** [comment]
Works for me, so not sure why @chunkytrunk is seeing this.

**Comment by chunkytrunk** [comment]
I can confirm this is not happening on my home system, just verified this. I can't really tell from where my requests are actually coming when at work since I'm forced to use a proxy here.

**Comment by jkyeung** [comment]
I also see a maze page when trying to view from work. I haven't tried at home, but where I need to see the docs is at work!

**Comment by cjw296** [comment]
I've tried kicking off a rebuild of `latest` and `stable` on RTD, let me know if it makes a difference...

**Comment by hbast** [comment]
working again! Thx!

**Comment by chunkytrunk** [comment]
Same here - thanks!

**Comment by cjw296** [comment]
@chunkytrunk - please can you re-open as this doesn't appear to be fixed: https://github.com/python-excel/xlrd/issues/229

**Comment by chunkytrunk** [comment]
Still seems fixed for me, but that can change any minute. Reopened as requested.

**Comment by cjw296** [comment]
@chunkytrunk - I've opened #3109 too, so I can track them all.
