### ISSUE TITLE
{% trans "Text in password reset email is not correctly translated" %}

### ISSUE THREAD

**Issue by HactarCE** [rtfd/readthedocs.org#3036]
I entered my email address into [this page](https://readthedocs.org/accounts/password/reset/) to reset my password, and everything worked as expected, except that the email contained some strange text which I assume was supposed to be translated into English for me, but unfortunately remained in what I believe to be Jekyllspeak:

![{% trans "A request has been made to reset your Read the Docs password. To confirm this reset request, please go to:" %}](https://i.imgur.com/0xOvF7X.png)

Due to my expertise in parsing Jekyllspeak, thankfully I was able to successfully reset my password.

Also it says "**you** password" instead of "**your** password" in the lower paragraph.

**Comment by ericholscher** [comment]
Thanks for the report -- this would be a great thing to fix with a pull request!
