### ISSUE TITLE
irreproducible import errors

### ISSUE THREAD

**Issue by kklmn** [rtfd/readthedocs.org#3037]
* Project URL: github.com/kklmn/xrt
* Build URL (if applicable): xrt.readthedocs.io/
* Read the Docs username (if applicable): konstantin.klementiev

Hello,

My doc builds are sometimes unsuccessful, with the import errors listed below. Most frequently this can be solved by manually triggering a new build (notice: without any change in the sources). Is there a way to make the build more reliable?

Thanks!

*** from the build log : ***

/home/docs/checkouts/readthedocs.org/user_builds/xrt/checkouts/latest/doc/index.rst:28: WARNING: autodoc: failed to import module 'xrt.xrtQook.xrtQook'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/xrt/envs/latest/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 176, in <module>
    from PySide import QtCore, QtGui, __version__, __version_info__
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../xrt/xrtQook/__init__.py", line 160, in <module>
    from matplotlib.backends import qt_compat
  File "/home/docs/checkouts/readthedocs.org/user_builds/xrt/envs/latest/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 179, in <module>
    "Matplotlib qt-based backends require an external PyQt4, PyQt5,\n"
ImportError: Matplotlib qt-based backends require an external PyQt4, PyQt5,
or PySide package to be installed, but it was not found.

*** end from the build log : ***

**Comment by humitos** [comment]
Hi @kklmn! Are you still having this issue?

It seems that your builds have been working for more than a month so I'm closing this issue since it seems that isse has been solved. Feel free to reopen it. Thanks!
