### ISSUE TITLE
Stable Build is Stuck on Old Branch

### ISSUE THREAD

**Issue by aklawren** [rtfd/readthedocs.org#3041]
## Details
I'm working on a locally hosted instance of Read The Docs with projects hosted in GitLab. For a couple of projects, the `stable` builds are stuck on an old *branch* (whereas typically `stable` stays up-to-date with the highest sequence *tag*). 

Originally, this seemed like a project specific glitch, but it appears `stable` is pinned to the `16R` branch for all the projects which contain that specific branch name.  

Below are the attempts made so far to try and get the projects updating as expected, with no luck:
   - Restarting the server
   - Updating the stable Identifier in the Django project dashboard
   - Deleting and re-creating the project from the Django admin dashboard
   - Removing the 16R tag from the repo

## Expected Result
I would expect that the stable build would remain in sync with the highest sequence git tag (similar to the behavior of other projects -- as shown below).
![screen shot 2017-08-10 at 10 45 07 am](https://user-images.githubusercontent.com/5193596/29183870-0d93afc6-7db9-11e7-802a-8219b74e6b8a.png)

## Actual Result 
The stable build version is stuck on the `16R` branch (shown below). 
![screen shot 2017-08-10 at 10 42 35 am](https://user-images.githubusercontent.com/5193596/29183787-c6ea60c4-7db8-11e7-80d6-a44cbde6b5c5.png)

**Comment by stsewd** [comment]
I think this is the same bug described in #3887. The current solution is recreating the project (the same name can be used)

**Comment by stsewd** [comment]
@aklawren in case you are interested, the fix for this bug was already deployed, can you test if that really solves your problem? (you may need to wipe and rebuild another version).

You may need to do some additional steps if that doesn't work https://github.com/rtfd/readthedocs.org/pull/3913#issuecomment-389228733
