### ISSUE TITLE
Double build on Bitbucket incoming webhook

### ISSUE THREAD

**Issue by petarmaric** [rtfd/readthedocs.org#3043]
## Details

* Project URL: https://readthedocs.org/projects/mir-spec/
* Build URL (if applicable): https://readthedocs.org/projects/mir-spec/builds/
* Read the Docs username (if applicable): petar.maric

Also checked the Bitbucket project configuration, only a single RTD related webhook is present.

## Expected Result

A RTD build is triggered on a Bitbucket incoming webhook.

## Actual Result

Two RTD builds are triggered on a Bitbucket incoming webhook.

**Comment by guillochon** [comment]
I have the same problem, but with GitHub. Not sure what else to try!

**Comment by stsewd** [comment]
@petarmaric @guillochon are you still having this issue?

**Comment by petarmaric** [comment]
I can't really say, as my project hasn't had any builds recently.

**Comment by stsewd** [comment]
@petarmaric @guillochon can you try this https://github.com/rtfd/readthedocs.org/issues/3255#issuecomment-373564346?

**Comment by guillochon** [comment]
Yep that looks like the fix! Thanks @stsewd!

**Comment by petarmaric** [comment]
Sorry @stsewd, I can't test it as my project hasn't had any builds recently.

**Comment by agjohnson** [comment]
Closing for now then, sounds like this is a configuration issue with GitHub/Bitbucket webhooks, not RTD.

@petarmaric feel free to reopen if you are still noticing the issue once you commit to your repo
