### ISSUE TITLE
GitHub integration broken on my haypo-notes project

### ISSUE THREAD

**Issue by vstinner** [rtfd/readthedocs.org#3044]
## Details

* Project URL: http://haypo-notes.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): haypo

## Expected Result

Pushing a commit to GitHub should trigger a documentation build.

## Actual Result

No build is triggered. I have to trigger the build manually.

The Integration page of my project has a GitHub item which says:

This integration was created automatically from an existing webhook configured on your repository. To make any changes to this webhook, you'll need to update the configuration there. You can use the following address to manually configure this webhook.

readthedocs.org/api/v2/webhook/haypo-notes/12118/

For more information on manually configuring a webhook, refer to our webhook documentation 

--

I tried to remove the ReadTheDocs service from my GitHub project to recreate it, multiple times, but it didn't work.

I also removed and recreated the ReadTheDocs project, multiple times, and it didn't work.

Previously, I had a red warning about the GitHub integration on ReadTheDocs, but sadly it's now gone, so I cannot copy/paste the message anymore.

**Comment by haypo** [comment]
I just pushed a dummy change just to test the integration:

* https://github.com/haypo/haypo_notes/commit/2a19c8a2f626595d5708cb8780bbde7f9b4e8c7b
* https://readthedocs.org/projects/haypo-notes/builds/ has no new build for this commit
* http://haypo-notes.readthedocs.io/cpython.html#embedded-libraries still contains the old doc

**Comment by stsewd** [comment]
Are you still having this problem? All the links are 404.

**Comment by vstinner** [comment]
Oh. I changed the name of my project from haypo-notes to vstinner. I created a new project when I renamed the GitHub repositry. And GitHub now notify properly ReadTheDocs. Thanks!

**Comment by vstinner** [comment]
FYI my new website: http://vstinner.readthedocs.io/
