### ISSUE TITLE
Fix Django 1.10 deprecation notices

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3046]
Here's all the deprecation notices we get when running against the python3.6 test suite:
https://gist.github.com/agjohnson/078be096d51dbe5921d4f81f1dae8dbe

List of applications that need attention:
- [ ] api
- [ ] bookmarks
- [ ] cdn
- [ ] comments
- [ ] donate
- [ ] gold
- [ ] notifications
- [ ] oauth
- [ ] payments
- [ ] profiles
- [ ] redirects
- [ ] restapi
- [ ] rtd_tests
- [ ] search
- [ ] settings
- [ ] static
- [ ] tastyapi
- [ ] templates
- [ ] vcs_support

More difficult issues to look at:
- [ ] doc_builder
- [ ] projects
- [ ] core
- [ ] builds

**Comment by jColeChanged** [comment]
I'm looking at core.

**Comment by jColeChanged** [comment]
I completed the warnings for py27 django 1.10 dep warnings for core. It turned out to be only spitting out warning for urls.subdomains

**Comment by ginstrom** [comment]
Completed for restapi

**Comment by humitos** [comment]
I'm clossing this issue in favor of https://github.com/rtfd/readthedocs.org/pull/3372

There are just two warnings missing but they are because third party libs.
