### ISSUE TITLE
kuma builds failing: "Error: An unexpected error occurred", no further info

### ISSUE THREAD

**Issue by jwhitlock** [rtfd/readthedocs.org#3050]
## Details

* Project URL: https://readthedocs.org/projects/kuma/
* Build URL (if applicable): https://readthedocs.org/projects/kuma/builds/5848952/, https://readthedocs.org/projects/kuma/builds/
* Read the Docs username (if applicable): jwhitlock

## Expected Result

A build, or some indication of what the issue was.

## Actual Result

The build fails with "Error: An unexpected error occurred", and no indication of what step the project was on when it failed.

**Comment by jwhitlock** [comment]
3 of the [last 15 builds](https://readthedocs.org/projects/kuma/builds/) have succeeded. There's no relevant changes to our docs, and we're seeing some docs now that were added a couple of weeks ago.  [Build 5896563](https://readthedocs.org/projects/kuma/builds/5896563/) is the most recent success. The failures, like [build 5899555](https://readthedocs.org/projects/kuma/builds/5899555/), have no useful feedback data.

The git checkout isn't in the successful build output, so it may be part of the pre-build and failing. We recently migrated our locale data to a submodule (https://github.com/mozilla/kuma/pull/4338), so this change may have an impact on the checkout operation.

**Comment by agjohnson** [comment]
Though I'm not exactly certain why the problem is seemingly non-deterministic, I believe I've addressed this issue with #3073.

**Comment by safwanrahman** [comment]
As the most of the build is passing, I think this is fixed by the patch addressed in #3073

**Comment by jwhitlock** [comment]
Builds are reliable again, thanks for the fix!
