### ISSUE TITLE
Update django project structure to post 1.4

### ISSUE THREAD

**Issue by megwill4268** [rtfd/readthedocs.org#3056]
## Details

Read the docs code project structure should be updated to the latest project structure. Particular issue pushing this is celery import conflict in upgrade from 3 to 4

## Expected Result

http://django-project-skeleton.readthedocs.io/en/latest/structure.html

## Actual Result

Using old style django project structure.

**Comment by humitos** [comment]
Hi @megwill4268! I think this issue stays here for too long and the codebase has changed since then. We are using celery 4 at the moment and it seems that the structure is descrived as the link you mentioned.

I'm closing this issue, fee free to reopen it if you consider. Thanks!
