### ISSUE TITLE
Mixup of two projects

### ISSUE THREAD

**Issue by chriseth** [rtfd/readthedocs.org#3061]
## Details

* Project URL: https://readthedocs.org/projects/solidity
* Build URL (if applicable): https://solidity.readthedocs.io/en/develop/
* Read the Docs username (if applicable):  chriseth

## Expected Result

All links in the "sidebar" of https://solidity.readthedocs.io/en/develop/ and the search results should link to sub-pages of https://solidity.readthedocs.io/en/develop/

## Actual Result

Some links go to http://solidity-482solution.readthedocs.io, for example the version links in the sidebar go to http://solidity-482solution.readthedocs.io/en/v0.4.15/ and search results as seen on https://solidity.readthedocs.io/en/develop/search.html?q=events&check_keywords=yes&area=default go to http://solidity-482solution.readthedocs.io/en/develop/structure-of-a-contract.html?highlight=events

This could be security critical as users might not notice the change of the domain.

**Comment by chriseth** [comment]
@axic just realized that the other project - solidity-482solution has a russian language setting while solidity.readthedocs.io only has "en" and "zh" and this russian translation is somehow mixed into solidity.readthedocs.io

**Comment by stsewd** [comment]
Are you still having this issue? I checked all the links you mention, and everything is ok.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Comment by stsewd** [comment]
@chriseth thanks for the update :)
