### ISSUE TITLE
Build failed: An unexpected error occurred

### ISSUE THREAD

**Issue by rtmclay** [rtfd/readthedocs.org#3064]
## Details

* Project URL: lmod.readthedocs.io 
* Build URL (if applicable):Build #5874517
                                          latest (5ceb383a1b1666b6c5d37df98881d29054c665e0)
* Read the Docs username (if applicable): rtmclay

## Expected Result

build or return some error message.

## Actual Result
I get: "Build failed: An unexpected error occurred"

This appears to be the same error as issue #3050 

I am guessing that it is cloning error.  Yet I can to do:

   $ git clone http://github.com/TACC/Lmod

easily and repeatedly.

**Comment by rtmclay** [comment]
This failure happens repeatedly.  Current there are 11 failures and 4 passes.  I have requested a build of the exact same release and have it fail 20 or 30 times before having a pass.  Thanks for looking at this problem.

**Comment by agjohnson** [comment]
I addressed this in #3073. You should test your builds to see if this resolved the error.

**Comment by rtmclay** [comment]
It is now working for me.  Thanks!
