### ISSUE TITLE
Internal Server Error when manually importing a project

### ISSUE THREAD

**Issue by deshipu** [rtfd/readthedocs.org#3066]
## Details

* Project URL: https://bitbucket.org/thesheep/pewpew
* Build URL (if applicable):
* Read the Docs username (if applicable): sheep

## Expected Result

The project gets imported and appears in my list.

## Actual Result

An empty page with huge "Internal Server Error" on it, and the name I used is no longer available.

I can reproduce this any time: I go to https://readthedocs.org/dashboard/import/manual/ and I enter the project name, the url: https://bitbucket.org/thesheep/pewpew and select "mercurial" as the repository type. When I click "Next" I get "Internal Server Error" and the name I've chosen is no longer free, however, the new project is not getting added.

**Comment by deshipu** [comment]
Update: I just saw that the projects *do* appear on my project list.

**Comment by stsewd** [comment]
Are you still having this issue?
I tested on my local instance and get the appropriate error message

>  Invalid project name, a project already exists with that name

**Comment by deshipu** [comment]
I didn't create any new projects recently, so I can't really tell. As I mentioned, the projects actually get created, so I didn't need to repeat this.

**Comment by RichardLitt** [comment]
Ok. Let's close this; if someone else has this issue, we can reopen it.
