### ISSUE TITLE
Change Python environment default to 3

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#3070]
Python 2 is going to stop being maintained in less than 3 years. We should switch our default Python version for projects to Python 3, as this should increase the number of python 3 projects being built on RTD by a large number. It's just a small settings change, but putting it here for discussion.

**Comment by ericholscher** [comment]
The code to be changed is here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L200

**Comment by Naereen** [comment]
Hi,
Is it planned soon to support Python 3.6 by default?
3.7 is already the new default version, but apparently RTD (still) builds with 3.5.
Thanks.

**Comment by stsewd** [comment]
@Naereen python 3.6 is already supported, you need to use a configuration file https://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by humitos** [comment]
@ericholscher I think we can do this now. I wonder if we need to create a date Feature flag for this, so only new projects start building with `python3` instead of forcing all the projects that were already building with `python2` to migrate. What do you think?

**Comment by humitos** [comment]
Oh, I got confused. By changing the `default=` attribute in the model we already get what I was proposing with the Feature flag :)

**Comment by Naereen** [comment]
> @Naereen python 3.6 is already supported, you need to use a configuration file https://docs.readthedocs.io/en/latest/yaml-config.html

Hi! I'm quite curious, I though python 3.6 was supported, but for instance [this build](https://readthedocs.org/projects/smpybandits/builds/8126289/) tried to use `python.version: 3.6` in my YAML file, and failed instantly.
See #4918

**Comment by stsewd** [comment]
It's supported, please see https://docs.readthedocs.io/en/latest/yaml-config.html#python-version

> The supported Python versions depends on the version of the build image your project is using. 

You need

```yaml
build:
  image: latest
```

**Comment by Naereen** [comment]
Oh, OK. Sorry I (still) didn't understand this point. Thanks!
My [latest build](https://readthedocs.org/projects/smpybandits/builds/8127151/) is working, thanks a lot!

**Comment by stsewd** [comment]
We use docker images to encapsulate the build process, each docker image has different python versions, and libs, here is the list https://docs.readthedocs.io/en/latest/builds.html#the-build-environment. Using latest is recommendable.

**Comment by impredicative** [comment]
Is there any reason why 3.6 isn't the default?

**Comment by humitos** [comment]
> Is there any reason why 3.6 isn't currently the default?

Just legacy code. We are upgrading it to make this to happen soon.
