### ISSUE TITLE
Build failing most of the time

### ISSUE THREAD

**Issue by trasher** [rtfd/readthedocs.org#3073]
## Details

* Project URL: http://glpi-user-documentation.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/glpi-user-documentation/builds/5899456/
* Read the Docs username (if applicable): trasher

## Expected Result

Doc get built ;)

## Actual Result

Most of the time, the build fails with "An unexpected error occurred". It's just a rst/md doc with a customized template; nothing really special; no code, ...

**Comment by agjohnson** [comment]
The error here was a unicode error during setup. This will likely need some local debugging to pinpoint

**Comment by trasher** [comment]
Let me know if I can help... All that I can tell you actually is that the docs build locally; with sphinx 2.2.11

**Comment by trasher** [comment]
I think I've found the cause of the issue... This seems to bre related to the MD part of the doc. I've just disabled `recommonmark.parser`; and now, the docs builds fine.

After check, I can see a warning locally when it is enabled:
```
/usr/lib64/python2.7/urllib.py:1299: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  return ''.join(map(quoter, s))
/usr/lib/python2.7/site-packages/recommonmark/parser.py:55: UserWarning: Container node skipped: type=document
  warn("Container node skipped: type={0}".format(mdnode.t))
```

Our doc was previously in MD, I'm migrating to RST; disabling the module is not a big issue. Anyways, I'd expect rtfd not to fail without message :)

Hope that helps.

**Comment by trasher** [comment]
Finally... This does not solve the issue. The commit on which I've disabled the module has been built; but this is failing again now.

**Comment by julienmalard** [comment]
I have the same problem with two repositories. Here is an example from the Tiko'n repository:
https://readthedocs.org/projects/tikon/builds/5945523/

Interestingly, occasionaly the builds will work on a translation of the same project (but not replicably so-- a few days ago the "Urdu" translation (actually still in Spanish) was working, but now the Tamil translation is working instead):
Tamil version logs:
https://readthedocs.org/projects/tikon-ta/builds/

Urdu version logs:
https://readthedocs.org/projects/tikon-ur/builds/

**Comment by agjohnson** [comment]
Okay, I finally found the source of this. This was a bug with our celery builder where the locale was not being picked up correctly. The result was any use of `os.walk` threw an exception when encountering a utf8 codepoint on a filename. We used `os.walk` in a few places. I'm not entirely sure why this presented as non-deterministic however. A few folks noticed the builds randomly failing.

I just did a deploy of the fix today, and I successfully rebuilt your project @trasher.

**Comment by agjohnson** [comment]
Same for you @julienmalard -- builds for your project are getting past the initial failure.

**Comment by julienmalard** [comment]
Many thanks @agjohnson! It works now.

**Comment by borsboom** [comment]
Yes, works for me as well!

**Comment by trasher** [comment]
Hello @agjohnson ;

Seems like this is fixed now; thank you very much!
