### ISSUE TITLE
Conda packages for Linux not found, because custom packages built on macOS

### ISSUE THREAD

**Issue by jkroes** [rtfd/readthedocs.org#3075]
## Details

* Project URL: https://github.com/jkroes/PersonalTutorials
* Read the Docs username (if applicable): jkroes

## Expected Result

RTFD builds the documents using the conda and pip packages specified in environment.yml, which is a mix of defaults, conda-forge, and custom-built osx64 packages on my own channel. 

Why is it looking for Linux packages? I'm new to RTFD but couldn't find proper documentation on using conda with RTFD.

## Actual Result

Fetching package metadata ...........

NoPackagesFoundError: Package missing in current linux-64 channels: 
  - sphinx-autorun 1.1.0 py36h5809654_0

**Comment by jkroes** [comment]
I guess all I had to do to bypass these errors was to convert the mac package to a linux-64 package and upload it to my anaconda channel. Touching on my earlier point, isn't this documented somewhere?

**Comment by stsewd** [comment]
There is some docs about conda http://docs.readthedocs.io/en/latest/conda.html. As you see still a beta feature and lacks of documentation. Can you help us to improve this? Documenting how you solve this problem, was solved?

**Comment by jakirkham** [comment]
Builds occur on a Docker image IIRC. So in a Linux environment. Hence it will search for Linux. Either you can try to relax your requirements so that the macOS only packages are not pulled in for doc building or you can try to build those packages for Linux (if possible).

**Comment by stsewd** [comment]
@jkroes can you please provide your rtd project url? Also, the github project that your linked is 404.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Please see the above suggestion https://github.com/rtfd/readthedocs.org/issues/3075#issuecomment-370043182
