### ISSUE TITLE
Custom sphinx extensions ignored during conda-based build process

### ISSUE THREAD

**Issue by jkroes** [rtfd/readthedocs.org#3076]
Details

Project URL: https://github.com/jkroes/PersonalTutorials
Read the Docs username (if applicable): jkroes
Expected Result

RTFD uses a custom directive provided by extension `sphinx-autorun` to evaluate code and render the results alongside the code. 

Actual Result

Sphinx blocks using the custom directive are not evaluated properly, though the conda package is shown as installed, `conf.py` includes the extension, and the directives work outside of RTFD with the conda package `sphinx-autobuild` and with the regular `make html` process.

**Comment by jkroes** [comment]
More info:

'View Docs'
Click on desired page and taken to http://personal-tutorials.readthedocs.io/en/latest/pytutorial2.html
Navigate to this link: http://personal-tutorials.readthedocs.io/en/latest/genindex.html
Re-click the first link and taken to http://personal-tutorials.readthedocs.io/en/latest/pytutorial.html
I see the desired results. 

The issue seems to involve an older version of a page (pytutorial2.html) being displayed, but after navigation the newer version is displayed (pytutorial.html) with the desired behavior. The old file that was used to generate the older HTML page is no longer in the git repo linked to RTFD...

**Comment by jkroes** [comment]
Update 2:

Deleting and recreating the repository fixed this issue.

**Comment by stsewd** [comment]
Looks like you don't have this project anymore (deleted?), are you still having this issue?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
