### ISSUE TITLE
Unable to install linuxdoc Python package

### ISSUE THREAD

**Issue by pvergain** [rtfd/readthedocs.org#3078]
## Details
  Could not find a version that satisfies the requirement linuxdoc==20170614 (from -r requirements.txt)
  No matching distribution found for linuxdoc==20170614 (from -r requirements.txt (line 12))
## Actual Result

  Could not find a version that satisfies the requirement linuxdoc==20170614 (from -r requirements.txt)
  No matching distribution found for linuxdoc==20170614 (from -r requirements.txt (line 12))

Linuxdoc is here:

- https://github.com/return42/linuxdoc/blob/master/linuxdoc/__init__.py

**Comment by stsewd** [comment]
Can you please provide more information? Is this the project you try to build?
https://github.com/return42/linuxdoc

**Comment by stsewd** [comment]
Well, if the docs of the repo you want to build is https://github.com/return42/linuxdoc. You need to check the `Install project` option on your settings, and the docs are successful built.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

And a solution was proposed.
