### ISSUE TITLE
Try getting a sponsor from codesponsor.io so the devs can have some (well-deserved!) compensation

### ISSUE THREAD

**Issue by CrazyPython** [rtfd/readthedocs.org#3079]
https://codesponsor.io

This has not been posted before.

**Comment by stsewd** [comment]
I'm not sure how this would be integrated. RTD already serves ads on their own and also have the gold memberships.

**Comment by davidfischer** [comment]
I talk with Eric from CodeSponsor regularly and we are focused on figuring out the areas we can work together. Currently, however, we do run our own ads and that's what pays the bills (mostly devs).

I think this issue can be closed.

**Comment by RichardLitt** [comment]
Thank you for the suggestion, @CrazyPython!
