### ISSUE TITLE
Delete Account?

### ISSUE THREAD

**Issue by maxwelld90** [rtfd/readthedocs.org#3090]
Hi,
Can somebody please delete my account? The username is `esig_maintainer`. There are no projects associated with it -- I wish to create a new account linked to my e-mail address.

Many thanks!
David

**Comment by ItsPugle** [comment]
Hey, @maxwelld90,

I've added the `Support` label for you. The Support Team from Read The Docs will look through it shortly.

**Comment by safwanrahman** [comment]
You can delete your account yourself now
https://readthedocs.org/accounts/delete/
