### ISSUE TITLE
please delete my casa1217 account from this readthedocs.org.  I have left the project, thank you fo ryour assistance.

### ISSUE THREAD

**Issue by casa1217** [rtfd/readthedocs.org#3091]
## Details

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by safwanrahman** [comment]
@casa1217 Now you can delete your account yourself
https://readthedocs.org/accounts/delete/
