### ISSUE TITLE
Unspecified error in building docs

### ISSUE THREAD

**Issue by julienmalard** [rtfd/readthedocs.org#3093]
## Issue
I have the same problem with two repositories, namely, that the builds will not complete and only show the error message "Build failed: an unexpected error occured". Here is an example from the Tiko'n repository:
https://readthedocs.org/projects/tikon/builds/5945523/

Interestingly, occasionally the builds will work on a translation of the same project (but not replicably so-- a few days ago the "Urdu" translation (actually still in Spanish) was working, but now the Tamil translation is working instead):
Tamil version logs:
https://readthedocs.org/projects/tikon-ta/builds/

Urdu version logs:
https://readthedocs.org/projects/tikon-ur/builds/

* Project URL: see above
* Build URL (if applicable): see above
* Read the Docs username (if applicable): julien.malard

## Expected Result
Built documentation.

## Actual Result
Unspecified error.

**Comment by agjohnson** [comment]
Addressed this in #3073. I'll close this one as a duplicate issue.
