### ISSUE TITLE
Requirements aren't being updated.

### ISSUE THREAD

**Issue by TagnumElite** [rtfd/readthedocs.org#3096]
## Details

* Project URL: https://readthedocs.org/projects/tagnumelite-pyffi
* Build URL: https://readthedocs.org/projects/tagnumelite-pyffi/builds/5956862/
* Read the Docs username: TagnumElite

## Expected Result
The Sphinx version would update.

## Actual Result
When updating sphinx from the `requirements-dev.txt` file it says the requirements are already satisfied when trying to build the doc it says Sphinx is outdated.

**Comment by Juanlu001** [comment]
The project has been removed.

**Comment by TagnumElite** [comment]
I gave up and switched to github pages.
