### ISSUE TITLE
Layout is corrupt when language=german

### ISSUE THREAD

**Issue by FroggieFrog** [rtfd/readthedocs.org#3097]
## Details

main website: https://readthedocs.org/

## Expected Result

no text is cut off or overlayed

## Actual Result

some text is not fully visible (see image).
![readthedocs](https://user-images.githubusercontent.com/6222752/30261341-7366627c-96cc-11e7-881f-14b3232e3fe4.png)

**Comment by stsewd** [comment]
Closing in favor of #779
