### ISSUE TITLE
https://docs.readthedocs.io/en/latest/getting_started.html to show text using more screen real estate.

### ISSUE THREAD

**Issue by Twoflower2** [rtfd/readthedocs.org#3099]
## Details

* Project URL: https://docs.readthedocs.io/en/latest/getting_started.html
* Build URL (if applicable):n/a
* Read the Docs username (if applicable): n/a

## Expected Result

*A description of what you wanted to happen*
https://docs.readthedocs.io/en/latest/getting_started.html show text using all screen real estate.

## Actual Result

*A description of what actually happened*
https://docs.readthedocs.io/en/latest/getting_started.html show text using half screen real estate.

## Suggestion
- Would be nice if a using could drag the text part to the right, bigger, if wanted.
- Or, in the `Read the docs` `v: lastest` dropdown/expander add the view size option

**Comment by agjohnson** [comment]
This has been brought up with our theme a number of times. Current plan is to size font depending on screen width. Closing here, this isn't a problem with RTD core.

**Comment by Twoflower2** [comment]
@agjohnson 

When will

> Current plan is to size font depending on screen width.

be active/work?
