### ISSUE TITLE
readthedocs fails silently on Python 3.6 project

### ISSUE THREAD

**Issue by joelgrus** [rtfd/readthedocs.org#3102]
## Details

* Project URL: https://github.com/allenai/allennlp
* Build URL: http://docs.allennlp.org/en/latest/
* Read the Docs username: joelgrus 

## Expected Result

Docs build the way they did under Python 3.5

## Actual Result

Docs "succeed" but most pages are empty. All of our classes / modules / functions have docstrings that used to show up but now are missing.

## Diagnosis

I can reproduce by using a Python 3.5 virtualenv locally. sphinx-build succeeds but if I run it with `-vv` it throws off a ton of warnings about the 3.6-style type annotations, and it generates the same bad docs with lots of empty pages.

**Comment by agjohnson** [comment]
This is potentially an issue with Sphinx, or at least the version of Sphinx you're using. You'll also need access to our 3.6 builder if you don't already, but if you are getting the same results locally, there isn't anything that we're doing different on RTD. I would pursue the issue on Sphinx.
