### ISSUE TITLE
dns apex  domain 

### ISSUE THREAD

**Issue by arsenovic** [rtfd/readthedocs.org#3104]
Would it be possible to setup a apex dns record to point to my website hosted on readthedocs? 
as is done with gh-pages (https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider)

**Comment by agjohnson** [comment]
You can, but we can't ensure the IPs won't change as the IPs aren't allocated directly to us. We recommend cname usage on a subdomain instead.

**Comment by choldgraf** [comment]
Just a note on this, I think CNAME redirection generally won't work if you're using HTTPS

https://stackoverflow.com/questions/9294215/why-isn-t-it-possible-to-use-a-cname-redirect-with-https

**Comment by mloning** [comment]
One solution is to set up a dummy website on GitHub Pages with a simple HTML script that redirects to your subdomain domain served by readthedocs and link that to your custom apex domain.

**Comment by davidfischer** [comment]
This issue is pretty old and closed but looks like folks are still finding it. I see in your linked issue that your DNS provider doesn't support ANAME or ALIAS records but we do support that option for any other users who find this: https://docs.readthedocs.io/en/stable/custom_domains.html
