### ISSUE TITLE
gsshapy: Conda UnsatisfiableError with pillow

### ISSUE THREAD

**Issue by snowman2** [rtfd/readthedocs.org#3105]
## Details

* Project URL:  http://readthedocs.org/projects/gsshapy
* Build URL: http://readthedocs.org/projects/gsshapy/builds/5982748/
* Read the Docs username:  snowman2

## Expected Result
http://readthedocs.org/projects/gsshapy/builds/5905665/

## Actual Result
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - pillow
  - poppler -> freetype 2.7|2.7.*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
