### ISSUE TITLE
Search of "latest" documentation shows some broken links

### ISSUE THREAD

**Issue by krzychb** [rtfd/readthedocs.org#3108]
## Details

* Project URL: http://readthedocs.org/projects/esp-idf/
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

* Search of "latest" documentation should not show broken links

## Actual Result

* Search of "latest" documentation shows some broken links.

## How to replicate

* Open: https://esp-idf.readthedocs.io/en/latest/?badge=latest
* In "Search docs" entry type "debugging"
* The first shown link is http://esp-idf.readthedocs.io/en/latest/api-guides/openocd.html?highlight=debugging, try to open it to see that it is broken

![screenshot from 2017-09-16 12-25-46](https://user-images.githubusercontent.com/12953787/30511586-96eac53a-9adc-11e7-85d4-8d0c5402c3f1.png)

**Comment by krzychb** [comment]
Hi Team,

Could you, please, review this issue? 
I just got another report, ref. links above, of users getting broken links when searching documentation.

**Comment by RichardLitt** [comment]
@humitos Want to take a stab at this?

**Comment by agjohnson** [comment]
Project has moved to rtd.com, closing this.
