### ISSUE TITLE
Transfer of ownership of "lxd" project

### ISSUE THREAD

**Issue by stgraber** [rtfd/readthedocs.org#3110]
## Details

* Project URL: https://readthedocs.org/projects/lxd/
* Read the Docs username (if applicable): stgraber

I'm the project leader for the LXC and LXD projects and the organization owner for https://github.com/lxc which includes https://github.com/lxc/lxd.

You can confirm my ownership of the project by the fact that I have personally made every single release commits on this project: https://github.com/lxc/lxd/releases

I've recently been made aware of the existence of https://readthedocs.org/projects/lxd/.
I don't have a problem with it other than it being out of date, missing Github webhooks and showing a branch for a LXD release that has long been made out of support (2.7). I'd love to clean it up and have it become our official documentation.

It's currently owned by @ajd394 but I don't have any contact information for this user so can't ask them to share access to the readthedocs project with me.

Can you transfer ownership of this project over to me (stgraber is my readthedocs account) or at least provide me with contact details for the current owner so that I can reach out to them?

Thanks.

**Comment by stgraber** [comment]
I also found it odd that after I linked my Github account with readthedocs it properly listed all the repositories I have access to for my various organizations, including this one, but didn't automatically grant me access to it (which is the behavior I've seen on other similar sites that have Github integration).

**Comment by ajd394** [comment]
My apologies I created it back when it didn't exist. If I just remove it
will thst solve the problem?

**Comment by stgraber** [comment]
Hi, yes, it would. I'd then be able to re-register it and connect it to the upstream repository.

**Comment by ajd394** [comment]
done.

**Comment by stgraber** [comment]
And re-enabled with upstream integration, thanks!
