### ISSUE TITLE
Documentation homepage is 404 on Safari and Firefox

### ISSUE THREAD

**Issue by desilinguist** [rtfd/readthedocs.org#3113]
## Details

The documentation for my project (RSMTool) just keeps 404ing on Safari and Firefox with the following error: "Can't find the page rsmtool.readthedocs.io". Other times, I get a different error: "Invalid hostname".

However, things work just fine on Chrome. I am really confused. I also re-built but that didn't seem to help. I also tried `rtfd.org` and `readthedocs.org` variants but they also 404.

* Project URL: http://rsmtool.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): desilinguist

## Expected Result

The documentation should load.

## Actual Result

Documentation doesn't load with a 404 error.

**Comment by safwanrahman** [comment]
The docs is loading fine for me.
http://rsmtool.readthedocs.io

**Comment by ericholscher** [comment]
Doc'd with: http://docs.readthedocs.io/en/latest/faq.html#help-my-build-passed-but-my-documentation-page-is-404-not-found
