### ISSUE TITLE
Support for translations in Mayan languages

### ISSUE THREAD

**Issue by julienmalard** [rtfd/readthedocs.org#3115]
## Details
I would need to translate my project into several Mayan languages (for the moment, Kaqchikel [ISO: cak, Glottolog: kaqc1270], Tz'utujil [ISO: tzj, Glottolog: tzut1248] and K'iche' [ISO: quc, Glottolog: kich1262]), but can't choose those languages as a repository language option in the ReadtheDocs interface. Would it be possible to add those?

## Expected Result
Option for these languages in the "project language" section of the project settings page.

## Actual Result
Languages currently not included.

**Comment by stsewd** [comment]
You can help with a PR similar to #3588

**Comment by julienmalard** [comment]
Fixed in #3759
