### ISSUE TITLE
Doc build killed during pip installation of large (~190 MB) dependency

### ISSUE THREAD

**Issue by smurching** [rtfd/readthedocs.org#3116]
## Details

* Project URL: https://github.com/smurching/spark-sklearn
* Build URL (if applicable): https://readthedocs.org/projects/spark-sklearn-smurching/builds/6008665/
* Read the Docs username (if applicable): smurching

## Expected Result

I'm trying to publish docs for [spark-sklearn](https://github.com/databricks/spark-sklearn) & am testing out the readthedocs build on my personal fork. 

## Actual Result

The build attempts to install a ~190 MB dependency via `pip install pyspark` and is killed. 

I'm not sure why this is happening; the only build env limitations I can find are the 15 min, 1 GB RAM limitations described at http://docs.readthedocs.io/en/latest/builds.html#build-process.

**Comment by agjohnson** [comment]
This looks to be hitting a memory limit. Docker doesn't always give us a reasonable exit code or kill reason. If you don't need the dependency for you documentation directly, I'd suggest mocking out the dependency. You can find an example in our docs.

**Comment by humitos** [comment]
Hi @smurching! I'm closing this one since there was a solution proposed here. Feel free to reopen if you consider. Thanks!
