### ISSUE TITLE
4secure all websites

### ISSUE THREAD

**Issue by JazzyBabyGirl1995** [rtfd/readthedocs.org#3118]
## Details

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by JazzyBabyGirl1995** [comment]
[DriverSupport.txt](https://github.com/rtfd/readthedocs.org/files/1323684/DriverSupport.txt)

**Comment by RichardLitt** [comment]
Hi @JazzyBabyGirl1995 - This looks like spam, so I am closing it. If you have a genuine issue, please fill out the issue template in the future, and do not include text file links. Thank you.
