### ISSUE TITLE
Enable users to delete their own account

### ISSUE THREAD

**Issue by RichardLitt** [rtfd/readthedocs.org#3120]
Currently, people are posting issues if they need their account deleted. This leads to extra noise in the issues, and to some privacy concerns. 

I propose we add an email account and notice to the README, letting users know where they can email to request account deletion. This will allow better triaging and chunking of deletions. 

@ericholscher What do you think?

**Comment by jleclanche** [comment]
Is adding a "Delete Account" button somewhere out of the question?

**Comment by RichardLitt** [comment]
That would also work. This is a proposed stop-gap measure which would be easier to set up, I believe.

**Comment by ericholscher** [comment]
There's a bunch of background here: https://github.com/rtfd/readthedocs.org/issues/1408 -- tl;dr, we need to decide how to handle a number of cases when deleting folks, and it isn't as simple as running user.delete().

**Comment by ericholscher** [comment]
I lied, #1408 is about deleting projects, which is a follow on effect on deleting users.

**Comment by RichardLitt** [comment]
Yep. What we can do now, though, is to set up a clearer, more private way for users to contact you (or someone else who can do this task), which doesn't require them spamming all of the watchers. What do you think?

**Comment by ericholscher** [comment]
Hmm, I guess. Though having the requests just come to my email isn't a great solution either. We should really implement a proper delete function; but I guess the people who want to delete their accounts are the least likely to contribute :/

**Comment by RichardLitt** [comment]
I feel let. How about we rename this "Enable users to delete their own account", tag it as Help Wanted, and see if anyone wants to bite? :)

**Comment by ericholscher** [comment]
Works for me. I'd like to get to it, but as above, users who are leaving the platform are hard to prioritize, so it hasn't gotten done.

**Comment by RichardLitt** [comment]
> users who are leaving the platform are hard to prioritize,

Ah. I'm sorry, I wasn't clear! I agree, I'm not prioritizing them. What I'm prioritizing is the notifications of watchers to this repo - people we want to keep! - and ensuring that we don't flood their streams with issues from people saying 'Delete my account please'. Some of the noise can be removed with a better process, leading to higher signal. 

I'll change the name of the issue now! Anyone who wants to take this on, feel free to comment here!

**Comment by safwanrahman** [comment]
@RichardLitt So the fix would be adding a button for the user to delete their account?

**Comment by RichardLitt** [comment]
@safwanrahman Yep. Want to take a crack at it?

**Comment by safwanrahman** [comment]
@RichardLitt I will go through the code and check if I can make it work. Hope that will work
