### ISSUE TITLE
Build exited due to time out

### ISSUE THREAD

**Issue by dw** [rtfd/readthedocs.org#3122]
## Details

* Project URL: https://mitogen.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/mitogen/builds/6028399/
* Read the Docs username (if applicable): dw

## Expected Result

1. Build completes without error, or
2. Build completes reporting error the occurred

## Actual Result

Build times out with no indication in the logs as to why

Tried disabling pdf and epub output as per #2710 but it didn't help

**Comment by dw** [comment]
It was due to a Sphinx plug-in running a command that was crashing, however the command does generate stderr output, it'd have been nice if that showed up on the builds page. Probably can close this bug? It's almost certainly a duplicate I guess :)

**Comment by RichardLitt** [comment]
> however the command does generate stderr output, it'd have been nice if that showed up on the builds page.

Perhaps you could make a PR to fix this? That way we won't run into the same issue again, most likely.

**Comment by safwanrahman** [comment]
Seems like builds are passing. https://readthedocs.org/projects/mitogen/builds/

**Comment by dw** [comment]
Thanks, yes the build is fixed now.
