### ISSUE TITLE
API returns malicious(?) code

### ISSUE THREAD

**Issue by yochannah** [rtfd/readthedocs.org#3124]
## Details

* Project URL: http://readthedocs.org/api/v2/domain/

## Expected Result

I was exploring the v2 API in hopes of using it, and came across this page: 
http://readthedocs.org/api/v2/domain/

Expectation: I'd be able to easily browse for my project and figure out how to embed content onto my web page. 

## Actual Result

As it stands currently, it looks like a) there is a *lot* of spam and b) some of the spam appears to contain an attempt to inject Java of some sort here: http://readthedocs.org/api/v2/domain/ - as it stands I wouldn't feel very safe drawing any data from the API :(

**Comment by agjohnson** [comment]
Hrm, well we do as best as we can with spam. We regularly clean this up, but it's bound to be in there. I don't see any cases of javascript injection, but again, not much we can't do here to ensure the data is clean -- being user submitted, you definitely shouldn't trust this data.

Not sure what we can do here, other than be more proactive about spam removal. This is difficult as we have limited resources already.

**Comment by agjohnson** [comment]
Closing this as I don't think there is anything we can do with our current API. In future API versions, I assume we'll probably make this data closed off to the public. Querying the API should be a authed user function, and return should be *your* domains, not *everyone's* domains.
