### ISSUE TITLE
500-error not behaving properly in main site

### ISSUE THREAD

**Issue by alexbarcelo** [rtfd/readthedocs.org#3128]
URL: https://readthedocs.org/500/

## Expected Result

The cute

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

## Actual Result

A really ugly 

```Internal Server Error```

## Preliminary diagnosis

A local deployment give those debug information:

```
 Traceback (most recent call last):
   File "/usr/local/lib/python2.7/wsgiref/handlers.py", line 85, in run
     self.result = application(self.environ, self.start_response)
   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 177, in __call__
     response = self.get_response(request)
   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 230, in get_response
     response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
   File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 296, in handle_uncaught_exception
     return callback(request, **param_dict)
 TypeError: server_error_500() takes at least 2 arguments (1 given)
```

I think that the `handler500` (in `readthedocs/urls.py`) using the `server_error_500`  (in `readthedocs/core/views/__init__.py`) is not correct because of the extra `exception` parameter. According to [official docs](https://docs.djangoproject.com/en/1.11/ref/views/#http-internal-server-error-view) this parameter is not expected.

Could not find anywhere where that parameter `exception` is being used. Is it safe to remove entirely? Same with the 404, I suppose that the ugly error received in https://readthedocs.org/404/ is due to the same mismatch.

**Comment by humitos** [comment]
Thanks for your report. This was fixed at https://github.com/rtfd/readthedocs.org/commit/8de1770d
