### ISSUE TITLE
Start a bug bounty program

### ISSUE THREAD

**Issue by EdOverflow** [rtfd/readthedocs.org#3129]
I would highly recommend starting a bug bounty program. This would allow researchers to contact you when they discover security vulnerabilities. HackerOne offer free programs to open source platforms: https://www.hackerone.com/product/community

I currently run one, so if you need any help getting started feel free to contact me.

**Comment by ericholscher** [comment]
Great idea, do you know of anyone who is funding bug bounty programs?

**Comment by EdOverflow** [comment]
@ericholscher:

1. https://internetbugbounty.org/ might be something to look into.
2. You do not have to actually provide financial rewards. Some BBPs only give reputation points. (https://hackerone.com/gitlab)

On a side note, I would be willing to join your team to help you get started on the platform. I currently run [Gratipay](https://hackerone.com/gratipay) and [Aspen](https://hackerone.com/aspen)'s BBPs on Hackerone. Please let me know if this is of interest to you.

**Comment by agjohnson** [comment]
@EdOverflow thanks for the pointers, I think this is a great idea! We definitely aren't in the position for a financial bug bounty, but I'd love to get the security community involved in guiding us more. It's certainly an area we don't get to focus on as much as we'd link.

I think I have your email, I'll move this conversation there.

**Comment by EdOverflow** [comment]
https://bugbountyguide.com/ now has some instructions on helping you launch a security program. It might be a good idea to start there to get a better idea of what the requirements are.
