### ISSUE TITLE
Can I edit docs added by someone else?

### ISSUE THREAD

**Issue by Ev1dentFir3** [rtfd/readthedocs.org#3133]
The Discord.js docs are out of date by several versions and basically obsolete. Is there a way to upload updated ones or does the original creator have to do it?

**Comment by RichardLitt** [comment]
I _think_ this is the same question as in #6. Might be a good one to answer and add to the [FAQ](https://docs.readthedocs.io/en/latest/faq.html).

**Comment by choovin** [comment]
yes

**Comment by RichardLitt** [comment]
Thanks @choovin. Can you clarify what you're saying yes to? :)

**Comment by Ev1dentFir3** [comment]
Yeah honestly I have never used readthedocs till now, but it's frustrating cause it's one of the first results on google when searching, but also way out of date so I figured I would update what I could if possible.

**Comment by Blendify** [comment]
Stale question closing.

**Comment by RichardLitt** [comment]
@Blendify I'm not sure that this is a stale issue. @Ev1dentFir3's question wasn't answered, which is on us, not him.

**Comment by humitos** [comment]
We have a policy for abandoned projects now, check it out at http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by RichardLitt** [comment]
Thanks @humitos. @Ev1dentFir3 - if this doesn't answer you, let us know!

**Comment by shirt-gov** [comment]
This issue has not been resolved as is the case with the discord.js issue.

**Comment by Ev1dentFir3** [comment]
the discord.js docs not being updated doesn't count as my question not being answered.

They answered my original question so his closing the ticket is valid.
