### ISSUE TITLE
pdf builds while html does not include in-line code

### ISSUE THREAD

**Issue by pf4d** [rtfd/readthedocs.org#3134]
* Project URL: http://cslvr.readthedocs.io/en/latest/
* Read the Docs username: pf4d

When building my docs, the pdf seems to be created OK, but the website doesn't include any docs included from the in-line documentation.

**Comment by ericholscher** [comment]
Is this still an issue? I'm guessing it's this: http://docs.readthedocs.io/en/latest/faq.html#my-project-isn-t-building-with-autodoc

**Comment by pf4d** [comment]
...  not sure, but eventually the problem seemed to have resolved itself.
