### ISSUE TITLE
Consider alternate storage mechanism for build command output

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3136]
Currently, 75% of our database storage is build command output, if I had to guess, more than 95% of it is never seen. So, the majority of this data does not have a lot of value to us or users. We should explore alternative ways of reducing the storage requirements here, while also aiming to reduce our operational overhead. Discussions here will feed directly into how we upgrade (or avoid upgrading) our database server.

## Option 1: get a bigger boat

Last time this came up, we decided a bigger database server was easiest. This could be the case now, but eventually our database will outgrow our budget, and the bigger database servers are not cheap.

## Option 2: more complex database usage

We could disregard usage patterns and instead turn to database sharding or partitioning, but these are heavy operational changes. Partitioning would at least be seamless from the aspect of the open source project, but would require special maintenance. We'd have the option of putting some of the data on cold storage.

Problems here are that rackspace's network disks are horribly unreliable and go belly up several times a year. I don't want to have to rescue our database.

Sharding could help, but I'm not sure what exactly we shard on. Database design would need to be reconsidered here, as it would likely be on project or user, but we still need to run join selects across shards.

## Option 3: don't store build command output in database

This data could probably exist just fine in Cloudfiles/s3. When users view the build command output, we'll fetch the json blob from cold storage, cache, and serve the data to the user -- all through our API.

The downside would be that our build command update mechanism, and likewise the build command live updated, would need to be reworked to respect the fact that pulling down a json blob continuously probably won't work well. On viewing this data, a slight delay might be introduced as we proxy the JSON.

A strong benefit here is that this moves the operational load to rackspace/amazon, doesn't require us to continually revisit upgrading or breaking up our database.

Another benefit, build data would be served through a CDN if we didn't proxy it. We'd store the link to the build data in the build model object.

Yet another benefit: cost would be about $10/mo for storage of 100G of data

## Option 4: rethink build data storage

Further reconsidering data, does having any more than the last 5 builds, or last 2 weeks, or 2 months even, of build data help anyone? Does historical build data really help anyone? We could just be storing failures, or otherwise deviating from the CI style tracking of all build data.

This won't work for use cases like integration with GitHub PRs though, we do need historical build data for display here, along with potentially storing build assets. So, this might be the wrong way to approach things.

# Things we need to determine

- [ ] What portion of build pages have pageviews
- [ ] How many pageviews go to build output pages
- [ ] What would flat file storage look like in terms of live updates -- is live update a requirement?
- [ ] What would the update mechanism be for flat file storage? How do we disturb the modeling the least and avoid complicating local development?
- [ ] How do we authenticate, for private repositories?
- [ ] How do we ensure authentication requirements are kept in sync with our models? For example, a public version that is changed to private needs to add authentication on flat files.
- [ ] Do we proxy everything instead? This breaks CDN usage, but saves us from a lot of headaches around authentication. Our app is the only ACL required.

**Comment by ericholscher** [comment]
I like keeping the data in cold storage. We could cache the last 2 weeks of data in the DB, and have a background task that syncs it to cold storage for old builds.

**Comment by ericholscher** [comment]
I think using cold storage here also paves the path for doing PR-based archiving of content as well. We could use a similar model where we keep the PR data on our web servers for 3 days, and then move it to cold storage in cloud files.

**Comment by agjohnson** [comment]
Good point on syncing. If we added a field to `Build` objects for the JSON blob URL, a celery scheduled task could exist to continually move this data into cold storage. This would leave local development untouched, and the syncing code could simply be an extension to RTD. Also leaves live updating in tact and would be entirely seamless.

If we kept the data structure of the API, the front end code just needs to be re-pointed to the JSON url.

I like this plan so far. 👍

**Comment by agjohnson** [comment]
Just had another thought on private repository support, we'll want authentication on the files. Not sure this is possible with cloudfiles, but is with s3. We can support either if we proxy through our API, but this doesn't leverage the CDN support. s3 is probably a better target here, as we can assign arbitrary authentication acls, i believe.

**Comment by agjohnson** [comment]
This is in production! Our database is not growing (as fast). 🎉
