### ISSUE TITLE
Canonical URL tag not injected into pages

### ISSUE THREAD

**Issue by lmakarov** [rtfd/readthedocs.org#3137]
## Details

* Project URL: https://docs.docksal.io (https://docksal.readthedocs.io)
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

As per documentation [here](http://docs.readthedocs.io/en/latest/canonical.html):
When using a custom domain and setting it as canonical under RTD Domains settings a tag is injected into all documentation pages, e.g.

```
<link rel="canonical" href="http://pip.readthedocs.io/en/latest/installing.html">
```

## Actual Result

The tag is missing, which leads to the docksal.readthedocs.io domain showing up in Google searches instead of the custom configured domain (docs.docksal.io).

**Comment by lmakarov** [comment]
I noticed mkdocs has an option to set the canonical site URL:
http://www.mkdocs.org/user-guide/configuration/#site_url

Does that have any effect with RTD?

**Comment by lmakarov** [comment]
I [added](https://github.com/docksal/docksal/blob/develop/mkdocs.yml#L5) `site_url` in `mkdocs.yml` and it does not have any effect.

**Comment by stsewd** [comment]
We don't touch the mkdocs theme, and I don't see that we do something with the `site_url` setting, can you try building with a more recent version of mkdocs? Maybe that option wasn't supported in the version you were building? We need to check building the project again and see if this problem can be fixed using only mkdocs.

**Comment by stsewd** [comment]
Also, the docs linked are only valid for sphinx, we definely can do the same for mkdocs if `site_url` works on most of the versions of mkdocs

**Comment by stsewd** [comment]
I just build your docs locally and I wasn't able to see the canonical tag either, that means that this is an mkdocs issue. Also, if I change the theme to `mkdocs`, then I can see the canonical tag.

I just created an issue on mkdocs so you can follow https://github.com/mkdocs/mkdocs/issues/1667 I'm closing this one.

**Comment by lmakarov** [comment]
@stsewd thanks for looking into this!
