### ISSUE TITLE
Increase timeout setting for Sequana project

### ISSUE THREAD

**Issue by cokelaer** [rtfd/readthedocs.org#3144]
## Details

I use RTD to build the Sequana project documentation. The builds have been successful for a while so the settings are correct. We use RTD on this project for a year and so far so good. thanks for the great job by the way. From time to time we suffered from the 900 seconds time out but optimising with conda helped us. However, we are always close to 900 seconds build and the latest builts failed due to this time limitation. We have indeed added a couple of small packages but this means we now constantly trigger the time out. Would it be possible to increase the timeout settings from 15 to minutes to 20 ? Thank you !

* Project name: sequana
* Project URL: http://github.com/sequana/sequana
* Build URL (if applicable): http://readthedocs.org/projects/sequana/
* Read the Docs username (if applicable): cokelaer

## Expected Result

Build completed

## Actual Result

Biuld exited due to time out

**Comment by RichardLitt** [comment]
Related to #3123.

**Comment by cokelaer** [comment]
@RichardLitt This may be unrelated but the builds do fail now with  a permission error

```
Cannot remove entries from nonexistent file /home/docs/.conda/pkgs/urllib3-1.12-py35_0/lib/python3.5/site-packages/easy-install.pth
```

https://readthedocs.org/projects/sequana/builds/6084016/

I'm just wondering whether you've changed something wtr to the timeout that has a side effect ?
thanks

**Comment by cokelaer** [comment]
okay this is probably not related since the latest and stable branch have been built successfully.

**Comment by RichardLitt** [comment]
@cokelaer I hadn't changed anything. Thanks for opening up a new issue!

**Comment by cokelaer** [comment]
still have the issue of the timeout error. Right now only the develop branch has been succesfully built. Others are failing with a timeout of 940seconds and 927 seconds

https://readthedocs.org/projects/sequana/builds/6151294/
https://readthedocs.org/projects/sequana/builds/6151072/

I noticed that there are 2 Sphinx builts and one with a "-b json" output that could be skipped to gain time ?

**Comment by cokelaer** [comment]
@RichardLitt would it be possible to increaes the build time out to 20 minutes ? I am stuck with building the doc for this package and need to update the documentation. I have solved the same issue for another package (keeping the time below 900s) but for that one, all dependencies are required and I do not think how I can decrease the build time. Thanks i advance.

**Comment by RichardLitt** [comment]
@agjohnson What do you think?

**Comment by cokelaer** [comment]
@RichardLitt @agjohnson sorry to bother you again but I had temporarily fixed the issue by removing some of the documenation (gallery examples) but facing again the 900 seconds issue today. I will need to update the doc for a publication very soon and will need to update the installation section but this is currently failing. Not sure what your decision is or will be. I have no issues with about 10 others packages but this one has a thorough documentation indeed and I do not see how I can make it shorter in build time for the time being. thanks for the feedback.

**Comment by cokelaer** [comment]
@RichardLitt @agjohnson 

I noticed that last week I had a "passed" build (http://readthedocs.org/projects/sequana/builds/6460617/) during the chritmas and new year time. I believe RTD was not as busy and so to give you an idea it took 720 seconds to build the sequana's documentation. Now, we are back to the 900 seconds limits. However, the good news is that I can assess more precisely the timeout increase that would be required. 

Indeed, by extrapolation, based on the time used by each  steps of the latest failed build (http://readthedocs.org/projects/sequana/builds/6499953/), I believe that a timeout of 20 minutes instead of 15 should be enough. The main difference is time for each steps occur in the latests steps that is in the sphinx builds (200 seconds instead of 100). 

thanks in advance.

**Comment by cokelaer** [comment]
@RichardLitt @agjohnson 
I am closing this issue. You may have changed something on RTD and the build now pass again with a time below the 900 seconds.

**Comment by RichardLitt** [comment]
@cokelaer Glad to hear it. Let us know if this issue pops up again.
