### ISSUE TITLE
Add project delete method that wipes build artifacts

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3145]
Raised in #3131, the Project model should probably just be removing files on project deletion. Historically, our stance has been to archive these files, but I think the expect effect should be that the files are completely removed.

We could probably review the admin function for removing projects as well, and call Project.delete() instead of relying on the query `.delete()` method.

There are also other places where we are using a one-off method of removing artifacts, these can all be unified under the `Project.delete()` method.

## Decide

- [ ] Do we want to remove files on project delete?
- [ ] Do we need extra protection from multiple users deleting projects?

**Comment by safwanrahman** [comment]
I believe we can remove the files upon project deletion. After the project got deleted, there are no values of the files. Moreover, if needed, its possible to get the files by building the project again.

**Comment by agjohnson** [comment]
@ericholscher I'm probably 👍  on making this change, thoughts? I know our position has been to keep these files, but seems its not expected from folks.

**Comment by ericholscher** [comment]
Yea, I think it makes sense. I'd love to have some kind of solution to #562 or similar to archive things to archive.org every month or so, but it makes sense to delete files I think.

**Comment by ericholscher** [comment]
I really hate breaking old URL's though >:x

**Comment by humitos** [comment]
This is already implemented. Once a project is deleted, all artifacts are removed. Closing here.

Reference in code: https://github.com/rtfd/readthedocs.org/blob/bde0088ee61bebc0d7227c5056c7e8f88255357a/readthedocs/projects/views/private.py#L183-L184
