### ISSUE TITLE
built error (remove entries from nonexistent file) on some branches and not others

### ISSUE THREAD

**Issue by cokelaer** [rtfd/readthedocs.org#3149]
## Details

* Project URL: github.com/sequana/sequana
* Build URL (if applicable): sequana.readthedocs.io
* Read the Docs username (if applicable): cokelaer

## Expected Result

successful built

## Actual Result

The built on RTD works in general but the latest built may fail on some branches and not others. For instance the build fails on the "develop" branch that is identical to "latest" branch, which passes. 
In the develop branch the error message is 

```
Cannot remove entries from nonexistent file /home/docs/.conda/pkgs/urllib3-1.12-py35_0/lib/python3.5/site-packages/easy-install.pth
```

for example: https://readthedocs.org/projects/sequana/builds/6084575/

thanks for any feedbacks or help

**Comment by cokelaer** [comment]
@RichardLitt FYI this is now failing on all branches (master, latest, develop)

**Comment by RichardLitt** [comment]
May be related to #3150. 

@cokelaer Any chance you've been touching .conda anywhere else on your system?

**Comment by cokelaer** [comment]
? not sure what you mean. I did not change anything in the admin part of the project on 
https://readthedocs.org/dashboard/sequana/edit/
However, I have updated a template file in the sphinx code of the documentation but it builds locally. 
As for the environment.yml and readthedocs.yml, they were not changed either.

**Comment by RichardLitt** [comment]
That error looks like it is a conda issue - so I wanted to make sure that you weren't touching that elsewhere. If you don't know what that means, that helps us out, as it means it is probably an error on our end. Thanks!

**Comment by cokelaer** [comment]
I have changed the requirements.txt slightly but this does not seem to be the issue indeed since this part of the build is succesfull as shown here : http://readthedocs.org/projects/sequana/builds/6094359/
thanks

**Comment by cokelaer** [comment]
FYI in RTD, the error occurs at the third stage when executing the command:
```
 python /home/docs/checkouts/readthedocs.org/user_builds/sequana/conda/master/bin/pip install -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/sequana/.cache/pip recommonmark readthedocs-sphinx-ext 
```

**Comment by cokelaer** [comment]
@RichardLitt sorry to sound a bit impatient, I was wondering whether you had any feedbacks or clues about what is happening on this project ? or whether you need further help from my side ? I'll be willing to do tests if that helps.

**Comment by RichardLitt** [comment]
@cokelaer Sorry to hear you need this sooner! I unfortunately don't know what the problem is - I'm helping out with triaging to make it easier for other maintainers, but can't diagnose this one any further at the moment.

**Comment by safwanrahman** [comment]
I am quite sure that this issue is cause of Conda. Updating conda version should fix it.
Merging https://github.com/rtfd/readthedocs-docker-images/pull/43 should fix the issue

**Comment by cokelaer** [comment]
I have added urllib3=1.22 in my conda environment in the environment.yml file
It worked on the develop branch on the project. Not sure this trick solve the problem or whereas the update of the conda version mentioned here above solved the problem. anyway this seem to fixed the issue. I have now other issue for the other branches related to time issue but that is a different issue. thanks. I'm closing the issue.
