### ISSUE TITLE
conda version used at RTD contains bug -- newer version available

### ISSUE THREAD

**Issue by wkerzendorf** [rtfd/readthedocs.org#3150]
## Details

http://tardis.readthedocs.io/en/latest/
https://readthedocs.org/projects/tardis/builds/6084573/
rtd user wkerzendorf

## Expected Result

We want to use the new conda build system to install our requirements. 

## Actual Result

The conda version used at RTD is 4.3.11 - the bug that we encounter is 
`ValidationError: Value for sha256 cannot be None`

that should be fixed in 4.3.14 according to https://github.com/conda/conda/issues/5278

**Comment by wkerzendorf** [comment]
@RichardLitt this is the problem - which I think is fixed in newer conda versions. thanks for the help

**Comment by wkerzendorf** [comment]
Is there any ETA for an update of conda on RTD?

**Comment by RichardLitt** [comment]
I'm trying to locate where the conda version is specified in the codebase, and I can't. @wkerzendorf how do you know that it is version 4.3.11?

**Comment by wkerzendorf** [comment]
@RichardLitt I'm not sure what you mean. The conda version used by rtd is 4.3.11 (and you can see that in the log). This conda version has problems resulting in the observed error. The easiest would be to update rtd to  a newer conda version. Does that help?

**Comment by RichardLitt** [comment]
@wkerzendorf Cool. I was trying to see if we could make a PR, but it sounds like this is a support issue. Labelling it appropriately.

**Comment by wkerzendorf** [comment]
@RichardLitt thank you for your help. If there are things we can help with (like testing) please let us know.

**Comment by humitos** [comment]
The conda version is specified in the docker build image: https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile#L54

**Comment by wkerzendorf** [comment]
@agjohnson how long until our fix trickles through to the actual docker images. I just built right now and it is still version 4.3.11.

**Comment by agjohnson** [comment]
I've just deployed the new images to our build servers. You can try a build now and should get the correct version of conda.

**Comment by agjohnson** [comment]
I haven't heard anything back to the contrary, so I'll close this. Feel free to reopen if the new build images didn't fix this problem.

I added automated tracking of the conda version releases through our CI:
https://github.com/rtfd/readthedocs-docker-images/blob/master/tests/test_dependencies.py

So we'll get CI failures when conda releases new versions. Hopefully this helps us keep more up to date.

**Comment by wkerzendorf** [comment]
@RichardLitt @agjohnson works like a charm - thank you
