### ISSUE TITLE
Increase timeout for gala-astro

### ISSUE THREAD

**Issue by adrn** [rtfd/readthedocs.org#3153]
## Details

* Project URL: [github](http://github.com/adrn/gala), [readthedocs](https://readthedocs.org/projects/gala-astro/)
* Build URL (if applicable): https://readthedocs.org/projects/gala-astro/builds/6090208/
* Read the Docs username (if applicable): adrn

## Expected Result

Build completed.

## Actual Result

`Error: Build exited due to time out`

Some builds succeed, but I've been seeing more timeouts lately so I think the build time is right around 900 sec. Locally on my Macbook Pro laptop running OS X 10.12, the sphinx build only takes ~200 sec. If possible, could the build time be increased to 1800 sec? Thanks so much for an awesome service!

**Comment by netflixhelp12** [comment]
support for netflix contact, netflix support, netflix tv support , fix problem for netflix, netflix problem, netflix phone number,http://netflix-netflixsupport.com, netflix support number, netflix tech support, netflix technical support, tech support for netflix ,netflix connection, connect to netflix http://netflix-netflixsupport.com
Netflix Ui 122 Ps4,How To Install Netflix On Ps4,Playstation 4 Netflix Problems, http://netflix-netflixsupport.com,Ps4 Netflix Problems Today,Netflix On Ps4 Issues,Netflix On Ps4 Issues,Netflix Nw-2-5,Netflix Down,Netflix Error Ui-122 Ps4, Netflix Error Ui-122 Ps3,http://netflix-netflixsupport.com, Netflix Error Code Ui-122 Ps4, Netflix Code Ui-122 Ps3, Netflix Error Code Ui-122 On Ps3 http://netflix-netflixsupport.com
You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number. http://netflix-netflixsupport.com

**Comment by adrn** [comment]
Hi @humitos, @RichardLitt -- I'm still facing these timeouts...Any way you could increase the timeout? If not, I'm going to have to move my docs off of RTD :(

**Comment by humitos** [comment]
Hi @adm. I'll take a look next week

**Comment by humitos** [comment]
@adrn Hi! I've increased the time limit. Let me know if that works. Feel free to reopen otherwise.
