### ISSUE TITLE
Build fails in setup-install step w/ typing module in Python2.7 (behave)

### ISSUE THREAD

**Issue by jenisys** [rtfd/readthedocs.org#3155]
## Details

* Project URL: https://github.com/behave/behave
* Build URL (if applicable): https://readthedocs.org/projects/behave/
* Read the Docs username (if applicable): jenisys

## Expected Result

The ``latest`` version of the project docs should build w/o problems.
Normal sphinx builds work w/o any problems.

Current work-around:

* Use CPython-3.x instead of CPython-2.x

## Actual Result

The ``latest`` version of the project docs currently fails in step ``python setup.py install --force``:

```sh
...
Running traceback2-1.4.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-zu6LMk/traceback2-1.4.0/egg-dist-tmp-UUZh24

Installed /tmp/easy_install-zu6LMk/traceback2-1.4.0/.eggs/pbr-3.1.1-py2.7.egg
ERROR:root:Error parsing
Traceback (most recent call last):
...
  File "/home/docs/checkouts/readthedocs.org/user_builds/behave/envs/latest/lib/python2.7/abc.py", line 180, in __subclasscheck__
    if issubclass(subclass, scls):
  File "/home/docs/checkouts/readthedocs.org/user_builds/behave/envs/latest/lib/python2.7/site-packages/typing.py", line 1265, in __subclasscheck__
    return super(GenericMeta, self).__subclasscheck__(cls)
TypeError: super() argument 1 must be type, not None
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-zu6LMk/traceback2-1.4.0/setup.cfg: TypeError: super() argument 1 must be type, not None
```

SEE ALSO:
* https://readthedocs.org/projects/behave/builds/6093267/

**Comment by stsewd** [comment]
I was able to replicate this on my local instance with your project, but I'm not sure why the error occurs, I was able to run `python setup.py install` successfully on virtual environments with python 2 y 3.

I'm going to do more research on this.

**Comment by stsewd** [comment]
So, I ran the same steps inside the docker container that is used to build the docs. Looks like there is a incompatibility between some packages installed by RTD and the ones used on the behave project. If the behave's dependencies are installed first the error doesn't happen.

**Comment by stsewd** [comment]
I digged a little more, the exact incompatible package is sphinx 1.6.x. With 1.5.x works perfectly on python2.

**Comment by stsewd** [comment]
I fork the project and delete the traceback2 dependency, the `python setup.py install` part pass, the sphinx build fails obviously because of the missing package.

Sorry, I don't know any alternative to replace this package 😞.

**Comment by humitos** [comment]
> I fork the project and delete the traceback2 dependency, the python setup.py install part pass, the sphinx build fails obviously because of the missing package.

Is `traceback2` _needed_ to build the docs? If not, a possible solution, could be to mock it, as described here: http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by humitos** [comment]
> I digged a little more, the exact incompatible package is sphinx 1.6.x. With 1.5.x works perfectly on python2.

If the docs are built properly with Sphinx 1.5.x, why not pin it in a `requirements-rtd.txt` of the project?

**Comment by humitos** [comment]
I'm marking it as `Support` seems it doesn't seem to be a `Bug` in Read the Docs code but a dependency problem with the project itself.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

And I can see your latest builds are successful.
