### ISSUE TITLE
Interest in a --process-dependency-links setting?

### ISSUE THREAD

**Issue by rgerkin** [rtfd/readthedocs.org#3156]
My docs would build more easily if pip would run with --process-dependency-links.  How would the project leaders feel if I submitted a PR that allowed the user to add a process-dependency-links to their readthedocs.yml, and which if that line was found would run pip with --process-dependency-links?  I only ask in advance because this isn't useful to me (or anyone else) unless this is in principle something that would be accepted, my own fork of readthedocs.org being irrelevant.  

The main objection I foresee is that --process-dependency-links is always on the verge of being removed from pip.  To that I would note that a lot of people are still depending on it until pip supports PEP 508 or some other reasonable method for allowing dependencies from arbitrary URLs.    If it is eventually removed from pip, the flag would probably just be ignored and installation would proceed as if the flag wasn't there.

**Comment by rgerkin** [comment]
Sort of, but then everyone who wanted this would have to start creating pipfiles instead of or an addition to any other package management they are doing.  I'm interested in making it possible for branches of my project that use packages which are not on pypi to still have documentation, without otherwise changing anything about the way I do package management.

**Comment by rgerkin** [comment]
See the two PRs above for an implementation of this feature request.  The readthedocs-build would need to be accepted first, and then a readthedocs.org built against that would pass its tests and ought to work.

**Comment by tony** [comment]
@agjohnson Does rtfd support pipenv / Pipfile?

**Comment by Stibbons** [comment]
not yet. I have writen a [generator](https://github.com/Stibbons/pipenv-to-requirements) that reflect `Pipfile` to `requirements.txt` to be able to use Rtd.

**Comment by netflixhelp12** [comment]
support for netflix contact, netflix support, netflix tv support , fix problem for netflix, netflix problem, netflix phone number,http://netflix-netflixsupport.com, netflix support number, netflix tech support, netflix technical support, tech support for netflix ,netflix connection, connect to netflix http://netflix-netflixsupport.com
Netflix Ui 122 Ps4,How To Install Netflix On Ps4,Playstation 4 Netflix Problems, http://netflix-netflixsupport.com,Ps4 Netflix Problems Today,Netflix On Ps4 Issues,Netflix On Ps4 Issues,Netflix Nw-2-5,Netflix Down,Netflix Error Ui-122 Ps4, Netflix Error Ui-122 Ps3,http://netflix-netflixsupport.com, Netflix Error Code Ui-122 Ps4, Netflix Code Ui-122 Ps3, Netflix Error Code Ui-122 On Ps3 http://netflix-netflixsupport.com
You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number. http://netflix-netflixsupport.com

**Comment by agjohnson** [comment]
@tony @Stibbons I have on my todo list to try a minimal pass at pipenv support this week. We won't be using pipenv for virtualenv management though, just pipfile handling.

@rgerkin thanks for the PRs, I'll have to think more on them. We'd rather not depend on deprecated features, though I understand the background with the flag now. Ideally, we're pushing projects to adopt modern tooling, but we might be able to add some validation to make this config option make more sense.

**Comment by rgerkin** [comment]
@agjohnson I understand.  I am also OK if this flag is implemented but undocumented to avoid too many people relying on it.

**Comment by agjohnson** [comment]
I'll think more on the validation issue and follow up on https://github.com/rtfd/readthedocs-build/pull/28. I think validation might be enough for a feature like this, where we can at least keep projects pinned to an old version of pip once the flag is fully deprecated or pip has some answer for pep508.

I'll take ownership on this one for now so that i don't lose track.

**Comment by rgerkin** [comment]
As long as people have dependencies that are not on pypi, I think it is still relevant.

**Comment by stsewd** [comment]
What about the solution of putting that option inside the requirements file?

**Comment by rgerkin** [comment]
I guess this could work if setup.py is also configured to just load the contents of the requirements file into `install_requires` (which is what I do anyway).  Then `python setup.py install`, and `pip install` should both work with dependency links.

**Comment by rgerkin** [comment]
Let me give it a shot and report back and if it doesn't work I'll reopen this.

**Comment by stsewd** [comment]
Great! Let us know how that goes :)
