### ISSUE TITLE
Build passed but no documentation or downloads

### ISSUE THREAD

**Issue by mcraig-ibme** [rtfd/readthedocs.org#3159]
## Details

* Project URL: https://readthedocs.org/projects/oxford-asl/
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

Documentation and downloads available after build passed

## Actual Result

There's no indication of a problem in the build, but no documents are visible. I tried recreating the project under a different name. I have another similar project which is working fine. The only difference I can find between them is that in the working project the 'Overview' page displays 'latest' in the 'Versions' box whereas in the non-working project this box is empty. However the 'latest' version is listed in the 'Versions' page and is active. I've also tried 'wiping' the 'latest' version.

**Comment by RichardLitt** [comment]
Related to #2356.

**Comment by mcraig-ibme** [comment]
Worth mentioning that the docs on my working project *are* updating when I rebuild so it's something specific to my new projects - it looked to me like #2356 was to do with queuing of updates which would presumably affect all projects?

**Comment by ShawnDriscoll** [comment]
I don't think any PDFs or EPUBs have been generated for any projects since Oct. 9th. Servers need looking at for broken chain.

**Comment by pietmolenaar** [comment]
I'm seeing the same here in four RTD projects, no PDF's or EPUBs generated since Oct. 9th; Output in log is identical to the latest versions that did build, latex says a pdf was generated, but probably not copied to the right location?

**Comment by sasha-carlos** [comment]
The same behaviour with downloads in http://findface.readthedocs.io/en/latest/.

**Comment by mcraig-ibme** [comment]
My existing projects are still working fine but not new ones. If it helps,  I have noticed the 'latest' version is missing from the overview version list in the non-working projects:

![image](https://user-images.githubusercontent.com/26383586/31762792-3d85601c-b4b4-11e7-9b63-b2380bd81ac1.png)

Also, in 'Admin->Versions', the 'latest' version is listed as 'Not built':

![image](https://user-images.githubusercontent.com/26383586/31762951-b7f5bf4a-b4b4-11e7-9e32-22fae0fac18d.png)

However it's been built several times:

![image](https://user-images.githubusercontent.com/26383586/31762973-c4ba155a-b4b4-11e7-9820-fcf01013de81.png)

Could there be some problem with identifying the version to publish?

**Comment by bloer** [comment]
Same problem in http://bgexplorer.readthedocs.io/en/latest/ . New project started today, build passed, but nothing in Downloads and homepage shows autogenerated index file.

**Comment by mcraig-ibme** [comment]
Here's something weird: I can only build and download these documents when I'm *not* logged in to RTD!
Of course they don't deploy to the web but you can download HTML/PDF etc.
But if I'm logged in, no downloads are listed.
Not sure if this might be relevant to the problem.

**Comment by vegu** [comment]
So i ran into the same problem as @mcraig-ibme, with the exact same symptoms, in my case it appears to have been a missing `index.md `

Adding that file and making sure it exists in `mkdocs.yml `fixed the issue for me

```
pages:
  - Home: index.md
```

Odd that it's not more vocal about this. Anyway, maybe it's the same issue on your end?

**Comment by mcraig-ibme** [comment]
I think it was! I'm using the `conf.py` method and RST but my main index file was *not* named `index.rst`.  So I renamed it to `index.rst` and changed the master doc in `conf.py` to:

    master_doc = 'index'

However my old master doc was specified correctly in `conf.py` so I would have expected it to work. Not clear if this is a bug or not, but it's clearly a nasty gotcha.

Many thanks @vegu
