### ISSUE TITLE
serve_docs fails with versions that have overlapping slug + project language

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3160]
I was able to somehow create a scenario where a version with a translation project returned two versions here in the version select below. We should make sure it's not possible to add or change a project language if it would create a conflicting scenario like this. Also, this shouldn't be `get` if we can't ensure a singular version returns.

/home/docs/checkouts/readthedocs-corporate/readthedocsinc/core/views.py in serve_docs at line 48

```python
    # here, the docs won't serve.
    versions = Version.objects.for_project(project)
    try:
        ver = versions.get(
            slug=version_slug,
            project__language=lang_slug
        )
    except (Version.DoesNotExist):
        try:
            ver = versions.get(
                project__slug=project.slug,
```

**Comment by stsewd** [comment]
I'm not sure if I understand this issue, maybe this was fixed with the recent changes on translations? Also, this seems something from the .com project

**Comment by stsewd** [comment]
The validation was added in https://github.com/rtfd/readthedocs.org/pull/3790

**Comment by agjohnson** [comment]
Reopening, this issue doesn't describe how translations are added, but how it is possible to set a project language in such a way that it would cause multiple versions to return. I believe this is how to reproduce:

* Add project A, language `en`
* Add project B, language `fr`
* Add project B as translation of project A
* Change project B language to `en`
* Version query above (and in rtd.org) will return 2 versions

I believe there are some sentry errors around this as well.

Marking needs replication to verify.

**Comment by humitos** [comment]
I didn't try it yet, but I remember that @stsewd's PR makes impossible this step with a validation on the form:

> Change project B language to en

IRC, the user is informed about this but, maybe I'm confused and this is _impossible_ from the translation page of project A, but not from the Admin page of project B. It worth a test.

**Comment by stsewd** [comment]
@agjohnson that was already fixed from both sides, admin panel and translations sections

![screenshot_2018-08-30 edit project read the docs](https://user-images.githubusercontent.com/4975310/44866164-12eed700-ac4a-11e8-96a0-906bf018eef4.png)

I'll leave it to you to close the issue.

**Comment by humitos** [comment]
@stsewd thanks for checking this. I'd say that we can close this issue.

**Comment by stsewd** [comment]
Just adding that 3 of those engines are included in the `texlive-full` package https://packages.debian.org/sid/texlive-full (Not, sure about `pLatext`, it is the same as `Plain Latex`?)
