### ISSUE TITLE
Increase timeout for psyplot and psy-maps

### ISSUE THREAD

**Issue by Chilipp** [rtfd/readthedocs.org#3165]
Thanks a lot for your fantastic platform!! For two projects, [psyplot](https://github.com/Chilipp/psyplot) and it's subproject [psy-maps](https://github.com/Chilipp/psy-maps) I am very often faced with the problem of the timeout after 900s. Both packages require to install the cartopy package via conda. The download of the necessary packages requires quite some time and then it is not enough left for the PDF and the EPUB documentation.

Could you please increase the timeout for both projects by 5 minutes (or 10 to be safe)?
Thanks a lot!

## Details

* Project URL: http://readthedocs.org/projects/psyplot/ and http://readthedocs.org/projects/psy-maps/
* Build URL (if applicable): http://readthedocs.org/projects/psyplot/builds/6118044/
* Read the Docs username (if applicable): Chilipp

## Expected Result

Build completion

## Actual Result

Error
Build exited due to time out

**Comment by Chilipp** [comment]
@RichardLitt and others. I know you have a lot to do and I really appreciate your work! Thanks for your great platform. Anyway, since I did not hear anything for the past 3 months since I opened this issue, I would like to know at least, whether it will be possible or whether I have to look for different solution.

**Comment by RichardLitt** [comment]
@agjohnson Any thoughts on this?

**Comment by Chilipp** [comment]
Dear @agjohnson and @RichardLitt,

I have to make some decisions and plans for the new release of this project by beginning of February, so since this issue is now 3.5 months old, I would really appreciate any comment on it. Can I stay on RTD or do I have to use a different platform?

Thanks for your help!
Philipp

**Comment by RichardLitt** [comment]
@ericholscher Any thoughts on this, too?

**Comment by ericholscher** [comment]
Sorry fro the delay here. Have you tried turning off pdf & epub builds, that should solve things in the short term.

**Comment by ericholscher** [comment]
I've raised the time limits to 1 hr.

**Comment by Chilipp** [comment]
Great! Thanks a lot :)
