### ISSUE TITLE
Sphinx HTML build with py3.x succeeds, but no ZIP or PDF file in Downloads

### ISSUE THREAD

**Issue by vlcinsky** [rtfd/readthedocs.org#3166]
## Details

* Project URL: https://readthedocs.org/projects/doit-tmp-doc/
* Build URL (if applicable): https://readthedocs.org/projects/doit-tmp-doc/builds/6123443/
* Read the Docs username (if applicable): vlcinsky

## Expected Result
After success with building Sphinx HTML I expect ZIP and ePub files present in project Downloads section.

## Actual Result
Build succeeds:

	python3.5 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/.cache/pip Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.5.3 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/checkouts/latest/requirements.txt
	cat docs/conf.py
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/sphinx-build -T -b readthedocssinglehtmllocalmedia -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/sphinx-build -b latex -D language=en -d _build/doctrees . _build/latex
	pdflatex -interaction=nonstopmode /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/checkouts/latest/docs/_build/latex/doit.tex
	makeindex -s python.ist doit.idx
	pdflatex -interaction=nonstopmode /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/checkouts/latest/docs/_build/latex/doit.tex
	mv -f /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/checkouts/latest/docs/_build/latex/doit.pdf /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/artifacts/latest/sphinx_pdf/doit-tmp-doc.pdf
	python /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/envs/latest/bin/sphinx-build -T -b epub -d _build/doctrees-epub -D language=en . _build/epub
	mv -f /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/checkouts/latest/docs/_build/epub/doit.epub /home/docs/checkouts/readthedocs.org/user_builds/doit-tmp-doc/artifacts/latest/sphinx_epub/doit-tmp-doc.epub 

Download section is empty even though build output seems to create ZIP and epub files and move it to downloads.

**Comment by ShawnDriscoll** [comment]
Been broken since the 9th.

**Comment by safwanrahman** [comment]
Seems like a issue in production. I have tried to reproduce it locally, but it does not reproduce locally.

**Comment by vlcinsky** [comment]
Tried to rebuild the doc now (clicking Build button) and the result is still the same as reported - no files in Download section.

We have decided to use our own build system for publishing the doc, so from our point of view it can be closed (as not resolved but not needed any more). But if can help to resolve some general problem with building the docs, we can keep it open and I may retry if there is any progress later on.

**Comment by RichardLitt** [comment]
Thanks for letting us know @vlcinsky. Let's keep this open until there is a fix for it, as it'll help others who have the same problem.

**Comment by ShawnDriscoll** [comment]
PDFs and EPUBs are generating now! YEY!

**Comment by mekrip** [comment]
PDF is generating nicely, but section numbers are missing in the PDF. 
In the local environment, the pdf has the sections numbers. 

Project : http://advance-python-tutorials.readthedocs.io/en/latest/index.html
PDF : https://media.readthedocs.org/pdf/advance-python-tutorials/latest/advance-python-tutorials.pdf

**Comment by vlcinsky** [comment]
@ShawnDriscoll  Thanks for your note.

My project is building downloads too so I close this issue.

@mekrip If you need to track the issue with missing section numbering, open a new one.
