### ISSUE TITLE
Weird loop that runs forever 

### ISSUE THREAD

**Issue by hvnsweeting** [rtfd/readthedocs.org#3167]
## Details

* Project URL: http://sqlalchemy.readthedocs.io/en/latest/
## Expected Result

See the doc of sqlalchemy

## Actual Result

A redirect and loop forever.

```
curl -L http://sqlalchemy.readthedocs.io/en/latest
<html>
<head>
<script>
window.location = 'http://sqlalchemy.readthedocs.io/en/latest/';
</script>

<!-- RTD Extra Head -->

<!-- 
Always link to the latest version, as canonical.
http://docs.readthedocs.org/en/latest/canonical.html
-->
<link rel="canonical" href="http://sqlalchemy.readthedocs.io/en/latest/" />

<link rel="stylesheet" href="https://media.readthedocs.org/css/readthedocs-doc-embed.css" type="text/css" />

<script type="text/javascript" src="_static/readthedocs-data.js"></script>

<!-- Add page-specific data, which must exist in the page js, not global -->
<script type="text/javascript">
READTHEDOCS_DATA['page'] = 'index' 		
READTHEDOCS_DATA['source_suffix'] = '.rst'
</script>

<script type="text/javascript" src="_static/readthedocs-dynamic-include.js"></script>

<!-- end RTD <extrahead> --></head>
<body>
Hopefully redirecting to <a href="http://sqlalchemy.readthedocs.io/en/latest/">http://sqlalchemy.readthedocs.io/en/latest/</a> !
</body>
</html>
```

**Comment by RichardLitt** [comment]
Replicated. Thanks for logging.

**Comment by safwanrahman** [comment]
I have gone through the source code of the [documentation](https://github.com/zzzeek/redirectthedocs) and it seems that its should redirect to the `canonical_url`. Which is the project url. So it become a infinity loop over there. For more information, you can see  #2267 and #1916

**Comment by safwanrahman** [comment]
@hvnsweeting the hacky way implemented by the project should work. Can you check with the maintainer if they have set the Canonical Domain the in the project [settings](https://readthedocs.org/dashboard/sqlalchemy/domains/)?
cc: @zzzeek

**Comment by zzzeek** [comment]
Please implement #2267.  #2267 was opened *eighteen months ago* and it has received *no response whatsoever* from any maintainers.   It is not fair that RTD provides no way whatsoever to leave once one has their userbase going there and the [hack](https://github.com/zzzeek/redirectthedocs) I made is completely stupid and doesn't work very well.

I added the canonical URL and the redirect is still not working.   I dont have time to constantly chase down RTD bugs (which is why I've moved off of it).

**Comment by zzzeek** [comment]
seems like it works now, perhaps it was caching.   but still.   #2267.  so simple.

**Comment by safwanrahman** [comment]
@hvnsweeting,  After @zzzeek added the canonical url, I have tested it and it seems to be working now. Can you please check and close the issue if that fixed?

**Comment by safwanrahman** [comment]
@zzzeek I will try to discuss with the maintainers to find a resolution of the issues.

**Comment by agjohnson** [comment]
> so simple

Contributions welcome!

**Comment by hvnsweeting** [comment]
It redirected me to http://docs.sqlalchemy.org/en/latest/ now, seems worked. Thank you all.
