### ISSUE TITLE
Different Online/offline PDF

### ISSUE THREAD

**Issue by mekrip** [rtfd/readthedocs.org#3168]
## Details

* Project URL: http://readthedocs.org/projects/fpga-designs-with-myhdl/
* Build URL (if applicable): http://fpga-designs-with-myhdl.readthedocs.io/en/latest/
* Read the Docs username (if applicable): PythonDSP

## Expected Result
* Online version is fine. But offline-html and PDF are not updated after 9th Oct.  
* Looks similar to https://github.com/rtfd/readthedocs.org/issues/3166
*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

I tried to load the document using new bitbucket repository and with new readthedoc url. Also, I created new local-git-repo to load it on bitbucket. 

Even for the fresh repository, the udpated date on the PDF is showing as 9-Oct; and only 3 chapters are shown in PDF/offline-html. 

Looks like not reading the file created after 9-Oct.

Duplicate Issue :  https://github.com/rtfd/readthedocs.org/issues/3166

**Comment by RichardLitt** [comment]
Thanks @mekrip. Why'd you close this, for future reference?

**Comment by mekrip** [comment]
@RichardLitt 
I think it is same as issue https://github.com/rtfd/readthedocs.org/issues/3166

**Comment by mekrip** [comment]
PDF is generating nicely, but section numbers are missing in the PDF.
In the local environment, the pdf has the sections numbers.

Project : http://fpga-designs-with-myhdl.readthedocs.io/en/latest/
PDF : https://media.readthedocs.org/pdf/fpga-designs-with-myhdl/latest/fpga-designs-with-myhdl.pdf

**Comment by mekrip** [comment]
Fixed.
