### ISSUE TITLE
Wiping has no effect

### ISSUE THREAD

**Issue by craig8** [rtfd/readthedocs.org#3170]
## Details

I have attempted to wipe the build and rebuild the master branch.  The only thing I can think of is that we did a force push on the master branch and perhaps readthedocs hasn't been able to figure that out.  All of the other branches are coming across swimmingly.  

* Project URL: https://github.com/VOLTTRON/volttron
* Build URL (if applicable): http://volttron.readthedocs.io/en/master/
* Read the Docs username (if applicable):  craig8

## Expected Result

A build should have been here

## Actual Result

The build was not here

**Comment by netflixhelp12** [comment]
support for netflix contact, netflix support, netflix tv support , fix problem for netflix, netflix problem, netflix phone number, netflix support number, netflix tech support, netflix technical support, tech support for netflix ,netflix connection, connect to netflix
Netflix Ui 122 Ps4,How To Install Netflix On Ps4,Playstation 4 Netflix Problems,Ps4 Netflix Problems Today,Netflix On Ps4 Issues,Netflix On Ps4 Issues,Netflix Nw-2-5,Netflix Down,Netflix Error Ui-122 Ps4, Netflix Error Ui-122 Ps3, Netflix Error Code Ui-122 Ps4, Netflix Code Ui-122 Ps3, Netflix Error Code Ui-122 On Ps3 
You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number.http://netflix-netflixsupport.com

**Comment by ericholscher** [comment]
I belive this should be fixed now. We have updated the wiping code to be more resilient.
