### ISSUE TITLE
local install readthedocs on our intranet, all links on the board redirect to readthedocs.org

### ISSUE THREAD

**Issue by wqshen** [rtfd/readthedocs.org#3172]
## Details
I am working on my intranet to install readthedocs, and it worked, but it also has some questions. 

The links on the board of docs pages is redirected to readthedocs.org, not our intranet, i don't know why, is it something need to be configured?

![image](https://user-images.githubusercontent.com/12339722/31765431-e9e1f5b8-b4f6-11e7-896a-b4fde0cef026.png)

**Comment by safwanrahman** [comment]
Have you changed the [`PRODUCTION_DOMAIN`](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/settings/dev.py#L12) in the settings?

By looking at the code, I am quite sure that changing the `PRODUCTION_DOMAIN` to correct path would solve the issue.

**Comment by wqshen** [comment]
Yes, it is worked
Thank you.

**Comment by RichardLitt** [comment]
For future reference: This is in the docs, here: https://docs.readthedocs.io/en/latest/settings.html. It may be advisable to reference this page elsewhere or change the flow of the information, as it wasn't clear here that the answer was already documented.
