### ISSUE TITLE
Subproject is project itself.

### ISSUE THREAD

**Issue by rhpvorderman** [rtfd/readthedocs.org#3173]
## Details

* Project URL: http://biopet-docs.readthedocs.io/projects/snptesttovcf/en/latest/
* Read the Docs username (if applicable): rhpvorderman

## Expected Result

Subproject can be removed if accidently refers to itself.

## Actual Result

Subproject can not be removed.
I accidently pointed our biopet project to be a subproject of biopet. (I wanted to add another project). Now I cannot add other subprojects to biopet anymore. I can not remove this circular dependency.
Help would be much appreciated.

**Comment by stsewd** [comment]
I was able to replicate this, I don't think we should allow this action in the first place.

**Comment by stsewd** [comment]
I was able to delete the subproject entering manually to the edit page. Here you can delete your subproject https://readthedocs.org/dashboard/biopet-docs/subprojects/snptesttovcf/edit/

**Comment by rhpvorderman** [comment]
Thanks for the workaround @stsewd ! Much appreciated!
I will close this issue since our problem is solved and the main problem is documented in a new issue. Thanks again!
