### ISSUE TITLE
Builds fail with mkdocs 0.17 because of deprecated `mkdocs json`

### ISSUE THREAD

**Issue by hfp** [rtfd/readthedocs.org#3174]
Two of my projects ([libxsmm](https://github.com/hfp/libxsmm), and [xconfigure](https://github.com/hfp/xconfigure)) rely on Mkdocs newer than v0.15, and manifested this per `requirements.txt`. However, `mkdocs>=0.16` (`requirements.txt`) broke with yesterday's release of MkDocs&#160;v0.17 because RTD invokes `mkdocs json` - see [release notes](http://www.mkdocs.org/about/release-notes/): "*The deprecated json command has been removed*". Workaround: adjust `requirements.txt` to `mkdocs>=0.16,<0.17`.

RTD: please review the actions needed to not rely on `mkdocs json`.

**Comment by DominikaK** [comment]
This happened to us as well in the RTD.com-hosted https://github.com/ezsystems/developer-documentation

**Comment by agjohnson** [comment]
Thanks for the report. No one has stepped up to help fix the search backend, so mkdocs search is going to remain in a broken state until a community effort can get behind integrating mkdocs with RTD properly.

**Comment by marcelstoer** [comment]
What MkDocs version does RTD use by default or put differently: how would I _find out_ which version it uses?

**Comment by marcelstoer** [comment]
Answering my own question...you find out if you pick any build (https://readthedocs.org -> Builds) and scroll to the end of the 2nd row:
![screen shot 2018-01-21 at 21 46 32](https://user-images.githubusercontent.com/624195/35198846-10386aba-fef5-11e7-8655-62d106a05d08.png)
If you want to change this you
- create a new file `rtd-requirements.txt` (or any other name) in the root of your repository
- put something like `mkdocs >= 0.16.3, < 0.17` into it
- go to https://readthedocs.org -> Admin -> Advanced settings and put that file name into the first text field

**Comment by marcelstoer** [comment]
This can be closed I guess as the default MkDocs was upgraded to 0.17.3 with #4041 and builds don't fail - at least not because of search.

**Comment by stsewd** [comment]
Yeah, rtd doesn't execute the `json` step anymore for mkdocs.
