### ISSUE TITLE
Text in the table of contents column overlaps the documentation

### ISSUE THREAD

**Issue by codeguru42** [rtfd/readthedocs.org#3176]
## Details

* Project URL: https://pytest-django.readthedocs.io/en/latest/helpers.html#helpers although I suspect this is system-wide and not specific to this particular project or page.

## Expected Result

Readable documentation which isn't garbled by the table of contents.

## Actual Result

![urcwk](https://user-images.githubusercontent.com/910753/31846707-12ea06bc-b5dd-11e7-8b7a-46f86a6ab694.png)

_Edited by @RichardLitt on 10-21 21:25 to include the screenshot previously linked._

**Comment by netflixhelp12** [comment]
support for netflix contact, netflix support, netflix tv support , fix problem for netflix, netflix problem, netflix phone number, netflix support number, netflix tech support, netflix technical support, tech support for netflix ,netflix connection, connect to netflix
Netflix Ui 122 Ps4,How To Install Netflix On Ps4,Playstation 4 Netflix Problems,Ps4 Netflix Problems Today,Netflix On Ps4 Issues,Netflix On Ps4 Issues,Netflix Nw-2-5,Netflix Down,Netflix Error Ui-122 Ps4, Netflix Error Ui-122 Ps3, Netflix Error Code Ui-122 Ps4, Netflix Code Ui-122 Ps3, Netflix Error Code Ui-122 On Ps3 
You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number.http://netflix-netflixsupport.com

**Comment by ericholscher** [comment]
This is a Sphinx theme bug, not something wrong with Read the Docs. It should be opened with the `alabater` theme.
