### ISSUE TITLE
Better User deletion

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#3182]
With #3175 we now have a way for users to mark themselves as wanting to be deleted, now we need to actually delete them. This could be done inline during delete, or as a batch job that runs after the web view returns.

We want to actually **delete** the User instance, but we need to confirm a couple things:

* Projects that the user _only_ owns are deleted. This is a [M2m](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L83), so we need to either *remove* them if there are multiple users, or *delete* the project if they are the only owner, so we don't end up with orphaned projects.

**Comment by ericholscher** [comment]
@agjohnson Anything else you can think of that attach to users? Looking at the code I see:

* FK: Comments - will be deleted
* FK: Bookmarks - will be deleted
* M2M: [Oauth connections](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/oauth/models.py#L38) - Believe these might need to be manually deleted (same logic, if only person in Org, delete, otherwise remove user)

**Comment by ericholscher** [comment]
We should also add a guide entry or something that is Googleable, that shows how to do this (http://docs.readthedocs.io/en/latest/guides/index.html)

**Comment by agjohnson** [comment]
Projects is the big one. There probably isn't a good reason why oauth models shouldn't be cascading if they aren't already -- those are all single user relations, but might have to be m2m for some other reason.

**Comment by shacharoo** [comment]
Hey there,
The currently implemented "delete" feature is misleading.
I wanted to change my username, but I saw that it's impossible, so i went on and deleted (my empty) account thinking that I'd be able to create a new one with a new username. Nowhere does it say that the account is only "disabled".
Now I can't re-register because my email is in use (because the account wasn't actually deleted), nor can I reactivate the account. Something needs to be done here 😄 

And on a personal note, If someone could hack the DB a bit and reactivate my account in the meantime, it would be delightful 🙏 Is there a support email anywhere? Couldn't find it.

Thanks,
Shachar.

**Comment by safwanrahman** [comment]
Hey @shacharoo, Apologies for the problem you are facing. Can you open a new issue about your problem so that we can ask out Operation teams to change the email or do other necessary things for you?
In the meantime, I am hoping to create a patch ASAP that will cover your use case.

**Comment by shacharoo** [comment]
Will do @safwanrahman, thanks!

**Comment by netflixhelp12** [comment]
Netflix Ui 122 Ps4 | Netflix support | How To Install Netflix On Ps4 | Playstation 4 Netflix Problems | Ps4 Netflix Problems Today | Netflix On Ps4 Issues | http://netflix-netflixsupport.com | Netflix Nw-2-5 | Netflix Down | Netflix Error Ui-122 Ps4 | Netflix Error Ui-122 Ps3 | Netflix Error Code Ui-122 Ps4 | Netflix Code Ui-122 Ps3 | Netflix Error Code Ui-122 On Ps3 http://netflix-netflixsupport.com

You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number. http://netflix-netflixsupport.com
