### ISSUE TITLE
Latest builds failing (lib-dynload file already exists)

### ISSUE THREAD

**Issue by gajop** [rtfd/readthedocs.org#3183]
## Details

* Project URL:  http://springboard-core.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/springboard-core/builds/6167062/
* Read the Docs username (if applicable): gajop

## Expected Result

Builds should work as normally.

## Actual Result

Builds seem to fail for bizarre reasons.
```
OSError: [Errno 17] File exists: '/home/docs/checkouts/readthedocs.org/user_builds/springboard-core/envs/latest/lib/python2.7/lib-dynload'
```

**Comment by bsumlin** [comment]
Same exact problem here, for about the last 5 hours.

`python3.5 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/pymiescatt/envs/latest`

**Comment by dsblank** [comment]
Seeing this too:

https://readthedocs.org/projects/conx/builds/6170070/

**Comment by dsblank** [comment]
Looks like it has been fixed?

**Comment by bsumlin** [comment]
Hasn't been fixed for me.

`python3.5 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/pymiescatt/envs/latest
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 351, in copyfile
    os.symlink(srcpath, dest)
FileExistsError: [Errno 17] File exists: '/usr/lib/python3.5/lib-dynload' -> '/home/docs/checkouts/readthedocs.org/user_builds/pymiescatt/envs/latest/lib/python3.5/lib-dynload'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 1130, in install_python
    copyfile(join(stdlib_dir, fn), join(lib_dir, fn), symlink)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 354, in copyfile
    copyfileordir(src, dest, symlink)
  File "/usr/local/lib/python3.5/dist-packages/virtualenv.py", line 329, in copyfileordir
    shutil.copytree(src, dest, symlink)
  File "/usr/lib/python3.5/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/usr/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/docs/checkouts/readthedocs.org/user_builds/pymiescatt/envs/latest/lib/python3.5/lib-dynload'
Using base prefix '/usr'`

**Comment by dhermes** [comment]
Same problem here. Some examples:

- https://readthedocs.org/projects/bezier/builds/6173086/
- https://readthedocs.org/projects/bezier/builds/6171629/
- https://readthedocs.org/projects/bezier/builds/6167853/
- https://readthedocs.org/projects/bezier/builds/6167745/

**Comment by gajop** [comment]
It seems to have been fixed for me (https://readthedocs.org/projects/springboard-core/builds/6173917/ passed). I haven't done anything, except reissuing the build from the online interface.
I have no idea if the fix is going to persist though.

**Comment by Raphux** [comment]
Same problem here since this afternoon : 
https://readthedocs.org/projects/passhport-fr/builds/

**Comment by edmorley** [comment]
We saw this last week too:
https://readthedocs.org/projects/treeherder/builds/6178579/
https://readthedocs.org/projects/treeherder/builds/6176994/
https://readthedocs.org/projects/treeherder/builds/6176988/

**Comment by stsewd** [comment]
Looks like all the docs here now build with no problem, anyone still with this issue?

I think this is a virtualenv error, when running parallel processes (probably similar to https://github.com/conda/conda/issues/2837)

**Comment by dhermes** [comment]
> anyone still with this issue?

Nope

**Comment by RichardLitt** [comment]
Let's reopen if anyone still has it. Thanks all.
