### ISSUE TITLE
Remove `gold` app

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#3186]
Currently, we have the `gold` app in the RTD codebase. We should break it out into a separate app, since it isn't relevant to other installs of RTD.

**Comment by netflixhelp12** [comment]
Netflix Ui 122 Ps4 | Netflix support | How To Install Netflix On Ps4 | Playstation 4 Netflix Problems | Ps4 Netflix Problems Today | Netflix On Ps4 Issues | http://netflix-netflixsupport.com | Netflix Nw-2-5 | Netflix Down | Netflix Error Ui-122 Ps4 | Netflix Error Ui-122 Ps3 | Netflix Error Code Ui-122 Ps4 | Netflix Code Ui-122 Ps3 | Netflix Error Code Ui-122 On Ps3 http://netflix-netflixsupport.com

You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number. http://netflix-netflixsupport.com

**Comment by shreyateeza** [comment]
@ericholscher Please explain me how this could be implemented. I am new here and would like to contribute to it.

**Comment by Tikam02** [comment]
we have to do complete removal of 'gold' app?? @ericholscher

**Comment by fiennyangeln** [comment]
Hi, I want to take this issue and I was thinking of moving the gold app to the `profiles` app. Is it correct?

**Comment by RichardLitt** [comment]
It sounds like it should be in it's own app, perhaps called `gold`. But I'm not sure.

**Comment by humitos** [comment]
@agjohnson what's the idea here? to move the `gold` app to the `readthedocs-ext` repo since it's not tied to RTD as software project?

**Comment by fiennyangeln** [comment]
@RichardLitt does it mean it needs a new repo?

**Comment by RichardLitt** [comment]
Again, I'm not sure. Let's wait on one of the main maintainers to answer.

**Comment by gaborbernat** [comment]
@RichardLitt whoa re the main maintainers?

**Comment by stsewd** [comment]
@gaborbernat you can see it here https://docs.readthedocs.io/en/latest/team.html

**Comment by RichardLitt** [comment]
@rtfd/core thoughts?

**Comment by agjohnson** [comment]
This isn't actionable by non-core folks, so not a good first issue.

**Comment by dojutsu-user** [comment]
Is this still valid?
I would like to work on this.
Also, what exactly is required here? Breaking gold app in multiple small apps or removing gold app and merging the code in other apps?

**Comment by stsewd** [comment]
@dojutsu-user this is still valid, but only actionable for the core team (because the code needs to be moved to a private repo)

**Comment by ericholscher** [comment]
I think we should close it -- we're not going to remove `gold` any time soon, and likely won't put more work into it until we remove it :)
