### ISSUE TITLE
Unable to register after deleting my account

### ISSUE THREAD

**Issue by shacharoo** [rtfd/readthedocs.org#3189]
I recently changed my username all across my accounts (github, linkedin, etc) and wanted to change it in RTD as well. Lucky for me I didn't have any projects yet, so I went ahead and deleted my account, thinking that I'd be able to sign up again using a different username for my email address.

Little did I know, the "delete" action only deactivates your account and doesn't remove the user from the DB, so when trying to sign up I got an error that there's an account associated with my email address. Boo.

Would it be possible to delete my old account, or at least change it's email address to `foo@bar.com` so I'd be able to sign up again? 😄 

The username is `farmersez` and email is `shachar.o@gmail.com`.

Other than that, I believe that there should be an option to activate accounts since deleting them doesn't really do anything 😄 

Thanks,
Shachar.

**Comment by shacharoo** [comment]
Tagging @safwanrahman because of reasons.

**Comment by ryohji-ikebe** [comment]
Hi,
I have faced up the same problem.
My old account name is 'ryohji', and i wanted to rename account name.
So i delete my own and try to create new one with same e-mail address, but https://readthedocs.org/ says `A user is already registered with this e-mail address.`; and I cant find the way to reactivate old one. :cry:

So, my first need of your support: please reactivate the account 'ryohji'; (renaming is not big issue to be solved)

I know, you have the BIG considerations to implement `delete` operation, so it will be helpful to users that deliver `reactivate` button for deactivate-flagged account.

Thanks for your supports!

**Comment by shacharoo** [comment]
Hey @safwanrahman , the main issue was fixed in #3214, but my account is still in "limbo" 😄 
I'm guessing there are many other accounts like that. Would it be possible to purge the DB from them (me included because it's been more than a month 🙏 ).
Thanks!

**Comment by safwanrahman** [comment]
@shacharoo yes, surely. We are determining if all the inactive account should be deleted. As you have requested for deletation, I will ask someone from the operation team to delete.

**Comment by safwanrahman** [comment]
@agjohnson Can you please delete the account?

**Comment by agjohnson** [comment]
@shacharoo @ryohji-ikebe Both users are now re-activated. Lets us know if you run into problems removing, I believe there is a bug on removal (sorry in advance for making you our test subjects here).

**Comment by ryohji-ikebe** [comment]
@agjohnson Thanks to your kind work of my account re-activation! 😄 
I have checked my account lives back.

And OK, I will tell you if I noticed there is any problems seeming caused by de-activation.

Thank you, again!
--
Ryohji

**Comment by shacharoo** [comment]
@agjohnson , I've successfully logged in as farmersez, deleted my account and signed up again as shacharoo. 
I'm not sure I'm the best guinea pig though since I didn't have any active project set up 😄  
Thanks!

**Comment by RichardLitt** [comment]
Thanks for letting us know, both of you! Glad this was resolved. Ping us if there are more issues.

**Comment by swati-rashmi** [comment]
Even i am facing the same issue....I deleted my account.Now i want to use the same email with different username to create a fresh account.But github says **'email invalid or taken'**.
Can somebody help me with this.
Can my account be deleted **swati-rashmi01**

**Comment by priya-tiwari** [comment]
Hi @RichardLitt @agjohnson ,
I created an account using my email "prtiwari@vmware.com" with username "breakeo". Later deleted that account so that I can add my company mail to my current account. But now I'm unable to add the email in my current account as it says "Email already in use". Please delete my previous account from the db as well.

**Comment by stsewd** [comment]
@priya-tiwari please contact us via email at support@readthedocs.org

**Comment by agjohnson** [comment]
Folks hitting this issue should reach out to us at `support@readthedocs.org`, we can help there. We don't usually monitor closed issues for new issue reports.
