### ISSUE TITLE
Support opt in to latest build image, automate wiping of environment

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3190]
I think providing an option to opt in to the latest build environment makes sense, probably through our yaml config, so it can be a per-version option. The hardest part about this however is if the environment changes, the python lib path gets damaged and builds will fail. We need a mechanism that:

- [ ] Detects the change in environment
- [ ] Wipes the environment if the build image is changed

Additional points of design up for interpretation:

- [ ] What does additional spec added to readthedocs.yml look like -- that is, we don't want to allow arbitrary image names here, so just the tag of `readthedocs/build` image?
- [ ] Do we just do this automatically with `python[version] == 3.6` in the rtd.yml?

This will touch the config file, our builder code. We could perhaps use a more generic way of wiping a build when the environment changes, as this also happens on version change.

**Comment by humitos** [comment]
I think this issue can be closed, since it's already implemented in #3432. Is there any of the questions/ideas posted here missing?

**Comment by agjohnson** [comment]
Yup! No one resolved this issue with an attached PR. Closing this.
