### ISSUE TITLE
build failing complaining numpy not installed, when it is ...

### ISSUE THREAD

**Issue by JackWalpole** [rtfd/readthedocs.org#3191]
## Details

Can't get a successful build.  Apparently obspy is failing to be installed because it needs numpy, but numpy is installed up top.  What's going on? 

> Collecting numpy (from -r docs/doc-requirements.txt (line 5))
>   Using cached numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl
> Collecting matplotlib (from -r docs/doc-requirements.txt (line 6))
>   Using cached matplotlib-2.1.0-cp35-cp35m-manylinux1_x86_64.whl
> Collecting scipy (from -r docs/doc-requirements.txt (line 7))
>   Downloading scipy-1.0.0-cp35-cp35m-manylinux1_x86_64.whl (49.6MB)
> Collecting nb2plots (from -r docs/doc-requirements.txt (line 8))
>   Using cached nb2plots-0.5.2.zip
> Collecting obspy (from -r docs/doc-requirements.txt (line 9))
>   Using cached obspy-1.0.3.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "/tmp/pip-build-molsc2j4/obspy/setup.py", line 33, in <module>
>         import numpy  # @UnusedImport # NOQA
>     ImportError: No module named 'numpy'
>     
>     During handling of the above exception, another exception occurred:
>     
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-molsc2j4/obspy/setup.py", line 37, in <module>
>         raise ImportError(msg)
>     ImportError: No module named numpy. Please install numpy first, it is needed before installing ObsPy.
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-molsc2j4/obspy/

* Project URL:  https://readthedocs.org/projects/splitwavepy
* Build URL (if applicable): https://readthedocs.org/projects/splitwavepy/builds/6176932/
* Read the Docs username (if applicable): JackWalpole

**Comment by agjohnson** [comment]
Not sure, this looks like a packaging problem, not a RTD specific issue. I'm not sure why the package is trying to import a dependency on setup.py, but that seems like A Bad Idea.

Closing here, but feel free to reopen if there is any specific actions we can take here.
