### ISSUE TITLE
Transfer ownership of django-bootstrap4 on readtehdocs.io

### ISSUE THREAD

**Issue by dyve** [rtfd/readthedocs.org#3195]
## Details

* Project URL: https://readthedocs.org/projects/django-bootstrap4/
* Read the Docs username (if applicable): dyve

Hi, user @bitkits has prematurely made a fork of our project and claimed the logical project name on readthedocs.org. Attempts to contact bitkits have failed.

Is it possible to transfer ownership of https://readthedocs.org/projects/django-bootstrap4/ to @dyve?

This is the original bootstrap3 project, which has a corresponding readthedocs url:
https://github.com/dyve/django-bootstrap3

This is the new bootstrap4 project (zostera is my company which has adopted the project)
https://github.com/zostera/django-bootstrap4

**Comment by safwanrahman** [comment]
Please mention the username of readthedocs

**Comment by dyve** [comment]
The current owner on readthedocs is https://readthedocs.org/profiles/bitkits/

**Comment by netflixhelp12** [comment]
support for netflix contact, netflix support, netflix tv support , fix problem for netflix, netflix problem, netflix phone number,http://netflix-netflixsupport.com, netflix support number, netflix tech support, netflix technical support, tech support for netflix ,netflix connection, connect to netflix http://netflix-netflixsupport.com
Netflix Ui 122 Ps4,How To Install Netflix On Ps4,Playstation 4 Netflix Problems, http://netflix-netflixsupport.com,Ps4 Netflix Problems Today,Netflix On Ps4 Issues,Netflix On Ps4 Issues,Netflix Nw-2-5,Netflix Down,Netflix Error Ui-122 Ps4, Netflix Error Ui-122 Ps3,http://netflix-netflixsupport.com, Netflix Error Code Ui-122 Ps4, Netflix Code Ui-122 Ps3, Netflix Error Code Ui-122 On Ps3 http://netflix-netflixsupport.com
You’re facing any Technical problem for Netflix.We provide you Netflix Account Support Service 1844-777-7886 by Phone Call Toll Free Customer Care Support Contact Number. http://netflix-netflixsupport.com

**Comment by jieter** [comment]
@safwanrahman what is the status on this? Would be very nice if we could put proper docs on readthedocs.org.

**Comment by stsewd** [comment]
@jieter there is a policy for this now http://docs.readthedocs.io/en/latest/abandoned-projects.html#name-conflict-resolution-for-active-projects

**Comment by dyve** [comment]
@safwanrahman @stsewd It's good that there is a policy. This request predated the policy, and some help would very really be appreciated. The project in question is a fork of the `django-bootstrap3` project that we maintain (under @dyve instead of under @zostera). The owner @bitkits has not responded (and has turned into "nobody" on GitHub as far as commits go). The last activity on GitHub is 10 months ago, the initial fork with 2 small commits:
https://github.com/bitkits/bootstrap4-django/commits/develop

<img width="1031" alt="schermafbeelding 2018-01-04 om 06 39 42" src="https://user-images.githubusercontent.com/82315/34551443-3294eca2-f11a-11e7-9bfe-45d679b0a7fa.png">

So we have someone who forked the Bootstrap3 project 10 months ago, changed the documentation and never responded to any contact attempts since then (we started this conversation in May 2017). we think @bitkits means well but is somehow not reading this.

This issue was opened before there was a policy, at the request of @rtfd staff. We would really like to

**Comment by safwanrahman** [comment]
Seems like this issue has been resolved. [django-bootstrap4](https://readthedocs.org/projects/django-bootstrap/) now belongs to @dyve. Thanks a lot for hosting your documentation at Read The Docs.

**Comment by dyve** [comment]
👍 Yes, this has been handled very well, thanks all!
