### ISSUE TITLE
Remove copyright application

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3199]
This was brought up in review and not handled. Doesn't look like we need it any longer?

**Comment by kikisdeliveryservice** [comment]
Hi! I'm new to rtd.  Is this referring to removing from base.py?

**Comment by agjohnson** [comment]
Greetings! 👋

It is, though the `copyright` application is likely called somewhere else in code as well. It shouldn't take much work at all, but I haven't looked into removing this yet.

If you want to try removing this, our development installation guide is here:
http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs

**Comment by agjohnson** [comment]
Original PR here: #1300

**Comment by kikisdeliveryservice** [comment]
Cool!  I'lll give it a try =)

**Comment by stsewd** [comment]
I would like to do an PR, or are you working on this, @kikisdeliveryservice?
