### ISSUE TITLE
please reactivate account

### ISSUE THREAD

**Issue by BurntWill** [rtfd/readthedocs.org#3209]
please reactivate my account OpenPavilion (account is currently inactive)

**Comment by OpenPavilion** [comment]
Would you please reactivate my account "OpenPavlion" ?

**Comment by RichardLitt** [comment]
@ericholscher Gentle ping.

**Comment by safwanrahman** [comment]
@humitos Is it possible to reactivate the account?

**Comment by humitos** [comment]
@BurntWill @OpenPavilion what do you mean by "reactive"? What's the problem with that account?

If you don't recall the password, you can reset it.

**Comment by safwanrahman** [comment]
@humitos In the past, deleting a account would make the account inactive. That was fixed later on.
So the account maybe become `is_active=False`

**Comment by humitos** [comment]
Thanks @safwanrahman! I just did that. Please, @BurntWill @OpenPavilion check that your account is active again.

Feel free to re-open the issue if there still a problem.
