### ISSUE TITLE
Unable to connect GitHub account to RTD account

### ISSUE THREAD

**Issue by ghost** [rtfd/readthedocs.org#3211]
I'm having an issue connecting this GH account to my RTD account. It says it's connected to another account, however I have no idea the username or email of whatever RTD account that would be. If someone could force the other account to disconnect or even possibly delete that account, I'd appreciate it!

**Comment by stsewd** [comment]
I think this is the user https://readthedocs.org/profiles/ghost/

**Comment by RichardLitt** [comment]
I'm not sure - @ghost is what GitHub calls deleted users. I think this can be closed.
