### ISSUE TITLE
Builds timing out in the build phase, but no logs available from that phase

### ISSUE THREAD

**Issue by juanrubio** [rtfd/readthedocs.org#3213]
## Details

* Project URL: https://readthedocs.org/projects/tizonia-openmax-il/
* Build URL (if applicable): https://readthedocs.org/projects/tizonia-openmax-il/builds/6202180/
* Read the Docs username (if applicable): tizonia

## Expected Result

Builds are being killed after 900 seconds and I would expect the logs from the execution up to that point to be available for inspection.

## Actual Result

The build is killed in the build stage, and the logs from that stage are not available. The last stage that have its logs available is
```
cat docs/sphinx-src/conf.py
```

A few notes:
- My project uses breathe and doxygen to produce embedded C API info. 
- The build process, i.e. doxygen xml + sphinx generation takes in my PC around 45 seconds.
- The last successful RTD build took 335 seconds and was this one here:
https://readthedocs.org/projects/tizonia-openmax-il/builds/5919677/
- No major sphinx configuration changes since the last successful build. Changes in the C/C++ code base only (a couple of extra thousand lines code).

**Comment by juanrubio** [comment]
I've noticed #3122. 

I'm rebuilding without PDF to see if that fixes the timeout issue.

**Comment by juanrubio** [comment]
OK, so that new build (no PDF) still has failed in the build phase, but this time, the logs from that phase have showed up in the site:
https://readthedocs.org/projects/tizonia-openmax-il/builds/6202844/
```
building [readthedocs]: targets for 59 source files that are out of date
updating environment: 61 added, 0 changed, 0 removed
reading sources... [  1%] development/BUILDING
reading sources... [  3%] development/clients/clients
reading sources... [  4%] development/clients/libtizdirble
reading sources... [  6%] development/clients/libtizgmusic
reading sources... [  8%] development/clients/libtizsoundcloud
reading sources... [  9%] development/clients/libtizyoutube
Killed
```

Any idea on why the build stage takes 588 seconds while on my pc it's less than 50?. Anything that I can do on my side to speed this up?

**Comment by stsewd** [comment]
For the command not showing I opened https://github.com/rtfd/readthedocs.org/issues/4288.

We migrate to Azure recently, we have faster builders now, could you test if your project is still falling?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, you can check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by juanrubio** [comment]
Sorry, I forgot to report back!. Yes, builds are faster now. My builds are now completing in under 50 seconds. Thanks!.
