### ISSUE TITLE
Allow skipping submodule clone

### ISSUE THREAD

**Issue by bendk** [rtfd/readthedocs.org#3215]
## Details

* Project URL: https://github.com/pculture/unisubs
* Build URL (if applicable): https://readthedocs.org/projects/amara/builds/6204577/
* Read the Docs username (if applicable): bendk

## Expected Result

Documentation to build

## Actual Result

The build process fails when checking out a submodule.  That's because it's a optional private repository.  It's not needed in general to run the app, and certainly not to build the documentation.

It would be great to have the option to skip submodule cloning for certain submodules, or altogether.  This would allow our builds to work again.

**Comment by stsewd** [comment]
I think this feature is on the plans https://github.com/rtfd/readthedocs-build/issues/30

**Comment by agjohnson** [comment]
For now, the most basic for of this change is to look for a `.gitmodules` and only conditionally run the submodule operations if we have submodules in the repository.

This would also address one of the issues in #3520, where i think we're going to have a lot of noisy commands that we can prune from the build output list.

**Comment by jerome-labbe-sb** [comment]
Hi, since the last update it's impossible for us to build our documentation anymore...
Just like OP, we need an option to skip submodules while having a .gitmodules file in our repo

**Comment by stsewd** [comment]
@jerome-labbe-sb maybe your problem is related to https://github.com/rtfd/readthedocs.org/issues/3707#issuecomment-369636647? By @humitos I know the rtd team is working on solving that problem.

**Comment by jerome-labbe-sb** [comment]
@stsewd unfortunately it doesn't seem to be related...

**Comment by stsewd** [comment]
@jerome-labbe-sb you can fill a new issue with more details about your problem, so we can help you.

**Comment by humitos** [comment]
@bendk Hi! We have a temporal flag to skip the checkout of all the submodules, so I added that flag to your `amara` project.

Later, when the PR pointed by @stsewd is merged, you will be able to configure it by yourself.

I'm closing this issue. Please, let me know if that fixes your problem or not.

**Comment by bendk** [comment]
Looks good so far, my first build failed but it was unrelated to the submodules.  Thanks for the good work!
