### ISSUE TITLE
Deleted test project still being hosted on RTD and indexed by google

### ISSUE THREAD

**Issue by markcmiller86** [rtfd/readthedocs.org#3224]
A wound up going through several iterations and a few project instantiations before I got something working and I was happy with.

I thought that using the 'delete' button in the project admin page of RTD would remove the generated documentation that RTD was hosting. But, I deleted that project a week ago and RTD is still hosting those pages and google is still indexing them.

I think I even 'wiped' the version before deleting the associated RTD project.

I need the content hosted here, http://visit-users-manual-test.readthedocs.io/en/latest/index.html is the stuff I wanted deleted...that whole doc tree there.

Strangly, although I deleted the project, I can still get to *some* of its pages through this link on RTD...

https://readthedocs.org/projects/visit-users-manual-test/

But, there is no 'Admin' button there any more. I assume that is becuase I deleted it.

The problem is that we're now hosting our manual correctly on RTD but at a different URL and this old stuff is out of date and confusing to anyone who stumbles into it (which is highly likely due to google showing it top in searches).

Can you help?

**Comment by ericholscher** [comment]
The project isn't deleted, it's still on the site: https://readthedocs.org/profiles/markcmiller86A/

**Comment by ericholscher** [comment]
Owned by that user

**Comment by markcmiller86** [comment]
Ah, ok, that user was actually *me* during a time that I had forgotten my password and the password reset functionality was not working. So, I guess I need to log in as myself as that user and delete that project from there?

**Comment by markcmiller86** [comment]
Ok, so here's the problem. That user is *me*. But, I don't remember the password for that account. And, I am pretty sure I have only *one* email associated with both my *working* account there and this old/stale account. So, if I *reset* the password, what happens? Does it reset only the old/stale account, only my new/working account, both?

**Comment by ericholscher** [comment]
I can just delete the user & project, if that works?

**Comment by markcmiller86** [comment]
That works ok for me but am wondering about one thing... Is it possible just to create a single page doc there with a link pointing to the "correct" stuff here, http://visit-sphinx-user-manual.readthedocs.io/en/latest/index.html. If not very easy, then yes, please delete that old stuff associated with username "markcmiller86A" and hosted at http://visit-users-manual-test.readthedocs.io/en/latest/index.html.

And, thanks so much for the help!

**Comment by ericholscher** [comment]
:+1: -- deleting the HTML might take a few hours, but projects should be gone.

**Comment by markcmiller86** [comment]
Thanks so much for the help!

**Comment by markcmiller86** [comment]
> @ericholscher deleting the HTML might take a few hours, but projects should be gone.

FYI...Its been almost 24 hours and the html still appears to be there. After deleting all cached pages from my browser, I can still get to it.

**Comment by markcmiller86** [comment]
@ericholscher for whatever reason, since having this old/stale user account deleted, the last two builds of documentation associated with the new/correct project are hanging in the "cloning" phase. Is this potentially related to the old user account deletion? Reason I ask is that that old user account and project was building from the same subversion repo and branch.

**Comment by markcmiller86** [comment]
@ericholscher apologies for being a pest but am preparing for Super Computing conference and would like this old content to be totally removed. It doesn't look like deleting the old user account for markcmiller86A was sufficient. That old content is still there. Can this be deleted...

http://visit-users-manual-test.readthedocs.io/en/latest/index.html

**Comment by ericholscher** [comment]
Should be deleted now.

**Comment by markcmiller86** [comment]
Ok, I confirm that now. Thanks so much. Sorry to be such a pest.
