### ISSUE TITLE
jquery-migrate version not compatible with jquery 3.0

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3226]
Through our extension, we are using `jquery-migrate` v1.2.1, but this is not compatible with jquery 3.0. I don't know if there is any strong reason why v1.2.1 is used here, but this can likely be upgraded to at least 1.12.x.

Some notes:

* We can't remove old versions of this file because old documentation will still reference these files
* I'm not sure of the historical significance of jquery-migrate, it might be worth exploring if it's needed still

**Comment by davidfischer** [comment]
> I'm not sure of the historical significance of jquery-migrate, it might be worth exploring if it's needed still

I have no idea if this is still needed but I would like to get rid of it. 

* As far as I can tell, nothing Read the Docs does relies on this.
* It is not included by Sphinx by default in local docs builds.
* MkDocs builds on Read the Docs do not include this at all.
* Removing it would simplify https://github.com/rtfd/readthedocs-sphinx-ext
