### ISSUE TITLE
verbosity option in readthedocs.yml

### ISSUE THREAD

**Issue by markcmiller86** [rtfd/readthedocs.org#3228]
When builds fail on RTD servers, there is very little in the way of information feedback that would allow someone to diagnose what failed and why.

Is there any easy way to support a `verbose:` option in readthedocs.yml? A simple true/false may be suffucient with false producing the defualt (very little output observable via the browser) and true producing literally *all* the stdout/stderr that is generated. Or maybe a `verbosity` option with various pre-defined levels.

Perhaps another option instead of hosting this content within RTD browsed project pages would be an `verbose_email` option that tells RTD servers to capture all output and then email to the specified address.

This would greatly help end-user ability to self-debug build problems freeing RTD development team from having to paw through and field build questions.

**Comment by safwanrahman** [comment]
The full tracelog of build error is in the API. Have you tried that?

**Comment by markcmiller86** [comment]
> @safwanrahman The full tracelog of build error is in the API. Have you tried that?

No. API? Perhaps I am ignorant but I am not using an application programming interface at least not directly. I imported a subversion branch via the RTD web pages and either ping the RTD servers to start a build or hit the build button manually. And, what I see during that processes is a very limited amount of information regarding what is happening. In particular, when things hang -- as they are now during cloning #3224, I get no information as to why, what is happening.  Where in that workflow is there an API?

**Comment by safwanrahman** [comment]
Currently, only the error tracelog is showing in the UI. But If you want more information of your build, you can get it from the API. I accept that there should be a way to see in the UI also.

Your build: https://readthedocs.org/projects/visit-sphinx-user-manual/builds/6224090/
API: https://readthedocs.org/api/v2/build/6224090/

**Comment by markcmiller86** [comment]
Oh, thats (https://readthedocs.org/api/v2/build/6224090/) awesome! I guess I didn't get far enough in the documentation to know there was another path I could go to to see the details. Thanks so much!

**Comment by safwanrahman** [comment]
Its actually in the UI. you need to click on the tracelog line. I think there are some CSS problem that making the full tracelog not showing there.
<img width="998" alt="screen shot 2017-11-05 at 1 42 21 am" src="https://user-images.githubusercontent.com/7114151/32408878-a6f7f668-c1ca-11e7-9ab4-91b952baacd2.png">

**Comment by willingc** [comment]
@markcmiller86 It looks like @safwanrahman has answered your request with two ways to review build information for debugging. Would you like to close this issue? Thanks.

**Comment by willingc** [comment]
Thanks @markcmiller86 👍
