### ISSUE TITLE
Injected footer in custom sphinx theme 

### ISSUE THREAD

**Issue by autophagy** [rtfd/readthedocs.org#3233]
I'm currently building a custom Sphinx theme to use with my projects hosted on readthedocs. At the moment, RTD currently injects this footer into the bottom of the page when build on RTD: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/templates/restapi/footer.html

Is there any way of controlling where in the HTML of the page this will be injected? Is there any way to prevent this from being inserted in the first place (like, being a Gold Member?). I couldn't find anything in the FAQs about it.

**Comment by RichardLitt** [comment]
Thanks, @Autophagy! When we figure this out (I don't know, or I'd help), we should make sure to add this to the FAQ.

**Comment by stsewd** [comment]
I believe that this is a rtd feature, if we hide this, rtd will not provide any value... But I think this should be possible to remove with some js or css

**Comment by humitos** [comment]
@autophagy Read the Docs injects the HTML returned by the `/footer_html` API call into `div.rst-other-versions`. If you remove that element from your theme, RTD won't be able to inject it.

What's the use case you want this for? Why would you like to hide that menu?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information :).
