### ISSUE TITLE
Account is inactive

### ISSUE THREAD

**Issue by makixx** [rtfd/readthedocs.org#3241]
I made a new account by the name of "maki" and I forgot to use a capital letter in my username. I decided to delete it so I could make "Maki" instead. It says account is inactive and I cant login anymore!

**Comment by safwanrahman** [comment]
@agjohnson Can you please delete the account?

**Comment by agjohnson** [comment]
User `maki` is active, but I didn't change this. Are you still having trouble logging in @makixx ?

**Comment by makixx** [comment]
Nvm, the website has been updated since the last time I visited it. I deleted both "maki" and "MakiXx", then made a new account "Maki"

**Comment by RichardLitt** [comment]
Thanks for updating us. 👍
