### ISSUE TITLE
Build passed but I can't see the documentation (maze screen)

### ISSUE THREAD

**Issue by dialex** [rtfd/readthedocs.org#3246]
## Details

* Repo URL: https://bitbucket.org/dialexnunes/start-testing/
* Docs URL (if applicable): https://start-testing.readthedocs.io/en/latest/
* Read the Docs username (if applicable): dialex

## Expected Result

See a sidebar with links to each markdown page. A default page with some markdown rendered.

## Actual Result

The empty maze screen. Similar as #2356.
All builds passed (latest and master) though.

<img width="811" alt="screen shot 2017-11-11 at 14 55 52" src="https://user-images.githubusercontent.com/2140450/32690580-e9e40bda-c6f0-11e7-849d-7843d1b0666a.png">

**Comment by madskinner** [comment]
repro URL: https://github.com/madskinner/pub2sd/
docs URL: https://pub2sd.readthedocs.io/en/latest/
readthedocs username: silseb

I'm getting the same issue the build has passed but only get empty maze screen.

**Comment by dialex** [comment]
Please help?

**Comment by dialex** [comment]
Should I give up on your product?

**Comment by stsewd** [comment]
@dialex I think you are missing a `index.md` file, here I can see your docs http://start-testing.readthedocs.io/en/latest/roles/automation/

**Comment by dialex** [comment]
That was a good tip @stsewd. I've added the `index.md` [file to my repo](https://github.com/dialex/start-testing/blob/master/index.md) and I still get [the maze](https://start-testing.readthedocs.io/en/latest/).

I had to go to settings and change the default version to `master` instead of `latest`. I'm not sure that's not a default. Thanks for guiding me into the right path. Cheers!

**Comment by SinChan4896** [comment]
Hi, I added the `index.md` in [my repo](https://github.com/SinChan4896/sdtv0.0.1/tree/master)
but how to set the `latest` to `master` ? it stated `latest `is the default, enable to unactivate...
![image](https://user-images.githubusercontent.com/84772487/168028960-c34ccbee-7c5e-4aad-9780-81e0277aa7ec.png)
![image](https://user-images.githubusercontent.com/84772487/168029744-3ab9361e-5b6d-49fd-b09b-d5307077625c.png)
