### ISSUE TITLE
mkdocs.yml not read when in docs dir

### ISSUE THREAD

**Issue by blairconrad** [rtfd/readthedocs.org#3249]
## Details

* Project URL: https://github.com/FakeItEasy/FakeItEasy
* Build URL (if applicable): http://fakeiteasy.readthedocs.io/en/4.2.0/
* Read the Docs username (if applicable): blairconrad

## Expected Result

The table of contents in the `mkdocs.yml` file is not respected, and our code formatting lost its "GitHub" styling. It's as if the `mkdocs.yml` file is not read at all.
*A description of what actually happened*

The [Build Process documentation says](http://docs.readthedocs.io/en/latest/builds.html?highlight=mkdocs.yml#mkdocs):

> When you choose Mkdocs as your Documentation Type, we will first look for a mkdocs.yml file in your repository. If we don’t find one, we will generate one for you. We will look inside a doc or docs directory first, and then default to the top-level of your documentation.

As part of FakeItEasy/FakeItEasy#1250, we moved our `mkdocs.yml` file from the root of the repo to the `docs` directory.  We expected no changes to the generated docs.

## Actual Result

Thereafter, the docs for the 4.2.0 release
1. no longer used GitHub style rendering for the code, and
1. did not respect the Table of Contents in the `mkdocs.yml`.

It's as if the `mkdocs.yml` file was not read at all.

I thought the problem might've been a bad `docs_dir`, so I added these lines to the YML:

```yml
docs_dir: .
site_dir: ../artifacts/docs
 ```

But it made no difference.
For now, I'm working around the problem by moving the `mkdocs.yml` file back to the root, as seen in FakeItEasy/FakeItEasy#1267.

**Comment by stsewd** [comment]
@blairconrad are you still having this issue?

**Comment by stsewd** [comment]
Thanks for the screenshot, looks like rtd isn't searching for the mkdocs.yml file in other directories, just in the root

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/mkdocs.py#L60-L60

Just a question, there is any difference putting it in another directory? Or it is just for keeping the root clean?

This will be allowed with the new configuration file https://github.com/rtfd/readthedocs.org/pull/4084/files#diff-bd10ec86a98c7d6bdf7ea8455b8fdfd4R78

**Comment by blairconrad** [comment]
Oh, it was for keeping the root clean and because the docs actually said that `doc` or `docs` were the preferred locations.

Thanks, I'll keep an eye on #4084.

**Comment by stsewd** [comment]
I had tested the new changes with your project, you may want to see this https://www.mkdocs.org/about/release-notes/#stricter-directory-validation

**Comment by stsewd** [comment]
So, with the information below, we don't want to support that behavior (is deprecated and marked as an error in recent versions). What we will support (yaml file only) is having a mkdocs project inside another directory:

- mkdocs/docs/index.md
- mkdocs/docs/mkdocs.yml

**Comment by blairconrad** [comment]
>  you may want to see this mkdocs.org/about/release-notes/#stricter-directory-validation

Yup, very clear, @stsewd. At least we know what not to do now.

Although I'm confused by

> * mkdocs/docs/index.md
> * mkdocs/docs/mkdocs.yml

I'd've expected

> * mkdocs/docs/index.md
> * mkdocs/mkdocs.yml

What do I miss?

**Comment by stsewd** [comment]
Ups, my mistake. It is as you mention (editing my comment)
