### ISSUE TITLE
Cannot import private github repo into readthedocs - no link to authorize REPO scope

### ISSUE THREAD

**Issue by SaintNazaire** [rtfd/readthedocs.org#3258]
## Details

* Project URL: Private repo
* Build URL (if applicable): Private repo
* Read the Docs username (if applicable): SaintNazaire 

## Expected Result

Compile Readthedocs documentation from private Github repo

## Actual Result

Failure.

## Current assistance response from Github

If the Github webhook delivery triggers some process on the receiving end, and that process needs to collect more information via the API, then that process needs to make an authenticated API calls because the repository is private:

https://developer.github.com/v3/#authentication

Sharing private information without any authentication would be a security concern.

Now, the Readthedocs application which you are targeting with webhooks in your private repository is an application you authorized with your user account. When you authorize an application, that application gets a token which can be used for authentication. However, you didn't authorize it with the right permissions (called scopes: https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-scopes-for-oauth-apps/). As far as I can tell, you haven't authorized the application with "repo" scope which is the only scope which grants access to content in private repositories. As a result of that, you are able to deliver information to Readthedocs via the webhook (expected), and Readthedocs is not able to read more information via the API because it doesn't have the right permissions (again expected). 

You'll need to grant "repo" scope to the application in order for the application to be able to access code in a private repository. Normally, the application would provide a link to authorize it with such scope. If it doesn't provide that -- I recommend reaching out to Readthedocs support and asking them why they don't provide that.

**Comment by safwanrahman** [comment]
Private Repo is not supported by the community version.
Please check https://readthedocs.com

**Comment by SaintNazaire** [comment]
Ok I just want to build a small documentation. GitHub costs USD 7/month, Docker about the same, Readthedocs USD 50/month !!! It seems there is a product space missing between community offer and commercial offer. Enabling private repo-ing on a limited basis - say 1-3 documentations - for free, especially for limited audiences would make much more sense.

**Comment by safwanrahman** [comment]
@SaintNazaire You can install your own instance of readthedocs in your instance. All the setup documentation is there.

**Comment by jfgossage** [comment]
@safwanrahman I am trying to understand what you mean by 

> your instance

 as I need to deal with this issue also.

**Comment by safwanrahman** [comment]
@jfgossage You can install readthedocs in a server or a local machine and thats your instance of readthedocs
