### ISSUE TITLE
Extend lifetime of `sessionid` cookie on every usage

### ISSUE THREAD

**Issue by dhermes** [rtfd/readthedocs.org#3259]
I've noticed that I would get signed out of RTD every 2 weeks or so, then I actually checked that the `sessionid` cookie gets set to 2 weeks after sign in and the `Expires` field never gets updated.

(If I grew up and used a password manager this wouldn't be as painful, but it's no fun to get signed out of a website that I use 3-4 days a week.)

**Comment by RichardLitt** [comment]
Thanks @dhermes. Interesting point: should we automatically log people out?

**Comment by dhermes** [comment]
@RichardLitt FWIW, there is nothing wrong with bounded lifetime cookies that expire if people don't visit RTD over that two week period. But if they **do** visit, that's the issue.

**Comment by ericholscher** [comment]
Is there a good Django setting for this? Seems like an easy patch, if you want to submit it! :)

**Comment by ericholscher** [comment]
Looks like we want: https://docs.djangoproject.com/en/1.11/ref/settings/#std:setting-SESSION_SAVE_EVERY_REQUEST ?

**Comment by humitos** [comment]
We are already doing this

https://github.com/rtfd/readthedocs.org/blob/d91807c5c772fbfdb4be5ff928c9268d4be05e80/readthedocs/settings/base.py#L56

Closing this issue.

**Comment by dhermes** [comment]
Thanks! The introduction of federated login via Google has also fixed this for me
