### ISSUE TITLE
Buld failing with unknown error

### ISSUE THREAD

**Issue by rb2745** [rtfd/readthedocs.org#3263]
## Details

* Project URL: http://onap.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/onap/builds/6271072/
* Read the Docs username (if applicable): rb2745

## Expected Result
Build to succeed
*A description of what you wanted to happen*
Build to succeed.   

## Actual Result
Unknown error encountered. 
This earlier bug report maybe related https://github.com/rtfd/readthedocs.org/issues/3140

*A description of what actually happened*
Build fails with little diagnostic information

**Comment by Ender27182818** [comment]
I've got the same problem on my new project started today:

https://readthedocs.org/projects/maxillo/builds/6274484/

The page just says:

Completed Nov. 15, 2017. 11:48 a.m.
Build took 0 seconds
Build #6274484
latest
Build failed
Error

Unknown error encountered. Please include the build id (6274484) in any bug reports.

**Comment by EliRibble** [comment]
I've got the same problem on my new project started today:

https://readthedocs.org/projects/maxillo/builds/6274484/

The page just says:

Completed Nov. 15, 2017. 11:48 a.m.
Build took 0 seconds
Build #6274484
latest
Build failed
Error

Unknown error encountered. Please include the build id (6274484) in any bug reports.

**Comment by safwanrahman** [comment]
Seems like its trying to parse the readthedocs.yml file from
`readthedocs/user_builds/onap/checkouts/latest/docs/submodules/so.git/aria/multivim-plugin/src/main/python/multivim-plugin/readthedocs.yml`, that is causing the error

**Comment by ericholscher** [comment]
@EliRibble `ProjectImportError: Failed to get code from 'https://bitbucket.org/Authentise/maxillo' (git clone): 128`

**Comment by ericholscher** [comment]
@EliRibble That page 404's for me.

**Comment by EliRibble** [comment]
Thanks, I thought the repo was marked public but it wasn't yet. I'll fix that.

**Comment by EliRibble** [comment]
Okay, works for me now, thank you.

**Comment by agjohnson** [comment]
I believe the initial bug has been resolved here, so I'll close.

Anyone else coming here with a similar error on your build: this error is a generic error that catches all the other errors we miss during build. Please create a new issue with your report, we can reference the error in our logs and hopefully add some more helpful reporting for some of these cases.
