### ISSUE TITLE
Build ends with Unknown Error (html is generated but no PDF)

### ISSUE THREAD

**Issue by piogor** [rtfd/readthedocs.org#3277]
## Details

* Project URL: http://tango-controls.readthedocs.io
* Build URL (if applicable): http://readthedocs.org/projects/tango-controls/builds/6278204/
* Read the Docs username (if applicable): piotr.goryl

## Expected Result

Build all documentation (html, PDF) without failing or meaningful error description ;-).

## Actual Result

Build ends with the following error:

> Error
> 
> Unknown error encountered. Please include the build id (6278204) in any bug reports

 However html was built but no new PDF output was generated (there is still old version available for download).

**Comment by piogor** [comment]
Again, I have investigated problem on my local environment - for some reason Sphinx 1.5.6 starts to generate corrupted latex output:

https://github.com/tango-controls/tango-doc/issues/137

It is enough to require Sphinx>=1.6.5 to solve the issue.

Anyway, it would be nice to have a way of getting access to more info about problematic builds (like pdflatex terminal output).

**Comment by RichardLitt** [comment]
@piogor your suggestion for more information might get lost. A targeted issue asking for more info about problematic builds, in the case of pdflatex specifically, might be a good one to open. 

Thanks for taking the time to log your problem and solution!

**Comment by piogor** [comment]
I will open the issue :).

**Comment by agjohnson** [comment]
This is an unhelpful error because something happened at the system level and we didn't catch the error. Raising a traceback is a security hole, so we're moving from "Oops, oh well" messaging to "Oops, well here's a reference" instead.

We'll address the particular issue here and hopefully come up with an actual error that we can catch for this case.

**Comment by RichardLitt** [comment]
Thanks for explaining, @agjohnson. Sounds good.

**Comment by stsewd** [comment]
I'm closing this issue in favor of https://github.com/rtfd/readthedocs.org/issues/4288, which is about the problem why the output of `pdflatex` wasn't shown.
