### ISSUE TITLE
More informative Error reports

### ISSUE THREAD

**Issue by piogor** [rtfd/readthedocs.org#3278]
## Details

* Project URL:  ALL
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

It would be nice if in case of `Unknown Error ` one can get more info, for example full terminal output. 
As it was in #3277 pdflatex gets into trouble (hangs) with latex output of Sphinx 1.5.6. This was not possible to find out on the RtD build report since there were no output from pdflatex.  Having access to it would make detecting problem easier.

## Actual Result

`Unknown Error` does not produce meaningful information. There are few of such reports: #3277, #3276, #2680 and so...

**Comment by agjohnson** [comment]
Giving out a possible traceback would be a security flaw here, so we've made the design decision -- on purpose -- to limit information here. The goal is to spur issue reports where we can actually determine the error cause.
