### ISSUE TITLE
Provides a way to set the "stable" version manually

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3279]
This issue comes from https://github.com/rtfd/readthedocs.org/issues/3268#issuecomment-345310676

I think it could be a good nice to have, so I'm opening this issue so we can discuss here if it would be better or it could be more confusing at the end.

Besides, how it should be implemented in the UI; I image it
 * in the "Admin -> Versions" page a `stable` title with an input and a description "Leave it blank to use the RTD default logic to determine the stable version")
 * as a setting somewhere in the `yaml` file

**Comment by aasis21** [comment]
@humitos @ericholscher, I would like to take up this issue. For UI part we can give a `ChoiceField`, so that there is also no validation issue. What do you say? 
And in `yaml` file, we can give a `stable_version:version_name `

**Comment by sfdye** [comment]
+1 for this feature, my build is failing because `stable` is not able figure out the latest tagged release

**Comment by ericholscher** [comment]
Isn't the way to do this to just create your own branch named "stable" and use that?

**Comment by sfdye** [comment]
@ericholscher I thought rtd will automatically pick up the latest release tag as `stable` version?

**Comment by ericholscher** [comment]
It should, but this ticket is about specifying it manually. If there is a bug in our version resolution, that is a separate issue.

**Comment by sfdye** [comment]
@ericholscher that would be my #3714

**Comment by stsewd** [comment]
RTD allow overriding the stable version by creating a branch or tag named `stable` (it's a little buggy right now #3913), isn't that what we want?

**Comment by stsewd** [comment]
Not sure if this is something we can put on our yaml, per-version settings only. This looks like a project setting.

**Comment by ericholscher** [comment]
I feel like the answer here should be "If you want a custom `stable` version, create either a tag or branch in your project with that name." Do we want to apply the same logic to `latest` as well? If so, we should likely document this, and then make sure the code works that way :)

**Comment by stsewd** [comment]
Currently, users can specify a custom latest on the web admin, I think the major feature here is that user's don't want to maintain 2 branches/tags, say they want `my-stable` be just `stable`.

**Comment by humitos** [comment]
> I think the major feature here is that user's don't want to maintain 2 branches/tags, say they want `my-stable` be just `stable`.

I think we don't want to add another setting for this only to support this case.

> "If you want a custom `stable` version, create either a tag or branch in your project with that name."

I suppose that we can document this and just close this issue.

**Comment by stsewd** [comment]
This can be closed in favor of https://github.com/rtfd/readthedocs.org/issues/5319, but we could still document that people can create a version named `latest` or `stable`

**Comment by humitos** [comment]
Yes. The only actionable thing missing from this issue is the documentation part https://github.com/rtfd/readthedocs.org/issues/3279#issuecomment-435141663

**Comment by agarwalrounak** [comment]
I will work on it.
