### ISSUE TITLE
Build fails without any error message

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3280]
I think we've created a new build failure state with some of the work on logging

http://readthedocs.org/projects/docs/builds/6276629/

**Comment by safwanrahman** [comment]
Nothing is in sentry

**Comment by humitos** [comment]
I wasn't able to reproduce this bug in my local instance. I've tried with a couple of different projects and nothing.

**Comment by agjohnson** [comment]
This could have been a temporary misfire because of old processes lingering. Will close for now.
