### ISSUE TITLE
Regain pyquery project ownership

### ISSUE THREAD

**Issue by gawel** [rtfd/readthedocs.org#3281]
## Details

* Project URL: https://readthedocs.org/projects/pyquery/
* Read the Docs username (if applicable): gawel

The project is currently owned by https://readthedocs.org/profiles/mirror/
But I'm the owner: https://github.com/gawel/pyquery

I'd like to regain project ownership so I can keep it up to date.

Is there any solution ?

## Expected Result

An up to date doc

## Actual Result

Not able to change project's settings

**Comment by safwanrahman** [comment]
Can you please take a look here

https://docs.readthedocs.io/en/latest/dmca/index.html

**Comment by gawel** [comment]
Ok, I've read that. Thanks.

Do I really need to follow those steps ? I'm pretty sure I've created this project some years ago and this mirror guy took ownership at some point (probably after an upgrade of rtdf).

**Comment by agjohnson** [comment]
@gawel nope, no need to follow dmca take down

The `mirror` user is an internal user we use for non-RTD sphinx projects. I can add you as a maintainer.

**Comment by gawel** [comment]
If this allow me to edit project's settings, that's perfect. (i'd like to switch to py3 one day, etc.)

**Comment by agjohnson** [comment]
Sorry for the wait. I have bestowed the power upon you, wield it wisely.

**Comment by gawel** [comment]
No problem. Thanks a lot.
