### ISSUE TITLE
Remove/Update talks about RTD page

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3283]
I think this page should be remove or updated:

http://docs.readthedocs.io/en/latest/talks.html

From my understand it's too poor and doesn't communicate anything. It doesn't have links to the talks or something like that. So, if it's too time consuming to keep it updated, I would remove it.

**Comment by RichardLitt** [comment]
It looks like the purpose of the page isn't to be a comprehensive list of talks, but:

> Note
> This page is mainly just for showing a demo of updating docs, during a talk.

 However, it hasn't been used that way in a while, so I think it could be removed now.

**Comment by humitos** [comment]
Ha, good point!

As you can image... I didn't read the note :P

**Comment by agjohnson** [comment]
👍 on removing. We can do live updates somewhere else.
