### ISSUE TITLE
Build failed without an informative error

### ISSUE THREAD

**Issue by lobachevzky** [rtfd/readthedocs.org#3284]
## Details

* Project URL: https://readthedocs.org/projects/mujoco/
* Build URL (if applicable): https://readthedocs.org/projects/mujoco/builds/6291128/
* Read the Docs username (if applicable): ethanabrooks

## Expected Result

A successful build.

## Actual Result

Build failed
Error
Unknown error encountered. Please include the build id (6291128) in any bug reports.

Thanks for your help with this.

**Comment by agjohnson** [comment]
Builds look to be passing now. Closing here, but feel free to reopen if you are still noticing problems.

**Comment by lobachevzky** [comment]
Sounds good.
