### ISSUE TITLE
Build passed but there is an error on the build page

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3285]
## Details

* Project URL: https://readthedocs.org/projects/mujoco/
* Build URL (if applicable): https://readthedocs.org/projects/mujoco/builds/6291303/
* Read the Docs username (if applicable):  ethanabrooks

## Expected Result

Matching the build status with the message

## Actual Result

It says the build Passed but it has Failed

![captura de pantalla_2017-11-19_16-43-48](https://user-images.githubusercontent.com/244656/32995885-007a55b2-cd49-11e7-8dca-8381fdb1d90a.png)

Related: #3284

**Comment by agjohnson** [comment]
This might be related to #3280
