### ISSUE TITLE
Build is stuck in "triggered" state, can't start any new builds

### ISSUE THREAD

**Issue by TimShawver** [rtfd/readthedocs.org#3289]
## Details

* Project URL: https://readthedocs.org/projects/qgrid/
* Build URL: https://readthedocs.org/projects/qgrid/builds/6294562/
* Read the Docs username: tim_shawver

## Expected Result

Build completes or provides some error message.  I was attempting to use a `readthedocs.yml` file for the first time, because my last builds have been broken with an error about not being able to find npm.  This error about npm seems to be new because I was able to build the docs successfully a few weeks ago, and there haven't been any doc-related changes in the repo since then.

## Actual Result

Build has been stuck in "Triggered" state for 40 minutes, with a loading spinner showing and no error messages. All other builds I start are also stuck in the "Triggered" state. I see a message about the number of tasks in the build queue: `Whoa! The build queue is 408 tasks long, new builds may take a while.`, and the number of tasks increases every time I refresh the page.

**Comment by agjohnson** [comment]
Just as the error states, the build queue was backed up. Things have returned to normal though.

**Comment by TimShawver** [comment]
Thanks, seems to be working now.
