### ISSUE TITLE
Only function stubs generated on RTD

### ISSUE THREAD

**Issue by tmcclintock** [rtfd/readthedocs.org#3290]
## Details

* Project URL: https://github.com/tmcclintock/cluster_toolkit
* Build URL (if applicable): http://cluster-toolkit.readthedocs.io/en/latest/index.html
* Read the Docs username (if applicable): tmcclintock

## Expected Result

My build uses autodoc and autoapi in an attempt to generate the API for my Python functions in RTD. The functions all have Google style docstrings ([example](https://github.com/tmcclintock/cluster_toolkit/blob/master/cluster_toolkit/bias.py)). Everything builds find locally when I run `make html`. I understand that this is because sphinx is using my local install. 

My Python library is a wrapper around functions written in C. The C code uses the [Gnu Science Library](https://www.gnu.org/software/gsl/) (GSL). Since RTD doesn't support the GSL I cannot use a virtualenv to run `setup.py` in my build, however this shouldn't matter since I only want RTD to generate an API for the Python wrappers.

## Actual Result

RTD only ends up with function stubs without any information about the function, as seen [here](http://cluster-toolkit.readthedocs.io/en/latest/cluster_toolkit/cluster_toolkit.bias.html#functions).  I am *not* having ImportErrors as per the [FAQ](https://docs.readthedocs.io/en/latest/faq.html), it's just that the docstrings aren't found on RTD.

I have attempted to fix this in the `conf.py` by adding a path to the Python modules, to the api generated with `autoapi`, and to both at the same time. The local build always works (sometimes with warnings about duplicate docstrings) but the RTD build never does.

Any advice is much appreciated. Thank you.

**Comment by tmcclintock** [comment]
It was an ImportError and I was just being dumb and didn't see it.

**Comment by RichardLitt** [comment]
Thanks for updating us and closing the issue, @tmcclintock. Glad you got this sorted!

**Comment by tmcclintock** [comment]
Well, sadly autodoc still isn't finding my files despite my best efforts and fifty commits, but cest la vie as they say.

**Comment by tmcclintock** [comment]
I was able to fix my issue by adding these lines to the `conf.py` file:

```
# General information about the project.
project = u'project_name'
__import__(project)
package = sys.modules[project]
```

This stopped the ImportErrors from appearing on the next line in the Build. It isn't totally clear to me why RTD wasn't able to locate my docstrings without this.
