### ISSUE TITLE
html_logo is not scaled in Internet Explorer 11

### ISSUE THREAD

**Issue by jnsebgosselin** [rtfd/readthedocs.org#3291]
## Details

* Project URL: http://readthedocs.org/projects/gwhat/
* Build URL (if applicable): http://gwhat.readthedocs.io/en/readthedocs_init/#
* Read the Docs username (if applicable): jnsebgosselin

```python
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
html_logo = 'img/logo.svg'
html_theme_options = {
    'logo_only': True,
    'display_version': False,
}

```
## Expected Result

The logo is scaled to fit in the sidebar header section like it is in Chrome and Firefox:

![image](https://user-images.githubusercontent.com/10170372/33088674-4985955e-cebc-11e7-8654-4918b9ac8836.png)

## Actual Result

The logo is not scaled (whether it is in svg or png format) and looks huge in Internet Explorer 11:

![image](https://user-images.githubusercontent.com/10170372/33088602-0d5c71ce-cebc-11e7-9d55-b92a9da7a67e.png)

Note that the same behaviour is also observed for https://docs.readthedocs.io/en/latest/

![image](https://user-images.githubusercontent.com/10170372/33088637-2966eb9c-cebc-11e7-9495-8fb25640ac7e.png)

**Comment by jnsebgosselin** [comment]
Quick fix: 
I scaled my svg logo so that its actual width was 250px using Inkscape and it is displaying fine in Explorer now.

**Comment by safwanrahman** [comment]
@ericholscher Do we support Internet Explorer 11?

**Comment by agjohnson** [comment]
Hah, well that's special.

There's no reason we shouldn't support support modern IE. Feel free to open this as a bug on https://github.com/rtfd/sphinx_rtd_theme. Closing here as this is a theme issue.

**Comment by jessetan** [comment]
@agjohnson I think this is both an issue of the theme and of [the actual logo file](https://raw.githubusercontent.com/rtfd/readthedocs.org/bd1113c10894647e594c081260773e5e0a6a5157/docs/img/logo.svg).

In the theme, the `<a>` which contains the image has no width set in the theme, which IE reacts differently to than other browsers (https://stackoverflow.com/a/14578128) causing the incorrect size.
Setting a width on the `<a>` helps, but makes the image scale disproportionately in IE. This comes from the lack of a `viewBox` attribute, see https://css-tricks.com/scale-svg/#article-header-id-5. ([This requires a toggle to be set in Inkscape 0.48 and is automatic in 0.91+](http://wiki.inkscape.org/wiki/index.php/Tricks_and_tips#Scaling_images_to_fit_in_webpages.2FHTML), or you can add it manually)

If I replace the width and height from the svg with a `viewBox` and add `width: 100%` to the `<a>` it looks pretty decent on IE:
![screen shot 2017-12-06 at 15 12 09](https://user-images.githubusercontent.com/3284111/33665644-ee138338-da97-11e7-9aae-666acde748ad.png)
Only the height is wrong, but only a height in px on the img seems to solve that.

Alternative would be to provide the logo as a PNG for IE
