### ISSUE TITLE
django.contrib.gis.geos.error.GEOSException: Could not parse version info string "3.6.2-CAPI-1.10.2 4d2925d6"

### ISSUE THREAD

**Issue by kakulukia** [rtfd/readthedocs.org#3297]
python 2.7.14 and 3.6.3 on OSX

Whats happening here?

I also found this bug ticket: https://code.djangoproject.com/ticket/28441
I cant downgrade geos like suggested: "Error: geos does not have a version "3.6.1" in the Cellar.
Versions available: 3.6.2"
looks like its only fixed in 1.11.5 but RTD doesnt run with 1.11.5

HELP!

**Comment by RichardLitt** [comment]
Hey @kakulukia, thanks for opening an issue. Can you use the issue template that was provided, and explain the steps that led to this error? Thank you.

**Comment by kakulukia** [comment]
Well the issue template is for online projects only, but as i said above im tried to get it to work on my osx machine and i was just following the installation instructions.
Nevertheless i manages to patch rtd to work with the latest Django version which suprisingly didnt took that much effort.

https://github.com/rtfd/readthedocs.org/pull/3305

**Comment by tony** [comment]
Also experienced this. See also: https://code.djangoproject.com/ticket/28441

**Comment by stsewd** [comment]
We already run on django 1.11 :tada: https://github.com/rtfd/readthedocs.org/pull/4750

**Comment by davidfischer** [comment]
> You shouldnt party that hard when theres a 2.1.3 and major changes ahead! :P

I think being on the latest LTS is where we ought to be. I am looking forward to 2.2 though.
