### ISSUE TITLE
Build - This page does not exist yet.

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#3303]
## Details

* Project URL: http://readthedocs.org/projects/web3py/builds/
* Build URL (if applicable):
* Read the Docs username (if applicable): techtonik

Hitting the Build button for the above project gives this message:
```

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \
```
I am logged in. If I am not logged in, RTD proposes to login.

## Expected Result

Starting build, or explaining why it doesn't happen.

**Comment by humitos** [comment]
This is something that was changed recently at #3260.

I think the that the decision is not to show the Build button in projects where you don't have permissions. I'm creating a PR for this behaviour.

**Comment by techtonik** [comment]
I like the button - it gives a hint that it is possible to rebuild docs online.

**Comment by humitos** [comment]
I also liked the button, but it's true that it's kind of weird to trigger builds in documentation that are not your projects.

I'm not sure if this could be a problem or not. Maybe @agjohnson can explain more about this decision.

**Comment by techtonik** [comment]
I don't see how manually triggering a build is a problem for projects that you don't own on RTD. As a contributor, I like to trigger builds regardless of my status with RTD. If there is abuse in the system, it should be proven that it actually takes place and throttled, like any sane API does.
