### ISSUE TITLE
Several recent consecutive builds are stuck in "Building" state

### ISSUE THREAD

**Issue by krzychb** [rtfd/readthedocs.org#3308]
## Details

* Project URL: http://esp-idf.readthedocs.io/en/latest/
* Build URL (if applicable):
  * https://readthedocs.org/projects/esp-idf/builds/6311619/
  * https://readthedocs.org/projects/esp-idf/builds/6311059/
  * https://readthedocs.org/projects/esp-idf/builds/6308949/
  * https://readthedocs.org/projects/esp-idf/builds/6308480/
  * https://readthedocs.org/projects/esp-idf/builds/6308479/

Initial enquiry done in https://github.com/rtfd/readthedocs.org/issues/3296#issuecomment-346633621

## Expected Result

Build should timeout instead of "Building" forever.

## Actual Result

Builds are stuck in "Building" state.

![image](https://user-images.githubusercontent.com/12953787/33186130-78bde458-d087-11e7-899d-58d2a2e63082.png)

**Comment by cdeil** [comment]
I also see builds stuck in the "Building" state for http://readthedocs.org/projects/gammapy/builds/
One is from 4 days ago, another one from yesterday, another one from today.
First saw this 4 days ago, so might be related to #3293.

**Comment by Bultako** [comment]
Ok
good to know there are more issues related from other people in RTD. Hopefully search in notebooks https://github.com/gammapy/gammapy/pull/1176#issuecomment-338620761 could also be solved at the same time..

**Comment by krzychb** [comment]
Since about one week I do not see this issue anymore for the new builds.
