### ISSUE TITLE
Missing theme resources on built docs

### ISSUE THREAD

**Issue by tekulvw** [rtfd/readthedocs.org#3311]
## Details

* Project URL: https://red-discordbot.readthedocs.io/en/v3-develop/
* Build URL (if applicable):
* Read the Docs username (if applicable): tekulvw

## Expected Result

Built docs should be rendered with the Sphinx RTD theme.

## Actual Result

Docs are rendered on the webpage without any theme formatting. Looking at the Chrome developer console it seems like we're getting a 404 for some URL. This has started recently (sometime within the last week) but we're not sure exactly when.

**Comment by RichardLitt** [comment]
The 404 is for https://readthedocs.org/api/v2/footer_html/. I'm not sure why that would happen.

**Comment by ericholscher** [comment]
Hrm, it looks like we aren't passing the version correctly to the footer call :/

**Comment by ericholscher** [comment]
We're looking the data up on slug, but querying it with a verbose name: https://github.com/rtfd/readthedocs.org/blame/master/readthedocs/doc_builder/backends/sphinx.py#L99

**Comment by ericholscher** [comment]
@tekulvw It looks like it's showing the correct theme files now -- did you do anything different?

**Comment by Kowlin** [comment]
Yes, we've reverted a change that I think caused this. https://github.com/Cog-Creators/Red-DiscordBot/pull/1144 (Sorry for the late response, this got lost in the endless notification feed)

**Comment by ericholscher** [comment]
Great, will close this issue 👍
