### ISSUE TITLE
Error: "can't open file 'setup.py': [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by alexpreynolds** [rtfd/readthedocs.org#3315]
## Details

* Project URL: http://bedops.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/bedops/builds/6318851/
* Read the Docs username (if applicable): alexpreynolds

## Expected Result

Usually, when we publish a new release of the bedops project via Github, the buildthedocs site is triggered and builds the current (now new, v2.4.30) version of documentation from the contents of the `/docs` folder under our project. (The `/docs` folder contains the `conf.py` script and all the ReST files and other documentation assets.)

## Actual Result

The documentation is staying at the previous release tag number (v2.4.29). The build log at https://readthedocs.org/projects/bedops/builds/6318851/ suggests that a file called `setup.py` cannot be found.

**Comment by humitos** [comment]
Duplicated of #3296 

Please check that issue. Feel free to re-open if it's not your case.
