### ISSUE TITLE
Nav pane and content area should use independent scrolling

### ISSUE THREAD

**Issue by jolleekin** [rtfd/readthedocs.org#3319]
## Affected Sites
Any docs site generated by Read the Docs using the default theme

## Steps to Reproduce
1. Go to a site generated by Read the Docs using the default theme (https://docs.readthedocs.io/en/latest/ for example)
2. Scroll the content area

## Expected Result
The nav pane is not scrolled

## Actual Result
The nav pane is scrolled

## Why Is This An Issue (at least for me)?
The nav pane tells me which article I'm reading and what previous/next articles are. If the nav pane has independent scrolling, I can easily jump to a previous/next article without scrolling everything.

Another reason is the nav pane and the content area display different contents with different length, so it makes more sense if they have independent scrolling.

**Comment by Blendify** [comment]
This issue should be reported to the theme repository https://github.com/rtfd/sphinx_rtd_theme and this should be possible by setting `sticky_navigation` to false in the theme settings.
