### ISSUE TITLE
Missing dependency to run tests locally

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3320]
## Details

* Project URL: http://docs.readthedocs.io/en/latest/tests.html

Hi, I was trying to run the tests locally following the guide, but I was getting an error, later I figure out that I needed mercurial installed, that requirement is not indicated on the guide.

## Expected Result

Pass all the tests following the guide.

## Actual Result

I was unable to pass the tests following the guide.

I would be happy to send a pull request later 😄

**Comment by RichardLitt** [comment]
Sounds like this could be fixed with a small PR to note that mercurial should be installed! Looking forward to seeing that, @stsewd. Thanks for logging this.
