### ISSUE TITLE
Build passed but I can't see the documentation (maze screen)

### ISSUE THREAD

**Issue by joshvillbrandt** [rtfd/readthedocs.org#3321]
## Details

* Project URL: https://github.com/joshvillbrandt/wireless
* Build URL (if applicable): http://wireless.readthedocs.io/en/latest/
* Read the Docs username (if applicable): joshvillbrandt

## Actual Result

No docs. The empty maze screen instead. Similar to #2356 and #3246.

## Expected Result

Expected to see docs. They previously existed here, but somehow disappeared. I have triggered new builds (which were successful but I still get the maze screen instead of docs).

Per the [Build Process for Mkdocs](http://docs.readthedocs.io/en/latest/builds.html#mkdocs) documentation, it should be sufficient to only have a README.md file in the root of the directory.

**Comment by konzy** [comment]
Same issue https://megatroniki.readthedocs.io/en/latest/

**Comment by dearmond** [comment]
Me too: https://readthedocs.org/projects/sitefarm/

I have the README.md in the /docs/ directory, which per the documentation, should be sufficient.

**Comment by tynan-cr** [comment]
This has something to do with the README location (tested using a local deploy of RTD):

1. When README.md is in the root of the repo, the project doesn't convert it to index.md, but builds the rest of the docs just fine.

2. When README.md is in the docs folder, mkdocs is skipped entirely during the build process, resulting in an empty directory, and thus a 404.

**Comment by ericholscher** [comment]
Do you not have an `index.md`?

**Comment by dearmond** [comment]
I have a README.md in the /docs directory.

From the [Build Process for Mkdocs](http://docs.readthedocs.io/en/latest/builds.html#mkdocs) documentation:
> If you have a README.md, it will be transformed into an index.md automatically.

**Comment by jtyr** [comment]
I have the `README.md` file in the root of the repo and I'm getting 404 as well.

**Comment by stsewd** [comment]
I'm sorry you're having this issue, I think this is just a documentation problem (see https://github.com/rtfd/readthedocs.org/issues/1954#issuecomment-183138623).

You can access to your docs here:
@joshvillbrandt  http://wireless.readthedocs.io/en/latest/README/
@dearmond http://sitefarm.readthedocs.io/en/latest/README/

**Comment by stsewd** [comment]
@jtyr you need an index.md file as mention above

**Comment by stsewd** [comment]
This was also a documentation problem, solved on https://github.com/rtfd/readthedocs.org/pull/3498/commits/d907524ddec69c2530324d9c6cc7011830a209d8
