### ISSUE TITLE
python: can't open file 'setup.py': [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by uralbash** [rtfd/readthedocs.org#3322]
## Details

* Project URL: http://lectureswww.readthedocs.io/
* Build URL (if applicable): http://readthedocs.org/projects/lectureswww/builds/6322630/
* Read the Docs username (if applicable): uralbash

## Expected Result

Successful build

## Actual Result

Project stopped builds although no changes were made

**Comment by mattip** [comment]
Duplicate of issue #3296, you need to disable "Install your project inside a virtualenv using setup.py install" in Advanced Settings

**Comment by humitos** [comment]
Thanks @mattip
