### ISSUE TITLE
Duplicate TOC entries

### ISSUE THREAD

**Issue by dplanella** [rtfd/readthedocs.org#3345]
## Details

* Project URL: http://adafruit-beaglebone-io-python.readthedocs.io

## Expected Result

The TOC entries on the sidebar are shown once (I have no particular preference for them being collapsed or not)

## Actual Result

The TOC entries on the sidebar appear duplicated. They appear once as collapsed entries and at the same time as expanded entries.

**Comment by dplanella** [comment]
This appears to be https://github.com/rtfd/sphinx_rtd_theme/issues/445

**Comment by RichardLitt** [comment]
Thanks, @dplanella. Let's track it there. Let me know if you think this should be reopened.
