### ISSUE TITLE
Invalid message on just imported / simple repositories

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3351]
When you create a project in github with just a `README.md` and import it on RTD, you get this message:

![captura de pantalla_2017-12-04_10-14-16](https://user-images.githubusercontent.com/244656/33559815-fee4658c-d8db-11e7-8d03-f1324102758f.png)

This message is wrong since the PATH of those failes are invalid/useless for the user. I think this is generated by Sphinx automatically, so I'm not sure if we can change that easily.

**Comment by stsewd** [comment]
Where is generated this file? The only relevant file I found is this https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl :/

Maybe passing some additional context?

**Comment by humitos** [comment]
Not really sure but IIRC this file is generated by Sphinx itself, maybe that _it's something_ that could help you to find out :/

**Comment by stsewd** [comment]
Found! https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L104

So, what should we put on there? Something like this?

> Create an index file on _your repository_ (or docs).

**Comment by humitos** [comment]
Nice!

    Please create an ``index.{ext}`` or ``README.{ext}`` file with your own content under the root directory in your repository (or under ``/docs`` directory).

Maybe something like that?

**Comment by stsewd** [comment]
@humitos PR on the way!
