### ISSUE TITLE
Integrate private GitLab installation 

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3352]
Once #3327 gets merged we will want to integrate domains different than `gitlab.com` (https://github.com/rtfd/readthedocs.org/pull/3327#discussion_r153367655)

One thing that I don't know how to handle is the OAuth App that it's needed to link from our Django Admin with the SECRET and CLIENTID tokens. Besides, we will need a OAuth App created under the domain of the private GitLab installation. 

We need to think a little more on how this would be implemented...

**Comment by agjohnson** [comment]
I don't think we want to support integration with private installs. If there is anyone with a private installation of GitLab, and wants special integration with RTD, this would likely fall under a custom support contract and commercial hosting. We don't support GHE either, due to complexity.

**Comment by humitos** [comment]
When I created this issue I was thinking on the .com but it seems that I created the issue under .org :/
