### ISSUE TITLE
List of versions in the flyout should always be up-to-date

### ISSUE THREAD

**Issue by samapico** [rtfd/readthedocs.org#3354]
I am using a local installation of ReadTheDocs (with version 27bf3d3).

My project uses multiple versions and I use tags for each version. On the "latest" build, the flyout at the bottom-left lists all available versions (e.g. "latest, stable, 1.0, 1.1, 1.2).

In the documentation of a specific version, however, only the versions *that existed at the time of the build* are listed. For example, under 1.2, I would see 1.1 and 1.0 listed, but under 1.1, only 1.0 would be listed.
I would expect to be able to jump back and forth between the available versions.

In order to have all versions listed for each version, I would need to manually rebuild every version after every release, which seems counter-intuitive.

**Comment by humitos** [comment]
That should work out of the box. That flyout (footer) is generated dynamically by: https://github.com/rtfd/readthedocs.org/blob/762d342b9a55f9efee3fe6c7ef56c2743430f25a/readthedocs/restapi/views/footer_views.py#L66

Do you have an example in the readthedocs.org site that we can take a look?

**Comment by samapico** [comment]
You're right, multi-version projects I could find hosted on rtd seem to work as expected. Weird... I did have to make some changes to get proper version links (see #3023), that might have something to do with my issue? I just changed the line without bothering with the new setting.

Here's what it looks like on my server. This is what the flyout looks like for the latest version:

![flyout-latest](https://user-images.githubusercontent.com/12238303/33803016-eb559f00-dd53-11e7-9887-dcf028cb3abd.png)

This is what it looks like from the 2.3.4 version:

![flyout-2 3 4](https://user-images.githubusercontent.com/12238303/33803017-eb6400a4-dd53-11e7-9615-b1eb16cce093.png)

**Comment by stsewd** [comment]
@samapico I think you may need to update your local installation to solve the issue.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Comment by MiracleYoung** [comment]
> his is what the flyout looks like for the late

Hi author, I'm newer for rtd, my question is how can I display the flyout?

I'm using sphinx now.

![](https://user-images.githubusercontent.com/12238303/33803016-eb559f00-dd53-11e7-9887-dcf028cb3abd.png)

**Comment by stsewd** [comment]
@MiracleYoung please provide the rtd project. It should just work
