### ISSUE TITLE
There was a problem with Read the Docs while building your documentation.

### ISSUE THREAD

**Issue by madskinner** [rtfd/readthedocs.org#3359]
## Details
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6362748).
* Project URL: https://github.com/madskinner/pub2sd2
* Build URL (if applicable):http://pub2sd2.readthedocs.io
* Read the Docs username (if applicable): silseb

## Expected Result
Build have been failing on not finding data files
*A description of what you wanted to happen*
added 'include_package_data=True' line in setup.py,
used pkg_resources, resource_filename in order to load data files

## Actual Result
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6362748).
*A description of what actually happened*
project runs on Win10 py3.4, passes on Travis-ci on py3.4, py3.5 and py3.6
though build says it fails the docs are built and visible on http://pub2sd2.readthedocs.io

**Comment by RichardLitt** [comment]
Possibly related to #3367, I think.

**Comment by stsewd** [comment]
Hi, I just saw that your last builds are successful https://readthedocs.org/projects/pub2sd2/builds/, were you able to solve your problem?

**Comment by madskinner** [comment]
Sorry for the delay in responding they seem to have solved themselves, finger trouble at my end I guess.
