### ISSUE TITLE
Build timeout

### ISSUE THREAD

**Issue by cdeil** [rtfd/readthedocs.org#3360]
## Details

* Project URL: https://gammapy.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/gammapy/builds/6362524/
* Read the Docs username (if applicable): deil

## Expected Result

Build passed

## Actual Result

Build timeout.

---

**Would it be possible to surface the build log from the step that times out?**

I suspect it's the HTML sphinx build, but I'm not sure.

For the build steps you do show, they are together < 5 min and the last one is this one and succeeds:
```
cat docs/conf.py
```
Locally the HTML sphinx build takes 5 min on my machine, so I'm surprised that our build times out here!?

**If the HTML build time really is the issue, would it be possible to increase the docs build time for this project a bit?**

I promise to try and reduce it by doing a bit less in our Sphinx build and limit the number of commits to master that will trigger a build on RTD. I can also try to get some funding, but this will not happen immediately, and in the meantime I can't do a release because our docs and changelog are outdated.

**Comment by cdeil** [comment]
We've decided to move Gammapy away from RTD (work in progress: https://github.com/gammapy/gammapy/issues/1241). Either build on travis-ci or our Jenkins, and host on gh-pages.

RTD maintainers: Thank you very much for setting up and supporting this great service!!! It was of great help to our project over the past years, and for me still is for several other Python package docs I have.

If someone has a link with information how to do the multi-version cross-linking of the docs like RTD does it, outside of RTD, please leave a comment!

Also, if there's some link with information how to extract or archive existing docs from RTD on check-out (e.g. a zip file or tarball with the HTML docs from past version that are being served), please leave a comment!

**Comment by RichardLitt** [comment]
Thank you for letting us know, @cdeil, for the nice words, and for clearly saying what you would need to come back! 

@agjohnson do we have issues that you know of for those two requests he mentions?
