### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by julienmalard** [rtfd/readthedocs.org#3362]
## Details

* Project URL: https://readthedocs.org/projects/tinamit/
* Build URL (if applicable): https://readthedocs.org/projects/tinamit/builds/6364471/
* Read the Docs username (if applicable): julien.malard

## Expected Result
Documentation should build with no errors.

## Actual Result
I received this message:

Erreur
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6364288).

However, the documentation does seem to build somewhat.

**Comment by stsewd** [comment]
Looks like you have a undefined variable
```
jinja2.exceptions.UndefinedError: 'theme_navigation_depth' is undefined
```
Just here https://github.com/julienmalard/Tinamit/blob/master/docs/source/_templates/layout.html#L140

But is kind of weird that the docs build.

**Comment by julienmalard** [comment]
Hello,


I copied the template directly from the RTD theme (which does compile in general) and only tweaked a few things to add support for right-to-left languages. Could that still be the problem?


Many thanks,

Julien Malard

________________________________
દ્વારા: Santos Gallegos <notifications@github.com>
મોકલ્યું: 21 ડિસેમ્બર 2017 00:17:13
પ્રતિ: rtfd/readthedocs.org
Cc: Julien Malard; Author
વિષય: Re: [rtfd/readthedocs.org] Build fails (#3362)


Looks like you have a undefined variable

jinja2.exceptions.UndefinedError: 'theme_navigation_depth' is undefined


Just here https://github.com/julienmalard/Tinamit/blob/master/docs/source/_templates/layout.html#L140

But is kind of weird that the docs build.

**Comment by stsewd** [comment]
I think so, maybe you can try updating to the latest template, also seems like the recent failures are related to your project having unicode branch names, rtd don't support unicode branches at the moment,

**Comment by julienmalard** [comment]
Thank you! What more information should I provide?
I had opened an issue with regards to the filenames and was told that pull request #4052 should fix it.

**Comment by stsewd** [comment]
@julienmalard You will need to delete or rename this branch https://github.com/julienmalard/Tinamit/tree/%D8%A7%D8%B8%DB%81%D8%B1, maybe all this problems related to unicode will be fixed when rtd run python3 in production, please follow  https://github.com/rtfd/readthedocs.org/issues/3060 for updates

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
