### ISSUE TITLE
Build timeouts for large sphinx docs

### ISSUE THREAD

**Issue by JordonPhillips** [rtfd/readthedocs.org#3363]
## Details

* Project URL: https://botocore.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/botocore/builds/6365917/
* Read the Docs username (if applicable): phjordon

## Expected Result

Documentation builds fully.

## Actual Result

Documentation build times out when trying to build pdf/epub.

## Context

botocore includes documentation for 128 different AWS services. Basically all of that documentation is generated from service definition files included in the repo. The generated rst tree clocks in at around 31MB.

From profiling I've found that generating our rst files from our service definition files takes about 70 seconds and then running sphinx on them takes about 500 seconds. So even if we commit pre-built rst files to our repo (which I have done on [the 'docs' branch](https://github.com/boto/botocore/tree/docs)) we still won't be able to build more than one format. But then I'm still getting timeouts for builds that should only output html, even though the html output completes just fine. The build ui isn't reporting anything from whatever task failed, so I'm not sure what it is trying to do after the html build finishes.

**Comment by RichardLitt** [comment]
@JordonPhillips Did you find a solution? :)
