### ISSUE TITLE
Github service: cannot unlink after deleting account

### ISSUE THREAD

**Issue by nlgranger** [rtfd/readthedocs.org#3374]
I have changed my github username and since it is not possible with readthedoc, I have deleted my account and created a new one.

When I try to connect readthedoc to github, it says `The social account is already connected to a different account.`. I have tried to revoke the connection to readthedoc on github but the message keeps appearing.

When I open https://readthedocs.org/accounts/github/login/?process=login, it redirects me to https://readthedocs.org/accounts/inactive/

* Project URL: https://github.com/nlgranger/LazyProc
* Build URL (if applicable): https://travis-ci.org/nlgranger/LazyProc

**Comment by humitos** [comment]
Thanks for your report.

This is a known problem and it will be solved once #3214 will deployed, I think.

**Comment by nlgranger** [comment]
Ok thanks, I will keep this issue open until then.

**Comment by safwanrahman** [comment]
@agjohnson Can you manually delete the account?

**Comment by agjohnson** [comment]
@nlgranger What is the name of the account that is currently inactive? I'll reactivate so you can delete this account.

**Comment by nlgranger** [comment]
The account was `pixelou`

**Comment by agjohnson** [comment]
Activated! There may be a problem with removing your user, so you'll be our test subject. Report back if you hit any errors removing your user.

**Comment by nlgranger** [comment]
Should I keep the github link active on the old account while I delete it again or the cleanup functionnality is not active yet? Should I delete the projects from the account as well?

**Comment by nlgranger** [comment]
Ok, so I did the worst case scenario:
1- Github account linked to old account
2- Project imported and set to build automatically with old account
3- Delete old account
4- Link github to new account
5- Import project into new account

Everything worked as expected. Thanks for the fix.

**Comment by RichardLitt** [comment]
Thanks for updating us, @nlgranger!
