### ISSUE TITLE
Old registration model still sticking around

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3376]
```python

IntegrityError: update or delete on table "auth_user" violates foreign key constraint "registration_registrationprofile_user_id_fkey" on table "registration_registration
profile"
DETAIL:  Key (id)=(18096) is still referenced from table "registration_registrationprofile".

```

**Comment by ericholscher** [comment]
Thoughts on what to do here? Can we safely delete that old table, without cascading the deletes?

**Comment by safwanrahman** [comment]
I think we can just drop the table without any problem. As its not related to any other table from the code

**Comment by humitos** [comment]
I also think we can just frop that table. Making a backup before that "just in case" :)

That table exists because of `django-registration` app that was used some time ago then removed and migrated to `allauth` but the db wasn't cleaned up. http://django-registration.readthedocs.io/en/latest/

**Comment by ericholscher** [comment]
Yea, we can just _rename_ the table, and see if things blow up :)

**Comment by ericholscher** [comment]
I've removed the FK constraint.

**Comment by ericholscher** [comment]
This has been removed. 👍

**Comment by quroom** [comment]
I got same error but I can't find registration_registration table in database.
How can I fix this problem?
