### ISSUE TITLE
mkdocs: where to specify mkdocs.yml - two translations of markdown documentation in one repository

### ISSUE THREAD

**Issue by chfw** [rtfd/readthedocs.org#3380]
## Details

There are multiple problems in this setup. I knew this is an edge use case. So firstly, we wondered if we can specify where mkdocs.yml is, like sphinx conf.py. And We got strange builds where build passed but no documentation accessible via the url.

* Project URL: 
https://readthedocs.org/dashboard/pyecharts/
https://readthedocs.org/dashboard/pyecharts-en/

* Build URL (if applicable):

https://readthedocs.org/projects/pyecharts-en/builds/6384125/ -> build passed but no pages there.

* Read the Docs username (if applicable): 

chfw

## Expected Result

We would like to build zh documentation in the master project and build en in pyecharts-en project.
## Actual Result

*A description of what actually happened*

No idea on how to tell readthedocs where mkdocs.yml is. Specifically, we would like the master project to use zh-mkdocs.yml and English project to use en-mkdocs.yml

And in principle, is it supported to have two translsations of mark-down documentation in one repo?

**Comment by marcelstoer** [comment]
Multi-language in the same repository is not currently supported by MkDocs problem. It's not a RTD issue. See mkdocs/mkdocs#774 for details.

**Comment by RichardLitt** [comment]
Thanks @marcelstoer. @chfw I am going to close this as out of scope. Take a stab in the mkdocs repo if you want this to be changed! Feel free to continue the conversation here if I you think I prematurely judged this.
