### ISSUE TITLE
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id

### ISSUE THREAD

**Issue by paternal** [rtfd/readthedocs.org#3381]
## Details

* Project URL: https://framagit.org/spalax/papersize
* Build URL (if applicable): https://readthedocs.org/projects/papersize/builds/6384804/
* Read the Docs username (if applicable): paternal

## Expected Result

Successful compilation.

## Actual Result

Compilation error, with the following message:

> There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6384782).

**Comment by paternal** [comment]
I compiled it again a few minutes later, and it went flawlessly. So as far as I am concerned, there is no issue here.
I am reporting it only because you requested it. Have fun! 🙂

**Comment by RichardLitt** [comment]
Thanks, @paternal! 

Maintainers: what's the policy on closing these?

**Comment by safwanrahman** [comment]
I think it was cause of our deployment process.
I have gone through the error log and seems like it happens while we deployed in the web server.

Can close it now!
