### ISSUE TITLE
Fix display of build advice

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3390]
Build advice display styling is wrong. This shouldn't use block level element around `setup.py install`.

![image](https://user-images.githubusercontent.com/1140183/33800434-d96c1d0c-dcfc-11e7-8f6e-92971abf4938.png)

**Comment by humitos** [comment]
Closing because this was fixed at https://github.com/rtfd/readthedocs.org/commit/14e498a2

Please, reopen if I'm wrong.
