### ISSUE TITLE
Recent builds are missing translated languages links

### ISSUE THREAD

**Issue by julienmalard** [rtfd/readthedocs.org#3401]
## Details

* Project URL: http://tikon.readthedocs.io/
* Build URL (if applicable): New builds do not include language links (https://readthedocs.org/projects/tikon/builds/). Older builds of the same project (e.g., https://readthedocs.org/projects/tikon-ta/builds/) do.
* Read the Docs username (if applicable): julien.malard

## Expected Result

*Language options should show in the pop-up tab as before.*

## Actual Result

*On recent builds, the translated languages do not show up anymore. However, the pages are still available (changing the language code directly in the page URL directs to the correct page.*

**Comment by julienmalard** [comment]
Seems to have fixed itself!

**Comment by RichardLitt** [comment]
Glad to hear it, @julienmalard! If you run into it again, reopen. Thanks for letting us know.
