### ISSUE TITLE
[Support] Lost access to an account

### ISSUE THREAD

**Issue by pfalcon** [rtfd/readthedocs.org#3407]
## Details

* Project URL: https://readthedocs.org/projects/micropython-pfalcon/
* Build URL (if applicable):
* Read the Docs username (if applicable): paul2

## Expected Result

Being able to log in, or use "forgot password" feature specifically for *that* account.

## Actual Result

I'd like to log in to that account, but I don't have password on a record, nor trying "forgot password" feature with my existing emails works. I don't know how I ended up having that account. Perhaps, it was created to quickly try out something, and was forgotten. Nor I have idea why no my email works with "forgot password" - perhaps, few years ago RTD could allow to register an account without email? What I actually would like to do is to transfer the project on this old "paul2" account to https://readthedocs.org/projects/micropython-pfalcon/ to my active account "pfalcon" (the actual problem is that I can't create a project by that name in my new account, because it's taken by that old account).

If anything can be helped here, I'd appreciate it. Thanks!

**Comment by stsewd** [comment]
@humitos can help here.

**Comment by humitos** [comment]
@pfalcon I sent an email to the account registered under `paul2`. Let me know if you receive that message.

**Comment by humitos** [comment]
Closing as stale. Please, ping me if you need more help with this.
