### ISSUE TITLE
zulip: Build started failing from an unrelated commit.

### ISSUE THREAD

**Issue by aero31aero** [rtfd/readthedocs.org#3409]
## Details

* Project URL: https://github.com/zulip/zulip
* Build URL (if applicable):https://readthedocs.org/projects/zulip/builds/?page=8
* Commit which failed: https://github.com/zulip/zulip/commit/be832387c547d831c06b9a288487f8ae845d0eb6

## Expected Result
The build should pass as earlier.

## Actual Result

The build failed, and other builds kept failing for all subsequent commits, starting from a commit that doesn't modify the docs.

**Comment by stsewd** [comment]
Well, looks like the builds for pdf and pub always failed but the build was marked as successful,I think some improvements were made and now the whole build is shown as failed.

Anyway, I could see the documents regardless of the failed compilation.

**Comment by stsewd** [comment]
Were you able to build the PDF and epub docs locally?

**Comment by stsewd** [comment]
Disabling the pdf and epub generation on the dashboard http://readthedocs.org/dashboard/zulip/advanced/ shows you a successful build.

**Comment by aero31aero** [comment]
Hey!  We disabled the pdf and epub creation. Thanks for responding on this and debugging.
