### ISSUE TITLE
Privacy level of a project

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3422]
## Details

While replicating #3396 I noted that if the privacy level of a project is set to `private` I can still see the docs (logout user of course). The levels public and protected works as expected.

## Expected Result

A logout user or no admin user can't see a project with privacy level set to private.

I know this is a beta feature, then this level of privacy has not been implemented?

**Comment by stsewd** [comment]
I just discovered that if the privacy level is set to private the builds aren't show, the docs are still accessible. I think this is a little confusing, can we put better docs on this?

**Comment by humitos** [comment]
How it should work? Private shouldn't show the project nor the docs?

**Comment by stsewd** [comment]
Public and protected are clear to me, with private I was expecting that no one can see the docs, but just hidden the builds and the project is more reasonable.

Maybe add a note that no matter the level of privacy, the documents are still seen by everyone?

**Comment by RichardLitt** [comment]
> Maybe add a note that no matter the level of privacy, the docs are still seen by everyone?

That makes sense to me.

**Comment by humitos** [comment]
Closing this one in favor of #2663
