### ISSUE TITLE
Pull instead of fetch?

### ISSUE THREAD

**Issue by maxirus** [rtfd/readthedocs.org#3423]
When running RTD locally, I noticed that changes in the repo to particular branch (ie. master) never get reflected in the docs built by RTD. Looking at the celery logs, I never see the branch updates pulled down and subsequently, the $RTD_HOME/user_builds/example-project/checkouts/master is never updated with the latest in the repo.

Unless I'm missing something, I believe this line should be a pull instead of a fetch:
https://github.com/rtfd/readthedocs.org/blob/2f8f4c2302241068dbbf7f429c79eb6f15524485/readthedocs/vcs_support/backends/git.py#L173

**Comment by maxirus** [comment]
Ok, I've figured out the issue. This function has a dependency on git version >=1.9 (See: [link](https://stackoverflow.com/questions/8432953/if-a-git-tag-changes-on-remote-a-git-fetch-does-not-update-it-locally-is-this) CentOS/RHEL comes with 1.8. Updating git to 2.8 fixes the issue.

I will open a PR to update the Docs to reflect this.

**Comment by RichardLitt** [comment]
Thanks, @maxirus! Looking forward to the PR. Why don't we keep this open until the PR is merged - reference this issue there.
