### ISSUE TITLE
Mkdocs 0.17.2 don't build, No such command "json

### ISSUE THREAD

**Issue by giansalex** [rtfd/readthedocs.org#3424]
## Details

* Project URL: https://github.com/giansalex/mkdocs-sample
* Build URL (if applicable): https://readthedocs.org/projects/giansalex-mkdocs/builds/6435771/
* Read the Docs username (if applicable): giansalex

## Expected Result

Build documentation with mkdocs + material theme.
[Requirements](https://github.com/giansalex/mkdocs-sample/blob/master/requirements.txt)

## Actual Result

`Error: No such command "json".`

**Comment by agjohnson** [comment]
This is a dulplicate of a few tickets. This is a known issue, and probably requires someone from the mkdocs community to step in and update our end. We haven't had a lot of focus on mkdocs support lately.

**Comment by giansalex** [comment]
i used github pages.
