### ISSUE TITLE
Can not import package

### ISSUE THREAD

**Issue by wkerzendorf** [rtfd/readthedocs.org#3428]
## Details

* Project URL: github.com/starkit//starkit
* Build URL (if applicable): https://readthedocs.org/projects/starkit/builds/6441952/
* Read the Docs username (if applicable): wkerzendorf

## Expected Result

I would like the documentation to build as it does with the same conda environment on many osx machines.

## Actual Result

The package is called starkit but it doesn't seem to import despite the setting that it should install in its own environment. Not clear what to do next
It doesn't build - see link

**Comment by stsewd** [comment]
Your latest builds are passing, were you able to solve the problem? Also, rtd build your docs on docker images (ubuntu OS). Maybe the package is for osx only?

**Comment by wkerzendorf** [comment]
@stsewd yes we did and I apologize that this wasn't reported before. we had to set 

```yml
python:
   setup_py_install: true
```

otherwise it would not build (IRC). I think this was set in some older projects through the RTD web gui and remembered. Now I always need to set it if using the conda environment (I switched back to pip for different reasons).
