### ISSUE TITLE
Don't show "build ideas" to unprivileged users 

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3430]
## Details

If a build fail and a _build idea_ is present, then it is show to admin and no-admin users. If no-admin users clicked, a 404 is given. For example: https://readthedocs.org/projects/tinamit/builds/6364471/ (_Try reseting it_).

## Expected Result

Don't show admin actions to no admin users.

Is there a valid reason for show this to no-admin users or if safe to hide this?

**Comment by humitos** [comment]
This is something that I notice the other day and I forget to report.

I think there is no reason to show the tips for non project admin or "staff" (not sure if staff is the correct one, but the permission used for the core team). This way, the end user and the core team can see the same and it's easy to debug in case it's needed.

My thoughts.

**Comment by ericholscher** [comment]
+1 on not showing it. Would love a PR for this!

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/builds/build_detail.html#L101 is the line to change.

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/builds/build_detail.html#L66 is the logic you'd want to check.
