### ISSUE TITLE
Cache YAML file in build environment

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#3431]
We will often not know much about the actual YAML file used to construct a build environment. We could in theory go back in time to find it, but we should cache it at the top level of the environment, so we can query it in the future.

**Comment by agjohnson** [comment]
I proposed storing a metadata json blob with builds that includes the configuration we used to build. This could be just the yaml file, but i think it would be more helpful as a blob of all of the settings used in the build. This would be more useful than caching for query, as we can also display metadata around the build to users -- build image used, python version used, requirements file found, etc.

**Comment by agjohnson** [comment]
Closing in favor of #3751
