### ISSUE TITLE
Use jinja2-time for dates in template files

### ISSUE THREAD

**Issue by Blendify** [rtfd/readthedocs.org#3435]
There are several templates that have a date and these can be tedious to manually update we should use the extension [jinja2-time](https://github.com/hackebrot/jinja2-time) to automate this progress.

**Comment by agjohnson** [comment]
We're using django templates, and I don't think we've discussed any need to use jinja. Reopen this is you know of any solutions for django templates that are comparable. This will still be low priority cleanup on reopening
