### ISSUE TITLE
Broken link to rst template

### ISSUE THREAD

**Issue by msyriac** [rtfd/readthedocs.org#3442]
This link:
http://docs.writethedocs.org/writing/beginners-guide-to-docs/#id1
linked from the homepage of the docs for readthedocs is broken.

**Comment by humitos** [comment]
Hi! Thanks for your report.

What is the page that contains that link? I don't find it.

**Comment by msyriac** [comment]
Whoops, sorry I left that out. The page that contains that link is:
http://docs.readthedocs.io/en/latest/getting_started.html

**Comment by stsewd** [comment]
Here is the broken link https://github.com/rtfd/readthedocs.org/blob/master/docs/getting_started.rst#in-restructuredtext where it says `syntax or this template`.

**Comment by stsewd** [comment]
And this is the correct link http://docs.writethedocs.org/guide/writing/beginners-guide-to-docs/#id1

**Comment by humitos** [comment]
Hi Santos! Would you like to propose a PR? 😀

**Comment by msyriac** [comment]
@humitos I just submitted a fix as a PR. Thanks @stsewd for the links.

**Comment by RichardLitt** [comment]
Merged and closed, as this was fairly trivial. Thank you, @msyriac, for noting this and PRing it! Great work.

**Comment by humitos** [comment]
@msyriac oh nice! I was on the phone so I haven't seen it before. Thanks for contributing!

**Comment by Artic2017** [comment]
jh
