### ISSUE TITLE
Increase build timeout limit for Pyrogram project

### ISSUE THREAD

**Issue by delivrance** [rtfd/readthedocs.org#3478]
## Details

* Project name: Pyrogram
* Project URL: https://github.com/pyrogram/pyrogram
* Build URL (if applicable): https://readthedocs.org/projects/pyrogram/builds/6498536
* Read the Docs username (if applicable): delivrance (https://readthedocs.org/profiles/delivrance)

Pyrogram is a fully functional Telegram Client Library written in Python, which also offers a complete documentation of the latest Telegram API (not available officially). This documentation consists of a fairly high amount of *.rst file and the build process is taking a good while to complete.

A stripped down version of the documentation is being successfully built in less than 90 seconds, as you can see here: https://readthedocs.org/projects/pyrogram/builds/6498464, and this makes me guess the configuration is set up properly.

I would kindly ask if is it possible to increase the timeout setting in order to allow the build process to complete successfully. I'm not really sure of how long the timeout should be set - on my local machine the entire build process takes roughly 12 minutes - so, would be nice to have at least a full build completed in order to see how much it takes.

Thanks.

## Expected Result

Build completed

## Actual Result

Build failed.
Error: Build exited due to time out

**Comment by stsewd** [comment]
Your latest builds are passing, Do you still need to increase the time for your project? Also, we recently move to azure, so we have faster builders now.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Comment by delivrance** [comment]
Thank you @stsewd. I don't think I need a time increase anymore. I've stripped down some of the docs allowing the old builders finishing in under 800 seconds. Now I've noticed it indeed takes much less time (around 200 seconds), I might consider reverting the changes and see how it goes. Thanks again!
