### ISSUE TITLE
interface for adding extra template context

### ISSUE THREAD

**Issue by davidism** [rtfd/readthedocs.org#3483]
I've been working on porting Flask's docs to be built on RTD instead of our custom builder. Our builder has a separate JSON file with metadata about versions, and inserts it into `html_context` by combining each project's Sphinx config with a standard config. `html_context` can also be set on the command line with `-A key=value` flags. RTD's interface doesn't allow doing this yet.

While that version information is already available from RTD and just needs to be documented (#3482), it would still be nice to be able to specify additional template context using the web interface. One option is a text box that users can paste JSON in, then add `html_context.update({{ extra_html_context|tojson }})` after RTD's default `html_context`.

**Comment by davidism** [comment]
@ericholscher mentioned this could be accomplished with a Sphinx plugin. However, this would require us to maintain a separate public package, make a new release of it with new context, and trigger RTD builds for all versions every time we wanted to change the global context, which is not very convenient. RTD directly supporting extra global context would be much nicer.

**Comment by ericholscher** [comment]
We currently support a user having a defined `html_context` in their `conf.py`. This can be generated with Python code, and doesn't require an extension. An example here: https://github.com/writethedocs/www/blob/master/docs/conf.py#L111-L114 -- I believe this is what you want?

**Comment by ericholscher** [comment]
We already call update on the existing `html_context` here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L130

I guess we could add `additiona_html_context` in YAML, but I'm not sure how this would be better than just having it defined in the `conf.py`?

**Comment by davidism** [comment]
The problem with it being in the code is that it's now tied to the version being built. The useful thing about the context is that it can be modified at build time.

**Comment by ericholscher** [comment]
I'm not sure I follow. Can you explain the exact use case?

**Comment by davidism** [comment]
Let's say we want to display the docs for Flask 0.10, 0.11, 0.12, and 1.0. If we want to display some standard information in the sidebar for each build, like links to each version, we don't want to have to go back to the 0.10 branch and update it so it knows that 1.0 was released. We want to inject the current list of versions as we build each one. The specific example with versions is already handled by RTD's context, but it demonstrates the idea.

**Comment by ericholscher** [comment]
Yea, this is actually a different problem on our side. We solve this in JavaScript by sending the data via the footer response. That is "v2" of #3482, where we give users access to that "realtime" project data in JS, so you don't have to rebuild all docs every time one version changes.

**Comment by ericholscher** [comment]
but I believe #3482 has what you want (a list of all active versions injected in template context on build)

**Comment by davidism** [comment]
Yes, for the versions use case, I've already got the information I need. This was a more general request for specifying global context at build time.

**Comment by ericholscher** [comment]
Gotcha.

**Comment by humitos** [comment]
@davidism Hi! I'm about to start working on this issue and I would like to have some more feedback from your side to know if by implementing the design proposed in #3490 will fit your needings or there is something else missing from our side to achieve this issue.

**Comment by davidism** [comment]
That appears to be documenting RTD's internal context. It mentions adding context to `conf.py`, but the problem with that is discussed above. This issue is about adding a field to the RTD admin form to provide context that is independent of the version being built. The version information was an example, but this could apply to arbitrary context a project wants to add.

**Comment by davidfischer** [comment]
You primarily need this in order to get versions of particular projects correct? I believe this can be handled through the API like so:

https://readthedocs.org/api/v2/version/?project__slug=flask

That will get you all the versions and you can grab just the `active` ones if you want to. The active ones can be [administered in the dashboard](https://readthedocs.org/projects/flask/versions/).

Let me know if this gets you were you need to be on this issue.

**Comment by davidism** [comment]
I don't need this anymore, although it may be useful to others. Perhaps it's more appropriate (or already present) in the YAML config?
