### ISSUE TITLE
No notification emails received upon build failure

### ISSUE THREAD

**Issue by justvanrossum** [rtfd/readthedocs.org#3489]
## Details

* Project URL: https://readthedocs.org/projects/drawbot/
* Build URL (if applicable): https://readthedocs.org/projects/drawbot/builds/
* Read the Docs username (if applicable): justvanrossum, typemytype

## Expected Result

We entered three valid, active, working email addresses on the Admin / Notifications page; we expected to receive notification emails upon build failure.

## Actual Result

We fail to receive notification emails upon build failures. And yes, we had build failures.

Could there be anything wrong with our configuration that causes this? Any help would be greatly appreciated.

Cc @typemytype

**Comment by justvanrossum** [comment]
Oh, I failed to note that we meticulously checked our spam folders.

**Comment by pllim** [comment]
I have the same problem across several projects that I signed up for notifications. I get failure notifications from other services like Appveyor and Travis CIs to the same email address without problem. c/c @bsipocz @rendinam

**Comment by stsewd** [comment]
Are you still having this issue?

**Comment by humitos** [comment]
We used to have a problem when sending emails at the beginning of the year and we solved it. So, I suppose that was what affected you. I'm closing it here, but feel free to reopen if you consider. Thanks!

**Comment by pllim** [comment]
Email notifications work for me now as well. Thank you for fixing it!

**Comment by jontwo** [comment]
What version has this bugfix? We are having the same problem at v2.8.2
