### ISSUE TITLE
Duplicate static files with mkdocs

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#3497]
## Details

On the very first build of a brand new mkdocs project, the docs build runs twice which creates duplicate CSS and JS files in the `<head>` of the output. When a project is built a second time, this error does not manifest itself.

To reproduce locally, do a manual project import of [mkdocs itself](https://github.com/mkdocs/mkdocs) and trigger a build.

## Expected Result

The HTML build should only run once and there should be no duplicate CSS and JS files referenced in the output.

## Actual Result

The output HTML references the same CSS and JS files multiple times.

This first screenshot illustrates that additional CSS and JavaScript files are added twice.
![screen shot 2018-01-09 at 1 19 00 pm](https://user-images.githubusercontent.com/185043/34746478-ff435342-f548-11e7-9ae0-73595b4c876c.png)

This second screenshot illustrates that the `extra_css` and `extra_javascript` have duplicates in the mkdocs.yml file.
![screen shot 2018-01-09 at 1 50 51 pm](https://user-images.githubusercontent.com/185043/34746488-0a7d580c-f549-11e7-9a66-2e58daa08567.png)

**Comment by davidfischer** [comment]
Very specifically it looks like since the build is triggered twice, the extra CSS and JS are appended twice. See: https://github.com/rtfd/readthedocs.org/blob/4d10f2e/readthedocs/doc_builder/backends/mkdocs.py#L89-L97

**Comment by stsewd** [comment]
Seems like the second build is triggered when synchronizing versions
`[17/Jan/2018 23:49:31] readthedocs.restapi.views.model_views:174[14143]: INFO Triggering new stable build: mkdocs:269190c9aa18a33d397f424860fcf07bbfe96f0c
`

**Comment by stsewd** [comment]
On readthedocs.org works fine, is this something that just affect to local instances? or maybe a recent regression?

**Comment by stsewd** [comment]
Also experienced with this repo https://github.com/orbingol/NURBS-Python (local instance only)

**Comment by stsewd** [comment]
I can't replicate this anymore, I think this was something to do with https://github.com/rtfd/readthedocs.org/pull/3946. @davidfischer can you confirm if this issue is solved?

**Comment by davidfischer** [comment]
I'm not seeing it! It is fixed.
