### ISSUE TITLE
gitlab theme integration not working

### ISSUE THREAD

**Issue by lazka** [rtfd/readthedocs.org#3500]
## Details

* Project URL: https://pygobject.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/pygobject/builds/6533135/

## Expected Result

I've added a gitlab configuration to the conf.py as suggested in https://docs.readthedocs.io/en/latest/vcs.html#gitlab

Building locally everything works and the proper links to gitlab are shown on each page
## Actual Result

As can be seen in the build log, it replaces all the configuration with "None"/False. No GitLab links are included on the pages.

**Comment by stsewd** [comment]
I think the gitlab context variables are injected from the git url (check only urls containing gitlab.com).

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/sphinx.py#L85-L88

But I think that these context variables have to be allowed to be redefined, I'm not sure if readthedocs.org support this (custom gitlab installations).

**Comment by humitos** [comment]
Hi @lazka !

> I've added a gitlab configuration to the conf.py as suggested in docs.readthedocs.io/en/latest/vcs.html#gitlab

That documentation is obsolete I'd say (there is a PR that fixes that at https://github.com/rtfd/readthedocs.org/pull/3490 --not sure if it fixes, but it removes that section and explains it better where/how it's used)

RTD autoinjects those variables when the repository is a GitHub.com, Bitbucket.com or Gitlab.com. At the moment, this integration is not supported for other domain.

**Comment by lazka** [comment]
Thanks for having a look.

So, afaics, it would be easy to fix by only replacing the user provided config if "display_gitlab" on the injection site is True (same with the others)?

Is this something you'd take contributions for?

If not, feel free to close this :)

**Comment by RichardLitt** [comment]
> So, afaics, it would be easy to fix by only replacing the user provided config if "display_gitlab" on the injection site is True (same with the others)?

That sounds good to me. One of the other maintainers should also weigh in before you start work on this, though! I'll label this as needing a design decision to make that clear.

**Comment by agjohnson** [comment]
Having more conditional operations around setting the `display_*` options, or the GitHub/GitLab/Bitbuket URLs would be a good addition. For instance, if a user has these options defined, perhaps we shouldn't force the `display_*` and URL options on the context data.

Feel free to open a PR with your thoughts there, we can offer some more guidance on the technical implementation there.

**Comment by lazka** [comment]
ok, thanks

(related issue: https://github.com/rtfd/sphinx_rtd_theme/issues/536)

**Comment by stsewd** [comment]
We can close this in favor of https://github.com/rtfd/readthedocs.org/issues/2971. After that you can use that together with https://github.com/rtfd/sphinx_rtd_theme/blob/ddfdd35e6977f21fb1771734732756b0cf1d6bba/sphinx_rtd_theme/breadcrumbs.html#L59
