### ISSUE TITLE
Owner name Briana Magana

### ISSUE THREAD

**Issue by vanetellez** [rtfd/readthedocs.org#3502]
## Details

* Project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by RichardLitt** [comment]
Thanks @vanetellez. This doesn't look filled out, so I am going to close it. Feel free to edit the issue or open a new one if you have something you need help with.
