### ISSUE TITLE
Unknown user created an out of date RTD repo for our project, and we have no way to contact them to claim it

### ISSUE THREAD

**Issue by CAM-Gerlach** [rtfd/readthedocs.org#3503]
## Details

* Project URL: https://spyderide.readthedocs.io/en/latest/
* Read the Docs username (if applicable): Mine: [CAM-Gerlach](https://readthedocs.org/profiles/maxgam/) User in question: [maxgam](https://readthedocs.org/profiles/maxgam/)

I'm a member of the development team for [Spyder](https://github.com/spyder-ide/spyder), the Scientific PYthon Development EnviRoment, which is to our knowledge the most used full Python IDE developed specifically for the scientific Python stack, and the de-facto primary IDE for, among others, the popular Anaconda distribution. Due to some problems with our Python Hosted docs, we've decided to switch to RTD, but unfortunately, it seems an random user by the cryptic name of maxgam, who to our knowledge has never had any association with the project, has rehosted it here on RTD. 

As of now, have no apparent means to contact this unknown user in order to transfer the project to its proper owners, implement our webhooks to automatically sync the repo with our github, nor otherwise maintain the project. Currently, it is out of date by over four months, despite large current and upcoming changes to the documentation intended to aid users and greatly reduce the overwhelming number of duplicate or user-side bug tickets we receive and have to individually deal with, to the tune of up to dozens per day; particularly now that we recently lost our funding, this creates a significant burden that reduces our ability to fix real bugs and make needed improvements. 

Therefore, our maintainer @ccordoba12 requested me to contact you by this means (per our [#5986](https://github.com/spyder-ide/spyder/issues/5986) , in order for you to contact the user or allow us to do so in order to resolve the issue, or simply transfer it directly. I read the [page of your documentation](https://docs.readthedocs.io/en/latest/abandoned-projects.html) that seemed relevant, but it was overall quite unclear, not explicitly defined what projects it applied to, nor how it was relevant to our specific situation, nor how to contact the user in question. Therefore, we were hoping for your help in resolving this matter, to ensure RTD is a viable platform for us and avoid further misguiding our users. Thanks!

**Comment by RichardLitt** [comment]
Thanks for pointing out lack of clarity in our docs. I personally don't have the answers for resolving this, but I would like to make sure that the docs are fixed to make it clearer for cases like this in the future. So, before this issue is eventually closed, let's circle back around and see if we can make that happen.

**Comment by ccordoba12** [comment]
Well, we read in your docs that anyone can upload any project they want to RTD. And that's fine, we don't see any problem with that.

But the thing is we can't get in touch with `maxgam` so she/he can give us admin access to the Spyder project in RTD, and that's why we are asking for your help to do that, i.e. to contact with her/him.

**Comment by CAM-Gerlach** [comment]
Thanks for your response. However, the primary issue, as @ccordoba12 states, is not the docs 
(that was just a side comment), but rather contacting the user. Specifically, the aforementioned doc states:

> The core team recommends users to get in touch with each other and solve the issue by respectful communication.

However, there appears to be no means that we can find to contact this user through ReadTheDocs, and as we have no idea who this person is, we have no way to reach out to them otherwise. Therefore, following said advice appears to be impossible, at least in this case, without your help—therefore, the primary purpose of this request.

**Comment by CAM-Gerlach** [comment]
Any updates, @RichardLitt or others? We're really hoping to be able to switch to RTD but wanted to get this issue resolved first. Thanks!

**Comment by humitos** [comment]
@CAM-Gerlach thanks for your report. There is already an issue to work on these points you mentioned mainly, the ability to contact the owner of the project at #3382. Unfortunately, nobody has been able to start with that one yet :(

> Also, I'd appreciate if you want to draft some more ideas in that issue that help us to define "What we shold build" and "How the flow should be".

I'm asking other core devs to see if I can get the contact of `maxgam` so I can help you guys.

Keep rocking with Spyder ;-)

**Comment by CAM-Gerlach** [comment]
@humitos 

> There is already an issue to work on these points you mentioned mainly, the ability to contact the owner of the project at #3382. Unfortunately, nobody has been able to start with that one yet :(

Thanks for letting us know, and sorry for the partial duplicate. For the time being, until a PR gets merged to implement that, might you want to modify

> The core team recommends users to get in touch with each other and solve the issue by respectful communication

in the docs since that's currently not possible (at least through RTD)?

> Also, I'd appreciate if you want to draft some more ideas in that issue that help us to define "What we shold build" and "How the flow should be".

I can't quite tell given the quote and syntax, but if this request is directed at me/us then I would be glad to at least provide some feedback, ideas and a (new) user perspective.

> I'm asking other core devs to see if I can get the contact of maxgam so I can help you guys.

Great! That's what we're hoping to do, so we can work this out with them.

> Keep rocking with Spyder ;-)

Thanks! We really appreciate your help!

**Comment by humitos** [comment]
> in the docs since that's currently not possible (at least through RTD)?

Nope. Currently is not possible to contact the owner of a project via RTD. This has been managed as you did: filling an issue and talking to the core devs (I've never been involved in this flow, but I'm trying to be helpul on this one as my first time)

> I can't quite tell given the quote and syntax, but if this request is directed at me/us then I would be glad to at least provide some feedback, ideas and a (new) user perspective.

Please do!

I have a vague idea on what we want to build, that's why I wanted to hear more ideas from people that really need this feature, regarding the flow for the user trying to contact the owner, and the flow for the owner. How things should be presented... etc

**Comment by CAM-Gerlach** [comment]
> Nope. Currently is not possible to contact the owner of a project via RTD. 

Right. So, my suggestion is that the docs be clarified as to this, as the implication in the current form is that that it is possible to contact the user (without going through this rather roundabout process).

> I have a vague idea on what we want to build, that's why I wanted to hear more ideas from people that really need this feature, regarding the flow for the user trying to contact the owner,

Sure, hopefully later tonight or early tomorrow I can do so. Thanks!

**Comment by humitos** [comment]
I already sent an email to `maxgam` communicating him this situation and linking this issue so `maxgam` can get more context. Let's see if he reply.

**Comment by CAM-Gerlach** [comment]
Thanks @humitos ! I'll await their reply.

**Comment by maxgamurar** [comment]
Hello there!
Please give me list of usernames to grant access for and I will do it right away.

Thanks

**Comment by maxgamurar** [comment]
Btw, I've added this repo as I was working on anaconda OSS docs package.

**Comment by ccordoba12** [comment]
Thanks @maxgamurar for your offer! My username in RTD is ccordoba12.

**Comment by maxgamurar** [comment]
@ccordoba12 done

**Comment by stsewd** [comment]
@humitos this seems resolved. Can be closed, right?

**Comment by CAM-Gerlach** [comment]
The RTD side of it, yes.  Thanks for your help @humitos et al!
