### ISSUE TITLE
Update AUTHORS.rst file

### ISSUE THREAD

**Issue by RichardLitt** [rtfd/readthedocs.org#3506]
It doesn't seem to have been updated since 2014.

**Comment by Jigar3** [comment]
I would like to take this issue.
Can you give me more details regarding it as I am new over here.
Any help is appreciated

**Comment by RichardLitt** [comment]
Welcome, @Jigar3! I think the easiest solution would be to go through the Contributors list and add in the names of users there to the list under 'Awesome Contributors'. You can do this by making a Pull Request to this repository. We can help with editing anyone who needs to be moved into a different category.

**Comment by Jigar3** [comment]
Thank you will do the same

**Comment by RichardLitt** [comment]
Well done, @Jigar3! Jump in with any other issues in the future if you'd like. Great work. :)

**Comment by Jigar3** [comment]
Thank you. 
Can you redirect me to some challenging issues which I could solve 
@RichardLitt. I also want to apply for gsoc this year so getting started with some demanding issues will be a great step forward.
Any help is appreciated

**Comment by RichardLitt** [comment]
@Jigar3 I would keep looking for "Good First Issue" issues. Some of them will be harder. As you scale up, just start picking issues you want that you think you may be able to do. Never worry about reaching out to us! Ask for help. We're here. :)
