### ISSUE TITLE
ReadTheDocs does not pull tags

### ISSUE THREAD

**Issue by axnsan12** [rtfd/readthedocs.org#3508]
## Details

* Project URL: https://readthedocs.org/projects/drf-yasg/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): cvijdea

## Expected Result

When I push a new tag with git, I expect ReadTheDocs to automatically pick it up and build the documentation for it.

## Actual Result

If you push a tag for an existing commit, ReadTheDocs does not react. You have to manually rebuild `latest` for it to realise there is now also a tag on the commit.

Steps to reproduce:

1. Create and push a commit
2. Tag the commit locally
3. Push the tag with ``git push --tags``
4. Watch as ReadTheDocs ignores it

Enabling the  `Create - Branch or tag created.` event for the GitHub webhook does not help.

**Comment by dlech** [comment]
Thanks for the workaround (manually rebuilding latest). I couldn't figure out why a tag worked last night but not today. Apparently I did something without realizing it last night.

It would be really nice to get #3546 merged.
