### ISSUE TITLE
Support different badge styles

### ISSUE THREAD

**Issue by wmayner** [rtfd/readthedocs.org#3509]
## Details

PR #3057 incidentally removed support for different badge styles that were available via https://shields.io/ querystrings. In projects that have badges from other services with other styles, this makes it more difficult to use a consistent badge style.

I will try to implement a PR for this if maintainers think it would be merged.

## Expected Result

`https://readthedocs.org/projects/pyphi/badge/?version=stable&style=flat-square` should return a badge without rounded edges.

## Actual Result

Only badges with rounded corners are available.

**Comment by agjohnson** [comment]
This seems reasonable. I would avoid adding any UX around this feature in RTD, but I think if users want to customize the badge via URL hacks, that is absolutely okay. I'm not sure if it makes sense to send a pruned list of query string args or not. I'd prefer pruning if we don't anticipate a lot of maintenance around the expected arguments. My only concern is that we're acting as a potentially malicious proxy to shields.io, so pruning might be good idea.

**Comment by fenilgandhi** [comment]
So, from what i understand, we can have different static badges in the media static folder and then they can be url pruned. This way we get different styles while not being dependent on https://shields.io

**Comment by stsewd** [comment]
This was solved in https://github.com/rtfd/readthedocs.org/pull/3632
