### ISSUE TITLE
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6548347)

### ISSUE THREAD

**Issue by zhaowei19920524** [rtfd/readthedocs.org#3511]
## Details

* Project URL: https://readthedocs.org/projects/mcmaster/
* Build URL (if applicable):https://readthedocs.org/projects/mcmaster/builds/6548347/
* Read the Docs username (if applicable): zhaowei0524@outlook.com

## Expected Result

Build success

## Actual Result

I don't know what happens. I only get some error info.

Having trouble with your build environment? Try reseting it. 
Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6548347).

**Comment by zhaowei19920524** [comment]
However, It works fine now. 
Please still have a look at what happens to that build process.

**Comment by safwanrahman** [comment]
Seems like your project was taking long time to setup.
Good to see it automatically fixed!
