### ISSUE TITLE
Py3 incompatibility

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3516]
I just realize that the `unicode` function is not available in Py3 and produces an error

https://github.com/rtfd/readthedocs.org/blob/909cb56ef69edb4fc36dbbf91f8c39422d5af041/readthedocs/doc_builder/python_environments.py#L164-L166

**Comment by stsewd** [comment]
It's going to be fixed in #3514 

https://github.com/rtfd/readthedocs.org/pull/3514/files#diff-31f8391d8643c47c6caedf53930c0b7eL166

See http://python-future.org/compatible_idioms.html#unicode

**Comment by humitos** [comment]
Using str will make the code fail in py2. I had that problem when i wore that code but i didn't realize that Unicode wasn't available in py3

**Comment by humitos** [comment]
Using str will make the code fail in py2. I had that problem when i wore that code but i didn't realize that Unicode wasn't available in py3

**Comment by humitos** [comment]
This is already fixed.
