### ISSUE TITLE
Delay in updating PDF

### ISSUE THREAD

**Issue by adamjstewart** [rtfd/readthedocs.org#3517]
## Details

* Project URL: https://github.com/adamjstewart/prolog
* Build URL: https://travis-ci.org/adamjstewart/prolog
* Read the Docs username: adamjstewart
* Read the Docs project name: prolog

## Expected Result

When I push a new commit to my GitHub repository, the HTML pages displayed on Rtd update almost immediately. I would expect the PDF to update at the same time.

## Actual Result

The PDF lags behind the HTML docs by around 1 day. As of right now, the Overview section of my docs is empty in the PDF. This section was written in [this](https://github.com/adamjstewart/prolog/commit/e91c9984be77bac749c411353d6dd24907363854#diff-e00a2dc1684e3f015ea142465fcce703) commit 18 hours ago.

If this is normal and the PDFs are only generated once per day, I would expect this to be noted somewhere in the documentation. If this is not normal, let me know if there are any errors on my side.

Note: this issue may be related to #2758 in which other users reported their PDF files not being updated. They may have simply not waited long enough for them to be generated.

@ZaidQureshi

**Comment by adamjstewart** [comment]
If I look at the most recent [build log](http://readthedocs.org/projects/prolog/builds/6561919/), it does indeed appear to be building both HTML and PDF versions of the documentation after each commit. I don't see any errors during the PDF build, so I'm not sure why it is not being updated on the website.

**Comment by stsewd** [comment]
May be related to https://github.com/rtfd/readthedocs.org/issues/4428

**Comment by asr** [comment]
I had the same issue in our project. After deleting the cached web content from my browser the issue was fixed.

**Comment by stsewd** [comment]
@asr thanks for the confirmation!

Looks like this is mostly due a browser/CDN/ISP caching issue, closing.
