### ISSUE TITLE
Code question: is old code needed

### ISSUE THREAD

**Issue by Blendify** [rtfd/readthedocs.org#3521]
## Details

https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/core/static-src/core/js/doc-embed/sphinx.js#L25

This whole thing seems rather confusing to me. One thing references a theme issue that was fixed and the other why are we dynamically adding the class?

**Comment by humitos** [comment]
@Blendify is issue still relevant?

It seems the link points to a place that it's not the right one, from my perspective.

Also, it's under `Mkdocs` milestone but it doesn't seems to be related to mkdocs :thinking:

**Comment by Blendify** [comment]
Can be closed
