### ISSUE TITLE
Documentation about preferences for tags over branches on stable version

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3528]
## Details

As mention here https://github.com/rtfd/readthedocs.org/issues/3268#issuecomment-358057139

> If you want to keep 2.0 as the stable while having a 3.0 branch, you can create a tag for 2.0 and that will be considered the stable. That way, RTD will take preferences for tags over branches to decide which one is the stable.

I think this needs to be documented here http://docs.readthedocs.io/en/latest/versions.html

**Comment by phyowaimg** [comment]
#3268
