### ISSUE TITLE
No such file or directory: 'docs/requirements.txt'

### ISSUE THREAD

**Issue by lk-geimfari** [rtfd/readthedocs.org#3529]
## Details

* Project URL: http://mimesis.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/mimesis/builds/6582000/

## Expected Result

The successful build of the docs.

## Actual Result

Build fails because RTD does not find file `requirements.txt`, which was defined  in `Advanced settings`:

![screenshot from 2018-01-18 07-44-15](https://user-images.githubusercontent.com/15812620/35081174-6ce43200-fc23-11e7-8fe1-2a15fba47488.png)

```
Could not open requirements file: [Errno 2] No such file or directory: 'docs/requirements.txt'
```

**Comment by stsewd** [comment]
Hi, your stable version is the `v1.0.4` tag, https://github.com/lk-geimfari/mimesis/tree/v1.0.4. On this version there isn't a `docs/requirements` file `https://github.com/lk-geimfari/mimesis/tree/v1.0.4/docs/requirements.txt`

**Comment by lk-geimfari** [comment]
@stsewd I forgot to create a new tag. Sorry for this and thank you very much for the fulminant feedback.
