### ISSUE TITLE
Build failed without details

### ISSUE THREAD

**Issue by johanneskoester** [rtfd/readthedocs.org#3531]
## Details

* Project URL: https://snakemake.readthedocs.io
* Build URL (if applicable): http://readthedocs.org/projects/snakemake/builds/6583093/
* Read the Docs username (if applicable): johanneskoester

## Expected Result

An automatic build should succeed

## Actual Result

It failed without further details: http://readthedocs.org/projects/snakemake/builds/6583093/

**Comment by johanneskoester** [comment]
This happens now since one week.

**Comment by RichardLitt** [comment]
Related to #1822.

**Comment by johanneskoester** [comment]
Yes that helps, thanks a lot!
