### ISSUE TITLE
searchtools.js missing init() call

### ISSUE THREAD

**Issue by malarzm** [rtfd/readthedocs.org#3532]
It seems like something is off with generating `searchtools.js`, it's ending with

```
/* Search initialization removed for Read the Docs */
```

instead of

```
$(document).ready(function() {
  Search.init();
});
```

Cross-referencing: https://github.com/doctrine/doctrine-sphinx-theme/pull/14

## Details

* Project URL: http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/
* Build URL (if applicable): https://readthedocs.org/projects/doctrine-mongodb-odm/builds/6583841/
* Read the Docs username (if applicable): malarzm

## Expected Result

Working search

## Actual Result

Not working search

**Comment by agjohnson** [comment]
Not sure of the actual issue here. This removal is on purpose, as we monkey patch the Sphinx included search with our search index. Closing this for now.

**Comment by malarzm** [comment]
@agjohnson can you please tell more about about the monkey patching process? It's somehow broken (or not working) in our case and I can't infer how it should be working basing on other readthedocs projects, also found nothing useful in the documentation. FWIW the search works perfectly fine in a locally built sphinx pages.
