### ISSUE TITLE
Project in the local read the docs don't see tags.

### ISSUE THREAD

**Issue by AnatoliyURL** [rtfd/readthedocs.org#3534]
## Details

* Project URL: local project.

## Expected Result

*I can see my tags and choose version in the admin panel*

## Actual Result

*ReadTheDocs pull repository without tags.*
I used one and the same project in local ReadTheDocs and in the readthedocs.org (url: https://readthedocs.org/projects/testdocstola/)

Tags is see in the readthedocs.org but not see in the local. 

I did one and the same action. 

How do you think. What is the problem? 
What need to do in order to have a stable version?
what are the required conditions to be met?

Local version read the docs 2.1.3
Use lightweight and annotated tags

I'm sorry my english.

**Comment by RichardLitt** [comment]
@AnatoliyURL Your English is fine. :) 

Any reason you closed this? Did you solve the problem?

**Comment by AnatoliyURL** [comment]
Well. I'm stupid man.)
We used old version read the docs 2.1.3. This version not supported tags.
This problem exactly solved in 2.1.5.
I'm sorry that I disturbed you. 
Thanks for the answer. :)


22 янв. 2018 г. в 13:41 Richard Littauer <notifications@github.com> написал(а):

@AnatoliyURL Your English is fine. :)

Any reason you closed this? Did you solve the problem?
