### ISSUE TITLE
Better UI for editing sub-projects (e.g. "Edit" button)

### ISSUE THREAD

**Issue by jflory7** [rtfd/readthedocs.org#3538]
## Background

See some background discussion in #1341 (relevant comment [here](https://github.com/rtfd/readthedocs.org/issues/1341#issuecomment-358802027)).

## Details

Editing a sub-project is not clear. To edit one, you have to click the title of the project, which is also close to the button to take you to the project page. I was confused at first about how to edit a project and commented in the previous issue, where I found out I was mis-clicking.

An "Edit" button would make this clear and hard to mistake.

## Expected Result

1. Go to sub-project menu
2. See "Edit" button
3. Change canonical URL, name, etc.

## Actual Result

1. Go to sub-project menu
2. Click project title
3. Change canonical URL, name, etc.

**Comment by apoorvkhare07** [comment]
Is this still up for taking ?

**Comment by stsewd** [comment]
@apoorvkhare07 there is  a PR already #3572 

You can check this by seeing the references that GitHub puts after the issue.

**Comment by jflory7** [comment]
Whoooo! Happy to see this added. Thanks RTD team! :tada:
