### ISSUE TITLE
Link to open an issue from a failed Build with pre-filled details

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3539]
There are several issues that are reported where there are missing information in the details section.

To solve this I was thinking on generating a link inside this message that could contain all the information pre-filled:

![captura de pantalla_2018-01-22_15-07-15](https://user-images.githubusercontent.com/244656/35242041-6ed4e288-ff86-11e7-9b89-c69a45505318.png)

I found that github supports _some_ query arguments in the URL but I didn't found a way to use those key/args inside the template itself.

https://help.github.com/articles/about-automation-for-issues-and-pull-requests-with-query-parameters/

I think it would be awesome if the user can just click a link and the username, project url, etc could be pre-filled automatically.

**Comment by RichardLitt** [comment]
Could you not have the link generated with that information in the body tag?

**Comment by humitos** [comment]
Yeah, _maybe_.

The template is 227 chars long, if we add the project and build link plus username I'm not sure if we are not creating a too long URL that it's not standard. I know there is a limit and I think it depends on the browser also...

https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

We could do that since the limit is around 2000 chars.

**Comment by agjohnson** [comment]
Neat idea. We need to make sure wouldn't show on the .com though, as we don't want github issues for those issues.

**Comment by stsewd** [comment]
What about putting this information on the header of the raw build log (see #3585)? So the user can just referrer that link or copy/paste the raw log on the issue.

**Comment by bansalnitish** [comment]
Hi @humitos, May I work on this!

**Comment by RichardLitt** [comment]
@bansalnitish It doesn't look like @humitos has opened a PR for this; he's only specified a need for it. I'd say go ahead! :)

**Comment by bansalnitish** [comment]
Thanks @RichardLitt!

**Comment by bansalnitish** [comment]
Hi @humitos, Can you please help me in reproducing this issue!

**Comment by humitos** [comment]
@bansalnitish hey! What you need?

The idea is to add a link in the build page (showed when it fails) that opens an issue in this Github project.

(there is a link to the GH docs to generate that link in the description)

**Comment by bansalnitish** [comment]
I got it @humitos, Thanks! I will be soon submitting a PR for the same!
