### ISSUE TITLE
Unknown locale u'ia'

### ISSUE THREAD

**Issue by clefebvre** [rtfd/readthedocs.org#3562]
## Details

* Project URL: https://readthedocs.org/projects/linuxmint-installation-guide-ia
* Build URL (if applicable): https://readthedocs.org/projects/linuxmint-installation-guide-ia/builds/6647565/
* Read the Docs username (if applicable): linuxmint

## Expected Result

The documentation should be in Interlingua.

## Actual Result

The documentation is in English.

## More Info

Hi, 

There seem to be a regression recently. This documentation has been compiling successfully for a month now and always properly showed up in Interlingua.

A few days ago, we noticed it now showed up in English instead.

The RTD configuration didn't change and neither did the PO translations.

Looking at the build logs, it seems Sphinx was updated and now seems more strict than before with non-supported languages.

The list of supported languages by Sphinx is available at http://www.sphinx-doc.org/en/stable/config.html#confval-language. It does not contain Interlingua.

In the latest build (which fails to be translated in Interlingua), we see the following warning:

```
Running Sphinx v1.6.5
making output directory...
loading translations [ia]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 17 po files that are out of date
writing output... [  5%] ../po/ia/LC_MESSAGES/burn.mo
WARNING: reading error: /home/docs/checkouts/readthedocs.org/user_builds/linuxmint-installation-guide-ia/checkouts/latest/docs/../po/ia/LC_MESSAGES/burn.po, unknown locale u'ia'

```

In previous builds (where the documentation was properly translated), we saw warnings as well, but they didn't prevent the translation from taking place:

```
Running Sphinx v1.5.6
making output directory...
loading translations [ia]... not available for built-in messages
loading pickled environment... not yet created
building [mo]: targets for 17 po files that are out of date
writing output... [  5%] ../po/ia/LC_MESSAGES/burn.mo
WARNING: reading error: /home/docs/checkouts/readthedocs.org/user_builds/linuxmint-installation-guide-ia/checkouts/latest/docs/../po/ia/LC_MESSAGES/burn.po
```

I'm not sure that's the cause of the issue. I'm not even sure it's related. I'm mentioning it in case it helps.

**Comment by RichardLitt** [comment]
Thanks @clefebvre. It sounds like this is unfortunately a Sphinx issue, not a Read The Docs issue. Can you open a ticket on the Sphinx project, and reference this here?

**Comment by stsewd** [comment]
Closing this as isn't a RTD issue but Sphinx.
