### ISSUE TITLE
Fonts are sent without gzip compression

### ISSUE THREAD

**Issue by jessetan** [rtfd/readthedocs.org#3564]
The fonts used (Lato and Roboto) are not sent using gzip compression. This makes them responsible for the bulk of the traffic on an initial page load. See the blue bars in the following graph:
![network-rtd](https://user-images.githubusercontent.com/3284111/35559962-541ddd1a-05ac-11e8-88e7-c83dbea52ed9.png)

Suggestion:
Turn on gzip compression for the following types in the RTD nginx config. 

extension|MIME type
---|--
ttf|[`application/font-sfnt`](https://www.iana.org/assignments/media-types/application/font-sfnt) (or old style `application/x-font-ttf`)
otf|[`application/font-sfnt`](https://www.iana.org/assignments/media-types/application/font-sfnt) (or old style `application/x-font-otf`)
eot|[`application/vnd.ms-fontobject`](https://www.iana.org/assignments/media-types/application/vnd.ms-fontobject)

This may have already been fixed, as suggested by https://github.com/rtfd/readthedocs.org/issues/2955#issuecomment-354143668, but the actual PR and files are not publicly visible so it cannot be verified if the mime types for these fonts are set up properly. This also does not mention otf fonts.

Note that woff(2) fonts [do not seem to benefit from gzip compression](http://www.phpied.com/font-face-gzipping-take-ii/).

**Comment by davidfischer** [comment]
As far as I can tell, these fonts are sent without compression regardless of whether the request says it can handle gzip compression. I will look to see if I can get this resolved.

**Comment by davidfischer** [comment]
I'm thinking perhaps the easiest way to solve this is just to change the theme to bundle woffs instead of TTFs.

**Comment by jessetan** [comment]
I've looked into changing the TTF file in the theme to WOFF(2) files, but I haven't found the exact same version of the lato font yet. Even if I use new TTF files I get a slightly different look in Chrome on macOS, probably due to increased hinting information in newer versions of the font.
Until we can get exactly the same visual appearance with WOFF, turning on gzip compression will save at least some bandwidth. It will also work for other themes that might use TTF.

**Comment by davidfischer** [comment]
We bundled the woff files for the .org in this PR: https://github.com/rtfd/readthedocs.org/pull/3982

I generated these woff files on fontsquirrel.

**Comment by davidfischer** [comment]
This is now resolved. After we moved all our static media to `assets.readthedocs.org` which is served by Azure's CDN solution all static assets serve with correct gzip settings.
