### ISSUE TITLE
read the docs does not read in certain python modules

### ISSUE THREAD

**Issue by nkasmanoff** [rtfd/readthedocs.org#3566]
## Details

* Project URL: http://burstcube.readthedocs.io/en/master/
* Build URL (if applicable):
* Read the Docs username (if applicable): nkasmanoff

## Expected Result
A more or less complete form of documentation for a series of python modules. 
*A description of what you wanted to happen*

## Actual Result
Using sphinx I have a list of python modules to be read in and have their respective functions and annotations displayed, but this is not the case for some of the modules when run through the readthedocs build. 
*A description of what actually happened*
Attached below are screenshots of the expected result (what happens when I generate the sphinx html locally, and what happens on the readthedocs website. 

locally generated html:

<img width="1036" alt="screen shot 2018-01-31 at 2 27 37 pm" src="https://user-images.githubusercontent.com/22650065/35643038-09c80a3c-0693-11e8-9fbd-f991237bb16d.png">

read the docs version: 

<img width="1041" alt="screen shot 2018-01-31 at 2 27 56 pm" src="https://user-images.githubusercontent.com/22650065/35643045-11ec6e88-0693-11e8-8ba6-8c41abded7d2.png">

Those screenshots are meant to demonstrate that through readthedocs, bcSim for instance does not have the same annotations I want it to have. 
Any advice would be much appreciated. 

Thanks,

Noah

**Comment by nkasmanoff** [comment]
After reading through the build I've found that it fails for these programs because they depend on numpy and matlplotlib which readthedocs is unable to find.

**Comment by nkasmanoff** [comment]
found solution in previous issues.

**Comment by RichardLitt** [comment]
Thanks for updating us, @nkasmanoff.
