### ISSUE TITLE
Is it possible to add a simple feedback form on each page of my documentation project as we have copyright info now? 

### ISSUE THREAD

**Issue by veenamj** [rtfd/readthedocs.org#3568]
## Details

* Project URL: community user
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

*We need to add a feedback form at the bottom of each page. So, is there any solution. I could get this https://github.com/rtfd/readthedocs.org/issues/2533 but it is still an open issue. 

## Actual Result

*Request tips to add a feedback form.

**Comment by stsewd** [comment]
Probably this could be a partial solution for now https://docs.readthedocs.io/en/latest/faq.html#i-want-comments-in-my-docs

**Comment by davidfischer** [comment]
One possibility is to embed a form directly with a `raw` directive. The documentation for readthedocs.org [used to have one](https://github.com/rtfd/readthedocs.org/commit/943fabd5a615114c0658e6e261907442fa5eb8c9#diff-42131210f9da9ab7f8109bf9af79860eL119).

Like the disqus plugin @stsewd mentioned, this may be best handled by a 3rd party Sphinx plugin.

**Comment by veenamj** [comment]
Thank you, @stsewd  and @davidfischer. I added sphinxcontrib-disqus in the conf,.py extensions and requirements file. I ran pip install sphinxcontrib-disqus. After running make html (a local build), I get this error -  
```
Extension error:
Could not import extension sphinxcontrib-disqus (exception: No module named sphinxcontrib-disqus)
make: *** [html] Error 1
```
Pip install went fine though. What would be the fix for this? Thanks in Advance.

**Comment by davidfischer** [comment]
@veenamj if you have a build URL, that would be helpful.

**Comment by veenamj** [comment]
There is no build URL  it is just a local build. I run the command and I get this error as soon as the command is executed?

**Comment by davidfischer** [comment]
If the build isn't on readthedocs, this doesn't sound like a readthedocs issue. Perhaps open an issue on https://github.com/Robpol86/sphinxcontrib-disqus.

**Comment by veenamj** [comment]
Thanks @davidfischer  I will raise it as an issue on  https://github.com/Robpol86/sphinxcontrib-disqus.

**Comment by veenamj** [comment]
I haven't posted anything on the disqus site. It looks like we need to create an account on Disqus site and add that to our project as described in http://www.milos.curuvija.com/miscellaneous/sphinx/how_to_integrate_disqus_with_sphinx.html

@davidfischer  and @stsewd  - This is FYI.

**Comment by davidfischer** [comment]
I'm going to close this as it doesn't appear to be a RTD issue.

**Comment by tinhoang-cerebras** [comment]
I'm also looking for a solution to add a feedback option at the bottom of readthedocs pages. either a stars, thumbs up/down...anyone have luck doing this?

**Comment by humitos** [comment]
@tinhoang-cerebras Hi! There is a long conversation on another project about this that you can read to get more ideas: https://github.com/pypa/pip/issues/8784. Read the Docs does not officially support any kind of feedback right now.
