### ISSUE TITLE
Build failed without error message

### ISSUE THREAD

**Issue by nilsnolde** [rtfd/readthedocs.org#3576]
## Details

* Project URL: https://readthedocs.org/projects/openrouteservice-py
* Build URL (if applicable): https://readthedocs.org/projects/openrouteservice-py/builds/6679713/
* Read the Docs username (if applicable): nilsnolde

## Expected Result

Build should have passed.

## Actual Result

Build failed.

**Comment by vidartf** [comment]
I'm seeing the same behavior across two different projects as well.

**Comment by agccie** [comment]
I'm also seeing the same issue although the latest documentation seems to be correct.
https://readthedocs.org/projects/aci-enhancedendpointtracker/builds/6680075/

**Comment by stsewd** [comment]
On my local instance the build succeeded, seems like a problem on the servers.

**Comment by nilsnolde** [comment]
Builds again. Probably a temp server failure...

**Comment by nilsnolde** [comment]
Sorry, that was too quick apparently. It says it builds successfully, but then it doesn't compile the autodoc sections at all: 
[](http://openrouteservice-py.readthedocs.io/en/latest/openrouteservice.html#openrouteservice-client-module)

**Comment by stsewd** [comment]
@nilsnolde that's because autodoc can't find the package, you need to mark the `Install Project` option on your project settings. And I believe injecting your project path here https://github.com/GIScience/openrouteservice-py/blob/master/docs/source/conf.py#L21 also can work.

**Comment by nilsnolde** [comment]
Oopsa, didn't see that option. Sorta figured that'd happen automatically. Thanks @stsewd for the info, it worked beautifully:) I rather set the option in advanced settings than sys.path injections.

**Comment by W3-Anjan** [comment]
Hello, on my project home page  [read the docs](https://github.com/w3-engineers/telemesh) build is failed. On the other hand, when I am trying to build from my profile it is successful but the home page is not updating. This problem occurs for the 1st time. @stsewd I don't find the `Install Project ` option

**Comment by stsewd** [comment]
@W3-Anjan I can see your docs at https://telemesh.readthedocs.io/en/latest/. If there is something else missing please describe it a little in a new issue.
