### ISSUE TITLE
RTD replaces branch/release with branch-release and 404's "Edit on Github" URL to docs

### ISSUE THREAD

**Issue by scaleoutsean** [rtfd/readthedocs.org#3578]
## Details

RTD adds a broken "Edit on Github" URL to docs.

Repro:
1) https://netapp-trident.readthedocs.io/en/stable-v18.01/ 
2) click on "Edit on Github".

* Project URL: https://github.com/NetApp/trident
* Build URL (if applicable): https://github.com/NetApp/trident/releases/tag/v18.01.0
* Read the Docs username (if applicable): netapp-trident (https://netapp-trident.readthedocs.io/en/stable-v18.01/)

## Expected Result

`Edit on Github` should not be broken.

## Actual Result

RTD replaces our `stable/v18.01` with `stable-v18.01` which breaks Edit on Github URLs (and possibly some other links to the repo).

(Ref: https://github.com/NetApp/trident/issues/90)

**Comment by humitos** [comment]
Thanks for the report. This is an already known bug and it's addressed at #1989 and a PR already merged at #3545 so, this should be solved in the next deploy.

**Comment by scaleoutsean** [comment]
Thanks. I did search open issues but not the closed ones :-)
