### ISSUE TITLE
Viewing / Modifying Redirects

### ISSUE THREAD

**Issue by JordonPhillips** [rtfd/readthedocs.org#3583]
## Details

* Project URL: https://boto3.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

I want to find out what redirects I have configured. I go to the redirect section of the admin page or call an api to get the information. If a redirect is incorrect I can then modify or delete it.

## Actual Result

I go to the redirect section of the admin page and see something like this:

![download](https://user-images.githubusercontent.com/2643092/35939310-9a89fc7a-0c00-11e8-8b54-c01a971d6690.png)

These bars provide no information on what the redirect is. If a redirect is improperly configured, the only way to fix it is to delete every redirect and then re-create them with the fix.

There appears to be no way to read or write redirects via the api.

**Comment by stsewd** [comment]
Thanks for reporting, I think this is a duplicate of #2431

**Comment by RichardLitt** [comment]
Agreed. Thank you, @JordonPhillips!
