### ISSUE TITLE
Github webhook stopped working, resync fails

### ISSUE THREAD

**Issue by dplanella** [rtfd/readthedocs.org#3587]
## Details

* Project URL: http://adafruit-beaglebone-io-python.readthedocs.io
* Build URL: https://readthedocs.org/projects/adafruit-beaglebone-io-python/builds/
* Read the Docs username: dplanella
* Upstream: https://github.com/adafruit/adafruit-beaglebone-io-python/blob/master/docs/index.rst

## Expected Result

- Documentation is automatically built upon an upstream git commit
- The latest tags are pulled as a result and can be enabled for documentation builds in the readthedocs admin interface

## Actual Result

Both points above used to work until about two months ago. Since then, despite multiple commits at the upstream project, the documentation is neither automatically built nor are the latest upstream tags pulled.

Resyncing the Github hook results in a "Fail.  Check back in a bit!" message. No matter how long the wait and how many retries, the error does not get fixed:
https://readthedocs.org/dashboard/adafruit-beaglebone-io-python/integrations/19437/sync/

**Comment by humitos** [comment]
@dplanella Hi! I think that I found the issue with this and I opened a PR at #3931 that I suppose that should fix the issue.

Can you check if you have a RTD webhook enabled under https://github.com/adafruit/adafruit-beaglebone-io-python/settings/hooks?

Also, can you check that you have an Integration under https://readthedocs.org/dashboard/adafruit-beaglebone-io-python/integrations/? (please, do not remove it since there is another issue with that: #3932)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also https://github.com/rtfd/readthedocs.org/issues/3931 was resolved. And I can't replicate the problem in my account.

**Comment by dplanella** [comment]
@humitos sorry for the delay, I hadn't noticed the bug had had a reply after all those months. Thanks a lot for looking at this.

To your questions:

> Can you check if you have a RTD webhook enabled under https://github.com/adafruit/adafruit-beaglebone-io-python/settings/hooks?

There is not such a directory in the code. The webhook used to work without it, before it broke.

> Also, can you check that you have an Integration under https://readthedocs.org/dashboard/adafruit-beaglebone-io-python/integrations/?

I do have a "GitHub incoming webhook" integration in there. That was the non-working one I was referring to in the initial bug post. The good news is, that when I now click on it and then at "Resync webhook", **I no longer get the error message**.

However, the sync history says that the last sync was 7 months ago (see screenshot below). I was expecting the sync to happen automatically. Is there anything else I should do on my side to get the syncs back to work?

![adafruit](https://user-images.githubusercontent.com/1689781/42584278-1f6ad4d6-8533-11e8-8e95-906458479b31.jpg)

**Comment by pdp7** [comment]
@dplanella I can not seem to access https://github.com/adafruit/adafruit-beaglebone-io-python/settings/hooks so I have asked @ladyada, @tdicola and @tannewt to check if they have permissions to do so

**Comment by ladyada** [comment]
@pdp7 hi yep here's the current hooks
![image](https://user-images.githubusercontent.com/1214161/43041850-8f15271e-8d3a-11e8-9d30-0564ed31b5ce.png)
what do you want added?

**Comment by pdp7** [comment]
@dplanella Do you know what webhook should be added to `adafruit-beaglebone-io-python`?

**Comment by stsewd** [comment]
@pdp7 Thanks for the update!
