### ISSUE TITLE
Unable to verify email address on the website

### ISSUE THREAD

**Issue by fgimian** [rtfd/readthedocs.org#3590]
## Details

* Project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): fgimian

## Expected Result

1. I receive an email with a link to confirm my email address **works**
2. I click the link and see a page that asks me to confirm **works**
3. I click confirm and expect a success message **fails**

## Actual Result

After clicking confirm I see:

```
Forbidden (403)
CSRF verification failed. Request aborted.
More information is available with DEBUG=True.
```

**Comment by davidfischer** [comment]
I just ran through the signup flow without an issue. This is a cross-site request forgery (CSRF) protection failure which requires cookies to work correctly. Do you happen to have cookies disabled? This issue can also occur if you clear your session between when you click the email and when you submit the "confirm" although that seems unlikely.

Would you mind trying again?

**Comment by fgimian** [comment]
Thanks so much for your reply @davidfischer, I tried again just now and everything worked correctly.  Not sure what was going on yesterday 😄 

Cheers
Fotis
