### ISSUE TITLE
Delete deprecated project that no longer has a github project

### ISSUE THREAD

**Issue by tpeeters** [rtfd/readthedocs.org#3591]
I would like to delete the project on http://mintapi.readthedocs.io
The associated github repositories were deleted a while ago. The company that was providing these APIs is no longer called Mint Labs, and the old API that is documented on readthedocs.io no longer works.

Can you please remove mintapi.readthedocs.io for me?

Thank you.

**Comment by stsewd** [comment]
The read the docs project is yours?

**Comment by tpeeters** [comment]
No, it was was created to host the documentation for a library provided by the company that I work for now, but the person who originally created the readthedocs project is no longer employed here (for several years already). I am now tasked with removing the incorrect/outdated documentation online and nobody has the account on read the docs that owns the project.

**Comment by stsewd** [comment]
There is a policy for abandoned projects, hope it helps a little https://docs.readthedocs.io/en/latest/abandoned-projects.html

Related #3382

**Comment by stsewd** [comment]
Looks like the project is removed, feel free to re-open if you consider.
