### ISSUE TITLE
Add branding guidelines

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3594]
## Details

I think this information needs to be on the docs index page and/or on the footer of the RTD site.

There is a repo containing the guidelines https://github.com/readthedocs/guidelines, but there is no mention where is the rtd project.

**Comment by Jigar3** [comment]
I would like to take this issue @stsewd. 
Can you give me details about how to accomplish this as I am new over here.
Any help is appreciated.

**Comment by stsewd** [comment]
@Jigar3 hi, thanks for your interest on collaborating! I think first we need to wait to some maintainer to tell us where is the guidelines rtd project. Then make a PR adding a link to the guidelines here https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/base.html#L101 and/or https://github.com/rtfd/readthedocs.org/blob/master/docs/index.rst

**Comment by Jigar3** [comment]
Till then can you suggest some beginner friendly issues

**Comment by stsewd** [comment]
You can search for issues with this label https://github.com/rtfd/readthedocs.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22

**Comment by stsewd** [comment]
I found the guidelines on other repo https://github.com/rtfd/guidelines https://read-the-docs-guidelines.readthedocs-hosted.com/branding.html

**Comment by dojutsu-user** [comment]
@stsewd I would like to take this issue up. Can you guide me on this?

**Comment by stsewd** [comment]
I updated my comment above https://github.com/rtfd/readthedocs.org/issues/3594#issuecomment-365070276

A link to will be needed https://read-the-docs-guidelines.readthedocs-hosted.com/branding.html

I think we still need a decision to where is the better place for this

**Comment by stsewd** [comment]
Maybe something like https://python.org? It says `Python Logo`

Also, I think @agjohnson or @davidfischer can help with the decision here

**Comment by davidfischer** [comment]
At the very least, there should be a link to the [guidelines repo](https://github.com/rtfd/guidelines) on the [design docs](https://docs.readthedocs.io/en/latest/design.html).

I think putting it in the footer of readthedocs.org is good too. I would put it under "business info" (as in the screenshot) and I'd call it "Branding" as opposed to "Branding Guidelines".

**Comment by dojutsu-user** [comment]
@davidfischer Where do you want the link to [guidelines repo](https://github.com/rtfd/guidelines) on the [design docs](https://docs.readthedocs.io/en/latest/design.html)? footer?

**Comment by stsewd** [comment]
@dojutsu-user I think both, also I think is better to link to the docs page https://read-the-docs-guidelines.readthedocs-hosted.com/ rather than the repo

**Comment by dojutsu-user** [comment]
@stsewd 
i have a doubt.
The changes in the image above is approved in the [comment above](https://github.com/rtfd/readthedocs.org/issues/3594#issuecomment-434364784) with the text `Branding` under the `Business Info` (Will make a PR soon on this).

and i am still unclear about where to add the link in the design docs?
the footer of it is :
![screenshot from 2018-10-31 01-02-58](https://user-images.githubusercontent.com/29149191/47745144-ffdba000-dca8-11e8-9f79-52a69dbcae24.png)
and i am unable to find a suitable place to add it.

**Comment by stsewd** [comment]
On the design docs, I think probably adding a new subtitle makes sense

**Comment by davidfischer** [comment]
> I think is better to link to the docs page https://read-the-docs-guidelines.readthedocs-hosted.com/ rather than the repo

This is good.

> On the design docs, I think probably adding a new subtitle makes sense

Agreed.

**Comment by dojutsu-user** [comment]
@stsewd okay.. i get it
so what will come under the subtitle.

My suggesstion:

![screenshot from 2018-10-31 11-29-29](https://user-images.githubusercontent.com/29149191/47769056-76f05300-dd00-11e8-800b-cb85dcc17668.png)

**Comment by stsewd** [comment]
Looks good to me, maybe just putting `here` instead of a naked link?

**Comment by dojutsu-user** [comment]
@stsewd 
I think this issue can be closed.

**Comment by stsewd** [comment]
Yes, it was resolved in https://github.com/rtfd/readthedocs.org/pull/4830
