### ISSUE TITLE
`CondaValueError: pip returned an error` while creating the conda environment

### ISSUE THREAD

**Issue by paugier** [rtfd/readthedocs.org#3603]
## Details

* Project URL: fluidsim
* Build URL (if applicable): https://readthedocs.org/projects/fluidsim/builds/6740246/
* Read the Docs username (if applicable): paugier

## Expected Result

Building the doc with conda (as described in the files `.readthedocs.yml` and `doc/environment.yml`).

## Actual Result

The build fails at the first command (creating the conda environment) with the **very short error log**:

```
  Running setup.py bdist_wheel for fluidfft: started

CondaValueError: pip returned an error.
```

See the [failing build](https://readthedocs.org/projects/fluidsim/builds/6740246/) and a very similar [succeeding build (Completed Nov. 22, 2017)](https://readthedocs.org/projects/fluidsim/builds/6305716/). Note that pip has to install exactly the same packages for the two builds (with the same pip version).

Of course I can create the environment at home with the commands:
```
hg clone https://bitbucket.org/fluiddyn/fluidsim
conda env create --name latest --file fluidsim/doc/environment.yml
```

**Comment by Tikam02** [comment]
Try running as default environment 2.7 or 3.4, without anaconda

**Comment by paugier** [comment]
Thank you for the advice, but I don't see how the documentation could be built without conda. The dependencies:
```
  - numpy
  - cython
  - h5py
  - sphinx
  - numpydoc
  - jupyter
  - matplotlib
  - fftw
  - pyfftw
  - mako
```

FFTW on the readthedocs server without conda?

For scientific code, it is a very nice feature of readthedocs to be able to work with conda. I don't see how I could use readthedocs without conda (or a similar distribution) for such type of codes.

**Comment by stsewd** [comment]
I tested on my local instance, seems like a problem with your repo visibility, I tried `git clone https://bitbucket.org/fluiddyn/fluidsim` on my terminal and also fails.

**Comment by paugier** [comment]
I think the repository has no problem. It is a Mercurial repository and Git can not handle Mercurial repositories (while it is possible to clone a Git repository with Mercurial).

Anyway, can you please try with
```
hg clone https://bitbucket.org/fluiddyn/fluidsim
```

**Comment by stsewd** [comment]
@paugier, sorry, my bad. I was able to pass the first step on my local instance, but increasing the memory and time limits. So I think that's the problem here (memory limit exceeded).

**Comment by paugier** [comment]
Thank you for the hint. Do you know what are the memory and time limits for the "production" instance?

**Comment by stsewd** [comment]
According to https://docs.readthedocs.io/en/latest/builds.html#build-process 1GB and 15 minutes.

**Comment by paugier** [comment]
Thanks a lot @stsewd for your time and your useful hint. I manage to decrease the memory usage during the build and the new version of the documentation is now available!

Of course, it could be nice to get an explicit warning when the memory or time limits are exceeded.

**Comment by RichardLitt** [comment]
> Of course, it could be nice to get an explicit warning when the memory or time limits are exceeded.

This would be good, I think. Any chance you'd like to work on a PR for this? If not, let's flag open a new ticket for this.

**Comment by stsewd** [comment]
@RichardLitt I create a new issue for this (#3613).
@paugier glad I was helpful here :)

**Comment by mrconway** [comment]
I've been getting this error for the past couple of months without any change in the build procedure:

https://readthedocs.org/projects/alphapy/builds/7177424/

Could be a memory limit issue as well...

**Comment by RichardLitt** [comment]
@mrconway Could you open a new issue and reference this one for that? This should have been resolved, so we should look into your error separately.
