### ISSUE TITLE
How does RTD know all project versions even for older releases

### ISSUE THREAD

**Issue by Blendify** [rtfd/readthedocs.org#3606]
I am trying to understand how the version selector gets all the version numbers even for older versions of the docs. In some example projects, I looked at few were defined in the HTML I assume the rest ad injected by a javascript? Can someone help clear this up for me? Thank you.

**Comment by stsewd** [comment]
This is done with a call to the rtd API (`/footer_html` endpoint) 

https://github.com/rtfd/readthedocs.org/blob/0c547f47fb9dffbeb17e4e9ccf205a10caf31189/readthedocs/restapi/urls.py#L43

Here is the js call

https://github.com/rtfd/readthedocs.org/blob/0c547f47fb9dffbeb17e4e9ccf205a10caf31189/readthedocs/core/static-src/core/js/doc-embed/footer.js#L40-L58

**Comment by Blendify** [comment]
Thanks.
