### ISSUE TITLE
Add venv to the .gitignore file

### ISSUE THREAD

**Issue by mohitkyadav** [rtfd/readthedocs.org#3609]
## Expected Result

Python virtual environment files should be ignored.

## Actual Result

Currently venv folder is not ignored by git.

I would like to send a PR, I'm also looking forward to apply for GSoC 2018 in readthedocs org please guide me.

**Comment by RichardLitt** [comment]
I think this would be a pretty good PR! Since it's simple, I would go ahead and open it up. :)
