### ISSUE TITLE
Dropdown to select Advanced Settings

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3610]
There are bunch of input fields under `Admin -> Advanced Settings` that could be converted into a dropbox:

* Default branch
* Default version

(this will limit the user to just those _active_/possible versions instead of writting things that are invalid or does not exist)

Also, this would involve more coding (since we need to populate the dropdown with data that we don't have in the database at the moment), but would be a good addition also:

* Requirements file
* Python configuration file

> This will probably need more discussion before start working on the implementation regarding the UX design

Ref: https://github.com/readthedocs/readthedocs-corporate/issues/137

**Comment by stsewd** [comment]
Referencing to my comment on the other issue https://github.com/rtfd/readthedocs.org/issues/3611#issuecomment-365809242. What about listing the valid options (like recommendations), but the user also can enter a _custom option_, with this the validation isn't necessary and probably a more simple solution.

**Comment by aasis21** [comment]
Hello @humitos @stsewd, I would like to work on this issue. I have added autofill for  "Default version"  and "Default branch" form field.  But having some doubt in general. Does all configuration files need to be shown and for which branch of the project?  Furthermore, for "Default version", do we need to show `version.slug` or `version.verbose_name` ?  I have opened a basic PR regarding this, please review and suggest changes.

**Comment by agjohnson** [comment]
Thinking about this a little more, I think you should be required to set the version to active before it can be set to  the default version. I think dropdown for default branch and default version are a great start. I see the following work:

* Populate a dropdown for both fields in the view
* Do form validation on fields and choices for active versions and existing branches

There are a couple things we can maybe punt on or include here:

* The reverse case, where you try to deactivate a version that set as your default version. Maybe just add validation and throw an error here
* Cleaning our branch list periodically, it's append only for now

The reverse case would be an easy addition i think

**Comment by ericholscher** [comment]
> Cleaning our branch list periodically, it's append only for now

This shouldn't be the case. We should be removing them as they are removed in VCS: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/views/model_views.py#L196
