### ISSUE TITLE
Validate user input under Advanced Settings

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3611]
Validate default branch/version and files conf.py/requeriments.txt on form submit. Raise a `ValidationError` if branch/version/file is invalid so the user can immediately fix the issue instead of triggering a random build.

Adding this validation would probably be enough to implement while we keep discussing #3610.

**Comment by apoorvkhare07** [comment]
Hi, a newcomer here. Would like to contribute to readthedocs community. 
Would this be a good issue to start with ?

**Comment by RichardLitt** [comment]
@apoorvkhare07 If you think you can take it on, do so! However, there are other issues labelled "Good First Issue" which might be easier. We'd be happy to help you with this one. My suggestion would be to try and get a PR up and going, and then open it and ask for help and feedback. If you have questions, feel free to ask here, too.

**Comment by Jigar3** [comment]
I want to take up this issue.
Can you explain this in more detail so as to I can have a more clear idea
@RichardLitt

**Comment by RichardLitt** [comment]
@humitos Can you put a bit more legwork in describing the issue and what should a good PR would look like? :)

**Comment by stsewd** [comment]
@humitos I think being very strict with this validation could be a problem.

- What about if someone wants to set all this options before building?
- Or want to move the requirements file on the next commit/version.

(I face this cases when testing on my local instance)

What about just showing a _warning_ (probably more complicated that the original issue)?

**Comment by stsewd** [comment]
@Jigar3 This issue is about adding more validations when setting the options  of requirements file, conf.py, and default version (can be a branch or a tag). This is done under Admin/Advanced Settings ot the project. Currently you can put any string on this fields, so if you made a typo o put the wrong file, you will need to build your project for getting feedback of what was wrong.

So, what @humitos propose is to verify is this files/tags/branches really exists on the repo before saving the form, this way the user gets feedback immediately. And probably you may want to read my above comment too.

**Comment by humitos** [comment]
@stsewd I think you are facing those issues because you are under development, but the most common use of those fields is to write something that's already in the repository and well known by RTD.

I personally prefer to solve the general case, and handle the couple of edge cases as exceptions of this rule. Besides, RTD should detect/find those files automatically. So, in case it doesn't find them properly, you will get an error on the Build and you will be able to change it (but RTD will have your latest code already clone ;) )

**Comment by Jigar3** [comment]
@stsewd How should I go about validating if the specified files are present or not?
Where and how should I check?
I am a litte confused. Can you help?

**Comment by stsewd** [comment]
@Jigar3 This setting is for all the project, no per versions, so I think is better to validate with the files on the default branch. You can add this validation on https://github.com/rtfd/readthedocs.org/blob/0e1112f96e3ba344271a44305028a811072fd10a/readthedocs/projects/forms.py#L179

**Comment by ericholscher** [comment]
I'm not sure I follow the logic here. Is there a list of things we should be validating, and how we might validate them? In particular, it could be really tricky to validate that a `conf.py` file exists.

**Comment by ericholscher** [comment]
We don't keep repos checked out in any reliable fashion in production.

**Comment by stsewd** [comment]
Ha, yesterday I noted that. In my local instance, the existing projects just pull the code but on rtd if I don't touch them in the same day or so, a clone happens.

**Comment by ericholscher** [comment]
I'm taking the `Accepted` label off here. I don't think this is actually something we can do, so I'd fav or closing it. We could try and leverage the GitHub API or something to handle this, but that seems way over-engineered for something that won't provide much value. I think we can just have a basic text fields and have it error on build, unless there is a less complex way of handling this.

**Comment by stsewd** [comment]
I'm closing this in favor of https://github.com/rtfd/readthedocs.org/issues/3610, we can't validate requirements.txt or setup.py files, as they require us to have a checkout of the project, we don't always have that (we remove checkout periodically)
