### ISSUE TITLE
MemoryError with larger dependency files

### ISSUE THREAD

**Issue by jadolfbr** [rtfd/readthedocs.org#3612]
## Details

* Project URL: https://github.com/SchiefLab/Jade
* Build URL (if applicable): https://readthedocs.org/projects/bio-jade/builds/6749799/
* Read the Docs username (if applicable): jadolfbr

## Expected Result

Clean build of requirements.txt

## Actual Result

Hit a MemoryError while downloading SciPy in the virtualenv. Had to remove from requirements.txt temporarily 
https://stackoverflow.com/questions/29466663/memory-error-while-using-pip-install-matplotlib

**Comment by stsewd** [comment]
The memory limit is 1Gb

https://docs.readthedocs.io/en/latest/builds.html#build-process

(You can request more memory as mention on the docs)

Probably we could add an option for the pip options (--no-cache-dir).

**Comment by humitos** [comment]
This seems to be a problem specific to `pip` and not RTD.

In any case, if you don't needs `matplotlib` (or any other dependency) to build your docs you shouldn't make it required to build the docs by having a separate `requirements.txt` file.

> Probably we could add an option for the pip options (--no-cache-dir).

The cache is useful for all the projects to not re-download the same packages all the time. So, we shouldn't add the `--no-cache-dir` option.

I'm closing this issue. Please, feel free to reopen if you consider.
