### ISSUE TITLE
TypeError: get_documenter() takes exactly 3 arguments (2 given)

### ISSUE THREAD

**Issue by matteobachetti** [rtfd/readthedocs.org#3617]
## Details

* Project URL: github.com/stingraysoftware/hendrics
* Build URL (if applicable): http://readthedocs.org/projects/hendrics/builds/6751812/
* Read the Docs username (if applicable): mbachett

## Actual Result

Sphinx throws the following error:
```
TypeError: get_documenter() takes exactly 3 arguments (2 given)
```
The project builds correctly locally, with Sphinx 1.6.2 and 1.7.0, with 
```
sphinx-build -T -E -D language=en . _build/html
```
so it may be that the problem lies with the readthedocs-related command line switches?

Thanks in advance for your help

**Comment by stsewd** [comment]
Hi, your last builds are successful, were you able to solve the problem?

**Comment by matteobachetti** [comment]
Apparently something happened that solved the situation without my
intervention :D. Thanks!
