### ISSUE TITLE
URL path of docs contains unexpected suffix

### ISSUE THREAD

**Issue by matt-hammond-bbc** [rtfd/readthedocs.org#3619]
## Details

* Project URL: https://readthedocs.org/projects/pydvbcss/
* Build URL (if applicable):
* Read the Docs username (if applicable): matt_bbcrd

## Expected Result

* A new release was prepared in a branch called "0.5.2" and was released with tag "0.5.2"
* Expected the URL of the docs to be http://pydvbcss.readthedocs.io/en/0.5.2/

## Actual Result

The actual URL of the docs turned out to be: http://pydvbcss.readthedocs.io/en/0.5.2_a/

**Comment by stsewd** [comment]
This is because should no be two versions with the same slug (branch and tag are considered both versions, same model). This suffix is done automatically.

**Comment by matt-hammond-bbc** [comment]
Thanks for the explanation. Is this a recent behaviour change? On previous releases (that have followed the same process) this has not occurred.

In the documentation [here](https://docs.readthedocs.io/en/latest/versions.html#tags-and-branches) it says:
> Read the Docs supports two workflows for versioning: based on tags or branches. If you have at least one active tag, tags will take preference over branches when selecting the stable version.

My understanding of this is that it means that because I have tags, the branches should be ignored.

**Comment by matt-hammond-bbc** [comment]
Update: I've fixed the problem for the tags/branches already committed by manually changing which builds are active in the Settings->Versions admin interface. But I'm still wondering if this will happen again.

**Comment by stsewd** [comment]
@matt-hammond-bbc I don't remember very well the process for creating branches/tags, but yeah, I think this should solve the problem, and it will happened again only if you have two versions with the same name.

And about the docs you mention, branches are ignored when selecting the stable version, but still are created on the database.

**Comment by stsewd** [comment]
Closing this as the problem was fixed, and the slug is a rtd feature to be unique.
