### ISSUE TITLE
Add rstcheck for linting rst files on travis

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3622]
[rstchek](https://github.com/myint/rstcheck) looks like a good tool for helping us to catch some common mistakes on our docs.

More background about this issue here https://github.com/rtfd/readthedocs.org/pull/3498#discussion_r168798352

**Comment by apoorvkhare07** [comment]
@stsewd Hi, I would like to work on this issue.
Will open a PR soon.
Are their any other details I need to know before I begin ?

**Comment by stsewd** [comment]
@apoorvkhare07 there is a PR in progress already #3624
