### ISSUE TITLE
Intermittent 404s and missing stylesheets when using custom domain

### ISSUE THREAD

**Issue by jeancochrane** [rtfd/readthedocs.org#3630]
## Details

* Project URL: 
     - Readthedocs link: http://dedupe.readthedocs.io
     - Custom domain: https://dedupe.io/developers/library
* Docs repo on GitHub: https://github.com/dedupeio/dedupe/tree/master/docs

## Expected Result

Docs should load at the custom domain (https://dedupe.io/developers/library) and use custom styles:

![dedupe-theme](https://user-images.githubusercontent.com/14170650/36343977-34ea8ffc-13d9-11e8-8308-4d6202eecdf7.png)

These styles are simple tweaks on top of the default `sphinx_rtd_theme`, which are defined in a static CSS file that gets loaded in the layout template. Custom CSS [here](https://github.com/dedupeio/dedupe/blob/master/docs/_static/css/custom.css); custom layout [here](https://github.com/dedupeio/dedupe/blob/master/docs/_templates/layout.html).

## Actual Result

Intermittently, https://dedupe.io/developers/library returns the readthedocs 404 page:

![readthedocs-404](https://user-images.githubusercontent.com/634572/36285151-4daafb4c-125f-11e8-925e-267574cc941f.png)

Sometimes the custom styles fail to load:

![weird-styles](https://user-images.githubusercontent.com/634572/36285152-4dc27628-125f-11e8-881e-d9b1bede6e03.png)

~In the case of the missing styles, the stylesheet still seems to be available from https://dedupe.io/developers/library/en/latest/_static/css/custom.css and is visible in the Resources tab in the dev tools, but the styles aren't applied to the page.~ During response periods where the styles seem wonky, the correponding stylesheets also 404. (See more in [my comment below](https://github.com/rtfd/readthedocs.org/issues/3630#issuecomment-366461120).) This makes me think that the 404s are the root of the issue.

In both cases, hard refreshing a few times appears to fix the issue, but then the behavior recurs sporadically.

Some other interesting behavior:

- I've tested this in Firefox 60.0a1(nightly build) and Chrome 63.0.3239.132, both on Ubuntu 16.04. The behavior happens sporadically in both browsers, although it seems more frequent on Chrome.
- I can't replicate either issue locally, or on the readthedocs subdomain (http://dedupe.readthedocs.io). This makes me think that something is up with the custom domain.

Here are the Nginx rules we use for proxying the custom domain:

```nginx
    location /developers/library/ {
        proxy_pass https://dedupe.readthedocs.io/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-RTD-SLUG dedupe;
        proxy_connect_timeout 10s;
        proxy_read_timeout 20s;
    }

    location /developers/library/index.html {
        return 301 https://dedupe.io/developers/library/;
    }

    location /en {
        return 301 https://dedupe.io/developers/library$uri;
    }
```

Any thoughts on how I can debug further would be appreciated!

**Comment by jeancochrane** [comment]
A little bit more information:

- When the page returns a 404, there are a couple console errors from CDNs:

![typekit](https://user-images.githubusercontent.com/14170650/36344264-36f3d12e-13dd-11e8-9282-505b65ce5340.png)

- Contrary to what I initially reported, when the stylesheets (and JS, it also seems like) fail to load, the correponding files are **not** accessible -- they return 404. This makes me think the sporadic 404s are the root of the issue, and the strange styles are simply a symptom on top of that.

**Comment by SLakhani1** [comment]
I would like to work on it any suggestions?

**Comment by davidfischer** [comment]
The two console issues are not relevant to the docs not loading. They are Adobe Typekit for loading a proprietary font and New Relic for error reporting. They are loaded on every readthedocs.org pageview and also on 404s. Typekit is used by readthedocs.org (normally not docs pages like dedupe.readthedocs.io) to load a font but requires the domain to be whitelisted which dedupe.readthedocs.io isn't. I'm not 100% sure why New Relic would have failed to load although they had some certificate issues a few days ago with unreleased versions of chrome. Both scripts would be loaded by simply visiting https://readthedocs.org/test/404/ (or any 404).

A capture of console output when the styles don't load would be really helpful.

Just to be clear, dedupe.io is your server and you aren't using RTD for serving a custom domain, correct?

<img width="830" alt="screen shot 2018-02-28 at 10 03 24 am" src="https://user-images.githubusercontent.com/185043/36804200-b0a862ca-1c6e-11e8-93f8-f57168338c54.png">

**Comment by jeancochrane** [comment]
Thanks for your replies @davidfischer and @humitos! Apologies that it's taken me so long to get back to work on this. Since I last checked in, we're now seeing consistent 404s on https://dedupe.io/developers/library/, although the RTD domain at https://dedupe.readthedocs.io/en/latest/ is still working fine.

@davidfischer: dedupe.io is our server, and it proxies back to RTD for SSL support as per the docs (https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl). We also have it set up as our "canonical domain" in the RTD settings, since we thought this was the right way to get the search engine juice flowing to the new domain:

![dedupe-docs-domain](https://user-images.githubusercontent.com/14170650/38036389-71e1d9b0-325b-11e8-85e8-f26e916f023c.png)
![dedupe-docs-edit-domain](https://user-images.githubusercontent.com/14170650/38036396-7533939c-325b-11e8-8f02-b414b7a5ee6b.png)

Is that the right approach here, or are these two setups (custom server and custom domain) mutually exclusive?

@humitos: I believe we did change the domain in the process of setting up the custom domain. Symptoms seem similar to #3493 but I'm not sure how I can take action based on the notes in that PR -- it seems like there were some symlinking issues on the RTD end. Let me know if there's something in particular I can try and I'd be happy to give it a go.

**Comment by humitos** [comment]
@jeancochrane not sure, but I think there is a problem in your NGINX setup, since when we access to https://dedupe.io/developers/library/ your server should be accessing to https://dedupe.readthedocs.io/ under the hoods and that URL works.

Seems that the problem is with your two extra locations (redirects) since this works: https://dedupe.io/developers/library but https://dedupe.io/developers/library/en/ doesn't.

I suppose that nothing regarding the Domain configuration is needed when using SSL and configured as it's mentioned in the docs.

**Comment by humitos** [comment]
Maybe I'm wrong :)

Another thing that I just found is this chunk of code:

https://github.com/rtfd/readthedocs.org/blob/adb5392c47a1b3fe506524d898dd147b038d4140/readthedocs/core/middleware.py#L83-L101

It seems that if you have a domain declared it will enter in the first if and then the `HTTP_X_RTD_SLUG` won't be read and that is why it may be failing.

Can you test by removing the domain from Read the Docs and test again all of your NGINX configs?

**Comment by jeancochrane** [comment]
Interesting idea! Removing the domain from the project settings causes https://dedupe.io/developers/library/ to redirect to http://dedupe.readthedocs.io/en/latest/. (I had removed the domain earlier to see if that was causing the issue -- I suspect that's why it looked like /developers/library/ was working, but /developers/library/en wasn't.) This is a lot better than the 404, but still not quite the behavior I expect. Where do you think the redirect is coming from? Looking at the nginx conf:

```
    location /developers/library/ {
        proxy_pass https://dedupe.readthedocs.io/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-RTD-SLUG dedupe;
        proxy_connect_timeout 10s;
        proxy_read_timeout 20s;
    }
```

I would expect the proxy to serve `https://dedupe.readthedocs.io/` from `/developers/library/`, not force a redirect.

**Comment by jeancochrane** [comment]
I haven't made much more progress on this, although I've tried pretty much every combination of Nginx config URIs that I can think of.

My suspicion right now is that the redirect is a red herring -- I'm guessing RTD sends back a canonical URL to the proxy, and when there is no domain then `slug.readthedocs.io` is the default domain. The crux of the issue seems to be that https://dedupe.io/developers/library/en/latest/ cannot properly proxy to https://dedupe.readthedocs.io/en/latest/ the way that we would expect based on [Nginx's documentation](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_pass). I'm pretty stumped as to why this might be, considering that I've triple-checked the way I pass URIs to the proxy and the config I posted above seems up to snuff with Nginx's expectations.

Any ideas for further places to inspect, particularly in the portions of RTD code that handle redirects to language/version specific pages, would be helpful!

**Comment by jeancochrane** [comment]
Finally got this working! I'm still not totally sure what the problem was, but changing the domain to https://docs.dedupe.io (i.e. using a reserved subdomain) caused everything to work as expected with no problems. I suspect something about the extended path of `/developers/library/` wasn't playing well with RTD.

Thanks for your help @humitos and @davidfischer! I really appreciate it.
