### ISSUE TITLE
Improvements to Build Screen Especially for Firefox

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#3639]
## Details

* Project URL: http://readthedocs.org/projects/requests-oauthlib/
* Build URL (if applicable):http://readthedocs.org/projects/requests-oauthlib/builds/6165196/
* Read the Docs username (if applicable): 

## Expected Result

The page should look the same as it does in Chrome/Webkit.

## Actual Result

In Firefox, the build screen scrollbars are unstyled and awkward. While this is an improvement over content being completely invisible before (https://github.com/rtfd/readthedocs.org/pull/3569), but it could be better.

![screen shot 2018-02-19 at 12 27 40 pm](https://user-images.githubusercontent.com/185043/36395911-6f470caa-1570-11e8-8fa0-e546db027741.png)

**Comment by bansalnitish** [comment]
@agjohnson I would like to work on this!

**Comment by RichardLitt** [comment]
@bansalnitish Go ahead! :D
