### ISSUE TITLE
No documentation with several versions

### ISSUE THREAD

**Issue by dfranco** [rtfd/readthedocs.org#3642]
## Details

* Project URL: http://docs.bacula-web.org/en/latest/
* Build URL (if applicable):http://readthedocs.org/projects/bacula-web/builds/
* Read the Docs username (if applicable): davide

## Expected Result

* I'm trying to build several version of my current Git tag repo and expect to have documentation for each versions. 

## Actual Result
* Latest version is built without issue, but previous Git tag documentation is empty

**Comment by stsewd** [comment]
Make sure your versions are activated and public on https://readthedocs.org/projects/bacula-web/versions/

**Comment by dfranco** [comment]
I have both latest and v7.4.0 version enabled and public.

But problem still persist as v7.4.0 is empty
http://docs.bacula-web.org/en/v7.4.0/

**Comment by stsewd** [comment]
@dfranco I can see both of your versions now, were you able to solved? what was the problem?

**Comment by stsewd** [comment]
Also on the commit that the version is marked https://github.com/bacula-web/bacula-web/tree/0ec2420ff79f5d56485b648ea064cebea18ccf70, there isn't a sphinx project, neither an index file.

**Comment by dfranco** [comment]
Hi @stsewd 
You're right, the tag (v7.4.0) doesn't contain the docs/source folder yet.
I need to recreate this tag at the right commit.
Thanks for your help
