### ISSUE TITLE
Tip message on build page

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3652]
I just saw this when building a project's doc in my local instance.

![captura de pantalla_2018-02-22_12-55-46](https://user-images.githubusercontent.com/244656/36555397-e1952e3e-17cf-11e8-89e4-6997f5242d4c.png)

As far as I remember this tip should only be shown if the build has failed and the last command's output contains the `setup.py` word on it but now is shown even before the build has ended.

Maybe it's related to #3644

**Comment by bansalnitish** [comment]
@humitos I would like to work on this!

**Comment by humitos** [comment]
@bansalnitish nice! Let us know if you need something else to start working on it :)

**Comment by stsewd** [comment]
@bansalnitish I strongly believe this is because #3644 (that issue is already assigned to @humitos)

**Comment by bansalnitish** [comment]
Thank you @humitos @stsewd. Yes, I agree with you that this might be linked to #3644. I will find another issue to work on!

**Comment by stsewd** [comment]
@humitos is this still an issue? or it was solved after https://github.com/rtfd/readthedocs.org/issues/3644?

**Comment by humitos** [comment]
@stsewd probably. I didn't see his issue anymore in several weeks.

I'm closing it here.
