### ISSUE TITLE
Remove the 'bookmarks' app completely

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3659]
There is a django app `bookmarks` that can be completely removed since it's not used at all: https://github.com/rtfd/readthedocs.org/tree/e9d0d2ff5b70e1c0b58be512a6cf10e7c11930b3/readthedocs/bookmarks

> Consider that removing this app could help us to not depend in `django-pagination` since it's used in some of the bookmarks templates.

**Comment by xrmx** [comment]
@humitos looks like this can be closed

**Comment by stsewd** [comment]
This was solved on #3663
