### ISSUE TITLE
Unable to Set Pin Through Either Mac Bridge or Chrome Extension, Bootloader Mode

### ISSUE THREAD

**Issue by BenCook28** [rtfd/readthedocs.org#3660]
My Trezor only says "Welcome! Please visit trezor.io/start."  I did that, and the Trezor screen doesn't change even though I have both the Chrome Extension and desktop Bridge for Mac.  I'm connecting to a Macbook pro through a USB-C to USB adaptor.  I searched through Trezor's docs and Reddit and Github and an internet search and a Crypto Currency publication I subscribe to and haven't yet resolved this issue.  

And after I installed the Chrome app, I got a warning about Bootloader mode even though I unplugged my Trezor per the warning, but still got the same message afterwards.  I may have gotten the warning since pressed the left button to see what would happen.  I seem to have a bitcoin wallet, but haven't set a PIN or seed.  If its not too much trouble, would you please help me with my PIN, seed, and resolve the bootloader mode issue?

**Comment by BenCook28** [comment]
Never mind, I had to install firmware first.  I finally noticed it on the, on a tab with the title TREZOR Wallet, but unfortunately I forget exactly where.

**Comment by RichardLitt** [comment]
Thanks for logging and self-updating us, @BenCook28! Glad you got it working.
