### ISSUE TITLE
Upgrade django-pagination

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3664]
We are using a fork of the unmaintained `django-pagination` (https://github.com/zyga/django-pagination).

On the other hand, I found that there is another fork that maybe is more maintained at https://github.com/pydanny/dj-pagination

I opened an issue that the 3dparty repository at https://github.com/zyga/django-pagination/issues/42

Ref #2435

**Comment by pydanny** [comment]
We use dj-pagination on a single project, but I have to admit it has a few glitches.

**Comment by humitos** [comment]
@pydanny thanks for your comment.

We don't use it in a heavy way, there are just a couple of pages that list

* the buils
* the projects
* search results (I think)

So, we won't probably be bitten for those glitches at this point and I think that the current version is more compatible with Py3 that the one that we have pinned at a specific commit.

(another option is to consider refactor this code to remove this dependency, but that would probably more complicated)

**Comment by pydanny** [comment]
Well, if you find any glitches with `dj-pagination`, let me know by mentioning `RTD` or `RTFD` in the issue. I'll move fixing them to the top of my priority queue.

It's the least I can do for you in return for all the awesomeness RTD provides to the universe.

**Comment by RichardLitt** [comment]
@ericholscher Do we have a list of great comments from really super nice people somewhere? If so, we should add this. :)

**Comment by ericholscher** [comment]
@RichardLitt we don't! That sounds like a good idea though, as a morale boost for some days when we're feeling down. Perhaps similar to testimonials in our docs?

**Comment by RichardLitt** [comment]
@ericholscher Exactly. Maybe somewhere just internally at the company. It's a silly idea, but it helps you feel good. :) You'd know best on where to put it.
