### ISSUE TITLE
Clean up logging in project tasks

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3665]
Some of the classes are using a `_log` method that mangles the original caller for logging. These should call `log.info` directly.

**Comment by kchawla-pi** [comment]
I would like to start on this. Any suggestions about where I should start, or anything I should know before I do?

**Comment by kchawla-pi** [comment]
Seems PR #3677 fixes this. Does it?

**Comment by stsewd** [comment]
@kchawla-pi yes, someone is already working on this issue.
