### ISSUE TITLE
Initially use virtualenv is checked, but is not functioning

### ISSUE THREAD

**Issue by posita** [rtfd/readthedocs.org#3668]
UPDATE 1: Okay, I think I know what's happening now. The setting "Install your project inside a virtualenv using `setup.py install`" was initially checked in the Advanced Settings UI, but was not honored. I had to uncheck it, save the settings, recheck it, and then save the settings again for that setting to take effect.

UPDATE 2: It looks like the [default value in the model is `False`](https://github.com/rtfd/readthedocs.org/blob/3c3445647c5606f746458f0575e475cf5406af69/readthedocs/projects/models.py#L185-L190). Is it possible the checkbox in the UI defaults to "set", but is not taken into account unless its value is actually changed in the form by the user before submission?

Original post is preserved below.

---

I cannot for the life of me figure this one out. I have two projects with nearly identical configurations:

- [`modwalk`](https://readthedocs.org/projects/modwalk/) (set up over a year ago)
- [`django-emojiwatch`](https://readthedocs.org/projects/django-emojiwatch/) (set up in the past couple of weeks)

For `modwalk`, `python setup.py install --force` is called just before `cat docs/conf.py`. (See, e.g., [this build](https://readthedocs.org/projects/modwalk/builds/6791657/).) For `django-emojiwatch`, the `… setup.py install …` step is conspicuously absent. (See, e.g., [this build](https://readthedocs.org/projects/django-emojiwatch/builds/6794621/).) Both projects use virtualenvs and have custom `docs/requirements.txt` files. I have verified the following settings are identical in both projects:

<img width="475" alt="screen shot 2018-02-23 at 10 21 32" src="https://user-images.githubusercontent.com/222581/36609964-822f274c-1883-11e8-9ea1-ba29fd40e552.png">

## Details

* Project URL: https://readthedocs.org/projects/django-emojiwatch/
* Build URL (if applicable): https://readthedocs.org/projects/django-emojiwatch/builds/6794621/
* Read the Docs username (if applicable): posita

## Expected Result

`python setup.py install --force` is called before `cat docs/conf.py`.

## Actual Result

`python setup.py install --force` is **_not_** called.

**Comment by posita** [comment]
I tried unchecking the virtualenv setting for `django-emojiwatch`, saving the settings, starting a build, then checking it again, saving the settings again, and starting [another build](https://readthedocs.org/projects/django-emojiwatch/builds/6794774/), which seems to have fixed my issue. For some reason the box was checked initially, even though that setting wasn't honored.

**Comment by pydanny** [comment]
`Initially use virtualenv is checked, but it's a lie` is an abusive title for an issue. It's assuming the bug you encountered was intentional, which it was not. There's no way the RTD team would do anything intentional to make your day less pleasant.

A better title would be something on the lines of `Initially use virtualenv is checked, but is not functioning`.

**Comment by stsewd** [comment]
> UPDATE 2: It looks like the default value in the model is False. Is it possible the checkbox in the UI defaults to "set", but is not taken into account unless its value is actually changed in the form by the user before submission?

When you click on submit, all the info on the form is saved. I think this issue is mostly to a corrupted environment or a previous build queued.

Please let us know if you have this problem again!

**Comment by stsewd** [comment]
We can't replicate this, I think it was a corrupted environment, wiping before triggering a new build should solve if this happens again. Feel free to reopen if this happens again.

**Comment by ast0815** [comment]
Hello, I think I might have the same issue now? Except that saving the preferences again did not help.

Previous builds installed the package: https://readthedocs.org/projects/remu/builds/9592095/

Newer builds do not and this makes the docs not build correctly: https://readthedocs.org/projects/remu/builds/11077033/

In fact, it seems like the new builds are skipping quite a few steps? E.g. building the PDF and other versions.

**Comment by stsewd** [comment]
@ast0815 you are using a configuration file, settings from the web interface are ignored https://github.com/ast0815/remu/blob/master/.readthedocs.yml, see https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by ast0815** [comment]
Ahhm, I see. I forgot about that file. Thanks!

On the advanced settings page it says

> These settings can be configured using a configuration file. That's the recommended way to set up your project. Settings in the configuration file override the settings listed here.

so I would have guessed that it would not touch the "generate PDF/epub" settings if I did not configure them. If it ignores all settings on that page as soon as there is a configuration file, I think that should be stated more clearly. That's just as an aside though.
