### ISSUE TITLE
Put RTD logo on GitHub OAuth App

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3675]
The default logo is shown when confirming the app and also on the list of authorized apps.

On GitLab and Bitbucket the logo isn't shown (at least when confirming)

RTD vs other app on GitHub's apps panel 

![screenshot-2018-2-24 build software better together](https://user-images.githubusercontent.com/4975310/36635459-0520f7e8-1983-11e8-94cf-0891834659cb.png)

**Comment by kritisingh1** [comment]
Hi @stsewd can I take this up? Thanks!

**Comment by stsewd** [comment]
@kritisingh1 thanks for your interest on contributing! But this issue can only be solved by people with access to the rtd app.

**Comment by kritisingh1** [comment]
Cool! No worries. I'll have a look at other issues. Thanks :)

**Comment by agjohnson** [comment]
I've updated the logos!
