### ISSUE TITLE
RTD build does not install dependencies properly

### ISSUE THREAD

**Issue by vmalloc** [rtfd/readthedocs.org#3678]
The build mentioned below performs `python setup.py install`, but I can't see any of the dependencies being installed in the log. It ends up failing on a missing module which was not installed properly...

This seems to block all current builds of the project

## Details

* Project URL: http://slash.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/slash/builds/6804415/
* Read the Docs username (if applicable):  vmalloc

**Comment by stsewd** [comment]
I can't see the build url, but I see your latest build https://readthedocs.org/projects/slash/builds/6804398/ and it's failing because you don't have that file on that version https://github.com/getslash/slash/tree/8943721bd25c0d98e2f2884510cbe908e86d03f5/doc

**Comment by vmalloc** [comment]
It was on a side branch. I pushed it to `develop` now to demonstrate -- the file now exists, yet the package itself being documented, for some reason, gets installed without its dependencies: http://readthedocs.org/projects/slash/builds/6807475/

As you can see in the build above, it runs `python setup.py install --force`, but no dependency appears in the output. The build fails on the missing dependency (logbook in this case)

**Comment by stsewd** [comment]
@vmalloc that's because indeed that package is never installed https://github.com/getslash/slash/blob/4d502d6b40d36dec4ad564fcab962267e0f12125/setup.py

You need to specify the requirements on the `setup.py` script or referencing the `requirements.txt` file  from your root project on the `pip_requirements.txt` file from your `/docs` directory. Something like this:

```
# docs/pip_requirments.txt

-r ../requirements.txt

# Other requirements...
``` 

But I recommend to put your requirements on `setup.py`

**Comment by vmalloc** [comment]
The project uses `pbr`, and thus has its requirements in `requirements.txt`. It works correctly when installed with `pip` and also when using `python setup.py develop`. I'll investigate further - it's possible it's a pbr bug....

**Comment by vmalloc** [comment]
BTW - `pbr` was introduced in that project on April 2017... It has worked well since then across many releases - so I'm guessing something broke in RTD's environment very recently that caused this...

**Comment by stsewd** [comment]
@vmalloc I don't know about `pbr`, sorry. But I can see that your requirements file is different

https://github.com/getslash/slash/blob/4d502d6b40d36dec4ad564fcab962267e0f12125/doc/pip_requirements.txt

https://github.com/getslash/slash/blob/a14d7ab412e197e44dde5537fe93a478a9d7abe3/doc/pip_requirements.txt

**Comment by vmalloc** [comment]
Reported to pbr as https://bugs.launchpad.net/pbr/+bug/1751997

**Comment by vmalloc** [comment]
Oh you're right - the old version explicitly installed the project via `-e .`...

Sorry - my bad. The pbr bug is real though, but unrelated to RTD. Thanks a lot!
