### ISSUE TITLE
Add admin functions for wiping a version from web instances

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3684]
This is exposed to project owners, but an admin function here would be really helpful for debugging purposes. The existing view for wiping versions will likely need to be broken out to a reusable view for the admin function.

**Comment by aasis21** [comment]
@agjohnson, I would like to work on this issue. Could use please elaborate it little more.

**Comment by ajatprabha** [comment]
Hi @agjohnson, I'm new here! This enhancement is not completely clear to me, so I wanted to ask a few things:
1. Are you talking about a ModelAdmin action here by `admin function` or something different from out-of-the-box Django admin actions?
2. If yes, is it about adding the action to `readthedocs.builds.admin.BuildAdmin` or to `readthedocs.projects.admin.ProjectAdmin` (more likely I believe)?

**Comment by agjohnson** [comment]
@ajatprabha we are looking for a django site admin feature, on VersionAdmin.
