### ISSUE TITLE
Add cancel button to the admin delete project page

### ISSUE THREAD

**Issue by Chirath02** [rtfd/readthedocs.org#3688]
## Details

* Project URL: http://localhost:8000/dashboard/project-name/delete/

## Expected Result
![screenshot_20180227_110252](https://user-images.githubusercontent.com/9161520/36712493-16b79a88-1baf-11e8-875e-6545e9fceeef.png)

Cancel button along with the Delete forever button.

## Actual Result

![screenshot_20180227_111038](https://user-images.githubusercontent.com/9161520/36712498-1cc42e00-1baf-11e8-99aa-3640f8ee9232.png)

No option to cancel or go back.

**Comment by Chirath02** [comment]
I got this working, but can someone help me with where I should include the CSS for this page?

**Comment by RichardLitt** [comment]
Thanks for this work, @Chirath02! Any reason you closed this?

**Comment by RichardLitt** [comment]
Closed due to https://github.com/rtfd/readthedocs.org/pull/3690#issuecomment-369289626.
