### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by philrz** [rtfd/readthedocs.org#3692]
## Details

* Project URL: https://github.com/draios/python-sdc-client
* Build URL (if applicable): https://readthedocs.org/projects/python-sdc-client/builds/6812055/
* Read the Docs username (if applicable): philrz

## Expected Result

One of our builds failed recently and the failure didn't make sense to me, so I took its advice and clicked the button to have it reset the build environment, expecting that might fix it.

## Actual Result

Once I did that, this next attempted build appeared to fail during the cloning step, with the output being:

Build #6812055
latest
Build failed
Having trouble with your build environment? Try resetting it.

Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6812055).

git clone --recursive https://github.com/draios/python-sdc-client.git .

**Comment by justb4** [comment]
Same here, first build triggered via GitHub, then manually, output below, as per request reporting:

![image](https://user-images.githubusercontent.com/582630/36735335-39521100-1bd6-11e8-89ab-baaacc171760.png)

**Comment by stsewd** [comment]
@philrz  Could you try building again? Probably a temporal issue on the servers.

@justb4 can you provide the build url?

**Comment by justb4** [comment]
Triggering now: http://readthedocs.org/projects/stetl/builds/6812961/

**Comment by philrz** [comment]
@stsewd: Yes, my build does complete now. Thanks for that.

Not sure if it's related, but hoping you could look at one other thing that's currently holding me up. For some reason, my docs build for `latest` seems to be consistently pointing at a branch called `teams-api`.

![image](https://user-images.githubusercontent.com/5934157/36749295-311155a4-1baf-11e8-8ef3-7d3215d79115.png)

The doc at https://docs.readthedocs.io/en/latest/versions.html indicates that it `latest` should point to the Default Branch, which this repo is `master`:

![image](https://user-images.githubusercontent.com/5934157/36749357-630a9822-1baf-11e8-8b29-6a10389f8e75.png)

I've tried telling it to Wipe, hit the Clean button, made `latest` inactive and re-Activated it, etc., but it keeps coming back set that way. The `teams-api` branch, in fact, doesn't even exist anymore, so the build fails every time (e.g. https://readthedocs.org/projects/python-sdc-client/builds/6813646/).

Is there something I'm missing about how to get it unstuck, or is there something you could check from your end? Thanks.

**Comment by stsewd** [comment]
@philrz the _default branch_ is the one from your rtd project, no the one from GitHub, you can change that on Advanced settings of the admin panel of your project.

**Comment by philrz** [comment]
Thanks @stsewd... my bad. I'm all set. Closing this issue.
