### ISSUE TITLE
TestProject.test_conf_file_not_found fails on master

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#3699]
## Details

With `09f8282be35c20dcca42c85d3f845bba8b784cfe`
```
tox -e py27
```
fails

## Expected Result

Tests green

## Actual Result

```
TestProject.test_conf_file_not_found 

self = <readthedocs.rtd_tests.tests.test_project.TestProject testMethod=test_conf_file_not_found>

    def test_conf_file_not_found(self):
        with self.assertRaisesMessage(
                ProjectConfigurationError,
                ProjectConfigurationError.NOT_FOUND) as cm:
>           self.pip.conf_file()

rtd_tests/tests/test_project.py:146: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/lib/python2.7/contextlib.py:24: in __exit__
    self.gen.next()
../.tox/py27/local/lib/python2.7/site-packages/django/test/testcases.py:616: in _assert_raises_message_cm
    yield cm
E   AssertionError: ProjectConfigurationError not raised
```

**Comment by xrmx** [comment]
Can this be caused by running the tests on an instance that has built pip documentation?

**Comment by stsewd** [comment]
@xrmx I think that for the tests a separate database is used, I can't replicate this issue on my local instance and the tests are all green on travis. What OS do you have?

**Comment by xrmx** [comment]
@stsewd was thinking more of the fact that there's a checkout of the pip docs or a build of the same around. The os is debian sid

**Comment by stsewd** [comment]
@xrmx also make sure to run the tests while the instance isn't running (some tests fail because of this).

**Comment by xrmx** [comment]
@stsewd wasn't running.
