### ISSUE TITLE
Failed build 

### ISSUE THREAD

**Issue by willingc** [rtfd/readthedocs.org#3700]
## Details

* Project URL: https://readthedocs.org/projects/jupyterhub/
* Build URL (if applicable): https://readthedocs.org/projects/jupyterhub/builds/6818352/
* Read the Docs username (if applicable): willingc

## Expected Result

The docs would build.

## Actual Result

`There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6818352)`

Possibly related to our change related to bower-lite https://github.com/jupyterhub/jupyterhub/pull/1667/commits/53396ed4548763adc2c39c8331c8499cb783626c

cc/ @minrk @humitos

**Comment by willingc** [comment]
Weird. Now it's building as of the latest push to JupyterHub repo (though no doc changes). https://readthedocs.org/projects/jupyterhub/builds/6819251/

I'll leave this open for a couple of days and loop back and close if no issues for a few more days.

**Comment by stsewd** [comment]
Probably a temporal issue on the servers, @willingc thanks for reporting!

**Comment by humitos** [comment]
@willingc I checked out our Sentry and I found that there was an internal API call that returned 500 (Internal Server Error) with no explanation about it :/

That's all the "help" that I can bring you, haha!

So, probably as @stsewd said, a temporary error about CPU load/memory or similar.

**Comment by willingc** [comment]
Thanks @humitos for checking Sentry and @stsewd for the response about a temporary server error. 

I'll close this and ping you folks if it happens again. Thanks!
