### ISSUE TITLE
Fail to build doc for psutil project

### ISSUE THREAD

**Issue by giampaolo** [rtfd/readthedocs.org#3706]
https://readthedocs.org/projects/psutil/builds/6823342/
Not sure what the problem is. The output seems OK.

**Comment by PoslavskySV** [comment]
Having the same issues with my project: output is OK, local build is OK, but RTD fails

Failed builds:

https://readthedocs.org/projects/rings/builds/6823203/
https://readthedocs.org/projects/rings/builds/6823978/

**Comment by stsewd** [comment]
@giampaolo I see your lasts builds are successful. As mention on the linked issue (#3707) I think this was because of a temporal issue on the rtd servers at that date. Feel free to reopen if you considered.
