### ISSUE TITLE
Build 6824044 failed

### ISSUE THREAD

**Issue by PoslavskySV** [rtfd/readthedocs.org#3707]
## Details

* Project URL: http://rings.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/rings/builds/6824044/
* Read the Docs username (if applicable): PoslavskySV

## Expected Result

Build docs.

## Actual Result

There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6824044).

**Comment by dfranco** [comment]
I have the exact same problem
https://readthedocs.org/projects/bacula-web/builds/6824421/
Even wiping the build environment didn't help

**Comment by PoslavskySV** [comment]
@dfranco I also tried swiping and it didn't helped. I found that build sometimes succeed: out of my ~15 builds 3 have passed.

**Comment by stsewd** [comment]
@PoslavskySV @dfranco @justb4 @keflavich and other people having the similar problem, probably this is a temporal issue on the servers as mention on https://github.com/rtfd/readthedocs.org/issues/3705#issuecomment-369574868

Maybe @humitos could help to see what happened.

**Comment by PoslavskySV** [comment]
@stsewd I still can't build the project (already for about  24 hours since yesterday)

**Comment by stsewd** [comment]
@PoslavskySV The core team is solving the problem now https://github.com/rtfd/readthedocs.org/issues/3215#issuecomment-369661968

**Comment by PoslavskySV** [comment]
@stsewd Great! Thank you very much!

**Comment by dfranco** [comment]
I confirm the problem is fixed for my project.

Thanks @stsewd and @PoslavskySV for your help.

**Comment by PoslavskySV** [comment]
I also confirm that the problem is fixed. Many thanks!
