### ISSUE TITLE
Improve project translation listing under admin tab 

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3708]
Currently, under `Admin -> Translations` tab we have something like this to list "Existing translations"

![captura de pantalla_2018-03-01_09-14-23](https://user-images.githubusercontent.com/244656/36849037-f26a5b10-1d30-11e8-8fd4-349bc8db5640.png)

I think we want to change this to feel more like the rest of the site (considering some improves that @stsewd has already done in other pages with listings --like redirects)

![captura de pantalla_2018-03-01_09-16-23](https://user-images.githubusercontent.com/244656/36849146-3f0d87d0-1d31-11e8-8427-ef777b5b9352.png)

(I took this image from Project Import, but it's just to share the idea)

**Comment by stsewd** [comment]
We need to wait to https://github.com/rtfd/readthedocs.org/pull/3572 gets approved/merged so we can reuse the css classes.

**Comment by saadmk11** [comment]
Can I Work on This Issue?

**Comment by humitos** [comment]
@saadmk11 I'd double check with @agjohnson or @ericholscher that my proposal is what we want before start working on it. I'm pinging them here looking for the :+1: of one of them.

**Comment by saadmk11** [comment]
> @saadmk11 I'd double check with @agjohnson or @ericholscher that my proposal is what we want before start working on it. I'm pinging them here looking for the  of one of them.

Okay Sure.

**Comment by agjohnson** [comment]
Yeah, all our admin forms should follow the new pattern. #3572 looks like a good base, we also have some existing admin forms that already use the pattern we're describing. I'd use those to start.

**Comment by saadmk11** [comment]
I saw  a few admin pages use the Old Pattern (Form and List view at the same time). I would like to propose to change the Old pattern with the new one as suggested by @agjohnson.
I was able to Find these pages using the old pattern:

1. **Domains**
2. **Maintainers**
3. **Redirects**
4. **Translations**
5. **Notifications**

And I would also like to address the **Environment Variables** page should have a `remove` button on the list view which is used in the new pattern.
I would like to work on this if this gets accepted.
and please feel free to add any corrections to my proposal.
if I understood it incorrectly please correct me.

**Comment by agjohnson** [comment]
It would be best to split this all into digestible chunks either way, but :+1: on addressing the old pattern use in all of our forms. We are about to start a contract that will address the UX and styling on these forms, so this part is not as important as having all the correct views and form handling.

**Comment by saadmk11** [comment]
@agjohnson If I understood you correctly, you want to split the old pattern views (different views for list, create/update form) so that it matches the new pattern. Such as the subproject views in the project Admin
https://github.com/rtfd/readthedocs.org/blob/b06dedb5bf008d5d835110faa6176c24146546f1/readthedocs/projects/views/private.py#L484-L503
If I'm correct we can start working on this in small pieces (page by page) and test it.
