### ISSUE TITLE
Build 6824799 failed

### ISSUE THREAD

**Issue by keflavich** [rtfd/readthedocs.org#3710]
* Project URL: https://readthedocs.org/projects/astroquery/
* Build URL (if applicable): https://readthedocs.org/projects/astroquery/builds/6824770/
* Read the Docs username (if applicable): keflavich

I got the following error, which I'm reporting as instructed:

"Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6824799)."

**Comment by RichardLitt** [comment]
This is one of a number of similar issues. See #3707. We're on it.

**Comment by humitos** [comment]
This was a temporary issue which should be fixed now while the servers recovers from their load. I'm closing this one, but feel free to reopen if you consider. Thanks!
