### ISSUE TITLE
Build 6825626 failed

### ISSUE THREAD

**Issue by algorys** [rtfd/readthedocs.org#3711]
## Details

* Project URL: https://github.com/Alignak-monitoring-contrib/alignak-app
* Build URL (if applicable): https://readthedocs.org/projects/alignak-app/builds/6825626/
* Read the Docs username (if applicable): Algorys

## Expected Result

Build success on develop branch.

## Actual Result

This build was terminated due to inactivity. If you continue to encounter this error, file a support request with and reference this build id (6825626).

**Comment by stsewd** [comment]
Probably related to https://github.com/rtfd/readthedocs.org/issues/3707#issuecomment-369636647
And see https://github.com/rtfd/readthedocs.org/issues/3215#issuecomment-369661968

**Comment by algorys** [comment]
Thanks @stsewd, I will follow theses issues. 

Strange thing is I've no submodule in my repository.

**Comment by mxbi** [comment]
I had this issue around the same time, resetting the build environment fixed it (although I am now getting a different error).

**Comment by algorys** [comment]
Seems solved by resetting environment.
