### ISSUE TITLE
Improve URL resolver performance

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#3712]
Our URL resolver (https://github.com/rtfd/readthedocs.org/blob/4d10f2e/readthedocs/core/resolver.py) which turns a `Project` and/or `Version` into a URL to their documentation needs some performance improvements to reduce or eliminate the number of database queries it makes.

This is particularly noticeable on the `footer_html` API call (https://github.com/rtfd/readthedocs.org/blob/ba71aa1/readthedocs/restapi/templates/restapi/footer.html#L43) which is called on every docs pageview to inject the version selector. In order to get the URL to each version in the version selector, four database queries are needed (to make sure this isn't a subproject or translation and get the domain). So for a project with 10 active versions, we are looking at 40 database queries. Most of this effort is wasted since the data is only needed once for the project.

**Comment by aasis21** [comment]
Hi @davidfischer, Can I take up this issue. I realize that the template calls `version.get_subdomain_url` which calls `project.get_docs_url` which further calls the `resolver` mentioned above. we should pass this resolved URL in template directly for reuse. Furthermore, the protocol in `resolver` function should be changed to `https`.

**Comment by davidfischer** [comment]
That's pretty accurate.

I'm not 100% sure that we should force HTTPS yet (see #3282). While every project hosted by `*.readthedocs.io` can and should use HTTPS, some docs use their own domain and not all of those support HTTPS (eg. http://docs.python-requests.org)

**Comment by davidfischer** [comment]
I should mention that I welcome a PR for this. However, I will caution you that this will probably be a bit complex.
