### ISSUE TITLE
problem with Read the Docs: Build 6826343 failed

### ISSUE THREAD

**Issue by mxbi** [rtfd/readthedocs.org#3713]
## Details

"There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6826434)."

This happened after the build ran "git show-ref --tags", although no other error messages are anywhere in the commands.

* Project URL: https://readthedocs.org/projects/mlcrate/
* Build URL (if applicable): 6826434
* Read the Docs username (if applicable): mxbi

## Expected Result

Build succeeded

## Actual Result

Build failed with error message and no obvious cause.

**Comment by RichardLitt** [comment]
I believe this is part of a few errors caused on our side. Fixes are being worked on now: see #3707.

**Comment by humitos** [comment]
This was a temporary issue which should be fixed now while the servers recovers from their load. I'm closing this one, but feel free to reopen if you consider. Thanks!
