### ISSUE TITLE
Build 828171 is failing 

### ISSUE THREAD

**Issue by sfdye** [rtfd/readthedocs.org#3714]
## Details

* Project URL: https://readthedocs.org/projects/pygithub/
* Build URL (if applicable): https://readthedocs.org/projects/pygithub/builds/6828171/
* Read the Docs username (if applicable): sfdye

## Expected Result
Build success for `stable` for the latest tag release `v1.37` on Github

*A description of what you wanted to happen*

## Actual Result
Build failed due to wrong version

*A description of what actually happened*

The `stable` version is still pointing to an old commit which did not fix the build.

#3279 should fix it.

## Background

We did a migration of the Github link from:
`https://github.com/jacquev6/PyGithub` to `https://github.com/PyGithub/PyGithub`

**Comment by humitos** [comment]
You have two different things happening here:

1. The error reported by RTD is

```
  File "conf.py", line 324, in <module>
    assert method is None or (githubClass, method) in [("github.StatsPunchCard.StatsPunchCard", "get")], githubClass + "." + method + " has no :calls: section"
AssertionError: github.PullRequestReviewerRequest.PullRequestReviewerRequest.__repr__ has no :calls: section
```

Which is related to your own project, not RTD.

2. `v1.37` is not being selected as `stable` version automatically.  I'd say that this is not related to #3279 because it should be automatically by RTD since it's the general rule and that issue linked is to skip that general rule for some other consideration. Anyway, in this case I think that you don't need to skip that rule, but you need that rule to work properly in your RTD project instead :)

**Comment by sfdye** [comment]
@humitos Thank you very much for your response

1. I am aware and this is already fixed in master, but as I said in the description the reason is because `stable` is pointing to the wrong sha, if it's pointing to master or 1.37 this failure should not appear.

2. Okay, what is the solution then?

**Comment by humitos** [comment]
I'm markng this a `Needed: replication` since it seems that we have a bug on our selection of the `stable` that it would be great to research a little more, but I'm not able to reproduce it.

**Comment by sfdye** [comment]
@stsewd Thanks for the pointer. I know that might work, but really don't want to take such a destructive move.

**Comment by sfdye** [comment]
@humitos For our case, it involves renaming of the repo.

**Comment by sfdye** [comment]
I finally get it working by deleting the project on rtd and importing again, thanks to advice from @stsewd . Don't think it's worth the effort to investigate and reproduce though, thus closing the issue. Re-open if anyone interested to dig in deeper.
