### ISSUE TITLE
Builds timeout: request for increased time limit

### ISSUE THREAD

**Issue by enielse** [rtfd/readthedocs.org#3716]
## Details

* Project URL: https://readthedocs.org/projects/pygsti/
* Build URL (if applicable): https://readthedocs.org/projects/pygsti/builds/6830583/
* Read the Docs username (if applicable): enielse

The builds are timing out after 15 minutes.  By the end of 15 minutes the HTML build completes successfully, but the json (and local-media) build does not finish in time (see referenced build url).  This is due to the project having a lot of documentation that needs to be built.  

It also seems somewhat due to the speed of the computers performing the build - what takes about 15 minutes on readthedocs takes < 3 minutes on my several-year-old laptop. 

If the build timeout could be increased to 30 or 45 minutes the builds should be successful.  Also, or alternatively, if the json and local-media builds are not needed (I'm not sure what these are used for), disabling them would speed up the build.

## Expected Result

A successful build.

## Actual Result

Builds timeout.

**Comment by enielse** [comment]
Update: I've been able to trim down the docs to get them to build within the 15-minute window, so some of the builds more recent than the one I referenced above pass.  I would still like the time limit to be extended, though, since this would let me build the "unabridged" version of my docs.

**Comment by humitos** [comment]
Hi! We were having some performance issues yesterday and we are trying to recover from them. So, probably your build will take less time today or tomorrow (just a guessing, though)

Please, wait some time and let us know again if this is still an issue for you.

> json and local-media builds are not needed

JSON is used for the search, and there is an issue to track the idea of disabling local-media at #3220

**Comment by enielse** [comment]
Ok, thanks.  I'll try to full docs again some in a few days or so.

**Comment by humitos** [comment]
It seems that your latest build are building properly. I'm closing here.

Anyway, those builds are five minutes away from the time limit. So, I just increased the time with 5 minutes more which should be enought for now. Feel free to request more time if it's needed, though.

Let us know in any case. Thanks!
