### ISSUE TITLE
Missed sphinx_rtd_theme.css on some pages

### ISSUE THREAD

**Issue by PoslavskySV** [rtfd/readthedocs.org#3717]
## Details

* Project http://rings.readthedocs.io
* Build URL (if applicable): 
* Read the Docs username (if applicable): PoslavskySV

## Expected Result

Page http://rings.readthedocs.io/en/latest/algorithms.html  should look normally with RTD style.

## Actual Result

Page http://rings.readthedocs.io/en/latest/algorithms.html  doesn't contain 
`sphinx_rtd_theme.css` and looks ugly. Other project pages looks fine (contain correct css). The local build is also OK and the markup is correct.

**Comment by PoslavskySV** [comment]
Probably also related to #3715

**Comment by stsewd** [comment]
@PoslavskySV indeed is the same bug. Closing this issue in favor of the other one (https://github.com/rtfd/readthedocs.org/issues/3715). Thanks for reporting.
