### ISSUE TITLE
Add release date to changelog

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3718]
It would be very helpful to have the date of the release in the changelog published at http://docs.readthedocs.io/en/latest/changelog.html

Code ref: https://github.com/rtfd/readthedocs.org/blob/8fe25841803e31a559c1b3ddb12d7f06cdeb0674/tasks.py#L62

**Comment by rajujha373** [comment]
shall I take up this issue? @humitos

**Comment by RichardLitt** [comment]
@rajujha373 If you have a suggestion for how the code should look, open a PR! :D

**Comment by stsewd** [comment]
This was implemented on https://github.com/rtfd/readthedocs.org/pull/3788 (merged)
