### ISSUE TITLE
Build #90721 Failed

### ISSUE THREAD

**Issue by mbarnes-sb** [rtfd/readthedocs.org#3721]
## Details

* Project URL: https://readthedocs.com/projects/starbreeze-ab-starvr-sdk/
* Build URL (if applicable): https://readthedocs.com/projects/starbreeze-ab-starvr-sdk/builds/90721/
* Read the Docs username (if applicable): 

## Expected Result

Build should succeed

## Actual Result

git submodule update --init --recursive --force
Cloning into 'StarVRExample/AntilatencyPlugin'...
fatal: could not read Username for 'https://github.com': terminal prompts disabled
fatal: clone of 'https://github.com/fl4re/starvr-plugin-antilatency.git' into submodule path 'StarVRExample/AntilatencyPlugin' failed
Command time: 0s Return: 128

**Comment by mbarnes-sb** [comment]
@jerome-labbe-sb fyi

**Comment by humitos** [comment]
@mbarnes-sb Hi! Please, if you have a problem with readthedocs.com send an email to the support team instead of opening an issue under the .org repository. Support Team will help you over there.

I'm closing this issue.

Thanks.
