### ISSUE TITLE
Transfer ownership of ansible-sensu

### ISSUE THREAD

**Issue by jaredledvina** [rtfd/readthedocs.org#3724]
## Details

* Project URL: https://readthedocs.org/projects/ansible-sensu/
* Build URL (if applicable): https://readthedocs.org/projects/ansible-sensu/builds/
* Read the Docs username (if applicable): jaredledvina

## Expected Result

Hi! Currently, the `ansible-sensu` repo has moved under the Sensu organization on Github. It appears, that ever since that move, the builds have never been kicked off even though looking at the Github integration, things look legit. I think, we just need an Owner of the RTD site to update the config for the new repo and/or relink the repo. 

I have already opened https://github.com/sensu/sensu-ansible/issues/135 but have been unsuccessful in getting the current owner to take a look. Is there any chance you'd be able to add the current Sensu Ansible maintainers as owners of the `ansible-sensu` docs repo? 

Current list of Sensu Ansible maintainers: https://github.com/sensu-plugins/community/#maintained-areas 

I'm happy to provide any information that might be helpful here, just let me know!

**Comment by jaredledvina** [comment]
Any chance someone might have a few to take a look here? If I need to provide any additional information I'm happy too. (likewise if there's a better avenue to accomplish this, let me know!)

**Comment by RichardLitt** [comment]
cc @humitos or @agjohnson?

**Comment by humitos** [comment]
@jaredledvina hi! I just send and email to @cmacrae. Let's see if we have any sucessful reply.

**Comment by cmacrae** [comment]
Hi guys 👋 Sorry about the delayed response. Yes, I'm absolutely happy for ownership/permissions to be granted for this. Let me know if there's any action I need to take!

**Comment by humitos** [comment]
To grant permissions to @jaredledvina so he can update the docs, you have to go to https://readthedocs.org/dashboard/ansible-sense/users/ and add @jaredledvina user. Thanks a lot!

**Comment by cmacrae** [comment]
Thanks! All done - @jaredledvina

**Comment by humitos** [comment]
@cmacrae thanks a lot!

I'm closing the issue since I can see @jaredledvina as a member of the project now. In any case, feel free to reopen if you consider.
