### ISSUE TITLE
"stable" doesn't point to latest tag.

### ISSUE THREAD

**Issue by Sraw** [rtfd/readthedocs.org#3729]
## Details
I have a tag named "0.0.4"(a new one) and a tag named "v0.0.3"(an old one).
I expect that "stable" will point to tag "0.0.4" instead of "v0.0.3".
But "stable" doesn't point to latest tag.

* Project URL: https://github.com/Sraw/nswebdav
* Build URL (if applicable): https://readthedocs.org/projects/nswebdav/versions/
* Read the Docs username (if applicable): Sraw

## Expected Result

In build page:
0.0.4: 509e05f0
v0.0.3: 48dde04d
stable: 509e05f0

## Actual Result
0.0.4: 509e05f0
v0.0.3: 48dde04d
stable: 48dde04d

**Comment by stsewd** [comment]
Looks like you disable all versions but latest and `0.0.4`.

But with the names you provide the code should be fine.

```python
>>> from packaging.version import Version
>>> versions = [Version('v0.0.3'), Version('0.0.4')]
>>> sorted(versions)
[<Version('0.0.3')>, <Version('0.0.4')>]
```

**Comment by Sraw** [comment]
@stsewd Yes, I expect it should be fine too. But it really doesn't.
The reason why I disable other versions is because `v0.0.3` has some issues which would cause failed build. And that's also why I need to push a new version `0.0.4`.
For now, `stable` still points to `48dde04d` which is `v0.0.3`.

That is really strange, I cannot understand what happen.

**Comment by humitos** [comment]
Did you try by wiping your versions?

I imported this project in my local instance and I got the proper versions selected:

![captura de pantalla_2018-03-05_20-51-27](https://user-images.githubusercontent.com/244656/37009934-1677e638-20b7-11e8-98fb-aefffe98c3ed.png)

**Comment by Sraw** [comment]
@humitos I have tried wiping `0.0.4`, `v0.0.3`, `stable` and `stable`. None of them works.
Perhaps that is caused by my advanced settings?
I manually set a pip requirements file to `docs/requirements.txt`, use `CPython 3.X` Python interpreter and enable global site-packages.

**Comment by stsewd** [comment]
@Sraw I also was able to import the project correctly on my local installation. Did you try activating `stable` momentarily and building it again (also wiping and building again master)?

**Comment by Sraw** [comment]
I manually delete whole project in readthedocs and then reimport it. Now it works fine...

Hope I wouldn't meet this issue again, thanks everyone!
