### ISSUE TITLE
Change "Submit" text on buttons to something more meaningful

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#3735]
All the forms contains a button `Submit` to send the form, but is not always is the _best word_  (where `Save` or `Add` would make more sense).

Probably should be done after some other PRs related to the UI gets merged, so we avoid a lot of conflicts.

**Comment by shubham76** [comment]
Hey @stsewd! I would like to work on this. Which other PRs are yet to be merged so that we can avoid conflicts with this one?

**Comment by stsewd** [comment]
@shubham76 I think #3572, #3548, #3445 are the PRs that you need to be aware while making changes. You can make an initial PR and if the changes crosses on some file, better wait to the others PRs are merged to continue on that file. Let me know if you need more help, also this was initial suggested by @davidfischer, so he can help you with the correct words on the buttons if you aren't 100% sure.

**Comment by shubham76** [comment]
Okay. I'll start working on it!
Thanks!

**Comment by davidfischer** [comment]
I'm thrilled with this!

**Comment by stsewd** [comment]
Fixed on #3749
