### ISSUE TITLE
Text on search buttons

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3741]
There are a few places we're using the copy "Go Crazy" in our UI. I know this is meant to be some light hearted, colorful language, but this term is insensitive, as is the case for most uses of the word "crazy". It's also poor UX as it's not clear what the button should do based on it's text, and I'm sure doesn't translate to other languages as it's more of an english slang term. We should change this to something that makes sense for everyone here.

**Comment by rajujha373** [comment]
@agjohnson  I am taking on this issue... Thanks :)

**Comment by vishrutkohli** [comment]
Can I also work on this issue?

**Comment by RichardLitt** [comment]
@vishrutkohli I think that #3752 covers all of the needed changes. I would suggest looking for some other issues labelled 'Good First Issue' for now. :)
