### ISSUE TITLE
Clean deletion of a Version

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3743]
When a Version is deleted, we are triggering `clear_artifacts` _and_ `symlink_project` but the later is triggered _before_ the object deletion; so, I think if the task is ran before it's effectively deleted the symlink won't be properly synced:

https://github.com/rtfd/readthedocs.org/blob/5472906a067adc60f42556108993255393408410/readthedocs/builds/models.py#L181-L187

To fix this we could chain some Celery task in this order:

1. trigger `clear_artifacts`
1. delete the Version object
1. trigger `symlink_projects`

Take into account that the first and last have to be executed in a broadcast call but the second one should be executed just once since it affects the database.

> This method `Version.delete` is not used in the codebase at all, so I'm not sure if this is a priority. I found that all the Versions are activated/deactivated but not deleted.

Ref: https://github.com/rtfd/readthedocs.org/pull/3649#issuecomment-370915276

**Comment by agjohnson** [comment]
We can use Celery task chaining to accomplish this probably.

**Comment by stsewd** [comment]
> This method Version.delete is not used in the codebase at all, so I'm not sure if this is a priority. I found that all the Versions are activated/deactivated but not deleted.

Actually, we delete the versions when syncing the versions

https://github.com/rtfd/readthedocs.org/blob/4fbe0afde6bd0fc9fc14baee79dd361d68f714cb/readthedocs/restapi/utils.py#L134-L154

https://github.com/rtfd/readthedocs.org/blob/4fbe0afde6bd0fc9fc14baee79dd361d68f714cb/readthedocs/restapi/views/model_views.py#L196-L196

I'm not sure about chaining the tasks. What I understand, is that we access to the versions from the `symlink_project` task, which is in a race condition with the deletion of the current version.

So at least that `clear_artifacts` is in a race condition with `symlink_projects`, we can just change the call order and that would be enough.

**Comment by stsewd** [comment]
`symlink_project` access to all versions and a version is being deleted at the same time. So, probably the symlink would stay
