### ISSUE TITLE
Track the Docker image hash in readthedocs-environment.json

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3744]
We are doing some basic checks on python version change around our `readthedocs-environment.json` metadata file. We should also drop the build image SHA in there, so that if it ever changes, we know to wipe the build env.

For instance, we're saving here:
https://github.com/rtfd/readthedocs.org/blob/7be1b805d59c0683855f05a252850bba09287a20/readthedocs/doc_builder/python_environments.py#L150-L162

On save, we should:

* Check to see if docker builds are enabled before writing information about the docker build
* Get the build image name that the build would use
* Query the docker API for the build image SHA that matches the build image name
* Write that to disk

On build, we should check this file against the current image SHA and if they differ, the image has changed and we should rebuild without the cache.

**Comment by humitos** [comment]
I agree with this idea.

I think we just need to add the `build.hash` option to the JSON file and check it again in the `is_obsolete` method.

`docker inspect` does the magic to get the `Id`:

```
$ docker inspect readthedocs/build:2.0 | jq ".[0].Id"
"sha256:9468fcb95b87a9a5cd58c2d37da35983df8c3334a80181fed12b5a04892fffb9"
```

I can take this one if you want and do it.

**Comment by ericholscher** [comment]
+1 on keeping any specific data that we can on disk, so we can do sanity checking against it.
