### ISSUE TITLE
There was a problem with Read the Docs while building your documentation

### ISSUE THREAD

**Issue by germartinez** [rtfd/readthedocs.org#3748]
## Details

* Project URL: **https://readthedocs.org/projects/gnosisjs/**
* Build URL (if applicable): **https://readthedocs.org/projects/gnosisjs/builds/6853414/**
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

ReadTheDocs shouldn't return a failed build ¿?
I can compile successfully my docs locally.

## Actual Result

*A description of what actually happened*

I get this message after building my latest version with Sphinx.

`There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6853414).`

Thank you!

**Comment by stsewd** [comment]
I was able to build your docs successfully on my local instance, did you try wiping the build?

**Comment by stsewd** [comment]
Not, the build that pass is for `stable`. The `lates` versions fails with `Could not import extension sphinx_js (exception: No module named sphinx_js)`.

**Comment by weeb-kun** [comment]
sorry, is there a way to include sphinx_js to build on readthedocs.org?
