### ISSUE TITLE
Transfer/add ownership

### ISSUE THREAD

**Issue by reox** [rtfd/readthedocs.org#3756]
## Details

* Project URL: http://readthedocs.org/projects/androguard/
* Build URL (if applicable): 
* Read the Docs username (if applicable): reox

## Expected Result

I'm working on https://github.com/androguard/androguard/ and like to update the documentation.

## Actual Result

Can not update the documentation, as the repository is owned by someone else, who is not part of the androguard developers.
See also https://github.com/rtfd/readthedocs.org/issues/2818#issuecomment-366809545

Can you please ask the user to transfer the ownership or add me as owner as well?

thanks in adanvce!

**Comment by humitos** [comment]
I sent an email contacting the owner of the project and linking this issue in the email. Hopefully we will have news in the next weeks.

**Comment by humitos** [comment]
The email was marked as SPAM. I tried from a different account today. Let's see how it goes.

**Comment by reox** [comment]
just wanted to know if there are any news here? thanks in advance!

**Comment by humitos** [comment]
We don't have news from `kotz` (my latest email wasn't marked as SPAM so, I suppose it was received)

We do have a policy for these times at http://docs.readthedocs.io/en/latest/abandoned-projects.html

05/26 will be 6 weeks from my email and will be considered _unreachable_.

**Comment by humitos** [comment]
@reox good news for you!

I just added you as Maintainer of http://readthedocs.org/projects/androguard/ since `kotz` never anwered my emails.

I'm closing this issue. Please, let us know if you have proper access and you can update those docs ;)

**Comment by reox** [comment]
thanks! yep, everything works fine!
