### ISSUE TITLE
Split requirements/pip.txt for LocalBuildEnvironment and RTD specific

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3757]
Now, we have a big `requirements/pip.txt` that covers two big things:

* RTD project specific requirements (django, requests, docker, etc)
* local builds for user's documentation (mkdocs, etc) --these are used when building documentation _without_ docker

We want to remove the dependencies for building the docs outside Docker from the `pip.txt` file, so to accomplish this issue we need:

- [ ] create a new file `requirements/local-docs-build.txt`
- [ ] take a look at that list and classify each of the requirements on one of these points
- [ ] move not RTD specific requirements to the new file
- [ ] QA/test manually by creating the proper venvs with the proper requirements and build random project's documentation

Ref: https://github.com/rtfd/readthedocs.org/pull/2916#issuecomment-371685947

**Comment by Jigar3** [comment]
I want to solve this issue. Can you help me get started

**Comment by stsewd** [comment]
@Jigar3 I think there is a very good description about the issue and the needed steps, there is something specific that you need help with?

**Comment by RichardLitt** [comment]
@Jigar3 I think that @rajujha373 has taken a stab at it. Look at his solution; it should help you see how you could have done it. For now, I think that you don't need to help solve this one. I would suggest looking at some other issues which are currently open! Please always feel free to ask questions, but know that we are mostly volunteer run, and we may expect you to tinker around a bit sometimes. :)
