### ISSUE TITLE
Verify Email is not send - set verify manually

### ISSUE THREAD

**Issue by jonazc** [rtfd/readthedocs.org#3770]
I installed RTD on a shared host webserver. It works fine, but there seems to be a problem with the email module. However, thats why I can't set up a account, because the Email verification is not sent. I cannot see any errors in the log.

Where or how do I have to set the verification bit manually so I get get around this problem in the first place?

**Comment by shubham76** [comment]
The verification link will be there in the terminal. You can click on that to verify the account.

**Comment by rajujha373** [comment]
@jonazc You can add an **Email addresses** at the /admin page and check the verified checkbox for an email to be verified manually.

**Comment by jonazc** [comment]
I got the link from terminal like @shubham76 proposed!
