### ISSUE TITLE
Can't build versions - problem with custom port?

### ISSUE THREAD

**Issue by jeyca** [rtfd/readthedocs.org#3774]
I have RTD installed on a shared Webhost following these instructions:

https://docs.readthedocs.io/en/latest/install.html

Everything went through like a charm, I just had to change the server call by: `python manage.py runserver 127.0.0.1:61500` because I can't work on port 8000.

But there seems to be a problem while building a public version. I imported the demo project and it keeps staying like this for too long time:

> ![building](https://user-images.githubusercontent.com/37297730/37289458-00cbf9ac-260a-11e8-9e5a-73b320aec63a.png)

So nothing changed for over 20 minutes, and no ready version appeared there.

Then I tried to start new builds like you see here, but nothing good happens:

> ![builds](https://user-images.githubusercontent.com/37297730/37289040-fdfb23b6-2608-11e8-9aa6-db7b27fa48aa.png)

in active versions this is shown:

> ![versions2](https://user-images.githubusercontent.com/37297730/37289065-0be95024-2609-11e8-8055-34d8a888128e.png)

and even when there are builds shown under the tab, there are no builds provided in the overview bar:

![nobuilds](https://user-images.githubusercontent.com/37297730/37289087-2719e03e-2609-11e8-8ac9-9dad1fd4b976.png)

I looked up what is going on in the terminal, and there is this report:

> [12/Mar/2018 09:13:17] readthedocs.projects.tasks:284[22442]: ERROR An unhandled exception was raised during build setup
Traceback (most recent call last):
  File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 268, in run
    self.project = self.get_project(pk)
  File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 424, in get_project
    project_data = api_v2.project(project_pk).get()
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/slumber/__init__.py", line 155, in get
    resp = self._request("GET", params=kwargs)
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/slumber/__init__.py", line 97, in _request
    resp = self._store["session"].request(method, url, data=data, params=params, files=files, headers=headers)
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(**host='localhost', port=8000**): Max retries exceeded with url: /api/v2/project/25/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9348d99cd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
[12/Mar/2018 09:13:17] celery.app.trace:248[22442]: ERROR Task readthedocs.projects.tasks.update_docs[b5e318c0-c754-441e-9ec7-a5228bbd52fa] raised unexpected: AttributeError("'UpdateDocsTask' object has no attribute 'setup_env'",)
Traceback (most recent call last):
  File "/home/xuser/src/rtd/lib/python2.7/site-packages/celery/app/trace.py", line 374, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/projects/tasks.py", line 288, in run
    build_id=build_pk,

I noticed the port=8000 there, that its possibly a problem here?!

**Comment by stsewd** [comment]
As mention on https://docs.readthedocs.io/en/latest/install.html (almost at the end)

> For builds to properly kick off as expected, it is necessary the port you’re serving on (i.e. runserver 0.0.0.0:8080) match the port defined in PRODUCTION_DOMAIN. You can utilize local_settings.py to modify this. (By default, it’s localhost:8000)

**Comment by jeyca** [comment]
Ok I set this up in an additional `readthedocs/settings/local_settings.py`, but it still didn't work. Then I also changed two other variables like this:

    PRODUCTION_DOMAIN = '127.0.0.1:61500'
    SLUMBER_API_HOST = 'http://127.0.0.1:61500'
    PUBLIC_API_URL = 'http://rtd.mypage.com'

then it worked somehow, but still I have to deal with some problems:

**1. Variable docu**
Unfortunately, I don't know exactly what these variables are used for and I can't find documentation about it.

**2. Proxy Error**
However, now the page takes some time for importing and building, but after that ends up here:

> ![proxy](https://user-images.githubusercontent.com/37297730/37296999-dbd01da0-261c-11e8-9dba-8610c6b876fc.png)


**3. Url problem**
When I browse back to the overview, I come to this:

> ![newbuild](https://user-images.githubusercontent.com/37297730/37297030-ee437c02-261c-11e8-90cf-5979e12e4faa.png)

when I click on **stable**, the url is like `http://127.0.0.1:61500/docs/xuser-demo/en/stable/`, so the domain is wrong, because it should be `http://rtd.mypage.com/...`. When I change the url manually, I can open the doc, yeah!

**4. build error**
But, still there is the error for the latest build. 

![builds2](https://user-images.githubusercontent.com/37297730/37297361-c7f26616-261d-11e8-82d7-9ebc898e73ea.png)

the logs for the builds include errors for latex and makeindex:

> pdflatex -interaction=nonstopmode /home/xuser/src/rtd/checkouts/readthedocs.org/user_builds/xuser-demo/checkouts/stable/docs/_build/latex/ReadtheDocsTemplate.tex
> Traceback (most recent call last):
>   File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 151, in run
>     env=environment,
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Command time: 0s Return: -1
> makeindex -s python.ist ReadtheDocsTemplate.idx
> Traceback (most recent call last):
>   File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 151, in run
>     env=environment,
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory
> Command time: 0s Return: -1
> pdflatex -interaction=nonstopmode /home/xuser/src/rtd/checkouts/readthedocs.org/user_builds/xuser-demo/checkouts/stable/docs/_build/latex/ReadtheDocsTemplate.tex
> Traceback (most recent call last):
>   File "/home/xuser/src/rtd/checkouts/readthedocs.org/readthedocs/doc_builder/environments.py", line 151, in run
>     env=environment,
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 390, in __init__
>     errread, errwrite)
>   File "/package/host/localhost/python-2.7.14/lib/python2.7/subprocess.py", line 1025, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory 


There still seems to be problems with the urls, and additionally with makeindex/pdflatex. Why does this only affect the latest build, but not stable? How can I fix the urls and the build problems?

**Comment by stsewd** [comment]
For the url `PRODUCTION_DOMAIN` should point to your production domain, not to localhost.

For the build problem is because your server don't have the libs for generate pdf and latex stuff (you can also configure rtd to build using docker https://docs.readthedocs.io/en/latest/development/buildenvironments.html or deactivate the pdf generation on your project admin panel).

Please see https://docs.readthedocs.io/en/latest/custom_installs/index.html for custom installations.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
