### ISSUE TITLE
Error while cloning: abort: couldn't find mercurial libraries

### ISSUE THREAD

**Issue by paugier** [rtfd/readthedocs.org#3786]
## Details

* Build URL (if applicable): https://readthedocs.org/projects/fluidsim/builds/6883162/
* Read the Docs username (if applicable): paugier

## Actual Result

The build failed because Mercurial does not seem to be installed on the server...

**Comment by humitos** [comment]
This should be fixed now.

I'm closing the issue. Please, feel free to reopen if you still have the problem.
