### ISSUE TITLE
Repository URL isn't a link

### ISSUE THREAD

**Issue by kezabelle** [rtfd/readthedocs.org#379]
See, for example, [this page, for django-admin-theme](https://readthedocs.org/projects/django-admin-theme/) - there's a URL in the *Repository* field, but it isn't marked up as an `<a href="...">`, from a UI standpoint, it'd be nice to not have to copy-paste that into my location bar, especially on devices where copy-pasting is kind of a chore (hello touch interfaces)

**Comment by destroyerofbuilds** [comment]
@agjohnson, can this issue please be re-opened. It seems @wraithan's change was refactored out as part of your change here: 0cd361e830c50b513cf44b5134ca419d82550457

**Comment by agjohnson** [comment]
Good catch, we sure can.
