### ISSUE TITLE
Search result titles incorrectly include "(from project foo)"

### ISSUE THREAD

**Issue by begriffs** [rtfd/readthedocs.org#3792]
## Expected Result

Search results should list the title of each page and a snippet.

```
Title One
some stuff in the page

Title Two
other stuff
```

## Actual Result

Each title ends with a note "(from project foo)"

```
Title One (from project foo)
some stuff in the page

Title Two (from project foo)
other stuff
```
[example](https://docs.citusdata.com/en/v7.2/search.html?q=testing&check_keywords=yes&area=default#)

## Cause

A recent commit to fix linter errors changed a `!=` operator to `!==`: https://github.com/rtfd/readthedocs.org/blame/e923c0cdf7547e63b4d2a9ab2b5e69b527bb482b/readthedocs/core/static-src/core/js/doc-embed/search.js#L52-L57

```js
if (fields.project !== project) {
```
Adding a breakpoint to that code, I saw that `fields.project` had the value `['foo']` while `project` was `'foo'`. The old comparison treated them as equal, but the strict comparison knows that they differ.

/cc @bansalnitish

**Comment by stsewd** [comment]
Seems that the search functionality comes from a private repo https://github.com/rtfd/readthedocs.org/blob/d918a0fde1252ddbfa9c57dc6f196a207d65d9dc/readthedocs/restapi/urls.py#L95-L102.

**Comment by humitos** [comment]
@davidfischer seems that the linting PR around js code, breaks the search page results. It makes what @begriffs is saying here. Can you take a look at this?

**Comment by bansalnitish** [comment]
We can revert this case as well as mark the check as a warning instead of error for fixing this issue.

**Comment by humitos** [comment]
Why `fields.project` is `['foo']` instead of just `'foo'` in first instance? Maybe that it's what needs to be changed, right?

**Comment by begriffs** [comment]
Any decision about what to do, i.e. revert the breaking change, or store as `'foo'` rather than `['foo']`? The former sounds more straightforward even though it seems like somewhat unclean code.

**Comment by stsewd** [comment]
Resolved on https://github.com/rtfd/readthedocs.org/pull/4176/
