### ISSUE TITLE
Request a workaround to redirect a sub-topic of an HTML page to a New HTML page. 

### ISSUE THREAD

**Issue by veenamj** [rtfd/readthedocs.org#3794]
## Details

* Project URL: Genearal Question
* Build URL (if applicable): NA
* Read the Docs username (if applicable): NA

## Expected Result

I need to redirect a subtopic of a page to the same topic that has been moved to the new page. Is that possible any way? ReadTheDocs Admin page only redirects page/exact redirects. 

I have used the same cross-reference tag when I moved the subtopic to the new page. But it is not working with ReadTheDocs Page/Exact Redirects. 

## Actual Result

General query.

**Comment by stsewd** [comment]
Maybe this https://github.com/rtfd/readthedocs.org/issues/3465 is what you need?

**Comment by humitos** [comment]
Just in case. It's already fixed but not deployed yet. That will happen tomorrow, hopefully.

**Comment by veenamj** [comment]
Thanks, @RichardLitt, and @humitos for informing!
