### ISSUE TITLE
[Support] Can't reset password

### ISSUE THREAD

**Issue by rmihael** [rtfd/readthedocs.org#3795]
## Details

* Project URL: nimble.readthedocs.io
* Read the Docs username (if applicable): p.dmitriev@nimble.com

I am trying to reset the password for p.dmitriev@nimble.com through https://readthedocs.org/accounts/password/reset/.

## Expected Result

An email with a password reset link will arrive in p.dmitriev@nimble.com mailbox.

## Actual Result

No email arrived.

**Comment by humitos** [comment]
@rmihael can you check your SPAM folder or similar? Seems to be related to your own email account.

I just reset my own password and I got the proper email in my inbox.

**Comment by rmihael** [comment]
I checked all folders, no signs of this email. Other emails arrive just fine.

The only thing that is special about this account is that it was disabled for some time and now re-enabled. Could it be that your email delivery service applies some weird rules for such accounts?

**Comment by rmihael** [comment]
@humitos, can you suggest any other action that I can take? We cannot fix documentation because of this problem. Is it possible to change account's email to something else that belongs to our domain? devadmin@nimble.com will work for me. I can confirm this change from p.dmitriev@nimble.com mail.

**Comment by rmihael** [comment]
@humitos, sorry to bother you, but this problem is blocking us. Is there anything that I can do to recover access to this account?

**Comment by humitos** [comment]
@rmihael Hi! Don't worry. I don't know what's the process here, so I'm asking to not screw anything :)

I'm sorry that I don't have the solution yet.

**Comment by davidfischer** [comment]
@rmihael, I sent an email to `p.dmitriev@nimble.com` from my readthedocs.org email account. Please respond to that email to confirm your ownership over the account in question.

**Comment by rmihael** [comment]
@davidfischer, I just replied. Thank you for help.

**Comment by davidfischer** [comment]
Thanks I received it and sent a temporary password to that email. I'm glad we got this sorted out.

**Comment by rmihael** [comment]
Thank you so much!
