### ISSUE TITLE
Failure building documentation: "There was a problem with Read the Docs while building your documentation"

### ISSUE THREAD

**Issue by HannahVMeyer** [rtfd/readthedocs.org#3796]
## Details

* Project URL: http://limmbo.readthedocs.io/en/latest/
* Build URL (if applicable): 6888310
* Read the Docs username (if applicable): HannahMeyer

## Expected Result
Successful build of documentation

## Actual Result
Error
There was a problem with Read the Docs while building your documentation.
Please report this to us with your build id (6888310).

The same error has occurred for build 6888069, 6888077.

Intermediate builds (6888087, 6888092, 6888288), did not show this error message but fail with: CondaValueError: pip returned an error.

**Comment by stsewd** [comment]
Hi, I import your project on my local instance and failed due memory limits, I think that's the problem you are experimenting. Note: I was able to build your docs successfully increasing the memory and time limit.

**Comment by stsewd** [comment]
Are you still having this problem? We move to azure recently and now we have faster servers, can you try building your project again?

**Comment by stsewd** [comment]
You can also check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

If you are still having the problem with memory/time limits, please open a new issue requesting more resources.
