### ISSUE TITLE
Organizations to group a set of projects

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#3798]
We (https://github.com/italia/) need to track the ownership of a set of project to an organization. That would mean something like have a view of e.g. all the aio-libs or pypa projects together.
That's a close match to RemoteOrganization but we need to augment it with some more fields like a title, description, short name, url, tags, and a whitelist of projects that we can hook to our RTD instance. 
Then we are thinking of a system of configuration files put on a well-known name repository inside the organization and webhook to track updates on the repository and update the RTD models. Do you think something of this may be helpful upstream?

**Comment by humitos** [comment]
Hi @xrmx! I'm not 100% sure to understand your proposal but I think this could be similar to what we already have implemented in our corporate site (readthedocs.com); where you can create Organizations, add projects to the organization and manage different teams of users with different permissions over the docs: http://docs.readthedocs.io/en/latest/business/organizations.html

Is something like that what you need? Otherwise, can you expand your idea?

**Comment by humitos** [comment]
Another thing that could be related to what you are proposing here is `Collections of projects`, which is an idea under our GSoC program to be implemented: http://docs.readthedocs.io/en/latest/gsoc.html#collections-of-projects

**Comment by xrmx** [comment]
Yes something like that but AFAIK we don't  care about permissions much. We want this hierarchy:

docs projects -> umbrella project -> organization

docs is a subproject of umbrella and both need to be associated with an organization. Each organization will have an homepage and we want to being able to restrict search to projects of the same organization / umbrella project (see #3765)

**Comment by xrmx** [comment]
So I've digged a bit more in the code. It looks like that we can leverage RemoteOrganization and add our logic into a Custom GithubService. One change that would make this job easier is to make the `oauth.services.__init__.registry` and thus the `oauth.utils.SERVICE_MAP` overridable from a config file. Would you accept a PR doing that?

**Comment by xrmx** [comment]
So I've found this `SettingsOverrideObject` which should do the trick without having to patch anything.

**Comment by RichardLitt** [comment]
Thanks for following up and letting us know, @xrmx!
