### ISSUE TITLE
Stop syncing `_static` directory for JSON

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#3799]
Currently we are syncing the `_static` directory on our JSON builder. We should stop moving this across to the webs, because we never use it, and it's taking up _a ton_ of disk space. I've deleted it manually, but we should also make sure we stop syncing it in the future.

**Comment by rajujha373** [comment]
Hi @ericholscher , can you please provide more details regarding the issue. I am thinking to give a hit at it. :)

**Comment by ericholscher** [comment]
Sure. We currently copy JSON from the build servers to the web servers, so that we can reindex search results. That happens after the files are synced from the "json" builder to a place on the filesystem. That syncing is handled here: 

* https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L656-L660
* https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/base.py#L60
* https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/doc_builder/backends/sphinx.py#L242-L246

We should probably add a step, or use an existing abstraction, to exclude the `_static` directory from being copied. Perhaps an additional argument to `move`, or maybe an `exclude_paths` option on the `BaseBuilder` class.

**Comment by stsewd** [comment]
Hi, @rajujha373 are you working on this issue?

**Comment by rajujha373** [comment]
Hi, @stsewd . Yes, Im working on this issue. :)
