### ISSUE TITLE
Return 404 at SubdomainMiddleware level if project doesn't exist

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3801]
While deploying .com we found that `SubdomainMiddleware` doesn't check the existence of the project that it's injecting at `request.slug`.

So, any middleware that relies on this to do some extra work, will probably do something like `Project.objects.get(slug=request.slug)` and will fail.

We workarounded it by adding `try/except` block in the middleware that uses this, but we should probably just raise a 404 inside the `SubdomainMiddleware` itself instead of continue with the flow.

Code: https://github.com/rtfd/readthedocs.org/blob/74bbb3ac23b6b06a70517bc1b301961db6821e32/readthedocs/core/middleware.py#L72

**Comment by dojutsu-user** [comment]
@humitos I would like to take this issue up.
If I'm not wrong, you probably want something like this

```python3
# Checking if the project exist or not
from django.shortcuts import get_object_or_404
get_object_or_404(Project, slug=subdomain)

request.subdomain = True
request.slug = subdomain
request.urlconf = SUBDOMAIN_URLCONF
return None
```

**Comment by humitos** [comment]
@dojutsu-user since this is a code that it's executed a lot, retrieving the whole Project object it may be overkilling since we not going to use that data anyway. You may just need to check if the project does exist with `.exists()` and using an if in this case.
