### ISSUE TITLE
Elasticsearch not working in local installation

### ISSUE THREAD

**Issue by rajujha373** [rtfd/readthedocs.org#3803]
I am using readthedocs in my localhost but the problem here is that the search feature is not working and throws an exception everytime I search something.

Elasticsearch version 5.6.8 and i think it might be an issue related to the version of elasticsearch used. It would be great if the version to be installed shall be included into the [installation documentation](http://docs.readthedocs.io/en/latest/install.html) too.

<code>

Request Method:  GET

Request URL: http://localhost:8000/search/?q=hello

Django version: 1.9.12

Exception Type: RequestError

Exception Value: TransportError(400, u'parsing_exception')

Exception Location: /home/raj/READTHEDOCS/venv/lib/python2.7/site-packages/elasticsearch/connection/base.py in _raise_error, line 105

Python Executable: /home/raj/READTHEDOCS/venv/bin/python

Python Version: 2.7.14

</code>

**Comment by xrmx** [comment]
You should use a 1.x version of elasticsearch, I think 1.3.x is the one that should work. 1.5.8 did not work for me.

**Comment by xrmx** [comment]
Also see https://github.com/rtfd/readthedocs.org/issues/3697

**Comment by rajujha373** [comment]
Thank you @xrmx .
 I downgraded the elasticsearch to version 1.3.8 and run <code> python manage.py reindex_elasticsearch </code> to make it running.

**Comment by stsewd** [comment]
@rajujha373 @xrmx would be awesome if you write a guide of how to make elastic search woking. Maybe under https://docs.readthedocs.io/en/latest/guides/index.html or on the `Developer Documentation` toctree.

**Comment by xrmx** [comment]
@stsewd I'll gladly write one once https://github.com/rtfd/readthedocs.org/pull/3787 is merged :)

**Comment by RichardLitt** [comment]
Let's keep this open until there's a guide PR to close it, then. :)

**Comment by rajujha373** [comment]
@RichardLitt  @stsewd Shall I write the guide for this then? @xrmx can update the guide once #3787 is merged :)

**Comment by stsewd** [comment]
@rajujha373 I'm not the one to said it, but looks like the PR that #3787 is based on (#3373) was marked as blocked a couple months ago

![screenshot-2018-3-22 upgrade search app to elastic search 5 4 by ericholscher pull request 3373 rtfd readthedocs org](https://user-images.githubusercontent.com/4975310/37808783-336f6138-2e1a-11e8-872a-aa53f53926f7.png)

So, I think is is safe to write the guide now. 

@humitos what do you think?

**Comment by humitos** [comment]
I don't know. I'd wait for Eric to reply --who is the one that originally started this work.

**Comment by rajujha373** [comment]
Cool @humitos , I am writing the guide then

**Comment by stsewd** [comment]
A guide was writing in https://github.com/rtfd/readthedocs.org/pull/3881

**Comment by jibunzel** [comment]
Why did this guide disappear in rtd? I have been having issues with my elasticsearch not working for searching files and this guide would be helpful.

**Comment by dojutsu-user** [comment]
@jibunzel 
Previous guide was removed because it got outdated.
You can find the new guide here: https://docs.readthedocs.io/en/latest/development/search.html
