### ISSUE TITLE
Two recent builds were terminated due to inactivity.

### ISSUE THREAD

**Issue by krzychb** [rtfd/readthedocs.org#3807]
## Details

* Project URL: https://github.com/krzychb/esp-idf
* Build URL (if applicable):
  *  https://readthedocs.org/projects/esp-idf-kb-cn/builds/6896066/
   * https://readthedocs.org/projects/esp-idf-kb/builds/6896067/
* Read the Docs username (if applicable): krzychb

## Expected Result

Build should complete

## Actual Result

Build was terminated:

![image](https://user-images.githubusercontent.com/12953787/37477033-f9639a52-2876-11e8-8363-ef6257a30c2b.png)

![image](https://user-images.githubusercontent.com/12953787/37477192-4bdcb71e-2877-11e8-8965-4e4632cb0eea.png)

Please help resolving this issue.

**Comment by stsewd** [comment]
I see both build failed by timeout

![screenshot-2018-3-15 esp-idf-kb-cn read the docs](https://user-images.githubusercontent.com/4975310/37477426-b38c8790-2845-11e8-95a6-877f4900c084.png)

**Comment by krzychb** [comment]
Now I see the timeout as well.
This is strange the failure qualification has changed. I have not seen it before.

Thanks for looking into it this issue.
