### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by ShalokShalom** [rtfd/readthedocs.org#3819]
Is there a dark theme?

**Comment by davidfischer** [comment]
Are you talking about a Sphinx documentation theme? Read the docs itself only produces one theme (https://github.com/rtfd/sphinx_rtd_theme) and it is not exactly a dark theme. However, if you look around I suspect there are dark themes.

Here's an incomplete list of Sphinx themes and what they look like:
https://github.com/rtfd/rtd-sphinx-themes-examples

**Comment by ShalokShalom** [comment]
I mean for readthedocs?

**Comment by davidfischer** [comment]
There isn't. However, there is some significant UI changes in the works. While I can't promise anything,  would you be looking for?

**Comment by ShalokShalom** [comment]
Sure :D

**Comment by SitiSchu** [comment]
Theres this Stylish theme: https://userstyles.org/styles/142968/readthedocs

You could ask the author in the comments if you can use his css and include it as custom CSS(an official dark theme would still be better ^^)

**Comment by agjohnson** [comment]
Closing this as a feature we likely wouldn't maintain. We are already bad enough at maintaining our styles, two would be infinitely harder for us to do well.

**Comment by adreyfus** [comment]
conf.py: 
```
html_css_files = [
    'css/rtd_dark.css',
]
```
[rtd_dark.zip](https://github.com/readthedocs/readthedocs.org/files/3434926/rtd_dark.zip)

**Comment by ShalokShalom** [comment]
https://darkreader.org/

**Comment by jtmoon79** [comment]
I was hoping this Feature might come along and be available for _all_ projects hosted at `readthedocs.io`.  Currently, my eyes burn reading them.

As for darkreader.org browser extension, I don't load any extensions in my browsers at home.  And at work, corporate security policy dissuades it.

**Comment by humitos** [comment]
@jtmoon79 this is a closed issue. We already decided that we are not going to implement this feature. On the other hand, most of modern web browser come with a "Reading mode" where you can configure a dark mode there.

**Comment by adreyfus** [comment]
conf.py: 
```
html_css_files = [
    'css/rtd_dark.css',
]
```
[rtd_dark-20200527-0855.zip](https://github.com/readthedocs/readthedocs.org/files/4687304/rtd_dark-20200527-0855.zip)

**Comment by jerclarke** [comment]
Userstyles.org barely works these days, and the style up on there was pretty nasty to actually use. 

I did a bunch of mods to make it darker and redo the syntax highlight (at least for PHP, which is what I was looking at) and the result is on this Gist, in case anyone wants to use it with the Stylus browser extension:

https://phpunit.readthedocs.io/en/9.3/writing-tests-for-phpunit.html

As a user, I also love to see a global dark-mode toggle built in to all utility sites like RTD. It's a lot simpler to "make it dark" than to add actual "custom themes". Luckily we can do it for ourselves and be patient :)

**Comment by MachinesJesus** [comment]
Using this on a project. https://darkreader.org/ extension for Chrome worked. Very excellent. Although I agree that ever GUI should have a dark mode switch. That said when there is tech like this chrome extension, perhaps the world will develop more rapidly and extensions will become the standard to solve this issue.

**Comment by hugovk** [comment]
https://pillow.readthedocs.io/ uses `sphinx_rtd_theme` and now has dark mode! I used the Dark Reader extension, exported the CSS, wrapped it in `@media (prefers-color-scheme: dark) { ... }` and added to our config.

See https://github.com/python-pillow/Pillow/pull/4968 for details (which also includes a bit of tweaking for black-on-white/transparent images that others can omit).

**Comment by WhyNotHugo** [comment]
Dark reader has a library which can generate the code. Perhaps the build process could generate and bundle that? It sounds low effort to maintain.

**Comment by rohit-kumar-j** [comment]
> Theres this Stylish theme: https://userstyles.org/styles/142968/readthedocs
> 
> You could ask the author in the comments if you can use his css and include it as custom CSS(an official dark theme would still be better ^^)

This is it. Thanks! 

![read_the_docs](https://user-images.githubusercontent.com/37873142/168166508-576b46cc-9bf3-465c-91c1-33949f388db7.gif)

**Comment by rohit-kumar-j** [comment]
> Userstyles.org barely works these days, and the style up on there was pretty nasty to actually use.
> 
> I did a bunch of mods to make it darker and redo the syntax highlight (at least for PHP, which is what I was looking at) and the result is on this Gist, in case anyone wants to use it with the Stylus browser extension:
> 
> https://gist.github.com/jerclarke/47665e0302bb54ac1688153dd8ff4db1
> 
> As a user, I also love to see a global dark-mode toggle built in to all utility sites like RTD. It's a lot simpler to "make it dark" than to add actual "custom themes". Luckily we can do it for ourselves and be patient :)

Thanks! This works without any stupid ads like : https://userstyles.org/styles/142968/readthedocs

**Comment by ShalokShalom** [comment]
> Dark reader has a library which can generate the code. Perhaps the build process could generate and bundle that? It sounds low effort to maintain.

Great idea, sounds awesome

**Comment by ErikKalkoken** [comment]
Here is an update to `rtd_dark.css` that will automatically render yours docs in dark or light mode based on system settings.

https://gist.github.com/ErikKalkoken/0baf538c767774bc11c0e8d4028972e6

**Comment by Ahajha** [comment]
Just commenting for anyone who might be in my situation: If you're using the dark reader extension and developing docs locally, you have to allow the extension to access local files, otherwise it won't do anything (Yes, this might be a security risk for some, use at your own discretion). If you're reading from a webpage, this won't be an issue.

**Comment by braveltd** [comment]
make dark theme available by default for all read the docs pleeeeeeaseee. we need it so much!

**Comment by ShalokShalom** [comment]
> make dark theme available by default for all read the docs pleeeeeeaseee. we need it so much!

You can use this
https://darkreader.org/

**Comment by pllim** [comment]
Now that there is a beta dashboard at https://beta.readthedocs.org/dashboard/ , is dark theme for dashboard supported yet?

**Comment by bukowa** [comment]
Because it's been a while, maybe there are some news?

**Comment by humitos** [comment]
The dashboard frontend repository is not at https://github.com/readthedocs/ext-theme and the issue for dark mode is at https://github.com/readthedocs/ext-theme/issues/216. Please, subscribe there for updates.
