### ISSUE TITLE
Update quickstart from README

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3832]
In our Quickstart guide from the README, https://github.com/rtfd/readthedocs.org#quickstart-for-github-hosted-projects we are pointing to the user to use the "Manual Import" to import a project from GitHub.

We need to re-write it to use the steps to import a project from a GitHub linked account instead (basically, add the steps to link your account and remove the steps to setup the webhook).

**Comment by varunotelli** [comment]
Hey I'd like to take up this issue. But could you explain what exactly I need to do?

**Comment by ze** [comment]
Hey @humitos, I submitted a pull request 2 days ago, would you be willing to review it? #3847 

Thanks!

**Comment by RichardLitt** [comment]
@ze We'll get to it when we have the time. :)

**Comment by davidfischer** [comment]
I believe this is fixed in #3847.
