### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by Peque** [rtfd/readthedocs.org#3833]
Not that it affected me, but in case it helps, and as readthedocs asks me to report an issue...

Build number 6932440.

![screenshot from 2018-03-22 21-48-41](https://user-images.githubusercontent.com/526577/37797706-d91ee310-2e1a-11e8-8020-1b86ad7f1364.png)

Thanks for this great tool! It usually works great. :blush:

**Comment by stsewd** [comment]
@Peque please provide the build url

**Comment by RichardLitt** [comment]
@stsewd Do we need that? Should we include that in the message about what to report?

**Comment by stsewd** [comment]
@RichardLitt I don't have access to the database so I need it :/

**Comment by Peque** [comment]
@stsewd Found it! :blush:

https://readthedocs.org/projects/mmsim/builds/6932440/

> Should we include that in the message about what to report?

Reporting the error number or the complete URL makes no difference for the user. Finding the URL later is a bit harder, as you need to look among all your projects.

If build IDs are really unique maybe they should be accessible from `https://readthedocs.org/builds/0123456/`?

**Comment by humitos** [comment]
It's too much easier when we are debugging if we have all the information filled in from the template. Clicking on an URLs it way faster that composing the URL by hand and remembering how was that format.

Those small things will help us to research/solve your issue faster.

Thanks!

**Comment by stsewd** [comment]
Seems like your previous builds are successful, and the latest 2 builds are failing because of a sphinx error. Closing, feel free to reopen if you consider.
