### ISSUE TITLE
Build fails to git checkout a specific hash/tag successfully

### ISSUE THREAD

**Issue by apcraig** [rtfd/readthedocs.org#3837]
## Details

* Project URL: https://readthedocs.org/projects/cice-consortium-cice 
* Build URL (if applicable): https://readthedocs.org/projects/cice-consortium-cice/builds/6936625/
* Read the Docs username (if applicable):  apcraig

## Expected Result

Documentation would checkout and build for a tag.  This works fine with master and other branches, but not with tags.

## Actual Result

I am trying to build documentation for a specific tag in github.  When I trigger that build, the checkout fails as follows

git clone --recursive https://github.com/cice-consortium/cice .
git show-ref remotes/origin/e03a341ba4d8fe569f581411a4b607e014fb8454 
git checkout --force origin/e03a341ba4d8fe569f581411a4b607e014fb8454
error: pathspec 'origin/e03a341ba4d8fe569f581411a4b607e014fb8454' did not match any file(s) known to git. 

I can duplicate this result on the command line.  

The following does work for a specific tag/hash.

git checkout --force e03a341ba4d8fe569f581411a4b607e014fb8454

or 

git checkout --force cice6.0.0.alpha

which is the actual tag associated with the hash.

git checkout --force origin/branch 

works fine for branches but origin/tag does not work for specific tags or hashes.

**Comment by irmen** [comment]
Encountering the same issue. seems like the git checkout process for "stable" documentation releases tries to do something wrong to get the tag it needs to checkout.  This used to work.

**Comment by stsewd** [comment]
@apcraig @irmen this was fixed on https://github.com/rtfd/readthedocs.org/pull/3843, can you try building again and see if your builds pass now?

**Comment by apcraig** [comment]
It works now for me.  Thanks.  I will close this issue.

**Comment by irmen** [comment]
@stsewd no luck, the stable build is still stuck at the previous version's commit in my project. I don't know what to do to solve this (apart from recreating my whole project, which is not something I'd like to do)

**Comment by stsewd** [comment]
@irmen please see https://github.com/rtfd/readthedocs.org/issues/3887#issuecomment-377848380 for more information

**Comment by irmen** [comment]
@stsewd thanks for the pointer. I will have a look. It is not a big issue though unless it is still stuck when I publish the next release. We will see.
