### ISSUE TITLE
Changing a tag to a branch leads to original and `_b` versions

### ISSUE THREAD

**Issue by brettcannon** [rtfd/readthedocs.org#3841]
## Details

* Project URL: http://gidgethub.readthedocs.io
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): brettcannon

## Expected Result

RTD to notice I changed a tag to a branch and then drop the old branch (in this case, `stable`).

## Actual Result

I now have a `stable` version for the now-deleted tag and a `stable_b` label for the branch. This breaks bookmarks for folks since I default to this branch (and I deleted the tag because RTD kept failing to build, maybe because of #3513 ?).

**Comment by brettcannon** [comment]
FYI I have temporarily turned off which version gidgethub.rtfd.io points to until/if this can be resolved (just in case people trying to diagnose what happened wonder why the site changed).

**Comment by stsewd** [comment]
@brettcannon hi, I think this is because rtd does a `git fetch` before each build, so it can't know if a tag was removed. Did you try wiping the environment? Yo can do this under the `versions` option (edit button).

**Comment by brettcannon** [comment]
Yep, I tried and it doesn't solve it: https://readthedocs.org/projects/gidgethub/builds/6959477/

**Comment by stsewd** [comment]
@brettcannon I can't see the build. Also, you need to rebuild for it takes effect.

**Comment by brettcannon** [comment]
I did and that's the link to the build failure.

**Comment by stsewd** [comment]
@brettcannon I can't see the build, I think is because you change the privacy level of the version, maybe?

**Comment by stsewd** [comment]
The latest build I see is from 4 days ago
![screenshot-2018-3-28 builds read the docs](https://user-images.githubusercontent.com/4975310/38057269-6dbab142-32a4-11e8-9f2b-9bd2a46d1648.png)

Can you try wiping and rebuilding the latest version?

**Comment by brettcannon** [comment]
All the rest of the builds are private since I don't want users stumbling on to outdated docs. Rebuilding the latest version (which is tied to `master`) built find, but I still have a `stable` version which won't build and a `stable_d` version which is tied to the actual `stable` branch.

**Comment by stsewd** [comment]
@brettcannon can you try deactivating that version (no changing the privacy)? Then wipe and rebuild all your versions.

**Comment by brettcannon** [comment]
I've tried various approaches to deactivation and such and that doesn't seem to quite fix it.

**Comment by stsewd** [comment]
@brettcannon please see https://github.com/rtfd/readthedocs.org/issues/3887#issuecomment-377848380 for more information

**Comment by brettcannon** [comment]
@stsewd thanks for the info. I can just live with being off the master (good motivation to make releases more frequently 😉 ).

**Comment by humitos** [comment]
@stsewd could you add a test case for this issue in #3913 also?

Besides the issue that you are reporting here, I think it's very bad UX to show things like `develop` (tag) and `develop_b` (branch). I understand that this is because the `slug` can't be repeated, but we should show to the user something nicer like `develop (tag)` and `develop (branch)` or similar.

**Comment by stsewd** [comment]
Not sure if I understand the steps here, @brettcannon you create a tag named `stable` and then a branch named `stable`?

**Comment by stsewd** [comment]
@brettcannon thanks for the clarification, that is the actual bug that #3913 is going to fix. When you create a custom `stable` tag/branch, rtd doesn't update the stable version automatically (even removing that tag/branch), the current solution is to recreate the project. Hope to fix this before you need to take such action.

**Comment by brettcannon** [comment]
@stsewd thanks for the info! I've just started pointing people at `latest`/`master` as the project is very stable at this point, so there's no major issue on my end to force a complete project recreation.

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/pull/3913/ was merged and released, this should be fixed by re-building another version that isn't stable (that way the versions are refreshed). Let me know if you still have this problem to reopen the issue.
