### ISSUE TITLE
Stable versions are broken

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3842]
For instance: http://readthedocs.org/projects/docs/builds/6938938/

**Comment by stsewd** [comment]
Related issues https://github.com/rtfd/readthedocs.org/issues/3841, https://github.com/rtfd/readthedocs.org/issues/3837

**Comment by humitos** [comment]
Previous `stable` passing is this one: http://readthedocs.org/projects/docs/builds/6933018/

Note that the only difference is that now the `git checkout` command is adding the `origin/` to the commit. Guessing, I would say that maybe some output has changed between Git 1.9 and Git 2.7.4 that was upgraded with the Ubuntu upgrade (a couple of days ago). Not sure, anyway.

**Comment by stsewd** [comment]
@humitos I think it is due the git upgrade, on my local instance I can't reproduce this. But the checkout commands are different

![screenshot-2018-3-24 cice-consortium cice read the docs](https://user-images.githubusercontent.com/4975310/37859813-e53ba4e4-2ee7-11e8-9866-3f33f4e98da3.png)
![screenshot-2018-3-23 test-build read the docs](https://user-images.githubusercontent.com/4975310/37859814-e8799512-2ee7-11e8-9cbb-00733d1250d0.png)

**Comment by stsewd** [comment]
Now I was able to reproduce this on my local instance with this project https://github.com/irmen/Pyro4

![screenshot-2018-3-23 pyoro read the docs](https://user-images.githubusercontent.com/4975310/37860022-8e0702be-2eeb-11e8-886a-408427782a20.png)

**Comment by stsewd** [comment]
Found it!

The error is here

https://github.com/rtfd/readthedocs.org/blob/f3c0c0aa33c6017951b900e540d61ef36ea71d4e/readthedocs/vcs_support/backends/git.py#L250-L252

This is because before `code` was the original `exit_code` of the command, but after #3831(I think) the original `exit_code` is lose. This is something I was wondering while writing tests on https://github.com/rtfd/readthedocs.org/pull/3764#issuecomment-375827453

**Comment by humitos** [comment]
Just a note for next week.

We should be careful with all the `record_as_success` that use the exit code to decide something.

**Comment by agjohnson** [comment]
Tags and stable are working again. Closing.

**Comment by stsewd** [comment]
@agjohnson other projects still has this issue, can be tracked on https://github.com/rtfd/readthedocs.org/issues/3837 anyway.
