### ISSUE TITLE
How to add custom font in the rtd project (no local)?

### ISSUE THREAD

**Issue by Legolasindar** [rtfd/readthedocs.org#3845]
## Details

* Project URL: https://readthedocs.org/projects/1ra-manual-dentrenament-basic-de-combat/
* Build URL (if applicable): https://readthedocs.org/projects/1ra-manual-dentrenament-basic-de-combat/
* Read the Docs username (if applicable): Legolasindar

Sorry, i search in the oficial web, in google, in reddit, and others, but i cant found the solution for my problem, and i cant find any oficial way to contact with a support of readthedocs web.

My knowledge of html, css, github and others thinks are poor.
I created a project in the RTD web (https://readthedocs.io), and linked to Github repository (https://github.com/CavallersDelCel/1RA_EBC).

For my project, i need to add custom font LinBiolinum_Kah.ttf.

I cant found the system for do adding custom fonts (and others things)

Some information speak about conf.py files, and others, but the RTD web no create this files and directories in my github project.

What am I doing wrong?

Thanks

**Comment by stsewd** [comment]
Maybe with this https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html? So you can add a css with the custom font (from the `_static` folder or from the internet)

**Comment by Legolasindar** [comment]
Thanks but, the RTD creates conf.py, but not in my git repository. I cant found this file in anyway.
All documentation of RTD speak about local linux install RTD, but never about uses RTD web.
I not understand how extrat the conf.py and other to put in my git project.

**Comment by stsewd** [comment]
@Legolasindar when you create a sphinx project the `conf.py` file is created automatically, then RTD uses that file and add additional information. You can read https://docs.readthedocs.io/en/latest/getting_started.html#in-restructuredtext

**Comment by Legolasindar** [comment]
But im not have linux. I not uses commands $ pip install sphinx sphinx-autobuild or something.
Im only creates .rst files (index and pages) in the Github.

**Comment by stsewd** [comment]
@Legolasindar when you don't do a sphinx project RTD install it before building your docs, RTD uses sphinx to build your rst docs. So, to be able to use the custom font, you need to init a sphinxs project so you are able to configure it. Sphinx is multiplatform, you can run that command on Windows' cmd too, you can try this `python -m pip install ...` if the other command doesn't work.

**Comment by Legolasindar** [comment]
Ok i maked all, but the text no get custom font. I set in the conf.py

```
def setup(app):
    app.add_stylesheet('css/custom.css')
```

I created custom.css with:

```
@font-face {
    font-family: "Linux Biolinum Keyboard";
    src: url("../fonts/LinBiolinum_Kah.ttf");
}

.keys
{
  font-family: "Linux Biolinum Keyboard", sans-serif;
}
```

And in a one rst page i put:

`<span class="keys">F 0 M</span>` 

Buts this code appear in flat text.

What im doing wrong?

**Comment by stsewd** [comment]
Can you provide a link to the full file?

**Comment by Legolasindar** [comment]
This is the index.rst, you can see the code below the image.
[https://github.com/CavallersDelCel/1RA_EBC/blob/master/docs/index.rst](url)

**Comment by stsewd** [comment]
I can see that your css and font are on the server and on the page

![selection_003](https://user-images.githubusercontent.com/4975310/37987846-f432d370-31c4-11e8-8dc4-336b73ab84c1.png)

- http://1ra-manual-dentrenament-basic-de-combat.readthedocs.io/ca/master/_static/fonts/LinBiolinum_Kah.ttf
- http://1ra-manual-dentrenament-basic-de-combat.readthedocs.io/ca/master/_static/css/custom.css

So, probably there is something wrong with the css code.

**Comment by Legolasindar** [comment]
Reviewing the code it seems that everything is fine.
But it's like RTD is not able to read HTML tags.

**Comment by stsewd** [comment]
@Legolasindar here is the error

```
src: url(../fonts/LinBiolinum_Kah.ttf);
```

The url should be inside quotes

```
src: url("../fonts/LinBiolinum_Kah.ttf");
```

**Comment by Legolasindar** [comment]
At first I had it with quotes, but it did not work either, I just removed the quotes in the last build.

I have this [stackoferflow](https://stackoverflow.com/questions/49530807/custom-font-with-css-not-work-in-sphinx-project) opened. The first answer work, but i need this work betwen text, not alone.

**Comment by stsewd** [comment]
I didn't note that you were using `<span class="keys">FM</span>`, yeah you should use the `raw` directive.

I just answered your question on stackoverflow so other people can see it. You need to use a custom role http://docutils.sourceforge.net/docs/ref/rst/roles.html#raw

So, this isn't a RTD problem.

**Comment by stsewd** [comment]
@Legolasindar thanks for letting us know. I'm closing this issue then.
