### ISSUE TITLE
Better Error Reporting on the Build Detail Page

### ISSUE THREAD

**Issue by bramwelt** [rtfd/readthedocs.org#385]
Build detail pages are a jumbled mess. It is generally hard for new users for RTD to grok the logs on the page and find the specific error that is making their build fail. It'd be nice to have links to each section of the page colored depending on the number of errors present.  

* Blue: 'No errors or warnings'
* Yellow: 'Some warnings or possible errors' (This includes \hbox overflows for LaTeX). 
* Red: 'Congratulations, you got ALL the errors!'.

When I have some time I'm going to do some simple templating/css hacking to show everyone a better idea of how this would look.

Please let me know if you have any feedback!

**Comment by ericholscher** [comment]
This is now done :)
