### ISSUE TITLE
Build process failing on autodoc

### ISSUE THREAD

**Issue by Themanwithoutaplan** [rtfd/readthedocs.org#3851]
## Details

* Project URL: http://openpyxl.readthedocs.io/en/latest/index.html
* Build URL (if applicable): https://readthedocs.org/projects/openpyxl/builds/6944717/
* Read the Docs username (if applicable): 

## Expected Result

The docs to be be buildt

## Actual Result

*A description of what actually happened*
```
Exception occurred:
  File "conf.py", line 272, in run_apidoc
    from sphinx.ext.apidoc import main
ImportError: No module named 'sphinx.ext.apidoc'
```
The full traceback is available at the build. I don't know why the exception is being raised. I can't replicate it locally and I have a dedicated tox environment for building docs, though the configuration is slightly different. It looks like this is an RTD-specific failure but if it's something to do with the way I've set things up I'd love to know.

**Comment by stsewd** [comment]
Did you tested it with `sphinx==1.6.5`? That is the sphinx version that rtd uses. You can use a mayor version by putting it on a requirements file.

> Incompatible changes
> 1.7.0b1
> ...
> #3929: apidoc: Move sphinx.apidoc to sphinx.ext.apidoc

From the changelog

https://github.com/sphinx-doc/sphinx/pull/3929/

**Comment by Themanwithoutaplan** [comment]
When testing locally with the same setup as RTD I get Sphinx 1.6.5 but I don't get the exception. This isn't surprising seeing as the import already reflects the change in packaging.

**Comment by stsewd** [comment]
@Themanwithoutaplan This is from a virtualenv with sphinx 1.6.5

```python
>>> import sphinx
>>> import sphinx.ext.apidoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sphinx.ext.apidoc'
>>> sphinx.__version__
'1.6.5'
>>> import sphinx.apidoc
>>> 

```

**Comment by Themanwithoutaplan** [comment]
It seems the import is the problem. Adding a `try…except` resolves it.

**Comment by RichardLitt** [comment]
Thanks for letting us know, @Themanwithoutaplan!

**Comment by Themanwithoutaplan** [comment]
Of course, it would be really nice if we didn't have to shoehorn APIDOC support into RTD like this.
