### ISSUE TITLE
Reduce logging to Sentry

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3856]
We're error logging a number of things that shouldn't be error logs. This pollutes Sentry with a number of issues that aren't really our issue (build failures on pip/etc). We should clean up our logging here to reduce noise and get back to a reasonable number of logging events.

**Comment by humitos** [comment]
Maybe this setting can be used to do not log known exceptions to Sentry on Celery tasks:

https://docs.sentry.io/clients/python/integrations/django/#additional-settings

**Comment by humitos** [comment]
http://docs.celeryproject.org/en/latest/userguide/tasks.html#Task.throws
