### ISSUE TITLE
Docs build fails with "One or more submodule URLs are not valid."

### ISSUE THREAD

**Issue by bramwelt** [rtfd/readthedocs.org#3857]
## Details

* Project URL: http://opnfvdocsdemo.readthedocs.io/
* Build URL (if applicable): First failure: http://readthedocs.org/projects/opnfvdocsdemo/builds/6933536/, Error message seen: http://readthedocs.org/projects/opnfvdocsdemo/builds/6940325/
* Read the Docs username (if applicable): opnfv-rtd

## Expected Result

Given our [.gitmodules](https://git.opnfv.org/opnfvdocs/tree/.gitmodules) file, the build succeeds.
The last change to our .gitmodules file was 8 days ago (March 19th).

## Actual Result

An error:
> One or more submodule URLs are not valid.

is displayed and the build fails.

**Comment by agjohnson** [comment]
I forgot to follow up here. This fix went live on monday, so issues with relative submodule urls should be resolved.
