### ISSUE TITLE
build error told me to report it

### ISSUE THREAD

**Issue by samuelstjean** [rtfd/readthedocs.org#3858]
## Details

* Project URL: https://nlsam.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/nlsam/builds/6948069/
* Read the Docs username (if applicable): samuelstjean

## Expected Result

It worked on my random test branch

## Actual Result
It does not work once it was merged to master

*A description of what actually happened*

it just spits out this scary looking error after doing cat conf.py 

+ There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (6948069).

**Comment by samuelstjean** [comment]
That's, eh, peculiar. It did use to work on the single branch I was using to check if it was rendering correctly before though weirdly enough, it's giving me a bunch of trouble on C extension.

Is there anything I can do for the next time to avoid cryptic error codes? Or is there a way to figure out the problem? Going through the build logs did not seem to indicate anything useful regarding memory unfortunately (and it works locally obviously).

**Comment by stsewd** [comment]
@samuelstjean see https://github.com/rtfd/readthedocs.org/issues/3613

**Comment by samuelstjean** [comment]
I cleaned up the whole environment and now it's pseudo working, so good enough for me, thanks.
