### ISSUE TITLE
Changing the repository URL in project setting does not update the "Edit on Github" link on top right 

### ISSUE THREAD

**Issue by Vafa-Andalibi** [rtfd/readthedocs.org#3863]
## Details

* Project URL: Cxhttp://cxsystem.readthedocs.io/en/master/
* Build URL (if applicable): 
* Read the Docs username (if applicable): 

## Expected Result

I have updated the project github URL in the setting, the new build is fine and is using the new URL, but the "edit on github" link on top right is still redirecting to the old repository. 

## Actual Result

The "Edit in Github" should redirect me to the new (changed) github url.

**Comment by Vafa-Andalibi** [comment]
yes, the build is with the new repo . The links in ReadtheDocs bar (lower left) that has the "On Github" section are fine, but not the link on top right .

**Comment by stsewd** [comment]
@Vafa-Andalibi did you try wiping the environment? You can do this on the `versions` section (edit button)

**Comment by Vafa-Andalibi** [comment]
Worked like a charm :) thanks ! 

Just one more thing really quick, can I have that project transferred to my other account? 
From this account: 
REte7fXsNqgoutJPVOriDw
to this one:
VisualNeuroscience-UH

**Comment by stsewd** [comment]
If you are the owner of the project, I think you just need to add your other account as maintainer (`admin` section).

**Comment by Vafa-Andalibi** [comment]
Thank you !
