### ISSUE TITLE
build fails when pip installing dependency

### ISSUE THREAD

**Issue by jpchen** [rtfd/readthedocs.org#3865]
## Details

* Project URL: http://docs.pyro.ai/en/docs-upgrade/
* Build URL: https://readthedocs.org/projects/pyro-ppl/builds/6953678/

i am trying to install a python library (pytorch) from a wheel i have hosted on an s3 server. i have an [install script](https://gist.github.com/jpchen/32325c3e9c9944947dd3f6f1586c5829) that i run which has been tested separately. upon fixing rtd specific build problems, the build now errors during the build process when running the command:
```python /home/docs/checkouts/readthedocs.org/user_builds/pyro-ppl/envs/docs-upgrade/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html```

the conf.py file (i am using sphinx) has the following relevant lines:
```
os.system('curl -o install.sh https://gist.githubusercontent.com/jpchen/32325c3e9c9944947dd3f6f1586c5829/raw/77d6208778da7568b50738a8acc57307a2e069a5/tst.sh')
os.system('bash install.sh')
os.system('rm -f install.sh')
```

**Comment by stsewd** [comment]
@jpchen hi, why did you close the issue? Were you able to solve the problem?

**Comment by jpchen** [comment]
not really, but i did a workaround, and figured it wasnt worth your time deep diving into it.
what would be really helpful though is to output the immediate commands leading up to the error. if a command errors, that entire command and its output is not outputted in the build log and it becomes hard to debug.

**Comment by RichardLitt** [comment]
Interesting. I am going to reopen this until someone from core can look at that suggestion, just to make sure this doesn't get lost because it's in a closed issue. Core person: feel free to close this or open a new issue for logging if you think that makes sense!

**Comment by stsewd** [comment]
I have opened an issue for that in https://github.com/rtfd/readthedocs.org/issues/4288
