### ISSUE TITLE
Cannot delete a project

### ISSUE THREAD

**Issue by jychoi-hpc** [rtfd/readthedocs.org#3866]
## Details

* Project URL: https://readthedocs.org/projects/adios-python/
* Build URL (if applicable):
* Read the Docs username (if applicable): 

## Expected Result

I am trying to delete the above project but cannot.

## Actual Result

When I pressed the "delete forever" button, I got the following error:
```
Fail.  Check back in a bit!
```

**Comment by davidfischer** [comment]
Thanks for reporting this. I am investigating.

**Comment by davidfischer** [comment]
This is definitely a bug. Thanks again for reporting and there should be a fix shortly.

**Comment by ericholscher** [comment]
Deploy should be going out to fix this in the next hour.

**Comment by masterandrey** [comment]
I cannot delete project
https://readthedocs.org/dashboard/tregexpr/delete/
