### ISSUE TITLE
Build failing and suggesting we contact you

### ISSUE THREAD

**Issue by tannewt** [rtfd/readthedocs.org#3867]
Please let us know what we can do to get it back going. Thanks!

## Details

* Project URL: https://readthedocs.org/projects/circuitpython/
* Build URL (if applicable): https://readthedocs.org/projects/circuitpython/builds/6954985/
* Read the Docs username (if applicable): 

## Expected Result

The project to build. We build it successfully with Travis: https://travis-ci.org/adafruit/circuitpython

## Actual Result

The build fails with:

```
There was a problem with Read the Docs while building your documentation. Please report
this to us with your build id (6954985).
```

**Comment by stsewd** [comment]
Seems related to #3842, I going to take a deeper look to the code to confirm.

**Comment by tannewt** [comment]
Thanks @stsewd !

**Comment by stsewd** [comment]
So, It looks like there is a problem with this submodule 

https://github.com/adafruit/circuitpython/blob/6711c5c90d497ce68ea1df249d36b32bdf2f4c6c/.gitmodules#L36-L38

Now RTD is using `GitPython` to check submodules (before, it simply executed git commands and parsed the output).

Your submodule `freetouch2` is not found by `GitPython`, and also if I run `git submodule status` it doesn't appear.

```
$ git submodule status 
 39f28ed4e0e5a06fc33fd01c1efc8c52c4140f03 frozen/Adafruit_CircuitPython_BusDevice (0.3.1)
 fa00b61d1bde90c3cf9cce74388cb9717058b2be frozen/Adafruit_CircuitPython_LIS3DH (0.1.2-3-gfa00b61)
 1142f1c7fdc232a46d74dd4f1946a5f462ae2555 frozen/Adafruit_CircuitPython_NeoPixel (1.0.0-rc.1)
 2d57c0ba9a09d6d30f0ae2b98aba9567c25e6fb6 frozen/Adafruit_CircuitPython_Thermistor (0.1.2)
 dac9176cac58cc5e49669a9a4d404a6f6dd7cc10 lib/axtls (heads/master-36-gdac9176)
 35aaec4418ad78628a3b935885dd189d41ce779b lib/berkeley-db-1.xx (remotes/origin/embedded)
 e9de7e35f2339598b16cbb375f9992643ed81209 lib/libffi (v3.2.1-146-ge9de7e3)
 5b8b5d459e7dd890724515bbfad86c705234f9ec lib/lwip (STABLE-1_4_1-RC1-13-g5b8b5d45)
 d48561b07386132b849d0125b0ff6a532d833d8b lib/nrfutil (heads/master)
 d2bcfda543d3b99361e44112aca929225bdcc07f lib/stm32lib (F4-1.16.0+F7-1.7.0+L4-1.8.1-7-gd2bcfda)
 aaa0f428111fbea7d56ab548053b11c9f12068f1 ports/atmel-samd/asf4 (remotes/origin/circuitpython)
 2001c62d1a0361c44acc7076d8ce91e1d1c66141 tools/python-semver (2.7.8-4-g2001c62)
 449f26673855736dbc0fc3f18d72403f25f62974 tools/uf2 (449f266)
 a04341153b41b4728f9b42a77cbd51c495362287 tools/usb_descriptor (heads/master)
```

I don't know much about git submodules, but I notice that your submodule doesn't have the same name as the path (all others have this), maybe that's the problem?

**Comment by tannewt** [comment]
I didn't think the name mattered. I'll poke at it. Its not working correctly for me here either. Thanks!

**Comment by tannewt** [comment]
I had accidentally checked in files in the spot where the submodule was supposed to be. The build is going again after this fix: https://github.com/adafruit/circuitpython/pull/724/commits/19b0b414e6091f75991be178f0ff2accd6e11124

Thanks for the help debugging!
