### ISSUE TITLE
 Support request: View Docs button redirect to localhost on local running instance.

### ISSUE THREAD

**Issue by uncelvel** [rtfd/readthedocs.org#3871]
## Details 

I have been Install a local RTD but when using View Docs that redirect to localhost not be a Hostname i have been config of config file before. So that's issue i fillter have not in issue before.  Or i missing some where?. 

![](https://i.imgur.com/EkmEiya.png)

## Expected Result
Click to ViewDocs button that redirect to http://**hostname**:8000/doc/pj/en/latest not a http://**localhost**:8000/doc/pj/en/latest

**Comment by agjohnson** [comment]
You likely need the `PUBLIC_DOMAIN` setting

**Comment by stsewd** [comment]
@uncelvel please check Anthony's solution and tell us if that works.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
