### ISSUE TITLE
"View docs" from build detail page link is wrong

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3879]
When a build is completed a "View docs" link is shown

![captura de pantalla_2018-03-29_18-22-35](https://user-images.githubusercontent.com/244656/38118098-2a19358c-337e-11e8-868e-fc70ea0f45e4.png)

https://github.com/rtfd/readthedocs.org/blob/adb5392c47a1b3fe506524d898dd147b038d4140/readthedocs/templates/builds/build_detail.html#L57-L64

This link points to `/project/version/latest/` because the `get_absolute_url` is called **before** the Version is built and uploaded:

https://github.com/rtfd/readthedocs.org/blob/adb5392c47a1b3fe506524d898dd147b038d4140/readthedocs/builds/models.py#L154-L166

cc @stsewd

**Comment by stsewd** [comment]
Sorry, I missed that :/ I going to see if the link can be retrieved from the API or can be formed with some predefined information.
