### ISSUE TITLE
Feedback/logging for build performance analysis

### ISSUE THREAD

**Issue by mars1026** [rtfd/readthedocs.org#3884]
## Details

* Project URL: http://www.github.com/plaidml/plaidml/
* Build URL (if applicable): https://readthedocs.org/projects/plaidml/builds/6965966/
* Read the Docs username (if applicable): vertexai

## Expected Result

The sphinx build takes 47 seconds on my unremarkable dev laptop, using a clean virtualenv using only the packages linked from docs/requirements.txt, so I expected that readthedocs.org would be able to build the docs and publish them.

## Actual Result

Each build spins away for 15-16 minutes before timing out.  The last entry in the log is `cat docs/conf.py` which is obviously not something that is going to take a lot of time, so presumably there is some other task following it which is failing and not being logged.

I am happy to work on the system to do whatever needs to happen to make the build run faster, however I have no idea where to start. I can't find any logs or profiling options or performance optimization suggestions. I don't know whether something in the build is getting stuck and running forever, or whether there is some part of the process which runs much more slowly on the RTD server for some reason. Is there anything I can do to get some feedback about what's going on?

**Comment by agjohnson** [comment]
It's not clear that it's happening, but the last command to complete is the `cat conf.py` step. The command that is failing (and not displayed as running yet) is the first pass at a Sphinx build. Do you get similar results running a full build (make clean; make html)?

**Comment by stsewd** [comment]
I think a related problem here is the user not able to see what command has failed. I'll try to see why is this happening (I think the command is only recorded after it is executed only, and due being killed by timeout isn't saved).

**Comment by stsewd** [comment]
We migrate to Azure recently, the build process is a little faster, can you check if your docs can be built now?

**Comment by stsewd** [comment]
I just trigger a new build, but it's failing because of another problem, feel free to reopen if you are still seeing the timeout problem.

I also opened https://github.com/rtfd/readthedocs.org/issues/4288 for the other issue commented here.
