### ISSUE TITLE
`basic` attribute not used on `trigger_build`

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3888]
While debugging a unrelated different thing, I found that the attribute `basic` is not used at all when calling `trigger_build`.

https://github.com/rtfd/readthedocs.org/blob/7aa6f4d41acbc8b35b7f2b891496ae0ded9f68f8/readthedocs/core/utils/__init__.py#L101

I don't know what this was useful for (I didn't check the git log yet) but it's something that we can probably remove for cleanness.

**Comment by stsewd** [comment]
This was removed on https://github.com/rtfd/readthedocs.org/pull/1580/files#diff-b9399e1d3499066c5564f98a620e8881L95 in https://github.com/rtfd/readthedocs.org/pull/1580

Looks like this was never used :thinking:
