### ISSUE TITLE
Trigger a build and wipe the same version

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3891]
I just realize that if you Trigger a Build on Version `N` and then go to the `N` Version details page and Wipe the version, you will be allowed to wipe it but you will get a weird error on the build.

![captura de pantalla_2018-04-02_19-10-25](https://user-images.githubusercontent.com/244656/38222303-86d27d1e-36a9-11e8-8722-ab223e2efe6d.png)

Not sure what is the solution here, but I wanted to create the issue to track this "problem".

**Comment by stsewd** [comment]
Is this really a problem? To me, this seems "normal". If I wipe the build, it's because I want to do a clean build, so, the current builds should stop (or fail).

**Comment by humitos** [comment]
It's not a big problem, but at least the build output page says something completely different to what has happened. I mean, it fails because we removed the files and the error makes no sense.

That, at least, will confuse the users.
