### ISSUE TITLE
500 when processing project.description via restructuredtext tag filter

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3892]
Accessing https://readthedocs.org/projects/pydbgen/ you will get a 500.

The error happen because the title overline is not accurate:

```
SystemMessage: <string>:1: (SEVERE/4) Title overline & underline mismatch.

****************************************
Random database/dataframe generator
***************************************
```

The important code sections.

Template:

https://github.com/rtfd/readthedocs.org/blob/393e31ad3a9aafee297df64f1a654ffcda7ef04a/readthedocs/templates/core/project_details.html#L79-L83

Python code:

https://github.com/rtfd/readthedocs.org/blob/393e31ad3a9aafee297df64f1a654ffcda7ef04a/readthedocs/core/templatetags/core_tags.py#L45-L71

There is no feedback at all saying what's the error. Possible solutions:

* should fail silently, show the raw description and communicate the user with a message or
* do not parse it via restructuredtext at all

**Comment by davidfischer** [comment]
I made a small edit as this issue was referencing my fork of RTD.
