### ISSUE TITLE
Valid webhook

### ISSUE THREAD

**Issue by robbert-harms** [rtfd/readthedocs.org#3903]
## Details

* Project URL: https://readthedocs.org/projects/mdt-toolbox/
* Build URL (if applicable): https://mdt-toolbox.readthedocs.io/en/latest_release/
* Read the Docs username (if applicable): 

## Expected Result

Getting the automatic webhook to Github working again.

## Actual Result

I recently deleted a project from ReadTheDocs because I wanted to change the URL to a different name. Ever since, the automatic building from GitHub no longer works. I removed and added again the webhook at Github, but to no avail. 

What to do to make RTD follow the github repository again?

**Comment by stsewd** [comment]
Do you also remove the webhook from read the docs (`Integrations` on the admin section)?

**Comment by stsewd** [comment]
Are you still having this problem? You can also try setting the webhook manually https://docs.readthedocs.io/en/latest/webhooks.html

**Comment by robbert-harms** [comment]
Thanks! This solved the issue for me.

**Comment by stsewd** [comment]
Thanks for the update!
