### ISSUE TITLE
Build fails - id 6997054

### ISSUE THREAD

**Issue by avanobberghen** [rtfd/readthedocs.org#3911]
## Details

* Project URL: https://readthedocs.org/projects/openimis/
* Build URL (if applicable): https://readthedocs.org/projects/openimis/builds/6997054/
* Read the Docs username (if applicable): openimis

## Expected Result

I'm trying to generate documentation from GitHub. I have a "docs" folder, a index.rst and a conf.py in my repository, and I can generate the (html) documentation locally with Sphinx, but the build fails on RTD.
The webhook on GitHub seems ok too.

## Actual Result

The build fails at this stage, but can't see any specific error:

git remote set-url origin https://github.com/openimis/master-version.git
git fetch --tags --prune
git checkout --force origin/master
git clean -d -f -f
git show-ref --tags
git branch -r
python2.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/openimis/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/openimis/envs/latest/bin/pip install --use-wheel --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/openimis/.cache/pip Pygments==2.2.0 setuptools==37.0.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.6.5 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
cat docs/conf.py

**Comment by stsewd** [comment]
I was able to build your docs on my local instance, can you try building again?

**Comment by avanobberghen** [comment]
Thanks for the support. I can also build them locally, but it fails on ReadTheDocs. I just tried again. Any clue?
![capture](https://user-images.githubusercontent.com/9592467/38559626-ce0522d8-3cd3-11e8-85ba-19971209e040.PNG)

**Comment by humitos** [comment]
I took a look at Sentry errors and I didn't find anything useful yet. At first sight it doesn't seems a problem with your repository, but I will need to research a little more to know what has happened.

**Comment by stsewd** [comment]
@avanobberghen your latest builds are successful, was your problem solved?

**Comment by avanobberghen** [comment]
Hi, yes, it's solved. I changed some contents in the .rst. Seems to work.
Thanks.
