### ISSUE TITLE
Add some rule based features around versioning and tags

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3914]
We already pin stable to the latest release version, but it would be interesting to have some rules around activating new versions as they come in as well. Some ideas for rules users could add:

* Automatically activate `M` major versions and `N` minor versions
* Don't activate beta releases
* Don't activate based on regex
* Activate based on regex (user provided regex could be a DOS attack vector, so not sure on this)
* Activate based on regex-ish rule

**Comment by humitos** [comment]
I remember there was a similar issue reported by a user saying like they want to auto build new releases instead of going to RTD and activate them. I can't find it at the moment. Maybe there are more info/context/useful info there.

**Comment by humitos** [comment]
Closing in favor of #4001
