### ISSUE TITLE
The localization dropdown incorrectly refers to "Taiwanese"

### ISSUE THREAD

**Issue by Strangehill** [rtfd/readthedocs.org#3917]
"Taiwanese" is a different language, the term used in the dropdown is more commonly and accurately referred to as "Traditional Chinese".

**Comment by davidfischer** [comment]
Seems an easy enough change. Based on [Django's master setup](https://github.com/django/django/blob/5b589a4/django/conf/global_settings.py#L139-L140) it seems they use "Traditional Chinese" and "Simplified Chinese".
