### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by drewejohnson** [rtfd/readthedocs.org#3919]
## Details
Attempting to build a tagged version of a project using the `stable` build, and I received the following error:

  > There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7003827).

I noticed the project wasn't auto-triggering the stable build after the tag, but the latest and develop branch are contain the updated project code. I got this error after manually triggering the build

* Project URL: http://serpent-tools.readthedocs.io/en/latest/?badge=latest
* Build URL (if applicable): https://readthedocs.org/projects/serpent-tools/builds/7003827/
* Read the Docs username (if applicable): andrewjohnson

## Expected Result

Build the stable branch for the tag

## Actual Result

The build failed to auto update the stable build and failed during a manual trigger.

Thank you! :smile:

**Comment by humitos** [comment]
It seems it was a random failure.

All of your following builds worked properly. Even `stable`.

I didn't find any relevant issue with this that we can debug.

**Comment by drewejohnson** [comment]
Sure enough, the tagged builds and stable builds have gone through :man_shrugging:

**Comment by RichardLitt** [comment]
Weird. Reopen if it happens again. Thanks for logging, anyway!
