### ISSUE TITLE
Flaky build environment, AttributeError: _ep_map

### ISSUE THREAD

**Issue by Artanicus** [rtfd/readthedocs.org#3924]
## Details

* Project URL: https://readthedocs.org/projects/python-cozify
* Build URL (if applicable): https://readthedocs.org/projects/python-cozify/builds/7006253/ vs. https://readthedocs.org/projects/python-cozify/builds/7006257/
* Read the Docs username (if applicable): Artanicus

## Expected Result
Build either passes or fails consistently.

## Actual Result
Build success seems random and every time it fails with the same error:
```
Running setup.py develop for cozify
Exception:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-cozify/envs/devel/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2636, in get_entry_map
    ep_map = self._ep_map
  File "/home/docs/checkouts/readthedocs.org/user_builds/python-cozify/envs/devel/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2607, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map
```

Wiping the build environment does not help and it's not just flaky from commit to commit but actually flaky with the same commit (auto-triggered vs. manually triggered). These are both builds of the same commit:
https://readthedocs.org/projects/python-cozify/builds/7006253/
https://readthedocs.org/projects/python-cozify/builds/7006257/

**Comment by Peque** [comment]
Same here. Seems to fail randomly and quite frequently. A couple of logs that failed in the last couple of hours:

- https://readthedocs.org/projects/mmsim/builds/7041587/
- https://readthedocs.org/projects/mmsim/builds/7041583/
- https://readthedocs.org/projects/mmsim/builds/7041522/
- https://readthedocs.org/projects/mmsim/builds/7041423/
- https://readthedocs.org/projects/mmsim/builds/7041307/

Rebuilding seems to always end up succeeding at some point.

**Comment by Artanicus** [comment]
This issue seems to be the same one, but failing more consistently: https://github.com/home-assistant/home-assistant/issues/13898

**Comment by stsewd** [comment]
Your latest builds are passing, are you still having problems?

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
