### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by FedeDP** [rtfd/readthedocs.org#3929]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/libmodule/
* Build URL (if applicable): https://readthedocs.org/projects/libmodule/builds/7015103/
* Read the Docs username (if applicable): nierro

## Expected Result
Normal build of my own docs.

## Actual Result
Weird error:

> There was a problem with Read the Docs while building your documentation. Please report this > to us with your build id (7015063).

Note that i did not touch anything related to docs in my linked github repo for that build.

**Comment by stsewd** [comment]
Can you try building your docs again manually? I think this was a temporal problem.

**Comment by FedeDP** [comment]
Fixed thanks!
