### ISSUE TITLE
Show only relevant integrations and automate the setup on Admin

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3936]
When importing a project for a known service (Gitlab/Github/Bitbucket) the webhook/integration is configured automatically.

Then, going to `Admin -> Integrations -> Add integration` you have a dropdown to select between:

* Github
* Bitbucket
* Gitlab
* Generic

I'd say that we should only list _only_ the relevant ones: Generic + the one of the known service for that `Project.repo` URL and I have an account of that service connected.

Also, in case the service connected (and project URL) is Gitlab, if I choose it that webhook option from the list it should be setup the webhook automatically instead of showing something like:

![captura de pantalla_2018-04-10_16-42-56](https://user-images.githubusercontent.com/244656/38588113-c1b5cf62-3ce9-11e8-9b0e-baabd898b4c8.png)

Related to #3932 and also low priority.

**Comment by stsewd** [comment]
What about the people that want to add a webhook to a supported service without connecting their account? Also, wouldn't people think that rtd only supports _that_ provider (the one that is connected to their account)?

**Comment by humitos** [comment]
> What about the people that want to add a webhook to a supported service without connecting their account?

In this case (when the project was not imported from a known service) we should show all the options available.

> Also, wouldn't people think that rtd only supports _that_ provider (the one that is connected to their account)?

Mmm... This makes me think that even importing a using a connected account, I may want to "depend on another" repository (like Bitbucket) and trigger builds when something in that _other_ repo has changed also.

I think this case it's kind of weird, though.

Anyway, we can close this issue as invalid for now.
