### ISSUE TITLE
readthedocs.org build failure with little info

### ISSUE THREAD

**Issue by esoergel** [rtfd/readthedocs.org#3941]
## Details

All recent builds of the docs for [CommCareHQ](https://github.com/dimagi/commcare-hq) have failed, and I don't see any indication of what the issue is.  The docs build fine locally.  Here's what I did locally to attempt to fix or reproduce the failure:

1. Created a new virtualenv and installed only the requirements file specified on readthedocs.org
1. Upgraded to the latest version of Sphinx, sphinx-rtd-theme, and docutils
1. Fix all errors and warnings logged when running `make html` locally
1. Added `django.setup()` to `docs/conf.py`

None of these affected what is being displayed about the build failure.  Notably, our docs are a mix of simple `.rst` files and autodocs generated from source files.  Neither appears to be updating.  Is there somewhere I could see a more complete log of the build to identify where it is failing?

* Read the Docs project URL: https://readthedocs.org/projects/commcare-hq/
* Build URL (if applicable): https://readthedocs.org/projects/commcare-hq/builds/7028354/ (although all recent builds have failed in the same way)
* Read the Docs username (if applicable): Dimagi

## Expected Result

I expect the build to complete successfully, or to show an error message indicating what the issue is.

## Actual Result

I receive this message:

> Error
> There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7028354).

![image](https://user-images.githubusercontent.com/2367539/38693785-f8329e18-3e55-11e8-8e18-1611b2a06af7.png)

**Comment by esoergel** [comment]
Perfect, that did the trick, thanks for your help!  For my own future reference, is there some place else I could've looked to get more info on the failure?  Or reproduction steps to identify that locally?

**Comment by stsewd** [comment]
@esoergel at the moment not really :/ (at least that you run gitpython on your project)

https://github.com/rtfd/readthedocs.org/blob/6bd1c684a3e27172653a306fdc5352d76a7015be/readthedocs/vcs_support/backends/git.py#L78-L86

I'll see if there is a way of catching this error and show a proper message for the build failure.

**Comment by esoergel** [comment]
Okay, thanks, I was able to resolve the other failures myself, and the documentation is building as expected now, so I'm all set.  Thanks again for the prompt assistance.
