### ISSUE TITLE
Use method docstring from abstract base class if derived class has none

### ISSUE THREAD

**Issue by Sraw** [rtfd/readthedocs.org#3942]
## Details

Let's say I have the following two classes

```
# -*- coding: utf-8 -*
import abc


class Superclass(object):
    """The one to rule them all"""

    @abc.abstractmethod
    def give(self, ring):
        """Give out a ring"""
        pass


class Derived(Superclass):
    """Somebody has to do the work"""

    def give(self, ring):
        print("I pass the ring {} to you".format(ring))
```

## Expected Result

The docstring of `Derived.give` should be inherited from `Superclass.give`.

Which means it should be "Give out a ring".

## Actual Result

It is none.

## Some workground

Actually, it works in the latest sphinx.

See this comment: https://github.com/sphinx-doc/sphinx/issues/3140#issuecomment-323145028

**Comment by stsewd** [comment]
Can you provide more information? Your project url, requirements file, etc.


You can use the sphinx version that you want by putting it on your requirements file

**Comment by Sraw** [comment]
My project url is here: https://github.com/Sraw/nswebdav

And the requirements file is here: https://github.com/Sraw/nswebdav/blob/master/docs/requirements.txt

Here is the related method: http://nswebdav.readthedocs.io/en/stable/source/nswebdav.html#nswebdav.async.AsyncNutstoreDav.close

Since this method is inherited from a base class, its docstring should also be inherited from that base class. But as you can see, there is nothing.

I have tested it with sphinx, and it works like a charm.

According to this pull request: https://github.com/sphinx-doc/sphinx/pull/4012

This feature is already be implemented on sphinx 1.7.

Or should I manually add `sphinx==1.7.0` to requirements.txt file?

**Comment by stsewd** [comment]
@Sraw yes, you need to add the sphinx version on your requirements file, RTD installs `sphinx==1.6.5` by default.

You can also have another requirement file just for rtd if that is a problem for your project.

**Comment by Sraw** [comment]
Works.

Sincerely, I recommend to upgrade RTD's sphinx. This feature is really useful.
