### ISSUE TITLE
please someone that can guide me step by step to publish a word in readthedocs 

### ISSUE THREAD

**Issue by ElishaBentzi** [rtfd/readthedocs.org#3949]
## Details

* Read the Docs project URL: mutualwelfare.org
* Build URL (if applicable): E-Nation.org
* Read the Docs username (if applicable):  Elisha

## Expected Result
Someone that can help me, to publish my word document in readthedocs

The document is in spanish and english  
this is the spanish version: [https://docs.google.com/document/d/19S9JwXFvIP0jkWouiiI0xwLCT8Q2-_VBc6q7N_-m-kk/edit#heading=h.47ipec7c13r8](url)

Thanks
## Actual Result

*A description of what actually happened*

I talk to someone if can help us to publish our document in readthedocs, but fail to do the task.

**Comment by RichardLitt** [comment]
Hey @ElishaBentzi. I'm not sure of your use case - why do you want this document to be on Read the Docs? Are you looking to host the content somewhere? 

Read the Docs only has two options for documentation formats - [reStructured text or Markdown](https://docs.readthedocs.io/en/latest/getting_started.html). Could you perhaps convert your doc into Markdown in a GitHub repository, and use that to [quickstart a Read the Docs page?](https://github.com/rtfd/readthedocs.org#quickstart-for-github-hosted-projects)

**Comment by RichardLitt** [comment]
Ok, that makes a bit more sense. Good luck converting it to Markdown, and then onto Read the Docs. 

I think the quickstart guide will help you. For now, this issue isn't a bug or an issue with Read the Docs, so I am going to close it. You can read more about our reasoning for keeping support-like questions off of GitHub [here](https://docs.readthedocs.io/en/latest/support.html). A good place to go for questions like yours, above, is StackOverflow. Good luck.
