### ISSUE TITLE
Support Python 3.6 interpreter

### ISSUE THREAD

**Issue by d2207197** [rtfd/readthedocs.org#3950]
## Details

* Read the Docs project URL: http://carriage.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/carriage/builds/7042295/
* Read the Docs username (if applicable): d2207197

## Expected Result and Actual Result

My project is Python 3.6 only, while currently readthedocs provides only Python 3.5.
`sphinx.ext.autodoc` failed due to Python 3.6 up syntax, like f-string.

```py
File "/home/docs/checkouts/readthedocs.org/user_builds/carriage/envs/latest/lib/python3.5/site-packages/carriage-0.2.6-py3.5.egg/carriage/array.py", line 285
    return f'{type(self).__name__}({short_repr.repr(self._items)})'
                                                                  ^
SyntaxError: invalid syntax
```

**Comment by stsewd** [comment]
Feel free to reopen if that doesn't solve your issue.

Also, here is an example of a project using python 3.6 https://github.com/neovim/python-client/blob/master/.readthedocs.yml
