### ISSUE TITLE
tests failing with postgresql

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#3957]
## Details

We're trying to run tests against postgres to match the database we use in production.

## Expected Result

tests pass

## Actual Result

With the following changes required to run tests against postgres https://github.com/rtfd/readthedocs.org/compare/master...italia:testspostgres?expand=1 tests fails with this https://travis-ci.org/italia/docs.italia.it/jobs/367583533

**Comment by xrmx** [comment]
This are logs against postgresql 9.6: https://travis-ci.org/italia/docs.italia.it/jobs/367631789

**Comment by xrmx** [comment]
For the other 50% not fixed by the PR above i've tried this but that's not it:
https://github.com/italia/docs.italia.it/commit/fa3983666a786f8ca511e706c78955717090e636

Any help would be much appreciated

**Comment by stsewd** [comment]
As I know, RTD uses Postgres in production.
