### ISSUE TITLE
Add repository offline

### ISSUE THREAD

**Issue by enric1994** [rtfd/readthedocs.org#3960]
Greetings,

I am using the self-hosted version of RTD using [Docker RTD](https://github.com/vassilvk/readthedocs-docker)

I am also using Gogs, a self-hosted Git, where I have a lot of repositories offline.

I would like to import my repos docs in RTD. The Import manually seems to work only with Github online repos.

There is a way to **build** without import the repos from the internet? Maybe drop the repos in an internal folder...

Thanks!

**Comment by stsewd** [comment]
You can do it, I import local repos with the `git://` protocol for development.

**Comment by stsewd** [comment]
If you do a `git clone git://localhost:3000/administrator/test_repo.git`, it works?

I use a custom git alias for serving git repos on local dev

https://github.com/stsewd/dotfiles/blob/3afb09b770780a5b7e1369ce38c8552c1983e6cd/gitconfig#L14-L15

**Comment by enric1994** [comment]
No, it don't work...
`errno=Connection refused`
Maybe Gogs don't support that protocol, or is my reverse proxy... So the problem is mine and not from RTD.

Thanks for your time!
