### ISSUE TITLE
Adding jazzband-bot to a project where credentials have been lost

### ISSUE THREAD

**Issue by borgstrom** [rtfd/readthedocs.org#3961]
## Details

* Read the Docs project URL: https://django-simple-menu.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): fatbox / borgstrom / jazzband-bot

## Expected Result

jazzband-bot is added as a maintainer to the django-simple-menu project

## Actual Result

The project was created in an account that I no longer have access to.  I am not able to maintain django-simple-menu anymore, and as such am transferring it to the @jazzband project, but to complete on-boarding the jazzband-bot user needs to be a maintainer on the project.

See: https://github.com/jazzband/roadies/issues/96

I'm hoping that jazzband-bot can be added as a maintainer of the django-simple-menu project by an administrator.

Thanks!

**Comment by davidfischer** [comment]
Why do you no longer have access to that account? Did you lose access to the email and the password?

**Comment by borgstrom** [comment]
@davidfischer -- The business was sold (including the domain name), and as such I do not have access to the email address for the fatbox user anymore.  The new owner did not want any of the open source software that the business produced so the projects ended up in my personal github account.

**Comment by stsewd** [comment]
This needs an action from our side I think

**Comment by davidfischer** [comment]
I actually think this might be safe to do:

- The repo on Read the Docs (http://github.com/borgstrom/django-simple-menu.git) now redirects to the jazzband org (https://github.com/jazzband/django-simple-menu)
- Looking at [other](https://readthedocs.org/projects/contextlib2/) [projects](https://github.com/jazzband/django-debug-toolbar) associated with jazzband-bot on RTD, they also point to the jazzband repos on github

Any objection?

**Comment by stsewd** [comment]
:+1:  from my side

**Comment by ericholscher** [comment]
Seems reasonable. 👍

**Comment by davidfischer** [comment]
This is now done.
