### ISSUE TITLE
Auto-redirect .rst => .html

### ISSUE THREAD

**Issue by ale5000-git** [rtfd/readthedocs.org#3964]
## Details

* Read the Docs project URL: https://pycompatlayer.readthedocs.io/

## Expected Result

To have relative urls working correctly on github.com they must point to other .rst files but to have them working on readthedocs.org they must point to .html

An automatic redirect of *.rst => *.html on readthedocs.org would make them working on both places.

## Actual Result

Currently they point to an unexistant .rst page.

**Comment by stsewd** [comment]
Any specific page that you have a relative url that we can look at?

**Comment by ale5000-git** [comment]
For example on [this page](https://pycompatlayer.readthedocs.io/en/latest/intro.html), there is a link on `LGPL-3.0-or-later`.

**Comment by stsewd** [comment]
@ale5000-git you need to use a sphinx role (ref or doc) to link between docs pages http://www.sphinx-doc.org/en/stable/markup/inline.html#role-doc

**Comment by agjohnson** [comment]
Yup, this looks to be a problem with your linking syntax. I don't think we'll support rst -> html redirection on Read the Docs. Closing this issue.

**Comment by ale5000-git** [comment]
@stsewd
@agjohnson

It must work also directly on GitHub so I must use only pure reStructuredText without sphinx extensions.
Any help?
