### ISSUE TITLE
requirements_file isn't being respected

### ISSUE THREAD

**Issue by maroux** [rtfd/readthedocs.org#3970]
## Details

* Read the Docs project URL: http://taskhawk.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/taskhawk/builds/7062836/
* Read the Docs username (if applicable): maroux

## Expected Result

`requirements/dev-3.6.txt` should have been installed so the correct version of Sphinx could be pulled.

## Actual Result

`requirements/dev-3.6.txt` is NOT installed and stale Sphinx version is used.

**Comment by stsewd** [comment]
In the 8th step of the build you can see that your requirements file is installed (`and also sphinx==1.7.2`). So, I'm not sure what's the problem here.

**Comment by maroux** [comment]
Ah, sorry, evidently I can't read.

**Comment by stsewd** [comment]
@maroux don't worry :+1:
