### ISSUE TITLE
pip install -r

### ISSUE THREAD

**Issue by kira0204** [rtfd/readthedocs.org#3971]
Hi,

RTD is installing modules from `requirements.txt`and I can't understand why is it required, because of this my build is failing because some of the C library packages are not there. 
Now is there any way to skip the installation of modules from requirements.txt file.

Thanks

**Comment by kira0204** [comment]
Hi @stsewd , sorry for the late reply.
I did not give the build and project url because I thought it's a general question.
https://readthedocs.org/projects/testthug/builds/7066425/ - this should suffice I guess.

Moreover I have `requirements.txt` for my tool but do not want to specify an extra `requirements.txt` for RTD. I am looking for ways in which I can disable the installment of the modules because it's not necessary.

**Comment by stsewd** [comment]
@kira0204 did you delete your project? I can't see your build or your project. RTD always look for a requirements file on your project (first on the `docs/` directory and then in the project root), that's a RTD feature, I think you can create an empty `requirements.txt` file in the `docs/` directory.

**Comment by kira0204** [comment]
@stsewd I got my privacy level as `private` which I changed it now, sorry for the inconvenience. Also I provided a `conf.py` file in my `docs` folder to mock one of the modules (RTD FAQs suggested this) but I don't think RTD is reading my file because I think in the build it should mention something along the lines `cat /path/to/conf.py`

**Comment by kira0204** [comment]
Update: Blank requirements.txt file works, but I would really love an option where I can select whether RTD should install requirements or not. Thanks @stsewd

**Comment by stsewd** [comment]
@kira0204 yeah, that's part of the rtd _philosophy_, a user imports a project and should just work, I'll try to see if we can put this as an option for the yaml file.
