### ISSUE TITLE
Refactor Task subclasses into decorated functions

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#3973]
Breaking out the task steps in order to reduce shared state on the tasks means
that we no longer need custom classes here. We should reduce the Task subclasses
back down to decorated functions, which preserve the naming, queue, and other
properties of the task.

- [ ] project.tasks
- [x] core.util.tasks

**Comment by humitos** [comment]
We were hitting this at #3946. Here is the official explanation of this (which is not a bug in Celery --but a potential feature :D): http://docs.celeryproject.org/en/latest/userguide/tasks.html#instantiation
