### ISSUE TITLE
Project.documentation_type is `auto`

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#3980]
We have 528 projects with the `Project.documentation_type` set in `auto` and this value is not allowed in the code.

This value is used, for example at: https://github.com/rtfd/readthedocs.org/blob/be4ff5b9c4fb6f8c4f8b093e98a1359491a52b1f/readthedocs/doc_builder/python_environments.py#L276

But the dictionary used to get the proper builder class doesn't have the `auto` value and make the build to fail:

https://github.com/rtfd/readthedocs.org/blob/be4ff5b9c4fb6f8c4f8b093e98a1359491a52b1f/readthedocs/doc_builder/loader.py#L15-L32

We do have a way to protect ourselves for this, but this is still happening in production.

https://github.com/rtfd/readthedocs.org/blob/be4ff5b9c4fb6f8c4f8b093e98a1359491a52b1f/readthedocs/projects/tasks.py#L429-L431

I suppose that this is still happening because of #3946 isn't deployed yet.

> This doesn't seem to be too important, but just filling this issue to keep track of this and make sure that it doesn't happen anymore after that PR is deployed.

Ref: https://sentry.io/read-the-docs/readthedocs-org/issues/472212666/events/latest/

**Comment by agjohnson** [comment]
Sentry issue: [READTHEDOCS-ORG-CWX](https://sentry.io/read-the-docs/readthedocs-org/issues/533070699/)

**Comment by agjohnson** [comment]
Lets target this for this release, I'm seeing a lot of new errors around this project type, including ^

**Comment by humitos** [comment]
To reproduce this, just change the `Documentation Type` to `auto` and the next build will fail.
