### ISSUE TITLE
Build failed, said to report, so I am...

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#3985]
## Details

https://readthedocs.org/projects/testfixtures/builds/7074250/

## Expected Result

Built docs ;-)

## Actual Result

Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7074250).

**Comment by cjw296** [comment]
Here's another one: https://readthedocs.org/projects/picky-conda/builds/7074668/

**Comment by swainn** [comment]
Same for us too: https://readthedocs.org/projects/tethys-platform/builds/7074517/

**Comment by SylvainCorlay** [comment]
Same here

**Comment by boegel** [comment]
+1 https://readthedocs.org/projects/easybuild/builds/7076258/

**Comment by gouarin** [comment]
same for us: https://readthedocs.org/projects/pylbm/builds/7076600/

**Comment by stsewd** [comment]
Maybe a temporary problem on the server, please retry in a couple of hours and tell us if still doesn't work.

**Comment by boegel** [comment]
@stsewd This has been going on since yesterday, at least about 16 hours now, first occurrence for me was https://readthedocs.org/projects/easybuild/builds/7073819/

**Comment by SylvainCorlay** [comment]
@stsewd same here. This appears to be an issue since yesterday night on multiple repositories in multiple organizations.

**Comment by stsewd** [comment]
Just for recap

@cjw296's project issue was solved (or at least clarified) in #3986
@SylvainCorlay's project is being investigated for more details in #3993

@boegel  I can see that your docs never built successfully before (+4 months ago) https://readthedocs.org/projects/easybuild/builds/6829697/ here I can see that your problem is due to timeout limit, you can request to increment this for your project on a separated issue.

@swainn @gouarin I will check your projects later.

**Comment by cjw296** [comment]
@stsewd - I thought I was pretty clear on #3986: I don't believe any of the build failures I reported here were as a result of other issues. Please take a look at the build urls, the wording suggests something unexpected has happened, maybe there's a traceback lurking on some rtd monitoring somewhere?

**Comment by boegel** [comment]
@stsewd Thanks for the feedback, much appreciated.

I must admit I've been ignoring those failing builds for a while, since the updated documentation did in fact get generated just fine @ http://easybuild.readthedocs.io/en/latest/. It doesn't anymore however...

For the most recent build, there's no trace that the failure occurs because of a timeout, and it shows a lot less steps (it seems like it actually never gets around to building the documentation), so I assumed something else is wrong, especially after seeing this issue where other people are reporting basically the same problem (with a total lack of a clear error).

I'll open a separate issue to request an increased timeout limit, but I'm not convinced that's the problem here...

**Comment by johnbywater** [comment]
"Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7077435)."

https://readthedocs.org/projects/eventsourcing/builds/7077435/

Also the 'latest' button, bottom left in the RTD theme, is dead. Also the interface is kinda generally confusing.

**Comment by stsewd** [comment]
@cjw296 yes, what I mean here is that your real issue was clarified since the issue reported here was only temporal for your project. I don't have access to the rtd servers, so I can't see the logs at the time.

**Comment by stsewd** [comment]
@SylvainCorlay thanks! 

> Note that we had multiple succesful builda with the very sams conda env before

Feel free to open a new issue requesting more memory/time for your projects if the issue happens too often (maybe this time the servers were too busy) or if the dependencies are really required to build the docs of your project.

**Comment by stsewd** [comment]
@johnbywater 
> Also the 'latest' button, bottom left in the RTD theme, is dead. Also the interface is kinda generally confusing.

I think that is an issue with the latest version of the theme #3925 https://github.com/rtfd/readthedocs.org/issues/3925#issuecomment-382149693

**Comment by johnbywater** [comment]
It's building for me again, thanks a lot!

**Comment by stsewd** [comment]
Hi everyone! I think we have the root of the problem https://github.com/rtfd/readthedocs.org/issues/3998#issuecomment-383599458, closing in favor of #3999

**Comment by agjohnson** [comment]
I haven't looked through the other issues that are tagging along on this report, but @cjw296 issue is not related (seemingly) to #3999.

**Comment by brittonsmith** [comment]
I was also seeing the issue reported here, starting sometime on Friday, April 20, for example [here](https://readthedocs.org/projects/ytree/builds/7073861/). I managed to get things working again by updating my environment.yml file. I did this by creating a new conda environment, pip installing my package, and outputting the environment using `conda env export`.  That doesn't necessarily get to the heart of the issue, but now things are working again.

**Comment by johnbywater** [comment]
I'm sorry, I said it was fixed, and the docs build for the new release, but "latest" builds from develop branch are failing again: https://readthedocs.org/projects/eventsourcing/builds/

**Comment by swainn** [comment]
I attempted a build on latest again today and got the same result: https://readthedocs.org/projects/tethys-platform/builds/7086280/

**Comment by humitos** [comment]
> I haven't looked through the other issues that are tagging along on this report, but @cjw296 issue is not related (seemingly) to #3999.

@agjohnson I couldn't reproduce it locally. It builds properly in `latest` and `stable`.

@cjw296 can you confirm if you are still having this issue? If it's fixed, please close the issue.

To all the other people involved in this issue: we deploy a fix for the generic build error message yesterday and your builds should be fixed now. In any case that you are still experimenting errors, please open new issues following the template. Thanks you all!

**Comment by cjw296** [comment]
@humitos - these are intermittent failures, if you're confident the changes for the generic build error messages will provide better ways forward, feel free to close this.
