### ISSUE TITLE
Allow develop mode installation

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#3986]
## Details

Here's the source control diff:

https://github.com/Simplistix/testfixtures/commit/2be6ef2e125cb2699231408d53bd26f7c24c9693

This resulted in https://readthedocs.org/projects/testfixtures/builds/7074328/

## Expected Result

Build successfully as before.

## Actual Result

```
/home/docs/checkouts/readthedocs.org/user_builds/testfixtures/envs/latest/lib/python3.5/site-packages/pkginfo/develop.py:45: UserWarning: No PKG-INFO found for path: /home/docs/checkouts/readthedocs.org/user_builds/testfixtures/checkouts/latest
  warnings.warn('No PKG-INFO found for path: %s' % self.path)
```

**Comment by stsewd** [comment]
I can see in your latest unsuccessfully build that you have rtd configured to look for your requirements file, but it doesn't exists on that commit.

**Comment by stsewd** [comment]
Ok, about the original issue reported, seems like an error on your conf.py file https://github.com/Simplistix/testfixtures/blob/a5d96032ed148d0b478bcc47834733e3e1f5ceb9/docs/conf.py#L9

I think there is some difference when installing your project with and without the yaml file: it installs your project twice, with the requirements file and with the setup.py installation.

**Comment by cjw296** [comment]
@stsewd - there's a few things going on, and it's why I was quite specific about build numbers:

1. Whenever you change settings, it triggers a new build. That's frustrating when you're changing settings so that the *next* commit pushed will work with them. I see no way to change settings in such a way that this doesn't cause breakage. I believe this was the cause of the following build failures:

https://readthedocs.org/projects/testfixtures/builds/7074222/
https://readthedocs.org/projects/testfixtures/builds/7074449/

2. I believe there is a bug lurking where if a requirements file name is specified in the project settings, even if the 'use requirements file' checkbox is *unchecked*, rtd attempts to look for the file. I believe that is the cause of the following failures:

https://readthedocs.org/projects/testfixtures/builds/7074249/
https://readthedocs.org/projects/testfixtures/builds/7074270/

3. There are currently intermittent build failures occurring, this seems to occur more frequently when more than one build is kicked off on a project. See #3985, which was the cause of this failure:

https://readthedocs.org/projects/testfixtures/builds/7074250/

4. That leaves the issue I've reported above, which is the cause of this failure:

https://readthedocs.org/projects/testfixtures/builds/7074328/

**Comment by stsewd** [comment]
@cjw296 please see https://pythonhosted.org/pkginfo/distributions.html#introspecting-development-checkouts `pkinfo.Develop` only works on a _develop mode_ installation, which rtd doesn't take care when `python.pip_install` is true, I think you can still use your old requirements file with the yaml file keeping your desire behavior with the `requirement_file` option https://docs.readthedocs.io/en/latest/yaml-config.html#requirements-file

**Comment by cjw296** [comment]
Right, hence [my comment](https://github.com/rtfd/readthedocs.org/issues/3986#issuecomment-383211644). I guess this becomes a feature request to add a `pip_develop` or `pip_editable` alternative to `pip_install`.

**Comment by stsewd** [comment]
Please change the issue title or create a new issue with the feature request (I think this is better, so we keep this issue as context)

**Comment by stsewd** [comment]
Ok, you should be able to install your project by putting this in your requirements file `-e .` and making pip_install = false instead of making a new configuration for the yaml file. We want to cover only common cases there, and there is a way of solving the problem, so closing.
