### ISSUE TITLE
conda environment.yaml using -e . in pip section doesn't work

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#3988]
## Details

Here's the environment.yaml:

Here's the build: https://readthedocs.org/projects/picky-conda/builds/7074334/

## Expected Result

Environment to be correctly built, here's Travis doing it:

https://travis-ci.org/Simplistix/picky-conda/jobs/369093815#L1769

## Actual Result

CondaValueError: pip returned an error.

**Comment by cjw296** [comment]
So, attempting to fix this, I made these changes to `.readthedocs.yml`:

https://github.com/Simplistix/picky-conda/commit/d58b62e4a045b22cea10d76b2aeb30e652c6f8b1

This then changes the problem to the one shown in https://readthedocs.org/projects/picky-conda/builds/7074413/:

```
Running Sphinx v1.7.2
/home/docs/checkouts/readthedocs.org/user_builds/picky-conda/conda/latest/lib/python2.7/site-packages/pkginfo/develop.py:45: UserWarning: No PKG-INFO found for path: /home/docs/checkouts/readthedocs.org/user_builds/picky-conda/checkouts/latest
  warnings.warn('No PKG-INFO found for path: %s' % self.path)
```
...that looks a lot like #3986

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

Also, I think this is the same as #3986
