### ISSUE TITLE
Edit On GitHub link broken

### ISSUE THREAD

**Issue by SylvainCorlay** [rtfd/readthedocs.org#3994]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/xleaflet/

## Expected Result

The link "Edit on GitHub" to point a valid URL.

## Actual Result

The link "Edit on GitHub" lacks the "blob" part

For example on page https://github.com/QuantStack/xleaflet//master/docs/source/index.rst, 

the link points to

https://github.com/QuantStack/xleaflet//master/docs/source/index.rst

instead of

https://github.com/QuantStack/xleaflet/blob/master/docs/source/index.rst

**Comment by stsewd** [comment]
I think the is kind of related to #3925, I will take a further look later.

**Comment by stsewd** [comment]
This is a bug from the rtd theme, I'm fixing it on https://github.com/rtfd/sphinx_rtd_theme/pull/617

**Comment by stsewd** [comment]
This should be fixed in the next release of the rtd theme.
