### ISSUE TITLE
Doc build broken with cryptic message to report this to you (astropy)

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#3995]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/7074563/
* Read the Docs username (if applicable):

## Expected Result

Successful build.

## Actual Result

Failure with the message, "There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7074563)."

**Comment by adrn** [comment]
I'm seeing the same on a few of my projects, for example:
* Read the Docs project URL: https://readthedocs.org/projects/pyia/
* Build URL (if applicable): https://readthedocs.org/projects/pyia/builds/7081331/
* Read the Docs username (if applicable): adrn

**Comment by RichardLitt** [comment]
Thanks. I'm not able to help with the error message - @humitos should be able to - but I wonder if the message could be improved. Would this be less cryptic? 

"There was a problem with Read the Docs while building your documentation. This is most likely a problem with our system, not with you! If you would like to report this, please do so here (https://github.com/rtfd/readthedocs.org/issues/) and use this build ID number: 833292002"

**Comment by RichardLitt** [comment]
This is most likely related to https://github.com/rtfd/readthedocs.org/issues/3995.

**Comment by agjohnson** [comment]
As we learn how to catch more of these errors, the plan is to make these less general. This is a problem with RTD though, so there is no way for a normal user to remedy this, hence the generic error. We'll investigate on our side, but most likely related to bugfix release 2.3.9 and others from last week.

**Comment by agjohnson** [comment]
Opened #3999 to deal with this, I'm rolling all the reports up there.
