### ISSUE TITLE
Doc build broken with cryptic message to report this to you (jwst)

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#3996]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/jwst-pipeline/
* Build URL (if applicable): https://readthedocs.org/projects/jwst-pipeline/builds/7075515/
* Read the Docs username (if applicable):

## Expected Result

Successful build.

## Actual Result

Failure with this message, "There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7075515)."

**Comment by brycefrank** [comment]
I am having a similar issue that fails on the same step, `git branch -r`

- Project URL: https://readthedocs.org/projects/pyfor-pdal-u/
- Build URL - https://readthedocs.org/projects/pyfor-pdal-u/builds/7077493/
- RTD Username: brycefrank

**Comment by RichardLitt** [comment]
This is most likely related to https://github.com/rtfd/readthedocs.org/issues/3985.

**Comment by agjohnson** [comment]
Just confirmed this is #3999. I'm going to roll all of the affected issues up there, feel free to follow along there.
