### ISSUE TITLE
I can't import my Sphinx doc project from github. 

### ISSUE THREAD

**Issue by artakhak** [rtfd/readthedocs.org#3997]
The project I am trying to import is at https://github.com/artakhak/IoC.Configuration.Documentation.  It shows in github projects (under "Import Repositories").

The steps I do in readthedocs.org are following.

-I click on plus button next to IoC.Configuration.Documentation in list "Import a Repository".
-On next page titled "Project Details" I check "Edit Advanced Options" and leave everything at defaults (I also tried the following in Repository URL: https://github.com/artakhak/IoC.Configuration.Documentation, and https://github.com/artakhak/IoC.Configuration.Documentation/docs)
-I click on checkbox "Edit advanced project options"
When I click next, I am taken to https://readthedocs.org/ . No error message. 

I already spent a lot of time, and I am starting to regret that I considered readthedocs.org. The repository has the format that readthedocs suggests. Please help.

**Comment by stsewd** [comment]
First of all, there is nothing wrong with your project content. I just imported successfully on my local instance. I think maybe is something with your project name, I'm going to try creating a project like that on my account.

**Comment by stsewd** [comment]
Sorry, I'm not able to reproduce this issue with a project with the same name.

**Comment by stsewd** [comment]
Did you try importing manually your project? http://127.0.0.1:8000/dashboard/import/manual/

**Comment by artakhak** [comment]
HI stsewd ,

Thanks for responding quickly.

Yes I was trying the manual import option (not sure what non-manual option is, since I could use only this option).

**Comment by artakhak** [comment]
My previous comment was wrong. I wasn't importing manually before. Juts tried import manually too and it didn't work either (the same result).

**Comment by stsewd** [comment]
Ok, I'm pinning @humitos here, maybe he can take a look at the logs on the server if any.

**Comment by stsewd** [comment]
What was your previous account? Maybe related to https://github.com/rtfd/readthedocs.org/issues/2953?

**Comment by artakhak** [comment]
It was artakhak. I still would like to use that account if it works.

**Comment by humitos** [comment]
Did you use the "Import Manually" button?

![captura de pantalla_2018-04-24_16-30-14](https://user-images.githubusercontent.com/244656/39215242-cb9d3d78-47dc-11e8-8723-ff2ddd9914ce.png)

If the project is on Github, you could connect your github account to your read the docs username and import it using the _plus_ sign shown in the image.

**Comment by stsewd** [comment]
@humitos yes, he did that https://github.com/rtfd/readthedocs.org/issues/3997#issuecomment-383549508

**Comment by stsewd** [comment]
We actually only needed a replication here, but not sure that we are going to replicate this soon. If someone else has the same problem, we can reopen and investigate more.
