### ISSUE TITLE
Build failed now. Worked 1 week ago.

### ISSUE THREAD

**Issue by achennu** [rtfd/readthedocs.org#3998]
## Details

* Read the Docs project URL: http://microbenthos.readthedocs.io/
* Build URL (if applicable): 
    * develop: https://readthedocs.org/projects/microbenthos/builds/7083608/
    * latest: https://readthedocs.org/projects/microbenthos/builds/7083645/

## Expected Result

Building and serving docs succeeds from either the master or the develop branch.

## Actual Result

Building failed on the develop branch. I wiped that version and re-triggered a build. That failed. I then triggered a build on the latest version (master) which has had no commits since last build. That also failed.

**Comment by jmsmkn** [comment]
I'm seeing the same thing for our builds (https://readthedocs.org/projects/evalutils/builds/7084112/), but this was after PyUp had upgraded Sphinx from 1.7.2 to 1.7.3. Rolling back Sphinx to version 1.7.2 did not fix it.

**Comment by agjohnson** [comment]
Just confirmed this is #3999. I'm going to roll all of the affected issues up there, feel free to follow along there.

**Comment by achennu** [comment]
Thanks. I will subscribe to that issue.
