### ISSUE TITLE
request for increased timeout for http://easybuild.readthedocs.io + http://boegel-eb.readthedocs.io

### ISSUE THREAD

**Issue by boegel** [rtfd/readthedocs.org#4002]
## Details

* Read the Docs project URL: http://easybuild.readthedocs.io + http://boegel-eb.readthedocs.io
* Build URL (if applicable):
  * last successful build before timeout issues: https://readthedocs.org/projects/easybuild/builds/6418666/
  * recent failed build due to timeout: https://readthedocs.org/projects/easybuild/builds/7049365/
* Read the Docs username (if applicable): `easybuild`

## Expected Result

Docs build succeeds without a timeout.

## Actual Result

Docs build fails due to hitting 15 min. timeout limit.

## Further info

Since a couple of weeks, the doc builds for http://easybuild.readthedocs.io have started failing consistently due to timeouts.
This was not a huge issue, since I'm mainly concerned with the HTML documentation, which was still being updated until recently.
Since a couple of days however, the documentation doesn't get updated at all anymore, which seems to be related to #3999.
Regardless of that issue, it seems like we're due for an increased timeout limit.

Since the last successful build (https://readthedocs.org/projects/easybuild/builds/6418666) required 869 seconds to complete, it seems we're just too close to the 15 min. timeout limit for the entire documentation build to complete...

I would also like to request the same timeout increase for my "staging" fork of the documentation, http://boegel-eb.readthedocs.io, which suffers from the same problem (most recent successful build was https://readthedocs.org/projects/boegel-eb/builds/6854582/, since then timeouts have been occurring, see https://readthedocs.org/projects/boegel-eb/builds/6854645/).

**Comment by humitos** [comment]
Hi @boegel! I just increased the time limit in both projects 5 minutes. That should be enough for now. Let me know if you are still experiencing issues.

**Comment by boegel** [comment]
Thank you very much @humitos! :+1:
