### ISSUE TITLE
RTD warns of build failure, log offers few clews

### ISSUE THREAD

**Issue by standage** [rtfd/readthedocs.org#4004]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kevlar
* Build URL (if applicable): https://readthedocs.org/projects/kevlar/builds/7085704/
* <strike>Read the Docs username (if applicable):</strike>

## Expected Result

Documentation builds

## Actual Result

Build terminates with a failure message. Hard to see what the problem is, if any, from the build logs.

**Comment by stsewd** [comment]
Maybe related to #3999

**Comment by standage** [comment]
Perhaps. It looks like I'm seeing order of magnitude fluctuations in build time: +/- 70 seconds at best, and 500+ seconds at worst.

**Comment by standage** [comment]
My latest build passed, so I'll chalk this up to transient behavior that is being actively monitored and addressed. Thanks!

**Comment by RichardLitt** [comment]
Thanks @standage!
