### ISSUE TITLE
Incompatible dependencies when installing with pip 10

### ISSUE THREAD

**Issue by jesuxgslp** [rtfd/readthedocs.org#4005]
## Details
Just try a clean local installation following the guide [installing-read-the-docs](http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs)

## Expected Result
clean installation

## Actual Result

django-haystack 2.8.1 has requirement Django>=1.11, but you'll have django 1.9.13 which is incompatible.

recommonmark 0.4.0 has requirement commonmark<=0.5.4, but you'll have commonmark 0.5.5 which is incompatible.

**Comment by stsewd** [comment]
Please provide your project and build url

**Comment by jesuxgslp** [comment]
Actually is just a fresh readthedocs install  (local install) following the oficial guide  [installing-read-the-docs](http://docs.readthedocs.io/en/latest/install.html#installing-read-the-docs)

**Comment by stsewd** [comment]
Are you using virtual env or similar?

**Comment by jesuxgslp** [comment]
Sure, as the guide describe 

    virtualenv rtd
    cd rtd
    source bin/activate

**Comment by stsewd** [comment]
Looks like the latest update of haystack drop support for the Django version that rtd uses https://github.com/django-haystack/django-haystack/commit/514023e01136e9393112252fec7eb3b101932d0b#diff-2eeaed663bd0d25b7e608891384b7298L15

**Comment by jesuxgslp** [comment]
Thanks  meanwhile I will try django-haystack==2.7.0

**Comment by stsewd** [comment]
@jesuxgslp mmm, yeah, I see. This is weird, recommonmark and commonmark were upgraded a long time ago https://github.com/rtfd/readthedocs.org/commit/64ee6f68472091895d0ad83ed0b072caaa5d5a77 https://github.com/rtfd/readthedocs.org/commit/cb219e890e969410178811485b0d2d43b8828a95

Can you tell me what pip version are you using?

**Comment by stsewd** [comment]
OK, I just tested it myself, I suspected, this is because pip 10, looks like is more strict about dependencies

**Comment by stsewd** [comment]
I'm changing the title of the issue to be more explicit about the issue.

**Comment by TelDragon** [comment]
Hello, are you successful in your local deployment?

I have successfully deployed the local environment here, but I failed to import the project successfully.

**Comment by safwanrahman** [comment]
Seems like this issue has been resolved!

**Comment by dinolinjob** [comment]
pip install CommonMark==0.5.4 will solve this problem
