### ISSUE TITLE
Exact Redirects changed behavior from working, now 404s

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#4008]
## Expected Result

All of our previously working and configured Exact Redirects should continue to work. 

## Actual Result

All of our configured Exact Redirects now result in 404s.

## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/pylons/
* Build URL (if applicable): https://docs.pylonsproject.org/en/latest/
* Read the Docs username (if applicable): stevepiercy

At some point within the last few days, perhaps with the recent changes to Exact Redirects in #3965 or #3593, all of our configured Exact Redirects now result in 404s. We expected them to continue to function. A complete list of our redirects is available at https://readthedocs.org/dashboard/pylons/redirects/

Example configuration:

Redirect Type:
Exact Redirect

From URL:
/docs/pyramid.html

To URL:
https://trypyramid.com/resources.html

https://docs.pylonsproject.org/en/latest/docs/pyramid.html used to redirect to https://trypyramid.com/resources.html. It now 404s.

This is a backward incompatible change, and it caught us by surprise. Is it possible to restore backward compatibility so that the previously entered redirects would still work without the now required "language/version" path preface? Or must I remove the redirects and add them all back with the preface?

**Comment by humitos** [comment]
Hi @stevepiercy, thanks for your report.

I think that you were affected by #3965. That PR fixes a bug and I understand that it's incompatible with your setup. Unfornately (for your setup), how is working now it's the correct way and you/we need to solve your problem in a different way now: re-writing your rules.

I need to understand what are your exact needing here:

1. if you need to fix any `/en/latest/(you From URL defined here)` to the `to_url`, I could prepend the `/en/latest` to all of your redirects in the database
1. if you need to redirect version independent `/<any lang>/<any version>/docs/pyramid.html` to `to_url` we should change the `Exact` redirect to a `Page` redirect.

Let me know this. In the meantime I will keep taking a look/talking to the other folks.

**Comment by stevepiercy** [comment]
@humitos thank you! This is not a rush. Let's see what the team comes up with in its internal discussion.

This project has only one version and language. It's primary purpose is to serve as redirects and mile markers to direct users to the correct resources and avoid 404s from old bookmarks, pages, and search engine indices.

Ideally backward compatibility would be maintained without configuration changes, and the redirects without specifying language/version would be implicit across all languages/versions for the project. In fact, that might be a desirable feature. IMO, DRY > explicit > implicit.

Pending the outcome of your internal discussion, and if there is no better alternative, then I would appreciate your execution of option 2 above.

Side note for option 2, the UI for Page Redirects make it appear that they would not work for external URLs (even though they do):

> Outcome: /$lang/$version/docs/pyramid.html -> /$lang/$version/https://trypyramid.com/resources.html

I can file a separate issue for that, if you think it merits it.

**Comment by humitos** [comment]
> Side note for option 2, the UI for Page Redirects make it appear that they would not work for external URLs (even though they do):

Yes. I think the Redirects section from the admin needs some love. It's very confusing how it works.

I just created a sample project locally to debug this and I finally understood the UI by debugging the code :)

Look at this example:

![captura de pantalla_2018-04-24_18-03-08](https://user-images.githubusercontent.com/244656/39218328-c2dd6336-47e9-11e8-9cf5-39ee1efa5687.png)

Then, if you open the browser at: 
http://rtd-project-a.readthedocs.io/en/latest/external you will be redirected to an external link.

**Comment by stsewd** [comment]
@humitos I thought that page redirects can only redirect to pages inside rtd :thinking:  https://docs.readthedocs.io/en/latest/user-defined-redirects.html#page-redirects

**Comment by humitos** [comment]
> Anyway, should I submit a separate issue for that UI bit?

Yes, please. So we track this specific thing in a separate issue (it may be a similar one, if you can take a minute to search before opening the new one, that would be great :D )

Also, when you know, please let us know what is the decision you made regarding this original issue and the redirects that do not work as you expect.

Thanks!

**Comment by stevepiercy** [comment]
Submitted #4023.

I was awaiting further response from your internal discussion:

> Pending the outcome of your internal discussion, and if there is no better alternative, then I would appreciate your execution of option 2 above.

Thank you!

**Comment by humitos** [comment]
@stevepiercy hey! I just updated our database to user all `Page Redirects` for your redirects. I tried some of them and they work as you want. Please confirm and close this issue if it's solved.

**Comment by stevepiercy** [comment]
@humitos the redirects work, however the Admin UI does not reflect the changes you made in the database:
https://readthedocs.org/dashboard/pylons/redirects/

I think all the redirects should display the prefix of `/en/latest` to remove ambiguity.

![google chrome005](https://user-images.githubusercontent.com/102112/39277273-d0b3378e-48a1-11e8-9213-54502bac0e4b.png)

Thank you!

**Comment by stsewd** [comment]
@humitos just for clarification, all redirects also work for external links? If so, that isn't specified in the docs.

**Comment by humitos** [comment]
@stsewd I don't know if _all_. At least `Page` redirects. For the other, we need to check the source code.

**Comment by stevepiercy** [comment]
@humitos You're right. Please ignore my comment. I'm closing this issue as complete. Thank you for your assistance!
