### ISSUE TITLE
Improve generic build error message

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4010]
@RichardLitt suggested an improved version of our generic message at https://github.com/rtfd/readthedocs.org/issues/3995#issuecomment-383559018

> There was a problem with Read the Docs while building your documentation. This is most likely a problem with our system, not with you! If you would like to report this, please do so here (rtfd/readthedocs.org/issues) and use this build ID number: 833292002

I like it more than the one we have at the moment.

I will always be "cryptic" since this message is shown only when we have no useful feedback to communicate to the user. That's why this message. In a perfect world, this message should never appear :)

Related: #3539

**Comment by stsewd** [comment]
Closing in favor of https://github.com/rtfd/readthedocs.org/issues/4751
