### ISSUE TITLE
 Could not read Username for 'https://gitlab.com': terminal prompts disabled

### ISSUE THREAD

**Issue by xKeiro** [rtfd/readthedocs.org#4011]
## Details

When I'm trying to "Build" I get the following error:
`Cloning into '.'... fatal: could not read Username for 'https://gitlab.com': terminal prompts disabled`

I'm really new to Git,  and ReadTheDocs (basically started learning them today), so I have no idea how to fix this issue, if somebody know what may be causing it, please let me know.

## Expected Result

A working document

## Actual Result

Error

**Comment by humitos** [comment]
Is it a private repo?

In Read the Docs .org you can only import public repos.

**Comment by xKeiro** [comment]
Oh awesome, it worked! I'm so sorry for wasting your time on this, but I just couldn't figure out what was the problem. Thanks a lot!
