### ISSUE TITLE
Stable build reactivates upon project version release on GitHub

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#4012]
## Expected Result

We expect that once we untick a box in the [project's Versions admin UI](https://readthedocs.org/dashboard/pyramid/versions/) that it stays that way for all releases.

## Actual Result

We suspect, but have not yet confirmed, that there is an unexpected behavior in RTD whenever we cut a new release of our project to GitHub. Here's what we think is happening.

* At our [project's Versions admin](https://readthedocs.org/dashboard/pyramid/versions/), we untick the Active checkbox for the `stable` version.
* Months later, we cut a new release of Pyramid.
* We notice that the previously mentioned checkbox has become ticked. 😮 

## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/pyramid/
* Build URL (if applicable): https://docs.pylonsproject.org/projects/pyramid/en/stable/

This is a difficult thing for us to test because we don't want to cut several releases to confirm. Sorry. The best we can do is watch for it the next time we cut a release.

We worked around it by setting the `stable` version to `Active` and `Private`. This makes it not public and removes it from the RTD pop-up version selector

However the [stable build](http://docs.pylonsproject.org/projects/pyramid/en/stable/) also returns a 404 for logged in admin users whom we expected to have the ability to view that build. Additionally for the `stable` build, the [green button View Docs `href` attribute](https://readthedocs.org/projects/pyramid/builds/7092478/) points to http://docs.pylonsproject.org/projects/pyramid/en/latest/, which I would expect to be http://docs.pylonsproject.org/projects/pyramid/en/stable/. Let me know if paragraph merits a separate issue report.

**Comment by humitos** [comment]
Just adding more context here (I didn't jump too deep into the code yet) but it seems that we are updateing the stable version only if it's active:

https://github.com/rtfd/readthedocs.org/blob/324cfb8d27aa56dd55a7c1c56389554eec95893f/readthedocs/projects/models.py#L760-L767

So, if you have untick the `active` field, it _shouldn't_ be updated.

> Additionally for the stable build, the green button View Docs href attribute points to http://docs.pylonsproject.org/projects/pyramid/en/latest, which I would expect to be http://docs.pylonsproject.org/projects/pyramid/en/stable

This is probably "bad UX": that green button always takes you to the `default branch` (defined in the Admin tab) documentation. Although, there is a _new_ and tiny "View docs" link shown immediately after the build has finished and completed in the right side (below the date and seconds spent for building)

**Comment by stsewd** [comment]
Thanks for reporting, I'm closing this in favor of https://github.com/rtfd/readthedocs.org/issues/4672, which I believe are the same problem. Also, I have a PR that fixes this https://github.com/rtfd/readthedocs.org/pull/4733, if after mergin/releasing youn notice the problem again, feel free to ask to reopen this issue, but I really think is the same problem (my pr doesn't fix this only for latest).

**Comment by stevepiercy** [comment]
OK, I've subscribed to both the issue and the PR, so I can track when it's ready. We just released Pyramid 1.10a1, and we'll soon do the same switcheroo as the final release of 1.9.
