### ISSUE TITLE
Bump to at least Sphinx 1.6.6

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#4015]
Sphinx 1.6.6 added support for `emphasize-lines` in PDFs.
https://github.com/sphinx-doc/sphinx/issues/1238

Currently RTD is at 1.6.5, so our PDFs are slightly less pretty than they could be.

**Comment by humitos** [comment]
If you need a different version of Sphinx, you can create a `requirements.txt` and pin the one you want.

On the other hand, we have a "feature" setting where we can mark your project to use `sphinx<2`. That's an admin setting that we need to enable in your project. Let me know if you want me to enable it for your project (providing its name) and I can do it. You test it, and let me know :)

**Comment by agjohnson** [comment]
I think we can bump up the default sphinx default version and the feature flag version. I'm not certain which ones we pick, but if sphinx 1.7 looks well tested on the feature flag projects, I think we can pin 1.7 at least

**Comment by stevepiercy** [comment]
1.7.4 was released today. Make sure to [exclude 1.7.3 because it had a recursive import](https://github.com/sphinx-doc/sphinx/issues/4889).

**Comment by stevepiercy** [comment]
@humitos BTW, your suggestion worked, and thank you! I assumed wrongly that I could not override the Sphinx version, since it's at the core of what y'all do. Silly me.
