### ISSUE TITLE
Use xelatex automatically based on project language

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4021]
xelatex supports unicode input and better supports CJK character sets. We can make a pretty accurate guess on whether to use xelatex based on the project language.

**Comment by skirpichev** [comment]
As it [was explained](https://github.com/rtfd/readthedocs.org/issues/1556#issuecomment-277936162), you shouldn't guess.  You can just query standard sphinx config option 'latex_engine'.

**Comment by skirpichev** [comment]
@humitos, no, thank you.  I had bad experience with projects, that were infected with Code of Conduct.

I hope someone else will solve this problem.

**Comment by RichardLitt** [comment]
Sorry to hear that, @skirpichev. The CoC is there to make it easier for people to work, not the opposite. 

Thanks @stevepiercy. It looks like discussion is happening on #1556. Let's discuss this there.

**Comment by skirpichev** [comment]
> The CoC is there to make it easier for people to work, not the opposite.

Or to block unpleasant opinions about the project, how did others.  I don't know.

**Comment by RichardLitt** [comment]
If you have unpleasant opinions about readthedocs, you're welcome to politely point out issues or to suggest changes. That's what the open source community is for - pointing out bugs and issues and making them better. As long as you're considerate, respectful, and generally nice, we're glad to have you and your work here. :) Let us know if you want to help out with this ticket.

**Comment by humitos** [comment]
I'm closing this issue in favor of #1556 which it's very similar and has more discussion around it.
