### ISSUE TITLE
Verify all our emails

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#4025]
Currently email verification is optional for users. This means when they sign up, they get a verification email, but they can still sign in without it.

We should eventually get all our active users verified. It feels like the process should be the following:

* On login, check if the email address is verified, if not, we should resend their verification email, and show a message in the UI about verifying them
* After some amount of time, we should turn on email verification as a requirement, so that we are better able to be sure our users have real emails.

**Comment by humitos** [comment]
@rajujha373 please, go ahead and submit a pull request! :)

I suppose the description should be clear enough, but if you have any question, please ask.

**Comment by dojutsu-user** [comment]
@humitos This issue seems interesting to me. I would like to take this issue. Can you please guide me on how to get started with it.

**Comment by dojutsu-user** [comment]
@humitos thanks, but the development environment is already up, can you please tell me how to check if the email is verified or not.
Actually, I am not able to find the model for this

![screenshot from 2018-10-15 14-56-52](https://user-images.githubusercontent.com/29149191/46942410-e8869b00-d08a-11e8-9d5f-db13dd232bfa.png)

**Comment by ericholscher** [comment]
There is a PR currently open for this. Thanks stalebot, we'll get on it :)
