### ISSUE TITLE
Broken search

### ISSUE THREAD

**Issue by shoyer** [rtfd/readthedocs.org#4026]
## Details

* Read the Docs project URL:  https://readthedocs.org/projects/xray/
* Built documentation URL: http://xarray.pydata.org/en/stable/
* Documentation source code: https://github.com/pydata/xarray/tree/master/doc

## Expected Result

Searching on our generated docs seems to be broken. For example, searching for the project name doesn't return any results:
http://xarray.pydata.org/en/latest/search.html?q=xarray&check_keywords=yes&area=default

We seem to also be suffering from https://github.com/rtfd/readthedocs.org/issues/3925 so this might be related.

**Comment by goerz** [comment]
Same problem here, for https://readthedocs.org/projects/qnet/builds/7100055/

Looks like that [0.3.0 release](https://github.com/rtfd/sphinx_rtd_theme/issues/610) of the theme broke things pretty hard.

**Comment by rameshthoomu** [comment]
Same issue here https://readthedocs.org/projects/hyperledger-fabric/builds/7107801/ -- Looking for a fix or workaround

**Comment by slel** [comment]
Same issue for [**xtensor**](https://xtensor.readthedocs.io), a C++ library meant for
numerical analysis with multi-dimensional array expressions;
and even a search for "array" or "tensor" gets no result.

**Comment by stsewd** [comment]
I think the issue is already solved, please try refreshing your browser cache

**Comment by slel** [comment]
Yes it works now. Thanks!

**Comment by HadrienG2** [comment]
Fixed it for me too :)

**Comment by shoyer** [comment]
Closing this since it's fixed for me, too (I'm not sure what happened)

**Comment by RichardLitt** [comment]
Thanks, @shoyer, anyway! :)
