### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by steffengraber** [rtfd/readthedocs.org#4028]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nest-simulator/
* Build URL (if applicable): https://nest-simulator.readthedocs.io/en/latest/
* Read the Docs username (if applicable): graber

## Expected Result

I'm working on https://github.com/nest/nest-simulator and like to update the documentation.

## Actual Result

Can not update the documentation, as the repository is owned by someone else, who is not part of the nest developers.
Can you please ask the user to transfer the ownership or add me as owner as well?

thanks in adanvce!

**Comment by humitos** [comment]
@steffengraber hi! I'm assigning this to myself to take care of.

We do have a policy for this cases at http://docs.readthedocs.io/en/latest/abandoned-projects.html

I will contact the user in the next week hopefully. Thanks

**Comment by humitos** [comment]
Sorry for the delay. I was able to send an email today. I will come back to this in 6 weeks from now.

    datetime.datetime(2018, 6, 22, 11, 35, 48, 961598)

**Comment by humitos** [comment]
@steffengraber hi! He gave you permissions to update the docs. You are now maintainer of that project.

Let us know if there is any problem. I'm closing this issue.

Thanks,
