### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by lukehinds** [rtfd/readthedocs.org#4030]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bandit/
* Build URL (if applicable):
* Read the Docs username (if applicable): klondon

Hello,

I am developer from the Bandit project. We are currently migrating from OpenStack [0] to PyCQA [1]. While at OpenStack we hosted our own sphinx docs and so we had not noticed that someone had imported our github mirror [2] under their own readthedocs account.

Now that we have moved to githiub [3] we want to host on readthedocs, but a user called `klondon` [4] who none of the Bandit developers know or have heard of before, has parked the /bandit page.

Is it possible the /bandit readthedocs could be transferred my account [5] from klondon's account?

[0] https://docs.openstack.org/bandit/latest/
[1] https://github.com/PyCQA
[2] https://github.com/openstack/bandit
[3] https://github.com/PyCQA/bandit
[4] https://readthedocs.org/profiles/lukehinds/
[5] https://readthedocs.org/profiles/lukehinds/

**Comment by humitos** [comment]
@lukehinds hi! I'm assigning this to myself to take care of.

We do have a policy for this cases at http://docs.readthedocs.io/en/latest/abandoned-projects.html

I will contact `klondon` in the next week hopefully. Thanks

**Comment by lukehinds** [comment]
Thanks @humitos !

**Comment by lukehinds** [comment]
Just noted, bullet [4] should have been https://readthedocs.org/profiles/klondon

**Comment by humitos** [comment]
I sent an email today to the author. I will be back to this in 6 weeks:

    datetime.datetime(2018, 6, 22, 11, 47, 21, 663167)

**Comment by humitos** [comment]
@lukehinds you are now maintainer. `klondon` just added you.

Please feel free to re open the issue if there is a problem.

**Comment by ericwb** [comment]
Hi @humitos, thank you for adding @lukehinds as a maintainer of the bandit docs. Can you also please add the other maintainers as well? Namely, @sigmavirus24, @ghugo, and myself @ericwb?

**Comment by lukehinds** [comment]
In fact it would be good for klondon to transfer ownership as they have no involvement in the project at all.

**Comment by lukehinds** [comment]
@ericwb just checked and I have rights to add maintainers (I removed klondon as well). I managed to add you, but for Ian and Gage they will need readthedocs accounts.

**Comment by ericwb** [comment]
Thanks @lukehinds! I've also added @sigmavirus24 (under different user name).
