### ISSUE TITLE
Import Error from module

### ISSUE THREAD

**Issue by isaacsultan** [rtfd/readthedocs.org#4034]
## Details

[build](https://readthedocs.org/projects/medembed/builds/7108602/)

I am importing a constant `DIR_PROCESSED` from `init.py`

The build fails like this:

```
from medembed import DIR_PROCESSED
ImportError: No module named 'medembed
```
My file structure

```
MedEmbed/
  docs/
    build/
    source/
      code.rst
      conf.py
      index.rst
  medembed/
    __init.py
    main.py
    transformer.py
    dataset.py
    embedding.py

```
As such I added within conf.py:

`sys.path.insert(0, os.path.abspath('../../medembed'))`

**Comment by humitos** [comment]
@isaacsultan hi! Thanks for your report.

This doesn't seem to be a problem with the RTD platform, but with your project itself. Just in case, are you able to build the docs locally in your computer?

**Comment by isaacsultan** [comment]
@humitos Hi, thanks for getting back to me so quickly. Somebody just helped me out with it on SO, it turns out I was missing `sys.path.insert(0, os.path.abspath('../../'))`
