### ISSUE TITLE
Update build list to include an alert state

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4036]
As raised in #4018, a better UI for a queue backup would be to show the affected builds in an alert state:

* Show an alert state on each hanging build in the build list if build.state == triggered and build.date > 5m ago. No need for redis here
* Alert state should be very minimal, a FA icon -- ie https://fontawesome.com/icons/exclamation-triangle?style=solid
* Perhaps mouse over on icon shows a brief message "This build is still waiting to be built"
* Link still goes to detail page
* There should be a warning box (using the standard notification pattern!) that says something along the lines of "This build has not started yet. This can be due to heavy build volume or to a problem with Read the Docs. If the problem persists, contact us"

**Comment by saadmk11** [comment]
Where should the warning box be on the list page or the detail page?
