### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by tambry** [rtfd/readthedocs.org#4040]
## Expected Result

readthedocs.org website (and all subdomains) load when only IPv6 connectivity is available.

## Actual Result

The readthedocs.org website (and all subdomains) fail to load with the error "No IP addresses found".  
This because there's no IPv6 addresses on DNS for the website, thus the browser has no IP addresses it can connect to.

## Fixing this

Fixing this involves enabling IPv6 on the Rackspace load balancer. According to their docs they support IPv6, so it's likely a small configuration issue.

**Comment by agjohnson** [comment]
We don't host with Rackspace anymore. We're working on a solution for ipv6 eventually, but this feature isn't tracked in our issue tracker here. Closing this issue as duplicate.
