### ISSUE TITLE
Support request: project deletion

### ISSUE THREAD

**Issue by aaronmarkham** [rtfd/readthedocs.org#4042]
## Details

* Read the Docs project URL: https://newdocs.readthedocs.io

## Expected Result

Please delete this project. The MXNet project documentation is now here:
https://mxnet.incubator.apache.org/

**Comment by davidfischer** [comment]
If you own/maintain this project, you can delete it yourself at the following link:
https://readthedocs.org/dashboard/newdocs/delete/

**Comment by stsewd** [comment]
If you are the owner of the project you can do this in the `Admin` section, if not see https://docs.readthedocs.io/en/latest/dmca/index.html

**Comment by aaronmarkham** [comment]
We tried contacting the contributor that set it up, but he's been non-responsive for 26 days. 
It seems a little heavy-handed to have to file a DMCA complaint, but I can request help from our legal department if that's your policy.

Thanks!

**Comment by aaronmarkham** [comment]
Hi @stsewd  - Is there another way to deal with this? It's super complicated how the MXNet org is setup right now, and getting a DMCA notice hasn't happened yet.
This isn't really a copyright issue. The content is wrong and outdated. It actually hurts users to find this old documentation in a google search and try to use it. It should be removed on that fact alone.

**Comment by hen** [comment]
I've appealed with the Apache MXNet developer community to see if anyone is able to contact the individual who setup the 'newdocs' account.

Failing that - @stsewd - where is the Trademark Violation Policy for readthedocs? I see the DMCA, but I think what's probably more applicable here is the equivalent to GitHub's https://help.github.com/articles/github-trademark-policy/

**Comment by ericholscher** [comment]
Generally we've been hands off on projects that users have set up. This feels like something that could be handled by the abandoned project policy though, since it's an old version of the mxnet docs that you want control over. 

We can reach out to the user and start the process if that sounds like a good option?

**Comment by aaronmarkham** [comment]
@ericholscher, yes, please try that. We also tried, but haven't heard back.

**Comment by humitos** [comment]
I'm assigning this issue to myself and I will start the process for abandoned projects. I'm sending an email to the owner today and I'll come back to in 6 weeks.

**Comment by RichardLitt** [comment]
@humitos - I'm curious, how are you internally logging that you'll come back in 6 weeks?

**Comment by humitos** [comment]
I didn't get any reply from the user. I deleted the project.
