### ISSUE TITLE
SVG graphics not rendered on readthedocs.org

### ISSUE THREAD

**Issue by scottgigante** [rtfd/readthedocs.org#4045]
## Details

* Read the Docs project URL: http://phate.readthedocs.io/
* Build URL (if applicable): http://phate.readthedocs.io/en/dev/
* Read the Docs username (if applicable): scottgigante

## Expected Result

I included SVG graphics in my `index.rst` as below.

```
.. raw:: html

    <a href="https://pypi.org/project/phate/"><img src="https://img.shields.io/pypi/v/phate.svg" alt="Latest PyPi version"></a>

.. raw:: html

    <a href="https://phate.readthedocs.io/"><img src="https://img.shields.io/readthedocs/phate.svg" alt="Read the Docs"></img></a>

.. raw:: html

    <a href="https://www.biorxiv.org/content/early/2017/12/01/120378"><img src="https://zenodo.org/badge/DOI/10.1101/120378.svg" alt="bioRxiv Preprint"></a>

.. raw:: html

    <a href="https://twitter.com/KrishnaswamyLab"><img src="https://img.shields.io/twitter/follow/KrishnaswamyLab.svg?style=social&label=Follow" alt="Twitter"></a>

.. raw:: html

    <a href="https://github.com/KrishnaswamyLab/PHATE/"><img src="https://img.shields.io/github/stars/KrishnaswamyLab/PHATE.svg?style=social&label=Stars" alt="GitHub stars"></a>
```

When running `sphinx-build html` on my local machine, I get the following.

![image](https://user-images.githubusercontent.com/8499679/39456996-880b9cf4-4cb8-11e8-8871-eb832422c809.png)

## Actual Result

The SVG badges simply don't show up. The build log shows no warnings related to the graphics.

![image](https://user-images.githubusercontent.com/8499679/39456990-7f25074c-4cb8-11e8-9414-6fbfd95cd4b4.png)

**Comment by stsewd** [comment]
Your stable version is on commit f9d2f371, wich doesn't have the svg badges https://github.com/KrishnaswamyLab/PHATE/blob/f9d2f371f00ba193daa3fa455121696f8d3a6081/Python/doc/source/index.rst

You dev version has the commit with the svg badges http://phate.readthedocs.io/en/dev/

**Comment by scottgigante** [comment]
Hmm - let me restate the problem then - they don't appear on Firefox!

**Comment by stsewd** [comment]
Do you mean the badges aren't shown on http://phate.readthedocs.io/en/dev/? I'm using Firefox, maybe a cache thing, try `Ctrl + f5` to update the page.

**Comment by scottgigante** [comment]
Aha! You're right, it's a cache problem. Sorry for the noise!

**Comment by RichardLitt** [comment]
Glad you got that sorted, @scottgigante! No worries.
