### ISSUE TITLE
sphinx_rtd_theme has no syntax highlighting on readthedocs.io

### ISSUE THREAD

**Issue by omani** [rtfd/readthedocs.org#4050]
## Details

* Read the Docs project URL: https://triggerfs.io/en/latest/install.html#manual
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

Code syntax highlighting the same way I see it on my local machine when building the docs with sphinx-build.

## Actual Result

No code syntax highlighting. This is also the case for other readthedocs.io sites which have the rdt_theme enabled.

My guess is that it only happens on the rtd theme. Any hints?

**Comment by omani** [comment]
also the official theme websitehas no highlighting, as well: http://sphinx-rtd-theme.readthedocs.io/en/latest/demo/demo.html#code-blocks

**Comment by davidfischer** [comment]
Syntax highlighting was added to the theme recently https://github.com/rtfd/sphinx_rtd_theme/pull/448. However, this version isn't yet the default version on Read the Docs. We are working through a few issues with upgrading the theme and we hope to have this as the default version in a few weeks.

In the meantime, you can pin the version to `sphinx_rtd_theme>=0.3.1` to get syntax highlighting.

**Comment by omani** [comment]
yes pinning worked for me. thank you.

feel free to close or keep it open for users to see.

**Comment by PoslavskySV** [comment]
It works for me too, but I have also to add

```css
.highlight {
    background: #ffffff !important;
}
```
in my `style.css` to make the background white again.

**Comment by Blendify** [comment]
The default style set by the theme is `default` however I think for older projects sphinx set the default to `sphinx` and would always override the theme. I do not think this is the case anymore though.

**Comment by amit1rrr** [comment]
> In the meantime, you can pin the version to sphinx_rtd_theme>=0.3.1 to get syntax highlighting.

I am new to RTD and Sphinx. I had to figure out how to do this. If you are in the same boat, I documented the steps in this thread: 
https://github.com/rtfd/readthedocs.org/issues/4072

**Comment by davidfischer** [comment]
I'm going to re-open this until https://github.com/rtfd/readthedocs.org/pull/4096 is fixed.
