### ISSUE TITLE
Contradictory Documentation

### ISSUE THREAD

**Issue by samlobel** [rtfd/readthedocs.org#4053]
## Details

I'm looking at [the privacy page](http://docs.readthedocs.io/en/latest/privacy.html).
There's a note that says that private documentation is still viewable if someone has a URL.

But then, down below, under the Private header, it says that it will 404 if an unauthorized user tries to look.

These seem contradictory to me. But, I don't know much about the project so I'm hesitant to make a PR.

If someone gives me some direction, I'll change the wording to whichever one is true.

**Comment by stsewd** [comment]
The first paragraph is about the generated documentation, the second is about the project page. For example, the docs project https://docs.readthedocs.io/en/latest/ anyone who knows that url can view the docs, but only authorized users can see the project page https://readthedocs.org/projects/docs/.

The docs project is public by the way.

**Comment by stsewd** [comment]
@samlobel hi, with the above explanation it is cleared enough? or maybe we can be more explicit about that on the docs? We will love for you to help us improve the docs if you consider.

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
