### ISSUE TITLE
Java code highlighting not working

### ISSUE THREAD

**Issue by mekrip** [rtfd/readthedocs.org#4055]
## Details
Java-Color-highlight is working fine locally, but not working on RTD. 

* Read the Docs project URL:  http://javaguide.readthedocs.io/en/latest/java/basic.html#hello-world

* Build URL (if applicable): https://readthedocs.org/projects/javaguide/builds/7133222/

* Read the Docs username (if applicable): pythondsp

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
I think this is the same issue as https://github.com/rtfd/readthedocs.org/issues/4050

**Comment by mekrip** [comment]
Thanks, it's working fine after adding "sphinx_rtd_theme>=0.3.1" in requirements.txt
