### ISSUE TITLE
Create a YAML schema file to plan out our changes to our yaml spec

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4058]
I raised in #3878 a good way to start our YAML spec changes would be to write a schema:

> I think the next step is to start writing a schema and some actual examples. https://github.com/23andMe/Yamale looks promising.

We should start here so that we can formalize the tree structure and naming conventions, and provide some validation checks.

Work required here might be:

- [x] Start writing a schema file
- [x] Start review early, or separate this work into two PRs
- [x] Add tests around validation of our schema and some example schema fixture files. This won't necessarily replace the need for logic unit tests similar to the build repo now

**Comment by stsewd** [comment]
I was looking at https://json-schema-everywhere.github.io/yaml, seems like more standard, but there is only a js implementation :(, I'll try to see if the library is mature enough, maybe we can use it doing external calls.

**Comment by agjohnson** [comment]
The underlying PR was just merged. Closing.
