### ISSUE TITLE
Be able to subscribe to projects and get notified when their docs update.

### ISSUE THREAD

**Issue by johnobrien** [rtfd/readthedocs.org#406]
This is a feature request. It would be cool if users could "subscribe" to documentation and, upon a successful update, get a notification of some sort.

Configurable on 'all', 'successful', 'failure', 'change'.

All: All builds regardless of status
Successful: only successful builds
Failure: Only failed builds.
Change: If the build status is different from the previous (was successful then failing or the inverse).

Original Text:
Dropbox integration

This is a feature request. It would be cool if users could "subscribe" to documentation and, upon a successful update, the PDF version of that documentation could be automatically pushed to a users dropbox account.

**Comment by ericholscher** [comment]
We have added webhooks to projects a while back. Also I think the proper way to handle this is at the VCS level, not on RTD. Closing this as I don't think we'll implement it.
