### ISSUE TITLE
docs don't scroll on chrome

### ISSUE THREAD

**Issue by konsumer** [rtfd/readthedocs.org#4066]
## Details

* Read the Docs project URL: all

## Expected Result

The docs should scroll when they are longer than the visible webpage

## Actual Result

It doesn't scroll in Chrome `Version 66.0.3359.139 (Official Build) (64-bit)`. I tested in incognito to ensure it's not a plugin or something else local to my installation of the browser. Sidebar works fine. Seems to work ok on Safari `Version 11.1 (13605.1.33.1.4)`.

**Comment by konsumer** [comment]
It appears it only happens with an experimental flag enabled in `chrome://flags`. I made another issue [here](https://github.com/nodemcu/nodemcu-firmware/issues/2366#issuecomment-386929049) (which was the original place I saw issue, and was frustrated that I couldn't read the NodeMCU docs.) I think I must have enabled this a while ago, and forgotten about it.

Mac: macOS 10.13.4 (17E202)
Chrome: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by thijskramer** [comment]
It could also be a bug in the latest Chrome, because I never had this issue before. I'm working on MacOS 10.13.4 (17E202) and using the 64-bit version of Chrome 66.0.3359.139. 

When I disable the `overflow-x` rule on the `<body>` with Chrome Devtools everything works as expected.

**Comment by konsumer** [comment]
My version is same. I also disabled `overflow-x` and got it working.

**Comment by stsewd** [comment]
Maybe the same issue as https://github.com/rtfd/sphinx_rtd_theme/issues/636? If so, that is a chrome bug, not from rtd.

**Comment by alexeyraspopov** [comment]
Can `overflow-x: hidden` be just removed from CSS?

**Comment by Fohlen** [comment]
Removing `overflow-x: hidden` does also make it possible to scroll for me again.

**Comment by stsewd** [comment]
@Fohlen thanks for the update, @konsumer can you try that solution?

**Comment by konsumer** [comment]
@stsewd: As I said, it worked fine when I disabled the experimental chrome features, so I just did that (I don't even remember why I originally enabled those.)

**Comment by stsewd** [comment]
@konsumer can we close this then?

**Comment by stsewd** [comment]
Closing this, as is more a google chrome bug not rtd.
