### ISSUE TITLE
Code samples no longer are doing syntax highlighting

### ISSUE THREAD

**Issue by pvcraven** [rtfd/readthedocs.org#4068]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/arcade-book/
* Build URL (if applicable): http://arcade-book.readthedocs.io/en/latest/chapters/15_searching/searching.html
* Read the Docs username (if applicable): professor_craven

## Expected Result

Expected code samples to have syntax highlighting.

## Actual Result

Code samples are in monospaced font, but no syntax highlighting.

This used to work, not sure when it stopped working. I am seeing this in all my projects, not just this one.

**Comment by stsewd** [comment]
You need to update the rtd theme on your requirements file (or create one). You can find more about this in https://github.com/rtfd/readthedocs.org/issues/4050
