### ISSUE TITLE
Cannot use Type Hints (Python 3.5)

### ISSUE THREAD

**Issue by imWildCat** [rtfd/readthedocs.org#4069]
## Details

* Read the Docs project URL: https://github.com/imWildCat/scylla/tree/master/docs
* Build URL (if applicable): https://readthedocs.org/projects/scylla-py/builds/7154547/
* Read the Docs username (if applicable): WildCat

## Expected Result

The doc is build successfully.

## Actual Result
Detailed info shown at: https://readthedocs.org/projects/scylla-py/builds/7154547/
```bash
    provider: BaseProvider = q.get()
            ^
SyntaxError: invalid syntax
```

It seems that *rftd* cannot recognise this kind of syntax.

**Comment by imWildCat** [comment]
Fixed according to https://github.com/rtfd/readthedocs.org/issues/2919

I created a file `.readthedocs.yml`: https://github.com/imWildCat/scylla/blob/master/.readthedocs.yml and specifies Python 3.6:

```yml
build:
    image: latest

python:
   version: 3.6
```

**Comment by RichardLitt** [comment]
Thanks, @imWildCat, for logging this. Glad you got it resolved!
