### ISSUE TITLE
Support for UML via PlantUML & sphinxcontrib-plantuml

### ISSUE THREAD

**Issue by n1ywb** [rtfd/readthedocs.org#407]
It would be totally awesome if readthedocs supported UML using the radical UML tool PlantUML and the Sphinx extension sphinxcontrib-plantuml.

PlantUML is the only UML tool I've ever used that I didn't hate, probably because it's not a GUI, you create UML diagrams using a straightforward textual language.

sphinxcontrib-plantuml lets you inline plantuml source code right in your .rst files. Here's a trivial sequence diagram.

```
.. uml::
    Obj1 -> Obj2: Hello, world
    activate Obj2
    Obj2 --> Obj1: Goodbye, cruel world
    deactivate Obj2
```

http://plantuml.sourceforge.net/
https://pypi.python.org/pypi/sphinxcontrib-plantuml

Here's a complete example in a Sphinx doc

![screenshot from 2013-06-20 15 25 28](https://f.cloud.github.com/assets/316961/683428/3e5ae71e-d9df-11e2-8a77-56d7177f5615.png)

**Comment by greglanthier** [comment]
+1

**Comment by ch3lo** [comment]
An alternative is to use the url passing the plantuml code as parameter

**Comment by agjohnson** [comment]
It seems nothing has changed since then, this still isn't a supported package by ubuntu and I'm not even seeing a PPA for this either.

I'm -1 on installing arbitrary packages from source, this isn't a high enough priority to play package manager for. Without someone maintaining this properly, it's bound to cause us a headache.

**Comment by tuomas2** [comment]
+1

**Comment by MantasVaitkunas** [comment]
+1

**Comment by agjohnson** [comment]
Github seriously needs a vote button :/ If you have nothing to add to this conversation, please refrain from pinging maintainers with `+1` comments.

Nothing has changed here, there is still no maintained package that is easily installable on Ubuntu 14.04. As our time is limited, supporting something like this from source is near the bottom of our expansive list.

We'd be happy to consider support plantuml if anyone wants to take on maintaining a PPA for Ubuntu. At this point we don't have much time to spare.

**Comment by n1ywb** [comment]
PPA here https://launchpad.net/~isage-dna/+archive/ubuntu/plantuml

On Tue, Jan 26, 2016 at 11:46 AM, Anthony <notifications@github.com> wrote:

> Github seriously needs a vote button :/ If you have nothing to add to this
> conversation, please refrain from pinging maintainers with +1 comments.
>
> Nothing has changed here, there is still no maintained package that is
> easily installable on Ubuntu 14.04. As our time is limited, supporting
> something like this from source is near the bottom of our expansive list.
>
> We'd be happy to consider support plantuml if anyone wants to take on
> maintaining a PPA for Ubuntu. At this point we don't have much time to
> spare.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/407#issuecomment-175108918>
> .
>



-- 
73 de n1ywb

**Comment by MantasVaitkunas** [comment]
@agjohnson, what actions should be done by community to solve this issue? As I understand  n1ywb provides PPA.

**Comment by agjohnson** [comment]
Feel free to open a PR at https://github.com/rtfd/readthedocs-docker-images for the base image

Note: we will begin testing against 16.04 soon, for it's April releast, so this PPA should be able to support 16.04 as well or we'll have to drop it when we do the upgrade.

**Comment by prikhi** [comment]
I'd love this too...

I've never used Docker, but maybe this link will help someone who has the knowledge to make a proper PR to the readthedocks-docker-images repo: 

https://hub.docker.com/r/grieve/sphinx-plantuml/~/dockerfile/

**Comment by tuukkamustonen** [comment]
It looks like there is now debian package for sid (debian unstable): https://packages.debian.org/source/sid/plantuml

@agjohnson Is it possible to use their package?

**Comment by timofurrer** [comment]
Ubuntu 16.10 has the [plantuml package](http://packages.ubuntu.com/yakkety/plantuml) in their repos as well.

As far as I can tell you are only using LSD releases for your rtd docker images. However, would it be possible to add this package to the 16.04 installation? (via pinning or download & dpkg)

I think this would make some documentation even more awesome! :beers:

**Comment by danwos** [comment]
For me it is not necessary to provide plantuml itself. It should be enough to make java available.

The sphinxcontrib.plantuml extension has a parameter called "plantuml", which defines the complete command to call plantuml (e.g. java -jar my_tools/plantuml.jar).

You could provide the plantuml.jar file inside the docs repository and and set the plantuml config var inside conf.py like this
`plantuml = 'java -jar %s' % os.path.join(os.path.dirname(__file__), "tools/plantuml.jar")`

From the repository owners point of view it is not so nice to keep tools inside the repo, but it may be ok.
But for the rtd team, this solution would be more generic, as it does not support a specific tool. Instead it only makes java available and is therefore supporting additional java tools beside plantuml as well.

Does somebody see any drawbacks for this solution?

**Comment by petrjasek** [comment]
I've made a PR for docker images which installs plantuml from repos:
https://github.com/rtfd/readthedocs-docker-images/issues/17
any feedback on that?

**Comment by petrjasek** [comment]
ping @agjohnson

**Comment by tartarini** [comment]
@agjohnson
considering that the plantuml package is in the mainstream Ubuntu packages.
Is there any issue in just installing it in the rtd images?
Just adding the following in conf.py works for me in Ubuntu:

`
plantuml = '/usr/bin/plantuml -Djava.awt.headless=true '
`

this addition would be really appreciated!

**Comment by mcicolella** [comment]
Any news about this?

**Comment by humitos** [comment]
`plantuml` was already added to the `latest` docker build image (https://github.com/rtfd/readthedocs-docker-images/commit/7bedf5408bc0b25dcf0281d776a2d32791e8c4e2). Now, I think this will be available when that latest docker image goes to production. I'm reopening this issue since it's something that's going to happen... sometime :)

**Comment by jirikuncar** [comment]
@humitos is there any known timeline to know when the image with `plantuml` will be in production?

**Comment by humitos** [comment]
@jirikuncar I don't know. But now, there is an option in the yaml to select the build image you want to use. See https://github.com/rtfd/readthedocs-build/pull/33 and #3339 

(that PR and the related ones to that option, will be merged soon)

**Comment by agjohnson** [comment]
Closing this as the latest image does have usable plantuml, our 18.04 image has an updated version and will be released soon.

**Comment by n1ywb** [comment]
Thank you, everybody, for this, especially @agjohnson for seeing it through after all these years. Today my cup runneth over.
