### ISSUE TITLE
There was a problem with Read the Docs while building your documentation. Please report this to us

### ISSUE THREAD

**Issue by jorisvandenbossche** [rtfd/readthedocs.org#4071]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/geopandas/
* Build URL (if applicable): https://readthedocs.org/projects/geopandas/builds/7161608/
* Read the Docs username (if applicable): 

I am not fully sure why it is failing, I don't find something in the different log parts that fail, but it just stops after the "cat doc/source/conf.py" step. 
And since it asked to report this, that's what I did.

**Comment by pagreene** [comment]
We are experiencing a potentially similar failure for several weeks:

- Project: https://readthedocs.org/projects/indra/
- Failing build url: https://readthedocs.org/projects/indra/builds/7174578/
- Usernames: https://github.com/pagreene, https://github.com/bgyori (our Read the Docs usernames are the same as Github usernames)

As with the above, our _automatic_ builds seem to fail directly after the conf step, however we have found that manually triggered builds continue and apparently succeed, except that they still throw the same error message.

**Comment by jorisvandenbossche** [comment]
I also did a manual trigger of the build, but that failed as well (and also didn't update the docs online)

**Comment by begriffs** [comment]
Experiencing this as well. My builds have been failing for days starting at [build 7213846](https://readthedocs.org/projects/citus-docs/builds/7213846/).

**Comment by stsewd** [comment]
Hi @begriffs,  think your build is failing because your repo has a unicode branch https://github.com/citusdata/citus_docs/tree/metrics-%E2%88%82eco%E2%88%82e, rtd doesn't support unicode names for now (we are planning to support them soon https://github.com/rtfd/readthedocs.org/pull/4052)

**Comment by begriffs** [comment]
@stsewd thanks for the quick response! That was exactly the issue. I deleted the offending remote branch and builds are back to normal.

**Comment by jorisvandenbossche** [comment]
Any updates on this? 
I just triggered a build for latest, and still have the same problem: https://readthedocs.org/projects/geopandas/builds/7289654/

(although in the meantime, there also has been a build that went further than the "cat doc/source/conf.py" step, but that one failed at the time due to an error in one of the our dependencies: https://readthedocs.org/projects/geopandas/builds/7259769/)

**Comment by humitos** [comment]
> but that one failed at the time due to an error in one of the our dependencies: readthedocs.org/projects/geopandas/builds/7259769

Where you able to solve this? This one in particular doesn't seem to be a problem in RTD but in your project configuration.

In case you need to mock a C library, you can read the FAQ at http://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by humitos** [comment]
@jorisvandenbossche hi! Your two latest builds passed. Do you still have this problem or you were able to solve it? Thanks!

**Comment by jorisvandenbossche** [comment]
Yes, it seems to be working now. Thanks!

**Comment by jorisvandenbossche** [comment]
The last build today seems to be failing again: https://readthedocs.org/projects/geopandas/builds/7486083/

**Comment by bgyori** [comment]
Following up on @pagreene's report from the `indra` project:
- Project: https://readthedocs.org/projects/indra/
- Failing build url: https://readthedocs.org/projects/indra/builds/7486455/

All the automatically triggered builds are still failing. In addition, the situation has gotten worse, since recently the manually triggered builds are failing too so we haven't been able to update our public documentation for a while. Any help would be very much appreciated!

```
Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7486455).

git clone --recursive https://github.com/sorgerlab/indra.git .
git checkout --force origin/master
git clean -d -f -f
git branch -r
python3.5 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest
python /home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest/bin/pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/indra/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx<1.8 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<0.6
python /home/docs/checkouts/readthedocs.org/user_builds/indra/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/indra/.cache/pip -rdoc/requirements.txt
cat doc/conf.py
```

**Comment by stsewd** [comment]
@jorisvandenbossche looks like a problem with memory limits, same for @bgyori 's project

**Comment by bgyori** [comment]
Thanks @stsewd, is this something we can solve by changing the project config? Or does this need to be solved on the server side?

**Comment by stsewd** [comment]
@bgyori you can check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html for some tips. If that doesn't solve the problem you need to ask a maintainer to increase the memory limits for your project.

**Comment by jorisvandenbossche** [comment]
Ah, yes, we are probably hitting the 15 min limit (it says the (failed) build run for 14.7 min). 

@humitos geopandas has quite some heavy dependencies to install, but still normally it doesn't take that long to create the environment locally. 
Does readthedocs do any caching of the conda packages?

**Comment by humitos** [comment]
> Does readthedocs do any caching of the conda packages?

Unfortunately, no. That's something that needs to be implemented: #3261 

Does `geopandas` to install all of those dependencies to build the docs, or they are needed only to _use_ geopandas? (I assume they are needed because you have the reference documentation also)

I double your time limit and triggered a new build. It should finish successfully. Let me know otherwise.

**Comment by jorisvandenbossche** [comment]
> I double your time limit and triggered a new build. It should finish successfully. Let me know otherwise.

Thanks for doing that! 
However, now there is another error "Problem parsing YAML configuration. Invalid "requirements_file": path requirements_rtd.txt does not exist", but we didn't change anything in the yaml config file, and there is also no requirements_rtd.txt mentioned in there.

**Comment by jorisvandenbossche** [comment]
> Does geopandas to install all of those dependencies to build the docs, or they are needed only to use geopandas? (I assume they are needed because you have the reference documentation also)

Some of them are needed because we run some examples in the docs (running them itself does not take a lot of time), but the most heavy dependencies (eg gdal and all its dependencies) are not optional.

**Comment by stsewd** [comment]
@jorisvandenbossche 
> However, now there is another error "Problem parsing YAML configuration. Invalid "requirements_file": 

Sorry about that, it was a bug and it was fixed today, if you rebuild your docs, the error should be gone.

**Comment by jorisvandenbossche** [comment]
> if you rebuild your docs, the error should be gone.

It still seems to give the same error now.

**Comment by humitos** [comment]
@jorisvandenbossche the problem is that you have set the file `requirements_rtd.txt` as the requirements file to be installed under `Admin -> Advanced Settings` and that file doesn't exist in your repo. Remove it from there and build it again.

**Comment by jorisvandenbossche** [comment]
Thanks for the quick answer! 
I didn't change anything there, so until now the `readthedocs.yaml` was apparently overruling that.

**Comment by humitos** [comment]
> Following up on @pagreene's report from the indra project:

Please, @bgyori open a new issue for this. It seems to be a different problem.

I imported this project in my local instance and the build is killed for a memory consumption.

Link this comment in the new issue and, if you can, please research a little about why it's consuming too much memory for the build. You can get some ideas from: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

Since the OOM is tricky to catch always properly, the message is sometimes not accurate.

**Comment by jorisvandenbossche** [comment]
@humitos sorry, the build is still failing (now again the original error, after adjusting the advanced settings). Any pointers on what this is related to ? (Memory, time,...)

**Comment by jorisvandenbossche** [comment]
Yes, it seems to work now. Thanks, closing then!
 
(back in July, I still saw some intermittent failures, but at least when re-triggering a build it sometimes passed. However, I am not sure it was related to a time-out, because when it passed, it was not close to the limit)

**Comment by vanshika-srivastava** [comment]
hi i am facing similar issue how can I report?
