### ISSUE TITLE
Invalid project name, a project already exists with that name

### ISSUE THREAD

**Issue by iccicci** [rtfd/readthedocs.org#4073]
## Details

* Read the Docs project URL: http://ccc.readthedocs.io/en/latest/
* Build URL (if applicable): 
* Read the Docs username (if applicable): iccicci

## Expected Result

Maybe I did confusion creating and deleting the project to change it's name.
I'm no longer able to create a project named "ccc" even if I created it yesterday and deleted it today.

Please just clean the project in the DB.

Thanks in advance,
iCC

**Comment by humitos** [comment]
@iccicci In the middle a spam project was created with that name :/

I deleted it. You should be able to re-create your project. Thanks.

**Comment by iccicci** [comment]
I really fast action, @humitos !

Much appreciated
