### ISSUE TITLE
Syntax highlighting not applied in HTML on code example via literalinclude

### ISSUE THREAD

**Issue by flexatone** [rtfd/readthedocs.org#4075]
## Details

I am seeing an issue where syntax highlighting is not being rendered in HTML output on code examples brought in via a literalinclude directive. I observe this result with multiple browsers. When I render the same RST source files with Sphinx 1.6.6 on my local system, syntax highlighting works as expected, both with built-in themes, as well as with the installable Read the Docs theme.

The relevant literalinclude example in HTML is here:
http://static-frame.readthedocs.io/en/latest/intro.html#immutability

The source RST for that page is here:
https://raw.githubusercontent.com/InvestmentSystems/static-frame/master/doc/source/intro.rst

Note that this only affects the HTML version; in the PDF generated by Read the Docs, the syntax highlighting is represented perfectly:
https://media.readthedocs.org/pdf/static-frame/latest/static-frame.pdf

* Read the Docs project URL:
http://static-frame.readthedocs.io

**Comment by davidfischer** [comment]
I believe this is a duplicate of #4050

**Comment by flexatone** [comment]
Thanks for the response. Yes, this appears to be a duplicate of #4050 

As suggested there, I was able to bypass this issue by targeting a version of the RTD theme in my requirements.txt file.

sphinx_rtd_theme>=0.3.1
