### ISSUE TITLE
Better UX for the docs badge

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4081]
This is related to the badge that is in the project overview section.

There are two things:

First is a little hard to know that clicking the badge will make the popup to copy the badge to appear. This is also because if the user puts the cursor under the badge, a link is shown.

![badge](https://user-images.githubusercontent.com/4975310/39855808-ffbd1836-53f2-11e8-9d49-272336f814c2.png)

The other thing is that the popup isn't responsive

![screenshot-2018-5-10 stsewd-demo read the docs](https://user-images.githubusercontent.com/4975310/39855793-fab83802-53f2-11e8-8ae8-e8135955ffdd.png)

**Comment by humitos** [comment]
Wow! I didn't know that this even exists :/

Do you have some opinions/ideas on how the proper way of showing this information will be?

**Comment by stsewd** [comment]
@humitos I discovered this by mistake a month ago :grin:, I don't remember where I saw some good UX for this, I'll try to see if I can remember. But basically, there was a _info_ symbol to the side of the badge, clicking that symbol shows the popup with links to the badge.

**Comment by stsewd** [comment]
Also, the popup can be shown as a modal window.

**Comment by dojutsu-user** [comment]
@humitos 
@stsewd 
I have tried this on local.
Here is something very simple and also visible to the users.

![ezgif-3-22667f3c908c](https://user-images.githubusercontent.com/29149191/51788288-4191bf00-21a2-11e9-911a-25c4fe14616d.gif)

If it's okay, I can make a PR.

**Comment by stsewd** [comment]
I think an icon to the side of the badge would be better

**Comment by dojutsu-user** [comment]
@stsewd 
Exactly which icon you are referring to?
I am not able to find any suitable one in font-awesome.

**Comment by dojutsu-user** [comment]
Is this is the one?
https://fontawesome.com/icons/info-circle?style=solid

**Comment by humitos** [comment]
I like the proposal. Although, I don't have the final word regarding UI decisions.

The info circle makes sense to me to be next to the badge icon. It's a "familiar" behavior I'd say.

**Comment by humitos** [comment]
For example, this is what github does:

![captura de pantalla_2019-01-28_18-50-59](https://user-images.githubusercontent.com/244656/51855527-cbba5e80-232d-11e9-84c1-f3c73b690dca.png)

![captura de pantalla_2019-01-28_18-51-10](https://user-images.githubusercontent.com/244656/51855538-d117a900-232d-11e9-9161-4e6cc749ad70.png)

**Comment by dojutsu-user** [comment]
@humitos 
Okay, I am proposing a PR with the same changes as suggested by you.
