### ISSUE TITLE
Support: Contacting owner of readthedocs.io project who isn't core maintainer to request ownership transfer

### ISSUE THREAD

**Issue by colinoflynn** [rtfd/readthedocs.org#4086]
## Details

* Read the Docs project URL: http://chipwhisperer.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): coflynn (mine)

## Expected Result

The readthedocs.io link for the ChipWhisperer project (http://github.com/newaetech/chipwhisperer) isn't pointing to the main repo, as the readthedocs.io project isn't owned by a core maintainer, and they are very outdated. Would like to contact the current readthedocs.io user and ask if OK to transfer project to us.

Can't find an email to ask them anywhere, so would appreciate it if you could reach out. If OK then please transfer ownership to coflynn account.

## Actual Result

N/A

**Comment by safwanrahman** [comment]
Can you get the email address of @phonchi from the repositroy commit log?
https://github.com/phonchi/chipwhisperer

**Comment by colinoflynn** [comment]
I didn't think that github would be redacting the emails online, so didn't even try cloning it. Yes that worked - will see if it was the true/active email, I've just sent them a note!

I'll update this when I hear back (or if I don't hear back), as assume anything else would need RTD admin to process.

**Comment by colinoflynn** [comment]
Quick update - did receive an OK, please let me know how to proceed, Thanks.

**Comment by stsewd** [comment]
@colinoflynn you can check https://docs.readthedocs.io/en/latest/abandoned-projects.html I think you only need to ask him and that is.

**Comment by colinoflynn** [comment]
I had seen those instructions (why I opened the issue originally), but it wasn't clear how moving the project itself has possible? Do they just delete the project and I recreate it on the new account is best?

**Comment by humitos** [comment]
> Quick update - did receive an OK, please let me know how to proceed, Thanks.

Didn't he added you as a maintainer under the rtd project? If he agreed with you, you can ask him to grant you permissions. After that, you will have access to the project.

**Comment by stsewd** [comment]
> Do they just delete the project and I recreate it on the new account is best?

Not sure about that, I think if he adds you as maintainer is the same result

**Comment by stsewd** [comment]
I can see that you were added as a maintainer of the rtd project, closing. Feel free to reopen if that wasn't the case.
