### ISSUE TITLE
Stable version is stuck on a particular commit

### ISSUE THREAD

**Issue by andy-maier** [rtfd/readthedocs.org#4087]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-zhmcclient/
* Build URL (if applicable): https://python-zhmcclient.readthedocs.io/
* Read the Docs username (if applicable): andi0661

## Actual & Expected Results

We had an issue in the python-zhmcclient project with showing the correct version number of the RTD page, and did some test releases (on a separate github branch, using git tags). RTD updated its stable version accordingly (and correctly), since the new git tag had the latest version. At the end of solving our version issue, we removed the experimental git tags again.

Since then, the stable version as perceived by RTD is stuck on commit 94ce7344. That commit still exists in the upstream git repo.

When we did that, we were not aware that RTD has some issues in this area (for example see PR #3913), otherwise we would have been more careful. Sorry for that, but now the question for us is how do we get out of that situation.

Today, we brought the git repo into a state where commit 94ce7344 is in the commit chain for the next release, and we created tag 0.19.10 on that commit. That caused RTD to correctly build the stable version.

However, we then added a few more commits on top and assigned a tag for release 0.19.11, but the RTD stable version still points to commit 94ce7344, so it seems we are definitely in the state where the RTD stable version is stuck on a commit.

I have read that deleting the RTD project and re-creating it solves the issue.

My questions are:

1. If we go for deleting and re-creating the RTD project, will we be able to create the project again after having deleted it (Given the policy that RTD currently does not accept new projects)?
2. Are there any better (lighter) solutions to this issue that we can apply?

**Comment by stsewd** [comment]
> Are there any better (lighter) solutions to this issue that we can apply?

Did you try to wipe the environment (this can be done on the `Versions` section) before the build? maybe this is not part of #3913 but just old repo content.

> If we go for deleting and re-creating the RTD project, will we be able to create the project again after having deleted it (Given the policy that RTD currently does not accept new projects)

I don't understand that policy you mention, you can recreate your project with the same name :)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).

**Comment by humitos** [comment]
@stsewd isn't this issue solved by your PR #3913?

**Comment by stsewd** [comment]
@humitos how the problem starts I think a wipe would be enough, but if it was the same cause as the related bug it should be fixed in the next deploy anyway.

**Comment by andy-maier** [comment]
Hi, I'm sorry for not reacting on the request for more information. I verified today that the stable version of our project is recent on RTD, and also when releasing a new version of our project today, its stable version on RTD was built and is up to date now.

So it seems the new RTD version has solved the issue!

Thanks much!!

**Comment by humitos** [comment]
@andy-maier thanks for the update! I'm happy that your problem is solved ;)
