### ISSUE TITLE
Consistently failing builds with no helpful error message

### ISSUE THREAD

**Issue by julienmalard** [rtfd/readthedocs.org#4089]
## Details
Build fails during pre-build git operations.

* Read the Docs project URL: http://readthedocs.org/projects/tinamit
* Build URL (if applicable): http://readthedocs.org/projects/tinamit/builds/7186051/
* Read the Docs username (if applicable): julien.malard

## Expected Result
Successful build or helpful error message.

## Actual Result
`Error: There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7186051).
`

**Comment by humitos** [comment]
You are experimenting this issue: #3060, because of your unicode branch name: https://github.com/julienmalard/Tinamit/tree/%E6%98%9F%E8%B0%95

This should be probably fixed by #4052 

I'm closing here because of duplicated with a possible pending solution. Feel free to reopen if you consider.

**Comment by julienmalard** [comment]
Thank you! Any way to know when #4052 has been merged and is on the live site so that I can check if it worked?

**Comment by stsewd** [comment]
@julienmalard unfortunately we couldn't make it work for unicode tags in production, but it fixed other bug related to tags.

**Comment by julienmalard** [comment]
Thanks for letting me know. Any recommendations to get my project working again? I am only building documentation for the "master" branch.

**Comment by julienmalard** [comment]
FYI, this seems to be fixed now and unicode branch names are working fine!

**Comment by humitos** [comment]
Thanks for the update!
