### ISSUE TITLE
Remove unused field from Project model

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4092]
When removing the comments app from the codebase in https://github.com/rtfd/readthedocs.org/pull/3802. A field was missing to be removed, we need to remove this and make a migration.

https://github.com/rtfd/readthedocs.org/blob/696a25f9b3350bb047caf1899a876aa1aa0fcbaa/readthedocs/projects/models.py#L140-L143

**Comment by Alig1493** [comment]
I would like to take up this issue if no one else is doing it.

**Comment by stsewd** [comment]
@Alig1493 thanks for the interest, but there is a PR in progress already https://github.com/rtfd/readthedocs.org/pull/4097

**Comment by Alig1493** [comment]
@stsewd the PR seems closed for the time being. Will it be alright for me to look into it at this moment?

**Comment by stsewd** [comment]
@Alig1493 sure, feel free to send a PR

**Comment by Alig1493** [comment]
@stsewd I have already made some progress on this issue. Just a coupe of questions regarding the test cases pertaining to these two fields:
* should they be removed
* should they be changed accordingly

If it's the latter then I might end up needing some assistance in resolving them.

Thank you in advance.

**Comment by Alig1493** [comment]
@stsewd I've made a PR here https://github.com/rtfd/readthedocs.org/pull/4431
Any guidance regarding this would be much appreciated.
