### ISSUE TITLE
Project import remote repository sync doesn't sync when org selected

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4101]
Steps to reproduce it:

1. go to "Import Project"
1. filter by your service (i.e. GitLab)
1. you will see the list of your repos under that service
1. go to the service page (i.e. gitlab.com)
1. create a repo there
1. go back to RTD import page
1. click on sync

When sync is finished you won't see your new repository there to be imported as project. You will have to refresh the page or filter by another category and filter back by your username.

This is because when the sync finishes, there is no request made to 

    https://readthedocs.com/api/v2/remote/repo/?own=gitlab

where `own` is the filter selected.

**Comment by stsewd** [comment]
Actually, I think this never does the final request.
