### ISSUE TITLE
Support .yaml extension for our configuration file

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4102]
Currently we only support `.yml` extension, which make some users (including myself) to be confused.

Probably, we need to just modifiy this file (https://github.com/rtfd/readthedocs-build/blob/bf2d1267c9a3dfa0b94588f23549ec527d5d5532/readthedocs_build/config/config.py#L17) to add the new names with the `.yaml` extension.

(take into account that `.yaml` is the official extension of the YAML file: http://yaml.org/faq.html)

We need:

- [ ] modify that file pointed here
- [ ] update the docs to reflect the new file names
- [ ] test this manually
- [ ] write some unit tests

Related: #4100

**Comment by stsewd** [comment]
Maybe a `Good First Issue`?

**Comment by StefanoChiodino** [comment]
This seems easy enough for me to get me started...hopefully ;)

**Comment by StefanoChiodino** [comment]
Looking into this I've found mention of `environment.yml`, `mkdocs.yml`. No mention of `yaml` extension for those so either they have the same problem or they are not correctly documented. Would those be look at in another issue?

**Comment by agjohnson** [comment]
Also, the python YAML implementation will parse JSON as well, perhaps we extend the even further :)

**Comment by StefanoChiodino** [comment]
Just realised: is `.readthedocs.yaml` also valid?

**Comment by agjohnson** [comment]
@StefanoChiodino yup, that is valid, some folks liked the idea of keeping the file hidden
