### ISSUE TITLE
Sphinx custom theme support sporadically doesn't work

### ISSUE THREAD

**Issue by kklmn** [rtfd/readthedocs.org#4103]
## Details

* Read the Docs project URL: http://xrt.readthedocs.io/
* Build URL (if applicable): https://github.com/kklmn/xrt
* Read the Docs username (if applicable): konstantin.klementiev

## Expected Result

In my theme template I have default.css_t stylesheet that imports basic.css. I expect *my* default.css (not a generic one) in the _static directory, with all the imports properly done. 

## Actual Result

The actual default.css is not mine, it doesn't have style elements I've tuned myself. Ok, I've simply given it another name, now I got it. The import of basic.css has also become wrong (since yesterday, probably): the builder reports on ThemeError, complaining about a missing theme variable that actually does exist and is supported in the "basic" theme::

    sphinx.errors.ThemeError: unsupported theme option 'body_min_width' given

Now, instead of importing I've simply copied basic.css into mydefault.css_t. But all these "solutions" are just ugly. Please make the templating mechanism properly work, as it used to. Thanks!

**Comment by kklmn** [comment]
> I'm not quite sure why RTD is using 1.6 for your build.
I don't think it is. If instead of importing basic.css into my "mydefault.css_t" I copy-paste it, it still uses body_min_width but now without errors. So it looks like a problem of importing (templating).

**Comment by davidfischer** [comment]
In [this build](https://readthedocs.org/projects/xrt/builds/7201143/), it did.

**Comment by kklmn** [comment]
Yes, I see it now, you're right.

**Comment by davidfischer** [comment]
My current best guess is that there was some sort of deployment error and one of the builders didn't deploy correctly. The failures appear to be on build01. Successes are elsewhere.

**Comment by kklmn** [comment]
Ok, I see that this problem with ThemeError was temporary. The issue with not copying default.css is really minor, I will just keep it renamed.
Thanks!

**Comment by kklmn** [comment]
Thanks for pointing to the Sphinx version used in the failed build. Closed
