### ISSUE TITLE
Risen BuildEnvironmentError exception from projects.tasks.py are logged

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4109]
There are some BuildEnvironmentError exceptions that we are riseing inside of the `run_setup` and `run_build` which end user messages that are being logged into our Sentry as errors but they are not errors to be reported to us at all since are just messages to the user.

Example: https://github.com/rtfd/readthedocs.org/blob/84cefc40f00083cbc74a473ffb4ef890294159a1/readthedocs/projects/tasks.py#L388-L390

We should find the way to catch them from the context manager and do not log to Sentry (`log.error`).

**Comment by agjohnson** [comment]
We're consistently hitting sentry limits, so putting this on our next release milestone

**Comment by humitos** [comment]
I hit this again today.

I think we need to refactor our exceptions a little by creating specific `BuildEnvironmentError` for these cases and do not log them. For example,

https://github.com/rtfd/readthedocs.org/blob/fea0215bce79d8b7167b1d16eecddd525b6c7a3d/readthedocs/projects/tasks.py#L407-L426

Those three exceptions should be something like `BuildDisabledError`, `VersionLockedError` and `YAMLParsingError`. Then under our `__exit__` method we need to check for these specific exceptions and do not log them:

https://github.com/rtfd/readthedocs.org/blob/fea0215bce79d8b7167b1d16eecddd525b6c7a3d/readthedocs/doc_builder/environments.py#L448-L451
