### ISSUE TITLE
Our project admin inactive -> outdated Read the Docs

### ISSUE THREAD

**Issue by dvorapa** [rtfd/readthedocs.org#4110]
Hello,

with our project Pywikibot we also have the docs on Read the Docs. But the former admin of our project and of Read the Docs account is inactive for a long time and the docs on Read the Docs are horribly outdated (you can see our issue tracker task here: https://phabricator.wikimedia.org/T187008). **Is there a way to somehow hide those outdated docs from Read the Docs website** (in order not to mislead our users)**?** We already have our docs hosted on Wikimedia platform (https://doc.wikimedia.org/pywikibot/), therefore this doc clone is not really needed. Also the docs on Read the Docs are loaded from the inactive admin fork. That would be fine, until our project renamed to shorter name (from pywikibot-core to pywikibot) and his fork was therefore ripped off.

If this is not possible, I would like to ask you to update the docs from official repository (https://github.com/wikimedia/pywikibot) somehow.

Thanks for any of your help
Pavel Dvorak / Dvorapa

## Details

* Read the Docs project URL: https://readthedocs.org/projects/pywikibot/
* Build URL (if applicable): https://pywikibot.readthedocs.io/en/latest/
* Read the Docs username (if applicable): 

## Expected Result

Docs in sync with current release and current official repository or no docs on Read the Docs at all

## Actual Result

Horribly outdated docs there

**Comment by safwanrahman** [comment]
@dvorapa Can you please check the documentation and follow according to it?
http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by dvorapa** [comment]
Hello there, we finally reached one of the devs with an access by an email, so consider this as resolved :)
