### ISSUE TITLE
not latest version of rtd_theme while building site

### ISSUE THREAD

**Issue by StrikerRUS** [rtfd/readthedocs.org#4117]
## Details

* Read the Docs project URL: https://lightgbm.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/lightgbm/builds/7218315/
* Read the Docs username (if applicable):

## Expected Result

The last version of `rtd_theme` on the site.

## Actual Result

Theme version is limited by `sphinx-rtd-theme<0.3`:
![image](https://user-images.githubusercontent.com/25141164/40278064-df54512a-5c32-11e8-9730-18b02ca8ff8a.png)

Despite the fact that #4096 has been already merged, our latest build used old theme, and in consequence  `html_theme_options` parameter doesn't work.
Out `conf.py` is very simple and can be found [here](https://github.com/Microsoft/LightGBM/blob/master/docs/conf.py).

When the latest theme will be able by default?

**Comment by StrikerRUS** [comment]
Is it caused by that latest `release` was 19 days ago?

**Comment by davidfischer** [comment]
#4096 is scheduled for deploy tomorrow.

**Comment by StrikerRUS** [comment]
So the sites are built not from master branch, right?

**Comment by davidfischer** [comment]
What is in `rel` is what's deployed. When the site is deployed, `master` is merged into `rel`. Also you can always check the [changelog](https://github.com/rtfd/readthedocs.org/blob/master/CHANGELOG.rst) to see what's deployed.

**Comment by StrikerRUS** [comment]
`2.3.12` release fixed the problem. Thanks for the info and changelog link!
