### ISSUE TITLE
Builds pass but only generate HTML, no PDF or EPUB

### ISSUE THREAD

**Issue by dwasyluk** [rtfd/readthedocs.org#4118]
## Details

* Read the Docs project URL: http://syscoin-docs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/syscoin-docs/builds/7220403/
* Read the Docs username (if applicable): dwasyluk

## Expected Result

A PDF and EPUB download is generated with each build.

## Actual Result

No PDF or EPUB files are generated/built, and the build output seems to suggest only the HTML build is running.

**Comment by dwasyluk** [comment]
Looks like I need to use RST to get automatic PDF generation...

**Comment by RichardLitt** [comment]
Thanks for logging and following up with this, @dwasyluk!
