### ISSUE TITLE
Accumulate some test cases that we want tested around search

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4121]
Related to the work that @safwanrahman is taking on, it would be helpful for us to outline some of the test cases that we want to verify before making changes to tests. The most helpful tests for us are probably integration tests however. I'm not certain how we want to test this. Things that would be good to test are:

* Search term hit rate, for currently matching queries
* Search term miss rate, for currently unmatched queries or problematic queries we want to resolve
* Result return -- test subproject/superproject relationship return

**Comment by ericholscher** [comment]
I think:

* Test that main site search returns facets
  - Test that adding a facet query to that search filters properly (eg. only `File`'s from that `Project` are returned)
* Test that doc search properly filters to the project that you're searching
  - We could also add a test for "subproject" search. Currently we should be returning results for the current project, and and others that are linked to it. So we could set up a project & subproject, and then search and confirm that works. 

I can't think of any specific term queries that we want to test for, though I'm sure there will be some based on open issues. Users are pretty good at coming up with queries that _should_ work :)

**Comment by agjohnson** [comment]
I did start documenting some from customers, i can fish up some misses. One found so far:

> How can we set the system to allow for exact phrase searching, i.e., “heat maps” in read the docs?
>
> Putting quotes around phrase doesn’t help. In the above example, it shows us everything that has “heat” and “map” separately, when we only want pages that have then together to show up.

I know there are other misses

**Comment by ericholscher** [comment]
We've added some initial search test cases -- this ticket is mostly calling for more specific regression type tests, so I'm going to keep it open, and see about adding them as we address the issues.

**Comment by ericholscher** [comment]
Going to close this, as we now have a number of smaller issues for tests around search functionality. We should put more specific issues as we come across things we need.
