### ISSUE TITLE
Evaluate django-elasticsearch-dsl

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#4128]
We might be able to simplify our integration with Elastic Search using existing tools.

Look at https://github.com/sabricot/django-elasticsearch-dsl to see if it makes sense.

**Comment by xrmx** [comment]
Probably using https://github.com/elastic/elasticsearch-dsl-py will simplify enough code you won't need more wrappers.

**Comment by safwanrahman** [comment]
@ericholscher [ImportedFile](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L887) does not include the json we use for indexing search. Should I create another model for including the json file or should add in `ImprotedFile`?

**Comment by ericholscher** [comment]
We don't want to store the JSON in the database -- it would vastly increase the size of the data we'd have to store, so it's not a goal. What do you need the JSON in the DB for?

**Comment by safwanrahman** [comment]
@ericholscher In my last comment I meant, "in `ImprotedFile`, only the `html` and `txt` file path is stored. But currently, there are no model where `json` file path is stored."
As we do not store the json file path in anywhere into database, Should I create another model where the json files path is stored or store the path in `ImprotedFile` model.

I did not mean storing content of json file. Only path, name and other information as we needed.

**Comment by ericholscher** [comment]
Going to call this done, as we have successfully used it in the prototype (#4183)
