### ISSUE TITLE
Problem Building Documentation (build id 7231626)

### ISSUE THREAD

**Issue by NathanielHoefer** [rtfd/readthedocs.org#4130]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ref-master/
* Build URL (if applicable):
* Read the Docs username (if applicable): NathanielHoefer

I am new to ReadTheDocs and after attempting to build the latest version of my project, I receive a generic error described below. 

## Expected Result

A successful build

## Actual Result

Build failure with the following response:
"There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7231626)."

**Comment by stsewd** [comment]
This is because you have an unexisting submodule https://github.com/NathanielHoefer/ref-master/blob/89659eba87d5a03c9b093ce14aecd552505801a5/.gitmodules#L1-L3, so rtd is very strict with that.

**Comment by NathanielHoefer** [comment]
That's exactly what it was. Thank you for assisting me!
