### ISSUE TITLE
Search Feature Doesn't Return Pages

### ISSUE THREAD

**Issue by NathanielHoefer** [rtfd/readthedocs.org#4144]
## Details

When compiling the documents locally, the search feature works as expected, however when compiled by ReadTheDocs, the search feature doesn't return any pages. 

* Read the Docs project URL: https://readthedocs.org/projects/nathaniel-reference/
* Build URL (if applicable): https://nathaniel-reference.readthedocs.io/en/latest/
* Read the Docs username (if applicable): Nathaniel Hoefer

## Expected Result

When utilizing the search feature found in the top left corner of my webpage, the pages with the searched keyword to be listed

## Actual Result

No associated pages are listed, no matter the search.

**Comment by stsewd** [comment]
I just search something on your project and it works as expected. Maybe a cache issue?

![screenshot-2018-5-24 search nathaniel hoefer reference 1 0 documentation](https://user-images.githubusercontent.com/4975310/40516938-924e135e-5f78-11e8-8575-8dc92b6f5862.png)

**Comment by NathanielHoefer** [comment]
That's exactly what it was. Thanks for your help!
