### ISSUE TITLE
Broken link to your help

### ISSUE THREAD

**Issue by coffeedogs** [rtfd/readthedocs.org#4148]
While [editing my project]( https://readthedocs.org/dashboard/my-pybitmessage-fork/edit/) I clicked the `Type of documentation you are building. [More info](http://www.sphinx-doc.org/builders.html#sphinx.builders.html.DirectoryHTMLBuilder)` but get a 404.

**Comment by stsewd** [comment]
Thanks for reporting! I think the link should be http://www.sphinx-doc.org/en/stable/builders.html#sphinx.builders.html.DirectoryHTMLBuilder.

The helptext is in 

https://github.com/rtfd/readthedocs.org/blob/2f5ae97d543f1c8051a3e1b708b63f7b858b3015/readthedocs/projects/models.py#L132-L137

We also need to do a migration after the change.
