### ISSUE TITLE
please update translations

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#4152]
@francescozaia kindly completed the italian translation so it would be cool to have it available :). I suppose it's the same for other languages. Thanks!

BTW i don't see the transifex client in any requirements.

**Comment by francescozaia** [comment]
Actually, there are [many translations that are ready to be reviewed](https://www.transifex.com/readthedocs/readthedocs/dashboard/) on Transifex, but they might need a review. I also sent a message to the italian translation coordinator @ojii with no luck. 😭

**Comment by RichardLitt** [comment]
Could there be a process for maintainers to easily review this in the future, so that we don't end up with a build-up of translations that aren't reviewed? At the moment, I'm unsure of how I can help, as a community member.

**Comment by xrmx** [comment]
To move things forward it may help would be to promote active translators to reviewers, no clue if you can do that as RTD developers or not though.

**Comment by agjohnson** [comment]
👍 from me. I think there are a few things that we need:

* A call out for translation reviewers in our docs/elsewhere
* Translation sources and updating transifex should be a more frequent process. Maybe in our CI?
* Local translation files should be updated as a normal part of our release process

Getting reviewers is tricky, but something we could promote more if our translation support was better.

**Comment by agjohnson** [comment]
For instance, in order to approve the italian translations, I need someone to review all the translations. The italian translation team on transifex has a few people, but no reviewers. I'm not sure the best way to recruit or manage community there.

It's too bad github doesn't natively support a similar feature, as i'd prefer not to have 2 separate communities.

**Comment by agjohnson** [comment]
Translations are all updated in #4645 and are updated on transifex
