### ISSUE TITLE
Python module not found by automodule.

### ISSUE THREAD

**Issue by mojochao** [rtfd/readthedocs.org#4154]
## Details

API documentation builds fine locally, but cannot find my `configaro.py` module when built by readthedocs

The configaro project (https://github.com/mojochao/configaro) contains a single top-level `configaro.py` module.  There are no project packages.  I have added the project directory to my `docs/source/conf.py` file.  

* Read the Docs project URL: https://readthedocs.org/projects/configaro
* Build URL (if applicable): https://readthedocs.org/projects/configaro/builds/7253700/
* Read the Docs username (if applicable): mojochao

## Expected Result

The https://configaro.readthedocs.io/en/latest/api.html page to contain the documentation from my `configaro.py` module when built by readthedocs.

## Actual Result

The https://configaro.readthedocs.io/en/latest/api.html page does not contain the documentation from my `configaro.py` module when built by readthedocs.

**Comment by mojochao** [comment]
Added a .travis.yml file configuring py3.6 builder and all is working now.

**Comment by RichardLitt** [comment]
Thanks for following up with this, @mojochao!
