### ISSUE TITLE
Which community leaders are requested to provide centos7 local deployment documents?

### ISSUE THREAD

**Issue by TelDragon** [rtfd/readthedocs.org#4155]
## Details

Do not use docker
The document provided now is only an Debian environment, and my environment is centos7, which involves many complex dependencies.

[#4122](https://github.com/rtfd/readthedocs.org/issues/4122)

**Comment by agjohnson** [comment]
We only support our production environment, which is Ubuntu 16.04, soon Ubuntu 18.04. We don't have the bandwidth to support more platforms. Feel free to submit a guide -- in our docs, under `/guides` if you have a working solution.
