### ISSUE TITLE
update doxygen?

### ISSUE THREAD

**Issue by mgiaco** [rtfd/readthedocs.org#4158]
Hi,

As I found out RTD uses doxygen version 1.8.11. Is it possible to update to the latest version? There is a newer version available. 

http://www.stack.nl/~dimitri/doxygen/manual/changelog.html

cheers
mathias

**Comment by stsewd** [comment]
So, we need to wait for the new docker image to be released wich use ubuntu 18.04 and maybe have a more recent version of doxygen

https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile#L2

**Comment by mgiaco** [comment]
Sounds great, many thanks
