### ISSUE TITLE
Unspecified error on new project

### ISSUE THREAD

**Issue by greschd** [rtfd/readthedocs.org#4161]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/phasemap/
* Build URL (if applicable): https://readthedocs.org/projects/phasemap/builds/7267555/
* Read the Docs username (if applicable): greschd

## Expected Result

ReadTheDocs should clone the repository and build the documentation.

## Actual Result

After the ``cat source/conf.py`` step, the build crashes with the generic error message "There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7267555)."

Maybe related: https://github.com/rtfd/readthedocs.org/issues/3732

**Comment by stsewd** [comment]
mmm, I imported your project on my local instance it fails in the pdf generation step, here you can check the logs

```
LaTeX Warning: Hyper reference `tutorial:phasemap-tutorial' on page 1 undefined
 on input line 90.


LaTeX Warning: Hyper reference `reference:phasemap-reference' on page 1 undefin
ed on input line 93.

[1 <./logo_on_white.png>] [2]
Chapter 1.
(/usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)

LaTeX Warning: Hyper reference `reference:phasemap.run' on page 3 undefined on 
input line 127.


LaTeX Warning: Hyper reference `reference:phasemap.run' on page 3 undefined on 
input line 129.

(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1ptm.fd)

LaTeX Warning: Hyper reference `reference:phasemap._box.Box' on page 3 undefine
d on input line 135.

(/usr/share/texlive/texmf-dist/tex/latex/psnfss/ts1pcr.fd)! Unable to read an entire line---bufsize=200000.
Please increase buf_size in texmf.cnf.
```

Can you try unchecking the pdf and epub generation for your project? (in case you don't really need that or also to confirm the error is there)

**Comment by greschd** [comment]
Unfortunately I still get an error with pdf and epub disabled: https://readthedocs.org/projects/phasemap/builds/7270680/

However, in hindsight it's obvious that pdf and epub won't work: The doc contains an mp4 video embedded with 

```
.. raw:: html

    <video width="500" controls="controls">
        <source src="_static/video.mp4" type="video/mp4" />
    </video>
```

Although that works with "bare" sphinx locally, maybe it's still the cause for the error in the html build?
