### ISSUE TITLE
Using "Sphinx Single Page HTML" Documentation type produces css-free output, and retroactively affects previous builds in the same way

### ISSUE THREAD

**Issue by bhouser** [rtfd/readthedocs.org#4162]
## Details

* Read the Docs project URL: private readthedocs.com project (https://knuddels-documentationtest.readthedocs-hosted.com/en/latest/)
* Build URL (if applicable):
* Read the Docs username (if applicable): bhouser

## Expected Result
I want to produce a build with with Settings -> Documentation Type set to "Sphinx Single Page HTML".  I expect the theme to load.

## Actual Result
The project builds.  But when I load the page, theme.css doesn't load.  It's not a failed HTTP Request for the CSS File: the file is not even requested.  The page appears to have no formatting at all.

In fact, selecting this setting retroactively breaks all of my previous build results.  If I switch "Documentation Type" back to "Sphinx HTML", all builds are retroactively fixed.

**Comment by stsewd** [comment]
Hi, this issue tracker is for the .org project, if you are using readthedocs.com, you should contact support there.

**Comment by bhouser** [comment]
I suppose I assumed that the software is so similar, that the .org project would have the same bug.  Sorry!  And thanks for the tip.

**Comment by bhouser** [comment]
Unfortunately I do not :(

**Comment by bhouser** [comment]
I think I now have a project on the org site, that has the same problem.  It's not my project, but most people have heard of it:
http://kernel.readthedocs.io/en/latest/

**Comment by bhouser** [comment]
I'm only guessing that this might be the same problem, since the symptoms appear to be the same.

**Comment by stsewd** [comment]
The problem on your project only happens when building as single html page? Because the kernel project is built as a muli html page. Also, it doesn't have a successful build in more than a year.

**Comment by bhouser** [comment]
I am so sorry ... it appears the kernel documentation has been moved here: https://www.kernel.org/doc/html/latest/index.html

So that was a false alarm.  The other URL I posted is probably not maintained anymore.  I found that page and thought it might be the same problem.
