### ISSUE TITLE
Override CSS with fork of `sphinx_rtd_theme`

### ISSUE THREAD

**Issue by wmayner** [rtfd/readthedocs.org#4163]
## Details

I have my own [fork of `sphinx_rtd_theme`](https://github.com/wmayner/sphinx_rtd_theme), and I'm trying to get the styles from my fork to override the default styles on readthedocs.org. I'm attempting to do this by using the upgrade flag (#4156) to replace the upstream `sphinx_rtd_theme` with my fork in my project's environment.

However, it looks like the `theme.css` that's served is still the upstream version. How can I override the CSS properly?

* Read the Docs project URL: pyphi.readthedocs.io
* Read the Docs username (if applicable): wmayner

## Expected Result

`theme.css` from my fork should be served.

## Actual Result

`theme.css` from upstream is served instead.

**Comment by davidfischer** [comment]
I'm pretty sure this is due to the optimization that replaces the theme CSS/JS with centralized versions on readthedocs.org. See this: https://github.com/rtfd/readthedocs-sphinx-ext/pull/39 and https://github.com/rtfd/sphinx_rtd_theme/pull/614

**Comment by wmayner** [comment]
Thanks—looks like it should work as expected when/if those get merged.

**Comment by stsewd** [comment]
@wmayner the attached PRs were merged and released. You can check now :)

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
