### ISSUE TITLE
Version link in lower left not working

### ISSUE THREAD

**Issue by xylar** [rtfd/readthedocs.org#4175]
## Details

* Read the Docs project URL: http://mpas-analysis.readthedocs.io/en/master/
* Build URL (if applicable): https://readthedocs.org/projects/mpas-analysis/builds/7273820/ (probably not relevant, as the issue applies to all recent builds)
* Read the Docs username (if applicable): xylar

## Expected Result

The link in the lower left corner of our Read the Docs page could be used to switch between versions.

## Actual Result

The text is there but clicking on it does not bring up the list of available versions as expected.  I have seen the same result on another Read the Docs page, http://xarray.pydata.org/en/stable/, so I'm pretty sure this isn't an issue specific to our project.  I primarily use Chrome but also tried Firefox to see if it was a browser issue.  I also tried both Ubuntu and Windows 10 so I'm confident the issue isn't on my side.

**Comment by stsewd** [comment]
Thanks for reporting, the team is working on fixing this.

**Comment by stsewd** [comment]
This was fixed with the new release.
