### ISSUE TITLE
GitLab login and account connection are broken

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4179]
There seems to be a problem with `django-allauth` and the return from gitlab. I get a 500 error on attempting to connect or reconnect my account, and can't login. Didn't test signup.

```
KeyError: 'id'
  File "django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "newrelic/hooks/framework_django.py", line 544, in wrapper
    return wrapped(*args, **kwargs)
  File "allauth/socialaccount/providers/oauth2/views.py", line 73, in view
    return self.dispatch(request, *args, **kwargs)
  File "allauth/socialaccount/providers/oauth2/views.py", line 134, in dispatch
    response=access_token)
  File "allauth/socialaccount/providers/gitlab/views.py", line 34, in complete_login
    extra_data.json()
  File "allauth/socialaccount/providers/base.py", line 86, in sociallogin_from_response
    uid = self.extract_uid(response)
  File "allauth/socialaccount/providers/gitlab/provider.py", line 25, in extract_uid
    return str(data['id'])
```

**Comment by humitos** [comment]
I couldn't replicate this issue in production (.org and .com)

I actually tested login with the three social services we support and it worked.

**Comment by humitos** [comment]
After login with gitlab, I disconnected my account. Log out. Reconnect the gitlab account. Log out and log in without problems.

The only issue that I'm seeing here is that I have to authorize the RTD.org app each time that I login with gitlab :/

**Comment by davidfischer** [comment]
> The only issue that I'm seeing here is that I have to authorize the RTD.org app each time that I login with gitlab :/

I'm seeing the same which is weird. However, I am also able to connect, disconnect, and login without any other issues.

**Comment by agjohnson** [comment]
Aha!

```
{
u'message': u'403 Forbidden  - You must accept the Terms of Service in order to perform this action. Please access GitLab from a web browser to accept these terms.'
}
```

This was returned from the gitlab api

**Comment by agjohnson** [comment]
Yup! By logging in to GitLab, I was immediately prompted to accept the ToS. Accepted resolved the bug.

Closing this as this is an edge case I don't think we really need to handle.
