### ISSUE TITLE
Build option for HTML zip with standalone files (not `singlehtml`)

### ISSUE THREAD

**Issue by akien-mga** [rtfd/readthedocs.org#4190]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/godot-fr
* Build URL (if applicable): https://readthedocs.org/projects/godot-fr/builds/7301006/
* Read the Docs username (if applicable): Akien

## Proposal

I would like an option (either in the project settings or in the [Read the Docs YAML config](https://docs.readthedocs.io/en/latest/yaml-config.html)) to change the `singlehtml` HTML zip build and download option to a standalone `html` HTML zip.

For big documentation like Godot's, the latter is more practical, as the former generates a single `index.html` of many MBs, and RTD even fails building it at times due to exceeding RAM limits.

Using the `html` build option for the downloadable zip should also remove the need for one build job, as the same files used for the web version could be packed into this zip.

Note: I might have missed the option if it exists already, but so far I only saw the option to disable the `singlehtml` zip altogether in the YAML config (which I'll use for now to speed up my builds).

**Comment by humitos** [comment]
There is a related issue at #3242

**Comment by stsewd** [comment]
Actually, it's a duplicated of #3242, @akien-mga if this is something else let me know!

**Comment by akien-mga** [comment]
It's the same issue indeed, thanks!
