### ISSUE TITLE
can not build

### ISSUE THREAD

**Issue by rom38** [rtfd/readthedocs.org#4191]
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7301518).

**Comment by stsewd** [comment]
Please provide all the information suggested by the template

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :).
