### ISSUE TITLE
autoclass not working, but no warnings or errors in log

### ISSUE THREAD

**Issue by robmoss** [rtfd/readthedocs.org#4208]
## Details

* Read the Docs project URL: http://epifx.readthedocs.io/en/latest/getting_started.html#forecast-summaries
* Build URL (if applicable): https://readthedocs.org/projects/epifx/builds/7306664/
* Read the Docs username (if applicable): robmoss

## Expected Result

When I build the documentation locally, I see:

![epifx-docs-local](https://user-images.githubusercontent.com/5481883/41146617-3dcf75e0-6b47-11e8-95b4-6175a861550b.png)

## Actual Result

When it builds on RTD, the result is:

![epifx-docs-rtd](https://user-images.githubusercontent.com/5481883/41146631-4bab450e-6b47-11e8-86c7-cacd4b19fd28.png)

The only error or warning in the build log is:

`copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist`

So I have no idea what might be causing this.

**Comment by stsewd** [comment]
I think you need to mark the option to install your project inside the virtualenv https://docs.readthedocs.io/en/latest/faq.html#can-i-document-a-python-package-that-is-not-at-the-root-of-my-repository

**Comment by robmoss** [comment]
I've tried that, but installing the project in a virtual environment fails because it can't install scipy:

`Running scipy-1.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-wlwgiltd/scipy-1.1.0/egg-dist-tmp-yp4yf4ya /tmp/easy_install-wlwgiltd/scipy-1.1.0/setup.py:375: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates warnings.warn("Unrecognized setuptools command, proceeding with " Traceback (most recent call last): File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 157, in save_modules yield saved File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 198, in setup_context yield File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 248, in run_setup DirectorySandbox(setup_dir).run(runner) File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 278, in run return func() File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 246, in runner _execfile(setup_script, ns) File "/home/docs/checkouts/readthedocs.org/user_builds/epifx/envs/latest/lib/python3.5/site-packages/setuptools/sandbox.py", line 47, in _execfile exec(code, globals, locals) File "/tmp/easy_install-wlwgiltd/scipy-1.1.0/setup.py", line 474, in <module> File "/tmp/easy_install-wlwgiltd/scipy-1.1.0/setup.py", line 450, in setup_package ImportError: No module named 'numpy'`

**Comment by stsewd** [comment]
I'm not sure about that, putting it the requirements.txt doesn't work? If  it is for a C dependency, you can see https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

You may try conda too https://docs.readthedocs.io/en/latest/conda.html

**Comment by robmoss** [comment]
Thanks, I'll try that out. I'm confused though, the documentation did build correctly until (somewhat) recently:

https://epifx.readthedocs.io/en/0.5.4/getting_started.html#forecast-summaries

**Comment by robmoss** [comment]
No, removing numpy and scipy from `install_requires` and installing into a virtualenv doesn't fix this, the autoclass content is still missing and there are no warnings or errors apart from static files one noted in my original report.

**Comment by robmoss** [comment]
The last known-good build was on October 25, 2017:

https://readthedocs.org/projects/epifx/builds/6179336/

Since that build, the only changes to build/configuration files (such as setup.py and the Spinx configuration file) were to bump the version number from 0.5.5 to 0.5.6.

**Comment by robmoss** [comment]
Would you like me to close this bug report, since it's caused by a bug in Sphinx?

**Comment by stsewd** [comment]
Thanks for finding the root of the problem, I think we can keep this open till we update the default Sphinx version, btw, you can pin to a recent version of Sphinx too.

**Comment by robmoss** [comment]
No worries. And yes, good point about pinning a newer version of Sphinx.

**Comment by tuttelikz** [comment]
checking logs for warnings helped me: the reason was i didn't define one dependency in requirements file for pip
