### ISSUE TITLE
Read The Docs automodule not working when I'm building it with rtd. but works when I build it with **make html** command

### ISSUE THREAD

**Issue by jtpaquet** [rtfd/readthedocs.org#4210]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/picamera-gui/
* Build URL (if applicable): https://readthedocs.org/projects/picamera-gui/builds/
* Read the Docs username (if applicable): jtpaquet (github)

Hi,
I'm having trouble documenting a class with the autoclass command. I specified where are my source files and I don't get import errors that tell me Sphinx is not finding my module. I think I'm getting this part right because when I go in the docs folder and I enter the command:
`
$ make html
`
the html files build well and I get what I want, which is this class documented.

![make html](https://user-images.githubusercontent.com/26312569/41177412-f9b2c43a-6b31-11e8-9973-94b806699702.png)

When I build it with Read The Docs to have it hosted on https://picamera-gui.readthedocs.io/en/latest/code.html#picameragui-py, I don't get any error, but the class is not displayed. 

![build rtd](https://user-images.githubusercontent.com/26312569/41177466-361d1466-6b32-11e8-8613-b2205a881b24.png)

In the admin settings of my Read The Docs project, I specified a requirements.txt file that I built with 
`
$ pip freeze > requirements.txt
`
![admin settings](https://user-images.githubusercontent.com/26312569/41177789-5831269a-6b33-11e8-997b-266217717cdd.png)

I also didn't check the *Install your project inside a virtualenv using setup.py install* box because I don't have a setup.py file in my folder and I don't know how I can install a virtual environment. When I check the box, I get this error in my Read The Docs builds

![setup py](https://user-images.githubusercontent.com/26312569/41177776-4c1dfcb6-6b33-11e8-97c0-349d9e5c2999.png)

I think I'm missing something and if somebody knows rapidly what I'm doing wrong, it would be great.

If I forgot information that might help you finding my problem, here is my deposit:
https://github.com/jtpaquet/PiCamera-GUI

Thank you,
Jérémy Talbot-Pâquet

PS: Sorry for the documentation in French

**Comment by stsewd** [comment]
You have a warning in your build https://readthedocs.org/api/v2/build/7316389.txt line 558

```
WARNING: autodoc: failed to import class u'PiCameraGUI' from module u'PiCameraGUI'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/envs/latest/local/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 140, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/checkouts/latest/picamera-gui/PiCameraGUI.py", line 12, in <module>
    from picamera import PiCamera
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/envs/latest/local/lib/python2.7/site-packages/picamera/__init__.py", line 72, in <module>
    from picamera.exc import (
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/envs/latest/local/lib/python2.7/site-packages/picamera/exc.py", line 41, in <module>
    import picamera.mmal as mmal
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/envs/latest/local/lib/python2.7/site-packages/picamera/mmal.py", line 47, in <module>
    from .bcm_host import VCOS_UNSIGNED
  File "/home/docs/checkouts/readthedocs.org/user_builds/picamera-gui/envs/latest/local/lib/python2.7/site-packages/picamera/bcm_host.py", line 47, in <module>
    _lib = ct.CDLL('libbcm_host.so')
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libbcm_host.so: cannot open shared object file: No such file or directory
```

I think you need this https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by jtpaquet** [comment]
Thanks a lot! I didn't think there was any problems, because it was building. I already had my packages imported this way, but i forgot to add 'picamera'. Here in my ``conf.py``.

![solved](https://user-images.githubusercontent.com/26312569/41236970-629383f6-6d60-11e8-90db-708945343643.png)

It was probably building with ``make html`` because Python was able to locate the 'picamera' package, but Read The Docs didn't beacause I didn't specify it.

If anybody has their project building with the ``make html`` command, but not with Read The Docs, click on view raw in your Read The Docs build to ensure there is not something missing.

**Comment by yangliu2** [comment]
You need to include your package link from github in `requirements.txt` file inside of the `docs` folder. If ReadTheDoc doesn't have access to your code, then it can't do autodoc. You would think they would have the code since they already pulled from github, but they don't. My inspiration came from this page. https://github.com/readthedocs/readthedocs.org/issues/7156
