### ISSUE TITLE
Refactor to use yamale for configuration parsing/validation

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4214]
We discussed this in #4181 but didn't come up with any significant reasons to throw out our current validation patterns. This still might be a win, but we'll focus on implementations first.

This is set to low priority and will only be a refactor at the end of the project, if we find a need for it.

Refs #4181 

Required work:
- [ ] Create new validators for any field types that aren't handled (path was one, but we might also need cross-field validators?)
- [ ] Support python versions by build image (related to ^)
- [ ] We should be able to surface errors directly to users, so these would need to match or exceed the verbosity of the current messages
- [ ] Likely extend the current validator classes to use better error reporting
- [ ] Or, possibly extend the yamale base validator to throw exceptions directly -- not just strings. This way we can get: line number, type of failure, failure string, etc.
- [ ] Move schema out of test fixtures
- [ ] Replace parsing/validation with new yamale pieces
- [ ] Replace config tests with new validator tests
- [ ] Remove string based tests for validator tests and test exceptions

**Comment by stsewd** [comment]
With the new stuff added around config module, I think this would be a heavy refactor. So, probably we can close this, maybe consider using an external lib for v3 p:

**Comment by agjohnson** [comment]
Sounds good!
