### ISSUE TITLE
autoclass works locally but not on rtd

### ISSUE THREAD

**Issue by aminzarshenas** [rtfd/readthedocs.org#4223]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bca/
* Build URL (if applicable): https://readthedocs.org/projects/bca/builds/7328757/
* Read the Docs username (if applicable): aminzarshenas
Project doc URL: https://github.com/aminzarshenas/bca/tree/master/doc

## Expected Result

When I locally go to the doc folder in my project and do: 

make latexpdf 

It works perfectly and the documentation for the class and its members are created in the .pdf file. 
Note that the class name is BCA and is defined in bca.py in bca/bca of my project. 
The .rst file for the documentation of the class is in bca/doc and its name is api.rst

## Actual Result

When I import the same project in rtd and build it, I do not get any errors and build is passed.
I can see other pages of my documentation (e.g., introduction) but the api page does not show the autoclass docs (https://bca.readthedocs.io/en/latest/api.html).

I tried couple of hints from other issues including giving access to virtual env, checking the install my project inside virtual env, adding "../..", "..", and "." to sys.path in conf.py, etc. But none of them work.

I appreciate any help or hints on this matter.

**Comment by stsewd** [comment]
Your build has some warnings

```
/home/docs/checkouts/readthedocs.org/user_builds/bca/checkouts/latest/doc/api.rst:89: WARNING: failed to import fit
/home/docs/checkouts/readthedocs.org/user_builds/bca/checkouts/latest/doc/api.rst:89: WARNING: failed to import get_params
/home/docs/checkouts/readthedocs.org/user_builds/bca/checkouts/latest/doc/api.rst:89: WARNING: failed to import predict
/home/docs/checkouts/readthedocs.org/user_builds/bca/checkouts/latest/doc/api.rst:89: WARNING: failed to import set_params
```

You can see your build logs with more detail in https://readthedocs.org/api/v2/build/7328757.txt

By the way, I can see the docs generated


![screenshot-2018-6-11 api documentation bca 0 1 0 documentation](https://user-images.githubusercontent.com/4975310/41266504-d1c4e7d6-6dbc-11e8-9651-20a535c91da5.png)

**Comment by aminzarshenas** [comment]
@stsewd Thank you for checking that and mentioning the warnings. I have noticed the warnings too but I was not able to fix them. 

It is very weird that I was not able to see the doc (API Documentation) before but now all of a sudden it is perfectly fine.

**Comment by stsewd** [comment]
@aminzarshenas can we close the issue, then?

**Comment by aminzarshenas** [comment]
@stsewd yes, please. Thank you very much.
