### ISSUE TITLE
Build fails after (recursive) clone, before git submodule sync

### ISSUE THREAD

**Issue by svenevs** [rtfd/readthedocs.org#4227]
## Details

The same mysterious build error occurs on the main project, as well as the test project.  "Fake NanoGUI" is the test project which I have admin access to, but I will include links to both build errors in case it is helpful.

* Read the Docs project URL:
    - https://readthedocs.org/projects/fake-nanogui/ and
    - http://readthedocs.org/projects/nanogui/
* Build URL (if applicable):
    - Fake NanoGUI: https://readthedocs.org/projects/fake-nanogui/builds/7329568/
    - NanoGUI: http://readthedocs.org/projects/nanogui/builds/7039066/
* Read the Docs username (if applicable): `sjm324`

## Expected Result

Docs build as normal.

## Actual Result

> There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7329568).

Unfortunately, the log gives little to no information about the actual failure.  It's a C++ project without any `setup.py` (which is disabled in the configs).  On the Fake NanoGUI one I'm working on a PR to merge in there, so I added a `.readthedocs.yml` to try and run some form of matrix testing.  I tried every combination of the `image` with py 2 and 3: `image: {1.0,2.0,latest} x python: {2,3}`, [every build failed on that with the same results](https://readthedocs.org/projects/fake-nanogui/builds/).

I can't help but think that it has to do with recursive cloning and submodules.  Do the system logs show anything more fruitful?  Each new build was done after a clean (wipe) of the `custom_fonts` branch, and the build errors occur with or without a `.readthedocs.yml`.

Thanks for any help :)

**Comment by stsewd** [comment]
The error is probably because you don't have this submodule

https://github.com/svenevs/nanogui/blob/885e4fccc69bbfdd4c527009eef8ed33641d9765/.gitmodules#L7-L9

https://github.com/svenevs/nanogui/tree/master/ext

(rtd uses gitpython which is very strict with unexisting submodules)

**Comment by svenevs** [comment]
How very interesting!  Thanks @stsewd you hit it right on the nose.

It's interesting that this surfaced recently, the GLEW submodule has been gone I think over a year now, possibly longer.  Nonetheless, it is fixed and building now, so future readers if you exist I deleted lines from `.gitmodules` that were not applicable anymore (that commit might be getting force pushed away).
