### ISSUE TITLE
Problem building project on fresh install

### ISSUE THREAD

**Issue by jrobert2** [rtfd/readthedocs.org#4238]
I've installed a fresh rtd instance in docker behind a proxy like this : 

```
FROM python:2
ARG proxy
ENV http_proxy $proxy
ENV https_proxy $proxy
ENV no_proxy "localhost,127.0.0.1"

RUN git clone https://github.com/rtfd/readthedocs.org.git
WORKDIR readthedocs.org
RUN pip install -r requirements.txt
RUN python manage.py migrate
RUN python manage.py loaddata test_data

```

It runs well untill i try to build a project (any). I get : 
```

 python /readthedocs.org/user_builds/test_project/envs/latest/bin/pip install --use-wheel --upgrade --cache-dir /readthedocs.org/user_builds/test_project/.cache/pip Pygments==2.2.0 setuptools<40 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.7.4 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<0.6
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --use-wheel 
```

I've found that : ``--use-wheel``  is deprecated [since pip 7](https://pip.pypa.io/en/stable/news/#id25) (in favor of --only-binary) and removed since[ pip 10 beta 1 ](https://pip.pypa.io/en/stable/news/#b1-2018-03-31 )

Removing --use-wheel from the code ( /readthedocs/rtd_tests/tests/test_doc_building.py  and /readthedocs/doc_builder/python_environments.py ) fixes the problem in my situation.

Is it the right thing to do ?

**Comment by stsewd** [comment]
That's because of your pip version, rtd uses a lower version in production.

Also see https://github.com/rtfd/readthedocs.org/pull/4206

**Comment by stsewd** [comment]
> I've found that : --use-wheel is deprecated since pip 7 (in favor of --only-binary) and removed since pip 10 beta 1

I didn't know that, I think we can merge the above PR after all. I thought this was only in the last version.

**Comment by jrobert2** [comment]
Ok, great, thanks !

**Comment by stsewd** [comment]
Closed in https://github.com/rtfd/readthedocs.org/pull/4206
