### ISSUE TITLE
Builds failing due to up to date packages not being available

### ISSUE THREAD

**Issue by jacobtomlinson** [rtfd/readthedocs.org#4246]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/opsdroid
* Build URL (if applicable): https://readthedocs.org/projects/opsdroid/builds/7347736/
* Read the Docs username (if applicable): jacobtomlinson

## Expected Result

Builds successfully

## Actual Result

All my latest builds are failing with the following error

```
python /home/docs/checkouts/readthedocs.org/user_builds/opsdroid/envs/latest/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/opsdroid/.cache/pip -r/home/docs/checkouts/readthedocs.org/user_builds/opsdroid/checkouts/latest/requirements.txt
Collecting aiohttp==3.3.2 (from -r /home/docs/checkouts/readthedocs.org/user_builds/opsdroid/checkouts/latest/requirements.txt (line 1))
  Could not find a version that satisfies the requirement aiohttp==3.3.2 (from -r /home/docs/checkouts/readthedocs.org/user_builds/opsdroid/checkouts/latest/requirements.txt (line 1)) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp==3.3.2 (from -r /home/docs/checkouts/readthedocs.org/user_builds/opsdroid/checkouts/latest/requirements.txt (line 1))
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

The package `aiohttp` at version `3.3.2` is available on pypi however it fails to install on readthedocs, perhaps there is some caching going on which is out of date.

Also I don't actually need the library to be installed to build the docs, however disabling `Install your project inside a virtualenv using setup.py install` under the Advanced Settings doesn't seem to stop this happening.

**Comment by stsewd** [comment]
I'm not sure why the package isn't found, but about the other issue, is because rtd tries to found a `requirements.txt` file and install it. You can create an empty requirements file and point to that in the admin section.

**Comment by jacobtomlinson** [comment]
Thanks for the suggested workaround @stsewd. It would be great if we could just turn it off in the settings rather than having to introduce a random empty file into our project though.

**Comment by stsewd** [comment]
I think there is an issue open for that (I couldn't find it), probably would be available using the configuration file.

**Comment by stsewd** [comment]
Found it https://github.com/rtfd/readthedocs.org/issues/1621#issuecomment-388165551

**Comment by jacobtomlinson** [comment]
Yep it does seem related to that one. I'll do the workaround and close this issue in favour of #1621. Thanks again!

**Comment by maarcingebala** [comment]
Hey all, I've just stumbled upon the same issue in our project - our builds are failing due to RTD being not able to `pip install yarl==1.2.6`,  although such version exists and it's available on PyPi. I tried installing the package manually on my local using the same Python and Pip version as on RTD and it worked. Any idea what might be the issue?
