### ISSUE TITLE
Version missing in generated READTHEDOCS_DATA

### ISSUE THREAD

**Issue by kakulukia** [rtfd/readthedocs.org#4248]
## Details

Its a project an a self hosted version of RTD.
RTD creates a file called `readtehdocs-data.ja` which results from the function `generate-rtd-data` and should create the following:

    # Will be available in the JavaScript as READTHEDOCS_DATA.
    readthedocs_data = {
        'project': self.version.project.slug,
        'version': self.version.slug,
        'language': self.version.project.language,
        'page': None,
        'theme': "readthedocs",
        'builder': "mkdocs",
        'docroot': docs_dir,
        'source_suffix': ".md",
        'api_host': getattr(settings, 'PUBLIC_API_URL', 'https://readthedocs.org'),
        'commit': self.version.project.vcs_repo(self.version.slug).commit,
    }

Weird is that `project` is filled with the right project name (so self.version appears to be not None) and the `commit` is filled with the right commit hash, so self.version.slug should be filled also.

## Expected Result

`version` should be filled with the string "latest".

## Actual Result

`version` is an empty string, resulting in a broken call for the version chooser menu and totally breaking that functionality.

**Comment by kakulukia** [comment]
I can't put it on RTD.org since its a private repo.
I fixed it with a custom javascript snippet setting 

    READTHEDOCS_DATA.version = "latest"

Its still weird tho, but that works.

**Comment by RichardLitt** [comment]
Thanks for following up, @kakulukia :)
