### ISSUE TITLE
Compilation Passing with Layout completely bugged

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [rtfd/readthedocs.org#4252]
Hello dear friends,

I am one of the maintainer of the project [tensorlayer/tensorlayer](https://github.com/tensorlayer/tensorlayer), we noticed yesterday that RTD is messing up completely our builds for maybe a few days (we just noticed).

Unfortunately, if we try to compile old versions of the docs (which already worked and was working in the past), it is not working anymore.

**I have noticed a few bugs:**
- **stable** is built from the same commit as tag release **1.8.5**. Only the tag release is working ...
   - Tag: https://tensorlayer.readthedocs.io/en/1.8.5/
   - Stable: https://tensorlayer.readthedocs.io/en/stable/

- If I create a new branch pointing to the same situation as the tag release above (1.8.5)... It fails completely: https://tensorlayer.readthedocs.io/en/test_build_rtd/

- If we try to download the stable html/epub/pdf files, they point to a wrong release (1.8.5rc2).

- And btw the builds are passing without any error in **latest** and still giving this page which looks like we lost the whole template: https://tensorlayer.readthedocs.io/en/latest/

It looks like the project is broken or corrupted on RTD side due to inconsistent results... I have absolutely no ideas about what to do to recover from this.

For information, if we compile on our computers the documentation, we have absolutely no issue with the doc, it's nice and smooth. It really looks like a problem on RTD side with our project, any help would be much appreciated.

Thanks a lot for your help,

Jonathan

@zsdonghao @luomai @lgarithm you can follow the discussion here.

**Comment by DEKHTIARJonathan** [comment]
Maybe related to this: https://github.com/rtfd/readthedocs.org/issues/3715

**Comment by stsewd** [comment]
This is because you are using a custom theme, not the one that rtd provides

https://github.com/tensorlayer/tensorlayer/blob/5e61f27c9edbdeeb7e513ceabd977960b65996bf/docs/conf.py#L441-L442

https://github.com/tensorlayer/tensorlayer/tree/master/docs/_themes/sphinx_rtd_theme

See https://github.com/rtfd/readthedocs.org/issues/4249

**Comment by DEKHTIARJonathan** [comment]
Fixed the issue, thanks a lot 👍

**Comment by zsdonghao** [comment]
@stsewd thanks a lot
