### ISSUE TITLE
Rework around skipping a build

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4257]
Currently, we have something like `if project.skip: return None` in `prepare_build` which is then handled at `trigger_build` helper. It's not a really good workflow and we probably want to raise an exception instead and manage it in a proper way.

https://github.com/rtfd/readthedocs.org/blob/14942e9c1322a320ec3ecd34fe6a797e975d3a6f/readthedocs/core/utils/__init__.py#L98-L104

Additionally, we were thinking on managing this from a signal or similar that could be extended from outside. As an example, in .com we will probably be using something like `organization.disabled` where we will want to skip those builds also.

Also, the error message shown in the project detail page should be extended to show different messages depending on the skip reason. Currently, it's fixed to resource usage.

Ref: #4255

**Comment by stsewd** [comment]
Related https://github.com/rtfd/readthedocs.org/pull/4991
