### ISSUE TITLE
Better UX when `git checkout` to a not existing branch/tag

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4259]
Sometimes we can end in a case where the user deletes a version in their repo and want to build that version in rtd. When this happens, the user needs to build a different available version.

Because of the order of the build process, a wipe isn't enough to solve this

- RTD will clone or update the repo as a first step
- Then, rtd will fetch the new versions (and deletions)
- RTD will checkout to the version that is going to build
  - RTD will fail here because executes `git checkout latest`
  - `latest` doesn't exist on the repo at the time (we updated the repo!)
- RTD will sync the versions with the data from the repo
   - This step never happens it the previous fails

This currently affects branches only and should affect tags after #4258 is solved

Raised in https://github.com/rtfd/readthedocs.org/pull/3913#issuecomment-395139718

**Comment by stsewd** [comment]
A solution can be: change the build process order

- clone or update the repo as a first step
- fetch the new versions (and deletions)
- sync the versions with the data from the repo
- checkout to the version that is going to build

But I'm not sure about the consequences of this change

https://github.com/rtfd/readthedocs.org/blob/9a4c45932cf6f1cf4f878e06e27d281f2cf24736/readthedocs/projects/tasks.py#L145-L147

**Comment by humitos** [comment]
I suppose that this issue will be solved by #4876, right?

**Comment by stsewd** [comment]
Yup, I forgot to linked it

**Comment by stsewd** [comment]
Actually no, this one will fix this https://github.com/rtfd/readthedocs.org/pull/4901
