### ISSUE TITLE
pip --only-binary=:all: option is not an exact replacement of --use-wheels

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4262]
On today's deploy we found that `mock==1.0.1` is not installable with `--only-binary=:all:` option but it was installable with the `--use-wheels`.

I tested this locally before deploying but it did work in my instance, so I was probably using a different version of pip or something like that. We are using pip 9.0.1 in production.

We need to keep discussing this.

For now, we revert the PR #4206 that introduces this change.
Revert PR at #4261

**Comment by humitos** [comment]
It seems like `--use-wheels` was like _prefer wheels_ instead of _force_ them. I think that maybe new pip versions do that by default and no option is needed.

**Comment by stsewd** [comment]
Ok, I couldn't find the changelog for this, but I found this in the docs

> Pip prefers Wheels where they are available. To disable this, use the --no-binary flag for pip install.
>
> If no satisfactory wheels are found, pip will default to finding source archives.

https://pip.pypa.io/en/stable/user_guide/#installing-from-wheels

So, we only need is to remove that option :).
