### ISSUE TITLE
save the environment if dependencies don't change

### ISSUE THREAD

**Issue by youkaichao** [rtfd/readthedocs.org#4263]
Hi, I'm wondering if you can consider saving the environment if the project dependencies don't change.

Package dependencies are supposed to be rather stable, so building the same environment for so many times is wasting time & computing resourse.

It's easy to detect whether the dependencies change or not, simply by checking the status of setup.py or readthedocs.yml.

Thanks for your wonderful website!

**Comment by stsewd** [comment]
The pip dependencies are cached, so the next time they aren't downloaded from internet, but reused from the cache. Also, to save disk space I have understood that rtd clean these resources regularly, so if you don't build your docs in a while, there isn't a cache and the dependencies are downloaded from internet.

**Comment by youkaichao** [comment]
so it's a tradeoff between computing resource and storage resource, and rtd think the storage resource is more valuable, right?

**Comment by stsewd** [comment]
I think is right to do it, I mean if you don't build your docs in some time there isn't a good reason to keep all that space in the servers, but if you build your docs every 5 minutes or so, the cache is used.

**Comment by stsewd** [comment]
Hope my explanation makes sense, we actually are searching for ways of reducing the disk space of the builders.
