### ISSUE TITLE
Port tests from pytest-describe to normal pytest tests

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4270]
The pytest-describe project seems abandoned, isn't compatible with a current version of pytest. We should port this tests. and delete the `pytest-describe` dependency to update `pytest` to a more current version.

Raised in https://github.com/rtfd/readthedocs.org/pull/4242/files#r195538134

**Comment by mashrikt** [comment]
Can we replace describe-blocks with class?
Like: def describe_validate_use_system_site_packages():
to: class ValidateUseSystemSitePackages:

**Comment by stsewd** [comment]
Yes, I was thinking the same, this issue is kind of blocked till we end the v2 of the configuration file https://github.com/orgs/rtfd/projects/2 (not sure if you can see the project).

**Comment by mashrikt** [comment]
I've made a PR for this, since I was working on it.
I understand it has to be merged later. Would still appreciate your review!

**Comment by ericholscher** [comment]
Fixed in #4429
