### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by dfranco** [rtfd/readthedocs.org#4275]
## Details

* Read the Docs project URL: http://readthedocs.org/projects/bacula-web/
* Build URL (if applicable): http://readthedocs.org/projects/bacula-web/builds/7369221/

## Expected Result

* Same result as here http://docs.bacula-web.org/en/v7.4.0/

## Actual Result

* Read the docs page's CSS (or something else) is broken. Please fix it asap.

Yesterday's docs build was broken on one of my branch, I suspected something wrong in this branch until I've built the stable branch.

Thanks for your help in advance

Best regards

**Comment by stsewd** [comment]
This is because you are using a custom theme, not the one that rtd provides

https://github.com/bacula-web/bacula-web/blob/65c733786d0c57ae6f7ee704176d099296e88dd6/docs/source/conf.py#L92

https://github.com/bacula-web/bacula-web/tree/master/docs/theme/sphinx_rtd_theme

See https://github.com/rtfd/readthedocs.org/issues/4249#issuecomment-397689901 for more information

**Comment by dfranco** [comment]
Hi @stsewd 

Thanks for your feedback
I manage to fix the problem with the theme.

I do have another question now
How can I add custom javascript code the to theme now ?

Best regards

**Comment by dfranco** [comment]
Is this something we still can use or not ?
https://docs.readthedocs.io/en/latest/guides/adding-custom-css.html

**Comment by stsewd** [comment]
Yeah, but it looks like that methods are deprecated, we should update our docs http://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx.application.Sphinx.add_js_file

**Comment by stsewd** [comment]
Actually, it is deprecated in sphinx 1.8 (we still use 1.7.x!)

**Comment by dfranco** [comment]
Hi @stsewd 
I'll use that method for my current branch.
On a proactive perspective, Is there any way to do it which is compatible with Sphinx version 1.8 and 1.7 ?
Thanks for your help

**Comment by RichardLitt** [comment]
Glad we could help, @dfranco. :) I'm closing this for now.
