### ISSUE TITLE
Page without CSS - WARNING: html_static_path entry ... does not exist

### ISSUE THREAD

**Issue by zonky2** [rtfd/readthedocs.org#4290]
## Details

* Read the Docs project URL: https://metamodels.readthedocs.io/de/latest/manual/extended/isotope.html
* Github page: https://github.com/MetaModels/docs-de/blob/de-2.0/manual/extended/isotope.rst

## Expected Result

I see the page without CSS-Styling

I found

```copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist```

with my conf.py

```
# -*- coding: utf-8 -*-
#
# MetaModels documentation build configuration file.
#
# This file is execfile()d with the current directory set to its
# containing dir.

import sys
import os
import sphinx_rtd_theme
from datetime import date

#sys.path.append(os.path.abspath('_ext/phpdomain'))
#sys.path.append(os.path.abspath('_ext/tk.phpautodoc/src'))

# -- General configuration ------------------------------------------------

extensions = [
    'sphinx.ext.intersphinx',
    #'sphinxcontrib-phpdomain',
    #'sphinxcontrib_phpautodoc',
]

templates_path = ['_templates']
source_suffix = '.rst'
master_doc = 'index'
project = u'MetaModels'
copyright = u'{:d}, <a href="https://now.metamodel.me/de/ueber-uns/team" title="Team MetaModels" target="_blank">Team MetaModels</a>'.format(date.today().year)
version = '2.0'
release = '2.0.0'
language = 'de'
exclude_patterns = ['_build', '_ext']
pygments_style = 'sphinx'

# -- Options for HTML output ----------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_path = ['_themes', ]
html_static_path = []
html_use_modindex = False
htmlhelp_basename = 'MetaModelsdoc'
html_favicon = '_img/favicon.ico'
html_last_updated_fmt = '%d.%m.%Y'

# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
  'papersize': 'a4paper',
  'pointsize': '10pt',
  'classoptions': ',openany,oneside',
  'babel' : '\\usepackage[german]{babel}',
}

latex_documents = [
  ('index', 'MetaModels.tex', u'MetaModels Documentation',
   u'Team MetaModels', 'manual'),
]

# -- Options for manual page output ---------------------------------------

man_pages = [
    ('index', 'metamodels', u'MetaModels Documentation',
     [u'Team MetaModels'], 1)
]

# -- Options for Texinfo output -------------------------------------------

texinfo_documents = [
  ('index', 'MetaModels', u'MetaModels Dokumentation',
   u'Team MetaModels', 'MetaModels', 'Online-Handbuch des Projektes.',
   'Miscellaneous'),
]

intersphinx_mapping = {
    'dcgeneral': ('http://contao-community-alliance.github.io/dc-general-docs/', None)
}
```

**Comment by davidfischer** [comment]
There appears to be an [older version of the RTD theme](https://github.com/MetaModels/docs-de/blob/de-2.0/_themes/sphinx_rtd_theme/layout.html) in your source and it is causing a conflict. Here's a comment explaining the problem: https://github.com/rtfd/readthedocs.org/issues/4249#issuecomment-397689901. If you remove that directory or override only the bits you need, things will start working again.

Do you remember why that duplicated theme was added? This is the third project where a copied version of the theme is in the source directory and I want to understand why. Were you following an old recommendation I am unaware of or something? I'm not trying to be snarky. I'm truly trying to get to the bottom of this.

**Comment by zonky2** [comment]
o.k. - I deleted the folder `/_themes/sphinx_rtd_theme` and now works fine

THX!

**Comment by stsewd** [comment]
Closing then, I'm also curious why people were having a local copy of the theme :thinking:
