### ISSUE TITLE
Build not respecting CPython 3.x Advanced Setting?

### ISSUE THREAD

**Issue by dkirkby** [rtfd/readthedocs.org#4293]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/skysim/
* Build URL (if applicable): https://readthedocs.org/projects/skysim/builds/7384015/
* Read the Docs username (if applicable): dkirkby

## Expected Result

Build uses CPython 3.x and finds the stdlib configparser.

## Actual Result

Build appears to use python 2.7 and does not find the required configparser package, as indicated by this line near the bottom of this [raw log](https://readthedocs.org/api/v2/build/7384015.txt):
```
Requirement already up-to-date: docutils>=0.11 in /home/docs/checkouts/readthedocs.org/user_builds/skysim/conda/latest/lib/python2.7/site-packages
```
There is some more discussion of this issue at astropy/package-template#334.

**Comment by dkirkby** [comment]
Thanks for the suggestion @stsewd.  I just tried that but it does not seem to make any difference. The new build log is [here](https://readthedocs.org/projects/skysim/builds/7389808/).

The `readthedocs.yml` I used for my latest build is [here](https://github.com/dkirkby/skysim/blob/503accecf7a1fdae7d96bc5ff42f403d7a386388/readthedocs.yml).  Is there some way to tell from the build log if this is being used?

**Comment by ericholscher** [comment]
You're using conda, which makes most of our other configuration stuff not work. You need to configure conda properly to make it work.

**Comment by stsewd** [comment]
I'm not familiar with conda, but I believe you need a `python` key https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

**Comment by bmorris3** [comment]
I'm having the same problem, and haven't figured out how to fix it. Any tips?

Thanks!

**Comment by stsewd** [comment]
Thanks for sharing the solution @bmorris3! Closing as this isn't a rtd problem, just a conda setting.
