### ISSUE TITLE
There was a problem with Read the Docs while building your documentation

### ISSUE THREAD

**Issue by tdb-alcorn** [rtfd/readthedocs.org#4299]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/q2/builds/7397259/
* Build URL (if applicable): https://readthedocs.org/projects/q2/builds/7397259/
* Read the Docs username (if applicable):

## Expected Result

Successful build.

## Actual Result

Build failed but the logs didn't show any error messages. A warning message above my build said:
```
Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7397259).
```
This build was triggered automatically when I changed the requirements.txt setting for my project. Immediately after triggering the build, I wiped the version because the build had been having problems with installing a package. My guess is that by wiping the project after a build has already begun, the process entered a weird failure mode.

I'm just putting this here as a courtesy because the error messaging asked me so politely.

**Comment by stsewd** [comment]
Thanks, this is already reported in https://github.com/rtfd/readthedocs.org/issues/3891
