### ISSUE TITLE
Using python3.6 to build

### ISSUE THREAD

**Issue by wqh17101** [rtfd/readthedocs.org#4301]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/matchzoo/
* Build URL (if applicable):https://readthedocs.org/projects/matchzoo/builds/7398199/
* Read the Docs username (if applicable):wqh17101
i want use python 3.6 to build so i create a .readthedocs.yml in my root dir
which is

 
```
build:
  image:latest

python:
  version: 3.6
```

## Expected Result
get a normal doc

## Actual Result
![default](https://user-images.githubusercontent.com/26429138/41904047-fe5e6f48-7969-11e8-91ce-5aa2d14f0f0e.png)
core dump

**Comment by stsewd** [comment]
Did you try building this locally? Does it work with py3.6?

**Comment by wqh17101** [comment]
Yes it works in my env py3.6 @stsewd

**Comment by stsewd** [comment]
Closing this as it was the same problem reported in https://github.com/rtfd/readthedocs.org/issues/4308 which was due to a tensorflow incompatibility.
