### ISSUE TITLE
Option to sign in with GitHub stopped working

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#4304]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable):
* Read the Docs username (if applicable): pllim

## Expected Result

Clicking "sign in with GitHub" would sign me in.

## Actual Result

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

**Comment by stsewd** [comment]
Mmm, I just tested this with my account and it works. Lets wait to someone who can see the logs

**Comment by humitos** [comment]
@pllim from the logs it seems that the rate limit was exceeded for a user (not sure that it's you) 42 minutes ago. Can you re-test login later? Please.

**Comment by pllim** [comment]
OK works now. Could be one of my colleagues from the same building... :woman_shrugging: 

Thanks for the clarification!
