### ISSUE TITLE
`stable` to point to long-lived release branch

### ISSUE THREAD

**Issue by mpharrigan** [rtfd/readthedocs.org#4305]
## Details

* Read the Docs project URL: http://docs.rigetti.com/en/stable/index.html
* Read the Docs username (if applicable): mpharrigan

## Expected Result

Under "Versions" in the RTD docs, it says

> Read the Docs supports two workflows for versioning: based on tags or branches. If you have at least one active tag, tags will take preference over branches when selecting the stable version.

Our project (https://github.com/rigetticomputing/pyquil) has a branch called `1.9` which we update with doc fixes. There is also a tag named `v1.9.0` that is set to inactive on RTD. There are other tags which are all disabled. I would expect `stable` to track the tip of branch `1.9`

## Actual Result

RTD builds docs for the `1.9` branch just fine but `stable` still points to the (inactive) `v1.9.0` tag

**Comment by stsewd** [comment]
Not sure about this, maybe is part of the bug solved in https://github.com/rtfd/readthedocs.org/pull/3913, or something else. Did you try wiping the environment before triggering a build? (Versions -> Edit -> Wipe)

**Comment by mpharrigan** [comment]
I wiped `latest`, `stable`, `1.9` and `v1.9.0` (this one is inactive) and triggered a build of `stable` but it re-built the tagged version instead of the tip of the `1.9` branch.

What's the time frame on deploying #3913?

**Comment by stsewd** [comment]
@mpharrigan hopefully in  one or two weeks I think, as you can see we don't have a specific time https://docs.readthedocs.io/en/latest/changelog.html

**Comment by mpharrigan** [comment]
Thanks, I'll report back when that fix is deployed

**Comment by stsewd** [comment]
@mpharrigan this fix was already deployed, can you test if that really solves your problem? You may need to wipe and rebuild another version. You need to do some additional steps if that doesn't work https://github.com/rtfd/readthedocs.org/pull/3913#issuecomment-389228733

**Comment by mpharrigan** [comment]
No, it didn't seem to work. I tried various combinations of wiping and activate-deactivating the `stable` and `1.9` versions

**Comment by stsewd** [comment]
Ok, I just imported your project locally, and indeed, this is another problem. We give priority to tags, even if they are inactive.

**Comment by stsewd** [comment]
This was proposed in https://github.com/rtfd/readthedocs.org/pull/3331/

Selecting the `stable` version happens when syncing the versions from the repository, so all the branches and tags are considered.

**Comment by mpharrigan** [comment]
Is this the intended behavior?

**Comment by stsewd** [comment]
Yes, this is intended. You will need to remove all tags to rtd select the branch :/

**Comment by mpharrigan** [comment]
Ah that's a bummer. I think the docs (quoted in my original post) should be changed then
