### ISSUE TITLE
"valid webhook set up" with Generic API incoming webhook

### ISSUE THREAD

**Issue by cedk** [rtfd/readthedocs.org#4306]
I get tenths of notifications about almost all my projects that they do not have a valid webhook set up. But they all have a Generic API incoming webhook which is working because builds are triggered.

## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/
* Build URL (if applicable):
* Read the Docs username (if applicable): ced

## Expected Result
Not having those notifications.

## Actual Result
Tenths of notifications are displayed each dashboard page.

**Comment by cedk** [comment]
I just found that clicking on "See the project integrations" dismiss the notification.

**Comment by RichardLitt** [comment]
Thanks for following up and logging this, @cedk.
