### ISSUE TITLE
Why it causes core dump

### ISSUE THREAD

**Issue by wqh17101** [rtfd/readthedocs.org#4308]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/matchzoo/
* Build URL (if applicable):https://readthedocs.org/projects/matchzoo/builds/7406071/ and https://readthedocs.org/projects/matchzoo/builds/77406100/
* Read the Docs username (if applicable):wqh17101

## Expected Result

Get the right content which generated by sphinx-apidoc

## Actual Result
The  77406100 is the one can build normally. But it can not display the content generated by sphinx-apidoc ,so i check the log 
![image](https://user-images.githubusercontent.com/26429138/41982302-a9f114c0-7a5d-11e8-94a5-524d54a7970b.png)
i find an error , obviously, it caused the bug.
So i fixed it and commit the file .
it works in my local env
![image](https://user-images.githubusercontent.com/26429138/41982504-2fad29be-7a5e-11e8-8b74-aa30868ba0ed.png)
but in the readthedoc's env ,it got the result of 7406071
![image](https://user-images.githubusercontent.com/26429138/41982582-64318068-7a5e-11e8-881b-af10a54f7929.png)
i got a core dump
And it seems that whatever i change (the right code in my env )and commit ,it would usually get a core dump.

**Comment by wqh17101** [comment]
I think there maybe something wrong i did.
The first time i build, it worked. And never worked again.
What i did is change the A file,and commit the A file then build online. The A file is the source of my doc's  content 
i wonder whether i should commit not only the A file,but also the build and source dir which generated from A file.

**Comment by stsewd** [comment]
You reported this already in https://github.com/rtfd/readthedocs.org/issues/4301, right? Can we keep the conversation just in one issue? or I misunderstood and those are different problems?

**Comment by wqh17101** [comment]
They are two problems . #4301 is about py36 support .
And this one is about core dump in py35

**Comment by stsewd** [comment]
I think this has nothing to do with the version, `3.6` is supported. I'm running your project locally to see what is happening.

**Comment by stsewd** [comment]
Sorry, I can't replicate this in my local installation. But your latest build is passing https://readthedocs.org/projects/matchzoo/builds/7407005/, were you able to solve the problem?

**Comment by wqh17101** [comment]
No,i reset the repo @stsewd

**Comment by wqh17101** [comment]
what do you need to replicate ? @stsewd

**Comment by stsewd** [comment]
@wqh17101 

> No,i reset the repo

What do you mean? Did you revert a commit?

> what do you need to replicate ?

The core dump error in my rtd local installation.

**Comment by wqh17101** [comment]
@stsewd 
What do you mean? Did you revert a commit?
yes
i just want to ask you what i can offer you to replicate  the problem

**Comment by wqh17101** [comment]
should i change the commit to the situation that the problem happened?

**Comment by stsewd** [comment]
@wqh17101  You can just link the commit here and I try that in my local instance, no need to revert your project

**Comment by bwanglzu** [comment]
@stsewd I guess the latest commit is this one: [link](https://github.com/faneshion/MatchZoo/commit/2ba59774ad36117769300b93be74b8d61facac34).

**Comment by wqh17101** [comment]
This is my teammate ,you can communication with him. @stsewd

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/issues/4308#issuecomment-400783750 this means it is a tensorflow bug? If so, we can close this.

I can't replicate with this commit https://github.com/faneshion/MatchZoo/commit/2ba59774ad36117769300b93be74b8d61facac34

**Comment by bwanglzu** [comment]
@stsewd I have no clue.  why it raises when building documentations?..I'm not able to replicate as well. Maybe the best thing to do is to wait until tomorrow (he went to sleep just now).

**Comment by humitos** [comment]
Do you need tensorflow to build the docs? I'd suggest you to use a different requirement.txt file to build your docs with only what's strictly necessary on it.

**Comment by bwanglzu** [comment]
@humitos Apparently we do not need tensoflow to build the docs  (we didn't even have requirements.txt for documentation) :(

**Comment by humitos** [comment]
RTD auto pick the requirements in the root of your project. That's why.

You may want to check http://docs.readthedocs.io/en/latest/yaml-config.html and http://docs.readthedocs.io/en/latest/yaml-config.html and specify a reqs file there.

**Comment by stsewd** [comment]
> we didn't even have requirements.txt for documentation

oh, I see. RTD tries to find a `requirements.txt` automatically in the root of the repo, you can create an empty `docs/requirements.txt`.

We are tracking the other _bug_ here https://github.com/rtfd/readthedocs.org/issues/1621

**Comment by bwanglzu** [comment]
@humitos @stsewd That make sense, thanks! I'll create a `requirements.txt` under docs folder and try to re-build it again, thanks!

**Comment by stsewd** [comment]
@bwanglzu let us know how that goes!

**Comment by bwanglzu** [comment]
@stsewd Thanks! Will reply tomorrow!

**Comment by wqh17101** [comment]
It doesn't work. @stsewd The core problem is that why i can build at the first time and when i make some right commits ,it failed. There is no  requirements change between the origin and the commit

**Comment by stsewd** [comment]
I build your project several times in my local instance and I wasn't able to replicate this. So I tested it in the readthedocs.org site, I was able to replicate there... but is weird, I'm using the 2.0 docker image in my local instance @humitos which one is used by rtd in production?

@wqh17101 can you test creating a `readthedocs.yml` file with this:

```yaml
build:
  image: 2.0

python:
  version: 3.5
```

**Comment by wqh17101** [comment]
![default](https://user-images.githubusercontent.com/26429138/42011555-6d95d9c0-7ac6-11e8-86f1-925d306d8167.png)
![default](https://user-images.githubusercontent.com/26429138/42011568-8222ccfe-7ac6-11e8-9abd-9e61e2a0bff8.png)
Let's compare the result.
It seems that it crashed when reading sources matchzoo.engine,where the file i commit is.

**Comment by wqh17101** [comment]
@wqh17101 can you test creating a readthedocs.yml file with this:
i will try @stsewd

**Comment by wqh17101** [comment]
it doesn't work @stsewd . So i think it is not the problem about setting of readthedocs.  We should focus on why i modify the file in matchzoo.engine,it will cause reading source failure on the site @stsewd

**Comment by stsewd** [comment]
Can you please point me to that file in your repo?

**Comment by wqh17101** [comment]
Sure , the file is https://github.com/faneshion/MatchZoo/blob/feature/document/matchzoo/engine/param_table.py 
![default](https://user-images.githubusercontent.com/26429138/42013472-0e6767a2-7ad0-11e8-8c20-bd80b160e4fa.png)
And the origin one is that i comment which can build normally.But the build env is 3.5 ,so it doesn't support f-string, so i just change the usage to present the same msg and get a core dump.
@stsewd

**Comment by wqh17101** [comment]
Something new? @stsewd

**Comment by stsewd** [comment]
Sorry, no. I can't replicate locally so I don't know how to help.

**Comment by wqh17101** [comment]
OK i will try whether i remain the F-string,i can do everything
Remain  the F-string , modify the docstring, i can build

**Comment by wqh17101** [comment]
Can I login the auto build env

**Comment by stsewd** [comment]
> Do my make and makefile have problem?

Readthedocs uses `sphinx-build` command to build your documentation, so it has nothing to do with your makefile.

**Comment by wqh17101** [comment]
@stsewd with `tensorflow==1.4.0` in my requirements, it works well

**Comment by stsewd** [comment]
@wqh17101 thanks for the information, this is related to https://github.com/rtfd/readthedocs.org/issues/3738 (see https://github.com/rtfd/readthedocs.org/issues/3738#issuecomment-371385013). Also, this is a tensorflow bug, closing then.
