### ISSUE TITLE
conda environment.yml / pip requirements.txt

### ISSUE THREAD

**Issue by JPelda** [rtfd/readthedocs.org#4310]
## Details
First I tried to build the docs via requirements.txt by pip freeze > requirements.txt. This was not working as I use many packages from conda.
But the conda env export > environemnt.yml does also not work although the build starts but several packages are not installed: 
- 'icc_rt>=2017.0.4',
- 'mkl_fft>=1.0.1'
etc.

Last build was done by using the https://docs.readthedocs.io/en/latest/yaml-config.html manual. Following report was given:
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7410983).

* Read the Docs project URL: https://memphis.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/memphis/builds/7410983/
* Read the Docs username (if applicable): JPelda

## Expected Result

I liked to upload my documentation to readthedocs.org

## Actual Result

Build failed

**Comment by stsewd** [comment]
You have a typo in your `readthedocs.yml` file.

https://github.com/JPelda/memphis/blob/52deda94a7c0ad2f457f5ff1f4331d0569c28b92/docs/readthedocs.yml#L2
it should be 

```yaml
build:
  image: latest
```

**Comment by JPelda** [comment]
Thank you for the hint and the fast reply!
But nevertheless, it is still not running.
Installing the package pyproj via conda install -c conda-forge pyproj runs smoothly but if I try to run setup.py via python setup.py install at my anaconda prompt their is the following failure (also for some other packages):

Searching for pyproj
Reading https://pypi.org/simple/pyproj/
Downloading https://files.pythonhosted.org/packages/29/72/5c1888c4948a0c7b736d10e0f0f69966e7c0874a660222ed0a2c2c6daa9f/pyproj-1.9.5.1.tar.gz#sha256=53fa54c8fa8a1dfcd6af4bf09ce1aae5d4d949da63b90570ac5ec849efaf3ea8
Best match: pyproj 1.9.5.1
Processing pyproj-1.9.5.1.tar.gz
Writing \pyproj-1.9.5.1\setup.cfg
Running pyproj-1.9.5.1\setup.py -q bdist_egg --dist-dir ..\Local\Temp\easy_install-on6deq0i\pyproj-1.9.5.1\egg-dist-tmp-51lnyd0f
using bundled proj4..
error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": http://landinghub.visualstudio.com/visual-cpp-build-tools


and in readthedocs.org the following:
File "/tmp/pip-build-7xtf3s93/GDAL/setup.py", line 138, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'

also it complains I did not install the recent pip.
conda list --> pip 10.0.1
readthedocs:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7xtf3s93/GDAL/
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by stsewd** [comment]
Thanks for the update!
