### ISSUE TITLE
Search by number

### ISSUE THREAD

**Issue by JrCs** [rtfd/readthedocs.org#4316]
Hi,
i have create some documents with title that contain a number like this:
```
object 12345
============
```

The problem is that i can't use the search using that number to find the document.
It's seems to be a problem with the json search version.
If i use the global search (that use elasticsearch) i can find the document.

So:
* why the json search version doesn't index numbers ?
* If the json search return nothing why the elasticseach search is not used ?

**Comment by humitos** [comment]
@JrCs Hi! Could you provide that data that was in the issue template, please? This is `username, `project URL` and a way to reproduce your issue. Thanks!

**Comment by JrCs** [comment]
@humitos it's a local installation of readthedocs.
If i understand well the words that can be search is in searchindex.js ?
If yes the number is never declare **alone** in the searchindex.js.

**Comment by humitos** [comment]
@JrCs I'm not really sure, but I think there are some part of the search that is closed source, so maybe that's what you are missing in your installation.

On the other hand, @safwanrahman is working on an almost complete rewrite of the search. He probably could answer your question better than myself.

**Comment by safwanrahman** [comment]
@JrCs thanks for your issue. It seems like your local installation does not have the closed source search code therefore its searching in built in `Sphinix`.
In the upcoming rewrite of search functionality, it will be open source and inside the readthedocs.org codebase.
I am closing this one, please keep look at the [search project](https://github.com/orgs/rtfd/projects/3) to know when we have a workable example.

**Comment by JrCs** [comment]
Thanks @safwanrahman for the information
