### ISSUE TITLE
Setup readthedocs project via (bash or Python) script

### ISSUE THREAD

**Issue by AdiL2608** [rtfd/readthedocs.org#4323]
# Is it possible to set up the project in an automated way without using the web interface?

Background:
- self hosted Git server
- self hosted rtd server
- custom script to generate rtd configuration

Template to generate documentation (conf.py , index.rst etc.) is generated by custom script. Also the initiallization of the repository on the git server is made by the custom script.

I want to complete the script by setting up the project automatically on the rtd server without using the webinterface and by supplying standard settings through the script. 

Then I would like to get the api adress returned to set up a webhook and copy it to my Git server. In this way the setup for VCS and documentation would be automated completely for each of my projects.

Sorry for asking here, at StackOverflow I could not get any hint to this topic.
Regards

**Comment by stsewd** [comment]
The current API is read only.

**Comment by safwanrahman** [comment]
Closing at its not possible at this time!

**Comment by AdiL2608** [comment]
Actually, it was possible to solve the issue with a Python script on the client´s side. I used Wireshark to trace the http packets which are sent to the read-the-docs server when using the web-interface and reproduced them to access the server and create the project..

**Comment by AdiL2608** [comment]
The script is here: https://gist.github.com/AdiL2608/344e4149681ead0f2a5193ea6b15492b
