### ISSUE TITLE
Point /latest to latest released version (including pre-releases)

### ISSUE THREAD

**Issue by sloria** [rtfd/readthedocs.org#4326]
Currently `stable` is an alias for the latest stable git tag and `latest` points to the HEAD of a specified git branch. As was pointed out in #965, users usually only deal with released versions (rather than development versions). I would like `latest` to be an alias for the latest pre-release version. Is this possible?

**Comment by sloria** [comment]
@stsewd True, but that requires manual intervention for every release. Ideally, `latest` (or some other alias) would automatically point the latest release.

**Comment by humitos** [comment]
If I understand correctly, this is a big change regarding the concept around `latest`. We use `latest` as the "most recent change/commit" in the repository tied to a specific branch (`master` by default in Git -but this can be changed from the admin).

I think you are proposing to use `latest` for "latest pre-release" and `stable` for "latest release" which will break the concept behind the `latest` alias.

> Is this possible?

At this moment, no.

**Comment by sloria** [comment]
@humitos Thanks for the clarification. Perhaps there should be a separate alias, then, that points to the latest release and does *not* exclude pre-releases?

**Comment by stsewd** [comment]
This is still valid, but requires a design decision

**Comment by agjohnson** [comment]
I'd prefer we address this with the version rules feature I've been looking for -- #4001

**Comment by EwoutH** [comment]
I would love a convenient tag other than `stable` and `latest` that always points to the latest pre-release. A native `prerelease` tag would be very convenient!
