### ISSUE TITLE
change version selector position

### ISSUE THREAD

**Issue by youkaichao** [rtfd/readthedocs.org#4332]
how can I change the **version selector** position? I want to place it to the top, like python [doc](https://docs.python.org/2/library/urllib2.html). Currently, it is at the right side like [this](https://easydl.readthedocs.io/en/latest/#) and takes much space.

## Details

* Read the Docs project URL: https://easydl.readthedocs.io/en/latest/#

## Expected Result

like https://docs.python.org/2/library/urllib2.html

## Actual Result

like https://easydl.readthedocs.io/en/latest/#

**Comment by stsewd** [comment]
You need to do it with a custom css file https://dohttps://docs.readthedocs.io/en/latest/guides/adding-custom-css.htmlcs.readthedocs.io/en/latest/guides/adding-custom-css.html

Closing as this isn't a rtd problem.
