### ISSUE TITLE
Search Beta Blog Post

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#4334]
Once we have search running in production, we should write a blog post. It should:

* Tell users about new functionality (eg. all the fancy stuff SimpleQuerySearch does, with example search links)
* Tell users how to test it
* Ask for feedback and thoughts on improvement

We should aim to have this out by around July 15 or so, so that we have some time to get user feedback before the end of the GSOC.

**Comment by safwanrahman** [comment]
I have gone through the pull reuqests that has been merged and found following things.
- Search is much faster than before
- User can now search for exact phrase by using `""` like `"This is Test"`. #2457
- Search is now case insensitive
- Possible to add [Simple Search Query Syntex](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html#_simple_query_string_syntax) in query.
- The documents where all of the query matches will show in top. Like If anyone search `This is test`, The result ordering will be as following.

    - The document where all the 3 word is present
    - The document where any of the 3 word is present
- After a page has been removed, the search index gets update automaticall

**Comment by safwanrahman** [comment]
Performance Improvements:
- [File Search](https://readthedocs.org/search/?q=installation&type=file)
  - Before: 1461 ms
  - After: 200 ms
- [Projects Search](https://readthedocs.org/search/?q=kuma&type=project)
  - Before: 455 ms
  - After: 162 ms
- [Doc Search API](https://readthedocs.org/api/v2/docsearch/?q=installation&project=docs&version=latest&language=en)
  - Before: 746 ms
  - After: 173 ms

- [Project Doc Search](https://readthedocs.org/projects/docs/search/?q=installation)
  - Before: 750 ms
  - After: 270 ms

**Comment by ericholscher** [comment]
@safwanrahman how are you getting these numbers?

**Comment by agjohnson** [comment]
Moving conversation to blog issues: https://github.com/rtfd/blog/issues/44

**Comment by safwanrahman** [comment]
@ericholscher I have taken it from making queries to `RTD` production and local machine, and only taken the `waiting time` from the browser console.
