### ISSUE TITLE
Badge documentation suggests broken link

### ISSUE THREAD

**Issue by kylebarron** [rtfd/readthedocs.org#4337]
On my project page, when I click on the documentation badge, I see the below image. For the badge image link, it's missing the `https:` prefix for each language.

![image](https://user-images.githubusercontent.com/15164633/42398335-799218de-8137-11e8-965e-127ac5efa265.png)

**Comment by stsewd** [comment]
I can confirm this is also happening in other projects.

**Comment by stsewd** [comment]
Looks like this change was on purpose https://github.com/rtfd/readthedocs.org/pull/4228

**Comment by kylebarron** [comment]
I just assumed the suggested text was meant to be able to be copy-pasted and work...

**Comment by stsewd** [comment]
Yeah, it is. This is still a bug.
