### ISSUE TITLE
Code styles broken

### ISSUE THREAD

**Issue by Suor** [rtfd/readthedocs.org#4339]
## Details

* Read the Docs project URL: https://funcy.readthedocs.io/en/stable/seqs.html
* Build URL (if applicable):
* Read the Docs username (if applicable): Suor

## Expected Result

Code looking nice.

## Actual Result

Code samples with small font-size and even smaller line height in latest and stable version. No code highlight in older versions.

**Comment by stsewd** [comment]
I think you may need to re-build the docs for that versions. Can you try that, please?

**Comment by Suor** [comment]
Rebuild latest, looks the same.

**Comment by davidfischer** [comment]
Did this change or are you just voicing that you don't like the current style?

There is an [open pull request](https://github.com/rtfd/sphinx_rtd_theme/pull/657) to change the `line-height` on code blocks in the theme but I'm not aware that it changed recently.

**Comment by stsewd** [comment]
> Rebuilt latest, looks the same.

But your comment was about the other versions not looking like latest. I mean to rebuild the other versions

**Comment by Suor** [comment]
![funcy-code](https://user-images.githubusercontent.com/284103/42429777-5ab0c3d6-8365-11e8-9469-c7abc063c6a2.png)
So this is how it supposed to look?

**Comment by stsewd** [comment]
I think you need to remove this line https://github.com/Suor/funcy/blob/master/docs/conf.py#L92. The same problem was fixed with in the rtd docs https://github.com/rtfd/readthedocs.org/pull/4331

**Comment by Suor** [comment]
I tried it locally, it removes green background, but font and line height
remain the same

пн, 9 июл. 2018 г., 11:16 Santos Gallegos <notifications@github.com>:

**Comment by stsewd** [comment]
> but font and line height remain the same

I think that is another issue that David mention https://github.com/rtfd/readthedocs.org/issues/4339#issuecomment-403314971

**Comment by Suor** [comment]
Ok, fixed with custom styles for now. Old versions would suck )
