### ISSUE TITLE
ReadTheDocs builds are failing

### ISSUE THREAD

**Issue by veenamj** [rtfd/readthedocs.org#4341]
## Details
ReadTheDocs builds are failing
* Read the Docs project URL: http://readthedocs.org/projects/qubole-documentation
* Build URL (if applicable): http://readthedocs.org/projects/qubole-documentation/builds/7457003/
* Read the Docs username (if applicable):  

## Expected Result 

*A description of what you wanted to happen*
Build should be successful

## Actual Result
 Sphinx Version 1.7.5 is causing the build failure. 

*A description of what actually happened*
Is there any way that ReadTheDOCs can revert to Sphinx version 1.7.4?  The build is failing only because of Sphinx Version 1.7.5.  

Builds with 1.7.4 also were successful.

**Comment by stsewd** [comment]
Interesting bug :thinking:, you know if it is already reported/fixed in sphinx?

And you can always pin to a specific Sphinx version creating a `requirements.txt` file.

**Comment by veenamj** [comment]
Thanks, @stsewd ! I'd totally forgotten about it.  It fixed the issue. Builds are running fine now.
