### ISSUE TITLE
git clone fails (after already succeeding)

### ISSUE THREAD

**Issue by gkiar** [rtfd/readthedocs.org#4342]
## Details

* Read the Docs project URL: http://clowdr-dev.rtfd.io/
* Build URL (if applicable): https://readthedocs.org/projects/clowdr-dev/builds/7460405/
* Read the Docs username (if applicable): gkiar

## Expected Result

I expected the documentation to be built.

## Actual Result

Despite successfully cloning the github repository in the first step of the build, the installation process fails later on because it is unsuccessful in cloning the repo.

Any help is much appreciated!

Thanks,
Greg

**Comment by stsewd** [comment]
You shoud use the https form for the git url `git+https://github.com/user/proyect.git`

**Comment by gkiar** [comment]
Ha, should've checked for that... Thanks :)
