### ISSUE TITLE
MultipleObjectsReturned in core.views.serve.serve.docs

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#4350]
We get this exception while trying to serve some docs:

```
MultipleObjectsReturned: get() returned more than one Version -- it returned 2!
  File "django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "readthedocs/core/views/serve.py", line 96, in inner_view
    return view_func(request, project=project, *args, **kwargs)
  File "readthedocs/core/views/serve.py", line 74, in inner_view
    return view_func(request, subproject=subproject, *args, **kwargs)
  File "readthedocs/core/views/serve.py", line 156, in serve_docs
    version = project.versions.public(request.user).get(slug=version_slug)
  File "django/db/models/query.py", line 391, in get
    (self.model._meta.object_name, num)
```

The view code looks legit at a first look but there's a huge side effect of the user filtering in the public() method. It does not filter the projects by user but it adds to the queryset all the other user projects which is not what we need here:

```
# project of the version we are looking for
>>> versione.project
<Project: Documentazione API anagrafe del Comune di Tre Civette sul Comò>
# this queryset is fine
>>> versione.project.versions.all()
[<Version: Version master of Documentazione API anagrafe del Comune di Tre Civette sul Comò (861)>, <Version: Version bozza of Documentazione API anagrafe del Comune di Tre Civette sul Comò (860)>]
# but here we have other projects' version too
>>> versione.project.versions.public(user)
[<Version: Version stabile of design-docs (859)>, <Version: Version master of Documentazione API anagrafe del Comune di Tre Civette sul Comò (861)>, <Version: Version bozza of design-docs (852)>, <Version: Version bozza of Documentazione API anagrafe del Comune di Tre Civette sul Comò (860)>]

```

**Comment by xrmx** [comment]
"ondering if not passing the user to public is the correct fix.

**Comment by stsewd** [comment]
I have encountered this sometimes locally, but I wasn't able to replicate, and I think this has never happened in production.

**Comment by stsewd** [comment]
Also, this had already been reported before https://github.com/rtfd/readthedocs.org/issues/2613

**Comment by xrmx** [comment]
Thanks for the heads up. I'll try to cook a test and a PR then.

**Comment by p3trus** [comment]
Just a short question, why is this issue closed? To me it appears that the fix has not been applied to readthedocs but to the fork only.

**Comment by p3trus** [comment]
Any plans to merge this bugfix in the near future?

**Comment by xrmx** [comment]
@p3trus this is the bug not the PR

**Comment by p3trus** [comment]
I know but the docsitalia team already fixed it.

**Comment by xrmx** [comment]
@p3trus you probably missed I'm the one who is trying to get this merged :)

**Comment by p3trus** [comment]
@xrmx I didn't mean to sound nagging. Just wanted to know the timeframe if there is any.

**Comment by xrmx** [comment]
@p3trus asking for ETA is nagging :) If you look at the PR you'll see clearly stated that it's not merged because coverage tests fail. They fail because code does not do what the tests expect and I suspect even before the proposed changes.
