### ISSUE TITLE
Private project is visible for anyone

### ISSUE THREAD

**Issue by personalsoft-fabianobonin** [rtfd/readthedocs.org#4351]
Hi, I did a private install of readthedocs.
One of my projects needs to be private, and I configured it as private in "Advanced settings/Privacy level".
But I can access the documentation anonymously.
It is a mkdocs project, and I did a manual build after changed the setting above.

**Comment by personalsoft-fabianobonin** [comment]
Just found that the privacy level is defined on versions:
https://github.com/rtfd/readthedocs.org/issues/2663

So I am closing the issue.

**Comment by RichardLitt** [comment]
Thanks for logging, and for following up and letting us know, @personalsoft-fabianobonin.
