### ISSUE TITLE
build fails without error

### ISSUE THREAD

**Issue by gdementen** [rtfd/readthedocs.org#4358]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/larray/
* Build URL (if applicable): https://readthedocs.org/projects/larray/builds/7472043/
* Read the Docs username (if applicable): gdementen

## Expected Result

Successfully build our project documentation

## Actual Result

Build failed just after "git clean" without any visible error, making it impossible to debug for us.
This is just one build in a series of failed builds: https://readthedocs.org/projects/larray/builds/

This **might** be related to the fact the url of the git repository of the project changed (from https://github.com/liam2/larray to https://github.com/larray-project/larray) because we have not had any successful build since the move, but we did change the project url in rtd's config.

Any help would be greatly appreciated!

PS: I tried wiping the build environment to no effect...

**Comment by stsewd** [comment]
I can see this error in my local instance `UnicodeDecodeError: 'utf8' codec can't decode byte 0xeb in position 78: invalid continuation byte`. Maybe a file with wrong encoding?

**Comment by gdementen** [comment]
@stsewd Do you have *any* extra info you can tell me? Obviously, the filename would be best, but I guess you don't have it. But do you have the full traceback? Or at least during what shell command the error happens?

**Comment by stsewd** [comment]
There isn't a traceback, just the msg error :/ I'll need to inspect with pdb to give you more details, I think later I'll have some time.

**Comment by gdementen** [comment]
Thanks a lot!

**Comment by stsewd** [comment]
It seems that the error happens when parsing the tags, rtd uses gitpython internally for git operations, it fails trying to recover the commit of this tag `<git.TagReference "refs/tags/0.27">`.

I did a `git show 0.27`, this is the output

```
tag 0.27
Tagger: Ga<EB>tan de Menten <gdementen@gmail.com>
Date:   Thu Nov 30 11:40:18 2017 +0100
```

There is a weird invalid character in the tagger field.

**Comment by gdementen** [comment]
Ah! My name causing problems again ;-). Seriously it was mangled by "git gui" which has troubles with some encodings in committer names. The strange thing is that we managed to make release 0.27 and 0.28 without problems, so this must be a relatively new problem in gitpython.

Sadly, there is nothing I can do about that now, short of rebasing and redoing that commit then force pushing but that will mess up with people who cloned our repository :(. Fixing the problem on gitpython would be the right move from me but I don't expect to have the time to do that in the near future. Anyway, thanks **a lot** for your great support!

**Comment by gdementen** [comment]
might be related to https://github.com/gitpython-developers/GitPython/issues/332

**Comment by stsewd** [comment]
>  The strange thing is that we managed to make release 0.27 and 0.28 without problems, so this must be a relatively new problem in gitpython.

Actually, the problem may be old, we just move to gitpython recently, previously we were parsing the git tags _by hand_.

**Comment by stsewd** [comment]
There is nothing we can do from the rtd side here, closing this as the main problem is a no-valid utf-8 character in the commit object.
