### ISSUE TITLE
Triggering a build manually redirects to build listing

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4359]
Currently, if you trigger a build manually from the project details page or from the build listing page the user is redirected to the build listing page. I think it would be better if the user is redirected to the build details page since the build object is already created.

In the details page the user can see that the build was triggered easily and maybe wait for completion while checking the commands.

> If we agree on making this change, we should mark this issue as `Good First Issue`

**Comment by agjohnson** [comment]
Yeah, this bugs me a lot. It should be a small change.

**Comment by pradyunsg** [comment]
I'd like to take a stab at this issue, if no one would mind... Any pointers as to which part of the codebase needs the relevant changes here? :)

**Comment by stsewd** [comment]
@pradyunsg here is the current redirect https://github.com/rtfd/readthedocs.org/blob/dde104daf23f580887e79d4fae91cf9577fbbb76/readthedocs/builds/views.py#L58-L58, we need to change that.
