### ISSUE TITLE
Specify specific version of sphinx without requirements.txt?

### ISSUE THREAD

**Issue by wohali** [rtfd/readthedocs.org#4361]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/couchdb
* Build URL (if applicable): https://readthedocs.org/projects/couchdb/builds/7476452/
* Read the Docs username (if applicable): wohali

## Expected Result

Build should succeed.

## Actual Result

Build fails due to a bug in sphinx, see https://github.com/sphinx-doc/sphinx/issues/5048 .

The problem is that this is a tagged version on our repository that we are not at liberty to alter per the ASF release policy. We can't just add a `requirements.txt` file to force a specific version of Sphinx. And, soon, pinning Sphinx shouldn't be necessary anyway, since 1.7.6 should eventually be released. ;)

Is there any other way to specify the specific version of Sphinx? Or, would rtd consider pinning to 1.7.4 until 1.7.6 is released? Thanks.

**Comment by stsewd** [comment]
> Is there any other way to specify the specific version of Sphinx?

No

> would rtd consider pinning to 1.7.4 until 1.7.6 is released?

Maybe we can, but we aren't pinning sphinx versions anymore, we are using `<1.8` to indicate the default the sphinx version. So whenever `1.7.6` is released you are able to build your docs successfully again.

**Comment by wohali** [comment]
OK, we've worked around this with a forced `requirements.txt` file to pin our Sphinx version.
