### ISSUE TITLE
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7476634).

### ISSUE THREAD

**Issue by mgeier** [rtfd/readthedocs.org#4362]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/splines/
* Build URL (if applicable): https://readthedocs.org/projects/splines/builds/7476634/
* Read the Docs username (if applicable): geier

## Expected Result

Successful build.

## Actual Result

Build failed with this error message:

> There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7476634).

I've "wiped" the build previously, because there have been other issues before, e.g. an error during "Installing setuptools, pip, wheel...": https://readthedocs.org/projects/splines/builds/7476053/.

**Comment by mgeier** [comment]
Reporting this already helped, now it works: https://readthedocs.org/projects/splines/builds/7476771/

**Comment by stsewd** [comment]
I think some of the failures are related to memory limits, maybe you want to check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

If this isn't a problem anymore, can we close this issue?

**Comment by mgeier** [comment]
Thanks for the hint, @stsewd!

I don't know what went wrong in the case that I reported, you should decide if this issue should be closed or not.

Here are some observations I made, in case somebody stumbles upon this issue:

* it's definitely helpful to reduce the number of output formats, especially if they are not needed anyway.

* in my case I actually want to use those dependencies during the documentation build, but it turns out that using `conda` needs more memory than using the "normal" image.

* I was using `conda` in the first place to get Python 3.6 support, but it turned out that this is also available for "normal" builds when using the `latest` image (see below).

* I'm not sure about this, but I guess using the "system site-packages" reduces the number of packages that have to be installed, therefore reducing the memory usage. The option `use_system_site_packages` was quite hard to find, BTW.

Here is the `readthedocs.yml` that worked for me

```yaml
build:
  image: latest

python:
  version: 3.6
  setup_py_install: true
  use_system_site_packages: true

requirements_file: doc/requirements.txt

formats: []
```

Please correct me if I'm wrong!

**Comment by mgeier** [comment]
The time/memory usage could be further reduced if `-E` were not used when calling Sphinx, see #4363.

**Comment by stsewd** [comment]
Thanks for reporting back! Yeah, using conda to only support python 3.6 is very heavy.
