### ISSUE TITLE
HackMD to readthedocs

### ISSUE THREAD

**Issue by vin-ni** [rtfd/readthedocs.org#4364]
Hello,
I'm trying to move from hackmd to read the docs. I found that the syntax is quite different and wanted to know if someone has experience converting it.

Examples for HackMD Syntax:
$\rightarrow$ `equals` →

```sequence
Alice->Bob: Hello Bob, how are you?
Note right of Bob: Bob thinks
Bob-->Alice: I am good thanks!
```
`equals`
<img width="459" alt="bildschirmfoto 2018-07-13 um 13 38 57" src="https://user-images.githubusercontent.com/9806572/42689781-1ca39ae2-86a2-11e8-8414-10f2bb663332.png">

especially the js-sequence-diagram part would be important. I found an example on [MkDocs+](http://bwmarrin.github.io/MkDocsPlus/js-sequence-diagrams/) but they use html snippets and custom js for each diagram if I understood it correctly. I'd like to keep the existing code (```sequence) to do this.

Thanks!

**Comment by stsewd** [comment]
RTD doesn't support that kind of syntax, I think is better to stick to a separate plugin.

**Comment by vin-ni** [comment]
Here's how I added it:

Add all the necessary js files in `conf.py`. (Place these files into docs > source > _static > js)

    def setup(app):
        app.add_javascript('js/snap.svg-min.js')
        app.add_javascript('js/underscore-min.js')
        app.add_javascript('js/webfontloader.js')
        app.add_javascript('js/sequence-diagram-min.js')
        app.add_javascript('js/custom.js')

Add to your `custom.js` file

    var diagrams = document.getElementsByClassName('diagram');

    for (let i = 0; i < diagrams.length; i++) {
        const diagramDom = diagrams[i];

        //skip if already svg inside
        let svgList = diagramDom.getElementsByTagName('svg');
        if (svgList.length > 0) {
            continue}

        let text = diagramDom.textContent;
        //remove inner html
        diagramDom.innerHTML = "";

        var options = {
            // Change the styling of the diagram, typically one of 'simple', 'hand'. New themes can be registered with registerTheme(...).
            theme: "simple",
        
            // CSS style to apply to the diagram's svg tag. (Only supported if using snap.svg)
            css_class: "diagramSVG",
        };

        // draw svg
        var diagram = Diagram.parse(text);
        diagram.drawSVG(diagramDom, options);
        
    }

    console.log('Ran custom.js');

This way, each time you open a page it will look for all diagrams and draw them.

The syntax for a`*.md` file would then be:

    <div class="diagram">
    Alice->Bob: Hello Bob, how are you?
    Note right of Bob: Bob thinks
    Bob-->Alice: I am good thanks!
    </div>

**Comment by RichardLitt** [comment]
Thanks for letting us know, @vin-ni, and for writing this all up. That's useful for future people searching through the issues. We appreciate it. \o/
