### ISSUE TITLE
Missing Docstrings 

### ISSUE THREAD

**Issue by imyiningliu** [rtfd/readthedocs.org#4365]
## Details

* Read the Docs project URL: https://scvi.readthedocs.io/en/master/inference.html
* Updated Build URL (if applicable): https://readthedocs.org/projects/scvi/builds/7536717/
* Read the Docs username (if applicable): imyiningliu 

## Expected Result

I ran `make html` locally and the documentation looks fine. 

## Actual Result

However, when I build the documentation, none of the docstring shows up in the package documentation section ([example](https://scvi.readthedocs.io/en/latest/dataset.html)). I tried building different versions but I always got the same issue. Any suggestions on what I should look into? I haven't found others having similar issue :( 

Edit: Docstrings show up except for one module (As described below).

**Comment by stsewd** [comment]
Probably you need to check the `Install project` option in the admin panel of your project.

**Comment by imyiningliu** [comment]
Thanks! I added `Install project` and it starts to build. However, one of our dependency (`loompy`) is only available for `python 3.6` but `readthedocs` uses `python 3.5` to build the documentation. Do you happen to know what we can try / whether `readthedocs` plans to use `python 3.6`?

**Comment by stsewd** [comment]
RTD already supports python 3.6, but it's available using a configuration file. See https://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by imyiningliu** [comment]
That solves our issue! Thank you so much

**Comment by imyiningliu** [comment]
I uploaded a new version of the documentation and the docstring for one module is still missing. 

The build was successful locally without any warnings, and I also included `.yml` file to use `python 3.6`. Do you know why the documentation is missing only for one module? 

Thanks!!

**Comment by stsewd** [comment]
@imyiningliu can you please be more specific? Which module is missing?

**Comment by imyiningliu** [comment]
Sorry I should've linked module in my comment - the [documentation for the inference class]( https://scvi.readthedocs.io/en/master/inference.html) is missing. 

The project GitHub page is available [here](https://github.com/YosefLab/scVI).

**Comment by stsewd** [comment]
@imyiningliu were you able to solve the problem?
