### ISSUE TITLE
Abandoned project

### ISSUE THREAD

**Issue by adarshp** [rtfd/readthedocs.org#4366]
Hi,

The project https://delphi.readthedocs.io/en/latest/ is connected to a non-existent Github repo: https://github.com/tacsbb/delphi-book/blob/master/index.rst.

I'm mentioning the user @tacsbb here in the hopes that they would be willing to release the `delphi` project name to use for our actively-developed project named Delphi: https://github.com/ml4ai/delphi.

I didn't see an email address listed on their profile, so I'm trying this method. If this doesn't work, could one of the RTD maintainers contact @tacsbb?

**Comment by humitos** [comment]
@adarshp I just sent an email to the owner. We will follow our policy and I'll come back in 6 weeks if he/she doesn't respond within this time.

**Comment by adarshp** [comment]
@humitos Thank you!

**Comment by humitos** [comment]
Hi @adarshp!

The owner of the project didn't answer. The namespace `delphi` is free to use.

Closing here.

**Comment by adarshp** [comment]
Great, thank you very much!
