### ISSUE TITLE
Unable to import from GitHub automatically or manually

### ISSUE THREAD

**Issue by kirill-andr** [rtfd/readthedocs.org#4372]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tracking-data-management/
* Build URL (if applicable): https://readthedocs.org/projects/tracking-data-management/builds/7490942/
* Read the Docs username (if applicable): key2market

*A description of what you wanted to happen*
I wanted to connect and import our projects from GitHub. That did not work so I tried to manually import the project from GitHub

## Actual Result
Upon connecting my github account, none of my repositories are visible in readthedocs. This is unusual, because I have done the same in other tools and it had worked.
<img width="840" alt="screen shot 2018-07-16 at 10 38 55 am" src="https://user-images.githubusercontent.com/25954151/42749609-7c2bfbaa-88e4-11e8-991a-842eee04441c.png">

Manually connected project from GitHub is not able to build successfully and gives the following error:
could not read Username for 'https://github.com': terminal prompts disabled
<img width="874" alt="screen shot 2018-07-16 at 9 49 10 am" src="https://user-images.githubusercontent.com/25954151/42747701-c10cd1e2-88dd-11e8-92d8-3793bddaf252.png">

**Comment by stsewd** [comment]
Your projects are private, rtd.org only supports public projects. You may want to check readthedocs.com for private projects.
