### ISSUE TITLE
Invalid "requirements_file": path docs/requirements.txt does not exist error

### ISSUE THREAD

**Issue by Benjamin-Lee** [rtfd/readthedocs.org#4378]
## Details

* Read the Docs project URL: squiggle.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

Build to succeed

## Actual Result

`Problem parsing YAML configuration. Invalid "requirements_file": path docs/requirements.txt does not exist` error

This is particularly strange because the repo clearly has a [`docs/requirements.txt`](https://github.com/Lab41/squiggle/blob/master/docs/requirements.txt) file. What could be causing this?

**Comment by Benjamin-Lee** [comment]
Update: I just triggered a new build on a repo (_i.e._ no changes) that had worked as of three hours ago and now it is failing with the same error:

http://readthedocs.org/projects/freqgen/builds/7495641/

Could this be related to either #4377 or the [GitHub outages](
https://status.github.com/) today?

**Comment by vimalloc** [comment]
As a data point same thing is happening to me. Only change in my code is a version number and a new tag. https://readthedocs.org/projects/flask-jwt-extended/builds/

Glad it's not just me, I thought I was going crazy for a second :+1:

**Comment by stsewd** [comment]
Sorry people, I'm trying to replicate this locally right now. But I think I know where is the bug.

**Comment by stsewd** [comment]
I can't replicate this locally (I think this is something to do with the builds being executed in another server). This was introduced in https://github.com/rtfd/readthedocs.org/pull/4298.
But, I think I know where the bug is, I'll send a PR soon. If you need your docs now, a workaround is using a configuration file https://docs.readthedocs.io/en/latest/yaml-config.html.

**Comment by stsewd** [comment]
The fix is ready https://github.com/rtfd/readthedocs.org/pull/4379, let's hope the rtd team can review/deploy that soon.

**Comment by rb2745** [comment]
The fix to the similar issue #3140 included: (1) a change in the RTD "search for configuration file logic" to use one in the repository root folder if found; and (2) explicitly including a configuration file in the root folder to preclude use of other yaml files found deeper within the repo and/or git submodule repositories collected during the build process.  For example, a root folder configuration file https://gerrit.onap.org/r/gitweb?p=doc.git;a=blob;f=readthedocs.yml;h=6e6b9af07e6d523a60342e76bf181288bf826c63;hb=HEAD

**Comment by agjohnson** [comment]
#4379 is now out. Raise a new issue if you are noticing any similar issues.
