### ISSUE TITLE
Page redirect: Preserve query data in "PAGE" url

### ISSUE THREAD

**Issue by ivankravets** [rtfd/readthedocs.org#4384]
## Details

We use URL in PAGE format in different places. This allows us to control default LOCALIZATION and default VERSION (latest or specific). Also, we add some marketing data via QUERY PARAMETERS to URL for GA. 

Example: http://docs.platformio.org/page/projectconf/section_env_build.html?utm_source=platformio&utm_medium=piohome#build-flags

## Expected Result

Valid redirect should be: http://docs.platformio.org/en/latest/projectconf/section_env_build.html?utm_source=platformio&utm_medium=piohome#build-flags

## Actual Result

http://docs.platformio.org/en/latest/projectconf/section_env_build.html#build-flags

**Comment by stsewd** [comment]
Can you please share how you configured the redirection? I'll try to replicate this tomorrow.

**Comment by ivankravets** [comment]
I have only these items:
![screen shot 2019-01-08 at 17 03 32](https://user-images.githubusercontent.com/1760209/50838717-5f1ff580-1367-11e9-8775-601b763ed917.png)

**Comment by stsewd** [comment]
I don't see the redirect from the original issue. But I was able to reproduce a different bug.

Are you sure you don't have an extra setup for redirecting from http://docs.platformio.org/page/projectconf/section_env_build.html?utm_source=platformio&utm_medium=piohome#build-flags ?

The another bug:

https://docs.platformio.org/en/latest/userguide/cmd_serialports.html redirects to https://docs.platformio.org/en/latest/userguide/cmd_device.html

But  https://docs.platformio.org/en/latest/userguide/cmd_serialports.html?foo=bar gives 404.

**Comment by ivankravets** [comment]
> Are you sure you don't have an extra setup for redirecting from 

You can reproduce this bug with any URL. For example, https://docs.readthedocs.io/page/webhooks.html?arg=test

**Comment by stsewd** [comment]
Sorry, I didn't know about the `/page` redirect.

**Comment by stsewd** [comment]
Ok, that's a different problem that the one I found before

https://github.com/rtfd/readthedocs.org/blob/d91807c5c772fbfdb4be5ff928c9268d4be05e80/readthedocs/core/urls/__init__.py#L13-L16

**Comment by stsewd** [comment]
This is deployed and working!
