### ISSUE TITLE
nested tables are not yet implemented.

### ISSUE THREAD

**Issue by Sraw** [rtfd/readthedocs.org#4396]
## Details

* Build URL (if applicable): https://readthedocs.org/projects/nswebdav/builds/7502924/

Source code line:

https://github.com/Sraw/nswebdav/blob/3949913757ada324c250fe490bfa3554e349b1b6/nswebdav/base.py#L359

As you can see, some of my docs use nested table which can be displayed well when I test locally by using `make html && python -m http.server` with `sphinx==1.7.6`.

But when I upload it to rtd, it shows the following error:

```
Markup is unsupported in LaTeX:
source/nswebdav:: nested tables are not yet implemented.
```

Here is my requirements.txt for rtd: https://github.com/Sraw/nswebdav/blob/master/docs/requirements.txt

## Expected Result

Build succeeds.

## Actual Result

Build fails with error which doesn't appear when test locally.

**Comment by stsewd** [comment]
The build fails when generating the pdf, you can disable the pdf generation in the admin panel of your project.

**Comment by Sraw** [comment]
Thank you very much. It works now.

**Comment by RichardLitt** [comment]
@Sraw Glad to hear it!
