### ISSUE TITLE
doc build status to GitHub Commit Status API #238 Open

### ISSUE THREAD

**Issue by peterkingalex** [rtfd/readthedocs.org#4397]
## Details

* Read the Docs project URL:
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by RichardLitt** [comment]
Thanks @peterkingalex. This hasn't been filled out; in the future, could you fill out the template when logging a bug? Thanks.
