### ISSUE TITLE
AdminPermission is_admin permission mismatch with views permissions

### ISSUE THREAD

**Issue by xrmx** [rtfd/readthedocs.org#4399]
## Details

If i am a superuser i see all the content that is guarded by the is_admin template tag even if i am not an admin of the project. is_admin is just a wrapper of core.permissions. AdminPermission and in fact the behavior matches the code.
The problem is that this access control does not match the one in the build views. e.g. In the project detail page i see the build version button but when i click it i get a 404. Same for updating project details.
Any idea on how to fix this?
 
## Expected Result

As a superuser if i cannot build a project i shouldn't see the button for doing so

## Actual Result

As a superuser a button that leds to a 404 is showed to me

**Comment by xrmx** [comment]
@humitos missed that, thanks! Will check and close the bug if that's it.

**Comment by xrmx** [comment]
For us it's not just the project admin button it's also the link to projects.views.private.project_version_detail for each version.

**Comment by xrmx** [comment]
We would like being able to inspect our users projects, are you willing to consider a PR that permit that? Like what David did but for the other two views.

**Comment by xrmx** [comment]
We need something like this https://github.com/italia/docs.italia.it/commit/5a76034dc14b1cc406e4607a95706fc8b408f221

We need to add another method to the queryset manager because for_admin_user is also used when we need to really pick projects from the user, e.g. import views.

**Comment by humitos** [comment]
In that case, this needs a deeper look since we extend the `for_admin_user` in our corporate site (to respect another kind of permissions) and we will need to make sure that is still supported after the changes needed for this here.

**Comment by xrmx** [comment]
So this is what i come up:
https://github.com/italia/docs.italia.it/pull/89

First commit is backport of David fix, the second does the same to more views and the last add the new queryset method that calls the old one so it may work even with your overridings. If it is interesting for you i can open a PR upstream of course.

**Comment by xrmx** [comment]
I think this is still valid

**Comment by stsewd** [comment]
We are planning in refactor the auth code, so it's easier to use/extend. Not sure if we should re-open this issue or wait for the refactor.
