### ISSUE TITLE
There was a problem with Read the Docs while building your documentation. Build id (7504698).

### ISSUE THREAD

**Issue by paulmueller** [rtfd/readthedocs.org#4400]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/drymass/
* Build URL (if applicable): https://readthedocs.org/projects/drymass/builds/7504698/
* Read the Docs username (if applicable): paulmueller

## Expected Result

The documentation builds.

## Actual Result

The build stops without any other error messages after ``cat docs/conf.py``.

## More information
- This is a sphinx project, the package source code is Python >= 3.6 and I am using autodoc
- The build runs fine with my local setup (Python 3.6)
- The build time is only 100s, so it is not a timeout.
- I started to experience this problem after the new rtd release 2.6.0. This might be related.
- Issue #4380 did not solve my problem.

**Comment by stsewd** [comment]
I saw this commit https://github.com/RI-imaging/DryMass/commit/5a8dced10908292a525ee6cac9d369698147ab19, just to clarify rtd does support python 3.6 but you need to specify a build image with that version https://docs.readthedocs.io/en/latest/yaml-config.html#build-image

I was able to build your docs in my local instance, so not sure what the problem is :/

**Comment by paulmueller** [comment]
Thanks for the hint - that seemed to have solved it :fireworks:.
https://readthedocs.org/projects/drymass/builds/7507493/

Would it make sense for rtd to check for the Python version in setup.py?
e.g.:

```
setup(...
         python_requires='>=3.6, <4',
         ...)
```

I am just thinking that something along these lines might make it easier to debug this type of issue.

**Comment by stsewd** [comment]
@paulmueller not all projects have a `python_requires` or even a `setup.py` file, so respecting that would be tricky. Glad that your docs are building again!
