### ISSUE TITLE
Confusing error message to end user

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4401]
In https://github.com/rtfd/readthedocs.org/issues/4071#issuecomment-405939492 I realized that we are saying that we have a problem parsing the YAML file but the problem is in fact in one of the options set from the web admin dashboard.

Example:

![captura de pantalla_2018-07-18_10-57-36](https://user-images.githubusercontent.com/244656/42886232-647bedbc-8a79-11e8-8aca-fe2430139fe0.png)

There is no `requirements_file` entry in the YAML file (https://github.com/geopandas/geopandas/blob/master/readthedocs.yml) but it exists under the `Admin -> Advanced Settings` field form.

We need to improve this error to something more user-friendly that expresses the real error. It's not an error on parsing the YAML file. The file was parsed properly, but the problem is with one of the values from one of the fields.

**Comment by stsewd** [comment]
Previously we weren't checking for the requirements file of the web admin, so an error would happen in the install requirements step. I think we can catch this cases when doing https://github.com/rtfd/readthedocs.org/issues/4388
