### ISSUE TITLE
Ads blocker nag appears if changing menus fast

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4402]
If you go to a page like this one https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/contributions.html and click fast between two different menu items (for example "Notifications" and "Contributions") you will see the nag that appears for a portion of second and then disappears.

I tried this in Firefox 61.0.1 (64-bits).

This is something not too much important but I wanted to report it anyway.

> You can replicate this with and without an Ads blocker active.

**Comment by davidfischer** [comment]
I can't seem to reproduce this. Notifications and Contributions are different page loads. I wonder if there's a list you are subscribing to that blocks the nag.

**Comment by humitos** [comment]
It only happens in Firefox. I couldn't reproduce it in Chrome.

> I wonder if there's a list you are subscribing to that blocks the nag.

This also happens here without running an Ad Blocker.

Just in case, by nag I'm referring to this green square:

![captura de pantalla_2018-07-18_13-54-17](https://user-images.githubusercontent.com/244656/42896085-342be180-8a92-11e8-9ce8-2356502cfd53.png)

**Comment by stsewd** [comment]
I can't replicate this in firefox 61.0.1 - Fedora 28. As David mention, notification/contributors load different pages

**Comment by davidfischer** [comment]
> This also happens here without running an Ad Blocker.

I don't see how that is possible. The element isn't even on the DOM if you aren't using an ad blocker.

**Comment by humitos** [comment]
I found another way to reproduce this issue in Chrome and Firefox (both without any ad blocker).

Load any docs page (e.g. http://sphinx-autoapi.readthedocs.io/en/latest/) and press Escape before it loads completely. You will see the that nag.

**Comment by stsewd** [comment]
I can confirm that.

**Comment by davidfischer** [comment]
Ok, thanks. This is good feedback. I was detecting an ad blocker by the ad request returning a 404. I guess I'll need a better method. I want to avoid [something heavy](https://github.com/sitexw/FuckAdBlock).
