### ISSUE TITLE
explain how uBlock users may allow ads

### ISSUE THREAD

**Issue by matkoniecz** [rtfd/readthedocs.org#4405]
## Details

* Read the Docs project URL: https://docs.readthedocs.io/en/latest/advertising/ad-blocking.html#allowing-ethical-ads
* Build URL (if applicable): https://github.com/rtfd/readthedocs.org/blob/master/docs/advertising/ad-blocking.rst
* Read the Docs username (if applicable): not applicable

## Expected Result

uBlock users are informed how they may whitelist ads

## Actual Result

uBlock users are not informed how they may whitelist ads

I considered whitelisting ads, but I am not so determined to debug by myself that I should do to achive that - and I expect to not be unique in this laziness

**Comment by stsewd** [comment]
Actually there is https://ads-for-open-source.readthedocs.io/en/latest/installation.html#installing-on-ublock-origin

**Comment by stsewd** [comment]
Thanks for whitelisting rtd btw ;)

**Comment by matkoniecz** [comment]
It appears to be unlinked from https://docs.readthedocs.io/en/latest/advertising/ad-blocking.html#allowing-ethical-ads (I searched https://raw.githubusercontent.com/rtfd/readthedocs.org/master/docs/advertising/ad-blocking.rst for install)

It may be also worth mentioning uBlock by name in https://docs.readthedocs.io/en/latest/advertising/ad-blocking.html#allowing-ethical-ads (I think that people are likely to use ctrl+f searching for their adblock)

**Comment by davidfischer** [comment]
I'll go ahead and add a link to the specific instructions for uBlock. The uBlock process is not quite as straight forward.
