### ISSUE TITLE
How do i make internal references work from Markdown documents?

### ISSUE THREAD

**Issue by mlncn** [rtfd/readthedocs.org#4412]
I think my question can equally be rephrased as:  What needs to happen for the latest recommonmark, with updated AutoStructify support, to be deployed on ReadTheDocs.org?

Motivation: Contributors to a couple ReadTheDocs projects i maintain have learned Markdown for use in the [GitLab](https://gitlab.com/)-hosted wikis and issue queues, as well as some familiarity from being on the Internet in the past decade.  As much as i'd love to say documentation is in ReStructuredText and that's that, i cannot do that in good conscience given that i mess up making external links in rst half the time.  (I'd use [AsciiDoc](http://asciidoc.org/) as advocated in [Codewriting](https://codewriting.org/) if left to my own devices.)  Documentation needs to be collaborative, so definitionally i'm not left to my own devices.  This means ReadTheDocs, with its excellent infrastructure and trusted reputation.  And it means Markdown, so people can easily contribute, including by copy-pasting things worked out in wikis, issues, and pads.

Current status: ReadTheDocs does [begrudgingly](http://ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/) support Markdown-only documentation, i really really don't want to give up cross-referencing documents, nor even semantic notes/warnings and everything else Sphinx can provide with ReStructuredText.  So i'm super excited that the latest version of [Recommonmark](https://github.com/rtfd/recommonmark) offers the ability to have Markdown documents that embed just enough ReStructuredText to do key directives, including document reference labels and admonitions.  Unfortunately it is [being](https://github.com/rtfd/recommonmark/issues/74) [reported](https://github.com/rtfd/recommonmark/issues/51) as not in the PyPi package management yet.

The most critical thing is that if someone references a file, for example:

```
[our values](values.md)
```
that it gets converted to the link to values.html.

`[our values](values)` also works, which is absolutely awesome.

This is all working locally!  (So long as i install with `pip install git+https://github.com/rtfd/recommonmark.git --upgrade`).

Does Recommonmark just need to get a new release into pypi?  Tag a first release on GitHub?  Or is there more to it than that, to get this wonderful new future on ReadTheDocs?

## Details

* Read the Docs project URL: https://readthedocs.org/projects/agaric-documentation/
* Read the Docs username (if applicable): mlncn

## Expected Result

Include a reference in a .md file to another .md file or a the named label using markdown link syntax, correctly determined to be an internal reference by recommommark autostructify.

## Actual Result

Broken links, as seen here: https://agaric-documentation.readthedocs.io/en/latest/purpose.html

**Comment by stsewd** [comment]
If you need the latest version from the git repo, you can add that as a requirement in your `requirements.txt` (using the git url).

**Comment by mlncn** [comment]
That's amazing!  I didn't realize that could work on rtd's hosting.

Thanks @stsewd!

Would still be interested in helping advance the default for everyone  :-)

**Comment by stsewd** [comment]
Closing as this was resolved, hope the team can make a more up to date release of recomonmark soon!

**Comment by mlncn** [comment]
I couldn't find documentation on how to make this work.  I had hallucinated that it was working but in fact my builds have been reported failing since i added a `requirements.txt` file with a single line:

```
git+https://github.com/rtfd/recommonmark.git
```

Ironically, the error message in the failing build is "No module named CommonMark".

Hmm, actually, on another project with the same requirements.txt line the error, right after `from CommonMark import DocParser, HTMLRenderer`, is "ImportError: cannot import name DocParser"

In https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html i had missed the link to https://pip.pypa.io/en/stable/user_guide/#requirements-files 

But that is still just general information on pip requirements files.  It doesn't say what ReadTheDocs actually needs in its supplemental ones.

I'm trying the contents of https://github.com/rtfd/readthedocs.org/blob/a197b0146c3f54b0a67e200e3550f548682e3d72/requirements/pip.txt

with just recommonmark substituted out.

Now i'm getting:

```
from CommonMark import Parser
ImportError: cannot import name Parser
```

I do not understand what is happening.

**Comment by stsewd** [comment]
You don't need all those requirements, from rtd, maybe you mean to add the requirements from the recommonmark repo. Anyway, I think you are facing this problem https://github.com/rtfd/recommonmark/pull/118

**Comment by mlncn** [comment]
@stsewd Thank you again for amazingly fast response!  Hmm, i'd expect that same error first, then.  But i realize what i need to do is get everything working in a virtualenv so that i can use a requirements.txt that i know works (right now pip freeze has every random pip thing i've ever installed on my computer, so i haven't wanted to use that).
