### ISSUE TITLE
Text in text code blocks is vertically mashed and squished together, in Chrome on Ubuntu 18.04

### ISSUE THREAD

**Issue by ttmc** [rtfd/readthedocs.org#4413]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bigchaindb-server/ with docs at http://docs.bigchaindb.com/projects/server/en/latest/ 
* Build URL (if applicable): NA
* Read the Docs username (if applicable): bigchaindb_admin

## Expected Result

Plain text code blocks should have some space between each horizontal line of text.

## Actual Result

When using Chrome 67.0 (64-bit) on Ubuntu 18.04, plain text code blocks have no space between the lines of text. The lines look like they are all mashed together. Below is a screenshot from http://docs.bigchaindb.com/projects/server/en/latest/simple-network-setup.html#set-up-the-firewall as seen in Chrome on Ubuntu 18.04.

![screenshot from 2018-07-23 17-16-52](https://user-images.githubusercontent.com/1210951/43086139-eec635b4-8e9c-11e8-8612-f371d341bae9.png)

You can find the source for that page at:

https://github.com/bigchaindb/bigchaindb/blob/master/docs/server/source/simple-network-setup.md

Below is a screenshot of the same docs from Firefox 61.0.1 (64-bit) on Ubuntu 18.04.

![screenshot from 2018-07-23 17-26-13](https://user-images.githubusercontent.com/1210951/43086398-89be4656-8e9d-11e8-94e0-a7523b095ac7.png)

**Comment by RichardLitt** [comment]
@davidfischer I think this is something you'd know about?

**Comment by humitos** [comment]
I wasn't able to reproduce this in Archlinux. I tested with Chrome 61.0.3163.79 (Build oficial) (64 bits) and Versión 68.0.3440.75 (Build oficial) (64 bits)
 and Firefox 61.0.1 (64-bits)

**Comment by davidfischer** [comment]
This appears to be an issue with the font Liberation Mono which is used on many Linux distros. https://github.com/rtfd/sphinx_rtd_theme/pull/657. I'm going to get this merged and deployed as it seems to be a recurring issue.

On MacOS it looks good, FWIW. I'll get the above PR merged though.

## Screenshots
<img width="1378" alt="screen shot 2018-07-27 at 10 03 35 am" src="https://user-images.githubusercontent.com/185043/43335597-661ab290-9184-11e8-8a9f-8b07299c42a7.png">
Chrome 67.0.3396.99 (Official Build) (64-bit)

<img width="1390" alt="screen shot 2018-07-27 at 10 05 33 am" src="https://user-images.githubusercontent.com/185043/43335713-aa82ae7e-9184-11e8-8a21-6cc9ccc732c8.png">
Firefox Developer Edition 62.0b12 (64-bit)

**Comment by davidfischer** [comment]
I got that PR merged and released. I think you have a few docs build issues in master but if you get it building this issue should be resolved.

**Comment by ttmc** [comment]
@davidfischer Thanks! I'll close this issue.

**Comment by ttmc** [comment]
We resolved the issue that was causing our docs to not build. They are building again, and now they look great in my browser (Chrome on Ubuntu). Thanks!
