### ISSUE TITLE
Remove `marketdata` project from RTD

### ISSUE THREAD

**Issue by femtotrader** [rtfd/readthedocs.org#4421]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/marketdata/
* Read the Docs username (if applicable): @milktrader

Following https://github.com/JuliaQuant/MarketData.jl/issues/46

We need to remove project page https://readthedocs.org/projects/marketdata/ because doc is now available at http://juliaquant.github.io/MarketData.jl/latest/

**Comment by femtotrader** [comment]
Hello @humitos 

I haven't get any reply from @milktrader.
Could you remove RTD project page https://readthedocs.org/projects/marketdata/ because doc is now available at http://juliaquant.github.io/MarketData.jl/latest/

Kind regards

**Comment by femtotrader** [comment]
Hi @humitos 

Any news?

Kind regards

**Comment by humitos** [comment]
I didn't get any response either. I removed the project. Thanks for your patience.

**Comment by femtotrader** [comment]
Thanks @humitos
