### ISSUE TITLE
Stable not updated to last tag

### ISSUE THREAD

**Issue by jouvin** [rtfd/readthedocs.org#4435]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/quattor-pan/versions/
* Build URL (if applicable): https://readthedocs.org/projects/quattor-pan/builds/7547701/
* Read the Docs username (if applicable): jouvin@lal.in2p3.fr

## Expected Result

`stable` rebuilt with tag `pan-10.7`

## Actual Result

`stable` is stucked with `origin/10.4`. Not sure how it happened as I don't thing it ever existed. I tried to wipe the build, disable the stable version and clicked on the 'Clean' button in the inactive version list... I didn't manage to fix the problem.

`latest` doesn't seem to suffer a similar problem.

**Comment by stsewd** [comment]
Can you please try rebuilding `latest` or `master`? That way the versions are refreshed.

**Comment by jouvin** [comment]
Unfortunatly, it doesn't help (https://readthedocs.org/projects/quattor-pan/builds/7550171/). The problem remains that in the version list, the associated branch/commit for `stable`  remains `origin/10-4`, something that doesn't exist and it never gets updated...

**Comment by jrha** [comment]
I fiddled around with the for a while thinking that perhaps our tag versions were not being parsed, but in the end I created the `10.4` branch it was referring to and that seems to have unstuck it.

**Comment by stsewd** [comment]
@jouvin I can see that your stable version has the new commit now, were you able to solve the issue?

**Comment by jouvin** [comment]
As said by @jrha we managed to fix the problem by creating the missing branch so that RTD managed to compile the stucked `stable` and after that it got updated as expected. May be worth an entry in the FAQ...

**Comment by jrha** [comment]
@stsewd thanks, #4259 seems like precisely what we hit, I don't feel like trying to reproduce it again though!
