### ISSUE TITLE
Inconsistency in documentation on docker image in use.

### ISSUE THREAD

**Issue by hsorby** [rtfd/readthedocs.org#4437]
The documentation on which Docker image is currently in use is inconsistent.

[readthedocs website](https://github.com/rtfd/readthedocs.org/blob/master/docs/builds.rst) says the Docker image currently in production use is `readthedocs/build:2.0`.  However the [Docker images repo.](https://github.com/rtfd/readthedocs-docker-images/blob/master/README.rst) says `readthedocs/build:3.0` is the latest image supported by readthedocs.

Is one of these two statements incorrect?

**Comment by stsewd** [comment]
The team is going to release the new docker images soon (and 3.0 would be the new stable), for now we are using https://github.com/rtfd/readthedocs-docker-images/tree/releases/3.x as latest

**Comment by stsewd** [comment]
Anyway, the docs say

> This is the latest default image supported by Read the Docs

I think that means the `latest` image == `3.0`, see https://docs.readthedocs.io/en/latest/yaml-config.html#build-image

**Comment by hsorby** [comment]
I think I see, and 

> This is the stable image previously used

Means this is the stable image previously used as latest?

**Comment by hsorby** [comment]
With the soon to be released docker images would 4.0 be the new latest?

**Comment by stsewd** [comment]
Yes, and we will only support `latest` and `stable`, no numbered versions anymore https://github.com/rtfd/readthedocs-docker-images/issues/62.

**Comment by hsorby** [comment]
> `readthedocs/build:2.0`
>    **stable**  Ubuntu 16.04 based image. This is the **stable** image previously used

Ok, I think this is the bit that has me confused.  To me it says that there is another image that is the **stable** image and that this one is the previous **stable** image.  But from the documentation elsewhere this is the **default** image and it is currently in use and possibly not previously in use????

**Comment by stsewd** [comment]
Yeah, that's confusing, not sure what is the correct, maybe just remove the second sentence or just remove the `previously`.

**Comment by hsorby** [comment]
So after reading the documentation you have pointed me at, I think the second sentence should read:

 `This is the **default** image currently in use.`

**Comment by agjohnson** [comment]
The docs are currently correct and will be updated as soon as we have a release. The docker images repo latest doesn't reflect production.

Closing as this isn't currently an issue.

**Comment by hsorby** [comment]
Then it would seem that the documentation isn't clear.

**Comment by RichardLitt** [comment]
@agjohnson Any chance we could improve them?
