### ISSUE TITLE
Build timeout due to autodoc requirements

### ISSUE THREAD

**Issue by eendebakpt** [rtfd/readthedocs.org#4443]
## Details

To get autodoc to work I added `setup_py_install: true` to the `.readthedocs.yml` (as described in #3634). A side effect is that my project must now be compiled by readthedocs, before it can be installed. Since my projects compiles code using swig and C++ I created a conda environment file in order to install [swig](http://www.swig.org/) in the build environment. This seems to be working, but now the build takes too long and I get a `Build exited due to time out` error. 

Is it possible to either
- Use autodoc, without building the project?
- Increase the time limit for this project?

More info:

* Read the Docs project URL: https://oapackage.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/oapackage/builds/7559891/
* Read the Docs username (if applicable): eendebakpt

## Expected Result

The build should have taken place within the amount of time allowed or autodoc should work without installing the package.

## Actual Result

A timeout error was generated.

**Comment by peendebak** [comment]
@stsewd I checked the link, but I don't see how this would help. My project does have a C extension, but I don't  see hoe the mocks can prevent building the extension.

**Comment by stsewd** [comment]
Yeah, you can't use mocks in those cases :/, we need to wait for a maintainer to increase your time limit, but it seems very weird: the command says ` Command killed due to excessive memory consumption`, but the general message says `Build exited due to time out`

**Comment by humitos** [comment]
@eendebakpt hi! you may want to subscribe to this issue about adding `swig` to the image container: https://github.com/rtfd/readthedocs-docker-images/issues/15

Let's handle the timeout issue for now at #4757

**Comment by eendebakpt** [comment]
Fixed with #4757
