### ISSUE TITLE
Build use wrong python version

### ISSUE THREAD

**Issue by LevavasseurYann** [rtfd/readthedocs.org#4445]
## Details

Hello,

I'm strugelling with *sphinx* and *readthedoc* since about 2 weeks and i'm about to left the battlefield.
Since the beginning i've tried many thing to build the documentation first with setup.py and now with YAML file. The point is that some of my imported package seems to fail the build even tough the build is a success. In fact some of my module/class/function aren't readed by the autodoc due to, i think, *tslearn* and *prefixspan* packages. I've tried to create the environment with a requirment.txt file but the environment isn't able to find *tslearn* and then i've tried to mock some of this packages.
All this attempt leave a blanck space where it should be the module doc of half of my files.
With the last build (successfull build btw) i've found the env use python 2.7 even though i've write in the yml file that i wanted python 3.6.
I'm about to abandon, if someone encoutered the same issues or find easly what is going on i take any advice.

thanks

* Read the Docs project URL: https://readthedocs.org/projects/workspace-internship/builds/7560664/
* Build URL (if applicable): https://workspace-internship.readthedocs.io/fr/latest/
* Read the Docs username (if applicable): YnnLvvssr

## Expected Result

Autodoc find all my comments in all the module

## Actual Result

Some module stay blank after a successfull build

**Comment by stsewd** [comment]
When you use conda, you need to specify the python version in your environment file

**Comment by stsewd** [comment]
See https://github.com/rtfd/readthedocs.org/issues/4293#issuecomment-405094548

**Comment by LevavasseurYann** [comment]
It work ! Thanks a lot
And after some others changes all finaly working.

**Comment by stsewd** [comment]
Thanks for the update and using rtd ;)
