### ISSUE TITLE
autosummary failed to import on latest build image

### ISSUE THREAD

**Issue by t-makaro** [rtfd/readthedocs.org#4446]
## Details

I've tried everything I can think of / could find on the internet, but autosummary keeps failing because it can't import my package. 

At first I thought it was because, rtd wasn't installing matplotlib. I created a new local environment without matplotlib, and was able to reproduce the error. I set rtd to install matplotlib. The error persisted. 

Then I realized it might be python3.5 (I use f-strings). I created a new local environment with python 3.5, I was able to reproduce the error. I set rtd to use python3.6. rtd fails to import my package.

I tried, ```pip_install=true```. I tried ```setup_py_install=true```. Neither worked.
I tried using conda with an environment.yml file, and got ```docs/requirements.txt does not exist``` which it shouldn't even need. 

I tried messing with ```sys.path.insert(…)``` in ```conf.py```, and using an environment without my package installed. That worked locally, but not on rtd.

Everything I've tried works locally, but not on rtd. The only thing that I can think of that I haven't tried is adding support for python 3.5 to my package.

* Read the Docs project URL: https://animatplot.readthedocs.io/en/latest/api.html#animation
* Build URL (if applicable): https://readthedocs.org/api/v2/build/7561124.txt
* Read the Docs username (if applicable): t-makaro

## Expected Result

My documents build with autodoc/autosummary

## Actual Result

My documents build without autodoc/autosummary leaving out all of the autogenerated docs.

**Comment by t-makaro** [comment]
Huh, adding python 3.5 support to my library and removing my readthedocs.yml fixed my problem.

**Comment by humitos** [comment]
To use python3.6 in Read the Docs you need to use `latest` build image and set `3.6` in the `python` option. Look at the example at: http://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by stsewd** [comment]
I think maybe it was a problem when changing environments and using the pip cache, can you try wiping the environment before changing the python version or triggering a new build with the new python version? You can wipe the environment in the Versions page, edit button

**Comment by t-makaro** [comment]
I tried the following three ```readthedocs.yml``` files. Tried building twice each with a wipe in between.

```yml
build:
  image: latest
python:
  version: 3.6
```
This gives the original issue. (docs build but without autodoc/summary)

```yml
build:
  image: latest
python:
  version: 3.5
```
This gives also the original issue. (docs build but without autodoc/summary)

And finally I tried:
```yml
python:
  version: 3.5
```
Works perfectly.

**Comment by t-makaro** [comment]
It doesn't help that the autosummary warning doesn't say why the import failed.

I can't make heads or tails of the docker image. (I've never dealt with docker before.)

The only packages that my package imports are ```numpy```(basically any version should work) and ```matplotlib>=2.2```(hard dependency even at import time) both are specified in my ```docs/requirements.txt```.

**Comment by stsewd** [comment]
We are planning to release some new docker images, hope that can solve the problem.

**Comment by stsewd** [comment]
We released our new docker images, can you give it a try now?

**Comment by xylar** [comment]
I am having what I believe to the the same problem.  Many of the classes that I document in my reference API show up fine when I build my documentation locally but not in ReadTheDocs.  For an example of missing autosummary, see:
https://mpas-analysis.readthedocs.io/en/v1.2/api.html#ocean-tasks

Like @t-makaro, this has been a problem for quite some time, likely ever since I switched to python 3.6 and `latest`, though I didn't notice it right away.

I just rebuilt so I presume that brought in the latest docker image and the problem persists.
https://readthedocs.org/api/v2/build/8631616.txt

I get a huge number of `WARNING: [autosummary] failed to import ...` messages that don't occur when I run locally.  The auto-generated API is incomplete enough to not be very useful.

Like @t-makaro, I will try going back to python 3.5 but my repo plans to stop supporting python 3.5 in the near future so that's no a great long-term solution.

**Comment by xylar** [comment]
I apologize, I spoke too soon.  Reverting back to python 3.5 and dropping latest seems to have made no difference for me so I suspect my issue is something else.

**Comment by xylar** [comment]
Again, very sorry.  I have found the problem and it is a library dependency, so unrelated.

**Comment by t-makaro** [comment]
I tested the new 4.0 image and it works fine. What's strange is that I then decided to try to use the 3.0 image and it worked too! I ended up using:

```
build:
  image: latest

python:
  version: 3.6
```
for my ```.readthedocs.yml```.

I can now build my docs with python 3.6 on rtd, so I'm closing as fixed.
