### ISSUE TITLE
Conda crashes with error 247

### ISSUE THREAD

**Issue by wkerzendorf** [rtfd/readthedocs.org#4447]
## Details

* Read the Docs project URL:  tardis.rtfd.org
* Build URL (if applicable): https://readthedocs.org/projects/tardis/builds/7555533/
* Read the Docs username (if applicable): wkerzend

## Expected Result

Should just install the conda environment and make the documentation

## Actual Result

it crashes with error code 247

**Comment by stsewd** [comment]
Looks like a problem with a package and the build environment, maybe you can test this solution https://github.com/stan-dev/pystan/issues/384#issuecomment-334356158

**Comment by stsewd** [comment]
I'm seeing the same issue in this project https://readthedocs.org/projects/fwdpy11/builds/7564088/. Maybe this is a conda problem? Can your try building locally?

**Comment by wkerzendorf** [comment]
Locally it builds the conda env with ease

**Comment by wkerzendorf** [comment]
@stsewd it now works again - for whatever reason. In our latest PR we've now also removed other channels - maybe that helps with resource problems.

**Comment by humitos** [comment]
@wkerzendorf multiple channels are a possible problem. Read my comment at https://github.com/rtfd/readthedocs.org/issues/4449#issuecomment-409018796 and the linked conda issue there.

**Comment by stsewd** [comment]
@wkerzendorf thanks for letting us know, I'm closing this issue, seems like the problem that @humitos mentions.
