### ISSUE TITLE
Unexpected build failure

### ISSUE THREAD

**Issue by molpopgen** [rtfd/readthedocs.org#4449]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fwdpy11
* Build URL (if applicable): https://readthedocs.org/projects/fwdpy11/builds/7560011/
* Read the Docs username (if applicable): molpopgen
## Expected Result

The docs to be built

## Actual Result

While trying to resolve #3192 for my project, @stsewd suggested that I trigger a rebuild of a branch manually.  Doing so resulted in this error:

```
Error
There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7560011).
```

Looking at the various outputs, there are no clues as to why this build failed, meaning I don't know what to fix.

This branch has had zero commits to it since the last successful build, too, which was ~4 months ago.

**Comment by stsewd** [comment]
The step that fails is when creating the documentation with sphinx (it's not displayed because of https://github.com/rtfd/readthedocs.org/issues/4288), I think your build if failing because of memory limits, I'm not sure why the other pass months ago, maybe the builders were too busy at the moment. Can you try building again?

**Comment by molpopgen** [comment]
ok, will give that a try.

**Comment by molpopgen** [comment]
Still no luck.  Another attempt seems to fail at the conda install step, but no reason is given.

**Comment by humitos** [comment]
@molpopgen does this happen randomly? (I triggered a new build of `dev` to test it)

I was able to build `dev` branch locally with `2gb` of memory. So, my guessing is that your process start consuming too much memory (more than `1gb` which is the default) and it was killed.

There is an issue reported in conda repo about the 247 exit code: https://github.com/conda/conda/issues/5004

I suggest you to try one of this workarounds if you didn't yet: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by molpopgen** [comment]
@humitos It seems to happens pretty consistently.

As for the RAM use, the setup is already minimal.  The requirements.txt is the minimum required to build the package and the dox.   The package must be built on RTD, else I can only build docs for, say, the current release on bioconda, and not the development/latest branches.

On my Pop OS! laptop, using GCC7.3, the peak RAM for the build is ~600MB and then the peak RAM for the Sphinx is under 250MB.  (Looking at RES here, not VIRT, btw.) Only the html output is getting built.  The RAM use during compilation is not that extreme for a C++ project.  So I gather that the 1GB limit includes the total for the build attempt, and is being applied to the conda install step, thus killing the job?

**Comment by humitos** [comment]
Hi @molpopgen! I've already increased the MEM available for your project's build.

I'm closing this issue for now but feel free to re-open if you consider.

> NOTE: I found that your project is failing because a different reason which is not being logged properly (it's a known bug and I just opened a PR for it which will be deployed soon hopefully: #4591) but locally it says `Segmentation fault (core dumped)` in the `conda install` step. I increased the memory for your project to `2g` locally and it passed.

Please, open a new issue if after deploying that fix your project is still having problem and I will take a look at it.

**Comment by wkerzendorf** [comment]
@humitos I encountered that again on wsynphot.rtfd.io - I think it is definitely the memory requirement that kills us and I have seen it now a few times. I understand running this with more RAM will cost more. Is there a possibility that you would allow us to pay for more RAM. using conda is very convenient. Thank you!!!

**Comment by humitos** [comment]
@wkerzendorf I don't see any build with memory issues in your project.

Please, open a new issue by filling the template with the information requested and I will take a look.

**Comment by humitos** [comment]
@wkerzendorf I don't see any build with memory issues in your project.

Please, open a new issue by filling the template with the information requested and I will take a look.
