### ISSUE TITLE
Configuring PHP framework in Readthedocs

### ISSUE THREAD

**Issue by patricdev** [rtfd/readthedocs.org#4453]
Hi Team, 

First of all, ReadTheDocs is amazing and I like the concept much and like to use it for my project developed in PHP.

I am trying to Implement readthedocs for my laravel project which is managed in bitbucket. Basically, it's a PHP language.

**Steps  Completed**

1. Created an account in readthedocs.org
2. Configured repository url, branch, programming language and other stuff.
3. Generated the webhook under Integration section and configured in the bitbucket project settings>> webhook.
4. Created docs folder in my project root folder.

**Queries:-**

1. How to proceed with the sphinx installation in Apache web server.
2. Need the steps to continue in the docs folder. like installation sphinx, quickstart configuration, and automatic sphinx-build.
3. Also, I need how to create .rst file and import templates. Any tutorial for that.
4. Is the documentation created under docs is manual writing right? and it does not pull the source code class, function comments into the docs folder?

Thanks
Arun Kumar
arunkumarinfo@gmail.com

**Comment by agjohnson** [comment]
You can find a lot of this information in our documentation or in the sphinx documentation and quick start guides. Read the Docs hosts documentation, so you don't need to add apache to host your documentation.

There are ways to do php autodoc, I'd suggest you look at some of the php projects that have had luck using sphinx already.

Closing as this isn't an issue with Read the Docs
