### ISSUE TITLE
Support strict validation for the configuration file

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4455]
We can support strict validation in the configuration file (v2 only at this point).

## What do I mean by _strict validation_?

Just to validate that there aren't other keys in the config file

## Why do we want this?

It can prevent typos :). It should be straightforward to implement this in the current validation steps. Just pop each value whenever it is used.

**Comment by davidfischer** [comment]
I'm +1 for this as it will prevent future bugs.

**Comment by humitos** [comment]
I think this is something good to have. I will avoid confusions to users, and by given them a good validation error message, it's something that they can fix by themselves.
