### ISSUE TITLE
Getting 404 on Module Index page

### ISSUE THREAD

**Issue by mertyildiran** [rtfd/readthedocs.org#4465]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dragonfire/
* Build URL (if applicable): https://readthedocs.org/projects/dragonfire/builds/
* Read the Docs username (if applicable): **mertyildiran**
* GitHub Sphinx documentation source: https://github.com/DragonComputer/Dragonfire/tree/master/docs/source

## Expected Result

On my local machine, I'm building the documentation with:

```Shell
sphinx-quickstart
sphinx-apidoc -f -o source/ ../dragonfire/
make html
```

and Module Index page is working perfectly fine:

![](https://i.imgur.com/VlXbo2s.png)

## Actual Result

But when I build the documentation on Read the Docs side, I get 404 on Module Index page: https://dragonfire.readthedocs.io/en/latest/py-modindex.html

I tried to remove non-ASCII characters with:
https://github.com/DragonComputer/Dragonfire/commit/e45a11e7402e8fa53a6311d012ea6db04f537458
https://github.com/DragonComputer/Dragonfire/commit/b1818c4c04a31d57601f216060291893f8055cb2
and removed Markdown support with:
https://github.com/DragonComputer/Dragonfire/commit/2a31dc1a8215e0f4a18d795438be5cb4d6c26431

but none of them solved the issue.

![](https://i.imgur.com/nhM4ujQ.png)

**Comment by stsewd** [comment]
Sorry but I don't see the file in your repo https://github.com/DragonComputer/Dragonfire/tree/master/docs/source

**Comment by mertyildiran** [comment]
`make html` generates it by looking up for **docstrings** in the whole project:
![](https://i.imgur.com/ZWikcK3.png)
I did what you said in [here](https://github.com/rtfd/readthedocs.org/issues/2396#issuecomment-397715773) but did not change anything.

**Comment by stsewd** [comment]
RTD execute the `sphinx-build` command only, it doesn't execute the `make` file nor the `sphinx-apidodc` command. See https://github.com/rtfd/readthedocs.org/issues/1139

**Comment by mertyildiran** [comment]
@stsewd I removed the build directory with `rm -rf build/` and ran:

```Shell
sphinx-build -b html source/ build/
```

It gave me exactly the same result with `make html`. I don't understand your point?

**Comment by stsewd** [comment]
You executed this command `sphinx-apidoc -f -o source/ ../dragonfire/`, which places the output inside the source/ dir

**Comment by mertyildiran** [comment]
@stsewd `sphinx-apidoc -f -o source/ ../dragonfire/` generates the `.rst` files according to my module structure right? So what's the relevance of `sphinx-apidoc` to generating `.html` documents from those `.rst` files?

**Comment by stsewd** [comment]
The `modindex` or `py-modindex` is still missing there, not sure how apidoc works here, can you check if this happens in a new virtualenv executing the same steps that rtd does?

**Comment by mertyildiran** [comment]
@stsewd please look at this repository for example: https://github.com/goldsmith/Wikipedia/tree/master/docs/source

It does not have any `modindex.rst` file, `py-modindex.rst` file or anything like that but it has http://wikipedia.readthedocs.io/en/latest/py-modindex.html available in its documentation.

**Comment by mertyildiran** [comment]
@stsewd I realized that the build was actually **failing** due to some missing dependencies and/or post-install scripts(when I noticed the "View raw" link on Read the Docs):

```Shell
WARNING: autodoc: failed to import module 'dragonfire.api'; the following exception was raised:
No module named 'nltk'
WARNING: autodoc: failed to import module 'dragonfire.arithmetic'; the following exception was raised:
No module named 'nltk'
WARNING: autodoc: failed to import module 'dragonfire.config'; the following exception was raised:
No module named 'nltk'
...
```

So after dealing some problems like **excessive memory consumption**, mocking out Python C extension, including Markdown into reStructuredText, etc. and after 23 commits/builds I finally achieved what I want:

https://github.com/DragonComputer/Dragonfire/commit/67068f13eb98b1a267ff89faec081b0d153cef92

https://dragonfire.readthedocs.io/en/latest/py-modindex.html (Working :+1: )

Thanks for the help! :trophy:

**Comment by g1itch** [comment]
> https://dragonfire.readthedocs.io/en/latest/py-modindex.html (Working +1 )

Not working. It's still showing the maze.
