### ISSUE TITLE
ReadtheDocs cannot parse tables in markdown

### ISSUE THREAD

**Issue by wilsonyou** [rtfd/readthedocs.org#4466]
## Details

I build my file from github to readthedocs but found the tables in markdown files cannot be parsed.

Could you please give an effective way to solve the issue.

This is my project address： 
https://github.com/wilsonyou/hopeone

this is location for the build 

https://hopeone.readthedocs.io/en/latest/generating-addresses.html

If you can provide an easy-to-understand method to solve this problem, I would really appreciate.

**Comment by stsewd** [comment]
This is a problem with sphinx and markdown file, here you can see some solutions https://github.com/rtfd/recommonmark/issues/3 https://github.com/rtfd/recommonmark/issues/103, or maybe you can consider writing your docs using reStructuredText.

**Comment by wilsonyou** [comment]
Thank you for you suggestions. But I cannot get the issue solved.

I don't know  what files are needed or how to configure the Admin in ReadtheDocS. 

Some says that the setup.py is needed or the requirements.txt is needed. I am not sure how to handle this.

Could you help me on this ?

Thanks

**Comment by stsewd** [comment]
You can use the admin interface of your project to specify a requirements.txt file or use a yaml file https://docs.readthedocs.io/en/latest/yaml-config.html#requirements-file

**Comment by wilsonyou** [comment]
@stsewd 

Thank you for your quick turnaround.

But I still cannot solve my issue.

The major issue is that I have many tables in md files, but  these tables cannot be parsed. If you could give me a real example about what files are needed and how to configure these file, then I think I can figure out.

Thanks

**Comment by stsewd** [comment]
In the related issue, there is a suggestion about using https://github.com/ryanfox/sphinx-markdown-tables, you may want to read those instructions

**Comment by wilsonyou** [comment]
@ I have read these instructions and did as the guide told. But the tables are still not parsed
Could you check my projects?
https://hopeone.readthedocs.io/en/latest/generating-addresses.html
Thanks

**Comment by wilsonyou** [comment]
@stsewd 
I have read these instructions and did as the guide told. But the tables are still not parsed
Could you check my project?
https://hopeone.readthedocs.io/en/latest/generating-addresses.html

Thanks

**Comment by stsewd** [comment]
I think you need to add a `requirements.txt` on your project with `sphinx-markdown-tables` as requirement.

**Comment by stsewd** [comment]
This should help too https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

**Comment by wilsonyou** [comment]
@stsewd 
Yes, I think you are right. A requirement.txt is needed. But I don't know how to configure the requirement.txt even I read the link you provided.

Could you please check my project and provide a reqirement.txt which is configured and ready to use?

Thank you for your support.

**Comment by wilsonyou** [comment]
@stsewd 
If you could provide that requirement.txt file. Please send it to me
Email: wilson_you@126.com
BTW, I think readthedocs is a great website to host documentation but if table conversion is not supported, I would feel really disappointed.

**Comment by wilsonyou** [comment]
I read your documentation on the website. It seems that the backend will read the conf.py file by default. But in this way, the table conversion is not supported. So, I tried to configure the Advanced Setting, but got stuck in it. In Advanced Setting, when I clikc the option  'Install your project inside a virtualenv using setup.py install', I have to input the requirement.txt file below the option.
But now, I don't know how to configure the setup.py and requirement.txt files.

**Comment by stsewd** [comment]
You need to create a `requirements.txt` file with this content

```
sphinx-markdown-tables
```

The link to the docs explains how to setup rtd to use the requirements.txt file.

> BTW, I think readthedocs is a great website to host documentation but if table conversion is not supported, I would feel really disappointed.

I think that is a problem with the sphinx extension that does the markdown supports, sphinx is mainly focused in reStructuredText, you also have mkdocs, which does support markdown.

BTW, your `setup.py` file doesn't seem to be right https://github.com/wilsonyou/hopeone/blob/master/setup.py. I'd recommend you to read a little about python packaging here https://packaging.python.org/guides/

**Comment by wilsonyou** [comment]
@stsewd 
Thank you for your suggestion. But I have little programming experience, and I don't know how to get started with your suggested link. Could you help on how to configure my setup.py？

**Comment by stsewd** [comment]
I think you may not need a `conf.py` file, can you try having only the `requirements.txt` file?

**Comment by wilsonyou** [comment]
I just now tried to input the requirements.txt file without selecting the conf.py. But it did not work.

**Comment by wilsonyou** [comment]
@stsewd I just now tried to input the requirements.txt file without selecting the conf.py. But it did not work.

**Comment by stsewd** [comment]
You don't need to mock `sphinx_markdown_tables` https://github.com/wilsonyou/hopeone/blob/6dd3252af7646c964a37a573d8eb042e8d5901d7/conf.py#L27

**Comment by stsewd** [comment]
I'm not sure if your project needs to mock the other packages, but you only need to delete the `sphinx_markdown_tables` from that list

**Comment by wilsonyou** [comment]
Hi man, finally, it works! Thank you so much!

By the way, if you want to know anything about China, please do not hesitate to ask me.

I am a technical writer in Beijing, China.

If you come to China in the near future, please contact me, I must buy a dinner.

Phone number : +86 13671352506
WeChat: 13671352506

**Comment by stsewd** [comment]
haha, glad that it works! I don't have plans to go to China in the near future, but who knows, I'll keep it in mind, thanks!

**Comment by anvithks** [comment]
> Hi man, finally, it works! Thank you so much!
> 
> By the way, if you want to know anything about China, please do not hesitate to ask me.
> 
> I am a technical writer in Beijing, China.
> 
> If you come to China in the near future, please contact me, I must buy a dinner.
> 
> Phone number : +86 13671352506
> WeChat: 13671352506

@wilsonyou how did you manage to get this working?

**Comment by wilsonyou** [comment]
@anvithks  Hi, you can refer to the following link : https://github.com/bumoproject/bumo-docs-cn

**Comment by anvithks** [comment]
@wilsonyou thank you. I managed to get it to work.
