### ISSUE TITLE
Things around i18n

### ISSUE THREAD

**Issue by ewjoachim** [rtfd/readthedocs.org#4471]
Following last years's chat on #2944 and the recent announcement on transifex by @agjohnson , I did a new pass on the french translation and found some problems (I've been marking them through transifex directly, see "39 problems" on this page https://www.transifex.com/readthedocs/readthedocs/dashboard/).

Now I think most of these problems are pretty much stemming from the usage of `blocktrans` without `trimmed`, and that makes the translation quite more complex to write. There are some other issues, though.

I was thinking of something we did recently at my work: requiring any PR that touches a translation to run makemessages and write the `.pot` file (BTW, the file that has no translation and is used to create other translations should ideally be identified with the extension `.pot` for `po template`, and not `.po`). This is easily done in the CI.

Then you could imagine having someone that has some experience on checking translation sources as a CODEOWNER of this `.pot` file, and would be automatically set as reviewer of any PR that touches this file.

Not saying it will solve all problems, but it might well help :)

**Comment by ewjoachim** [comment]
Wow how did I miss the other i18n issues you opened >< Sorry for the noise, should have been posting to an existing issue 😭

**Comment by humitos** [comment]
I added a note in #4479 mentioning the usage of `trimmed` in our docs. I think this could help to keep the blocktrans updated.

Also, I created a PR to add `trimmed` to all blocktrans that need this option at #4480 

@ewjoachim does this help? do you have other suggestions?

**Comment by agjohnson** [comment]
Thanks for the feedback @ewjoachim !

I think we're aiming to automate updating translations for our workflow, but we're not there yet.

I'll review some of the issues and note then in Tranisfex. I don't know if we have good answers for some of the issues.

Closing this here as I don't know if there are any other actionable changes besides `trimmed` updates
