### ISSUE TITLE
Support request: deletion of several projects

### ISSUE THREAD

**Issue by lextm** [rtfd/readthedocs.org#4473]
## Details

* Read the Docs project URLs:
https://readthedocs.org/projects/dockpanelsuite/
https://readthedocs.org/projects/jexus/
https://readthedocs.org/projects/jexuswebserver/
https://readthedocs.org/projects/linpeiman/
https://readthedocs.org/projects/obfuscar/
https://readthedocs.org/projects/restructuredtext.net/
https://readthedocs.org/projects/sharpsnmp/
https://readthedocs.org/projects/sharpsnmppro/

* Read the Docs username (if applicable): lextm

## Expected Result

As the creators of such projects I should be able to delete them.

## Actual Result

Instead all I got is "Fail.  Check back in a bit!" from the delete link. Similar to #4042 

Please help.

**Comment by humitos** [comment]
Thanks for reporting this @lextm! I found some interesting logs that could point us in the right direction to solve this issue.

There is a problem with how we delete the SSL via Cloudflare for the custom domain. We will be working on this and hopefully, we will have a fix for this soon.

Sentry: https://sentry.io/read-the-docs/readthedocs-org/issues/630965612/
Error at: https://github.com/readthedocs/readthedocs-ext/blob/36e27c05199bc16660d54df66c6d239f097786ad/readthedocsext/cdn/providers/cloudflare.py#L136

**Comment by davidfischer** [comment]
Thanks for reporting these. You should be able to delete these projects now. For some reason, Cloudflare failed to get an SSL certificate for these, they got into a weird state, and then the API to remove them was throwing a 500. A fix to handle this more gracefully on the RTD side is in review.

**Comment by lextm** [comment]
Thank you, guys! It works now.
