### ISSUE TITLE
Table of Contents jumping

### ISSUE THREAD

**Issue by skaller** [rtfd/readthedocs.org#4474]
## Details

* Read the Docs project URL: https://felix.readthedocs.io/
* Read the Docs username (if applicable): skaller

Using a  vertically constrained browser window:

(1) Please open https://felix.readthedocs.io/en/latest/expressions.html
(2) Scroll down the left margin TOC and click on "Qualified Names"
(3) The TOC jumps back to the top
(4) To select the next entry from the TOC, one has to scroll down each time

## Expected Result

The TOC shouldn't move in this case. 

## Actual Result

The TOC jumped.

BUG2
=====

When I scroll the document text, the TOC scrolls too. The TOC should not move.
The TOC should be in an independent window. In fact scrolling the TOC also
scrolls the text pane.

# Solution

The wrong HTML positioning attributes are being used. The TOC window
should be locked onto the side of the browser window. It should use 
CSS `position: fixed`.

**Comment by agjohnson** [comment]
This is a regression, automatic scrolling was already part of the navigation menu. This is a theme issue either way though. I'll move this issue into our theme tracker.

I don't recall if we have a scrolling option on our theme, but if not, you can change this with CSS. The theme is meant to scroll in this behavior however, so this is not buggy behavior. We won't be using fixed positioning for the menu.
