### ISSUE TITLE
Index layout wrong

### ISSUE THREAD

**Issue by skaller** [rtfd/readthedocs.org#4475]
## Details

* Read the Docs project URL: https://felix.readthedocs.io/
* Read the Docs username (if applicable): skaller

Please examine the generated index here:

https://felix.readthedocs.io/en/latest/genindex.html

## Expected Result

The index contains two level index entries. It should look like this:

```
A
abstract
  type
application
  direct
  indirect
```

## Actual Result

The second level subentries line up on the left margin, making
the index incomprehensible. It actually looks like this:

```
A
abstract
type
application
direct
indirect
```
# Solution

Spaces should be inserted in front of the second level entries.

**Comment by agjohnson** [comment]
Moved this to rtfd/sphinx_rtd_theme#671, this is a theme issue with CSS, not an issue with RTD. Looks like the styling of `ul` might not consider this usage on `genindex`. Closing here.
