### ISSUE TITLE
Footer menu "needs" vertical scroll when many version/translation shown

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4496]
Accessing a project with so many versions and clicking on the versions menu, you will see so many versions that it impossible to click on Read the Docs links (project, build, github, etc) and also it's hard to select the translation.

![screenshot_2018-08-08 requests http for humans requests 2 19 1 documentation](https://user-images.githubusercontent.com/244656/43860880-73f7f14c-9b2b-11e8-8174-fabef1e4ae98.png)

> Edit: I'm showing this example with a local version of `requests` with many versions active. This is not happening in the production version of requests.

**Comment by dojutsu-user** [comment]
@humitos 
I tried some css adjustments locally. Here's the results

1. When there are too many versions and translations
![ezgif-4-045218f8984e](https://user-images.githubusercontent.com/29149191/50054995-cbe00f80-016e-11e9-8600-50b0ea7c7e18.gif)

2. When there are limited versions and translations
![ezgif-4-8a20fdd2583f](https://user-images.githubusercontent.com/29149191/50055000-d69aa480-016e-11e9-91d9-23e87cb9c10d.gif)

If these are okay, I can make a PR for this.
