### ISSUE TITLE
Upgrading a Gold subscription causes two recurring charges

### ISSUE THREAD

**Issue by UniversalSuperBox** [rtfd/readthedocs.org#4503]
## Details

* Read the Docs username (if applicable): UniversalSuperBox

## Expected Result

When changing from one subscription level to another, the difference between the two levels is charged. Alternatively, the previous subscription level is kept until the renewal where the new subscription amount is charged.

Either way, only one level is charged on the next renewal.

## Actual Result

I subscribed to Read the Docs Gold with a $10 subscription on July 8. The next day, I upped my subscription to $50. I was charged for both transactions, first for $10 and then for $50. Yesterday (August 8), I was charged $10 for my first subscription renewal. Today, I was charged $50 for the second.

I'm all for putting in the extra $10, but I'd rather get another two adoptable projects. :P

**Comment by stsewd** [comment]
Thanks for supporting rtd, hope the team can debug this and see what is happening soon.

**Comment by RichardLitt** [comment]
@davidfischer Probably related to #4504.

**Comment by UniversalSuperBox** [comment]
@RichardLitt, it's related but I tried the steps in #4504 to fix this.

**Comment by davidfischer** [comment]
Thanks for reporting this. From a charging (Stripe) perspective, here's what I see:

- 4 total charges:
  * $10 on 2018-07-08
  * $50 on 2018-07-09
  * $10 on 2018-08-08
  * $50 on 2018-08-09
- There is not an active "subscription" so unless action is taken you will not be charged in September.

So it looks to me like there are definitely some erroneous charges. Which ones would you like refunded? If you're planning to sign up again, perhaps refunding the 2018-07-08, 2018-08-08, and 2018-08-09 charges is right?

I haven't yet dug into the code but my guess is that the subscription code is a bit naive and it didn't delete/change the previous subscription. It just added a new one. When updating a subscription, it should probably just change the existing subscription (eg. $10/mo -> $50/mo) and not try to charge immediately or pro-rate it somehow.

**Comment by davidfischer** [comment]
> I haven't yet dug into the code but my guess is that the subscription code is a bit naive

It isn't actually! The code is supposed to [upgrade the subscription correctly](https://github.com/rtfd/readthedocs.org/blob/4d10f2e/readthedocs/gold/forms.py#L60-L68) which I believe won't charge until the next period. However, I can see from the Stripe logs that `source` didn't make it into the request and Stripe rejected the request after that. Then it defaulted to a new subscription.

Long story short, this is definitely a bug.

**Comment by UniversalSuperBox** [comment]
@davidfischer, It'd be great if 07-08, 08-08, and 08-09 could be refunded. Thank you for digging in to this so quickly!

**Comment by davidfischer** [comment]
Ok, I have refunded those 3. According to Stripe:

    Refunds take 5-10 days to appear on a customer's statement.

I'm going to leave this ticket open until we fix it.
