### ISSUE TITLE
One module documentation is not showing in readthedocs even if it shows up in local sphinx build

### ISSUE THREAD

**Issue by Tahsin-Mayeesha** [rtfd/readthedocs.org#4506]
## Details

Project URL : https://github.com/Tahsin-Mayeesha/Mediaviz/tree/master/docs/build/html
* Read the Docs project URL: https://mediaviz.readthedocs.io/en/latest/py-modindex.html

## Expected Result

I've one module named mediaviz.draw that is not showing up in Readthedocs, but it shows up
in my local build.  I'm not sure why readthedocs is skipping this module even if it's picking up
other modules.

**Comment by RichardLitt** [comment]
Thanks for logging this issue, @Tahsin-Mayeesha. ReadTheDocs support here is volunteer run, which means that there is no guarantee that someone will get to this urgently; if you want more urgent support, I would suggest either paying for support by buying a commercial license, or trying StackOverflow. Please see this [Support page](https://docs.readthedocs.io/en/latest/support.html).

**Comment by Tahsin-Mayeesha** [comment]
@RichardLitt  I found a workaround by directly writing into index.rst file all the automodules for the project. 

The reason I asked for urgent support was because I am participating in Google Summer Of Code 2018 with the deadline coming on August 14th, I basically needed to make the documentation work by then or find out other ways like directly hosting in Github pages and ditch readthedocs if necessary. I think the current workaround is sufficient for my purpose. 

Docs are up at https://mediaviz.readthedocs.io/en/latest/ , I really like the readthedocs theme too. 

However I'm curious myself why this bug would occur, even if all the modules are being listed the draw module keeps being missed when I import from Github. Should I close this issue now?

**Comment by stsewd** [comment]
I can see your package, not really sure what is the issue.

![screenshot_2018-08-12 python module index mediaviz 0 1 documentation](https://user-images.githubusercontent.com/4975310/43999992-2660c35a-9ddd-11e8-8ffd-ba1b56240457.png)

**Comment by RichardLitt** [comment]
@Tahsin-Mayeesha Glad you found a workaround. I edited the title so that other maintainers know this is not urgent anymore (it's a bit unfair to everyone else who might also have urgent bugs to say that yours is more important than theirs).

I'm not sure what the issue was. But if it's resolved, go ahead and close this. :)

**Comment by Tahsin-Mayeesha** [comment]
@RichardLitt  I don't care about the title at this point :) , I simply like my work to be done. 

To be really clear, the issue on why Readthedocs has failed to pick up one module consistently from the github import while sphinx makes the local build correct, that issue has not been solved as of yet.

 However I'm closing the issue. Glad I didn't have to ditch readthedocs from my first user experience!

**Comment by RichardLitt** [comment]
Thanks @Tahsin-Mayeesha! Glad you got it working.
