### ISSUE TITLE
Refactor config models to dataclasses

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4525]
Currently, we are using namedtuples. A problem with this is that you can't have default values when we move to python3 in production (3.7) we can refactor those to dataclasses.

Pros:

- Default values
- Type hints
- Less repetition
- Our code looks more cool :sunglasses: 

ref https://github.com/rtfd/readthedocs.org/pull/4456#discussion_r207318041

**Comment by invinciblycool** [comment]
Taking this up. Confirming that the dataclasses should be immutable?
Also where do I refer for the defaults?

**Comment by stsewd** [comment]
We move to use plain classes + `__sluts__` for now, closing.
