### ISSUE TITLE
Failed to create PDF build in readthedocs

### ISSUE THREAD

**Issue by wilsonyou** [rtfd/readthedocs.org#4527]
The original docment was written in Chinese.

1. Failed to build a PDF file
2. The links in html files did not work

Read the Docs project URL:
https://readthedocs.org/projects/bumodoc/builds/7644052/

github URL:
https://github.com/bumoproject/bumo/tree/wilsonyou-patch-1

When I tried to build a PDF build, it failed and the following error message was displayed.

! Package inputenc Error: Unicode char 式 (U+5F0F)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.85 ...式详细介绍了两种交易提交方式
                                                  ，即调用接口生成tr...
(That makes 100 errors; please try again.)
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on bubi.log.

Thank you for any one who could help me on this issues.

**Comment by wilsonyou** [comment]
@stsewd 

I tried some methods as you suggest, but it did not work.

Previously I build the doc written in English, it works.

We need to generate PDF files.

But now when the doc is Chinese, it seems some characters readthedocs cannot parse.

Could you provide some suggestions on how to configure the conf.py or the Admin?

Thanks

**Comment by stsewd** [comment]
As the linked issue, there isn't a solution right now :/

**Comment by wilsonyou** [comment]
@stsewd 
If the hyperlink does not,  i have to accept that.

But I hope the pdf problem can be solved.

**Comment by wilsonyou** [comment]
@stsewd 

Could you help to figure out what happened to the hyperlink. Because the hyperlink works in github and after i push the doc to readthedocs, the hyperlink does not work

**Comment by stsewd** [comment]
Which hyperlink?

**Comment by wilsonyou** [comment]
@stsewd 
https://bumodoc.readthedocs.io/zh_CN/wilsonyou-patch-1/docs/keypair%E6%89%8B%E5%86%8C.html#protobuf%E6%95%B0%E6%8D%AE%E7%BB%93%E6%9E%84
But when you check the hyperlinks in the file on github, they work.
https://github.com/bumoproject/bumo/blob/wilsonyou-patch-1/docs/keypair%E6%89%8B%E5%86%8C.md

**Comment by stsewd** [comment]
Oh, I see, the anchor links to the same document don't work, looks like the Chinese characters are removed from the anchor. I just found this https://github.com/rtfd/recommonmark/issues/83, can you check if the given workaround works for you?

**Comment by wilsonyou** [comment]
@stsewd 

Thank you, i will check out.

Do you have a solution to parse the encoding in the doc?

**Comment by stsewd** [comment]
>  Do you have a solution to parse the encoding in the doc?

Sorry, I don't know what you mean with that

**Comment by wilsonyou** [comment]
@stsewd 

I want to build a PDF file, but the readthedocs could not parse some characters in my documentation. So could you help me to solve this issue.
The following are some error codes:
1]

! Package inputenc Error: Unicode char 发 (U+53D1)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.80 \chapter
             {Keypair手册}

! Package inputenc Error: Unicode char 布 (U+5E03)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.80 \chapter
             {Keypair手册}
[2]
Chapter 1.

**Comment by wilsonyou** [comment]
@stsewd  You told me that I can deselect the "generate PDF" option, I tried and it really worked. 
But now my question is that I need the pdf file. So, please help me on this issue.
You can also refer to the following link:
https://readthedocs.org/projects/bumodoc/builds/7644690/

**Comment by wilsonyou** [comment]
@stsewd 
Thank you. When this function can be available? Do you have a plan?

**Comment by stsewd** [comment]
We don't have any plan, but I will try to see if the team can give priority to that issue (probably not soon as the team is really busy right now because we are migrating rtd to azure).

But I let you know that it could take a while, as we need to install the program in the latest docker image, then wait to release that image and finally change our code

Closing as there are other issues that track all the problems that were mention here.
