### ISSUE TITLE
Change validation message

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4530]
This line contains a wrong error message

https://github.com/rtfd/readthedocs.org/blob/79032b53b0aa75bce4d4a522c7f4771db730aa6c/readthedocs/config/config.py#L448-L452

 should be changed to a more accurate one, or even better, use the new validator `validate_dict` as we do in other places

https://github.com/rtfd/readthedocs.org/blob/79032b53b0aa75bce4d4a522c7f4771db730aa6c/readthedocs/config/config.py#L624-L625

Ref to https://github.com/rtfd/readthedocs.org/pull/4456#discussion_r210359620

**Comment by sriks123** [comment]
Hi @stsewd can I work on this issue?

**Comment by stsewd** [comment]
Sure, go ahead!

**Comment by RichardLitt** [comment]
@sriks123 Just wanted to point out that @invinciblycool has provided a fix for this! Might want to find another issue. :)
