### ISSUE TITLE
Pip dependency

### ISSUE THREAD

**Issue by remyabel** [rtfd/readthedocs.org#4538]
## Details

The [installation guide](https://docs.readthedocs.io/en/latest/install.html) suggests that you need pip >= 1.5, but this is not true. As of the latest commit, the required version is 10.0.1. Even when running `pip install -r requirements.txt` in a virtualenv, it will try to uninstall the system-wide pip and upgrade. I see that the pip requirements using `pur` such as in 3c02f8feb0ecc934ae37a29e459f76c04274d923. My question is: is there an explicit reason to require a newer version of pip?

## Expected result

I expect there to not be a dependency on a specific version of pip. Yes, I know you can do `pip install --upgrade pip` but this will screw up systems that package pip and rely on it for system functionality (such as Fedora and its package manager dnf). There is also another issue where pip installed pips can result in orphaned packages, see [here](https://www.linuxguideandhints.com/fedora/pip.html).

## Actual result

```
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
```

**Comment by stsewd** [comment]
> Even when running pip install -r requirements.txt in a virtualenv, it will try to uninstall the system-wide pip and upgrade.

That's curious, I don't think I have experienced that before. I think we use `pip` as a dependency to build projects locally (we use docker images in production).

The main reason we pin pip is because we use some options that are only available in some pip versions.

**Comment by remyabel** [comment]
Something must be screwy on my end. I redid the virtualenv and it's using the correct pip now.

**Comment by RichardLitt** [comment]
@remyabel Thanks for following up and letting us know.
