### ISSUE TITLE
RTFD doesn't delete all files when a project is removed

### ISSUE THREAD

**Issue by tiran** [rtfd/readthedocs.org#454]
A couple of months ago I removed my project $SPAM from RTFD. The URL

   https://$SPAM.readthedocs.org/

shows an error page just like I expect. But

   https://$SPAM.readthedocs.org/en/latest/

still has all pages and images. It seems like RTFD doesn't remove all files of a deleted project. 

Christian

PS: I'd rather not post the true value of $SPAM because I don't want to draw attention to outdated docs.

**Comment by tobias47n9e** [comment]
Has any progress been made for redirects or purging old pages? I also had to restructure my documentation, but Google now seems to rank the non-existing pages higher than the existing pages.

**Comment by ericholscher** [comment]
CLosing as dupe of #1408
