### ISSUE TITLE
Integration of Apache Solr to power search

### ISSUE THREAD

**Issue by Pravandan** [rtfd/readthedocs.org#4540]
## Details

As of now no search engine is seemed to be used and also when a user searches it loads an entire new page, but with integration of Apache Solr we can have an AJAX request to display search results, on the same web page on which the user is currently present.

## Expected Result

Using Apache Solr to display the search results on the same page.

**Comment by stsewd** [comment]
Actually, we use Elastic Search to power the search in projects, I think there are some plans to implement this feature soon. /cc @safwanrahman

**Comment by agjohnson** [comment]
Yeah, we use ES, so I don't think we'd switch backends at this point.

**Comment by safwanrahman** [comment]
I dont think its needed to change the Search Engine of Read the Docs to Solr.
As we are already using Elasticsearch, we are thinking in #504 to implement Search As You Type functionality!
