### ISSUE TITLE
Drop python 2 support

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4543]
We are already running python3 in production and python2 support is ending. We can drop the python2 compatibility layer (from isort for example), and also don't run python2 on Travis, instead start testing with python 3.7

**Comment by ericholscher** [comment]
I'm +1 on this. The corporate side is still Python 2, so that is the primary blocker currently, but I'm +1 on it after that.

**Comment by stsewd** [comment]
Just linking to some tools that can help with the cleanup

- https://github.com/asottile/pyupgrade

**Comment by davidfischer** [comment]
I'm a definite +1 on dropping support for Python2. Supporting both comes at a cost. I have a few notes:

- Dropping support should involve a major rev (eg. `v3.0.0`).
- We might want to drop dual Python support at a specific date (eg. January 1, 2019). I don't think this is super critical but for 3rd parties who take our code that might be nice.
- I assume we'll discontinue use of `six` and `future` (we use both) and we'll slowly clean up code that uses them.

**Comment by agjohnson** [comment]
Agreed on lumping this into v3.0, moving discussion here to our on-going discussion on deprecation #4594

**Comment by agjohnson** [comment]
Nevermind, breaking out a discrete ticket! We'll address this at v3 at the end of the year.
