### ISSUE TITLE
Redirect botocore and boto3 doc pages

### ISSUE THREAD

**Issue by JordonPhillips** [rtfd/readthedocs.org#4546]
## Details

We would like for the boto3 and botocore docs to be redirected to the following sites:

* botocore: https://botocore.amazonaws.com/v1/documentation/api/latest/index.html
* boto3: https://boto3.amazonaws.com/v1/documentation/api/latest/index.html

Preferably in such a way that links still go to the right place. The url path is a bit different, but everything after latest follows the same paths as latest on rtd right now. If there's a way for us to stop the builds so we don't waste your build resources, we'd also really appreciate that.

* Read the Docs project URL: https://boto3.readthedocs.io and https://botocore.readthedocs.io
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Context

boto3's docs are enormous, well over 100mb when built out. This is because we support all 144 (and counting) aws services. This means that our doc builds take an exceptionally long time. For a while it has been too long to update all of the artifacts that rtd will generate within the build timeout (e.g. the boto3 PDF available is version 1.1.4 which was released in 2015). Some time last year it got to the point where sometimes the html build will time out, and now we have to be lucky for it to finish. This is all compounded by our nearly daily releases.

With that in mind we decided to self-host. @dstufft talked to Eric about this, who recommended we open this GitHub issue to sort out redirects.

**Comment by stsewd** [comment]
>  If there's a way for us to stop the builds so we don't waste your build resources

For that you only need to remove the webhook from the project admin page (`Admin` -> `Integrations` -> select integration -> click on delete).


For the redirects, I'm not sure, but maybe #4501 could help

**Comment by JordonPhillips** [comment]
Thanks! I went ahead and removed the webhooks. The redirect looks like it's probably working. Error pages are getting redirected, though the content pages are not. Hopefully that's due to CDN caching.

**Comment by JordonPhillips** [comment]
We could try running a build where we have no contents, but we'd still end up with a root index that wouldn't redirect. If we just deleted the project then we wouldn't have redirects at all, and I'm not terribly confident that we'd be able to recreate the project.

**Comment by JordonPhillips** [comment]
Thanks! I'll give that a try. Since it'll just be the index remaining I can put a meta refresh in to redirect that particular page. Not ideal, but shouldn't be too bad since 99% of pages won't have to go through that.

**Comment by humitos** [comment]
Hi @JordonPhillips! I'm working on a solution for this. I'll add the redirect at NGINX level. After that we can test if it's working as you expect.

**Comment by JordonPhillips** [comment]
That would be awesome! We were about to merge a PR in a branch with empty docs an an html redirect, but an nginx level redirect would be much better. How long do you expect it would take?

**Comment by humitos** [comment]
The PR is already done and reviewed. I need to make a change and it will be ready to be deployed. I'd say a couple of days as much.

**Comment by JordonPhillips** [comment]
Sorry to bug you, but is there any status update?

**Comment by stsewd** [comment]
A deploy is planned for this Wednesday I think

**Comment by humitos** [comment]
We just deployed this and should be working now.

I'm closing this issue but feel free to reopen if you find that it's not correct. Thanks for your patience.

**Comment by JordonPhillips** [comment]
Thanks so much! Looks perfect!
