### ISSUE TITLE
Templating {{ super() }} doesn't return body but articleBody

### ISSUE THREAD

**Issue by vin-ni** [rtfd/readthedocs.org#4560]
## Details

I'm using the readthedocs template and need a class on the body or a bodywrapper, so I can apply custom styles to a certain page. I'm using the layout.html to add to the template, but the wrapper is around `articleBody`. Any other way I could add a special refference class to the body?

The documentation says, `document` returns the body.

My Code in layout.html is:

```
{%- block document %}
  {% if pagename == 'index' %}
  <div id="indexPage">
    {{ super() }}
    </div>
  {% else %}
    {{ super() }}
  {% endif %}
{% endblock %}
```

## Expected Result

The `body` has a wrapper div with the id "indexPage"

## Actual Result

The `articleBody` has a wrapper div with the id "indexPage"

**Comment by vin-ni** [comment]
Ok, I found a solution. I just went into the original layout.html and added
`<body class="wy-body-for-nav" id="{{pagename}}">`

**Comment by humitos** [comment]
@vin-ni thanks for reporting this and sharing the solution.

I'm closing the issue here, but feel free to reopen if you need further help with this.
