### ISSUE TITLE
Retrieving variables via rst works offline not online

### ISSUE THREAD

**Issue by vin-ni** [rtfd/readthedocs.org#4563]
## Details

I'm setting variables via the rst and use them in *layout.html*. It works fine locally, but throws an error with readthedocs online.

The rst:

```
:bodyCssID: mainIndex
```
and I retrieve it in the layout.html like that:
``` html
{%- set bodyCssID = '' %}
{%- set bodyCssID_key = 'bodyCssID' %}
{%- if meta is defined %}
    {%- if bodyCssID_key in meta.viewkeys() %}
        {%- set bodyCssID = meta.get(bodyCssID_key) %}
    {%- endif %}
{%- endif %}

<body class="wy-body-for-nav" id="{{bodyCssID}}">
```

## Expected Result

The project builds and uses the variable as an id. As when I build it with `make clean html`

## Actual Result

The build fails with the following error:
`An error happened in rendering the page Frost/Uniform Control Mechanism and LSH Protocol Jes.
Reason: UndefinedError("'dict object' has no attribute 'viewkeys'",)`

**Comment by stsewd** [comment]
Please provide the build url of your rtd project. I'm not familiar with using variables in sphinx, but I guess this is because you are using another sphinx version locally.

**Comment by vin-ni** [comment]
I currently took it out, as I'm adding other stuff.
https://vinnireaddocstest.readthedocs.io/en/latest/

How can I compare the versions?

**Comment by stsewd** [comment]
On rtd, in the sphinx-build step, you can see `Running Sphinx v1.7.7`. Locally you can see something similar on the output or just run `sphinx-build --version`

**Comment by vin-ni** [comment]
I'm using `1.7.5`. Can I downgrade the online version?

**Comment by stsewd** [comment]
Yeah, you can use a `requirements.txt` file, and setup rtd to use it (from the web interface or using a configuration file) https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

**Comment by vin-ni** [comment]
Can I set it directly in the web interface or do I need to write a requirements.txt?

**Comment by stsewd** [comment]
You need to write the requirements file, also is a good idea to pin the sphinx version in a requirements file, as we constantly update the default sphinx version.

**Comment by vin-ni** [comment]
Like that: `sphinx>=1.7.5` ?
How can I check the online version of Sphinx? 
(Sorry for so many questions. Using it for the first time)

**Comment by vin-ni** [comment]
Unfortunately still fails with the same error.
```
assembling single document... Frost/index Frost/Uniform Control Mechanism and LSH Protocol PokW/index PokW/delegation PokW/smallexample 
writing... 
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 304, in main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 331, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 337, in build_update
    self.build(['__all__'], to_build)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 403, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 1255, in write
    self.write_doc(self.config.master_doc, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 608, in write_doc
    self.handle_page(docname, ctx, event_arg=doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/vinnireaddocstest/envs/latest/local/lib/python2.7/site-packages/sphinx/builders/html.py", line 1022, in handle_page
    (pagename, exc))
ThemeError: An error happened in rendering the page index.
Reason: UndefinedError("'None' has no attribute 'viewkeys'",)

Theme error:
An error happened in rendering the page index.
Reason: UndefinedError("'None' has no attribute 'viewkeys'",)
```

**Comment by vin-ni** [comment]
I have a feeling, that this is the issue in the layout.html code.
`meta.viewkeys()`

**Comment by vin-ni** [comment]
Maybe you have another idea what I'm trying to achieve:
I just want to pass a custom id to the body of each page via the rst file so I can use it in the custom css.

**Comment by stsewd** [comment]
Not sure what kind of data type is meta, but if it's a python like dict, you can try `{%- if bodyCssID_key in meta %}`

**Comment by vin-ni** [comment]
I got it from [stackoverflow](https://stackoverflow.com/a/26691408/1779355).

Apparently you don't need the meta?

**Comment by stsewd** [comment]
Looks like a little old, but you say that does work locally

**Comment by vin-ni** [comment]
Yes

**Comment by stsewd** [comment]
what python version are you running locally? on rtd you are running 2.7. You can change that in your project's admin panel.

**Comment by vin-ni** [comment]
I tried that I think.
Local Version `2.7.15`

**Comment by stsewd** [comment]
Any news from this? I'm not able to see the project anymore :/ I was going to try this locally

**Comment by stsewd** [comment]
Closing this as the user [hasn't responded or given more information](https://docs.readthedocs.io/en/latest/contribute.html#initial-triage), feel free to reopen with more information if you are still having this problem :). Also, your latest builds are passing without any errors now https://readthedocs.org/projects/vinnireaddocstest/builds/
