### ISSUE TITLE
Builds failing with message to report it

### ISSUE THREAD

**Issue by markcmiller86** [rtfd/readthedocs.org#4565]
## Details

Builds are failing with this message...

Error

There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7681147).

* Read the Docs project URL: https://readthedocs.org/projects/visit-sphinx-python-manual/
* Build URL (if applicable): https://readthedocs.org/projects/visit-sphinx-python-manual/builds/7681147/

## Expected Result

A vanilla local build runs fine so expect same on RTD

**Comment by stsewd** [comment]
Although the correct error should be shown, I got this traceback

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 492, in run_build
    outcomes = self.build_docs()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 684, in build_docs
    outcomes['html'] = self.build_docs_html()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/projects/tasks.py", line 700, in build_docs
    html_builder.append_conf()
  File "/home/stsewd/rtd/readthedocs.org/readthedocs/doc_builder/backends/sphinx.py", line 170,
    trace
  File "/home/stsewd/.pyenv/versions/rtd/lib/python3.6/site-packages/six.py", line 690, in rerai
    value = tp()
TypeError: 'ProjectConfigurationError' object is not callable
```

Investigating...

**Comment by markcmiller86** [comment]
@stsewd Thanks so much for looking into this! That said, I use pretty much the identical conf.py file in another RTD hosted project without issue, https://readthedocs.org/projects/visit-sphinx-user-manual.

As an aside, can you recommend best way to run sphinx locally to emulate/duplicate behavior of RTD?

**Comment by stsewd** [comment]
The main problem with this project is that it has 2 conf.py files, then rtd first tries to load the one from the admin panel, which doesn't exist, then it tries to find one for itself, it found 2 (conf.py and tests/conf.py). So it raises an exception instead of choosing one.

About your other question, you can run the same commands that are shown in the build page.

**Comment by markcmiller86** [comment]
Ok, super. Thx. Fixed now and its generating!

**Comment by RichardLitt** [comment]
Glad you got it fixed!
