### ISSUE TITLE
Segmentation fault (core dumped) when installing sphinx packages in conda

### ISSUE THREAD

**Issue by frankier** [rtfd/readthedocs.org#4574]
## Details

* Read the Docs project URL: https://desdeo.readthedocs.io/projects/desdeo-vis/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/desdeo-vis/builds/7693988/ and https://readthedocs.org/projects/desdeo-vis/builds/7694049/
* Read the Docs username (if applicable): frankier

Firstly, thanks for the project. It's been a lot of help with streamlining the process of getting some basic documentation available, helping to make the whole thing more enjoyable.

## Expected Result

The build gets to the next step after running:

    conda install --yes --name latest mock pillow sphinx sphinx_rtd_theme

## Actual Result

Segmentation fault (core dumped)

## Extra comments

This bug is a bit mysterious to me. My attempted setup is perhaps a bit unusual since I'm trying to install a newer version of nodejs/npm in conda than is otherwise available (I want to embed custom widgets in notebooks ultimately embedded in the docs), but the build is failing before it gets to anything odd.

My first attempt at a conda build went through successfully: https://readthedocs.org/projects/desdeo-vis/builds/7693933/

A subsequent build has successfully got through this stage:

**Comment by frankier** [comment]
Just to note, still happening intermittently. Easy to workaround since I can always just trigger another build.

https://readthedocs.org/projects/desdeo-vis/builds/7699176/

**Comment by eendebakpt** [comment]
@frankier I have the same problem (see https://readthedocs.org/projects/oapackage/builds/7817015/)

**Comment by frankier** [comment]
Can this be converted from "Support" to "Bug" since it's happening for multiple people.

**Comment by RichardLitt** [comment]
@frankier It might be a bug; I'm not sure! One of the other maintainers will get to this as soon as they can. They'll relabel as needed. It's not clear to me how to resolve this.

**Comment by stsewd** [comment]
This is something happening during build time, I think this is triggered by excessive memory consumption (happens a lot with conda). Why is this happening randomly? Sometimes the builders are busy and other times they aren't.

I think we have an exclusive queue for projects that require more resources, but the team need to analyze the situation. Also, you can take a look at https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by msarahan** [comment]
Hi, I'm a conda maintainer. Please see response at https://github.com/rtfd/readthedocs.org/issues/5014#issuecomment-448583257

We will look into this.

**Comment by stsewd** [comment]
Please open a new issue if your project needs more resources, so the team can evaluate the situation and increment them.
