### ISSUE TITLE
Missing python packaging user guide

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#4576]
## Details

This is based on [this tweet](https://twitter.com/theavalkyrie/status/1034254482832470016).

* Read the Docs project URL: https://readthedocs.org/projects/python-packaging-user-guide/

## Expected Result

I expect the packaging guide to be there

## Actual Result

It is not there

**Comment by theacodes** [comment]
More Context:
About 10 minutes ago, I deleted the account associated with my dead name, `jonparrott`. This seems to have broken every project associated with that name even though all of these projects have additional owners.

Prior to deletion I added my new account, `theacodes`, to every project. After deletion, this account does not have access.

Projects affected:

- https://readthedocs.org/projects/python-packaging-user-guide/
- https://readthedocs.org/projects/nox/
- https://readthedocs.org/projects/urllib3/
- https://readthedocs.org/projects/google-auth/
- https://readthedocs.org/projects/google-cloud-python/

I feel like I'm forgetting one...

(note: since this comment contains my deadname, I will edit it an remove it as soon as y'all confirm you have the info you need).

**Comment by theacodes** [comment]
To specify: I deleted the RTD account. I disassociated the old RTD account from my GitHub account before deletion.

**Comment by ncoghlan** [comment]
The symptoms from my side are the same as those that Thea is seeing on her new account: projects where we're co-maintainers (i.e. including Thea's old account) are not appearing in my project list at https://readthedocs.org/dashboard/

**Comment by stsewd** [comment]
Ok, I was able to replicate this in my local instance. Looks like we are deleting all projects that belong to a user when it deletes its account (even if this wasn't the original owner of the project).

**Comment by theacodes** [comment]
Yeah I'm thinking that if there are *any* other owners the project
shouldn't be deleted. In this case it was my intention to rotate to my new
account, so if projects created by my old account get deleted that would
have defeated the purpose.

**Comment by agjohnson** [comment]
Absolutely. We had a similar theoretical bug that we patched a while back, this is a different but related. Let me see if I can easily restore things from a backup

**Comment by theacodes** [comment]
Thank you! (& Sorry again for breaking stuff)

**Comment by agjohnson** [comment]
No worries!

Everything is in flux since our migration to Azure, so frankly, it might be faster to just recreate the projects unfortunately.

**Comment by theacodes** [comment]
packaging.python.org and google-auth-library-python had a significant
number of redirects in place that would be practically impossible to
recreate.

**Comment by agjohnson** [comment]
Files for the projects above have mostly been restored, I'm working on the database restore pieces now. Files aren't accessible by domain name until I get data out from the snapshot and back into our production database.

Good news: our new database restore procedure has officially been tested though :heavy_check_mark:

**Comment by theacodes** [comment]
Yes, if you can restore those and assign to my new account that would be
awesome.

**Comment by agjohnson** [comment]
Sounds good. I'll need verification for the changes on the orphaned projects as per our policy on intervening on project changes -- I'll send some verification emails tomorrow.

Things are mostly restored now. I didn't reload builds or build commands, if there is anything important there, let us know and we can manage restoring it. I haven't fully tested building either, but things appear okay.

I'll wrap up some of the smaller pieces tomorrow morning.

**Comment by theacodes** [comment]
Cool, so after the verification process my access will be restored to all of those projects?

**Comment by theacodes** [comment]
Okay, I'm not sure if this is related or not, but it appears one of the restore projects is not updating properly.

See https://nox.thea.codes/en/stable/ and https://nox.thea.codes/en/latest. These docs are quite old. The most recent two builds for [latest](https://readthedocs.org/projects/nox/builds/7703178/) and [stable](https://readthedocs.org/projects/nox/builds/7703179/) were successful and pulled in the correct commits from GitHub, but the HTML itself doesn't seem to be updating.

**Comment by agjohnson** [comment]
Oops, I didn't test that I restored things with the correct permissions, so there is probably an issue there. I'll check on that later and follow up on email verification

**Comment by ncoghlan** [comment]
The Python Packaging User Guide has reverted quite a bit as well - most notably, the new Overview page that was merged in https://github.com/pypa/python-packaging-user-guide/commit/4b5e8600775f8be01cbd282d95a1255dded198db is missing.

The currently displayed PyPUG build *does* include the changes from mid-July to update Continuum Analytics references to Anaconda, Inc (to account for the company name change), so it's likely that that's just the most recently archived version.

However, I forced a new build, and even though that reported itself as successful, the https://packaging.python.org doesn't appear to have updated to the latest version.

(@theacodes I also added you back as a project maintainer on the user guide)

**Comment by theacodes** [comment]
Yeah I rebuilt nox again earlier today as well and it's still not updating.

**Comment by agjohnson** [comment]
Sorry, we had a busy day yesterday, so i'm just now getting to my yesterday todo list.

@theacodes it looks like nox is updating correctly. I see the version of nox that is marked as stable showing up at https://nox.thea.codes/en/stable/. I think latest looks correct too?

@ncoghlan I think the pypa guide is also updating correctly. Can you confirm your versions look as you expect, or if they don't, that rebuilding does update the hosted versions as you'd expect?

**Comment by ncoghlan** [comment]
The overview is back in PyPUG, so it does look like that's building again: https://packaging.python.org/overview/

Potentially still a CDN cache invalidation issue, though?
