### ISSUE TITLE
Build error message

### ISSUE THREAD

**Issue by willingc** [rtfd/readthedocs.org#4578]
Hi wonderful RTD folks :smile:

## Details

Error message: There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7701130).

## Expected Result

Docs to build.

## Actual Result

There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7701130).

**Comment by willingc** [comment]
For now, an FYI. I'm doing some work on the repo later today. Will let you know if it happens again. thanks.

**Comment by stsewd** [comment]
Could you please provide the build url? The id isn't enough if we don't have the project name

**Comment by agjohnson** [comment]
We have enough info here. Sentry report seems to imply it's an issue communicating with the Docker unix socket:

https://sentry.io/read-the-docs/readthedocs-org/issues/612009754/events/28746990813/

**Comment by agjohnson** [comment]
As far as I can tell, when calling `stop` on a container, Docker is not returning within the timeout. We can perhaps remedy this by catching the timeout exception and hard killing the container?

**Comment by humitos** [comment]
Mmm... The docker timeout is one thing, but the build shouldn't fail because of that. This exception is handled in our code:

https://github.com/rtfd/readthedocs.org/blob/6fd22b01d9f4772c96c86a145da2cb3b7008e61d/readthedocs/doc_builder/environments.py#L770-L776

There has to be something else.

**Comment by willingc** [comment]
I think that this was a hiccup. I can build again. Closing.
