### ISSUE TITLE
Build failed (Sphinx in sub-directory) 

### ISSUE THREAD

**Issue by bwulff** [rtfd/readthedocs.org#4580]
## Build failed after switching to rst (Build #7706619)

* Read the Docs project URL: https://readthedocs.org/projects/lecturesight/
* Build URL (if applicable): https://readthedocs.org/projects/lecturesight/builds/7706619/
* Read the Docs username (if applicable): bwulff

## Expected Result

Docs are built. 

## Actual Result

Build failed with no further information about what went wrong. Last line in raw log is pip saying it installed everything successfully. 

Reporting this here mainly because the error message suggested reporting. Will look into it myself. 

## Further Details

- the docs rst files are in doc/src
- the theme is in doc/theme
- building locally works with `cd doc/src ; sphinx-build -b html . /<destination-dir>`

**Comment by bwulff** [comment]
Important info: A clone of the exact same content (except renamed theme dir) is at: https://github.com/bwulff/materialdoctest

The rtd project is: https://readthedocs.org/projects/lecturesight-doc-test/

That build works. I copied the stuff into the other repo (main project), suspect I have a bug in the conf.py or the project conf on rtd.

**Comment by stsewd** [comment]
I think your project is still trying to be built with mkdocs, maybe you forgot to change the doc type in the admin panel?

**Comment by bwulff** [comment]
Apparently I failed to hit "Save" when I switched the doc type from Markdown to Sphinx on rtd. Now I've got a Sphinx error message that is clearly due to an error in conf.py

**Comment by bwulff** [comment]
Swift reaction from you RTD, great! 

..sorry for spamming
