### ISSUE TITLE
Unexpected build failed. 

### ISSUE THREAD

**Issue by vimalloc** [rtfd/readthedocs.org#4593]
## Details

I'm getting a build failed on my project, but according to the logs I don't see any build failures, and only one warning:

```
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
...
build succeeded, 1 warnings.

The HTML pages are in _build/html.
```

Locally I am able to build the html without issue. 

* Read the Docs project URL: https://readthedocs.org/projects/flask-jwt-extended
* Build URL (if applicable): https://readthedocs.org/projects/flask-jwt-extended/builds/7714303/
* Read the Docs username (if applicable): Vimalloc

## Expected Result

The build should either be successful, or there should be an indication in the logs of why it was unsuccessful. 

## Actual Result

The build failed. My guess is it is because of that warning mentioned above, but it isn't clear to me

**Comment by stsewd** [comment]
Looks like it's failing in the pdf generation step

**Comment by vimalloc** [comment]
I'm glad I'm not crazy at least :) If there's any information I can provide or anything I can do to help test this I would be more then happy to do so. FWIW the commit that triggered this was purely a documentation commit. If needed I could try reverting it and seeing if it still is having an issue, to help narrow down the target area.

**Comment by stsewd** [comment]
Can you try building your project again? Maybe it was a temporal issue on the servers

**Comment by vimalloc** [comment]
It was triggered via a webhook, doing a quick search I don't see a way to manually retrigger that. Do you know if there is any way to retry that without dirtying the git history, or would my best bet be to push up a dummy commit to trigger it again?

Thanks for you help with this :+1:

**Comment by stsewd** [comment]
You need to do it from your project builds page https://readthedocs.org/projects/flask-jwt-extended/builds/

**Comment by vimalloc** [comment]
I’m embarrassed to say that I didn’t realize the button on that page was used for retriggering, I though it was a filter. Retriggered and everything is peachy. Thanks for the help! 👍

**Comment by RichardLitt** [comment]
@vimalloc No worries. Thanks for circling back and letting us know. 

Is there anything we could do to make that button clearer?

**Comment by vimalloc** [comment]
I'm not a web designer so take this with a *huge* grain of salt, but I think for me at least it might be more clear if it was the select option first then the build button second. It just feels a bit more intuitive to me that way. Something like:

```html
<html>
    <header><title>Title</title></header>
    <body>
        <select label="Version">
            <option value="latest">Latest</option>
            <option value="stable">Stable</option>
        </select>
        <button label="Build">
            Build
        </button>
    </body>
</html>
```

Maybe updating the size  on the components to be the same to visually indicate that they were grouped together as well? Not sure if that would actually look good or not 🤷‍♂️.
