### ISSUE TITLE
Deprecation list Jan 2019 & RTD v3.0

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4594]
We've talked about deprecating a number of things in Jan 2019, so let's make official plans and get things announced for a v3.0. Here are things on the chopping block:

* ~API v1~ We've already announced this one. :wave:
* ~Old authenticationless github/bitbucket/generic build trigger API-ish endpoints. GitHub is removing "Services" Jan 31 2019, which uses the `/github` deprecated endpoint as well.~ See #4568 for this
* ~Python 2.x support for codebase~ See #4543
* ~Python 3 as default build version~ PR is open! #3581 
* Anything to do with mkdocs? I think deprecating < v1.0 is pretty aggressive, but there might be a less aggressive method of this when using
* ~Django 1.11 support maybe?~ Done! :wave:

**Comment by stsewd** [comment]
> any reason to keep python2 support now?

.com is still running py2 I think.

**Comment by davidfischer** [comment]
I would like to get rid of all dashboard access over HTTP including the API. Basically [all this stuff](https://github.com/rtfd/readthedocs-ops/blob/8dbdaff/salt/base/nginx/sites/readthedocs-site.conf#L105-L115) should forward to HTTPS.

**Comment by stsewd** [comment]
Also, our current version of django, not sure if other people are using a heavily customized fork of rtd that could cause problems.

**Comment by davidfischer** [comment]
> Anything to do with mkdocs? I think deprecating < v1.0 is pretty aggressive, but there might be a less aggressive method

I don't know how we do this in practice. Nothing stops people from just putting `mkdocs<1.0` in their requirements file. I would be +1 on locking down versions of Sphinx/MkDocs based on something in the YAML file and it can't be overridden with a requirements file. That way we can deprecate versions of Sphinx/MkDocs.

**Comment by davidfischer** [comment]
> Also, our current version of django, not sure if other people are using a heavily customized fork of rtd that could cause problems.

I would not let that slow us down. If we could get to Django 1.11 before January, that would be amazing.

**Comment by agjohnson** [comment]
Yeah, I'm about 100% not concerned with forks of RTD for our development roadmap. I'm a big :+1: on migrating to modern Django.

**Comment by agjohnson** [comment]
> .com is still running py2 I think.

It is, but this isn't blocking us on deprecating.

**Comment by agjohnson** [comment]
> I would like to get rid of all dashboard access over HTTP including the API. Basically all this stuff should forward to HTTPS. This has been announced in the docs and on the blog.

I don't think there is anything to deprecate here, we'll just start redirecting links. 3 of those 4 endpoints are being deprecated anyways, so we just need to worry about the `/api` endpoint.

**Comment by stsewd** [comment]
Can we include https://github.com/rtfd/readthedocs.org/issues/2663 here?

**Comment by agjohnson** [comment]
I guess it probably does make sense to include this in our list of changes we should notify on. We can do this before v3.0 perhaps?

**Comment by humitos** [comment]
I think we should default to Python 3 by adding `default=3` as database level also: #3070. Actually, I've already did this before but I closed it for some reason:https://github.com/rtfd/readthedocs.org/pull/4613

**Comment by stsewd** [comment]
> Actually, I've already did this before but I closed it for some reason:#4613

@humitos it was because there is another PR already p: (https://github.com/rtfd/readthedocs.org/pull/3581)

**Comment by ericholscher** [comment]
+1 on removing python2 support. We should likely do that in an RTD v3.

I think the main thing here is to see who is using the old endpoints, and make a plan to email them about it. It should be a pretty simple thing to change, I hope, but we should definitely alert folks who are hitting `/build` for example in custom scripts of a migration path.

**Comment by agjohnson** [comment]
Endpoint deprecations are found at #4568, we'll want to tackle that very soon to start the notification process. We need a month or two ideally.

It doesn't seem there is much to do with Mkdocs. Break out a separate ticket if there is and apply to v3 milestone.

We'll discuss removing privacy levels with v3 as well, that may be a later deprecation.

I'll close this as discrete tickets are more helpful now that we've discussed the overall plan i think.
