### ISSUE TITLE
Support Ads Shown For Gold User Logged In with Adblock

### ISSUE THREAD

**Issue by Breakthrough** [rtfd/readthedocs.org#4595]
## Details

* Read the Docs project URL: http://pyscenedetect.readthedocs.io
* Build URL (if applicable): http://github.com/Breakthrough/PySceneDetect
* Read the Docs username (if applicable): Breakthrough

## Expected Result

**I am a gold member** using RTD to host docs for my users, and I happen to use an ad blocker.  I should see no ads.

Furthermore, neither should my users, as I am paying to hide ads on my site for them.

## Actual Result

See screenshot below.  I am logged in.  Is this expected behaviour?

I'm told to go ad-free by subscribing, but I already have...

![screenshot](https://user-images.githubusercontent.com/125316/44886903-4015a680-ac97-11e8-9038-c7456fa859bb.png)

It would also be nice for people browsing my documentation using adblockers to not see this message as well, as I thought the whole point of me paying for gold was to hide these messages.

(Aside, I also accidentally double-billed two $5 subscriptions but only see the one - can I turn it into a $10 one to cover another project, without having to pay again?)

Thank you!

**Comment by davidfischer** [comment]
I refunded 2 more $5 charges and left only the $10 charge and the $10/mo subscription.

I also figured out the problem and have a PR in for it.

**Comment by Breakthrough** [comment]
Awesome, thanks for all your help looking into and solving the problem @davidfischer!!
