### ISSUE TITLE
Buttons in Everything Bagel example don't render text unless clicked on macOS High Sierra

### ISSUE THREAD

**Issue by ilovetogetspamed** [rtfd/readthedocs.org#4601]
## Details

Buttons in Everyting Bagel example don't render text unless clicked on OSX 10.13.6 

iMac (Retina 5K, 27-inch, Late 2015), AMD Radeon R9 M380 2048 MB
Python 3.7.0

Source and image of output: https://gist.github.com/ilovetogetspamed/73a55800fa0dd9b440f59eb04609f503

* Read the Docs project URL:  https://pysimplegui.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*Buttons that have visible labels.*

## Actual Result

*Outlines of buttons*

**Comment by stsewd** [comment]
I don't follow this... Is this an error with the pysimplegui? If so, you should create an issue in their repo, rtd only host their docs.

If this is something else, can you please include a screenshot or describe where/how we can see that behavior?

**Comment by ilovetogetspamed** [comment]
So sorry!  It's been a 'Monday' on Tuesday.  I apologize.  It is a problem with their code.  I'll post it there.  I think I need another cup of coffee!

**Comment by RichardLitt** [comment]
@ilovetogetspamed No worries! Thanks for following up and for figuring it out. :)
