### ISSUE TITLE
Image not readable

### ISSUE THREAD

**Issue by wilsonyou** [rtfd/readthedocs.org#4610]
## WARNING: image file not readable: docs/image/download_bumo_back2.png

* https://readthedocs.org/projects/bumo1/builds/7743348/

I tried to build a doc on docthedocs, although the build was completed, the images were not readable and not displayed. 

Could you help me solve this issue?

**Comment by wilsonyou** [comment]
solved. directory error.

**Comment by RichardLitt** [comment]
Glad you got it, @wilsonyou. Don't hesitate to keep reaching out if you're lost. :)
