### ISSUE TITLE
Correct rendering of Chinese characters becomes incorrect during page load

### ISSUE THREAD

**Issue by strophy** [rtfd/readthedocs.org#4612]
When loading a full (no cache) Read The Docs hosted page with Chinese text, the font rendering changes from some default font (probably Arial) to some web font (probably Lato). While the web font can render Chinese characters, it does so incorrectly. Chinese typography should conform to a grid. In particular, the Chinese Em dash should [span the width of two characters without a break](https://en.wikipedia.org/wiki/Chinese_punctuation). Chinese fonts will render this correctly, but Lato renders this as two English-width hyphens, breaking the grid layout. This means there will likely be other rendering errors related to Chinese with this font.

I appreciate this is a fairly minor issue, and hard to describe in text. I've recorded a short video of the issue, and you can see for yourself by loading the following link in incognito mode. Notice how the third line of text shifts to the left once the web font loads?

* Video: https://youtu.be/gvKxMvE-xQc
* Read the Docs project URL: https://docs.dash.org/zh_CN/latest/introduction/safety.html

It would be great to use a font that renders this correctly, either the default font (Arial) or another web font that supports this properly. Some Googling suggests Noto Sans may be an appropriate alternative that also looks very similar to Lato. I've encountered a similar issue on a different site for Japanese, which may default to a Chinese font, rendering characters such as 直 incorrectly. This is because the character is at the same code point (because it is the same character), but the rendering looks wrong to Japanese speakers. It would be great to consider issues like this as more non-English content appears on RTD.

**Comment by humitos** [comment]
I have **no idea** about Chinese. That said, here we go.

I was able to notice the issue you reported here. Also, I noticed that the third paragraph also has a dash but it looks correct to me: the alignment doesn't break.

I pasted them into a Python console and I could notice that the "correct dash" has a little space on its right which seems to keep the correct alignment:

```python
>>> wrong_dash = '—'
>>> right_dash = '一'
```

From my understanding it seems that in the wrong version a "simple-English" dash has used and in the right version (correctly rendered) the proper Chinese character is used.

Went deeper and I found that I'm wrong, I think.

```python
In [1]: import unicodedata

In [2]: >>> wrong_dash = '—'
   ...: >>> right_dash = '一'
   ...: 
   ...: 

In [3]: wrong_dash
Out[3]: '—'

In [4]: right_dash
Out[4]: '一'

In [6]: unicodedata.name(wrong_dash)
Out[6]: 'EM DASH'

In [7]: unicodedata.name(right_dash)
Out[7]: 'CJK UNIFIED IDEOGRAPH-4E00'

In [8]: unicodedata.name('-')
Out[8]: 'HYPHEN-MINUS'

In [9]: 
```

So, what I thought was the wrong dash, it has the name that you mentioned which I think it's the correct. The other one (`right_dash`), I don't know what it is but looks better, though :confused: 

I read this article http://gniw.ca/unicode-two-em-dash.php and I found that there is another character called *TWO-EM DASH* (https://www.fileformat.info/info/unicode/char/2e3a/index.htm) that maybe is what it's needed in the first paragraph:

```python
In [18]: unicodedata.name('\u2E3A')
Out[18]: 'TWO-EM DASH'

In [19]: print('\u2E3A')
⸺
```

(it takes a little more space than 2 English character as it's noted in this text)

Finally, I think that for the first paragraph we need to use the `TWO-EM DASH`. What do you think?

**Comment by strophy** [comment]
Hi, that's a nice bit of research there! 

The character from the third paragraph that you have marked "right dash" is actually the Chinese number one. It might make a bit more sense when you see the progression `1 2 3 --> 一 二 三`, so the word `一些` means `some`. It is not possible or meaningful to use the character `一` as replacement for `-`.

I was unaware of the existence of a `TWO-EM DASH` but I would suggest RTD should follow standard practice and use Chinese fonts to render Chinese text. It is common practice throughout China to use `--` to create a dash exactly two characters wide, and any text submitted to RTD (e.g. by my translators or other users) will use this convention. There is quite a bit of detail about this on [Wikipedia](https://en.wikipedia.org/wiki/Chinese_punctuation), the characters render correctly there and you can see it is in fact two hyphens rather than a single double-wide character.

Hope this helps, even though I suspect it won't make your job easier ;)

**Comment by agjohnson** [comment]
I'm going to move this discussion to our theme, this isn't a problem with RTD code. We can't dictate the codepoints generated in documentation, so we're likely stuck dealing with a font issue instead. We're unlikely to switch out the font used by default, but we might be able to select a better CJK using CSS or conf.py.

**Comment by agjohnson** [comment]
Moved to rtfd/sphinx_rtd_theme #670
