### ISSUE TITLE
Can I reference a subproject through relative path?

### ISSUE THREAD

**Issue by vivianyangsh** [rtfd/readthedocs.org#4625]
## Details

We are using readthedocs to deploy 2 sets of environemnts: staging and production. And we used subprojects. From the parent project, can I use a relative path to reference a child project? I currently used absolute path, but because the production environment has a different domain address, the link to subprojects become broken when in the production environement

## Expected Result

If parent is project_name_b, subproject is project_name_b, I should be able to reference b with

```
/project_name_b
```

## Actual Result

There seems to be no way to use relative path, I tried
```
/project_name_b
/project_name_b/index
../project_name_b/index (because locally on our build server, parent and subprojects are in the same location at the same level)

**Comment by stsewd** [comment]
I think there is another directory that you need../project_name_b/index (because locally on our build server, parent and subprojects are in the same location at the same level), ../projects/project_b/

**Comment by stsewd** [comment]
Closing as this isn't a rtd problem.

**Comment by RichardLitt** [comment]
@vivianyangsh If you feel that this is a RTD problem, though, feel free to comment. It's possible our docs aren't clear enough.
