### ISSUE TITLE
Center Document Body

### ISSUE THREAD

**Issue by DzianisH** [rtfd/readthedocs.org#4629]
## Details

* Read the Docs project URL: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html
## Expected Result

*Page content either shows at the center of the page or it justifies to improve user experience*

## Actual Result

*Page content aligned to left side => right part of the screen is unused.
Screenshot: http://prntscr.com/kt4m3w*

**Comment by davidfischer** [comment]
Different [sphinx themes](http://www.sphinx-doc.org/en/master/theming.html) will have different behavior with respect to this.

The attached image is the Read the Docs sphinx theme and you can open an issue or create a pull request [here](https://github.com/rtfd/sphinx_rtd_theme).
