### ISSUE TITLE
Read the docs adds title to Alabaster theme

### ISSUE THREAD

**Issue by Benjamin-Lee** [rtfd/readthedocs.org#4630]
## Details

* Read the Docs project URL: squiggle.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

![expected](https://snag.gy/d5fbKQ.jpg)

There is no title in the top left.

This issue persists even though my conf.py contains the following:

```
html_theme_options = {
    # "fixed_sidebar": True,
    "logo_name": False,
    "sidebar_collapse": False,
    "show_related": True,
    "description": "DNA Sequence visualization for humans."
}
```

## Actual Result

![actual](https://snag.gy/PMH4zQ.jpg)

The title of the project is in the top left.

**Comment by agjohnson** [comment]
Read the Docs doesn't do anything special to context data or really anything special at all to Alabaster. Not sure what would be changing this -- you can try a full wipe of the project, in the case that you recently changed the config option. Otherwise, let us know if you come across any other information that would help determine if this is a bug.

**Comment by stsewd** [comment]
Does the title show when building locally?

**Comment by stsewd** [comment]
Also, looks like it's by default false

https://github.com/bitprophet/alabaster/blob/7d94bd592ab7d2876b0855d321995a557a9b1d5b/alabaster/theme.conf#L25

And it's interpreted as a string https://github.com/bitprophet/alabaster/blob/7d94bd592ab7d2876b0855d321995a557a9b1d5b/alabaster/about.html#L5

**Comment by stsewd** [comment]
I just build your docs locally (inside and outside rtd), the `logo_name` setting is working as expected. Also, I can see that you are using `logo_name` to `True` https://github.com/Lab41/squiggle/blob/e0482237ced49750b5f1b0912079b5a47177f0d4/docs/conf.py#L91.

I'm closing, feel free to reopen with more information.
