### ISSUE TITLE
Unicode in link names not possible

### ISSUE THREAD

**Issue by AdrianLxM** [rtfd/readthedocs.org#4637]
## Details

* Read the Docs project URL: https://androidaps.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/androidaps/builds/7792444/

The build fails if the link name has unicode in it.
```
...
  File "/home/docs/checkouts/readthedocs.org/user_builds/androidaps/envs/l10n_master/lib/python2.7/site-packages/recommonmark/states.py", line 129, in run_role
    rawtext=str(content),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 8: ordinal not in range(128)
```

An example is this file: https://github.com/openaps/AndroidAPSdocs/blob/68c9a48f65a26402b589191aa0462269e89e301f/docs/CROWDIN/de/Configuration/Preferences.md
... where it fails on the `ä` in 
```
Weitere Informationen zu den Einstellungen der Wear-Zifferblätter sind unter [Zifferblätter](../Configuration/Watchfaces.md) zu finden.
```

Thanks,
Adrian

**Comment by agjohnson** [comment]
Also, consider filing this against the recommonmark package, as the parsing bug is triggered from that code.

**Comment by AdrianLxM** [comment]
@stsewd with python3 it works. Thank you very much!
