### ISSUE TITLE
Celery update breaks our code

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4640]
Today I reinstalled my virtual env, reinstalling the requirements noted this when building a simple project:

```
     raise RuntimeError(E_WOULDBLOCK)
RuntimeError: Never call result.get() within a task!
See http://docs.celeryq.org/en/latest/userguide/tasks.html#task-synchronous-subtasks
```

This is because of this change https://github.com/celery/celery/pull/4432, we need to:

1) downgrade celery
2) refactor our code

I'm trying 2 now

**Comment by stsewd** [comment]
Ok, this only happens in development (`CELERY_ALWAYS_EAGER = True`). I'm not sure how to _fix_ this, we need a way to pass `disable_sync_subtasks=False` down to the `get` method, but I found that `options` isn't used there...

https://github.com/celery/celery/blob/a1fb557b6ecc494514e3480518be57b985d0927d/celery/canvas.py#L1240

So, if there isn't another way of passing the `disable_sync` option, we can:

- Require to run rtd on dev with celery on
- Downgrade celery
- Maybe send a patch to celery project?

**Comment by agjohnson** [comment]
FWIW, I never use `ALWAYS_EAGER` in development. I used `contrib/supervisord.conf` to start all the services

**Comment by stsewd** [comment]
I use supervisor sometimes, but it gets too heavy sometimes for my computer p:

So, should we update our installation guide?

**Comment by stsewd** [comment]
We already mention the redis installation there
