### ISSUE TITLE
Improve Intro and Getting Started documentation

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#4648]
I think the [introduction](https://docs.readthedocs.io/en/latest/) and [getting started guide](https://docs.readthedocs.io/en/latest/getting_started.html) could use a few improvements to make it easier for brand new users who may not already know about Sphinx/MkDocs/Markdown/RestructuredText and are just looking for a guide on how to write some docs.

I also think our introduction could stand some improvements to point users in the right direction. We have a lot of docs, but a few layout and explanation improvements will help users find the right section for them.

Here are some specific goals and improvements:

- Make it easier to start a brand new docs project
  * Have a getting started guide for Sphinx
  * Have a getting started guide for Sphinx with commonmark
  * Have a getting started guide for MkDocs
  * Explain the why between the above technologies
- Improve the intro paragraphs ("Read the Docs hosts documentation for...") on the index page to explain RTD's value proposition and why somebody should choose Read the Docs.
- Full sentence/paragraph descriptions on different sections (eg. User documentation) rather than just a big toctree.

**Comment by RichardLitt** [comment]
I think this is a great idea, and needed. I still don't fully grok how to do this, either.

Aside: Is there a reason there are two milestones, `Documentation` and `Better User Documentation`? Could we join them?

**Comment by ericholscher** [comment]
Some existing content which might be useful to steal:

* http://ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/
* https://sphinx-tutorial.readthedocs.io/

**Comment by davidfischer** [comment]
> Aside: Is there a reason there are two milestones, Documentation and Better User Documentation? Could we join them?

I don't know the answer to this. Perhaps @agjohnson does?
