### ISSUE TITLE
Request to API: enable build for specific branch

### ISSUE THREAD

**Issue by KengoTODA** [rtfd/readthedocs.org#4649]
Hello, 
thanks for providing so great web application! I'm using Read the Docs for [SpotBugs Documentation](https://spotbugs.readthedocs.io/en/stable/) and others. Here I have a request to RTD API:

## Expected Result

* API provides a feature to enable/disable build for specific branch.
* So I can use it to run build for the pushed Git branch automatically.

## Actual Result

* V2 API provides no feature like this, so we need some hacking like [puppeteer](https://github.com/KengoTODA/rtd-bot/blob/master/src/rtd.ts#L124-L128).

**Comment by stsewd** [comment]
We are discussing new api features in https://github.com/rtfd/readthedocs.org/issues/4286, I move this request there.

Also, this may be useful https://github.com/rtfd/readthedocs.org/issues/4001

**Comment by KengoTODA** [comment]
Thank you!
