### ISSUE TITLE
Request to API: Get build activity for specific Git branch

### ISSUE THREAD

**Issue by KengoTODA** [rtfd/readthedocs.org#4650]
Hello, 
thanks for providing so great web application! I'm using Read the Docs for [SpotBugs Documentation](https://spotbugs.readthedocs.io/en/stable/) and others. Here I have a request to RTD API:

## Expected Result

* API provides a feature to get build activity (running, succeeded, failed etc.) for specific Git branch.
* So I can call [GitHub Checks API](https://developer.github.com/v3/checks/) or similar API to mark pull-request succeeded/failed.
   * I want to mark pull-request failed, if RTD build is failed.

## Actual Result

* V2 API provides no feature like this, so it is hard to mark pull-request.

**Comment by stsewd** [comment]
I think we have an internal undocumented API for query the build status, anyway, moving to #4286.

Also, you may be interested in https://github.com/rtfd/readthedocs.org/issues/1340

**Comment by KengoTODA** [comment]
Yes feature of my probot is similar with #1340, thank you
