### ISSUE TITLE
Respect case

### ISSUE THREAD

**Issue by tdegeus** [rtfd/readthedocs.org#4652]
## Details

* Read the Docs project URL:  goosempl.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): tdegeus

## Expected Result

I have a Python module that contains upper-case letters. I would like to autodoc the module, however it appears that the readthedocs converts everything to lower-case.

> I currently have a work around replacing all upper-case instances for autodoc to lower-case instances. But this is not a very durable solution.

**Comment by stsewd** [comment]
Can you please link to the specific module and page? Also, does this behaviour happens locally? I don't think this is a rtd issue, but from autodoc.

**Comment by tdegeus** [comment]
@stsewd 

* This happens for http://goosempl.readthedocs.io / https://github.com/tdegeus/GooseMPL
* There are no issues what so locally, the case is respected.
* It has so far only happened on *rtd*. Some snippets from the raw build are listed below, all displaying that *rtd* partially looses the upper-cases.

```bash
Project: goosempl
...
git remote set-url origin https://github.com/tdegeus/GooseMPL.git
...
copying build/lib.linux-x86_64-2.7/goosempl/__init__.py -> /home/docs/checkouts/readthedocs.org/user_builds/goosempl/envs/latest/lib/python2.7/site-packages/goosempl
...
writing GooseMPL.egg-info/PKG-INFO
...
```

**Comment by stsewd** [comment]
I can see that your package originally is in lowercase, also that you have some try..catch around lowercase and uppercase, not sure why. Anyway, your package is in lowercase.

I suppose this is working locally because you are using Windows (case insensitive filesystem)

**Comment by tdegeus** [comment]
@stsewd 

The `try ... except` are simply a workaround to get *rtd* working. But thanks for your remark! I had not realised that GitHub did not get informed of the case when I changed and pushed it (probably because my macOS is not really case sensitive). 

Sorry for the false issue.

**Comment by stsewd** [comment]
No worries!
