### ISSUE TITLE
Add admin interface for reindexing a project search

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4654]
We have a management command for this, but a site admin command probably makes a lot more sense. Let's move the management command to a site admin feature.

Work required:

- [ ] On Project admin, a command that reindexes all active versions (project queryset and all attached active versions)
- [ ] On Version admin, a command that reindexes by version queryset instead
- [ ] Drop management command, these aren't good interfaces for site admins and are mostly hidden
- [ ] The management command seems to just do all versions active or not, we should probably test for active versions instead.
- [ ] There should also be an admin function to wipe the index for a version and for a project

I wiped project indexes manually with:

```python
query = {'query': {'bool': {'must': [{'term': {'project': 'docs'}}]}}}
PageIndex.delete_document(query)
SectionIndex.delete_document(query)
```

**Comment by A-red-BREASTED-robin** [comment]
hi

**Comment by sriks123** [comment]
Hi @agjohnson I am interested to work on this issue. I just wanted to ask can someone who is new to this project can solve this issue?

**Comment by stsewd** [comment]
Thanks for the interest, I think this kind of depends on https://github.com/rtfd/readthedocs.org/pull/4722

**Comment by dojutsu-user** [comment]
@agjohnson I would like to take this issue up.
Can you please guide me on how to get started with this.

**Comment by ericholscher** [comment]
Should be easy enough to do it now, but we should build it knowing that the functionality that we call to index things might change, but that should be a small change in this part of the code.

**Comment by dojutsu-user** [comment]
> We have a management command for this

I am assuming that this command is `python manage.py reindex_elasticsearch -p <project_name>`.
right?

I will be making an initial PR soon.

**Comment by dojutsu-user** [comment]
One doubt, by the terms `Project Admin`, `Version Admin`, did you mean the project and version admin interface provided by the django or the one which is on RTD like `readthedocs.org/dashboard/<project-slug>/edit/` ?

**Comment by agjohnson** [comment]
These should be implemented as site admin features -- that is, in the Django admin.

**Comment by dojutsu-user** [comment]
This issue can be closed now.

**Comment by ericholscher** [comment]
:+1:
