### ISSUE TITLE
Trouble saving images during build

### ISSUE THREAD

**Issue by t-makaro** [rtfd/readthedocs.org#4661]
## Details

Sphinx-gallery is trying to add support for images that are saved to disk when an example is run:https://github.com/sphinx-gallery/sphinx-gallery/pull/417#issuecomment-423748055

I am trying to get a prototype of this to work over at: https://github.com/t-makaro/animatplot/pull/14

My docs build works perfectly locally or on cirleci, but for some reason when run on RTD the image files do not seem to be produced properly. (This would be much easier to debug if I could download the built source off RTD). The images are being saved to disk using matplotlib's PillowWriter, but for some reason on RTD only the first frame is saved.

* Read the Docs project URL: https://animatplot.readthedocs.io/en/latest/auto_examples/index.html
* Build URL (if applicable): https://readthedocs.org/projects/animatplot/builds/7828348/
* Read the Docs username (if applicable): t-makaro

## Expected Result

Two images are produced, and there are both animated. See:

https://145-87026896-gh.circle-artifacts.com/0/home/circleci/project/docs/build/html/auto_examples/plot_sqwell.html

## Actual Result

Two images are produced, but they are static.

https://animatplot.readthedocs.io/en/latest/auto_examples/plot_sqwell.html#sphx-glr-auto-examples-plot-sqwell-py

**Comment by t-makaro** [comment]
If I switch to using matplotlib's imagemagickwriter to save the gif. Then the build fails completely: https://readthedocs.org/projects/animatplot/builds/7828320/

with:
```
outfile must be *.htm or *.html
```

**Comment by stsewd** [comment]
What are the requirements to use this feature? Maybe there is something that needs to be installed?

**Comment by stsewd** [comment]
I'll take a look on Monday

**Comment by t-makaro** [comment]
The features are still under development I'm installing a dev version of sphinx-gallery by listing the git branch in the requirements file. As far as I can tell, it is installed properly it does run my example code and produces an image which it then adds to the auto-generated documents. (Ultimately, it uses matplotlib and Pillow to save the image to disk). The problem is that the gif isn't produced properly. Yet, local builds and circleci work fine.

**Comment by stsewd** [comment]
I'm not familiar with the libs you are using, neither the process that they follow to generate the images, so I can't tell if this is a rtd problem. What commands are you using to build the docs locally?

**Comment by stsewd** [comment]
Nevermind about the above comment, I don't think the extension is the problem (looks like I just needed to refresh the page to trigger the gif). I'm thinkgin something related to the libs installed locally. Maybe the pandoc version?

**Comment by stsewd** [comment]
Our latest image is using `pandoc 1.16.0.2`

**Comment by stsewd** [comment]
Ok, I was able to build the docs correctly inside the docker container, still not sure what is happening inside the rtd code. But something must be failing silently.

**Comment by stsewd** [comment]
Just adding that the generated git is half the size from the one generated outside rtd. Maybe a permissions issue?

**Comment by stsewd** [comment]
So, I finally was able to replicate this inside the container, if I do all the steps using a virtualenv, the generated gif is static (one frame, half the original size, etc). If I do all the steps using the global python interpreter, then the gif is generated correctly. I'm not really sure why is this happening. Locally, I was able to generate the correct gif using a virtualenv.

**Comment by choldgraf** [comment]
Hello! I'm one of the devs working with Sphinx Gallery. Could it be a difference in dependency versions? I think that there are some other ways to create gifs using matplotlib (with imagemagick I believe) so maybe that'll get it working

**Comment by t-makaro** [comment]
@stsewd Thank you for taking the time to replicate the issue. 

How could I install imagemagick for use on RTD? I did make one attempt to use imagemagick, but the build failed completely on RTD. (Imagemagick is also less good for my workflow).

**Comment by stsewd** [comment]
We have an open issue about adding imagemagick to the rtd docker images https://github.com/rtfd/readthedocs-docker-images/issues/70

**Comment by t-makaro** [comment]
I presume that would require me to use the latest docker image (once it's added), but I was having trouble building on the latest docker image. #4446 Though I think that I may know away around it. I'll try to test that later.

**Comment by stsewd** [comment]
If https://github.com/rtfd/readthedocs-docker-images/issues/70 works to solve this issus, we can keep this closed, if there is something else we should do let us know, so we can re-open.
