### ISSUE TITLE
Remove logic around finding a configuration file inside directories

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4669]
This should only search for a configuration file on the project's root.

https://github.com/rtfd/readthedocs.org/blob/6261427e662d9c3733568c33f760c5f5a2100c6d/readthedocs/config/config.py#L956-L956

As we can face some weird cases like a third party dependency having a `readthedocs.yml` file. Also, looks like travis only search for a configuration file on the root. And we have on our docs that we only search on the root.

Ref https://github.com/rtfd/readthedocs.org/issues/4668

**Comment by sobolevn** [comment]
Can we still provide a way to specify your `conf.py` location in the configuration?

Use-case: I have my application in root folder and my docs in `docs/` subfolder.
I do not want to have extra files that might interact with my app.

Real world example: https://github.com/wemake-services/wemake-python-styleguide

So, can we have an `conf_path` (or similar) option in `readthedocs.yml`?

**Comment by stsewd** [comment]
@sobolevn with our rtd configuration file v2, we have an option to specify the `conf.py` path (but you still need to put the readthedos.yaml in the root of your project). Right now you can to use the admin panel.

Our v2 will be available soon!

**Comment by stsewd** [comment]
This change has nothing to do with the `conf.py` file btw, it's about the `readthedocs.yml` file

**Comment by Mihir-Karbelkar** [comment]
Is this issue open because I would like to work on this as my first bug. All the "Good First Issue" have a PR opened for them. Can you help me out?

**Comment by humitos** [comment]
I think it was closed by #4755. Thanks!

**Comment by ppwwyyxx** [comment]
How about allowing a few other candidate locations other than root, like `docs/readthedocs.yml` as well?
Putting all kinds of config files for different services all in root is quite annoying. Despite they are hidden, they still show up on github.
