### ISSUE TITLE
RuntimeError when refreshing accounts locally

### ISSUE THREAD

**Issue by invinciblycool** [rtfd/readthedocs.org#4670]
## Details
A RuntimeError is returned when `refreshing your accounts` is clicked because [get_task_data](https://github.com/rtfd/readthedocs.org/blob/6261427e662d9c3733568c33f760c5f5a2100c6d/readthedocs/core/utils/tasks/retrieve.py#L16) gets task result which results in a RuntimeError saying `*** RuntimeError: Cannot retrieve result with task_always_eager enabled`

## Steps to Reproduce

- Setup the project locally

- Click on refresh your accounts under the `Import a Repository` section

**Comment by stsewd** [comment]
I think this is a duplicate of https://github.com/rtfd/readthedocs.org/issues/4077, also, you need to create a social application in your local instance to be able to use that functionality.

**Comment by invinciblycool** [comment]
@stsewd Okay. Also I was able to reproduce the issue after creating a social application.

**Comment by stsewd** [comment]
Your local instance needs to be visible from the internet to make this work properly, closing in favor of https://github.com/rtfd/readthedocs.org/issues/4077

**Comment by stsewd** [comment]
I use ngrok to test the github integration btw.

**Comment by invinciblycool** [comment]
Oh okay. Yeah I am familiar with `ngrok`. I will use it too. Thanks for the help.
