### ISSUE TITLE
"Edit on GitHub" url broken for sphinx projects

### ISSUE THREAD

**Issue by sualko** [rtfd/readthedocs.org#4671]
## Details

* Read the Docs project URL: https://jsxc.readthedocs.io
* Build URL (if applicable): https://github.com/jsxc/documentation

## Expected Result
"Edit on GitHub", "View on GitHub" and so on should link to https://github.com/jsxc/documentation.

## Actual Result
Those links points to https://github.com/jsxc/documentation/blob/master/home/docs/checkouts/readthedocs.org/user_builds/jsxc/checkouts/latest/conf.py/index.rst

As you can see the string `/home/docs/checkouts/readthedocs.org/user_builds/jsxc/checkouts/latest/conf.py` is added to the url. The only thing that I can think of, is that I have currently no tags in my repo. Maybe this is the reason, I don't know.

**Comment by pdavide** [comment]
@stsewd I don't think this is a duplicate issue as this bug is appearing in sphinx based projects too.
In the #4482 the value for `conf_py_path` is changed from a relative to an absolute path. This is passed to the sphinx build context and then in used in the readthedocs default theme to [generate the "Edit on [VCS]" link](https://github.com/rtfd/sphinx_rtd_theme/blob/310043695f75cac495f8bde089a301e53f46d6db/sphinx_rtd_theme/breadcrumbs.html#L45).
This is also documented in: https://docs.readthedocs.io/en/latest/vcs.html?highlight=conf_py_path
Maybe you need an absolute path here, but we also need to provide a relative path in the checkout to the docs root in order to generate a correct "Edit on [VCS]" link.

**Comment by stsewd** [comment]
oops, didn't see that your project is sphinx type. Yeah, that's a bug

**Comment by pdavide** [comment]
@stsewd that's not my project, I just noticed the same bug in a sphinx based project and commented this same issue instead of opening a new one.
Thanks for your commitment.

**Comment by leastprivilege** [comment]
I can confirm that we have the same issue with Sphinx.

https://identitymodel.readthedocs.io/en/latest/client/discovery.html
edit points to
https://github.com/IdentityModel/IdentityModel2/blob/master/home/docs/checkouts/readthedocs.org/user_builds/identitymodel/checkouts/latest/docs/conf.py/client/discovery.rst

**Comment by stsewd** [comment]
I have a PR that fixes this https://github.com/rtfd/readthedocs.org/pull/4696, should be fixed in our next deploy.

**Comment by francescozaia** [comment]
Is there an expected timeframe for the next deploy? Sorry to bother but this is affecting some of our docs. Thanks!

**Comment by stsewd** [comment]
We don't have a schedule for deploys, but I'd say next week or so

**Comment by ericholscher** [comment]
This should now be deployed. It will likely require a doc rebuild to fix.

**Comment by francescozaia** [comment]
It works indeed! Thanks a lot!

**Comment by sualko** [comment]
:tada: thanks for the quick fix :clap:

**Comment by fv3rdugo** [comment]
We use the default template, it has been necessary to modify a file and when it has been rebuild it has worked. The links to Edit Github are ok.  Thanks!

**Comment by stsewd** [comment]
@iamarnavgarg hi, you should only need to trigger a new build on the affected version, you can do this from the `Build` section of your project's dashboard.

**Comment by iamarnavgarg** [comment]
Thanks @stsewd . While building the project using `make html ` and writing breadcrumbs.html for broken links returns the following error: 

```
Theme error:
An error happened in rendering the page contents.
Reason: RuntimeError('maximum recursion depth exceeded',)
make: *** [html] Error 2
```

Can you please suggest where I am going wrong?

**Comment by stsewd** [comment]
Can you please point me to the project? Why do you need to override breadcrumbs.html?

**Comment by iamarnavgarg** [comment]
Hi @stsewd I have overcome the issue. Thanks for help!
However, I am not able to understand the purpose of the following lines in sphinx_rtd_theme
1. [Line 41](https://github.com/rtfd/sphinx_rtd_theme/blob/b9bf19f5be9ec18fc60ada9220d222cf57c21394/sphinx_rtd_theme/breadcrumbs.html#L41
)
2. [Line 61](https://github.com/rtfd/sphinx_rtd_theme/blob/b9bf19f5be9ec18fc60ada9220d222cf57c21394/sphinx_rtd_theme/breadcrumbs.html#L61
)
3. [Line 63](https://github.com/rtfd/sphinx_rtd_theme/blob/b9bf19f5be9ec18fc60ada9220d222cf57c21394/sphinx_rtd_theme/breadcrumbs.html#L63)

Can you please help me in it?

**Comment by iamarnavgarg** [comment]
@stsewd
