### ISSUE TITLE
RTD wants me to set up webhooks on a now non-maintaining project

### ISSUE THREAD

**Issue by Neui** [rtfd/readthedocs.org#4684]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/wla-dx/

I owned the wla-dx documentation project but not the github repository, so RTD couldn't set up integration for it (or I just didn't do it, can't really remember). The point is I get the "The project wla-dx doesn't have a valid webhook set up, commits won't trigger new builds for this project."-warning. Now since it isn't my project, I added the owner as a maintainer and he removed me as a maintainer. Now I can't access any of the admin stuff any more and it isn't listed as "my project".

## Expected Result

Not getting the "The project wla-dx doesn't have a valid webhook set up, commits won't trigger new builds for this project"-warning any more.

## Actual Result

I am still getting the warning. Following the "the project integrations"-link leads me to a "This page does not exist yet." with the URL being https://readthedocs.org/dashboard/wla-dx/integrations/ .

![Screenshot of the "my projects" page, showing my only project wla-dx-neui and the warning](https://user-images.githubusercontent.com/1196130/46256389-92bacc00-c4aa-11e8-8c6c-107ed4197f31.png)

**Comment by stsewd** [comment]
If you click the `the project integrations` link, does it disappear?

Also, this seems like a bug, we should show this message to owners only, if a user is removed we need to clean the messages.

**Comment by Neui** [comment]
> If you click the `the project integrations` link, does it disappear?

As the time I reported this, it didn't dissapear. I clicked on it multiple times. (One before writing the issue to see where it leads to me and multiple times to see what the message is for the issue)

However, I just opened RTD again and clicked on it and it then dissapeared. Did something changed? Note that I just did this on a Windows computer with Firefox where before I was using an Ubuntu computer (also with Firefox).

**Comment by stsewd** [comment]
Nothing has changed, that is the default behavior.

**Comment by remram44** [comment]
I am seeing this message even with a GitLab incoming webhook set (and working).

**Comment by stsewd** [comment]
@remram44 can you try to click on the link? It should disappear, but anyway I think the error should disappear when everything is ok.

**Comment by remram44** [comment]
It did! Weird, I am sure I had clicked on it before (or middle-clicked).

**Comment by humitos** [comment]
I introduced this bug in #4033 when I refactored how the webhook was added from a Celery task instead of the same request process and how all the notifications work when triggered from Celery and attached to the user.

**Comment by dojutsu-user** [comment]
@humitos 
fixing this issue means to undo the changes related to the webhook in #4033 ??
