### ISSUE TITLE
sphinx 1.8.1 build errors with "Inconsistency detected by ld.so: dl-version.c: 224 ..." 

### ISSUE THREAD

**Issue by jcmgray** [rtfd/readthedocs.org#4686]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/quimb/
* Build URL (if applicable): https://readthedocs.org/projects/quimb/builds/7830573/ (first broken build)
* Read the Docs username (if applicable): ``jcmgray``

## Expected Result

The documentation built without hitch until it seems ``sphinx`` changed from ``v1.8.0`` to ``v1.8.1``. The actual [commit](https://github.com/jcmgray/quimb/commit/17c4b49f5f851f3f760a239476c100aead3b0869) which was broken first wasn't docs related but I see from the logs the sphinx version did change.

## Actual Result

At the build stage I get the error:

```
Running Sphinx v1.8.1
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!
```
---

### other notes / attempted troubleshooting:

* I have tried setting ``sphinx=1.8.0`` in the conda dependency yaml (and wiping the build) but this hasn't had an effect, I think as the command ``conda install --yes --name develop mock pillow sphinx sphinx_rtd_theme`` is run subsequently and ends updating to ``1.8.1``.
* The [sphinx release notes](http://www.sphinx-doc.org/en/master/changes.html) for 1.8.1 don't seem to mention applicable breaking changes.
* I tried reverting the build image to ``2.0`` from ``latest`` with no effect.
* The docs build locally (ubuntu 18.04 + conda) with ``sphinx=1.8.1`` without issue.

**Comment by stsewd** [comment]
Maybe this is a sphinx bug? Also, to pin dependencies using conda we have this https://github.com/rtfd/readthedocs.org/issues/3829 (we are waiting for a conda release)

**Comment by stsewd** [comment]
Not sure if this is the same https://github.com/sphinx-doc/sphinx/issues/5496

**Comment by stsewd** [comment]
Not worries, I'll try to reproduce this locally later and see where the problem is

**Comment by stsewd** [comment]
> I'll try to reproduce this locally later and see where the problem is

Conda is really heavy for my computer, I'm hitting my memory limit before the build ends :/

**Comment by jcmgray** [comment]
Closing as the docs now seem to be working - I've had a quick look in the logs but couldn't see any particular changes that might explain it. @stsewd thanks very much for taking a look!
