### ISSUE TITLE
Installation timeout

### ISSUE THREAD

**Issue by rsyi** [rtfd/readthedocs.org#4691]
## Details

Installation times out before docs can be built. Not sure if this is a common problem -- is there anything I can do to allow the build to occur more quickly? I tried disabling the epub and pdf compilations, but it doesn't quite help. It appears the installation fails during the `python install` step.

* Read the Docs project URL: https://pylift.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/pylift/builds/7867307/
* Read the Docs username (if applicable): ryi

## Expected Result

Docs build normally.

## Actual Result

Installation times out, docs not built.

**Comment by stsewd** [comment]
The command that fails isn't that one (https://github.com/rtfd/readthedocs.org/issues/4288), so probably is failing when installing your requirements or building the actual html.

Did you read this https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html?

If that doesn't help, I'll investigate a little more. Also, you can request more time/memory is nothing else helps.

**Comment by rsyi** [comment]
Ah no I didn't see that page yet. I have functioning documentation now, thank you!

For those who come across a similar problem, here were my steps towards resolution:
* I added a `readthedocs.yml` file that set `formats: []` and `python: use_system_site_packages: true` and found that the build now gave me more informative error messages: https://readthedocs.org/projects/pylift/builds/7874640/ 
For some reason, it seems that the `requirements.txt` file I had by default in my parent directory was being used! 
* Add in a `rtd_reqs.txt` file (empty), and explicitly specify that as my requirements file in the Advanced Settings section.

Does this mean by default the `requirements.txt` file I had in my parent directory was being used by readthedocs?

**Comment by stsewd** [comment]
> Does this mean by default the requirements.txt file I had in my parent directory was being used by readthedocs?

Yes, rtd by default tries to install a requirements.txt file, you'll be able to skip that in our v2 of the config file https://github.com/rtfd/readthedocs.org/issues/1621#issuecomment-419146325, for now using a empty file is a workaround.

Can we close this issue?

**Comment by rsyi** [comment]
Great good to know. Thanks, and yes!
