### ISSUE TITLE
Fail to create conda environment

### ISSUE THREAD

**Issue by JiaweiZhuang** [rtfd/readthedocs.org#4695]
## Details

* Read the Docs project URL: http://cloud-gc.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/cloud-gc/builds/7872181/
* Read the Docs username (if applicable): zhuangjw

## Expected Result

Builds worked normally 3 days ago.

## Actual Result

Since 2 days ago, the builds always failed with `CondaValueError: pip returned an error.`

This error happens for other projects using conda, for example https://readthedocs.org/projects/xesmf/builds/7872438/

I noticed the recommendation [Use pip when possible](https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html#use-pip-when-possible). Does this error happen because conda uses too much memory?

**Comment by stsewd** [comment]
> I noticed the recommendation Use pip when possible. Does this error happen because conda uses too much memory?

I think it can be, I'll test this locally later

**Comment by JiaweiZhuang** [comment]
@stsewd Thanks! I switched to pip and the error is gone. But does this mean that I shouldn't use conda (also for other projects)?

The just-build page has another problem that the "Edit on GitHub" button was broken. That button was working before. Seems to duplicate #4671. Looks like there's already a solution #4696.

**Comment by stsewd** [comment]
If your project can be built using pip, that is preferred over conda, if you really need to use conda and it fails, you can request more time/memory for your project. And yes, #4696 fix that problem, hope we can deploy that soon.

**Comment by agjohnson** [comment]
Both projects show the same failure:

```
pip._vendor.pkg_resources.RequirementParseError: Invalid requirement, parse error at "'; extra '"
```

This doesn't look resource related. Most likely, if not a problem with the formatting of your requirements, is a change in conda somewhere?

**Comment by JiaweiZhuang** [comment]
@agjohnson  Good catch. I think I've found the issue: conda-forge/testpath-feedstock#7

**Comment by stsewd** [comment]
If this isn't a problem related to rtd, we can close this issue.

**Comment by JiaweiZhuang** [comment]
Sounds good to me
