### ISSUE TITLE
Remove $ before shell commands in docs

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#4698]
The developers have a [preference](https://github.com/rtfd/readthedocs.org/pull/4676#discussion_r221400605) to not have a `$` before shell commands in the docs. This makes it easier to copy and paste from our docs. We should remove it everywhere. The following command should show it everywhere.

    grep -Ri "    $ " docs/*.rst docs/*/*.rst

**Comment by houllette** [comment]
@davidfischer I can take a stab at this!

**Comment by davidfischer** [comment]
I think #4699 is almost there and there's just a few things left for @

**Comment by himanshuc3** [comment]
Is this issue closed. I am looking for a beginner issue!

**Comment by stsewd** [comment]
This issue is already taken, there is a PR opened https://github.com/UPC/ravada/issues/890

**Comment by himanshuc3** [comment]
OK. I would like to take any beginner issues but most of them have open PRs on them. I'll figure something else out i guess.

**Comment by RichardLitt** [comment]
@himanshuc3 If you can't find any that are open, let us know. We can probably make some more.

**Comment by rajdeepbharati** [comment]
Can I take up this issue?

**Comment by stsewd** [comment]
@rajdeepbharati sorry, there is an open PR already https://github.com/rtfd/readthedocs.org/pull/4699

**Comment by championballer** [comment]
@RichardLitt It would be great if some good first time issues can be introduced for the project.

**Comment by stsewd** [comment]
There are, but some are already taken https://github.com/rtfd/readthedocs.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22, we try to label introductory issues with that label. When watching the repo GitHub show issues on your "timeline/dashboard" when they are labeled.
