### ISSUE TITLE
Deploying built documentation to S3 (and others)

### ISSUE THREAD

**Issue by mikebryant** [rtfd/readthedocs.org#470]
It would be nice to be able to deploy built documentation to S3 or similar, instead of hosting it under nginx.
This could be achieved in a nice decoupled way by providing an option to save the files using the standard django media framework - then by using something like django-storages you could easily send those files wherever you wanted.

**Comment by ericholscher** [comment]
Closing this, as I don't think this is something we will likely support any time soon. All the files are generated by Sphinx, and never pass through Django, and we have a Syncer abstraction now that could be subclassed to sync them to different backends. We may add Syncer's in the main codebase, but users could add and configure them, so I'm calling this done.
