### ISSUE TITLE
Translation requires mo files

### ISSUE THREAD

**Issue by csezenoglu** [rtfd/readthedocs.org#4702]
## Details

* Read the Docs project URL: https://loop-antennas.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): csezenoglu

I completed the steps in "Manage Translations" subject [here](https://docs.readthedocs.io/en/latest/guides/manage-translations.html#manage-translations)

If I commit only po files, RTD did not build locale language html files, and there was no error or warning.
If I commit mo files, RTD build successfully.

## Expected Result

RTD build the po files. 

## Actual Result

RTD build only mo files.

**Comment by stsewd** [comment]
I don't know much about translations yet, bu tI know @humitos has more experience dealing with translations

**Comment by agjohnson** [comment]
RTD doesn't do anything to generate the mo files, those are required to be checked into your repository, correct. If it's not clear in the guide, we should update the guide to mention checking these files in.

**Comment by csezenoglu** [comment]
Yes, I think some explanations can be added "Manage Translation" document.
There are two notes about documentations:
1. https://docs.readthedocs.io/en/latest/i18n.html

"Compiling to MO" section:
> Also, note that it’s not a good idea to track MO files in version control, since they would need to be updated at the same pace PO files are updated, so it’s silly and not worth it. They are ignored by .gitignore, but please make sure you don’t forcibly add them to the repository.

What does it mean exactly?

2. https://docs.readthedocs.io/en/latest/localization.html

Note:
> You must commit the .po files for Read the Docs to translate your documentation.

This part needs some expansion.

**Comment by humitos** [comment]
> "Compiling to MO" section

What this section says is correct. It's talking about "RTD Django application" not about "Project's documentation translation at RTD".

> You must commit the .po files for Read the Docs to translate your documentation.

I think this is correct.

> RTD doesn't do anything to generate the mo files

I'm in doubt with this. I suppose that `.mo` files are not required and they should be built automatically by Sphinx.

Sphinx docs: http://www.sphinx-doc.org/en/master/intl.html
Sphinx specific conf to auto generate `.mo`: http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-gettext_auto_build

@csezenoglu taking a look at your `.po` file I don't see any translated text: https://github.com/csezenoglu/RTD-Loop-Antennas/blob/master/locale/tr_TR/LC_MESSAGES/index.po. That's why Sphinx picks the original text, because there is no translation :)

**Comment by agjohnson** [comment]
Tested this and the build step should in fact generate mo files. We do check all of these in on our docs and django translations for our own docs, but it shouldn't be necessary. There is something else going wrong.

My guess is that your locale is `tr_TR`, which is not a locale code we used. Turkish would be `tr` I believe. Try this and try to adding translated strings into your po files first. I think one of these two options will solve your problem.

**Comment by humitos** [comment]
> My guess is that your locale is `tr_TR`, which is not a locale code we used

It's not that _we_ use, actually. It is a Sphinx thing: http://www.sphinx-doc.org/en/master/usage/configuration.html#confval-language

**Comment by agjohnson** [comment]
Well, sort of. We set the language via the project language choices:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/constants.py#L114-L259

These don't exactly map up with the Sphinx supported languages.

Also, the language value is mostly arbitrary, for example:

```
% sphinx-intl update -p _build/gettext -l patrick_SWAYZE 
Create: locales/patrick_SWAYZE/LC_MESSAGES/index.po
Create: locales/patrick_SWAYZE/LC_MESSAGES/bar.po
Create: locales/patrick_SWAYZE/LC_MESSAGES/foo.po

% sphinx-build -D language=patrick_SWAYZE . _build/html
Running Sphinx v1.7.8
loading translations [patrick_SWAYZE]... not available for built-in messages
loading pickled environment... done
building [mo]: targets for 3 po files that are out of date
writing output... [100%] locales/patrick_SWAYZE/LC_MESSAGES/bar.mo                                    
building [html]: targets for 3 source files that are out of date
updating environment: [config changed] 3 added, 0 changed, 0 removed
reading sources... [100%] index                                                                       
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                        
generating indices... genindex
writing additional pages... search
copying images... [100%] images/test.png                                                              
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build/html.
```

**Comment by humitos** [comment]
@agjohnson thanks for clarifying this.

From your last command output, we can see something that is key about the original issue reported:

```
building [mo]: targets for 3 po files that are out of date
writing output... [100%] locales/patrick_SWAYZE/LC_MESSAGES/bar.mo                                    ```

That means that Sphinx automatically builds the `.mo` files and so they are not required to be included in the repository.

So, @csezenoglu could you put your project in the desired state where you expect that it should work but it's not? At the moment, I don't see any issue with Read the Docs that I can replicate in my side.

**Comment by csezenoglu** [comment]
It is ok now. Thank you for your interest. I think some detailed explanations should be added documentation. If you want I can add proper details.

**Comment by humitos** [comment]
@csezenoglu great!

Feel free to open a PR with the detailed explanations that you think are needed into the docs. Appreciated!

**Comment by agjohnson** [comment]
I opened #4718 to maybe address catching this as an error on our side. Perhaps we can do validation that the locale exists and warn the user.

This might also tie in with something like a transifex or weblate integration that could also warn that:

* Translations are out of date
* Translations are below a threshold of translated %

etc.

Glad your issue is fixed though!
