### ISSUE TITLE
Slow menu updates; should be able to browse the menu without loading the page

### ISSUE THREAD

**Issue by jfehrle** [rtfd/readthedocs.org#4707]
## Details

* Read the Docs project URL: https://coq.inria.fr/distrib/current/refman/proof-engine/vernacular-commands.html

When browsing the left-hand menu, clicking on a new top-level section can be slow (a couple seconds) because it loads the full document.  This is a long while just to see a few subentries in the menu. The user should be able to browse the menu without so much delay.

For example: I'm looking at the "Gallina specification language" chapter. I want to see the subentries of "Extensions of Gallina" in the short (on-screen) table of contents. Clicking on "Extensions of Gallina" takes a couple seconds before its subentries are visible because that loads the entire chapter as well.

![image](https://user-images.githubusercontent.com/1253341/46371716-faede700-c63d-11e8-9aa6-f63a65a95246.png)

![image](https://user-images.githubusercontent.com/1253341/46371756-122cd480-c63e-11e8-8037-33c524d064d1.png)

**Comment by stsewd** [comment]
This issue should be on the [rtd theme repo](https://github.com/rtfd/sphinx_rtd_theme). Not sure if that would be possible, I'm not that familiar with sphinx internals.

**Comment by jfehrle** [comment]
Moved to https://github.com/rtfd/sphinx_rtd_theme/issues/681 in the rtd theme repo.
