### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by naor2013** [rtfd/readthedocs.org#4713]
When is Python 3.7 support coming for creating docs with RTD? Sphinx already supports it and we can create the docs ourselves with no issue but when using RTD, we get errors regarding missing imports that only exist in 3.7.

**Comment by humitos** [comment]
Hi @naor2013! Unfortunately, we don't have this into our roadmap yet.

I'm not sure if this could be part of our 4.0 Docker image or not: https://github.com/rtfd/readthedocs-docker-images

I think it shouldn't be a big change in the image (just add 3.7 from pyenv) but what is taking some time is testing and deploy the images.

**Comment by naor2013** [comment]
Thanks! Thanks. For now, we'll make our own docs so we can wait. take your time and keep doing an awesome job! :D

**Comment by agjohnson** [comment]
You can also skip installation of those dependencies and mock them out in your docs. Agreed that 3.7 would be helpful though, I think we can add it to our 4.1 RC image. Moving this to rtfd/readthedocs-docker-images#72

**Comment by vEpiphyte** [comment]
@naor2013 You can use `conda` to do 3.7 at the moment if it is a pressing need.  See https://github.com/rtfd/readthedocs-docker-images/pull/73 for notes and a patch.
