### ISSUE TITLE
Build failed at git clean stage

### ISSUE THREAD

**Issue by spinicist** [rtfd/readthedocs.org#4728]
## Details

Hello,
I am trying to swap from Github Pages (compiled with mkdoc) to ReadTheDocs (and Sphinx) for my C++ project. I wanted to do this in a separate branch before merging to master, but that appears to be failing because the `git clean` step fails (there is a directory in the master branch that no longer exists in the Sphinx branch).

* Read the Docs project URL: https://readthedocs.org/projects/quit
* Build ID: 7885204
* Build URL (if applicable): https://readthedocs.org/projects/quit/builds/7885204/
* Read the Docs username (if applicable): same as Github

## Expected Result

ReadTheDocs completes the build

## Actual Result

The build fails at the `git clean` stage.

**Comment by stsewd** [comment]
The issue is because you have an invalid submodule https://github.com/spinicist/QUIT/blob/0d81abb965d9c1be0ccbd071d9ee453daad6e4db/.gitmodules#L10 and rtd fails when checking for submodules

**Comment by stsewd** [comment]
And thanks for using rtd!

**Comment by humitos** [comment]
@spinicist please, remove the submodule that @stsewd mentioned and try building again. It should work after that. If that's the case, please close this issue.

In case you find any different problem on your building after removing that submodule, please open a new issue.

Thanks and welcome home ;)

**Comment by spinicist** [comment]
Thanks at @stsewd and @humitos! That invalid submodule must have been hanging around for months 😳 I've excised it and it does now work.

Any idea why rtd didn't report the failing submodule step? When I looked at the raw logs, the last step kept saying it exited with status 0 which was confusing.

**Comment by stsewd** [comment]
That's another issue #4288

**Comment by spinicist** [comment]
Great - hopefully that will get resolved in the future.

Final question - is there a way to get rtd to skip the submodule checkout stage? For my project, I don't need the submodules to build the documentation.

Thanks for your fast responses, very much appreciated.

**Comment by stsewd** [comment]
We have that feature in our next version of the configuration file https://github.com/rtfd/readthedocs.org/pull/4493 (hope we have an opt-in or open beta soon), stay tuned!

**Comment by spinicist** [comment]
Good news, thanks again.

**Comment by humitos** [comment]
Happy that you fixed your issue!

**Comment by spinicist** [comment]
Um, it fixed one issue but now I have another related one (sorry).

I have two branches - `master` and `sphinx` - in my github repo. When I pushed my updates to the `sphinx` branch and triggered a build, it all worked fine (https://quit.readthedocs.io/en/sphinx/). However, when I merged those changes to `master` and pushed, which is picked up by rtd as `latest`, I don't get my documentation, but the documentation for one of the submodules (ceres, https://quit.readthedocs.io/en/latest/). For some reason on `latest` rtd decides to pick up the `conf.py` for Ceres (https://readthedocs.org/projects/quit/builds/7896020/)

So I could use that beta version ASAP 😉

**Comment by stsewd** [comment]
You can select a `conf.py` file from the web admin of your project `Admin` -> `Advanced Settings`

**Comment by spinicist** [comment]
I missed that setting. Hooray! It all works now.

**Comment by Faith-Ogundu** [comment]
hello. i'm a beginner and im finding it really difficult to effect changes on my page as it keeps failing on the build stage. Something that has to do with the build stage. please can you assist me resolve this issue?
