### ISSUE TITLE
Domain HTTPS stuck pending validation

### ISSUE THREAD

**Issue by ChaosCA** [rtfd/readthedocs.org#4736]
## Details

* Read the Docs project URL: http://docs.owlgaming.net/
* Build URL (if applicable): https://gitlab.com/OwlGamingCommunity/docs
* Read the Docs username (if applicable): chaosmta

## Expected Result

Enabled always use HTTPS on the domain and it applies the SSL cert.

## Actual Result

The status is stuck saying "Pending" for > 12 hours. The domain is CNAME'd properly to the `readthedocs.io` through Cloudflare.

**Comment by davidfischer** [comment]
Maybe DNS is very slow propagating, but the DNS does not appear to be correct from where I'm sitting.

    $ dig docs.owlgaming.net CNAME +short
    owlgaming.readthedocs.io.

This should return *just* `readthedocs.io` not a subdomain.

**Comment by ChaosCA** [comment]
Thank you! Your correct I had it setup incorrectly.

**Comment by nadar** [comment]
I do have the same problem, but the domain is set correctly:

```sh
$ dig docs.unglue.io CNAME +short
readthedocs.io.
```

**Comment by humitos** [comment]
@nadar I checked the logs and I see that Cloudflare returned 409 (Conflict) when saving the Domain. I assume that this is because the cert is already requested/created at Cloudflare.

I also make a query to Cloudflare to double check its status and it says that the status is `pending_validation`.

I'm investigating a little more and asking my team mates because I'm not 100% about how it works :confused:

**Comment by humitos** [comment]
@nadar also, check David's response: https://github.com/rtfd/readthedocs.org/issues/4736#issuecomment-427663456


> This should return _just_ `readthedocs.io` not a subdomain.

:point_up_2:

**Comment by nadar** [comment]
Yes, status is also pending in the control panel 😞 - since more then 2 days. So i assume something wen't wrong.

<img width="581" alt="bildschirmfoto 2018-12-29 um 11 15 32" src="https://user-images.githubusercontent.com/3417221/50537015-1beda780-0b5b-11e9-8aeb-c7150c503ca9.png">

**Comment by davidfischer** [comment]
It was stuck waiting on verification. When I refreshed it, everything worked and it deployed correctly. Maybe we need a way to do that from the UI.
