### ISSUE TITLE
Requirements.txt file not found

### ISSUE THREAD

**Issue by ZRunner** [rtfd/readthedocs.org#4737]
## Details

* Read the Docs project URL: https://zbot.rtfd.io
* Build URL (if applicable): Last was https://readthedocs.org/projects/zbot/builds/7903502/
* Read the Docs username (if applicable): ZRunner
* GitHub URL: https://github.com/ZRunner/ZBot

For a few days, without having moved any configuration files, the compilation fails every time, supposedly because the requirements.txt file does not exist, while it is present in the /docs folder. I tried to move it to the root of the repository, or change the path from the project settings, without success. It seems I'm not the only one with this problem...
When I compile the project from my computer, no problems occur.

## Expected Result

A nice compilation with all the changes I need to make quickly

## Actual Result

Error in the command `python /home/docs/checkouts/readthedocs.org/user_builds/zbot/envs/v3/bin/pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/zbot/.cache/pip -r requirements.txt`

**Comment by stsewd** [comment]
Please see https://github.com/rtfd/readthedocs.org/issues/4668#issuecomment-425157245 and https://github.com/rtfd/readthedocs.org/issues/4668#issuecomment-425646491

We have this issue open https://github.com/rtfd/readthedocs.org/issues/4669

**Comment by ZRunner** [comment]
It seems to work now. Thank you so much!
