### ISSUE TITLE
Different images for a source project and its translations

### ISSUE THREAD

**Issue by MaslovaEV** [rtfd/readthedocs.org#4738]
## Details
I have implemented a translation for my project using the instructions at [Manage translations](https://docs.readthedocs.io/en/latest/guides/manage-translations.html).  And as it is expected the translation shows the same images as in the source project. 

But in my case, the translation requires other images. 

Is there any way to specify images for a translation other than in the source project?

**Comment by stsewd** [comment]
This issue tracker is for issues related to rtd, for questions like this, you should use stackoverflow or sites like that. What you are asking looks like a sphinx feature or extension.
