### ISSUE TITLE
There was a problem with Read the Docs while building your documentation

### ISSUE THREAD

**Issue by emodric** [rtfd/readthedocs.org#4741]
## Details

* Read the Docs project URL: https://netgen-layouts.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/netgen-layouts/builds/7912551/
* Read the Docs username (if applicable): emodric

## Expected Result

A build to succeed without an error message

## Actual Result

There's an error message about a problem with the build.

> There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (7912551).

The error message is generic and I can't deduce what the problem is. I also got the e-mail that the build errored out. However, the build did actually succeed and the updated docs are visible online.

**Comment by stsewd** [comment]
You are not building pdf or epub, right?

**Comment by emodric** [comment]
Nope, only HTML.

**Comment by stsewd** [comment]
I'm not sure, it's failing o the last step, someone with access to the logs can take a deeper look.

**Comment by humitos** [comment]
I think it was a temporal error in the servers. It failed when creating the docker container for some reason.

I re-trigger you `latest` version and it should pass.

[ ... ]

I passed. I'm closing this issue. Please, feel free to reopen if you consider.
