### ISSUE TITLE
Artifacts aren't cleaned when changing from Sphinx to Mkdocs

### ISSUE THREAD

**Issue by raoshridhar90** [rtfd/readthedocs.org#4764]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/wait/
* Build URL (if applicable): 
* Read the Docs username (if applicable): shridhar.rao

## Expected Result

HTML copy of what I see on **View Docs**

## Actual Result

HTML copy is of Sphinx document I was trying out
![what i see](https://user-images.githubusercontent.com/13954344/47010106-bf820b00-d15b-11e8-8f91-f3c437ad8348.JPG)
![what i get](https://user-images.githubusercontent.com/13954344/47010105-bf820b00-d15b-11e8-8023-76c12b03c39a.JPG)

P.S: I am absolutely brand new at this because I know nothing about Python. I'm just a technical writer trying to find a way to document my company's backend.

**Comment by stsewd** [comment]
> HTML copy of what I see on View Docs

Sorry, I don't understand your issue, can you please clarify a little more?

We have this getting started guides for sphinx or mkdocs here https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html https://docs.readthedocs.io/en/latest/intro/getting-started-with-mkdocs.html

**Comment by davidfischer** [comment]
> If I have the time, I will update your documentation (if open source) because there are big gaps in it in my opinion as a technical writer.

I wrote this relatively recently and would love help on filling in the gaps. It is open source and you can find the getting started with mkdocs guide [here](https://github.com/rtfd/readthedocs.org/blob/master/docs/intro/getting-started-with-mkdocs.rst).

> Hey @davidfischer, I thought that was the problem too, the first time I encountered this. But in this current generation instance, it is Markdown as shown below.

Actually when I look at this, I don't yet see what the problem is. Based on your repository, I think it should generate HTML like [this](https://wait.readthedocs.io/en/latest/about/). Maybe I don't yet fully understand the problem.

**Comment by stsewd** [comment]
So, I think I understand the problem here, your project is mkdocs type, mkdocs doesn't support pdf or epub generation. But, I can see that your project does have links to download pdf and epub.

So, I saw your builds, and I found that one of those was using sphinx, there were generated pdf and epub files. Then, when building back with mkdocs, those files aren't removed, so your project keeps serving the old sphinx generated files.

We should clean that files when building with mkdocs.

**Comment by raoshridhar90** [comment]
@stsewd thank you! How do I clean those files is my question.

**Comment by stsewd** [comment]
I think a workaround can be building with sphinx again, but un-selecting the epub and pdf generation, then if you change back to mkdocs, those files should be removed. But this is a bug on rtd and we should fix it.

**Comment by raoshridhar90** [comment]
What if I get rid of Sphinx? As someone who knows very little about Python, Sphinx has been excessively complicated for me. But I'll try your suggestion and close this open query when I do it. However, it's late in India so I'll get to it tomorrow!

Thanks!


On Oct 18, 2018 at 01:48, <Santos Gallegos<mailto:notifications@github.com>> wrote:


I think a workaround can be building with sphinx again, but un-selecting the epub and pdf generation, then if you change back to mkdocs, those files should be removed. But this is a bug on rtd and we should fix it.

**Comment by raoshridhar90** [comment]
> > If I have the time, I will update your documentation (if open source) because there are big gaps in it in my opinion as a technical writer.
> 
> I wrote this relatively recently and would love help on filling in the gaps. It is open source and you can find the getting started with mkdocs guide [here](https://github.com/rtfd/readthedocs.org/blob/master/docs/intro/getting-started-with-mkdocs.rst).
> 
> > Hey @davidfischer, I thought that was the problem too, the first time I encountered this. But in this current generation instance, it is Markdown as shown below.
> 
> Actually when I look at this, I don't yet see what the problem is. Based on your repository, I think it should generate HTML like [this](https://wait.readthedocs.io/en/latest/about/). Maybe I don't yet fully understand the problem.

Hey @davidfischer, I will definitely do it when I figure out this problem. Also, I think there are gaps in the ReadTheDocs documentation. MkDocs seems pretty straightforward. However, for now, the [link](https://wait.readthedocs.io/en/latest/about/) you attached seems to be broken, so I don't really know what you mean. Haha, wow. This is confusing.

**Comment by raoshridhar90** [comment]
> I think a workaround can be building with sphinx again, but un-selecting the epub and pdf generation, then if you change back to mkdocs, those files should be removed. But this is a bug on rtd and we should fixed it

@stsewd, I tried that but same problem again. Doesn't seem to be making a difference. I hope that bug is ironed out soon then!

**Comment by davidfischer** [comment]
> However, for now, the link you attached seems to be broken

That's weird. It seems to be working for me even in incognito!

I still don't seem to understand this issue. I don't see the links to download an epub or PDF anymore.

<img width="1269" alt="screen shot 2018-10-18 at 10 55 13 am" src="https://user-images.githubusercontent.com/185043/47174020-68e41080-d2c4-11e8-9e6f-98ac892f12d7.png">

**Comment by stsewd** [comment]
@davidfischer If I recall correctly, we don't generate any type of download for Mkdocs projects, the download section shouldn't be there.

@raoshridhar90 rtd built the html files for download on sphinx always, it can only be disabled using a configuration file https://docs.readthedocs.io/en/latest/yaml-config.html#supported-settings The pdf and epub aren't there, so the previous step worked! So, I see two workarounds here, using a config file to not build any format, or just recreating your project and using mkdocs as the doctype from the beginning

**Comment by stsewd** [comment]
>If @stsewd is saying it shouldn't be generating any download, then I don't know why this is. Any explanations, @stsewd?

Is because of the same problem, you built wih sphinx once, rtd generated the download files, then when changing to mkdocs, rtd doesn't clean the previous files.

- We don't provide any downloads on Mkdocs (that's a limitation of mkdocs, not from rtd). 
- You can use markdown with sphinx (downloads here are supported)

**Comment by raoshridhar90** [comment]
> > If @stsewd is saying it shouldn't be generating any download, then I don't know why this is. Any explanations, @stsewd?
> 
> Is because of the same problem, you built wih sphinx once, rtd generated the download files, then when changing to mkdocs, rtd doesn't clean the previous files.
> 
> * We don't provide any downloads on Mkdocs (that's a limitation of mkdocs, not from rtd).
> * You can use markdown with sphinx (downloads here are supported)

Haha, cool. I'll play around with Sphinx a bit. Thank you so much for all the help. I hope you get that bug sorted out. Also, thank you so much; you guys are much friendlier and much more helpful than StackOverflow. Those dudes are rude!

**Comment by raoshridhar90** [comment]
@stsewd, I migrated completely to Sphinx from Mkdocs, but thanks for all the help!

**Comment by stsewd** [comment]
Not stale, just low priority :) bot

**Comment by stsewd** [comment]
I can't replicate this anymore locally or in production. It was fixed https://github.com/rtfd/readthedocs.org/pull/4947/ in with the `delete_unsynced_media` arg

**Comment by jyearsley** [comment]
I'm having this same problem, that is, my them is Mkdocs, but the build is done by Sphinx even when I make the change in Advanced Settings

**Comment by humitos** [comment]
@jyearsley if you are using a configuration file (see https://docs.readthedocs.io/en/stable/config-file/v2.html), you should change this in that file. If that doesn't solve your immediate problem, please open a new issue filling the template with your projects' info.
