### ISSUE TITLE
Download role not appearing with Sphinx 1.8

### ISSUE THREAD

**Issue by aradi** [rtfd/readthedocs.org#4765]
## Details

* Project URL: https://readthedocs.org/projects/aradi-rtdtest/
* Build URL: https://readthedocs.org/projects/aradi-rtdtest/builds/7948735/
* Read the Docs username: balint

## Expected Result

* Generating an HTML document with working download links.

## Actual Result

*Download links are missing in the HTML output.

**Comment by stsewd** [comment]
I can see the download links here https://readthedocs.org/projects/aradi-rtdtest/downloads/ and 
![screenshot_2018-10-16 test chapter rtd test documentation](https://user-images.githubusercontent.com/4975310/47027325-dcebb080-d12c-11e8-8a27-121999fa3418.png)

**Comment by aradi** [comment]
Sorry, my formulation was misleading. If you look at the generated HTML document https://aradi-rtdtest.readthedocs.io/en/latest/rtdtest.html, the links for the two files are missing, which were added via the `:download:` role to the RST-source. The original RST-source is:
```
Test chapter
============

Download button for some input file:

.. only :: builder_html

   See :download:`full input 1 <_downloads/md1/dftb_in.hsd>` and
   :download:`full input 2 <_downloads/md2/dftb_in.hsd>`

Finished.
```

**Comment by stsewd** [comment]
The links are relative to the current file or if you want to put absolute links, it need to begin with `/`


http://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#role-download

**Comment by aradi** [comment]
As the `_downloads` folder is in the same folder as the RST-source file (in `docs/`) it should work in my opinion. If I build the HTML locally using  sphinx 1.8, the download links in the generated HTML appear as expected. Further the build log on Readthedocs seems also to indicate, that the `:download:` role was used correctly, as the referenced files are copied: 
```
copying downloadable files... [ 50%] _downloads/md1/dftb_in.hsd
copying downloadable files... [100%] _downloads/md2/dftb_in.hsd
```

**Comment by stsewd** [comment]
I guess the `_downloads` folder is colliding somehow with the folder from sphinx?

**Comment by aradi** [comment]
I don't think so:
* On my local system, building with Sphinx 1.8 produces the right HTML page.
* I've renamed `_downloads` into `_mydownloads`. On my local system, it still works. On readthedocs it's still broken. Although Sphinx apparently recognizes the `:download:` role and the associated files
```
copying downloadable files... [ 50%] _mydownloads/md1/dftb_in.hsd
copying downloadable files... [100%] _mydownloads/md2/dftb_in.hsd
```
the appropriate links in the HTML page still do not show up.

**Comment by stsewd** [comment]
I was looking a little more into this issue, I realized that you are using `.. only :: builder_html`, rtd uses a custom builder called `readthedocs`. So, you should use `.. only :: builder_html or readthedocs`. I tested this locally and it works

![screenshot_2018-10-22 test chapter rtd test documentation](https://user-images.githubusercontent.com/4975310/47311235-cd71d900-d5fe-11e8-8013-0a7ef6ad6573.png)

**Comment by aradi** [comment]
Works perfectly, thank you very much for your time! :smile:
