### ISSUE TITLE
Remove /embed endpoint

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4768]
Similar to #4731

https://github.com/rtfd/readthedocs.org/blob/604e1fa0374a0ba1b242b88e6f242eff77b7b6c3/readthedocs/restapi/urls.py#L66-L66

Raised in https://github.com/rtfd/readthedocs.org/pull/4731/files#r222783446

**Comment by dojutsu-user** [comment]
@stsewd Will it be okay if I take this issue.

**Comment by stsewd** [comment]
Sure
