### ISSUE TITLE
HTML microdata: itemscope='https://schema.org/APIReference'

### ISSUE THREAD

**Issue by kael** [rtfd/readthedocs.org#4770]
## Details

https://docs.readthedocs.io/en/latest/ (example)

## Actual Result

Currently, API docs contain HTML microdata using the http://schema.org/Article context.

It is imprecise and confusing compared to other types of articles (Tech & News).

```html
<div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article"></div>
```

## Expected Result

There's a more precise context to describe API references https://schema.org/APIReference, although it's unclear what's its status. Perhaps there's some stuff to look into.

```html
<div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/APIReference"></div>
```

More on the topic: [API Discovery: Can we do better?](https://news.ycombinator.com/item?id=13004833)

**Comment by stsewd** [comment]
I think you should open this issue on the sphinx repo, this isn't handled by rtd.

**Comment by kael** [comment]
Well, searching a bit further, it seems it's [already implemented](https://github.com/rtfd/apitheme/blob/bc22c6d439f1f47832c80fc9a0b7722fc95cf549/apitheme/layout.html#L143) :tada:. But I cant' find any working example, after having searched in several RTD cases.

Should I migrate the issue to the other repo ? Or perhaps you could enlighten me ? Is there any working case using https://schema.org/APIReference that I could look into ?

**Comment by stsewd** [comment]
I haven't used it (I don't even know about that repo), https://github.com/rtfd/apitheme#via-git-or-download those steps are the way to go (you need to copy the apitheme folder inside `docs/_themes/sphinx_rtd_theme`)

**Comment by kael** [comment]
I'm actually looking for an online real case of https://schema.org/APIReference, perhaps there are some RTD already online though. Gonna keep looking. Thanks.

**Comment by strefethen** [comment]
FWIW, here's an example from Google:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fcloud.google.com%2Fdatastore%2Fdocs%2Freference%2Fdata%2Frest%2Fv1%2Fprojects%2FbeginTransaction
