### ISSUE TITLE
Build fails with no error message 

### ISSUE THREAD

**Issue by AndySomogyi** [rtfd/readthedocs.org#4772]
## Details

* Read the Docs project URL: https://mechanica.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): AndySomogyi

## Expected Result
I would expect the build to either succeed, or fail with an error message where I could track down and fit the error. 

## Actual Result

The build initiates a git pull, but stops for no apparent reason with the last ```bit branch -r``` operation. 

*A description of what actually happened*

The build # is 7951390, raw text is here:

```
Read the Docs build information
Build id: 7951390
Project: mechanica
Version: latest
Commit: 376aae18799adbfb09c0f0c16b7849f526c86d94
Date: 2018-10-16T13:27:53.186016
State: finished
Success: False


[rtd-command-info] start-time: 2018-10-16T18:27:57.883991, end-time: 2018-10-16T18:27:57.892780, duration: 0, exit-code: 0
git remote set-url origin https://github.com/AndySomogyi/mechanica.git


[rtd-command-info] start-time: 2018-10-16T18:27:57.985328, end-time: 2018-10-16T18:27:58.148345, duration: 0, exit-code: 0
git fetch --tags --prune


[rtd-command-info] start-time: 2018-10-16T18:27:58.246247, end-time: 2018-10-16T18:27:58.324295, duration: 0, exit-code: 0
git checkout --force origin/master
HEAD is now at 376aae1 updates

[rtd-command-info] start-time: 2018-10-16T18:27:58.552538, end-time: 2018-10-16T18:27:58.561889, duration: 0, exit-code: 0
git clean -d -f -f


[rtd-command-info] start-time: 2018-10-16T18:27:58.710674, end-time: 2018-10-16T18:27:58.719472, duration: 0, exit-code: 0
git branch -r
origin/HEAD -> origin/master
  origin/adj
  origin/facecollapse
  origin/gh-pages
  origin/master
  origin/old-mesh-operations
  origin/polygon
  origin/skeletal
  origin/tmp
```

**Comment by stsewd** [comment]
I guess this is because this submodule doesn't exists https://github.com/AndySomogyi/mechanica/blob/376aae18799adbfb09c0f0c16b7849f526c86d94/.gitmodules#L30

See https://github.com/rtfd/readthedocs.org/issues/4371

**Comment by AndySomogyi** [comment]
Yeah, that fixed it, thanks. 

It would be kind of cool if the build process would give you an error about submodules.

**Comment by stsewd** [comment]
Yeah, we are going to do that on #4371
