### ISSUE TITLE
Builds timeout during cat conf.py

### ISSUE THREAD

**Issue by matt-chan** [rtfd/readthedocs.org#4773]
## Details

Not sure if this is something I'm doing that's causing it to timeout, or if it's something that is RTD-side. All my builds are timing out and there's no meaningful output.

* Read the Docs project URL: https://readthedocs.org/projects/iodata/
* Build URL (if applicable): https://readthedocs.org/projects/iodata/builds/7952133/
* Read the Docs username (if applicable): theochem

## Expected Result

Builds should complete, or give error messages which caused timeout.

## Actual Result

The last printed message is cat conf.py.

**Comment by stsewd** [comment]
This is because conda is very heavy, please try https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html If that doesn't work you can request more build time

**Comment by stsewd** [comment]
And it's probably falling when creating the docs, see https://github.com/rtfd/readthedocs.org/issues/4288

**Comment by humitos** [comment]
@matt-chan do you _really_ need to install all those dependencies to build just the docs? That's one of the most important questions. Are you using `numpy` and `cython` for building the docs? Maybe a simple `requirements.txt` file is enough, or even not needed at all for this docs.

**Comment by matt-chan** [comment]
I got it working. Sorry about that. There was a bug in my conf.py which ended up eating up all the build time. I couldn't see the error though because of #4288. I'll re-open next time if I really time-out.

**Comment by stsewd** [comment]
@matt-chan glad that your docs are building again, can you please tell me what the problem was? Maybe other users are facing the same problem and I can help there.

**Comment by matt-chan** [comment]
The issue was a shell script I was calling from conf.py. I accidentally put a ```make html``` into it. It worked fine locally, but I forgot that RTD calls "make html" itself. It probably was going into an infinite loop.
