### ISSUE TITLE
Sample repos with multilple configs on branches

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4774]
It would be good to have a list of several repositories under GitHub, Bitbucket and GitLab with different branches with different configurations (YAML, no YAML, docker build image, python version, submodules, mkdocs, etc) that all the @rtfd/core have access to them. This way, we can add a new config option and see how it behaves.

This will allow us to trigger builds for all these branches and to know what to expect from those builds.

Currently, each core dev has his own repos, but it would be good to add them under the `rtfd` organization:

* https://gitlab.com/humitos/rtd-yaml-requirement/
* https://gitlab.com/humitos/rtd-project-a
* https://gitlab.com/humitos/rtd-project-b
* https://gitlab.com/humitos/rtd-test-private
* https://gitlab.com/humitos/rtd-test-auto-wipe
* https://github.com/davidfischer/rtd-mkdocs-test/

(some of them could be combined into one repo with multiple branches)

**Comment by davidfischer** [comment]
I moved my MkDocs repo under `rtfd` and everyone in core should have access. https://github.com/rtfd/rtd-mkdocs-test

**Comment by humitos** [comment]
I started this process at https://github.com/rtfd/test-builds. I created the initial structure and I'm going to add some of those branches mentioned there also.

Feel free to include your owns and let me know if you want to discuss the structure.

**Comment by humitos** [comment]
I'm closing this issue since the repository is already created and most of their branches also. There are some cases that can be added in the near future as Bitbucket (with mercurial) repository also.

Although, I'm calling this done and we should continue extending it from the new repo.

**Comment by ericholscher** [comment]
This is super cool. I'd love to see links to each doc version on the README, and also document that this exists somewhere in the .org docs, so that users can perhaps also use them if needed. Another good thing would be to clean up our nagios checks to use repos that we control: https://github.com/rtfd/readthedocs-ops/blob/master/salt/community/nagios/fixtures/rtd-web.yaml -- they break every so often when users change configuration.

**Comment by ericholscher** [comment]
Will make the later an issue in the builds repo

**Comment by humitos** [comment]
> This is super cool. I'd love to see links to each doc version on the README

Done. Check it now.

> and also document that this exists somewhere in the .org docs, so that users can perhaps also use them if needed

I'm not sure that this could be useful for users. I don't have in mind a way to talk about this without making the document confusing for them. Maybe, it could be a NOTE in the developer section somewhere.
