### ISSUE TITLE
Make form for adopting a project a ChoiceField

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#4777]
This is the form for adopting projects for Gold Members.

![screenshot from 2018-10-18 11-29-40](https://user-images.githubusercontent.com/29149191/47134225-9a130f80-d2c9-11e8-8c40-22a3e22dc002.png)

Currently the input field does not specify any idea about what to enter.
Although, the project's slug is need to be enter, but it is written nowhere which creates confusion and the user ends up entering the project's name which gives an error.

This issue was discussed in the comments [#427135794](https://github.com/rtfd/readthedocs.org/pull/4721#issuecomment-427135794), [#427137725](https://github.com/rtfd/readthedocs.org/pull/4721#issuecomment-427137725) and [#427139109](https://github.com/rtfd/readthedocs.org/pull/4721#issuecomment-427139109)

**Comment by dojutsu-user** [comment]
@stsewd Will adding the `help_text` would be enough?

![screenshot from 2018-10-18 12-09-43](https://user-images.githubusercontent.com/29149191/47135702-f7f62600-d2ce-11e8-80cf-156558c4dcd6.png)

**Comment by humitos** [comment]
That field should probably be a `ChoiceField` where the user can only select the available options.

**Comment by dojutsu-user** [comment]
https://github.com/rtfd/readthedocs.org/blob/df85fefc5f59c7a00bcc1ffe23965efe75e8c895/readthedocs/gold/views.py#L108-L110

@humitos from the code, it seems that the user can adopt **any** project.

**Comment by humitos** [comment]
Mmm... OK. It doesn't make too much sense to me, since it's a weird case to want to support a project that you are not involved to.

So, if we want to keep this behavior, my solution of the `ChoiceField` doesn't fit here.

Another different approach, that we don't have in any other place I think, would be to use a field with autocomplete --not sure if we want that, though. Probably, no.

I'd say that for now, the `help_text` is the first step, but it doesn't solve the whole problem anyway.

**Comment by ericholscher** [comment]
I'm +1 on adding it as a ChoiceField -- I think the current implementation wasn't a design decision. If someone needs to adopt a project they don't own, we can handle that as a support issue.

**Comment by dojutsu-user** [comment]
@ericholscher So, can i start working on this?

**Comment by ericholscher** [comment]
Sure!

**Comment by dojutsu-user** [comment]
@ericholscher 
I have made a PR, can you please review it.

**Comment by ericholscher** [comment]
Fixed in #4841
