### ISSUE TITLE
Increase build time for adaptive

### ISSUE THREAD

**Issue by basnijholt** [rtfd/readthedocs.org#4778]
## Details

* Read the Docs project URL:
http://adaptive.readthedocs.org
* Build URL (if applicable):
https://readthedocs.org/projects/adaptive/builds/7963306/
* Read the Docs username (if applicable):
basnijholt

## Expected Result

I hope the whole build will go through.

## Actual Result

Installing the packages takes 380s (from `environment.yml`) + 200s (standard rtd installation) = 580s. This is already almost 10 minutes already.

Building the docs takes about 8 minutes on my machine, so 9 minutes in total isn't enough.

I've seen other issues (https://github.com/rtfd/readthedocs.org/issues/2291) where the build time was increased, so it would be great if we could have some more time too :smile:

Also, I install all packages with `pip` and no extra formats are being built.

**Comment by ericholscher** [comment]
Please reopen if it's still an issue.

**Comment by basnijholt** [comment]
Thanks a lot! 😇

The [documentation is awesome](https://adaptive.readthedocs.io/en/latest/docs.html#examples) now!

**Comment by basnijholt** [comment]
@ericholscher, would it be possible to increase the timeout even more?

For some reason, the building is failing sometimes due to timeouts and other times succeeding. Maybe some of the used servers are slower than others?

**Comment by ericholscher** [comment]
Sure, will do that now.

**Comment by ericholscher** [comment]
I've also moved you to our priority build queue, which runs fewer builds at a time, so hopefully it will be more consistent in timing as well.
