### ISSUE TITLE
New CSS style blocks top half of the page

### ISSUE THREAD

**Issue by earth-tone** [rtfd/readthedocs.org#4786]
Your new CSS has made your service unusable. The top 1-3 paragraphs of the page are no longer visible, depending on screen size.

This is a very simple CSS fix, but when I submitted a [bug report](https://github.com/rtfd/readthedocs.org/issues/4753), I was told it was my fault by employees that appear to be trying to cover their own asses.

It is not my fault. It is a very simple CSS problem that you've introduced in your new styles. The page needs to expand downwards as the menu up top expands. Somewhere, someone inexperienced in CSS has made an alteration to your framework so that this no longer works. 

I've removed my documentation from your site. I'm pretty pissed off about how your employees handled the problem. It's obvious what has happened to anyone that has spent 20 minutes working on a website, and it's not my Markdown or YAML, which have nothing to do with CSS.

**Comment by davidfischer** [comment]
@earth-tone, I'm going to use this time to remind you of the Read the Docs [code of conduct](https://docs.readthedocs.io/en/latest/code-of-conduct.html).

* Please choose your words more carefully and be respectful. Read the Docs is a free service with some full time people and some volunteers but insulting folks is not going to get them to help you with your problem.
* Members of Read the Docs tried to help you and you disagreed with what they said (I believe they are correct FWIW). When you disagreed, you specifically said "are you retarded?". This is unacceptable. Specifically this violates the part of our code of conduct around "be considerate", "be respectful" and "be careful of the words you choose".
* If this behavior continues, we will take further action.

![screen shot 2018-10-21 at 6 55 23 am](https://user-images.githubusercontent.com/185043/47267956-5ace0400-d4ff-11e8-83c4-c5b40ac2ad4f.png)

I'm going to close this issue. If you'd like help, please feel free to open a new issue where you treat Read the Docs contributors and employees with respect.
