### ISSUE TITLE
prevent jQuery from being loaded twice

### ISSUE THREAD

**Issue by basnijholt** [rtfd/readthedocs.org#4787]
## Details

* Read the Docs project URL: http://adaptive.readthedocs.org

## Expected Result

We **have** to load jQuery in the `<head>` [(to show interactive plots)](https://adaptive.readthedocs.io/en/latest/docs.html#examples) which is what we do by having [this in our `conf.py`](https://github.com/python-adaptive/adaptive/blob/master/docs/source/conf.py#L145), a custom [`layout.html`](https://github.com/python-adaptive/adaptive/blob/master/docs/source/_templates/layout.html), and an empty [`_static/jquery.js`](https://github.com/python-adaptive/adaptive/blob/master/docs/source/_static/jquery.js) file that gets loaded at the bottom by default (to prevent loading jquery a second time).

## Actual Result
We overwrite the default [`jquery.js`](https://github.com/python-adaptive/adaptive/blob/master/docs/source/_static/jquery.js), which works in local builds. However, on readthedocs it uses another `jquery` file.

Html of our locally build docs:
```html
        <script type="text/javascript" src="../_static/jquery.js"></script>
        <script type="text/javascript" src="../_static/underscore.js"></script>
        <script type="text/javascript" src="../_static/doctools.js"></script>
```

Readthedocs source `html`:
```html
        <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-2.0.3.min.js"></script>
        <script type="text/javascript" src="https://media.readthedocs.org/javascript/jquery/jquery-migrate-1.2.1.min.js"></script>
        <script type="text/javascript" src="https://media.readthedocs.org/javascript/underscore.js"></script>
```

Because of this `ipywidgets` are not displayed on [adaptive.readthedocs.io](adaptive.readthedocs.io).

How can I change this behavior?

Related: [qt/adaptive/issues/118](https://gitlab.kwant-project.org/qt/adaptive/issues/118)

**Comment by stsewd** [comment]
Maybe related to https://github.com/rtfd/readthedocs.org/issues/3063 and https://github.com/rtfd/readthedocs.org/issues/4367#issuecomment-427889953

**Comment by basnijholt** [comment]
I fixed this issue using this commit https://github.com/python-adaptive/adaptive/commit/6cdd24e9d8f0e8ac4e981a10433acb9d1397690c.

Basically I added this code to my `conf.py`:
```python
def remove_jquery_and_underscore(app):
    # We need to remove the jquery and underscore file that are
    # added by default because we already add it in the <head> tag.
    remove = lambda x: not any(js in x for js in ['jquery', 'underscore'])
    if hasattr(app.builder, 'script_files'):
        app.builder.script_files = [x for x in app.builder.script_files
                                    if remove(x)]

def setup(app):
    app.connect('builder-inited', remove_jquery_and_underscore)
```

**Comment by basnijholt** [comment]
This above solution fixed our problem, but I really consider it a hack.

The proper solution is in https://github.com/rtfd/sphinx_rtd_theme/pull/545.

I will close this issue now. @stsewd thanks for the prompt reply! 😄
