### ISSUE TITLE
URLs in search results have unnecessary (and misleading?) path elements

### ISSUE THREAD

**Issue by joelanders** [rtfd/readthedocs.org#4788]
## Details

Hi, we host some multi-language custom-domain docs on RTD and noticed that the search results link to a kind-of funny URL (which nevertheless returns the correct content).

## Expected Result

Search for something, eg https://docs.deflect.ca/en/latest/search.html?q=deflect&check_keywords=yes&area=default

The results should look like https://docs.deflect.ca/en/latest/deflect_diy/index.html?highlight=deflect

## Actual Result

The results actually look like https://docs.deflect.ca/projects/deflect-docs-russian/en/latest/deflect_diy/index.html?highlight=deflect

We only seem to get this extra `/project/deflect-docs-russian` path on the English version of our docs.

Thanks for your time :)
-Joe

**Comment by stsewd** [comment]
I guess this is because you have https://readthedocs.org/projects/deflect-docs-russian/ as a subproject of https://readthedocs.org/projects/deflect-docs/, but looks like you only wanted it as a translation (which is already included as one). You only need to remove the subproject.

**Comment by joelanders** [comment]
Hi again, thanks for the tip, that does sound like it could be close to our problem. But when I try to view the subprojects of "Deflect Documentation," it says that it is already a subproject of "Deflect Documentation" (and the "view subprojects" link just points to the current page).

<img width="611" alt="deflect-docs" src="https://user-images.githubusercontent.com/1390211/47352818-053e5680-d6bb-11e8-941f-69151932f6f5.png">

I guess I could try deleting the project and recreating it, being careful to get all the settings right again (maybe by screenshotting each page of settings). Does that sound like the best thing to try next?

Thanks again.

**Comment by stsewd** [comment]
Hmm, that's very weird, how long do you have that project created? Maybe in that time the validation wasn't there? If this is recent, it's a bug. Recreating the project sounds like the way to fix this, also, using a configuration file can help for the future (so, not screenshots for backup https://docs.readthedocs.io/en/latest/yaml-config.html)

**Comment by stsewd** [comment]
Hi, were you able to solve the problem?

**Comment by joelanders** [comment]
Hi again, I should let you know that recreating the project solved the issue.

Thanks for your help :)
