### ISSUE TITLE
Disable django.security.DisallowedHost from logging

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4791]
We have properly configured our `ALLOWED_HOST` setting and it's blocking some of these attacks properly. Although, this is spamming Sentry with many error logs.

Since this is not an error and I think we don't really need to take any kind of action, we should disable this from the logging as mentioned here:

https://docs.djangoproject.com/en/1.11/topics/logging/#django-security

Sentry query: https://sentry.io/read-the-docs/readthedocs-org/?query=logger%3A%22django.security.DisallowedHost%22

**Comment by dojutsu-user** [comment]
@humitos 
I would like to work on this issue.
