### ISSUE TITLE
Abandoned project name request

### ISSUE THREAD

**Issue by claresloggett** [rtfd/readthedocs.org#4794]
I'm trying to import my github project https://github.com/claresloggett/ponder into readthedocs and name it "ponder". When I try, I get the error "Invalid project name, a project already exists with that name". However when I go to the corresponding readthedocs site, ponder.readthedocs.io, there is nothing there.

I'm new to readthedocs and don't know how to tell whether this is an error and there is actually no such project, or whether this project does exist but has no files (is that possible?). If the latter is the case I'd like to find out whether it's an abandoned project. I can see that readthedocs has an abandoned project policy but I don't know who to contact if I want to request a name.

Thanks for any help!

## Details

* Read the Docs project URL: N/A - I'm trying to create it. However presumably ponder.readthedocs.io
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): claresloggett

## Expected Result

Import my github project.

## Actual Result

The project name appears to be taken, but there is actual no sign of the project on readthedocs (or if there is, I don't know how to find it).

**Comment by stsewd** [comment]
Hi @claresloggett, the project is https://readthedocs.org/projects/ponder/ it seems abandoned for me.

**Comment by RichardLitt** [comment]
@humitos Can you take a look at this?

**Comment by humitos** [comment]
Hi all! I will start the process for Abandoned Project soon: http://docs.readthedocs.io/en/latest/abandoned-projects.html

**Comment by claresloggett** [comment]
I've renamed this support request as it's now clear the project does exist but looks abandoned.

**Comment by claresloggett** [comment]
Thanks @RichardLitt @humitos  !

**Comment by humitos** [comment]
@claresloggett I sent the email today.

We will wait for the user's response. Otherwise, we will follow our policy in 6 weeks.

Thanks,

**Comment by humitos** [comment]
The email address of the user is unreachable and 

* it's the only contact that we have
* there is no docs built
* the github repo does not exist anymore

so, I decide to go forward with this an release the `ponder` name.

@claresloggett feel free to import your project under that slug.

Thanks

**Comment by claresloggett** [comment]
Thanks very much @humitos!
