### ISSUE TITLE
html output in "Downloads" works, but readthedocs page does not display docstrings

### ISSUE THREAD

**Issue by akdiem** [rtfd/readthedocs.org#4813]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bloodflow/
* Build URL (if applicable): https://bloodflow.readthedocs.io/en/latest/
* Read the Docs username (if applicable): akdiem

## Expected Result

*I changed from using the Alabaster theme to the RTD theme and expect all of the RTD page to look like it. I also expect to see my project docstrings when clicking on the links. I also expect the sidebar links to be expandable.*

## Actual Result

*When downloading the html from the Downloads page and open index.html I get the expected result. However, on the build URL I get the old layout back for most of the links and do not see any of the docstring documentation.*

**Comment by stsewd** [comment]
I just downloaded the docs, and look good for me

![screenshot_2018-10-26 artery fe 0 1 0 documentation](https://user-images.githubusercontent.com/4975310/47574715-d49e2d00-d905-11e8-8af2-8e46e10d0430.png)


But I think what you mean, is that this version is a `singlehtml`, rather than several pages as the ones you see on the web.

**Comment by akdiem** [comment]
Hi, thank you for your response! So you can reproduce exactly what I'm seeing if I understood correctly, i.e. the download looks fine, but the webpage doesn't. How do I fix this? Because on the web none of my docstrings show up on any of the pages.

**Comment by stsewd** [comment]
Actually, I can see the docstrings on the web too 

![screenshot_2018-10-27 arteryfe package artery fe 0 1 0 documentation](https://user-images.githubusercontent.com/4975310/47606376-72622c80-d9d8-11e8-9960-fd8a493b5605.png)

What I mean is that the downloaded page is just one big page and the web is several pages, but the content it's the same (as far as I can tell)

**Comment by akdiem** [comment]
Yes, now the docstrings are visible on the web too. Could this have been an issue with a cached version or something like that? Because when I opened the issue, they definitely weren't.

**Comment by stsewd** [comment]
Yeah, probably just a delay. Can we close this issue, then?

**Comment by akdiem** [comment]
Thank you, yes!
