### ISSUE TITLE
can't browse html offline docuentation

### ISSUE THREAD

**Issue by seguri** [rtfd/readthedocs.org#4815]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/borgbackup/downloads/

## Expected Result

Browse the offline documentation.

## Actual Result

I tested every html zip down to 1.1.3 and none of them loads successfully. `index.html` is stuck in a refresh loop. It still tries to contact external urls like app.travis-ci.org, assets.readthedocs.org, asciinema.org (the video displayed in the home page of borg backup).

**Comment by stsewd** [comment]
For asciinema and travis links, you should open an issue on the borg repo https://github.com/borgbackup/borg.

For the search, we have this open issue https://github.com/rtfd/readthedocs.org/issues/2637 

Thanks for reporting.
