### ISSUE TITLE
Protected privacy level differs between html version and downloads

### ISSUE THREAD

**Issue by ijaureguialzo** [rtfd/readthedocs.org#4816]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/lm-xml-apuntes/
* Build URL (if applicable): https://lm-xml-apuntes.readthedocs.io
* Read the Docs username (if applicable): ijaureguialzo

## Expected Result

When I set the project privacy level to protected, I was expecting any user would be able to download the resulting PDF or ePub clicking on the link.

## Actual Result

* Logged in with my readthedocs user: The file is downloaded properly.
* Not logged in: If I follow the [link to the PDF](
https://readthedocs.org/projects/lm-xml-apuntes/downloads/pdf/latest/) or [ePub](
https://readthedocs.org/projects/lm-xml-apuntes/downloads/epub/latest/), I get a "found a labyrinth" page and no file is downloaded. The html version of the documentation is shown correctly.
* In all cases: If I turn the privacy level to public, everybody can download the file.

Maybe this is the intended behaviour, but then there should be a column for "Downloads" on the [page about Privacy](https://docs.readthedocs.io/en/latest/privacy.html#protected) stating what should I expect to happen, because it differs from the html version.

**Comment by stsewd** [comment]
I think that you are right, the same behavior should be present on the downloads page. Also, we are planning to remove the privacy levels from the community site https://github.com/rtfd/readthedocs.org/issues/4594

**Comment by agjohnson** [comment]
Discussion around privacy levels is happening at #2663, I'll roll this issue in there.
