### ISSUE TITLE
Problems with module import when running RTD inside docker container

### ISSUE THREAD

**Issue by kfrajtak** [rtfd/readthedocs.org#4821]
## Details

I am trying to run RTD inside docker container. I have spent countless hours of trying making it work. I have succeeded once, but then run into python version issue when building the documentation. 

I am using docker-compose file originally based on https://hub.docker.com/r/moul/readthedocs/ and then customized (the base image is now `python:2.7-stretch`).

I believe everything is installed correctly, but then when RTD is started I get 

```
  File "/app/readthedocs/config.py", line 1, in <module>
    from readthedocs.settings.dev import *
ImportError: No module named readthedocs.settings.dev
```

That configuration [file](https://github.com/kfrajtak/rtd_docker/blob/master/config/etc/default/rtd-config.py) is a part of the project and is being added from the host system when the image is built (as `/etc/default/rtd-config.py`) and then copied to app root when installation script is executed 
```
cp -f /etc/default/rtd-config.py $APPDIR/readthedocs/config.py
```

I know this is not an application related issue but more an environment setup issue, but I will greatly appreciate any help.

The project is available [here](https://github.com/kfrajtak/rtd_docker) for anyone willing to help.

Thank you

## Expected Result

I'd like to have it up and running.

## Actual Result

It does not work and the container does not start. I even tried removing that step, but then the app did not launch since configuration settings were empty. 

PS: I have noticed the docker build images, but is there an image just for running RTD?

**Comment by stsewd** [comment]
> PS: I have noticed the docker build images, but is there an image just for running RTD?

No, we don't run the application with docker in production.

**Comment by kfrajtak** [comment]
Please accept my apology, I made a stupid mistake and have been ignoring it in the output (the fileswere not being extracted correctly from the archive).

Now the problem is 
```
  File "/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 129, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
```
and it is driving me crazy :)

**Comment by stsewd** [comment]
@kfrajtak looks like you should change the secret_key setting with something safe. Also, we will be deprecating python 2 very soon.

**Comment by kfrajtak** [comment]
I have fixed the problem! The config file was not loaded. Please, close this issue. Thank you

BTW is there a way how to find out why my build is not working (i.e. log files, etc.)?

Thank you

**Comment by stsewd** [comment]
We save all the output on the db on the Build model, we also do some logging, that should be a django thing to see where the logs are saved.

**Comment by kfrajtak** [comment]
Thank you a lot.
