### ISSUE TITLE
RTD does not respect Numpy pinning in pip-requirements file

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#4822]
## Details

* Read the Docs project URL: https://github.com/astropy/astropy
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/8021231/
* Read the Docs username (if applicable): pllim

## Expected Result

Successful build.

## Actual Result

There is a known compatibility issue between our code and Numpy 1.15.3 (xref astropy/astropy#7943) and to get around that, we pin to `numpy>=1.10.0,<1.15.3` in our `pip-requirements` file, which in turn is called by `pip-requirements-doc`, which is fed into our RTD build.

However, RTD build is still picking up Numpy 1.15.3 despite the pinning, hence fails. I am not sure how to ask RTD to respect the version pinning. Here is what I hope is a relevant snippet from the log (also linked above):

```
python .../astropy/envs/latest/bin/pip install --exists-action=w --cache-dir .../astropy/.cache/pip -r pip-requirements-doc
Collecting numpy<1.15.3,>=1.10.0 (from -r pip-requirements (line 1))
  Using cached https://.../numpy-1.15.2-cp36-cp36m-manylinux1_x86_64.whl

Installing collected packages: numpy, sphinx
  Found existing installation: numpy 1.15.3
    Uninstalling numpy-1.15.3:
      Successfully uninstalled numpy-1.15.3
  Found existing installation: Sphinx 1.7.9
    Uninstalling Sphinx-1.7.9:
      Successfully uninstalled Sphinx-1.7.9
Successfully installed numpy-1.15.2 sphinx-1.6.7

python .../astropy/envs/latest/bin/pip install --ignore-installed --cache-dir .../astropy/.cache/pip .
Processing .../astropy/checkouts/latest
Collecting numpy>=1.13.0 (from astropy==3.2.dev23162)
  Using cached https://.../numpy-1.15.3-cp36-cp36m-manylinux1_x86_64.whl
Installing collected packages: numpy, astropy
  Running setup.py install for astropy: started
    Running setup.py install for astropy: still running...
    Running setup.py install for astropy: still running...
    Running setup.py install for astropy: finished with status 'done'
Successfully installed astropy-3.2.dev23162 numpy-1.15.3
```

Any help would be greatly appreciated. Thank you! (cc @bsipocz )

**Comment by pllim** [comment]
p.s. I just realized that `numpy>=1.13.0` is stated in `setup.py` and is overwriting `pip-requirements` in your build process. Is there a way to ask it to check that Numpy 1.15.2 is already there and therefore no need to install (again)?

**Comment by stsewd** [comment]
So, this is happening because we use the `--ignore-installed` option on pip, any reason to not pin on `setup.py`?.

I don't' think there is a better way right now, I guess changing the installation order would help for this cases (first install the package and then the requirements file), that will be possible with our config file v2.

**Comment by pllim** [comment]
@stsewd , thank you for your response. Yes, we ended up also pinning it in `setup.py` and the build is fixed now. Looking forward to config file v2. Thank you for the great service!
