### ISSUE TITLE
checking out wrong branch name

### ISSUE THREAD

**Issue by ThomasWaldmann** [rtfd/readthedocs.org#4844]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/flatland/
* Build URL (if applicable): https://readthedocs.org/projects/flatland/builds/8034952/
* Read the Docs username (if applicable): thomaswaldmann

## Expected Result

build docs from master branch.

## Actual Result

```
git checkout --force default
error: pathspec 'default' did not match any file(s) known to git. 
```

So it tries to checkout `default` instead of `master`. I  tried changing the branch in the settings, but i can not select `master` and not selecting anything (`------`) does not help either.

**Comment by ThomasWaldmann** [comment]
Note: the project has recently switched from bitbucket/mercurial to github/git, in case that matters.

Building the docs for the `0.8` tag does not work either.

**Comment by ThomasWaldmann** [comment]
I already tried "cleaning" the build environment (as it offers on the rtfd site), did not help either.

**Comment by stsewd** [comment]
I think there was an open issue already for this  (I'm searching now.) Did you try changing the default branch from the advanced settings?

**Comment by ThomasWaldmann** [comment]
Yes, as I said: no `master` there. And not selecting anything (`------`) does obviously **not** choose the VCS default branchname as the help text there says (which would be `master` in case of git). Smells like a bug.

**Comment by stsewd** [comment]
Found the ticket, It was closed recently because it was stale https://github.com/rtfd/readthedocs.org/issues/1170, the current workaround is recreating the project.

**Comment by ThomasWaldmann** [comment]
Yes, deleting and recreating the project solves the problem.

Having to do that sucks, though. It's likely just a form field not getting updated / processed correctly, right?

**Comment by stsewd** [comment]
Ok, I was able to reproduce without having a real mercurial repo, if someone makes a mistake when creating the project and choose the wrong repo type can have this problem.

**Comment by stsewd** [comment]
So, the problem is that we are relying on the `LATEST` slug rather than calling `get_default_branch`, we could update the latest version or change where we are not using `get_default_branch`.

**Comment by ThomasWaldmann** [comment]
"Building the docs for the 0.8 tag does not work either." did you also fix that?

**Comment by stsewd** [comment]
Isn't deployed yet. What I understand, that was referencing to an old version of mercurial, when building from master, the rest of the versions should refresh their versions.
