### ISSUE TITLE
Annotated methods: use the right method signature in RTD

### ISSUE THREAD

**Issue by BlackLight** [rtfd/readthedocs.org#4847]
Problem: My project has docstrings associated to annotated methods. Example: [this plugin action](https://github.com/BlackLight/platypush/blob/master/platypush/plugins/websocket.py#L24) which is actually wrapped by [this decorator](https://github.com/BlackLight/platypush/blob/master/platypush/plugins/__init__.py#L9).

I would expect the signature of the original method to be shown in the RTD documentation generated from the project. In the example above, I would expect RTD to show me a method signature like:

```python
send(self, url, msg, ssl_cert=None, *args, **kwargs)
```

[What I get instead](https://platypush.readthedocs.io/en/latest/platypush/plugins/websocket.html#platypush.plugins.websocket.WebsocketPlugin.send) is:

```python
send(**kwargs)
```

Which means that the signature that gets propagated is the annotation's one, not the signature of the annotated method.

The issue actually applies to the content of the docstring itself as well (i.e. the docstring of the annotation is propagated to RTD, not the one of the annotated method), but at least I've found a workaround for that [by overriding](https://github.com/BlackLight/platypush/blob/master/platypush/plugins/__init__.py#L34) the `__doc__` variable.

However, I haven't found any solution for overriding the signature of the method that is propagated to RTD.

Is this an expected behaviour, a bug or something that can be overridden with a workaround?

**Comment by stsewd** [comment]
When building your docs locally, do you see the same behavior? I don't think this is a rtd issue, I think you need https://docs.python.org/3/library/functools.html#functools.wraps

**Comment by BlackLight** [comment]
Using `functools.wraps` indeed fixes the issue, thanks!
