### ISSUE TITLE
sphinx-argparse: WARNING: Failed to import "func" from "module.submodule"

### ISSUE THREAD

**Issue by paulmueller** [rtfd/readthedocs.org#4855]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nanite/
* Build URL: https://readthedocs.org/projects/nanite/builds/8043996/
* Read the Docs username: paulmueller

## Expected Result

sphinx-argparse correctly documents my CLI.

## Actual Result

I get errors like 

```
/home/docs/checkouts/readthedocs.org/user_builds/nanite/checkouts/latest/docs/sec_cli.rst:19: WARNING: Failed to import "fit_parser" from "nanite.cli.rating"
```
without any explanation why the import failed.

This might be related to one of these things:
 - I am using Python 3.6 on readthedocs
 - #3032
 - sphinx-argparse itself

In any case, a more detailed error message would be helpful.

**Comment by stsewd** [comment]
Did you try this locally? It works? Maybe you need to install using pip? (I think I saw something similar in another issue)

**Comment by paulmueller** [comment]
Yes, locally it works (using pip with --no-site-packages) on Ubuntu 17.10. Not sure what you meant by "installing using pip", but doing this:

https://github.com/AFM-analysis/nanite/commit/3ac1eb9dda8aeb8cebbeabe441a3df0f1b965f0a

does not help:

https://readthedocs.org/projects/nanite/builds/8045730/

**Comment by paulmueller** [comment]
It turns out that I had to mock tkinter and the matplotlib backend in conf.py:
```python
for mod in ["tkinter",
            "matplotlib.backends.backend_tkagg"]:
    sys.modules[mod] = mock.Mock()
```
For some reason, sphinxarg.ext is not very verbose when it comes to failed imports...

I tracked down the error by writing my own argparse extension (https://github.com/AFM-analysis/nanite/commit/7a00bdd8bb0371be89a74fc3862f4690d37491a3) which then gave me detailed error messages on rtd:
- https://readthedocs.org/projects/nanite/builds/8092723/
- https://readthedocs.org/projects/nanite/builds/8092689/

**Comment by stsewd** [comment]
@paulmueller thanks for posting the solution!
