### ISSUE TITLE
New Git tags not showing up in the readthedocs.org Admin interface

### ISSUE THREAD

**Issue by ttmc** [rtfd/readthedocs.org#4858]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bigchaindb-server/
* Build URL (if applicable): NA
* Read the Docs username (if applicable): NA

## Expected Result

We just release the latest version of BigchainDB Server, version 2.0.0b8. Here is the release on GitHub:

https://github.com/bigchaindb/bigchaindb/releases/tag/v2.0.0b8

Like all "releases" on GitHub, it has a Git tag (i.e. a label for the Git commit). In this case, the Git tag is `v2.0.0b8`.

When I go to the Admin interface on readthedocs.org, that tag (`v2.0.0b8`) is expected to show up, for example, in the list of Versions under Admin --> Versions (i.e. at https://readthedocs.org/dashboard/bigchaindb-server/versions/ ).

## Actual Result

The tag `v2.0.0b8` is not listed there. Nor is it an option in the drop-down list at `Admin --> Advanced Settings --> Default branch`

## Notes

This is new. We've been using readthedocs.org for years and this never happened before.

That drop-down list for `Admin --> Advanced Settings --> Default branch` seems new. I seem to recall being able to type anything in there before. Maybe the code introducing that drop-down list broke something?

The same problem happened earlier today when we released a new version of the BigchainDB Python Driver, i.e. this release: 

https://github.com/bigchaindb/bigchaindb-driver/releases/tag/v0.6.2

The associated Git tag (`v0.6.2`) doesn't show up in the BigchainDB Python Driver Admin interface on readthedocs.org.

**Comment by stsewd** [comment]
We have an open issue about this, https://github.com/rtfd/readthedocs.org/issues/4450.

This _problem_ isn't new, you should be able to see your new branches if you trigger a new build on latest (or any other version).

**Comment by ttmc** [comment]
@stsewd Issue #4450 was created in July, but readthedocs.org was working fine (detecting _all_ Git tags, including new ones) until we did our latest releases. We did several releases (new Git tags) since July and were able to update readthedocs.org to tell it to use the new tag... until yesterday.

That's why this seems like something new and different.

**Comment by stsewd** [comment]
RTD has never been able to detect new tags/branches on webhooks. I think you were relying in one of two things:

1) A build to latest or another version was triggered
2) You were able to put anything on the admin interface

RTD currently works like this:

- Clone the repo
- Checkout to the branch
- Sync the versions with the information from the repo that was just cloned.

2) was changed to a select, which means to have the latest versions, rtd needs to the above steps.

Closing as now I can see your new tag no the versions list. Feel free to subscribe to the related issue.
