### ISSUE TITLE
Easier way to add custom CSS

### ISSUE THREAD

**Issue by alexmojaki** [rtfd/readthedocs.org#4860]
[Adding Custom CSS or JavaScript to a Sphinx Project](https://github.com/rtfd/readthedocs.org/blob/f9a839dd4d1c8cf5444006bbdfde283a915d6071/docs/guides/adding-custom-css.rst) describes "The easiest way to add custom stylesheets..." but it seems there's an even easier undocumented way. Sphinx automatically includes a link to `_static/custom.css`, so creating that file is enough without changing `conf.py`. That's what I've done:

- https://github.com/alexmojaki/birdseye/tree/f5f9276b29751a4f5a18212fb2a295be4e0c9440/docs
- https://birdseye.readthedocs.io/en/latest/index.html

**Comment by alexmojaki** [comment]
Should I go ahead and make a PR?

**Comment by RichardLitt** [comment]
I want to ask @humitos or @agjohnson's opinion first.

**Comment by humitos** [comment]
> but it seems there's an even easier undocumented way

@alexmojaki Undocumented by us or by Sphinx?

**Comment by alexmojaki** [comment]
I can't find any documentation for it anywhere. Now that I think of it, maybe it comes from the theme I'm using or something else, and not sphinx itself.

**Comment by humitos** [comment]
What you said about using custom.css sounds familiar to me but I wouldn't suggest to use that feature if it's undocumented from Sphinx because that probably means that it's not officially supported and may change in the near future.

**Comment by agjohnson** [comment]
Also, it might be a Sphinx version-dependent feature. This would also be good to verify if it is a Sphinx feature. We could also make a helper for our theme, but that of course wouldn't be a universal fix.
