### ISSUE TITLE
Warnings on build

### ISSUE THREAD

**Issue by rajdeepbharati** [rtfd/readthedocs.org#4861]
## Details

* Read the Docs project URL: [https://readthedocs.org/](https://readthedocs.org/)
* Build URL (if applicable): [http://127.0.0.1:8000/](http://127.0.0.1:8000/)
* Read the Docs username (if applicable): NA
* When I am building the project, a warning is being shown.

## Expected Result

Guardian authentication backend must be hooked.

## Actual Result

When I am building the database/loading test data/creating superuser/running server;
I'm being shown the following warning:

```
System check identified some issues:

WARNINGS:
?: (guardian.W001) Guardian authentication backend is not hooked. You can add this in settings as eg: `AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend', 'guardian.backends.ObjectPermissionBackend')`.
```
## Notes
* Operating System: macOS Mojave
Do you want me to work on this issue?

**Comment by dojutsu-user** [comment]
@rajdeepbharati 
I don't think RTD is using `django-guardian` as one of AUTHENTICATION_BACKENDS. It is being used for its other functions/classes - `assign`, `get_object_for_user`, `GuardedModelAdmin` (class).
I grepped all the files, searching for `guardian` and I found only these uses of it.

Also, AUTHENTICATION_BACKENDS was introduced during the configuration of `django-allauth` ( [#commit](https://github.com/rtfd/readthedocs.org/commit/9fd05097527735c25b039d543ec3fd71e59517da)), much after the configuration of `django-guardian` (related commits: [#commit1](https://github.com/rtfd/readthedocs.org/commit/29c982994b0ce9421d5f0a396f2c4f44f1b1bba6), [#commit2](https://github.com/rtfd/readthedocs.org/commit/449efcde8a0fa4861d6083d329fa1ca8111812e8))

**Comment by stsewd** [comment]
I think I saw the same warning on production, so this shouldn't be causing any problems.
