### ISSUE TITLE
Remove 'Sphinx Template Changes' subtitle from Design Docs.

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#4862]
Link: https://docs.readthedocs.io/en/latest/design.html

I think **Sphinx Template Changes** subtitle is not required as it provides outdated information.
The path given for the styles of the generated documentation (`readthedocs/templates/sphinx/_static/rtd.css`) is also not present (or outdated).

And, RTD have separated repo for the [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme) whose link is present at the bottom of the same page.

We can also update it, instead of removing, if required.

**Comment by ericholscher** [comment]
Makes sense to me. :+1:

**Comment by dojutsu-user** [comment]
Will make a PR soon.

**Comment by dojutsu-user** [comment]
@ericholscher 
I have made a PR.
Please review it
