### ISSUE TITLE
Remove unused model fields from Project

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4866]
I found that these fields are not used or are deprecated:

https://github.com/rtfd/readthedocs.org/blob/f9a839dd4d1c8cf5444006bbdfde283a915d6071/readthedocs/projects/models.py#L98-L109

https://github.com/rtfd/readthedocs.org/blob/f9a839dd4d1c8cf5444006bbdfde283a915d6071/readthedocs/projects/models.py#L192

https://github.com/rtfd/readthedocs.org/blob/f9a839dd4d1c8cf5444006bbdfde283a915d6071/readthedocs/projects/models.py#L216

https://github.com/rtfd/readthedocs.org/blob/f9a839dd4d1c8cf5444006bbdfde283a915d6071/readthedocs/projects/models.py#L256-L276

These probably can be completely removed. If they are going to be removed, it's needed to check around all the code that they are not using anywhere.

**Comment by dojutsu-user** [comment]
@humitos 
I would like to work on it.
and just to bring it to your notice, RTD is using django-guardian,
So in the `settings/base.py`, one of its configurable variable is deprecated.
https://github.com/rtfd/readthedocs.org/blob/a6120f4e8af7127b887d4058df51805a8cabcf78/readthedocs/settings/base.py#L334
Here is the changelog from django-guardian
https://django-guardian.readthedocs.io/en/stable/develop/changes.html#release-1-4-2-mar-09-2016

**Comment by humitos** [comment]
@dojutsu-user thanks for noticing that. Would you like to propose a PR to upgrade that?

On the other hand, that guardian problem is not related to this issue, isn't it?

**Comment by dojutsu-user** [comment]
@humitos 
no, it isn't related to this issue.
Will submit a PR soon for the things.
