### ISSUE TITLE
Read the docs is not building from the last commit from master (github integration)

### ISSUE THREAD

**Issue by aanm** [rtfd/readthedocs.org#4868]
## Details

Read the docs is not building from the last commit of master

* Read the Docs project URL: https://cilium.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/cilium/builds/8056953/
* Read the Docs username (if applicable): aanm

## Expected Result

Build the documentation from the last commit available on github

## Actual Result

As you can see the last commit being built seems to be one from last month. Every time a new build is scheduled that same commit is used.

**Comment by stsewd** [comment]
The build url is 404  https://readthedocs.org/projects/cilium/builds/8056953/

**Comment by stsewd** [comment]
Also, I can't see a master or latest version on your versions

![screenshot_2018-11-05 versions read the docs 3](https://user-images.githubusercontent.com/4975310/48025115-81e82080-e110-11e8-91c8-e74e14dd96d2.png)

**Comment by aanm** [comment]
@stsewd I can see it, isn't required for an admin to login into RTD to check a build status?

**Comment by aanm** [comment]
@stsewd it's marked as "protected"

**Comment by stsewd** [comment]
I think you have your version as private/protected. Anyway, the problem is because you have a branch named latest https://github.com/cilium/cilium/tree/latest

**Comment by aanm** [comment]
thank you!

**Comment by jbteves** [comment]
I'm actually having the same problem.

Project URL:
https://github.com/jbteves/dcmwrangle
Build URL: https://readthedocs.org/projects/dcmwrangle/builds/10565434/
RTD username: jbteves (integrated with GitHub)
If you look at the build it says successful, it notes that the files are built, but if you "View docs" then it renders an older commit (1e2e94f vs 97b3a19). I can also open a new issue if desired. Unlike the above user, I checked my tree and "latest" 404's, so there shouldn't be a naming collision.
