### ISSUE TITLE
Build failed without any explicit error

### ISSUE THREAD

**Issue by a-sevin** [rtfd/readthedocs.org#4869]
## Details

* Read the Docs project URL: https://shesha.readthedocs.io/en/master/
* Build URL (if applicable): https://readthedocs.org/projects/shesha/builds/8059786/
* Read the Docs username (if applicable):

## Expected Result

Documentation generated

## Actual Result

Build failed without any explicit error

There was a problem with Read the Docs while building your documentation. Please report this to us with your build id (8059786).

**Comment by stsewd** [comment]
I'm guessing this is because of a memory limit issue.

**Comment by a-sevin** [comment]
Thanks for your answers... So I could not use readthedocs build system anymore...

**Comment by stsewd** [comment]
You can, please see https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html and https://github.com/rtfd/readthedocs.org/issues/4573
