### ISSUE TITLE
Version list is most of the time out of date with GitHub

### ISSUE THREAD

**Issue by NyanKiyoshi** [rtfd/readthedocs.org#4877]
## Details
Some times, the RTD versions list is up to date whenever the CI are done confirming everything is good and running correctly. But other times, new branches (versions) don't show up at all, even days after the new branch was pushed.

RTD does receive the webhook events telling it a new branch was pushed. But does not take that into account.

* Read the Docs project URL: https://readthedocs.org/projects/urbanotopus-ny/
* Build URL (if applicable): https://github.com/nyankiyoshi/urbanotopus
* Read the Docs username (if applicable): NyanKiyoshi

## Expected Result
Having the versions updated whenever a webhook event of a new branch created occurs.

Or having a button to refresh the versions (branches).

## Actual Result
Everything stays the same.

**Comment by stsewd** [comment]
Please see https://github.com/rtfd/readthedocs.org/issues/4450
