### ISSUE TITLE
Validate profile fields on form

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4887]
Related code

https://github.com/rtfd/readthedocs.org/blob/164800694a25d769234c6e7019c483f347fe9226/readthedocs/core/forms.py#L20-L46

This will raise an exception if the length is greater than the model

Sentry issue https://sentry.io/read-the-docs/readthedocs-org/issues/666774301/

**Comment by stsewd** [comment]
I guess you are using sqlite, this can be replicated using postgres

**Comment by dojutsu-user** [comment]
@stsewd 
I am unable to set up postgres as of now, but i found from the django documentation that there is a limitation of 30 characters for both first_name and last_name in Django 1.11([reference](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.first_name)).
Also the limit for homepage is set for 100 characters.

**Comment by dojutsu-user** [comment]
@stsewd Can i start working on this?

**Comment by RichardLitt** [comment]
@dojutsu-user If you can craft a PR that seems to make a substantive difference towards resolving this issue, go ahead. You don't need to ask permission for that. We'll review it when we can. If you're asking for more help in figuring out how to resolve this issue, there's no need to ask if you can start working on it - just ask for help. :)
