### ISSUE TITLE
Builds fail with no 'master' branch

### ISSUE THREAD

**Issue by MTecknology** [rtfd/readthedocs.org#4890]
It seems RTD is unable to import/build my project if there is no 'master' branch, even though the default branch is 'develop'. If I create a master branch, builds will start succeeding.

After reading the logs, it looks a lot like the build process has 'master' hard coded into a few places.

* Read the Docs project URL: https://readthedocs.org/projects/gitlight/versions/
* Build URL (if applicable):
  - https://readthedocs.org/projects/gitlight/builds/8084189/
  - https://readthedocs.org/api/v2/build/8084307.txt
* Read the Docs username (if applicable): MTecknology

**Comment by stsewd** [comment]
I believe this should only pass once when first importing the project, rtd doesn't have the versions, it clones the repo, _checkout to master_, and then sync the versions.

That step can be done before the checkout, I think when https://github.com/rtfd/readthedocs.org/issues/4259 is fixed, will cover this case too.

I'll search if this only happens on the first import or in some other places later.

**Comment by MTecknology** [comment]
I tried adding the branch to the project for an initial import and then the docs could build. After deleting the branch, builds stopped working again.

**Comment by stsewd** [comment]
> After deleting the branch, builds stopped working again.

But did you change the default branch to be `develop`? Maybe a build to master was triggered by a webhook? Can you check the webhook responses? (if there is a push to develop, what branches are marked to build)

**Comment by MTecknology** [comment]
I thought I tried that, but I just tried again and it seems to be working. I guess it /is/ the same thing. Thanks!

**Comment by stsewd** [comment]
Well, when the other problem gets fixed, the first build will still fail, but you won't need to create a master branch because there will be another branch (develop) in the list of available versions.
