### ISSUE TITLE
My docs look different / many links break header 

### ISSUE THREAD

**Issue by michaelwittig** [rtfd/readthedocs.org#4893]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/aws-cf-templates/
* Build URL (if applicable):
* Read the Docs username (if applicable): michaelwittig

It looks like the layout / theme changed between mid September and mid October. The new layout has problems if the navigation contains too many links. 

## Expected Result

Before: https://templates.cloudonaut.io/en/v7.4.0/

![screenshot 2018-11-12 at 08 51 52](https://user-images.githubusercontent.com/950078/48333574-3d9cd900-e658-11e8-9632-6ea462a110a2.png)

## Actual Result

After: https://templates.cloudonaut.io/en/v7.5.0/

![screenshot_2018-11-12_at_08_52_00](https://user-images.githubusercontent.com/950078/48333654-83f23800-e658-11e8-8078-4384b4e107d9.png)

**Comment by humitos** [comment]
Mhr, what theme do you want to use? `readthedocs` or `mkdocs` default theme?

If you want `readthedocs` you need to set it in the `mkdocs.yml` file (this is because the default theme picked by RTD changed some time ago to behaves in the same way than building locally).

**Comment by michaelwittig** [comment]
okay. thanks
