### ISSUE TITLE
Cloudflare custom domain does not redirect http to https

### ISSUE THREAD

**Issue by austinhuang0131** [rtfd/readthedocs.org#4907]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/discordtel/
* Build URL (if applicable):
* Read the Docs username (if applicable): austinhuang

I have `Always use HTTPS` on for domain `discordtel.austinhuang.me`. Do note that my domain is under Cloudflare.

Cloudflare record: ![screen shot 2018-11-15 at 9 41 38 pm](https://user-images.githubusercontent.com/16656689/48594646-61457500-e91f-11e8-9c99-607a10b5e4ef.png)

Setting: 
![screen shot 2018-11-15 at 9 43 21 pm](https://user-images.githubusercontent.com/16656689/48594672-833ef780-e91f-11e8-8c2a-6291428fbe8d.png)

## Expected Result

http://discordtel.austinhuang.me should redirect to https

## Actual Result

It remains http

(https://discordtel.austinhuang.me is accessible)

**Comment by stsewd** [comment]
Please see https://github.com/rtfd/readthedocs.org/issues/4641. You can read for more background https://github.com/rtfd/readthedocs.org/issues/3938#issuecomment-419229337
