### ISSUE TITLE
Search index is not updated for sub-projects

### ISSUE THREAD

**Issue by csadorf** [rtfd/readthedocs.org#4908]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/signac/
* Build URL (if applicable):
* Read the Docs username (if applicable): csadorf

This RTD page has sub projects.

## Expected Result

The search index is reindexed whenever the main or any of the sub-projects is updated.

## Actual Result

Search results lead to dead links, for example, the results for the following search:

 * http://docs.signac.io/en/latest/search.html?q=read+only&check_keywords=yes&area=default

leads to dead links, such as:

* https://docs.signac.io/projects/core/en/latest/collections.html?highlight=read%20only

**Comment by michaeldboyd** [comment]
+1, I also can here today to post this

**Comment by bdice** [comment]
The docs still have this issue -- we haven't gotten a response from the RTD team via this issue or via email. Hoping for some community guidance.

**Comment by humitos** [comment]
I just triage the issue. Following your links I can see it's a bug in our side.

We have a lot of work done in our search backend but we had some problems deploying it. This issue may be automatically fixed once these changes get deployed.

**Comment by safwanrahman** [comment]
Thanks for the issue. We have recently deployed our new search backend.
It seems like the new backend solves the issue you have mentioned.

So I am closing the issue. Please feel free to open the issue if the bug still exists.
