### ISSUE TITLE
AutoDocs not being generated

### ISSUE THREAD

**Issue by HarryShomer** [rtfd/readthedocs.org#4913]
## Details

* Project URL: https://readthedocs.org/projects/hockey-scraper/
* Build URL: https://readthedocs.org/projects/hockey-scraper/builds/8116770/
* Username: harryshomer

## Expected Result

I expected it to generate the documentation for the docstrings. 

## Actual Result

They aren't generated and are just blank. This is something that works locally on my machine but isn't here. The build is also not generating an errors.

**Comment by stsewd** [comment]
Hi, can you point me out what pages aren't showing the docstrings?

**Comment by HarryShomer** [comment]
These two: [One](https://hockey-scraper.readthedocs.io/en/latest/live_scrape.html) and [two](https://hockey-scraper.readthedocs.io/en/latest/scrape_functions.html). 

For both the docstrings should be at the bottom under the headers.

**Comment by stsewd** [comment]
I can see that there are some errors on the install and build steps

```
File "/home/docs/checkouts/readthedocs.org/user_builds/hockey-scraper/envs/latest/lib/python3.5/site-packages/hockey_scraper-1.2.8-py3.5.egg/hockey_scraper/live_scrape.py", line 98
    print(f"The LiveGame object for game {game_id} has been created. "
                                                                     ^
SyntaxError: invalid syntax
```

Looks like you need python3.6, you need to use a configuration file to have python3.6 support https://docs.readthedocs.io/en/latest/yaml-config.html

**Comment by HarryShomer** [comment]
Yep, that's it. Thank you for your help!
