### ISSUE TITLE
Build fails without error message 

### ISSUE THREAD

**Issue by simonvh** [rtfd/readthedocs.org#4916]
## Details

* Read the Docs project URL: https://gimmemotifs.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/gimmemotifs/builds/8123114/
* Read the Docs username (if applicable): simonvh

## Expected Result

A finished build or an error message.

## Actual Result

The build fails after `git branch -r`, but I can't see any error.

**Comment by stsewd** [comment]
I tested it locally, it's failing in the conda env creation

**Comment by stsewd** [comment]
And looks like your latest builds are passing now

**Comment by simonvh** [comment]
Thanks for testing! I simplified the conda environment, seems like that was the issue (somehow?). Not sure if the underlying issue is resolved, but it's fixed for me. I'll close the issue. Thanks again for looking at it.

**Comment by stsewd** [comment]
Yeah, it could be, conda is very heavy in resources (memory or time), some builds are killed because of that.
