### ISSUE TITLE
Function annotation support

### ISSUE THREAD

**Issue by pkovacs19** [rtfd/readthedocs.org#4921]
## Details

* Read the Docs project URL: https://gitlab.com/energyincities/EPlusGA/tree/docs
* Build URL (if applicable): https://eplusga.readthedocs.io/en/latest/
* Read the Docs username (if applicable): pkovacs

Hello, I am having a similar issue to issue  #2919 (pep484 type annotation support at readthedocs.org).  My docs can build just fine locally when I run "make html" command in sphinx.  My readthedocs build completes, but I receive this error during the build process:

`WARNING: autodoc: failed to import module 'evaluator'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/eplusga/envs/latest/lib/python3.6/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/eplusga/checkouts/latest/eplus_ga/evaluator.py", line 14, in <module>
    from problem import Problem
  File "/home/docs/checkouts/readthedocs.org/user_builds/eplusga/checkouts/latest/eplus_ga/problem.py", line 13, in <module>
    class Problem:
  File "/home/docs/checkouts/readthedocs.org/user_builds/eplusga/checkouts/latest/eplus_ga/problem.py", line 139, in Problem
    def to_platypus(self) -> platypus.Problem:
AttributeError: module 'platypus' has no attribute 'Problem'`

The solution in the issue #2919 was to build the env with python 3.6.  I have done that but does not resolve my issue.  I have added a readthedocs.yml file at the root directory of the project.  My yml file looks like:

`requirements_file: docs/requirements.txt

build:
  image: latest

python:
  version: 3.6`

Any help would be greatly appreciated.

## Expected Result

The documentation to generate in readthedocs

## Actual 

Build completes, but the documentation does not generate.

**Comment by stsewd** [comment]
Sphinx is reading the annotations, the problem happens here `AttributeError: module 'platypus' has no attribute 'Problem'`. https://gitlab.com/energyincities/EPlusGA/blob/docs/eplus_ga/problem.py#L139

The module `platypus` doesn't have a `Problem` class, maybe you have another version installed locally?

**Comment by pkovacs19** [comment]
Thanks for your reply, stsewd.  You were right, I've updated my requirements.txt file to have the proper platypus version installed.   Sorry for the newbie question!  

Thanks for your help!

**Comment by RichardLitt** [comment]
@pkovacs19 We're all new at some point, and someone else may find this issue helpful. Don't worry about it! Thanks for logging the issue :)
