### ISSUE TITLE
Config value: 'pages'. Error: Invalid pages config

### ISSUE THREAD

**Issue by Aazhar** [rtfd/readthedocs.org#4923]
## Details

* Read the Docs project URL: anhalytics.rtfd.io
* Build URL (if applicable): https://readthedocs.org/projects/anhalytics/builds/8150298/
* Read the Docs username (if applicable): 

## Expected Result

To be built successfully

## Actual Result
WARNING -  Config value: 'include_search'. Warning: Unrecognised configuration name: include_search 
ERROR   -  Config value: 'pages'. Error: Invalid pages config. set([<type 'list'>]) set([<type 'dict'>, <type 'unicode'>]) 

Aborted with 1 Configuration Errors!

**Comment by stsewd** [comment]
Read the Docs installs `mkdocs=0.17.3` by default, I guess you are using another version locally, you can use a `requirements.txt` file to install another version https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

**Comment by Aazhar** [comment]
I am using readthedocs build online, here you can see it : https://readthedocs.org/projects/anhalytics/builds/8150298/

**Comment by stsewd** [comment]
Yes, and rtd installs `mkdocs=0.17.3` by default, and you are using a configuration that is only supported in another mkdocs version, to rtd installs the version of mkdocs that your config uses, you need to create a `requirements.txt` file with the correct mkdocs version

**Comment by Aazhar** [comment]
Ok thank you for helping
