### ISSUE TITLE
The docs are not updated

### ISSUE THREAD

**Issue by sergibondarenko** [rtfd/readthedocs.org#4926]
## Details

* Read the Docs project URL: https://sentinl.readthedocs.io/en/latest/
* Build URL (if applicable):https://readthedocs.org/projects/sentinl/builds/8152458/
* Read the Docs username (if applicable): sergibondarenko

## Expected Result
The docs are updated.

*A description of what you wanted to happen*
I want to update the docs. Here is the source https://github.com/sirensolutions/sentinl/tree/master/docs and 
mkdocs.yml https://github.com/sirensolutions/sentinl/blob/master/mkdocs.yml

## Actual Result
The docs are not updated.

*A description of what actually happened*
The build is successful but I don't see the docs updated.

**Comment by stsewd** [comment]
Which docs aren't up to date? I can see that the last change (howto) are here https://sentinl.readthedocs.io/en/latest/HOWTO-Alerts-in-Dashboard/

**Comment by sergibondarenko** [comment]
Why don't I see the changes here? And why there are 2 different formats?
![screenshot from 2018-11-26 18-41-49](https://user-images.githubusercontent.com/5389745/49031687-f90e5300-f1aa-11e8-9728-b9ad881559bd.png)

**Comment by sergibondarenko** [comment]
Click Wizard
![screenshot from 2018-11-26 18-42-51](https://user-images.githubusercontent.com/5389745/49031742-1f33f300-f1ab-11e8-8b01-c3a8d94d3278.png)
And you see this
![screenshot from 2018-11-26 18-43-22](https://user-images.githubusercontent.com/5389745/49031757-2d820f00-f1ab-11e8-8bc5-31d04af8a922.png)
But original doc is https://github.com/sirensolutions/sentinl/blob/master/docs/Watcher-Wizard.md

**Comment by stsewd** [comment]
I'm seeing the correct docs on rtd 
![screenshot_2018-11-26 sentinl docs](https://user-images.githubusercontent.com/4975310/49031899-3954dd80-f179-11e8-95af-0c16cd1a93e4.png)

![screenshot_2018-11-26 wizard - sentinl docs](https://user-images.githubusercontent.com/4975310/49031915-4376dc00-f179-11e8-8af0-a986802039fd.png)

I'm guessing this is bc of cache in your browser or ISP (you can refresh the browser cache with ctrl+f5).

> And why are there 2 different doc formats?

Previously we were using the rtd theme as default if the users don't had one, but now were are building with the same config from `mkdocs.yml`, so if you don't have a theme, mkdocs will put one by default. See https://www.mkdocs.org/user-guide/styling-your-docs/

**Comment by sergibondarenko** [comment]
Yeah, you are right, it was cache. I cleared it and now I see correct docs. Thank you.
