### ISSUE TITLE
vrv.js.org SSL On Cloudflare Problem

### ISSUE THREAD

**Issue by stampylongr** [rtfd/readthedocs.org#4930]
## Details

* Read the Docs project URL: https://vrv.js.org
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result
The expected result, in this case, is that the domain should be using an SSL certificate from js.org, but instead, it's Cloudflare settings is being managed by Read The Docs. Is there any way to fix this?
More details here (as I'm terrible at explaining things): https://github.com/js-org/js.org/pull/2557#issuecomment-442183620

## Actual Result

*A description of what actually happened*

**Comment by davidfischer** [comment]
There are a couple of mistakes in your setup of a custom domain on Read the Docs. Here's [our documentation for your reference](https://docs.readthedocs.io/en/latest/custom_domains.html?highlight=domains#custom-domain-ssl).

Firstly, our documentation says to point your CNAME to `readthedocs.io`, not to `<slug>.readthedocs.io`.

    $ dig CNAME +short vrv.js.org
    vrvjs.readthedocs.io.   # this should be just readthedocs.io

However, if you are proxying your connection through cloudflare (the orange cloudflare cloud in their UI) then you *must* point to `cloudflare-to-cloudflare.readthedocs.io`. If you are using cloudflare for DNS only, I believe this is not necessary.

Fundamentally it comes down to who is doing SSL termination and if you want any pagerules on your side. If you want Read the Docs to do the termination, then update your CNAME to `readthedocs.io` and remove any proxying through Cloudflare. In this case, you can't have any pagerules. If you want your Cloudflare setup to handle SSL termination and pagerules, then change your CNAME to `cloudflare-to-cloudflare.readthedocs.io`.

**Comment by stampylongr** [comment]
OK, thank you for clearing this up. I will be closing this now.

**Comment by davidfischer** [comment]
Feel free to re-open it if you can't get it working.
