### ISSUE TITLE
Don't allow to connect services of the same type

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4932]
Currently users can connect several accounts of the same provider (or at least the ui show that), this doesn't make much sense. We should remove/block the buttons and check that we can register only one account per provider.

![screenshot_2018-11-28 connected services read the docs](https://user-images.githubusercontent.com/4975310/49176080-0e54c000-f318-11e8-97c1-e11ad3dd919b.png)

note: I'm not sure what would happen if I try to connect with another account

**Comment by stsewd** [comment]
So, this comes from allauth

https://github.com/pennersr/django-allauth/blob/master/allauth/templates/socialaccount/snippets/provider_list.html

Actually, we override that template https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/socialaccount/snippets/provider_list.html

Also, looks like we don't have css for a disabled button, I created one

![screenshot_2018-12-13 connected services read the docs](https://user-images.githubusercontent.com/4975310/49970125-5e2aae00-fef8-11e8-9e7c-a7775cffda37.png)

Still need to figure out how to filter the connected services.

**Comment by stsewd** [comment]
Ok, figureout how to do this, I have to use a templatetag.

![screenshot_2018-12-13 connected services read the docs 1](https://user-images.githubusercontent.com/4975310/49978115-fe8fcb00-ff16-11e8-98f1-66b79388519a.png)

Still not sure if we want this, and I haven't test what happens when integrating accounts of the same service. The docs are not clear about that https://django-allauth.readthedocs.io/en/latest/overview.html#supported-flows I guess they allow it, in that case we may need to use a custom form? https://django-allauth.readthedocs.io/en/latest/forms.html or maybe just deal with the ui for now.

**Comment by agjohnson** [comment]
Is there a reason we want to block users with multiple connections? I'd guess that this is probably not a serious problem and we could probably better address this by altering the query in #4818.

**Comment by stsewd** [comment]
So, yeah, this isn't a serious problem, but it just feels weird to have two GitHub accounts linked to one rtd account :). We can close this, or wait to have some option from allauth

**Comment by agjohnson** [comment]
I think most CI/CD services allow connecting multiple accounts, so perhaps it's better to keep this functionality. Removing multiple accounts as a feature for new users seems a little like throwing the baby out with the bath water, so I do lean towards a more direct approach for the bugs we're noticing around detecting the oauth source.

**Comment by stsewd** [comment]
I'm going to close this, we could revisit if there is an update from alloauth side.
