### ISSUE TITLE
Remove trailing slashes on svn checkout

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4934]
If someone enters an svn repo like `https://svn.code.sf.net/p/docutils/code/`, it would be concatenated with the version `/trunk/`, so we ended up with `https://svn.code.sf.net/p/docutils/code//trunk`

Related code

https://github.com/rtfd/readthedocs.org/blob/7f2b831ac18ee839535254e9b14e595621ebf653/readthedocs/vcs_support/backends/svn.py#L61

**Comment by dojutsu-user** [comment]
@stsewd 
Working on it.

**Comment by humitos** [comment]
Is this a problem when checking out? I don't think so. Does this cause any other issue?

**Comment by stsewd** [comment]
@humitos I don't think so, but at the same time I'm not so familiar with svn p: but when testing yesterday, it didn't fail.

**Comment by stsewd** [comment]
I think so, it feels weird for the user to see `//` in the URL.
