### ISSUE TITLE
Validate tags > 100 characteres

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4935]
Not sure how to do this validation yet, the best option is that django-taggit to handle that.

Related issue https://github.com/alex/django-taggit/issues/510

Sentry issue https://sentry.io/read-the-docs/readthedocs-org/issues/661257950/

**Comment by humitos** [comment]
We should probably add a `clean_tags` method in this form

https://github.com/rtfd/readthedocs.org/blob/7f2b831ac18ee839535254e9b14e595621ebf653/readthedocs/projects/forms.py#L164

This is low priority though since it only breaks with spam projects.

**Comment by dojutsu-user** [comment]
@humitos 
Thanks for guiding to the code.
@stsewd 
Will submit a PR soon.

**Comment by dojutsu-user** [comment]
This is to inform you.
Stack Trace/Error Log cannot be seen by all the people with the given Sentry link.
It requires to log in into the RTD.

**Comment by stsewd** [comment]
Yes I know, it can be only seen by the core team, it may contain secrets.
