### ISSUE TITLE
build often time out

### ISSUE THREAD

**Issue by lucays** [rtfd/readthedocs.org#4936]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/ocg-rule/
* Build URL (if applicable):https://readthedocs.org/projects/ocg-rule/builds/8169721/
* Read the Docs username (if applicable):碎冰

## Expected Result

build pass

## Actual Result

often time out

the issue happend  2 days ago when  I try to change sphinx theme.
all worked well before.

I have read some related issues, I found if dont output pdf/epub, then works.(disable htmlzip dont work)
but I really need pdf/epub, it's very nice. I dont know what happened, even rollback codes, still cant work.
html build just takes less then 1 min. then no logs and after 900s, time out.
wipe build envrioment also dont work.
Fortunately, several times it build pass(such as [this](https://readthedocs.org/projects/ocg-rule/builds/8164002/)), takes 5 minutes, so I think 900s is enough for me.

Why sometimes it build pass?What happened? How to fix?
if I delete project, can I start same name project again?
Sorry for my English.

**Comment by stsewd** [comment]
> disable htmlzip dont work

What do you mean? I think `htmlzip` is the one that consumes a lot of time/memory, probably you can still keep pdf/epub. Also, you can check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by lucays** [comment]
> > disable htmlzip dont work
> 
> What do you mean? I think `htmlzip` is the one that consumes a lot of time/memory, probably you can still keep pdf/epub. Also, you can check https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

I tried [#2274](https://github.com/rtfd/readthedocs.org/issues/2274#issuecomment-397729907), disable it, but still dont work.
900s should be enough for me, before 2 days it takes only 1 min~3 minutes.

**Comment by stsewd** [comment]
your latest builds are still building `htmlzip`.

**Comment by lucays** [comment]
yes I tried it in the morning, such as [this](https://readthedocs.org/projects/ocg-rule/builds/8166289/) and [this](https://readthedocs.org/projects/ocg-rule/builds/8164039/), then I delete the yml...
now I tried again:https://readthedocs.org/projects/ocg-rule/builds/8170194/

**Comment by lucays** [comment]
> your latest builds are still building `htmlzip`.

I tried again and it still dont work: :https://readthedocs.org/projects/ocg-rule/builds/8170194/
it's strange...

**Comment by stsewd** [comment]
> the issue happend 2 days ago when I try to change sphinx theme.

Are you still using the different theme? Maybe that's why is taking so much time to build pdf/epub formats

**Comment by lucays** [comment]
> > the issue happend 2 days ago when I try to change sphinx theme.
> 
> Are you still using the different theme? Maybe that's why is taking so much time to build pdf/epub formats

after I find this issue, I rollback codes, but still dont work.
now latest version dont use other theme.

**Comment by stsewd** [comment]
Maybe a cache thing? Can you try wiping the env before building again? (Versions -> Edit -> Wipe)

**Comment by lucays** [comment]
today(in China) build 4 times, once pass, other time out(pdf fail twice, output pdf, epub fail once)
just depend on luck...?

**Comment by lucays** [comment]
fix some rst syntax warning then seem it works.

**Comment by RichardLitt** [comment]
Glad it worked, @lucays. Thanks for following up.
