### ISSUE TITLE
Build fails because of memory limits

### ISSUE THREAD

**Issue by mdraw** [rtfd/readthedocs.org#4942]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/elektronn3/
* Build URL (if applicable): https://readthedocs.org/projects/elektronn3/builds/8181031/
* Read the Docs username (if applicable): mdraw

## Expected Result

Documentation builds

## Actual Result

Build fails with "There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8181031).".

Documentation builds of https://elektronn3.readthedocs.io/en/latest/ have been failing for about a month now. Wiping doesn't help and I don't know how to find out what the issue is. The first commit on which the automatic build has started to fail was this one: https://github.com/ELEKTRONN/elektronn3/commit/337fba1529f51bfef4a009e0e99a760197de2145 but I don't see how this could have caused an issue.
The project is configured to be built with conda, see https://github.com/ELEKTRONN/elektronn3/blob/master/.readthedocs.yml.

**Comment by stsewd** [comment]
It fails when creating the conda environment `conda env create --name latest --file docs/sphinx-environment.yml`, I can't see any more details, you may want to try that command locally and see if it fails locally too.

**Comment by mdraw** [comment]
Thanks for the info. `conda env create --name latest --file docs/sphinx-environment.yml` works fine on my machine, but I noticed that `conda-env` consumes up to 460 MB of RAM while resolving dependencies. Could it be that the process is killed due to excessive memory consumption?

**Comment by mdraw** [comment]
I'll assume that excessive memory usage is the problem. I just found https://github.com/conda/conda/issues/5003 and apparently there are no plans to fix this issue on conda's side. https://github.com/rtfd/readthedocs.org/blob/master/docs/guides/build-using-too-many-resources.rst#use-pip-when-possible recommends to pip if possible, so I guess I'll give pip another chance.

**Comment by mdraw** [comment]
Well, that didn't help a lot :(

**Comment by stsewd** [comment]
You are using `use_system_site_packages: true`, which mean you already have some libs installed, you can check what libs are installed here https://docs.readthedocs.io/en/latest/builds.html#the-build-environment

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/issues/4942#issuecomment-444130442 what I mean with that is that you can skip the installation of some libs, that can help with the timeout

**Comment by mdraw** [comment]
@stsewd I have set `use_system_site_packages: true` as an attempt to make installation less resource intensive. Neither setting it to `true` nor `false` fixes the problem for me. I have tried to keep dependencies at a minimum, but most of them really are necessary.

@humitos I have tried mocking some large dependencies with http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports and skipping their installation, but mocking dependencies destroys a lot of auto-generated documentation content, especially type information, in my local `sphinx-build` tests.
Yes, I need to install my package to build the docs correctly.

I understand that readthedocs has limited resources and I don't want to cause any trouble with too resource-intensive automatic builds. If there is no good solution for this problem, I will look into building the docs locally (which works fine on my machine) and uploading them manually.

**Comment by stsewd** [comment]
If you still need more resources for your project let us know, so the team can see the possibility to give more resources for your project.

**Comment by mdraw** [comment]
@stsewd If it is possible to provide more memory for the documentation build, that would indeed be very helpful for the elektronn3 project. Do I need to apply for this somewhere?

**Comment by humitos** [comment]
The build fails when installing `torch` that it's `~600Mb`. I'm not sure what `pip` is doing there, but I had to double the memory set by default.

```
Collecting torch>=1.0.0 (from elektronn3==0.0.0)
  Downloading https://files.pythonhosted.org/packages/31/ca/dd2c64f8ab5e7985c4af6e62da933849293906edcdb70dac679c93477733/torch-1.0.1.post2-cp36-cp36m-manylinux1_x86_64.whl (582.5MB)
Killed
```

Elektronn3 is building now. This is the last build that I triggered: https://readthedocs.org/projects/elektronn3/builds/8695023/

Let me know if anything.

**Comment by mdraw** [comment]
Thank you so much for the help! I don't understand what is happening in the
`pip install -r docs/sphinx-requirements.txt` step. Its output claims that
`Requirement already satisfied: torch==1.0.0 from https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl in /home/docs/checkouts/readthedocs.org/user_builds/elektronn3/envs/latest/lib/python3.6/site-packages (from -r docs/sphinx-requirements.txt (line 4)) (1.0.0)` and gives similar messages for all the other packages, although to my understanding at this point none of the dependencies are actually installed yet. In my `sphinx-requirements.txt` I specify the much more lightweight cpu-only wheel of PyTorch, which should normally fix the high memory usage.
The actual `pip install .` phase then doesn't find the packages that should have been installed via `sphinx-requirements.txt` and downloads the "full" versions of the dependencies as specified in `setup.py`.

As a workaround, I could dynamically try to detect a readthedocs build vm in `setup.py` and change the `torch` dependency in the `install_requires` section of my `setup.py` to point to the small cpu-only wheel of PyTorch.

**Comment by mdraw** [comment]
I've just tried changing some stuff in the readthedocs configuration file to see if I can get the requirements installation to work as intended (without any 600MB wheels...) and to make it work again in a normal memory-constrained builder.
Strangely, the first build with this worked fine (https://readthedocs.org/projects/elektronn3/builds/8720636/) but a subsequent build that didn't change anything about the configuration failed again with a memory consumption error and the same broken requirement installation: https://readthedocs.org/projects/elektronn3/builds/8720799/. Like before, wiping and rebuilding didn't help here either.

Did I accidentally remove the increased memory limit by switching the builder image?

**Comment by stsewd** [comment]
No, sometimes the builders are too busy, and sometimes we don't have so much load.

**Comment by humitos** [comment]
@mdraw do you _realy_ need `torch` to build your docs or [you can mock it](https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules) and have render the documentation anyways?

Or, using autodoc and mock it?: http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports

**Comment by mdraw** [comment]
As I mentioned in my comment earlier (https://github.com/rtfd/readthedocs.org/issues/4942#issuecomment-449163335) I've tried mocking `torch` but this breaks the docstrings, because they make use of types like `torch.Tensor` a lot. E.g. `torch.nn.Module` is rendered as "sphinx.ext.autodoc.importer._MockObject" and `torch.Tensor` is rendered as "<sphinx.ext.autodoc.importer._MockObject object at 0x7f0043fd0b70>]" in the documentation when mocking `torch`. Type information is very important for elektronn3, so I want to avoid messing it up.

Besides that, I think even mocking it wouldn't solve the current installation issue because the actual issue is that my `docs/sphinx-requirements.txt` is not processed correctly by the readthedocs builder and it just installs the packages defined in `setup.py`.

**Comment by kiran-kate** [comment]
@mdraw, I see that your project still has this problem. Does that mean there is no solution? We are facing the same issue and the mock_imports didn't work for me.

**Comment by mdraw** [comment]
@kiran-kate sorry for the late reply and thanks for asking. Actually by forcing sphinx 2.2 and making some changes to my setup.py I've finally managed to fix this problem (see https://github.com/ELEKTRONN/elektronn3/commit/a3555340b29050e80ee3f8307cf194f3b7f00f55 and https://github.com/ELEKTRONN/elektronn3/commit/69e2e003e3e627371fe74c14db5be1840fb3e541). Documentation builds are now very fast and seem to work quite reliably now.

**Comment by kiran-kate** [comment]
Thank you so much @mdraw, the trick worked for me too. It doesn't fail at installing pytorch now, but it is not generating docs for all the modules now. It is possible that my rtd requirements.txt does not have all the required packages since I didn't copy extra dependencies there, but was wondering if there is a way to check the exact log to see which imports might be failing.

**Comment by stsewd** [comment]
> Thank you so much @mdraw, the trick worked for me too. It doesn't fail at installing pytorch now, but it is not generating docs for all the modules now. It is possible that my rtd requirements.txt does not have all the required packages since I didn't copy extra dependencies there, but was wondering if there is a way to check the exact log to see which imports might be failing.

Yes, you can. You can see this in the build page, if you click over the sphinx-build step you can see if there is any warnings about missing imports

**Comment by kiran-kate** [comment]
Thank you @stsewd for such a prompt help. I found the problem and fixed it. So rtd works for my project too now, with the trick in setup.py to check for the environment variable READTHEDOCS and not install pytorch and including it as autodoc_mock_imports in conf.py instead. Thank you @mdraw for the exact details again.
