### ISSUE TITLE
[Markdown] Trailing # is stripped in title

### ISSUE THREAD

**Issue by thomaslevesque** [rtfd/readthedocs.org#4943]
## Details

* Read the Docs project URL: https://fakeiteasy.readthedocs.io/en/stable/raising-events/#from-c
* Build URL (if applicable): https://readthedocs.org/projects/fakeiteasy/builds/8180106/
* Read the Docs username (if applicable): thomaslevesque

## Expected Result

For this markdown title:

```markdown
### From C#
```

I expected it to be rendered like this:

> ### From C#

## Actual Result

It's rendered without the final `#`:

> ### From C

**Comment by RichardLitt** [comment]
I think this may be an mkdocs issue, not a ReadTheDocs issue.

**Comment by RichardLitt** [comment]
Great. Thanks. :)
