### ISSUE TITLE
Pip install doesn't use editable option.

### ISSUE THREAD

**Issue by coady** [rtfd/readthedocs.org#4944]
## Details
The [yaml config documentation](https://docs.readthedocs.io/en/latest/yaml-config.html) states that `pip install` is run in editable mode:

## Expected Result
> Behind the scene the following Pip command will be run:
> 
> $ pip install -e .[tests,docs]

## Actual Result
But it doesn't use the `-e` option.  This can break builds which rely on setting a relative path in `docs/conf.py`.

**Comment by humitos** [comment]
You are right.

I think we should remove the `-e` from the documentation.

>  This can break builds which rely on setting a relative path in `docs/conf.py`.

This doesn't sound like a good way to configure the project to me.

**Comment by coady** [comment]
> > This can break builds which rely on setting a relative path in `docs/conf.py`.
> 
> This doesn't sound like a good way to configure the project to me.

Well sphinx actually encourages it, particularly with autodoc.  From its default conf.py:
```
# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

```

**Comment by stsewd** [comment]
I don't see any mention of installing the package in dev mode when modifying the path.

**Comment by monsij** [comment]
Is a PR still required @coady

**Comment by stsewd** [comment]
@monsij yes, it is.

**Comment by monsij** [comment]
Could you describe what is to be done ? `-e` removal ..anything else?

**Comment by stsewd** [comment]
Just that https://github.com/rtfd/readthedocs.org/issues/4944#issuecomment-443633361

**Comment by dojutsu-user** [comment]
@monsij 
Are you working on this?
If not, I would like to send a PR.

**Comment by monsij** [comment]
Yeah,i've started to work. Anyways you can continue. I'll find another :-) @dojutsu-user

**Comment by dojutsu-user** [comment]
@monsij 
I was about to start the work.
You can continue and make a PR.
