### ISSUE TITLE
Documentation not accessible in Russia without VPN

### ISSUE THREAD

**Issue by strophy** [rtfd/readthedocs.org#4945]
## Details

* Read the Docs project URL: http://docs.dash.org
* Read the Docs project IP: 165.227.0.140
* Read the Docs username (if applicable): strophy

## Description

Roskomnadzor blocks the IP range 165.227.0.0-165.227.255.255 in Russia. This means our documentation is not available there without a VPN. The blocking seems to be collateral damage resulting from the decision to block Telegram messenger. Is there any option to change to a different IP, or push this request further up to your host? Are the docs currently hosted by Azure, Rackspace or someone else?

Thanks for any help you can offer on this, although I appreciate it is totally not a problem with RTD and almost entirely out of your control...

**Comment by stsewd** [comment]
We are hosted in azure right now

**Comment by 3eph1r0th** [comment]
165.227.0.140 IP from docs.dash.org is still blocked in Russia. Can you please change IP address for that domain address?
