### ISSUE TITLE
Readthedocs for PyLops library - memory issue

### ISSUE THREAD

**Issue by mrava87** [rtfd/readthedocs.org#4946]
## Details
Hello,
I have been trying to build my documentation from this project https://github.com/Statoil/pylops in readthedocs. 

I get an error about memory comsumption (build report below) but I do not seem to find more details onto at which point of the build this happens.  I am aware of the fact that you limit the build to 1GB memory, if you could help me understand where the build fails I could try to simplify the example to be able to avoid reaching the limit :)

Basically the documentation uses sphinx-gallery to create various examples for each class that I implement and some of them require quite some computation to be meaningful, but we are still talking about less than 10 minutes on a normal OSX laptop. 

I have sent an email to your support account and Manuel replied suggesting to open an issue.

Looking forward to hearing from you,
MR
* Read the Docs project URL: https://readthedocs.org/projects/pylops
* Build URL (if applicable): https://readthedocs.org/projects/pylops/builds/8181469/
* Read the Docs username (if applicable):  mrava87

## Expected Result
Building documentation

*A description of what you wanted to happen*
I would like to get my documentation built succesfully 

## Actual Result
Command killed due to excessive memory consumption

**Comment by mrava87** [comment]
Hi humitos,
looking forward to hearing from you, hope you can help me troubleshoot this problem :)

**Comment by stsewd** [comment]
I guess you could reduce the number of images or generate the images outside rtd (I think someone did this in the past)

**Comment by mrava87** [comment]
Thanks for suggestions. Could you explain how that would help? Would it help if I have a ply.close() at the end of each Sphinx-gallery example?

And if I generate them outside of rtd how can I then keep the Sphinx-examples in the documentation?

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/issues/3468

**Comment by mrava87** [comment]
Mmh this sounds a poor man job trying to replicate what Sphinx-gallery (https://sphinx-gallery.readthedocs.io/en/latest/) does for you. This is used by many libraries like Matplotlib and sciiti-learn and they have tons of images. How do they get around?

**Comment by mrava87** [comment]
Quick update. Things work now:

- added plt.close(‘all’), this didn’t solve the problem but the build run for longer before giving up
- remove most heavy computational examples and build is successful.

I guess the problem is that memory really goes above limit, but I wonder if it would be possible to explain how we can access the stdout and stderr of the Sphinx-build command, otherwise it’s a bit difficult to troubleshoot :)

**Comment by mrava87** [comment]
Also I think the solution in the issue you linked should not be encouraged as it makes things may more cumbersome and just does not take advantage of a fantastic library which sphinx-gallery is :)

**Comment by stsewd** [comment]
Looks like we replace the output when it's killed

https://github.com/stsewd/readthedocs.org/blob/ff377cc2496bdb40df484296a70205383ddececa/readthedocs/doc_builder/environments.py#L274-L276

I guess we could keep the original output.

**Comment by mrava87** [comment]
Up to you to decide of course but I personally think that would help a lot :)

Thanks for help!

**Comment by stsewd** [comment]
I think it's a good idea, I opened https://github.com/rtfd/readthedocs.org/issues/4957 to track that, closing this issue as the problem was solved.
