### ISSUE TITLE
Best Practices Question: redirects for non-existent docs

### ISSUE THREAD

**Issue by Nick-Harvey** [rtfd/readthedocs.org#4948]
## Details
Overall, I'd like to find out what's the best way to handle redirects for docs that get deleted. Here's the situation

We have old docs (v1.2.1 and we're now on 1.7.11) that are still being indexed by Google that are showing up pretty high in search results. Version 1.2.1 has been retired for a long time now and is set to an inactive version in RTD. Also, there are documents that since 1.2.1 have been deleted that users are still finding via search. When going to that page they get the banner saying that the version is old and that they should go do the latest. But since that doc doesn't exist in the latest version of the docs the link in the note won't work and users get the Maze page. So I guess my question(s) are as follows

1. Is there a way to do a version wide redirect, possibly to a page that says these are outdated docs please go to xyz (which is a link to root of latest) 
2. Whats the best way of handling the deletion of docs and redirects. 
3. Is there a way to create a build notification that contains a list of broken links so we can resolve them. 
4. What's the best process for retiring old versions completely. 

More context of what I'm talking about is in a github issue here: https://github.com/pachyderm/pachyderm/issues/3224

* Read the Docs project URL: https://pachyderm.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Have you read this https://docs.readthedocs.io/en/latest/user-defined-redirects.html? I think there are some use cases there, not sure if that covers all your questions,

**Comment by Nick-Harvey** [comment]
Thanks for chiming in :). We are using the user-defined-redirects but as I'm sure you can imagine that at scale, it gets unruly fast. One idea for a solution that comes to mind, is to have a customizable redirect page. That way when a user finds old documentation via search, instead of maze page or old docs, they get a page that can say whatever and include the correct links.

**Comment by stsewd** [comment]
> is to have a customizable redirect page

Do you mean like a custom 404 page? we have https://github.com/rtfd/readthedocs.org/issues/353 and https://github.com/rtfd/readthedocs.org/issues/2551
