### ISSUE TITLE
Request for increase build timeout in Chainer project

### ISSUE THREAD

**Issue by kmaehashi** [rtfd/readthedocs.org#4955]
## Details

* Read the Docs project URL: https://chainer.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/chainer/builds/8191404/
* Read the Docs username (if applicable): kmaehashi

## Expected Result

Build succeeds.

## Actual Result

Build fails with timeout.

Recently we added native code to our Python module, which increased the build time.
We made some effort to improve the build speed (e.g., using `make -j2` or building with `-O0`), however,  the build sometimes succeed (https://readthedocs.org/projects/chainer/builds/8191403/), but sometimes fail with timeout (https://readthedocs.org/projects/chainer/builds/8191404/).

Could you increase the build timeout limit?

Thanks in advance!

**Comment by humitos** [comment]
You can disable some formats, for example, to reduce the time for the builds. Here is a guide for this, https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

I increased the build time to 1500 seconds. Let me know!

I strongly suggest you to read that guide and remove the formats that are not used.

**Comment by kmaehashi** [comment]
Thank you for your suggestions and increasing the build time! Builds seems to woking stably now.
We will also consider removing the unused format.

**Comment by stsewd** [comment]
Glad that it worked
