### ISSUE TITLE
Use `-c` option when calling sphinx

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#4962]
We ask users to enter a `path/to/conf.py` file, but we only use the directory of this file (is used to set the cwd). We could use http://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-c

**Comment by humitos** [comment]
What this would be useful for?

**Comment by humitos** [comment]
I still don't follow. What's the benefit for the user?

I think it doesn't worth the effort of changing all of our structure with no earning here.

**Comment by stsewd** [comment]
It's less confusing, more explicit. Right now if the user enters something like `docs/foo.py` rtd still will search for `docs/conf.py`.

**Comment by humitos** [comment]
So, I think it's better to change the Python code to validate that `docs/foo.py` (does/does not) exist first and if it doesn't raise a `ValidationError` instead of changing the whole code (yaml scheme, validation over the path, etc).

**Comment by stsewd** [comment]
We validate that, but still, we never use the full path, for mkdocs we use the `-f` option. Also, if the user has the `conf.py` inside `package/docs/source`, we don't show that route anywhere (we change directory on our end, but we don't show that), but that's one more thing of rtd as ci again....

**Comment by stsewd** [comment]
This is also helps to show the relative path more explicitly, right now the full path is hidden in the `cwd` of the command (not  visible from the build page). I mean, currently we show the relative path to the `conf.py` file instead of the repo root.
