### ISSUE TITLE
Yii2 cookbook layout issue 

### ISSUE THREAD

**Issue by faizanktk** [rtfd/readthedocs.org#4965]
Open this link https://yii2-cookbook.readthedocs.io/logging-problems-and-solutions/

and check the issue

**Comment by faizanktk** [comment]
@ericholscher

**Comment by humitos** [comment]
Please, check this https://github.com/rtfd/readthedocs.org/issues/4893

I think it's duplicated.

**Comment by stsewd** [comment]
This is an issue with the mkdocs theme, you should report there https://github.com/mkdocs/mkdocs/ or use the rtd theme, which has a sidebar for the menu.
