### ISSUE TITLE
build failing due to old python version

### ISSUE THREAD

**Issue by joelmiller** [rtfd/readthedocs.org#4969]
I'm trying to build some documentation (which has previously been successful).  My package relies on networkx.  I am getting the error message:

> NetworkX requires Python 3.5 or later (2.7 detected).

So I suspect the issue is that networkx now requires a higher version of python than it used to, but readthedocs is using 2.7.  How can this be fixed?

* Read the Docs project URL:  https://readthedocs.org/projects/epidemicsonnetworks/
* Build URL (if applicable):   https://readthedocs.org/projects/epidemicsonnetworks/builds/8215970/
* Read the Docs username (if applicable):  joelmiller

*A description of what you wanted to happen*

I expected a successful build.

## Actual Result

*A description of what actually happened*

The full error message is

> Obtaining networkx from git+https://github.com/networkx/networkx/#egg=networkx (from -r requirements.txt (line 1))
>   Updating /home/docs/checkouts/readthedocs.org/user_builds/epidemicsonnetworks/envs/latest/src/networkx clone
>     Complete output from command python setup.py egg_info:
>     NetworkX requires Python 3.5 or later (2.7 detected).
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 255 in /home/docs/checkouts/readthedocs.org/user_builds/epidemicsonnetworks/envs/latest/src/networkx/
>

**Comment by joelmiller** [comment]
I was just coming back here to say I had discovered exactly that.

Thanks

**Comment by RichardLitt** [comment]
@joelmiller Glad you got it working. Thanks for following up.

**Comment by hwindlass** [comment]
It is too cryptic for me to understand, which file I need to do modifications for python version change?
Could you please specify the path of the file? Or there is any configuration file, which I need to download?

**Comment by stsewd** [comment]
@hwindlass you can read https://docs.readthedocs.io/en/latest/config-file/index.html
