### ISSUE TITLE
Git -> error: unknown option 'prune-tags'

### ISSUE THREAD

**Issue by MIKNOTAURO** [rtfd/readthedocs.org#4972]
## Details
I'm getting this error: unknown option `prune-tags' after build my docs.

I saw the code inside 
    vcs_support/backends/git.py

The fetch method has a flag '--prune-tag' which is not a valid flag in git.

I deleted that part and now everything works, but now I'm curious.

Did I miss something? or Am I wrong?

![image](https://user-images.githubusercontent.com/2102746/49681499-61d9b300-fa68-11e8-9fda-703ed9ee3941.png)

**Comment by dojutsu-user** [comment]
Can this be related to the git version (it should be >=2.17) ??
This error is same as this ([comment](https://github.com/rtfd/readthedocs.org/issues/3775#issuecomment-437657207)).

**Comment by stsewd** [comment]
I'm guessing you are using a local installation, you need `git >=2.17`, see https://docs.readthedocs.io/en/latest/install.html#requirements
