### ISSUE TITLE
Link update on FAQ page

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#4977]
Link - https://docs.readthedocs.io/en/latest/faq.html#i-want-to-use-the-read-the-docs-theme-locally

Under the "I want to use the Read the Docs theme locally" subheading,  repo link for sphinx _rtd_theme is given as https://github.com/snide/sphinx_rtd_theme. It should be https://github.com/rtfd/sphinx_rtd_theme.

I am not sure on this change, this link might be intentional.
Will it be okay to change the link?

**Comment by stsewd** [comment]
Yes, we need to update the link, I believe there are another places that point to the `snide` username.

**Comment by dojutsu-user** [comment]
@stsewd 
I grepped for 'snide' and didn't find another.
Will make a PR for this one soon
