### ISSUE TITLE
BuildEnvironmentWarning logged as error

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4978]
After #4804 got merged `BuildEnvironmentWarning` start being logged again as an error.

This is not a big problem but it's annoying when debugging since it uses our Sentry quota.

* https://sentry.io/read-the-docs/readthedocscom/issues/793207804/
* https://sentry.io/read-the-docs/readthedocs-org/issues/783202503/

Relating to #4590 since that could help us to avoid logging all of these.

**Comment by dojutsu-user** [comment]
@humitos 
I would like to take this issue up.
Any idea on how to start?
