### ISSUE TITLE
Validate url from Webhook notification

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#4981]
We are allowing `''` as URL for webhook notifications.

We need to add better validation to this form.

### Steps to reproduce it

1. Go to Admin -> Notifications
1. Click the Add button under the Webhook Notifications

Sentry: https://sentry.io/read-the-docs/readthedocs-org/issues/789512412/?referrer=github_plugin

**Comment by dojutsu-user** [comment]
Working on it.
