### ISSUE TITLE
Failed docs build help

### ISSUE THREAD

**Issue by bmorris3** [rtfd/readthedocs.org#5004]
## Details

* Read the Docs project URL: https://arcesetc.readthedocs.io/en/latest/
* Build URL (if applicable): build #8276197 https://readthedocs.org/projects/arcesetc/builds/8276197/
* Read the Docs username (if applicable): bmorris3

## Expected Result

Expected the docs to build successfully. 

## Actual Result

Failed with error: 
```
Error

There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8276197).
```
The build details say: 
```
Note: The static directory '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' was not found. This is often because it is
      empty and you are using git. If so, you don't need it, so make
      sure it isn't included in the html_static_path setting in your conf.py
      file, otherwise Sphinx may fail the build if you are turning warnings into
      errors.
```

**Comment by humitos** [comment]
Thanks for your report.

I checked the logs and it seems to be a temporary error when trying to create the docker container. I saw that your latest builds worked properly.

I'm closing it here. Feel free to reopen if you consider.
