### ISSUE TITLE
Show `pip freeze` during build

### ISSUE THREAD

**Issue by goerz** [rtfd/readthedocs.org#5006]
It would be really nice if there was a `pip freeze` as part of the build process immediately before `cat docs/conf.py`

This would have made figuring out what went wrong in https://readthedocs.org/projects/krotov/builds/8281165/ much easier. It was a broken update of the nbsphinx package. While in principle, the `conda env create` tells me the installed versions of some of the packages, its output is rather messy. With a `pip freeze`, it would be very easy to diff the logs of two builds to see which versions changed.

**Comment by goerz** [comment]
Of course, it would be even better if the `readthedocs.yml` allowed to specify the install/build commands, the way that e.g. `.travis.yml` or `.appveyor.yml` do.

**Comment by stsewd** [comment]
I think this would be a good addition :)

> Of course, it would be even better if the readthedocs.yml allowed to specify the install/build commands, the way that e.g. .travis.yml or .appveyor.yml do.

Well, I think that is not the purpose of rtd (personal opinion), but our next version of the config file is more extensible and configurable.

**Comment by humitos** [comment]
Consider using `conda list` for conda environments and `pip list` for pip ones.

**Comment by agjohnson** [comment]
I'd probably be -1 on polluting the output with either of these. This is another CI feature I don't really think RTD needs

**Comment by goerz** [comment]
In my opinion, RTD *desperately* needs CI features. The crazy hoops I have to jump through to install dependencies and generate the documentation when a `make docs` would be right there is what's making me look very seriously at [doctr](https://drdoctr.github.io/doctr/docs/index.html).

**Comment by ericholscher** [comment]
This information is currently in the build output page (eg. the pip install). We had some bugs in the past where libraries were not being used correctly after being installed, which is where this feature would be useful. We believe we've fixed those issues, so we're going to close this issue now because we aren't likely to implement this.

**Comment by eric-wieser** [comment]
> This information is currently in the build output page (eg. the pip install). 

This unfortunately doesn't help if conda is used, which silences the pip install output.
