### ISSUE TITLE
How to pass private config vars to RTD?

### ISSUE THREAD

**Issue by byrnereese** [rtfd/readthedocs.org#5007]
## Details

* Read the Docs project URL: https://ringcentral-api-docs.readthedocs.io/en/bootstrap
* Read the Docs username (if applicable): byrnereese

## Problem Description

I recently created a mkdocs plugin (https://github.com/byrnereese/mkdocs-git-committers-plugin) that will display a list of contributors associated with a documentation page. It used the Github API which has aggressive API rate limits unless you are auth'ed with a token. 

So I created a token, and added it to my docs mkdocs.yml file under the plugin config. This is obviously far from ideal.

Is there a way to pass these types of values in through an ENV (environment variable) to RTD so that I do not need to reveal these auth tokens publicly?

**Comment by stsewd** [comment]
Currently, there isn't, but it's on plans https://github.com/rtfd/readthedocs.org/pull/4899
