### ISSUE TITLE
TeX capacity exceeded, sorry [input stack size=5000].

### ISSUE THREAD

**Issue by aanm** [rtfd/readthedocs.org#5008]
## Details

Is it possible to increase TeX's input stack?

* Read the Docs project URL:

* Build URL (if applicable):
https://readthedocs.org/projects/cilium/builds/8283503/
* Read the Docs username (if applicable):

## Expected Result

The build to succeed

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

```
! TeX capacity exceeded, sorry [input stack size=5000].
\&->\discretionary {\char `\&
                             }{\sphinxafterbreak }{\char `\&}
```

**Comment by humitos** [comment]
How do you normally do that?

**Comment by aanm** [comment]
@humitos every build now, probably we have reached a limit with TeX?

**Comment by humitos** [comment]
I'm sorry. I don't follow.

**Comment by RichardLitt** [comment]
@aanm Can you explain your question in a different way?

**Comment by aanm** [comment]
@RichardLitt @humitos sorry for the late reply, this happens on every built triggered in readthedocs. I had to disable the PDF build option in https://readthedocs.org/dashboard/cilium/advanced/ in order for the build to complete successfully.

```
Enable PDF build:
 Create a PDF version of your documentation with each build.
```

**Comment by stsewd** [comment]
What we need here are some docs on how to increase the TeX capacity, or something actionable from our side.

**Comment by aanm** [comment]
@stsewd what can I do to help providing that information?

**Comment by stsewd** [comment]
> What we need here are some docs on how to increase the TeX capacity,

@aanm that, is that a latex configuration?
