### ISSUE TITLE
Abandoned project: twilio-salesforce.readthedocs.io

### ISSUE THREAD

**Issue by atbaker** [rtfd/readthedocs.org#5020]
## Details

* Read the Docs project URL: twilio-salesforce.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): atbaker

## Description

Hi there - I work at Twilio and I'm trying to gain control of the twilio-salesforce.readthedocs.io project. It was created a long time ago and is woefully out of date, but I don't believe any of the developers who set up this project still work here.

Could you help me transfer ownership of this project to my account, `atbaker`?

If not that, I'd settle for a list of users on that project. I could then confirm that none of them work at Twilio and try and contact them some other way to transfer ownership.

Thank you!

**Comment by humitos** [comment]
Hi @atbaker! I just sent an email to the owner of that project to follow our policy: http://docs.readthedocs.io/en/latest/abandoned-projects.html

I'll come back here when I get a reply from the user and/or after 6 weeks without answer at all.

**Comment by ericholscher** [comment]
/remind 3 weeks to transfer project if we don't hear back.

**Comment by ericholscher** [comment]
/remind me to transfer project if we don't hear back in 3 weeks

**Comment by humitos** [comment]
@atbaker Hi! You were added as maintainer of that project. I'm closing here. Let me know if you need anything else. Thanks!
