### ISSUE TITLE
Was CMake support removed?

### ISSUE THREAD

**Issue by Syndace** [rtfd/readthedocs.org#5026]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-xeddsa/
* Build URL (if applicable): https://readthedocs.org/projects/python-xeddsa/builds/8307687/
* Read the Docs username (if applicable): Syndace

## Description

My project uses CMake to compile a library during the python package setup. Around four months ago it worked fine (for example [this build](https://readthedocs.org/projects/python-xeddsa/builds/7632383/) succeeded), but now it seems like CMake is not installed or not available.

**Comment by humitos** [comment]
Hi! `cmake` was not available, I checked all the docker images.

The thing is that the package `ref10` used to use `make` and `gcc` and now tries to use `cmake` and `make`.

From https://readthedocs.org/projects/python-xeddsa/builds/7632383/

```
Compiling the ref10 library...
Make sure "make" and "gcc" are installed and available.
```

and from https://readthedocs.org/projects/python-xeddsa/builds/8307687/

```
Attempting to compile the ref10 library...
The compilation requires CMake and the "make" tool.
The "cmake" and "make" commands are used.
```

I hope it helps.

**Comment by Syndace** [comment]
Oh boy, and I even wrote that myself :D Well thank you, sorry for bothering

**Comment by RichardLitt** [comment]
@Syndace Not a problem at all. :) Thank you.
