### ISSUE TITLE
Request to increase memory limit for dropbox-sdk-python project

### ISSUE THREAD

**Issue by greg-db** [rtfd/readthedocs.org#5027]
# Details

* Read the Docs project URL: https://readthedocs.org/projects/dropbox-sdk-python
* Build URL (if applicable): https://readthedocs.org/projects/dropbox-sdk-python/builds/8263925/
* Read the Docs username (if applicable): dropboxapi

## Expected Result

The documentation build for the dropbox-sdk-python library builds successfully.

## Actual Result

The documentation build for the dropbox-sdk-python library failed with:
> Command killed due to excessive memory consumption

That may be due to a large number of objects and routes for the Dropbox API.

Can the memory limit be increased for this package?

(Alternatively, if there is a way to optimize this on our side, or perhaps run the build locally so readthedocs doesn't have to, we'd be happy to look into that. Please share any such documentation if so.)

Thank you!

**Comment by stsewd** [comment]
Some things you can try are https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by humitos** [comment]
@greg-db after trying what Santos suggested, please if you still have issues let me know and I will increase the limits for this project. Thanks!

**Comment by humitos** [comment]
I guess that a problem could be that all the objects live in only one single huge file: https://dropbox-sdk-python.readthedocs.io/en/latest/moduledoc.html

Actually, that page almost kills my browser just to render it. I suppose that something similar happens with Sphinx. Maybe splitting into a page per module is a good idea.

**Comment by greg-db** [comment]
It looks like splitting out the docs into multiple pages was sufficient. The latest build succeeded. Thanks all!

**Comment by humitos** [comment]
@greg-db nice! Docs are easier to follow/read/surf now from my point of view and my browser doesn't get stuck when opening any page.
