### ISSUE TITLE
WARNING: html_static_path entry and Missing searchtools.js_t

### ISSUE THREAD

**Issue by strophy** [rtfd/readthedocs.org#5029]
## Details

* Read the Docs project URL: https://docs.dash.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/dash-docs/builds/8309041/
* Read the Docs username (if applicable): strophy

I'm getting 2 build warnings that I can't seem to fix:

```
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
copying searchtools... WARNING: Missing searchtools.js_t
```

I've tried setting `html_static_path = []` as described in #1776 without success, but it is definitely still loading files from the _static directory in my project. I'm not sure where searchtools.js_t is defined. The static error exists on other versions and languages of my documentation, but the search error isn't present for different languages. What could be causing this?

**Comment by stsewd** [comment]
I can confirm that we inject the `_static` path value in the build step, and it doesn't exist, not sure why we do that, maybe we used to use this a time ago? I'm investigating more.

**Comment by stsewd** [comment]
Here we insert the static path https://github.com/rtfd/readthedocs.org/blob/5386e844ac96a211f4aa58e36a49e1a1e7da2b06/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L40-L40

Here is the value https://github.com/rtfd/readthedocs.org/blob/5386e844ac96a211f4aa58e36a49e1a1e7da2b06/readthedocs/doc_builder/backends/sphinx.py#L117-L117

https://github.com/rtfd/readthedocs.org/blob/5386e844ac96a211f4aa58e36a49e1a1e7da2b06/readthedocs/doc_builder/constants.py#L15-L20

**Comment by stsewd** [comment]
Ok, I found that we used to have an override there, but I guess it was deletes/moved to the theme/extension

**Comment by stsewd** [comment]
Found it https://github.com/rtfd/readthedocs.org/pull/1946

**Comment by stsewd** [comment]
The another warning (`copying searchtools... WARNING: Missing searchtools.js_t`) believe is bc another reason, related to the extension https://github.com/rtfd/readthedocs-sphinx-ext/blob/addf69becb2a8b34baf3449a86df91df7c4184c5/readthedocs_ext/readthedocs.py#L176-L180

**Comment by stsewd** [comment]
The other warning comes exactly from https://github.com/rtfd/readthedocs-sphinx-ext/blob/addf69becb2a8b34baf3449a86df91df7c4184c5/readthedocs_ext/readthedocs.py#L234

**Comment by stsewd** [comment]
Ok, looks like your project is using `sphinx<2` (1.8.3), that file was renamed in https://github.com/sphinx-doc/sphinx/pull/5207/.

This is one of the incompatible changes with rtd, I'll try to see how we can support 1.7 and 1.8.

Also, you can use a `requirements.txt` file to specify a sphinx version.

**Comment by strophy** [comment]
I see the half-fix was merged, but I am still seeing both errors. Where can I find documentation of how to use requirements.txt, and how do I specify to use Sphinx 2, I wasn't aware this was even released yet? The current release of sphinx-doc seems to be at 1.8.3...

**Comment by stsewd** [comment]
The changes aren't deployed yet. 

> Where can I find documentation of how to use requirements.txt

https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

> and how do I specify to use Sphinx 2, I wasn't aware this was even released yet? 

What I mean, is that your project is using `sphinx<2`, which means that you are using sphinx `1.8.3`. And we don't support sphinx `1.8.x` officially yet (but I believe with the recent changes, it should be supported)
