### ISSUE TITLE
Shallow clone breaks build

### ISSUE THREAD

**Issue by stephenfin** [rtfd/readthedocs.org#5031]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/patchwork/
* Build URL (if applicable): https://readthedocs.org/projects/patchwork/builds/8314815/
* Read the Docs username (if applicable):

## Expected Result

The build, which utilizes the `reno.sphinxext` module, should work.

## Actual Result

The build fails due to missing tags. These are presumably missing due to the shallow cloning of repos introduced in #4939.

## Additional Information

The original issue that #4939 purported to resolve was #1888, **Optional** use of shallow clone for git repos (emphasis mine). While shallow clone might be useful at large, it should be possible to disable it for projects that rely on git history to build their docs.

**Comment by stsewd** [comment]
I'm guessing this is because the `reno` package needs the git history https://docs.openstack.org/reno/.

**Comment by stephenfin** [comment]
> I'm guessing this is because the `reno` package needs the git history [docs.openstack.org/reno](https://docs.openstack.org/reno/).

Indeed :disappointed:

**Comment by humitos** [comment]
@stsewd I think we should add a Feature flag for these cases to omit shallowing.

**Comment by stsewd** [comment]
We have to options here, feature flag (this can only be added by the core team), or an option in the web interface (this can be handled by the user).

**Comment by stephenfin** [comment]
Yeah, I've been looking at this. I see both approaches were adopted for submodules, with bd364946aa providing the feature flag approach and the later bfa6bdb346 providing a config file based approach. I'd been adding a `git.shallow_clone` setting using the latter approach based on the idea that pretty much everyone using reno or similar tools would be affected. I'm not sure how the config file ties into the web interface though and I don't see submodule configuration there. Is this a third option?

**Comment by stsewd** [comment]
We can't have this option in the config file because the config file is parsed after the clone step. And we don't have the submodules option on the web because we are moving all per-version settings to the config only, all per-project settings will be available on the web.

**Comment by stephenfin** [comment]
Oh, of course 🤦 I guess web UI is the way to go so, though I'm not sure where to nestle that in.

**Comment by humitos** [comment]
> feature flag (this can only be added by the core team), or an option in the web interface (this can be handled by the user).

Feature flag is the way to go. Admin option is overkill I'd say. I don't expect to have this problem too often.

**Comment by stephenfin** [comment]
See above. I've a pull request which should resolve this using the feature flag.

**Comment by stsewd** [comment]
@humitos I was thinking that we can use the providers API to fetch only the yaml, I think Travis does that.

**Comment by ericholscher** [comment]
**This is now deployed behind a feature flag, if anyone needs this functionality, just ask an admin.**

**Comment by humitos** [comment]
@stephenfin done for `git-pw`, `patchwork` and `infrared`. Please, if you have any issue open a new one to continue the discussion there. Thanks!

> I [triggered a build manually](https://readthedocs.org/projects/git-pw/builds/8327070/) in `git-pw` and it worked ;)

**Comment by tylerbutler** [comment]
> Feature flag is the way to go. Admin option is overkill I'd say. I don't expect to have this problem too often.

Is that the final decision? I think anyone who includes Git commit info in their docs using something like `sphinx-git` will hit this problem. Moreover, it's a time bomb. Builds will work fine for a while, then one day, once commits you are referencing have fallen out of the shallow clone, builds will start failing, complaining that commit hashes you're referring to 

I understand prioritizing other work - but this seems like it represents a lot of ongoing maintenance work for support, and also is confusing to users IMO.
