### ISSUE TITLE
git command fails but build doesn't fail

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5033]
## Details

I noticed this while reporting #5032 

* Read the Docs project URL: https://readthedocs.org/projects/test-builds/builds/
* Build URL (if applicable): https://readthedocs.org/projects/test-builds/builds/8319150/
* Read the Docs username (if applicable): humitos

## Expected Result

Fail the build completely.

## Actual Result

`git` command fails, but the build continues and passes. This means that the version built is invalid and we end up serving inconsistent docs.

![captura de pantalla_2018-12-24_10-48-03](https://user-images.githubusercontent.com/244656/50396298-8f617480-0769-11e9-92de-6e9035db3e65.png)

**Comment by stsewd** [comment]
I saw this when svn was failing some weeks ago, we need to verify the exit code and raise the proper exception.
