### ISSUE TITLE
Document Feature flag user can request us

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5041]
We have several Feature flags that can be applied to projects. Although, we don't have a document that explains that they are there and how to request them to be enabled.

List of Feature flags available,

https://github.com/rtfd/readthedocs.org/blob/dec39ba70315eca338359f8381af4610a3e56274/readthedocs/projects/models.py#L1018-L1029

We should write some docs around this mentioning them and explaining how they are used and how to request them.

Comes from: https://github.com/rtfd/readthedocs.org/pull/5036#issuecomment-450011872

**Comment by humitos** [comment]
I think just a specific page under our docs is enough. Maybe another entry in the FAQ with a general question like: "I want a different configuration that's not available under Admin" or well, something better than that ;)

**Comment by dojutsu-user** [comment]
Okay.
Working on it.

**Comment by agjohnson** [comment]
I don't think the point behind feature flags is to advertise to users to get a feature added, it's for us to manage the flags internally or automatically. Once a feature is ready for production, a user can manage the feature by themself, but this shouldn't require feature flags.

Our use cases for feature flags are:

* Quick iteration to get a partial/half baked feature out
* Sampling builds to test large changes

We shouldn't expect users to ask us for a feature -- features are ready when they're ready.
