### ISSUE TITLE
How to claim an existing but non active project on RTD

### ISSUE THREAD

**Issue by cokelaer** [rtfd/readthedocs.org#5045]
## Details

I wanted to create a new RTD project for one of my package on pypi but the name already exists on RTD.

However, it looks like a non active project with no builts. I do not know whether the owner will use it or not.

So, I would like to contact the owner or to claim this name for my project. What do you recommend , what shall I do ? I have read the RTD page https://docs.readthedocs.io/en/latest/abandoned-projects.html that explains your policy but I do not see the action I should take now. thanks

**Comment by cokelaer** [comment]
Here is the project's URL; https://fitter.readthedocs.io/en/latest/
Thanks

**Comment by humitos** [comment]
@cokelaer I sent an email to the owner today. I'll come back when I got a response (or not). Thanks!

**Comment by humitos** [comment]
/remind me to free `fitter` project slug if I didn't receive any response from the owner in 4 weeks

**Comment by humitos** [comment]
Hi @cokelaer! Good news. I received a reply from the owner telling me that it was fine to free the namespace. You can create your project with that slug. Enjoy Read the Docs!

I'm closing here. Let me know if everything is fine.

**Comment by humitos** [comment]
Thanks bot, but this is already done! ;)
