### ISSUE TITLE
Show active feature flags in project admin at readthedocs.org

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5046]
Users can open an issue to request for the feature flags.
I think it would be good to just show them the list of active feature flags for their project. It will avoid confusion that whether it is active or not or how many are active.

Related #5044

**Comment by dojutsu-user** [comment]
I am a little confused on this.
Will this be okay to implement it or not?

**Comment by agjohnson** [comment]
I also don't think we want to surface this. We use feature flags as an internal mechanism, it's not a user mechanism we need to communicate to the uesrs. Further, we do automatic sampling and I'm not sure we need to, or want to, alert the user to some of these.

I'll close this for now.
