### ISSUE TITLE
Error: [No such file or directory: 'pdflatex'] even after disabling the option in the project admin (local)

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5047]
I have disabled theses options in the admin
1. Create a PDF version of your documentation with each build.
2. Create a EPUB version of your documentation with each build.

Then also, every time when I tried to build the project, I get this error.
![screenshot from 2018-12-28 16-53-27](https://user-images.githubusercontent.com/29149191/50514031-a41f6e80-0ac1-11e9-8b13-6291a027d6e8.png)

## Steps to reprocuce
1. Manually import a project.
2. First build will give this error.
3. I enabled the Feature flag for v2 configuration.
4. Change the default branch.
5. Disable the options for PDF and EPUB
6. Build again and it will give this error.

I am not very sure that this can be reproduced in other system.

**Comment by stsewd** [comment]
What project are you using? If the project is rtd, we have PDF enabled in the config file, v2 doesn't merge the values from the admin, it always take precedence the config

**Comment by dojutsu-user** [comment]
Yes i am using the rtd project (my forked).
Sorry, I wasn't aware of it and was trying to build in local using RTD.
Thanks for help.

**Comment by stsewd** [comment]
See https://github.com/rtfd/readthedocs.org/pull/4451 for the v2 docs
