### ISSUE TITLE
How do I get readthedocs to use a custom 404 page? 

### ISSUE THREAD

**Issue by sg-s** [rtfd/readthedocs.org#5050]
## Details

* Read the Docs project URL: https://xolotl.readthedocs.io/en/master/

## Expected Result

If I go to https://xolotl.readthedocs.io/en/master/fsdf, I expect to see the 404 page that is part of my theme (which is what I see when I build locally) 

## Actual Result

Instead, I get the default readthedocs 404 page with the maze.

 I don't understand why the 404.html that is built as part of my theme isn't being used. 

I can't find any setting in readthedocs that specifies custom 404 pages

I've looked at these links, and I don't think they help:

* https://github.com/rtfd/readthedocs.org/issues/2551
* https://docs.readthedocs.io/en/latest/user-defined-redirects.html
* https://github.com/rtfd/readthedocs.org/issues/4948

Any help appreciated!

**Comment by humitos** [comment]
Hi @sg-s and thanks for your report.

Currently, this is not possible.

There are more discussion around this and the problems of different implementations at #353 (actually, it feels this issue is a duplicated of that one)

**Comment by humitos** [comment]
> is this because they're not using readthedocs, and instead hosting on github?

I suppose, yes.

I hope RTD support this soon. It's something that I've wanting for some time. 

I'm closing this issue here. Please, subscribe to the one that I linked here since all the discussion will happen there mostly.

Thanks!

**Comment by humitos** [comment]
@sg-s hey! we do support custom 404 pages now!

Your project now shows your custom page at: https://xolotl.readthedocs.io/en/master/notfound

The only thing missing is fixing the resources (css, js, images, etc) to use absolute URLs so they are found by the browser properly.

**Comment by sg-s** [comment]
@humitos Thanks! will check this out

**Comment by stsewd** [comment]
@sg-s all links to css/js are relative, those should be absolute. Since the 404 page can be displayed in any subpage `/foo/bar/404.thml` not just in `/404.hml`

**Comment by sg-s** [comment]
Great, thanks. Sounds like I need to modify the theme I'm using and replace all relative links with absolute links

**Comment by humitos** [comment]
@sg-s let us know if after changing the links it does work! ;)
