### ISSUE TITLE
Builds failing for projects using the "typing" package

### ISSUE THREAD

**Issue by delivrance** [rtfd/readthedocs.org#5051]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyrogram/
* Build URL (if applicable): https://readthedocs.org/projects/pyrogram/builds/8338798/
* Read the Docs username (if applicable): **delivrance**

## Expected Result

Build expected to succeed.

## Actual Result

Build fails.

## Description

Hi. I suspect there's a bug in the `typing` package shipped as built-in package in Python 3.5.2 -- which I think is the version used by CPython 3.x in readthedocs. Because of this, builds for projects using it will fail.

I successfully reproduced the issue locally with Python 3.5.2 (newer versions starting from 3.5.3 are not affected).
I also tried to force `typing` as external dependency, but it seems to be ignored by Python itself.
I finally took the updated typing.py module from https://raw.githubusercontent.com/python/typing/master/src/typing.py and manually replaced the file shipped with 3.5.2. The errors vanished.

Is there any chance to see an interpreter update in your build instances?

**Comment by stsewd** [comment]
Typing is supported with python 3.6, you need to use a config file, soon 3.6 (or 3.7) will be the default interpreter.

**Comment by delivrance** [comment]
@humitos Thanks, it worked: https://readthedocs.org/projects/pyrogram/builds/8342227/
@stsewd Nice to hear that, thanks again.
