### ISSUE TITLE
Remove deprecated build URLs

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5057]
Once #4568 gets merged, deployed and after 31st January we can remove all of these URLs and all the code associated to them since they will stop working and won't be used anymore.

Similar PR for corporate site at https://github.com/rtfd/readthedocs-corporate/pull/433

**Comment by agjohnson** [comment]
Note: After Jan 31st, we can remove the github endpoint, after Apr 1st, we can remove the rest or at least throw an exception from them.

**Comment by dojutsu-user** [comment]
I am interested in sending a PR for this.
But, I am not able to find what exactly needs to be removed.
Can I get some help on this to get started.

**Comment by stsewd** [comment]
@dojutsu-user there is a PR open for this https://github.com/rtfd/readthedocs.org/pull/5479

**Comment by dojutsu-user** [comment]
@stsewd 
Thanks for that.
