### ISSUE TITLE
A test is connecting to github.com and makes CircleCI to fail

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5063]
These are the last lines from CircleCI output, so I suppose that the test with the problem is under `test_backend.py`.

It seems that this does not affect TravisCI because I didn't see it here, but it does affect CircleCI and tests from Corporate are not passing because of this.

Also, tests should not download anything from GitHub anyway.

We need to research a little more here to find the issue and use a local repository for this purpose.

```
../.tox/py36/readthedocs.org/readthedocs/rtd_tests/tests/test_backend.py . [ 44%]
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)? Too long with no output (exceeded 10m0s)
```

**Comment by stsewd** [comment]
Tried this offline, it works. But I'm thinking something about this line is causing the problem https://github.com/rtfd/readthedocs.org/blob/f4d3a93a5c487351e836d51066faf40511a0b45a/readthedocs/rtd_tests/utils.py#L72-L72

**Comment by stsewd** [comment]
or even better https://discuss.circleci.com/t/git-clone-fails-in-circle-2-0/15211/2

**Comment by humitos** [comment]
The problem of using this URL for the invalid submodule `git@github.com:rtfd/readthedocs.org.git` is that this URL is not invalid for Corporate.

This was changed at https://github.com/rtfd/readthedocs.org/commit/d8c2131c13712cec7138a8dcff6c66ff2f80594c

I will skip this test for now in Corporate.
