### ISSUE TITLE
Doesn't refreshing/updating pdf version

### ISSUE THREAD

**Issue by EDI-N** [rtfd/readthedocs.org#5069]
Helo I got a problem with refreshing pdf version on https://wiki.edi-n.com/ (username EDI-N). It builds on Sphynx.

Why I say "update"? - Cause new pdf generates at new repository or some "master2457" branch without any problem... but only once!
Can you help me with it? ... some advice or prompt methods to delete pdf from media.readthedocs.org
Last time it's pdf updates last month 28th.

**Comment by stsewd** [comment]
Maybe a CDN or ISP cache thing? Can you check if everything is normal now?

**Comment by EDI-N** [comment]
Sorry for a long feedback: I make a few changes and they displayed immediately after build at web-page and in generated pdf version (for large changes needs little more time). Thank you, everything is working great now!
