### ISSUE TITLE
RFE: filter by name when importing a repository

### ISSUE THREAD

**Issue by larsks** [rtfd/readthedocs.org#5072]
## Details

The user interface for browsing available repositories is almost unusable if the number of available repositories is large.  Even restricted to just my personal repositories, it took me almost [three minutes of scrolling](https://youtu.be/vQtcgtj97Xw) to find the one I wanted. 

## Expected Result

I wish there was a text field into which I could type a partial repository name and have the list of available repositories restricted to those matching the name. E.g, the Travis UI for selecting a repository @ https://travis-ci.org/account/repositories.

## Actual Result

So. Much. Time.

**Comment by stsewd** [comment]
Duplicate of #1899
