### ISSUE TITLE
Changing the badge style for README.rst

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5074]
These badges looks better than the regular ones.

![](https://img.shields.io/travis/rtfd/readthedocs.org.svg?style=for-the-badge&logo=travis) ![](https://readthedocs.org/projects/docs/badge/?version=latest&style=for-the-badge&) ![](https://img.shields.io/codecov/c/github/rtfd/readthedocs.org/master.svg?style=for-the-badge&logo=codecov)

This needs some discussion and approval.

**Comment by stsewd** [comment]
Current ones look good for me, is what we use in all of our repos

**Comment by dojutsu-user** [comment]
@stsewd 
I think this can be closed then.
This was just a suggestion and is not of any priority.
