### ISSUE TITLE
Doxygen API documentation are not building on readthedocs

### ISSUE THREAD

**Issue by nagalakshmi92** [rtfd/readthedocs.org#5076]
## Details

* Read the Docs project URL: https://rocm-documentation.readthedocs.io/en/latest/index.html
* API Section URL : https://rocm-documentation.readthedocs.io/en/latest/ROCm_API_References/HIP-API.html

## Expected Result
Doxygen API Documentation hosted on readthedocs server.

## Actual Result
 while trying to host same documentation on readthedocs server we were not able to generate API's.

## Detailed Description

Locally when tried to build API's Using Sphinx, breathe and Doxygen we are able to generate API related Documentation by providing xml data path in conf.py ,when tried to host same documentation on readthedocs server we were not able to generate API's, we see no data being generated.

**Comment by humitos** [comment]
Please, check the WARNING messages in the build output. There are a lot of

`WARNING: Unknown directive type "doxygenfunction".`

So, it seems that doxygen is not correctly installed or something.

**Comment by nagalakshmi92** [comment]
Locally using sphinx tool it is working fine, we have installed doxygen on local machine. we tried to connect doxygen using conf.py  file for readthedocs server. Is there a procedure for calling Doxygen in readthedocs server.
