### ISSUE TITLE
groupoffice.readthedocs.io is not building

### ISSUE THREAD

**Issue by mschering** [rtfd/readthedocs.org#5078]
group office.readthedocs.io is not building

It reports this error:

A configuration file was not found. Make sure you have a conf.py file in your repository.

But it is certainly there: https://github.com/Intermesh/groupoffice-docs

It was building just before I committed some new docs. But I never touched conf.py

**Comment by humitos** [comment]
Hi! Please, follow our template to help developers with quick access to the requirements for debugging. Thanks!

**Comment by mschering** [comment]
OK:

## Details

* Read the Docs project URL: https://readthedocs.org/projects/groupoffice
* Build URL (if applicable): https://readthedocs.org/projects/groupoffice/builds/8367190/
* Read the Docs username (if applicable): mschering@intermesh.nl

## Expected Result

The site should build as it builds fine on my laptop.

## Actual Result

It reports this error:

A configuration file was not found. Make sure you have a conf.py file in your repository.

But it is certainly there: https://github.com/Intermesh/groupoffice-docs

**Comment by stsewd** [comment]
Please make sure you have `conf.py` path ii the rtd configuration. Since the field is empty, rtd is trying to guess, but there are two `conf.py` files.

![screenshot_2019-01-09 intermesh groupoffice-docs](https://user-images.githubusercontent.com/4975310/50906592-6f7db200-13f3-11e9-9d37-cf41540a6ac9.png)

**Comment by mschering** [comment]
Thanks! That fixed it.
