### ISSUE TITLE
Web docs don't update

### ISSUE THREAD

**Issue by cheesemarathon** [rtfd/readthedocs.org#5088]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/diyhue
* Build URL (if applicable):
* Read the Docs username (if applicable): cheesemarathon

## Expected Result

Getting started page to update to reflect the source

## Actual Result

The project seems to build fine. When downloading a PDF or a ZIP of the HTML it has built correctly and reflected the source files. However, the web page [here](https://diyhue.readthedocs.io/en/latest/) does not update the getting started page even though it is built correctly in the source HTML and PDF!

**Comment by humitos** [comment]
I do see reflected the latest commit on the web version of the documentation: `da233985` (https://github.com/diyhue/ReadTheDocs/commit/da23398507e68cc8b12c21b64fae1135ac20e0fc)

If that not the problem that you are having, please give more information. Thanks.

**Comment by cheesemarathon** [comment]
I have just pushed a commit to the Getting Started page [here](https://github.com/diyhue/ReadTheDocs/commit/4ca80e824a75773bf6e3817f0845b391744c8b40). [The build was successful.](https://readthedocs.org/projects/diyhue/builds/8373792/) However [this page](https://diyhue.readthedocs.io/en/latest/getting_started.html) does not reflex the change. However, the change can be seen in the [PDF](https://readthedocs.org/projects/diyhue/downloads/pdf/latest/) and the [HTML ZIP](https://readthedocs.org/projects/diyhue/downloads/htmlzip/latest/)

**Comment by cheesemarathon** [comment]
Ok solved the issue myself! Im not sure why I didnt think of this sooner. For some odd reason my browser was caching an old version of that page an not pulling the newly built one. Clear the cache and it was fixed.

**Comment by stsewd** [comment]
Can you be more specific about what exactly isn't updating? I did a quick review and both are the same. So, I'm guessing a browser/CDN/ISP caching thing.
