### ISSUE TITLE
Build fails during conda install step without error message 

### ISSUE THREAD

**Issue by fmaussion** [rtfd/readthedocs.org#5098]
Hi! Everything is in the title - it started a couple of days ago and I can't build any documentation since then... I didn't change anything in our build process. 

Thanks for your help!

## Details

* Read the Docs project URL: https://oggm.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/oggm/builds/8383487/
* Read the Docs username (if applicable): fmaussion

## Expected Result

Docs being built.

## Actual Result

Unexpected failure: https://readthedocs.org/projects/oggm/builds/8383487/

**Comment by humitos** [comment]
`conda` failed with 247 exit code. There are more info about this at https://github.com/rtfd/readthedocs.org/issues/4449#issuecomment-409018796

**Comment by fmaussion** [comment]
Thanks a lot for the rapid answer!

Unfortunately there is not much I can do to reduce our memory consumption, as I have no control on how conda works. See https://github.com/rtfd/readthedocs.org/issues/4432 for a similar discussion about the dependencies of our projects - which rely on many conda packages.

Note that I've been able to reduce the size of our build process on [mybinder](https://github.com/OGGM/oggm-edu/pull/27) using pip instead of conda, but this would require much more flexibility on the ReadTheDocs side (similar to that of [repo2docker](https://github.com/jupyter/repo2docker)).

Is there a way to ask for a bit more resources as a RTD gold user? (since very recently only ;)

**Comment by fmaussion** [comment]
Sorry to follow-up on this: I know you guys are making all this for free - and I'm thankful for this. 

I just have no way to reduce the memory consumption of conda... Alternatively, I would be able to install our environment via pip, but I would need more control on the build process than available currently on RTD.

It seems that the only solution is to increase the memory limit. I would be willing to pay for such a service. Did you guys ever thought of a "premium" business model?

**Comment by humitos** [comment]
Hi @fmaussion!

We do not charge FOSS in our platform and we do not pretend them to pay for using Read the Docs service.

That said,

> I would be willing to pay for such a service. Did you guys ever thought of a "premium" business model?

We do have a premium business model that it's our readthedocs.com platform. It's thought for companies and private repositories, though.

> Is there a way to ask for a bit more resources as a RTD gold user? (since very recently only ;)

Thanks for the support. Appreciated!

> It seems that the only solution is to increase the memory limit.

I increased the memory for your project a little more and put your project in a special queue and triggered a new build.

Please let me know if that works.

**Comment by humitos** [comment]
First testing build, passed: https://readthedocs.org/projects/oggm/builds/8406103/ :tada: 

I'm closing for now. Feel free to reopen or ask anything you need.
