### ISSUE TITLE
Show a list of all installed packages (eg `conda list` or `pip list`) before building the docs

### ISSUE THREAD

**Issue by jorisvandenbossche** [rtfd/readthedocs.org#5099]
Regularly, when something went wrong with the doc build, I want to check all the installed packages in the environment being used to build the docs (to see everything looks OK, or if any package version changed, or ...).

However, currently this is (as far as I know) rather impossible to do. Eg in this doc build (https://readthedocs.org/projects/geopandas/builds/8356667/), the  log of the `conda env create` step is truncated, so this also gives no indication to what is exactly installed.

Therefore, I thought it might be useful to add one step to the build in which to give an overview of the environment. This could simply be showing the output of `conda list` for conda environments or `pip list` for pip-based ones.

**Comment by humitos** [comment]
> the log of the `conda env create` step is truncated, so this also gives no indication to what is exactly installed.

There is a PR that will remove the progress bar #5094 and will help with this.

> This could simply be showing the output of `conda list` for conda environments or `pip list` for pip-based ones.

There is another issue for this at #5006. I'm closing this as duplicated of that one.

Feel free to reopen if you consider.

**Comment by jorisvandenbossche** [comment]
> There is a PR that will remove the progress bar #5094 and will help with this.

It will help with lo longer truncating the build log, but the `--quiet` will also remove printing of the downloaded packages (where for now there was *some* version information visible).

> There is another issue for this at #5006. I'm closing this as duplicated of that one.

Yes, that is indeed the same request.

Thanks for the quick answer!

**Comment by humitos** [comment]
> It will help with lo longer truncating the build log, but the `--quiet` will also remove printing of the downloaded packages (where for now there was _some_ version information visible).

If that's the case, the documentation is wrong:

```
       -q, --quiet
              Do not display progress bar.
```

From https://conda.io/docs/commands/conda-install.html

**Comment by humitos** [comment]
I think the `--quiet` is what we want:

```
$ conda install --quiet beautifulsoup4
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/humitos/.pyenv/versions/miniconda3-latest

  added / updated specs: 
    - beautifulsoup4


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.6.3       |           py36_0         138 KB

The following NEW packages will be INSTALLED:

    beautifulsoup4: 4.6.3-py36_0

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Time: 0h:00m:15s                                                                                                                                                                              

~ ⌚ 14:11:25
$ 
```

**Comment by jorisvandenbossche** [comment]
Yes, that's for `conda install`, which is indeed the result we would want. 
However, the initial environment is created with the `conda env create` command (docs don't say much: https://conda.io/docs/commands/env/conda-env-create.html), and here the behaviour is (unfortunately) a bit different.

**Comment by humitos** [comment]
> and here the behaviour is (unfortunately) a bit different.

Did you try it? What version?

```
$ conda create -n testenv --quiet sqlite
Solving environment: ...working... done

## Package Plan ##

  environment location: /home/humitos/.pyenv/versions/miniconda3-latest/envs/testenv

  added / updated specs: 
    - sqlite


The following NEW packages will be INSTALLED:

    libedit:      3.1.20170329-h6b74fdf_2
    libgcc-ng:    8.2.0-hdf63c60_1       
    libstdcxx-ng: 8.2.0-hdf63c60_1       
    ncurses:      6.1-he6710b0_1         
    sqlite:       3.26.0-h7b6447c_0      

Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Time: 0h:00m:05s                                                                                                                                                                              
```

It does work in the same way from what I see here.

```
$ conda --version
conda 4.5.12
```

**Comment by jorisvandenbossche** [comment]
Can you try `conda env create` instead of `conda create` ? (that is what readthedocs is using)

**Comment by humitos** [comment]
Mmm... interesting. It does not show the packages installed :/

```
$ conda env create --quiet -f environment.yml  
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Time: 0h:01m:01s                                                                                                                                                                              
```

I think this is bad UX and should be reported to `conda`. I'm noting thing into #5094.

**Comment by jorisvandenbossche** [comment]
I completely agree it is bad UX, it would be much nicer if it would behave more similarly to `conda create` (I think all the `conda env` commands were created somewhat separately at some point, and never fully integreated / made consistent with the others)
