### ISSUE TITLE
Remove un-needed python dependencies

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5101]
Reviewing #5100 I realized that we have dependencies like `defusedxml` but there are no `from/import defusedxml` in our entire code base. So, we should remove them and rely on the proper package installation to install the proper version of it (to keep the compatibility they want).

Probably the same happens with `lxml` and `httplib2` and more. Please, consider finding out other cases here.

> NOTE: if they are required for some reason that it's not explicit in the code (because it's an _optional_ package for _another_ package but make it works faster/better/whatever we need to add a comment above the requirement explaining it.

**Comment by dojutsu-user** [comment]
@humitos 
I think there's no use case of `beautifulsoup4` also.

**Comment by Mike-Dai** [comment]
@humitos  Can I work on this issue?

**Comment by humitos** [comment]
@Mike-Dai Yes. Go ahead.
