### ISSUE TITLE
Unknown error building documentation

### ISSUE THREAD

**Issue by virtuald** [rtfd/readthedocs.org#5103]
## Details

* Read the Docs project URL: https://robotpy-pathfinder.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/robotpy-pathfinder/builds/8386241/
* Read the Docs username (if applicable): virtuald

## Expected Result

Build succeeded.

## Actual Result

> Error
> 
> There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8386241).

I've tried resetting the build environment too and that didn't seem to make any difference.

**Comment by humitos** [comment]
It seems there is a problem with one of the git submodules:

    Gitmodule path 'Pathfinder' did not exist in revision of parent commit HEAD

**Comment by virtuald** [comment]
Ha, oops. Curious, where did you see that error message? I don't see it.

**Comment by humitos** [comment]
In our Sentry account.

We are not exposing that error. We need to fix that. There is another issue created for that (that I don't find now).

I'm closing this issue, but feel free to reopen if you consider or you can't solve your issue. Thanks!

**Comment by virtuald** [comment]
That fixed it, thanks!
