### ISSUE TITLE
Enable no shallow clone for deepaas.readthedocs.io

### ISSUE THREAD

**Issue by alvarolopez** [rtfd/readthedocs.org#5105]
As noted in #5031, the use of shallow clones breaks the build of http://deepaas.readthedocs.io.

Would it be possible to have the feature flag enabled for this repo?

**Comment by humitos** [comment]
Hi @alvarolopez! Please, wipe your environment and trigger a new build. It should pass properly now. Feel free to reopen if you consider or something goes wrong. Thanks!

**Comment by alvarolopez** [comment]
Awesome. Thanks.

**Comment by alvarolopez** [comment]
Related this is not anymore needed, as per: https://github.com/readthedocs/readthedocs.org/issues/5989#issuecomment-1088730607
