### ISSUE TITLE
Sample some projects for Docker image 5.0rc1

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5106]
We just released `4.0` and `5.0rc1`.

So,

* `2.0` got deprecated
* `3.0` became `stable`
* `4.0` became `latest`

Now, we want to start testing `5.0rc1` with some projects. This image have [some changes](https://github.com/rtfd/readthedocs-docker-images/compare/4.0.0..master).

We want to create a Feature flag that "no matter has the user selected for the docker image we want to use `5.0rc` for `container_image`" when building the docs.

Once we have this feature added, we can start with 100, 500, 1500 and 5000 projects for a month and half and after that, release the new image.

**Comment by stsewd** [comment]
Current implementation of the config module allow us to override user's image frmo the db field `container_image`

**Comment by humitos** [comment]
Yes, but we don't want to do that avoid future miss-understandings. We just released these images and we didn't know why there were projects with `4.0rc1`, it it was because we wanted to test the image or because they needed something specific from that image. Now, we want to avoid that confusion by creating a Feature flag.

This flag, will be useful to test all the `rc` releases, not just this one in particular.
