### ISSUE TITLE
If docker image is overridden in the project, it's not saved into .json

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5108]
Our `PythonEnvironment.save_environment_json` method has a bug.

When the `Project.container_image` is manually set by an admin, it's not used when saving the `.json` file into disk and it's used the default image instead.

The problem is at this line,

https://github.com/rtfd/readthedocs.org/blob/33ed2735dc6e5e6e3b9e552bbbb72df600648a4a/readthedocs/doc_builder/python_environments.py#L187

although, `self.project.container_image` is `None` at that point because I suppose the `container_image` field does not come with in the API call. We may want to add it when using an Admin user to hit this endpoint.

**Comment by stsewd** [comment]
As explained here, we do that from the config module

https://github.com/rtfd/readthedocs.org/pull/5109#discussion_r247980054

That solves the problem?

**Comment by humitos** [comment]
@stsewd did you tested that the json gets the proper value on it? It should match the image used to execute the commands to the one saved in the json file.

**Comment by stsewd** [comment]
Yes, I just checked it

```bash
$ cat envs/latest/readthedocs-environment.json
{"python": {"version": 3.6}, "build": {"image": "readthedocs/build-dev:3.0", "hash": "sha256:64998dc2...."}}
```

Before it was building with the latest image.

**Comment by humitos** [comment]
@stsewd so, your project was building with `latest`, then you set `project.container_image = 'readthedocs/build-dev:3.0'` and trigger the build again and that's the JSON that you are showing here?

**Comment by stsewd** [comment]
Yes
