### ISSUE TITLE
Manage setup_vcs problems better

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5114]
I introduced a bug at https://github.com/rtfd/readthedocs.org/commit/e0c84056e

If the repo is invalid (`.setup_vcs` fails), we catch the exception, log it and continue as if everything went correct.

https://github.com/rtfd/readthedocs.org/blob/19e709089d645ac712a4c16b06a6083dbacd0539/readthedocs/projects/tasks.py#L612-L636

**Comment by humitos** [comment]
I think you are right. I'd revert this PR for now and propose a better solution for this.

**Comment by stsewd** [comment]
I guess we can remove the try except block only from `self.sync_repo()`. The another block was already catching a general exception.
