### ISSUE TITLE
Project Build fails after running twice on same commit

### ISSUE THREAD

**Issue by justusschock** [rtfd/readthedocs.org#5120]
## Details

* Read the Docs project URL: https://delira.readthedocs.io/en/latest/

## Expected Result
Building the docs from the same commit twice or from consecutive commits should work for both commits

## Actual Result
The second build fails

The manual workaround is to wipe the build environment and trigger the build again manually.

**Comment by stsewd** [comment]
Can you please share the exact builds? Also, your latest builds are passing.

**Comment by justusschock** [comment]
This happened for example in build [8395475](https://readthedocs.org/projects/delira/builds/8395475/) and worked after wiping the environment in build [8395750](https://readthedocs.org/projects/delira/builds/8395750/). Note that both builds worked on the exact same commit of the repo.

**Comment by stsewd** [comment]
I can only think of a requirement being updated and having trouble with an old package. So, I don't think it would be happening very often.

**Comment by justusschock** [comment]
At the beginning it happened at almost every build (if I didn't wipe before), now it seems to be more stable.
