### ISSUE TITLE
Half screen is blank

### ISSUE THREAD

**Issue by ron819** [rtfd/readthedocs.org#5123]
<img width="929" alt="a29330bf-d8de-44ab-a4cb-eb9fae5933e5" src="https://user-images.githubusercontent.com/40163787/51328332-d21e2000-1a7b-11e9-888b-f282cd364a77.png">

In any readthedocs website I enter , in any browser (firefox,chrome, edge, opra) half of the screen is blank (see yellow circle) this causes appearances  of scroll bars which I must use to read the whole text.
I know that other users do not suffer from this issue.

What can be the cause?

**Comment by stsewd** [comment]
Closing as duplicated of https://github.com/rtfd/sphinx_rtd_theme/issues/295
