### ISSUE TITLE
Discrepancy between latest build image

### ISSUE THREAD

**Issue by Podshot** [rtfd/readthedocs.org#5124]
## Details

* Read the Docs project URL: https://amulet-map-editor-pod.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/amulet-map-editor-pod/builds/8407366/
* Read the Docs username (if applicable): Podshot

## Expected Result
ReadTheDocs.org uses the latest build image (4.0 according to https://github.com/rtfd/readthedocs-docker-images) and recognizes and uses Python 3.7 to build the docs

## Actual Result
The build fails with an error saying that Python 3.7 is not a valid/supported Python version

This could also be a result of me attempting to try the latest/4.0 build before it's actually recognized as the "latest" image by the site/builder and it's instead using 3.0 as the latest build image, which doesn't support Python 3.7

**Comment by stsewd** [comment]
The change isn't deployed yet

**Comment by Podshot** [comment]
Is there an estimated timeline of when the change will be deployed?

**Comment by humitos** [comment]
Hopefully, no more than 2 weeks.

If you want, you can help us by testing our `5.0rc1` docker image that supports `3.7`. Let me know, and I will enable it in your code (your YAML file does not have to define any image)

**Comment by humitos** [comment]
Please subscribe to #5056 to follow when the docker `4.0` image will be available. I'm closing this issue here. Thanks.

**Comment by Podshot** [comment]
@humitos I would very much like to be able to test the 5.0rc1 docker image if you would enable it. Thanks!

**Comment by humitos** [comment]
@Podshot Done. I applied this image to the project `amulet-map-editor-pod`. Let us know if anything.
