### ISSUE TITLE
Edit on GitHub link for example built with sphinx-gallery

### ISSUE THREAD

**Issue by glemaitre** [rtfd/readthedocs.org#5131]
## Details

* Read the Docs project URL: http://imbalanced-learn.org/en/stable/
* Build URL (if applicable): https://github.com/scikit-learn-contrib/imbalanced-learn/tree/master/doc
* Read the Docs username (if applicable): glemaitre

## Description

We use `sphinx` to build our documentation and `sphinx-gallery` to build a gallery of examples.
The "Edit on GitHub" button is properly working for all sphinx documentation except the gallery.
Sphinx-gallery generates an `auto_examples` directory where it drops the examples. "Edit on GitHub" try to redirect on this directory instead of the source directory (i.e. `examples` directory).

For instance, the following example was built:

https://imbalanced-learn.readthedocs.io/en/stable/auto_examples/applications/porto_seguro_keras_under_sampling.html#sphx-glr-auto-examples-applications-porto-seguro-keras-under-sampling-py

which point to:

https://github.com/scikit-learn-contrib/imbalanced-learn/blob/09a068c9935662bfe6fcd49a067d7d941ffaacfb/doc/auto_examples/applications/porto_seguro_keras_under_sampling.rst

instead of:

https://github.com/scikit-learn-contrib/imbalanced-learn/blob/09a068c9935662bfe6fcd49a067d7d941ffaacfb/examples/applications/porto_seguro_keras_under_sampling.py

Is there any way that I can redirect those examples to the right URL?

**Comment by GuillaumeFavelier** [comment]
It seems we encounter the same issue on [`PyVista`](https://github.com/pyvista/pyvista/issues/636), what solution did you end up using @glemaitre ?
