### ISSUE TITLE
Build failure for PyWWT

### ISSUE THREAD

**Issue by astrofrog** [rtfd/readthedocs.org#5133]
Today I noticed that the build for the 'pywwt' project is [failing](https://readthedocs.org/projects/pywwt/builds/8419772/) just after the git clean step, and I get the message:

*There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8419772).*

The full log is:

```
Read the Docs build information
Build id: 8419772
Project: pywwt
Version: latest
Commit: c08bdbf37f31e7c6dca970443c73ec6b64d37fab
Date: 2019-01-20T09:16:03.519773Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-01-20T09:16:03.909211Z, end-time: 2019-01-20T09:16:05.439721Z, duration: 1, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/WorldWideTelescope/pywwt .
Cloning into '.'...

[rtd-command-info] start-time: 2019-01-20T09:16:05.674727Z, end-time: 2019-01-20T09:16:05.748276Z, duration: 0, exit-code: 0
git checkout --force origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at c08bdbf Added release date for v0.5.3

[rtd-command-info] start-time: 2019-01-20T09:16:05.807591Z, end-time: 2019-01-20T09:16:05.816593Z, duration: 0, exit-code: 0
git clean -d -f -f
```

What could be going wrong?

**Comment by humitos** [comment]
Hi! This is what I see in the logs:

```
Gitmodule path 'astropy_helpers' did not exist in revision of parent commit HEAD
"Blob or Tree named 'astropy_helpers' not found"
```

Maybe that helps you to fix it. I can go back to this during the week, maybe.

(if the submodule exists, maybe a wipe fixes the problem)

**Comment by astrofrog** [comment]
@humitos - that helped, thanks! Basically our package had a ``.gitmodules`` file but no submodule checked out in the repository. I'm not sure why this didn't come up as an issue before though, but it was definitely a problem on our side.

**Comment by humitos** [comment]
We were communicating similar errors in a friendly user way on build details page, so probably there is a regression here.

**Comment by stsewd** [comment]
@humitos the submodules issue is still open https://github.com/rtfd/readthedocs.org/issues/4371 and I'm working in submitting a patch in gitpython
