### ISSUE TITLE
'versions' became full, and new branch cannot be listed

### ISSUE THREAD

**Issue by KengoTODA** [rtfd/readthedocs.org#5135]
Thanks for providing so cool product! I'm a heavy user so facing one issue:

## Details

* Read the Docs project URL: https://readthedocs.org/projects/spotbugs/
* Read the Docs username (if applicable): rtd-bot

It seems that this issue is similar with #2491.

## Expected Result

* I can see the newly pushed branch in the version list. So I can check the build result on time.

## Actual Result

* I cannot see it even after I wait several days. So I cannot confirm the build result on time.
* I still can see deleted branches in that page, even though they're totally needless for me.

**Comment by KengoTODA** [comment]
> visit the integration detail page and follow the directions for re-syncing your repository webhook.

I cannot find the directions for re-syncing webhook in [integration detail page](https://readthedocs.org/dashboard/spotbugs/integrations/50313/). I also confirmed that [the config page in GitHub side](https://github.com/spotbugs/spotbugs/settings/hooks/55934956) has no direction either.

I'll attach screenshot of RTD site. Do I need to delete and recreate webhook?
![screenshot from 2019-01-22 11-00-51](https://user-images.githubusercontent.com/505751/51509679-0192ab00-1e35-11e9-9fde-ea0437520259.png)

**Comment by stsewd** [comment]
Your webhook wasn't created when you imported the project, that's why. You can add new permissions from the gihub side. These permissions https://docs.readthedocs.io/en/latest/webhooks.html#github

**Comment by KengoTODA** [comment]
Thanks! I've updated config in GitHub side, and watch coming builds to confirm how it works.

**Comment by stsewd** [comment]
Was the problem solved?

**Comment by KengoTODA** [comment]
I've confirmed that new branch is listed in the RTD's version page. However old branch (already removed from GitHub) is still listed. I hope this has no problem for my app.

I will confirm with my users, to make sure we can close this issue. Thanks for your waiting!

**Comment by KengoTODA** [comment]
It seems that no problem has been reported recently. Thank you, I will close this issue :)
