### ISSUE TITLE
Use :guilabel: sphinx role for all the Admin menu guideance

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5137]
I think this is the best way to render all the Admin menu instructions for the user and we should use it all across our documentation:

    :guilabel:`Domains` > :guilabel:`Edit Domain`

Example: https://docs.readthedocs.io/en/latest/custom_domains.html#custom-domain-ssl

I found that many places use bold for this, but this approach of `:guilabel:` is better.

**Comment by rexzing** [comment]
I am a first time contributor to this project. I like to work on this one. I just cloned the project. Any tips to start?

**Comment by dojutsu-user** [comment]
@rexzing 
You can start by reading the contribution guide: https://docs.readthedocs.io/en/latest/contribute.html
Welcome to the community.

**Comment by rexzing** [comment]
I folowed the guide and now I have a u and running server. Where should I look for " Admin menu instructions"? Any example file?

**Comment by dojutsu-user** [comment]
Files for the `docs` are under the `docs` folder (`readthedocs.org/docs/`).
Example is provided in the issue description.
Here are the docs for contributing to the docs: https://docs.readthedocs.io/en/latest/docs.html

**Comment by rexzing** [comment]
![screenshot from 2019-01-23 14-43-47](https://user-images.githubusercontent.com/25826165/51595689-56115580-1f1d-11e9-9cca-5d6298682ea7.png)
In here should I add :guilabel: to "New Email Notifications" and "Email" ?

**Comment by dojutsu-user** [comment]
I guess, yes.
You can make a PR, the team will review it there.

**Comment by rexzing** [comment]
I finished the task. Shall I PR to master?

**Comment by rexzing** [comment]
Oh.. I just submit a PR. What should I do now?

**Comment by dojutsu-user** [comment]
@rexzing 
I would suggest the following steps:

1. Close this PR.
2. In your forked repo, create a new branch.
3. Make changes.
4. Add and commit changes.
5. Make the PR from that branch with correct PR title and description.

**Comment by rexzing** [comment]
I think this issue is fixed and ready to close.

**Comment by stsewd** [comment]
Yes, thanks
