### ISSUE TITLE
Build not triggered anymore after commit

### ISSUE THREAD

**Issue by marcelstoer** [rtfd/readthedocs.org#5142]
## Details

* Read the Docs project URL: https://nodemcu.readthedocs.io/en/master/en/modules/encoder/#example_3
* Build URL (if applicable): https://readthedocs.org/projects/nodemcu/builds/
* Read the Docs username (if applicable): marcelstoer

## Expected Result

The documentation is built upon every new push to an active GitHub branch i.e. active RTD version.

## Actual Result

Somehow the build triggers stopped working several days ago. If I trigger the builds manually all is well.

This commit for example didn't trigger a build: https://github.com/nodemcu/nodemcu-firmware/commit/6f3f1126d6fed06ceb71db41d12bd2363101ab99 As of now, I didn't start it manually either. Maybe this helps with the analysis.

I noticed there were no integrations at https://readthedocs.org/dashboard/nodemcu/integrations/ so I added the GitHub integration FWIW. I don't remember if I ever saw any integration listed but the build triggers have been working fine for a couple of years.

**Comment by stsewd** [comment]
I think you were using the deprecated github services, https://github.com/rtfd/readthedocs.org/pull/4898 You should have received an email.

**Comment by marcelstoer** [comment]
> You should have received an email.

We're a bunch of volunteers who are maintaining a project without admin permissions. The original authors have left the ship years ago and don't even react to emails these days anymore. Hence, anything that requires access to the GitHub admin pages of the repository is out of reach for us. Thus, "we" won't ever get an email from you; not your fault of course.

What do we do now?

**Comment by stsewd** [comment]
Here we have some docs

https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

> Hence, anything that requires access to the GitHub admin pages of the repository is out of reach for us.

Not sure about the github permissions... Not much we can do from our side :/

**Comment by marcelstoer** [comment]
Thanks for the pointer.

**Comment by humitos** [comment]
> The original authors have left the ship years ago and don't even react to emails these days anymore

Open a new issue for this. Take a look at this docs first: http://docs.readthedocs.io/en/latest/abandoned-projects.html

Thanks!
