### ISSUE TITLE
Version Switcher does not appear in Chrome but does in FireFox

### ISSUE THREAD

**Issue by odscjames** [rtfd/readthedocs.org#5149]
## Details

* Read the Docs project URL: http://standard.openownership.org/en/v0-1/
* Build URL (if applicable): latest
* Read the Docs username (if applicable):

## Expected / Actual Result

Version Switcher does not appear in Chrome but does in FireFox

## Details

In Chrome, http://standard.openownership.org/en/v0-1/ renders with no version switcher widget appearing. If I open the network calls, I can see the call to /api/v2/footer_html/ 404's.

Oddly, in FireFox the widget appears. In Network calls, I can see the call to /api/v2/footer_html/  works.

The call looks like exactly the same URL for me (the callback function is different, but that's to be expected).

**Comment by ericholscher** [comment]
It works fine for me in Chrome. Guessing this is another issue.

**Comment by ericholscher** [comment]
This is a privacy issue. It only works with accounts that are logged in and have access to that version.,

**Comment by odscjames** [comment]
Ah, thank you. I will look into that.
