### ISSUE TITLE
Build error with build id #8442214

### ISSUE THREAD

**Issue by ThiefMaster** [rtfd/readthedocs.org#5166]
## Details:

* Project URL: https://readthedocs.org/projects/indico/
* Build URL: https://readthedocs.org/projects/indico/builds/8442214/
* Read the Docs username: ThiefMaster

## Expected Result
A successful build :heavy_check_mark: 

## Actual Result
:bomb:

---

No useful info in the build log, but past builds often failed with a completely random segfault.

**Comment by dojutsu-user** [comment]
Hi! This is what I see in the logs when I tried building the docs locally.

```
Gitmodule path 'ext_modules/jquery' did not exist in revision of parent commit HEAD
"Blob or Tree named 'ext_modules' not found"
```
(if the submodule exists, maybe a wipe fixes the problem)

Related comment: [#5133 (comment)](https://github.com/rtfd/readthedocs.org/issues/5133#issuecomment-455857467)

**Comment by stsewd** [comment]
This is because you have submodules that are not in the repo https://github.com/indico/indico/blob/master/.gitmodules

**Comment by ThiefMaster** [comment]
Thanks, removing the obsolete .gitmodules file fixed it!

indico/indico@ece9051d18c18632e5c3667ce202750cae4ee7bc
