### ISSUE TITLE
Convert docsearch newlines into BR's

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#5168]
Currently the results are split in docsearch by a newline between headers and content. We output the newline, but it doesn't mean anything in HTML. We should visually distinguish this. 

<img width="785" alt="screenshot 2019-01-24 11 35 10" src="https://user-images.githubusercontent.com/25510/51693025-1eadb200-1fcc-11e9-982c-ba23dab0d245.png">

**Comment by ericholscher** [comment]
Ended up changing these to periods instead of <br>'s as it looks better.

**Comment by stsewd** [comment]
This was already done in https://github.com/rtfd/readthedocs.org/pull/5197/
