### ISSUE TITLE
Online build failing - seems related to suffixes 

### ISSUE THREAD

**Issue by barbara-sfx** [rtfd/readthedocs.org#5172]
## Details

* Read the Docs project URL: https://readthedocs.com/projects/signalfx-product-docs/
Build URL (if applicable): https://readthedocs.com/projects/signalfx-product-docs/builds/176579/  (build failed)
* Read the Docs username (if applicable): brsnyder

## Expected Result

*Successful build*

## Actual Result

*Build fails*

Hi --

I am trying to use both RST and MD files in my project, per request from my engineering department.

I installed a couple of extensions (recommonmark and sphinx_markdown_tables) and updated conf.py accordingly.  I have it working locally in 1.8.2. The text I've added to my conf.py for suffixes is:

```
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}
```

The online build seems to be failing due to some text added to conf.py on your side. It is in this section:

```
###########################################################################
#          auto-created readthedocs.org specific configuration            #
###########################################################################
```

And it is failing in this part of the file:

```
from sphinx import version_info

# Get suffix for proper linking to GitHub
# This is deprecated in Sphinx 1.3+,
# as each page can have its own suffix
if globals().get('source_suffix', False):
    if isinstance(source_suffix, string_types):
        SUFFIX = source_suffix
    else:
        SUFFIX = source_suffix[0]  <== this is the line showing up in the error message
else:
    SUFFIX = '.rst'

```

Here is the error text I see online:

```
Exception occurred:
  File "conf.py", line 526, in <module>
    SUFFIX = source_suffix[0]
KeyError: 0
The full traceback has been saved in /tmp/sphinx-err-Sy7Cam.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

```
I'm posting this here instead of the sphinx repo because it builds successfully locally, so doesn't seem to be a sphinx problem.

Is there anything I need to do on my side to fix this, or do you need to modify something on your end?

Also, as a side note, could it be related to the fact that you are running such an old version of sphinx (1.4)?

Thanks -- Barbara

**Comment by stsewd** [comment]
This was fixed in https://github.com/rtfd/readthedocs.org/pull/5183/
