### ISSUE TITLE
Build error with build id #8446832

### ISSUE THREAD

**Issue by AtsushiSakai** [rtfd/readthedocs.org#5173]
## Details:

* Project URL: https://readthedocs.org/projects/PythonRobotics/
* Build URL(if applicable): https://readthedocs.org/projects/pythonrobotics/builds/8446832/
* Read the Docs username(if applicable): AtsushiSakai

## Expected Result

Build success

## Actual Result

Build failure

**Comment by stsewd** [comment]
You have a submodule setup here https://github.com/AtsushiSakai/PythonRobotics/blob/master/.gitmodules, but isn't in the repo

**Comment by AtsushiSakai** [comment]
@stsewd Thank you for your support. It was fixed. Thank you!!
