### ISSUE TITLE
Subdmodule with invalid URL (using git@ for public repo)

### ISSUE THREAD

**Issue by TheEnbyperor** [rtfd/readthedocs.org#5174]
## Details:

* Project URL: https://readthedocs.org/projects/FlawCon Badge/
* Build URL(if applicable): https://readthedocs.org/projects/flawcon-badge/builds/8449189/
* Read the Docs username(if applicable): theenbyperor

## Expected Result

A successfull build as happens locally to my machine

## Actual Result

Simply an error of "There was a problem with Read the Docs while building your documentation" with no actual error in the console output and all commands finishing with exit code 0

**Comment by humitos** [comment]
Hi @TheEnbyperor! It seems that you have configured an invalid/non-existent submodule called: `micropython`. If you remove it, builds will start working again.

    Gitmodule path 'micropython' did not exist in revision of parent commit HEAD

**Comment by TheEnbyperor** [comment]
That module is an integral part of the repo, and is also properly defined in .gitmodules

**Comment by stsewd** [comment]
@TheEnbyperor I can't see the submodule in the repo https://github.com/FlawCon/flawcon_badge

**Comment by humitos** [comment]
I suppose the problem is that the URL of your git submodule is `git@github.com:micropython/micropython.git` instead of `https://` and Read the Docs does not support it.

I just did a quick test and I was able to build with `https` instead of `git@` in the URL.
