### ISSUE TITLE
'More info' link in admin settings goes to unexpected location

### ISSUE THREAD

**Issue by EJEP** [rtfd/readthedocs.org#5175]
## Details

In Admin->Settings, section 'Documentation type' there is a link titled 'More info'  next to a dropdown menu allowing selection of 'Sphinx Html', 'Mkdocs (Markdown)', 'Sphinx Htmldir' or 'Sphinx 
Single Page HTML'.

## Expected Result

I expected this to link a page containing information about the possible choices from the menu.

## Actual Result

The link is to the `sphinx.builders.html.DirectoyHTMLBuilder` class (http://www.sphinx-doc.org/en/master/usage/builders/#sphinx.builders.html.DirectoryHTMLBuilder). This is unexpected if one is new to read the docs.

**Comment by EJEP** [comment]
The link was added in 3fb8a68, which references a discussion of the sphinx builders.

**Comment by EJEP** [comment]
This is fixed by #5180

**Comment by stsewd** [comment]
#5180 is not merged yet :)
