### ISSUE TITLE
GitHub incoming webhook for project "godot" no longer working

### ISSUE THREAD

**Issue by akien-mga** [rtfd/readthedocs.org#5188]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/godot
* Build URL (if applicable):
* Read the Docs username (if applicable): Akien

## Issue description

The GitHub incoming webhook for [godot](https://readthedocs.org/projects/godot) used to work fine to trigger a new build on new GitHub commits, but it stopped working a few weeks ago.

I tried to delete it and recreate it but to no avail, it's not working. Link to the webhook page: https://readthedocs.org/dashboard/godot/integrations/65717/

The page mentions that it was created from an existing webhook in the godotengine/godot-docs repository, but there are none for RTD. There was an entry for RTD in the "Integrations", which I delete, and tried again to delete the RTD webhook and recreate one, but it still doesn't work and says "This integration was created automatically from an existing webhook configured on your repository."

The referenced documentation doesn't seem to match the current workflow in the "Integrations" section of the RTD dashboard.

I have webhooks on godotengine/godot-docs-l10n which work fine on the other hand.

**Comment by davidism** [comment]
I experienced the same thing with Click. It seems that clicking "add integration" doesn't add a webhook for existing projects. It does add a service under the "Integrations & services" tab, but that doesn't seem to work anymore (and it's listed as deprecated). You can safely remove the service it adds (or not). To get builds working, you need to go to the "Webhooks" tab and manually add that webhook URL (which you should probably regenerate now that you've made it public). See https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services and https://docs.readthedocs.io/en/latest/webhooks.html#webhook-integration-github.

**Comment by stsewd** [comment]
You need to set up the webhook from the github side too https://docs.readthedocs.io/en/latest/webhooks.html#webhook-integration-github. If you have done that, can you please share the result from the webhook? Admin -> Integrations -> Integration

**Comment by akien-mga** [comment]
Thanks, I had misunderstood the docs and thought I had to take these steps to configure a GitHub webhook on the ReadTheDocs dashboard, hence my confusion.

I've configured the webhook on GitHub according to the docs and it seems to work now, thanks!
