### ISSUE TITLE
Misalignment when selecting content inside code blocks

### ISSUE THREAD

**Issue by algomaster99** [rtfd/readthedocs.org#5194]
## Details

* Read the Docs project URL: https://treeherder.readthedocs.io/installation.html
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

![screenshot from 2019-01-29 18-29-46](https://user-images.githubusercontent.com/35191225/51910355-f9b6a600-23f4-11e9-867e-63b6204967ac.png)

On tweaking css, it fixed the bug and now it is properly aligned.

## Actual Result

![screenshot from 2019-01-29 18-23-55](https://user-images.githubusercontent.com/35191225/51910362-00451d80-23f5-11e9-9457-0c745cbf0467.png)

The highlighted text is not aligned properly with highlighter box.

**Comment by algomaster99** [comment]
Can I work on this issue?

**Comment by stsewd** [comment]
Looks good for me using firefox 64.0.2 on fedora 29.

**Comment by dojutsu-user** [comment]
Doesn't work for me as expected.

![screenshot from 2019-01-29 21-30-56](https://user-images.githubusercontent.com/29149191/51921595-b87ec000-240d-11e9-828a-97a4426d29c8.png)

Chrome Version 71.0.3578.98 (Official Build) (64-bit)
Ubuntu 18.04.1 LTS

**Comment by algomaster99** [comment]
@dojutsu-user In the expected result, I did some css tweaks to fix it. Otherwise the actual result is being rendered.

**Comment by algomaster99** [comment]
@stsewd Oh okay. But the fix is required in Chrome Version 71.0.3578.98 and Ubuntu 18.04 LTS. Should I fix it?

**Comment by stsewd** [comment]
Yeah, at least isn't a bug from chrome (are you using a pre-release?). The fix should go to https://github.com/rtfd/sphinx_rtd_theme

**Comment by algomaster99** [comment]
No, I am using a stable chrome version. Okay, I will fix it as soon as possible. Will make the PR soon! :)

**Comment by algomaster99** [comment]
I am having a little trouble setting up the project. Can you help? 
![screenshot from 2019-01-29 23-09-00](https://user-images.githubusercontent.com/35191225/51928029-fc2bf680-241a-11e9-995f-6f06a10201b9.png)
Please tell me the IRC channel's link too. So I can communicate easier.

**Comment by dojutsu-user** [comment]
@algomaster99 
I would like to guide you to the docs page for setting up `sphinx_rtd_theme` - https://sphinx-rtd-theme.readthedocs.io/en/latest/contributing.html

IRC channel - #readthedocs
Gitter channel - https://gitter.im/rtfd/readthedocs.org

**Comment by stsewd** [comment]
I don't think we have a channel for the theme, but we use the same for all rtd projects: https://docs.readthedocs.io/en/stable/contribute.html#get-in-touch I'm available in gitter

**Comment by algomaster99** [comment]
@dojutsu-user I followed all the instructions but I am unable to set-up. And I don't know why but I can't use a simple grunt. I have to force it. And still it shows the same error.

**Comment by dojutsu-user** [comment]
I'm unable to reproduce the error.
Not sure, but maybe there's a problem with Ruby installation.

**Comment by algomaster99** [comment]
@dojutsu-user I have set it up according to the instruction but I had to run this command `gem install rb-inotify` as well to run `grunt` successfully. Basically, a gem was missing. Is this some issue with my local system only?

**Comment by dojutsu-user** [comment]
@algomaster99 
yes, it seems the issue is local to you only.
Try installing `Ruby` all over again. I think the `gem` is only causing problem here.

**Comment by algomaster99** [comment]
Oh okay! Yeah I have set it up now without any errors.

**Comment by algomaster99** [comment]
After around 6-7 hours of non-stop fiddling, I couldn't find a fix that covers both firefox and chrome.
Initially, I tried using `display: inline-flex` which worked fine in chrome but it creates a problem in firefox. On spending more time, I used a property `display: inline-table`. It worked well for the default page hosted (localhost:1919/) on both browsers. Unfortunately, the line `sudo apt-get install nfs-common nfs-kernel-server` (which is a code) is actually divided into 4 spans so when I apply the style, it ignores the spaces and it becomes like this:  `apt-getinstallnfs-commonnfs-kernel-server` but the highlighting problem is fixed.

**Comment by algomaster99** [comment]
After around 6-7 hours of non-stop fiddling, I couldn't find a fix that covers both firefox and chrome.
Initially, I tried using display: inline-flex which worked fine in chrome but it creates a problem in firefox. On spending more time, I used a property display: inline-table. It worked well for the default page hosted (localhost:1919/) on both browsers. Unfortunately, the line sudo apt-get install nfs-common nfs-kernel-server (which is a code) is actually divided into 4 spans so when I apply the style, it ignores the spaces and it becomes like this: apt-getinstallnfs-commonnfs-kernel-server but the highlighting problem is fixed.
Do you have any suggestion? @dojutsu-user

| | Firefox | Firefox | Chrome | Chrome |
|--------------	|----------------------	|---------------	|----------------------	|---------------	|
| Display type | Selection(Highlight) | Text(Spacing) | Selection(Highlight) | Text(Spacing) |
| inline-table | fixed | fixed | fixed | broken |
| inline-flex | broken | fixed | fixed | fixed |

**Comment by stsewd** [comment]
@algomaster99 would be great if you move this issue and the proposed solution to https://github.com/rtfd/sphinx_rtd_theme, there are people more familiar with css and those tricks p:. Thanks for researching in to this.

**Comment by dojutsu-user** [comment]
@algomaster99 
I think this issue can be closed here as you have already opened https://github.com/rtfd/sphinx_rtd_theme/issues/719
