### ISSUE TITLE
Could not find a version that satisfies the requirement django-filter==2.1.0

### ISSUE THREAD

**Issue by jonathanmf** [rtfd/readthedocs.org#5202]
## pip install -r requirements.txt is not working

When I `pip install -r requirements.txt`

## Actual Result

```
Collecting django-filter==2.1.0 (from -r requirements/pip.txt (line 14))
  Could not find a version that satisfies the requirement django-filter==2.1.0 (from -r requirements/pip.txt (line 14)) (from versions: 0.1.0, 0.2.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6a1, 0.6, 0.7, 0.8, 0.9.0, 0.9.1, 0.9.2, 0.10.0, 0.11.0, 0.12.0, 0.13.0, 0.14.0, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 2.0.0.dev1, 2.0.0)
No matching distribution found for django-filter==2.1.0 (from -r requirements/pip.txt (line 14))
```

When I change : 
```
# Filtering for the REST API
django-filter==2.2.0
```
TO 

```
# Filtering for the REST API
django-filter==2.0.0
```
Compiling is working but after I have an another issue with `python manage.py migrate`

```
   from configparser import RawConfigParser
ImportError: No module named configparser
```

Any issue with those packages?

Thx
Jonathan

**Comment by stsewd** [comment]
Do you mean installing the requirements from read the docs? https://github.com/rtfd/readthedocs.org/blob/master/requirements.txt

**Comment by davidfischer** [comment]
Based on your description, it looks like you're `pip install`-ing Read the Docs' requirements under Python2. As of Read the Docs 3.0, we only support Python 3.6+. https://docs.readthedocs.io/en/latest/changelog.html#version-3-0-0

**Comment by jonathanmf** [comment]
Definitely, python3 is working a lot better ;) thx everything is running fine now. Great support

**Comment by davidfischer** [comment]
I should mention that you can still build documentation with Python2. However, the RTD web interface requires Python 3.6+.

**Comment by jonathanmf** [comment]
I better understand ;) thanks again !
