### ISSUE TITLE
Transfer ownership of django-autoslug

### ISSUE THREAD

**Issue by justinmayer** [rtfd/readthedocs.org#5216]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/django-autoslug/
* Read the Docs username: jm

## Background

After announcing he no longer had adequate time to maintain the project, @neithere kindly transferred ownership of [django-autoslug](https://github.com/justinmayer/django-autoslug) to me. When I realized I needed access to other accounts (e.g., PyPI, ReadTheDocs) in order to issue new releases, I reached out several times to @neithere but did not receive a response. Knowing that he is busy and simply doesn't have time to reply, I then [filed an issue on the PyPI repo](https://github.com/pypa/warehouse/issues/5088), and the administrators helpfully [transferred ownership of the PyPI account](https://github.com/pypa/warehouse/issues/5088#issuecomment-447137695) shortly thereafter.

## Request

Having fully read the [associated policy](https://docs.readthedocs.io/en/latest/abandoned-projects.html), would you please assist me with this and transfer ownership of [this project](https://readthedocs.org/projects/django-autoslug/)?

**Comment by humitos** [comment]
I will take care of this in the following days.

**Comment by humitos** [comment]
Hi @justinmayer, considering the whole background that you linked here, I think there is no need to try to contact @neithere again and wait for 6 weeks. I will add you as mantainer of the `django-autoslug` project on Read the Docs.

You should be maintainer of the project under Read the Docs now.

Let me know if it works and feel free to re-open the issue if you consider.
