### ISSUE TITLE
Build error with Build id #8496699

### ISSUE THREAD

**Issue by bmeatayi** [rtfd/readthedocs.org#5217]
## Details
One of the requirements of my package is pybluez. During the build, it seems that a header file is missing:
fatal error: bluetooth/bluetooth.h: No such file or directory

On a local machine (Ubuntu), this issue can be solved by 'sudo apt-get install libbluetooth-dev'. So, I think adding this package to the docker image would solve the problem.

* Read the Docs project URL:
https://explorepy.readthedocs.io/en/latest/

## Expected Result
A successful build!

## Actual Result
"
Collecting pybluez (from explorepy==0.1.0->-r docs/requirements.txt (line 3))
...
Building wheels for collected packages: pybluez
  Building wheel for pybluez (setup.py): started
  Building wheel for pybluez (setup.py): finished with status 'error'
  Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/explorepy/envs/latest/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-o9kmgjtq/pybluez/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-ih35bkwy --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/btcommon.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/__init__.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/msbt.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/osx.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/ble.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/widcomm.py -> build/lib.linux-x86_64-3.5/bluetooth
  copying bluetooth/bluez.py -> build/lib.linux-x86_64-3.5/bluetooth
  running build_ext
  building 'bluetooth._bluetooth' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/bluez
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I./port3 -I/usr/include/python3.5m -I/home/docs/checkouts/readthedocs.org/user_builds/explorepy/envs/latest/include/python3.5m -c bluez/btmodule.c -o build/temp.linux-x86_64-3.5/bluez/btmodule.o
  In file included from bluez/btmodule.c:20:0:
  bluez/btmodule.h:5:33: fatal error: bluetooth/bluetooth.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by stsewd** [comment]
> sudo apt-get install libbluetooth-dev

That looks like a very specific case, not sure if we can install that in the docker images. Also, do you really need that dependency to build your docs? You can try mocking it https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by agjohnson** [comment]
I'd echo mocking out your dependencies, we don't support installing arbitrary packages for use cases like this. Closing this ticket as we won't support this library.
