### ISSUE TITLE
Unable to flag spam: can't find flagging option

### ISSUE THREAD

**Issue by wesinator** [rtfd/readthedocs.org#5218]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/windows-support-800-214-7840/
* Build URL (if applicable): 
* Read the Docs username (if applicable): https://readthedocs.org/profiles/paulisteni/

## Expected Result

Flag option on project page to report spam project
https://github.com/rtfd/readthedocs.org/blob/43073b15999d18f96532682ba838717521119abf/readthedocs/templates/projects/includes/flagging.html

## Actual Result

Logged in, trying to report the above project as spam, but I can't find anywhere to do it on the page.
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/5124946/52167271-a12e2400-26e6-11e9-996f-8a990eb9ace8.png">
The flagging in https://github.com/rtfd/readthedocs.org/blob/43073b15999d18f96532682ba838717521119abf/readthedocs/templates/projects/includes/flagging.html is not loaded anywhere

**Comment by agjohnson** [comment]
We don't have a feature for this and I don't think we will add this either. We don't have resources to continually remove spam projects, and automating this is a great way to open up ourselves to abuse. Closing this support and moving to #5227
