### ISSUE TITLE
Depedency install fails when using conda

### ISSUE THREAD

**Issue by gidden** [rtfd/readthedocs.org#5220]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyam-iamc/
* Build URL (if applicable): https://readthedocs.org/projects/pyam-iamc/builds/8491871/
* Read the Docs username (if applicable): gidden

I am attempting to build the [`pyam`](https://github.com/IAMconsortium/pyam/tree/rtd) project on RTD. I have some non-trivial depedencies (notably on mapping/GIS libraries) that require conda installation in order to get lower-level c libraries like `gdal`. Other projects seem to successfully build off of these dependencies, such as [`xarray`](https://github.com/pydata/xarray/blob/master/doc/environment.yml) (see a recent successful [build](https://readthedocs.org/projects/xray/builds/8454263/)). 

## Expected Result

Successful install of dependencies when using

```
conda:
  file: doc/environment.yml
```

With an `environment.yaml` looking like

```
name: pyam_docs
channels:
- conda-forge
dependencies:
- cartopy
- sphinx>=1.8
- sphinxcontrib-bibtex
- sphinxcontrib-programoutput
- sphinx-gallery
- nbsphinx
- numpydoc
- nbformat
- jupyter
- pillow
```

## Actual Result

The build hangs on the following command

```
conda env create --quiet --name rtd --file /home/docs/checkouts/readthedocs.org/user_builds/pyam-iamc/checkouts/rtd/doc/environment.yml
Solving environment: ...working...
Command time: 503s Return: 247
```

**Comment by gidden** [comment]
Perhaps manual rebuilding of docs would help? But it is not clear to me how to do that.

**Comment by stsewd** [comment]
You can trigger a manual build from the builds page https://readthedocs.org/projects/<your-project>/builds/. Also, I think this is related to the memory consumption from conda, so when the servers are busy it fails.

**Comment by gidden** [comment]
Ok, got it! I can now manually rebuild.

Regarding memory issues, that seems like a reasonable hypothesis. It seems like the failure rate is pretty high (I have tried manually a number of times now and cannot produce a successful result). Is there a way to mitigate this? Or am I stuck since I have a dependency requiring conda?
