### ISSUE TITLE
confirmation emails are not sending

### ISSUE THREAD

**Issue by svenevs** [rtfd/readthedocs.org#5221]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): `svenevs`

## Expected Result

I want to be able to verify the second e-mail on my account.  The current primary e-mail address `@gmail.com` is not the one I want to use.  I want to use the one that is `@school.edu`.

## Actual Result

No verification e-mails are sent to the desired e-mail address, meaning I cannot set that as my primary e-mail address (and eventually delete the other one).

If I need to share the actual e-mails here I can, but I'm just looking for help on sending the confirmation e-mail to the correct one.  If I had to guess, the conflict comes from the fact that when I originally signed up for RTD my GitHub username was different.  Before transferring ownership to this new username and deleting the old account, I looked inside the connected services and it showed GitHub with my old username.  I had some issues with Travis CI that related to an old cache flagging me because of the username change.

But I don't understand how that would affect RTD not sending the confirmation e-mail to me.  I've checked spam and every other folder besides Inbox, I'm 95% certain that there's something about this e-mail address that is preventing the confirmation e-mail from being sent.

Thank you for any help!

**Comment by stsewd** [comment]
Are you still having this problem?

**Comment by svenevs** [comment]
Hello, sorry for not responding.  I ended up just creating a new e-mail and committing to it since I couldn't get `.edu` to work.  I setup overly agressive filters and this went in a very not correct inbox :(
