### ISSUE TITLE
Build error with build id #8504705

### ISSUE THREAD

**Issue by ambroisemaupate** [rtfd/readthedocs.org#5223]
## Details:

* Project URL: https://readthedocs.org/projects/roadiz/
* Build URL(if applicable): https://readthedocs.org/projects/roadiz/builds/8504705/
* Read the Docs username(if applicable): roadiz

## Expected Result

Begin Sphinx compilation

## Actual Result

Compilation fails after doing a `git clean -d -f -f` but return code is `0`

**Comment by stsewd** [comment]
This is because you have an unused submodule in your project https://github.com/roadiz/docs/blob/master/.gitmodules See #4371

**Comment by humitos** [comment]
@stsewd why it should matter if the submodule is used or not?

I mean, we should be able to clone it no matter if the build uses it for building the docs or not.

The submodule looks valid to me.

**Comment by stsewd** [comment]
The submodule isn't in the project https://github.com/roadiz/docs, is the case of phantom submodules that makes gitpython fail

Also, I have a PR for this in gitpython https://github.com/gitpython-developers/GitPython/pull/818

**Comment by ambroisemaupate** [comment]
I don't understand it. This sub-module **is** used, it's our RTD theme which is stored in a different repository. It's mandatory for documentation compilation.

**Comment by ambroisemaupate** [comment]
Ok, compilation works fine after removing `.gitmodules` file. Our RTD theme is cloned in `conf.py` so no need to use git submodule anyway.

**Comment by humitos** [comment]
> Ok, compilation works fine after removing `.gitmodules` file. Our RTD theme is cloned in `conf.py` so no need to use git submodule anyway.

This a workaround, but not the real solution. Thanks for the update!

We need to find a proper solution for this, though.
