### ISSUE TITLE
Build error with conda

### ISSUE THREAD

**Issue by justusschock** [rtfd/readthedocs.org#5225]
## Details:
I need to build my docs with conda, because I need python 3.7. 

* Project URL: https://readthedocs.org/projects/delira/
* Build URL(if applicable): https://readthedocs.org/projects/delira/builds/8505294/
* Read the Docs username(if applicable): justusschock

## Expected Result
A successful build with conda and python 3.7

## Actual Result
The build successes with python 3.6 ([build #8505283](https://readthedocs.org/projects/delira/builds/8505283/); despite some sphinx warnings, which make python 3.7 necessary), but as soon as I switch to conda, I get the following error:
```
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8505294).
```

**Comment by stsewd** [comment]
Can you try wiping and building again? (Versions -> edit -> wipe). Also, maybe it's related to the memory consumption from conda. And, our next release will add support for python 3.7

**Comment by justusschock** [comment]
I already tried (and tried once again just to be sure). It failed again: [https://readthedocs.org/projects/delira/builds/8506706/](https://readthedocs.org/projects/delira/builds/8506706/)

**Comment by agjohnson** [comment]
This looks to be a bug, #5228. Closing this in favor of the bug report.
