### ISSUE TITLE
Build failing with a missing `tests.settings`

### ISSUE THREAD

**Issue by wgordon17** [rtfd/readthedocs.org#5229]
## Details

* Read the Docs project URL: https://awesome-django-timezones.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/awesome-django-timezones/builds/8510026/
* Read the Docs username (if applicable): wgordon17

## Expected Result

My project is a Django package, which imports the Django settings. Locally, I'm able to get things working by setting a `DJANGO_SETTINGS_MODULE environment variable that points to `tests.settings` (a directory and file in my git repo). Unfortunately, RTD can't seem to find the file when I set the environment variable, and removing the environment variable also doesn't work

    ImportError: No module named 'tests.settings'

## Actual Result

My assumption is that RTD is cloning my entire, which means `tests.settings` should be available? Unless it's under a different package name by chance?

**Comment by stsewd** [comment]
I think this is because the command is executed inside the `docs` folder, and the env variable is set relative to the root of the project. I'm proposing #4962 to avoid this things

**Comment by wgordon17** [comment]
Thank you @stsewd! That pointed me in the right direction! Adding a `__init__.py` to the `docs/` directory...and symlinking my `tests/settings.py` into the `docs/` repo as well...worked great! Oh, and I also changed my `DJANGO_SETTINGS_MODULE` to `docs.settings` instead of `tests.settings`.

Worked like a charm 👍
