### ISSUE TITLE
Trigger build through API

### ISSUE THREAD

**Issue by marcelstoer** [rtfd/readthedocs.org#5231]
I guess this is a feature request vor the v3 API.

## Expected Result

I can trigger a build through the API (POST or PUT).

## Actual Result

Function as per https://docs.readthedocs.io/en/stable/api/v2.html#builds not (yet) available.

**Comment by humitos** [comment]
Yes. APIv3 will support many "writable" actions. We are working on the design of it and its implementation.

If you want to give us feedback, ideas or anything that you consider that we should care about when making APIv3, please comment here: https://github.com/rtfd/readthedocs.org/issues/4286 and/or its PR: https://github.com/rtfd/readthedocs.org/pull/4863

I'm closing this issue.

**Comment by marcelstoer** [comment]
Then I suggest you link directly to those issues at https://docs.readthedocs.io/en/stable/api/v2.html where it says

> If there are features you would like in v3, please get in touch in the issue tracker.

Thanks for the pointer. Will take a look.
