### ISSUE TITLE
Build error with build id #8514783

### ISSUE THREAD

**Issue by justinshenk** [rtfd/readthedocs.org#5232]
## Details:

* Project URL: https://readthedocs.org/projects/traja/
* Build URL(if applicable): https://readthedocs.org/projects/traja/builds/8514783/
* Read the Docs username(if applicable): justinshenk

Break occurred soon after updating `.readthedocs.yml` to include

```
conda:
  environment: environment.yml
```

## Expected Result

A normal build.
## Actual Result
Quit after `git clean -d -f -f`.

**Comment by stsewd** [comment]
Your latest builds are passing now, are you still having this problem?

> Break occurred soon after updating `.readthedocs.yml` to include

```
conda:
  environment: environment.yml
```

I'm guessing it may be related to the excessive consumption of memory in conda

**Comment by justinshenk** [comment]
I no longer have the issue, thanks for following up.
