### ISSUE TITLE
Auto-wipe when env var is added/deleted

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5249]
If an environment variable is added from the Admin, it could happen that it doesn't change anything since no file is modified and Sphinx could ignore them.

A way that we can implement to avoid this is by saving the names of the environment variables for a project into our `readthedocs-environment.json` file. By doing that our current checking system for obsolete environment will detect it and auto-wipe the version.

**Comment by dojutsu-user** [comment]
Working on it.

**Comment by dojutsu-user** [comment]
@humitos 
I was working on it and I have some doubts about this.
* Names of the environment variables can be saved in `readthedocs-environment.json` file but for which version?

* > If an environment variable is added from the Admin
    
    Here `Admin` is referred to project admin, i.e. this url - `readthedocs.org/dashboard/<slug>/environmentvariables/` or Django admin?

**Comment by humitos** [comment]
> Names of the environment variables can be saved in `readthedocs-environment.json` file but for which version?

Each version contains its own `.json` file.

Supposing I build `latest` today with no env vars. It succeed. Immediately after it finished, I add a env var from the admin and build `latest` again. At this point, RTD should check the env vars in the `.json` file for `latest` version and if they are different wipe the environment before building.

Consider also saving not only the names but a hash of the values also --or maybe even better just _one_ hash of all the names together with the values. We don't really need to know the names nor the values, we just want to detect if any of them has changed.

> Here `Admin` is referred to project admin, i.e. this url - `readthedocs.org/dashboard/<slug>/environmentvariables/` or Django admin?

The first URL you mentioned. Project's admin accessible by a regular user.

**Comment by dojutsu-user** [comment]
@humitos 
Thank you for the explanation.
