### ISSUE TITLE
Compilation issue with build #8533245

### ISSUE THREAD

**Issue by respawner** [rtfd/readthedocs.org#5250]
## Details

* Read the Docs project URL: https://peering-manager.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/peering-manager/builds/8533245/
* Read the Docs username (if applicable): gmazoyer

## Expected Result

Doc is being generated without any errors.

## Actual Result

The build starts as usual and steps are being passed until the actual `mkdocs build` step. This step fails a `StopIteration` exception being raised.

**Comment by ericholscher** [comment]
This looks like a bug in your configuration, not something that is an issue with Read the Docs.

**Comment by stsewd** [comment]
Does it build locally? Also, it can be an incompatibility with python 3.7. We upgrade our default interpreter.

**Comment by respawner** [comment]
I tried building it locally, using python 3.7, with no luck same issue.

I can try building it with a python version prior to 3.7 if it can help.

**Comment by stsewd** [comment]
> I tried building it locally, using python 3.7, with no luck same issue.

Then, looks like a problem outside read the docs. We can close this issue if so.

**Comment by respawner** [comment]
> > I tried building it locally, using python 3.7, with no luck same issue.
> 
> Then, looks like a problem outside read the docs. We can close this issue if so.

I tried compiling it using python 3.5 and it works fine.

```
# python .venv/bin/mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /root/test/_build/html
# ls _build/html
404.html  config-template  css  fonts  img  index.html  integration  js  man  search  search.html  setup  sitemap.xml
`
``

**Comment by stsewd** [comment]
You can change the python interpreter using a configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by respawner** [comment]
It works with the following configuration:

```
version: 2

python:
  version: 3.5

mkdocs:
  configuration: mkdocs.yml
```

I guess this issue can be closed.
