### ISSUE TITLE
Build error with build id #8538507 

### ISSUE THREAD

**Issue by nukappa** [rtfd/readthedocs.org#5257]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/novosparc-nukappa

## Actual Result

Build fails when it tries to import/compile POT with the following error

``Collecting POT (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/28/4b/7aaa1f840a359f5953dd378e0237fa8faf9b0a415ff7282b7375fbe68d27/POT-0.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ig3rvxtc/POT/setup.py", line 7, in <module>
        from Cython.Build import cythonize
    ModuleNotFoundError: No module named 'Cython'``

Cython is stated in the `requirements.txt` file, which is read normally before:

``
Collecting Cython (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/7c/29/f93ddb609d9f81eade237d36c102fd1d3838da7847b45a2cae0fde9db76a/Cython-0.29.4-cp37-cp37m-manylinux1_x86_64.whl
``

**Comment by stsewd** [comment]
Maybe this can help https://github.com/rtfd/readthedocs.org/issues/5297#issuecomment-464495686

**Comment by nukappa** [comment]
Solved this by adding a `requirements.txt` file inside the docs and omitting any library that needs to be C++ compiled.
