### ISSUE TITLE
Build error with build id #8539595

### ISSUE THREAD

**Issue by sriharikarnam** [rtfd/readthedocs.org#5258]
## Details:

* Project URL: https://readthedocs.org/projects/ROCm Documentation/
* Build URL(if applicable): https://readthedocs.org/projects/rocm-documentation/builds/8539595/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Your latest builds are passing now, are you still having this problem?
