### ISSUE TITLE
Can't find resyncing instructions

### ISSUE THREAD

**Issue by Juanlu001** [rtfd/readthedocs.org#5260]
> I think that "manually re-syncing" relying on the user is not a solution.

(https://github.com/rtfd/readthedocs.org/issues/5062#issuecomment-451094602)

Talking about "manually re-syncing", [the webhooks docs mention](https://docs.readthedocs.io/en/latest/webhooks.html#resyncing-webhooks)

> To resync a webhook from Read the Docs, visit the integration detail page and follow the directions for re-syncing your repository webhook.

But I don't see such a thing in, for example, https://readthedocs.org/dashboard/poliastro/integrations/57915/.

**Comment by Juanlu001** [comment]
In reality, this is a follow-up from my comment at https://github.com/rtfd/readthedocs.org/issues/4450#issuecomment-450150930, since I again pushed a branch to my GitHub repository and the build was not triggered, although the event was received:

https://readthedocs.org/dashboard/poliastro/integrations/57915/exchange/bac1718a-b4f4-4f64-b7a1-1e20dd51e9d5/

**Comment by humitos** [comment]
> But I don't see such a thing in, for example, [readthedocs.org/dashboard/poliastro/integrations/57915](https://readthedocs.org/dashboard/poliastro/integrations/57915/).

When I go to my Admin > Integrations > GitHub incoming webhook I see a button there that says "Resync webhook". Does not appear to you? Clicking it should resync the webhook and subscript to the new GH events.

Also, please check that your webhooks in GH are properly configured after that at https://github.com/poliastro/poliastro/settings/hooks

Example,

![captura de pantalla_2019-02-09_23-09-19](https://user-images.githubusercontent.com/244656/52526894-0d4cf100-2cc0-11e9-910e-dd2bf8ccdda4.png)

The first one is the proper one, which is subscribed to **create, delete, pull_request and push** the second one is the old one. Yours, should look like the first one. Let me know!

**Comment by Juanlu001** [comment]
> When I go to my Admin > Integrations > GitHub incoming webhook I see a button there that says "Resync webhook". Does not appear to you?

Not really:

![screenshot_2019-02-09 integration read the docs](https://user-images.githubusercontent.com/316517/52527282-396b7080-2cc6-11e9-9f21-270647bd0015.png)

My webhook on GH looks like the first one, but it was not subscribed to pull requests, so I amended that already.

**Comment by humitos** [comment]
OK! My webhook page looks different

![captura de pantalla_2019-02-10_11-41-31](https://user-images.githubusercontent.com/244656/52532671-0f976580-2d29-11e9-92f7-5ac1f67a0f3f.png)

Taking a look at the code, that's because your integration's attribute `can_sync` is `False`. 

https://github.com/rtfd/readthedocs.org/blob/cb1f941825a320daa321b87d1fd5460badfccd3b/readthedocs/templates/projects/integration_webhook_detail.html#L32-L49

I'm not sure what that means yet

https://github.com/rtfd/readthedocs.org/blob/cb1f941825a320daa321b87d1fd5460badfccd3b/readthedocs/integrations/models.py#L282-L286

I checked the `provider_data` for your integration and it's `''`. So, that's the reason.

Now, I need to find out how `''` ended up there. I'll keep you updated.

> My webhook on GH looks like the first one, but it was not subscribed to pull requests, so I amended that already.

If only `pull requests` was missing, I suppose that you still have experimenting the problem of creating a new branch and don't see it reflected on RTD as a Version, right?

**Comment by Juanlu001** [comment]
> I suppose that you still have experimenting the problem of creating a new branch and don't see it reflected on RTD as a Version, right?

Correct! But I guess the culprit is that my webhook is not synced. Thanks for looking into this!

**Comment by agjohnson** [comment]
The resync option is only available if the webhook was set up using a connected GitHub account. If you disconnected your GitHub account, or reconnected, I'm not sure of the behavior. But, without this connected account, we can't attempt the API operations to resync the webhook, so it's a manual configuration piece that you need to handle on GitHub.

Is you GitHub account connected to your RTD account, and does that GH user have access to the admin of the repository?

**Comment by Juanlu001** [comment]
@agjohnson I just logged out and logged in with my GH account just to try and it worked, and this user has access to the admin of the repository.

**Comment by stsewd** [comment]
We only show this button if the repo was imported using the `import from repo` option, if the project was manually imported, or the webhook was deleted and add it again, it doesn't show the `Resync option`.

Probably we can close this in favor of https://github.com/rtfd/readthedocs.org/issues/3932. Or clarify the docs in the meantime.

**Comment by humitos** [comment]
Do we have a proposed workaround in the meantime? I'd like to give a solution to @Juanlu001 and other people hitting this problem.

**Comment by stsewd** [comment]
I think there is a confusion with the feature that @Juanlu001 is mentioning

> since I again pushed a branch to my GitHub repository and the build was not triggered, although the event was received

We currently listen to create/delete events to update the versions list of a project. Users still need to activate and trigger a build to new branches. If you want that feature, keep an eye in #4001

**Comment by humitos** [comment]
@stsewd oh, I think you are right.

@Juanlu001 the new feature regarding how we handle webhooks on Read the Docs was about "detecting that a new branch/tag was added into the repo and create a Version for it" (not activated --which won't build by default, though). Can you confirm that the new branch created in the repo was automatically detected and added as a version on RTD?

**Comment by Juanlu001** [comment]
If I recall correctly, the new branch didn't create a new version, although it eventually did when I pushed more commits to it.

If I understand correctly there's some progress in https://github.com/rtfd/readthedocs.org/issues/4001 by @stsewd, so let's revisit this when I branch my project again. If you don't want to keep an issue open until July, let's close it and I will comment here if I have further problems.

**Comment by stsewd** [comment]
Maybe it was in a github downtime or in our servers downtime. You can revisit the webhooks page (on github and rtd) to see if the webhook was correctly handled. Let's close this for now, let us know if something doesn't work.

**Comment by Helveg** [comment]
It seems like resyncing is broken for projects that don't have a `.readthedocs.yaml` file. All webhooks then return

```
{"build_triggered":false,"project":"nmodl-glia","versions":[], "versions_synced": false}
```

Note the last field, which dissapears once you add the yaml
