### ISSUE TITLE
Custom domain throwing an SSL error

### ISSUE THREAD

**Issue by palewire** [rtfd/readthedocs.org#5261]
## Details

* Read the Docs project URL: https://www.firstpythonnotebook.org/
* Read the Docs username (if applicable): palewire

## Expected Result

The custom domain should serve via SSL.

## Actual Result

An SSL error.

![screenshot from 2019-02-10 16-02-38](https://user-images.githubusercontent.com/9993/52541752-9827fd00-2d4d-11e9-8885-81a95c039dba.png)

I believe I have my CNAME record set correctly. Seen here.

![screenshot from 2019-02-10 16-05-16](https://user-images.githubusercontent.com/9993/52541760-ad049080-2d4d-11e9-9dcf-155877e59f39.png)

**Comment by stsewd** [comment]
Looks fine from my side, are you still having this issue?

**Comment by palewire** [comment]
Looks like it's working now. I don't know why, but I'm happy!
