### ISSUE TITLE
google-auth is orphaned

### ISSUE THREAD

**Issue by theacodes** [rtfd/readthedocs.org#5266]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/google-auth
* Build URL (if applicable):
* Read the Docs username (if applicable): theacodes

## Expected Result

*A description of what you wanted to happen*

I should be able to manage the google-auth project.

## Actual Result

*A description of what actually happened*

It appears to be orpaned and has no maintainers. This probably happened as a result of me deleting my old account as detailed in #4576.

I'm happy to verify my identity via whatever means y'all want.

**Comment by humitos** [comment]
> This probably happened as a result of me deleting my old account as detailed in #4576.

I'm almost sure that this was the case. I'm re-adding you as maintainer.

**Comment by humitos** [comment]
@theacodes done! You should have access to the project now. I'm closing the issue, but feel free to reopen if it does not work as you expects. Thanks!

**Comment by theacodes** [comment]
All seems well, thank you!
