### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for gwcelery

### ISSUE THREAD

**Issue by lpsinger** [rtfd/readthedocs.org#5267]
One of my projects (gwcelery) has a large number of commits between versions. As a consequence of readthedocs doing a shallow fetch of my repository, the tags are not present and the version number which is detected by Versioneer is set to 0.

I read in the [Readthedocs documentation](https://docs.readthedocs.io/en/latest/guides/feature-flags.html#available-flags) that there is a feature flag to disable shallow cloning on a pre-repo basis. Please set the `DONT_SHALLOW_CLONE` feature flag for my repo.

 ## Details

* Read the Docs project URL: https://readthedocs.org/projects/gwcelery/
* Build URL (if applicable): https://readthedocs.org/projects/gwcelery/builds/8560028/
* Read the Docs username (if applicable): lpsinger

## Expected Result

The title of my Latest documentation should be `gwcelery 0.2.5+101.gb194402 documentation`. The version number is deduced by Versioneer looking at the most recent tag and at the commit hash of the tip of master.

## Actual Result

The title of my Latest documentation is `gwcelery 0 documentation`, because the most recent tag was over 50 commits ago and was pruned away by the shallow fetch.

**Comment by humitos** [comment]
@lpsinger this is done! Enjoy Read the Docs.

Let me know if this works as you expected. Thanks!
