### ISSUE TITLE
Project stopped having its builds run on Git push without warning

### ISSUE THREAD

**Issue by timabbott** [rtfd/readthedocs.org#5268]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/zulip/builds/
* Build URL (if applicable):
* Read the Docs username (if applicable): zulip

## Expected Result

When we push new changes to our Git master branch, a ReadTheDocs build is triggered.

## Actual Result

Builds seem to now only run manually (I just triggered a manual build to fix our docs right now), starting apparently 6 weeks ago:

![image](https://user-images.githubusercontent.com/2746074/52611334-0518c100-2e3a-11e9-9c25-35cdfe41f58a.png)

I administer our GitHub

**Comment by dojutsu-user** [comment]
I think this is because the deprecated github services. You might have received an email #4898.
Docs: https://docs.readthedocs.io/en/latest/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by timabbott** [comment]
Ahh, that would do it.  I searched my email, and didn't get that email from GitHub; weird.  

Anyway, thanks for the fast support!

**Comment by dojutsu-user** [comment]
That's great. :+1: 
Feel free to open another issue if the problem still persists.
