### ISSUE TITLE
Build error with build id #8574742

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#5287]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ginga/
* Build URL (if applicable): https://readthedocs.org/projects/ginga/builds/8574742/
* Read the Docs username (if applicable): pllim

We have recently switched from specifying a separate pip requirement file to using https://github.com/ejeschke/ginga/blob/master/readthedocs.yml with dependencies defined in https://github.com/ejeschke/ginga/blob/962ef1a0c341daf6668de9a5663b1beff6c79dcf/setup.cfg#L53-L54 
(ejeschke/ginga#739). We have also switched from GitHub Services to using webhooks (ejeschke/ginga#744). I actually don't think the webhook switch has anything to do with this error, but rather the switch from requirements to YML broke something that was not triggered because GitHub Services stopped working.

Any help would be greatly appreciated. Thanks!

cc @ejeschke

## Expected Result

Successful build.

## Actual Result

Build failed with a cryptic and ironic "successful" message:

```
Successfully installed Jinja2-2.10 MarkupSafe-1.1.0 ...
```

**Comment by pllim** [comment]
FWIW, I tried wiping the "latest" build twice but without success.

**Comment by pllim** [comment]
Doh, there was a missing quote in the YAML! Sorry for the noise. 😬

**Comment by stsewd** [comment]
Hmm, we should give a better error though

**Comment by stsewd** [comment]
So, when parsing the yaml, this generates `['recomended', "docs'"]` It adds the `'` to the element, so the error comes from another step. So, I think a better hint is https://github.com/rtfd/readthedocs.org/issues/4288
