### ISSUE TITLE
The "versions" list is ordered in a weird way

### ISSUE THREAD

**Issue by facundobatista** [rtfd/readthedocs.org#5291]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fades/
* Build URL (if applicable): 
* Read the Docs username (if applicable): facundobatista

## Expected Result

The "versions" list be easily consumable by human.

## Actual Result

The "version" list is ordered alphabetically, but reversed, and giving numbers priority over letters.

**Comment by stsewd** [comment]
That's how it supposed to be, we have that order to select the `stable` version. So, most of the time people want to select a recent version.

**Comment by facundobatista** [comment]
If most of the time people want to select a recent version, why not to order it by the commit's timestamp? that's real "recentness", not second-guessing by the tag name...

**Comment by stsewd** [comment]
See https://github.com/rtfd/readthedocs.org/issues/5151

**Comment by facundobatista** [comment]
I saw #5151, it's a branch about applying a "smart" sort to this list.

My point (unanswered here) is that if people want to select a recent version (@stsewd words above) why not sorting about commit timestamp?

**Comment by stsewd** [comment]
We don't save that information in the db as far as I know

**Comment by stsewd** [comment]
We discussed this with the team, and we decided that sort by senver is the best path.

**Comment by humitos** [comment]
A hacky implementation for this is happening at https://github.com/readthedocs/readthedocs.org/pull/6680
