### ISSUE TITLE
API documentation missing after successful build

### ISSUE THREAD

**Issue by pevogam** [rtfd/readthedocs.org#5295]
## Details

* Read the Docs project URL: https://guibot.readthedocs.io/en/latest/source/guibot.guibot.html
* Build URL (if applicable):
* Read the Docs username (if applicable): pevogam

## Expected Result

I expect the docstrings from each module to be shown just like they are shown at the stable version of the same source code:

https://guibot.readthedocs.io/en/stable/source/guibot.guibot.html

## Actual Result

Nothing is shown, the modules appear to be empty on the web page. The build of "latest" is successful and indicates no error. No changes related to the API were undertaken between "stable" and "latest".

**Comment by stsewd** [comment]
Looks like the latest build was about 6 months ago. Anyway, I can see some warnings in the sphinx build step https://readthedocs.org/projects/guibot/builds/7548040/, looks like is because of the python version (is using 2.7), you can use a configuration file to use python 3 https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by pevogam** [comment]
The build is six months old but I have recent builds on another project using similar setup with the same end result.

Interesting observation about the python version - shouldn't such incompatibility be and immediate error that will fail the build? Also, at the present we don't have any custom configuration in place which probably means a default configuration should be assumed. Reading from your link above, the default assumed python version should be 3 (also the version for the project) so I am not sure where does the assumption of python 2.7 come from. Does the RTD compilation process perform some extra heuristics to detect the python version?

**Comment by stsewd** [comment]
That's the new default, previous default was python 2, which you can change from the admin panel of your project, or by using a configuration file.

**Comment by stsewd** [comment]
And we don't fail on warning, but there is an option to turn warnings into failures in the configuration file

**Comment by pevogam** [comment]
Yes, what I meant was why using the wrong python version is a warning and not an error on the first place (especially on major version change) but it might make sense for most projects out there.

The advised fix worked well, thanks a lot!
