### ISSUE TITLE
Cannot install dependency that imports cython

### ISSUE THREAD

**Issue by david-cortes** [rtfd/readthedocs.org#5297]
I have this package here:
https://www.github.com/david-cortes/ctpfrec

Which has as a dependency this other package:
https://www.github.com/david-cortes/hpfrec

Both of these packages depend on cython and import it within `setup.py`. The second package currently builds just fine in RTD and has its documentation hosted there.
The first package was building fine a couple months ago, but today it fails to install the second one as a dependency due to not being able to import cython, even though the second one builds just fine when it’s the main package rather than a dependency.
This is the error thrown:
```
Collecting hpfrec (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/7f/6b/4dfdfaad114faaf75228ce4b9f03f264738fd53e7ce9253288eeb86ca06d/hpfrec-0.2.2.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-guHwJq/hpfrec/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
```

This is despite both packages listing `cython` as a dependency in `requirements.txt`.

**Comment by david-cortes** [comment]
BTW, also happens with this other one: Build #8592946
this package: https://www.github.com/david-cortes/contextualbandits
fails to install this other pacakge: https://www.github.com/david-cortes/costsensitive
while the second one has its documentation building just fine.

**Comment by stsewd** [comment]
Same issue (or related) as https://github.com/rtfd/readthedocs.org/issues/5257. Our mayor change was to default to python 3.7 recently, I can guess that has something to do with this problem? You can use a configuration file to change the python version https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by david-cortes** [comment]
> Same issue (or related) as #5257. Our mayor change was to default to python 3.7 recently, I can guess that has something to do with this problem? You can use a configuration file to change the python version https://docs.readthedocs.io/en/stable/config-file/v2.html

No, that didn't help, I tried changing it back to Python 3.5 which was the version under which it latest built, but it still threw the same error. Moreover, the dependency that imports Cython has its documentation building just fine when it is the main package (with Python 3.7).

Some google search suggests it might be a problem with the `path` variable not set up adequately.

**Comment by nukappa** [comment]
Hi, just wanted to tell you that I solved a similar problem I had by simply adding a `requirements.txt` inside the docs which omits any libraries that need C++ compiling. Maybe that helps. #5257

**Comment by david-cortes** [comment]
> Hi, just wanted to tell you that I solved a similar problem I had by simply adding a `requirements.txt` inside the docs which omits any libraries that need C++ compiling. Maybe that helps. #5257

Well, that “solves” the issue for the majority of use cases – same as using `mock` for them – but still:
* If subclassing something from the package that has Cython code, those methods wouldn’t end up being documented.
* There was no problem importing `Cython.Distutils` within dependencies in RTD environement 6 months ago – would be nicer to have it behave like before.

**Comment by david-cortes** [comment]
In response to the bot @stale, the issue is still present.

**Comment by humitos** [comment]
@david-cortes it's hard to debug those builds without the links to them. Can you update your comments to put the proper links on those numbers? Thanks!

At this point, I don't understand why this is a problem on Read the Docs and not with the package itself.

**Comment by david-cortes** [comment]
@humitos If you mean the build links, here are some:

Let’s call this pakcage A:
https://readthedocs.org/projects/ctpfrec/builds/8596895/
In the link above, package A fails to install due to a dependency failing to install from `pip` – let’s call that one package B. Specifically, when the RTD environment tried to install package B, it fails at this line:
```python
from Cython.Distutils import build_ext
```

Now this is package B also building in RTD:
https://readthedocs.org/projects/hpfrec/builds/8585741/
In the link above, package B built successfully in RTD, and today still builds without problems, despite the import above which failed when B was a dependency of A.

This was package A building fine 7 months ago:
https://readthedocs.org/projects/hpfrec/builds/8585741/
Back then, it still had the same package B as dependency, which had the same problematic import. Nothing was changed in the build configuration, and trying to build it today with the same Python version with which it was building fine 7 months ago (Python 3.5) does not make any difference.

As for why I’d say it’s a problem with RTD:
a) There was no issue with previous RTD versions.
b) The problem only exists when a package that builds fine in RTD appears as dependency of another package.
c) It happens with different packages and not with just those 2.

**Comment by humitos** [comment]
Are you able to install all those requirements in your local computer with pip into a virtualenv?

After installing those reqs, can you execute the `from ... import` line? Does it work?

Using the same virtualenv, can you build the docs locally?

Those are the questions that I'm interested on having an answer.

From my point of view it's a problem on how the packages are packaged. `hpfrec` fails when trying to be installed with pip outside RTD.

```
~ ⌚ 8:24:05
$ python -m venv testenv

~ ⌚ 8:24:11
$ source testenv/bin/activate
(testenv) 
~ ⌚ 8:24:20
$ pip install hpfrec
Collecting hpfrec
  Using cached https://files.pythonhosted.org/packages/7f/6b/4dfdfaad114faaf75228ce4b9f03f264738fd53e7ce9253288eeb86ca06d/hpfrec-0.2.2.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dv_v5071/hpfrec/setup.py", line 3, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-dv_v5071/hpfrec/
(testenv) 
~ ⌚ 8:24:30
```

**Comment by david-cortes** [comment]
@humitos Yes, I'm able to install `hpfrec` through `pip`, and can build the docs locally with `setuptools`, `distutils`, and `pip`. You can also  check that `cython` is among the package requirements:
https://github.com/david-cortes/hpfrec/blob/master/requirements.txt
https://github.com/david-cortes/hpfrec/blob/master/setup.py

And is also among the requirements for the package that depends on `hpfrec`:
https://github.com/david-cortes/ctpfrec/blob/master/requirements.txt
https://github.com/david-cortes/ctpfrec/blob/master/setup.py

I tried a `pip` install in different computers and OSes and in all cases it worked fine. Here's the output from installing it in a new environment:
```
david@debian:~$ conda create -n testenv python=3.7
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.8
  latest version: 4.6.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/david/anaconda3/envs/testenv

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.7.3               |       h0371630_0        36.7 MB
    ------------------------------------------------------------
                                           Total:        36.7 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/linux-64::certifi-2019.3.9-py37_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1b-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.0.3-py37_0
  python             pkgs/main/linux-64::python-3.7.3-h0371630_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-40.8.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.27.2-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.1-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y


Downloading and Extracting Packages
python-3.7.3         | 36.7 MB   | ############################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > conda activate testenv
#
# To deactivate an active environment, use:
# > conda deactivate
#

david@debian:~$ source activate testenv     
(testenv) david@debian:~$ pip install hpfrec
Collecting hpfrec
Collecting numpy (from hpfrec)
  Downloading https://files.pythonhosted.org/packages/91/e7/6c780e612d245cca62bc3ba8e263038f7c144a96a54f877f3714a0e8427e/numpy-1.16.2-cp37-cp37m-manylinux1_x86_64.whl (17.3MB)
    100% |████████████████████████████████| 17.3MB 835kB/s 
Collecting pandas>=0.21 (from hpfrec)
  Using cached https://files.pythonhosted.org/packages/22/e6/2d47835f91eb010036be207581fa113fb4e3822ec1b4bafb0d3d105fede6/pandas-0.24.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting scipy (from hpfrec)
  Downloading https://files.pythonhosted.org/packages/3e/7e/5cee36eee5b3194687232f6150a89a38f784883c612db7f4da2ab190980d/scipy-1.2.1-cp37-cp37m-manylinux1_x86_64.whl (24.8MB)
    100% |████████████████████████████████| 24.8MB 810kB/s 
Collecting cython (from hpfrec)
  Using cached https://files.pythonhosted.org/packages/ab/1b/85223a9d7d39ea8d0dec76785ef5e2aa7a82a3eaa92cb7becd2a64cef663/Cython-0.29.6-cp37-cp37m-manylinux1_x86_64.whl
Collecting python-dateutil>=2.5.0 (from pandas>=0.21->hpfrec)
  Downloading https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl (226kB)
    100% |████████████████████████████████| 235kB 142kB/s 
Collecting pytz>=2011k (from pandas>=0.21->hpfrec)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.5.0->pandas>=0.21->hpfrec)
  Downloading https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Installing collected packages: numpy, six, python-dateutil, pytz, pandas, scipy, cython, hpfrec
Successfully installed cython-0.29.6 hpfrec-0.2.2.13 numpy-1.16.2 pandas-0.24.2 python-dateutil-2.8.0 pytz-2018.9 scipy-1.2.1 six-1.12.0
```

**Comment by nsheff** [comment]
@david-cortes what ended up being the way to solve this? I'm facing a similar issue, and I see that your builds work now after you fixed something, but I can't figure out what your actual solution was...

**Comment by david-cortes** [comment]
@nsheff : the solution was to use PEP518 and have cython as a build-time requirement, which is added through a file `pyproject.toml`, but this "solution" brings its own issues along. Works fine for readthedocs nevertheless.

The other "solution" is to mock the whole cython module in the `config.py` file for readthedocs, but that doesn't solve it for `pip`.

**Comment by nsheff** [comment]
For the PEP518 solution, Hmm, I tracked that at this commit, https://github.com/david-cortes/ctpfrec/commit/e0a2e2bbf3b41a2e7d166da2ab51fb33f0fbe725
which was the first to build successfully on RTD, but how did you get RTD to recognize the pyproject.toml file? Is there any other setting you have to change? I tried this but it didn't solve the problem in my build, which still says `ModuleNotFoundError: No module named 'Cython'` (https://readthedocs.org/projects/bedshift/builds/13510677/) The toml file is:

```
[build-system]
requires = ["cython", "setuptools", "wheel"] 
```
https://github.com/databio/bedshift/blob/dev/pyproject.toml

RTD doesn't seem to acknowledge it

**Comment by david-cortes** [comment]
@nsheff : Yes, you also need to add that file to `MANIFEST.IN` to include it in the package.

**Comment by nsheff** [comment]
Ok, thank you, I got it to work -- I had to use the toml file in the dependency package that requires cython.

Also, it doesn't look like it's included in your manifest: https://github.com/david-cortes/ctpfrec/blob/master/MANIFEST.in

Anyway, thanks for your help!
