### ISSUE TITLE
Extra slash in "Edit on GitHub" link

### ISSUE THREAD

**Issue by mahmoud** [rtfd/readthedocs.org#5303]
## Details

* Read the Docs project URL: http://glom.readthedocs.io/
* GitHub URL: https://github.com/mahmoud/glom
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): mahmoud

## Expected Result

"Edit on GitHub" link at the top of the page should link to doc on GitHub.

## Actual Result

"Edit on GitHub" link at the top of the page links to 404. There is an extra slash in the URL: `https://github.com/mahmoud/glom//master/docs/index.rst` (after `glom`, before `master`)

Interestingly, the "Edit" link in the bottom left menu seems to work fine.

**Comment by rexzing** [comment]
Hi magnunleno,
I don't think it happens because of the extra slash but because of the missing word `blob`. The url should be `https://github.com/mahmoud/glom/blob/master/docs/index.rst`. Isn't it?

**Comment by stsewd** [comment]
Can you try updating the rtd-theme? https://github.com/mahmoud/glom/blob/5a10e66c2f1204988f97e6545055bfc5b36e052f/requirements-rtd.txt#L36 Current one is `0.4.3` https://pypi.python.org/pypi/sphinx_rtd_theme

**Comment by mahmoud** [comment]
@rexzing you're absolutely right!

@stsewd trying this now, thanks!

**Comment by mahmoud** [comment]
@stsewd Hmm, no luck I'm afraid. In fact, I see 3 slashes now: `https://github.com/mahmoud/glom///master/docs/index.rst`.

**Comment by stsewd** [comment]
Thanks, I'll try to replicate this locally and dig a little more

**Comment by mahmoud** [comment]
Whoops, I lied, did stuff on the wrong local branch. Updating the theme got me a working link, with blob, but it does have an extra slash fwiw: `https://github.com/mahmoud/glom//blob/master/docs/index.rst`

It still gets me to GitHub though, so I'm happy enough! :) Thanks for your help!

**Comment by stsewd** [comment]
The extra slash is from the repo url, we could strip it, tho

**Comment by mahmoud** [comment]
I'll leave it up to you, but I think an rstrip and join of a single slash should yield a nicely normalized URL. :)

**Comment by mahmoud** [comment]
@ststewd Thank you!
