### ISSUE TITLE
Incompatible dependency for prospector with pylint-django

### ISSUE THREAD

**Issue by rexzing** [rtfd/readthedocs.org#5304]
When installing `requirements/lint.txt` I got the error `prospector 1.1.6.2 has requirement pylint-django==2.0.2, but you'll have pylint-django 2.0.4 which is incompatible`.

**Comment by stsewd** [comment]
Can you please give more details? Where are you seeing this problem? What error is this causing?

**Comment by rexzing** [comment]
Sorry for the details I miss-pressed the enter button. I think I can fix this by changing `pylint-django<2.0.5 ` to `pylint-django==2.0.4 `

**Comment by rexzing** [comment]
Should I make a PR?

**Comment by stsewd** [comment]
Yes, it should be https://github.com/PyCQA/prospector/blob/8bb1970aa31b962291ef0cff4b757a34aa566298/setup.py#L38
