### ISSUE TITLE
conda env takes too long to be loaded

### ISSUE THREAD

**Issue by doutriaux1** [rtfd/readthedocs.org#5310]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cdat-vcs

* Build URL (if applicable): https://readthedocs.org/projects/cdat-vcs/builds/8575975/

* Read the Docs username (if applicable): cdoutrix

## Expected Result

*A description of what you wanted to happen*

The doc build takes almost no time but creating the env seem to take so long it times out or something similar

## Actual Result

*A description of what actually happened*

build timed out

**Comment by stsewd** [comment]
Yes, this is a known problem in conda, not much we can do about this from our side. And your conda file looks really heavy https://github.com/CDAT/vcs/blob/master/environment.yml, between more channels conda is slower.

**Comment by doutriaux1** [comment]
@stsewd I'll tried to minimize channels didn't seem to help much. Somewhere on readthedocs website it says we can get an exemption (or longer build time). Do you know who to contact about it? Thanks.

**Comment by stsewd** [comment]
This same issue works, just need to wait for a maintainer.

**Comment by humitos** [comment]
Assigning this one to myself to take a look in the following days, hopefully.

**Comment by humitos** [comment]
I jumped into this today but I found that your build is failing because a package is not found: https://readthedocs.org/projects/cdat-vcs/builds/8665155/

Although, I put your project into a queue with more resources. Use this power accordly ;)

Feel free to reopen the issue if it still does not build properly. Also, I'd appreciate an update here if it does work.

**Comment by doutriaux1** [comment]
@humitos thank you so much, will be using this power VERY carefully! I appreciate this!

**Comment by doutriaux1** [comment]
@humitos it still seems to take too long. see: https://readthedocs.org/projects/cdat-vcs/builds/8666237/
At this point I'm not sure what to do... Can we manually upload the documentation?

**Comment by humitos** [comment]
It's not a problem of time consumed, but memory.

247 exit code is a problem known for conda devs (there are some history on RTD issues about this --you can do a search on the issues).

I'm not sure if there are anything else we can do from Read the Docs.

Are you able to build your docs locally? Can you measure how much memory and time it takes? People from conda has shared this with us in the past: https://conda.github.io/conda-benchmarks/

> Can we manually upload the documentation?

Not yet. See #1083

**Comment by doutriaux1** [comment]
Thanks I will look into this! I appreciate the feedbacks.
