### ISSUE TITLE
Missing JavaScript files

### ISSUE THREAD

**Issue by Peque** [rtfd/readthedocs.org#5316]
## Details

* Read the Docs project URL: https://bulebule.readthedocs.io/en/sphinxcadquery/building.html
* Build URL (if applicable): https://readthedocs.org/projects/bulebule/builds/8614142/
* Read the Docs username (if applicable): Peque

## Expected Result

`_static/thingiview/xxxx.js` files are accesible/served. When I build the documentation locally, that is the case.

## Actual Result

It seems `_static/thingiview/xxxx.js` files are missing and RtD replies with a 404 error.

## Notes

These files are copied to `_static/thingiview/` by this extension:

https://github.com/Peque/sphinxcadquery

Note I am not sure if:

- The files are actually there on RtD, but not served (only returning a 404)
- The files are directly not copied to `_static`, in which case I do not know why it would work locally but not remotely

Do you have any ideas/suggestions on how to proceed to fix/debug this?

**Comment by stsewd** [comment]
Which version of sphinx are you using locally?

**Comment by Peque** [comment]
@stsewd 1.8.4.

**Comment by Peque** [comment]
I am essentially using the same Conda environment configuration file that Read the Docs is using:

https://github.com/Bulebots/bulebule/blob/sphinxcadquery/environment.yaml

Read the Docs is then provided with:

https://github.com/Bulebots/bulebule/blob/sphinxcadquery/.readthedocs.yaml

**Comment by davidfischer** [comment]
Looking at the build output, I can see it tried to install sphinxcadquery 0.3.0:

```
...
Collecting sphinxcadquery (from -r /home/docs/checkouts/readthedocs.org/user_builds/bulebule/checkouts/sphinxcadquery/condaenv.jlxucw.requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/5d/87/51c81890eb58f97371f202d28c5c601e1752105d70329ada719f136cd36c/sphinxcadquery-0.3.0.tar.gz
...
```

However, the file on PyPI does not contain those JavaScript files:

```
$ wget https://files.pythonhosted.org/packages/5d/87/51c81890eb58f97371f202d28c5c601e1752105d70329ada719f136cd36c/sphinxcadquery-0.3.0.tar.gz
$ tar tvfz sphinxcadquery-0.3.0.tar.gz
drwxrwxr-x  0 peque  peque       0 Feb 19 15:15 sphinxcadquery-0.3.0/
-rw-rw-r--  0 peque  peque     703 Feb 19 15:15 sphinxcadquery-0.3.0/PKG-INFO
-rw-rw-r--  0 peque  peque    1135 Feb 19 11:28 sphinxcadquery-0.3.0/README.rst
-rw-rw-r--  0 peque  peque      38 Feb 19 15:15 sphinxcadquery-0.3.0/setup.cfg
-rw-rw-r--  0 peque  peque    1020 Feb 19 11:23 sphinxcadquery-0.3.0/setup.py
drwxrwxr-x  0 peque  peque       0 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery/
-rw-rw-r--  0 peque  peque      22 Feb 19 15:09 sphinxcadquery-0.3.0/sphinxcadquery/__init__.py
-rw-rw-r--  0 peque  peque    3564 Feb 19 15:08 sphinxcadquery-0.3.0/sphinxcadquery/sphinxcadquery.py
drwxrwxr-x  0 peque  peque       0 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/
-rw-rw-r--  0 peque  peque     703 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/PKG-INFO
-rw-rw-r--  0 peque  peque     268 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/SOURCES.txt
-rw-rw-r--  0 peque  peque       1 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/dependency_links.txt
-rw-rw-r--  0 peque  peque       7 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/requires.txt
-rw-rw-r--  0 peque  peque      15 Feb 19 15:15 sphinxcadquery-0.3.0/sphinxcadquery.egg-info/top_level.txt
```

This is probably a problem with the `setup.py` as I can see the problem persists to the latest release 0.5.0. Try creating a [MANIFEST.in](https://docs.python.org/2/distutils/sourcedist.html#manifest-template) and make sure that when you run `python setup.py sdist` that the JS files are in there!

**Comment by davidfischer** [comment]
If you're satisfied with this and it works, feel free to close this issue out.

**Comment by Peque** [comment]
@davidfischer I did have the wrong line defined in `package_data`. [It is fixed now](https://github.com/Peque/sphinxcadquery/commit/67a832adaf8d83e5763a91009a60268ac4659f52) and it seems to be working.

Thanks for your help, and really sorry for the noise! :sweat_smile:
