### ISSUE TITLE
Custom domain do not work

### ISSUE THREAD

**Issue by wilsonyou** [rtfd/readthedocs.org#5317]
## Details
Could you please checkout whether the setup for custom domain is correct?

The following is my domain name set on readthedocs:

![image](https://user-images.githubusercontent.com/40747875/53063201-4bd37e80-34fe-11e9-9ac8-081efe13aa84.png)

The following is the setup on cloudfare:
![image](https://user-images.githubusercontent.com/40747875/53063273-81786780-34fe-11e9-9df3-2eb180886a6c.png)

After these setup, the following error is displayed:
![image](https://user-images.githubusercontent.com/40747875/53063326-aa006180-34fe-11e9-8190-c5921b648904.png)

Thank you for your efforts in advance.

**Comment by davidfischer** [comment]
Firstly, we do not explicitly support a top level naked domain. You would need an A record for that (your first CNAME in the picture would be for bumo.io.bumo.io, BTW) and point to our IP. That will work but we don't explicitly support it in case we want to move our IP address.

Secondly, I'm not seeing those records in DNS. It's possible this is a propagation issue and it will be resolved in time.

    > dig www.bumo.io CNAME +short    # returns nothing

**Comment by wilsonyou** [comment]
@davidfischer 

Thank you David. 

Now I changed it to as the following figure, does it work?
![image](https://user-images.githubusercontent.com/40747875/53071276-b1cefe80-351c-11e9-8b45-01e11cb97205.png)

**Comment by davidfischer** [comment]
Very odd but I'm still not seeing this DNS record

**Comment by davidfischer** [comment]
There must be some other problem with the setup here. These DNS records are not propagating at all.

Here's some info on using a naked root domain with Cloudflare: https://blog.cloudflare.com/zone-apex-naked-domain-root-domain-cname-supp/
