### ISSUE TITLE
Build error with build id #8621987

### ISSUE THREAD

**Issue by slochower** [rtfd/readthedocs.org#5322]
## Details:

* Project URL: https://readthedocs.org/projects/pAPRika/
* Build URL(if applicable): https://readthedocs.org/projects/paprika/builds/8621987/
* Read the Docs username(if applicable): slochower

## Expected Result

Read the Docs uses `.readthedocs.yaml` to install a `conda` environment and build the documentation. 

## Actual Result

No documentation builds and the output does not indicate where the problem is. The last command to fail is `git clean -d -f -f`.

**Comment by stsewd** [comment]
Probably timing out in the conda env creation. This is a known problem in conda, between more channels conda is slower.

https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

**Comment by slochower** [comment]
Hmm, that could be! I just added a separate environment for Read the Docs that's pretty trim (no external channels) and I'm still getting no output from the build process.

Separate environment: https://github.com/slochower/pAPRika/blob/readthedocs/docs/rtd.yaml
RTD yaml: https://github.com/slochower/pAPRika/blob/readthedocs/.readthedocs.yml
Build output: https://readthedocs.org/projects/paprika/builds/8622104/

**Comment by stsewd** [comment]
Can you trying wiping the version first? Admin -> Versions -> Edit -> Wipe

**Comment by slochower** [comment]
Wiping doesn't appear to have had any effect.

**Comment by slochower** [comment]
As far as I can tell, it doesn't look like RTD is building from my conda file. Is there a straightforward way to check this?

**Comment by stsewd** [comment]
I'll try to replicate this locally.

**Comment by stsewd** [comment]
Sorry, this looks like a bug from our side. I think a temporal solution is to update your config file to v2 https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1

I'll try to fix this now.

**Comment by slochower** [comment]
Thanks! Working now with version 2.

**Comment by stsewd** [comment]
Reopening till I have a fix for v1 :)

**Comment by slochower** [comment]
Okay thanks -- sorry for the quick close.

By the way, I get successful builds but some unexpected errors:

```
/home/docs/checkouts/readthedocs.org/user_builds/paprika/conda/readthedocs/lib/python3.6/site-packages/pytraj/core/../.libs/libresolv-2-c4c53def.5.so: symbol __res_maybe_init version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference
```

for some modules. Is this also a problem on your end or should I look for something locally? (We can build on Travis, etc., without problems.)

**Comment by stsewd** [comment]
That looks like something else, maybe a dependency from conda.

**Comment by stsewd** [comment]
Ok, so, this isn't a _bug_ actually. You were using `conda.environment` with v1, but in v1 this setting is `conda.file` https://docs.readthedocs.io/en/stable/config-file/v1.html#conda-file. We should raise an error tho.

**Comment by slochower** [comment]
Ah, sorry about that. Thanks for looking into it.
