### ISSUE TITLE
local build is failing due to from sphinx.cmd.build import main ImportError: No module named sphinx.cmd.build

### ISSUE THREAD

**Issue by ChoiByungWook** [rtfd/readthedocs.org#5325]
## Details
I was attempting to emulate the doc build process within RTD, as a preventative test measure for changes made to our project's README.

I was following the process in regards to here: https://docs.readthedocs.io/en/latest/builds.html and reproducing the build steps that have happened within RTD: https://readthedocs.org/projects/sagemaker/builds/8577862/

I pulled down the readthedocs/build:latest and ran it with a bash entry point.
`docker run -it --entrypoint bash readthedocs/build:latest`

From there, I ran each step manually within the container.

All the build steps found here: https://readthedocs.org/projects/sagemaker/builds/8577862/ ended up succeeding except for the last one, which handles the build itself.
`python /home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build -T -W -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

This fails with:
`Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build", line 6, in <module>
    from sphinx.cmd.build import main
ImportError: No module named sphinx.cmd.build`

I also run into this issue with readthedocs/build:4.0rc1 image, as I noticed the pyenv versions on the readthedocs/build:latest defaulted to 3.6.2 instead of the 3.6.4 that showed up in the RTD build:  https://readthedocs.org/projects/sagemaker/builds/8577862/

I found these old GitHub issues which seem to indicate that these images are meant for internal usage only: https://github.com/rtfd/readthedocs-docker-images/issues/5 and https://github.com/rtfd/readthedocs-docker-images/issues/38. Running the same exact steps might not reproduce the same results that happen on RTD.

What is the guidance here? Am I missing a step?

Here is the pip list:
```
/home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/python -m pip list | grep sphinx
readthedocs-sphinx-ext   0.5.16
sphinx-rtd-theme         0.4.3
sphinxcontrib-websupport 1.1.0
Sphinx                   1.7.9
```

Printenv
```
HOSTNAME=587668fbd7a1
PYENV_ROOT=/home/docs/.pyenv
TERM=xterm
CONDA_VERSION=4.4.10
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
PYTHON_VERSION_33=3.3.6
PYTHON_VERSION_36=3.6.2
PATH=/home/docs/.pyenv/shims:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/docs/.conda/bin:/home/docs/.pyenv/bin
PYTHON_VERSION_35=3.5.4
PYTHON_VERSION_34=3.4.7
PWD=/home/docs/tmp
LANG=C.UTF-8
SHLVL=1
HOME=/home/docs
APPDIR=/app
PYTHON_VERSION_27=2.7.13
DEBIAN_FRONTEND=noninteractive
LESSOPEN=| /usr/bin/lesspipe %s
LESSCLOSE=/usr/bin/lesspipe %s %s
_=/usr/bin/printenv
OLDPWD=/home/docs
```

## Expected Result

Same build result: https://readthedocs.org/projects/sagemaker/builds/8577862/

## Actual Result
`python /home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build -T -W -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

This fails with:
`Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build", line 6, in <module>
    from sphinx.cmd.build import main
ImportError: No module named sphinx.cmd.build`

**Comment by stsewd** [comment]
What version of sphinx are you installing? Your docs are running with `Sphinx v1.7.9` in rtd

**Comment by ChoiByungWook** [comment]
Oh apologies, the I forgot grep was case sensitive.

/home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/python -m pip list | grep Sphinx
Sphinx                   1.7.9

I'll update the original correspondence above as well.

**Comment by ChoiByungWook** [comment]
If I don't use a pyenv I am able to build properly, although I need to modify builder from readthedocs to html.

**Comment by ChoiByungWook** [comment]
I think I found the issue.

I am attempting to reproduce each step that RTD runs through bash commands, however all of the RTD commands are executed within Python. I believe removing the python in the last build step, allows for running the build steps that readthedocs runs.

`python /home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build -T -W -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

`/home/docs/checkouts/readthedocs.org/user_builds/sagemaker/envs/v1.18.3.post1/bin/sphinx-build -T -W -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

There are a little small things to change, which are handled in the RTD code, such as the directory that build is happening and also the access to builders.

**Comment by stsewd** [comment]
I think we modify the python path to have the correct interpreter, and yeah, we are not always explicit about the cwd #4962 .

**Comment by ChoiByungWook** [comment]
@stsewd, Awesome. Closing.
