### ISSUE TITLE
Remove unused fiels and methods from core/models

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5327]
We are not using these:

https://github.com/rtfd/readthedocs.org/blob/3218c808e87206983c4eb3ce4faceddbcc0f7aa3/readthedocs/core/models.py#L35-L39

https://github.com/rtfd/readthedocs.org/blob/3218c808e87206983c4eb3ce4faceddbcc0f7aa3/readthedocs/core/models.py#L53-L67

And I don't think we are going to use them in the future, if we agreed in the removal, we can mark this as a good first issue.

**Comment by ReshmaPD** [comment]
Hello @stsewd,
do we just delete these specific lines and send a PR?

**Comment by stsewd** [comment]
Yes, and any other code related to these lines. Also, you can check that all tests are passing after that. And I think you'll need to generate a migration file.

**Comment by rshrc** [comment]
Since this issue is addressed now, should we close it?

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/pull/5383 isn't merged yet.

**Comment by rshrc** [comment]
> #5383 isn't merged yet.

So when will this be ready for merge?

**Comment by dojutsu-user** [comment]
Hi @rshrc 
Team will merge it when the time permits.
Thanks for the contribution.
