### ISSUE TITLE
Make ToC sidebar closeable/collapseable

### ISSUE THREAD

**Issue by emceeaich** [rtfd/readthedocs.org#5330]
## Details

* Read the Docs project URL: Any, but https://bmo.readthedocs.io/en/latest/ is an example

## Expected Result

User should be able to collapse the ToC sidebar

## Actual Result

Unable to collapse ToC sidebar which has been reported to the bugzilla.mozilla.org team as a migraine trigger making this [a potential a11y issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1524434#c3).

**Comment by stsewd** [comment]
Thanks, this is already tracked in our theme https://github.com/rtfd/sphinx_rtd_theme/issues/336
