### ISSUE TITLE
Build error with build id #8627546

### ISSUE THREAD

**Issue by kmpaul** [rtfd/readthedocs.org#5334]
## Details:

* Project URL: https://readthedocs.org/projects/mpirical/
* Build URL(if applicable): https://readthedocs.org/projects/mpirical/builds/8627546/
* Read the Docs username(if applicable): kmpaul

## Expected Result

The next step in the build process should be a `conda env create ...` step, but it does not appear to happen.

## Actual Result

Here is the raw output:

```
Read the Docs build information
Build id: 8627546
Project: mpirical
Version: latest
Commit: bb8f3e1a8cbff6fe2f537d3951352e81173f5259
Date: 2019-02-21T15:51:25.055848Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-02-21T15:51:25.532241Z, end-time: 2019-02-21T15:51:25.556201Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/NCAR/mpirical


[rtd-command-info] start-time: 2019-02-21T15:51:25.622583Z, end-time: 2019-02-21T15:51:25.935828Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50
From https://github.com/NCAR/mpirical
   ad562c4..bb8f3e1  master     -> origin/master

[rtd-command-info] start-time: 2019-02-21T15:51:26.261499Z, end-time: 2019-02-21T15:51:26.413667Z, duration: 0, exit-code: 0
git checkout --force origin/master
Previous HEAD position was ad562c4 Using conda and requirements file for docs
HEAD is now at bb8f3e1 Only use the conda `env.yml` file for ReadTheDocs

[rtd-command-info] start-time: 2019-02-21T15:51:26.475459Z, end-time: 2019-02-21T15:51:26.487617Z, duration: 0, exit-code: 0
git clean -d -f -f
```

As you can see, the result is the same as with #5322, but I cannot say if this is for the same reason.  The conda environment is not that large, as far as I know.  I've successfully built the docs in the past with much the same environment.  ...which makes me concerned that there is something wrong with my `.readthedocs.yml` file...?

**Comment by stsewd** [comment]
Hi, sorry about this. Looks like a bug from our side, can you try https://github.com/rtfd/readthedocs.org/issues/5322#issuecomment-466219872. Please subscribe to the other issue.
