### ISSUE TITLE
Command killed due to excessive memory consumption for Oracle Cloud Infrastructure Python SDK

### ISSUE THREAD

**Issue by arthall** [rtfd/readthedocs.org#5337]
## Details

* Read the Docs project URL: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/8630806/
* Read the Docs username (if applicable): arthall

## Expected Result

Project would build without issues.

## Actual Result

Process fails while writing output:
```
writing output... [ 67%] api/identity/models/oci.identity.models.WorkRequestLogEntry
writing output... [ 67%] api/identity/models/oci.identity.models.WorkRequestResource
writing output... [ 68%] api/identity/models/oci.identity.models.WorkRequestSummary
writing output... [ 68%] api/index
Killed


Command killed due to excessive memory consumption
```

I opened https://github.com/rtfd/readthedocs.org/issues/4251 a while back due to issues with memory consumption and timeouts.  I made all the recommended changes and the project has been building successfully, until today.   We added a new service with this latest release, but the docs build process is failing before reaching these new docs when writing the output.

Here is the latest PR so you can see which docs where added: https://github.com/oracle/oci-python-sdk/pull/106/commits/917e8c568228f9a0ec72c120876b1b941f812ca4

**Comment by stsewd** [comment]
I just saw that @humitos incremented the build time in https://github.com/rtfd/readthedocs.org/issues/4251#issuecomment-405958817, probably your project needs more memory too.

**Comment by arthall** [comment]
I tried another build today.  https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/8659397/  The process is still being killed.  Are there any recommendations for how to get past this?  We are planning to add new services with the next release which means an increase in the number of rst files.

**Comment by ivankravets** [comment]
The same with @PlatformIO :(

https://readthedocs.org/projects/platformio/builds/8726293/

**Comment by humitos** [comment]
@ivankravets please, can you open a different issue for you request?

**Comment by ivankravets** [comment]
@humitos thanks, done! => https://github.com/rtfd/readthedocs.org/issues/5434

**Comment by humitos** [comment]
I suppose the problem of these docs is this the page [Single Page Reference](https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/api/index.html) that includes all the API reference in one incredible huge page.

**Comment by arthall** [comment]
That page is enormous.  I've got to check to see if there is any part of the build and package process which references it.  It's worth removing the page from the docs which get built on ReadTheDocs if it allows the other pages to get built.

**Comment by humitos** [comment]
I think if you remove that page, your build will work.

**Comment by arthall** [comment]
The single page reference was removed with the latest release and the docs are building again.  Thank you for the help.
