### ISSUE TITLE
Be more defensive in how we insert our mkdocs media

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#5340]
This logic can be executed multiple times on [some builds](https://readthedocs.org/projects/phpspreadsheet/builds/8340376/) (see the `mkdocs.yml`):

https://github.com/rtfd/readthedocs.org/blob/ed8dd29a68d009fc08929fabf7155883482619c1/readthedocs/doc_builder/backends/mkdocs.py#L143-L152

If we have an issue reseting the branch/tag of the docs, we will end up inserting our media files twice, which causes them to be executed twice.

## Solution

This code should check if one of the files we insert is already in the list:

```
if 'readthedocs-data.js' not in user_config.get('extra_javascript'):
```

**Comment by saadmk11** [comment]
Can I work on This Issue?
If I understood the problem correctly we need to add conditions for `'extra_javascript'` and `'extra_css'`
to check if the static files already exist in the `user_config` if not then add the files. Please Correct me if I'm Wrong.
