### ISSUE TITLE
Build disabled

### ISSUE THREAD

**Issue by MilosKozak** [rtfd/readthedocs.org#5347]
Your project is currently disabled for abuse of the system. Please make sure it isn't using unreasonable amounts of resources or triggering lots of builds in a short amount of time. Please file a ticket to get your project re-enabled.

https://readthedocs.org/projects/androidaps/builds/?page=1

**Comment by AdrianLxM** [comment]
The reason probably was, that we had our i10n branch that was integrated with crowdin being set to auto-build with crowdin pushing too many commits. Sorry for that.

I disabled auto-build for that branch.

It would be great if you could re-enable our account. Thanks!

**Comment by ericholscher** [comment]
This has been reenabled. 👍
