### ISSUE TITLE
Request abandoned project: rows

### ISSUE THREAD

**Issue by turicas** [rtfd/readthedocs.org#5348]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rows/
* Build URL (if applicable):
* Read the Docs username (if applicable): turicas

## Expected Result

I'm the creator of [rows](https://pypi.org/project/rows/) Python package (available on PyPI) but another user created a ["test" project called rows on RTD](https://readthedocs.org/projects/rows/). He didn't add any docs and actually put [the wrong license](https://github.com/toguko/teste_doc#license) in the build repo.

## Actual Result

Since this name is not currently being used for nothing useful, I'd like to take the ownership so I can publish rows' docs in there.

**Comment by humitos** [comment]
I sent this email today.

/remind me to mark `rows` project abandoned in 6 weeks if no reply for the `toguko`

**Comment by toguko** [comment]
6 weeks, to much time :)

I receive an e-mail from Read the Docs asking to "give him permissions to be able to manage that project documentation under the Read the Docs platform so they can keep it updated" 

I replied saying the I don't want to give permission, I want to give the ownership to you guys.
I was just testing the "rows" and learning how to use the Read the Docs properly when I created that.

Let me know if I can do something else to pass the ownership to you.

**Comment by humitos** [comment]
@toguko hi! Thanks for replying. To give permissions to @turicas you have to log in into Read the Docs, and go to your project's admin page: https://readthedocs.org/dashboard/rows/users/ and add `turicas`. Thanks!

**Comment by toguko** [comment]
Done, turicas added as maintainer.

**Comment by humitos** [comment]
Thanks @toguko! I'm closing this issue.

@turicas you should be able to manage the project now.
