### ISSUE TITLE
Build error with build id #8647215 - no errors in log

### ISSUE THREAD

**Issue by geographika** [rtfd/readthedocs.org#5349]
## Details:

* Project URL: https://readthedocs.org/projects/mappyfile/
* Build URL(if applicable): https://readthedocs.org/projects/mappyfile/builds/8647215/
* Read the Docs username(if applicable): geographika

## Expected Result
A successful build

## Actual Result

The build fails, with very little in the log - it seems to fail at ``git clean -d -f -f``

Tried wiping the build environment, and setting the conf.py manually in advanced settings, changing Python version etc. but no luck so far.

**Comment by stsewd** [comment]
Probably same as #4371. You don't have this submodules https://github.com/geographika/mappyfile/blob/master/.gitmodules in your repo https://github.com/geographika/mappyfile/tree/master/tests/mapfiles

**Comment by geographika** [comment]
@stsewd - many thanks for the quick reply and solution. Fixing the submodules fixed the builds. I had found the issue previously but forgot the project had submodules..
It looks like reporting the error to the log is only possilble by fixing gitpython as mentioned at https://github.com/gitpython-developers/GitPython/issues/279 ?

**Comment by stsewd** [comment]
Yeah, I already have a PR almost accepted in gitpython https://github.com/gitpython-developers/GitPython/issues/279, but looks like tests are failing in their master branch for python 3.7
