### ISSUE TITLE
doxygen content exceding theme width

### ISSUE THREAD

**Issue by SuryaGrandhi** [rtfd/readthedocs.org#5355]
## Expected Result

Want to display the doxygen API content like this..
https://imgur.com/LEB3jcH

## Actual Result

I am trying it on the local machine.

Here the doxygen content is going out of bounds like below.
https://imgur.com/CqcIWzC

I have tried:
Giving custom css in the **_static** folder.
Adding **css to the class** of the doxygen content.
Tried adding 'body_max_width': '80%' to the **html_theme_options** in conf.py file.

But not able to get any result as expected.

**Comment by stsewd** [comment]
> I am trying it on the local machine.

So, you are seeing this locally and not only on read the docs?

Maybe is worth creating this issue in the theme repo https://github.com/rtfd/sphinx_rtd_theme

**Comment by SuryaGrandhi** [comment]
> > I am trying it on the local machine.
> 
> So, you are seeing this locally and not only on read the docs?
> 
> Maybe is worth creating this issue in the theme repo https://github.com/rtfd/sphinx_rtd_theme

Thanks @stsewd. I will look into that.

**Comment by SuryaGrandhi** [comment]
Hi, @stsewd I have also tried the same on readthedocs server. It was not working. Moreover I have seen the repos for which it is working as required. 

Checked Conf.py and Doxyfile. Do we need to check any other details. Please suggest.

**Comment by stsewd** [comment]
Sorry, no. I still think this is a problem with the theme https://github.com/rtfd/sphinx_rtd_theme/issues/731 or with something else, not from read the docs (since it can be replicated locally).

**Comment by SuryaGrandhi** [comment]
Okay then. Let us see if anyone can help out. Else we can close it. 

Thanks.

**Comment by Blendify** [comment]
Let's use the [rtfd/sphinx_rtd_theme#731](https://github.com/rtfd/sphinx_rtd_theme/issues/731) to continue this discussion.
