### ISSUE TITLE
Trigger build on default branch when saving a project

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5358]
Currently when we save a project form (admin panel),
it triggers a build to latest

https://github.com/rtfd/readthedocs.org/blob/9874b866fea9696fa8495d7b3699f1bf1a3f923d/readthedocs/projects/forms.py#L69-L74

https://github.com/rtfd/readthedocs.org/blob/9874b866fea9696fa8495d7b3699f1bf1a3f923d/readthedocs/core/utils/__init__.py#L97-L98

Even if latest is deactivated, we should trigger a build to the default branch instead.

**Comment by dojutsu-user** [comment]
@stsewd 
I'm working on it.

**Comment by dojutsu-user** [comment]
@stsewd 
Does the build needs to trigger build for both the `default_branch` and `latest` branch ?

**Comment by humitos** [comment]
@dojutsu-user I think it should trigger just the `default_branch` without `latest`.
