### ISSUE TITLE
RTD built succesfully but documentation not updated

### ISSUE THREAD

**Issue by caravansary83** [rtfd/readthedocs.org#5360]
## Details

* Read the Docs project URL: https://jupiter.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*
The build was successful and the documentation at https://jupiter.readthedocs.io/en/latest/ should be updated. 

## Actual Result

*A description of what actually happened*

The build was successful and the documentation at https://jupiter.readthedocs.io/en/latest/ was not updated. It still shows the old version.

**Comment by humitos** [comment]
Hi! Can you provide more information about what is the specific commit that was built and what's one of the differences that we should be able to notice on the docs? Otherwise, it's hard to guess and prone to make mistakes.

**Comment by caravansary83** [comment]
Hello, the specific commit is https://github.com/ANRGUSC/Jupiter/commit/2a9c3068932373d4909663c12997e7566bba69ad

**Comment by davidfischer** [comment]
Looking at the generated docs (eg. [this](https://jupiter.readthedocs.io/en/latest/Jdeploy.html)), those changes are definitely present and there hasn't been a [build](https://readthedocs.org/projects/jupiter/builds/) since 10 minutes before this issue was opened.

**Comment by stsewd** [comment]
I'm guessing browser or ISP cache issue, you can try cleaning the cache and see if that fixed it.

**Comment by caravansary83** [comment]
Those changes finally showed up. Thank you so much for all your reply!

**Comment by stsewd** [comment]
Glad it works, closing.
