### ISSUE TITLE
path problem, wrong images displayed 

### ISSUE THREAD

**Issue by kulichechka** [rtfd/readthedocs.org#5373]
## Details
Two of our guideline artlicles are displayed on readthedocs with wrong screenshots. On github everything is ok and the path is correct but when displayed on readthedocs the screenshots seem to be taken from wrong catalog and mixed. Please see the details below:

* Read the Docs project URL: https://wiki.edi-n.com/ru/latest/services/EDIN_DOCflow/edin_docflow/instruktsia-biznes-administratora.html
https://wiki.edi-n.com/ru/latest/services/EDIN_DOCflow/edin_docflow/instruktsia-administratora-polzovatelei.html
* Build URL (if applicable): https://readthedocs.org/projects/edi-n/builds/
* Read the Docs username (if applicable): EDI-N

## Expected Result
Article instruktsia-administratora-polzovatelei.rst should contain images from catalog pics_instruktsia-administratora-polzovatelei
Article instruktsia-biznes-administratora.rst should contain images from catalog pics_instruktsia-biznes-administratora

**Comment by stsewd** [comment]
I can see the same images as the repo

https://github.com/EDI-N/Docs/blob/master/docs/source/services/EDIN_DOCflow/edin_docflow/instruktsia-administratora-polzovatelei.rst

https://github.com/EDI-N/Docs/blob/master/docs/source/services/EDIN_DOCflow/edin_docflow/instruktsia-biznes-administratora.rst

**Comment by kulichechka** [comment]
@stsewd thank you for dealing with the issue. I don't know how it happened but the screenshots are ok now.

**Comment by stsewd** [comment]
Probably something with the browser cache. Closing.
