### ISSUE TITLE
"Default branch: latest" does not exist

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5390]
* Read the Docs project: https://readthedocs.org/projects/test-builds/

Going to `Advanced settings` the `Default branch` selector shows `latest` as an option. I think this is invalid since the repo has no `latest` branch: https://github.com/rtfd/test-builds/branches/all?utf8=%E2%9C%93&query=latest

In this particular project seems that this is not a real problem, since the build that was triggered after saving it to this branch [picked the `origin/master` anyway](https://readthedocs.org/projects/test-builds/builds/8694899/) but I saw other projects failing for this (in the corporate site).

Anyway, `latest` should not be an option since it's not a valid branch on the repository.

**Comment by saadmk11** [comment]
@humitos I went Through the Code for this. it seems like we are creating a duplicate version for `LATEST` an `STABLE`

![screenshot from 2019-03-05 00-34-44](https://user-images.githubusercontent.com/24854406/53754601-a0073700-3ede-11e9-9591-baf3bbf47efe.png)

and in the forms we are showing all the `Versions` as the `default_branch` choices
https://github.com/rtfd/readthedocs.org/blob/c428dd336992fd8716fc53180b626ba7925ba9b1/readthedocs/projects/forms.py#L231-L241

so should we remove latest and stable from the choices as they are not valid branch ?
if I'm Wrong please let me know how it should be handled.

**Comment by stsewd** [comment]
The project has a `latest` version https://readthedocs.org/projects/test-builds/versions/, it points to master. That version we create automatically.

**Comment by stsewd** [comment]
I think the related issue is because of https://github.com/rtfd/readthedocs.org/issues/5358

**Comment by stsewd** [comment]
Also, I think of this more like an alias. Actually the name is incorrect, it should be "default version" (but we already use that name for another setting!).

I say this because, it can be a tag too.

**Comment by stsewd** [comment]
The extra origin issue is fixed in https://github.com/rtfd/readthedocs.org/pull/5523

**Comment by stsewd** [comment]
I propose _re-propossing_ this issue to change the name of this setting to something more accurate p:

**Comment by humitos** [comment]
If a project doesn't have a _branch_ or _tag_ called `latest` and you select `Default branch: latest` from the admin, does not fail the build when triggering `latest`?

**Comment by stsewd** [comment]
With the current PR no, it's doesn't. A build is triggered to master or whatever alias was used

**Comment by humitos** [comment]
OK. I still think that `latest` should not appear there, but not failing is better than what we have now :)

**Comment by stsewd** [comment]
Yeah, latest shouldn't be there. What do you think about including `stable`? I think neither should be listed there (actually they should if the user put those branches/tasg)., we should filter for `machine=False` I think.

**Comment by saadmk11** [comment]
> Yeah, latest shouldn't be there. What do you think about including `stable`? I think neither should be listed there (actually they should if the user put those branches/tasg)., we should filter for `machine=False` I think.

I was proposing something like this on my initial response. I think this is a good way to go :+1:

**Comment by humitos** [comment]
@stsewd yeah, `stable` shouldn't be there either. Filtering by `machine=False` looks good to me :+1:
