### ISSUE TITLE
Unable to Login with OAuth

### ISSUE THREAD

**Issue by FRCTeam5902** [rtfd/readthedocs.org#5399]
## Details

We are trying to connect our GitHub and Read the Docs account. It's showing a dimmed out connect button. Successfully did it with one GitHub account (personal) but now trying to do it with our robotics team account and it's not allowing us to click authorize.

## Expected Result

Authorize GitHub account on Read the Docs.

## Actual Result

Authorization button is dimmed out and not able to be clicked.

Screenshot - https://www.dropbox.com/s/qq4te86m9oa51wu/Screenshot%202019-03-05%2010.52.00.png?dl=0

**Comment by stsewd** [comment]
Are you saying trying to connect two github accounts to the same rtd project? I have never tried that, maybe it's not possible? (https://github.com/rtfd/readthedocs.org/issues/4932)

**Comment by FRCTeam5902** [comment]
No just one GitHub account to the rtd account 

It worked on another computer. May have been a caching issue.
