### ISSUE TITLE
Don't allow to create subprojects with same alias

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5402]
Currently we can create several subprojects with the same alias, when serving the docs from 

https://github.com/rtfd/readthedocs.org/blob/bdb4aa5da5b5b5fb45244176c2bee58fb5442414/readthedocs/core/views/serve.py#L71-L74

It gives a 500 error.

**Comment by saadmk11** [comment]
@stsewd I would like to work on this bug fix.

**Comment by stsewd** [comment]
Sure

**Comment by saadmk11** [comment]
@stsewd I have added a `clean_alias` method in the `ProjectRelationshipBaseForm` which will check if the alias already exists. This will prevent Projects from Creating New subprojects with same alias. But what should we do for the existing subprojects with same alias. Should 
 it Return the first object if `ProjectRelationship.MultipleObjectsReturned` exception occurs. What do you suggest?

**Comment by stsewd** [comment]
We should inspect the database and remove/rename those alias, I think they are almost spam projects.

**Comment by saadmk11** [comment]
> We should inspect the database and remove/rename those alias, I think they are almost spam projects.

Okay. :+1:
