### ISSUE TITLE
update the clone step in the installation guide to include submodules

### ISSUE THREAD

**Issue by agarwalrounak** [rtfd/readthedocs.org#5408]
## Details

When running the pre-commit command `pre-commit run`, it gives the error that `.pre-commit-config.yaml` does not exist though the command `ls -a` clearly mentions that `.pre-commit-config.yaml` exists.

## Actual Result

![screenshot from 2019-03-07 01-23-19](https://user-images.githubusercontent.com/38394281/53909628-2b680000-4078-11e9-8d32-5cb45437a135.png)

**Comment by stsewd** [comment]
You are missing the submodule.

`git submodule update --init`

We should update the clone step in the installation guide to include submodules.

https://docs.readthedocs.io/en/stable/install.html#get-and-run-read-the-docs

**Comment by agarwalrounak** [comment]
@stsewd Thanks for the prompt reply :) I will send a PR with the required changes soon.
