### ISSUE TITLE
github services warning

### ISSUE THREAD

**Issue by brianmay** [rtfd/readthedocs.org#5412]
## Details

For a number of my projects, I continue to see this warning:

```
    Your project, python-tldap, needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations.
    Your project, karaage-user, needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations.
    Your project, karaage-programmer, needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations.
    Your project, karaage, needs to be reconfigured in order to continue building automatically after January 31st, 2019. For more information, see our documentation on webhook integrations.
```

I have already reconfigured these projects already to delete the github service and add the webhook. I did so way before the deadline.  Why am I still seeing this warning?

## Expected Result

No warning message.

## Actual Result

Warning messages appear.

**Comment by agjohnson** [comment]
These are one time warnings. If your projects are configured, you can click the link in the messages to acknowledge them.

**Comment by brianmay** [comment]
Clicking the link just takes me to the documentation. I don't see anyway of acknowledging them, and they keep showing up every time I log in.

**Comment by brianmay** [comment]
Oh, I see, I am middle clicking the link so it opens a new window.

I have to left click on each link, view the documentation, then click back and it is gone. This is terrible UI.

**Comment by stsewd** [comment]
Yes, we have an open issue about that https://github.com/rtfd/readthedocs.org/issues/4684
