### ISSUE TITLE
Point users to use a configuration file from advanced settings

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5413]
Currently users may still be using the advanced settings to build their docs, they should use a configuration file, now they can do everything from the web in the config file.

I was thinking in blocking the UI for new projects, but we can't do that, because that would be a problem for people moving to read the docs (they can't modify their docs). A long solution can be allowing to have a global configuration (codecov has this feature), and that can be merged with the configuration of each version (probably I can create another issue to discuss this more if we agree).

Anyway, going back to the original issue:

We already have something like this in the settings

![screenshot_2019-03-06 edit project read the docs](https://user-images.githubusercontent.com/4975310/53922454-651e1400-4042-11e9-88a6-09115ff01a34.png)

I was thinking we could use the same pattern in the advanced settings

![screenshot_2019-03-06 edit advanced project settings read the docs](https://user-images.githubusercontent.com/4975310/53922478-81ba4c00-4042-11e9-91c2-96ddc6eb43c4.png)

But I think that first we should group the settings, we have global and per version settings, so putting the global settings first would be the idea (those are not present in the config file). Then we can list the per-version settings (available in the config file) but first showing a tip/link to the config file docs.

```
Advanced settings

[ ] Single version
[Default branch]
[Default version]
....

:warning: All the next options can be configured using a configuration file.

[Python interpreter]
[ ] Istall project
[Requirements file]
....

```

**Comment by davidfischer** [comment]
I think this is a great proposal. I like the idea of separating out global features that can't be configured in the YAML file. I almost wish there was another page to put those 3 settings on but I don't think they belong on the regular settings page.

**Comment by stsewd** [comment]
There are more, I didn't put all p:

**Comment by davidfischer** [comment]
There aren't *that* many though.
