### ISSUE TITLE
Docs on conditional content

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#5420]
A common question we get is how to do conditional content with Sphinx. There are a few options for this:

* https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html#module-sphinx.ext.ifconfig
* https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#directive-only

We should document these two methods in a guide or perhaps even break out an author's guide to start some RTD independent content on Sphinx authoring.

**Comment by agarwalrounak** [comment]
Hi @agjohnson ! I think the issue #4603 deals with the same thing.

**Comment by agarwalrounak** [comment]
I have asked to work on that issue and I can include one more description under "How to have conditional content in your documentation" :
- Using `ifconfig` directive to make conditional content

**Comment by stsewd** [comment]
>  I think the issue #4603 deals with the same thing.

@agarwalrounak yes, they are related. Probably they can be addressed in the same PR

**Comment by agarwalrounak** [comment]
@stsewd Sure, I will send a PR soon.

**Comment by dojutsu-user** [comment]
Still valid bot.

**Comment by humitos** [comment]
I'm closing this one in favor of #4603

**Comment by stsewd** [comment]
We should update the other issue to include the other methods that are mentioned here
