### ISSUE TITLE
Remove possibel unused constant

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5422]
At first sight looks like isn't used anymore after https://github.com/rtfd/readthedocs.org/pull/5383

https://github.com/rtfd/readthedocs.org/blob/78c34c904b347110b2cd545b4b5a80ed526590f7/readthedocs/core/models.py#L13-L13

We should still double check and make sure tests are passing after the removal.

**Comment by saadmk11** [comment]
Okay. I'll remove the constant and double check if the tests are passing and submit a PR.
