### ISSUE TITLE
Build error with build id #8736950

### ISSUE THREAD

**Issue by felipelm** [rtfd/readthedocs.org#5429]
## Details:

* Project URL: https://readthedocs.org/projects/qlf/
* Build URL(if applicable): https://readthedocs.org/projects/qlf/builds/8736950/
* Read the Docs username(if applicable): felipelm

## Expected Result

Build the documentation

## Actual Result

After checking out to the correct branch it stops and fails the build.

**Comment by stsewd** [comment]
Probably the same as #4371 Can you check if your submodules are correct https://github.com/desihub/qlf/blob/master/.gitmodules?

**Comment by felipelm** [comment]
@stsewd yes they all exists and are used in the project. I can't see the error in the raw build log. Is it possible to change the build log level to debug?

**Comment by stsewd** [comment]
I don't see this submodule in your project https://github.com/desihub/qlf/blob/0b707af3d5fcef2929ebb38ca6e2ecfd88c81cd0/.gitmodules#L19-L20

**Comment by felipelm** [comment]
@stsewd that's true I missed that one.

The build worked fine now.

Sorry for the trouble and thanks for the help!
