### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by ivankravets** [rtfd/readthedocs.org#5434]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/platformio/
* Build URL (if applicable): https://readthedocs.org/projects/platformio/builds/8726293/
* Read the Docs username (if applicable): ikravets

## Expected Result

Completed build.

## Actual Result

Broken build.

**Comment by humitos** [comment]
Hi @ivankravets! I increased your memory and triggered a build. It should pass now.

BTW, did you check this guide? https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html I'm not sure _why_ it uses too much memory on the Sphinx step.

Actually, please disable `htmlzip` and maybe `pdf` formats which consume _a lot_ of resources on these kind of projects. @stsewd I suppose that sharing the toctrees on them will help, what do you think?

**Comment by stsewd** [comment]
I didn't see so much gain locally inside docker, but outside it was a lot of time being reduced. So, not really sure, but it's worth it to try.

**Comment by humitos** [comment]
Without the flag, it took 785s

https://readthedocs.org/projects/platformio/builds/8815492/

After adding the feature flag,

https://readthedocs.org/projects/platformio/builds/8816161/

**Comment by ivankravets** [comment]
@humitos Thank you so much for the help. Should be something done on our side? HTML + PDF are useful formats for our developers.

**Comment by humitos** [comment]
@ivankravets OK! We are done for now. Let us know if it happens again.
