### ISSUE TITLE
Remove Login button when already clicked on login

### ISSUE THREAD

**Issue by ironbatshashank** [rtfd/readthedocs.org#5435]
## On the homepage when the user clicks login instead of signup the user can still see the login button on login page.

 https://github.com/rtfd/readthedocs.org
On readthedocs.org/accounts/login/  page

*The user should not be able to see the login button when he is already on login page. *

**Comment by stsewd** [comment]
Just for clarification, this is what the issue is about

https://readthedocs.org/accounts/login/

![Screenshot_2019-03-12 Sign In Read the Docs](https://user-images.githubusercontent.com/4975310/54214213-ce26e100-44b3-11e9-860c-986551f42d00.png)

**Comment by stsewd** [comment]
I don't think this is worth it, seems fine for me having the login button there.

**Comment by krutik710** [comment]
@stsewd Do this issue still has to be worked on?

**Comment by ironbatshashank** [comment]
@stsewd I just thought it's a good newcomer issue.

**Comment by stsewd** [comment]
> @stsewd I just thought it's a good newcomer issue.

It is, but it requires a design decision from someone of the core team before someone can work on this.

**Comment by humitos** [comment]
I'm fine if someone wants to work on this.
