### ISSUE TITLE
Branch not appearing on the "inactive list" in the Versions tab

### ISSUE THREAD

**Issue by mathieuboudreau** [rtfd/readthedocs.org#5438]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/axondeepseg/
* Build URL (if applicable): N/A
* Read the Docs username: mathieuboudreau

## Expected Result

That our branch name ([jca/171-logo](https://github.com/neuropoly/axondeepseg/tree/jca/171-logo)) appears in the inactive list in the "Versions" tab so that we can trigger a build and preview the changes before merging.

Encountered as part of this PR (https://github.com/neuropoly/axondeepseg/pull/185).

## Actual Result

The branch never appeared on the inactive list in the "Versions" tab

<img width="816" alt="Capture d’écran 2019-03-12 à 14 36 19" src="https://user-images.githubusercontent.com/1421029/54222469-7058c000-44d8-11e9-9522-bcd89ae96d72.png">

Our RTD webhook sees the events though when pushing new commits to that branch:

<img width="754" alt="Capture d’écran 2019-03-12 à 15 12 13" src="https://user-images.githubusercontent.com/1421029/54223364-43a5a800-44da-11e9-9501-a25754b0ef34.png">

**Comment by stsewd** [comment]
We don't create versions from Pull requests, but we create version when you create a new branch. Can you check that we received that event? (branch creation). Also, webhooks in github were down for a moment today, so maybe related.

Anyway, you can force the version update triggering a build in any version.

**Comment by mathieuboudreau** [comment]
I did try creating a a new branch from that branch t debug this issue, but that one did not appear in the list either. 

>you can force the version update triggering a build in any version.

This isn't clear to me (both what it's for or how to do it) in my case where my branch isn't appearing.

**Comment by stsewd** [comment]
https://readthedocs.org/projects/axondeepseg/builds/ go ther is trigger a build to latest or any other branch, that way we clone the repo and update the list of versions.

**Comment by mathieuboudreau** [comment]
I just checked again and the branch appeared; either someone on your side triggered that build on latest for me, or maybe I was just too impatient (though I waited +1 hours) and/or the initial branch creation occurred during the githook blackout. Thanks!
