### ISSUE TITLE
Report parsing error of the yaml to the user

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5439]
When a project has a syntax error in the yaml file like

```
build:
  image:latest
```

https://github.com/flatironinstitute/CaImAn/blob/1885c51aab3592d8f07f866637985016c50fab0d/readthedocs.yml#L3

(there should be a space)

We raise a general exception instead of something more useful.

**Comment by humitos** [comment]
This one is a good candidate for a contributor as Good First Issue

**Comment by Mike-Dai** [comment]
Can I work on this issue?

**Comment by krutik710** [comment]
@stsewd @humitos I'd also like to work on this issue

**Comment by Abhi-khandelwal** [comment]
@stsewd @humitos I would like to work on this issue , Can I work on this issue. This would be my first contribution.

**Comment by stsewd** [comment]
Anyone, please feel free to send a PR with a test.

**Comment by AakankashaNarayanSharma1** [comment]
Hi. I am trying to push the changes but am getting the error 
remote: Permission to rtfd/readthedocs.org.git denied to AakankashaNarayanSharma1.
fatal: unable to access 'https://github.com/rtfd/readthedocs.org.git/': The requested URL returned error: 403
please help me in resolving this as this is my first commit. Thanks

**Comment by stsewd** [comment]
Sorry, this is fixed by https://github.com/rtfd/readthedocs.org/pull/5510, it solves two problems, didn't realize of this issue.

@AakankashaNarayanSharma1 looks like you are pushing to the main repo instead of your fork. I recommend you to read about remotes in git.
