### ISSUE TITLE
RTD build killed in conda

### ISSUE THREAD

**Issue by pgunn** [rtfd/readthedocs.org#5440]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/caiman
* Build URL (if applicable): https://readthedocs.org/api/v2/build/8744881.txt
* Read the Docs username (if applicable): caiman

## Expected Result

Builds of "dev" succeed

## Actual Result

Builds of "dev" fail while conda is creating the environment.

This is a request to up the resource limit for this project. I know it has a lot of dependencies (and a C++ extension), but as I understand, python needs to import the package to extract docs from it with pydoc and I don't think we can easily avoid that (this is complex scientific software). This software successfully built on RTD 3 months ago, so I suspect the resource limits have tightened since then.

Project code on github is here: https://github.com/flatironinstitute/CaImAn/tree/dev

I appreciate what you do
--Pat

**Comment by humitos** [comment]
Error 247 on conda is a problem on them, not us :/

I increased the memory of your project to overcome this situation for now.

Please feel free to reopen if you consider.
