### ISSUE TITLE
Sitemap sort order may prioritise unstable/development documentation

### ISSUE THREAD

**Issue by strophy** [rtfd/readthedocs.org#5447]
In `sitemap.xml`, the sort order should prioritise the user-selected default version (Admin > Versions > Default Version) in the backend instead of setting `latest` to highest priority. In many cases (and also by [definition](https://docs.readthedocs.io/en/stable/versions.html)), `latest` points at development documentation while `stable` is the version most people should be using, and should appear first in search results.

Example from: https://docs.dash.org/sitemap.xml
`stable` should be higher priority than `latest`, but the reverse is true.
```
<url>
  <loc>http://docs.dash.org/en/latest/</loc>
  <changefreq>daily</changefreq>
  <priority>1</priority>
</url>

<url>
  <loc>http://docs.dash.org/en/stable/</loc>
  <changefreq>weekly</changefreq>
  <priority>0.9</priority>
</url>
```

**Comment by humitos** [comment]
@strophy do you think the `changefreq` should be as it is right now? So, in your example it could be

* `stable` with `priority=1` and `changefreq=weekly`
* `latest` with `priority=0.9` but `changefreq=daily`

What do you think?

**Comment by strophy** [comment]
To some extent, it depends on the current development focus. Sometimes patches are released to a stable version, which results in updates to the `stable` documentation. Other times the focus is on new features, so `latest` sees most of the updates, and beta users (testnet) are the main audience.

If it is not possible to define `changefreq` in settings or conf files, I think your proposal makes reasonable sense for most projects. The bug report pertains mostly to respecting the user-selected "Default Version", any `changefreq` weekly or faster is fine with me personally.

**Comment by humitos** [comment]
OK, thanks for the explanation.

We won't probably accept a configuration option for this. So, I prefer to go forward with my proposal considering that you also think it's reasonable for most of the projects :)
