### ISSUE TITLE
Manual cloning via SSH is not supported

### ISSUE THREAD

**Issue by M1k13** [rtfd/readthedocs.org#5448]
Hey,

When I go to "Import a Project" > "Manual import" and fill in "Repository URL:(git@gitolite.x.x.org:/docs.git" I get a warning: "Manual cloning via SSH is not supported".

I want to use ssh and not http/https, is that possible? 
Its a testing environment with no firewall and its on the same vlan as my readthedocs.x.x.org machine. 

Kind regards,

**Comment by stsewd** [comment]
No, we don't support ssh urls, this is because we don't suppor private repositorios. For that we have https://readthedocs.com

**Comment by M1k13** [comment]
Thanks !
