### ISSUE TITLE
Inconsistency of links in footer

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5449]
Links in the footer of https://readthedocs.org/ points to `latest` version of documentation except the link for `Documentation`, which points to https://docs.readthedocs.io/ which redirects to `stable` version.
~It should also points to https://docs.readthedocs.io/en/latest/~

All the links must points to `stable` version.

**Comment by stsewd** [comment]
All links should point to stable, we change that some time ago.

**Comment by dojutsu-user** [comment]
@stsewd 
Most of the links are pointing to `latest` as of now....
I will change the issue description and will make a PR soon.

**Comment by stsewd** [comment]
We also have the page redirect, which will redirect to the default version https://docs.readthedocs.io/page/getting_started.html I think that's better, so we don't have to keep track of these links if we change the default version again.

**Comment by dojutsu-user** [comment]
yeahh... that is better.
I will make the required changes.
Thanks.

**Comment by dojutsu-user** [comment]
btw... I am not clear as why the links should not point to `latest` version?

**Comment by stsewd** [comment]
Because the documentation will be not even with the production running instance of rtd (which is always stable). So, if we add a new feature and their docs, the feature will be available in master, but not in the site. That will be confusing.

**Comment by dojutsu-user** [comment]
ohhh... okay
I get it.
Thanks for the explanation.
