### ISSUE TITLE
502 Bad Gateway on Projects > Versions page

### ISSUE THREAD

**Issue by markcoatsworth** [rtfd/readthedocs.org#5458]
The Projects > Versions page for our project is throwing a 502 Bad Gateway error. It's happening at the following URL: 

https://readthedocs.org/projects/htcondor/versions

I thought this might be a transient error but it's been happening consistently for the last day or so. All the other pages I've tried seem to work fine.

It's worth noting a similar ticket  #5441  was filed a couple of days ago for a 502 error on the Import a Repository page. This seems to be working correctly now.

## Details

* Read the Docs project URL: https://htcondor.readthedocs.io
* Build URL (if applicable): 
* Read the Docs username (if applicable): htcondor

## Expected Result

A list of the different versions of our docs, dropdown menus to connect them to different branches, etc.

## Actual Result

Server Error

502 - Web server received an invalid response while acting as a gateway or proxy server.

There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

**Comment by dojutsu-user** [comment]
Hi @markcoatsworth 
I am able to open the webpage.
![Screenshot from 2019-03-14 21-36-04](https://user-images.githubusercontent.com/29149191/54372408-41417a80-46a1-11e9-9d8a-7c1b0e97ed96.png)

**Comment by stsewd** [comment]
I'm seeing 502 too, Investigating now

**Comment by stsewd** [comment]
Looks like this only happens to users with admin/owner privileges.

**Comment by markcoatsworth** [comment]
Thanks @dojutsu-user for looking into this! I just checked again and @stsewd is correct. The page loads correctly when not logged in. But when I log in as the project owner it's still throwing the 502 error.

**Comment by stsewd** [comment]
Just an update here, the problem is caused due the amount of versions (branches and tags) that your project has. We are trying to figure out where the bottleneck is, but if you don't need all those branches/tags removing them from the repo could fix the problem.

**Comment by markcoatsworth** [comment]
Alright thanks @stsewd! This makes sense and we've actually already been working to reduce the number of branches and tags. This will give us extra motivation to move on with it. Much appreciate your help.

**Comment by davidfischer** [comment]
This is fixed and deployed. https://readthedocs.org/projects/htcondor/versions is still a little slow, but it shouldn't timeout now.
