### ISSUE TITLE
Remove Haystack reference in Docs

### ISSUE THREAD

**Issue by MIKNOTAURO** [rtfd/readthedocs.org#5462]
This can be confusing...
url: https://docs.readthedocs.io/en/stable/features.html 

![image](https://user-images.githubusercontent.com/2102746/54422086-56370180-46d3-11e9-8339-066ee808bf05.png)

**Comment by stsewd** [comment]
Yeah, we removed the `Haystack` dependency a time ago https://github.com/rtfd/readthedocs.org/pull/4039

**Comment by saadmk11** [comment]
@stsewd ill create a PR for this.
