### ISSUE TITLE
 dev.db-journal file is being tracked 

### ISSUE THREAD

**Issue by rshrc** [rtfd/readthedocs.org#5463]
## Details

When the server is running on a local instance, and we are importing a project and building a doc there is this automatic creation of a dev.db-journal which as per assumption is different for all the different users.

## Expected Result
The file creation is normal but it should not be tracked by git. It might lead to merge conflicts later on.

**Comment by stsewd** [comment]
Yes, I think that file is generated from celery. We can add it to our `.gitignore` file.
