### ISSUE TITLE
Dashboard screen performance issue

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#5465]
While working on #5464, I discovered a performance issue on the [dashboard screen](https://readthedocs.org/dashboard/).

Getting the latest build status and the number of builds for each project results in an extra SQL query each. This results in O(n) SQL queries where n is the number of projects displayed. It should be possible to get the latest build and number of builds for each project using a [Django annotation](https://docs.djangoproject.com/en/1.11/ref/models/querysets/#django.db.models.query.QuerySet.annotate) or a similar feature.

<img width="1140" alt="Screen Shot 2019-03-15 at 10 35 18 AM" src="https://user-images.githubusercontent.com/185043/54450600-0f1a3200-470e-11e9-8fbb-4579689de8f4.png">

**Comment by saadmk11** [comment]
Working on it
