### ISSUE TITLE
Profile page performance issue

### ISSUE THREAD

**Issue by davidfischer** [rtfd/readthedocs.org#5468]
While working on #5464, I discovered a performance issue on the [profile page](https://readthedocs.org/profiles/davidfischer/).

There appears to be a couple duplicated queries in the profile screen. One is to get maintainers for a project and another is to get the latest build. This results in O(n) SQL queries where n is the number of projects displayed. It should be possible to get this data using an annotation.

Parts of this look similar to #5467 and #5465.

There is also one query per project to generate the "view docs" link but that will probably involve refactoring the resolver. You might want to hold off on that as that is not a *good first issue*. See #3712.

<img width="1157" alt="Screen Shot 2019-03-15 at 11 24 33 AM" src="https://user-images.githubusercontent.com/185043/54453941-96b76f00-4715-11e9-8b9a-fb0433242023.png">

**Comment by saadmk11** [comment]
@davidfischer should these issues be worked on after merging #5464 or should i install debug toolbar locally and try to resolve them?

**Comment by davidfischer** [comment]
#5464 will help you work on them but it isn't necessary to fix them.
