### ISSUE TITLE
Make /random/ path works

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5480]
Currently hitting https://readthedocs.org/random/ produces 502 and hitting https://readthedocs.org/random/pip/ may return a `.js` file or a non `.html` file which is not useful.

We need to fix it and return always return a HTML file. For this, we could use the model `HTMLFile`.

**Comment by saadmk11** [comment]
working on it :)

**Comment by saadmk11** [comment]
@humitos  I changed the Model to `HTMLFile` but I wasn't able to reproduce the error you talked about on `/random/ ` page. Can you tell me how I can reproduce the Error?
