### ISSUE TITLE
Validate dict when parsing the mkdocs.yml file

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5481]
https://github.com/rtfd/readthedocs.org/blob/429126503822056f2e1278461cdf655637035897/readthedocs/doc_builder/backends/mkdocs.py#L90

This function doesn't always return a dict, and we expect a dict in the code. We need to show an appropriated error to the user.

This check should be something similar to https://github.com/rtfd/readthedocs.org/blob/429126503822056f2e1278461cdf655637035897/readthedocs/config/parser.py#L27-L30

We could point to https://www.mkdocs.org/user-guide/configuration/. The file can't be empty either.

**Comment by saadmk11** [comment]
I would like to work on this

**Comment by kpym** [comment]
I have an empty [readthedocs.yml](https://gitlab.com/kpym/recettes-sphinx/blob/ccdb754577cdb6796f694247fc034a84c376d813/readthedocs.yml) and I [obtain](https://readthedocs.org/projects/recettes/builds/8904039/) `Problem in your project's configuration. Parse error in readthedocs.yml: Expected mapping`. Before it was working [without problem](https://readthedocs.org/projects/recettes/builds/8801471/). 

Is this related to this issue ?

**Comment by stsewd** [comment]
Sure!

**Comment by avinashbhat** [comment]
Hi! Is this issue fixed or up to grabs?

**Comment by stsewd** [comment]
Yeah, but there is an open PR already https://github.com/rtfd/readthedocs.org/pull/5490 the only thing missing are tests, you can base your work on that.
