### ISSUE TITLE
Integrate elasticsearch in django admin panel

### ISSUE THREAD

**Issue by dojutsu-user** [rtfd/readthedocs.org#5484]
RTD hosts millions of documentation, each documentation have many versions and each version have many builds.
Searching through it is slower with sql queries.
Elasticsearch can be used to speed up the search in the admin panel.

The workflow can be something like this - 
- Enter the search term in the search bar
- That term is used to query from elasticsearch which gives the relevant `ids` of the model instances
- with the output `ids` from the elasticsearch, those instances can be fetched from the database.

**Advantags :**
- Faster search
- sorting can be customized.

**Comment by rshrc** [comment]
I would like to work on this, but would require some assistance

**Comment by dojutsu-user** [comment]
Hi @rshrc.
Thanks for your interest in contribution.
This issue requires knowledge of Elasticsearch.
Also, this needs to get approval of the core team before any work can be done on this.

**Comment by rshrc** [comment]
I've worked with Elasticsearch before but when I looked up integration of the same with the admin, I did not find a lot of material or documentation. Is there any kind of reference that might help?

**Comment by dojutsu-user** [comment]
@rshrc 
We should wait for the core team to approve this and then we can discuss on its implementation details.

**Comment by humitos** [comment]
@dojutsu-user Hi! I'm not really sure to understand the benefits of using ES on the Admin (Django Admin, I understand, right?). Let me know if I'm wrong.

We currently use the Django Admin only for administration purposes, like changing a slug for a project or a version. Look up for a user and give more permissions, and things like that. How are you thinking to connect ES on these cases?

**Comment by dojutsu-user** [comment]
@humitos 
Elasticsearch can just improve the speed of lookups of versions, user and other things.
But, I think that RTD is not "heavily" dependent on django admin as per your comment above, so this will be just extra code without gaining much output.
