### ISSUE TITLE
Builds page returns 502

### ISSUE THREAD

**Issue by webknjaz** [rtfd/readthedocs.org#5488]
## Details

* Read the Docs project URL: https://tutorial.octomachinery.dev
* Build URL (if applicable): https://readthedocs.org/projects/octomachinery-bot-tutorial/builds/
* Read the Docs username (if applicable): webknjaz

## Expected Result

I see a list of builds

## Actual Result

**502 - Web server received an invalid response while acting as a gateway or proxy server.**

**There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.**

**Comment by stsewd** [comment]
It looks ok now, we saw some timeouts ~5 minutes ago

**Comment by webknjaz** [comment]
I was able to see builds page and trigger a new build a minute ago and then when I opened https://readthedocs.org/projects/octomachinery-bot-tutorial/builds/ I saw 502 again.
So I think the issue is still there.

Also, it didn't autobuild the commit from two hours ago https://github.com/sanitizers/github-bot-tutorial/commit/ea87e719fcd0ff5a88b46ed47ad954c806430a53, this is the reason I went to see that page in the first place... It's probably related to RTD missing events from GitHub (of the top of my head).

**Comment by stsewd** [comment]
Ok, I'm seeing the issue again, the problem is the whole site, not just the build page.

**Comment by stsewd** [comment]
Hopefully this is going to get resolved in some minutes.

**Comment by webknjaz** [comment]
Okay, I was able to open the page once and now it's 502 again...

**Comment by webknjaz** [comment]
I've managed to catch 502 on the front page as well...

**Comment by webknjaz** [comment]
Alright... Works again, seems pretty responsive.

**Comment by webknjaz** [comment]
FTR it still works for me. I think this can be closed now.

**Comment by stsewd** [comment]
Yes, this was solved in the operations level

**Comment by webknjaz** [comment]
@stsewd thanks!
