### ISSUE TITLE
Please enable USE_PDF_LATEXMK flag for the diofant project

### ISSUE THREAD

**Issue by skirpichev** [rtfd/readthedocs.org#5494]
It [seems](https://github.com/rtfd/readthedocs.org/issues/1556#issuecomment-474258894), there should be a separate request to enable this new feature per project, so here it is.  Project URL: https://diofant.readthedocs.io/.

N.B.  pdf docs are build on Travis-ci with the following font packages installed:
```
      - texlive-fonts-recommended
      - lmodern
```
I hope, rtfd environment has above stuff, but could you first - check that?

Thank you.

**Comment by humitos** [comment]
I enabled the feature flag in your project.

`lmodern` is not installed in our build environment, though. I'm not sure that we will able to install it soon since we use Ubuntu 18.04 and it seems that it's only available in 18.10 (https://packages.ubuntu.com/search?keywords=lmodern&searchon=names&suite=cosmic&section=all)

You may probably need to change your font or similar. Although, in that case, this will be a different problem to fix.

**Comment by skirpichev** [comment]
> I enabled the feature flag in your project.

Thank you.  Unfortunately, it [doesn't work](https://readthedocs.org/projects/diofant/builds/8779140/).  It seems, xindy wasn't installed. But you have an issue #5476.

I'll play around a little more trying to use makeindex instead of xindy

> we use Ubuntu 18.04 and it seems that it's only available in 18.10 

Hmm, perhaps I use some wrong Ubuntu 18.04:
https://packages.ubuntu.com/search?suite=bionic&searchon=names&keywords=lmodern

> You may probably need to change your font or similar.

I doubt this will work.

**Comment by skirpichev** [comment]
With makeindex - pdf file was created and looks ok.

But it seems I have found another problem.  Building of the pdf was enabled in the `.readthedocs.yml`.  Yet, after this - no links to this build artifact was displayed, until I turn on "Enable PDF build" checkbox in the web-interface.  Should I create an issue, or there is one (which I fail to find)?

**Comment by humitos** [comment]
You are right. My query on the Ubuntu packages was wrong. I will add `lmodern` to our build environment --although, it won't be deployed _soon_. It may take some weeks: https://github.com/rtfd/readthedocs-docker-images/pull/99

> Should I create an issue, or there is one (which I fail to find)?

Yes. Please. I thought I also saw this problem while debugging.

I'm thinking on closing this issue. Is there any else actionable here?

**Comment by skirpichev** [comment]
Thank you, closed.  #5497 created to track the last problem.

**Comment by humitos** [comment]
> I will add `lmodern` to our build environment --although, it won't be deployed _soon_. It may take some weeks: [rtfd/readthedocs-docker-images#99](https://github.com/rtfd/readthedocs-docker-images/pull/99)

Hey @skirpichev! Where you able to build your PDF _without_ using `lmodern` in the end or this was not a problem when building your PDF on RTD? Thanks!

**Comment by skirpichev** [comment]
> you able to build your PDF without using lmodern

Yep, sorry.  Perhaps, fonts-lmodern was installed on your system.  This variant also works.
