### ISSUE TITLE
Can't login to account

### ISSUE THREAD

**Issue by kwshaw1** [rtfd/readthedocs.org#5498]
## Details

A few months ago I created an account for the content shown at https://pi-spec-test.readthedocs.io/en/latest/, but now I can’t get back into that account. Maybe I don't have the correct user name, because when I try to log in with what I think are correct credentials I get new account setup. Can you send me the login name associated with the content mentioned above, or provide other information that would help me log in? 

## Expected Result

Log into account and see source files for existing project. 

## Actual Result

All login attempts take me to new account setup.

**Comment by stsewd** [comment]
This is the current owner https://readthedocs.org/profiles/kwshaw1/

**Comment by kwshaw1** [comment]
Thanks, I was now able to reset the password and log in.


-      Kevin
