### ISSUE TITLE
Build time out

### ISSUE THREAD

**Issue by dputhier** [rtfd/readthedocs.org#5499]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pygtftk
* Build URL (if applicable): https://readthedocs.org/projects/pygtftk/builds/8780238/
* Read the Docs username (if applicable): dputhier

## Expected Result

* Build pass

## Actual Result

* Issue with time out.

Hello,
Our python package, pygtftk, requires the installation of several external dependencies through conda then the computation of several help files. This help files are dynamically produced using sphinx/sphinxcontrib-programoutput. This allow us to maintain a large set of tools including a CLI containing currently 58 subcommands. It seems that in the latest version we are running out of time since builds are ending with time out (we were close to that in the previous releases). There is no real way for us to limit the time for producing the doc as, we have already limited the number of examples and these examples are performed on artificial datasets that have a very limited number of feature. So we would like to ask whether we could benefit for an extended time to compute our doc ?
Best

**Comment by humitos** [comment]
Hi @dputhier! Did you check this guide https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html ?

Also, I checked your latest builds and it's failing because of a problem in the YAML file.

Besides, it seems you have `latest` and `master` enabled which are the same and both builds are triggering on each push to master.

**Comment by dputhier** [comment]
Hi humitos,
I stopped builds of both latest and master. I also checked the guide. My feeling is that building dynamically our doc is just too time consuming for the ressources provided by readthedoc server. As we cannot limit the number and size of example usages (we would like to extend the documentation...) we will go for a github page to host the doc which will be easier for us to maintained. 
Best

**Comment by humitos** [comment]
> My feeling is that building dynamically our doc is just too time consuming for the ressources provided by readthedoc server. 

We can increase the built time and memory if it's needed, but before doing that I needed to guide you to the first steps that can be done from your side to decrease the usage of resources if possible.

> As we cannot limit the number and size of example usages (we would like to extend the documentation...) we will go for a github page to host the doc which will be easier for us to maintained.

That's a pity :cry:
