### ISSUE TITLE
Pyramid docs PDF version fails to build

### ISSUE THREAD

**Issue by stevepiercy** [rtfd/readthedocs.org#5503]
## Details

Per https://github.com/rtfd/readthedocs.org/pull/5453#issuecomment-474279358 I have opened this issue. This is the `master` branch of Pyramid.

Note that I install extra xelatex packages. I don't know if that is relevant. The build error appears to be because it cannot find 

Please let me know what I can do to troubleshoot. Thank you!

* Read the Docs project URL:

https://readthedocs.org/projects/pyramid/

* Build URL (if applicable):

https://readthedocs.org/projects/pyramid/builds/8781263/

* Read the Docs username (if applicable):

stevepiercy

## Expected Result

Successful build of PDF version

## Actual Result

Failed to build PDF. Tail of build log:

```
Output written on pyramid.pdf (1273 pages).
Transcript written on pyramid.log.
Latexmk: Index file 'pyramid.idx' was written
Latexmk: References changed.
Latexmk: Missing input file: 'pyramid.ind' from line
  'No file pyramid.ind.'
Latexmk: References changed.
Latexmk: Log file says output to 'pyramid.pdf'
Rule 'makeindex pyramid.idx': File changes, etc:
   Non-existent destination files:
      'pyramid.ind'
------------
Run number 1 of rule 'makeindex pyramid.idx'
------------
------------
Running 'internal xindy   -o "pyramid.ind" "pyramid.idx"'
------------
Latexmk: calling xindy( -o pyramid.ind pyramid.idx )
Latexmk: applying rule 'makeindex pyramid.idx'...
Can't exec "xindy": No such file or directory at (eval 11) line 14.
Collected error summary (may duplicate other messages):
  makeindex pyramid.idx: Command for 'makeindex pyramid.idx' gave return code -1
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
Latexmk: Errors, so I did not complete making targets
```

**Comment by humitos** [comment]
Hi @stevepiercy! The problem is that you are using `xindy` and we don't support it yet. It's failing because it's not installed in our environment. See #5476. 

`latex_use_xindy` is setup to `False` by default on Read the Docs right now until we support it. It seems you are set it to `True` at some point. Actually, because it's the default behavior when using `xelatex`

> The default is True for 'xelatex' or 'lualatex' as makeindex, if any indexed term starts with a non-ascii character, creates .ind files containing invalid bytes for UTF-8 encoding. With 'lualatex' this then breaks the PDF build.

http://www.sphinx-doc.org/en/stable/usage/configuration.html#confval-latex_use_xindy

I need to fix that to avoid using xindy while it's not supported.

In the meantime, you should force to be `latex_use_xindy = False` and it should work (it worked locally).

**Comment by stevepiercy** [comment]
@humitos thanks for the tip. Tried again with that setting, and the [PDF version of the docs built successfully](https://readthedocs.org/projects/pyramid/builds/8784843/). 🎆 🍾 🍻 

Once #5507 is merged, then I should remove the setting, correct?

**Comment by humitos** [comment]
> Once #5507 is merged, then I should remove the setting, correct?

It's the same. I won't change anything.

You should remove it if you really want your PDF to build using `xindy`, but it doesn't seem needed for your project.

**Comment by stevepiercy** [comment]
Thank you to everyone who worked on this beast. PDFing is *hard*.
