### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by appellj** [rtfd/readthedocs.org#5504]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/writing-fundamentals-guide/
* Build URL (if applicable): https://readthedocs.org/projects/writing-fundamentals-guide/builds/8781987/
* Read the Docs username (if applicable): appellj

## Expected Result
Successful build

## Actual Result
Getting the following error:

Error
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (8781987).

**Comment by stsewd** [comment]
Your latest build is working, looks like you were experimented the same problem as #5332

**Comment by appellj** [comment]
Weird! Nothing changed in my files, so I don't know why it started working. Thanks!
