### ISSUE TITLE
.readthedocs.yaml not being used

### ISSUE THREAD

**Issue by cjw296** [rtfd/readthedocs.org#5506]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/testfixtures/
* Build URL (if applicable): https://readthedocs.org/projects/testfixtures/builds/8783893/
* Read the Docs username (if applicable): chris@python.org

## Expected Result

I'm trying to move this project from the web config interface to using `.readthedocs.yaml`, I've added the config file and configured it to do a `pip install .[build]` before running Sphinx.

## Actual Result

I've had this work great with new projects of mine and really like it, but `testfixtures` is one of my oldest projects and seems to ignore the `.readthedocs.yaml` that I added in https://github.com/Simplistix/testfixtures/commit/5b0857f125d15a5f4b5b120bede6e0e1934f7ebc. Looking at the build log, I don't see the `pip install .[build]` I've configured.

**Comment by stsewd** [comment]
I'm going to investigate a little more here, at first sight seems like you have a valid config file.

**Comment by stsewd** [comment]
I think there is a syntax error here

https://github.com/Simplistix/testfixtures/blob/5b0857f125d15a5f4b5b120bede6e0e1934f7ebc/.readthedocs.yml#L7-L8

The indentation is wrong.

But instead of showing that error to the user, we are defaulting to create our own config file, I think showing the error should be the way to go, instead of trying to fix it magically.

**Comment by cjw296** [comment]
Ah, nice spot! Yes, showing the error would definitely save lots of work all round :-)

**Comment by stsewd** [comment]
I'm going to fix the bug around not showing the correct message to the user, but fixing the indentation should make your project pass.

**Comment by cjw296** [comment]
yaml fix worked, thanks: https://readthedocs.org/projects/testfixtures/builds/8786855/
