### ISSUE TITLE
Out of date warning about web hooks

### ISSUE THREAD

**Issue by astrofrog** [rtfd/readthedocs.org#5508]
Since the end of last year, I've seen warnings about the change in the web hooks behavior. I've updated all my projects to the new way of dealing with hooks and they are all building fine but I still see the same warnings when I log in to RTD. Is there any way to remove these?

<img width="841" alt="Screenshot 2019-03-20 at 16 04 09" src="https://user-images.githubusercontent.com/314716/54695523-6400e280-4b2a-11e9-9c0c-bf394a9a1e70.png">

**Comment by stsewd** [comment]
You can remove them by clicking the links (middle click doesn't work)

**Comment by astrofrog** [comment]
Ah great, thanks!
