### ISSUE TITLE
Documentation is loaded very slowly

### ISSUE THREAD

**Issue by basnijholt** [rtfd/readthedocs.org#5515]
## Details

* Read the Docs project URL: https://adaptive.readthedocs.io/en/latest/docs.html#examples
* Build URL (if applicable): https://readthedocs.org/projects/adaptive/builds/8787274/
* Read the Docs username (if applicable): `basnijholt`

## Expected Result

The page/documentation to load quickly.

## Actual Result

Loading [this](https://adaptive.readthedocs.io/en/latest/docs.html#examples) page happens with only 50 kB/s (average) or 200 kB/s (max) and since the page is rather large, it takes a minute to display.

I am not sure about this but I suspect that this happens since @ericholscher [moved the builds to the priority queue](https://github.com/rtfd/readthedocs.org/issues/4778#issuecomment-445915622) (which is great for our build time.)

**Comment by ericholscher** [comment]
This page is incredibly large, how much data are you trying to serve before the page is rendered?

**Comment by stsewd** [comment]
Loading all those interactive graphics make the page slow, I don't think we can do something about that.

**Comment by humitos** [comment]
> I am not sure about this but I suspect that this happens since @ericholscher [moved the builds to the priority queue](https://github.com/rtfd/readthedocs.org/issues/4778#issuecomment-445915622) (which is great for our build time.)

This is not related with loading slowly.

> This page is incredibly large, how much data are you trying to serve before the page is rendered?

It transfers 7.20Mb. That's probably the problem. `docs.html` file is 6.32Mb and it includes _a lot_ of inline javascript without being minified. That's the problem to me.

**Comment by basnijholt** [comment]
Thanks a lot for the comments! 

I had the suspicion of the page being throttled in some way, which doesn't appear to be true.

The solution doesn't lie with RTD, but I'll address this issue in `bokeh` where I could indeed suggest the use of minified JS.

Thanks again for the great service that you guy provide! I'll close this issue.
