### ISSUE TITLE
Link to GitHub include 'origin' and thus are broken

### ISSUE THREAD

**Issue by paulmeems-waterwatchfoundation** [rtfd/readthedocs.org#5518]
## Details
I'm facing the same problem as mentioned in #3203 
That issue is closed.

* Read the Docs project URL: http://datastandard.globalcoffeeplatform.org
* Build URL (if applicable): https://readthedocs.org/api/v2/build/8790271.txt
* Read the Docs username (if applicable):

## Expected Result
I expect the 'Edit on GitHub' to be
https://github.com/globalcoffeeplatform/CoffeeDataStandard/blob/master/docs/source/index.rst
Without the 'origin' part.
*A description of what you wanted to happen*

## Actual Result
Now the link is 
https://github.com/globalcoffeeplatform/CoffeeDataStandard/blob/origin/master/docs/source/index.rst

*A description of what actually happened*
I've rebuild several times. Perhaps I need a different version of some tool?
I'm using Spinx v1.8.4 and sphinx-rtd-theme v0.4.2

**Comment by stsewd** [comment]
I'm not really sure why we put the `origin` there, but you can solve this problem in the meantime going to your project's advanced settings, the `default branch` setting will be filled with `master`, you just need to change it to `blank` (which is basically the same as master) and click `save`.

**Comment by paulmeems-waterwatchfoundation** [comment]
Thanks @stsewd your workaround works.

**Comment by stsewd** [comment]
Looks like we are mixing some fields when saving the versions

https://github.com/rtfd/readthedocs.org/blob/5ed7677e864360b10b9f2d0efbf2b22ac8af354c/readthedocs/builds/models.py#L180-L185
