### ISSUE TITLE
Owner change: wagtail-modeltranslation

### ISSUE THREAD

**Issue by DiogoMarques29** [rtfd/readthedocs.org#5524]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/wagtail-modeltranslation/
* Build URL (if applicable): https://wagtail-modeltranslation.readthedocs.io/en/latest/
* Read the Docs username (if applicable):  InfoPortugal

## Expected Result
I would like to require the ownership of the RTD project as the current owner is not a main committer of the github repo.

## Actual Result

N/A

**Comment by humitos** [comment]
Hi @DiogoMarques29! I sent an email to the owner following our policy: http://docs.readthedocs.io/en/latest/abandoned-projects.html

I will come back here if I don't have a reply in 6 weeks.

/remind me about take action here in 6 weeks

**Comment by humitos** [comment]
I received a confirmation to add you as maintainer from the owner. I've already done this. Let me know if anything.
