### ISSUE TITLE
Improve installation guide suggestion

### ISSUE THREAD

**Issue by xwy27** [rtfd/readthedocs.org#5525]
## Details

As a windows user, when following the [installation guide](https://docs.readthedocs.io/en/latest/install.html) for Other OS: `source venv/bin/activate`, I get the error output for no source command and no such directory.

## Expected Result

1. Virtual environment is activated.
1. The active file is in `\venv\bin\` folder

## Actual Result

1. Error occurs.
1. The activate file is in `\venv\Scripts\` folder

## Solution

After reading the docs of [virtualenv userguide](https://virtualenv.pypa.io/en/stable/userguide/), I find that the activate file for virtualenv is in `\venv\Scripts\` folder for windows only, but `\venv\bin\` folder for other operating systems. Also windows prohibits the scripts execution.

Following steps helps:

1. Execute the powershell as an administrator.
1. Relax system’s script execution policy to AllSigned by command `Set-ExecutionPolicy AllSigned`
1. Relax the system execution policy to allow running of local scripts without verifying the code signature using the command:`Set-ExecutionPolicy RemoteSigned`
1. Activate the virtualenv with the command: `.\venv\Scripts\activate`

More, if using cmd, you can just skip the script execution policy configuration and activate the virtualenv with the command: `.\venv\Scripts\activate`

## Hope

I hope the starting guide for installation could be more consummate and if you want, I could make a pull request for updating the doc.

**Comment by stsewd** [comment]
Actually, RTD doesn't run on Windows, we use symbolic links and other unixlike commands. I think there is a way of using something like that on Windows, but I don't think it will work with the default cmd/powershell

**Comment by xwy27** [comment]
Ops, I see that. It works rendering the index page, but could not work for other fucntions.

**Comment by stsewd** [comment]
We still can have some notes for windows users, like using the linux subsystem could work, but I don't have experience with that.

**Comment by xwy27** [comment]
Actually, windows provides WSL(windows subsystem for linux) to match the requirement of running native Linux command-line tools directly on Windows. I'm trying to find whether it could works if RTD runs in the WSL and is retrieved in windows browser. I would post the result later.

**Comment by xwy27** [comment]
Unfortunately, I've tried the WSL, but it gets the same result while RTD serving in windows.
It always returns HTTP connection error with **status code 500**. The raising error shows new connection could not be established(I search). I could not solve the problem. 

Below are the error images:
![front_display_error.jpg](https://i.loli.net/2019/03/23/5c95be7a75a4c.jpg)
![back_display_error.jpg](https://i.loli.net/2019/03/23/5c95be7a6c197.jpg)

**Comment by saadmk11** [comment]
@xwy27 you need elasticsearch installed and running on your local machine to use the search functionality.

**Comment by xwy27** [comment]
@saadmk11 Yes, I found that the elasticsearch is not activate. But the error output even occur when I try to login with Github. It still has a HTTP connection error.

**Comment by saadmk11** [comment]
@xwy27 you need to setup allauth for that. You can use ngrok for that as you need a live server for it. I would suggest importing projects manually for development or use the test data.
