### ISSUE TITLE
Set no shallow clone option for lf-releng-global-jjb

### ISSUE THREAD

**Issue by zxiiro** [rtfd/readthedocs.org#5527]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/lf-releng-global-jjb/

We're running into issues caused by #5031 shallow cloning since we use a tool called reno to generate release notes from git commits. Please disable shallow clone for this project.

## Expected Result

Reno is able to execute in RTD with access to the full git repo.

## Actual Result

Reno blows up due to missing commit objects.

**Comment by davidfischer** [comment]
I set the flag. Please reopen if you encounter any issues.
