### ISSUE TITLE
Request: Scroll-bar for the left hand pane menu.

### ISSUE THREAD

**Issue by ni-code** [rtfd/readthedocs.org#5541]
* Build URL (if applicable):
http://docs.godotengine.org/en/3.1/ or other docs that have long "menus"

## Expected Result
Currently there is no visible scoll-bars in the left hand pane menu, Long menu lists can be scrolled with the mouse wheel, but it would be nice if there was a visible scroll bar, it would also help to visualize that there is more items in the menu list, than just the ones displayed.

*A description of what you wanted to happen*
Visible scroll-bar in the left hand pane for big menu lists.

Because my english is not native, here is a picture that better describe the issue:

![docs_scroll_bar](https://user-images.githubusercontent.com/10292929/55043143-a9427a00-502c-11e9-8731-4f0e2688f833.png)

**Comment by stsewd** [comment]
Thanks, this issue is part of the theme, not from rtd itself. Please subscribe to https://github.com/rtfd/sphinx_rtd_theme/issues/468
