### ISSUE TITLE
Build error with build id #8819304

### ISSUE THREAD

**Issue by craig8** [rtfd/readthedocs.org#5543]
## Details:

* Project URL: https://readthedocs.org/projects/volttron/
* Build URL(if applicable): https://readthedocs.org/projects/volttron/builds/8819304/
* Read the Docs username(if applicable): craig8

## Expected Result

The build to work

## Actual Result

Failed in the cloning I think.  What is weird is the clone command include . as where to clone it.  That makes it fail.

![image](https://user-images.githubusercontent.com/3979063/55044122-71790980-500f-11e9-92e5-c84bf14d575e.png)

**Comment by stsewd** [comment]
There is an invalid submodule in your repo https://github.com/VOLTTRON/volttron/blob/58b015c1e6f62fc1cf7151f4dd44a5a81bd295e0/.gitmodules#L2

See #4371

**Comment by craig8** [comment]
That works for me as our project shouldn't have submodules this helps me move forward!  Thank you for your help...would never have found this without you!
