### ISSUE TITLE
Please enable USE_PDF_LATEXMK flag for the faust project

### ISSUE THREAD

**Issue by ask** [rtfd/readthedocs.org#5548]
## Details

* Read the Docs project URL: http://faust.readthedocs.io
* Read the Docs username (if applicable): faustdocs

**Comment by humitos** [comment]
I enabled it and triggered a build at https://readthedocs.org/projects/faust/builds/8846501/

Let me know if anything. Thanks!

**Comment by humitos** [comment]
The build failed because you need to disable `xindy` since we don't support it yet (this is already fixed in master, but it's not deployed)
