### ISSUE TITLE
Ability to Set the version of the documentation for a project that you want to see

### ISSUE THREAD

**Issue by s7726** [rtfd/readthedocs.org#555]
When googling around for documentation I often find I'm taken to the documentation for a version of something I don't have.

I would like to be able to set that I want to see version x of project y so that when I come in from another link of some kind I get a notification of some kind that makes it immediately apparent that I'm not looking at the version of the documentation that I have set.

I personally don't mind if I have to be logged in or a cookie is set to achieve this.

**Comment by agjohnson** [comment]
We'd probably implement this with our "collections" concept, otherwise I can't think of a UI that wouldn't be really complicated. Closing this and moving to #3784
