### ISSUE TITLE
Local instance allows weak passwords

### ISSUE THREAD

**Issue by jasonaowen** [rtfd/readthedocs.org#5551]
## Details

The [installation instructions](https://docs.readthedocs.io/en/stable/install.html) say to run `python manage.py createsuperuser`, which prompts for a password; self-sign-up users are also prompted for a password. By default, `createsuperuser` requires a non-empty password, and self-sign-up requires a password that is six characters or longer. Neither impose any further password complexity requirements, including checking for well-known passwords like `password` or `123456`.

## Expected Result

An error message - or at least a warning - about using insecure passwords.

## Actual Result

"Superuser created successfully." and successful sign-up.

**Comment by davidfischer** [comment]
I'm not opposed to having a more sane default setting of [`AUTH_PASSWORD_VALIDATORS `](https://docs.djangoproject.com/en/1.11/topics/auth/passwords/#enabling-password-validation).
