### ISSUE TITLE
Recommended Docker image does not contain Python 3.7

### ISSUE THREAD

**Issue by jasonaowen** [rtfd/readthedocs.org#5553]
## Details

The [instructions for setting up a Docker build environment](https://docs.readthedocs.io/en/stable/development/buildenvironments.html) specify using the `latest` image:

> To get started using Docker for build environments, you’ll need to pull down at least one build image. For example, to pull down our latest image:
> 
> `docker pull readthedocs/build:latest`
> 
> The default image used by our build servers is `readthedocs/build:latest`. This would be a good place to start testing as the latest version could operate differently. See DOCKER_IMAGE below for setting this configuration option.

Attempting to build with that image fails due to the image not including Python 3.7.

Looking at the [Docker Hub image tags](https://hub.docker.com/r/readthedocs/build/tags), it appears that the `latest` tag hasn't been updated in nearly a year, but there are several other, more recent tags, including `stable`.

## Expected Result

Following the [instructions to build the sample data](https://docs.readthedocs.io/en/stable/install.html#get-and-run-read-the-docs) (combined with the instructions on setting up a Docker build environment) results in a successful build.

## Actual Result

The build failed, with the error message `/bin/sh: 1: python3.7: not found`.

**Comment by humitos** [comment]
I can confirm this is an issue. I just downloaded `6b9ab0a5ddaf` and it does not contain `python3.7`.

Although, there is something weird since it says the image was built 12 months ago

```
$ docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
readthedocs/build                               latest              6b9ab0a5ddaf        12 months ago       8.86GB
```

So, it seems they are not properly tagged.

**Comment by humitos** [comment]
I added a rule to our Docker Hub repository that matches `5.0.x` to `latest`. This should not be an issue anymore.
