### ISSUE TITLE
Docker instructions should estimate size

### ISSUE THREAD

**Issue by jasonaowen** [rtfd/readthedocs.org#5554]
## Details

The [instructions on setting up a Docker build environment](https://docs.readthedocs.io/en/stable/development/buildenvironments.html) describe pulling the build image, but give no sense of how much space will be required. The [Docker Hub list of tags](https://hub.docker.com/r/readthedocs/build/tags) does not seem to accurately describe how much space the assembled image requires.

Running `docker images` after pulling gives a more accurate estimate:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
readthedocs/build   latest              6b9ab0a5ddaf        12 months ago       8.86GB
```

...but still does not account for the temporary space needed to download, decompress, and apply layers.

On my machine, that image required approximately 10GB of space in Docker's data root (which, in the [Ubuntu-packaged version](https://packages.ubuntu.com/bionic-updates/docker.io), defaults to `/var/lib/docker`).

(See also #5553, as `readthedocs/build:latest` may not be the best image to use for estimating.)

## Expected Result

The installation instructions should estimate the minimum amount of disk space required, so that users can make sure they are prepared before downloading several gigabytes.

## Actual Result

I had to free up extra space and retry the download.

**Comment by stsewd** [comment]
We could mention that each image is around 5 and 9 GB

This are my local images

```
readthedocs/build-dev                           2.0                         2 months ago        5.48GB
readthedocs/build-dev                           3.0                         2 months ago        8.87GB
readthedocs/build-dev                           stable                      2 months ago        8.87GB
readthedocs/build-dev                           4.0                         2 months ago        6.8GB
readthedocs/build-dev                           latest                      2 months ago        6.8GB
```
