### ISSUE TITLE
The mkdocs_json builder is obsolete

### ISSUE THREAD

**Issue by orlnub123** [rtfd/readthedocs.org#5560]
While looking into https://github.com/rtfd/readthedocs.org/issues/5559 I tried to figure out where the mkdocs_json builder was used. It was added in https://github.com/rtfd/readthedocs.org/commit/92a183a56dd754287ae02774c2af013101818ab7 but has since become obsolete and isn't used anywhere.

The only difference between the mkdocs_json builder and the regular mkdocs builder is that `mkdocs json` gets used instead of `mkdocs build`. Since that commit the `mkdocs json` command has been deprecated in MkDocs 0.13.0 and removed in 0.17.0.

This isn't a big problem but I thought I'd open this issue anyway.

**Comment by dojutsu-user** [comment]
Hi @orlnub123 
Thanks for opening this issue.
I think it is a duplicate of #4205

**Comment by orlnub123** [comment]
You're right, thanks for looking into it! I'll close this in favor of that one.
