### ISSUE TITLE
Mention that PDF/epub is not generated on MkDocs

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5561]
In our [YAML documentation](https://docs.readthedocs.io/en/latest/config-file/v2.html#formats) we mention that you can set `formats: all` (or include `pdf`) to build the PDF format of your documentation.

Although, there are some people expecting a PDF/epub output when using MkDocs which does not support building PDF/epub as an output.

We should create a note in that section communicating this.

Also, it may worth to add the same note under the Advanced Settings where we have the checkbox for building the PDF/epub.

**Comment by rshrc** [comment]
Will send a PR addressing this issue

**Comment by profgrammer** [comment]
Hi, I would like to work on this issue, How can I proceed?

**Comment by dojutsu-user** [comment]
Hi @profgrammer 
Thanks for your interest in contributing.
But, there's already a PR for this issue #5565.

**Comment by stsewd** [comment]
Fixed in https://github.com/rtfd/readthedocs.org/pull/5565
