### ISSUE TITLE
Owner addition / transfer: pika.readthedocs.io

### ISSUE THREAD

**Issue by lukebakken** [rtfd/readthedocs.org#5562]
## Details

* Read the Docs project URL:

https://pika.readthedocs.io/

https://github.com/pika/pika

* Read the Docs username (if applicable):

Currently it's probably `gmr` (Gavin Roy). My username is `lukebakken`.

## Expected Result

User `lukebakken` is allowed to manage `pika.readthedocs.io`

**Comment by stsewd** [comment]
Can you please explain a little more? Why do you need permissions? Why `gmr` can't give you permissions?

**Comment by lukebakken** [comment]
@gmr has been unresponsive to my email over the past month. As you can see from the following issues in the Pika project, this is a long-standing problem:

https://github.com/pika/pika/issues/1196

https://github.com/pika/pika/issues/1103

I just released Pika `1.0.0` and the out-of-date documentation at pika.readthedocs.io is confusing users. To be honest I'm surprised any manual intervention is necessary to update RTD. If this can't be resolved by the end of this week I will have to host the Pika docs someplace else. Updating RTD permissions is the easiest solution all around. Thanks!

**Comment by stsewd** [comment]
I think the problem is https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services, do you have access to the repo's webhooks? If you don't, after having permissions in rtd, you'll still need to trigger a manual build every time.

BTW, I just triggered a new build to latest manually, so at least you have that up to date, I can't activate new versions.

**Comment by lukebakken** [comment]
Thank you for triggering the new build.

Yes, I have administrative permissions for the Pika repository (https://github.com/pika/pika) and I can modify / add webhooks. I will do that as soon as I can access the integration settings for Pika on RTD (according to [this doc](https://docs.readthedocs.io/en/stable/webhooks.html#webhook-integration-github)).

**Comment by gmr** [comment]
Luke, what is your rtd username so I can add you as a maintainer?

>

**Comment by lukebakken** [comment]
I just confirmed that I have been added as a maintainer. Thanks everyone!
