### ISSUE TITLE
Banners don't render nicely depending on Project CSS

### ISSUE THREAD

**Issue by koaning** [rtfd/readthedocs.org#5563]
Howdy. 

I'm digging your service (it seems to work a bit nicer than github pages for my project) which I why I'd like to notify you of a possible optimisation for your ads. I have a sphinx template with a custom css which makes the text of your banner slightly hard to read. 

![image](https://user-images.githubusercontent.com/1019791/55458992-b512db00-55ee-11e9-8066-9402501c1fcf.png)

## Details

* Read the Docs project URL: https://scikit-lego.readthedocs.io/en/latest/

## Expected Result

The text might become hard to read depending on my custom css settings. 

## Actual Result

The css might be able to change based on the background color?

**Comment by koaning** [comment]
@davidfischer this is a ping, just to check if this is on your roadmap. i am pining you because @humitos assigned you.

**Comment by davidfischer** [comment]
@koaning I will be the one working on this. It isn't the top of my queue but I should get to it in the next week.
