### ISSUE TITLE
Inability to delete old builds breaks use of exact redirects

### ISSUE THREAD

**Issue by DominikaK** [rtfd/readthedocs.org#5564]
## Details

* Read the Docs project URL: https://readthedocs.com/projects/ez-systems-developer-documentation/
* Build URL (if applicable): https://doc.ezplatform.com/en/2.2/
* Read the Docs username (if applicable):

## Expected Result

We use Exact Redirects to redirect from outdated documentation versions (in this case 2.2) to the latest version.
Our redirect looks like this: `/en/2.2/$rest -> /en/latest/`

To use a redirect like this, we uncheck the old version and set as Public (per information from RtD support).

We need to be able to delete old builds to get the redirect to work.

## Actual Result

Because it is impossible to delete old builds, the redirect does not work. Instead, the old version is still available.

**Comment by humitos** [comment]
Hi @DominikaK! It seems you are using readthedocs.com (corporate) service and this is the repository for readthedocs.org (community) service only.

Please, contact us via email at support@readthedocs.com so we can follow up from there.

Thanks!

> I'm closing this issue from here.

**Comment by stsewd** [comment]
Just in case, you should see a `clean` button in the versions list.
