### ISSUE TITLE
Validate docs dir before writing custom js

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5568]
If the user puts an invalid docs dir, we fail with a generic error, we should raise a more specific one.

https://github.com/rtfd/readthedocs.org/blob/44951fbf8fe1fe12fa9f99f3075f87bd77188525/readthedocs/doc_builder/backends/mkdocs.py#L175-L176

**Comment by saadmk11** [comment]
@stsewd Should the validation be here?
https://github.com/rtfd/readthedocs.org/blob/44951fbf8fe1fe12fa9f99f3075f87bd77188525/readthedocs/doc_builder/base.py#L84

or should we put it be before
https://github.com/rtfd/readthedocs.org/blob/44951fbf8fe1fe12fa9f99f3075f87bd77188525/readthedocs/doc_builder/backends/mkdocs.py#L175-L176
