### ISSUE TITLE
How do disable "On GitHub" options in RTD footer

### ISSUE THREAD

**Issue by pllim** [rtfd/readthedocs.org#5570]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable):
* Read the Docs username (if applicable): pllim

## Expected Result

Want to hide the "On GitHub" options (both View and Edit) in RTD footer (that thingy that let you choose version on bottom right).

## Actual Result

Not sure how to disable it. I found the code snippet in your repository but how do I customize the footer?

https://github.com/rtfd/readthedocs.org/blob/50cb9a24045cf29c5719ffb92fd22cfdd54b0f34/readthedocs/restapi/views/footer_views.py#L119-L130

https://github.com/rtfd/readthedocs.org/blob/b02baab55ae4646c4d2be70d3abd6fbb798af0a4/readthedocs/restapi/templates/restapi/footer.html#L79-L89

Thank you for this invaluable service to the open source community!

**Comment by stsewd** [comment]
I don't think this is possible right now with css, we should put classes to the html labels to make it work.

**Comment by stsewd** [comment]
You could still do it with a hacky way using the `injected` class

https://github.com/rtfd/readthedocs.org/blob/ee5ffd0d5e9951da95942fa1badb796ac3f58484/readthedocs/restapi/templates/restapi/footer.html#L2-L2

**Comment by pllim** [comment]
@stsewd , thanks for the quick reply. My HTML/CSS skills are very limited. Can you please elaborate on the hacky option? How do I use it to overwrite the footer?

**Comment by stsewd** [comment]
I believe this should work
```css
.rst-other-versions > dl:nth-child(3) {
   display: none;
}
```

**Comment by pllim** [comment]
@stsewd , ah, the snippets you posted were meant for the RTD codebase and not downstream in our own project?

**Comment by stsewd** [comment]
You need put it on your project

**Comment by stsewd** [comment]
Closing as duplicated of https://github.com/rtfd/readthedocs.org/issues/3507
