### ISSUE TITLE
How to change the hyperlink of the title

### ISSUE THREAD

**Issue by Code-Egg** [rtfd/readthedocs.org#5573]
## Details

* Read the Docs project URL: https://mkdocs.readthedocs.io/en/stable/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Actual Result
Click the top left home icon will redirect to the original URL(https://mkdocs.readthedocs.io/en/stable/), not sure how I can define a specific URL,e.g. "https://google.com" and it won't effect any other existing pages.

**Comment by stsewd** [comment]
If you mean for mkdocs projects, you should ask there, or search if there is an option in https://www.mkdocs.org/user-guide/configuration/ For sphinx, you can override the template used in https://github.com/rtfd/sphinx_rtd_theme/blob/a49a812c8821123091166fae1897d702cdc2d627/sphinx_rtd_theme/layout.html#L119

We don't maintain the theme for mkdocs https://github.com/mkdocs/mkdocs/tree/master/mkdocs/themes/readthedocs

Closing as this isn't a problem with rtd, you can use other channels to post questions https://docs.readthedocs.io/en/stable/support.html
