### ISSUE TITLE
Please enable USE_PDF_LATEXMK flag for the yellowbrick-zh project

### ISSUE THREAD

**Issue by bbengfort** [rtfd/readthedocs.org#5574]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/yellowbrick-zh/
* Build URL (if applicable): https://www.scikit-yb.org/zh/latest/
* Read the Docs username (if applicable): bbengfort

## Expected Result

Per [the docs for building PDF format for non-ASCII languages](https://docs.readthedocs.io/en/latest/guides/pdf-non-ascii-languages.html), I am requesting that the Read the Docs core team enable the `USE_PDF_LATEXMK` feature flag for the chinese translation of our documentation. I have already updated our `conf.py` with the settings for _Chinese_ projects (the documentation is currently a mix of Chinese and English). 

We hope that enabling this flag will allow the build process to be completed successfully. 

## Actual Result

We are getting pdflatex errors during the build process.

**Comment by humitos** [comment]
@bbengfort done!

Closing. Feel free to reopen if you consider.

Also, I'd appreciate your feedback here so we can start thinking on enable it by default.

**Comment by bbengfort** [comment]
@humitos perfect, thank you -- looks like everything is building correctly now! 

Unfortunately, I don't have a lot of feedback in this area. We are fortunate to have speakers of languages besides English contribute to our documentation and translate them. It is my hope that in the future, automatic translation tools will be useful enough to also support this and make our code bases much more accessible to international audiences. In the meantime, it seems that we should be prepared for this eventuality, and if there are no consequences to turning on the flag by default, then perhaps that would remove a barrier that would help lead to more international documentation. 

At the very least, a checkbox in the UI would be awesome!

**Comment by humitos** [comment]
>  there are no consequences to turning on the flag by default, then perhaps that would remove a barrier that would help lead to more international documentation

Yes! There is where I'm wanting to go. This is a new feature and I was worried that it could break some projects if it's enabled by default. That's why it's under a flag for now.

I'm trying to get more people testing it and giving me some feedback in return. Actually, it feels very solid for now and we will probably enable it by default soon.

**Comment by bbengfort** [comment]
Great news! Thank you for all your hard work on Read the Docs!
