### ISSUE TITLE
Gitlab login failure

### ISSUE THREAD

**Issue by cromefire** [rtfd/readthedocs.org#5577]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): Should be `Cromefire_` or `cromefire_`

## Expected Result

I'm able to login/sign up via Gitlab

## Actual Result

```
Social Network Login Failure

An error occurred while attempting to login via your social network account.
```

**Comment by humitos** [comment]
Hrm. I couldn't reproduce your issue.

* Did you accept RTD app on Gitlab?
* Can you revoke it permission from Gitlab page and login again?
* Can you connect your account from the Admin page under RTD?

**Comment by cromefire** [comment]
1. Yes
2. No
3. No

**Comment by cromefire** [comment]
I tried everything multiple times

**Comment by stsewd** [comment]
> Can you revoke it permission from Gitlab page and login again?
> no

Why can't you do that? You should be able to remove the rtd integration app from your github account

**Comment by cromefire** [comment]
> Why can't you do that? You should be able to remove the rtd integration app from your github account

I can revoke it, reauthorize it, but it doesn't work

**Comment by cromefire** [comment]
Don't you have some logs that collect errors like this?

**Comment by cromefire** [comment]
It gives me some `code` (I guess that OAuth2) and `state` parameters. Does the `state` provide some useful information to you?

**Comment by cromefire** [comment]
Works again somehow BTW

**Comment by stsewd** [comment]
Thanks for the update!
