### ISSUE TITLE
Where is the admin page? Srsly.

### ISSUE THREAD

**Issue by jkhartshorne** [rtfd/readthedocs.org#5581]
The documentation constantly refers to things that must be done on the admin page. There is no discussion of *where* this page might be found. This seems like a serious oversight.

Also, where is the admin page? I've spent over an hour trying to track it down...

**Comment by dojutsu-user** [comment]
Hi @jkhartshorne 
You can access the admin page from here.
Link: `https://readthedocs.org/projects/<project-slug>/`

![export](https://user-images.githubusercontent.com/29149191/55910003-eeed6e00-5bfa-11e9-9f89-f894e381b2d4.png)

**Comment by stsewd** [comment]
We could expand a little about this in the initial page of the docs (or the first time we mention it)
