### ISSUE TITLE
self-hosted readthedocs issue

### ISSUE THREAD

**Issue by cutemomo6256** [rtfd/readthedocs.org#5583]
Hi, I've got an issue when I use self-hosted readthedocs
when rtd build on this step--> python3.6 -mvirtualenv --no-site-packages --no-download /readthedocs.org/user_builds/testrtd/envs/latest

I got an error that says --> readthedocs.doc_builder.environments:709[107]:ERROR (Build)[testrtd:latest][Errno 2] no such file or directory: '/readthedocs.org/user_builds/testrtd/envs/latest/readthedocs-environment.json'

can anyone help me out please. I've uses the docker to build.
thanks a lot!

**Comment by stsewd** [comment]
How are you using docker? Do you mean running the whole project with docker or https://docs.readthedocs.io/en/stable/development/buildenvironments.html?

**Comment by cutemomo6256** [comment]
both of it, including readthedocs service and readthedocs build environments
I've use "-v /var/run/docker.sock:/var/run/docker.sock" on readthedocs service
and set the "base.py" file of "docker enable" to true,

I've read the error log, and the log tells me that it has start the container of  readthedocs build environments, but stop at

 readthedocs.doc_builder.environments:709[107]:ERROR (Build)[testrtd:latest][Errno 2] no such file or directory: '/readthedocs.org/user_builds/testrtd/envs/latest/readthedocs-environment.json'

thanks again for helping me.

**Comment by cutemomo6256** [comment]
Here is the complete log, which hope you help me out with my problem, thanks!
![擷取](https://user-images.githubusercontent.com/46988439/56015751-af26a380-5d2c-11e9-8497-0cbd21d847e8.PNG)

**Comment by stsewd** [comment]
I believe this is a problem with permissions, you should check if the file is created with enough permissions for the user running the docker process.


We have some problems when running docker locally in linux systems https://github.com/rtfd/readthedocs.org/pull/5556

Short story, we have the user and group harcoded in the docker file 

https://github.com/rtfd/readthedocs-docker-images/blob/869edef45470331670112c36acaf4a086430d3d7/Dockerfile#L138-L142

We don't support custom installations, you can check https://docs.readthedocs.io/en/stable/support.html for other channels of support. Closing as this isn't a rtd bug, also we have the another PR to track the problem with the permissions problems in linux.
