### ISSUE TITLE
Error in `Versions` dashboard when a project has many versions

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5584]
When a user has many versions and edits the version from the `Versions` menu in the admin panel, they can hit this problem

`The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.` 

Sentry issue https://sentry.io/organizations/read-the-docs/issues/790916614/?project=148442&referrer=RegressionActivityEmail

From our docs project https://readthedocs.org/dashboard/docs/versions/

We can get around setting that to `None`, but we'll lose the security protection.

I think we could remove that menu from there. Some pros/cons

- It feels weird to paginate the versions to edit them (with the current UI at least?)
- The list is very large, and already have the `Versions` menu in the nav bar (which is paginated)
- The current versions list in the admin menu allows users to activate/deactivate  change privacy in several versions at once (we will lose this if we remove it).
- Is this really used anyway? like editing several versions is something users do really often?

**Comment by saadmk11** [comment]
I have ran into this issue in the django admin panel also while trying to edit a project.
The versions menu on the admin panel is almost similar to the version menu on the navbar which seems much more efficient to handle version editing. and for the admin panel version page if the project has a lot of versions it creates a very long list of forms which feels less and less usable to my eyes.

**Comment by dojutsu-user** [comment]
> I have ran into this issue in the django admin panel also while trying to edit a project.

Happens with me also.

> The versions menu on the admin panel is almost similar to the version menu on the navbar which seems much more efficient to handle version editing.

I am +1 with @saadmk11 here.

I am +1 on removing the menu from there because
- It is creating problems
- The long list doesn't look good to eyes
- We have similar implementation in `readthedocs.org/projects/<slug>/versions/`

> Is this really used anyway? like editing several versions is something users do really often?

I don't think that users edit 9-10 versions at a single time.

Also I think that we can set `DATA_UPLOAD_MAX_NUMBER_FIELDS` to `None` in development environment only as it creates problem when using django admin panel.

**Comment by davidfischer** [comment]
> I think we could remove that menu from there.

:+1: Definitely

> Is this really used anyway? like editing several versions is something users do really often?

It's kind of annoying. I checked GA and it does ~1,500 pageviews/month which is ~0.1%. I think we can kill it.

**Comment by dojutsu-user** [comment]
@davidfischer 
Can I start working on this?
Also, what is your opinion on setting `DATA_UPLOAD_MAX_NUMBER_FIELDS` to `None` in development environment?

**Comment by davidfischer** [comment]
> Can I start working on this?

Yes please.

> Also, what is your opinion on setting DATA_UPLOAD_MAX_NUMBER_FIELDS to None in development environment?

I would rather leave this on in development as it catches a type of problem. It forces us to not ever show 1,000+ fields at a time which is definitely broken UX. Also, I think it is more secure in production. Feel free to override it in your `local_settings.py` file.

**Comment by dojutsu-user** [comment]
@davidfischer 
Thank you for the information.
Will make a PR soon.
