### ISSUE TITLE
Search doesn't work for only numbers search

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5591]
We got an email with this report

https://topicaltraceflags.readthedocs.io/en/latest/search.html?q=8666&check_keywords=yes&area=default

returns no results, but, for example, there are

https://topicaltraceflags.readthedocs.io/en/latest/cat/qry_StatsAndEst.html
https://topicaltraceflags.readthedocs.io/en/latest/cat/qry_CompInfo.html  

pages with "8666" term.

**Comment by humitos** [comment]
It works now!

The last build for this documentation was almost 2 years ago and we may turned off some part of the logistic (ImportedFile model) needed for the migration/reindex of the projects. That's probably why this stop working: there were no ImportedFile for this project and version in the db.
