### ISSUE TITLE
Build error with build id #8916159

### ISSUE THREAD

**Issue by simontorres** [rtfd/readthedocs.org#5592]
## Details:

Builds have failed since 3 month ago. I had a `readthedocs.yml` (without the dot) file configured but I set the configuration mostly on the webpage. Now I'm renaming it to `.readthedocs.yml` and see what happens, but it seems very unlikely that it will fix the build issue.

* Project URL: https://readthedocs.org/projects/goodman_pipeline/
* Build URL(if applicable): https://readthedocs.org/projects/goodman/builds/8916159/
* Read the Docs username(if applicable): simontorres

## Expected Result

a build to succeed

## Actual Result

- the project is cloned and the master branch is checked out but stops there and the information regarding the error is not clear.

Here is the raw output

```
Read the Docs build information
Build id: 8916159
Project: goodman
Version: latest
Commit: 0b7845cbccfb5a4dca8071ea08732bc09ce045d9
Date: 2019-04-15T14:37:43.754470Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-04-15T14:39:01.158117Z, end-time: 2019-04-15T14:39:01.172107Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/soar-telescope/goodman_pipeline.git


[rtd-command-info] start-time: 2019-04-15T14:39:01.236899Z, end-time: 2019-04-15T14:39:04.113821Z, duration: 2, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50


[rtd-command-info] start-time: 2019-04-15T14:39:04.351370Z, end-time: 2019-04-15T14:39:04.399851Z, duration: 0, exit-code: 0
git checkout --force origin/master
HEAD is now at 0b7845c Merge pull request #271 from simontorres/fix_new_bugs_trace

[rtd-command-info] start-time: 2019-04-15T14:39:04.511912Z, end-time: 2019-04-15T14:39:04.535482Z, duration: 0, exit-code: 0
git clean -d -f -f
```

**Comment by stsewd** [comment]
I think this is because you don't have a submodule in your repo as it is declared in https://github.com/soar-telescope/goodman_pipeline/blob/master/.gitmodules

Ref #4371

**Comment by stsewd** [comment]
Latest build is passing https://readthedocs.org/projects/goodman/builds/8936137/

**Comment by simontorres** [comment]
Yes, thanks, it was that. I removed the `.gitmodules` file and I also had the repo configured by the web interface and changed to the `.readthedocs.yml` file.

Thanks again for the solution and sorry for forgetting to report back.
