### ISSUE TITLE
Build error with build id #8920567

### ISSUE THREAD

**Issue by tdegeus** [rtfd/readthedocs.org#5595]
## Details:

* Project URL: https://readthedocs.org/projects/GooseEYE/
* Build URL(if applicable): https://readthedocs.org/projects/gooseeye/builds/8920567/
* Read the Docs username(if applicable): tdegeus

## Expected Result

Perfect build (the docs compile without warnings or errors locally).

## Actual Result

The build fails after `git clean -d -f -f` without any error message. 

I have already tried resetting the build environment, and deleting and reinitialising the project.

**Comment by dojutsu-user** [comment]
I think this is because you don't have a submodule in your repo as it is declared in https://github.com/tdegeus/GooseEYE/blob/master/.gitmodules

Ref: #4371

**Comment by tdegeus** [comment]
Thanks @dojutsu-user !
