### ISSUE TITLE
Build error with build id #8923859 

### ISSUE THREAD

**Issue by jorisvandenbossche** [rtfd/readthedocs.org#5598]
## Details

* Read the Docs project URL: https://geopandas.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/geopandas/builds/8923859/

The GeoPandas (https://github.com/geopandas/geopandas) doc building is already failing for some time. I assume this is due to the conda environment creation that is taking too resources.

Some time ago, I put some effort into improving this (eg I pinned all versions in the `environment.yaml` file, as this speeds up the environment creation), and then sometimes the build succeeded (like 1 in 10 times), but now it is again failing all the time. 
I know https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html is indicating that it is a known problem with conda, and advising to use pip. 

https://docs.readthedocs.io/en/stable/builds.html says *"We can increase build limits on a per-project basis, if you provide a good reason your documentation needs more resources."*. Therefore, I was wondering in which way this can be asked (here via github?)

Specifically for the docs of GeoPandas:

- we use [sphinx-gallery](https://sphinx-gallery.readthedocs.io/en/latest/) for the example gallery, which means we need to install the dependencies needed for running those examples, and not only just geopandas itself
- for those dependencies (the "geospatial stack", i.e. gdal, proj, libspatialindex, etc and their python wrappers), it is difficult to use `pip` as those packages don't always provide wheels that include the necessary C library, and thus those need to be installed separately using a system package manager (I don't see any option in the config file to do a `apt-get install` ?). 
  `conda` handles this natively as it just installs those as additional dependencies.

**Comment by jorisvandenbossche** [comment]
This is somewhat blocking a new release (since I want to be sure to have docs for the released version). 

Is there a possibility to manually upload html files for a certain tag? To at least have the docs for that release, making the actual issue less urgent?

**Comment by stsewd** [comment]
We don't support uploading html files for now, see #1083. Hope we can increase the memory on monday.

**Comment by jorisvandenbossche** [comment]
@stsewd that would be great, thanks for considering it!

**Comment by jorisvandenbossche** [comment]
Sorry for pinging (I know this is not necessarily a priority for you), but any update?

**Comment by stsewd** [comment]
I moved the Geopandas project to another queue, but it didn't help. So I ended up increasing the memory limits to 1200 mb. I just triggered a new build and it was successful https://readthedocs.org/projects/geopandas/builds/8960434/.

Let me know if you still have more problems.

**Comment by jorisvandenbossche** [comment]
Thanks a lot! Very much appreciated, and thanks for the awesome readthedocs platform

**Comment by jorisvandenbossche** [comment]
This started reappearing again a few days ago (conda giving memory problems):

```
$ conda env create --quiet --name stable --file doc/environment.yml
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working... Killed

Command killed due to excessive memory consumption 
Command time: 197s Return: 137 
```

I didn't note any change on our side (no additional dependencies, it's also failing on the stable docs that worked a few days ago), and also didn't see a conda change (eg new conda version) compared to the working builds of a few days ago. Is it possible something changed on readthedocs' end?

**Comment by stsewd** [comment]
@jorisvandenbossche check if the python version wasn't updated, I saw some problems related to that when python 3.8 was released

**Comment by jorisvandenbossche** [comment]
Python is pinned to 3.7 in the environment.yml file, so that shouldn't have changed I think.

**Comment by stsewd** [comment]
@jorisvandenbossche I've increased the memory limit to 1.5G https://readthedocs.org/projects/geopandas/builds/10018413/ Not sure why is using more resources now, maybe an increase of packages in the conda-forge channel?
