### ISSUE TITLE
ProxyMiddleware could be removed

### ISSUE THREAD

**Issue by humitos** [rtfd/readthedocs.org#5605]
We have installed `ProxyMiddleware` (forked from old Django) at:

https://github.com/rtfd/readthedocs.org/blob/a7e27120e34e87ebccc691008c5d25a0192847b4/readthedocs/settings/base.py#L137

and it only adds the `REMOTE_ADDR` based on `HTTP_X_FORWARDED_FOR`.

The only place where `REMOTE_ADDR` is used is at `readthedocs.analytics.utils.get_client_ip`:

https://github.com/rtfd/readthedocs.org/blob/a7e27120e34e87ebccc691008c5d25a0192847b4/readthedocs/analytics/utils.py#L19-L28

which has a fallback that does exactly the same than the middleware.

I think we could make another checks just in case, and remove it completely.

**Comment by dojutsu-user** [comment]
I'm working on it.
I have one doubt.
I grepped for `get_client_ip` and didn't found anything except its definition.
Is it being used in a private repo?

**Comment by agjohnson** [comment]
We might want to verify that we aren't using this in other ways. It might not be directly called in our code, but are we using it to log the correct IP of a request, for example?

**Comment by davidfischer** [comment]
> We might want to verify that we aren't using this in other ways. It might not be directly called in our code, but are we using it to log the correct IP of a request, for example?

Some of this conversation is in #5607. I do not believe that the proxymiddleware is used anymore and I don't see `REMOTE_ADDR` used outside of advertising code. I checked in .org and in the private .com or -ext repos.

**Comment by davidfischer** [comment]
Also, we shouldn't be logging full IPs anywhere except our server logs which are deleted after 10 days. This is part of our DNT pledge.

**Comment by agjohnson** [comment]
But the actual IPs are still useful regardless of the timeframe that we're storing them. Did anyone verify that this isn't important to our logging mechanisms before merge?

**Comment by davidfischer** [comment]
> But the actual IPs are still useful regardless of the timeframe that we're storing them. Did anyone verify that this isn't important to our logging mechanisms before merge?

I looked and as far as I can tell it isn't. Our application logs `/var/log/readthedocs` do not log IPs. The only logs I can see with full IPs are our nginx logs which aren't affected by this and are rotated away after 10 days.

It is conceivable that Sentry uses this although if Sentry does capture this info, we should probably set it such that it doesn't.
