### ISSUE TITLE
Build timeout

### ISSUE THREAD

**Issue by rainwoodman** [rtfd/readthedocs.org#5606]
## Details

* Read the Docs project URL:  https://nbodykit.readthedocs.io
* Build URL (if applicable):  https://readthedocs.org/projects/nbodykit/builds/8698186/
* Read the Docs username (if applicable):

## Expected Result

Build proceeds.

## Actual Result

Build is stuck at 'installing' with no log written after `git clean`. Even after cleaning the build it still appears to be stuck in installing. Could it be the installation script is waiting for a yes and no answer from stdin? It is hard to guess due to the lack of log.

**Comment by stsewd** [comment]
I'll investigate more on monday

**Comment by stsewd** [comment]
Looks like it takes a lot of time to create the conda env https://readthedocs.org/projects/nbodykit/builds/8945515/

We can considerate increasing the build time, but we would appreciate if you can try some of these options first
https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

**Comment by rainwoodman** [comment]
Thanks. I will try to tweak the build time.

Is there a partial log of the step that I can use to check for gradual
improvments? The current empty log doesn't provide a lot of useful feedback
for tweaking.

**Comment by stsewd** [comment]
Sorry no, you can try passing from conda to pip first (if possible) since that's the more heavy step

**Comment by rainwoodman** [comment]
It turns out we only use a handful a packages from conda-forge. Thus I converted them to pip, and removed conda-forge from my channel list.

https://github.com/bccp/nbodykit/pull/582/

Either this change, or conda improved its algorithm, but the doc buids seems to be working now. Thanks!
