### ISSUE TITLE
text column in the array not able to render into PDF (build fail in pdflatex step)

### ISSUE THREAD

**Issue by SuryaGrandhi** [rtfd/readthedocs.org#5610]
## Details
In our documentation I have used piecewise function in doxygen content (without cases). It has been done using the below comment in the code:

```
 *  \f[
 *    f(x) = \left\{
 *    \begin{array}{ll}
 *        x,   & \text{if opt == operation_one} \\
 *        x^P, & \text{if opt == operation_two} \\
 *        x^Q, & \text{if opt == operation_two_inverse}
 *    \end{array}
 *    \right.
 *  \f]
```
I am able to get the hmtl doxygen output but while building the project, the build is failing in the pdflatex step and PDF is not getting generated.

**I have tried:**

- adding  latex_engine = 'xelatex'  in the sphinx conf.py but it did not work.
- checked the mathjax path is correct or not and is perfectly fine.

So, why is it working in html but not able to render in the PDF form. _Please provide suggestions_ to get the PDF generated.

## Expected Result

*PDF to be generated*

## Actual Result

*PDF is not being generated*

**Comment by stsewd** [comment]
Please add the link to the project and build

**Comment by SuryaGrandhi** [comment]
> Please add the link to the project and build

Build #8938949 
Project Link: https://readthedocs.org/projects/doc-test-1-rtd/

**Comment by stsewd** [comment]
Are you able to build the pdf successfully locally?

**Comment by SuryaGrandhi** [comment]
> Are you able to build the pdf successfully locally?

I have tried the steps as per this:
http://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.latex.LaTeXBuilder

Installed required packages along with latexmk.
But I am only getting the default pdf but not as expected. Can I know how to do it locally?

**Comment by stsewd** [comment]
I think an easy way is looking at the make or bat files and see what commands are executed in there or just use the files, if the content is the same locally as rtd, this isn't a rtd problem.

https://github.com/SuryaGrandhi/Doc_Test/blob/master/Makefile

**Comment by SuryaGrandhi** [comment]
>  if the content is the same locally as rtd, this isn't a rtd problem.
> 
> https://github.com/SuryaGrandhi/Doc_Test/blob/master/Makefile

The content is same as in local as well as in the repo.

**Comment by stsewd** [comment]
I mean if building the pdf locally is the same result as building the pdf in read the docs

**Comment by SuryaGrandhi** [comment]
> I mean if building the pdf locally is the same result as building the pdf in read the docs

No the result is different though the make and bat files are similar on repo and local directory.

**Comment by SuryaGrandhi** [comment]
> Are you able to build the pdf successfully locally?

@stsewd I think the problem is with the \text{some_text} unable to get rendered properly by the readthedocs in the math mode, i.e while using `\f$`. I have faced a similar problem while inserting a **_subscript text_**.

The output of `\f$\text{aaa}_{\text{bbb}} = \text{ell_width}\f$` is throwing pdflatex error
while `\f$ aaa_{bbb} = ell\_width\f$` executed fine.

And the solution(possible) for the original issue is also similar removed the` \text{} `since unable to render in the math mode and it executed fine. Please suggest other solutions if any.

**Comment by stsewd** [comment]
Sorry, I'm not really familiar with latex. Maybe this is due a different version of latexmk used in rtd and the one used locally?

**Comment by SuryaGrandhi** [comment]
No issues @stsewd we have tried a different format to get a workaround. Thanks for your efforts.
