### ISSUE TITLE
Build error with build id #8948351

### ISSUE THREAD

**Issue by MicBoucinha** [rtfd/readthedocs.org#5614]
## Details:

* Project URL: https://readthedocs.org/projects/PyBpod GUI Plugin Emulator/
* Build URL(if applicable): https://readthedocs.org/projects/pybpod-gui-plugin-emulator/builds/8948351/
* Read the Docs username(if applicable): MicBoucinha

## Expected Result

Build successful.

## Actual Result

Build failed.
With the following raw log, which doesn't seem to have any specific error.

```
Read the Docs build information
Build id: 8948351
Project: pybpod-gui-plugin-emulator
Version: develop
Commit: fd49af997d23d3da86f93259163fbef2b552961d
Date: 2019-04-22T16:44:25.585846Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-04-22T16:44:26.133751Z, end-time: 2019-04-22T16:44:26.140420Z, duration: 0, exit-code: 0
git remote set-url origin https://MicBoucinha@bitbucket.org/fchampalimaud/pybpod-gui-plugin-emulator.git


[rtd-command-info] start-time: 2019-04-22T16:44:26.248933Z, end-time: 2019-04-22T16:44:27.035612Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50
From https://bitbucket.org/fchampalimaud/pybpod-gui-plugin-emulator
   49eba30..fd49af9  develop    -> origin/develop

[rtd-command-info] start-time: 2019-04-22T16:44:27.194041Z, end-time: 2019-04-22T16:44:27.202277Z, duration: 0, exit-code: 0
git checkout --force origin/develop
Previous HEAD position was 49eba30 Added current features to documentation readme
HEAD is now at fd49af9 Restore docs configuration

[rtd-command-info] start-time: 2019-04-22T16:44:27.339359Z, end-time: 2019-04-22T16:44:27.344413Z, duration: 0, exit-code: 0
git clean -d -f -f
```
Anyone has a clue on what could be wrong here?
Thanks!

**Comment by lerks** [comment]
I'm having a similar issue in build 8948306 (project torchbiggraph): even though my build was able to progress one command further than yours, it also then mysteriously and silently failed with no error. See https://readthedocs.org/api/v2/build/8948306.txt

**Comment by martindevans** [comment]
Same problem for me with build [8948432](https://readthedocs.org/api/v2/build/8948432.txt) and a few others (I've tried to run 5 builds over the last 15 minutes). They all get to this stage:

    Installing setuptools, pip, wheel...
    done.

And mysteriously stop there.

**Comment by mcicolella** [comment]
Same problem for me with build https://readthedocs.org/api/v2/build/8948452.txt

**Comment by lwanger** [comment]
Same for me with Build #8948520 . They are all failing at the "git clean -d -f -f" too with no error messages reported.

**Comment by davidfischer** [comment]
There appears to be a regression with our latest release. We are looking at it.

**Comment by ericholscher** [comment]
This was a regression with our latest release. It should be fixed now if you try and rebuild your project.

**Comment by MicBoucinha** [comment]
Thanks so much. It is working again.

**Comment by lwanger** [comment]
Working... thanks!
