### ISSUE TITLE
Build error with build id #8948278

### ISSUE THREAD

**Issue by lukio** [rtfd/readthedocs.org#5616]
## Details:

* Project URL: https://readthedocs.org/projects/tryton-ar/
* Build URL(if applicable): https://readthedocs.org/projects/tryton-ar/builds/8948278/
* Read the Docs username(if applicable): gcooplibre

## Expected Result

Build success

## Actual Result

The build faild. This is the raw information:

Read the Docs build information
Build id: 8948278
Project: tryton-ar
Version: latest
Commit: 3ebd2af270e88624ff19e647f6d777e7eda4049d
Date: 2019-04-22T16:26:14.432219Z
State: finished
Success: False

[rtd-command-info] start-time: 2019-04-22T16:26:14.885256Z, end-time: 2019-04-22T16:26:15.389661Z, duration: 0, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/tryton-ar/documentacion-tryton-ar.git .
Cloning into '.'...

[rtd-command-info] start-time: 2019-04-22T16:26:15.569921Z, end-time: 2019-04-22T16:26:15.653662Z, duration: 0, exit-code: 0
git checkout --force origin/master
Note: checking out 'origin/master'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3ebd2af Agrego documentacion manejo de cheques rechazados

[rtd-command-info] start-time: 2019-04-22T16:26:15.723878Z, end-time: 2019-04-22T16:26:15.730152Z, duration: 0, exit-code: 0
git clean -d -f -f

[rtd-command-info] start-time: 2019-04-22T16:26:19.288827Z, end-time: 2019-04-22T16:26:22.197495Z, duration: 2, exit-code: 0
python3.7 -mvirtualenv --no-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/tryton-ar/envs/latest
Using base prefix '/home/docs/.pyenv/versions/3.7.1'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/tryton-ar/envs/latest/bin/python3.7
Also creating executable in /home/docs/checkouts/readthedocs.org/user_builds/tryton-ar/envs/latest/bin/python
Installing setuptools, pip, wheel...
done.

**Comment by ericholscher** [comment]
This was a regression with our latest release. It should be fixed now if you try and rebuild your project.

**Comment by stsewd** [comment]
Project is passing now https://readthedocs.org/projects/tryton-ar/builds/8949207/, feel free to reopen if you have more problems.
