### ISSUE TITLE
Build Failure at "generating doctree and html" step

### ISSUE THREAD

**Issue by SuryaGrandhi** [rtfd/readthedocs.org#5623]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/doc-test-1-rtd/
* Build URL (if applicable): https://readthedocs.org/projects/doc-test-1-rtd/builds/8952548/
* Read the Docs username (if applicable): SuryaGrandhi

## Expected Result

*Build should be passed to get the proper documentation*

## Actual Result

Build failed at step

`python /home/docs/checkouts/readthedocs.org/user_builds/doc-test-1-rtd/envs/latest/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

**Comment by stsewd** [comment]
Are you able to build this locally? What version of sphinx are you using locally?

**Comment by SuryaGrandhi** [comment]
> Are you able to build this locally? What version of sphinx are you using locally?

Yes @stsewd the build is succeeded locally and we are using Sphinx v1.8.1

**Comment by stsewd** [comment]
I was able to build the docs locally after increasing the build time and memory limit. You can check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html. Also, I think you are just testing rtd in the moment, so we can increase the build/memory time to the final project.

**Comment by SuryaGrandhi** [comment]
> I was able to build the docs locally after increasing the build time and memory limit. 

I am not able to get what you meant by increasing the build time and memory unit while building locally.

>You can check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

I have check the link and have created a .yml to remove the html-zip downloadable form. Is there anything else we can do?

Also if the build failure is due to insufficient build time, the build failure message should be "Error: Build exited due to time out" but it is different in this case. I am only seeing Build failed message.(not reason as above)

**Comment by stsewd** [comment]
> how to increase the build time and memory limit locally?

Sorry for the confusion, I mean I did it in my local installation of read the docs. For doing it in the live site, you should ask for more resources creating an issue (here is fine). But I just wanted to put more resources in your final project, not the ones for testing.

> I tried to check in the given link and have created a .yml to remove the html-zip downloadable form. Is there anything else we can do?

Avoid heavy requirements that are not needed to build the docs, we can add more resources if there isn't anything else that we can do.

> Also if the build failure is due to insufficient build time, the build failure message should be "Error: Build exited due to time out" but it is "Build failure" instead.

Some times the command exits without much information, and we put a general message

**Comment by humitos** [comment]
I think it would be good to enable `SHARE_SPHINX_DOCTREE` to this project since each of the build steps is using ~200s (and I suppose it's because of doxygen, but that maybe the doctree could be shared and improve these times)

**Comment by SuryaGrandhi** [comment]
> I think it would be good to enable `SHARE_SPHINX_DOCTREE` to this project since each of the build steps is using ~200s (and I suppose it's because of doxygen, but that maybe the doctree could be shared and improve these times)

Do you mean we need to eanble the flag in doxygen file.
As we are documenting 6 APIs project using breathe and doxygen and including in single rst file, so will it have some impact on build time??

Do we have any other way to reduce build time because main concern is six APIs project which are taking more time for build as you pointed.

**Comment by stsewd** [comment]
> As we are documenting 6 APIs project using breathe and doxygen and including in single rst file

Probably that's the reason, you can try splitting it in  more files

> Do you mean we need to eanble the flag in doxygen file.

No, that's an internal flag in rtd, but I don't think it will help so much, because the first build isn't passing anyway.

**Comment by humitos** [comment]
> No, that's an internal flag in rtd, but I don't think it will help so much, because the first build isn't passing anyway.

This will help at step by step level (the second step will share the doctree of the first one), no need for the first build to pass.

**Comment by stsewd** [comment]
Yeah, I mean the first step isn't passing

**Comment by humitos** [comment]
The first step is not passing in the build linked in the description, but it's in the other ones.

**Comment by stsewd** [comment]
I activated the flag, but the build is still failling.

Also, if you don't require the pdf for your documentation, you can disable it from the admin panel of your project

**Comment by SuryaGrandhi** [comment]
> I activated the flag, but the build is still failling.

And the reason the build is failing is in the pdflatex step (I think RC for this is https://github.com/rtfd/readthedocs.org/issues/5610). Can you elaborate on what went wrong there.

To add to that, even after removing that piecewise functions I am getting the errors like below.
```
! LaTeX Error: \begin{fulllineitems} on input line 26729 ended by \end{descript
ion}.
```

> Also, if you don't require the pdf for your documentation, you can disable it from the admin panel of your project

Yes I am aware of the advanced options, but I need pdf for the documentation.

**Comment by humitos** [comment]
@SuryaGrandhi those errors that you are mentioning are more related to the PDF Sphinx build step than with Read the Docs itself. We can't help too much there unfortunately.
