### ISSUE TITLE
"Latest" version does not seem to be updating automatically and missing builds.

### ISSUE THREAD

**Issue by KelSolaar** [rtfd/readthedocs.org#5636]
## Details

* Read the Docs project URL: https://colour.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/colour/builds/8976284/
* Read the Docs username (if applicable): 

## Expected Result

The *latest* version of the documentation should be built automatically along with builds for tagged project release.

## Actual Result

The *latest* version of the documentation had to be built manually thus I'm wondering why I had to do it and what needs to be done to avoid having to do it manually where most of the builds are automatic for the branches they are tracking.

In fact, if you look at the history since https://readthedocs.org/projects/colour/builds/8804781/, *latest* was never built but *master* was.

I also noticed that triggering manually *latest* oddly triggered builds of [v0.3.13](https://readthedocs.org/projects/colour/builds/8976286/) and [stable](https://readthedocs.org/projects/colour/builds/8976285/).

Finally, the  *master* and *develop* weren't build at all for the *v0.3.13* tagged release although it worked seemingly fine for *v0.3.12*.

**Comment by stsewd** [comment]
The other versions are triggered because `v0.3` becomes the new stable. Not sure about `latest`. Can you check the webhook's log? https://readthedocs.org/dashboard/colour/integrations/

**Comment by KelSolaar** [comment]
@stsewd : We don't have any integration configured apparently:

![image](https://user-images.githubusercontent.com/99779/56859454-5408d800-69df-11e9-801e-0c38cee9ffbe.png)

**Comment by stsewd** [comment]
Please check https://docs.readthedocs.io/en/stable/webhooks.html#webhook-creation and https://docs.readthedocs.io/en/stable/webhooks.html#i-was-warned-i-shouldn-t-use-github-services

**Comment by KelSolaar** [comment]
Thanks I don't remember seeing a notification that this was happening. I will look into it over the weekend.

**Comment by KelSolaar** [comment]
Adding the integration worked by the look of it! I will close this one for now.

Cheers,

Thomas
