### ISSUE TITLE
Please revive deleted project or allow creating new project with the same name

### ISSUE THREAD

**Issue by soumitrakp** [rtfd/readthedocs.org#5639]
## Details

* Read the Docs project URL: JUDI
* Build URL (if applicable):
* Read the Docs username (if applicable): soumitrakp

## Expected Result

I am new to readthedocs. I created a project named 'JUDI' based on a private github repository. Later I moved the repository to a public github repository. So I deleted the old project and tried to recreate the project with the updated github repository.
 
## Actual Result

I get an error that a project named 'JUDI' already exists.

**Comment by stsewd** [comment]
The namne is taken by https://readthedocs.org/projects/judi/, you can follow https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by soumitrakp** [comment]
Thank you for the information. I understand. You may close the issue.
Best regards,
Soumitra

**Comment by stsewd** [comment]
@soumitrakp the project hast not successful builds, and the last one was +7 months ago. The GitHub project doesn't even exists https://github.com/belummandi/Perihal-Situs-Judi-Online. You can request the name if you want.

**Comment by soumitrakp** [comment]
It would be great if I get the name. Please let me know what I need to do.
Thank you.

**Comment by soumitrakp** [comment]
Hi Santos,
Could you please make the existing project named 'judi' abandoned so that I
can reuse it. I guess the existing project meets all these requirements:
* The project has been determined abandoned by the rules described above
* The candidate is able to demonstrate their own failed attempts to contact
the existing owner
--   I could not find the contact of the existinting owner as the github
profile is missing
* The candidate is able to demonstrate that the project suggested to reuse
the name already exists and meets notability requirements
-- Let me know what I need to do for this
* The candidate is able to demonstrate why a fork under a different name is
not an acceptable workaround
-- Even forkning is not possible
* The project has fewer than 100 monthly pageviews
* The core team does not have any additional reservations.
Thank you.
Soumitra

**Comment by humitos** [comment]
> * The candidate is able to demonstrate their own failed attempts to contact the existing owner

I'm sending an email to the owner of the project and if we don't have any reply in 6 weeks we can mark the project as abandoned.

/remind me about mark `judi` project abandoned in 6 weeks.

**Comment by humitos** [comment]
The user did not respond in time.

@soumitrakp you should be able to create `judi` project now. Feel free to reopen the issue if you have any problem.

**Comment by soumitrakp** [comment]
Thank you. I could create project 'judi' without any problem.
Soumitra
