### ISSUE TITLE
Build error with build id #8973732

### ISSUE THREAD

**Issue by sriharikarnam** [rtfd/readthedocs.org#5640]
## Details:

* Project URL: https://readthedocs.org/projects/ROCm Documentation/
* Build URL(if applicable): https://readthedocs.org/projects/rocm-documentation/builds/8973732/

## Expected Result

*The build should get built successfully*

## Actual Result

*Build is getting failed with a error message as*
`ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5DzaY9/breathe/`

And here the environment is taking python version 2.7 instead of python 3.7 . As we need at least python 3.5 can you let us know how we can update python version from 2.7 to 3.7.

**Comment by humitos** [comment]
Hi @sriharikarnam! You can use the `readthedocs.yml` file for to define what version of Python to use. See the docs at https://docs.readthedocs.io/en/stable/config-file/v2.html. Thanks!

**Comment by sriharikarnam** [comment]
Thanks @humitos. The issue has been solved.
