### ISSUE TITLE
Inconsistent theme and display of docstrings

### ISSUE THREAD

**Issue by 2fasc** [rtfd/readthedocs.org#5643]
## Details

* Read the Docs project URL: https://distributed-malaria-detection.readthedocs.io/en/latest/index.html
* Build URL (if applicable): https://readthedocs.org/projects/distributed-malaria-detection/builds/8984800/
* Read the Docs username (if applicable): 2fasc
* Github: https://github.com/2fasc/Distributed_Malaria_Detection

## Expected Result
I expected RTD to apply the rtd theme and display sites with the documentation for my functions.
Local builds work just fine. 

## Actual Result
The displayed theme is a mixture of alabaster and the rtd theme and there is no documentation generated for the functions that show the alabaster theme. I don't know if this is related though. 

Thank you for your help!

**Comment by stsewd** [comment]
The read the docs theme doesn't support sphinx 2.x yet https://github.com/2fasc/Distributed_Malaria_Detection/blob/1d30cfd9a94809ba39d1ca42532d294f1a8697a1/requirements_rtd.txt#L78

https://github.com/rtfd/sphinx_rtd_theme/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sphinx+2

**Comment by 2fasc** [comment]
Thank you!

**Comment by 2fasc** [comment]
I checked a couple hours later and everything is displayed as it should.

**Comment by stsewd** [comment]
>  I checked a couple hours later and everything is displayed as it should.

I think the mixture about sphinx and alabaster was because of cache :)

**Comment by 2fasc** [comment]
> I think the mixture about sphinx and alabaster was because of cache :)

That makes sense. 

I don't know if this is of general interest but adding a sentence in the FAQs that make clear that updates might not occur immediately could be helpful for others as well :sweat_smile:  

I really appreciated your support!
