### ISSUE TITLE
Remove build artifacts and repo storage after build

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#5646]
One of the tests that we'd like to perform, in order to address our build disk usage, is to remove build artifacts and repo storage directly after the build process ends. This will reduce storage, remove the need for wiping environments, and will further allow us to isolate build processes. We do need to test for the performance hit of continually re-fetching repositories and pip/etc fresh each build. The trade off eventually might be more time on the build servers, but with vastly smaller storage disks.

- [ ] Add a feature flag to remove these files after build for select projects on the feature flag
- [ ] Add a task chain that calls for build server delete of files after the build process completes and files are synced to webs/blob storage
- [ ] Ensure we're deleting the project build artifacts, repo checkout, and pip cache

**Comment by humitos** [comment]
> Ensure we're deleting the project build artifacts, repo checkout, and pip cache

One part of this item was not done: remove build artifacts, because of a concurrency problem. See https://github.com/rtfd/readthedocs.org/blob/25191ff2f6b15e01eeb2617b239d724b04c98d78/readthedocs/projects/tasks.py#L1433-L1438
