### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for sunpy

### ISSUE THREAD

**Issue by Cadair** [rtfd/readthedocs.org#5648]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sunpy/
* Read the Docs username (if applicable): Cadair

Hi, we are using `setuptools_scm` to get our versions and the shallow clone is preventing `git describe` working correctly, it would be awesome if you could change this for us! Thanks!

**Comment by stsewd** [comment]
Done, I just triggered a build to latest. It's doing a full clone. Let us know if there is a problem

**Comment by Cadair** [comment]
Thanks!
