### ISSUE TITLE
Build error with build id #9000594

### ISSUE THREAD

**Issue by vinjana** [rtfd/readthedocs.org#5653]
## Details:

* Project URL: https://readthedocs.org/projects/Roddy/
* Build URL(if applicable): https://readthedocs.org/projects/roddy-documentation/builds/9000594/
* Read the Docs username(if applicable): vinjana

## Expected Result

The documentation should build.

## Actual Result

Four commands seem to be issued, all of which terminate with exit code 0. Still the build status is set to failed in the end. None of the commands actually seem to touch the ReStructuredText files: The last succeeding command is "git -d -f -f". I can only speculate that a command that follows, but that is not displayed, fails.

Note that the documentation builds fine locally with warningsAsErrors=true in Gradle.

**Comment by julienfastre** [comment]
Same error, buildId is 9001996

**Comment by stsewd** [comment]
@vinjana the issue is because you have some old/unused submodules in your repo https://github.com/TheRoddyWMS/Roddy/blob/master/.gitmodules

See #4371 

@julienfastre please provide the full build link

**Comment by stsewd** [comment]
@julienfastre feel free to open a new issue.

@vinjana let us know how it goes

**Comment by vinjana** [comment]
Everything working now! Further issues were related to plantuml (added a `requirements.txt` to my Gradle project).

**Comment by julienfastre** [comment]
@stsewd Thanks. I could solve my issue by... reading the docs :-)
