### ISSUE TITLE
"default branch" under "advanced settings" does not persist

### ISSUE THREAD

**Issue by timothydmorton** [rtfd/readthedocs.org#5659]
## Details

I am trying to build docs for a development branch of a project (github.com/timothydmorton/isochrones).  I change the "default branch" to "bolo" under the "advanced settings" for the project on RTD, save changes, and it triggers a build from the "bolo" branch.  When I try to push changes to "bolo", however, nothing triggers, and I go back to the settings page, and see that the default is back to "latest" instead of "bolo" as I had set.  So in order to trigger a new build each time, I have to go to the settings menu and change the default branch. 

## Expected Result

I would expect that clicking "save" on the settings menu would save "bolo" as the default build branch, and that subsequent pushes to "bolo" would trigger builds.

## Actual Result

I have to change the settings each time I want a new build.

**Comment by stsewd** [comment]
I think this was fixed in https://github.com/rtfd/readthedocs.org/pull/5547 (which got merged after the last deploy). I'm going to double check before closing.

**Comment by stsewd** [comment]
@timothydmorton can you please tell us if you are still having this issue?
