### ISSUE TITLE
Notifications don't disappear after action

### ISSUE THREAD

**Issue by yackx** [rtfd/readthedocs.org#5665]
## Details

A persistent error message appears on every page and claims my email address is not verified, although it is.

I have a single email address associated with my account, and it has been verified. Actually, after verification, I even saw both success and error messages.

<img width="596" alt="readthedocs-bug" src="https://user-images.githubusercontent.com/1193689/57210423-e3644b80-6fdc-11e9-9b81-29f56bd6e6b1.png">

## Expected Result

No error message displayed

## Actual Result

Incorrect error message:

> Your primary email address is not verified. Please verify it here.

**Comment by dojutsu-user** [comment]
@yackx 
It will go away once you click on `verify it here`.

**Comment by stsewd** [comment]
As mention the note will disappear if you click on it. I'm pretty sure there was an issue for this already, I couldn't find it :/

**Comment by stsewd** [comment]
It was closed https://github.com/rtfd/readthedocs.org/issues/4684

**Comment by yackx** [comment]
The referenced issues #4684 does not seem to match this one.

If I click on "verify it here", I am lead to "Change email" screen. There, if I click on "Make primary", the warning/error message goes away. But that was just me guessing and clicking on a what seemed to be an unrelated button ("make primary" vs "verify" actions).

I fail to see why that extra action is required after I've clicked the link in the email. That alone should verify the address (and make it primary) IMO.

**Comment by stsewd** [comment]
There are related to the notification, when the user _fixes_ the problem that the notifications says, it doesn't disappear until it's clicked.

**Comment by humitos** [comment]
> There are related to the notification, when the user _fixes_ the problem that the notifications says, it doesn't disappear until it's clicked.

Unfortunately, this is how our notification system works now.

We are not using template-based notifications, but instead when an action is needed based on some db field, we create a notification object with the proper message. Then, the only way to make it disappear is to click on the link from the notification (which trigger an AJAX call to delete it).

We are not going to change this behavior soon, so I'm going to close this issue for now. We can reopen it if we want to refactor our notification system.
