### ISSUE TITLE
Build error with build id #9019701

### ISSUE THREAD

**Issue by jsnigula** [rtfd/readthedocs.org#5666]
## Details:

* Project URL: https://readthedocs.org/projects/vhc/
* Build URL(if applicable): https://readthedocs.org/projects/vhc/builds/9019701/
* Read the Docs username(if applicable): hetdex

## Expected Result

Tried to build documentation

## Actual Result

Build fails during cloning stage, resetting build environment didn't help.

**Comment by humitos** [comment]
I think you have your project configured as `Git` repository instead of `Subversion`. Could you check that?

**Comment by jsnigula** [comment]
Under settings, it is configured as subversion… There was a mistake, that the Default Branch was set to latest, but that didn’t dix the problem

**Comment by jsnigula** [comment]
I tried to set the repository to git, and then back to subversion, after that I got a different error (build 9024091) I fixed that, but now I’m back at the original cloning error.

**Comment by humitos** [comment]
It's taking more that 15 minutes to do the `svn checkout`. That's why it's failing. My guess is that the server running the SVN is very slow and/or the repository too big.

(I tried to checkout it locally and it goes really slow in a 50mb connection)

The error message could be improved, though.

**Comment by jsnigula** [comment]
Aah, 

thanks a lot, that solved the problem, I moved the test data out of the repository, now it works fine.
