### ISSUE TITLE
Using conda ends up with sphinx 2.0.1 and cannot update doxygen version

### ISSUE THREAD

**Issue by allanleal** [rtfd/readthedocs.org#5669]
## Details

* Read the Docs project URL: https://reaktoro.readthedocs.io/en/fix-readthedocs-integration-with-doxygen/
* Build URL (if applicable): https://readthedocs.org/projects/reaktoro/builds/
* Read the Docs username (if applicable):

## Expected Result

Using conda with environment.yml in which `sphinx==1.8.5` and `doxygen==1.8.14` are specified as dependencies:

~~~yaml
channels:
  - conda-forge

dependencies:
- cmake>=3.13
- doxygen==1.8.14
- pip:
  - sphinx==1.8.5
  - sphinx_rtd_theme
  - sphinxcontrib-images
~~~

should actually force sphinx 1.8.5, but 2.0.1 gets installed. 

Doxygen version is not an up to date one in readthedocs server. So, doxygen build produces incorrect HTML files.

## Actual Result

Force sphinx to be given version.
Allow doxygen to be updated.

**Comment by humitos** [comment]
Hi @allanleal! This is a known issue: #3829. There is a proposal at #5631 but it does not behave as we need.

I'm closing as duplicate. Please, subscribe to one of those if you want to be up to date.
