### ISSUE TITLE
Please enable USE_PDF_LATEXMK for the learnrst project

### ISSUE THREAD

**Issue by jpch89** [rtfd/readthedocs.org#5677]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/learnrst/
* Build URL (if applicable): https://readthedocs.org/projects/learnrst/builds/9035466/
* Read the Docs username (if applicable): jpch89

## Expected Result
I am writing some notes for reST in Chinese, but I failed to build the project with a downloadable pdf link. Then I've changed the settings in conf.py according to [Guide to build PDF for non-ASCII language](https://github.com/rtfd/readthedocs.org/commit/649b8bc2eba9722ee40f630a00e42ea30d3e37e0), so I hope you can enable the new feature for my project in order to get a correct output.

## Actual Result

Without enabling USE_PDF_LATEXMK, I'm now getting some LaTeX Errors.

**Comment by humitos** [comment]
I enabled that feature in your project and triggered a new build at https://readthedocs.org/projects/learnrst/builds/9037815/

I can see that now it's calling `latexmk` in the build output and the build passed.

**Comment by jpch89** [comment]
> 
> 
> I enabled that feature in your project and triggered a new build at https://readthedocs.org/projects/learnrst/builds/9037815/
> 
> I can see that now it's calling `latexmk` in the build output and the build passed.

Thank you, new feature works like magic!
