### ISSUE TITLE
cannot install project module in rtd venv

### ISSUE THREAD

**Issue by brandondube** [rtfd/readthedocs.org#5682]
## Details

* Read the Docs project URL: https://prysm.readthedocs.io/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/prysm/builds/9043634/
* Read the Docs username (if applicable): bdube

## Expected Result

rtd builds docs normally

## Actual Result

sphinx crashes because my project's package is not installed.

I used to use conda for the RTD environment which worked great, but recently builds have been failing due to memory limits.  I ported to the rtd config V2 format w/ a req.txt file,

https://github.com/brandondube/prysm/blob/dev/readthedocs.yml
https://github.com/brandondube/prysm/blob/dev/docs/requirements.txt

but now my builds crash because my module is not installed.  Why is it not being installed?  There is no error from the setuptools part of the config, and when I use pip for the method there is it the same -- no error for install, but fail on building docs.

**Comment by stsewd** [comment]
You are missing the `version` key in the configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html#version

**Comment by brandondube** [comment]
no dice --

https://readthedocs.org/projects/prysm/builds/9043683/
https://github.com/brandondube/prysm/commit/dacd2186f7b54731c154f4b84c55ce098b071377

**Comment by stsewd** [comment]
Looks like a known problem with the package you are using for automatic versioning https://stackoverflow.com/questions/35811267/readthedocs-and-setuptools-scm-version-wrong

**Comment by brandondube** [comment]
I don't think so

- When I was using conda on RTD, this was no issue ( see, e.g., https://readthedocs.org/projects/prysm/builds/9015056/)

- This is a botched install, not a versioning problem

**Comment by stsewd** [comment]
I saw a warning about the shallow cloning, I activated a flag for your project to do a full clone. The dev version is private, so I can't see if it's working now.

**Comment by brandondube** [comment]
I triggered a build for dev -- no dice, same problem.  On my dashboard the dev docs are listed as public -- what do I change to make them public?

**Comment by brandondube** [comment]
/home/docs/checkouts/readthedocs.org/user_builds/prysm/envs/dev/bin/python ./setup.py install --force

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/prysm/envs/dev/lib/python3.7/site-packages/prysm-0.17.dev8+g312087c-py3.7.egg
Processing dependencies for prysm==0.17.dev8+g312087c
Finished processing dependencies for prysm==0.17.dev8+g312087c
```

It looks like setup.py executes just fine.  The sphinx invocation,

python /home/docs/checkouts/readthedocs.org/user_builds/prysm/envs/dev/bin/sphinx-build -T -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

does start with `python`, not `/home/docs/checkouts/readthedocs.org/user_builds/prysm/envs/dev/bin/python`

I thought there might be a path problem, so I put a `print(sys.executable)` in conf.py.  Sphinx is running from the correct py binary, so it isn't that.

I tried recreating this locally, and it is repeatable; setup.py install must do something strange.  It puts an egg in sites-packages, which works when you do `python; import prysm; print(prysm.__version__)`.  But when `get_distribution` is run as part of conf.py, it crashes.  This is either a bug in setuptools or very unexpected behavior.  The problem isn't RTD, and is just coming up now because my package is no longer being installed via pip.

I think the issue is that in https://github.com/brandondube/prysm/commit/29f328d46c9bf232dfe60abc3f5ca76bf1583756 when I moved to pip/venv, I didn't have version: 2 in the RTD conf file and that made the difference.
