### ISSUE TITLE
Cache pip packages per version rather than per project

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5685]
We are currently saving the pip cache per project, which can lead to some weird deps problems when building from different versions.

https://github.com/rtfd/readthedocs.org/blob/768856e3f72fd0ec1e4fbe9eab8913cb5f01b490/readthedocs/projects/models.py#L616-L621

Ref https://github.com/rtfd/readthedocs.org/pull/5680#issuecomment-491095510

**Comment by humitos** [comment]
> which can lead to some weird deps problems when building from different versions.

What are these problems?

**Comment by stsewd** [comment]
Different versions have different requirements, dependencies of another dependencies, etc.

**Comment by stsewd** [comment]
Also if the cache gets corrupted, users need to wipe in order to get it working again.

And we can't clean the cache in #5680

**Comment by humitos** [comment]
> Also if the cache gets corrupted, users need to wipe in order to get it working again.

I don't think we are having this problem.

> And we can't clean the cache in #5680

There is no need to save a cache if we are going to clean it after use it once. If that's what we want, we just don't need to save the cache at all. We can use,

* do not mount a a volume outside the docker container
* use `--no-cache-dir` option in pip

Having a per-version pip cache does not makes too much sense to me.

**Comment by agjohnson** [comment]
I'm going to close this, I think it goes against our goal of removing caching entirely. If we weren't on this path, it would be a helpful feature, but I think the benefits ephemeral build process bring will trump any gains by tuning caching
