### ISSUE TITLE
No syntax highlighting with nbsphinx

### ISSUE THREAD

**Issue by timothydmorton** [rtfd/readthedocs.org#5688]
## Details

* Read the Docs project URL: https://isochrones.readthedocs.io
* Read the Docs username: timothydmorton

## Expected Result

Documentation built on rtd from notebooks with nbsphinx would have syntax highlighting  in the code cells as they do when built locally on my machine.

## Actual Result

The documentation builds on rtd and everything looks good except there is no syntax highlighting in the code cells.

**Comment by davidfischer** [comment]
I see a lot of warnings in [recent builds](https://readthedocs.org/projects/isochrones/builds/9050048/) related to:

    WARNING: Pygments lexer name 'ipython3' is not known

Pygments is the library that provides syntax highlighting so I suspect it is related.

**Comment by timothydmorton** [comment]
Interesting, thanks for finding this-- is there anything I can do to fix this?  I have pygments version 2.2.0 locally; not sure what is on RTD by default.

**Comment by timothydmorton** [comment]
OK, looks like 2.3.1 on RTD.

**Comment by davidfischer** [comment]
That lexer comes from ipython itself. There's a bug (with a workaround) here: https://github.com/spatialaudio/nbsphinx/issues/24

**Comment by timothydmorton** [comment]
yup, just found it, and trying now!  thanks

**Comment by timothydmorton** [comment]
OK, the solution was actually just to add ipython to the requirements.txt used by RTD.
