### ISSUE TITLE
Set no shallow clone for nextstrain-augur

### ISSUE THREAD

**Issue by tsibley** [rtfd/readthedocs.org#5689]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nextstrain-augur
* Read the Docs username (if applicable): trs

## Expected Result

Builds to run with a full clone of the git repo so author information can be generated from the full git history.

**Comment by davidfischer** [comment]
No problem. This is all setup. If you encounter issues, please feel free to re-open it.
