### ISSUE TITLE
NameError: name 'reportlab' is not defined

### ISSUE THREAD

**Issue by trasher** [rtfd/readthedocs.org#5697]
## Details

* Read the Docs project URL: https://glpi-install.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/glpi-install/builds/9066046/
* Read the Docs username (if applicable): trasher

## Expected Result

Build success.

## Actual Result

Build failing with error `NameError: name 'reportlab' is not defined`

**Comment by humitos** [comment]
It seems that you are calling `rst2pdf` from your `conf.py` file. That's not needed when building on Read the Docs. RTD uses a different PDF builder.

**Comment by trasher** [comment]
I have used it in the past locally, but this is no longer required now. Did not pay attention since I think it was not used (and previousely do not breaks builds).

Thank you :)
