### ISSUE TITLE
In-doc search design document

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#5699]
We should create a design document that lays out the design of our in-doc search UI. This comment is the start of that work already, but we should make a PR of it on our own. 

Some existing examples of design docs are here: https://docs.readthedocs.io/en/latest/design/

**Comment by dojutsu-user** [comment]
Linking the issue #504 and the [comment](https://github.com/rtfd/readthedocs.org/issues/504#issuecomment-492423346)

**Comment by dojutsu-user** [comment]
Update:
Researching on the topic and will make the PR for the design document in a day or two.
