### ISSUE TITLE
ReadTheDocs footer not being inserted

### ISSUE THREAD

**Issue by effigies** [rtfd/readthedocs.org#5702]
## Details

Most RTD-hosted docs I've worked with automatically insert a footer that allows other versions of the docs to be browsed easily. For a project ([bids-standard/bids-specification](https://github.com/bids-standard/bids-specification)) using the [mkdocs-material](https://github.com/squidfunk/mkdocs-material) theme, this does not occur.

At least in the case of Sphinx themes, no explicit accommodation seems to be made for this injection; it just happens. I see that the mkdocs' RTD theme seems to have some accommodation, but their [latest](https://mkdocs.readthedocs.io/en/latest/) branch uses their regular theme, which seems to make no mention.

So it's not really clear what is causing the failure. If it's a theming issue, do you have any pointers on what would need to be changed in Material in order to get this functionality? Or perhaps our [mkdocs.yml](https://github.com/bids-standard/bids-specification/blob/rtdtest/mkdocs.yml) needs fixing?

* Read the Docs project URL: https://bids-specification.readthedocs.io/en/rtdtest/
* Build URL (if applicable): https://readthedocs.org/projects/bids-specification/builds/9078855/
* Read the Docs username (if applicable): markiewicz

Also, I'm working on a testing branch on GitHub, in case browsing our code would be useful: https://github.com/bids-standard/bids-specification/tree/rtdtest

Thanks very much for any help you can give.

## Expected Result

Footer appears, looking something like (taken from another project):

<img width="302" alt="Screen Shot 2019-05-13 at 20 11 28" src="https://user-images.githubusercontent.com/83442/57859448-fa672280-77c0-11e9-9eda-10898723751b.png">

In viewing the DOM, I would expect to see:

<img width="614" alt="Screen Shot 2019-05-16 at 09 58 06" src="https://user-images.githubusercontent.com/83442/57859549-2a162a80-77c1-11e9-866d-ad01decf6f91.png">

## Actual Result

No footer appears.

**Comment by effigies** [comment]
Looks like it's a failure of the theme to import jQuery. Found via https://github.com/geosolutions-it/MapStore2/pull/3570. Sorry for the noise.

**Comment by davidfischer** [comment]
It is a goal of mine to make our footer JavaScript more self-contained and dependency free. However, I believe a number of sphinx features may not work well without jquery.

**Comment by effigies** [comment]
That'd be neat; still, adding a minified copy jQuery isn't a big thing to ask of users. I'm not sure if this dependency is documented somewhere, but it took me a couple hours of digging to finally figure it out. Hopefully I've put enough good search terms in the initial post that others running into this problem will be able to find this issue.
