### ISSUE TITLE
Transfer ownership of "biopython" project 

### ISSUE THREAD

**Issue by grihabor** [rtfd/readthedocs.org#5704]
## Details

I want to transfer biopython.readthedocs.io url to the actual maintainer of the project

* Project: https://github.com/peterjc/biopython
* Target maintainer: https://github.com/peterjc

**Comment by stsewd** [comment]
Hi, you can do this adding the user as maintainer in https://readthedocs.org/dashboard/biopython/users/

After that, the other user can remove you from the maintainers if you wish

**Comment by grihabor** [comment]
Thank you! Done, @peterjc please check

**Comment by peterjc** [comment]
Thank you!

Minor correction - we will want to use https://github.com/biopython/biopython (the official repository) not https://github.com/peterjc/biopython (my personal fork), but it looks like I can now change the RTD repository URL as needed. It might be useful to point at my personal fork in the short term to avoid too many test changes on the official repository.

I hope to look at this tomorrow :)

**Comment by stsewd** [comment]
Yes, you can change that.
