### ISSUE TITLE
Can we claim scons for the SCons project

### ISSUE THREAD

**Issue by bdbaddog** [rtfd/readthedocs.org#5708]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scons/
* Build URL (if applicable):
* Read the Docs username (if applicable): bdbaddog

## Expected Result

Looks like someone tried to build rtd docs for scons a while back but the git repo is gone.
We'd like to  claim the project name for SCons project (http://scons.org)

## Actual Result

Someone else owns rtd's scons project

**Comment by humitos** [comment]
Hi @bdbaddog! I sent an email to the user following our http://docs.readthedocs.io/page/abandoned-projects.html policy.

I will contact you back in 6 weeks if the user does not respond us.

/remind me about take action on this project in 6 weeks

**Comment by bdbaddog** [comment]
Thanks @humitos

**Comment by humitos** [comment]
@bdbaddog the user's email does not exist anymore and I couldn't deliver it. So, I just granted permissions to you. Enjoy!

**Comment by bdbaddog** [comment]
Thanks!
