### ISSUE TITLE
Docs served without SSL, though SSL is set 

### ISSUE THREAD

**Issue by tlongers** [rtfd/readthedocs.org#5715]
Thank you for this thoughtfully-designed, helpful tool - I've had a great experience so far in migrating my org's research handbook to Read The Docs. I just encountered this small glitch when setting up a custom domain for testing.

## Details

* Read the Docs project URL: https://doccydoc.readthedocs.io/
* Custom domain: https://newhelp.securityforcemonitor.org/

## Expected Result

If the user visits `https://newhelp.securityforcemonitor.org/en/latest/` the pages are correctly served with SSL. If the user visits `http://newhelp.securityforcemonitor.org/en/latest/` it should redirect to the `https://~` version. 

![image](https://user-images.githubusercontent.com/2115933/58164793-65f83680-7c7e-11e9-9147-66496534ccda.png)

## Actual Result

The redirect does not occur, and the documentation is served as `http://~`.

![image](https://user-images.githubusercontent.com/2115933/58164761-5a0c7480-7c7e-11e9-8ab7-580462e9fc0c.png)

## Action taken

I've tested it on current Chrome, Firefox and Safari browsers, and the behaviour is the same.

I think I've set everything up correctly on the RtD admin pages:

![image](https://user-images.githubusercontent.com/2115933/58165503-d5225a80-7c7f-11e9-81af-c4c3d7cbeb09.png)

I've also set up the CNAME record with our name server. Current DiG output is:

```bash
$ dig newhelp.securityforcemonitor.org
; <<>> DiG 9.10.6 <<>> newhelp.securityforcemonitor.org
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 24934
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 2, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;newhelp.securityforcemonitor.org. IN	A

;; ANSWER SECTION:
newhelp.securityforcemonitor.org. 11371	IN CNAME readthedocs.io.
readthedocs.io.		257	IN	A	104.18.230.122
readthedocs.io.		257	IN	A	104.18.228.122
readthedocs.io.		257	IN	A	104.18.227.122
readthedocs.io.		257	IN	A	104.18.229.122
readthedocs.io.		257	IN	A	104.18.231.122

;; AUTHORITY SECTION:
readthedocs.io.		33757	IN	NS	ivan.ns.cloudflare.com.
readthedocs.io.		33757	IN	NS	tegan.ns.cloudflare.com.

;; Query time: 57 msec
;; SERVER: 10.16.0.1#53(10.16.0.1)
;; WHEN: Wed May 22 10:39:12 BST 2019
;; MSG SIZE  rcvd: 225
```
Perhaps this is something that will just resolve with a bit more time, or have I missed something important? Thanks again for any guidance you can offer.

**Comment by tlongers** [comment]
Okay, so time is the great healer: it fixed itself!

**Comment by tlongers** [comment]
Actually no it didn't - sorry, reopening.

**Comment by humitos** [comment]
@tlongers thanks for your report.

We are already aware about this and we have this issue opened to track this issue at #4641. Please, subscribe there to be notified about any news.

I'm closing this one.

**Comment by tlongers** [comment]
Thanks @humitos
