### ISSUE TITLE
Set no shallow copy for deluge

### ISSUE THREAD

**Issue by cas--** [rtfd/readthedocs.org#5716]
As noted in #5031, I'm asking to disable shallow clone for [deluge](https://readthedocs.org/projects/deluge/).

This is a real pain to suddenly encounter failed builds and spend time searching around to finally stumble upon this!

**Comment by humitos** [comment]
I enabled the flag in your project. Please, wipe it and re-trigger a build.

Let me know if anything.

**Comment by cas--** [comment]
Thanks. 

A link to wipe environment document would have been useful: https://docs.readthedocs.io/en/stable/guides/wipe-environment.html
