### ISSUE TITLE
Build error with build id #9109576

### ISSUE THREAD

**Issue by lpsinger** [rtfd/readthedocs.org#5718]
## Details:

* Project URL: https://readthedocs.org/projects/ligo.skymap/
* Build URL(if applicable): https://readthedocs.org/projects/ligo-skymap/builds/9109576/
* Read the Docs username(if applicable): lpsinger

## Expected Result

Build should succeed.

## Actual Result

The build fails without providing a clear log message.

**Comment by humitos** [comment]
Hi @lpsinger. It seems it was a temporary problem in our servers.

I just triggered a new build for your docs and it failed for a different reason.

Please, take a look at this guide first and come back to us if you have any doubt: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

Thanks!

**Comment by lpsinger** [comment]
Thank you!
