### ISSUE TITLE
RTD build fails quietly on envt setup for earthpy. it did used to work however.

### ISSUE THREAD

**Issue by lwasser** [rtfd/readthedocs.org#5719]
## Details

* Read the Docs project URL: earthpy -- https://earthpy.readthedocs.io/en/latest/
* Build URL (if applicable):  https://readthedocs.org/api/v2/build/9110151.txt
* Read the Docs username (if applicable): lwasser

## Expected Result
I expected the docs to build successfull

## Actual Result

my doc build keeps failing quietly. the raw logs are below and i don't understand what is the issue other than it cant seem to install my environment file. essentially it starts to setup the envt file and just stops. 

in [this pr](https://github.com/earthlab/earthpy/pull/326) i've been playing with pinning versions of packages. but because i don't have useful error messages (or don't know where to find them) i can't seem to trouble shoot. can anyone suggest a fix or a direction for me to take? Many thanks - also if i am not posting in the correct spot please let me know. 

```
Read the Docs build information
Build id: 9110151
Project: earthpy
Version: rtd
Commit: 92456e0f0cd2ce886c6cb27ade043977661d3465
Date: 2019-05-22T18:02:30.848100Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-05-22T18:02:31.355260Z, end-time: 2019-05-22T18:02:31.368784Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/earthlab/earthpy


[rtd-command-info] start-time: 2019-05-22T18:02:31.481292Z, end-time: 2019-05-22T18:02:31.876050Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50
From https://github.com/earthlab/earthpy
   25d65ab..92456e0  rtd        -> origin/rtd

[rtd-command-info] start-time: 2019-05-22T18:02:32.123753Z, end-time: 2019-05-22T18:02:32.147174Z, duration: 0, exit-code: 0
git checkout --force origin/rtd
Previous HEAD position was 25d65ab pandas version
HEAD is now at 92456e0 pin all things

[rtd-command-info] start-time: 2019-05-22T18:02:32.325381Z, end-time: 2019-05-22T18:02:32.342381Z, duration: 0, exit-code: 0
git clean -d -f -f


[rtd-command-info] start-time: 2019-05-22T18:02:35.665104Z, end-time: 2019-05-22T18:06:59.499044Z, duration: 263, exit-code: 247
conda env create --quiet --name rtd --file /home/docs/checkouts/readthedocs.org/user_builds/earthpy/checkouts/rtd/docs/environment.yml
Solving environment: ...working... done
Preparing transaction: ...working... done
Verifying transaction: ...working...
```

**Comment by stsewd** [comment]
Believe this is because you are using conda, which is timing out or consuming a lot of resources, please try https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

If that doesn't work for you, we can increase the memory limits.

**Comment by lwasser** [comment]
Ok thank you @stsewd  i will look into this now. I really appreciate the quick response.

**Comment by lwasser** [comment]
hi @stsewd if you can increase the memory limits that would be great. 
i have modified my envt file to be more bare bones following the existing docker image... it still is hanging. Unfortunately the spatial libraries really need to be installed via conda-forge for dependencies to work properly.

i am open to trying some other things but it still seems to be spinning and failing.
```
name: earthpy_docs
channels:
- conda-forge
dependencies:
- python=3.7
- geopandas=0.4.1
- rasterio=1.0.21
- scikit-image
```

many thanks

**Comment by lwasser** [comment]
ok @stsewd   one other note.
when the build happens it sits on this step with no messages in the dialog box for several minutes... it seems like it is hanging? is this still because of conda? it's odd as things used to work just a few weeks ago and then it just broke again.

i'm playing with settings on the rtd branch of earthpy but am just wondering why it seems to be hanging for so long. i removed most of the deps and am trying to install with pip where i can but again the geospatial stuff needs conda. this is where it hangs for a while each time

<img width="945" alt="Screen Shot 2019-05-23 at 5 18 08 PM" src="https://user-images.githubusercontent.com/7649194/58292481-c4a4d980-7d7e-11e9-93ff-424f8a945c3a.png">

**Comment by stsewd** [comment]
Sorry for the confusion, the last executed command is  `conda env create` isn't show in the build page because rtd saves the commands after they are executed (some timnes when the command fails for memory limits rtd doesn't capture the last command)

We are tracking these problems in

https://github.com/rtfd/readthedocs.org/issues/3613
https://github.com/rtfd/readthedocs.org/issues/4288

> it's odd as things used to work just a few weeks ago and then it just broke again.

Probably a new dependency made conda slow, also, if the conda index is bigger than conda requires more time (that's what I understand anyway).
Also, maybe our builders are a little busy, so that reduce the resources.

I'll try to get a look at increasing the build resources for your project soon.

**Comment by stsewd** [comment]
I've increased build memory and time for your project, I've triggered a couple of builds and look ok. The rtd branch is failing for another reason. Let me know if you find other problems.

**Comment by lwasser** [comment]
thank you @stsewd !! the build is working now. the RTD branch was a test so that is OK if it doesn't build. Many thanks for your help and time on this! i greatly appreciate it
