### ISSUE TITLE
RTD project failing to init/update submodules.

### ISSUE THREAD

**Issue by tgamblin** [rtfd/readthedocs.org#5721]
## Details

I'm trying to set up a single repository for localized documentation projects, and that involves having a submodule for my main project, with a lot of "fake" symlink tree directories in `docs/*`  that point back to the main project and differ only in what language is set in config.py.  This build *was* working before but it seems to have gotten into a weird state.

* Read the Docs project URL: https://spack.readthedocs.io 
* Build URL (if applicable): https://readthedocs.org/projects/ja-docs/builds/9113851/
* Read the Docs username (if applicable): tgamblin

## Expected Result

Project is checked out and submodules are inited and updated, as they would be for this sequence of commands:

```
git clone https://github.com/spack/localized-docs.git
cd localized-docs
git submodule init
git submodule update
cd docs/ja
sphinx-build -b html -d _build/doctrees  -W . _build/html
```

These commands work on my laptop, so I am not sure what's going on with the RTD directory.

## Actual Result

Project is checked out and symlinks into a submodule directory fail to resolve. This results in a `requirements.txt` not found error.

**Comment by stsewd** [comment]
This is because we now validate these files before the fetching submodules, we are moving these validations to a later step https://github.com/rtfd/readthedocs.org/pull/5627

See https://github.com/rtfd/readthedocs.org/issues/5238

**Comment by tgamblin** [comment]
Thanks!  This enabled me to get things working.
