### ISSUE TITLE
RTD: Build exited due to time out

### ISSUE THREAD

**Issue by typ1-brods** [rtfd/readthedocs.org#5723]
## Details

* Read the Docs project URL: https://androidaps.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/androidaps/builds/9114296/
* Read the Docs username (if applicable): typ1-brods

## Expected Result

I want to built l10n_master branch. It has been working for months.

## Actual Result

Now it has failed serveral times since yesterday due to timeout. The github branch, that RTD hast to build from, is a automated Translation branch of crowdin.com.

**Comment by stsewd** [comment]
Could you check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html first? If that doesn't work, we can increase the build limits for your project.

**Comment by typ1-brods** [comment]
@stsewd I could not find a solution until now. It's disappointing that "latest" branch is built, "l10n_master" not. Both should have nearly the same content. Can we check if increasing build limits will work?

**Comment by stsewd** [comment]
Sure, I'll try to check that soon

**Comment by typ1-brods** [comment]
@stsewd Did you try that yet?

**Comment by stsewd** [comment]
So, I increased the build time and memory, but the build is still failing. I just noticed that latest build in only 232 seconds, I increased the build time to 1500 seconds but i10n branch is still failing. And a first sight the changes aren't that many, or changes in requiremenst or conf.py.

So, my guessing this is a bug parsing the md files, I'll try to build this locally (outside rtd) and see if I can replicate the excessive build time.

**Comment by stsewd** [comment]
So, I'm not able to build your docs locally, there are several errors like this one

`sphinx-build -b html . _build/html`

```
/home/stsewd/github/AndroidAPSdocs/docs/CROWDIN/nl/index.rst:4: ERROR: Unknown directive type "opmerking".

.. opmerking::
   **VOOR JE EIGEN VEILIGHEID**
```
Please fix those errors and try again. I'm not sure why the build is reported as time out, I'm investigating that.

**Comment by typ1-brods** [comment]
Thank you very much. This is a error I can work with. Can you post the whole log file?

**Comment by stsewd** [comment]
You can see the full details building your project locally with `sphinx-build -b html . _build/html`

**Comment by typ1-brods** [comment]
So, I have fixed all ERRORS. When locally building, there are only WARNINGS. Although, online building times out https://readthedocs.org/projects/androidaps/builds/9174827/

Any ideas? Maybe sth to do with this warning: "enable_auto_doc_ref" is deprecated?

**Comment by stsewd** [comment]
I'll continue investigating, now I can build your docs locally. One thing that comes to my mind is the command waiting for input or something weird like that.

**Comment by stsewd** [comment]
I was able to replicate this in my local instance of rtd, but I can't replicate it outside rtd. It gets stuck in 

```
Running Sphinx v1.5.6
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 842 source files that are out of date
updating environment: 842 added, 0 changed, 0 removed
/home/stsewd/rtd/readthedocs.org/user_builds/androidaps/envs/l10n_master/lib/python3.7/site-packages/recommonmark/parser.py:280: UserWarning: Unsupported inline type Hardbreak                                                                                                   
  warn("Unsupported inline type " + inline.t)
^[ading sources... [  3%] CROWDIN/bg/Installing-AndroidAPS/Building-APK   
```

**Comment by stsewd** [comment]
I don't know why, but removing all `Building-APK.md` files make the build pass.

`find . -name Building-APK.md -delete`

**Comment by stsewd** [comment]
So, I removed all images in all `Building-APK.md` files and it pass.

`vim +g/Screenshot/d CROWDIN/bg/Installing-AndroidAPS/Building-APK.md`

**Comment by stsewd** [comment]
Actually, just removing the link to the image 41 in all `Building-APK.md` files makes the build pass.

**Comment by stsewd** [comment]
Actually (again, and finally), what makes the timeout is lines that have this form

```
![Screenshot 1](../images/Installation_Screenshot_01.png)<!-- Comment -->
```

(the comment just next to image, without space)

This makes the build happy

```
![Screenshot 1](../images/Installation_Screenshot_01.png) <!-- Comment -->
```
(note the space after the image)

It works putting the comment in any place but next to an image without spaces.

I don't know why times out only inside the container (we use docker to run the builds in Read the Docs), I can only guess a deep dependency of recommonmark.

Let me know if you have any other problem after fixing the above syntax in those pages.
