### ISSUE TITLE
SKIP_SUBMODULES: psy-maps and psy-simple

### ISSUE THREAD

**Issue by Chilipp** [rtfd/readthedocs.org#5732]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/psy-maps and https://readthedocs.org/projects/psy-simple
* Read the Docs username (if applicable): Chilipp

## Expected Result

The submodules should not be cloned because they only contain test files, unimportant for the docs.

## Actual Result

The submodules are currently cloned drastically slowing down the build. Please set the ``SKIP_SUBMODULES`` feature flag for these two projects (see https://docs.readthedocs.io/en/stable/guides/feature-flags.html)

**Comment by humitos** [comment]
> The submodules are currently cloned drastically slowing down the build. Please set the `SKIP_SUBMODULES` feature flag for these two projects (see [docs.readthedocs.io/en/stable/guides/feature-flags.html](https://docs.readthedocs.io/en/stable/guides/feature-flags.html))

You can do this by yourself using the config file: https://docs.readthedocs.io/en/latest/config-file/v2.html#submodules

I'm closing this issue, but feel free to re-open if you consider that it's still valid. Let us know if the config file works for you as well.
