### ISSUE TITLE
incomplete path of linked source, missing `master`

### ISSUE THREAD

**Issue by Borda** [rtfd/readthedocs.org#5735]
## Details

I am generating the documentation with Sphinx, and I found a way how to link the particular functions from a repository such that I have custom `linkcode` function. Running it locally, everything works fine, but after build on Read-the-docs one segment of the path is missing - `master`.
The particular path generation is here - https://github.com/Borda/BIRL/blob/fccb6bc7abfd8a44377097fdc0178afeeefd396a/docs/source/conf.py#L316

* Read the Docs project URL: https://birl.readthedocs.io/en/latest
* Build URL (if applicable): https://readthedocs.org/api/v2/build/9077197.txt
* Read the Docs username (if applicable): Borda

## Expected Result

*A description of what you wanted to happen*
https://github.com/Borda/BIRL/blob/birl/utilities/data_io.py#L1037-L1055

## Actual Result

*A description of what actually happened*
https://github.com/Borda/BIRL/blob/master/birl/utilities/data_io.py#L1037-L1055

**Comment by Borda** [comment]
or is there another way how to link source-code to the docs? I have tried a few from stack-overflow, but none worked as expected... :/

**Comment by stsewd** [comment]
That's weird because you are harcoding the `master` branch.

The only thing I can see that may be causing problems is https://github.com/Borda/BIRL/blob/fccb6bc7abfd8a44377097fdc0178afeeefd396a/docs/source/conf.py#L303

It could return (`../foo`) and then it resolves to `blob/master/../foo` -> `blob/foo/`

At first sight I think you don't need to use `relpath`, you already have the correct path from `inspect.getsourcefile`.

**Comment by Borda** [comment]
ok, I will try... and is there a way how to get the actual branch/tag name to be inserted?

**Comment by stsewd** [comment]
In an easy way I don't think so. But I've used this to get the actual branch for another type of project `git symbolic-ref --short HEAD`

**Comment by Borda** [comment]
well the previous hint did not work, I got a very full path
https://github.com/Borda/BIRL/blob/master//home/docs/checkouts/readthedocs.org/user_builds/birl/checkouts/devel/birl/utilities/cls_experiment.py#L26-L176
but now I can try to dig deeper into this...

**Comment by stsewd** [comment]
In that case, I think you need to get the full path from `__file__` first, and them `../..` and use that to get the relpath. Actually, you already have the root here https://github.com/Borda/BIRL/blob/fccb6bc7abfd8a44377097fdc0178afeeefd396a/docs/source/conf.py#L22

**Comment by Borda** [comment]
pls, could you be more specific, instead of the `fn`?

**Comment by stsewd** [comment]
```diff
-fn = os.path.relpath(fn, start=os.path.abspath('..'))
+fn = os.path.relpath(fn, start=PATH_ROOT)
```

**Comment by Borda** [comment]
in the end, I made a switch between local build and RTD...
