### ISSUE TITLE
Build succeeds, no html generated (aka maze screen)

### ISSUE THREAD

**Issue by mlsmithjr** [rtfd/readthedocs.org#5751]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytranscoder/
* Build URL (if applicable): https://readthedocs.org/projects/pytranscoder/builds/9157413/
* Read the Docs username (if applicable): mlsmithjr

## Expected Result

Docs accessible via published URL http://pytranscoder.readthedocs.io.

## Actual Result

Successful build, but always get the maze screen (document not found).
Locally I get good docs with "make html".

Thanks for any assistance you can render.

**Comment by davidfischer** [comment]
@mlsmithjr, The build appears to be generated but there's no index.html file in the output. I'm trying to figure out why not. However, for example, there are other pages: https://pytranscoder.readthedocs.io/en/latest/contents.html

**Comment by mlsmithjr** [comment]
My conf.py sets master_doc = "contents".  First attempts to publish and the build complained there was no "contents.html" file so I switch to that.  For a time it worked fine.

**Comment by davidfischer** [comment]
I think there are two possible courses of action:

* The best one in my opinion would be to unset `master_doc` and move `contents.rst` -> `index.rst`.
* The alternative if you really want to use `contents.rst` and `contents.html` is setup [a redirect](https://docs.readthedocs.io/en/stable/user-defined-redirects.html). I recommend the first one though.

https://docs.readthedocs.io/page/faq.html?highlight=index.html#help-my-build-passed-but-my-documentation-page-is-404-not-found

**Comment by mlsmithjr** [comment]
Excellent.  Will do. Thanks much for your help.
