### ISSUE TITLE
Build error with build id #9164099

### ISSUE THREAD

**Issue by kendonB** [rtfd/readthedocs.org#5756]
## Details:

* Project URL: https://readthedocs.org/projects/Caster/
* Build URL(if applicable): https://readthedocs.org/projects/caster/builds/9164099/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result

This repo hasn't built successfully for a while and I've been unable to figure out what's going wrong. I was originally getting the error where the site_dir was inside the docs_dir. I then added a minimal `mkdocs.yml` and that didn't work. Then I tried adding `mkdocs==0.16` to `requirements.txt` (i.e. require an old version) and that didn't work. Then I tried adding `mkdocs==0.15.2` to `requirements.txt` (i.e. require an older version) and that didn't work. I've now reverted everything back and (of course) have the original error.

I just need some help with how to actually get it right.

## Actual Result

Build fails.

**Comment by stsewd** [comment]
Your project is missing the required `mkdocs.yml` file, we are generating one automatically for you, but isn't exactly what your project needs.

Please refer to the mkdocs configuration https://www.mkdocs.org/user-guide/configuration/

Also, take a look to the rtd configuration file to help you setup your mkdocs project https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by stsewd** [comment]
Also, we are going to remove soon the _try to guess and create a configuration file for users_, most of the time it doesn't work and isn't explicit to the user what's happening https://github.com/rtfd/readthedocs.org/issues/2483.

Closing as this isn't a RTD issue.
