### ISSUE TITLE
"SyntaxError: unexpected token: identifier" with filenames with apostrophes

### ISSUE THREAD

**Issue by Juanlu001** [rtfd/readthedocs.org#5757]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/poliastro/
* Build URL (if applicable): https://readthedocs.org/projects/poliastro/builds/9072047/
* Read the Docs username (if applicable): Juanlu001

## Expected Result

No JS syntax errors.

## Actual Result

> `SyntaxError: unexpected token: identifier`

![Screenshot from 2019-06-03 08-42-52](https://user-images.githubusercontent.com/316517/58781653-cd967600-85dc-11e9-82cd-2c548ac306ed.png)

**Comment by stsewd** [comment]
Thanks for reporting this!

We inject these values from our sphinx extension, PR at https://github.com/rtfd/readthedocs-sphinx-ext/pull/66
