### ISSUE TITLE
Build error with build id #9166117

### ISSUE THREAD

**Issue by justinshenk** [rtfd/readthedocs.org#5758]
## Details:

* Project URL: https://readthedocs.org/projects/simages/
* Build URL(if applicable): https://readthedocs.org/projects/simages/builds/9166117/
* Read the Docs username(if applicable): justinshenk

## Expected Result

Build would give an error

## Actual Result

Build fails without error:

```
git clone --no-single-branch --depth 50 https://github.com/justinshenk/simages .

> Command time: 0s Return: 0

git checkout --force origin/master

> From https://github.com/justinshenk/simages
   2dd77e4..4eb6293  master     -> origin/master

git clean -d -f -f

> Command time: 0s Return: 0
```

**Comment by stsewd** [comment]
Hi, this is a problem while reading the submodules file.

You don't have this submodule in your repo https://github.com/justinshenk/simages/blob/4eb6293ca73c0ae13845f8ebc3ce9c9af539139c/.gitmodules#L2

See #4371

**Comment by justinshenk** [comment]
Thank you @stsewd!
