### ISSUE TITLE
Project building with mkdocs 17.3 and I can't figure out how to get it to use a later version

### ISSUE THREAD

**Issue by kendonB** [rtfd/readthedocs.org#5761]
## Details

* Read the Docs project URL: https://caster.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/caster/builds/9167222/
* Read the Docs username (if applicable): kendonB

## Expected Result

Page builds just like the page here: https://kendonbcaster.readthedocs.io/en/latest/ with build info https://readthedocs.org/api/v2/build/9167056.txt

## Actual Result

Page doesn't build. One difference I can see is that 9167222 uses `mkdocs==17.3` all over the place and the other shows `mkdocs<1.1`. I have added mkdocs<1.1 to requirements.txt but it doesn't seem to work.

**Comment by stsewd** [comment]
> I have added mkdocs<1.1 to requirements.txt but it doesn't seem to work.

Read the Docs is installing your requirements from https://github.com/kendonB/Caster/blob/fix_docs/castervoice/doc/build/requirements.txt

Which doesn't contain `mkdocs<1.1`

Looks like you are using an old type of configuration for mkdocs, so you wanto to pin your mkdocs version to `mkdocs==17.3`

**Comment by kendonB** [comment]
To be clear, the kendonb copy works fine and I'm trying to fix the dictation-toolbox copy. See here: https://github.com/dictation-toolbox/Caster/blob/develop/castervoice/doc/build/requirements.txt which does contatin `mkdocs<1.1` yet it gets built with `mkdocs==17.3`

**Comment by stsewd** [comment]
So, here is the explanation. The other project was created a time ago, we updated the default version of mkdocs for new projects, so we don't break old projects.

That's why you see `mkdocs==17.3` in the pip install step.

However, according to your requirements, you want to install `mkdocs<1.1`, which is already installed (0.17.3). So what you really want to put in your requirements is `mkdocs==1.1` or the version that you need.

**Comment by kendonB** [comment]
OK I tried that and I can see that it installs the new version near the end of the requirements bit. https://readthedocs.org/projects/caster/builds/9167350/

However, I still see no updates to the actual site: https://caster.readthedocs.io/en/latest/

**Comment by stsewd** [comment]
Sorry, I can't tell the difference between those docs. Anyway, please try cleaning your browser's cache

**Comment by kendonB** [comment]
That might have been it. I can see it's working now. Thanks for your help!!!
