### ISSUE TITLE
Build error with build id #9163229

### ISSUE THREAD

**Issue by letrend** [rtfd/readthedocs.org#5784]
## Details:

* Project URL: https://readthedocs.org/projects/CARDSflow/
* Build URL(if applicable): https://readthedocs.org/projects/cardsflow/builds/9163229/
* Read the Docs username(if applicable): roboy

## Expected Result

The build fails when checking out master

## Actual Result
Aborts and reports failure

**Comment by stsewd** [comment]
This is because this submodule doesn't exist or isn't proper configured

https://github.com/CARDSflow/CARDSflow/blob/e5ebf344ec177548397cec95ad52f18d08a15a00/.gitmodules#L34-L36

See #4371

**Comment by letrend** [comment]
awesome, that solved the problem, thanks a lot!!!
