### ISSUE TITLE
Enable DONT_OVERWRITE_SPHINX_CONTEXT on further godot-* projects

### ISSUE THREAD

**Issue by akien-mga** [rtfd/readthedocs.org#5799]
## Details

* Read the Docs project URL: all `godot-*` projects listed under https://readthedocs.org/profiles/Akien/
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): Akien

## Expected Result

As discussed in #2971, the `DONT_OVERWRITE_SPHINX_CONTEXT` should be enabled manually by sysadmins for projects which need it.

I asked earlier to enable it for the `godot` repo, and it works well. Now I would like it enabled for all `godot-*` localization projects, so that I can override the `Edit on GitHub` link there too.

Those projects are listed here: https://readthedocs.org/profiles/Akien/

Alternatively, here's the list of project names:
```
godot-de
godot-es
godot-fr
godot-ko
godot-pl
godot-pt-br
godot-ru
godot-uk
godot-zh-cn
```

Thanks in advance.

**Comment by stsewd** [comment]
Done, let us know if any problem

**Comment by akien-mga** [comment]
Hi,

Reusing this ticket as it's related, but tell me if it would be better to file a new issue.

Could you enable `DONT_OVERWRITE_SPHINX_CONTEXT` on those three newly created instances, as well as bump their timeout to `5400` for #3555?

```
godot-fi
godot-it
godot-ja
```

Thanks in advance!

**Comment by stsewd** [comment]
Sure, I'll do that now

**Comment by stsewd** [comment]
Done, let us know if there is any problem

**Comment by akien-mga** [comment]
Thanks!
