### ISSUE TITLE
can not install package

### ISSUE THREAD

**Issue by am2222** [rtfd/readthedocs.org#5804]
## Details

* Read the Docs project URL: https://pydggrid.readthedocs.io/
* Build URL (if applicable): https://pydggrid.readthedocs.io/
* Read the Docs username (if applicable):
am2222
## Expected Result

Hi,
My project needs to be compiled to be able to use autodoc, How I can make it to be installed before compiling documentation on readthedocs server?

## Actual Result
In build log I face this error
``WARNING: autodoc: failed to import module '??'; the following exception was raised:
No module named '???'``

**Comment by stsewd** [comment]
Hi, you can use a configuration file to install your project

https://docs.readthedocs.io/en/stable/config-file/v2.html

This setting https://docs.readthedocs.io/en/stable/config-file/v2.html#packages
