### ISSUE TITLE
Different rendering on RTD vs local build

### ISSUE THREAD

**Issue by t-makaro** [rtfd/readthedocs.org#5809]
## Details

* Read the Docs project URL: [nbconvert](https://nbconvert.readthedocs.io/en/latest/config_options.html)

On nbconvert's docs, we are getting different documentation rendering depending on whether we build locally or on RTD. This was not an issue for nbconvert <=5.4.0, but it is for nbconvert >=5.5.0.

Expected:
![image](https://user-images.githubusercontent.com/18018386/59554575-f2360a80-8f59-11e9-82cd-1ec1d2e0fa25.png)
which is what I get when I build locally.

Actual Result on RTD:
![image](https://user-images.githubusercontent.com/18018386/59554578-feba6300-8f59-11e9-9932-575b3592cccf.png)

This makes the division between the config and the type hard to distinguish. (This rst file is automatically generated, so this isn't easy to change the rst.)

### reST

```rst
Configuration options
=====================

Configuration options may be set in a file, ``~/.jupyter/jupyter_nbconvert_config.py``,
or at the command line when starting nbconvert, i.e. ``jupyter nbconvert --Application.log_level=10``.

Application.log_datefmt : Unicode
    Default: ``'%Y-%m-%d %H:%M:%S'``

    The date format used by logging formatters for %(asctime)s

Application.log_format : Unicode
    Default: ``'[%(name)s]%(highlevel)s %(message)s'``

    The Logging format template
```

The only difference wrt docs for nbconvert 5.5.0 is that we added a ```.readthedocs.yml``` with the follwing content:
```yml
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

conda:
  environment: docs/environment.yml

build:
  image: latest

python:
  version: 3.7

**Comment by humitos** [comment]
Hi! I think you are using Sphinx 2.x on RTD and a different version locally. Could it be?

I've seen this already and it was because of that
