### ISSUE TITLE
Web Based Documentation Editor

### ISSUE THREAD

**Issue by CorruptComputer** [rtfd/readthedocs.org#5811]
## Details

* Read the Docs project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

It would be awesome if we had the choice of a web based editor right in Read The Docs, this would help with people who aren't very familiar with Git. This could be done with GitHub Apps, when a user edits it from the web interface it could automatically create a Pull Request on the repository with the changes.

## Actual Result

This option doesn't exist.

**Comment by dojutsu-user** [comment]
I like the idea.
What are  your thoughts.... @ericholscher?

**Comment by stsewd** [comment]
I think we used to have this feature a long time ago, it was removed for some reason

**Comment by ericholscher** [comment]
Yea, this is definitely not something we have the skills or capacity to work on. It's a good idea, but perhaps someone else should make it :)

**Comment by humitos** [comment]
I found this some time ago that could be helpful in case that someone wants to implement this: https://django-front.readthedocs.io/en/latest/

**Comment by Seth10001** [comment]
I would love to see this! Has anyone done this yet?
