### ISSUE TITLE
Rename sipp-wip.readthedocs to sipp.readthedocs

### ISSUE THREAD

**Issue by wdoekes** [rtfd/readthedocs.org#5824]
Hi!

Per #5403, it seems I can ask here if I want to rename a slug.

@rkday now holds https://sipp.readthedocs.io/ but I'd like to move https://sipp-wip.readthedocs.io/ there.

Rob, I assume you're okay with that?

Thanks!

**Comment by stsewd** [comment]
> @rkday now holds https://sipp.readthedocs.io/ but I'd like to move https://sipp-wip.readthedocs.io/ there.

What you are asking is to have the slug `sipp` which is occupaid right now. You can follow https://docs.readthedocs.io/en/stable/abandoned-projects.html

Or if you both agreed and you don't need to keep any data from the other project, you could remove both projects and create a new one with the `sipp` slug.

**Comment by rkday** [comment]
I've deleted the old one; go ahead with the rename.

**Comment by wdoekes** [comment]
Superb! :ok: 

I'll go check if I can drop the -wip and recreate a new one.

**Comment by wdoekes** [comment]
Seems to work. Thank you all :)
