### ISSUE TITLE
Random failure for "project needs at least Sphinx v2.0"

### ISSUE THREAD

**Issue by cas--** [rtfd/readthedocs.org#5839]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/deluge/
* Build URL (if applicable): https://readthedocs.org/projects/deluge/builds/9270025/
* Read the Docs username (if applicable): cas

## Expected Result

Automated builds pass 

## Actual Result

Automated builds fail randomly (no changes to docs or docs config) with the following error which requires the build to be manually wiped and rebuilt. This has happened multiple times now so feel this is a bug that needs reporting.

```
Sphinx version error:
This project needs at least Sphinx v2.0 and therefore cannot be built with this version.
```

**Comment by stsewd** [comment]
Thanks for reporting, this is the same as #5810
