### ISSUE TITLE
Build error with build id #9274652

### ISSUE THREAD

**Issue by trombastic** [rtfd/readthedocs.org#5843]
## Details:

* Project URL: https://readthedocs.org/projects/PyScada/
* Build URL(if applicable): https://readthedocs.org/projects/pyscada/builds/9274652/
* Read the Docs username(if applicable): trombastic

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, this is because your project has some unused submodules in https://github.com/trombastic/PyScada/blob/master/.gitmodules, see #4371

**Comment by trombastic** [comment]
Thank you very much!
