### ISSUE TITLE
Build error with build id #218632

### ISSUE THREAD

**Issue by veenamj** [rtfd/readthedocs.org#5844]
## Details:

* Project URL: https://readthedocs.org/projects/Qubole Data Service/
* Build URL(if applicable): https://readthedocs.org/projects/qubole-qubole-documentation/builds/218632/
* Read the Docs username(if applicable): dev+readthedocs@qubole.com

## Expected Result

*A description of what you wanted to happen*

## Actual Result

Builds failing with IOError: [Errno 26] Text file busy: '/home/docs/checkouts/readthedocs.org/user_builds/qubole-qubole-documentation/envs/latest/bin/python2.7'

**Comment by veenamj** [comment]
There seems to be something because our account is on readthedocs.com. I'm closing this issue.

**Comment by stsewd** [comment]
Hi, the error is because two builds where triggered at the same version simultaneity

**Comment by veenamj** [comment]
okay = @stsewd  - Thanks for letting me know!
