### ISSUE TITLE
grant third party access to organization

### ISSUE THREAD

**Issue by martinberoiz** [rtfd/readthedocs.org#5851]
Hello,

I am member of two GitHub organizations:

https://github.com/toros-astro
https://github.com/ctmobservatory

A colleague granted third party access to toros-astro but he doesn't remember how. I want to do the same for ctmobservatory but I can't seem to find a way to grant third party access to readthedocs. I'm not sure if I need to request from within readthedocs or from within GitHub.

Any help is much appreciated, thanks.

## Details

* Read the Docs project URL: https://ctmo-manager.readthedocs.io/en/latest/
* Build URL (if applicable): 
* Read the Docs username (if applicable): martinberoiz

## Expected Result

I would like to find somewhere in readthedocs.org a way to request third party access to my organization.

## Actual Result

I can't find a way to request that in https://readthedocs.org/accounts/social/connections/

**Comment by stsewd** [comment]
If you already connected your account, you should be able to see your org in https://readthedocs.org/dashboard/import/

**Comment by agjohnson** [comment]
If you don't see your organization in your list of importable repositories, a GitHub organization owner needs to authorize our application, it's not an action RTD takes.

See https://help.github.com/en/articles/approving-oauth-apps-for-your-organization for more information on granting this. Feel free to reopen if this is not what you're describing.

**Comment by martinberoiz** [comment]
thanks for the prompt reply, but I still have trouble because I am the owner of the organization and I know how to approve the request once the request is made, but I don't know how to initiate the request.

The link https://help.github.com/en/articles/approving-oauth-apps-for-your-organization explains how to approve the grant request, but I can't make it appear there in my organization settings to begin with.

I'm sorry if I can't explain myself very well, I can further clarify if necessary.

**Comment by stsewd** [comment]
@martinberoiz do you have the read the docs app listed in the `Authorized OAuth Apps` tab?

Do you see your org in https://readthedocs.org/dashboard/import/?
Did you try with the sync button in the above page?

**Comment by stsewd** [comment]
Also, what do you mean with "I can't find a way to request that in https://readthedocs.org/accounts/social/connections/"?

The `Connect to GitHub` button doesn't work?

**Comment by martinberoiz** [comment]
Hi, thank you for your patience,

> do you have the read the docs app listed in the Authorized OAuth Apps tab?

Yes, I have it in my personal account. It seems to imply there that if I have readthedocs listed in my Authorized OAuth Apps in my personal account (martinberoiz), this should also reflect in the organizations I am part of? But for some reason it will not show up in my organization `ctmobservatory`.

> Do you see your org in https://readthedocs.org/dashboard/import/?

I see one of them (toros-astro) but not the other (ctmobservatory). The reload button does not fix the issue.

> The Connect to GitHub button doesn't work?

That button seem to work, since I am connected in my personal account, and readthedocs appear in my Authorized OAuth Apps. But that doesn't propagate to the organizations I own.

**Comment by martinberoiz** [comment]
OMG, never mind. I had to manually grant permission by clicking on readthedocs entry in https://github.com/settings/applications and then grant permission to each organization separately.

**Comment by martinberoiz** [comment]
Thanks for your help

**Comment by maddox05** [comment]
@martinberoiz what exactly did you do? I click on my third party applications and It does not give me any options to add them to the org.

**Comment by 12rambau** [comment]
got to your profile ->settings -> applications -> Authorized oAuthApp. 

There you should find a list of all the application that are wired to your profile. find RDT in the list and click on it: 
in "organization access", click on "grant" for the organization you want to see in the RDT list. 

<img width="698" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/12596392/9c503999-9a15-4261-b541-22255668d203">

**Comment by maddox05** [comment]
awesome thanks, seems like githubs docs are outdated.
