### ISSUE TITLE
Inform users when maintenance operations are taking place.

### ISSUE THREAD

**Issue by jorgecarleitao** [rtfd/readthedocs.org#590]
Following issue #589, I suggest we add a message on the user's admin panel when maintenance is taking place on the server.

This way the user is informed that ongoing server-side work is being done and unexpected behavior or lag is expected, thus avoiding spending time by lack of communication.

This issue can probably be addressed by issue #553.

**Comment by ericholscher** [comment]
We have a maintenance mode in the code now.
