### ISSUE TITLE
No settings for displaying field attribute documentation

### ISSUE THREAD

**Issue by Mgamerz** [rtfd/readthedocs.org#632]
I've built documentation about field attributes in my python files (class variables), and when I do a local sphinx html build I see the documentation. It's important for my project as there's a lot of fields. When I push and your site updates my documentation, these don't seem to be displayed. I tried searching for things in your documentaiton for Read the Docs, but the search seems broken... (It also seems broken on other projects too.) Is there a special syntax you use or are they disabled entirely?

Great service by the way, stuff looks great.

**Comment by whit537** [comment]
We're getting [bit by this as well](https://github.com/gratipay/filesystem_tree.py/pull/20#issuecomment-130357210). I installed `sphinx_rtd_theme` locally, and (as @wbolster reports), my results differ between local and production regardless of the theme:

# Local

![screen shot 2015-08-12 at 12 25 51 pm](https://cloud.githubusercontent.com/assets/134455/9229879/5628a65c-40ed-11e5-9f6e-c9ab9584a861.png)

# Production

![screen shot 2015-08-12 at 12 25 09 pm](https://cloud.githubusercontent.com/assets/134455/9229864/432d2014-40ed-11e5-871a-86fab2e5e94c.png)

**Comment by gregmuellegger** [comment]
I tried it with your repository: https://github.com/gratipay/filesystem_tree.py

I created a fresh Python 2.7 virtualenv, installed `filesystem_tree` with `python setup.py install` installed Sphinx with `pip install Sphinx` and then ran `make html` in the `docs` directory.

The result is this:
![screen1](https://cloud.githubusercontent.com/assets/88278/9308875/b33527e0-4506-11e5-8891-2f1bbe8c8694.png)

So it seems that it is not related to the rtd theme. But either to Sphinx or the way that you build your docs. What actual command do you use to build your docs locally?

**Comment by whit537** [comment]
Well, I'll be darned. I performed the steps you performed and got the same result:

![screen shot 2015-08-17 at 1 14 14 pm](https://cloud.githubusercontent.com/assets/134455/9311069/f281a768-44e1-11e5-816f-bd6b60979800.png)

Perhaps my previous result is with an older version of Sphinx?

**Comment by whit537** [comment]
Possibly relevant: https://github.com/sphinx-doc/sphinx/issues/1444 and https://github.com/sphinx-doc/sphinx/issues/344?

**Comment by whit537** [comment]
Reticketed as https://github.com/sphinx-doc/sphinx/issues/2006.

**Comment by whit537** [comment]
> What actual command do you use to build your docs locally?

@gregmuellegger To answer your question directly: `make html` in the `docs` directory, just as you used.

**Comment by gregmuellegger** [comment]
@whit537 I hope you are okay when I'm closing this here as I think it's a Sphinx issue.

**Comment by whit537** [comment]
@gregmuellegger Yeah, that's fine. I will follow up here if necessary based on what Sphinx says. :-)
