### ISSUE TITLE
Don't highlight version as outdated if it is the same as custom default branch

### ISSUE THREAD

**Issue by kmike** [rtfd/readthedocs.org#635]
In Scrapy default branch is set to 0.22: http://doc.scrapy.org/en/latest/

There is also an explicit 0.22 version from the same branch: http://doc.scrapy.org/en/0.22/ - it is highlighted as outdated. 

I can just remove 0.22 from visible versions, but I think it is good to have URLs with explicit version number - links can become outdated otherwise.

**Comment by ericholscher** [comment]
I believe this should be fixed with our updates to this logic -- please let me know if it is still an issue, and I will re-open.

**Comment by dangra** [comment]
looks good. thanks!
