### ISSUE TITLE
Please clarify commercial usage of Read the Docs

### ISSUE THREAD

**Issue by svisser** [rtfd/readthedocs.org#649]
The website currently mentions that it's free but it's not explicit about commercial usage. This suggests commercial usage is allowed but I'm wondering whether that's the case and what the conditions (if any) are.

**Comment by ericholscher** [comment]
We now have https://readthedocs.com for commercial use.

**Comment by ilukac** [comment]
Hi,

Sorry to comment on a close issue but didn't find any better way to ask. We have a bit specific situation for which is hard to figure out the answer. We are working on a product which will be soon available in an open core mode (core part opensourced with some features commercial as add-ons). 
The goal is to make a sustainable product like what you are trying to do with the rtd.com.

The product documentation will be mostly about the core part and we are preparing it to be available on a public repo for the whole product, including the smaller parts for addons, there is not much sense in dividing it. Now we are checking to use RTD but not sure if we can use the free option for our mostly but not completely open sourced product. 

Could you confirm that we can use the free version? Or not :)
