### ISSUE TITLE
Subproject and single version

### ISSUE THREAD

**Issue by henrikbjorn** [rtfd/readthedocs.org#651]
Hello :)

Tried enabled Single Version for a project that have many subprojects added. This didn't work as the resulting url returns 404.

According to the documentation it would only break for multiple versions / languages.

Is it possible to get it to work and have urls like myproject.rtfd.org/projects/proj1 and myproject.rtfd.org/projects/proj2 ?

**Comment by ericholscher** [comment]
Believe this should be fixed now. We did a bunch of work around subprojects & single version code, including a test for this: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/rtd_tests/tests/test_resolver.py#L100

**Comment by henrikbjorn** [comment]
@ericholscher :+1: :100:  !
