### ISSUE TITLE
Intregration with Dash

### ISSUE THREAD

**Issue by Kapeli** [rtfd/readthedocs.org#662]
I'll list here all the issues I have found while trying to integrate ReadTheDocs with Dash. It would be great if this list could be worked through so that Dash could someday integrate with RTD.

**Searching issues:**
- [ ] I mainly want to add RTD integration to cover Python packages, and the issue is that there doesn't seem to be a correlation between Python packages listed at [pypi.python.org](https://pypi.python.org) and RTD project names. For example, [beautifulsoup.readthedocs.org](http://beautifulsoup.readthedocs.org) has docs for beautifulsoup in Chinese, while [beautiful-soup-4.readthedocs.org](http://beautiful-soup-4.readthedocs.org) contains the actual docs for beautifulsoup. A Dash user will most likely search for "beautifulsoup" and install the Chinese docs. 
  - Possible workaround: [wiki.python.org/moin/CheeseShopDev](https://wiki.python.org/moin/CheeseShopDev) has a TODO entry for "A link from package to RTFD". When they add that I should be able to use it.
- [ ] Searching for something like "zend" doesn't give you the "zf2" project. Ideally, a search for both "zf" and "zend" should return the "zf2" project. 
  - Possible workaround: one idea would be for RTD to search the title of the main page of the generated docs.

**Organization issues:**
- [ ] As far as I can tell, anyone can claim any project name and have docs generated for it without any kind of verification/review. That's kind of bad, as you get issues like the one I mentioned regarding beautifulsoup. I've also seen some other Chinese docs that are listed as English.

**Versioning issues:**
- [ ] Versions are not easy to navigate using the API. All the downloads listed in the JSON response are for "latest", regardless of the version. It's also unclear which versions are public and which are not (e.g. compare versions listed at [readthedocs.org/projects/pip](https://readthedocs.org/projects/pip/) to [readthedocs.org/api/v1/version/pip](http://readthedocs.org/api/v1/version/pip/?format=json)).

**Comment by ghuntley** [comment]
Project @ReactiveUI would love to see this functionality added. Ref: https://github.com/reactiveui/ReactiveUI/pull/771

**Comment by jmagnusson** [comment]
I agree with @chris-erickson that being able to manually add the docs that you want would be perfectly good. Together with @GaretJax's idea on having RTD generate .docset files I think we're on to something.

What do you think @Kapeli?

**Comment by Kapeli** [comment]
I'm very reluctant to add half-baked features to Dash, because they cause a lot of confusion and complaints from users. I might do it sometime in the future though, but I'd much rather work on features that I can add properly.

**Comment by jmagnusson** [comment]
@Kapeli I understand your point! Sucks to be left out though because you're a Python junkie :cry:

**Comment by ericholscher** [comment]
Closing this, as I think it doesn't make sense to support Dash as things are currently architected. If the Python world ever ends up with a specific API doc tool, it would make sense to integrate that with Dash, but since Dash isn't used for Prose documentation, Read the Docs will likely never support it fully.

**Comment by Kapeli** [comment]
> Closing this, as I think it doesn't make sense to support Dash as things are currently architected. If the Python world ever ends up with a specific API doc tool, it would make sense to integrate that with Dash, but since Dash isn't used for Prose documentation, Read the Docs will likely never support it fully.

Dash works fine with Prose docs. It's a lot harder to support than API docs, yes, but there are a lot of docsets that are not API-related or API-only. That's my job though and you're not supposed to do anything about it. I'm not expecting RTD to generate docsets.

My issues with supporting RTD have nothing to do with the docs themselves. I don't think I mentioned the docs anywhere in this issue, I might be wrong though. I admit I have lots of issues with Sphinx, but I can work around them.

My issue is with the services RTD provides (searching, versioning and organisation). If RTD would fix those issues, or at least some of them, I'd be able to integrate it.

If this is something you're not willing to do, that's fine and I understand and respect your decision. Don't blame it on Dash and the Prose docs though. The main issue is RTD's API and organisation. Everything else I can work around.

**Comment by ericholscher** [comment]
Good points. The main issue on our side is that most package repositories (PyPI specifically) don't allow any kind of oauth claiming, and we don't really have a sane way to namespace and claim packages. Since we aren't a language specific tool, there are a large number of things that could be named "sphinx" for example.

I guess the proper solution would be to allow a project to specify a link to an existing package in a repository somewhere (eg. 'beautifulsoup' on RTD -> bs4 on PyPI), but again without platform support, it's almost impossible for us to verify a claim of ownership.

**Comment by Kapeli** [comment]
Project naming is an issue, but I think I can work around it a bit on my end by warning users about the issue, sorting the results and possibly allowing users to search using the full RTD URL of a project they want.

Things have changed with Dash and RTD since this issue was opened, so maybe it's best if we go through it step by step.

How do I search for projects using the API? The only thing I could find was https://read-the-docs.readthedocs.org/en/latest/api.html#file-search, but it doesn't seem to work (see http://readthedocs.org/api/v1/file/search/?format=json&q=virtualenvwrapper). File search is not really what I want though, just project search. For my needs, I think I'd want an API that searches projects using the RTD name (i.e. `pip`), the RTD URL (i.e. `http://pip.readthedocs.org/`) and the project URL (i.e. `https://pip.pypa.io/`) and nothing else. I can work with any kind of project search API you have though.

**Comment by asafayan** [comment]
Any further progress on this issue since Sept 2015?  I assume not.

**Comment by stantond** [comment]
@Kapeli If this is still a thing, that search problem could sit in a new issue to be solved in isolation

(I'd love to see RTD integration in Dash!)

**Comment by Kapeli** [comment]
@stantond Good idea. I've done that. One thing I've noticed is that there's an API to get the complete list of projects on RTD. I can definitely use that to just grab the list of all projects and implement my own search over it.

I'll start working on it and experimenting.

I'm closing this issue as it's become too old/outdated.

**Comment by jonashaag** [comment]
@Kapeli what's the state of Dash and RTD integration? I'd be interested in helping with this.

**Comment by Kapeli** [comment]
I've given up on it for now. Even if I come up with a way to get what I need from RTD (search, versioning and so on), there's still the issue with Sphinx, which doesn't have a strict/common format between docs and is hard to index right. Using the intersphinx index is the best approach I have so far, but it often misses things and is incomplete, even for the main Python docs.

It's one of those features that I'm afraid to add because then I'll be stuck maintaining it forever and constantly add fixes/workarounds for. Docs for Node.js packages are in the same boat.

**Comment by asfaltboy** [comment]
I admin I haven't read all the thread above, but would really love to see more rtfd docsets in dash. Maybe we should undertake this feature iteratively, for example first creating an rtfd scraper which handles a few common sphinx themes, and try to make it modular enough to allow people to add their own?

If one was to write this sort of parser, where would y'all suggest to start?

**Comment by rgov** [comment]
There's a newer RTD [API](https://docs.readthedocs.io/en/stable/api/v2.html#versions).

1. GET https://readthedocs.org/api/v2/project/?slug=requests
2. Pick a result and get its ID, e.g., 668
3. GET https://readthedocs.org/api/v2/project/668/active_versions/

The download links appear to be correct for all versions. The canonical URL field may not be correct.

**Comment by humitos** [comment]
@Kapeli Hi! This thread caught my attention because I've been working on a new APIv3 (see https://docs.readthedocs.io/en/latest/api/v3.html and https://github.com/readthedocs/readthedocs.org/pull/6169). It's currently on Beta and we are planning to make a stable release soon. Although, I'd love to know if you are still interested on having an integration between Dash and Read the Docs and what are exactly the things that are missing from our side for this to happen.

From what I understand from here, only a search endpoint where you can find projects by name, url or project url. Am I correct?

Regarding the consistency around the names/slugs of the projects, I think there isn't too much we can do there.

**Comment by Kapeli** [comment]
@humitos Yes, the search endpoint is all that's needed now. If possible, the results should also include the language the project is in, so I can clearly show it in the interface.

**Comment by dufferzafar** [comment]
@Kapeli What tool do you use to convert a read the docs site to a dash docset?

**Comment by Kapeli** [comment]
> @Kapeli What tool do you use to convert a read the docs site to a dash docset?

I use a custom tool for almost every Python lib I support. Try doc2dash for something general purpose.

**Comment by alvaromunoz** [comment]
Just chiming in to see if you're planning to set https://readthedocs.org/search/ to be callable as an API, or modify https://readthedocs.org/api/v2/search/ so the `project` parameter is optional or be able to search for projects instead of everything.
