### ISSUE TITLE
Graphs of interesting stats.

### ISSUE THREAD

**Issue by wraithan** [rtfd/readthedocs.org#699]
It would be nice to have graphs of things like builds per hour, new projects per day, etc. Currently we have all the data for that, but we aren't exposing it in any way.

**Comment by agjohnson** [comment]
We added collectd and graphite to our stacks a while ago. We can easily graph Interesting Things now, but we're not exposing said things anywhere publicly. Perhaps it would be an upgrade, but going to close this out as it's mostly covered with our operations stack.
