### ISSUE TITLE
store rtd setting in project's robots.yaml

### ISSUE THREAD

**Issue by techtonik** [rtfd/readthedocs.org#752]
For local troubleshooting and debug it may worth to expose RTD project settings to files. More specifically - read them from file provided by the project. I named it `robots.yaml`, but it could be anything.
```
readthedocs:
  confpath: doc/pypy/conf.py
````

**Comment by gregmuellegger** [comment]
We are working on this as part of the https://github.com/rtfd/readthedocs-build repository. So stay tuned!

**Comment by ericholscher** [comment]
Closing this, as the PR #1849 will add the initial ability to use a YAML config, when it is merged in the next few days. :fire:
