### ISSUE TITLE
Display queue depth warning when it backs up

### ISSUE THREAD

**Issue by wraithan** [rtfd/readthedocs.org#758]
Currently a fair amount of IRC questions and issues opened result from RTD taking a lot time to build someone's project.

Generally when I respond to those questions, after checking the build depth it is easy to explain why their build hasn't started yet. Perhaps we can preempt this by having a banner that shows up when we are backed up by more than 10 or 20 or something.

It wouldn't be hard to do in pure JS. ajax to the depth endpoint, check the value, if it is over a certain amount, set that amount in the html and unhide the banner.

**Comment by ericholscher** [comment]
This got done a while ago :)
