### ISSUE TITLE
Metadata ":orphan:" is displayed in the output

### ISSUE THREAD

**Issue by froschdesign** [rtfd/readthedocs.org#809]
The [metadata field ":orphan:"](http://sphinx-doc.org/markup/misc.html#file-wide-metadata) should not be displayed in the output, but the current renderings contains this markup.

- [Example on readthedocs.org](http://zf2.readthedocs.org/en/latest/modules/zend.form.view.helpers.html#standard-helpers)
- [the markup of the example](https://github.com/zendframework/zf2-documentation/blob/master/docs/languages/en/modules/zend.form.view.helper.form-element.rst)

(This issue is related to #772, but it was closed too quickly.)

**Comment by froschdesign** [comment]
Sorry, for the late response.

> Does it work with the default Sphinx themes?

I don't now. I can not test this.

But the [problem](http://zf2.readthedocs.org/en/latest/modules/zend.form.view.helpers.html#standard-helpers) is still present on readthedocs.org! So, please reopen the issue.

**Comment by jdillard** [comment]
I realize this issue is super old, but I just ran into something similar where I had `:orphan:` at the top of an included file, as seems to have been the case here. You aren't supposed to put metadata at the top of includes, especially if the include isn't at the top of the file.

Related issue: https://github.com/sphinx-doc/sphinx/issues/3167

**Comment by clonker** [comment]
Just to have it documented somewhere, you can tell the include directive to skip `:orphan:`. In some cases it is hard-wired into generated rst files (for example with sphinx-gallery). In that case one may use

```rst
.. include:: examples/index.rst
    :start-after: :orphan:
```

**Comment by cwarnermm** [comment]
Thank you, @clonker! This is the answer I've been looking to find for a while. In my case, I'm trying to hide ``:nosearch::`` rather than ``:orphan:``, and in both cases your solution works!
