### ISSUE TITLE
Haystack SearchFieldError: ... has an empty model_attr 'version' and doesn't allow a default or null value

### ISSUE THREAD

**Issue by espdev** [rtfd/readthedocs.org#827]
I try to set up `solr` search for my local RTD. I get an error:
```
haystack.exceptions.SearchFieldError: The model '<ImportedFile: MyFileName.html: MyProjectName>' 
has an empty model_attr 'version' and doesn't allow a default or null value.
```

This error occurs after the following commands:
```
./manage.py build_files
./manage.py update_index
```
The command `update_index` raises this error. 
What's going on? What am I doing wrong?

**Comment by ericholscher** [comment]
Haystack isn't supported anymore. All search now uses Elastic Search directly.

**Comment by ugokingsley** [comment]
ger
