### ISSUE TITLE
Publishing of wrong PDF file

### ISSUE THREAD

**Issue by FlorianWilhelm** [rtfd/readthedocs.org#835]
In my project PyDSE I am using the **.. plot::** environment which itself creates PDF files of each plot. When RTD builds the PDF of PyDSE everything seems fine as can be seen in the build log https://readthedocs.org/builds/pydse/1416946/. But the RTD site of PyDSE publishes just a single plot as PDF, not the generated documentation, check out http://pydse.readthedocs.org/. For me it seems as if the code who is responsible for publishing the generated documentation gets confused and takes one of the earlier generated PDFs of one of the plots instead of the PDF of the documentation.

**Comment by ericholscher** [comment]
Believe this got fixed with a recent commit.
