### ISSUE TITLE
Search results show reST markup

### ISSUE THREAD

**Issue by zerocrates** [rtfd/readthedocs.org#839]
See, for example, https://docs.readthedocs.org/en/latest/search.html?q=welcome&check_keywords=yes&area=default

This can make the "context" part of the results mostly just a sea of special characters used to make the headers and links and other things.

The global search on readthedocs.org/search doesn't seem to do this, though.

**Comment by ericholscher** [comment]
This is actually using the Sphinx search, not Read the Docs -- so it's a bug with Sphinx and not us. This should be raised with the Sphinx devs here: https://github.com/sphinx-doc/sphinx

**Comment by parsch** [comment]
Facing the same problem with locally built sphinx docs (no matter if using the sphinx-rtd-theme or a custom theme) I came across a related sphinx issue (https://github.com/sphinx-doc/sphinx/issues/1618) and was able to solve this problem by using https://github.com/TimKam/sphinx-pretty-searchresults as suggested over there.
