### ISSUE TITLE
Provide an API to query the build status by commit

### ISSUE THREAD

**Issue by hgrecco** [rtfd/readthedocs.org#872]
In order to do a check before release that everything is ok, I would like to have a way to obtain the current build status for a given commit. So, in addition to:

```
GET /api/v1/build/{id}/
```

also have this:

```
GET /api/v1/commit/{sha1}/
```

or 

```
GET /api/v1/{user}/{project}/commit/{sha1}/
```

Is this possible right now?

**Comment by hgrecco** [comment]
New (simpler?) idea: Is it possible to insert the commit hash in the sphinx html? If it can be done already, then I just need to download the the page and check that it matches the version my latest hash.

**Comment by agjohnson** [comment]
This should be part of newly built documentation with our theme already, we pass the commit hash in with via the API. We are storing the commit hash on the build object now, but we don't expose the commit as a first class endpoint in the api.

**Comment by ericholscher** [comment]
You can find similar API endpoints here: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/restapi/views/core_views.py

Adding a `build_status` endpoint to that file with a test would be a good place to start.

**Comment by PeterJCLaw** [comment]
This looks like it might have some overlap with #2251 which also adds commit ids to builds.

**Comment by RichardLitt** [comment]
@agjohnson This "good first issue" is quite old. Can we improve the solution to fixing it, to encourage contribution? Same with https://github.com/rtfd/readthedocs.org/issues/1045.

**Comment by Alig1493** [comment]
Would it be possible to get a more up to date information on this issue? I'm interested to have a look. Thanks.

**Comment by humitos** [comment]
> Would it be possible to get a more up to date information on this issue? I'm interested to have a look.

Thanks for your interest.

I think the original aspect of the issue is still valid: "build an API endpoint that receive a project and a commit hash and return the status (failed/success) of that build"

The `Build` object should have the commit hash: https://github.com/rtfd/readthedocs.org/blob/1af444173481df9a7b16e015fc6b12abe8155e7e/readthedocs/builds/models.py#L430-L431

So, I think we have all the information to create that endpoint. This could be next to the others at this file: https://github.com/rtfd/readthedocs.org/blob/1af444173481df9a7b16e015fc6b12abe8155e7e/readthedocs/restapi/views/model_views.py

@Alig1493 let me know if you are able to start with that info or not. Please, keep us updated on this :)

Thanks!

**Comment by Alig1493** [comment]
Will the api endpoint be under v1 or v2?

**Comment by humitos** [comment]
v2 is the right place.
v1 is deprecated and shouldn't be used.

**Comment by safwanrahman** [comment]
@humitos There are already `api/v2/buid/<id>`, so what should be the endpoint for this?

**Comment by humitos** [comment]
Yes. What I understood from the original report is to have the ability that given the sha and the project you can know the status of that build.

Now, a build id is needed, that you don't know how to get it from a sha.

Makes sense?

**Comment by safwanrahman** [comment]
@humitos I have understand. I wanted to explain that, there are already a endpoint for `api/v2/buid/<id>`, so the getting with another endpoint like `api/v2/buid/<commit hash>` will make the user confuse.
So I was wondering, what the API endpoint will be.

**Comment by humitos** [comment]
> Can you please clarify?

What about `/api/v2/build/commit/{hash}`?

**Comment by shaddygarg** [comment]
Hey, I would like to contribute to this project. Can I take up this issue if no one is currently working on it?

**Comment by safwanrahman** [comment]
@shaddygarg It has been already worked on by @Alig1493

**Comment by stsewd** [comment]
https://github.com/rtfd/readthedocs.org/pull/3544 (just linking the PR here)
