### ISSUE TITLE
Images are generating via aafigure (via PIL) fail without _imagingft

### ISSUE THREAD

**Issue by tony** [rtfd/readthedocs.org#876]
Logs: https://readthedocs.org/builds/tmuxp/1579742/

I use [sphinxconfig-aafig](https://pythonhosted.org/sphinxcontrib-aafig/) with png image generation at http://tmuxp.readthedocs.org/en/latest/examples.html.

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tmuxp/envs/latest/local/lib/python2.7/site-packages/PIL/ImageFont.py", line 42, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```

This would work 3 months ago, and the error does happen intermittently over the past year on servers since this C module is known to have a confusing install process on some systems.

http://stackoverflow.com/questions/4011705/python-the-imagingft-c-module-is-not-installed (this may or not be relevant in the version of ubuntu on the server)

**Comment by tony** [comment]
I'm reopening this one. :smile:

tree: https://github.com/git-pull/tao-of-tmux/tree/561ebb6411b6774c704d57effaf7865255caffc7
build output: https://readthedocs.org/projects/the-tao-of-tmux/builds/3457460/

With `pillow` removed:

tree: https://github.com/git-pull/tao-of-tmux/tree/a3e2d5b9a506a6fda247622dd7e7b9daace4bcc6
build output: https://readthedocs.org/projects/the-tao-of-tmux/builds/3457454/

I'm going to dig around a bit more.

**Comment by tony** [comment]
@ericholscher Do the servers have ``libfreetype6-dev``?

**Comment by agjohnson** [comment]
@tony the build server images have the library, but not the development headers. I opened rtfd/readthedocs-docker-images#2, are there any other missing reqs?

**Comment by tony** [comment]
Nice to meet you @agjohnson!

I'm having trouble getting the docker images to work to verify on my side.

To be safe, we may as well include the rest of the pillow pre-reqs (https://pillow.readthedocs.org/en/3.0.x/installation.html):

``libfreetype6-dev libtiff5-dev libjpeg8-dev zlib1g-dev liblcms2-dev libwebp-dev``

I think it's ok to omit ``tcl8.6-dev tk8.6-dev python-tk``.

**Comment by tony** [comment]
I see https://github.com/rtfd/readthedocs-docker-images/pull/2 was merged.  Is it live yet? My latest build still has the error.

**Comment by agjohnson** [comment]
No, not live yet, the new images will probably be deployed sometime next week, unless i have free time this weekend.

**Comment by tony** [comment]
@agjohnson I assume this didn't go live yet, just rebuilt and still got the same issue https://readthedocs.org/projects/the-tao-of-tmux/builds/3485557. Wanted to mention because I couldn't get setup correctly qa readthedocs-docker-images locally.

**Comment by agjohnson** [comment]
No, it never got rebuilt, i have some time to squeeze in a deploy today though. I merged in the other missing dependencies above as well, so hopefully that will take care of most PIL issues.

**Comment by tony** [comment]
Thank you for getting back to me.  It's nice we were able to get in the other deps too.

@agjohnson Any updates on this?

**Comment by tony** [comment]
@agjohnson @ericholscher any update on this?  This problem has been plaguing me for a while.

**Comment by tony** [comment]
As of https://readthedocs.org/projects/the-tao-of-tmux/builds/3603481/ (Dec. 31, 2015. 10:58 p.m.) the build passed!

I verified by building manually today https://readthedocs.org/projects/the-tao-of-tmux/builds/3614221/ (Jan. 6, 2016. 6:53 a.m.) and it worked like a charm!

Thanks @agjohnson
