### ISSUE TITLE
html_style works locally but not on ReadTheDocs

### ISSUE THREAD

**Issue by Suor** [rtfd/readthedocs.org#885]
I use readthedocs theme both locally and on ReadTheDocs. However, `html_style` has no effect when docs are compiled on the service.

By the way, I am just trying to add some custom CSS. Here is my `conf.py` - https://github.com/Suor/funcy/blob/master/docs/conf.py

**Comment by delfick** [comment]
I'm running into the same situation here.

**Comment by gregmuellegger** [comment]
We are now displaying the actually used `conf.py` in the build process. You can have a look and see in which cases we override the `html_style` configuration. You can override the value properly when setting `html_theme = "sphinx_rtd_theme"`.

**Comment by logemann** [comment]
doesnt make any difference to me. **html_style** is still being ignored.

**Comment by agjohnson** [comment]
There is a pattern for this in our docs now:
http://docs.readthedocs.io/en/latest/guides/adding-custom-css.html

Closing this here as I don't think we'll change this
