### ISSUE TITLE
Fixed custom subdomain (CloudFlare) Support

### ISSUE THREAD

**Issue by wallrj** [rtfd/readthedocs.org#888]
There's already a closed ticket for this (#625) which I can't re-open, so thought I'd create another.

CloudFlare operate both as DNS provider and as a reverse proxy. 

You first add eg docs.clusterhq.com IN CNAME flocker.readthedocs.org and get the expected DNS response. 

However, when you then turn on their caching and SSL termination features, the CNAME record is changed to a standard A record pointing to the CloudFlare reverse proxy servers.

But they configure their reverse proxy to make requests to docs.clusterhq.com -- which works, because presumably their servers use an internal DNS server which has the original CNAME.

But we find that after a while, ReadTheDocs will stop responding to requests for docs.clusterhq.com, presumably because they have performed a subsequent DNS check and found that the domain no longer has a CNAME to a readthedocs.org subdomain.

It would be good if we could just enter a custom subdomain via the readthedocs web interface -- overriding the automatic DNS lookup system described here:
 * http://read-the-docs.readthedocs.org/en/latest/symlinks.html#cnames

See https://github.com/rtfd/readthedocs.org/issues/625#issuecomment-51769977 for some more debug output and discussion.

**Comment by ericholscher** [comment]
This will be addressed with #1575 -- closing this here.
