### ISSUE TITLE
Generic branch aliases (beyond the built-in "latest")

### ISSUE THREAD

**Issue by itamarst** [rtfd/readthedocs.org#893]
We have a release tag and a release branch, and we'd like to continue pushing documentation improvements to the release branch so documentation gets updated without having to do a release.
Given RTD's use of branch names in the URL/version listing, however, we need to name the release branch in a way that looks OK as part of a URL, which is a bit silly.

It would be nice if branches could be configured with aliases, so we could say something like "branch `release/myproject-0.1` should display as `0.1`".

**Comment by ericholscher** [comment]
:+1: on adding an alias concept. The names of VCS tags & branches aren't always meant to be user facing. We should add the ability to add a specific alias to each Version, which would then be it's user facing slug.

**Comment by agjohnson** [comment]
Moving this to #4001, where we discuss adding more version aliasing rules.
