### ISSUE TITLE
Cannot make plot_directive to work on Python-3

### ISSUE THREAD

**Issue by ankostis** [rtfd/readthedocs.org#896]
I'm trying to embed autogenerated matplotlib diagrams into the docs with the Sphinx's ``plot_directive`` but i have multiple issues with the current state of things in python-3.
I have read the relevant issues explaining how to use the global system's packages (#217, #218 & #272, #334), yet i cannot figure out the following:

1. The "virtualenv + --system-site-packages" does not work, and when RTD prepares the build, it still tries to download and install a new matplotlib version, and ofcourse [it fails](https://readthedocs.org/builds/wltp/1617132/) due to freetype:

    ...
    Extension error:
    Could not import extension matplotlib.sphinxext.plot_directive (exception: No module named 'matplotlib')

3. I cannot find somewhere a list with the available global-site packages in each environment. In my case I need real (not mocked-out) pandas, numpy, scipy & matplotlib for the pyplot-diagrams to work.   Are these available as site-packages?  (assuming that i manage to see them)

**Comment by cdeil** [comment]
Something changed on readthedocs.
For me `pip install scipy` now works:
https://readthedocs.org/projects/gammapy/builds/3287203/
Thanks!

**Comment by agjohnson** [comment]
I believe py3 is still affected here. I'll open a ticket to get some of the missing py3 dependencies into our builders

**Comment by gregmuellegger** [comment]
@ankostis We now have python3 packages for matplotlib, scipy and numpy on the servers. I assume that the plot_directive will now work for Python3 builds. Sorry for the real long wait. Finally we are there :)

**Comment by cdeil** [comment]
:tada: :smile:  :tada: 
Thank you!
