### ISSUE TITLE
Bring back Vagrant (or other sandbox environment)

### ISSUE THREAD

**Issue by malept** [rtfd/readthedocs.org#913]
Vagrant was removed (in #911) because the provisioning Salt states were removed. The Salt states were removed because they were unmaintained. What's the best path towards bringing back some development/sandbox environment that automatically provisions all of the services/dependencies required to run readthedocs?

Related question: how are production servers currently provisioned?

**Comment by gregmuellegger** [comment]
I would also recommend introducing a Vagrant environment for the readthedocs.org repository. It should be easy for developers to get started with a full setup using Postgres, Celery with Redis and all the other bells and whistles.

It does not need to resemble the production environment in total as this might be to complex. But just being able to test against a similar stack would be very beneficial. Developing against sqlite when we use Postgres in production is really a big antipattern.

I'm happy to invest some time there. I assume it would require about 3 hours to have something already working and usable for local development. Plus another hour to document it properly in the installation guide.

**Comment by agjohnson** [comment]
Going to close this, not sure we can realistically muster the effort to make this happen. We currently use VM provisioning that is closely tied to our production infrastructure, and not easy to separate to a general instance. If it was, we'd still have a difficult time allocating resources here.
