### ISSUE TITLE
Build fails with no real error message

### ISSUE THREAD

**Issue by nmerket** [rtfd/readthedocs.org#918]
I have a feeling this is a configuration issue, but I have tried just about everything I can think of and am getting nowhere. I am trying to build the docs I have at the svn repository in this location:

https://hpxml.nrel.gov/pubsvn/branches/hpxmlguide/guide/

Right now my settings are as follows.

```
Repo: https://hpxml.nrel.gov/pubsvn/
Repository Type: Subversion
Python config file: guide/source/conf.py
Default branch: branches/hpxmlguide
```

When I do a build it fails, but doesn't give me anything really useful.

```
Built: Sept. 3, 2014. 11:26 a.m.
State: Finished
Outcome: Failed (Status Code: 0)
Version: latest
Type: html
Build Standard Output
```

**Comment by ericholscher** [comment]
Believe this was fixed.
