### ISSUE TITLE
Short urls must redirect to canonical url

### ISSUE THREAD

**Issue by aik099** [rtfd/readthedocs.org#924]
Each project by default have these urls:

* slug.readthedocs.org
* slug.rtfd.org

When I go to `slug.rtfd.org` I've got redirected to `slug.readthedocs.org` and that's correct. However if I've specified project's canonical url to point to something else then `slug.readthedocs.org` then this isn't taken into consideration during redirects.

I think that both above mentioned urls must redirect to specified canonical url (if user have specified one of 2 shorts urls as canonical ones, then don't hit the redirect loop).

**Comment by ericholscher** [comment]
Closing this because I don't believe we will ever default redirect top-level short domains.
