### ISSUE TITLE
Is there a list of system-packages for python 2 & 3?

### ISSUE THREAD

**Issue by ankostis** [rtfd/readthedocs.org#927]
I've been trying to figure out if matplotlib plot directives are supported (#896) on python3 and would prefer not to rely on trial'n error.

Is it possible to have an updated list of the system's packages for python 2 AND python-3?

**Comment by cdeil** [comment]
:+1: This would be very useful to have!

**Comment by paternal** [comment]
I had a similar problem, and I wrote the [`packages`](http://packages.readthedocs.org) sphinx extension. Among others, it displays the list of installed [python 2](http://packages.readthedocs.org/en/latest/python/python2/) and [python 3](http://packages.readthedocs.org/en/latest/python/python3/) packages. The list of [installed debian packages](http://packages.readthedocs.org/en/latest/deb/) may be useful too.
