### ISSUE TITLE
Odd issue, have multiple accounts with same email address, GitHub sync only works with one =(

### ISSUE THREAD

**Issue by JoshuaEstes** [rtfd/readthedocs.org#932]
Hello and thanks for this amazing service. One problem that I have is that I seem to have created a new account by logging in with my email address instead of my username. I'm not sure exactly how I can see the email addresses that are associated with an account, and this might just be an issue with my own stupidity.

One account I synced my GitHub with and thus seemed to render the other account useless on trying to do this. The accounts are as follows https://readthedocs.org/profiles/JoshuaEstes/ (Synced with GitHub) and https://readthedocs.org/profiles/f1gm3nt/ (Not Synced with GitHub). Let me know if there is anything else you need from me. Great work guys!

**Comment by agjohnson** [comment]
This ticket has be lingering for a long time, closing and merging into #1875. Feel free to follow there if this is still an issue.
