### ISSUE TITLE
[question] - Without writing a custom builder is it possible to turn off pdf generation?

### ISSUE THREAD

**Issue by orsenthil** [rtfd/readthedocs.org#947]
Sometimes it is not desirable to create pdf and I wish if there was a setting to turn off automatic pdf generation. Do you think it is a good feature request?

**Comment by stevepiercy** [comment]
I would like to turn off automatic PDF generation for many Pylons Project projects. The support burden would be too great for too little benefit, given the HTML docs are more than adequate. Even with PDF generation, using [Pyramid as an example](https://media.readthedocs.org/pdf/pyramid/latest/pyramid.pdf), the PDF has several layout problems, especially with code samples.

A related question: Has PDF generation always been a default setting? It seems like it started around January 2015 in most of the Pylons Project projects.

**Comment by davidheijkamp** [comment]
I managed to achieve to disable PDF generation by changing the latex_documents variable in conf.py to this: latex_documents = [].

**Comment by stevepiercy** [comment]
@davidheijkamp that tip does not work for our repo. A PDF build is still attempted and shows as "Passed", even though it actually fails. https://readthedocs.org/builds/pyramid_cookbook/2947148/ Maybe you have other configuration options.

**Comment by ericholscher** [comment]
That build seems to pass, it properly exits after not outputting anything,
which seems like success to me. We're working on adding the ability to
configure output formats as we speak, so hopefully this will be resolved in
the next couple weeks.

On Thu, Jun 11, 2015 at 2:08 AM, Steve Piercy <notifications@github.com>
wrote:

> @davidheijkamp <https://github.com/davidheijkamp> that tip does not work
> for our repo. A PDF build is still attempted and shows as "Passed", even
> though it actually fails.
> https://readthedocs.org/builds/pyramid_cookbook/2947148/ Maybe you have
> other configuration options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rtfd/readthedocs.org/issues/947#issuecomment-111052604>
> .
>



-- 
Eric Holscher
Maker of the internet residing in Portland, Oregon
http://ericholscher.com

**Comment by edmorley** [comment]
This was fixed in #1344 - there are now additional checkboxes to turn off PDF/epub in settings.

**Comment by gregmuellegger** [comment]
Yep, indeed. Thanks for pointing this out. Closing this ticket for now.

**Comment by stevepiercy** [comment]
Thank you!
