### ISSUE TITLE
Installation documentation misses prerequisites

### ISSUE THREAD

**Issue by tdewolf** [rtfd/readthedocs.org#961]
When you install readthedocs on a clean ubuntu, the pip install -r pip_requirements.txt fails because there are some packages not installed.
It would be nice to add to the documentation some prerequisites to make the install process smooth and easy.
I had to install the following extra packages in order to complete the install procedure as described http://read-the-docs.readthedocs.org/en/latest/install.html:

* libxml2-dev
* libxslt1-dev
* zlib1g-dev

**Comment by ericholscher** [comment]
Closing this, as it should be a pull request. Feel free to send one along if it's still an issue.
