### ISSUE TITLE
Alias for the latest released version

### ISSUE THREAD

**Issue by vitaut** [rtfd/readthedocs.org#965]
It would be nice to have an alias to the latest released version of the documentation. For example, in GitHub you can refer to the latest release with URL like https://github.com/cppformat/cppformat/releases/latest.

In ReadTheDocs `latest` refers to the latest development documentation which is rarely what user needs, because users usually deal with released versions of software rather than unreleased software from the head of the `master` branch.

**Comment by mboersma** [comment]
Would it be possible to disable `stable` altogether? This kind of magic behavior is un-Pythonic and error-prone; it has caused us nothing but grief.

**Comment by vitaut** [comment]
@mboersma Can't you disable it in Admin/Versions or do you want to force others not to have it?
