### ISSUE TITLE
MkDocs builds: Nav badge appears in wrong place for RTD theme

### ISSUE THREAD

**Issue by dnrce** [rtfd/readthedocs.org#975]
With the RTD theme for MkDocs, the nav badge appears in the lower right as it does for non-RTD themes, instead of being integrated into the bottom of the RTD theme's sidebar. Clicking the lower left area still toggles the right-side nav menu.

**Comment by ericholscher** [comment]
This is a mkdocs issue, not one with Read the Docs. Closing it here.
