### ISSUE TITLE
Build incorrectly marked as failed

### ISSUE THREAD

**Issue by vitaut** [rtfd/readthedocs.org#979]
The Overview page of the [C++ Format](https://readthedocs.org/projects/cppformat/) project shows `master (Build Failed)`. However, in the [Recent Builds](https://readthedocs.org/builds/cppformat/) page, both the latest HTML and PDF builds of the `master` version are marked as Passed.

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
