### ISSUE TITLE
Shorter URLs

### ISSUE THREAD

**Issue by rmzelle** [rtfd/readthedocs.org#989]
Instead of http://docs.citationstyles.org/en/latest/primer.html, I would much rather have a shorter URL like http://docs.citationstyles.org/primer.html for our default version and default language. I'm aware of the [Single Version Documentation](https://docs.readthedocs.org/en/latest/single_version.html) option, but I still want to be able to use release branches (and possibly translations).

So, I'm wondering if there is any merit in adding the ability to individually suppress `/<language>/` for the default language, and `/<version>/` for the default version. For example, assume that our documentation is primarily in English and that we always want to point our end users to our latest release, which is 1.0.1. In that case, I would like to suppress the "/en/" and "/1.0.1/", so we would get:

English, "1.0.1" branch:
http://docs.citationstyles.org/primer.html
(this content should still be accessible through http://docs.citationstyles.org/1.0.1/primer.html as well)

English, "1.0" branch:
http://docs.citationstyles.org/1.0/primer.html

English, "master" development branch:
http://docs.citationstyles.org/master/primer.html

I realize that there would be a risk for overlap if I wanted to offer alternative languages, as in:

French, v1.0.1:
http://docs.citationstyles.org/fr/primer.html

but I think this wouldn't be too much of a practical issue, since it's unlikely people use the same strings for locale codes and branch/tag names.

**Comment by ericholscher** [comment]
Yea, this isn't going to happen. We have single version support, and full URL's. That should be enough for anyone :)

**Comment by sandeepkrjha** [comment]
Can we change Short URL for any project? Currently [it's](https://readthedocs.org/projects/stingray-/) showing two Short URL:

>  stingray-.readthedocs.io
>stingray-.rtfd.io

Can I change these URLs to something like this:
>sandeepkrjha-stingray.readthedocs.io
>sandeepkrjha-stingray.rtfd.io

**Comment by humitos** [comment]
@sandeepkrjha short question is "No". It's in the FAQ, http://docs.readthedocs.io/en/latest/faq.html#how-do-i-change-my-slug-the-url-your-docs-are-served-at

**Comment by ericholscher** [comment]
That does sound like a bug in our slug generation though. Having a dash on the end is ugly. You can however re-create the project, and a new slug will be generated.

**Comment by nsheff** [comment]
> We have single version support, and full URL's. That should be enough for anyone :)

You could really be more flexible and support projects that want one but not the other. You already have the capability, there's no reason not to enable all 4 options:

- single-version, single-language    <- current "Single Version" option
- single-version, multi-language    <- can't do it
- multi-version, single-language    <- can't do it.
- multi-version, multi-language    <- current default option

I, like the OP, want multi-version, single-language, but have the extra `/en` in all my URLs, though any other language translation is extremely unlikely.
