### ISSUE TITLE
Table of contents rendering in PDF

### ISSUE THREAD

**Issue by rmzelle** [rtfd/readthedocs.org#990]
In http://docs.citationstyles.org/en/latest/primer.html, I start the document with a table of contents with 4 levels, since the sidebar TOC with 2 levels is too limiting.

This looks fine in the HTML version, but in the PDF both TOCs show up, which I don't want. And whereas the sidebar TOC is very nicely rendered, the TOC I manually inserted looks rather poorly (see https://media.readthedocs.org/pdf/citation-style-language/latest/citation-style-language.pdf ).

Is there a way to a) suppress one of the two TOCs in the PDF version, and b) if suppressing the manually inserted version, to change the number of levels of the sidebar TOC to 4, or, if suppressing the sidebar TOC, to have the manually inserted version rendered more nicely?

**Comment by ericholscher** [comment]
This is a Sphinx question, not a Read the Docs one. Sadly I don't know much about the PDF rendering, so I'm closing it here.
