### ISSUE TITLE
Opt-out of flat style badges

### ISSUE THREAD

**Issue by maelstrom59** [rtfd/readthedocs.org#992]
In 740ca6550f9d60858a376c14ed48291163597678 the default style for badges was changed to the flat style.

The problem now is that there is no obvious way to use the shields.io default 'rounded' style.

I had this issue in maelstrom59/ArchMap@6200060faf0001c8e05de695daa24653afc6b210 (line 14), it's a bit of an ugly hack because you can actually use any value after `&style=`. As far as I can tell, this is because the RTD code passes the `style` parameter to [shields.io](http://shields.io) which then defaults to their default 'round' style if the parameter is anything other than `flat` or `flat-square`.

Hopefully this makes some sense, apologies if I've got the wrong idea. Either way it would be good to have a bit more info for the  ['Style' section on the badges page](https://github.com/rtfd/readthedocs.org/blob/master/docs/badges.rst#style).

**Comment by ericholscher** [comment]
Seems this got fixed. Closing the issue.
