### ISSUE TITLE
Long project names fail with shell error.

### ISSUE THREAD

**Issue by ckuehl** [rtfd/readthedocs.org#994]
I am seeing the following build error:

```
/bin/sh: 1: /home/docs/checkouts/readthedocs.org/user_builds/rackspace-cloud-core-infrastructure-services-user-guide/envs/latest/bin/sphinx-build: not found
```

I also see:

```
doc_builder
-----

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/readthedocs/projects/utils.py", line 85, in run
    stderr=subprocess.PIPE, env=environment)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

No settings have changed on our project, so can someone please take a look and see what is preventing our builds?

Thanks!

**Comment by fergonco** [comment]
I run into this same issue as well. After trying and trying, finally I found this issue and created the same project with a shorter name. It works now. 

Maybe it is a good idea to limit the length of the project name until this issue is solved.

Many thanks for the awesome project, in any case.

**Comment by sjagoe** [comment]
This also appears to be an issue when building a _branch_ of a project where the branch-name is long.

**Comment by gregmuellegger** [comment]
We should find out about the maximum path length that we can support and fix this in the code.
@ericholscher Can you remember any of the investigations you did for this?

**Comment by agjohnson** [comment]
I'll take this on.

For background information here, the shebang max length is set in the kernel by `BINPRM_BUF_SIZE`, which defaults to 127 characters. Short of compiling a custom kernel, the easiest fix is to avoid shebang lines all together and instead call the virtualenv `python` with the script we're executing as an argument.
