### ISSUE TITLE
Error: Could not import extension numpydoc

### ISSUE THREAD

**Issue by noamg** [rtfd/readthedocs.org#995]
I am compiling the documentation to my project with Sphinx (and extensions autodoc, numpydoc)
source: https://github.com/noamg/signal_processing
Locally, the compilation of html documentation succeeds.

In readthedocs I get:

Extension error:
Could not import extension numpydoc (exception: No module named numpydoc)

I tried to use the admin page, to ask readthedocs to install the package on virtualenv, and included numpydoc in the requirements.txt
but I get the same error.

Anyone knows what to do?

Noam

**Comment by gregmuellegger** [comment]
Seems like this project is no longer on the described github page. @noamg if this is still a problem for you on another project, then please open a new ticket.
@maelstrom59 thanks for trying to help out!
